app/controllers/idv/document_capture_controller.rb, app/controllers/idv/hybrid_mobile/document_capture_controller.rb, app/controllers/idv/in_person/address_controller.rb, app/controllers/idv/in_person/state_id_controller.rb, app/controllers/idv/in_person_controller.rb, app/presenters/idv/in_person/usps_form_presenter.rb, app/views/idv/in_person/address/show.html.erb, app/views/idv/in_person/state_id.html.erb, app/views/idv/in_person/state_id/show.html.erb, app/views/idv/shared/_document_capture.html.erb, spec/controllers/idv/document_capture_controller_spec.rb, spec/controllers/idv/in_person/address_controller_spec.rb, spec/controllers/idv/in_person/state_id_controller_spec.rb, spec/controllers/idv/in_person_controller_spec.rb, spec/presenters/idv/in_person/usps_form_presenter_spec.rb, spec/views/idv/in_person/state_id.html.erb_spec.rb, spec/views/idv/shared/_document_capture.html.erb_spec.rb
[LG-11850](https://cm-jira.usa.gov/browse/LG-11850)
Removed territories from IPP state selects that cause USPS API errors.
- [] Step 4: Verify that the Armed Forces items and Outlying Islands item are removed from the state/territory select
=> Lg 11850 remove invalid usps states

app/services/usps_in_person_proofing/enrollment_helper.rb, spec/services/usps_in_person_proofing/enrollment_helper_spec.rb
[LG-13684](https://cm-jira.usa.gov/browse/LG-13684)
* Added `enhanced_ipp` to the `properties.event_properties` of the `USPS IPPaaS enrollment created` event
**Scenario: When the Service Provider has requests EIPP for the user**
**Scenario: When the Service Provider has requests any other identity verification level**
=> LG-13684 Add enhanced_ipp to enrollment created event

app/controllers/two_factor_authentication/options_controller.rb, app/forms/two_factor_login_options_form.rb, app/services/analytics_events.rb, spec/controllers/two_factor_authentication/options_controller_spec.rb, spec/forms/two_factor_login_options_form_spec.rb
[LG-13527](https://cm-jira.usa.gov/browse/LG-13527)
This ticket adds `enabled_mfa_methods_count` and `mfa_method_counts` to the `multi_factor_auth_option_list` event.
For local development QA, you will need an existing account with either a phone setup or multiple methods registered to the account. You will also need to run `make watch_analytics` to see the event.
https://github.com/18F/identity-idp/assets/17969963/0de58800-d420-4fb0-9cd0-d2c9c7e653dc
=> LG-13527: Add submission analytics event for sign-in MFA selection screen

app/presenters/idv/in_person/ready_to_verify_presenter.rb
This is a follow-up to the reversion in #10882 and #10912 to do it in two stages. This change adds support so the ReadyToVerifyPresenter can handle either hyphens or endash prior to making the changes that will do that.
=> Support more formats for translation of Post Office hours

app/forms/register_user_email_form.rb, app/services/analytics_events.rb, spec/controllers/sign_up/registrations_controller_spec.rb, spec/forms/register_user_email_form_spec.rb
Updates logging for new account email submission to include `email_language` property.
This is planned to be used for measuring how frequently this field is changed by users to select an option other than the current page locale.
1. Run `make watch_events` in a separate terminal process
3. Click "Create an account"
4. Enter an email
5. Optional: Change the value for "Select your email language preference"
6. Check "I have read and accept the Login.gov Rules of Use"
7. Click "Submit"
8. In `make watch_events` terminal tab, look for "User Registration: Email Submitted" event
9. Observe `email_language` property matches what had been selected when submitting the form
=> Log email language for new account creation

app/services/analytics_events.rb, app/services/gpo_confirmation_uploader.rb, spec/services/gpo_confirmation_uploader_spec.rb
We have observed a number of issues with the `GpoConfirmationUploader`. We are adding more visibility to the job to improve our monitoring and alerting to deal with failures.
This commit adds a line to `events.log` when confirmations get uploaded. It includes a count of the confirmations that were uploaded so we can build a metric for that.
This new logging is in addition to the records that get written to the `letter_requests_to_usps_ftp_logs` which are used in monthly reports.
=> LG-13123 Log when `GpoConfirmationUploader` uploads `GpoConfirmations`

app/controllers/idv/by_mail/request_letter_controller.rb, spec/controllers/idv/by_mail/request_letter_controller_spec.rb, spec/features/idv/gpo_disabled_spec.rb
This commit fixes a bug where the `RequestLetterController` was not respecting `GpoVerifyByMailPolicy#send_letter_available?`. If that method returned false then links would be hidden but users could still visit the controller directly and request letters.
This commit adds a before action to fix the issue and adds tests.
=> LG-13820 Redirect from request letter controller when letter send is not available

spec/mailers/previews/user_mailer_preview_spec.rb
Adds a test to verify that mailer content doesn't include SVG images. As described in the included inline code comment (and [related folder README](https://github.com/18F/identity-idp/blob/main/app/assets/images/email/README.md)), SVG images are not well supported in mail clients. This is often hard to spot in development, since our HTML previews render correctly in a browser, but the mailer may not always show the expected content when sent in a deployed environment. The intent of the test is to reduce the feedback loop for this issue, and ensure that the issue is caught sooner.
Previously:
- https://github.com/18F/identity-idp/pull/10839#discussion_r1648075095
- https://github.com/18F/identity-idp/pull/6892
- https://github.com/18F/identity-idp/pull/6585#issuecomment-1187577858
Verify …
=> Add spec to ensure mailers don't include SVG

Makefile, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/utilities.css.scss, app/views/layouts/base.html.erb, app/views/layouts/component_preview.html.erb, app/views/saml_idp/shared/saml_post_binding.html.erb
Splits utilities out of `application.css` to its own standalone stylesheet `utilities.css`.
**Why?**
- **Predictability**. There have been a number of issues ([[1]](https://github.com/18F/identity-idp/pull/10898#discussion_r1662668282) [[2]](https://github.com/18F/identity-idp/pull/10394#issuecomment-2049857818)) related to the load order of stylesheets, and particularly utility classes and the relative ordering of the design system styles and our application-specific styles. This new implementation ensures that the general priority ordering of `utilities > application styles > design system styles` takes effect.
- **Performance**. While there's not expected to be a net reduction in overall page size, splitting the stylesheets into smaller chunks allows parallelized HTTP/2 downloads to …
=> Split utilities stylesheet to standalone file

config/routes.rb
Fixes an issue where trying to change the language on the OpenID Connect logout confirmation screen results in a 404 page, by allowing the pages to be localizable (within the `:locale` block in the `routes.rb` file).
The only other routes defined out side the `:locale` block are not meant to be human-facing.
1. Prerequisite: Have the [OIDC sample application](https://github.com/18f/identity-oidc-sinatra) running in a separate process
2. Visit http://localhost:9292
3. Click "Sign in"
4. Complete sign-in
5. At SP, click "Sign out"
6. Observe OIDC logout screen
7. Change language of the page using the language selector
Before: You'd see a 404
After: You see the page translated in the language you're expecting
Verify there are no regressions in other places which reference these URLs. …
=> Allow OIDC routes to be localizable

app/controllers/users/piv_cac_setup_from_sign_in_controller.rb, app/services/analytics_events.rb, config/routes.rb, spec/features/sign_in/setup_piv_cac_after_sign_in_spec.rb, spec/features/users/sign_in_spec.rb, spec/support/features/session_helper.rb
Supports [LG-13477](https://cm-jira.usa.gov/browse/LG-13477) (#10918)
Updates feature specs targeting the expected behavior for prompting a user to add a PIV to their account after signing in when having previously failed logging in with PIV due to the card not being associated with a user.
Specifically:
- Shifts specs to a new file, since there's several scenarios related to this behavior, and this helps keep the size of `features/users/sign_in_spec.rb` in check
- Improves `stub_piv_cac_service` to behave more realistically to the deployed user behavior
- Previously, the tests would manually "visit" the PKI service with the assumption that the user would always be redirected back to the current URL. This is not true for PIV/CAC setup after sign-in, which [submits to the default PIV/CAC …
=> Align PIV/CAC setup-after-sign-in specs to user behavior

app/controllers/users/sessions_controller.rb, app/services/analytics_events.rb, spec/controllers/users/sessions_controller_spec.rb
Supports [LG-13904](https://cm-jira.usa.gov/browse/LG-13904)
Updates "Email and Password Authentication" event to include a new `new_device` property.
This will help support:
- Monitor expected behaviors for deployment of new sign-in email aggregation feature
- With in-progress reCAPTCHA-at-sign-in behaviors, which are expected to only apply for new device sign-ins
1. Have a separate terminal process running `make watch_events`
3. Sign in
4. Observe event for "Email and Password Authentication" has expected result for `new_device`
To force `new_device: true`, try in a private browsing window. To force `new_device: false`, first sign-in, sign-out, and start over.
=> Log new_device with email and password authentication event

spec/features/openid_connect/vtr_spec.rb, spec/features/saml/vtr_spec.rb, spec/features/two_factor_authentication/sign_in_spec.rb, spec/features/users/piv_cac_management_spec.rb, spec/features/users/sign_in_spec.rb, spec/support/features/session_helper.rb
Supports [LG-13477](https://cm-jira.usa.gov/browse/LG-13477) (https://github.com/18F/identity-idp/pull/10918)
Builds upon the changes in #10939 to use the new `stub_piv_cac_service` enhancements consistently throughout existing specs, removing the `visit_piv_cac_service` method and related spec helpers.
As mentioned in #10939, the goal is to have this behave more realistically to the live implementation, and to have the tests interact with the page in the same way a user would. Previously, we relied heavily on visiting specific URLs that don't necessarily follow from interactions on the page.
=> Use improved PKI service test stub consistently

app/controllers/idv/hybrid_handoff_controller.rb, app/controllers/idv/link_sent_controller.rb, app/forms/idv/api_image_upload_form.rb, app/forms/idv/consent_form.rb, app/forms/idv/how_to_verify_form.rb, app/javascript/packages/document-capture/components/document-capture-warning.tsx, app/javascript/packages/document-capture/components/document-capture.tsx, app/services/idv/steps/doc_auth_base_step.rb, app/views/idv/session_errors/rate_limited.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/controllers/idv/image_uploads_controller_spec.rb, spec/controllers/idv/link_sent_controller_spec.rb, spec/features/idv/doc_auth/document_capture_spec.rb, spec/features/idv/doc_auth/hybrid_handoff_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb, spec/javascript/packages/document-capture/components/document-capture-warning-spec.jsx, spec/javascript/packages/document-capture/components/review-issues-step-spec.jsx, spec/presenters/image_upload_response_presenter_spec.rb, spec/views/idv/session_errors/rate_limited.html.erb_spec.rb
[LG-13096](https://cm-jira.usa.gov/browse/LG-13096)
Moved doc auth error messages in the `.yml` files so all of them are under `doc_auth.errors.` keys (some of them were under `errors.doc_auth.`
Provide a checklist of steps to confirm the change
=> Consolidated doc auth error messages.

config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
[LG-13537](https://cm-jira.usa.gov/browse/LG-13537)
In-person failure to verify email content and translations changed.
Note: The main change here is the removal of the word 'online'.
Screenshots are in JIRA ticket for design review.
=> LG-13537: Remove the term online from failure CTA body

app/controllers/users/sessions_controller.rb, app/services/analytics_events.rb, spec/controllers/users/sessions_controller_spec.rb
Reverts 18F/identity-idp#10957
See: https://gsa-tts.slack.com/archives/C0NGESUN5/p1721323664223389?thread_ts=1721322619.321579&cid=C0NGESUN5
=> Revert "Log new_device with email and password authentication event"

app/controllers/idv/in_person/public/usps_locations_controller.rb, app/controllers/idv/in_person/usps_locations_controller.rb, app/presenters/idv/in_person/ready_to_verify_presenter.rb, app/services/usps_in_person_proofing/enrollment_helper.rb, spec/presenters/idv/in_person/ready_to_verify_presenter_spec.rb
Follow up to https://github.com/18F/identity-idp/pull/10925  (and #10882 / #10912) that implements the remainder of the changes to display translated results for Post Office search. This should not be merged until #10925 has been deployed.
=> Translate Post Office search results

Makefile, config/application.yml.default
Includes `config/application.yml.default` in YAML normalizations.
**Why?**
- Avoid inconsistent line spacing and quoting
Verify `make lint_yaml` passes.
=> Apply YAML normalizations to application.yml.default

app/controllers/application_controller.rb, spec/features/sign_in/setup_piv_cac_after_sign_in_spec.rb
[LG-13477](https://cm-jira.usa.gov/browse/LG-13477)
Fixes an issue where a user would be returned to the PIV prompt screen when prompted to add a PIV card to their account after signing in when having previously failed logging in with PIV due to the card not being associated with a user.
Part of the changes here improve spec helpers relating to PIV/CAC, which currently do not reflect real-world usage, since the PIV/CAC-after-sign-in prompt does _not_ return a user to `'login/add_piv_cac/success'` in live code. Instead, the prompt page submits to the `'/present_piv_cac'` route (`Users::PivCacAuthenticationSetupController#submit_new_piv_cac`), and is therefore redirected back to `'/piv_cac'` after being returned from the PKI service. The stub abstractions wrongly assumes that the PKI …
=> LG-13477: Fix reprompt for adding PIV on sign-in after reauthentication

app/jobs/get_usps_proofing_results_job.rb, app/services/usps_in_person_proofing/mock/fixtures.rb, app/services/usps_in_person_proofing/mock/responses/request_passed_proofing_secondary_id_type_results_response_ial_2.json, spec/jobs/get_usps_proofing_results_job_spec.rb, spec/support/usps_ipp_helper.rb
[LG-13758](https://cm-jira.usa.gov/browse/LG-13758)
As we await the new API contract from USPS with the expanded list of secondary ID options, we are temporarily bypassing the secondary check completely. This is to support the friends and family testing for Enhanced IPP
Please see the scenarios below for 
1. [EIPP Enabled with Unsupported Secondary ID](#eipp-enabled-unsupported)
1.  [EIPP Enabled with Supported Secondary ID](#eipp-enabled-supported)
1. [The current flow in production - EIPP Disabled (ID IPP) with Unsupported Secondary ID](#eipp-disabled-unsupported)
1. [The current flow in production - EIPP Disabled (ID IPP) with Supported Secondary ID](#eipp-disabled-supported)
> [!NOTE]
> Pre requisite for all of this is to spin up the …
=> LG-13758: Bypass secondary id check for Enhanced IPP

app/forms/openid_connect_token_form.rb, app/models/document_capture_session.rb, app/services/rate_limiter.rb, app/services/service_provider_request_proxy.rb, config/environments/development.rb, spec/controllers/country_support_controller_spec.rb, spec/controllers/sign_up/cancellations_controller_spec.rb, spec/controllers/sign_up/email_confirmations_controller_spec.rb, spec/controllers/sign_up/passwords_controller_spec.rb, spec/forms/openid_connect_token_form_spec.rb, spec/models/user_spec.rb, spec/presenters/openid_connect_user_info_presenter_spec.rb, spec/services/out_of_band_session_accessor_spec.rb, spec/services/send_sign_up_email_confirmation_spec.rb
`ActiveSupport::Duration#to_i` returns the duration in seconds ([docs](https://api.rubyonrails.org/classes/ActiveSupport/Duration.html#method-i-to_i)), so it's redundant to convert a duration to seconds before calling `.to_i`.
It also has a large impact on performance, relatively speaking.
Instances discovered via project search for `.seconds.to_i`
Benchmark code:
```rb
require 'benchmark/ips'
Benchmark.ips do |x|
x.report('before') do
5.minutes.seconds.to_i
end
x.report('after') do
5.minutes.to_i
end
x.compare!
end
```
```
Warming up --------------------------------------
before   124.827k i/100ms
after   278.805k i/100ms
Calculating -------------------------------------
before      1.257M (± 1.1%) i/s -      6.366M in   5.064966s
after      2.788M (± 0.7%) i/s -     13.940M in …
```
=> Avoid unnecessary seconds conversion before to_i

app/javascript/packages/document-capture/components/document-capture-troubleshooting-options.spec.tsx, app/javascript/packages/document-capture/components/document-capture-troubleshooting-options.tsx, app/services/marketing_site.rb, app/views/idv/in_person/state_id.html.erb, spec/controllers/redirect/help_center_controller_spec.rb, spec/services/marketing_site_spec.rb
[LG-13945](https://cm-jira.usa.gov/browse/LG-13945)
Fixed a broken link on the document capture page. We were pointing them to a non-existent help center page.
```
failed_alerts:
- name: Document Classification
result: Attention
```
<details>
<summary>Upload Your ID</summary>
</details>
<details>
<summary>Error Page</summary>
</details>
<details>
<summary>Help Center</summary>
</details>
=> Fixed broken link to help center.

app/javascript/packages/document-capture/components/barcode-attention-warning.tsx, app/javascript/packages/document-capture/components/document-capture-troubleshooting-options.spec.tsx, app/javascript/packages/document-capture/components/document-capture-troubleshooting-options.tsx, app/javascript/packages/document-capture/components/document-capture-warning.tsx, spec/javascript/packages/document-capture/components/document-capture-warning-spec.jsx
[LG-13599](https://cm-jira.usa.gov/browse/LG-13599)
When a user goes through doc auth and gets a failed doc auth result, they are now offered the option to go through In-Person Proofing.
=> LG-13599 Failed doc auth result offers IPP offramp

app/policies/idv/gpo_verify_by_mail_policy.rb, config/application.yml.default, lib/identity_config.rb, spec/features/idv/end_to_end_idv_spec.rb, spec/features/idv/gpo_disabled_spec.rb, spec/features/idv/in_person_spec.rb, spec/policies/idv/gpo_verify_by_mail_policy_spec.rb, spec/support/features/in_person_helper.rb
The `no_verify_by_mail_for_biometric_comparison_enabled` was used to control whether the GPO option was available for users performing a biometric comparison. We have enabled the feature flag in production and will be moving forward with this feature. This commit retires the feature flag.
=> Retire `no_verify_by_mail_for_biometric_comparison_enabled` feature flag

Makefile, app/javascript/packages/normalize-yaml/CHANGELOG.md, app/javascript/packages/normalize-yaml/README.md, app/javascript/packages/normalize-yaml/cli.js, app/javascript/packages/normalize-yaml/index.js, app/javascript/packages/normalize-yaml/index.spec.js, app/javascript/packages/normalize-yaml/visitors/collapse-spacing.js, app/javascript/packages/normalize-yaml/visitors/index.js, app/javascript/packages/normalize-yaml/visitors/smart-punctuation.js, app/javascript/packages/normalize-yaml/visitors/sort-keys.js, config/application.yml.default
Updates `normalize-yaml` to support the ability to ignore sorting for specific keys, and applies key sorting to `application.yml.default`.
**Why?**
- So it's easier for a developer to scan the file for a specific key, trusting that the file's keys are ordered alphabetically
1. Reorder or add keys in `application.yml.default`.
2. Run `make normalize_yaml`
3. Verify that keys in `application.yml.default` are sorted
=> Sort keys in application.yml.default

app/views/idv/in_person/ready_to_verify/show.html.erb, app/views/user_mailer/shared/_in_person_ready_to_verify.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/mailers/user_mailer_spec.rb, spec/views/idv/in_person/ready_to_verify/show.html.erb_spec.rb
[LG-13629](https://cm-jira.usa.gov/browse/LG-13629) Implementation: EIPP Barcode page and email consistency updates
Content updates (in English, Spanish, French, and Chinese) for EIPP for:
+ Ready to Verify View
+ Ready to Verify Email
+ Ready to Verify Reminder Email 
The Ready to Verify **View** and **Email** are different templates.. Updating the text should fix both places but inspect both views. The email and reminder email are the same template (with a few additions/changes on the reminder email.)
<details>
<summary>EIPP: Ready To Verify View</summary>
</details>
<details>
<summary>EIPP Ready to Verify Email</summary>
</details>
<details>
<summary>EIPP Ready to Verify Reminder Email</summary>
</details>
<details>
<summary>IPP: Ready To Verify View -- Confirm content did not changed- …
=> LG-13629 EIPP Content Updates for Ready to Verify View and Email

app/controllers/idv/in_person/usps_locations_controller.rb, app/services/usps_in_person_proofing/enrollment_helper.rb, spec/controllers/idv/in_person/usps_locations_controller_spec.rb, spec/services/usps_in_person_proofing/enrollment_helper_spec.rb
[LG-13944](https://cm-jira.usa.gov/browse/LG-13944)
- Set the sponsor_id field on in-person enrollments when they are created during the IPP usps location controller update request.
- Updated the `enrollment_helper.schedule_in_person_enrollment` method to check if a sponsor_id exists on the in-person enrollment before attempting to schedule a usps enrollment.
=> LG-13944 Add sponsor_id to initial IPP in-person enrollment creation

app/jobs/get_usps_proofing_results_job.rb, spec/jobs/get_usps_proofing_results_job_spec.rb
[LG-13715](https://cm-jira.usa.gov/browse/LG-13715)
* Added `enhanced_ipp` to the `properties.event_properties` of the `GetUspsProofingResultsJob: Enrollment status updated` event.
Scenario:
EIPP -> USPS Proofing Passed -> Passed with unsupported Secondary ID - Logged
EIPP -> USPS Proofing Passed -> Passed with Primary ID check - Logged
ID IPP -> USPS Proofing Passed -> Passed with unsupported secondary ID - Logged
ID IPP -> USPS Proofing Passed -> Passed with Primary ID check - Logged
=> LG-13715 Add enhanced_ipp to enrollment updated event

app/views/mfa_confirmation/show.html.erb, app/views/openid_connect/logout/confirm_logout.html.erb, app/views/partials/multi_factor_authentication/_mfa_selection.html.erb, app/views/shared/_banner.html.erb, app/views/shared/_footer_lite.html.erb, app/views/sign_up/registrations/_sp_registration_heading.html.erb, app/views/users/backup_code_setup/reminder.html.erb, app/views/users/webauthn_setup/new.html.erb, spec/support/matchers/accessibility.rb
Updates decorative SVG images to use `aria-hidden` instead of `role="img"`.
This builds upon #10200, and seeks to address the original issue while avoiding some incompatibilities between the role and  expectations around decorative images.
This is partly motivated by errors surfaced by automated checking tools, e.g. [Axe's `aria-allowed-role`](https://dequeuniversity.com/rules/axe/4.9/aria-allowed-role) or [PageSpeed Insights](https://pagespeed.web.dev/).
Some background investigation leading to this:
- Originally spotted a [recommendation in a blog post by a well-known accessibility engineer](https://www.scottohara.me/blog/2019/05/22/contextual-images-svgs-and-a11y.html#image-elements-that-are-decorative), not directly related to this issue, though similarly recommending `aria-hidden` …
=> Use aria-hidden for decorative SVG images

spec/models/agreements/iaa_spec.rb
Updates the spec for `Agreements::Iaa` to fix flakey test failures.
Example failure: https://gitlab.login.gov/lg/identity-idp/-/jobs/1326656
The issue is that the spec in question compares a [factory-created record with a randomized order number](https://github.com/18F/identity-idp/blob/5a01dc3425ca8b2a7bfd5cc8894c3c3c86c37891/spec/models/agreements/iaa_spec.rb#L69) with [a record that has a set order number](https://github.com/18F/identity-idp/blob/5a01dc3425ca8b2a7bfd5cc8894c3c3c86c37891/spec/models/agreements/iaa_spec.rb#L5). And because [the randomized order number is between 1 and 1000](https://github.com/18F/identity-idp/blob/5a01dc3425ca8b2a7bfd5cc8894c3c3c86c37891/spec/factories/agreements.rb#L28), this leaves a 1 in 1000 chance that the number conflicts.
The fix is to assign a …
=> Fix flakey IAA Agreements spec

app/components/alert_component.rb, app/components/alert_icon_component.rb, app/components/badge_component.rb, app/components/base_component.rb, app/components/icon_component.rb, app/components/login_button_component.rb, app/components/manageable_authenticator_component.rb, app/components/status_page_component.rb, config/application.yml.default, lib/identity_config.rb, spec/components/alert_component_spec.rb, spec/components/alert_icon_component_spec.rb, spec/components/badge_component_spec.rb, spec/components/block_link_component_spec.rb, spec/components/icon_component_spec.rb, spec/components/login_button_component_spec.rb, spec/components/status_page_component_spec.rb
Adds support to `BaseComponent` to use `ActiveModel::Model` validation helpers.
**Why?**
- We already perform validation in a number of our components, and this helps align to Rails conventions in place of ad hoc error raising
- Makes available a number of new helpers to help with common use-cases
- Simplifies code
- Should improve performance, since validation is not performed in production
1. Update usage of an affected component to try passing an invalid constructor option value
- e.g. change [this line](https://github.com/18F/identity-idp/blob/6c484f6f25c91d0385912c2453a74c3bb0cff6a7/spec/components/previews/alert_component_preview.rb#L8) to pass `type: :wrong`
2. View page with rendering of the component usage you updated
- e.g. http://localhost:3000/components/inspect/alert/preview …
=> Use ActiveModel validations for components

app/validators/multiple_mfa_options_validator.rb
Today during rspec league, we were looking at adding test coverage for files that have no test coverage.  Then we found that this file isn't in use anywhere.  Consequently, we decided to delete it.  Fin.
=> Remove file that is not in use [skip changelog]

app/controllers/saml_idp_controller.rb, app/models/federated_protocols/saml.rb, app/presenters/openid_connect_user_info_presenter.rb, app/presenters/saml_requested_attributes_presenter.rb, app/services/authn_context_resolver.rb, app/services/id_token_builder.rb, app/services/vot/acr_component_values.rb, app/services/vot/parser.rb, lib/saml_idp_constants.rb, spec/controllers/sign_up/email_confirmations_controller_spec.rb, spec/policies/service_provider_mfa_policy_spec.rb, spec/presenters/openid_connect_user_info_presenter_spec.rb, spec/services/analytics_spec.rb, spec/services/authn_context_resolver_spec.rb, spec/services/id_token_builder_spec.rb
https://gitlab.login.gov/lg-people/lg-people-appdev/Melba/backlog-fy24/-/issues/43
This change builds off the changes in https://github.com/18F/identity-idp/pull/10948
This is the initial work to replace our public-facing Vectors of Trust (VOT) API interface(s) with acr_values. This work is focused on the OIDC implementation; we will follow up with whatever changes we need to make for SAML in the next week.
This change:
- Maintains the current VoT implementation and API for current SPs
- Adds support for selecting proofing with biometric comparison using new Authentication Context Class Reference values (ACR values) in our OIDC API
- Does not change other ACR implementations
Acceptance testing detailed [here](https://docs.google.com/document/d/1_TJBdEiErT460qoJh-jiw9E3mlPCffguMn28--4LJK8/e …
=> Add biometric acr_values for OIDC protocol

lib/tasks/backfill_sponsor_id.rake, spec/factories/in_person_enrollments.rb, spec/lib/tasks/backfill_sponsor_id_rake_spec.rb
Context: We need to run roll plan 0032 again before enhanced IPP launches, because we caught a bug where sponsor_id was not being set for all in_person_enrollments.  PR #10984 fixed the bug.  As noted in [this jira comment](a.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1984737) on LG-13578, there are now in_person_enrollments with a nil sponsor_id in multiple environments.  As a result, we need this rake task to be available in all environments.
[LG-14030: Ensure roll plan 0032's rake task is available in all environments](https://cm-jira.usa.gov/browse/LG-14030)
1. Reintroduce the roll plan we need to run for roll plan 0032.  
Confirmed automated tests pass.
=> LG-14030: Ensure roll plan 0032's rake task is available in all environments

app/models/email_address.rb, app/services/marketing_site.rb
This removes a couple unused methods that seem to be left over from past refactoring.
=> Remove unused methods

app/views/idv/phone_errors/failure.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
When the GPO option is available the verify-by-phone rate limit screen contains the following:
> For security reasons, we limit the number of times you can attempt to verify your phone number online.
>
> You can:
> - Verify by mail, which takes 5 to 10 days
> - Cancel and start over again after 5 hours and 59 minutes
However, when the verify-by-mail option is not available this list only contains one bullet point. This commit removes the list when there is no verify by mail option. It introduces a paragraph to tell the user to try again after the rate limit expires.
Screenshots:
Verify-by-mail available:
Verify-by-mail unavailable:
=> Update the verify-by-phone rate limit screen in no-GPO case

.gitlab-ci.yml
To avoid rate limiting issues with Docker Hub, this PR switches to using ECR
=> Use ECR for Redis and Postgres images

spec/controllers/frontend_log_controller_spec.rb, spec/controllers/idv/address_controller_spec.rb, spec/controllers/idv/how_to_verify_controller_spec.rb, spec/controllers/idv/hybrid_mobile/capture_complete_controller_spec.rb, spec/controllers/idv/in_person/address_controller_spec.rb, spec/controllers/idv/in_person/ssn_controller_spec.rb, spec/controllers/idv/in_person/state_id_controller_spec.rb, spec/controllers/idv/link_sent_controller_spec.rb, spec/controllers/idv/ssn_controller_spec.rb, spec/controllers/redirect/return_to_sp_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/controllers/sign_up/completions_controller_spec.rb, spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb, spec/controllers/users/authorization_confirmation_controller_spec.rb, spec/controllers/users/passwords_controller_spec.rb, spec/controllers/users/piv_cac_authentication_setup_controller_spec.rb, spec/controllers/users/reset_passwords_controller_spec.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb, spec/mailers/user_mailer_spec.rb, spec/requests/rack_attack_spec.rb
Updates specs to replace `expect(@analytics).to receive(:track_event).with` with equivalent `expect(@analytics).to have_logged_event`.
This follows #11001, and includes updating some of the more involved analytics stubbing.
**Why?**
- Because `have_logged_event` includes a number of additional helpers implemented through the `FakeAnalytics` class:
- Accidental PII leak detection
- Undocumented analytics method arguments checking
- Facilitate work in #10987
Verify that there are no lingering references to stubbed `:track_event` for `Analytics` class in the `spec/` directory.
=> Assert logged events using have_logged_event (part 2)

app/controllers/concerns/verify_profile_concern.rb, app/controllers/openid_connect/authorization_controller.rb, app/forms/openid_connect_authorize_form.rb, app/policies/pending_profile_policy.rb, app/services/saml_request_validator.rb, spec/forms/openid_connect_authorize_form_spec.rb, spec/policies/pending_profile_policy_spec.rb, spec/services/saml_request_validator_spec.rb
https://gitlab.login.gov/lg-people/lg-people-appdev/Melba/backlog-fy24/-/issues/43
This is some cleanup for the ticket adding new biometric comparison ACR values for OIDC. 
Several methods that had been used to determine whether biometric comparison (I think) are no longer necessary,  as the resolved authn context object is available at the moment of consumption. One other similarly named method was no longer in use.
=> Clean up unnecessary methods 

app/views/idv/in_person/ready_to_verify/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/views/idv/in_person/ready_to_verify/show.html.erb_spec.rb
[LG-13672](https://cm-jira.usa.gov/browse/LG-13672)
Updates IPP and EIPP barcode pages to have a new alert at the top, and removes the line "We have sent this information to the email you used to sign in." from the bottom.
<details>
<summary>IPP Barcode Page:</summary>
</details>
<details>
<summary>EIPP Barcode Page:</summary>
</details>
=> LG-13672 Update barcode page to add alert and remove a line

Gemfile, Gemfile.lock
Updates the saml_idp version. Changes are a pure refactor to reduce complexity; there should be no differences in behavior.
=> Update saml_idp version

.gitlab-ci.yml
**Bug**: Literal `\n`
**Solution**: Use `printf`
=> Use printf to format newlines correctly in bash

dockerfiles/idp_prod.Dockerfile, dockerfiles/idp_review_app.Dockerfile
Update the old rds combined cert bundle with the new global cert bundle, required for the new encryption policy that is on our databases.
=> change cert bundle to the new global bundle

app/controllers/application_controller.rb, app/presenters/openid_connect_user_info_presenter.rb, app/services/analytics.rb, app/services/attribute_asserter.rb, app/services/authn_context_resolver.rb, app/services/id_token_builder.rb, spec/policies/pending_profile_policy_spec.rb, spec/presenters/account_show_presenter_spec.rb, spec/services/attribute_asserter_spec.rb, spec/services/authn_context_resolver_spec.rb, spec/views/accounts/_identity_verification.html.erb_spec.rb
changelog: Upcoming Features, IdV with Biometric Comparison, Supporting biometric acr in SAML
https://gitlab.login.gov/lg-people/lg-people-appdev/Melba/backlog-fy24/-/issues/44
The testing plan should be similar to what was done for OIDC - https://docs.google.com/document/d/1_TJBdEiErT460qoJh-jiw9E3mlPCffguMn28--4LJK8/edit
=> Support biometric ACR values in SAML

spec/support/shared_examples/account_creation.rb
Updates account creation shared example test cases to remove assertions about CSP expectations.
Since #10997, these assertions have started failing on unrelated pull requests. The assertions are redundant, since they're [already tested in `csp_spec.rb`.](https://github.com/18F/identity-idp/blob/8b736a28f2836c30b6d151990f552a23160d6325/spec/requests/csp_spec.rb#L11-L98). Limiting the amount of work performed in shared examples should also have a multiplicative benefit on runtime of these specs, since there are now 3x2 (6) fewer test cases being run.
Verify that build passes..
=> Remove OIDC form-action CSP assertions from account creation specs

app/controllers/users/sessions_controller.rb, config/application.yml.default.docker, spec/requests/csp_spec.rb
Updates content security policy to limit directives to only those strictly necessary for Digital Analytics Program.
See documentation: https://github.com/digital-analytics-program/gov-wide-code#content-security-policy
Since these conflicted with the [recommendations from Google for Google Analytics](https://developers.google.com/tag-platform/security/guides/csp#google_analytics_4_google_analytics), I had reached out to the DAP support team to clarify that their documented recommendations are sufficient. I'll also plan to monitor this after the changes go live to ensure there are no issues.
Verify that there are no errors in browser developer tools console when loading the preview site for this branch:
TBD
(It's enabled temporarily in preview environments, but this will be removed prior to …
=> Limit analytics CSP revisions to necessary entries

spec/features/users/sign_in_spec.rb
Updates reCAPTCHA sign-in failure specs to include coverage for expected logging:
- Expected logging properties
- Expected user_id associated with attempted user
```
rspec spec/features/users/sign_in_spec.rb:905
```
=> Add test coverage for expected reCAPTCHA sign-in logging

app/controllers/redirect/policy_controller.rb, app/views/devise/sessions/new.html.erb, app/views/idv/agreement/show.html.erb, spec/controllers/redirect/policy_controller_spec.rb, spec/views/devise/sessions/new.html.erb_spec.rb, spec/views/idv/agreement/show.html.erb_spec.rb
Supports [LG-14093](https://cm-jira.usa.gov/browse/LG-14093)
Adds support for the `Redirect::PolicyController` to redirect with logging to https://login.gov/policy/our-privacy-act-statement/ 
This is meant to help support [LG-14093](https://cm-jira.usa.gov/browse/LG-14093), which will help identify how many users may exit sign-in using one of the available brochure site links on the Sign In page. Currently, we have no logging insights to clicks on these links.
This updates the "Security Practices and Privacy Act Statement" link to use the redirect controller since support already existed for this, but does not yet update the "Privacy Act Statement" link. That link will be updated in a separate pull request to avoid [issues with 50/50 deploy …
=> Add support for Privacy Act brochure site redirect logging

app/javascript/packages/webauthn/enroll-webauthn-device.spec.ts, app/javascript/packages/webauthn/enroll-webauthn-device.ts
Updates WebAuthn enrollment to pass the `hints` property on the correct nesting level of the configuration.
Previously, it was passed as a property of `authenticatorSelection`, but it is a sibling option of `authenticatorSelection`.
Specification: https://w3c.github.io/webauthn/#sctn-parseCreationOptionsFromJSON
Related Slack discussion: https://gsa-tts.slack.com/archives/C01710KMYUB/p1723054132991659
If you have Chrome 128 available ([currently beta, stable release planned for 8/14/24](https://chromestatus.com/roadmap)), you can verify that you are prompted for a security key when choosing to add a security key to your account. Previously, you would see a QR code prompting for a passkey, with small text mentioning the ability to use a security key.
Before|After
---|---
=> Fix WebAuthn hints to pass on public key credential options

spec/services/attribute_asserter_spec.rb
WIP Currently just open so folks can look at the changes made in the attributes_asserter_spec file
As part of https://gitlab.login.gov/lg-people/lg-people-appdev/Melba/backlog-fy24/-/issues/55, we discovered a number of issues with our returned AAL values. I wanted to write some tests to make sure our understanding of the current state vs the expected state was accurate.
This first commit is just a refactor of the spec file in order to make it easier to understand and work with,
=> Adding tests to assert AAL values

app/views/account_reset/pending/confirm.html.erb, spec/features/account_reset/pending_request_spec.rb
[LG-13870](https://cm-jira.usa.gov/browse/LG-13870)
This PR adds the H1 element to the account reset cancel request confirmation form as well as a more descriptive button explaining the next step in the account reset cancellation process.
Pre-requisites: An existing account with at least 1 MFA method
<details>
| English | Spanish | French | Chinese |
|--------|--------|--------|--------|
| <img width="767" alt="screenshot of current you requested to delete your account page in english" src="https://github.com/user-attachments/assets/6662bc14-1c65-40f6-9e9b-7f08c7dffc1a"> | <img width="794" alt="screenshot of current you requested to delete your account page in spanish" src="https://github.com/user-attachments/assets/1a9dcff8-37cc-49bb …
=> LG-13870: Update the Account deletion cancel request confirmation page to reflect current Login.gov content and design system standards

app/models/doc_auth_log.rb
The `DocAuthLog` model had the following columns in its ignored columns.
- `email_sent_view_at`
- `email_sent_view_count`
- `send_link_view_at`
- `send_link_view_count`
These columns were dropped by a migration added in f24fb015d0d. This commit follows up on that by removed the reference to these in the ignored columns list.
=> LG-13725 Remove old hybrid flow columns from `DocAuthLog` model

db/primary_migrate/20240807202012_drop_aamva_from_doc_auth_logs.rb, db/schema.rb
This column was added to the `ignored_columns` list in https://github.com/18F/identity-idp/commit/85da36e3a4f9515e585782e37a79b5036845f42c. This commit follows up on that by adding a migration to drop the column.
=> LG-13725 Drop `aamva` column from `doc_auth_logs`

.gitlab-ci.yml
Try to speed up idp prod image builds so that they do not delay the overall pipeline completion.
Caching seems to be super slow, so try turning that off.
=> idp_prod image build optimization

app/presenters/account_show_presenter.rb, spec/presenters/account_show_presenter_spec.rb, spec/views/accounts/show.html.erb_spec.rb
@mitchellhenke identified a number of 500 errors logged to New Relic related to an unhandled exception caused in the account show presenter.
[Slack thread](https://gsa-tts.slack.com/archives/C01710KMYUB/p1723129598352139)
=> Bug fix for PR10847 - Verified pending states

app/services/analytics_events.rb, spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb, spec/controllers/users/passwords_controller_spec.rb, spec/features/account_email_language_spec.rb, spec/features/event_disavowal_spec.rb, spec/features/idv/doc_auth/agreement_spec.rb, spec/features/idv/doc_auth/welcome_spec.rb, spec/features/idv/pending_profile_password_reset_spec.rb, spec/features/legacy_passwords_spec.rb, spec/features/two_factor_authentication/multiple_tabs_spec.rb, spec/features/two_factor_authentication/sign_in_via_personal_key_spec.rb, spec/features/users/sign_in_spec.rb, spec/features/users/user_edit_spec.rb, spec/features/visitors/i18n_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb
Removes `allowed_extra_analytics` from `spec/features/users/sign_in_spec.rb` and resolves all flagged issues.
Most of these come from IdV events, documented to the best of my ability.
~Separately, it may be worth revisiting whether it's necessary for sign-in specs to go through the complete IdV flow, or if it would be fine to stub an already-IdV'd user instead (see [`sign_in.rb` shared examples](https://github.com/18F/identity-idp/blob/main/spec/support/shared_examples/sign_in.rb), specifically [use of `create_ial2_account_go_back_to_sp_and_sign_out`](https://github.com/18F/identity-idp/blob/c02f05010d324b121f5ba7e33e22ea6a39af8c68/spec/support/shared_examples/sign_in.rb#L358))~  **Edit:** Addressed separately in #10967.
Validate that tests pass.
In most cases, I added new method …
=> Document all analytics logged through sign_in_spec

app/models/user.rb, app/services/idv/session.rb, spec/features/idv/in_person_spec.rb, spec/models/user_spec.rb, spec/services/idv/session_spec.rb, spec/support/features/in_person_helper.rb
[LG-13864](https://cm-jira.usa.gov/browse/LG-13864)
- Change the order of events when the enter password form is submitted in the IPP flow. The USPS enrollment request will be made before a profile is created. Currently, when the USPS enrollment request fails the following issues occur:
1. Users are no longer about to retry enter password form because the `IdvStepConcern` before action `no_pending_profile` check automatically navigates the user back to the account page.
2. Users are stuck in a loop in account page where they cannot re-attempt verification.
These issues stem from the user having a profile with an enrollment in the `establishing` state after a USPS enrollment failure occurs.
**Scenario: USPS enrollment failure during ID-IPP enrollment**
**Scenario: User drops off after USPS …
=> LG-13864 Create profile after USPS enrollment

app/views/devise/sessions/new.html.erb, app/views/sign_up/registrations/new.html.erb, spec/views/devise/sessions/new.html.erb_spec.rb, spec/views/sign_up/registrations/new.html.erb_spec.rb
Updates Privacy Act links to use the policy redirect controller, which was updated in #11031 (RC 404) to support this link.
Follows #11031
1. In a separate terminal process, run make watch_events
2. Go to http://localhost:3000/
3. Click "Privacy Act Statement"
4. See "Policy Page Redirect" event in events logging with redirect_url of https://www.login.gov/policy/our-privacy-act-statement/
=> Use redirect logging controller for Privacy Act links

Gemfile, Gemfile.lock, app/controllers/concerns/saml_idp_auth_concern.rb, app/controllers/saml_idp_controller.rb, app/services/analytics_events.rb, spec/controllers/saml_idp_controller_spec.rb
https://gitlab.login.gov/lg-people/lg-people-appdev/Melba/backlog-fy24/-/issues/90
This change updates the saml_idp version to include two fixes that will improve our SAML signature validation.
* Allows the implementation to identity non-namespaced Signature blocks, therefore indicating that they are signed
* It allows our SAML validation code to correctly identify the DigestMethod node, and not sometimes incorreclty default to SHA1
* Removes analytics logging that was used to validate that these changes would have minimal impact
=> Integrate SAML validation namespace fixes

app/models/doc_auth_log.rb
The `aamva` column was dropped in #11052. This commit follows-up on that by removing it from the `ignored_columns` list on the model.
This commit should be merged after changes in #11052 are deployed.
=> LG-13725 Remove `aamva` from `DocAuthLog` ignored columns

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_link.scss
Fixes an issue where external links doubly announce to screen readers that they open in a new window.
This addresses a few problems:
- Double announcement
- Lack of translation in non-English locales
- Confusing placement of the text _before_ the link content
This should hopefully be a temporary patch, pending upstream improvements tracked at https://github.com/uswds/uswds/issues/5942 
2. Enable screen reader
3. Navigate to "Security Practices and Privacy Act Statement" link
4. Observe that the link only announces that it opens in a new tab a single time, in the page's current locale, and after the link's content is announced
Language|Before|After
---|---|---
English|![english-before](https://github.com/user-attachments/assets/cc0e0c08-f921-43a5-ad1f-70202973 …
=> Disable USWDS default external link screen reader text

spec/controllers/account_reset/cancel_controller_spec.rb, spec/controllers/account_reset/delete_account_controller_spec.rb, spec/controllers/account_reset/request_controller_spec.rb, spec/controllers/accounts/personal_keys_controller_spec.rb, spec/controllers/application_controller_spec.rb, spec/controllers/idv/otp_verification_controller_spec.rb, spec/controllers/idv/phone_controller_spec.rb, spec/controllers/idv/resend_otp_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/controllers/sign_up/cancellations_controller_spec.rb, spec/controllers/sign_up/email_confirmations_controller_spec.rb, spec/controllers/sign_up/passwords_controller_spec.rb, spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb, spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb, spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb, spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb, spec/controllers/users/edit_phone_controller_spec.rb, spec/controllers/users/personal_keys_controller_spec.rb, spec/controllers/users/phone_setup_controller_spec.rb, spec/controllers/users/reset_passwords_controller_spec.rb, spec/controllers/users/sessions_controller_spec.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb, spec/controllers/users/two_factor_authentication_setup_controller_spec.rb, spec/requests/rack_attack_spec.rb
Updates analytics assertions in specs to inline properties passed to `have_logged_event`, rather than creating a separate variable to pass.
This is a somewhat subjective stylistic preference, though some more objective rationale is included below. It's meant to complement ongoing effort to standardize and refine logging assertions in specs.
**Why?**
- Improves readability of tests
- Eyes are not moving around to find references to hash variable
- Keyword arguments referenced as a variable are hard to keep colocated with the actual assertion, and often drift away randomly
- Especially when the analytics hash is defined outside the spec itself, e.g. as an RSpec `let` memoized variable, which is unnecessary as we usually ought to only assert the expected log result once in most cases, and …
=> Inline keyword arguments passed to have_logged_event

Gemfile, Gemfile.lock
**Why**: Fixes warning:
> warning: abbrev was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add abbrev to your Gemfile or gemspec. Also contact author of highline-2.1.0 to add abbrev into its gemspec.
=> Update highline to remove dependency on abbrev

app/views/shared/_email_languages.html.erb, app/views/users/email_language/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
[LG-13869](https://cm-jira.usa.gov/browse/LG-13869)
Updates email language preference hint text to (a) use active voice, and (b) avoid listing out languages, which indirectly resolves an issue with [WCAG SC 3.1.2 Language of Parts](https://www.w3.org/WAI/WCAG21/Understanding/language-of-parts.html).
Verify new text on "Create an account" page:
3. See new hint text under "Select your email language preference"
Verify new text on account "Email language preference" page:
2. Sign in
3. From account page, click "Edit" under "Email preferences" > "Language"
4. See new paragraph text
---|---|---
Create account|![image](https://github.com/user-attachments/assets/b138fb6f-c4c1-42b5-9476- …
=> LG-13869: Update email languages preference copy

app/jobs/risc_delivery_job.rb, spec/jobs/risc_delivery_job_spec.rb
changelog: Internal, Error Handling, Avoid duplicating ActiveJob's retry machinery
It may address
https://gitlab.login.gov/lg-people/lg-people-appdev/Melba/backlog-fy24/-/issues/37.
This is an attempt to use ActiveJob's retry machinery properly, so that errors do not bubble up to NewRelic.
=> Avoid duplicating ActiveJob's retry machinery

lib/reporting/fraud_metrics_lg99_report.rb, spec/lib/reporting/fraud_metrics_lg99_report_spec.rb
[LG-12819](https://cm-jira.usa.gov/browse/LG-12819)
Added 5 new metrics to the LG-99 report for team Judy.
=> Lg 12819-Team Judy metrics

app/models/service_provider_identity.rb, lib/data_pull.rb, spec/lib/data_pull_spec.rb
I got a ticket to look up some user UUIDs, and found that the script reported 2 users as "missing" when they had been deleted, and we still had tombstoned data for them. 
- `AgencyIdentity` rows are deleted via `dependent: :destroy` when a user is deleted
- `ServiceProviderIdentity` rows stay around when users are deleted (to prevent UUID reuse) so we can use that to look up users
- `DeletedUser` table keeps the internal UUIDs around as well
=> Update uuid-convert script to look up deleted users

config/initializers/job_configurations.rb
Nuisance papercut discovered while working on [LG-14022](https://cm-jira.usa.gov/browse/LG-14022). (Not tagging in the title so the Jira state doesn't get erroneously updated.)
Nearly every job has a comment above it explaining what it's for. While working on a story for `identity_verification_report`, I noticed that the completely unrelated `usps_auth_token_refresh` job directly underneath it looked as if it was a confusing continuation because it didn't follow the pattern.
This is not an earth-shatteringly informative comment, but it makes the file less visually-confusing by not being a weird outlier, and "What if I reformatted the whole file so this wasn't an issue?" is way too big of a distraction.
=> Adds a comment to usps_auth_token_refresh config

config/initializers/job_configurations.rb, spec/config/initializers/job_configurations_spec.rb
Staggering these jobs should be good enough. The specific times and order in which the reports run were not picked with a specific reason in mind. Feel free to suggest different times if there's a reason to.
=> Stagger weekly Cloudwatch-heavy report jobs to not hit rate limits

spec/features/openid_connect/vtr_spec.rb, spec/features/users/profile_recovery_for_gpo_verified_spec.rb, spec/features/users/sign_up_spec.rb, spec/features/webauthn/sign_in_spec.rb
Updates a few feature specs to avoid opting into the JavaScript-enabled driver where not strictly necessary to do so.
**Why?**
- Improve build speed, since the default driver is faster
=> Use faster default driver for feature tests not requiring JavaScript

config/initializers/unused_identity_config_keys.rb
Currently we log a hash, which gets turned into a string via `inspect`, which results in a format that can't be parsed by Cloudwatch and makes it difficult to filter via `name`. This PR changes the log output to be JSON so that it can be.
Before:
```
{:name=>"unused_identity_config_keys", :keys=>[:my_key]}
```
After
```
{"name":"unused_identity_config_keys","keys":["my_key"]}
```
=> Log unused_identity_config_keys event as JSON

app/services/analytics_events.rb
Removes `pii_like_keypaths` as a documented method property for analytics methods.
**Why?**
- The purpose of documenting properties is to serve as a reference for values that are logged. `pii_like_keypaths` is not logged ([source](https://github.com/18F/identity-idp/blob/2f991d88cebbb4211342db5bbe2dae4d05d3e48e/app/services/analytics.rb#L18)).
- Consistency across analytics methods which may receive this property.
=> Remove pii_like_keypaths from documented analytics properties

app/controllers/two_factor_authentication/backup_code_verification_controller.rb, app/forms/backup_code_verification_form.rb, app/services/backup_code_generator.rb, spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb, spec/forms/backup_code_verification_form_spec.rb, spec/services/backup_code_generator_spec.rb
Supports [LG-14078](https://cm-jira.usa.gov/browse/LG-14078)
Updates backup code verification to use [the conventional form pattern](https://github.com/18F/identity-idp/blob/main/docs/backend.md#forms-formresponse-analytics-and-controllers):
- Validation should use `ActiveModel#valid?` in combination with validation methods appending errors as relevant
- Include errors in `FormResponse` return value
- Use errors from form response result to display in user interface
- Remove unused `BackupCodeGenerator#verify` method and update specs to ensure coverage for actively-used methods
To simplify review, consider hiding whitespace changes: https://github.com/18F/identity-idp/pull/11089/files?w=1
Verify that you can sign in with backup codes:
1. Prerequisite: Have an account with backup codes …
=> Refactor backup code verification to follow conventional form pattern

config/application.rb
Following some discussion [here](https://gsa-tts.slack.com/archives/C0NGESUN5/p1723820108719159), this PR disables writing the merged config file on boot.
=> Do not write config file by default on boot

app/views/devise/sessions/new.html.erb, app/views/layouts/base.html.erb, spec/helpers/script_helper_spec.rb, spec/views/devise/sessions/new.html.erb_spec.rb
Updates non-critical scripts to use `defer` instead of `async`.
While both `async` and `defer` _load_ scripts without blocking the parser, `async` will block the parser to execute the script as soon as it's loaded, which may block parsing if it happens before parsing is complete. `defer` will instead wait for parsing to complete before executing the script, which is acceptable behavior for the scripts affected by the changes in this pull request.
The [HTML specification includes helpful diagrams illustrating the difference](https://html.spec.whatwg.org/multipage/scripting.html#attr-script-async:~:text=This%20is%20all%20summarized%20in%20the%20following%20schematic%20diagram%3A):
Related resource: https://web.dev/articles/optimizing-content-efficiency-loading-third-party-javascript#async-de …
=> Use defer for non-critical scripts

app/services/analytics_events.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/features/idv/account_creation_spec.rb, spec/features/idv/cancel_spec.rb, spec/features/idv/doc_auth/ssn_step_spec.rb, spec/features/idv/gpo_disabled_spec.rb, spec/features/idv/phone_input_spec.rb, spec/features/idv/proofing_components_spec.rb, spec/features/idv/sp_requested_attributes_spec.rb, spec/features/idv/step_up_spec.rb, spec/features/idv/steps/phone_otp_verification_step_spec.rb, spec/features/idv/threat_metrix_pending_spec.rb, spec/features/idv/uak_password_spec.rb, spec/features/sp_cost_tracking_spec.rb, spec/features/users/password_recovery_via_recovery_code_spec.rb, spec/support/fake_analytics_spec.rb
Adds missing analytics methods property documentation for happy path identity verification.
Turns out I already did most of the work for this in #10966, and there was only one property left to be documented.
**Why?**
- Move toward full documentation coverage for analytics methods
=> Document analytics methods properties in primary IdV flow

spec/features/two_factor_authentication/second_mfa_reminder_spec.rb
Attempts to resolve an issue where the "Second MFA Reminder user with multiple mfas who would otherwise be candidate does not prompt the user on sign in" spec occasionally fails in continuous integration.
Example: https://gitlab.login.gov/lg/identity-idp/-/jobs/1371605
It's not entirely clear what causes this, but it's hypothesized that something with the time travel in the existing implementation results in the user arriving at the sign-in page rather than the account page.
The changes here reorganize the test to avoid relying on time helpers, and instead stub the user in a way where the account is old enough to be prompted for the second MFA reminder.
This also has the upside of avoiding magic numbers within the test (`travel 6.days`), using the default configuration values instead. …
=> Try: Fix second MFA reminder flakey spec

CONTRIBUTING.md
Removes a reference to `@18f/identity-frontend` frontend development interest group team.
This was an earlier experiment of creating focus area-specific interest groups, which was discontinued due to lack of usage and participation.
Verify that documentation still makes sense after removals.
=> Remove reference to frontend interest group team in contributing guide

app/views/idv/in_person/state_id/show.html.erb, spec/features/idv/steps/in_person/state_id_50_50_spec.rb, spec/features/idv/steps/in_person/state_id_controller_spec.rb, spec/support/features/in_person_helper.rb
[LG-12532](https://cm-jira.usa.gov/browse/LG-12532)
Added integration tests for covering 50/50 state for the state ID page FSM and Controller.
Added integration tests for the state ID page controller.
=> LG-12532 Add 50/50 tests for IPP state id page

lib/reporting/fraud_metrics_lg99_report.rb, spec/lib/reporting/fraud_metrics_lg99_report_spec.rb
We've had some issues with query volume from this report ([thread](https://gsa-tts.slack.com/archives/CMW9H0RFX/p1722271455385999)), and this proposes a couple changes to reduce the rate at which it makes requests.
The time slice shouldn't be an issue until there are more than 10,000 events in each one (I picked 6 hours).
=> Reduce threading and increase time slice default values for LG-99 Report

dockerfiles/idp_prod.Dockerfile, dockerfiles/idp_review_app.Dockerfile
Updates Dockerfiles to avoid unnecessary effort during assets precompilation:
- Yarn installation
- Debugging backtrace
`assets:precompile` will call `yarn install` by default unless disabled by `SKIP_YARN_INSTALL`.
See other references:
https://github.com/18F/identity-idp/blob/0923f956485381438c21d8c1ec62dae19f97c2f1/.gitlab-ci.yml#L79
https://github.com/18F/identity-idp/blob/0923f956485381438c21d8c1ec62dae19f97c2f1/deploy/build-post-config#L21
Check logs for "build-idp-image" and "build-review-image" in CI and observe no installation logging during assets precompilation.
=> Avoid Yarn install and trace in Docker assets precompilation

lib/reporting/protocols_report.rb, spec/lib/reporting/protocols_report_spec.rb
We would like to know who is using the deprecated AAL3 ACR parameter.
See
https://gitlab.login.gov/lg-people/lg-people-appdev/Melba/backlog-fy24/-/issues/10
changelog: Internal, Reporting, Add AAL3 usage to protocols report
=> Add AAL3 usage to protocols report

app/controllers/idv/in_person/ssn_controller.rb, app/controllers/idv/ssn_controller.rb, spec/controllers/idv/link_sent_controller_spec.rb, spec/policies/idv/flow_policy_spec.rb
The SSN show page includes Javascript for device profiling. To identify a device profiling transaction we set `threatmetrix_session_id` and render that alongside the Javascript that performs the device profiling. This UUID is used downstream to fetch device profiling results.
We observed that some users did not have a `threatmetrix_session_id` value in downstream steps. In many cases this appears to be because they submitted the "link sent" step which calls `undo_step` on the SSN step. Then, either due to network issues or an unusual path through the process they were able to submit the SSN form without re-rendering the SSN show page and regenerating a threatmetrix session ID.
Investigating this we questioned why the threatmetrix session id needs to be deleted when the user submits …
=> LG-14127 Stop deleting TMx session ID when undoing SSN step

Gemfile.lock
Updates the `fugit` gem to resolve a security advisory.
See: https://github.com/floraison/fugit/security/advisories/GHSA-2m96-52r3-2f3g
Updated via: `bundle update fugit`
Verify `make audit` produces no security advisories.
=> Update fugit dependency

app/jobs/reports/combined_invoice_supplement_report_v2.rb, spec/jobs/reports/combined_invoice_supplement_report_v2_spec.rb
Similar to https://github.com/18F/identity-idp/pull/11095
Differences:
- Adds a failing spec
- Skips rows with missing data
- Adds logging to investigate specific data
=> Add handling for missing data in CombinedInvoiceSupplementReportV2

app/javascript/packages/analytics/digital-analytics-program.patch
Modifies DAP (Digital Analytics Program) patch to load Google Tag Manager using `<script defer>` instead of `<script async>`, which should have better performance characteristics in avoiding interrupted page parsing due to execution of an `async` script.
Related Slack discussion: https://gsa-tts.slack.com/archives/C02CZB4G5/p1724265882031569
References:
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLScriptElement/defer
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLScriptElement/async
- https://html.spec.whatwg.org/multipage/scripting.html#dom-script-async
- https://calendar.perfplanet.com/2016/prefer-defer-over-async/
Follows #11097
Repeat Testing Plan from #11097, verifying loaded GTM script has `defer` attribute.
Also confirm that `yarn install` creates a new copy of …
=> Use defer when loading GTM script via patched DAP

app/controllers/concerns/idv/verify_info_concern.rb, app/controllers/idv/in_person/verify_info_controller.rb, app/controllers/idv/verify_info_controller.rb, app/services/analytics_events.rb, spec/controllers/idv/in_person/verify_info_controller_spec.rb, spec/controllers/idv/verify_info_controller_spec.rb
This commit makes changes to the way to `VerifyInfoController#show` logs events in the main IdV and in-person contexts.
This controller action has 2 primary concerns:
1. Rendering the “Verify your information” page
2. Managing the results of the `ResolutionProofingJob` that runs when the “Verify your information” page is submitted
Which concern is active for these actions is controlled by the `async_state` which is a `ProofingSessionAsyncResult`. This is a struct that includes the status of the `ResolutionProofingJob`. This status can have 4 values:
- `NONE`: This means that no job has been submitted. In this state the controller should render the “Verify your information” page.
- `IN_PROGRESS`: This means that the job is running. In this state the controller should render a loading state …
=> LG-14094 Stop logging extra “IdV: doc auth verify visited” events

app/javascript/packs/mock-device-profiling.tsx, app/javascript/packs/ssn-field.ts, app/javascript/packs/state-guidance.ts
Updates code which binds events to `DOMContentLoaded` to execute immediately.
This event is typically used to ensure that all content is present on a page before executing JavaScript, in case the script is loaded earlier than the elements it references. Packs are always loaded as the last content of every page ([source](https://github.com/18F/identity-idp/blob/83ec71c3912c259be6dc7f93426df5c81a69edb3/app/views/layouts/base.html.erb#L75)), so it's not necessary to wait before referencing these elements.
This also relates to #11096 and #11126, where `defer` has the effect of delaying `DOMContentLoaded` being fired, unlike asynchronous scripts. We can offset this by not relying on the `DOMContentLoaded`.
>The DOMContentLoaded event fires when the HTML document has been completely parsed, and …
=> Remove unnecessary use of DOMContentLoaded

config/initializers/job_configurations.rb, spec/config/initializers/job_configurations_spec.rb
See #11115 and #11030
PR #11115 is likely to get at the cause/source of our intermittent reporting problems. That said, this PR along with #11030 gives us some extra insurance that the reports will run regardless of other efforts. Since this is a fairly small and safe change, I'm suggesting that we do this while also focusing on the more important line of improvement that is work like #11115
=> Stagger more reporting jobs

db/primary_migrate/20240822122355_add_selected_email_to_identity.rb, db/schema.rb
[LG-13001](https://cm-jira.usa.gov/browse/LG-13001)
Adds `email_address_id` column to **Identities** table to preserve 50/50 state integrity prior to releasing https://github.com/18F/identity-idp/pull/10951
=> LG 13001 Identity table migration for implementation Select email to share with partner

lib/reporting/drop_off_report.rb, spec/lib/reporting/drop_off_report_spec.rb
https://cm-jira.usa.gov/browse/LG-14117
This code queries Cloudwatch for the relevant IPP success events and adds them to the report.
I was hoping that we could include the new event addition in the list with the other events we query for, but the structure/schema does not match up. I'm still chasing down our options there, see [this thread](https://gsa-tts.slack.com/archives/C04GA9WQ85B/p1723564151026709?thread_ts=1723482960.667779&cid=C04GA9WQ85B). Meanwhile, I've tried to write code where simplifying the query would require a minimal rewrite if we can arrange for it.
* Try and trigger some fake data in staging
* Run the report in staging
=> Add in-person proofing successes to the weekly drop-off report

.rubocop.yml, app/jobs/reports/monthly_gpo_letter_requests_report.rb, app/services/doc_auth/lexis_nexis/image_metrics_reader.rb, app/services/encryption/encryptors/attribute_encryptor.rb, app/services/flow/base_flow.rb, lib/reporting/mfa_report.rb, spec/features/phone/confirmation_spec.rb, spec/models/user_spec.rb, spec/support/matchers/accessibility.rb, spec/support/shared_examples_for_email_validation.rb
[Based on an observation in another PR](https://github.com/18F/identity-idp/pull/11142/files#r1731375804), I realized we were 99% consistent on `#map` over `#collect`, and that Rubocop could easily help us stay at 100% consistency
Basically: it discourages all of the `#*ect` methods (except `#select`, that's much clearer than `#find_all`)
[Docs link](https://docs.rubocop.org/rubocop/cops_style.html)
=> Use Rubocop to enforce consistent collection methods

app/controllers/idv/in_person/verify_info_controller.rb, spec/controllers/idv/in_person/verify_info_controller_spec.rb
[LG-13726](https://cm-jira.usa.gov/browse/LG-13726)
An error recently surfaced in NewRelic: `undefined method 'merge' for nil` occurring in the verify info controller. This error would occur because a possibly nil "pii_from_user "object was being called "merge" upon. This updates the code to check for missing PII before rendering the verify info controller, as well as handle that nil object gracefully and prevent such an the error from breaking the app.
https://github.com/user-attachments/assets/c801c977-6b9c-46b6-a604-71b298136e9b
https://github.com/user-attachments/assets/03a14af3-8d69-4fe1-bb24-cc253918bbe3
=> LG-13726 update verify info controller to redirect when pii is missing

app/views/idv/shared/_document_capture.html.erb, spec/views/idv/shared/_document_capture.html.erb_spec.rb
[LG-14314](https://cm-jira.usa.gov/browse/LG-14314)
- the mock-client meta data is defined only when the mock-client attribute is true
See video recording below or follow steps
https://gsa-tts.slack.com/archives/C0751MB0CAV/p1724762294302399?thread_ts=1724762259.730499&cid=C0751MB0CAV
=> revert back to sending mock client metadata only when using the mock doc auth vendor

app/controllers/event_disavowal_controller.rb, app/services/analytics_events.rb, app/services/event_disavowal/build_disavowed_event_analytics_attributes.rb, spec/controllers/event_disavowal_controller_spec.rb
[LG-14123](https://cm-jira.usa.gov/browse/LG-14123)
Passes the `disavowed_event.user.id` value along to the respective Analytics events.
=> LG 14123 Include associated user_id in event disavowal CloudWatch logs

app/services/analytics_events.rb
The `idv_doc_auth_verify_polling_wait_visited` gets logged when a polling event occurs on the verify info step. This event does not have any extra attributes that it needs to log. As a result we left off the extra arguments when adding it.
Leaving off the extra arguments led to an issue with the `AnalyticsEventsEnhancer`. This adds attributes to the events that are prefixed with `idv_` when they are called. A result of this was a `ArgumentError` for this event since it did not have the extra arguments for these attributes.
=> Allow for extra arguments to `idv_doc_auth_verify_polling_wait_visited` event

app/presenters/completions_presenter.rb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/presenters/completions_presenter_spec.rb, spec/views/sign_up/completions/show.html.erb_spec.rb
[LG-14220](https://cm-jira.usa.gov/browse/LG-14220)
Updates content logic for the consent screen to be simplified and standardized across IAL1 and IdV consent.
1. Have the IdP and [sample application](https://github.com/18f/identity-oidc-sinatra) running simultaneously
2. Go to http://localhost:9292
3. (Optional) Set "Level of Service" to "Identity-verified"
4. Click "Sign in"
5. Proceed to sign in
6. (If not prompted to consent, visit http://localhost:3000/account/connected_accounts , "Disconnect" on the listed applications, and start over)
7. When prompted to consent, observe consistent language "We’ll share this information with %{sp}:"
8. Simulate yearly re-consent by applying diff:
```diff
diff --git a/app/presenters/completions_presenter.rb b/app/presenters/completions_presenter.rb …
```
=> LG-14220: Standardize and simplify content for consent screen

app/controllers/idv/agreement_controller.rb, app/services/idv/session.rb, spec/controllers/idv/agreement_controller_spec.rb
[LG-14196](https://cm-jira.usa.gov/browse/LG-14196)
This is the first of a two-part series; part 1 needs to be released before part 2.
Socure's API requires us to pass the time when a user consented to IdV. We currently store a boolean, `idv_consent_given`, on the user session, tracking whether they have agreed to sharing their data for IdV. This moves to storing a timestamp, `idv_consent_given_at`, so that we can stop answering "When did the user consent?" with "Yes." (Pragmatically, because it's stored on the session, we know they consented very recently. But we should store the actual timestamp.)
N.B. also that we are not currently sending any data to Socure in production environments; it is all feature-flagged off.
I am currently leaving the old …
=> LG-14196 | Set idv_consent_given_at timestamp

config/application.yml.default
[LG-14095](https://cm-jira.usa.gov/browse/LG-14095)
Previously, the default in the Rails production environment was lexisnexis. This PR makes it mock everywhere, and forces us to explicitly set an overriding default in the S3 configs for each env.
=> LG-14095: make the default doc_auth vendor `mock`

app/services/encryption/contextless_kms_client.rb, app/services/encryption/kms_client.rb, app/services/encryption/kms_logger.rb, app/services/encryption/password_verifier.rb, app/services/encryption/user_access_key.rb, spec/services/encryption/contextless_kms_client_spec.rb, spec/services/encryption/kms_client_spec.rb, spec/services/encryption/kms_logger_spec.rb
To better understand the usage of the older single-region KMS key, this adds the context that would have been used in the KMS API call to the KMS log.
=> Log context of contextless kms

package.json, yarn.lock
Updates `micromatch` to the latest version to resolve a security advisory.
Advisory: GHSA-952p-6rrq-rcjv
`micromatch` is a subdependency of `fast-glob`. While not strictly necessary to update `fast-glob` as part of this, I did so for good measure ([bug fixes and performance improvements](https://github.com/mrmlnc/fast-glob/releases)).
Approach was to manually remove the top-level entry for `micromatch` in `yarn.lock` and re-run `yarn install`.
`make audit` produces no vulnerabilities.
=> Update fast-glob (micromatch) to resolve security advisory

app/views/users/service_provider_revoke/show.html.erb, spec/features/account_connected_apps_spec.rb, spec/support/features/navigation_helper.rb
Updates the connected accounts revocation screen to return a user to their connected accounts (where they came from) if they choose to cancel revocation, rather than the root accounts dashboard.
It also includes a handful of general code quality improvements:
- Use standard PageFooterComponent
- Update feature specs to interact with the page as a user would be expected to, rather than visiting URLs directly
- Avoid redundant navigation in feature specs
- Avoid redundant assertions (e.g. checking history path in revocation scenario, when already asserted in preceding scenario)
2. Sign in
3. From accounts dashboard, click "Your connected accounts"
4. Click "Disconnect" on one of  your connected accounts
a. If you don't have a connected account, run and sign in …
=> Return user to connected accounts when cancelling revocation

app/controllers/idv/enter_password_controller.rb, app/controllers/idv/welcome_controller.rb, app/services/analytics_events.rb, app/services/idv/session.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/controllers/idv/welcome_controller_spec.rb, spec/features/idv/analytics_spec.rb
We want to start tracking how long it takes people to complete identity proofing. Part of that is understanding how long it takes people to go from the start of the process to the enter password step where their profile is created. At this point we want to know:
1. How long did it take the person to complete the workflow
2. What steps remain before person finishes proofing (i.e. verify-by-mail, in-person-proofing, or fraud review)
The enter password submit events already logs enough information to determine the second. This commit starts tracking the duration of the proofing session by adding a timestamp at the welcome step and logging the elapsed seconds since on the enter password events.
=> LG-14253 Track time to complete proofing workflow

app/jobs/reports/fraud_metrics_report.rb, lib/reporting/fraud_metrics_lg99_report.rb, spec/jobs/reports/fraud_metrics_report_spec.rb, spec/lib/reporting/fraud_metrics_lg99_report_spec.rb
changelog: Internal, Reporting, Update LG-99 Report Layout
[LG-14259](https://cm-jira.usa.gov/browse/LG-14259)
Broke the LG-99 csv/tables into 3 sections
LG-99
Suspension
Reinstatement
Before:
After:
=> LG-14259 Update Report formatting

Gemfile.lock, spec/support/matchers/accessibility.rb
Fixes an issue with our accessibility page testing where applying `:wcag22aa` runs _only_ [tests for rules specific to WCAG 2.2 AA](https://github.com/dequelabs/axe-core/blob/master/doc/rule-descriptions.md#wcag-22-level-a--aa-rules), and does not inherit from rules below that.
I noticed this when trying to fix an existing issue which hadn't been flagged by the tests. I'll plan to open a separate pull request for that, since it involves writing new tests, but the scope of this pull request is addressing existing issues within the current tests.
There are existing issues with the phone input component. These are addressed in newer versions of the library, and while I have an in-progress branch to implement the upgrade, there are some incompatibilities with the newer version and content …
=> Run all relevant Axe accessibility test groups

app/views/accounts/_connected_app.html.erb, app/views/accounts/connected_accounts/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/features/account_connected_apps_spec.rb
Supports [LG-13665](https://cm-jira.usa.gov/browse/LG-13665)
Updates the layout of the connected accounts page to show the content of individual accounts in a stacking arrangement, with a "Disconnect" button.
This incrementally works toward [LG-13665](https://cm-jira.usa.gov/browse/LG-13665), [pending clarification about identities without linked emails](https://gsa-tts.slack.com/archives/C05R6BLVAQG/p1725033025669399).
It also includes a bit of general clean-up:
- Avoid `String#html_safe` in favor of `_html` suffix for locale string
- Use semantic HTML markup (headings for each item, `<ul>` for list of accounts)
2. Sign in
3. Click "Your connected accounts"
4. Observe that accounts are rendered as shown in "After" screenshot
Before|After
---|---
=> Rearrange connected accounts in stacked layout

app/views/shared/_footer_lite.html.erb
Updates footer markup to use [`<picture>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) to avoid loading an unnecessary image.
The GSA logo rendered the footer is either light or dark depending on the viewport size. In the previous implementation, both images would be downloaded, despite the fact that only one would ever be visible.
2. Verify no visual regression of the "GSA" logo in the footer, at both large and small viewport size
3. Open browser developer tools Network tab
4. Reload the page
5. Verify that only one variation of the "square-gsa" logo is loaded
Before|After
---|---
=> Use picture element to avoid unnecessary image load

app/controllers/concerns/saml_idp_auth_concern.rb, app/controllers/saml_idp_controller.rb, app/models/federated_protocols/oidc.rb, app/models/federated_protocols/saml.rb, app/services/analytics_events.rb, app/services/attribute_asserter.rb, spec/features/idv/analytics_spec.rb, spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb, spec/models/federated_protocols/saml_spec.rb
Restrict ial and aal determination to the idp app.
This was unnecessarily leaking into the saml_idp gem. A subsequent PR in
that repo will remove these concerns there.
As part of the move to semantic ACR values, we will also replace the regex prefix matching for IALs and AALs with explicit enumerations.
=> Refactor ial/aal determination

app/jobs/get_usps_proofing_results_job.rb, spec/jobs/get_usps_proofing_results_job_spec.rb
The `GetUspsProofingResultsJob` fetches the results of USPS enrollments and updates the status of the enrollment and the profile based on the response.
When the job updates an enrollment (and associated profile) it is expected to log a `GetUspsProofingResultsJob: Enrollment status updated` event. This is done by calling `#log_enrollment_updated_analytics`. As part of the change in #11186 we identified that `#handle_unexpected_response` response did not log an enrollment update analytics event.
This commit adds logging for the cases where `#handle_unexpected_response` is called and enrollments are updated. There are 2 cases where this occurs:
- When the enrollment ID is invalid. A `#handle_invalid_enrollment_code` method was added to account for this.
- When the applicant unique ID is …
=> Log that an in-person enrollment is updated when canceled for invalid enrollment or applicant ID

app/assets/stylesheets/components/_card.scss, app/views/test/telephony/index.html.erb
Removes styles for the "wide" variation of the `card` CSS class, and re-layouts the telephony test page as a two-column grid of individual cards.
These styles are only used on the telephony testing screen in internal development. Removing them avoids additional ad-hoc (non-design-system-standard) styling and reduces the size of the end-user application stylesheet.
Easier to review with whitespace changes hidden: https://github.com/18F/identity-idp/pull/11176/files?w=1
1. Go to http://localhost:3000/test/telephony
2. Observe updated layout
Before|After
---|---
=> Remove wide card styles

app/controllers/idv/by_mail/enter_code_controller.rb, app/mailers/user_mailer.rb, spec/mailers/previews/user_mailer_preview.rb, spec/mailers/user_mailer_spec.rb
I noticed these 2 cleanup opportunities while working on a new account verified email:
- There is some out-of-place indentation in `EnterCodeController`
- There is a comment saying to remove an argument in the next deploy. The next deploy after that comment was added was ~150 deploys ago.
This commit cleans up both
=> Touch up code related to "account_verified" email

app/components/status_page_component.html.erb, app/components/status_page_component.rb, app/controllers/accounts/connected_accounts/selected_email_controller.rb, app/controllers/sign_up/select_email_controller.rb, app/forms/select_email_form.rb, app/models/user.rb, app/presenters/account_show_presenter.rb, app/services/analytics_events.rb, app/views/accounts/_connected_app.html.erb, app/views/accounts/connected_accounts/selected_email/edit.html.erb, config/initializers/simple_form.rb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, config/routes.rb, spec/components/status_page_component_spec.rb, spec/controllers/accounts/connected_accounts/selected_email_controller_spec.rb, spec/controllers/sign_up/select_email_controller_spec.rb, spec/features/account_connected_apps_spec.rb, spec/features/visitors/email_language_preference_spec.rb, spec/forms/select_email_form_spec.rb, spec/i18n_spec.rb, spec/presenters/account_show_presenter_spec.rb, spec/support/matchers/accessibility.rb, spec/views/accounts/connected_accounts/selected_email/edit.html.erb_spec.rb, spec/views/accounts/connected_accounts/show.html.erb_spec.rb, spec/views/sign_up/select_email/show.html.erb_spec.rb
[LG-13665](https://cm-jira.usa.gov/browse/LG-13665)
Adds a new flow to allow a user to change their selected email shared with a partner from their Connected Accounts dashboard screen.
1. Go http://localhost:3000
2. Sign in
3. From account dashboard, click "Connected Accounts" in sidebar
4. (If you don't have any connected accounts, sign in and consent using [sample application](https://github.com/18f/identity-oidc-sinatra))
5. Observe:
1. If you have selected a specific email to be changed (either from consent screen or from the following steps), it is shown
2. Otherwise, you see "Email not yet selected"
7. Click "Change"
8. Change your selected email (you may need to _add_ a second email first, unless you have "Not yet selected")
9. Click "Submit"
10. Repeat Step 5
=> LG-13665: Add option to change selected email shared with partner

app/controllers/application_controller.rb, app/controllers/concerns/mfa_setup_concern.rb, app/forms/recaptcha_form.rb, app/forms/webauthn_visit_form.rb, app/presenters/two_factor_options_presenter.rb, app/services/user_event_creator.rb
Rearranges a handful of `&&` conditions to move trivial-cost checks to earlier in the condition, leveraging boolean short-circuiting to avoid more costly checks.
These were discovered by searching ` && ` in `app/**/*.rb` files and manually reviewing each instance.
It's not expected this should have a meaningful impact, but there may be scenarios where a condition was already written with short-circuiting in mind, where the latter part of a condition relies on a dependency established in an earlier part. Those have been considered as part of these changes, but a secondary review is appreciated.
=> Rearrange conditions to short-circuit before database queries

app/models/concerns/user_access_key_overrides.rb, app/services/encryption/password_verifier.rb, app/services/encryption/uak_password_verifier.rb, app/services/encryption/user_access_key.rb, spec/services/encryption/password_verifier_spec.rb, spec/services/encryption/uak_password_verifier_spec.rb
Follow up to #11174 to add even more context to our logging. The depths of the calls are pretty far removed, so it unfortunately requires passing it from pretty far up.
=> Log more context of contextless KMS

app/controllers/users/sessions_controller.rb, spec/controllers/users/sessions_controller_spec.rb
Adds necessary CSP exceptions to allow reCAPTCHA to be loaded when performed at sign-in.
You need to add configuration values for reCAPTCHA credentials, but they don't have to be valid.
In `config/application.yml`:
```
recaptcha_enterprise_api_key: 'test'
recaptcha_enterprise_project_id: 'test'
recaptcha_site_key: 'test'
```
Verify that the header values are present on the sign-in screen:
1. Start `make run`
2. In a terminal console: `curl -I --silent http://localhost:3000 | grep content-security-policy`
3. Observe "google.com" and "gstatic.com" domains in the resulting header value
=> Add CSP allowlisting for reCAPTCHA at sign in

app/controllers/idv/in_person/state_id_controller.rb, app/services/idv/steps/in_person/state_id_step.rb, app/views/idv/in_person/state_id.html.erb, app/views/idv/in_person/state_id/show.html.erb, spec/controllers/idv/in_person/state_id_controller_spec.rb, spec/services/idv/steps/in_person/state_id_step_spec.rb
[LG-13824](https://cm-jira.usa.gov/browse/LG-13824)
This renames the state ID form name `"state_id"`, and the field `"state_id_number"`, to `"identity_doc"` and `"id_number"` so that the fields do not start with the word "state" - The fields starting with the word "state" causes Chrome and Firefox to make incorrect assumptions that some fields can be autofilled with geographical state, if a user has such an autofill entry saved, when those fields should not be autofilled as such. <sub><sup>This behavior is also a pain for developer testing...</sup></sub>
Notes: 
- This change translates the data back to their original param names in the controller, so this doesn't affect how the data is named throughout the application. The name state_id only has an adverse …
=> LG-13824 Rename state id form as workaround to aggressive browser autofill behavior

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_profile-section.scss, app/views/accounts/connected_accounts/show.html.erb, app/views/accounts/history/show.html.erb, app/views/accounts/show.html.erb, app/views/accounts/two_factor_authentication/show.html.erb, app/views/events/show.html.erb, app/views/layouts/application.html.erb, app/views/test/telephony/index.html.erb, spec/features/account_email_language_spec.rb
Updates card styling to standardize around the usage of cards as stackable elements, as used in the account page and elsewhere (e.g. telephony test screen). This inverts previous assumptions of the base layout card styling as the default, which has much wider padding by default, now implementing those styles in the base layout specifically as the outlier.
In doing so, it eliminates the need for a special `profile-info-box` CSS class, since those styles are now the baseline card styling.
Verify no visual regressions on wide and narrow viewport sizes, particularly for the base layout and account page card stylings.
=> Simplify and standardize card styling

app/javascript/packages/memorable-date/index.spec.ts, app/javascript/packages/validated-field/validated-field-element.ts, app/javascript/packages/validated-field/validated-field.spec.tsx
Fixes an issue where React `<ValidatedFieldElement />` changes to error messages after creating an element would not be reflected (not kept in sync). This happens because the error messages were previously assigned when the element is connected to the page, and never updated after that. Because React will often try to reuse an existing element rather than recreating one, this creates issues if we want to change the error messages after the element is mounted.
The solution is to compute the error messages on-demand, each time an error message is shown.
Verify that the included test passes:
```
yarn mocha app/javascript/packages/validated-field/validated-field.spec.tsx
```
Optionally, verify that the included test fails on `main`:
```
git checkout main
git checkout …
```
=> Support changing error strings after ValidatedFieldElement connected

app/controllers/socure_webhook_controller.rb, app/services/analytics_events.rb, app/services/idv/analytics_events_enhancer.rb, spec/controllers/socure_webhook_controller_spec.rb
[LG-13990](https://cm-jira.usa.gov/browse/LG-13990)
Logs a new event upon authorized receipt of a correctly formatted webhook event from Socure. Will log only the following data:
- `created` => `created_at`
- `customerUserId` => `customer_user_id`
- `eventType` => `event_type`
- `referenceId` => `reference_id`
- `customerUserId` => `user_id`
Run the following :
```
curl -X POST -H "Authorization: this-is-a-secret" -H "Content-Type: application/json" -d '{"event":{ "referenceId": "REF_ID","eventType": "TESTING","pii":"PII","customerUserId":"123","harmless_data":"kitten"}}'  http://127.0.0.1:3000/api/webhooks/socure/event
```
look in your event log and expect to see similar to:
```
{"name":"idv_doc_auth_socure_webhook_received","properties":{"event_properties":{" …
```
=> LG-13990: log an event on receipt of Socure webhooks

app/views/sign_up/select_email/show.html.erb
Relates to [LG-13665](https://cm-jira.usa.gov/browse/LG-13665) and [LG-13001](https://cm-jira.usa.gov/browse/LG-13001) (brings implementations in sync)
Updates partner email selection during sign-up completions to use accessibility labeling from similar view in #11196.
Specifically, revises the radio button "label" to use the heading ("Select your preferred email") rather than the paragraph description ("You may change which email you share with Example Sinatra App since you have multiple emails associated with your Login.gov account."), and provides the paragraph description as an additional `aria-describedby` resource.
1. (Prerequisite: Revoke consent for OIDC sample application if already consented)
2. Run [OIDC sample application](https://github.com/18f/identity-oidc-sinatra) in a …
=> Improve accessibility labeling for partner email select

config/initializers/ab_tests.rb, spec/config/initializers/ab_tests_spec.rb
Addendum for [LG-14216](https://cm-jira.usa.gov/browse/LG-14216) (implemented in #11148)
Updates the discriminator evaluation for reCAPTCHA at sign-in to randomly assign requests which aren't associated with a user. This provides some resiliency against user existence probing, though there are other mitigations which already provide protection (ping me on Slack if interested).
This test is not currently live in production.
This would likely be very incompatible with #11202 since it would result in persisting records for many random values (although only within the domain of 1 bytes worth of random data), so I'd plan to avoid opting-in reCAPTCHA for persistence if moving forward with these changes.
Verify that reCAPTCHA is performed based on percent tested when trying to authenticate with …
=> LG-14216: Assign reCAPTCHA A/B test bucket for missing user

app/forms/idv/api_image_upload_form.rb, app/services/analytics_events.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb
[LG-13316](https://cm-jira.usa.gov/browse/LG-13316)
Added selfie_attempts as a metric in existing log event named 'doc auth image upload vendor submitted'.
=> Lg 13316 add selfie attempt num to idv event

app/views/accounts/_auth_apps.html.erb, app/views/accounts/_pii.html.erb, app/views/accounts/_piv_cac.html.erb, app/views/accounts/_webauthn_platform.html.erb, app/views/accounts/_webauthn_roaming.html.erb, spec/features/accessibility/account_pages_spec.rb, spec/views/accounts/_auth_apps.html.erb_spec.rb, spec/views/accounts/_piv_cac.html.erb_spec.rb, spec/views/accounts/_webauthn_platform.html.erb_spec.rb, spec/views/accounts/_webauthn_roaming.html.erb_spec.rb
Adds feature tests to run automated accessibility tests against account pages.
This was motivated by observing issues when running Axe browser extension on account pages, then realizing we had no coverage for these screens.
It also includes changes to fix existing issues, further reinforcing the value of these tests.
=> Run automated accessibility tests for account pages, fix issues

app/forms/idv/api_image_upload_form.rb, app/forms/webauthn_setup_form.rb, app/forms/webauthn_verification_form.rb, app/services/analytics_events.rb, spec/forms/webauthn_setup_form_spec.rb, spec/forms/webauthn_verification_form_spec.rb
Removes `.compact` from form `extra_analytics_attributes`, since this is handled by the `Analytics` class as of #10987.
The extra compacting also hid parameters from the `UndocumentedParamsChecker`, evidenced by the additional changes to document these parameters after removing the `.compact`.
=> Remove redundant Hash#compact for extra analytics events

lib/tasks/backfill_in_person_pending_at.rake
[LG-14320](https://cm-jira.usa.gov/browse/LG-14320)
Added a script to deactivate profiles that are considered to be IPP verification cancelled state.
Scenario: Running backfill script
```bash
bundle exec rake seed:broken_profiles
```
```ruby
InPersonEnrollment.where(status: [:expired, :cancelled, :failed]).
includes(:profile).
where.not(profile: { in_person_verification_pending_at: nil }).
count
```
**Note: It might be good to setup the seeder to create a few pending profiles for testing to ensure those do not get updated.**
```bash
bundle exec rake profiles:backfill_deactivated_ipp_verification_cancelled UPDATE_PROFILES=false
```
```bash
bundle exec rake profiles:backfill_deactivated_ipp_verification_cancelled UPDATE_PROFILES=true
```
```ruby …
```
=> LG-14320 Add deactivate IPP cancelled profiles task

app/controllers/idv/cancellations_controller.rb, spec/controllers/idv/cancellations_controller_spec.rb, spec/factories/users.rb
changelog: Internal, In-person proofing, The "Exit Login.gov" button on the cancel page from the barcode step will no longer cancel user's pending enrollments.
[LG-14390](https://cm-jira.usa.gov/browse/LG-14390)
The "Exit Login.gov" button on the cancel page from the barcode step will no longer cancel user's pending enrollments.
Scenario: Barcode Page: "exit login.gov" button from cancel page 
Scenario: During Identity Verification: "exit login.gov" button from cancel page
=> LG-14390 No longer cancel pending enrollments on logout from cancel page

app/controllers/idv/by_mail/enter_code_controller.rb, app/controllers/idv/enter_password_controller.rb, app/services/user_alerts/alert_user_about_account_verified.rb, lib/action_account.rb, spec/controllers/idv/by_mail/enter_code_controller_spec.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/lib/action_account_spec.rb, spec/services/user_alerts/alert_user_about_account_verified_spec.rb
When a user completes verification we send them an `account_verified` email which contains the following information:
- The date the verification occurred
- The service provider for which the verification was performed
This applies to all verifications except for verifications through in-person which have their own email.
Prior to this commit the service provider was determined using the SP in the session. This means that when the user is verifying in an out-of-band flow (verify-by-mail or fraud review in this case) their email would likely not contain the name of the SP that triggered the verification. For verify-by-mail we tell the user to enter their code by going to “secure.login.gov”. In this case there is no SP in the session. For fraud review we made no effort to send an email with …
=> Use `Profile#initiating_service_provider` to determine SP named in `account_verified` email

app/controllers/idv/session_errors_controller.rb, app/services/analytics_events.rb, spec/controllers/idv/session_errors_controller_spec.rb
[LG-13135](https://cm-jira.usa.gov/browse/LG-13135)
Renames the symbol `:submit_attempts_remaining` to `remaining_submit_attempts` for consistency with the rest of the codebase.
=> LG-13135: rename `submit_attempts_remaining`

app/controllers/idv/how_to_verify_controller.rb, app/services/analytics_events.rb, spec/controllers/idv/agreement_controller_spec.rb, spec/controllers/idv/by_mail/enter_code_controller_spec.rb, spec/controllers/idv/document_capture_controller_spec.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/controllers/idv/how_to_verify_controller_spec.rb, spec/controllers/idv/hybrid_handoff_controller_spec.rb, spec/controllers/idv/hybrid_mobile/capture_complete_controller_spec.rb, spec/controllers/idv/hybrid_mobile/document_capture_controller_spec.rb, spec/controllers/idv/in_person/address_controller_spec.rb, spec/controllers/idv/in_person/ssn_controller_spec.rb, spec/controllers/idv/in_person/state_id_controller_spec.rb, spec/controllers/idv/in_person/usps_locations_controller_spec.rb, spec/controllers/idv/in_person/verify_info_controller_spec.rb, spec/controllers/idv/link_sent_controller_spec.rb, spec/controllers/idv/mail_only_warning_controller_spec.rb, spec/controllers/idv/phone_controller_spec.rb, spec/controllers/idv/ssn_controller_spec.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/controllers/idv/welcome_controller_spec.rb, spec/controllers/risc/security_events_controller_spec.rb, spec/features/idv/confirm_start_over_spec.rb, spec/features/idv/outage_spec.rb, spec/features/idv/verify_by_mail_pending_spec.rb, spec/features/users/profile_recovery_for_gpo_verified_spec.rb, spec/features/users/verify_profile_spec.rb, spec/forms/gpo_verify_form_spec.rb, spec/services/usps_in_person_proofing/enrollment_helper_spec.rb
Updates controller specs to remove blanket exemptions for `allowed_extra_analytics`, and adds documentation where existing errors occur in doing so.
Most of these are in IdV/IPP.
**Why?**
* So that analytics properties are documented in [Analytics Events handbook article](https://lg-public.pages.production.gitlab.login.gov/identity-internal-handbook/articles/analytics-events.html), and we have a clear understanding of what analytics properties exist
* Incremental step toward removing `allowed_extra_analytics`
Double-check that required keyword arguments are always passed.
=> Document analytics properties exempted in controller specs

app/services/analytics_events.rb, app/services/doc_auth/mock/result_response.rb, app/services/flow/flow_state_machine.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/features/idv/analytics_spec.rb, spec/features/idv/in_person_threatmetrix_spec.rb, spec/features/idv/steps/in_person/address_spec.rb, spec/features/idv/steps/in_person/state_id_step_spec.rb, spec/services/doc_auth/mock/doc_auth_mock_client_spec.rb, spec/services/doc_auth/mock/result_response_spec.rb
Implements suggestion from https://github.com/18F/identity-idp/pull/11220#discussion_r1751995660 to unexempt `state_id_step_spec.rb` allowed extra analytics, fixing issues exposed:
- Doc auth mock proofing vendor didn't include all expected analytics properties
- Fix: Include expected analytics property
- `step_count` is only included for FSM implementation, but is being removed in non-FSM approach
- Fix: Remove `step_count` from FSM with expectation that it's no longer needed
=> Fix expected analytics logging for DocAuth result

spec/features/idv/doc_auth/document_capture_spec.rb
[LG-13092](https://cm-jira.usa.gov/browse/LG-13092)
Consolidated a bunch of test cases in `features/idv/doc_auth/document_capture_spec.rb` for speed and eliminated some test duplication.
All of the doc capture error handling except rate limiting is now tested in a single inline test (that bumps the rate limits so that we don't trip over them) that retries with different error conditions to check the messages shown for each. This is much faster than restarting IdV from scratch for each error.
=> Jmax/lg 13092 delete duplicate tests in document capture spec.rb

app/controllers/idv/enter_password_controller.rb, app/services/analytics_events.rb, lib/reporting/identity_verification_report.rb, spec/controllers/idv/enter_password_controller_spec.rb
Users are marked `fraud_review_pending` on the last step of the IdV process. For users who go through document capture and verify by phone that means that they are marked `fraud_review_pending` at enter password. However, users doing verify-by-mail or in-person-proofing are not marked `fraud_review_pending` until they complete those flows. This is done so that users do not get marked `fraud_review_pending` if we have disabled device profiling by the time they get to those later steps.
This is an issue with logging at the enter-password step since those users in in-person and verify-by-mail that will eventually be marked fraud review pending are not when we log those properties. This is especially problematic since we use the `idv_final` event at the password step for the Identity …
=> LG-14432 Log `fraud_pending_reason` on `idv_final` event

config/locales/fr.yml
N/A
This PR removes an extraneous space on authentication setup success screen in French
Pre-requisite
|--------|--------|
|  <img width="729" alt="Screenshot 2024-09-13 at 9 01 09 AM" src="https://github.com/user-attachments/assets/5b61f4d8-0296-4a04-a4b9-6f4e0db97022"> | <img width="846" alt="image" src="https://github.com/user-attachments/assets/57d70c82-07f6-4be6-a5b1-b61038eb7180"> |
=> Hotfix: fix exclamation mark for authentication setup success page in French

lib/reporting/drop_off_report.rb, spec/lib/reporting/drop_off_report_spec.rb
[LG-14364](https://cm-jira.usa.gov/browse/LG-14364)
This is to update the `Verified (event)` field in the IdV Drop-off Report so that it accurately reflects only events where the user is successfully verified.
This uses the existing `idv_final_resolution_verified` method.
=> LG-14364 update Verified (event) in dropoff report

lib/tasks/backfill_in_person_pending_at.rake
The backfill script will no longer overwrite existing deactivation reasons on IPP cancelled profiles.
[LG-14498](https://cm-jira.usa.gov/browse/LG-14498)
The backfill script will no longer overwrite existing deactivation reasons on IPP cancelled profiles.
Ensure a profile exists with deactivation reason `encryption_error`:
**Note: With default config this will be time sensitive make sure InPersonEnrollment status isn't `passed` when you go to update the enrollment status. The profile cannot be active during this test plan**
Scenario: Running Backfill script
```ruby
InPersonEnrollment.where(status: [:expired, :cancelled, :failed]).
includes(:profile).
where.not(profile: { in_person_verification_pending_at: nil }).
count
```
```bash
bundle exec …
```
=> LG-14498 Fix backfill deactive IPP cancelled profiles

config/application.yml.default, spec/controllers/idv/in_person/address_controller_spec.rb, spec/controllers/idv/in_person_controller_spec.rb, spec/features/idv/analytics_spec.rb, spec/features/idv/in_person_spec.rb, spec/features/idv/in_person_threatmetrix_spec.rb, spec/features/idv/steps/in_person/verify_info_spec.rb, spec/features/idv/steps/in_person_opt_in_ipp_spec.rb, spec/support/features/in_person_helper.rb
[LG-13657](https://cm-jira.usa.gov/browse/LG-13657)
In preparation for turning on the `in_person_state_id_controller_enabled` flag in other environments, this PR turns it on in `test` and updates tests accordingly.
=> LG-13657 Remove IPP FSM - set controller feature flag in test and update tests

Gemfile.lock, spec/controllers/users/email_confirmations_controller_spec.rb, spec/controllers/users/emails_controller_spec.rb, spec/controllers/users/sessions_controller_spec.rb, spec/factories/email_addresses.rb, spec/factories/users.rb, spec/features/users/sign_up_spec.rb, spec/services/push_notification/email_changed_event_spec.rb, spec/services/push_notification/http_push_spec.rb, spec/services/push_notification/identifier_recycled_event_spec.rb, spec/services/reset_user_password_spec.rb, spec/services/usps_in_person_proofing/proofer_spec.rb, spec/support/features/session_helper.rb
Upgrade Faker to latest major version (2.19 -> 3.4.2)
* Includes API fixes (i.e., `Faker::Internet.safe_email` is now `Faker::Internet.email`)
=> Upgrade Faker to latest major version

app/controllers/idv/agreement_controller.rb, app/controllers/idv/in_person/verify_info_controller.rb, app/controllers/idv/verify_info_controller.rb, app/jobs/socure_shadow_mode_proofing_job.rb, app/services/proofing/socure/id_plus/input.rb, app/services/proofing/socure/id_plus/request.rb, spec/controllers/idv/in_person/verify_info_controller_spec.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/services/proofing/socure/id_plus/input_spec.rb, spec/services/proofing/socure/id_plus/request_spec.rb, spec/support/flow_policy_helper.rb
Socure requires that we send them the timestamp that the user submitted consent to share their info. A previous commit started recording the timestamp in the `Idv::AgreementController`. This commit does the work to start passing to timestamp to Socure in the applicant hash.
=> LG-14260 Send the actual timestamp that consent was submitted in Socure request

app/controllers/two_factor_authentication/webauthn_verification_controller.rb, app/controllers/users/two_factor_authentication_controller.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb, spec/features/remember_device/revocation_spec.rb, spec/features/webauthn/hidden_spec.rb, spec/support/shared_examples/remember_device.rb
[LG-12213](https://cm-jira.usa.gov/browse/LG-12213)
Fixes an issue where a user may be redirected away from authenticating with Face or Touch Unlock if they are on an unsupported device, and if they have a stronger authenticator available.
For context, we detect if the current device has a platform authenticator available when signing in, and if they're on a "supported" device for enrolling Face or Touch Unlock (iOS 16+, Android 9+). If they are not on a supported device, but the user has a platform authenticator credential associated with their device, we redirect them to their list of MFA options. They can choose to still authenticator with Face or Touch Unlock if they want.
The problem is that the check was performed when the user arrives at the Face or Touch Unlock verification …
=> LG-12213: Fix redirect when selecting Face/Touch on unsupported device

app/controllers/saml_idp_controller.rb, app/services/analytics_events.rb
changelog: Internal, Protocols, Removes dependency on service provider instance variable
https://gitlab.login.gov/lg-people/Melba/backlog-fy24/-/issues/2 and
[LG-4875](https://cm-jira.usa.gov/browse/LG-4875)
This is the penultimate step to clear out this old ticket :)
The matching_cert method has been pulled into the request object, rather than the service_provider object. There's one more bit of cleanup to be done on the saml_idp to remove that instance variable, but since all the pieces are in place to remove the IdP's dependency on it, I thought I would do that first.
Updating the IdP code will possibly allow us to remove this ValidationError, which is catching the edge case we've seen in the past where a request that is signed will have an X509 Certificate …
=> Remove dependency on saml_idp instance variable

app/javascript/packages/webauthn/enroll-webauthn-device.spec.ts, app/javascript/packages/webauthn/enroll-webauthn-device.ts, app/javascript/packs/webauthn-setup.ts
[LG-14327](https://cm-jira.usa.gov/browse/LG-14327)
Updates WebAuthn registration to avoid passing `hints` for platform authenticators.
This was introduced in LG-12571 (#10382), specifically aimed at improving the experience of registering security keys. While the hints provided for platform authenticators weren't intended or expected to have an impact, it was discovered that providing these hints can cause browsers to impose additional constraints for registration (see [related Slack discussion](https://gsa-tts.slack.com/archives/C01710KMYUB/p1724761159588019)). Specifically, Chrome on macOS prevents the user from registering their device if iCloud Keychain syncing is not available.
1. On a macOS device without iCloud Keychain (e.g. GFE), visit http://localhost:3000
2. Sign in
3. On …
=> LG-14327: Remove registration hints for Face or Touch Unlock

spec/presenters/two_factor_options_presenter_spec.rb
Removes a spec testing expected behavior for the `platform_auth_set_up_enabled` feature flag.
This feature flag was removed in #9485, but the tests were accidentally added back in #9532, likely due to merge conflict handling since they were merged around the same time.
=> Remove lingering reference to outdated F/T setup feature flag

app/controllers/idv/in_person/state_id_controller.rb, spec/controllers/idv/in_person/state_id_controller_spec.rb, spec/features/idv/steps/in_person/state_id_50_50_spec.rb
[LG-12377](https://cm-jira.usa.gov/browse/LG-12377)
This removes the before action that causes the State ID controller to show a 404 when the `in_person_state_id_controller_enabled` feature flag is turned off.
Both URLs work with the controller state enabled:
Disabling the controller variable to simulate 50/50 state:
Enabling the controller variable to simulate 50/50 state:
<details>
</details>
<details>
</details>
=> LG-12377 Remove 404 action for State ID Controller/FSM removal

.mocharc.js
Updates how we use [`quibble`](https://github.com/testdouble/quibble) for JavaScript module substitution in tests to avoid explicitly passing `loader` option to Mocha.
This resolves a warning that's logged when running tests, and will likely help avoid a future incompatibility when Node.js removes the `--loader` flag:
```
(node:34551) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("quibble", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
```
It's no longer necessary to pass the loader option in newer versions of Node.js, because Quibble ✨ automagically ✨ registers the …
=> Remove unnecessary quibble loader registration

app/components/phone_input_component.scss, app/javascript/packages/phone-input/index.spec.ts, app/javascript/packages/phone-input/index.ts, spec/components/previews/phone_input_component_preview.rb
Supports [LG-14382](https://cm-jira.usa.gov/browse/LG-14382)
Updates `PhoneInputComponent` to remove special consideration for a case where only a single country is supported, which would avoid rendering country list as a dropdown selector.
This was originally added in #5619, specifically for IdV phone verification step. At the time, we only accepted U.S. phone numbers for phone verification. This has since been expanded to support U.S. territories. Therefore, we don't currently use this functionality at all in the application.
These changes facilitate the work being done in #11257, where the single country variant does not work as expected after the upgrade.
Easier to review with whitespace changes hidden: https://github.com/18F/identity-idp/pull/11260/files?w=1
1. Go to …
=> Remove unused single country variant from phone input component

app/views/devise/sessions/new.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/views/devise/sessions/new.html.erb_spec.rb
[LG-14400](https://cm-jira.usa.gov/browse/LG-14400)
Adds a disclaimer text block in the sign in view that will show if recaptcha is enabled.
Checklist of steps to confirm the changes.
=> LG-14400 add recaptcha disclaimer text on sign-in

config/initializers/ab_tests.rb
The `RECAPTCHA_SIGN_IN` A/B test has a discriminator block that does the following:
1. Return `nil` if captcha was not performed
2. Return the user's UUID if the user is present
3. Return a random value if no user is present with the intent of sorting them into a bucket
The implementation of `AbTest#bucket` checks if the discriminator resolved by this discriminator block is blank and returns `nil` if it is ([ref](https://github.com/18F/identity-idp/blob/983e21648dc7695f11c37e3eff7997ef4bd90f1e/lib/ab_test.rb#L46)).
The `blank?` method has a special implementation for `String` ([ref](https://github.com/rails/rails/blob/dfd1e951aa1aeef06c39fffb2994db8a8fa1914f/activesupport/lib/active_support/core_ext/object/blank.rb#L141-L163)) that returns `true` if the string consists of only whitespace. …
=> Fix flaky `RECAPTCHA_SIGN_IN` A/B test

app/controllers/idv/in_person/usps_locations_controller.rb, app/javascript/packages/address-search/components/full-address-search-input.tsx, app/javascript/packages/address-search/components/full-address-search.spec.tsx, app/javascript/packages/address-search/hooks/use-validated-usps-locations.ts, app/services/usps_in_person_proofing/applicant.rb, spec/controllers/idv/in_person/usps_locations_controller_spec.rb
[LG-14071](https://cm-jira.usa.gov/browse/LG-14071)
Added client side character checking to PO search address field so that it aligns with other address field validations such as the ones associated with the state ID form. 
Also added a validation function server side in case someone disables JS and submits. (It will fail as it used to instead of showing the new unsupported characters message since this is not how users ~should~ be interacting with the form, but it's technically possible.)
(To see the dynamism of the error message you can also throw in a dollar sign and resubmit)
=> Add erroneous character checking to address search field

spec/controllers/idv/welcome_controller_spec.rb
The welcome controller had a test that checked that something matched a timestamp. This test failed when the clock advanced before we ran our expectation. This commit changes the test to expect the value to not change which is what we really intend to test.
=> Fix flaky spec on the welcome controller

app/services/proofing/resolution/result_adjudicator.rb, spec/features/idv/analytics_spec.rb, spec/jobs/socure_shadow_mode_proofing_job_spec.rb, spec/services/proofing/resolution/result_adjudicator_spec.rb
This commit removes the birth year from the logged biographical info in the proofing results. We are walking this back while we do some additional work with privacy to describe this.
=> Stop logging the year of birth in proofing results

app/javascript/packages/document-capture/components/document-capture.tsx, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/features/idv/doc_auth/document_capture_spec.rb
update capture heading to selfie step in for split doc auth
[LG-14392](https://cm-jira.usa.gov/browse/LG-14392)
Added selfie capture heading translations and added title to selfie step for split doc auth
<details>
</details>
<details>
</details>
=> LG-14392 Add doc_auth.headings.selfie_capture

app/controllers/concerns/idv/verify_info_concern.rb, app/controllers/idv/verify_info_controller.rb, app/services/analytics_events.rb, app/services/idv/session.rb, app/services/idv/steps/threat_metrix_step_helper.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/controllers/idv/otp_verification_controller_spec.rb, spec/controllers/idv/phone_errors_controller_spec.rb, spec/controllers/idv/ssn_controller_spec.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/support/flow_policy_helper.rb
[LG-14393](https://cm-jira.usa.gov/browse/LG-14393)
This PR updates the `preconditions` of `VerifyInfoController` (both remote + IPP variants) to require the presence of a `threatmetrix_session_id`. This is to work around a **rare** case where a user might end up on the verify info screen with no session id present. This is not an ideal fix, but rather an attempt to prevent a condition where a user will have no chance of passing identity verification.
1. Apply the patch below (hit copy, then `pbpaste | git apply`) to ensure no threatmetrix_session_id is written to your session
2. Go through IdV up to the SSN screen
3. When you click the **Continue** button, you should not see the Verify info screen, but rather the "Update your SSN" screen
4. Verify that …
=> LG-14393: Require threatmetrix_session_id for verify info step

app/models/anonymous_user.rb, app/services/account_reset/delete_account.rb, app/services/analytics_events.rb, spec/controllers/account_reset/delete_account_controller_spec.rb, spec/factories/users.rb
[LG-14100](https://cm-jira.usa.gov/browse/LG-14100)
Add Identity Verified details to 'Account Reset: delete' event.
Reduce wait time for Account Reset: delete by setting in your local application.yml
`account_reset_wait_period_days: 0`
identity_verified:
profile_idv_level: (if applicable)
=> LG-14100 Include identity-verified status in account reset delete event

lib/ab_test.rb
We are considering using a different hash algorithm for the `AbTest#bucket` method.  We expect a different hashing algorithm to give us better performance which could be a meaningful bump considering how much we call the `#bucket` method every request.
This commit lays some groundwork by adding method tracers to the impacted methods. This will allow us to assess the impact this change could have.
=> Add NewRelic method tracers to the AbTest bucket tooling

app/helpers/ipp_helper.rb, spec/helpers/ipp_helper_spec.rb
[LG-14492](https://cm-jira.usa.gov/browse/LG-14492)
Errors in NewRelic revealed that some USPS exceptions include a response body with a String instead of a hash, but we were assuming the body would be a hash in our method to scrub it for sponsor ID, causing the error `undefined method 'with_indifferent_access'  for instance of a String`.
This accepts a String and still ensures that it is scrubbed of a sponsor ID.
=> LG-14492 Accept a string in the ipp helper scrub method

app/services/proofing/aamva/proofer.rb, app/services/proofing/aamva/response/verification_response.rb, spec/fixtures/proofing/aamva/responses/verification_response_namespaced_success.xml, spec/services/proofing/aamva/request/verification_request_spec.rb, spec/services/proofing/aamva/response/verification_response_spec.rb, spec/services/proofing/aamva/verification_client_spec.rb
Supports work for [LG-14546](https://cm-jira.usa.gov/browse/LG-14546)
This PR:
* Removes the `Proofing::Aamva::Response::VerificationResponse#reasons` method, which did not appear to be referenced anywhere.
* Moves `Proofing::Aamva::Response::VerificationResponse#success?` to the `Proofer` class
The idea here is that the proofer should be responsible for determining whether something succeeded rather than the response.
=> Refactor + clean up AAMVA proofer

app/jobs/reports/duplicate_ssn_report.rb
- Follow-up, similar to #9818
I checked NewRelic and noticed that the Duplicate SSN report had timed out [(NewRelic link)](https://onenr.io/0KQXrBDG8Ra). Looks like the report has timed out often over the last few weeks.
=> Increase DB query timeout in Duplicate SSN Report

app/services/proofing/aamva/proofer.rb, spec/services/proofing/aamva/proofer_spec.rb
[LG-14546](https://cm-jira.usa.gov/browse/LG-14546)
Updates the AAMVA proofer to require that `state_id_expiration` be verified with AAMVA for a result to be considered successful.
This requirement is applied only when the expiration date is present.
=> LG-14546: Require AAMVA verification of expiration dates

app/controllers/concerns/idv/verify_info_concern.rb, app/services/analytics_events.rb, app/services/idv/analytics_events_enhancer.rb, spec/controllers/idv/in_person/verify_info_controller_spec.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/features/idv/analytics_spec.rb
We use Threatmetrix for device profiling. When a user's device profiling transaction represents a review or reject status they need to undergo the fraud review process. Part of that process is looking at what was returned by Threatmetrix in the logged response body.
The Threatmetrix response body is incredibly large. It causes some issues with Cloudwatch parsing the JSON written to the log.
This commit adds a new event to capture the Threatmetrix response body. The plan is to verify that this new event works for our fraud analysis purposes and then stop logging it on the existing event. The change to stop logging the response body on the existing event will be in a follow-up change.
=> LG-13462 Log the Threatmetrix response body in its own event

app/services/analytics_events.rb
[LG-14171](https://cm-jira.usa.gov/browse/LG-14171)
While it is intuitively obvious that liveness checking is required if the user is generating selfie events, creating a dashboard on CW will be much easier if we can filter all events by one parameter.
=> LG-14171: add liveness_checking_required to all selfie events

app/models/profile.rb, app/models/user.rb
See https://gitlab.login.gov/lg-people/Melba/backlog-fy24/-/issues/118
changelog: Internal, Refactoring, Move constant to appropriate owner
https://gitlab.login.gov/lg-people/Melba/backlog-fy24/-/issues/118
=> Move FACIAL_MATCH_IDV_LEVELS constant to Profile

app/javascript/packages/document-capture/components/_file-input.scss, app/javascript/packages/document-capture/components/documents-step.tsx, app/javascript/packages/document-capture/components/file-input.tsx, app/javascript/packages/document-capture/components/selfie-step.tsx, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/features/idv/doc_auth/document_capture_spec.rb, spec/javascript/packages/document-capture/components/documents-and-selfie-step-spec.tsx
visual and content changes for split doc auth capture pages
[LG-14169](https://cm-jira.usa.gov/browse/LG-14169)
Follow Up to PR: https://github.com/18F/identity-idp/pull/11245 that was merged in prematurely and reverted. 
Changed visuals and content to match Figma and AC listed in the ticket
=> LG-14169 visual and content changes to split doc auth

app/controllers/test/oidc_test_controller.rb, app/services/analytics_events.rb, app/services/saml_request_validator.rb, app/services/vot/supported_component_values.rb, app/views/accounts/_identity_verification.html.erb, app/views/test/oidc_test/index.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, docs/sdk-upgrade.md, spec/views/accounts/_identity_verification.html.erb_spec.rb
https://gitlab.login.gov/lg-people/Melba/backlog-fy24/-/issues/116
This change wraps up the rest of the language change from biometric_comparison to facial_match.
- fixes the OIDC test controller that is used for facial match testing
- updates another private method that somehow avoided discovery the first go around
-  Updates the yml/erb files
- Updates the analytics_events field descriptions
=> More renaming to Facial Matching

config/locales/telephony/fr.yml, config/locales/telephony/zh.yml, spec/i18n_spec.rb
[LG-14497](https://cm-jira.usa.gov/browse/LG-14497)
This PR contains a couple of updates identified by the LQA process:
1. Translate "digit" as "chiffres" in French in address verification OTP messages
2. Insert a missing full width comma in Simplified Chinese translation of the address verfication OTP message
=> LG-14497: LQA updates

config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
LG-14067 Implement new attempts language in attempts screen
[LG-14067](https://cm-jira.usa.gov/browse/LG-14067)
Updated text and translations for "out of attempts" screen during doc auth.
<details>
</details>
=> LG-14067 Implement new attempts language in attempts screen

spec/views/idv/how_to_verify/show.html.erb_spec.rb
[LG-14290](https://cm-jira.usa.gov/browse/LG-14290) Eng: Add step indicator component to Opt-in page (How to Verify)
- Update specs per review [here](https://github.com/18F/identity-idp/pull/11298#pullrequestreview-2348335219)
1. Removed parentheses used inside it description in spec file 
2. Update specs to make readable 
<details>
</details>
<details>
</details>
=> LG-14290- Add step indicator to How To Verify View - Fix Specs

config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/i18n_spec.rb
[LG-14398](https://cm-jira.usa.gov/browse/LG-14398)
Adds translations for the text "Email not yet selected".
This was implemented behind a feature flag in [LG-13665](https://cm-jira.usa.gov/browse/LG-13665) (#11196), but translations were not available for this particular string because it was not known to be needed until implementation had already started (see [related Slack discussion](https://gsa-tts.slack.com/archives/C05R6BLVAQG/p1725033025669399)), and the turnaround time for translations is long.
1. Prerequisite: Have a connection with a service provider ([documentation](https://github.com/18F/identity-idp/blob/main/docs/local-development.md#simulating-a-partner-authentication-request))
3. Sign in (if not already)
4. From account dashboard, go to …
=> LG-14398: Add translations for "Email not yet selected"

app/controllers/sign_up/select_email_controller.rb, spec/controllers/sign_up/select_email_controller_spec.rb
[LG-14389](https://cm-jira.usa.gov/browse/LG-14389)
Logs analytics events when the user visits and submits the email selection screen when prompted to consent to share information with a partner.
This leverages existing analytics events created for changing the selected email for a partner in [LG-13665](https://cm-jira.usa.gov/browse/LG-13665) (#11196), using the property `needs_completion_screen_reason` to differentiate if the email was changed stemming from the consent screen.
Prerequisites:
- If you've already consented for the OIDC sample application, sign in and revoke consent from the "Connected accounts" page of your account dashboard
- You must have multiple email addresses associated with your account
Validate that the expected events are logged:
1. Run `make watch_events` in a …
=> LG-14389: Add analytics for consent screen email selection

config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
Changed the alt text to "Photo taken. Submit photo"
[LG-14157](https://cm-jira.usa.gov/browse/LG-14157)
Update the alt text to "Photo taken. Submit photo" for the green checkmark button after a selfie is taken
=> Replace alt text on capture button with new alt text

app/services/analytics.rb, lib/saml_idp_constants.rb, spec/services/analytics_spec.rb
- Deter using the resolved ACRs directly in reporting. The resolved list of ACRs (or Vectors of Trust) is volatile and subject to relatively frequent change as service features are added, removed, or modified over time. Instead, most analytics users should use the resolved attribute flags (e.g., `facial_match` or `enhanced_ipp`) for event filtering. Going forward, the purpose of the `sp_request.component_values` field should be solely to support investigating unexpected behavior.
- Eliminate unexpected "reformatting" or "truncation" of resolved ACR names. While truncating these strings makes composing queries simpler, it introduces complexity and confusion when triaging and debugging requests. Originally, the purpose was to be able to do simple filters like …
=> Use a list to log resolved ACRs in events

app/javascript/packs/document-capture.tsx
[LG-14545](https://cm-jira.usa.gov/browse/LG-14545)
On the PO search page for the IPP flow, the `extendSession` callback was being called without a `sessionURL` being provided. This is due to the IPP flow being almost entirely in Ruby and not having a current session on the React side of things.
This change conditionally adds the `extendSession` callback only if the flow is not Opt In IPP.
This issue is also not happening in the Help Center so there is no separate ticket for that work as per the AC.
=> Fix 404 Error on PO Search Page for IPP Flow

app/models/email_address.rb, config/application.yml.default, lib/identity_config.rb, spec/controllers/users/two_factor_authentication_setup_controller_spec.rb, spec/features/sign_in/piv_recommended_after_sign_in_spec.rb, spec/features/users/sign_up_spec.rb, spec/models/email_address_spec.rb, spec/models/user_spec.rb
[LG-14397](https://cm-jira.usa.gov/browse/LG-14397)
=> LG-14397: Remove use_fed_domain_class

app/javascript/packs/document-capture.tsx, app/views/idv/shared/_document_capture.html.erb, spec/javascript/packages/document-capture/components/document-capture-spec.jsx
[LG-14545](https://cm-jira.usa.gov/browse/LG-14545)
This fixes a regression from https://github.com/18F/identity-idp/pull/10894 which added an argument to `extendSession`, but did not add it for the usage in document capture. https://github.com/18F/identity-idp/pull/11287 was a short-term fix, and this more fully addresses it by defining sessionsURL as we do for other URLs.
The regression is something that TypeScript could catch, but requires bigger changes.
=> Extend session when changing document capture steps

app/services/id_token_builder.rb, config/application.yml.default, spec/features/idv/doc_auth/document_capture_spec.rb, spec/features/idv/doc_auth/how_to_verify_spec.rb, spec/features/idv/doc_auth/hybrid_handoff_spec.rb, spec/features/idv/steps/in_person/state_id_50_50_spec.rb, spec/features/idv/steps/in_person_opt_in_ipp_spec.rb, spec/features/openid_connect/openid_connect_spec.rb, spec/features/reports/authorization_count_spec.rb, spec/services/id_token_builder_spec.rb, spec/support/features/idv_helper.rb, spec/support/idv_examples/sp_handoff.rb, spec/support/oidc_auth_helper.rb
This is part of a bigger effort to minimize our use of the vectors of trust API interface, so that we can ultimately deprecate it.
This change:
- updates our testing code to default to the new semantic facial match acr value when utilizing helpers.
- Adds the default issuer to the test application.yml.default. this is temporary, as on november 7th both facial match and the semantic acr values will be generally available
- fixes a bug where the id_token `acr` field was only returning legacy acr values. (the `id_token_builder_spec` is on my [list of spec files](https://docs.google.com/document/d/1zKDhHaOdH6Kyz2NivJSEZHnknkMLujYw2kbts2QAycY/edit) that need increased semantic acr value testing. )
=> Use semantic acr values as test default

spec/jobs/get_usps_proofing_results_job_spec.rb, spec/support/usps_ipp_helper.rb
[LG-14321](https://cm-jira.usa.gov/browse/LG-14321)
Refactored/Rewrote the `spec/jobs/get_usps_proofing_results_job_spec.rb` file
**Improvement Metrics:**
Test Coverage: 98.35% => 99.59%
Branch Coverage: 85.19% => 86.42%
Runtime: ~20 seconds => ~9 seconds
Examples: 129 => 181
**Additional Review Notes:**
It might be easier to review my PR looking at the first commit. I created a new file when I started this refactor. The last commit move the new changes to the old file name.
=> LG-14321 Refactor GetUspsProofingResultsJob tests

spec/controllers/idv/by_mail/resend_letter_controller_spec.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/controllers/idv_controller_spec.rb, spec/controllers/users/piv_cac_login_controller_spec.rb, spec/policies/pending_profile_policy_spec.rb, spec/presenters/account_show_presenter_spec.rb, spec/presenters/saml_requested_attributes_presenter_spec.rb, spec/services/attribute_asserter_spec.rb, spec/services/vot/parser_spec.rb, spec/views/accounts/_identity_verification.html.erb_spec.rb
[Expand acr values coverage](https://gitlab.login.gov/lg-people/Melba/backlog-fy24/-/issues/113)
As part of the Service Level initiative, we want to expand test coverage to include acr_values, both original and new semantic values.
This change expands test coverage in various spec files that were mostly testing using vtr values. 
-  makes acr_values the default test case (to make it easier to remove vtr test cases in the future)
- adds acr_values test cases
- includes semantic acr_values
=> Expand acr_values test coverage

app/controllers/concerns/idv/verify_info_concern.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/features/idv/analytics_spec.rb
We use Threatmetrix for device profiling. When a user's device profiling transaction represents a review or reject status they need to undergo the fraud review process. Part of that process is looking at what was returned by Threatmetrix in the logged response body.
The Threatmetrix response body is incredibly large. It causes some issues with Cloudwatch parsing the JSON written to the log.
In 2ddece00b322a3a38c577cbc172e831700200dd1 we started logging the response body on its own event. We continued to log the Threatmetrix response body in its original place on the verify info proofing results event. This was done so we can validate that the response body is properly logged on the new event and works for our purposes.
This commit follows up that previous commit by removing the response …
=> LG-14609 Stop logging Threatmetrix response body in verify info results

spec/services/attribute_asserter_spec.rb
I was working on a change that required some tests added to this spec file, and I got fed up with how it is structured, so I updated it to use a factory object rather than a double. This allowed me to hydrate the service provider with the correct data, rather than having to rely on stubs. The change ended up being out of scope of the other change, so I pulled it into its own branch for ease of review.
=> changelog: Internal, Tests, Updating some tests to be easier to read

spec/controllers/users/piv_cac_authentication_setup_controller_spec.rb
Refactoring related to [LG-14455](https://cm-jira.usa.gov/browse/LG-14455)
Updates specs for `Users::PivCacAuthenticationSetupController` to fix inaccuracies and follow conventions:
- Specs described `#index` where the controller has no `index` action, fixed to `#new`
- Specs used `describe` to prescribe contextual scenarios, updated to `context`
- Specs were written context-first, rather than action-first
Easier to review with whitespace changes hidden: https://github.com/18F/identity-idp/pull/11355/files?w=1
Example before/after:
```rb
describe 'when not signed in' do
describe '#index' do
it '...' do
end
end
end
describe 'when signed out' do
describe '#index' do
it '...' do
end
end
end
describe '#new' do
context 'when not signed in' do
it '...' do
end
end
context 'when signed out' do
it …
```
=> Restructure PIV/CAC setup spec for consistency

config/locales/zh.yml
In this PR, I'm requesting an engineer(s) to review.
[LG-14803](https://cm-jira.usa.gov/browse/LG-14803)
As part of Chinese (Simplified) quality assurance check, I am deleting the extra spacing in several instances that DOS is requesting to remove.
SBAR details in the [document](https://docs.google.com/document/d/12Xr2Zv1kqYlx7BN_SsBYZCdp5t9ILd0ojiYD_S9b5Q8/edit?usp=sharing).
Only extra spacing in certain instances are deleted. 
No characters, symbols, or punctuation marks are deleted.
=> Remove some spacing in zh.yml 

app/controllers/users/emails_controller.rb, app/views/users/emails/show.html.erb, config/locales/zh.yml, spec/controllers/idv/by_mail/resend_letter_controller_spec.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/controllers/idv_controller_spec.rb, spec/controllers/users/emails_controller_spec.rb, spec/controllers/users/piv_cac_login_controller_spec.rb, spec/policies/pending_profile_policy_spec.rb, spec/presenters/account_show_presenter_spec.rb, spec/presenters/saml_requested_attributes_presenter_spec.rb, spec/services/attribute_asserter_spec.rb, spec/services/vot/parser_spec.rb, spec/views/accounts/_identity_verification.html.erb_spec.rb
- In-person proofing: Update Chinese translation on How to Verify view for selfie ([#11344](https://github.com/18F/identity-idp/pull/11344))
- Partner account: Cancel adding email ([#11303](https://github.com/18F/identity-idp/pull/11303))
- Test Coverage: Making acr_values the default test case ([#11345](https://github.com/18F/identity-idp/pull/11345))
=> Deploy RC 423 to Prod

spec/features/idv/get_proofing_results_job_scenarios_spec.rb
[LG-14590](https://cm-jira.usa.gov/browse/LG-14590)
Added integration tests for password reset behavior before and after GetUspsProofingResultsJob runs.
=> LG-14590 Add GetProofingResultsJob password reset integration tests

app/controllers/idv/hybrid_mobile/entry_controller.rb, spec/controllers/idv/hybrid_mobile/entry_controller_spec.rb
Remove document capture session validation event
[LG-14514](https://cm-jira.usa.gov/browse/LG-14514)
Removing outdated doc auth event tracker.
=> lg-14514 Remove document capture session validation event

app/views/two_factor_authentication/options/no_option.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
Removes unused view code `two_factor_authentication/options/no_option`.
Added in #3839, last reference removed in #7063.
Confirm no lingering references to view.
=> Remove unused 2FA no_option route view

app/assets/stylesheets/variables/_email.scss, app/components/login_button_component.scss
[LG-14651](https://cm-jira.usa.gov/browse/LG-14651)
Someone pointed out in Slack that the hover states on the login-button were the same as the default state. This updates the component scss so that the hover state is visible and different.
PRIMARY
<details>
</details>
<details>
</details>
PRIMARY LIGHTER
<details>
</details>
<details>
</details>
PRIMARY DARKER
<details>
</details>
<details>
</details>
=> LG-14651: add different hover states to login-button component

app/views/idv/in_person/ready_to_verify/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/support/features/idv_step_helper.rb
[LG-14360](https://cm-jira.usa.gov/browse/LG-14360)
Move and update content on sign out link
With no Service Provider
English
Spanish
French
Chinese
No Service Provider
=> LG-14360: Update sign out link

app/jobs/reports/protocols_report.rb, lib/reporting/protocols_report.rb, spec/mailers/previews/report_mailer_preview.rb
Add facial match query to protocols report](https://gitlab.login.gov/lg-people/Melba/backlog-fy24/-/issues/123)
My first ticket related to these changes didn't include the new table in the emailable report method, so when the weekly email went out the feature usage table was not included.
This change:
- adds the table to the report
- adds the report to the [mailer previews](https://github.com/18F/identity-idp/blob/main/docs/local-development.md#email-template-previews) that can be accessed at `localhost:3000/rails/mailers` so it's easier to catch these kinds of issues.
=> Add feature usage table to Protocols Report

Gemfile.lock, app/jobs/good_job_v4_ready_job.rb, config/initializers/job_configurations.rb, db/worker_jobs_migrate/20241021192429_recreate_good_job_cron_indexes_with_conditional.rb, db/worker_jobs_migrate/20241021192430_create_good_job_labels.rb, db/worker_jobs_migrate/20241021192431_create_good_job_labels_index.rb, db/worker_jobs_migrate/20241021192432_remove_good_job_active_id_index.rb, db/worker_jobs_migrate/20241021192433_create_index_good_job_jobs_for_candidate_lookup.rb, db/worker_jobs_migrate/20241021192434_create_good_job_execution_error_backtrace.rb, db/worker_jobs_migrate/20241021192435_create_good_job_process_lock_ids.rb, db/worker_jobs_migrate/20241021192436_create_good_job_process_lock_indexes.rb, db/worker_jobs_migrate/20241021192437_create_good_job_execution_duration.rb, db/worker_jobs_schema.rb, spec/jobs/good_job_v4_ready_job_spec.rb
We're quite far behind on good_job versions, and a major version update was released back in July. The structure of jobs has changed, and we must complete all jobs scheduled or queued in the old format prior. This is described further in the [v3 to v4 update guide](https://github.com/bensheldon/good_job/tree/main?tab=readme-ov-file#upgrading-v3-to-v4).
=> Update good_job in preparation for 4.0 upgrade

config/application.yml.default, spec/lib/identity_config_spec.rb
Adds a test that requires all configuration to have a default value specified in the top-level of `application.yml.default`.
**Why?**
- So it's clearer by looking at `application.yml.default` all of the available configuration
- Adds missing values:
- `lexisnexis_threatmetrix_api_key`
- `lexisnexis_threatmetrix_base_url`
- `lexisnexis_threatmetrix_org_id`
- `lexisnexis_threatmetrix_policy`
- It complements the existing "redundant configuration" by ensuring a value exists in the default scope, particularly where previously two environments may have shared the same configuration, now collapsed to a single default value in the top-level scope
Previous discussion: https://github.com/18F/identity-idp/pull/11340#discussion_r1804852553
```
rspec spec/lib/identity_config_spec.rb
```
Review that …
=> Add test to require all config defined in application.yml.default

spec/features/multiple_emails/sp_sign_in_spec.rb, spec/support/features/session_helper.rb, spec/support/idv_examples/sp_handoff.rb, spec/support/oidc_auth_helper.rb
Supports [LG-14455](https://cm-jira.usa.gov/browse/LG-14455) (#11368)
Creates new common spec helpers for decoding OIDC tokens, refactoring existing specs to use them.
Specifically, these helpers can be used to help assert that specific information is shared with a partner after the user authenticates.
This helper is extracted from #11368, with revisions to distinguish decoded token vs. decoded `id_token`.
=> Extract common spec helpers for decoding OIDC tokens

.rubocop.yml, Gemfile, Gemfile.lock, app/models/event.rb, app/models/in_person_enrollment.rb, app/models/phone_configuration.rb, app/models/profile.rb, app/models/user.rb, app/services/access_token_verifier.rb, app/services/agency_identity_linker.rb, app/services/create_new_device_alert.rb, app/services/gpo_reminder_sender.rb, app/services/proofing/socure/reason_codes/importer.rb, app/services/usps_in_person_proofing/enrollment_helper.rb, lib/identity_cors.rb, lib/reporting/authentication_report.rb, lib/reporting/drop_off_report.rb, lib/reporting/mfa_report.rb, lib/reporting/protocols_report.rb, spec/jobs/in_person/send_proofing_notification_job_spec.rb, spec/services/agency_identity_linker_spec.rb, spec/services/funnel/registration/add_mfa_spec.rb, spec/support/ab_tests_helper.rb, spec/support/matchers/accessibility.rb
Updates `rubocop-rails` to the latest version and addresses identified issues.
In particular, this supports #11357, where Rails 7.2 will now noisily output deprecation messages for `enum` usage with keyword arguments, slated to be removed in Rails 8 (see https://github.com/rails/rails/pull/50987). Newer versions of `rubocop-rails` includes [a `Rails/EnumSyntax` cop](https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsenumsyntax) to help identify these.
Review relevant cops for changes to identify any incompatibilities with "Safety" notes from documentation:
https://docs.rubocop.org/rubocop-rails/cops_rails.html
=> Update rubocop-rails to lint deprecated enum keywords

app/javascript/packages/webauthn/verify-webauthn-device.spec.ts, app/javascript/packages/webauthn/verify-webauthn-device.ts
[LG-14325](https://cm-jira.usa.gov/browse/LG-14325)
This makes it so when a user is leveraging webauthn as an MFA, it should not have to prompt user to enter in another credential before accepting the MFA. 
When signing in with Security key and F/T Unlock, User should not be prompted to enter in PIN.
=> LG-14325: Change from default to discouraged for authentication

app/controllers/concerns/two_factor_authenticatable_methods.rb, app/controllers/two_factor_authentication/backup_code_verification_controller.rb, app/controllers/two_factor_authentication/otp_verification_controller.rb, app/controllers/two_factor_authentication/totp_verification_controller.rb, app/controllers/two_factor_authentication/webauthn_verification_controller.rb, spec/features/openid_connect/phishing_resistant_required_spec.rb, spec/features/saml/phishing_resistant_required_spec.rb
Supports [LG-14455](https://cm-jira.usa.gov/browse/LG-14455)
Removes a `before_action` check from MFA controllers to ensure that a user is only allowed to MFA with a phishing-resistant MFA or PIV/CAC if required by the partner.
These are not effective bypass checks, and are already considered as part of `confirm_two_factor_authenticated` for final authentication checks of [OIDC](https://github.com/18F/identity-idp/blob/da770f38fd02f062be98435ccc3ad4b21859c97e/app/controllers/openid_connect/authorization_controller.rb#L25) and [SAML](https://github.com/18F/identity-idp/blob/da770f38fd02f062be98435ccc3ad4b21859c97e/app/controllers/saml_idp_controller.rb#L30). Since weaker MFA options are excluded from the options listing when phishing-resistant or PIV/CAC is required from a partner, the …
=> Remove controller-level "bypass" check for SP MFA requirement

lib/identity_job_log_subscriber.rb, spec/lib/identity_job_log_subscriber_spec.rb
While working to troubleshoot some job queue alarms, we're hoping it is helpful to add some additional information around CPU and idle time for each job performed. This PR adds both `cpu_time` and `idle_time` to the default job event metrics: https://github.com/rails/rails/blob/fe0fb9fdf04f638996e785d3e291f5fe8bc138a0/activesupport/lib/active_support/notifications/instrumenter.rb#L161-L172
=> Add cpu_time and idle_time to job logs

app/controllers/openid_connect/authorization_controller.rb, app/controllers/saml_idp_controller.rb, app/services/analytics_events.rb, app/services/saml_request_validator.rb, app/services/vot/parser.rb, spec/controllers/application_controller_spec.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/forms/openid_connect_authorize_form_spec.rb, spec/services/attribute_asserter_spec.rb, spec/services/authn_context_resolver_spec.rb, spec/services/saml_request_validator_spec.rb, spec/services/vot/parser_spec.rb
[Ignore unknown authentication contexts](https://gitlab.login.gov/lg-people/Melba/backlog-fy24/-/issues/119)
[Link to 1-pager](https://docs.google.com/document/d/1PrKobld51OX3pZA1uklu9Rm3IHUkqrVJ-c0-z0aFSWc/edit#heading=h.x444b6dcc7j5)
This change updates our SAML integration to allow and ignore unknown authentication context class reference (ACR) values that are sent via the request, as long as there is at least one valid AuthnContext value that we can assert. (OIDC already allowed arbitrary values to be passed in.)
[SAML spec line 1820](http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf)
> If Comparison is set to "exact" or omitted, then the resulting authentication context in the authentication
statement MUST be the exact match of at least …
=> Ignore unknown authncontext

app/jobs/fraud_rejection_daily_job.rb, spec/jobs/fraud_rejection_daily_job_spec.rb
If a user is in fraud review for over 30 days they are automatically rejected by the `FraudRejectionDailyJob`. Prior to this commit the analytics service was initialized with an anonymous user. As a result the event was not logged for the fraud review rejected user. This commit fixes that issue so these events will appear associated with the rejected user.
=> Log the user of a fraud rejected profile on automatic rejection

spec/mailers/previews/user_mailer_preview.rb
We expect that most users who receive the `account_verified` email will have proofed with a service provider that has a `return_to_sp_url` and thus a `homepage_url`. This commit updates the mailer preview to replicate that situation so the email is displayed as expected.
=> Add a service provider with a homepage URL to account verified mailer preview

yarn.lock
Updates the browserslist `caniuse-lite` database dependency.
**Why?**
- More accurate usage data for browser support
- Resolve warning message when building:
```
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
```
**Impact**
Summary:
- Android Chrome: Minimum version increased from 123 to 129
- Chrome: Unchanged
- iOS (All browsers): Unchanged
- macOS Safari: Minimum version increased from 17.2 to 17.5
- Firefox: Minimum version increased from 122 to 129
Full difference of `browsers.json`:
Before:
```
["and_chr 123","and_uc 15.5","android 123","chrome 122","chrome 121","chrome 120","chrome 119","chrome 109","edge 122","edge 121","firefox 122","ios_saf 17.3","ios_saf …
```
=> Update browserslist database

app/controllers/application_controller.rb, app/controllers/concerns/two_factor_authenticatable_methods.rb, app/controllers/two_factor_authentication/options_controller.rb, app/controllers/two_factor_authentication/piv_cac_mismatch_controller.rb, app/controllers/two_factor_authentication/piv_cac_verification_controller.rb, app/controllers/users/piv_cac_authentication_setup_controller.rb, app/presenters/two_factor_authentication/sign_in_piv_cac_selection_presenter.rb, app/presenters/two_factor_login_options_presenter.rb, app/services/analytics_events.rb, app/views/two_factor_authentication/options/index.html.erb, app/views/two_factor_authentication/piv_cac_mismatch/show.html.erb, app/views/users/piv_cac_authentication_setup/new.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, config/routes.rb, spec/controllers/two_factor_authentication/piv_cac_mismatch_controller_spec.rb, spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb, spec/controllers/users/piv_cac_authentication_setup_controller_spec.rb, spec/factories/piv_cac_configurations.rb, spec/features/two_factor_authentication/piv_cac_sign_in_spec.rb, spec/features/two_factor_authentication/sign_in_spec.rb, spec/presenters/two_factor_authentication/sign_in_piv_cac_selection_presenter_spec.rb, spec/presenters/two_factor_login_options_presenter_spec.rb, spec/views/two_factor_authentication/options/index.html.erb_spec.rb, spec/views/two_factor_authentication/piv_cac_mismatch/show.html.erb_spec.rb, spec/views/users/piv_cac_authentication_setup/new.html.erb_spec.rb
[LG-14455](https://cm-jira.usa.gov/browse/LG-14455)
Implements a new workflow to help guide a user to adding a replacement PIV/CAC if they attempt to authenticate with a PIV which isn't the one associated with their account, such as if a user receives a new PIV/CAC card.
This is easiest to test using the simulated PIV/CAC service in local development, where you can create custom subject names for PIV/CAC to force a mismatch:
```
identity_pki_disabled: true
```
Verify that the PIV/CAC mismatch replacement workflow is shown under expected circumstances:
1. Have [sample application](https://github.com/18f/identity-oidc-sinatra) running in a separate process
3. Create an account with PIV/CAC as an authenticator. Optionally add another MFA, as this will affect …
=> LG-14455: Improved messaging for PIV/CAC mismatch

app/controllers/openid_connect/authorization_controller.rb, app/controllers/saml_idp_controller.rb, app/services/analytics_events.rb, app/services/saml_request_validator.rb, app/services/vot/parser.rb, spec/controllers/application_controller_spec.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/forms/openid_connect_authorize_form_spec.rb, spec/services/attribute_asserter_spec.rb, spec/services/authn_context_resolver_spec.rb, spec/services/saml_request_validator_spec.rb, spec/services/vot/parser_spec.rb
Reverts 18F/identity-idp#11362
There is some chance that this change is related to this error that Kevin is seeing on the staging SAML sample app (conversation here: https://gsa-tts.slack.com/archives/C0NGESUN5/p1729781695092109) -- I am prepping a revert so that if I don't figure it out in a timely fashion, we can continue with the deploy.
=> Revert "Ignore unknown authncontext"

app/controllers/openid_connect/authorization_controller.rb, app/controllers/saml_idp_controller.rb, app/services/analytics_events.rb, app/services/saml_request_validator.rb, app/services/vot/parser.rb, spec/controllers/application_controller_spec.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/forms/openid_connect_authorize_form_spec.rb, spec/services/attribute_asserter_spec.rb, spec/services/authn_context_resolver_spec.rb, spec/services/saml_request_validator_spec.rb, spec/services/vot/parser_spec.rb
This PR is reverting a revert (I was worried it was related to a problem with the sample SAML staging app, but looks like it is not the cause). The [original PR](https://github.com/18F/identity-idp/pull/11362) comment is copied below
>>
[Ignore unknown authentication contexts](https://gitlab.login.gov/lg-people/Melba/backlog-fy24/-/issues/119)
[Link to 1-pager](https://docs.google.com/document/d/1PrKobld51OX3pZA1uklu9Rm3IHUkqrVJ-c0-z0aFSWc/edit#heading=h.x444b6dcc7j5)
This change updates our SAML integration to allow and ignore unknown authentication context class reference (ACR) values that are sent via the request, as long as there is at least one valid AuthnContext value that we can assert. (OIDC already allowed arbitrary values to be passed in.)
[SAML spec …
=> Ignore unknown authncontext (#11362)

app/jobs/get_usps_proofing_results_job.rb, app/models/in_person_enrollment.rb, app/models/profile.rb, app/services/analytics_events.rb, spec/features/idv/get_proofing_results_job_scenarios_spec.rb, spec/jobs/get_usps_proofing_results_job_spec.rb, spec/models/in_person_enrollment_spec.rb, spec/models/profile_spec.rb
[LG-14591](https://cm-jira.usa.gov/browse/LG-14591)
Cancel enrollments that have profiles with a deactivation reason during the GetUspsProofingResultsJob. 
This PR also improves the `Profile.activate_after_passing_in_person` method by not allowing profiles with deactivation reasons or fraud pending reasons to be activated. Currently this method nils out `deactivation_reason`, fraud_review_pending_at, fraud_rejection_at, and fraud_pending_reason without any presence checks allowing profiles with fraud or deactivation reasons to become activated when calling the activate method. This will no longer be the case and the activate_after_passing_in_person will throw an error when the profile has a deactivation reason or reasons not to activate the profile (i.e. Fraud …
=> LG-14591 Cancel enrollments with deactivated profiles in proofing job

dockerfiles/application.yaml
At the moment the `LOGIN_ENV` variable that is set breaks the CSP check for the pivcac integration since it uses that to construct the idp's CSP settings. Switching this to `reviewapps` to fix.
=> Changing LOGIN_ENV to properly construct piv url

spec/controllers/users/two_factor_authentication_setup_controller_spec.rb
Supports [LG-14655](https://cm-jira.usa.gov/browse/LG-14655)
Refactors specs for `Users::TwoFactorAuthenticationSetupController#create`.
Specific improvements:
- Update `describe` description to follow conventions for controller action method names (`'PATCH create'` ➡️ `'#create'`)
- Remove duplicate assertions for expected analytics logging
- Avoid testing internal implementation details irrelevant for expected outcomes (asserting that form class is called)
- Reduce boilerplate, using combination of `subject` and `before` common setup
- Leverage [RSpec one-liner syntax](https://rspec.info/features/3-12/rspec-core/subject/one-liner-syntax/) to simplify redirect expectations
- Add test coverage for expected error message on invalid submission
This is split from the work of …
=> Refactor 2FA setup controller specs

lib/reporting/protocols_report.rb, spec/lib/reporting/protocols_report_spec.rb
[Add id_token_hint usage to weekly protocols report](https://gitlab.login.gov/lg-people/Melba/backlog-fy24/-/issues/129)
This change:
- Adds a row in the weekly protocols report to track id_token_hint usage
- Refactors some code to reduce duplication
=> Add id_token_hint usage tracking

app/jobs/get_usps_proofing_results_job.rb, app/models/in_person_enrollment.rb, app/services/usps_in_person_proofing/enrollment_helper.rb, spec/jobs/get_usps_proofing_results_job_spec.rb, spec/services/usps_in_person_proofing/enrollment_helper_spec.rb
This PR is a follow-up to [a conversation](https://docs.google.com/document/d/1xYSYHCU9k5oRQt_h93XtMDuevHpeSNECCORGAdWLh28/edit#bookmark=id.3tmqufqzuddp) we had 10/22/24 in Joy Engineering Huddle.  The instance method `usps_unique_id` was marked as deprecated in the `in_person_enrollment` model.  I did research and found PR #6883, which replaced the deprecated `usps_unique_id` method with the class method `set_unique_id`.  `usps_unique_id` used 18 characters from the in_person_enrollment's uuid, whereas `set_unique_id` randomly generates 18 characters.
As noted in [this github comment from 2022](https://github.com/18F/identity-idp/pull/6883#discussion_r963657507), it would have been safe to remove any references to `usps_unique_id` after letting the job run once to assign a unique ID to …
=> Delete deprecated code

app/forms/recaptcha_form.rb, app/services/analytics_events.rb, spec/features/phone/add_phone_spec.rb, spec/forms/recaptcha_enterprise_form_spec.rb, spec/forms/recaptcha_form_spec.rb, spec/forms/recaptcha_mock_form_spec.rb, spec/support/shared_examples/sign_in.rb
[LG-14887](https://cm-jira.usa.gov/browse/LG-14887)
Updates reCAPTCHA analytics logging to include the expected ["action" name](https://cloud.google.com/recaptcha/docs/actions-website), so that we can more clearly differentiate reCAPTCHA results between sign-in and phone setup.
1. In a separate terminal process, run `make watch_events`
2. Go to http://localhost:3000 in a private browsing window
3. Sign in to an account
4. In the `make watch_events` output, find the event for "reCAPTCHA verify result received", and observe the expected `properties.event_properties.recaptcha_action: 'sign_in'`
5. Optionally, repeat these same steps for the phone setup flow for international numbers, and verify the expected value of `phone_setup`
=> LG-14887: Log action name with reCAPTCHA assessment result received

app/jobs/reports/protocols_report.rb, spec/mailers/previews/report_mailer_preview.rb
Last week's update of the ProtocolsReport led to an [Argument Error](https://one.newrelic.com/nr1-core/errors-inbox/entity-inbox/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=43200000&state=87de4533-e030-dc27-4af6-da3c56c7144d) when the cron job attempted to run.
I'm not totally sure how the GoodJob cron jobs work, but I believe it's because I added an `initializer` method for the Mailer Preview feature, and that the report_date argument was being passed into that rather than the `perform` method. There may be a different way to solve this, but I wasn't sure how to test it.
=> changelog: Internal, Analytics, Fix weekly protocols report

docs/local-development.md
Adds documentation for how to use PIV/CAC in local development, since this is a core feature of the application yet is not explicitly documented for how to operate locally.
Reads through the revised documentation and verify that you are able to understand the instructions well enough to get up-and-running if you were unfamiliar with using PKI in local development.
=> Update local development documentation for working with PKI

Gemfile.lock
Updates `rexml` from `3.3.7` to `3.3.9`, to resolve a security advisory:
https://www.ruby-lang.org/en/news/2024/10/28/redos-rexml-cve-2024-49761/
Verify that build passes, and the application runs after `bundle install`.
=> Update rexml dependency

app/controllers/idv/phone_controller.rb, spec/features/idv/steps/in_person/verify_info_spec.rb
[LG-14031](https://cm-jira.usa.gov/browse/LG-14031)
Fixes missing success banner on phone page. The IPP verify info URL was not included as an acceptable referrer URL in the phone controller. This adds it.
https://github.com/user-attachments/assets/4ab5f09d-e134-43b4-9c89-371ad13b5bc1
=> LG-14031 Fix missing success banner on phone page

spec/support/fake_analytics_spec.rb, spec/support/have_logged_event_matcher.rb
Updates `have_logged_event` matcher to output an instructional error message if called without analytics being stubbed.
This would have saved me a few minutes of debugging a cryptic error message, not realizing that analytics hadn't already been stubbed in the context of the test I was writing.
Before:
```
Failure/Error:
(events[expected_event_name] || []).filter do |actual_attributes|
values_match?(expected_attributes, actual_attributes)
end
NoMethodError:
undefined method `[]' for nil
```
After:
```
Failure/Error:
expect(@analytics).to have_logged_event('Multi-Factor Authentication')
Matching expected logged events requires analytics to be stubbed.
Check that you've called `stub_analytics` before asserting `have_logged_event`.
```
Find a random spec calling …
=> Display instructions when asserting logged event without stubbing analytics

app/jobs/data_warehouse/table_summary_stats_export_job.rb, spec/jobs/data_warehouse/table_summary_stats_export_job_spec.rb
changelog: Internal, Reporting, naming improvements for table stats export
[LG-14548](https://cm-jira.usa.gov/browse/LG-14548)
Simple naming change to something that makes more sense for the application of the code from prior [PR-11386](https://github.com/18F/identity-idp/pull/11386)
=> LG-14548 Improve directory naming for table summary exports

app/controllers/users/reset_passwords_controller.rb, app/forms/reset_password_form.rb, app/services/analytics_events.rb, config/application.yml.default, config/initializers/ab_tests.rb, lib/identity_config.rb, spec/controllers/users/reset_passwords_controller_spec.rb, spec/forms/reset_password_form_spec.rb
Adds an event property indicating whether the password was the same as the user's current password when successfully resetting a user password.
This will be used to understand how common this behavior is, in case there's improvements we could make to this workflow, particularly for users who might be impacted by identity verification profile deactivation due to password reset.
Related Slack discussion: https://gsa-tts.slack.com/archives/C01710KMYUB/p1730231046429359
2. Create an account. Remember your password
3. Once you reach account dashboard, go to http://localhost:3000/verify
4. Complete identity verification
5. Sign out
6. Click "Forgot your password?
7. Submit the email address associated with your account
8. Click "Reset your password" in the email …
=> Log if password matches current for password reset event

app/javascript/packages/document-capture/components/file-input.tsx, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/features/idv/in_person_spec.rb, spec/javascript/packages/document-capture/components/file-input-spec.jsx
[LG-14592](https://cm-jira.usa.gov/browse/LG-14592)
Currently screen readers read "No file chosen" on the input even though a file is uploaded. The useEffect in FileInput suppresses the input value causing 
=> Fix error in screenreader by removing the useEffect that sets the file input value to null

Gemfile, Gemfile.lock
This makes an update to a couple of dependencies (and their dependencies) to include some performance updates in the new versions.
=> Update premailer and zxcvbn dependencies

Gemfile.lock, app/controllers/idv/phone_controller.rb, app/controllers/socure_webhook_controller.rb, app/jobs/reports/protocols_report.rb, app/jobs/socure_docv_results_job.rb, app/services/doc_auth/socure/requests/docv_result_request.rb, app/services/doc_auth/socure/responses/docv_result_response.rb, db/primary_migrate/20241029152408_index_socure_doc_v_transaction_token.rb, db/schema.rb, docs/local-development.md, spec/controllers/socure_webhook_controller_spec.rb, spec/features/idv/steps/in_person/verify_info_spec.rb, spec/jobs/socure_docv_results_job_spec.rb, spec/mailers/previews/report_mailer_preview.rb, spec/support/fake_analytics_spec.rb, spec/support/have_logged_event_matcher.rb
- In-person proofing: Fix missing success banner on phone page ([#11412](https://github.com/18F/identity-idp/pull/11412))
- Analytics: Fix weekly protocols report ([#11406](https://github.com/18F/identity-idp/pull/11406))
- Automated Testing: Improve documentation ([#11417](https://github.com/18F/identity-idp/pull/11417))
- Automated Testing: Improve error message when asserting logged event without stubbing analytics ([#11414](https://github.com/18F/identity-idp/pull/11414))
- Dependencies: Update dependencies to resolve security advisory ([#11409](https://github.com/18F/identity-idp/pull/11409))
- Documentation: Update local development documentation for working with PKI ([#11408](https://github.com/18F/identity-idp/pull/11408))
- Identity Verification: Fetch document capture results …
=> Deploy RC 427 to Production

app/controllers/accounts/connected_accounts/selected_email_controller.rb, app/views/accounts/_connected_app.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/controllers/accounts/connected_accounts/selected_email_controller_spec.rb, spec/features/account_connected_apps_spec.rb
[LG-14691](https://cm-jira.usa.gov/browse/LG-14691)
Whenever the email shared with a partner is changed, show a flash message next to the connected account indicating that the email was (recently) successfully changed.
<details>
</details>
<details>
</details>
=> LG-14691: Display flash message on successful email update

app/assets/stylesheets/components/_btn.scss, app/assets/stylesheets/email.css.scss, app/javascript/packages/clipboard-button/package.json, app/javascript/packages/tooltip/package.json, package.json, yarn.lock
Updates the Login.gov Design System (`@18f/identity-design-system`) from v9.3.0 to v9.4.0
See changelog: TBD
1. Install new dependencies with `yarn install`
2. Run application with `make run`
3. Verify no compilation errors and no visual regressions when browsing at http://localhost:3000
One noticeable difference will be alignment of icons in error message for multi-line field errors.
Before|After
---|---
=> Update Login.gov Design System from v9.3.0 to v9.4.0

app/assets/stylesheets/tables-report.css.scss, app/views/report_mailer/tables_report.html.erb
[LG-14431](https://cm-jira.usa.gov/browse/LG-14431)
Updated The text and background colors of report tables sent as HTML emails.
Reports can be previewed locally at [http://localhost:3000/rails/mailers/report_mailer](http://localhost:3000/rails/mailers/report_mailer) 
<details>
</details>
<details>
</details>
=> LG-14431 update email report table colors

app/services/proofing/resolution/plugins/aamva_plugin.rb, app/services/proofing/resolution/progressive_proofer.rb, lib/aamva_test.rb, spec/services/proofing/resolution/plugins/aamva_plugin_spec.rb, spec/services/proofing/resolution/progressive_proofer_spec.rb
Continuing the work in #11420, this PR extracts `proof_id_with_aamva_if_needed` into `AamvaPlugin`. It then adds a spec for the plugin covering the following use cases:
* Remote unsupervised proofing
* In-person proofing (residential address == id address)
* In-person proofing (residential address != id address)
=> ProgressiveProofer refactor 2/N: AAMVA

app/javascript/packages/document-capture/components/file-input.tsx, app/javascript/packages/eslint-plugin/CHANGELOG.md, app/javascript/packages/eslint-plugin/configs/recommended.js, app/javascript/packages/eslint-plugin/package.json, docs/frontend.md, yarn.lock
Updates ESLint configuration to integrate relevant rules from the Airbnb ESLint configurations `eslint-config-airbnb` and `eslint-config-airbnb-base`.
**Why?**
- Incremental step toward migrating to [ESLint 9](https://eslint.org/docs/latest/use/migrate-to-9.0.0) ([updated configuration syntax not supported by Airbnb shared configurations](https://github.com/airbnb/javascript/issues/2804))
- More explicit control over rules relevant to our projects
- No longer need to disable stylistic rules for Prettier compatibility
- Avoid unnecessary configuration for tools and practices not relevant to our projects (e.g. in the course of this exercise, I discovered that Airbnb includes a number of configuration for React component classes, and other tools like Vue.js)
- Shallower dependency tree, …
=> Integrate and remove dependency on Airbnb ESLint rules

app/mailers/user_mailer.rb, spec/mailers/previews/anonymous_mailer_preview_spec.rb, spec/mailers/previews/report_mailer_preview.rb, spec/mailers/previews/report_mailer_preview_spec.rb, spec/mailers/previews/user_mailer_preview_spec.rb, spec/support/shared_examples/mailer_preview.rb
Creates RSpec shared examples to be used for mailer previews, to ensure consistency for how these mailers are tested.
Example issues this would catch:
- Existing issue where there is no preview for `ReportMailer#deleted_user_accounts_report` because the report mailer specs did not check that all mailer methods have a corresponding preview
- [Potential issue of introducing SVG images to mailer](https://github.com/18F/identity-idp/pull/11444/files/27237bb478e6b5d511aa5383f623a9660a02391e..9197b5d102fa597e69c1d79c1c27bcbc42e5b7fa#r1826182517) because we were only testing user mailers for SVG images
Ensure no regressions of mailers: http://localhost:3000/rails/mailers/
=> Use shared examples for mailer preview specs

app/assets/stylesheets/tables-report.css.scss, app/views/report_mailer/tables_report.html.erb
[LG-14793](https://cm-jira.usa.gov/browse/LG-14793)
Adds Login.gov logo before the report and separators around the data to better brand the emails to Login.gov.
Before
After
=> Add the login.gov logo and the separator bars

app/services/analytics.rb, lib/action_account.rb, spec/lib/action_account_spec.rb, spec/services/analytics_spec.rb
[LG-14673](https://cm-jira.usa.gov/browse/LG-14673)
When an operator executes the `review-pass` or `review-reject` scripts, they log an analytics event. This PR updates those analytics events to be attributed to the SP that was associated with the initial profile creation.
=> LG-14673: Add SP info to fraud review events

app/services/proofing/mock/resolution_mock_client.rb, app/services/proofing/socure/id_plus/proofer.rb, spec/jobs/socure_shadow_mode_proofing_job_spec.rb, spec/services/idv/agent_spec.rb, spec/services/proofing/mock/resolution_mock_client_spec.rb, spec/services/proofing/socure/id_plus/proofer_spec.rb
[LG-14717](https://cm-jira.usa.gov/browse/LG-14717)
Updates `SocureShadowModeProofingJob` to log reason code descriptions (now that we have them available thanks to #11350) along with the codes themselves. This will hopefully make the job of checking these logs to verify things are functioning correctly a little easier.
Right now the intention is for this verbose logging to be in place for the relatively short shadow mode test period. Whether or not we continue this when we move fully into prod will depend on whether we find it useful.
1. Set the `idv_socure_reason_code_download_enabled`, `socure_reason_code_api_key`, and `socure_reason_code_base_url` configs in your application.yml
2. From the rails console …
=> LG-14717: Log Socure reason code descriptions

config/locales/es.yml
[LG-14888](https://cm-jira.usa.gov/browse/LG-14888)
Updates a few translations based on feedback from translators.
Verify updated text for reCAPTCHA disclosure in Spanish:
Prerequisite: Configure real reCAPTCHA in local development. Any credentials work, they don't need to be valid:
```yaml
development:
recaptcha_site_key: 'test'
recaptcha_enterprise_api_key: 'test'
recaptcha_enterprise_project_id: 'test'
recaptcha_mock_validator: false
sign_in_recaptcha_score_threshold: 0.3
sign_in_recaptcha_percent_tested: 100
```
1. Go to http://localhost:3000/es/
2. See updated translations
Verify updated text for "Email not selected" in Spanish:
2. Sign in
3. From account page, go to "Your connected accounts"
4. If you don't have any connected accounts, run and sign in …
=> LG-14888: Update Spanish strings for LQA feedback

app/services/proofing/resolution/plugins/instant_verify_residential_address_plugin.rb, app/services/proofing/resolution/progressive_proofer.rb, spec/jobs/resolution_proofing_job_spec.rb, spec/services/proofing/resolution/plugins/instant_verify_residential_address_plugin_spec.rb, spec/services/proofing/resolution/progressive_proofer_spec.rb
Continuing the work in #11420 and #11427, this PR extracts `proof_residential_address_if_needed` into `InstantVerifyResidentialAddressPlugin`. It then adds a spec for the plugin covering the following use cases:
* Remote unsupervised proofing
* In-person proofing (residential address == id address)
* In-person proofing (residential address != id address)
=> ProgressiveProofer refactor 3/N: Instant Verify residential address

app/services/proofing/resolution/plugins/aamva_plugin.rb, app/services/proofing/resolution/plugins/instant_verify_state_id_address_plugin.rb, app/services/proofing/resolution/progressive_proofer.rb, spec/services/proofing/resolution/plugins/aamva_plugin_spec.rb, spec/services/proofing/resolution/plugins/instant_verify_state_id_address_plugin_spec.rb, spec/services/proofing/resolution/progressive_proofer_spec.rb
Continuing the work in #11420, #11427, and #11433 this PR extracts `proof_id_address_with_lexis_nexis_if_needed` into `InstantVerifyStateIdAddressPlugin`. It then adds a spec for the plugin covering the following use cases:
* Remote unsupervised proofing
* In-person proofing (residential address == id address)
* In-person proofing (residential address != id address)
It then cleans up some tests in the `ProgressiveProofer` spec that are now covered by individual plugin specs.
=> ProgressiveProofer refactor 4/N: InstantVerify state id address

app/javascript/packages/analytics/index.ts, app/javascript/packages/captcha-submit-button/captcha-submit-button-element.spec.ts, app/javascript/packages/captcha-submit-button/captcha-submit-button-element.ts
Improves the behavior of reCAPTCHA submit buttons to ensure that a misconfigured reCAPTCHA environment does not prevent form submission.
Ideally this should never happen, since we would configure an environment correctly, but this adds additional resilience to handle if it were misconfigured. Prior to these changes, it'd be very hard to tell that there was an issue, because we would not receive events corresponding to the submission.
Validate that if reCAPTCHA is misconfigured, you're still able to sign in.
Configure reCAPTCHA in a way that uses invalid credentials:
```
development:
recaptcha_site_key: 'test'
recaptcha_enterprise_api_key: 'test'
recaptcha_enterprise_project_id: 'test'
recaptcha_mock_validator: false
sign_in_recaptcha_score_threshold: 0.3
sign_in_recaptcha_percent_tested: …
```
=> Add error handling for failed reCAPTCHA execute

app/controllers/accounts_controller.rb, app/controllers/users/email_confirmations_controller.rb, app/controllers/users/emails_controller.rb, app/forms/add_user_email_form.rb, app/mailers/user_mailer.rb, app/services/send_add_email_confirmation.rb, app/views/accounts/connected_accounts/selected_email/edit.html.erb, app/views/sign_up/completions/show.html.erb, app/views/sign_up/select_email/show.html.erb, app/views/users/emails/show.html.erb, app/views/users/emails/verify.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/controllers/accounts_controller_spec.rb, spec/controllers/users/email_confirmations_controller_spec.rb, spec/mailers/user_mailer_spec.rb, spec/views/users/emails/verify.html.erb_spec.rb
[LG-14692](https://cm-jira.usa.gov/browse/LG-14692)
Update Banner message when confirming email to notify users they can update their email for connected accounts. 
1. Create Account 
2. Add new email to existing account
3. verify the new content
=> LG-14692: Banner message for selected email confirmation

app/controllers/users/sessions_controller.rb, app/services/analytics_events.rb, spec/controllers/users/sessions_controller_spec.rb
Updates sign-in analytics properties to include properties from `SignInRecaptchaForm#to_h`, notably `error_details`.
**Why?**
- So that we can attribute failure reasons when a reCAPTCHA response isn't received due to form-specific validations like [token presence](https://github.com/18F/identity-idp/blob/2ef75e5135b85b009745b1ce14e374c4ac1c91a4/app/forms/recaptcha_form.rb#L17)
- As an incremental step toward refactoring 'Email and Password Authentication' to include conventional `FormResponse` success and error details
- For phone setup, we [merge the reCAPTCHA result](https://github.com/18F/identity-idp/blob/2ef75e5135b85b009745b1ce14e374c4ac1c91a4/app/forms/new_phone_form.rb#L133-L138) into the phone setup errors to ensure its errors are included in the corresponding "Multi-Factor …
=> Include FormResponse error details for reCAPTCHA at sign-in

app/jobs/data_warehouse/daily_sensitive_column_job.rb, config/application.yml.default, lib/identity_config.rb, spec/jobs/data_warehouse/daily_sensitive_column_report_spec.rb
changelog: Internal, Reporting, Update S3 config
[LG-14425](https://cm-jira.usa.gov/browse/LG-14425)
We discovered the bucket name would need to be shortened to prevent the bucket_name_length error in environments with long last names.
=> LG-14425: update s3 bucket name

app/controllers/idv/hybrid_mobile/socure/document_capture_controller.rb, app/services/doc_auth/socure/request.rb, app/services/doc_auth/socure/requests/document_request.rb, app/services/doc_auth/socure/requests/docv_result_request.rb, app/services/doc_auth/socure/responses/docv_result_response.rb, spec/controllers/idv/hybrid_mobile/socure/document_capture_controller_spec.rb, spec/controllers/idv/socure/document_capture_controller_spec.rb, spec/services/doc_auth/socure/request_spec.rb, spec/services/doc_auth/socure/requests/document_request_spec.rb, spec/services/doc_auth/socure/requests/docv_result_request_spec.rb
[LG-14790](https://cm-jira.usa.gov/browse/LG-14790)
Implemented handle_connection_error for socure requests
=> lg-14790 handle network failures for socure

app/controllers/concerns/idv/document_capture_concern.rb, app/controllers/idv/document_capture_controller.rb, app/controllers/idv/hybrid_mobile/document_capture_controller.rb, app/controllers/idv/hybrid_mobile/socure/document_capture_controller.rb, app/controllers/idv/socure/document_capture_controller.rb, spec/controllers/idv/document_capture_controller_spec.rb, spec/controllers/idv/hybrid_mobile/document_capture_controller_spec.rb, spec/controllers/idv/hybrid_mobile/socure/document_capture_controller_spec.rb, spec/controllers/idv/socure/document_capture_controller_spec.rb, spec/features/idv/hybrid_mobile/entry_spec.rb, spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb
[LG-14658](https://cm-jira.usa.gov/browse/LG-14658)
Added a before action to all of the document capture controllers to make sure the user stays in their assigned vendor bucket. i.e., if we send them to Socure, they can't use LN by manually entering the Socure document capture URL, and vice-versa.
** IN PROGRESS **
Bring up the app running locally, with access from your phone via WiFi
`HOST=0.0.0.0 make run`
The two relevant `application.yml` values to use LN are:
```
doc_auth_vendor: 'lexis_nexis'
doc_auth_vendor_default: 'lexis_nexis'
```
The two relevant `application.yml` values to use Socure are:
```
doc_auth_vendor: 'lexis_socure'
doc_auth_vendor_default: 'lexis_socure'
```
=> Add `ensure_user_stays_in_vendor_bucket` to all the controllers.

app/controllers/concerns/unconfirmed_user_concern.rb, app/controllers/sign_up/email_confirmations_controller.rb, spec/controllers/sign_up/passwords_controller_spec.rb, spec/features/visitors/email_confirmation_spec.rb, spec/support/analytics_helper.rb
Fixes an issue where we currently log the 'User Registration: Email Confirmation' event twice for every account registration.
Email confirmation happens across two controllers, which each individually validate the incoming confirmation token. Since the analytics were logged as part of this shared validation, it was being logged twice.
The solution is to move the analytics logging to happen only after the first successful validation.
Verify you see a single 'User Registration: Email Confirmation' event when confirming an email address for a new account:
1. Run `make watch_events` in a separate terminal process
3. Click "Create an account"
4. Enter an email address
5. Confirm Rules of Use
6. Click "Submit"
7. In the email received, click "Confirm email …
=> Fix duplicate logging for successful email confirmation

app/controllers/concerns/unconfirmed_user_concern.rb, app/controllers/sign_up/passwords_controller.rb, spec/controllers/sign_up/passwords_controller_spec.rb
Updates shared code for email confirmation token to only be called as needed.
As mentioned in #11466, email confirmation happens across two controllers, which each individually validate the incoming confirmation token. Prior to these changes, the validation included a few things performed in _both_ the initial email confirmation, as well as the password setup screen:
- Assigning forbidden passwords instance variable
- Flashing a success message
Since these are only relevant for the display of the password setup screen, the changes here move the code into the password setup controller.
Verify no regressions of expected behavior:
3. Enter the email address `examplelongemailaddress@example.com`
4. Confirm Rules of Use
5. Click …
=> Extract password view setup behaviors from shared email confirmation behavior

app/javascript/packs/mock-device-profiling.tsx, app/views/sign_up/registrations/new.html.erb, spec/features/account_creation/threat_metrix_spec.rb, spec/support/features/session_helper.rb
[LG-14863](https://cm-jira.usa.gov/browse/LG-14863)
Adds a new widget to control result of ThreatMetrix result in account creation flow when mock proofer is enabled.
Repeat Testing Plan from #11340, but select a device profiling result from the "Create an account" page.
Verify that the `account_creation_tmx_result` analytics event includes the expected result.
e.g. with "Reject" selected:
```rb
{
"name": "account_creation_tmx_result",
"properties": {
"event_properties": {
"success": true,
"errors": {
"review_status": [
"reject"
]
},
},
},
}
```
Before|After
---|---
=> LG-14863: Add UI to simulate account creation ThreatMetrix result

config/locales/zh.yml
[LG-14703](https://cm-jira.usa.gov/browse/LG-14703)
s/为了你的安全/出于安全考虑/g per DOS LQA
changelog: Bug Fixes, Translations, Updates Simplified Chinese strings
I am leaving these as comments inline so they're with the context of where the change occurred. It's otherwise not obvious where these changes are. More to do tomorrow.
=> LG-14703 | Update Chinese translations

app/presenters/idv/in_person/ready_to_verify_presenter.rb, app/presenters/idv/in_person/verification_results_email_presenter.rb, config/locales/es.yml, config/locales/zh.yml, spec/i18n_spec.rb, spec/presenters/idv/in_person/ready_to_verify_presenter_spec.rb, spec/presenters/idv/in_person/verification_results_email_presenter_spec.rb
changelog: User-Facing Improvements, In-person proofing, Fix barcode page due date format for Spanish, French, and Chinese translations; Improve Spanish translation for information alert.
[LG-14049](https://cm-jira.usa.gov/browse/LG-14049)
Fixed barcode page due date format for Spanish (\<day\> de \<month\> de \<year\>), French (\<day\> \<month\> \<year\>), and Chinese (\<year\>年\<month\>]月\<day\>日) translations; Improved the Spanish translation for the information alert.
Note: This PR fixes the time.formats.event_date translation and will update other areas of the code found in the Other Areas of the screenshots section.
<details>
<summary>EIPP Ready to Verify Page</summary>
</details>
<details> …
=> LG-14049 Fix barcode info alert dates and content

app/controllers/idv/hybrid_mobile/socure/document_capture_controller.rb, app/controllers/idv/socure/document_capture_controller.rb, spec/controllers/idv/hybrid_mobile/socure/document_capture_controller_spec.rb, spec/controllers/idv/socure/document_capture_controller_spec.rb
[LG-14835](https://cm-jira.usa.gov/browse/LG-14835)
Set capture app url in document capture sessions table. Added rspec tests for functionality
=> Lg 14835 set capture app url

app/controllers/idv/hybrid_mobile/socure/document_capture_controller.rb, app/services/doc_auth/socure/request.rb, app/services/doc_auth/socure/requests/document_request.rb, app/services/doc_auth/socure/requests/docv_result_request.rb, app/services/doc_auth/socure/responses/docv_result_response.rb, spec/controllers/idv/hybrid_mobile/socure/document_capture_controller_spec.rb, spec/controllers/idv/socure/document_capture_controller_spec.rb, spec/services/doc_auth/socure/request_spec.rb, spec/services/doc_auth/socure/requests/document_request_spec.rb, spec/services/doc_auth/socure/requests/docv_result_request_spec.rb
[LG-14790](https://cm-jira.usa.gov/browse/LG-14790)
Implemented handle_connection_error for socure requests.
Follow Up PR after reverting [1st PR](https://github.com/18F/identity-idp/pull/11430)
=> Lg 14790 handle network failures for socure

app/assets/stylesheets/email.css.scss
Removes a handful of styles from the email mailer stylesheet which are currently unused.
- Last reference to `.legal` and `.footer` removed in #2703
- Last reference to `.mr-tiny` removed in #1279
Verify no regressions in mailer templates visual appearance.
http://localhost:3000/rails/mailers/
=> Remove unused email styles

config/locales/es.yml
Follow-up revision for [LG-14888](https://cm-jira.usa.gov/browse/LG-14888) (originally implemented in #11448)
Updates Spanish translations for reCAPTCHA disclaimer text to move "la" and "las" outside the link text, per feedback from translators.
Verify updated text for reCAPTCHA disclosure in Spanish:
Prerequisite: Configure real reCAPTCHA in local development. Any credentials work, they don't need to be valid:
```yaml
development:
recaptcha_site_key: 'test'
recaptcha_enterprise_api_key: 'test'
recaptcha_enterprise_project_id: 'test'
recaptcha_mock_validator: false
sign_in_recaptcha_score_threshold: 0.3
sign_in_recaptcha_percent_tested: 100
```
1. Go to http://localhost:3000/es/
2. See updated translations
Before|After
---|---
=> LG-14888: Update Spanish reCAPTCHA strings link text

app/assets/stylesheets/components/_btn.scss, app/javascript/packages/spinner-button/spinner-button-element.spec.ts, app/javascript/packages/spinner-button/spinner-button-element.ts, app/javascript/packages/submit-button/submit-button-element.spec.ts, app/javascript/packages/submit-button/submit-button-element.ts, app/javascript/packages/webauthn/webauthn-verify-button-element.spec.ts, app/javascript/packages/webauthn/webauthn-verify-button-element.ts, package.json, yarn.lock
[LG-14754](https://cm-jira.usa.gov/browse/LG-14754)
Updates the behavior of submit buttons to avoid disabling the button using `disabled` attribute, instead using a combination of `aria-disabled` and event handlers to prevent duplicate submission when the button is already activated.
This fixes an issue where focus loss can occur if the page's submit button is the active element when submitting the form. While this is usually not a problem because it's expected that the user will be navigated away after submitting the form, this can cause issues in some screen readers which announce the loss of focus (e.g. JAWS announcing "Unavailable").
Verify that focus is maintained when submitting a form, and that you cannot submit twice:
`SpinnerButtonComponent`:
Apply diff to force a pause in …
=> LG-14754: Avoid focus loss on submit button when submitting form

app/controllers/socure_webhook_controller.rb, app/services/analytics_events.rb, spec/controllers/socure_webhook_controller_spec.rb, spec/factories/document_capture_sessions.rb
[LG-14905](https://cm-jira.usa.gov/browse/LG-14905)
* add docv_transaction_token to webhook analytics events
* correct user_id in webhook analytics event to use the user's uuid
- complete Socure DocV and verify docVTransactionToken and user_id in event logs
=> LG-14905: socure webhook analytics event updates

.rubocop.yml, app/views/sign_up/select_email/show.html.erb, lib/linters/i18n_helper_html_linter.rb, spec/lib/linters/i18n_helper_html_linter_spec.rb, spec/views/accounts/connected_accounts/selected_email/edit.html.erb_spec.rb, spec/views/sign_up/select_email/show.html.erb_spec.rb
Fixes an issue where partner email selection text was showing as escaped HTML.
The content was recently updated in #11468 to add HTML, and while the string key is correctly suffixed with `_html`, one of two views uses `I18n.t` instead of `t`, which does not perform automatic unescaping ([docs](https://guides.rubyonrails.org/i18n.html#using-safe-html-translations:~:text=Automatic%20conversion%20to%20HTML%20safe%20translate%20text%20is%20only%20available%20from%20the%20translate%20(or%20t)%20helper%20method.%20This%20works%20in%20views%20and%20controllers.)).
Verify the text does not show escaped HTML:
1. Run [sample application](https://github.com/18f/identity-oidc-sinatra) in parallel to IdP
2. Prerequisite: If you've already consented with partner application, sign in and revoke consent …
=> Fix HTML escaping for partner email sharing

Makefile, scripts/yaml_characters
Updates our [font optimizer](https://github.com/18F/identity-idp/blob/main/docs/frontend.md#fonts) tooling to disregard strings used for either telephony or user mailer emails. Since these are used in contexts which do not load the affected web fonts, they shouldn't be considered.
Currently this has no net effect on the characters being used, but this would have prevented a lot of developer toil in #11203 (see [related discussion](https://github.com/18F/identity-idp/pull/11203#discussion_r1745866051)). The hope is that these changes can limit the frequency of needing to regenerate font files.
Verify that `make lint_font_glyphs` succeeds.
=> Improve font optimizer to exclude telephony, mailer strings

app/forms/frontend_error_form.rb, app/javascript/packages/analytics/README.md, app/javascript/packages/analytics/index.spec.ts, app/javascript/packages/analytics/index.ts, app/javascript/packages/captcha-submit-button/captcha-submit-button-element.ts, app/javascript/packages/webauthn/webauthn-verify-button-element.ts, app/javascript/packs/track-errors.ts, app/javascript/packs/webauthn-setup.ts, app/services/frontend_error_logger.rb, docs/frontend.md, spec/controllers/frontend_log_controller_spec.rb, spec/forms/frontend_error_form_spec.rb, spec/services/frontend_error_logger_spec.rb
Updates frontend error logging through `trackError` to require an identifier label.
This fixes an issue where explicit calls to `trackError` are currently not surfaced in error logging, due to changes in #8950 to filter out errors originating in scripts outside our own code. An unintended side-effect of this change is that we were ignoring our own errors.
Including an `errorId` serves a dual purpose of guaranteeing that the error originates in our own code, while also providing an easy way to trace the source of the error.
Verify that an error would be tracked to NewRelic for an error logged through `trackError`.
1. Add a `binding.pry` immediately before the call to `NewRelic::Agent.notice_error` in `FrontendErrorLogger` (see diff below)
2. Repeat Testing Plan from #11449
3. Observe that …
=> Add identifier for explicit frontend error logging

app/controllers/idv/hybrid_mobile/socure/document_capture_controller.rb, app/controllers/idv/socure/document_capture_controller.rb, app/services/doc_auth/socure/requests/document_request.rb, spec/controllers/idv/hybrid_mobile/socure/document_capture_controller_spec.rb, spec/controllers/idv/socure/document_capture_controller_spec.rb, spec/services/doc_auth/socure/requests/document_request_spec.rb
remove the customerUserID from the DocumentRequest
[LG-14839](https://cm-jira.usa.gov/browse/LG-14839)
Removed references of document_capture_session_uuid and customerUserID from DocumentRequest and tests.
=> lg-14839 remove the customerUserID from the DocumentRequest

app/javascript/packages/address-search/CHANGELOG.md, app/javascript/packages/address-search/components/full-address-search.spec.tsx, app/javascript/packages/address-search/components/full-address-search.tsx, app/javascript/packages/address-search/components/in-person-locations.spec.tsx, app/javascript/packages/address-search/components/in-person-locations.tsx, app/javascript/packages/address-search/package.json, app/javascript/packages/address-search/types.d.ts
[LG-11857](https://cm-jira.usa.gov/browse/LG-11857)
Added an new prop to the `InPersonLocations` and `FullAddressSearch` components to show a heading on the top of the results section of the post office address search display.
Optional test, if you want to get wild!
<a id="steps-for-testing-the-package-locally"></a>
=> LG-11857: add header post office search results

app/controllers/idv/in_person/public/usps_locations_controller.rb, spec/controllers/idv/in_person/public/usps_locations_controller_spec.rb
[LG-14442](https://cm-jira.usa.gov/browse/LG-14442)
Adds error handling to the public USPS locations controller. Also adds a check for invalid characters before making the call to USPS, otherwise throwing a UspsLocationsError. Analytics added for when errors occur.
In the identity-site which calls this public controller, the front end checks should prevent invalid characters from being submitted before the controller should have to handle it. So instead of a manual test plan, automated tests have been added to test that this check and the error handling works.
=> LG-14442: Add error handling and invalid character check to public usps locations controller

app/controllers/concerns/idv/verify_info_concern.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/features/idv/threat_metrix_pending_spec.rb
**Why**
* The "internal error" view displayed during IdV is a last resort view. Prior to this change, this view was also shown when we received a ThreatMetrix API response that included an exception message.
* Showing the internal error view for an unknown exception raised by the ThreatMetrix API is not useful for the subject undergoing proofing and it obfuscates the action that can be taken by either the proofing subject or the support agent investigating the identity resolution errors.
**How**
* Added a logic branch to the routing handling of `Idv::VerifyInfoConcern#idv_failure` that still preferences the known actionable error cases (i.e., ssn_failure, rate_limiter, etc.), which is eventually called by both `Idv::VerifyInfoController` and `Idv::InPerson::VerifyInfoController`
1. The …
=> LG-14464: Show warning CTA on ThreatMetrix API exception

app/javascript/packages/captcha-submit-button/captcha-submit-button-element.spec.ts, app/javascript/packages/captcha-submit-button/captcha-submit-button-element.ts
Updates `CaptchaSubmitButton` to better handle a scenario where reCAPTCHA is slow to load.
Currently, if reCAPTCHA is not loaded by the time the user submits the form, the form will submit immediately, which may produce a failing result from the backend if reCAPTCHA is being enforced.
This is rather unlikely to happen, since the [initial reCAPTCHA script](https://www.google.com/recaptcha/enterprise.js?render=example) is small (roughly 2kb in size), but still technically possible, particularly if someone is using browser extensions or system features to autofill the sign-in form.
The proposed changes here take advantage of [documented reCAPTCHA features to "queue" callbacks prior to reCAPTCHA being loaded](https://developers.google.com/recaptcha/docs/loading)†, with an additional fallback …
=> Improve race condition handling for slow reCAPTCHA load

app/controllers/idv/hybrid_handoff_controller.rb, app/services/idv/session.rb, spec/features/idv/doc_auth/hybrid_handoff_spec.rb
[LG-14810](https://cm-jira.usa.gov/browse/LG-14810)
Desktop users bucketed to use the Socure doc auth vendor should only see "Use your phone to take photos" unless they are configured to do so.
=> LG-14810 Users only see "Use your phone to take photos" for Socure

app/jobs/data_warehouse/table_summary_stats_export_job.rb
A column named `id` sometimes is a `uuid` type, which breaks when calling `max(id)`. Based on an error discussed [here](https://gsa-tts.slack.com/archives/C03N6KQBAKS/p1731528552864369).
=> Only export stats for tables with integer id columns

app/controllers/socure_webhook_controller.rb, spec/controllers/socure_webhook_controller_spec.rb
[LG-14807](https://cm-jira.usa.gov/browse/LG-14807)
Remove inactive CaptureApp session from the database so that a new one can be created when rendering document capture by setting value to nil in db.
=> LG-14807 reset the socure docV url when the CaptureApp session has ended

.gitlab-ci.yml, dockerfiles/application.yaml, dockerfiles/nginx-prod.conf, dockerfiles/nginx.Dockerfile, dockerfiles/status-map.conf, dockerfiles/update-ips.sh
Added nginx image build for kubernetes.
This is to fix https://gitlab.login.gov/lg-team/mary/containerization-initiative/-/issues/85
=> add nginx image and build

app/javascript/packages/webauthn/enroll-webauthn-device.spec.ts, app/javascript/packages/webauthn/enroll-webauthn-device.ts
It is expected that this will allow Android devices to create synced credentials using Google Password Manager, and for such devices to provide an AAGUID value.
changelog: User-facing Improvements, F/T Unlock passkeys, Set residentKey option for webauthn to preferred
[LG-14911](https://cm-jira.usa.gov/browse/LG-14911)
=> Set residentKey option for webauthn to preferred

.gitlab-ci.yml
After last week, we are now running Postgres 16.4 everywhere, and CI should match
=> Update postgres versions used in CI

app/controllers/idv/hybrid_mobile/socure/document_capture_controller.rb, spec/controllers/idv/hybrid_mobile/socure/document_capture_controller_spec.rb
[LG-14008](https://cm-jira.usa.gov/browse/LG-14008)
Made the Socure hybrid handoff controller go to the hybrid handoff complete page on success, not the SSN page.
=> Redirect to the document_capture_complete page, not the SSN page, on Socure success

app/controllers/concerns/idv/step_indicator_concern.rb, spec/controllers/concerns/idv/step_indicator_concern_spec.rb
[LG-15054: Ensure that GPO steps cannot display in IPP step indicator](https://cm-jira.usa.gov/browse/LG-15054)
- Now that GPO has been removed from the IPP flow, there's no need to include GPO + IPP scenarios in the IPP step indicator.
Please manually test the IPP and GPO flow in order to ensure there are no regressions.
IPP
<details>
<summary>Step Indicator:</summary>
</details>
GPO
<details>
<summary>Step Indicator:</summary>
</details>
=> LG-15054: Remove GPO from IPP step indicator

app/services/proofing/resolution/plugins/instant_verify_residential_address_plugin.rb, app/services/proofing/resolution/plugins/instant_verify_state_id_address_plugin.rb, config/application.yml.default, lib/identity_config.rb, spec/services/proofing/resolution/plugins/instant_verify_residential_address_plugin_spec.rb, spec/services/proofing/resolution/plugins/instant_verify_state_id_address_plugin_spec.rb
This PR was extracted from #11479, and is in support of 
[LG-14725](https://cm-jira.usa.gov/browse/LG-14725)
Historically, we have used one config flag, `proofer_mock_fallback`, to control whether mocked resolution and address Proofers are used during identity verification. This value is set to `true` (use mocks) by default and `false` (don't use mocks) in production environments.
We are moving (gradually) toward a world where we have multiple identity resolution vendors, and thus 3 possible config states for identity resolution (Instant Verify, Socure KYC, and Mock). #11479 is about running Instant Verify and Socure side-by-side in production, and requires a different configuration strategy than `proofer_mock_fallback: false`.
This PR adds a new config setting, …
=> Add idv_resolution_default_vendor config

app/jobs/data_warehouse/daily_sensitive_column_job.rb, db/primary_migrate/20241115215510_update_sensitive_columns_comments.rb, db/schema.rb
changelog: Internal, Reporting,remove system tbale and updatesentitive missed tags
[LG-15077](https://cm-jira.usa.gov/browse/LG-15077)
Updated sensitive column tag as per the [doc](https://docs.google.com/spreadsheets/d/1ovD_0n16aGbsgyOPJ410Xm5pIGcw9dacH0Ol2fUHSbM/edit?usp=sharing) and removed system tables from DailySensitiveColumnJob
=> lg-15077 update sensitivetag

spec/lib/tasks/dev_rake_spec.rb
Description:
Remove allow extra analytics * from dev_rake_spec.rb to fix "Unnecessary allowed_extra_analytics" error.
=> Remove allow extra analytics * from dev_rake_spec

app/controllers/concerns/idv/document_capture_concern.rb, app/controllers/idv/document_capture_controller.rb, app/controllers/idv/socure/document_capture_controller.rb, app/jobs/socure_docv_results_job.rb, app/services/analytics_events.rb, app/services/idv/session.rb, app/views/idv/socure/document_capture/wait.html.erb, config/application.yml.default, lib/identity_config.rb, spec/controllers/idv/document_capture_controller_spec.rb, spec/controllers/idv/socure/document_capture_controller_spec.rb
[LG-14007](https://cm-jira.usa.gov/browse/LG-14007)
Upon return from Socure via the redirect url, check for the stored result (fetched by a job triggered by a webhook event). If not yet present, render the wait page that refreshes every 15 secs.
=> LG-14007: wait for Socure result if not present upon return

app/services/proofing/resolution/plugins/threat_metrix_plugin.rb, spec/services/proofing/resolution/plugins/threatmetrix_plugin_spec.rb
It looks like in 1767dd586ed9fd1cab3662a90fece1e992d679a3 we introduced a typo where `request_ip` was spelled `request_id`. This resulted in us sending a null `request_ip` to Threatmetrix.
This commit fixes the typo and modifies a spec to make sure the expected arguments are sent to the proofer.
=> Fix a typo in the `ThreatMetrixPlugin`

config/routes.rb
[LG-14828](https://cm-jira.usa.gov/browse/LG-14828)
Remove deprecated state ID step routes `/verify/in_person_proofing/state_id`
Ensure that users are not able to navigate to the `/verify/in_person_proofing/state_id` route
=> LG-14828 Remove deprecated state ID step routes

app/services/marketing_site.rb, app/views/idv/in_person/ready_to_verify/show.html.erb, app/views/user_mailer/shared/_in_person_ready_to_verify.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/mailers/user_mailer_spec.rb, spec/views/idv/in_person/ready_to_verify/show.html.erb_spec.rb
[LG-11666](https://cm-jira.usa.gov/browse/LG-11666)
Updates Ready to Verify barcode page and email/reminder email:
-  Removes the text "You can visit any Participating Post Office location." from the body text under the "Post Office information" heading
- For EIPP only, adds a section with the heading "Need to change your Post Office location?" and add body text under it: "You don’t need to create a new barcode, you can bring this barcode to any participating Post Office location. Find other participating Post Office locations."
- Also refactored the specs for the show.html.erb content to focus on sections of content as contexts, for readability and consistency.
Verify that the new H3 and body text are …
=> LG-11666 Add Post Office search link to barcode page and emails

lib/reporting/protocols_report.rb, spec/lib/reporting/protocols_report_spec.rb
[Fix facial match usage query](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/134)
- Excludes 'SAML Auth' and 'OpenID Connect: authorization request' from the IAL2 usage report
- Adds tests to make sure the queries look okay as [per feedback on last PR](https://github.com/18F/identity-idp/pull/11447#discussion_r1828018895)
=> Exclude stale sessions in IAL2 usage query

app/controllers/concerns/idv/verify_info_concern.rb, app/controllers/idv/in_person/verify_info_controller.rb, app/controllers/idv/verify_info_controller.rb, app/services/idv/proofing_components.rb, app/services/idv/session.rb, app/services/proofing/resolution/plugins/aamva_plugin.rb, lib/idp/constants.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/features/idv/analytics_spec.rb, spec/features/idv/end_to_end_idv_spec.rb, spec/features/idv/proofing_components_spec.rb, spec/services/idv/proofing_components_spec.rb
**Why**
* Prior to this change, we always stored 'aamva' in a `User`'s `proofing_components.source_check` column regardless of whether a call to AAMVA was made or not. Accuracy is good and storing the actual "vendor_name" will align our analytics across our events.
**How**
* Instead of hard-coding `vendor_name` in `proofing_components.source_check`, we dig into the result object (as produced by the `ResultAdjudicator`) for the actual vendor_name. This value should always be present even though we don't have any validators for it.
* This makes testing a little messier, but cleaning up the various vendor names in our specs should be done in future work. For now, a new constant with the known `source_check` names has been added (`Idv::Constants::Vendors::SOURCE_CHECK`).
* No new specs have …
=> LG-13761: ProofingComponents to store real vendor used to verify document PII

spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_success.json
LexisNexis informed us that the name suffix should be available in a TrueID response if the name suffix is present on the document. This commit adds the name suffix to the response fixture so that we have a fixture to represent this case.
We plan to read the name suffix and check it against the DLDV service in a future change. This commit prepares us for that.
=> Add name suffix to TrueID response fixture

app/controllers/idv/enter_password_controller.rb, app/services/idv/profile_maker.rb, app/services/idv/session.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/policies/idv/flow_policy_spec.rb, spec/services/idv/profile_maker_spec.rb, spec/services/idv/session_spec.rb
Proofing components are intended to represent the proofing flow that was used to create a profile. Traditionally these have been generated by tracking proofing components in a database table associated with the user. There were a number of problems with this approach which 5021e2ef8237ecc6ff38f6338371e89fb8dcf06d introduced a `Idv::ProofingComponents` service to address. This service generates proofing components from the session instead of from the database table.
This commit uses the `Idv::ProofingComponents` service to generate the proofing components stored on the profile. This will allow us to drop the proofing components table in a future change.
=> LG-14366 Store dynamically-generated proofing components on Profile

app/controllers/idv/hybrid_mobile/socure/document_capture_controller.rb, app/controllers/idv/socure/document_capture_controller.rb, app/services/analytics_events.rb, spec/controllers/idv/hybrid_mobile/socure/document_capture_controller_spec.rb
[LG-15125](https://cm-jira.usa.gov/browse/LG-15125)
As in #11500 for the standard flow, we need to wait for the Socure result to be received before we can determine where to send the user.
Currently, if the wait times out, we show a placeholder plain text of "Technical difficulties!!!" to be replaced with the appropriate "Try again?" page in a following ticket.
Note there is some identical code in the standard vs hybrid controllers that might be refactored into a concern in the future, but until all of the paths are complete, I thought it best to live with the duplication for now.
=> LG-15125: Wait for Socure result - hybrid flow

app/controllers/users/reset_passwords_controller.rb, app/forms/reset_password_form.rb, app/services/analytics_events.rb, config/application.yml.default, config/initializers/ab_tests.rb, lib/identity_config.rb, spec/controllers/users/reset_passwords_controller_spec.rb, spec/forms/reset_password_form_spec.rb
Effectively reverts #11423.
This pull request is created preemptively under the assumption that the test will only run for a short amount of time to collect enough data to build a case, not because there are any specific problems with the code itself.
This keeps refactoring improvements in #11423. The specific process for reverting was:
1. `git revert a419d8c` (a419d8c)
2. `git cherry-pick ba76ff4` (ba76ff4)
3. `git cherry-pick 23e93e1` (23e93e1)
4. Commit to remove assumptions for `password_matches_existing` extra property from `ResetPasswordForm` spec (683b7d9de7c25564d8286a4ad5aaa994816f87b5)
(This is reflected in branch commit history)
Repeat testing plan from #11423, verifying that there is no `password_matches_existing` in the password reset event payload.
=> Revert logging whether password matches current for password reset event

config/routes.rb
Reverts 18F/identity-idp#11510
Temporary revert to be cherry-picked into RC 433 deployment, while we investigate requests to deprecated routes.
Related Slack discussion: https://gsa-tts.slack.com/archives/C04GA9WQ85B/p1732216903820289
=> Revert "LG-14828 Remove deprecated state ID step routes"

app/services/proofing/resolution/plugins/instant_verify_residential_address_plugin.rb, app/services/proofing/resolution/plugins/instant_verify_state_id_address_plugin.rb, spec/jobs/resolution_proofing_job_spec.rb, spec/services/proofing/resolution/plugins/instant_verify_residential_address_plugin_spec.rb, spec/services/proofing/resolution/plugins/instant_verify_state_id_address_plugin_spec.rb
Supports work for:
[LG-14725](https://cm-jira.usa.gov/browse/LG-14725)
#11515 added a new config setting, `idv_resolution_default_vendor`, but left the code able to use the `proofer_mock_fallback` setting in certain circumstances. This PR removes the fallback.
**This should not be merged until after #11515 is in prod and all necessary config changes have been made**
=> Remove proofer_mock_fallback, erm, fallback

app/helpers/script_helper.rb, app/helpers/stylesheet_helper.rb, app/services/asset_preload_linker.rb, spec/helpers/script_helper_spec.rb, spec/helpers/stylesheet_helper_spec.rb, spec/services/asset_preload_linker_spec.rb
Updates asset helpers to bypass internal `stylesheet_link_tag` and `javascript_include_tag` logic for handling preload response headers, appending preload headers without caps. As of https://github.com/rails/rails/pull/48405 (Rails 7.1), preload headers added by tag helpers are capped at 1kb, which is very limiting, especially given our approach of loading many, smaller assets targeted as sidecar assets for UI components.
While the caps have created some incentives to be more intentional with preloading (e.g. #10612), we've already addressed the lowest hanging fruit, and a number of critical scripts are currently not being preloaded (e.g. reCAPTCHA behaviors on the sign-in screen).
References:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link
Verify that preload headers are …
=> Add uncapped preload headers for style, script assets

lib/data_pull.rb, lib/script_base.rb, spec/lib/data_pull_spec.rb
Following discussion yesterday [here](https://gsa-tts.slack.com/archives/C03KDV9S8T1/p1732139497048669?thread_ts=1732138386.924899&cid=C03KDV9S8T1), this PR tries to address two potential improvements in the data request script:
1. Looking up the service provider issuer automatically when the script is supplied without a requesting issuer, but is given `ServiceProviderIdentity`/`AgencyIdentity` UUIDs
2. Configurable depth (defaulting to 0)
=> Update Data Request script to compute requesting issuer and have configurable depth

lib/data_requests/deployed/create_user_report.rb, spec/lib/data_requests/deployed/create_user_report_spec.rb
A bit of a followup to #11541 and further discussion in [this thread](https://gsa-tts.slack.com/archives/C03KDV9S8T1/p1732558404564499?thread_ts=1732138386.924899&cid=C03KDV9S8T1). This makes a change so we never return the account UUID in the report in the `reporting_issuer_uuid` field.
=> Do not return User UUID in requesting_issuer_uuid when generating user report

config/routes.rb
[LG-15171](https://cm-jira.usa.gov/browse/LG-15171)
Fixes redirect for put for state id routes renaming. This is so that the transition to the new routes can be made without users still being directed to the old routes. 
=> LG-15171 Fixes redirect for PUT

Gemfile, Gemfile.lock, app/controllers/saml_idp_controller.rb, app/services/analytics_events.rb, spec/controllers/saml_idp_controller_spec.rb
[Create tracking for SHA256 validations](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/136)
This change adds some temporary event logging so that we can evaluate what level of impact turning on SHA256 error validation in the saml_idp gem might have to partner integrations.
=> Add analytics tracking for signature algorithm errors

app/services/reporting/agency_and_sp_report.rb, app/services/reporting/total_user_count_report.rb, spec/services/reporting/agency_and_sp_report_spec.rb, spec/services/reporting/total_user_count_report_spec.rb
changelog: Internal, Reporting, Update MKMR to split verified useres by facial matching
[LG-15119](https://cm-jira.usa.gov/browse/LG-15119)
Updated the Monthly Key Metrics Report to split numbers distinguishing between facial match IDV and Legacy IDV.
<details>
<summary>Before:
</summary>
</details>
<details>
<summary>After:
</summary>
</details>
=> LG-15119 Update MKMR to split verified users by facial matching

scripts/create-deploy-pr
Updates `scripts/create-deploy-pr` to run fetch the latest `git` remote before starting the script.
If the deployer hasn't recently fetched the remote repository, they can often encounter a cryptic error when trying to create the branch based on the latest commit in the staging environment.
Related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1719949060382589
Run `DRY_RUN=1 scripts/create-deploy-pr` and verify no errors in output
=> Fetch latest origin as part of deploy PR script

app/services/proofing/resolution/result_adjudicator.rb, spec/features/idv/analytics_spec.rb, spec/jobs/socure_shadow_mode_proofing_job_spec.rb, spec/services/proofing/resolution/result_adjudicator_spec.rb
In #11267 we quit logging the user's year-of-birth while we waited for additional security and privacy review. We received approval to start logging this attribute. This commit undoes the changes in #11267 so the year-of-birth is now logged
=> LG-14371 Start logging year-of-birth in biographical info hash

app/services/doc_auth/lexis_nexis/doc_pii_reader.rb, config/application.yml.default, lib/identity_config.rb, spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb
We are working to send additional data to AAMVA when it is present on documents. This commit lays groundwork for this by reading those new attributes from TrueID when configured to do so.
We are waiting on security approval before we start writing these new attributes into the Login.gov session. For that reason the reading of these attributes is feature flagged and disabled by default.
=> LG-14985 Read additional document data from TrueID when configured to do so

app/controllers/accounts/connected_accounts/selected_email_controller.rb, app/controllers/sign_up/select_email_controller.rb, app/views/accounts/connected_accounts/selected_email/edit.html.erb, app/views/sign_up/select_email/show.html.erb, spec/controllers/accounts/connected_accounts/selected_email_controller_spec.rb, spec/controllers/sign_up/select_email_controller_spec.rb, spec/views/accounts/connected_accounts/selected_email/edit.html.erb_spec.rb, spec/views/sign_up/select_email/show.html.erb_spec.rb
[LG-14741](https://cm-jira.usa.gov/browse/LG-14741)
This will make it so when a user has their max number of emails they will not be given the option to add email 
1. Have an account with the max number of emails. 
2. When changing email for SP you shoul dnot see an option to add a new email.
=> LG-14741 max email add new email link

app/mailers/user_mailer.rb, app/views/user_mailer/reset_password_instructions.html.erb, app/views/user_mailer/shared/_in_person_warning_banner.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/i18n_spec.rb, spec/mailers/previews/user_mailer_preview.rb, spec/mailers/user_mailer_spec.rb
[LG-14748](https://cm-jira.usa.gov/browse/LG-14748)
Add a warning banner to the password reset email for users with a pending in-person enrollments.
**Note:** You might have enable gpo flow from the environment vars 
<details>
<summary>Updated Password Reset Email</summary>
<h3>English:</h3>
<h3>Spanish:</h3>
<h3>French:</h3>
<h3>Chinese:</h3>
</details>
=> LG-14748 Add in person warning to password reset email

app/controllers/redirect/redirect_controller.rb
Removes the unused `event` keyword argument from the `redirect_to_and_log` private controller method for the `RedirectController` base controller.
This was superseded by the `tracker_method` keyword argument and slated for eventual removal. Based on current usage, there are no instances of `event` keyword argument and it can be safely removed.
Double-check for existing usage of the `event` keyword argument.
=> Remove unused event parameter from RedirectController

app/javascript/packages/webauthn/is-expected-error.spec.ts, app/javascript/packages/webauthn/is-expected-error.ts
Updates expected error logging conditions for WebAuthn errors to exclude a handful of additional error cases.
After further investigation, these errors are explainable by either known device / credential manager incompatibilities, or lack of support when verifying on a device other than the one that set up Face or Touch Unlock.
This follows #11481, which effectively fixed explicit frontend error logging, causing additional errors to be surfaced in NewRelic error logging.
Related Slack discussions:
- https://gsa-tts.slack.com/archives/C0NGESUN5/p1731614421090339
- https://gsa-tts.slack.com/archives/C0NGESUN5/p1731960018256199
```
yarn app/javascript/packages/webauthn/is-expected-error.spec.ts
```
This will be difficult to test in practice, since the errors surfaced here are edge cases on …
=> Exempt additional WebAuthn error logging as expected

app/controllers/concerns/idv/document_capture_concern.rb, app/controllers/concerns/idv/verify_info_concern.rb, app/controllers/idv/by_mail/request_letter_controller.rb, app/controllers/idv/in_person/usps_locations_controller.rb, app/controllers/idv/link_sent_controller.rb, app/controllers/idv/personal_key_controller.rb, app/forms/event_disavowal/password_reset_from_disavowal_form.rb, app/forms/reset_password_form.rb, app/jobs/resolution_proofing_job.rb, app/models/proofing_component.rb, app/models/user.rb, app/services/idv/phone_step.rb, app/services/idv/steps/doc_auth_base_step.rb, spec/controllers/concerns/idv/step_indicator_concern_spec.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/controllers/idv/in_person/usps_locations_controller_spec.rb, spec/controllers/idv/link_sent_controller_spec.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/features/idv/end_to_end_idv_spec.rb, spec/forms/event_disavowal/password_reset_from_disavowal_form_spec.rb, spec/forms/gpo_verify_form_spec.rb, spec/jobs/resolution_proofing_job_spec.rb, spec/models/user_spec.rb, spec/services/idv/session_spec.rb
[LG-13763](https://cm-jira.usa.gov/browse/LG-13763)
`ProofingComponent` is a model that tracks, in general terms, how a user has verified their identity. It exists in a 1:1 relationship with `User`, which gets kind of sticky / tricky for users with multiple Profiles.
Proofing components are useful for logging purposes, so we want to keep them. But instead of storing them attached to `User` in this way, we are now dynamically deriving them from the user's `IdV::Session`.
So then, now that we are doing that, we can stop writing to the old user-bound `proofing_components` stuff. That's what this PR does. We'll be dropping the table itself in a future PR.
=> LG-13763: Stop writing to the proofing_components table

app/controllers/concerns/idv/document_capture_concern.rb, app/controllers/concerns/idv/socure_errors_concern.rb, app/controllers/idv/document_capture_controller.rb, app/controllers/idv/hybrid_mobile/document_capture_controller.rb, app/controllers/idv/hybrid_mobile/socure/document_capture_controller.rb, app/controllers/idv/socure/document_capture_controller.rb, app/models/document_capture_session.rb, app/presenters/socure_error_presenter.rb, app/services/doc_auth/socure/responses/docv_result_response.rb, app/services/document_capture_session_result.rb, app/views/idv/hybrid_mobile/socure/document_capture/errors.html.erb, app/views/idv/session_errors/state_id_warning.html.erb, app/views/idv/shared/_error.html.erb, app/views/idv/socure/document_capture/errors.html.erb, app/views/idv/welcome/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, config/routes.rb, spec/controllers/idv/document_capture_controller_spec.rb, spec/controllers/idv/hybrid_mobile/socure/document_capture_controller_spec.rb, spec/controllers/idv/link_sent_controller_spec.rb, spec/controllers/idv/socure/document_capture_controller_spec.rb, spec/features/idv/doc_auth/socure_document_capture_spec.rb, spec/features/idv/hybrid_mobile/hybrid_socure_mobile_spec.rb, spec/support/features/document_capture_step_helper.rb, spec/support/socure_docv_fixtures.rb, spec/views/idv/shared/_error.html.erb_spec.rb
Added plumbing and UX display for categorized Socure errors.
changelog Upcoming Features, Socure, Added nice error displays
[LG-14010](https://cm-jira.usa.gov/browse/LG-14010)
Passed the Socure errors through from the original DocV response back through the document capture result, then added a presenter and updated error page to display it all nicely.
This test procedure requires a sandbox set up to use Socure. See jmax
or Doug to coordinate use of one.
- SSM into the sandbox and modify the file
`/srv/idp/current/app/services/doc_auth/socure/responses/docv_result_response.rb`. Insert
the following lines after line 36:
```    
parsed_body['documentVerification']['decision']['value'] = 'reject'
parsed_body['documentVerification']['reasonCodes'] = ['I848']
```
- …
=> LG-14010 - More detailed error page for Socure errors

app/controllers/users/sessions_controller.rb, app/services/analytics_events.rb, spec/controllers/users/sessions_controller_spec.rb, spec/support/analytics_helper.rb, spec/support/fake_analytics.rb, spec/support/shared_examples/sign_in.rb
[LG-15183](https://cm-jira.usa.gov/browse/LG-15183)
Fixes an issue where the "reCAPTCHA verify result received" event does not correctly associate the `user_id` if the sign-in attempt is unsuccessful for a reason other than reCAPTCHA.
This happens because the user is not yet signed-in. For "Email and Password Authentication" events, we work around this by [explicitly passing the `user_id` from the user associated with the given email parameter](https://github.com/18F/identity-idp/blob/2cf5663c22dc66681f293d79d62a4365756d4510/app/controllers/users/sessions_controller.rb#L213). The changes proposed here instead override the base `ApplicationController#analytics_user` to use this parameter-based user during the submission, so that all analytics logging will have that user associated.
Verify …
=> LG-15183: Associate user_id for reCAPTCHA result analytics of failed sign-in

app/controllers/concerns/unconfirmed_user_concern.rb, app/controllers/sign_up/cancellations_controller.rb, app/controllers/sign_up/email_confirmations_controller.rb, app/controllers/users/email_confirmations_controller.rb, app/controllers/users/emails_controller.rb, app/forms/add_user_email_form.rb, app/forms/select_email_form.rb, app/services/analytics_events.rb, app/services/email_confirmation_token_validator.rb, spec/controllers/accounts/connected_accounts/selected_email_controller_spec.rb, spec/controllers/sign_up/passwords_controller_spec.rb, spec/controllers/sign_up/select_email_controller_spec.rb, spec/controllers/users/email_confirmations_controller_spec.rb, spec/controllers/users/emails_controller_spec.rb, spec/forms/add_user_email_form_spec.rb, spec/forms/select_email_form_spec.rb, spec/services/email_confirmation_token_validator_spec.rb
Adds a handful of additional logging details to be able to help monitor usage with the new partner email selection feature:
- Add property `from_select_email_flow` (boolean) to `'Add Email: Email Confirmation'`: Whether email was confirmed after being added as part of partner email selection
- Add property `in_select_email_flow` (boolean) to `'Add Email Requested'`: Whether email is being added as part of partner email selection
- Add property `in_select_email_flow` (boolean) to `'Add Email Address Page Visited'`: Whether email is being added as part of partner email selection
- Add property `selected_email_id` (integer) to `:sp_select_email_submitted`: Submitted ID value for email address record
Repeat Testing Plan from #10951, and observe logging details above as applicable.
=> Add additional logging details for partner email selection

app/forms/recaptcha_form.rb, app/jobs/risc_delivery_job.rb, app/services/doc_auth/lexis_nexis/request.rb, app/services/doc_auth/socure/request.rb, app/services/outbound_health_checker.rb, app/services/piv_cac_service.rb, app/services/proofing/lexis_nexis/authenticated_request.rb, app/services/proofing/lexis_nexis/request.rb, app/services/proofing/socure/id_plus/request.rb, app/services/proofing/socure/reason_codes/api_client.rb, app/services/recaptcha_annotator.rb, app/services/usps_in_person_proofing/proofer.rb, config/application.yml.default, lib/identity_config.rb
[LG-14520](https://cm-jira.usa.gov/browse/LG-14520)
- Add a new configurable parameter - `recaptcha_request_timeout_in_seconds`
- Use this parameter in Recaptcha form submissions and Recaptcha annotation submissions
- Remove redundant configuration of specific timeouts in other places where we make Faraday requests
It's hard to come up with a simple test plan for this. The best way is to look for timeouts that occur after deployment and confirm that they do not exceed the threshold that was set.
=> Add recaptcha timeout

Gemfile, Gemfile.lock
Brings in the changes from https://github.com/18F/saml_idp/pull/129 to add IDP support for AES-GCM encryption of SAML responses. Other changes are required within our service provider configurations and partner portal, so it is not available quite yet, but allows for testing manually outside of those contexts.
=> Update saml_idp gem to add support for AES-GCM encryption algorithms

app/jobs/reports/combined_invoice_supplement_report_v2.rb, spec/jobs/reports/combined_invoice_supplement_report_v2_spec.rb
Currently, the Combined Invoice Supplement Report V2 takes a long time to run. The report runs across all IAAs in the database. Since this report is primarily used for billing, inactive IAAs are less relevant. In speaking with those consuming this report, they suggested we could safely exclude IAAs that have been expired for more than 90 days, so this PR does that.
=> Exclude old IAAs from Combined Invoice Supplement Report V2

spec/config/initializers/ab_tests_spec.rb
Because of how this spec tests initializers, it can leave weirdly configured AB tests around after it runs. This is usually not a problem, but can introduce flakiness in CI.
I think this will introduce failures elsewhere in the test suite, I'm opening this PR as part of effort to suss out how much.
=> Reload all AB tests after running AB test specs

app/services/proofing/lexis_nexis/ddp/response_redacter.rb
[LG-15197](https://cm-jira.usa.gov/browse/LG-15197)
Updates ThreatMetrix `ResponseRedactor` to remove `policy_details_api` from the list of allowed fields, to prevent it from being logged.
The `policy_details_api` field value is very large, and its properties are available through another of the logged fields (`tmx_variables`). The net effect of removing `policy_details_api` is a 73% reduction in the log size for the `response_body` field.
While there's no test coverage spanning individual keys, the allowlist behavior can be verified with existing specs for the redactor class:
```
rspec spec/services/proofing/lexis_nexis/ddp/response_redacter_spec.rb
```
=> LG-15197: Omit policy_details_api from ThreatMetrix response body logging

app/controllers/users/webauthn_platform_recommended_controller.rb, app/views/users/webauthn_platform_recommended/new.html.erb, spec/controllers/users/webauthn_platform_recommended_controller_spec.rb, spec/views/users/webauthn_platform_recommended/new.html.erb_spec.rb
Fixes an edge-case where an error may occur during redirect of skipped Face/Touch Unlock recommendation if user submits multiple times.
Fixes include:
- Use `SubmitButtonComponent` which has built-in duplicate submission prevention
- Provide fallback where `nil` redirect would otherwise be used
More explanation in related Slack thread: https://gsa-tts.slack.com/archives/C01710KMYUB/p1733496464529579
Verify no 500 errors in following test flow:
Reconfigure to force recommendation A/B test to always be visible:
```yaml
recommend_webauthn_platform_for_sms_ab_test_account_creation_percent: 100
```
3. Continue account creation up to MFA selection screen
4. At MFA selection screen, emulate mobile device using [Chrome DevTools device …
=> Fix Face/Touch recommendation duplicate submission

app/controllers/idv/enter_password_controller.rb, app/services/idv/session.rb
Return a Profile from Idv::Session::create_profile_from_applicant_with_password, then use that directly in EnterPasswordController.
=> Minor refactor of profile handling in EnterPasswordController

app/controllers/concerns/ial2_profile_concern.rb, app/models/profile.rb, spec/controllers/concerns/ial2_profile_concern_spec.rb, spec/features/idv/get_proofing_results_job_scenarios_spec.rb, spec/models/profile_spec.rb
[LG-14748](https://cm-jira.usa.gov/browse/LG-14748)
Cancel in-person enrollments when a profile is deactivated with reason `encryption_error`.
Scenario: User has a pending in-person enrollment and resets their password
=> LG-14749 Cancel enrollments on profile encryption error

app/services/saml_request_validator.rb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/controllers/saml_idp_controller_spec.rb, spec/services/saml_request_validator_spec.rb
[Add "No Certs" Error](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/140)
Slack conversation [here](https://gsa-tts.slack.com/archives/C01SU3NB9T3/p1733341354604359)
Ursula bug ticket [here](https://cm-jira.usa.gov/browse/LG-15243)
We have validations in the identity-idp-config repo to prevent partners from deploying non-pkce integrations without certificates to prod. However, we do not have those validations in the Partner Portal (because sometimes a partner doesn't have all the finalized details before creating an integration.)
This means that a partner could attempt to test an integration without a certificate, which currently blows up when we attempt to encrypt the response. This change adds a specific validation to ensure that a requesting service provider has …
=> Adding a SAML Validation error when there is no registered certs

lib/reporting/protocols_report.rb
Updating the SAML signature query in the weekly protocols report to use the SAML Auth Request event, rather than the SAML Auth event, as it is more accurate.
Event update [here](https://github.com/18F/identity-idp/pull/11558)
=> Update report to use earlier event

app/controllers/idv/how_to_verify_controller.rb, app/presenters/idv/how_to_verify_presenter.rb, app/views/idv/how_to_verify/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/features/idv/doc_auth/hybrid_handoff_spec.rb, spec/support/features/doc_auth_helper.rb, spec/views/idv/how_to_verify/show.html.erb_spec.rb
[LG-14923](https://cm-jira.usa.gov/browse/LG-14923)
Update the content for the "How To Verify" page to include a mobile flow without mentioning taking a selfie.
=> LG-14923 Update content for mobile required flow without facial matching

app/controllers/idv/by_mail/sp_follow_up_controller.rb, app/controllers/idv/personal_key_controller.rb, app/presenters/idv/by_mail/sp_follow_up_presenter.rb, app/services/analytics_events.rb, app/views/idv/by_mail/sp_follow_up/new.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, config/routes.rb, spec/controllers/idv/by_mail/sp_follow_up_controller_spec.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/features/idv/sp_follow_up_spec.rb, spec/presenters/idv/by_mail/sp_follow_up_presenter_spec.rb
In #11591 we added a `post_idv_follow_up_url` that allows users to return to a service provider after finishing verification out-of-band.
This commit puts this new URL to work in the verify-by-mail code. After this commit users who enter a verify-by-mail code without an SP in their session will see a new SP follow-up screen. This screen includes a CTA that prompts the user to connect their account to the service provider they started proofing with. This link leads to the new post-IdV follow-up URL.
=> LG-15177 Add a CTA to return to an SP after entering a verify-by-mail code

docs/backend.md
Expands on existing [backend form object documentation](https://github.com/18F/identity-idp/blob/main/docs/backend.md#forms-formresponse-analytics-and-controllers) to include more details on how to validate forms and handle errors.
Specific goals:
- Use human-readable error messages
- Tie errors to specific forms
- Use `FormResponse#first_error_message` as single message for flash
- Bind form object with SimpleForm
Verify that [the proposed documentation](https://github.com/18F/identity-idp/blob/aduth-form-validation-errors/docs/backend.md#forms-formresponse-analytics-and-controllers) makes sense.
=> Expand on form pattern documentation validation, error handling

app/presenters/account_show_presenter.rb, app/views/accounts/_identity_verification.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/features/idv/sp_follow_up_spec.rb, spec/presenters/account_show_presenter_spec.rb, spec/views/accounts/_identity_verification.html.erb_spec.rb
This commit adds a new alert to the account page. This alert appears when a user has completed IdV, but has not connected their account to their SP (i.e. they have not gone back to the SP and done a verified sign in since completing IdV). If a link to the SP is available, a link to go back to the SP is provided.
=> LG-15135 Add an alert when a user needs to connect to their initiating service provider

docs/frontend.md
Updates [Frontend documentation](https://github.com/18F/identity-idp/blob/main/docs/frontend.md) to include a section about images: what formats are expected, how they're optimized, and exceptions.
This builds upon a section started in #11381, generalized to images more broadly. It's based on a conversation I had in Slack with another developer who was adding an [email image](https://github.com/18F/identity-idp/tree/main/app/assets/images/email), which are an exception to the common rule of using SVG, and must be optimized manually.
Verify that the [proposed content](https://github.com/18F/identity-idp/blob/aduth-frontend-image-assets/docs/frontend.md#image-assets) makes sense.
=> Add Frontend documentation for Images best practices

config/initializers/app_artifacts.rb, lib/openid_connect_key_validation.rb, spec/lib/openid_connect_key_validation_spec.rb
As part of work to allow zero down-time rotation of OIDC keys, this is an initial step to validate that the keys are minimally correct before we potentially add more keys into the mix. It's brief, but ensures that the private key can sign data that is verifiable by the public key.
=> Validate OIDC identity provider public/private keys

app/controllers/idv/hybrid_mobile/socure/document_capture_controller.rb, app/controllers/idv/socure/document_capture_controller.rb, spec/controllers/idv/hybrid_mobile/socure/document_capture_controller_spec.rb, spec/controllers/idv/socure/document_capture_controller_spec.rb, spec/features/idv/doc_auth/socure_document_capture_spec.rb, spec/support/features/idv_helper.rb
[LG-14794](https://cm-jira.usa.gov/browse/LG-14794)
Reuse socure capture app url when we can, also adding feature tests aligned with test scenarios listed in the ticket.
=> Lg-14794 reuse valid capture app url

app/services/saml_request_validator.rb, spec/controllers/saml_idp_controller_spec.rb, spec/services/saml_request_validator_spec.rb
Link to the relevant [slack conversation](https://gsa-tts.slack.com/archives/C01SU3NB9T3/p1733859019145089):
Recently we added an error condition for when a partner does not have a certificate set, designed to help partners in the integration environment. It was believed this would not impact partners in product because the only two active, non-pkce integrations that did not have certificates were actually staging integrations.
However, one of our partners has pkce set, but is using SAML in the web, and so got caught in this error. They have `block_encryption` set to `none`, so they don't need a certificate. 
This change adds a condition where if a partner does not have any registered certificates, BUT is not requesting encrypted responses, then it will not error out.
Write a brief …
=> Allow no certs if block_encryption is set to 'none'

bin/summarize-user-events
(Context for anyone not working on this project can be found in [Slack](https://gsa.enterprise.slack.com/archives/C0849B839FC))
Sometimes it is convenient to source events locally rather than having to make a Cloudwatch query every time.
This PR checks to see if stdin is a tty, and if it's not, tries to read newline-delimited JSON (ndjson) events from it.
=> [Hackathon] Allow sourcing events from stdin

bin/summarize-user-events, lib/event_summarizer/example_matcher.rb
- Add an example of a Matcher that just counts events
- Add really, really basic Markdown output
=> [Hackathon] Add ExampleMatcher

app/controllers/concerns/saml_idp_auth_concern.rb, app/controllers/openid_connect/authorization_controller.rb, app/controllers/openid_connect/logout_controller.rb, app/controllers/openid_connect/token_controller.rb, app/controllers/openid_connect/user_info_controller.rb, app/controllers/saml_idp_controller.rb, app/forms/openid_connect_authorize_form.rb, app/forms/openid_connect_logout_form.rb, app/forms/openid_connect_token_form.rb, app/services/access_token_verifier.rb, app/services/analytics_events.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/openid_connect/logout_controller_spec.rb, spec/controllers/openid_connect/token_controller_spec.rb, spec/controllers/openid_connect/user_info_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/forms/openid_connect_authorize_form_spec.rb, spec/forms/openid_connect_token_form_spec.rb
There is no ticket! This is part of a [hackthon project](https://docs.google.com/document/d/1YEZTFIXmPRD_fVe3lA_bB4rBid66eNfgyMUFqq0BOF4/edit?tab=t.0). The goals of this project is to monitor authentication and logout requests to be on the lookout for broken integrations. This will allow us to be more proactive with partners who may be struggling with their integrations.
The existing error logging, however, was not really designed for pulling out specific details and notifying us about them, so a new event seemed like a good fit for this problem.
This change:
- Adds a new event called `integration_errors_present`
- Wires that event into our existing code flow, whenever a request is made that can fail.
There is some duplicative code that is similar but not exactly the same. It could …
=> Add integration error event

app/controllers/idv/hybrid_mobile/socure/document_capture_controller.rb, app/controllers/idv/socure/document_capture_controller.rb, app/presenters/account_show_presenter.rb, app/services/saml_request_validator.rb, app/views/accounts/_identity_verification.html.erb, config/initializers/app_artifacts.rb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, docs/backend.md, docs/frontend.md, lib/openid_connect_key_validation.rb, spec/controllers/account_reset/delete_account_controller_spec.rb, spec/controllers/idv/hybrid_mobile/socure/document_capture_controller_spec.rb, spec/controllers/idv/in_person/ready_to_verify_controller_spec.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/controllers/idv/socure/document_capture_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/factories/in_person_enrollments.rb, spec/factories/profiles.rb, spec/factories/users.rb, spec/features/idv/doc_auth/socure_document_capture_spec.rb, spec/features/idv/sp_follow_up_spec.rb, spec/lib/openid_connect_key_validation_spec.rb, spec/models/profile_spec.rb, spec/presenters/account_show_presenter_spec.rb, spec/services/saml_request_validator_spec.rb, spec/views/accounts/_identity_verification.html.erb_spec.rb, spec/views/accounts/show.html.erb_spec.rb
- Account screen: Add a new link to return to the service provider for verified users who have not connected their account yet. ([#11606](https://github.com/18F/identity-idp/pull/11606))
- Automated Testing: Improve test setup for enrolling profiles ([#11315](https://github.com/18F/identity-idp/pull/11315))
- Dcoumentation: Add Frontend documentation for Images best practices ([#11613](https://github.com/18F/identity-idp/pull/11613))
- Documentation: Expand on form pattern documentation validation, error handling ([#11611](https://github.com/18F/identity-idp/pull/11611))
- OpenID Connect: Validate identity provider public/private keys ([#11612](https://github.com/18F/identity-idp/pull/11612))
- socure: Reuse socure valid urls ([#11555](https://github.com/18F/identity-idp/pull/11555))
=> Deploy RC 438 to Production

bin/summarize-user-events, lib/event_summarizer/idv_matcher.rb
Add timestamps to output so you can actually tell when something happened.
Example:
* (08:57 PM) AAMVA request failed. The ID # from the user's non-driving ID card was invalid according to the state of OR
* (09:03 PM) AAMVA request failed. The ID # from the user's non-driving ID card was invalid according to the state of OR
* (09:06 PM) Instant Verify request failed. 1 check failed: AddrNotHighRisk (addr_highrisk_fail)
* (09:06 PM) AAMVA request failed. The ID # from the user's non-driving ID card was invalid according to the state of OR
* (09:13 PM) AAMVA request failed. The ID # from the user's non-driving ID card was invalid according to the state of OR
=> [HACKATHON] Output formatting tweaks

lib/event_summarizer/idv_matcher.rb, lib/event_summarizer/vendor_result_evaluators/true_id.rb
```
* (05:53 PM) TrueID request failed. Evidence suggests that the document may have been tampered with.
* (08:56 PM) User successfully verified their identification card on the first attempt
```
=> report on TrueID success/failure

lib/event_summarizer/idv_matcher.rb
If the user has not completed the initial workflow and we see some time go by without an idv-related event, consider the attempt abandoned.
* (12:56 PM) User successfully verified their identification card on the first attempt
* (12:57 PM) AAMVA request failed. The ID # from the user's non-driving ID card was invalid according to the state of OR
* (01:03 PM) AAMVA request failed. The ID # from the user's non-driving ID card was invalid according to the state of OR
* (01:03 PM) User abandoned identity verification
* (01:00 PM) User failed to verify their identification card (check logs for reason)
* (01:04 PM) User successfully verified their identification card after 1 tries
* (01:06 PM) AAMVA request failed. The ID # from the user's non-driving ID card was invalid …
=> [HACKATHON] Attempt to detect idv abandonment

app/services/sp_return_url_resolver.rb, spec/services/sp_return_url_resolver_spec.rb
In #11591 we added a `post_idv_follow_up` URL in response to issues we were having getting users for a particular partner to return to their SP. This partner expressed concerns about have the appropriate locale for these users since they are returning to the partner without initiating a session at the partner.
The original implementation for the change in #11591 included a locale param on the `post_idv_follow_up` URL. After some discussion with other engineers we identified that this pattern of hardcoding a param onto a single service providers was undesirable. This commit introduces the ability to include template-able values in these URLs and introduces the locale as one of those values.
=> LG-15237 Allow the SP return URL resolver to interpolate locale values into URLs

app/services/analytics_events.rb
The YARD documentation gets scraped and use in internal documentation. We have a few cases where per-param text was being "globbed" into the method-wide description, creating some confusing docs (see screenshot below).
I started out fixing the "vendor submitted" image event but then found a few more, by searching around with `/# [^@ ]/` regex.
Confirm that YARD parses descriptions of event as expected, confirm it in our analytics events JSON file
**Before**
```
> make analytics_events
> jq -r '.events[] | select( .event_name | contains("vendor submitted")) | .description' < public/api/_analytics-events.json
"attempts")
fingerprints for that field.
SDK upgrades
The document capture image was uploaded to vendor during the IDV process
```
**After**
```
> make analytics_events
> jq -r …
```
=> Fix documentation formatting for Analytics Events

dockerfiles/idp_deploy.Dockerfile
Updates image build process to reference AWS Public ECR instead of DockerHub
If the images build correctly as part of this PR then this change is successful
=> Update image source from dockerhub to AWS Public ECR

spec/support/fake_analytics.rb, spec/support/fake_analytics_spec.rb
Updates the behavior of `FakeAnalytics` extra analytics checker to only support individually allowlisted properties and not blanket wildcard exceptions.
As of #11634, we have complete documentation coverage for every analytics event, thus removing the need for this override, which was introduced as a temporary solution when introducing the check, due to the level of effort in documenting existing analytics events.
=> Remove support for wildcard allowed_extra_analytics

spec/forms/recaptcha_enterprise_form_spec.rb, spec/forms/recaptcha_form_spec.rb, spec/support/fake_analytics.rb, spec/support/fake_analytics_spec.rb
Removes all support for `allowed_extra_analytics`.
Follows #11643, addressing the one remaining use-case of reCAPTCHA forms, which passthrough extra analytics, currently used to support optional `phone_country_code` logging. Testing with this property allows coverage for the behavior while avoiding flagging the extra analytics check.
This is also meant to support #11605, which currently has some flakey test failures within the extra analytics checking global RSpec configuration.
=> Remove all supports for allowed extra analytics

app/components/step_indicator_component.rb, app/controllers/idv/personal_key_controller.rb, spec/components/step_indicator_component_spec.rb, spec/features/idv/end_to_end_idv_spec.rb
We received feedback from a partner that users may think that they are done with the identity verification workflow on the personal key page because all of the steps on the step indicator are marked complete. This commit modifies the step indicator on the personal key page so the "Re-enter password" step is not complete on that page.
Since there is no longer a case where all step indicator steps are complete this change also removes the `complete` status from the `StepIndicatorComponent`.
=> Modify the personal key page such that the "Re-enter password" step is not marked complete

config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
When a user successfully complete document capture we showed an alert on the next screen that says "We successfully verified your ID". We received feedback that this may lead people to believe that they are finished with IdV. This commit updates the language to prevent any confusion.
=> LG-15280 Update the alert for successful document capture

app/controllers/test/ipp_controller.rb, app/views/test/ipp/index.html.erb, config/routes.rb
Related to work for
[LG-15000](https://cm-jira.usa.gov/browse/LG-15000)
Adds a new `/test/ipp` route, **accessible only for local development**, that will show the most recent in-person proofing enrollments, for `pending` ones, provide a big "Approve" button.
If you click Approve, it will then call the part of `GetUspsProofingResultsJob` that processes a successful response from USPS, and move the associated profile out of IPP.
The code to actually do the approving was sourced from the test instructions from #11261.
BEHOLD
=> Add a big "Approve" button for pending in-person proofing enrollments

app/controllers/accounts/connected_accounts/selected_email_controller.rb, app/forms/select_email_form.rb, app/views/accounts/connected_accounts/selected_email/edit.html.erb, spec/controllers/accounts/connected_accounts/selected_email_controller_spec.rb, spec/features/account_connected_apps_spec.rb, spec/forms/select_email_form_spec.rb, spec/views/accounts/connected_accounts/selected_email/edit.html.erb_spec.rb
[LG-15156](https://cm-jira.usa.gov/browse/LG-15156)
Bug fix for https://cm-jira.usa.gov/browse/LG-13665 form allows a blank submission.
This occurs when a user has a service partner connection that has not yet been associated with an email address.
=> LG 15156 Select your preferred email allows blank submission

config/application.yml.default
No ticket but discovered Chinese was not enabled in staging [here](https://cm-jira.usa.gov/browse/LG-15148) and Slack conversation [here](https://gsa-tts.slack.com/archives/C0NGESUN5/p1734537094308409).   
- Removed `available_locales` from production list so that the default would be used (which includes zh)
=> Enable Chinese in all production environments

app/controllers/concerns/idv/document_capture_concern.rb, app/presenters/socure_error_presenter.rb, app/services/doc_auth/socure/responses/docv_result_response.rb, spec/controllers/idv/link_sent_controller_spec.rb
[LG-14010](https://cm-jira.usa.gov/browse/LG-14010)
General cleanup and minor syntax improvements from the previous PR.
=> LG-14010 minor review comments

app/javascript/packages/analytics/digital-analytics-program.spec.ts, spec/javascript/packages/document-capture/hooks/use-async-spec.jsx
Updates a few instances of JavaScript behavior now able to be simplified using [`Promise.withResolvers`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers), available as of Node.js v22.
See [MDN "Description" documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers#description) for an explanation of the exact type of code this feature seeks to replace.
This builds upon #11605 and #11648, leveraging newly-available features.
Since the changes only affect specs, it should be sufficient to verify that tests pass:
```
yarn test
```
=> Use Promise.withResolvers to simplify promise handling

app/controllers/concerns/idv/step_indicator_concern.rb, app/controllers/idv/by_mail/request_letter_controller.rb, app/controllers/idv/by_mail/resend_letter_controller.rb, app/views/idv/in_person/address/show.html.erb, app/views/idv/in_person/state_id/show.html.erb, spec/views/idv/in_person/ready_to_verify/show.html.erb_spec.rb, spec/views/idv/shared/ssn.html.erb_spec.rb
[LG-10206](https://cm-jira.usa.gov/browse/LG-10206)
Moves STEP_INDICATOR_STEPS from InPersonFlow into StepIndicatorConcern. InPersonFlow is FSM-related and will get deleted in a future clean-up PR, so these constants need to be moved as they are still used for the IPP step indicator. References to the old Idv::Flows::InPersonFlow::STEP_INDICATOR_STEPS are updated to reference the new constants.
Note: For 50/50 state management, the old constants in the InPersonFlow are not being removed in this PR. 
No new features or behavior was added - regression testing would be good:
=> LG-10206 Move STEP_INDICATOR_STEP constants out of InPersonFlow

app/mailers/user_mailer.rb, app/views/user_mailer/idv_please_call.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/mailers/previews/user_mailer_preview.rb, spec/mailers/previews/user_mailer_preview_spec.rb, spec/mailers/user_mailer_spec.rb, spec/support/shared_examples/mailer_preview.rb
**NOTE: This is the first of three PRs, which will be spread across deploys. The next one is #11662, then #11664.**
[LG-15000](https://cm-jira.usa.gov/browse/LG-15000)
We want to update the remote flow to send the "Please call" email. Since it will be the same email the IPP flow currently sends, we're going to rename it to be more generic: `idv_please_call` rather than `in_person_please_call`.
This PR is step one of the process:
* Rename templates, i18n keys, etc
* Add `idv_please_call` method to the mailer
* Add `in_person_please_call` as an alias to that method (so we don't break)
A subsequent PR will actually add the email to the remote flow and update the in person flow to use the new name.
1. Update …
=> LG-15000: Add idv_please_call email

Makefile, lib/linters/mail_later_linter.rb, spec/lib/linters/mail_later_linter_spec.rb, spec/mailers/user_mailer_spec.rb
Fixes an issue where the custom `mail_later` Rubocop cop will fail if checking a method call on a variable reference to a mailer.
In doing so, it fixes a separate issue where errors raised in the course of performing Rubocop lint check are not output in the build output.
Previously: https://github.com/18F/identity-idp/pull/11458#issuecomment-2524146499
Verify that the build output now displays errors occurring during Rubocop check: https://gitlab.login.gov/lg/identity-idp/-/jobs/1577667
Verify that the lint checks pass.
=> Fix mail_later Rubocop cop when method called on variable reference

spec/features/idv/doc_auth/socure_document_capture_spec.rb
Verify socure rate limit display decrements correctly
[LG-15193](https://cm-jira.usa.gov/browse/LG-15193)
Adding feature test to ensure that rate limit value displayed to user on Socure error page is correct and properly decrements as user fails more than once. 
Bug was fixed as a part of [LG-14010](https://github.com/18F/identity-idp/pull/11560)
=> lg-15193 verify socure rate limit display decrements correctly

spec/features/account_creation/completions_cancel_spec.rb, spec/features/idv/cancel_spec.rb, spec/features/idv/end_to_end_idv_spec.rb, spec/features/idv/uak_password_spec.rb, spec/features/two_factor_authentication/second_mfa_reminder_spec.rb, spec/features/users/password_recovery_via_recovery_code_spec.rb, spec/features/users/user_profile_spec.rb
Following #11669, I've been monitoring a few other areas where tests seem to be a bit flakey. This PR adds some path expectations to try to address them.
=> Add additional path expectations in end to end specs to reduce test flakiness

app/services/idv/analytics_events_enhancer.rb, lib/analytics_events_documenter.rb, spec/features/idv/analytics_spec.rb, spec/services/idv/analytics_events_enhancer_spec.rb, spec/support/fake_analytics.rb
**Why**
* When Idv::AnalyticsEventEnhancer was first introduced it was opt-in, but this no longer makes sense for our current analytics tracking needs.
* While a better long-term strategy would be to eliminate the event enhancer, this should be addressed in future work given its complexity.
**How**
* Broke up the IGNORED_METHODS constant into 3 buckets: 1) frontend events and 2) events solely used in jobs. Anything that doesn't fall neatly in either category should just be put in the `IGNORED_METHODS` constant and those additions should be minimal.
* Added specs to ensure that the list of event methods referenced don't get out of sync with AnalyticsEvents and that there is no overlap between ignored and explicitly opted-in methods.
**Non-Goals**
* Adding new tests to validate event …
=> LG-14064: Make IdV event enhancement opt-out

app/controllers/socure_webhook_controller.rb, app/jobs/socure_docv_repeat_webhook_job.rb, app/jobs/socure_docv_repeat_webhooks_job.rb, app/services/doc_auth/socure/webhook_repeater.rb, config/application.yml.default, lib/identity_config.rb, spec/controllers/socure_webhook_controller_spec.rb, spec/features/idv/doc_auth/socure_document_capture_spec.rb, spec/features/idv/hybrid_mobile/hybrid_socure_mobile_spec.rb, spec/jobs/socure_docv_repeat_webhook_job_spec.rb
[LG-15271](https://cm-jira.usa.gov/browse/LG-15271)
Broadcast webhooks received from Socure to configure receivers.
Currently configured in the Timnit Sandbox
=> LG-15271: Socure webhook repeater

spec/services/user_alerts/alert_user_about_account_verified_spec.rb, spec/support/mailer_helper.rb, spec/support/mailer_helper_spec.rb
mailer_helper.rb provides the `expect_delivered_email` helper, which we use in our specs to assert that an email was sent.
This PR:
1. Adds the inverse `expect_email_not_delivered`
2. Adds a spec to capture the expected behavior
3. Updates some places where body matching was previously incorrectly passing
=> mailer_helper update

app/assets/stylesheets/components/_header.scss
changelog: User-Facing Improvements, Accessibility, skipnav container no longer blocks content at large zoom levels
[LG-15265](https://cm-jira.usa.gov/browse/LG-15265)
See also https://github.com/uswds/uswds/issues/6260
Works around an irksome bug where high zoom levels caused part of "Skip to main content" to overlap the actual content.
<details>
</details>
<details>
</details>
=> LG-15265 | Work around "content" blocking content

app/controllers/idv/by_mail/enter_code_controller.rb
Removes an unused method `Idv::ByMail::EnterCodeController#threatmetrix_enabled?`
Last reference removed in #8397
=> Remove unused method checking enabled ThreatMetrix

bin/summarize-user-events, lib/event_summarizer/idv_matcher.rb
- I added a command line flag, `-f`, for passing in a file that contains ndjson.  I made this change to enable using `binding.pry` with the script.  Previously, the script regarded the piped-in file as `stdin`, which made it impossible to interact with `binding.pry` breakpoints via the terminal.
- Since gpo was ripped out of the ipp flow, I removed the handling of the ipp + gpo flow.
- Drop a `binding.pry` somewhere in the script.
- Run the script and interact with the breakpoint via the CLI.
=> [HACKATHON] Enable user narrative script to work with `binding.pry`

scripts/create-release
`scripts/create-release` is used to tag a release after it is deployed. Previously this script required you to pass in the actual PR ID. This update allows you to just pass in the PR URL directly, which is ever so slightly faster.
Before:
```shell
scripts/create-release 1234
```
After:
```shell
scripts/create-release https://github.com/18F/identity-idp/pull/1234
```
(The old way still works too.)
=> Allow passing PR url to create-release script

app/controllers/idv/by_mail/enter_code_controller.rb, app/controllers/idv/enter_password_controller.rb, app/jobs/get_usps_proofing_results_job.rb, app/mailers/user_mailer.rb, app/views/user_mailer/idv_please_call.html.erb, spec/controllers/idv/by_mail/enter_code_controller_spec.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/jobs/get_usps_proofing_results_job_spec.rb, spec/mailers/user_mailer_spec.rb, spec/services/user_alerts/alert_user_about_account_verified_spec.rb, spec/support/mailer_helper.rb, spec/support/mailer_helper_spec.rb
[LG-15000](https://cm-jira.usa.gov/browse/LG-15000)
Updates the non-IPP IDV flows to send the "Please Call" email
1. Run through IDV, selecting phone verification. Ensure you are flagged by ThreatMetrix.
2. Confirm you receive the "Please Call" email at the end of the flow
3. Confirm you **do not** receive the "You've been verified" email at the end of the flow
1. Run through IDV, selecting verify by mail. Ensure you are flagged by ThreatMetrix.
2. Confirm you receive the "Please Call" email after you enter your code
3. Confirm you **do not** receive the "You've been verified" email after you enter your code
=> LG-15000: Send "Please call" email from other parts of IDV

app/controllers/concerns/idv/verify_info_concern.rb, app/controllers/idv/in_person/verify_info_controller.rb, app/controllers/idv/verify_info_controller.rb, app/services/idv/proofing_components.rb, app/services/idv/session.rb, spec/controllers/idv/in_person/verify_info_controller_spec.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/features/idv/analytics_spec.rb, spec/features/idv/end_to_end_idv_spec.rb, spec/services/idv/proofing_components_spec.rb
[LG-15051](https://cm-jira.usa.gov/browse/LG-15051)
Prior to this PR, we always said (in proofing components) that the resolution check was done via LexisNexis.
This PR:
- Starts tracking the actual vendor used for identity resolution in idv_session
- Uses that data to set the resolution_check value in ProofingComponents
- ALSO starts tracking residential_resolution_check in ProofingComponents for the check done with the residential address (for the IPP case)
1. Run through IdV (remote). At the end, look at the Profile record that was generated. Verify that `resolution_check` is set to `ResolutionMock` and that `residential_resolution_check` is set to `ResidentialAddressNotRequired`
2. Run through IdV (IPP). At the end, look at the Profile record that was …
=> LG-15051: Record correct resolution vendor in proofing components

app/presenters/account_show_presenter.rb, app/views/accounts/_identity_verification.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/features/idv/sp_follow_up_spec.rb, spec/views/accounts/_identity_verification.html.erb_spec.rb
[LG-15314](https://cm-jira.usa.gov/browse/LG-15314)
Due to a misunderstanding with the Department of State, the strings for a prompt redirecting users to their service provider when they hadn't connected their account to them used "partner agency" as a literal string rather than an interpolation.
This fixes that, and also omits the message in the case that the name is nil since it is otherwise incomprehensible and contains no link.
That required some test changes, and also led to a bit of refactoring. Shoutout to @jmhooper for encouraging that part.
<details>
</details>
<details>
No SP name, so CTA not displayed:
(Otherwise it would read …
=> LG-15314 | Replace 'partner agency' with SP name

app/jobs/resolution_proofing_job.rb
Part 1 of 2 for [LG-15187](https://cm-jira.usa.gov/browse/LG-15187)
Adds a new parameter to ResolutionProofingJob prior to implementation, so that the new signature method can be used once all job queues are running the same code.
See: #11685 for implementation
=> LG-15187: Update Socure Idv A/B test logic, pt.1

app/controllers/idv/forgot_password_controller.rb, app/jobs/resolution_proofing_job.rb, app/models/user.rb, app/views/users/webauthn_setup/new.html.erb, spec/controllers/idv/by_mail/enter_code_controller_spec.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/features/multiple_emails/email_management_spec.rb, spec/features/sp_cost_tracking_spec.rb, spec/features/two_factor_authentication/sign_in_spec.rb, spec/features/users/sign_in_spec.rb, spec/jobs/get_usps_proofing_results_job_spec.rb, spec/services/user_alerts/alert_user_about_account_verified_spec.rb, spec/support/features/session_helper.rb, spec/support/idv_examples/sp_handoff.rb, spec/support/shared_examples/phone/rate_limiting.rb, spec/support/shared_examples/sign_in.rb
Refactoring to use more descriptive method and remove the sort when not needed.
=> Use `#last_sign_in_email_address` where appropriate

spec/services/idv/agent_spec.rb
Supports work for 
[LG-15187](https://cm-jira.usa.gov/browse/LG-15187)
This PR just refactors the `Idv::Agent` spec to use more `let` and `subject` blocks. This will make future changes I want to make for LG-15187 a little cleaner.
=> Refactor Idv::Agent spec

spec/config/initializers/ab_tests_spec.rb, spec/rails_helper.rb
**TLDR:** This PR updates our RSpec config to reload A/B tests after each spec file in a test run. This is because by default A/B tests are initialized _once and only once_, and this makes it possible for them to "hold on" to mocked configuration data, potentially leading to flakiness.
Previously in #11583 I added a cleanup hook to the `ab_tests_spec.rb` file, but there are two problems with this:
1. Theoretically, A/B tests could get "stuck" by any spec, so it needs to be applied more broadly
2. The way I added it didn't actually work. RSpec complained:
```
WARNING: `after(:suite)` hooks are only supported on the RSpec configuration object. This `after(:suite)` hook, registered on an example group, will be ignored. Called from /builds/lg/identity-idp/spec/config/initializers/ab_tests_spec …
```
=> Aggressively reload A/B tests during spec runs

spec/features/idv/steps/in_person/state_id_spec.rb
This test is checking validation around when the user reports they are under 13 years of age.  Around New Year, it's possible that the year for the Rails app and the year for the browser might differ. So this PR adds in a little bit of wiggle room to the calculation.
=> Fix a feature test that breaks around New Year

Gemfile.lock
When running scripts or similar with NewRelic enabled, we get a deprecation warning:
```
[DEPRECATED] Bundler.rubygems.all_specs has been removed in favor of Bundler.rubygems.installed_specs
```
This was addressed in NewRelic [here](https://github.com/newrelic/newrelic-ruby-agent/pull/2823), and this PR updates the gem to fix the warning.
=> Update newrelic_rpm gem to fix Bundler deprecation warning

app/javascript/packages/document-capture/components/document-capture.tsx, app/javascript/packages/document-capture/components/in-person-call-to-action.tsx, app/javascript/packages/document-capture/components/review-issues-step.tsx, app/javascript/packages/document-capture/context/upload.tsx, app/javascript/packages/document-capture/services/upload.ts, app/presenters/image_upload_response_presenter.rb, app/services/analytics_events.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/features/idv/analytics_spec.rb, spec/javascript/packages/document-capture/context/upload-spec.jsx, spec/presenters/image_upload_response_presenter_spec.rb
[LG-15217](https://cm-jira.usa.gov/browse/LG-15217)
We want to be able to track metrics for users who choose to "try again online" or fall back to "try in person" after not being able to verify their ID in the remote flow. In particular we want to know how many submission attempts they've made before eventually trying in person. This PR adds `submit_attempts` to the analytics for these events: "Frontend: IdV: Capture troubleshooting dismissed" and "Frontend: IdV: Verify in person troubleshooting option clicked"
https://github.com/user-attachments/assets/e0fffbe8-91b7-4aee-80fe-c8059a8392da
=> LG-15217 Add submit_attempts property to doc auth troubleshooting option actions

app/services/proofing/aamva/proofer.rb, spec/services/proofing/aamva/proofer_spec.rb
While investigating a support case [here](https://gsa-tts.slack.com/archives/C20J64X6V/p1735908075619039), I noticed that we didn't seem to be logging AAMVA maintenance windows as expected. Following some discussion [here](https://gsa-tts.slack.com/archives/C03DCUECFH7/p1735926961106209), the issue is that we only include the attribute if the call does not raise an exception.
This PR includes the `jurisdiction_in_maintenance_window` attribute in both cases.
=> Include jurisdiction_in_maintenance_window in result when AAMVA raises exception

app/controllers/concerns/threat_metrix_concern.rb, app/controllers/idv/in_person/ssn_controller.rb, app/controllers/idv/ssn_controller.rb, app/controllers/users/two_factor_authentication_setup_controller.rb, spec/controllers/concerns/threat_metrix_concern_spec.rb, spec/controllers/idv/in_person/ssn_controller_spec.rb, spec/controllers/idv/ssn_controller_spec.rb, spec/controllers/users/two_factor_authentication_setup_controller_spec.rb
Supports [LG-15302](https://cm-jira.usa.gov/browse/LG-15302)
Moves feature flag check from shared `ThreatMetrixConcern` to individual controllers, so that overriding CSP for account creation is not dependent on profiling collection being enabled for identity proofing.
Verify that CSP override occurs on MFA setup screen when account creation profiling collection is enabled and identity proofing device profiling collection is disabled.
```yaml
development:
account_creation_device_profiling: collect_only
proofing_device_profiling: disabled
```
=> Override CSP for ThreatMetrix based on feature-specific config

config/application.yml.default
AAMVA let us know these states are now available to us through DLDV. I used the "Jonny Proofs" script in the [DLDV Outage Guide](https://gitlab.login.gov/lg/identity-devops/-/wikis/Runbook:-AAMVA-DLDV-outage) to confirm connectivity.
This commit adds these states to the list of configured states.
=> LG-15260 Add NH and OK to list of AAMVA supported states

app/controllers/idv/in_person/ready_to_verify_controller.rb, app/mailers/user_mailer.rb, app/views/idv/in_person/ready_to_verify/show.html.erb, app/views/user_mailer/shared/_in_person_ready_to_verify.html.erb, config/application.yml.default, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, lib/identity_config.rb, spec/controllers/idv/in_person/ready_to_verify_controller_spec.rb, spec/i18n_spec.rb, spec/mailers/user_mailer_spec.rb, spec/views/idv/in_person/ready_to_verify/show.html.erb_spec.rb
[LG-15378](https://cm-jira.usa.gov/browse/LG-15378) Add temporary copy about post office closure to barcode email and barcode page
- Add config `in_person_proofing_post_office_closed_alert_enabled` in the default and set it to **true** so that this banner will be displayed once it is deployed in each environment (including production) on Tuesday 01/07/25. **To my understanding, we can then use AWS secrets to disable it on Friday 01/10/25 so we don't need to wait for a deployment to hide the alert**
- Add config `in_person_proofing_post_office_closed_alert_enabled: false` in the test section 
- Add Warning Banner to conditionally display Post Office Closed Message on Ready to Verify Email (this includes email reminder and EIPP email) (aka Barcode email)
- Add Warning Banner to …
=> LG-15378 Add Conditional Warning Banner to Ready to Verify View and Email

app/mailers/user_mailer.rb, app/views/user_mailer/in_person_post_office_closed.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/i18n_spec.rb, spec/mailers/previews/user_mailer_preview.rb, spec/mailers/user_mailer_spec.rb
[LG-15377](https://cm-jira.usa.gov/browse/LG-15377)
Added an in-person post office closed email template.
=> LG-15377 Add in-person post office closed email

app/controllers/concerns/two_factor_authenticatable_methods.rb
[LG-15362](https://cm-jira.usa.gov/browse/LG-15362)
As discussed in [slack](https://gsa-tts.slack.com/archives/C05MGJ72GU9/p1735663969801249) check for timeframe expired event for new device email was causing a lengthy query in many cases. @mitchellhenke added a maximum time window for the events that would limit those searches.
=> LG-15362 Bug fix: Limit query for timeframe expired event

app/forms/gpo_verify_form.rb, app/services/analytics_events.rb, spec/controllers/idv/by_mail/enter_code_controller_spec.rb
When a user enters a code during GPO there usually is not a service provider present in the SP session. This is because the letter we send instructs users to go directly to Login.gov to enter the code. As a result it is difficult to collect verification events for service providers in the out-of-band case since we cannot group events by `properties.service_provider`.
This commit adds the initiating service provider to the logged analytics event when a user enters a GPO code. The issuer is already logged on in-person and fraud review so this change allows us to group all out-of-band verification events by service provider.
=> LG-15396 Log the initiating SP on verify-by-mail code entry

db/primary_migrate/20250106232958_drop_proofing_components_table.rb, db/schema.rb
[LG-14367](https://cm-jira.usa.gov/browse/LG-14367)
Since #11564 we've stopped writing to this table, so now is the time to drop it.
This table was previously used as a temporary datastore for proofing component values as a user moves through IdV. We now dynamically derive those values from the Idv::Session, so this table is not needed any longer.
=> Drop proofing_components table

app/services/idv/proofing_components.rb, spec/services/idv/proofing_components_spec.rb
[LG-15051](https://cm-jira.usa.gov/browse/LG-15051)
-->
In #11674 we added a fallback in the case resolution_vendor was not set in IdV::Session to account for the 50/50 state.
Here we remove it, since that's been deployed.
=> LG-15051: Remove fallback to LexisNexis

package.json, yarn.lock
Removes outdated `resolutions` fields from `package.json`. Indirectly resolves a security advisory with `nanoid` dependency (CVE-2024-55565).
These packages were pinned to specific versions because they were subdependencies with security updates where our direct dependency had not yet updated to the fixed version. Since our direct dependencies are now using updated versions of these packages, the field is no longer necessary.
Previously: #9341
Related: #11719
Verify there are no audit results after installing Yarn packages:
1. `yarn install`
2. `yarn audit`
=> Remove outdated package.json version resolutions

app/services/idv/aamva_state_maintenance_window.rb
[LG-15261](https://cm-jira.usa.gov/browse/LG-15261)
My previous PR for this was https://github.com/18F/identity-idp/pull/11705 and explained it well. This cleans up a couple trivial things:
- A couple FIXME lines I'd addressed but not removed.
- `Sun#last` is valid with fugit so I can correctly define the window
=> LG-15261 | Trivial tweaks to AAMVA maintenance window file

Gemfile.lock
Reverts 18F/identity-idp#11699
Due to low-frequency errors that are potentially related to this upgrade, this PR reverts the original
=> Revert "Update newrelic_rpm gem to fix Bundler deprecation warning"

app/services/encrypted_doc_storage/doc_writer.rb, app/services/encrypted_doc_storage/local_storage.rb, app/services/encrypted_doc_storage/s3_storage.rb, config/application.yml.default, lib/identity_config.rb, spec/services/encrypted_doc_storage/doc_writer_spec.rb, spec/services/encrypted_doc_storage/local_storage_spec.rb, spec/services/encrypted_doc_storage/s3_storage_spec.rb
[Add Document Encryption Service for Doc Escrow](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/143)
This change adds an `EncryptedDocStorage` service that will be used for Doc Escrow.
- encrypts the front and back images of a document
- stores the images locally by default
- returns the image UUIDs and the encryption key
Open questions:
This implementation stole liberally from @jmhooper's [initial implementation of this service](https://github.com/18F/identity-idp/pull/7351/files#diff-49d7f0f1cea15bb7ca7d7c7c4108c78504fbeeae0066ae767cdd872dbf0cfaad). It currently relies on two images being passed in. Do we think that will always be the case? Is it possible that there might be single images (like a selfie?) 
I am wondering if this updated …
=> Add Document Encryption Service for Doc Escrow

app/javascript/packages/document-capture/components/acuant-capture.tsx, spec/javascript/packages/document-capture/components/acuant-capture-spec.jsx
Disable drag and drop functionality if selfie required. 
[LG-15270](https://cm-jira.usa.gov/browse/LG-15270)
Disable drag and drop functionality if selfie required. This functionality was already present as a part of the disable upload, doing a similar approach for the drag/drop functionality. 
=> lg-15270 disable drag and drop when selfie is required

Makefile, app/services/analytics_events.rb, lib/analytics_events_documenter.rb, spec/lib/analytics_events_documenter_spec.rb
- "Email and Password Authentication" description was wrong
- Similar to #11640
**Before**
The description included some notes from the `new_device` attribute
```bash
> make analytics_events
> jq -r '.events[] | select( .event_name | contains("Email and Password") ) | .description' < public/api/_analytics-events.json
the attempt was unsuccessful, since it cannot be known whether it's a new device.
Tracks authentication attempts at the email/password screen
```
**After**
The description is only the description
```bash
> make analytics_events
> jq -r '.events[] | select( .event_name | contains("Email and Password") ) | .description' < public/api/_analytics-events.json
Tracks authentication attempts at the email/password screen
```
=> Fix analytics event documentation formatting

app/services/doc_auth/lexis_nexis/doc_pii_reader.rb, spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb
The regex we used to read the height from a TrueID response did not account for a space that may appear between feet and inches. As a result height values like `5' 11"` were not read. This commit updates the regex to fix that.
=> Account for a space in the height returned by TrueID

app/services/proofing/aamva/applicant.rb, spec/services/proofing/aamva/applicant_spec.rb
[LG-15453](https://cm-jira.usa.gov/browse/LG-15453)
From the AAMVA DLDV guide regarding formatting the height:
> Height data should be 3 characters (i.e. 5 foot 7 inches is submitted as 507)
We were not previously zero-padding the inches, leading to us sending "57" in the 5' 7" case.
=> LG-15453: Fix issue formating heights for AAMVA DLDV

Gemfile, Gemfile.lock, app/controllers/saml_idp_controller.rb, app/services/analytics_events.rb, spec/controllers/saml_idp_controller_spec.rb
[Add specific saml_idp error for wrong Encryption Algorithm](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/131)
-->
This change is the follow-up to several weeks of tracking whether this change will https://github.com/18F/saml_idp/pull/126. [Running a query](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-1209600~timeType~'RELATIVE~tz~'LOCAL~unit~'seconds~editorString~'fields*20*40timestamp*2c*20*40message*2c*20*40logStream*2c*20*40log*0a*7c*20filter*20name*20*3d*20*27SAML*20Auth*27*0a*7c*20filter*20properties.event_properties.certs_different*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*2010000~queryId~'33d02f58-9385-440d-bf8f-95100245ed0e~source~(~'prod_*2fsr …
=> changelog: Bug Fixes, SAML Gem, Validates signature algorithm correctly

.rubocop.yml, Gemfile, Gemfile.lock, spec/views/two_factor_authentication/options/index.html.erb_spec.rb, spec/views/users/backup_code_setup/reminder.html.erb_spec.rb
Updates Rubocop to the latest version (1.70.0).
**Why?**
- Incorporate new features and bug fixes
- In particular, the [new support for passing target Ruby version as an environment variable](https://github.com/rubocop/rubocop/pull/13607) helps me with an issue I've been having with a local global pre-commit hook
**Included:**
- Version bump
- Fixes to affected files
- Enable new rule [`Lint/ConstantReassignment`](https://docs.rubocop.org/rubocop/cops_lint.html#lintconstantreassignment)
- Sync `TargetRubyVersion` to `.ruby-version`
Verify Rubocop lint checks all files and passes.
```
rubocop
```
=> Update Rubocop to latest version (1.70.0)

app/javascript/packages/document-capture/components/_file-input.scss
Removes unused styles from file input component.
Repeat of #11313 
Explanation:
- The selector `usa-file-input` refers to a custom element which does not exist
- Common `width` styles can be collapsed to a single style declaration
Verify no regressions in display of file input in document capture.
=> Remove unused file input styles

app/services/idv/aamva_state_maintenance_window.rb
The AAMVA maintenance window for TN had a typo where `duration_minutes` was named `duration`. This resulted in a `NoMethodError` when we tried to call `minutes` on `nil`.
=> Fix the TN AAMVA maintenance window scheulde

app/controllers/concerns/backup_code_reminder_concern.rb, app/controllers/users/backup_code_reminder_controller.rb, app/controllers/users/backup_code_setup_controller.rb, app/models/user.rb, app/services/analytics_events.rb, app/views/users/backup_code_reminder/show.html.erb, config/routes.rb, spec/controllers/concerns/backup_code_reminder_concern_spec.rb, spec/controllers/users/backup_code_reminder_controller_spec.rb, spec/controllers/users/backup_code_setup_controller_spec.rb, spec/features/two_factor_authentication/backup_code_sign_in_spec.rb, spec/features/two_factor_authentication/backup_code_sign_up_spec.rb, spec/models/user_spec.rb, spec/views/users/backup_code_reminder/show.html.erb_spec.rb
Supports [LG-10965](https://cm-jira.usa.gov/browse/LG-10965)
Refactors backup code reminder to be implemented as a standalone controller. This supports [LG-10965](https://cm-jira.usa.gov/browse/LG-10965), which expands the current reminder to apply for any sign-in, not just sign-ins without an associated service provider. 
**Why?**
- Adds missing analytics for visits and submissions to the reminder screen
- Optimizes database query on checking whether the user should be reminded for backup codes (apply timeframe on "second-last-sign-in" query)
- Avoid edge case where user may see reminder screen multiple times during same session (most notably as its usage would be extended in LG-10965)
- Incremental step toward skinny / single-responsibility controllers with [conventional action …
=> LG-10965: Extract new controller for backup code reminder

app/controllers/idv/in_person/ready_to_verify_controller.rb, app/mailers/user_mailer.rb, app/views/idv/in_person/ready_to_verify/show.html.erb, app/views/user_mailer/in_person_post_office_closed.html.erb, app/views/user_mailer/shared/_in_person_ready_to_verify.html.erb, config/application.yml.default, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, lib/identity_config.rb, spec/controllers/idv/in_person/ready_to_verify_controller_spec.rb, spec/mailers/previews/user_mailer_preview.rb, spec/mailers/user_mailer_spec.rb, spec/views/idv/in_person/ready_to_verify/show.html.erb_spec.rb
[LG-15379](https://cm-jira.usa.gov/browse/LG-15379)
Updates barcode page and email to remove the temporary alerts about the January 9th post office closure.
=> LG-15379 removes post office closure alerts from barcode page and email

Gemfile
We moved `faker` outside of the test group in #7698, and removed the non-test usage in #9154. This PR moves it back to the test group so we aren't unnecessarily installing it in non-test environments.
=> Move Faker gem from all environments to test

config/application.yml.default, lib/identity_config.rb
[LG-15272](https://cm-jira.usa.gov/browse/LG-15272)
Added an IdentityConfig variable for the maximum allowed number of socure users.
=> LG-15272 Add IdentityConfig variable for maximum allowed doc auth socure users

app/services/doc_auth/lexis_nexis/request.rb, app/services/proofing/aamva/proofer.rb, spec/services/doc_auth/lexis_nexis/request_spec.rb, spec/services/proofing/aamva/proofer_spec.rb
Following yesterday's discussion on noisy NewRelic errors, this PR removes the NewRelic reporting from both AAMVA and LexisNexis exceptions. This should not be a significant change in visibility as we have existing alarms on the infrastructure side.
=> Do not report LexisNexis or AAMVA exceptions to NewRelic

app/controllers/application_controller.rb, app/presenters/openid_connect_user_info_presenter.rb, app/presenters/saml_requested_attributes_presenter.rb, app/services/attribute_asserter.rb, app/services/openid_connect_attribute_scoper.rb, app/services/out_of_band_session_accessor.rb, spec/controllers/sign_up/passwords_controller_spec.rb, spec/features/openid_connect/openid_connect_spec.rb, spec/features/saml/ial1_sso_spec.rb, spec/presenters/openid_connect_user_info_presenter_spec.rb, spec/services/attribute_asserter_spec.rb, spec/services/openid_connect_attribute_scoper_spec.rb, spec/services/out_of_band_session_accessor_spec.rb
We have a service provider who would like to be able to receive the user's UI locale when they receive attributes after sign in. This partner has a `post_idv_follow_up_url` that is configured to redirect the user to Login.gov with a request for verified attributes. Since the user does not see a UI on their site and likely does not have an established session there they want to know what locale the user is using on Login.gov to provide a consistent experience.
This commit enables partners to request to user's locale using the `locale` OIDC scope. The locale is stored in the session and set to the current user's locale on every request. This ensures the latest value will be returned to service providers.
=> LG-15391 Allow SPs to request the user's locale

app/controllers/concerns/idv/document_capture_concern.rb, app/controllers/idv/document_capture_controller.rb, app/controllers/idv/hybrid_mobile/document_capture_controller.rb, app/controllers/idv/hybrid_mobile/socure/document_capture_controller.rb, app/controllers/idv/hybrid_mobile/socure/errors_controller.rb, app/controllers/idv/socure/document_capture_controller.rb, app/controllers/idv/socure/errors_controller.rb, app/javascript/packages/document-capture/components/document-capture.tsx, app/javascript/packages/document-capture/components/in-person-prepare-step.tsx, app/javascript/packages/document-capture/context/in-person.ts, app/javascript/packs/document-capture.tsx, app/presenters/socure_error_presenter.rb, app/services/analytics_events.rb, app/services/idv/session.rb, app/views/idv/document_capture/show.html.erb, app/views/idv/hybrid_mobile/document_capture/show.html.erb, app/views/idv/hybrid_mobile/socure/errors/show.html.erb, app/views/idv/shared/_document_capture.html.erb, config/routes.rb, spec/controllers/idv/document_capture_controller_spec.rb, spec/controllers/idv/hybrid_mobile/socure/document_capture_controller_spec.rb, spec/features/idv/doc_auth/socure_document_capture_spec.rb, spec/features/idv/hybrid_mobile/hybrid_socure_mobile_spec.rb, spec/support/features/document_capture_step_helper.rb, spec/views/idv/shared/_document_capture.html.erb_spec.rb
[LG-15337](https://cm-jira.usa.gov/browse/LG-15337)
Socure `Try again` page for hybrid mobile flow
If the system times out waiting for the data from Socure, show the try again page with, if available, an option to switch to  in person proofing.
`Try again` takes the user back to the Socure document capture page. `Try in person` takes the user to the beginning of the IPP flow, part of the hybrid_mobile document capture React app.
**Setup:**
- For example, using the `solipet` env:
```
git checkout dprice/lg-15337-try-again-hybrid
git pull
git checkout stages/solipet
git reset --hard dprice/lg-15337-try-again-hybrid
git push --force-with-lease
```
```
doc_auth_vendor: socure
doc_auth_vendor_default: socure
doc_auth_socure_wait_polling_timeout_minutes: 0
doc_auth_socure_job_sleep_seconds: 120 …
```
=> LG-15337: Socure `Try again` page for hybrid mobile flow

config/initializers/ab_tests.rb, spec/controllers/idv/hybrid_mobile/entry_controller_spec.rb
[LG-15515](https://cm-jira.usa.gov/browse/LG-15515)
Set the default bucket for AB routing to the default doc auth vendor.
1. Set doc_auth_vendor_switching_enabled to false in config
1. Set percentages for doc auth vendors to 0
1. Verify that the document capture controller for the default doc auth vendor is rendered
=> LG-15515: AB doc auth vendor bucketing default to configured default doc auth vendor

app/assets/stylesheets/components/_step-indicator.scss
[LG-15303](https://cm-jira.usa.gov/browse/LG-15303)
When the browser's text zoom level is very high, the step indicator steps can become very crowded.
This commit adds a min-width to individual steps that is based on the root font size to prevent this issue.
<details>
<summary>Google Chrome (Android)</summary>
<table>
<tbody>
<tr>
<th colspan="2">100% text zoom</th>
</tr>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<th colspan="2">200% text zoom</th>
</tr>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<th colspan="2">250% text zoom</th>
</tr>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<th colspan="2">300% text zoom</th>
</tr>
<tr>
<th>Before</th> …
=> LG-15303: Improve layout of step indicator at high text zoom levels

Makefile, docs/mobile.md
I had some trouble getting local testing working over HTTPS on iPhone, which (it seems), no longer has a "Proceed anyway" type link available when it encounters a self-signed certificate. Working around this involved:
1. Explicitly binding to my IP address rather than `0.0.0.0`
2. Not including a port number in the `CN` field of the self-signed cert.
3. Adding a `subjectAltName` to the self-signed cert.
This PR:
* Updates the docs to recommend binding to an explicit IP address to address item 1
* Updates SSL cert generation to address items 2+3
=> Fixes and updates for local testing over HTTPS

app/controllers/concerns/idv/document_capture_concern.rb, app/controllers/idv/document_capture_controller.rb, app/controllers/idv/in_person/state_id_controller.rb, app/controllers/idv/link_sent_controller.rb, app/controllers/idv/socure/document_capture_controller.rb, app/services/doc_auth/socure/responses/docv_result_response.rb, app/services/idv/session.rb, spec/controllers/idv/document_capture_controller_spec.rb, spec/controllers/idv/in_person/state_id_controller_spec.rb, spec/controllers/idv/link_sent_controller_spec.rb, spec/controllers/idv/socure/document_capture_controller_spec.rb, spec/policies/idv/flow_policy_spec.rb
[LG-15166](https://cm-jira.usa.gov/browse/LG-15166)
**Why**
* Currently, we compute the vendor for remote document verification
  using DocAuthRouter, which requires downstream business logic to
  depend on context that may or may not be available. In order to
  eliminate calls to DocAuthRouter in places like Idv::ProofingComponents,
  we first need to start storing the vendor directly in Idv::Session.
**How**
* Add a new key `doc_auth_vendor` to Idv::Session.
* Set the new key after successful document capture. If the user opted
  for in person proofing, it will be `usps` (managed directly in `Idv::InPerson::StateIdController`), otherwise we use the
  existing `Idv::DocAuthVendorConcern#doc_auth_vendor` method.
* Clear `Idv::Session#doc_auth_vendor` if the …
=> LG-15166: Store doc auth vendor in Idv::Session

config/application.yml.default, lib/aws/ses.rb, lib/identity_config.rb, lib/telephony/pinpoint/sms_sender.rb, lib/telephony/pinpoint/voice_sender.rb, spec/lib/aws/ses_spec.rb
Similar to changes we've made elsewhere to put AWS clients in connection pools with a retry on instance profile credential requests (#1887, #7292), this PR does similar for SES since we've seen similar issues with instance profile credential requests failing.
=> Retry instance profile credentials when sending emails via SES

lib/feature_management.rb
This makes it so that we are not required to have LOGIN_DOMAIN set to identitysandbox.gov for certain things to happen, so  we can use things like tooling.identitysandbox.gov and have newrelic/prefill_otp_codes_allowed_in_sandbox/current_env_allowed_to_see_gpo_code config work.
=> allow subdomains of identitysandbox.gov to work

app/javascript/packages/rails-i18n-webpack-plugin/extract-keys-webpack-plugin.js, app/javascript/packages/rails-i18n-webpack-plugin/extract-keys-webpack-plugin.spec.js
Updates Webpack i18n string extraction to match on a pattern of Webpack renamed source code for references to `t` in `@18f/identity-i18n`.
Example source:
```
children: i18n_t('in_person_proofing.headings.cta')
```
This isn't an especially resilient solution, but since we don't currently operate on the raw source of the files, we have to try to extract with some transformations from Webpack and Babel applied (see related #6359).
Verify that production-optimized build includes previously-missing strings in output.
```
NODE_ENV=production yarn build
find ./public/packs -type f -name 'document-capture-*.en.js' -exec grep "in_person_proofing.headings.cta" {} +
```
The result of the `find` command should be non-empty. (On `main`, the result is empty)
=> Fix string extraction for Webpack function renaming

.gitlab-ci.yml
Turns out there was a syntax error in this scheduled job, so this has been failing and CI hasn't alerted us
[Example failed run](https://gitlab.login.gov/lg/identity-idp/-/jobs/1624861)
=> Fix syntax error in Pinpoint scheduled job

app/jobs/data_warehouse/daily_sensitive_column_job.rb, spec/jobs/data_warehouse/daily_sensitive_column_job_spec.rb
This job currently fails when there is no S3 bucket configured, though it looks like it intends to skip. This PR makes a small change to where the check happens and skips upload to S3 if the configured bucket name is blank.
=> Skip S3 upload for daily sensitive column job if bucket name is blank

app/controllers/concerns/saml_idp_auth_concern.rb, app/services/saml_endpoint.rb, spec/controllers/saml_idp_controller_spec.rb
We currently raise an unhandled exception in some cases when receiving a request for a SAML year that is not currently configured. This PR stores the SAML years from `AppArtifacts` in a constant and adds a year check to the SAML controller that returns an error if the year is not available.
=> Return error when SAML year is invalid

app/javascript/packages/i18n/CHANGELOG.md, app/javascript/packages/i18n/index.spec.ts, app/javascript/packages/i18n/index.ts, scripts/enforce-typescript-files.mjs, spec/javascript/support/console.ts, spec/rails_helper.rb, webpack.config.js
Builds upon #11775 to increase visibility of missing translation strings at build-time and in JavaScript-enabled feature tests:
- At build-time, fails build if attempting to compile locale data where string data is missing. Previously, this only failed in test environments.
- At runtime, logs output to console if attempting to reference missing translation string. Previously, this would silently fail and return the original key, resulting in scenarios like what led to #11775.
The latter works well in combination with feature test behavior to fail tests where any console logging occurs. Unfortunately most tests which involve document capture disable this behavior (`allow_browser_log: true`), but there's at least one which would have caught the original issue …
=> Fail louder on missing translation data

app/views/users/webauthn_platform_recommended/new.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/i18n_spec.rb, spec/views/users/webauthn_platform_recommended/new.html.erb_spec.rb
Related to [LG-14655](https://cm-jira.usa.gov/browse/LG-14655)
Updates content for an alternative design to recommend Face or Touch Unlock to users authenticating or creating an account with SMS.
This was originally intended to be included in [LG-14655](https://cm-jira.usa.gov/browse/LG-14655).
Repeat testing plan in #11402.
=> Update alternative content for Face/Touch recommended test

app/controllers/concerns/idv/document_capture_concern.rb, app/controllers/concerns/idv/socure_errors_concern.rb, app/controllers/idv/document_capture_controller.rb, app/controllers/idv/hybrid_mobile/document_capture_controller.rb, app/controllers/idv/hybrid_mobile/socure/document_capture_controller.rb, app/controllers/idv/hybrid_mobile/socure/errors_controller.rb, app/controllers/idv/socure/document_capture_controller.rb, app/controllers/idv/socure/errors_controller.rb, app/jobs/socure_docv_results_job.rb, app/services/doc_auth/socure/responses/docv_result_response.rb, spec/features/idv/doc_auth/socure_document_capture_spec.rb, spec/features/idv/hybrid_mobile/hybrid_socure_mobile_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb, spec/services/doc_auth/socure/responses/docv_result_response_spec.rb
[LG-14973](https://cm-jira.usa.gov/browse/LG-14973)
Add the PII checks in the `DocPiiForm` to the Socure flow.
Verify that the tests in in `spec/services/doc_auth/socure/responses/docv_result_response_spec.rb` adequately check the functionality and pass.
=> LG-14973 Add PII check to Socure flow

lib/action_account.rb, lib/script_base.rb, spec/lib/action_account_spec.rb, spec/lib/script_base_spec.rb
[LG-15538](https://cm-jira.usa.gov/browse/LG-15538)
Adds a warning line with emoji when this script is running locally (it is expected to be run remotely via SSM in the devops repo instead of directly)
Example locally:
```bash
> ./bin/data-pull uuid-convert abc def
⚠️ WARNING: returning local data for data-pull
*Task*: `uuid-convert`
*UUIDs*: 
+--------------+-------------+---------------+---------+
| partner_uuid | source      | internal_uuid | deleted |
+--------------+-------------+---------------+---------+
| abc          | [NOT FOUND] | [NOT FOUND]   |         |
| def          | [NOT FOUND] | [NOT FOUND]   |         |
+--------------+-------------+---------------+---------+
```
=> LG-15538: Add warning when returning local data

app/helpers/script_helper.rb, spec/helpers/script_helper_spec.rb
Fixes an issue where scripts rendered using `preload_links_header: false` option unexpectedly output a `preload_links_header="false"` attribute on the rendered script tag.
This regressed in #11504, where we switched from using `javascript_include_tag` to `tag.script`. The `preload_links_header` behavior was intended to mimic that of `javascript_include_tag`, but did not recreate the behavior of deleting the option from attributes before rendering the script tag ([source](https://github.com/rails/rails/blob/33beb0a38db1c058123a8e3cc298cad918adfe32/actionview/lib/action_view/helpers/asset_tag_helper.rb#L117)).
2. Right click and view source for page
3. Verify that `track-errors.js` script tag toward the bottom of page `<body>` content does not include a …
=> Avoid printing preload_links_header attribute for scripts

app/controllers/idv/hybrid_mobile/socure/document_capture_controller.rb, spec/features/idv/hybrid_mobile/hybrid_socure_mobile_spec.rb
[LG-15159](https://cm-jira.usa.gov/browse/LG-15159)
Added check to see if user already made it to capture_complete on show, if so user is now redirected back to capture complete. Uncommented rspec tests meant for testing as well as adding more to it to test full AC of ticket.
=> Lg 15159 A user who has reached the capture complete page in hybrid flow should not be able to recapture

spec/mailers/previews/user_mailer_preview.rb
Alternative to https://github.com/18F/identity-idp/pull/11786
- Mailer previews occasionally load in production environments (sandbox) but in #11757, we moved the Faker gem to the test group (which breaks these previews in sandbox)
- Removing the usage of Faker in the previews helps keep the previews working, and keeps the production dependencies smaller
=> Remove Faker use in UserMailerPreview

app/controllers/application_controller.rb, app/controllers/concerns/backup_code_reminder_concern.rb, app/views/users/backup_code_reminder/show.html.erb, spec/controllers/concerns/backup_code_reminder_concern_spec.rb, spec/features/two_factor_authentication/backup_code_sign_in_spec.rb, spec/views/users/backup_code_reminder/show.html.erb_spec.rb
[LG-10965](https://cm-jira.usa.gov/browse/LG-10965)
Updates backup code reminder screen to use new controller actions implemented in #11738 to support use with sign-ins associated with a partner application, and updated after-sign-in logic to include partner-associated sign-ins to be considered for backup code reminder.
Repeat testing plan from #11738, but also verify that it shows reminder when initiating sign-in from partner application (e.g. [sample OIDC application](https://github.com/18F/identity-oidc-sinatra)), and that you eventually return to the partner application after making your reminder choice.
Note the partner logo in the screenshot, indicating that it is a partner-associated sign-in request:
=> LG-10965: Show backup code reminder for partner-initiated requests

app/jobs/risc_delivery_job.rb, config/newrelic.yml, lib/identity_job_log_subscriber.rb, spec/jobs/risc_delivery_job_spec.rb, spec/lib/identity_job_log_subscriber_spec.rb
A follow-up to an older change in #10806, this PR makes some bigger changes to exception handling in the `RiscDeliveryJob` to reduce the volume of noisy exceptions sent to NewRelic. Primarily, it wraps any of the `NETWORK_ERRORS` in a new `DeliveryError`. The original exception is still kept in [Exception#cause](https://ruby-doc.org/3.4.1/Exception.html#method-i-cause). The new error class is then added to the ignored list in NewRelic so that we still get any of the exceptions in `NETWORK_ERRORS` in other contexts if they're outside of this job.
I've added the flag to include the error message in the `retry_stopped` callback for job logging as that's primarily the event that will be useful when we give up on retrying due to network failures.
=> Reduce RiscDeliveryJob exception noise in NewRelic

app/controllers/concerns/saml_idp_auth_concern.rb, app/forms/openid_connect_authorize_form.rb, app/services/saml_request_parser.rb, spec/forms/openid_connect_authorize_form_spec.rb
Small performance improvement to avoid queries for ServiceProvider where issuer is not present. We see this sometimes around SP requests based on looking into NewRelic metrics and local testing to confirm. Also moves a frequently used Regexp into a constant to avoid having to re-create it every time.
=> Avoid queries for ServiceProvider with blank issuer

app/services/analytics_events.rb, spec/controllers/users/reset_passwords_controller_spec.rb
Updates `AnalyticsEvents` method signatures to avoid assigning a default empty hash value `{}`, preferring `nil` instead to ensure values are omitted from logs.
As with #11799, this serves to reduce the size (and cost) of our logging payloads by removing values which aren't relevant for querying. It is not possible to query for an empty hash value in CloudWatch Insights.
This is also an iterative step in the migration away from `errors` to `error_details` which will involve making `error_details` a guaranteed return value from `FormResponse#to_h`.
=> Avoid empty hash default values in analytics methods

app/controllers/users/emails_controller.rb, app/views/users/emails/verify.html.erb, spec/controllers/users/emails_controller_spec.rb, spec/views/users/emails/verify.html.erb_spec.rb
[LG-15173](https://cm-jira.usa.gov/browse/LG-15173)
Updates the add email confirmation screen to link "Back" when adding during partner email selection flow, to ensure that the user can seamlessly continue to the partner application.
Verify that the "Check your email" confirmation screen links to:
- "Return to your profile" account page if added from the account dashboard
- "Back" to the email selection screen if added from the consent screen
- "Back" to the connected accounts page if added from the connected accounts page
1. Run [sample partner application](https://github.com/18F/identity-oidc-sinatra) in a separate terminal process
2. Go to http://localhost:9292
3. Click "Sign in"
4. Create an account or sign in with a user who has not already granted consent to the sample partner …
=> LG-15173: Adding email in select flow links back to select page

spec/controllers/event_disavowal_controller_spec.rb, spec/controllers/idv/by_mail/request_letter_controller_spec.rb, spec/controllers/idv/by_mail/resend_letter_controller_spec.rb, spec/controllers/idv/cancellations_controller_spec.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/controllers/idv/otp_verification_controller_spec.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/controllers/idv/phone_controller_spec.rb, spec/controllers/idv/session_errors_controller_spec.rb, spec/controllers/idv/sessions_controller_spec.rb, spec/controllers/openid_connect/logout_controller_spec.rb, spec/controllers/redirect/help_center_controller_spec.rb, spec/controllers/redirect/marketing_site_controller_spec.rb, spec/controllers/redirect/return_to_sp_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/controllers/sign_out_controller_spec.rb, spec/controllers/users/backup_code_setup_controller_spec.rb, spec/controllers/users/email_language_controller_spec.rb, spec/controllers/users/rules_of_use_controller_spec.rb, spec/controllers/users/sessions_controller_spec.rb, spec/features/idv/cancel_spec.rb, spec/support/fake_analytics_spec.rb, spec/support/have_logged_event_matcher.rb
Changes `have_logged_event` analytics matcher to fail when using a `hash_including` matcher value which includes a hash exactly equal to the one that is logged.
Asserting against logs is intended to provide confidence in the expected shape of our analytics logging payload. `hash_including` allows for undesirable drift between the expected and actual logging payload, which may result in false positives or a general lack of test coverage. `hash_including` can be useful in cases where asserting specific differences in logged payload values in `context` blocks, in which case it is generally expected that the hash logged would include more properties than those specified in the `hash_including` argument.
It is easier to [review these changes with whitespace changes …
=> Raise error when analytics test hash_including is exactly equal

docs/frontend.md
Adds an introductory section to the existing [front-end documentation](https://github.com/18F/identity-idp/blob/main/docs/frontend.md) with a high-level overview of the architecture and folder structure. Much of this information is already detailed in subsequent sections, but it can be helpful for someone new to our project to understand the tools and process at a high level.
This is prompted partly by a recent request by a team to better understand our JavaScript build pipeline. While this doesn't address the full scope of "build pipeline", it can hopefully serve as an entry point to build upon.
Review [updated information](https://github.com/18F/identity-idp/blob/aduth-frontend-docs-intro/docs/frontend.md) for accuracy and helpfulness.
=> Add introductory high-level overview for frontend documentation

app/controllers/users/webauthn_setup_controller.rb, app/forms/webauthn_setup_form.rb, app/models/webauthn_configuration.rb, app/services/analytics_events.rb, spec/controllers/users/webauthn_setup_controller_spec.rb, spec/forms/webauthn_setup_form_spec.rb, spec/models/webauthn_configuration_spec.rb
[LG-14052](https://cm-jira.usa.gov/browse/LG-14052)
Updates Security Key and Face or Touch Unlock setup to automatically convert to the other if the reported [transports](https://w3c.github.io/webauthn/#enum-transport) are inconsistent with the expected platform attachment.
As outlined in the Testing Plan, despite hints that we provide to the browser to try to ensure that the user sets up a WebAuthn credential with the intended platform attachment, it is still often possible for a user to set up an authenticator of the other type (e.g. Chrome's "Save another way"). In these scenarios, converting the credential to the inferred type will ensure that the user has a better sign-in experience and that our usage tracking is more accurate to the actual type of authenticator used. [Previous …
=> LG-14052: Convert mismatched WebAuthn platform attachment

app/controllers/concerns/idv/document_capture_concern.rb, app/controllers/idv/how_to_verify_controller.rb, spec/controllers/idv/how_to_verify_controller_spec.rb, spec/features/idv/doc_auth/how_to_verify_spec.rb, spec/features/idv/doc_auth/socure_document_capture_spec.rb
[LG-15375](https://cm-jira.usa.gov/browse/LG-15375)
We found a bug where if a user was bucketed into Socure for doc auth, when they tried to opt-in to IPP from the How To Verify page, they would be redirected to Socure. This fixes it.
- Both requiring a selfie and not, run through IdV in an environment configured for Socure only. 
- From the How To Verify page, attempt to opt in to IPP and verify that you are able.
- Go back and choose to continue online
- From the Hybrid Handoff page, attempt to opt in to IPP and verify that you are able.
=> LG-15375: Ensure Socure user can opt in to IPP

app/forms/idv/doc_pii_form.rb, spec/forms/idv/doc_pii_form_spec.rb
[LG-15277](https://cm-jira.usa.gov/browse/LG-15277)
The Socure  API in Sandbox environment returns test PII with an ID expiration date in the past.  This is a temporary solution, until the Socure Sandbox API is fixed, to be able to test DocV scenarios in dev.
1. Update application.yml as follows:
```
socure_docv_verification_data_test_mode: true
socure_docv_verification_data_test_mode_tokens: '["1111-1111"]'
``` 
2. Complete IdV until Socure document capture is rendered (ie: /verify/socure/document_capture)
3. visit path /verify/socure/document_capture_update?docv_token=1111-1111
4. verify ssn page is displayed
5. Verify ticket exists to undo this temporary solution - [LG-15600](https://cm-jira.usa.gov/browse/LG-15600)
=> bypass ID expiration by configuration in test mode

app/jobs/reports/sp_proofing_events_by_uuid.rb, config/application.yml.default, config/initializers/job_configurations.rb, lib/identity_config.rb, lib/reporting/sp_proofing_events_by_uuid.rb, spec/jobs/reports/sp_proofing_events_by_uuid_spec.rb, spec/lib/reporting/sp_proofing_events_by_uuid_spec.rb
We have an agency partner who requested a specialized report the involves a table with columns representing proofing events and rows representing users for the partner where the values in each cell correspond to whether that user encountered that event in the given time period. We have been manually servicing this request for a little while. This commit adds tooling to generate this report automatically so it does not require manual processing.
This commit does not add the report to the job schedule with the intention being to test it first before scheduling it to run automatically.
=> LG-15394 Add tooling for an SP proofing events by UUID report

app/controllers/api/internal/two_factor_authentication/auth_app_controller.rb, app/controllers/api/internal/two_factor_authentication/piv_cac_controller.rb, app/controllers/api/internal/two_factor_authentication/webauthn_controller.rb, app/controllers/concerns/mfa_deletion_concern.rb, app/controllers/users/auth_app_controller.rb, app/controllers/users/backup_code_setup_controller.rb, app/controllers/users/edit_phone_controller.rb, app/controllers/users/piv_cac_controller.rb, app/controllers/users/webauthn_controller.rb, spec/controllers/concerns/mfa_deletion_concern_spec.rb
Related to [LG-14052](https://cm-jira.usa.gov/browse/LG-14052)
Refactors to create a new `MfaDeletionConcern#handle_successful_mfa_deletion` method. This builds upon #11795, where the method was initially introduced to handle "Undo" behaviors associated with a mismatched WebAuthn configuration.
Deleting a multi-factor authentication method always incurs the following:
- Creating a user history event
- Revoking remembered device
- Dispatching a RISC security event
Previously, these were duplicated across controllers for each method, which creates risk of human error for failing to account for one or more of these actions.
As an example, refactoring this behavior reveals that we don't have a user event associated with deleting backup codes, which became obvious when abstracting this method …
=> Extract mixin for common MFA deletion behaviors

lib/data_pull.rb, lib/data_requests/deployed/create_mfa_configurations_report.rb, spec/lib/data_pull_spec.rb, spec/lib/data_requests/deployed/create_mfa_configurations_report_spec.rb
https://gitlab.login.gov/lg-teams/agnes/data-warehouse-ag/-/issues/599
To make it easier to investigate support cases, this PR creates a new report that can be run by passing a set of UUIDs. It is based on the existing MFA Report used by the IG User Report. I've also added the `platform_authenticator` field to WebAuthn configurations in the report so we can tell what kind of authenticator it is. I've included a sample of what the report looks like below:
<details>
<summary>Sample Report</summary>
```json
[
{
"phone_configurations": [
{
"id": 1,
"phone": "+1 555-000-0000",
"created_at": "2025-01-01T00:00:00.000Z",
"confirmed_at": "2025-01-01T00:00:00.000Z"
}
],
"auth_app_configurations": [
{
"name": "My auth app",
"created_at": "2025-01-01T00:00:00.000Z"
}
], …
```
=> Create MFA Report script

app/jobs/reports/sp_idv_weekly_dropoff_report.rb, config/application.yml.default, config/initializers/job_configurations.rb, lib/identity_config.rb, lib/reporting/sp_idv_weekly_dropoff_report.rb, spec/jobs/reports/sp_idv_weekly_dropoff_report_spec.rb, spec/lib/reporting/sp_idv_weekly_dropoff_report_spec.rb
We have a partner who requested a specialized IdV drop-off report for their service providers. This report needs to run every Monday and collect weekly data from a specified date up through the previous week.
We have been running this report manually for a few weeks now. This commit moves the code the generates this report into the IdP so it can be run automatically.
=> LG-15395 Add specialized SP IdV Dropoff Report

app/controllers/idv/hybrid_mobile/socure/document_capture_controller.rb, spec/controllers/idv/hybrid_mobile/socure/document_capture_controller_spec.rb, spec/controllers/idv/socure/document_capture_controller_spec.rb
[LG-15179](https://cm-jira.usa.gov/browse/LG-15179)
This fix makes sure a user is allowed to complete DocV after they timeout and the timeout is over.
=> LG-15179 Timed out hybrid user should be able to retry docv

app/services/doc_auth/lexis_nexis/doc_pii_reader.rb, spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_attention_barcode.json, spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_attention_barcode_with_face_match_fail.json, spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_failed_to_ocr_dob.json, spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_failure_no_liveness.json, spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_failure_no_liveness_low_dpi.json, spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_failure_with_all_failures.json, spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_failure_with_face_match_fail.json, spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_failure_with_face_match_pass.json, spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_failure_with_liveness.json, spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_success.json, spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb
We have received clarification on the following from our vendor:
1. The `Fields_Sex` attribute is no longer available in the `ID_AUTH_FIELDS` group
2. The `Sex` attribute available in the `AUTHENTICATION_RESULT` group can be used to reliably determine the sex displayed on the document
3. The `Sex` attribute in the `AUTHENTICATION_RESULT` group takes on the values of `Male` or `Female`.
This commit updates the `DocPiiReader` and the TrueID response fixtures to reflect this.
=> LG-15457 Read the sex attribute from the TrueID authentication result

app/controllers/concerns/idv/doc_auth_vendor_concern.rb, app/services/idv/socure_user_set.rb, spec/controllers/concerns/idv/doc_auth_vendor_concern_spec.rb
[LG-15274](https://cm-jira.usa.gov/browse/LG-15274)
Once a user is bucketed into using socure, this adds their UUID to the socure users redis set to keep track of how many socure users we have.
=> LG-15274 add socure user to redis set

app/controllers/concerns/idv/doc_auth_vendor_concern.rb
Link to the relevant ticket: 
BUG FIX FOR:
[LG-15274](https://cm-jira.usa.gov/browse/LG-15274)
Adding document_capture_user.uuid fallback if current_user is nil
=> Bug Fix for LG-15274 add user to socure user set

app/controllers/concerns/idv/doc_auth_vendor_concern.rb, spec/controllers/concerns/idv/doc_auth_vendor_concern_spec.rb
- Socure: Changing is_defined to defined method ([#11828](https://github.com/18F/identity-idp/pull/11828))
- Socure: Socure user set uuid nil issue fix (#11827) ([#11827](https://github.com/18F/identity-idp/pull/11827))
=> Deploy RC 448.1 to Production

app/models/event.rb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
[LG-11867](https://cm-jira.usa.gov/browse/LG-11867)
Updates `Event` model to add support for `webauthn_platform_added` and `webauthn_platform_removed` event types, including corresponding label texts.
This is split from #11823 to avoid issues during deployment where an old server may not be aware of these event types when displaying user activity history.
Repeat Testing Plan from #11823 and then switch to this branch. The History page should continue to show expected labels. On `main`, this would show invalid label strings.
See #11823 (there are no expected user-facing impact of these changes alone)
=> LG-11867: Create separate user events for platform authenticators (event type, strings)

app/decorators/event_decorator.rb, spec/decorators/event_decorator_spec.rb
Related to [LG-11867](https://cm-jira.usa.gov/browse/LG-11867)
Updates logic of `EventDecorator#event_type` to avoid trying to return a human-readable label for an event type that is not known to the application.
This isn't a typical behavior, but the included inline code comment explains the circumstances where it can occur:
```
```
As an aside, tracking existing references to `EventDecorator#event_type` can be tricky since the name is the same as `Event#event_type`, where only the decorator returns a human-readable label. This label is used on the History and Devices pages. In the future, it could be worth renaming this method to more clearly differentiate (e.g. `readable_event_type`, or `event_type_label`)
Repeat Testing Planf rom #11823 and then switch to this branch. The History page …
=> Avoid showing label for unknown event type

app/presenters/openid_connect_user_info_presenter.rb, app/services/analytics_events.rb, app/services/attribute_asserter.rb, app/services/authn_context_resolver.rb, spec/controllers/openid_connect/token_controller_spec.rb, spec/factories/service_provider_identities.rb, spec/forms/openid_connect_token_form_spec.rb, spec/presenters/openid_connect_user_info_presenter_spec.rb, spec/services/attribute_asserter_spec.rb, spec/services/authn_context_resolver_spec.rb
[Add tracking for AAL resolution](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/146)
This change:
- Adds a method to determine the asserted AAL level via the AuthnContextResolver
- Adds tracking in the OIDC and SAML attributes presenters in order to indicate when there is a mismatch
Note: In the OIDC code flow, this attribute is set in the [authorization_form class](https://github.com/18F/identity-idp/blob/main/app/forms/openid_connect_authorize_form.rb#L125). My hope is that once this bug is fixed, we will be able to remove that value and associated code.
=> Tracking AAL attribute value differences

app/controllers/api/internal/two_factor_authentication/webauthn_controller.rb, app/controllers/users/webauthn_controller.rb, app/controllers/users/webauthn_setup_controller.rb, app/controllers/users/webauthn_setup_mismatch_controller.rb, app/forms/two_factor_authentication/webauthn_delete_form.rb, app/forms/webauthn_setup_form.rb, spec/controllers/api/internal/two_factor_authentication/webauthn_controller_spec.rb, spec/controllers/users/webauthn_controller_spec.rb, spec/controllers/users/webauthn_setup_controller_spec.rb, spec/controllers/users/webauthn_setup_mismatch_controller_spec.rb, spec/forms/two_factor_authentication/webauthn_delete_form_spec.rb, spec/forms/webauthn_setup_form_spec.rb
[LG-11867](https://cm-jira.usa.gov/browse/LG-11867)
Adds new user event types for Face or Touch Unlock platform authenticators.
The implementation of Face or Touch Unlock built upon support for WebAuthn-based security keys. In the implementation of Face or Touch Unlock, the user experience was segmented based on whether or not the authenticator is a [platform authenticator](https://www.w3.org/TR/webauthn-3/#sctn-authenticator-attachment-modality). However, prior to these changes, that did not extend to the user events created for adding an removing the authentication method. As a result, adding or removing Face or Touch Unlock would be reflected on a user's Activity page as "Hardware security key added" and "Hardware security key removed". The intent of these changes is to add new event …
=> LG-11867: Create separate user events for platform authenticators

app/controllers/concerns/two_factor_authenticatable_methods.rb, app/controllers/two_factor_authentication/backup_code_verification_controller.rb, app/controllers/two_factor_authentication/otp_verification_controller.rb, app/controllers/two_factor_authentication/personal_key_verification_controller.rb, app/controllers/two_factor_authentication/piv_cac_verification_controller.rb, app/controllers/two_factor_authentication/totp_verification_controller.rb, app/controllers/two_factor_authentication/webauthn_verification_controller.rb, app/controllers/users/sessions_controller.rb, app/forms/sign_in_recaptcha_form.rb, app/services/analytics_events.rb, app/services/recaptcha_annotator.rb, config/application.yml.default, lib/identity_config.rb, spec/controllers/concerns/two_factor_authenticatable_methods_spec.rb, spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb, spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb, spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb, spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb, spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb, spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb, spec/controllers/users/sessions_controller_spec.rb
changelog: Upcoming Features, Recaptcha, Annotate sign-in reCAPTCHA from 2-factor attempts
[Annotate sign-in reCAPTCHA after fully authenticated](https://cm-jira.usa.gov/browse/LG-15254)
1. Store the `recaptcha_assessment_id` in session.
2. Annotate with INITIATED_TWO_FACTOR when attempting any MFA method if there is a `recaptcha_assessment_id` in session.
3. Annotate with PASSED_TWO_FACTOR or FAILED_TWO_FACTOR depending on success when completing any MFA method if there is a `recaptcha_assessment_id` in session.
4. Recording the `recaptcha_annotation` along with the pre-existing event whenever an annotation is made.
=> Annotate sign-in reCAPTCHA from 2-factor attempts

app/controllers/concerns/rate_limit_concern.rb, app/controllers/idv/link_sent_poll_controller.rb, app/forms/idv/api_image_upload_form.rb, spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb
[LG-15476](https://cm-jira.usa.gov/browse/LG-15476)
Modified hybrid flow rate limit logic to accept successful submission on final attempt. Had to move around some logic to keep logging intact. Added spec test to cover hybrid flow final submission.
=> Lg 15476 hybrid rate limit final attempt bug fix

app/policies/idv/flow_policy.rb, app/services/doc_auth/mock/result_response.rb
During load testing, these two spaces currently generate a lot of object allocations, particularly the `STEPS` element. It seemed safe to move this into a constant in that looks like it shouldn't change, but I am less familiar with this area of things. In an IdV-only load-test, the allocations saved here might be up to as much of 33% of the memory allocated.
=> Reduce object allocations in identity verification

app/services/encryption/encryptors/aes_encryptor.rb, spec/services/encryption/encryptors/aes_encryptor_spec.rb
Similar to #11841, though with a different approach to reducing memory usage. We currently check whether the layers of encoded/encrypted content can be Base64 decoded before attempting to Base64 decode it. This is mostly redundant, and we can use the exceptions for control flow as they are used currently.
=> Reduce allocations in AesEncryptor

app/controllers/users/email_confirmations_controller.rb, spec/controllers/users/email_confirmations_controller_spec.rb
[LG-15672](https://cm-jira.usa.gov/browse/LG-15672)
Fixes an issue where users may be redirected to the email selection experience even if the feature is disabled, resulting in a 404.
Related Slack thread: https://gsa-tts.slack.com/archives/C01710KMYUB/p1738779905418149
Test with and without `feature_select_email_to_share_enabled` enabled:
1. Have [sample application](https://github.com/18F/identity-oidc-sinatra) running in separate process
2. Go to http://localhost:9292
3. Click "Sign in"
4. Sign in or create an account
5. After returned to sample application, go to http://localhost:3000
6. Add email address from account dashboard
7. Confirm email address
8. Observe that:
- If feature is disabled, you're redirected to account dashboard with email selected
- If feature is enabled, you're …
=> LG-15672: Only redirect to select email screen if feature enabled

app/controllers/idv/link_sent_controller.rb, spec/features/idv/in_person_spec.rb
[LG-15479](https://cm-jira.usa.gov/browse/LG-15479)
We have a rare but persistent issue where users get stuck on the "Verify your information" screen because the `zipcode` stored with their PII is `nil`.
One way the user can end up in this situation is:
1. Use hybrid handoff to upload identity documents that are valid, but have a barcode-related "attention" warning
2. Opt then to enroll in in-person proofing (from their mobile device) instead
3. Select a USPS location on their mobile device
4. When prompted, return to their desktop and click the "Continue" button
In this case, the user would end up in a state where they have _both_ an IPP enrollment _and_ `pii_from_doc` set in their session. This would cause the system to get confused, and attempt to use …
=> LG-15479: Fix nil zipcode error during identity resolution

app/javascript/packages/document-capture/components/file-input.tsx
[LG-14933](https://cm-jira.usa.gov/browse/LG-14933)
The document capture success message was not displayed, but was taking up space on the screen, which was not intended as part of the design.
<details>
</details>
<details>
</details>
=> LG-14933 Remove extra space from document capture form.

app/jobs/reports/ab_tests_report.rb, app/views/report_mailer/tables_report.html.erb, config/initializers/job_configurations.rb, lib/ab_test.rb, lib/reporting/ab_tests_report.rb, spec/jobs/reports/ab_tests_report_spec.rb, spec/lib/ab_test_spec.rb, spec/lib/reporting/ab_tests_report_spec.rb, spec/mailers/previews/report_mailer_preview.rb, spec/mailers/report_mailer_spec.rb
[LG-15559](https://cm-jira.usa.gov/browse/LG-15559)
Adds the ability to generate email reports for A/B test results to be sent to a team contact email on a regular basis.
This is intended to help:
- Ensure accountability to create queries ahead of an A/B test being active in production, to guarantee that we're able to produce usable analytics for the test
- Reduce manual engineer effort to actively monitor an A/B test after a few hours and on subsequent days of a test being active to make sure that the data being reported is in line with expected values
- Be able to report data directly to relevant stakeholders automatically without additional involvement from an engineer
- Improve visibility of ongoing A/B test progress to an entire team and other stakeholders
End-to-end testing is …
=> LG-15559: Add support for A/B tests daily reporting

app/services/analytics_events.rb, app/services/form_response.rb, spec/forms/add_user_email_form_spec.rb, spec/forms/openid_connect_authorize_form_spec.rb, spec/forms/openid_connect_token_form_spec.rb, spec/forms/otp_delivery_selection_form_spec.rb, spec/forms/password_form_spec.rb, spec/forms/password_reset_email_form_spec.rb, spec/forms/personal_key_form_spec.rb, spec/forms/register_user_email_form_spec.rb, spec/forms/reset_password_form_spec.rb, spec/forms/totp_setup_form_spec.rb, spec/forms/two_factor_login_options_form_spec.rb, spec/forms/update_user_password_form_spec.rb, spec/forms/webauthn_setup_form_spec.rb, spec/forms/webauthn_visit_form_spec.rb, spec/services/form_response_spec.rb, spec/services/saml_request_validator_spec.rb
Updates `FormResponse#to_h` to avoid including `errors` in the serialized hash if `error_details` is present.
This is a continuation (cleanup) of #11810, which effectively omitted `errors` from analytics logging, but continued to assign the value as `nil`. The changes here avoid assigning the value altogether.
Related: https://github.com/18F/identity-idp/pull/11810#discussion_r1932673815
=> Omit errors from serialized form response if details present

app/controllers/idv/document_capture_controller.rb, app/controllers/idv/in_person/address_controller.rb, app/controllers/idv/in_person/state_id_controller.rb, app/policies/idv/flow_policy.rb, app/services/idv/session.rb, spec/controllers/idv/document_capture_controller_spec.rb, spec/controllers/idv/in_person/address_controller_spec.rb, spec/controllers/idv/in_person/state_id_controller_spec.rb, spec/policies/idv/flow_policy_spec.rb, spec/support/flow_policy_helper.rb
[LG-15294](https://cm-jira.usa.gov/browse/LG-15294)
During FSM clean-up we discovered that the [flow policy](https://handbook.login.gov/articles/identity-verification-flow-policy.html) was not yet being fully used within the in_person/state_id_controller and in_person/address_controller. The step_info was included but it wasn't yet being called. These changes address that by adding the confirm_step_allowed before_action and refactoring the undo_step lambdas in both the state_id_controller and address_controller, so they could be properly called in the clear_future_steps! Flow Policy step.
There is no new or changed functionality for manual testing - you will want to test the IPP flow to make sure everything is working as usual.
=> LG-15294: Integrate Flow Policy with IPP steps - State ID and Address

app/jobs/data_warehouse/table_summary_stats_export_job.rb, spec/jobs/data_warehouse/table_summary_stats_export_job_spec.rb
[[LG-14947](https://gitlab.login.gov/lg-teams/agnes/data-warehouse-ag/-/issues/545)]
The stale data check was showing in agnes/int environments that if we started created alarms team agnes would suffer daily alerts.
- Added timestamp columns so that we could use them downstream when querying redshift
- Added tests to reflect timestamp functionality
- Added a table exclusion list to remove certain tables like join tables that contain event data but dont contain a relevant timestamp column
=> LG-14947 - stale data trigger update idp job

app/services/idv/session.rb
Sort of a continuation of #11841 and #11844, this PR removes a frequently unnecessary hash allocation. `#fetch(key, default)` will always instantiate the default even if the key exists. The behavior is not identical in that a `nil` value in the hash will be returned if it is there and this will fall through and return the empty hash. We should never be storing `nil` here as we use [delete](https://github.com/18F/identity-idp/blob/e2452fb9f1f210ff3e197fa66eb4d50846e18f2f/app/services/idv/session.rb#L188) when clearing the session value.
We could alternatively use the block form `#fetch(key) { |key| ... }` as a "lazy" instantiation of the hash, but it didn't feel necessary in this case.
The pattern of a default empty hash value appears in other places in the codebase, but `session` is …
=> Remove frequently unnecessary hash allocation

app/services/idv/session.rb, spec/presenters/idv/by_mail/letter_enqueued_presenter_spec.rb, spec/services/idv/session_spec.rb, spec/views/idv/by_mail/letter_enqueued/show.html.erb_spec.rb
- [Per comment on #11854](https://github.com/18F/identity-idp/pull/11854#discussion_r1947096203), the dynamic access and string manipulation makes these methods a hotspot
- Dynamically defining these methods one should hopefully let the JIT optimize this a little better, and lets us use the default implementations for #method_missing and #respond_to_missing?
NB, I have not performance tested this myself to confirm the hypothesis, I am open to checking that before merging. The unit test coverage is solid so this should still work
=> Remove method_missing usage in Idv::Session

lib/ab_test.rb, spec/lib/ab_test_spec.rb, spec/services/analytics_spec.rb
Updates the behavior of `AbTest` to not include bucket assignments in logs if `should_log` is not defined.
Previously, if a test did not define `should_log`, the A/B test assignment for that test would be included in every application event. To avoid unnecessary noise in unrelated analytics events, this pull request proposes to change the default from an opt-out to an opt-in.
Existing tests already assign `should_log` and should be unimpacted by these changes.
Optionally, delete the `should_log` option for one of the existing test configuration and verify with `make watch_events` that unrelated analytics events do not include the A/B test assignment.
=> Invert default logging behavior for A/B test

app/services/analytics_events.rb, lib/analytics_events_documenter.rb, spec/lib/analytics_events_documenter_spec.rb
Updates `make lint_analytics_events` to check for consistent use of `**extra` extra keyword arguments on analytics events methods when required. Previously, the check was flexible in allowing other names, or unused variables (prefixed with `_`).
**Why?** So that we're consistent with how we expect additional keyword arguments to be logged.
Optional: Check for `AnalyticsEvents` method keyword arguments not named `**extra`.
=> Update AnalyticsEventsDocumenter to require exact "**extra"

app/controllers/users/verify_password_controller.rb, app/forms/verify_password_form.rb, app/services/analytics_events.rb, spec/controllers/users/verify_password_controller_spec.rb, spec/forms/verify_password_form_spec.rb
This pull request changes `VerifyPasswordForm` to avoid assigning `personal_key` on `FormResponse#extra` and instead assign as an instance variable accessible through a new attribute reader.
**Why?**
- `extra` is intended to be used for analytics logging and should exclude sensitive information ([docs](https://github.com/18F/identity-idp/blob/main/docs/backend.md#formresponse)). Personal key is a very sensitive value, and while we've taken steps to ensure that it isn't logged, the previous implementation creates a lot of unnecessary risk that it could accidentally be logged in future changes.
- The aforementioned "taken steps to ensure that it isn't logged" meant that we were only logging `success` values for this analytics event. By removing personal key from `extra`, we can log the …
=> Log errors for profile reactivate password submitted

README.md, docs/ab-testing.md, lib/ab_test.rb
[LG-14241](https://cm-jira.usa.gov/browse/LG-14241)
Adds new documentation for how to implement an A/B test, including examples and a breakdown of available options.
Review [proposed documentation](https://github.com/18F/identity-idp/blob/aduth-ab-testing-docs/docs/ab-testing.md) for accuracy, typos, and readability.
=> LG-14241: Add A/B testing documentation

Gemfile.lock
Updates `net-imap` gem to resolve a security advisory:
GHSA-7fc5-f82f-cx69
Changelog: https://github.com/ruby/net-imap/releases
This does not appear to be flagged (yet) by `bundle-audit`, but ensure build passes and `make audit` produces no advisories.
=> Update net-imap gem to 0.5.6

app/controllers/concerns/rate_limit_concern.rb, app/controllers/idv/link_sent_controller.rb, app/controllers/idv/socure/document_capture_controller.rb, spec/controllers/idv/socure/document_capture_controller_spec.rb, spec/features/idv/doc_auth/socure_document_capture_spec.rb
We strongly suspect that the `before:` filters should've caught this condition, but they were largely bypassed for the update event. It turns out that we don't need the bypasses if we change the rate-limiting logic slightly. Instead of making our before filter "smart", we simply pass in whether or not we should check for successful document capture.
Removed the filter bypasses from `socure/document_capture_controller.rb`
- Configure your environment to use Socure.
- Proceed through IdV using the hybrid handoff flow, and verify that you are able to complete document capture.
- Cancel after document capture, and re-try IdV. Repeat until you have one attempt remaining.
- Verify that on your final attempt, you are able to complete document capture and proceed through IdV
=> LG-15693 undefined method profiles for nil

lib/reporting/protocols_report.rb, spec/lib/reporting/protocols_report_spec.rb
[Add analytics to track integrations not passing `openid` in the scope parameter](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/148)
OIDC requests are supposed to have an `openid` scope value in order to conform to the spec. We currently do not have a validation for that value, so many integrations not passing it through. This ticket is to add tracking to the weekly protocols report to get a list of integrations that are not conforming, so we can do targeted outreach to get them to update their requests.
I have tested that the cloudwatch query is valid via:
`aws-vault exec prod-power -- bundle exec rails runner lib/reporting/protocols_report.rb --date 2025-02-09`
=> Add openid scope analytics

app/services/proofing/aamva/applicant.rb, app/services/proofing/aamva/proofer.rb, app/services/proofing/aamva/request/verification_request.rb, app/services/proofing/aamva/verification_client.rb, spec/services/proofing/aamva/proofer_spec.rb, spec/services/proofing/aamva/request/verification_request_spec.rb
**Why**
Requested attributes are for our internal analytics to ensure that the fields sent match any errors we get back. Prior to this change, the requested attributes were sourced from the response body, which meant that regardless of what attributes were requested, we would only know about the attributes that were "seen" and processed by DLDV.
Without knowing which fields were actually requested, troubleshooting certain errors is challenging as there would be a mismatch between what was actually sent and how AAMVA processed the request.
**How**
* Added the logic for generating requested attributes to `Proofing::Aamva::Request::VerificationRequest` as part of creating the request body.
* Instead of Set, we use a Hash. Attributes that have a value are coded as 1. Core attributes (e.g., …
=> LG-15456: Source AAMVA requested attributes from request

app/jobs/reports/sp_idv_weekly_dropoff_report.rb, lib/reporting/sp_proofing_events_by_uuid.rb
This commit fixes 2 issues I found when test-driving the new DOL reports:
1. The IdV weekly dropoff report invoked the wrong report maker class. This commit fixes that.
2. The UUID matrix report timed out trying to batch fetch agency UUIDs. This commit modifies it to use the report timeout.
=> Fix DOL report issues

app/controllers/api/attempts/configuration_controller.rb, app/controllers/api/attempts/events_controller.rb, app/presenters/attempts_configuration_presenter.rb, config/routes.rb, spec/controllers/api/attempts/events_controller_spec.rb, spec/presenters/attempts_configuration_presenter_spec.rb
Note: this PR is dependent on https://github.com/18F/identity-idp/pull/11716 which adds the `attempts_api_enabled` feature flag
[Create initial Attempts API endpoints](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/145)
This change adds the three endpoints that will be utilized in the Attempts API. 
- A configuration endpoint for discovery (/.well-known/ssf-configuration)
- A status endpoint for API status information (/api/attempts/status)
- A polling endpoint for the eventual data stream (/api/attempts/poll)
Detailed descriptions of the end-state of the endpoints can be found [in our technical documentation draft](https://docs.google.com/document/d/1hXrpBPPm4WMusGkX_Q-D8AI0hYFQZNZ-pOy7zKeu0So/edit?tab=t.0#heading=h.z3sevm9fnyoo) and in …
=> Add feature-flagged Attempts API routes

app/javascript/packages/document-capture/components/acuant-capture.tsx, app/javascript/packages/document-capture/components/document-capture-review-issues.tsx, app/javascript/packages/document-capture/components/document-side-acuant-capture.tsx, app/javascript/packages/document-capture/components/documents-step.tsx, app/javascript/packages/document-capture/components/selfie-step.tsx, spec/javascript/packages/document-capture/components/acuant-capture-spec.jsx, spec/javascript/packages/document-capture/components/document-side-acuant-capture-spec.tsx
[LG-15107](https://cm-jira.usa.gov/browse/LG-15107)
Fixed an issue where if a user closes the selfie camera without selecting the green checkmark, it does not show  "How to capture" guidance. 
=> LG-15107 selfie capture fix

package.json, scripts/lint-openapi-spec.mjs
Updates `lint` NPM script to include `.cjs` and `.mjs` files in lint checks.
These file extensions are used when using either [CommonJS](https://nodejs.org/docs/latest/api/modules.html#modules-commonjs-modules) or [ES Modules](https://nodejs.org/docs/latest/api/esm.html#modules-ecmascript-modules) in a package with an opposing [`type`](https://nodejs.org/api/packages.html#type).
Verify `yarn lint` passes.
=> Include MJS and CJS files in ESLint lint

app/components/tab_navigation_component.html.erb, app/components/tab_navigation_component.rb, app/components/tab_navigation_component.scss, app/javascript/packages/analytics/README.md, app/views/devise/sessions/new.html.erb, app/views/sign_up/registrations/new.html.erb, spec/components/tab_navigation_component_spec.rb, spec/features/saml/saml_spec.rb, spec/features/visitors/password_recovery_spec.rb, spec/support/features/session_helper.rb, spec/views/devise/sessions/new.html.erb_spec.rb
[LG-15484](https://cm-jira.usa.gov/browse/LG-15484)
Updates the visual appearance of the "Sign in" and "Create an Account" tabs on the sign-in page.
The intention of these changes is to improve the design clarity of the buttons being a tab control, since we have observed with the current (previous) designs that many users will click on the active button (e.g. "Sign in") while already on that page, with the expectation of it being a call-to-action button to continue signing in.
Changes also include some standardization of button appearance between the "Sign in" and "Create an account" pages:
- Always display the button at full-width (previously the button was full-width on the Sign In page, but wide width on the Create an Account page)
- Always display the button with a "Submit" label …
=> LG-15484: Update design of Sign In/Create Account tabs

app/components/tab_navigation_component.html.erb, app/components/tab_navigation_component.rb, app/components/tab_navigation_component.scss, app/javascript/packages/analytics/README.md, app/views/devise/sessions/new.html.erb, app/views/sign_up/registrations/new.html.erb, spec/components/tab_navigation_component_spec.rb, spec/features/saml/saml_spec.rb, spec/features/visitors/password_recovery_spec.rb, spec/support/features/session_helper.rb, spec/views/devise/sessions/new.html.erb_spec.rb
Reverts 18F/identity-idp#11872
=> Revert "LG-15484: Update design of Sign In/Create Account tabs"

app/controllers/concerns/fraud_review_concern.rb, app/controllers/concerns/verify_profile_concern.rb, app/controllers/idv/please_call_controller.rb, app/controllers/idv/welcome_controller.rb, app/forms/reset_password_form.rb, app/jobs/fraud_rejection_daily_job.rb, app/jobs/get_usps_proofing_results_job.rb, app/models/in_person_enrollment.rb, app/models/user.rb, app/services/analytics_events.rb, app/services/usps_in_person_proofing/enrollment_helper.rb, lib/action_account.rb, spec/controllers/concerns/idv_step_concern_spec.rb, spec/controllers/idv/please_call_controller_spec.rb, spec/controllers/idv/welcome_controller_spec.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/factories/in_person_enrollments.rb, spec/factories/profiles.rb, spec/features/idv/get_proofing_results_job_scenarios_spec.rb, spec/forms/reset_password_form_spec.rb, spec/jobs/fraud_rejection_daily_job_spec.rb, spec/jobs/get_usps_proofing_results_job_spec.rb, spec/lib/action_account_spec.rb, spec/models/in_person_enrollment_spec.rb, spec/models/user_spec.rb, spec/services/usps_in_person_proofing/enrollment_helper_spec.rb
[LG-15216](https://cm-jira.usa.gov/browse/LG-15216)
Enable user's to not lose in-person enrollment progress after a password reset when the user in fraud review.
Changes Include:
- New InPersonEnrollment status `in_fraud_review`
- New metric for GetUspsProofingResultsJob `enrollments_in_fraud_review`
- Update to the action account scripts to update relevant in-person enrollments base on result 
Scenario: Fraud review in-person enrollment and user password resets with personal key
```ruby
job = GetUspsProofingResultsJob.new
job.perform(Time.zone.now)
```
Scenario: Fraud review in-person enrollment and user password resets without personal key
```ruby
job = GetUspsProofingResultsJob.new
job.perform(Time.zone.now)
```
Scenario: Fraud review in-person enrollment …
=> LG-15216 Handle password reset for in-person enrollments waiting for fraud review

app/components/tab_navigation_component.html.erb, app/components/tab_navigation_component.rb, app/components/tab_navigation_component.scss, app/javascript/packages/analytics/README.md, app/views/devise/sessions/new.html.erb, app/views/sign_up/registrations/new.html.erb, spec/components/tab_navigation_component_spec.rb, spec/features/saml/saml_spec.rb, spec/features/visitors/password_recovery_spec.rb, spec/support/features/session_helper.rb, spec/views/devise/sessions/new.html.erb_spec.rb
[LG-15484](https://cm-jira.usa.gov/browse/LG-15484)
Updates the visual appearance of the "Sign in" and "Create an Account" tabs on the sign-in page.
This is a redo of #11872, which was reverted in #11893 due to a minor visual regression in narrow-width devices.
It is identical to the original pull request, with the added fix in bfa93663a0caca02d86d7a80cfb5ac20a5ff9813 (`text-align: center`).
Repeat Testing Plan from #11872.
Verify that at very narrow screen widths (360px and smaller), the text is center-aligned when it starts to wrap.
See original screenshots in #11872.
The screenshots below show the difference at very narrow screen width (360px):
Before|After
---|---
=> LG-15484: Update design of Sign In/Create Account tabs (Redo)

app/views/user_mailer/reset_password_instructions.html.erb, spec/mailers/user_mailer_spec.rb
[LG-15624](https://cm-jira.usa.gov/browse/LG-15624)
- Update "in person verification" pending test to check banner is hidden
- If person proofing verification must be pending AND feature flag `feature_pending_in_person_password_reset_enabled` is enabled, hide the banner
*Before*
*After*
=> LG-15624: Hide the warning banner on the password reset page

app/controllers/concerns/mfa_deletion_concern.rb, app/controllers/users/backup_code_setup_controller.rb, app/models/event.rb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/controllers/concerns/mfa_deletion_concern_spec.rb
[LG-15602](https://cm-jira.usa.gov/browse/LG-15602)
Updates the existing `handle_successful_mfa_deletion` method parameter to include a newly added event type for `backup_codes_removed`. Adds translation strings for 'Backup codes removed'
English
French
Spanish
Chinese
=> LG-15602 Track user event for deleted backup codes

app/jobs/reports/ab_tests_report.rb, spec/jobs/reports/ab_tests_report_spec.rb
[LG-15803](https://cm-jira.usa.gov/browse/LG-15803)
Fixes an error where the recurring job for A/B test reporting doesn't complete because the `perform` method doesn't receive all arguments.
The underlying issue is that the `super` call did not pass all of the original position arguments received by the call, so the job did not have the arguments to send to the enqueued `perform` ([ref](https://github.com/rails/rails/blob/04775277406fe6bb26e7c8052d2459c568a780d8/activejob/lib/active_job/core.rb#L104)).
```
rspec spec/jobs/reports/ab_tests_report_spec.rb
```
You could also locally modify the [job configuration](https://github.com/18F/identity-idp/blob/25c473a5acb6d0ef0d149281564039bd6ffa7dc2/config/initializers/job_configurations.rb#L239-L244) to either use a shorter `cron` value, or …
=> LG-15803: Include all arguments in A/B report base job class initialization

app/views/accounts/_connected_app.html.erb
Updates layout of partner email selection screen to include a line break between "connected with:" line and the selected email, per the original design. This [regressed](https://github.com/18F/identity-idp/pull/11701/files#diff-24662f53f7421ce345236893cae4aaaeeeacf654f0a8f57c94229488bd946563L19) in recent changes. It particularly affects cases where the user has not yet selected an email to be shared with the partner application.
Disable partner email selection feature before starting, in `config/application.yml`:
```
development:
feature_select_email_to_share_enabled: false
```
1. Have [sample application](https://github.com/18F/identity-oidc-sinatra) running in a separate process
2. Go to http://localhost:9292
3. Click "Sign in"
4. Create an account
5. Once returned to the partner, …
=> Restore line break for partner email selection

app/services/usps_in_person_proofing/enrollment_helper.rb, app/services/usps_in_person_proofing/transliterable_validator.rb, config/application.yml.default, lib/identity_config.rb, spec/controllers/idv/in_person/address_controller_spec.rb, spec/controllers/idv/in_person/state_id_controller_spec.rb, spec/features/idv/steps/in_person/address_spec.rb, spec/features/idv/steps/in_person/state_id_spec.rb, spec/forms/idv/in_person/address_form_spec.rb, spec/forms/idv/state_id_form_spec.rb, spec/services/usps_in_person_proofing/enrollment_helper_spec.rb, spec/services/usps_in_person_proofing/transliterable_validator_spec.rb
[LG-15120](https://cm-jira.usa.gov/browse/LG-15120)
Removed the usps_ipp_transliteration_enabled flag.
**Scenario: Fill out state-ID form with transliterate-able characters**
**Scenario: Fill out state-ID form with supported characters (A-Z, a-z)**
**Scenario: Fill out state-ID form with non-transliterate-able characters**
```
Our system cannot read the following characters: Ӑ, 𝒏, 𝒔. Please try again using the characters on your ID.
```
=> LG-15120 Remove usps_ipp_transliteration_enabled flag

app/services/usps_in_person_proofing/mock/proofer.rb
- This pull request supports work for [LG-15114](https://cm-jira.usa.gov/browse/LG-15114)  Create an alarm for In Person Locations Request Failure.
- It is so I can test an alarm I created in [identity-devops- PR# 5546 ](https://gitlab.login.gov/lg/identity-devops/-/merge_requests/5546/diffs) in the Joy sandbox more easily. 
* Add option to throw a Timeout Error to the UPSP In-person proofing mocks when address for USPS search = 'usps waiting'
<details>
This view already existed. It will now be able to mimick a timeout error for USPS get facilities. 
</details>
=> LG-15114 Add Option to Throw Timeout Error in USPS In-person Mock Proofer

app/controllers/accounts_controller.rb, app/controllers/concerns/fully_authenticatable.rb, app/controllers/openid_connect/authorization_controller.rb, app/controllers/saml_idp_controller.rb, app/decorators/null_service_provider_session.rb, app/decorators/service_provider_session.rb, app/presenters/account_show_presenter.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/features/openid_connect/authorization_confirmation_spec.rb, spec/features/saml/authorization_confirmation_spec.rb
[LG-15716](https://cm-jira.usa.gov/browse/LG-15716)
This adds a check on the session that is added when a user is handed off to SP. Which prevents the continue to SP link to appear in account page. 
- Start from SP 
- Sign in and be redirected to SP
- From SP go straight back to login.gov and reach account page
- Verify that the "continue to SP" link does not appear.
Before 
After
=> LG-15716: Dont show link when user has already been directed

app/views/accounts/_backup_codes.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
[LG-13405](https://cm-jira.usa.gov/browse/LG-13405)
Uses existing translation string for 'Backup codes' in place of currently applied 'Save these backup codes'
|    | Before | After |
|----|:------:|:-----:|
| En |    ![Screenshot 2025-02-26 at 8 22 54 AM (2)](https://github.com/user-attachments/assets/4906f0b6-8818-416f-afd7-fb4f4becbea6)   |   ![Screenshot 2025-02-26 at 8 17 48 AM (2)](https://github.com/user-attachments/assets/ad52c097-4ae9-490a-a287-2e2170ba7092)   |
| Es |    ![Screenshot 2025-02-26 at 8 23 00 AM (2)](https://github.com/user-attachments/assets/42c7f026-fede-4066-90a2-0f230d39a0e3)   |   ![Screenshot 2025-02-26 at 8 17 56 AM (2)](https://github.com/user-attachments/assets/296eb64a-a9f9-4d …
=> LG-13405 Incorrect section heading for backup codes in account dashboard

app/jobs/recaptcha_annotate_job.rb, app/models/recaptcha_assessment.rb, app/services/recaptcha_annotator.rb, config/environments/test.rb, db/primary_migrate/20250224134110_create_recaptcha_assessments.rb, db/schema.rb, spec/factories/recaptcha_assessments.rb, spec/jobs/recaptcha_annotate_job_spec.rb, spec/services/recaptcha_annotator_spec.rb
[LG-15655](https://cm-jira.usa.gov/browse/LG-15655)
Implements a new worker job to send [annotations for Google reCAPTCHA Enterprise](https://cloud.google.com/recaptcha/docs/annotate-assessment).
The intent is to avoid these external API requests slowing user response times in the main application. Since these annotations are already treated as "fire and forget", they're a prime candidate to worker-ize, particularly since we don't rely on any result of the job.
The primary challenge with this is ensuring that annotations for a particular assessment are handled in order in a "last wins" approach. We don't necessarily need all annotations to be sent, as long as the last annotation enqueued is the one to be sent. ~This is achieved using GoodJob's concurrency helpers with a maximum …
=> LG-15655: Offload reCAPTCHA annotations to worker job (Part 1 of 2)

app/services/usps_in_person_proofing/enrollment_helper.rb
[LG-14115](https://cm-jira.usa.gov/browse/LG-14115)
- Remove code that is no longer needed.
- Most of the extraneous code mentioned in [LG-14115](https://cm-jira.usa.gov/browse/LG-14115) has already been deleted.  However, we still needed to do a little bit of cleanup in the enrollment_helper.
=> LG-14115: Remove dead code [skip changelog]

app/views/shared/_banner-lock-icon.html.erb, app/views/shared/_banner.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/i18n_spec.rb
Enforces consistency of using non-breaking spaces within paired punctuation to avoid orphaned punctuation when line breaks occur, and fixes existing issues. It also adds French quotation characters ("guillemets": « ») as expected punctuation pairs.
The intent is to avoid the sorts of issues observed in #11911, consistently requiring that non-breaking spaces be used whenever there is whitespace within paired punctuation (parentheses, quotes, etc.).
Example (fixed in #11911):
Verify there's no regressions in the affected text. For example, ensure that the expanded banner text shows the lock icon within parentheses with whitespace.
=> Avoid orphaned punctuation using non-breaking whitespace

app/controllers/application_controller.rb, app/forms/openid_connect_token_form.rb, app/javascript/packs/session-expire-session.ts, app/javascript/packs/session-timeout-ping.ts, app/views/session_timeout/_warning.html.erb, config/application.yml.default, config/initializers/ahoy.rb, config/initializers/devise.rb, config/initializers/session_store.rb, lib/identity_config.rb, spec/controllers/application_controller_spec.rb, spec/features/users/sign_in_spec.rb, spec/views/layouts/application.html.erb_spec.rb
[LG-15833](https://cm-jira.usa.gov/browse/LG-15833)
Fixes an issue where the partner request details are lost if the user clicks "Continue sign in" at sign-in after the session has already expired.
The approach here is to change "Continue sign in" to be a plain link element with the `request_id` as an added parameter of the current page, and limit the behavior of the JavaScript to only override this behavior while the session is still assumed to be active. When the session expires, the JavaScript won't do anything, and will allow it to behave as a normal link, refreshing the page with the `request_id`. The sign-in page controller is already set up to [interpret and save the `request_id` parameter](https://github.com/18F/identity-idp/blob/321ea52d8a04065d292b83fc1729cb4bba20a4ad/app/control …
=> LG-15833: Maintain partner link when session times out at sign-in

lib/data_pull.rb, spec/lib/data_pull_spec.rb
Based on discussion [here](https://gsa-tts.slack.com/archives/C03KDV9S8T1/p1740766941059479). It would be useful when looking at the summary of profiles to know what level they were proofed at. This PR adds the `idv_level` column to the output of the report.
Sample output:
```
+--------------------------------------+------------+--------+---------------------+-------------------------+-----------------+------------------------------------+--------------------------------+---------------------------+
| uuid                                 | profile_id | status | idv_level           | activated_timestamp     | disabled_reason | gpo_verification_pending_timestamp | fraud_review_pending_timestamp | fraud_rejection_timestamp |
+--------------------------------------+------------+--------+------ …
```
=> Add idv_level to ProfileSummary report

app/jobs/data_warehouse/table_summary_stats_export_job.rb
[LG-930](https://gitlab.login.gov/lg-teams/agnes/data-warehouse-ag/-/issues/930)
- Added a timestamp overwrite for a table to the idp job for the stale data check
- Added table exclusion for the usps_confirmations table which has been identified as a transient table
=> changelog: Internal, Reporting, adding timestamp override

app/javascript/packages/document-capture/components/acuant-capture.tsx, app/javascript/packages/document-capture/components/document-side-acuant-capture.tsx, app/javascript/packages/document-capture/context/selfie-capture.tsx, app/javascript/packs/document-capture.tsx, spec/javascript/packages/document-capture/components/document-side-acuant-capture-spec.tsx, spec/javascript/packages/document-capture/components/documents-step-spec.tsx, spec/javascript/packages/document-capture/components/selfie-step-spec.tsx, spec/javascript/packages/document-capture/context/selfie-capture-spec.jsx
[LG-15755](https://cm-jira.usa.gov/browse/LG-15755)
Utilized immediatelyBeginCapture to remove step where user clicks take photo and sees empty selfie state design (and needs to click again) before sdk opens. 
Tested on local machine with phone using [Mobile Local Dev](https://github.com/18F/identity-idp/blob/main/docs/mobile.md)
> doc_auth_selfie_capture_enabled: true
domain_name: <local IP>:3000
mailer_domain_name: <local IP>:3000
enable_load_testing_mode: true
doc_auth_vendor: 'lexisnexis'
doc_auth_vendor_default: 'lexis_nexis'
lexisnexis_base_url:
lexisnexis_hmac_auth_enabled: true
lexisnexis_trueid_account_id:
lexisnexis_trueid_username:
lexisnexis_trueid_password: …
=> Lg-15755 do not display previous empty design for selfie capture

Gemfile.lock
Addresses [CVE-2025-27221](https://www.cve.org/CVERecord?id=CVE-2025-27221)
```
Name: uri
Version: 1.0.2
CVE: CVE-2025-27221
GHSA: GHSA-22h5-pq3x-2gf2
Criticality: Low
URL: https://www.cve.org/CVERecord?id=CVE-2025-27221
Title: CVE-2025-27221 - userinfo leakage in URI#join, URI#merge and URI#+.
Solution: update to '~> 0.11.3', '~> 0.12.4', '~> 0.13.2', '>= 1.0.3'
```
=> Update uri gem to resolve security vulnerability

app/controllers/concerns/two_factor_authenticatable_methods.rb, app/services/recaptcha_annotator.rb, config/application.yml.default, db/primary_migrate/20250228141538_add_timestamps_to_recaptcha_assessments.rb, db/schema.rb, lib/identity_config.rb, spec/controllers/concerns/two_factor_authenticatable_methods_spec.rb, spec/services/recaptcha_annotator_spec.rb
Reverts 18F/identity-idp#11926
Causing Issues in new relic due to concurrency issues.
=> Revert "LG-15655: Submit reCAPTCHA annotations through worker job (Part 2 of 2)"

app/services/saml_request_validator.rb, spec/controllers/saml_idp_controller_spec.rb, spec/services/saml_request_validator_spec.rb
[Validation nil error](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/150)
This change adds a guard for the `authorized_authn_context` validation. Before, if the service provider did not exist but the authn_context was requesting IdV, IALMax, or IAL2, the validation would throw a no method error.
=> Ensure validations work when there is no valid service provider

lib/data_pull.rb, spec/lib/data_pull_spec.rb
Follow up to fix a bug from #11935 where the resulting rows are missing a field in the case where a User or Profile was not found. I've also added a check to this and other table-based reports to try to avoid a regression where the row lengths do not match.
=> Fix missing field in profile-summary when data is missing

app/jobs/resolution_proofing_job.rb, app/services/proofing/resolution/plugins/phone_finder_plugin.rb, app/services/proofing/resolution/progressive_proofer.rb, app/services/proofing/resolution/result_adjudicator.rb, spec/controllers/idv/in_person/verify_info_controller_spec.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/features/idv/analytics_spec.rb, spec/services/proofing/resolution/plugins/phone_finder_plugin_spec.rb, spec/services/proofing/resolution/progressive_proofer_spec.rb, spec/services/proofing/resolution/result_adjudicator_spec.rb
We are working on a feature where the user's phone number can be verified in the verify-info check. This feature is called "Phone Finder Pre-check".
Phone-Finder Pre-check will make a best effort to find a phone number on the user's account (either from their MFA methods or hybrid flow) and validate that phone number when the user submits their info. If the number matches the user will be sent straight to OTP confirmation for that phone number.
As part of this feature we will need the resolution proofing job to send the phone number to phone finder if a phone number is found for the user at the verify info step. This commit implements that by have the resolution proofing job communicate with phone finder and store a result if a phone number is provided in the applicant hash.
=> LG-15643 Pre-check phone number when the phone number is present in the applicant

.rubocop.yml, bin/action-account, bin/data-pull, lib/data_pull.rb, lib/script_base.rb, spec/lib/data_pull_spec.rb, spec/lib/script_base_spec.rb
We often get requests for data that involve searching for accounts that share devices. These kinds of requests occur more often than not. Currently we default to not searching for shared devices. This has led to mistakes where we did not provide shared account data.
This commit attempts to address the issue by making the `--depth` argument required. This will require investigators to explicitly opt-in or out of shared device searches.
From @mitchellhenke:
> The `exit 1` in `lib/script_base.rb` was causing some rather opaque failures in CI as it sets the status code to 1 and caused some tests to end early rather without reporting whether they failed. The unhelpful message at the end of a CI run was `Stopped processing SimpleCov as a previous error not related to SimpleCov has been …
=> LG-15573 Make the `--depth` argument required for IG data pull script

app/views/idv/phone_errors/warning.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
As part of the phone-finder pre-check work the user can arrive on the phone warning screen without entering a number. In this case the "You entered (XXX) XXX-XXXX" message on the screen does not make sense.
This commit changes the message to say "We couldn't find a record of you using this number: (XXX) XXX-XXXX".
English:
Spanish:
French:
Chinese:
=> LG-12326 Update the phone warning screen message

app/views/idv/otp_verification/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
As part of the phone-finder pre-check work the user can arrive on the OTP verification screen without entering a number. In this case the "Entered the wrong number" message on the screen does not make sense.
This commit removes the message and leaves the link that allows a user to try a different number.
English:
Spanish:
French:
Chinese:
=> LG-15586 Remove the "Entered the wrong number" message from IdV OTP verification controller

app/controllers/idv/how_to_verify_controller.rb, app/controllers/idv/hybrid_handoff_controller.rb, app/forms/idv/api_image_upload_form.rb, spec/controllers/idv/how_to_verify_controller_spec.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/features/idv/in_person_spec.rb, spec/support/features/idv_step_helper.rb
[LG-15739: Enable user to switch from in-person proofing to remote identity verification](https://cm-jira.usa.gov/browse/LG-15739)
- User now has the ability to start in-person proofing, change their mind, and successfully complete remote identity verification.  Before, this was not possible.
- Originally, when this jira ticket was written, the suggested tactic was to add FlowPolicy to the usps_locations_controller and cancel any lingering establishing enrollments when the user navigated backward from the usps_locations_controller.  Since the usps_locations_controller is only an API call, this approach did not work.  I met with the engineer who wrote the ticket, and we agreed on the approach that this PR takes.
Scenario 1: User fails remote idv, starts IPP, then resumes remote idv with …
=> LG-15739: Enable user to switch from in-person proofing to remote identity verification

app/models/concerns/user_access_key_overrides.rb, app/models/user.rb, app/policies/two_factor_authentication/personal_key_policy.rb, app/presenters/account_show_presenter.rb, app/presenters/navigation_presenter.rb, app/services/encryption/password_verifier.rb, spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb, spec/controllers/users/passwords_controller_spec.rb, spec/features/legacy_passwords_spec.rb, spec/features/two_factor_authentication/sign_in_via_personal_key_spec.rb, spec/features/users/regenerate_personal_key_spec.rb, spec/forms/personal_key_form_spec.rb, spec/forms/reset_password_form_spec.rb, spec/forms/security_event_form_spec.rb, spec/forms/update_user_password_form_spec.rb, spec/models/profile_spec.rb, spec/models/user_spec.rb, spec/services/encryption/password_verifier_spec.rb, spec/services/idv/profile_maker_spec.rb, spec/services/personal_key_generator_spec.rb
[!51](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/151)
To address some of the issues in #11963, we need to ensure that we are reading both the multi-region and single-region encrypted values before we stop writing the single region key. This PR adds the missing multi-region reads with tests. It should not result in a change in behavior.
=> Ensure reading of multi-region encrypted passwords and personal keys

app/controllers/idv/hybrid_mobile/entry_controller.rb, app/forms/idv/api_image_upload_form.rb
- default doc auth vendor to LN when not defined 50/50 state ([#11981](https://github.com/18F/identity-idp/pull/11981))
=> Deploy RC 459.1 to Prod

app/models/concerns/user_access_key_overrides.rb, app/services/encryption/password_verifier.rb, spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb, spec/controllers/users/passwords_controller_spec.rb, spec/features/legacy_passwords_spec.rb, spec/features/two_factor_authentication/sign_in_via_personal_key_spec.rb, spec/features/users/regenerate_personal_key_spec.rb, spec/forms/personal_key_form_spec.rb, spec/forms/reset_password_form_spec.rb, spec/forms/security_event_form_spec.rb, spec/forms/update_user_password_form_spec.rb, spec/models/profile_spec.rb, spec/models/user_spec.rb, spec/services/encryption/password_verifier_spec.rb, spec/services/personal_key_generator_spec.rb
[!51](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/151)
Related PRs:
- https://github.com/18F/identity-idp/pull/8934
- https://github.com/18F/identity-idp/pull/8973
- https://github.com/18F/identity-idp/pull/9047
- https://github.com/18F/identity-idp/pull/9164
We have been using the multi-region key as our primary key, and can begin winding down the encryption usage of the old single-region key. We cannot yet remove it entirely due to passwords and recover keys encrypted via `UserAccessKey`.
This PR stops encrypting new passwords and personal keys with the single-region KMS key.
This should not be merged until #11966 has been deployed.
=> Remove single-region key encryption for password and recovery key

app/models/profile.rb, app/models/user.rb, app/services/encryption/encryptors/pii_encryptor.rb, spec/models/profile_spec.rb, spec/models/user_spec.rb, spec/services/encryption/encryptors/pii_encryptor_spec.rb, spec/services/idv/profile_maker_spec.rb
Similar to #11963, but for Profile PII. We currently only attempt to [decrypt PII with the multi-region key](https://github.com/18F/identity-idp/blob/main/app/services/encryption/encryptors/pii_encryptor.rb#L77-L79), so it should now be safe to stop writing with the single-region key.
=> Remove single-region key encryption for Profile PII

app/controllers/idv/by_mail/enter_code_controller.rb, app/controllers/idv/please_call_controller.rb, app/forms/gpo_verify_form.rb, app/models/user.rb, spec/controllers/idv/by_mail/enter_code_controller_spec.rb, spec/forms/gpo_verify_form_spec.rb, spec/models/user_spec.rb, spec/services/gpo_reminder_sender_spec.rb
[LG-15886](https://cm-jira.usa.gov/browse/LG-15886)
- Rename `in_person_enrollment_status` method to `latest_in_person_enrollment_status`
Since this faulty method didn't cause any user-facing bugs, there isn't a manual testing plan for the change.  Running the automated tests should be sufficient.
=> LG-15886: Fix bug in user model's latest_in_person_enrollment_status method

app/services/attempts_api/redis_client.rb, spec/services/attempts_api/redis_client_spec.rb
[!142](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/142)
-->
To assist with acknowledging received events, this PR implements a method to delete keys out of the hash. The hourly bucket makes this a little wonky, and may need to be re-evaluated in the future.
=> Add delete_events to Attempts API RedisClient

app/jobs/get_usps_proofing_results_job.rb
[LG-15917](https://cm-jira.usa.gov/browse/LG-15917)
Add the user's uuid to the enrollment skipped event during the GetUspsProofingResultsJob
**Scenario: When the user resets their password and does not login to complete password reset**
=> LG-15917 Add user uuid to enrollment skip events

Gemfile.lock, db/worker_jobs_migrate/20250317182751_add_index_good_jobs_concurrency_key_created_at.rb, db/worker_jobs_schema.rb
`good_job` added a new index to improve performance for certain queries, so this PR updates the gem with the related migration.
=> Upgrade good_job

dockerfiles/application.yaml
Adds the missing init containers overrides to the `application.yaml` to properly override the new base manifests. Also removes some unnecessary `ImagePullPolicy` overrides since those containers aren't pointing to a `main` tag
=> Updating application.yaml for new init containers

docs/attempts-api/schemas/events/IdentityProofingEvents.yml, docs/attempts-api/schemas/events/identity-proofing/IdvAddressSubmitted.yml
This change adds the IdvAddressSubmitted to the list of events in the openapi spec.
=> Add IdvAddressSubmitted event in openapi spec

app/services/encryption/multi_region_kms_profile_migrator.rb, lib/tasks/backfill_profiles.rake, spec/lib/tasks/backfill_profiles_rake_spec.rb, spec/services/encryption/kms_client_spec.rb, spec/services/encryption/multi_region_kms_profile_migrator_spec.rb
Following #11986, we identified some older profiles that had not been completely migrated. This sort of re-implements a combination of https://github.com/18F/identity-idp/pull/9114 and https://github.com/18F/identity-idp/pull/9116.
I also removed some stubbing in the KMS client spec.
=> Add backfill task for multi-region encrypted profiles

app/controllers/api/attempts/events_controller.rb, app/services/attempts_api/redis_client.rb, spec/controllers/api/attempts/events_controller_spec.rb, spec/services/attempts_api/redis_client_spec.rb, spec/services/attempts_api/tracker_spec.rb
[153](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/153)
This change adds some functionality to the `poll` endpoint.
- Calls a delete method to remove all acknowledged sets
- Reads events, starting from the earliest redis bucket
- Returns the events as json
=> Add initial polling

app/controllers/users/sessions_controller.rb, config/application.yml.default, lib/identity_config.rb, spec/controllers/users/sessions_controller_spec.rb, spec/features/users/sign_in_spec.rb
[LG-15873](https://cm-jira.usa.gov/browse/LG-15873)
This removes log only mode for recaptcha sign in
- Signing in works as expected if valid recaptcha result
- if user gives invalid result, properly redirected to error page
=> LG-15873 delete log only recaptcha feature toggle

Gemfile, Gemfile.lock, app/services/encryption/multi_region_kms_profile_migrator.rb, db/primary_migrate/20250321141653_change_null_constraint_on_sp_return_log.rb, db/schema.rb, docs/attempts-api/schemas/events/IdentityProofingEvents.yml, docs/attempts-api/schemas/events/identity-proofing/IdvAddressSubmitted.yml, lib/tasks/backfill_profiles.rake, spec/lib/tasks/backfill_profiles_rake_spec.rb, spec/services/encryption/kms_client_spec.rb, spec/services/encryption/multi_region_kms_profile_migrator_spec.rb
- Attempts API: Add event in spec (#12011) ([#12011](https://github.com/18F/identity-idp/pull/12011))
- Events: Drop NOT NULL const. on sp_return_logs.requested_at ([#12007](https://github.com/18F/identity-idp/pull/12007))
- Maintenance: Remove rspec-retry gem ([#12015](https://github.com/18F/identity-idp/pull/12015))
- Maintenance: Add backfill task for multi-region encrypted profiles ([#12006](https://github.com/18F/identity-idp/pull/12006))
- Maintenance: Use capybara-webmock fork to be able to update Rack ([#12009](https://github.com/18F/identity-idp/pull/12009))
=> Deploy RC 463 to Production

app/controllers/application_controller.rb, app/controllers/users/sessions_controller.rb, app/decorators/null_service_provider_session.rb, app/decorators/service_provider_session.rb, app/models/service_provider.rb, app/services/attempts_api/request_token_validator.rb, app/services/attempts_api/tracker.rb, app/services/attempts_api/tracker_events.rb, spec/controllers/application_controller_spec.rb, spec/decorators/null_service_provider_session_spec.rb, spec/decorators/service_provider_session_spec.rb, spec/models/service_provider_spec.rb, spec/services/attempts_api/tracker_spec.rb
[154](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/154)
This change wires in the first attempt event to be stored in Redis. This code:
- Adds an attempts_api_tracker object in the applications controller
- Adds a way to access the `attempts_api_session_id` from the session object
- wires in a call to the `email_and_password_auth` event
I tested it locally using the OIDC sinatra sample app. I want to add a view there to make it easy to see events as they are generated/delete them
=> Wiring up first attempt event

app/models/sp_return_log.rb, db/primary_migrate/20250325164321_drop_requested_at_from_sp_return_log.rb, db/schema.rb
changelog: Internal, Events, Drop column sp_return_logs.requested_at
Step 3 of 3
Steps:
1. Add migration to drop the NOT NULL constraint and deploy
2. Add column to `ignored_columns`, remove all reads and writes and deploy
3. Drop column using `safety_assured` and deploy
[LG-13781](https://cm-jira.usa.gov/browse/LG-13781)
=> Drop column sp_return_logs.requested_at

app/controllers/sign_up/passwords_controller.rb, app/controllers/users/backup_code_setup_controller.rb, app/controllers/users/totp_setup_controller.rb, app/services/attempts_api/tracker_events.rb, docs/attempts-api/schemas/events/sign-in/MfaLoginBackupCodeSubmitted.yml, docs/attempts-api/schemas/events/sign-in/MfaLoginWebauthnRoamingSubmitted.yml, spec/controllers/sign_up/passwords_controller_spec.rb, spec/controllers/users/backup_code_setup_controller_spec.rb, spec/controllers/users/sessions_controller_spec.rb, spec/controllers/users/totp_setup_controller_spec.rb, spec/rails_helper.rb, spec/support/attempts_api_tracking_helper.rb, spec/support/fake_attempts_tracker.rb
[155](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/155)
This change adds three user registration events. those events are:
- mfa-enroll-backup-code
- mfa-enroll-totp
-  user-registration-password-submitted
This change also adds some spec support to make it easier to test, as well as updating a couple of event descriptions in the openapi spec.
=> Adds user registration events

spec/features/idv/doc_auth/how_to_verify_spec.rb, spec/support/features/session_helper.rb
Based on reports [here](https://gsa-tts.slack.com/archives/C0NGESUN5/p1742421743002739) where a test attempts to go to the next page before completing authentication. Adding some additional assertions around page expectations addresses the issue for me locally. We don't see the issue in CI, so I suspect it's due to the speed of the system, and adding assertions makes sure requests can complete before moving on to the next step in the test.
=> Improve test reliability by adding page assertions in feature test helpers

spec/models/in_person_enrollment_spec.rb
[LG-12897](https://cm-jira.usa.gov/browse/LG-12897)
[Last year](https://gsa-tts.slack.com/archives/C04GA9WQ85B/p1711724402126509) around the end of March, we had a flaky test failure due to DST change, and it happened again [this year](https://gsa-tts.slack.com/archives/C04GA9WQ85B/p1743426907691619). This PR sets a specific time for the test so that it is less likely to fail due to the time of year. Time changes aren't super impactful on the behavior, so it should be fine to fix this in the test only.
=> Improve InPersonEnrollment test that is flaky around DST changes

app/controllers/two_factor_authentication/otp_verification_controller.rb, app/models/phone_configuration.rb, app/services/update_user_phone_configuration.rb, lib/data_requests/deployed/create_mfa_configurations_report.rb, lib/tasks/create_test_accounts.rb, lib/tasks/dev.rake, spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb, spec/factories/phone_configurations.rb, spec/factories/users.rb, spec/features/phone/add_phone_spec.rb, spec/features/phone/confirmation_spec.rb, spec/fixtures/data_request.json, spec/lib/data_requests/deployed/create_mfa_configurations_report_spec.rb, spec/lib/data_requests/local/write_user_info_spec.rb
[LG-12304](https://cm-jira.usa.gov/browse/LG-12304)
Restores phone_configurations.confirmed_at changes from prior PR and keeps in changes for the other 2 removed DB columns.
=> LG-12304 Remove unused phone confirmation data (1a of 2)

app/controllers/concerns/two_factor_authenticatable_methods.rb, app/controllers/two_factor_authentication/backup_code_verification_controller.rb, app/controllers/two_factor_authentication/otp_verification_controller.rb, app/controllers/two_factor_authentication/personal_key_verification_controller.rb, app/controllers/two_factor_authentication/piv_cac_verification_controller.rb, app/controllers/two_factor_authentication/totp_verification_controller.rb, app/controllers/users/webauthn_setup_controller.rb, app/services/attempts_api/tracker_events.rb, docs/attempts-api/schemas/events/RegistrationEvents.yml, docs/attempts-api/schemas/events/registration/MfaEnrollCodeRateLimited.yml, spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb, spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb, spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb, spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb, spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb, spec/controllers/users/webauthn_setup_controller_spec.rb
[155](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/155)
This change adds these events:
- mfa-enroll-code-rate-limited
- mfa-enroll-webauthn-platform  
- mfa-enroll-webauthn-roaming
it also:
- completes a refactor of a method name that has been a TODO for several years
- updates the name of a confusingly named event
=> Add more enrollment events

app/controllers/concerns/idv/choose_id_type_concern.rb, app/controllers/idv/choose_id_type_controller.rb, app/controllers/idv/hybrid_mobile/choose_id_type_controller.rb, app/models/document_capture_session.rb, app/views/idv/shared/choose_id_type.html.erb, spec/controllers/idv/hybrid_mobile/choose_id_type_controller_spec.rb, spec/features/idv/doc_auth/choose_id_type_spec.rb, spec/features/idv/hybrid_mobile/hybrid_choose_id_type_spec.rb
[LG-15915](https://cm-jira.usa.gov/browse/LG-15915)
Adding check for previous form submission to auto-populate choose id type screen.
=> Lg 15915 fill choose id type on back

app/controllers/concerns/remember_device_concern.rb, spec/controllers/concerns/remember_device_concern_spec.rb
[!158](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/158)
This PR addresses a bug where if a service provider has a `default_aal` of 2 and requests `urn:gov:gsa:ac:classes:sp:PasswordProtectedTransport:duo` as their AAL, the MFA expiration interval will be at the AAL2 level. A requested value should always override the default, resulting in the current unexpected behavior of not being able to use remembered device if the service provider explicitly allows it in the request (if they have `default_aal` of 2).
This issue stems from #6252 where we started using the requested or resolved AAL value for MFA expiration interval calculation, but left the `default_aal` check. The resolved AAL will fall back to the service provider's `default_aal`, …
=> Fix default AAL overriding specified AAL value

app/jobs/get_usps_proofing_results_job.rb, app/services/analytics_events.rb, spec/jobs/get_usps_proofing_results_job_spec.rb
[LG-15945](https://cm-jira.usa.gov/browse/LG-15945)
- Update the status_check_completed_at enrollment timestamp when an enrollment is skipped during the `get_usps_proofing_results_job`
- Add the response analytics to the enrollment_skipped event
- Analytics found here https://github.com/18F/identity-idp/blob/abea53e220970ecbbe6b8c0d02ee7f440cda41a4/app/jobs/get_usps_proofing_results_job.rb#L682-L701
=> LG-15945 Update status_check_completed_at for skipped enrollments

app/controllers/concerns/saml_idp_logout_concern.rb, app/controllers/openid_connect/authorization_controller.rb, app/controllers/openid_connect/logout_controller.rb, app/controllers/saml_idp_controller.rb, app/controllers/sign_out_controller.rb, app/controllers/users/sessions_controller.rb, app/services/attempts_api/tracker_events.rb, docs/attempts-api/schemas/events/sign-in/LogoutInitiated.yml, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/openid_connect/logout_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/controllers/sign_out_controller_spec.rb, spec/controllers/users/sessions_controller_spec.rb, spec/features/users/sign_up_spec.rb, spec/support/shared_examples/sign_in.rb
[157](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/157)
This change adds two new events:
- login-completed
- logout-initiated
There are a handful more sign-in events, but those are all MFA-submitted events. While beginning that process, I noticed that our multiauth verification methods were collapsed [into here](https://github.com/18F/identity-idp/blob/main/app/controllers/concerns/two_factor_authenticatable_methods.rb#L20-L28) into one class. It makes sense to similarly collaps the different events into a single mfa-submitted event that includes a type rather than a [bunch of different types of mfa submitted events](https://github.com/18F/identity-idp/blob/main/docs/attempts-api/schemas/events/SignInEvents.yml#L20-L28)
For the next PR, I …
=> Login completed and initiated events

app/controllers/idv/how_to_verify_controller.rb, app/controllers/idv/welcome_controller.rb, app/presenters/idv/how_to_verify_presenter.rb, app/presenters/idv/welcome_presenter.rb, app/services/analytics_events.rb, app/views/idv/how_to_verify/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/controllers/idv/welcome_controller_spec.rb, spec/features/idv/analytics_spec.rb, spec/features/idv/doc_auth/how_to_verify_spec.rb, spec/features/idv/doc_auth/hybrid_handoff_spec.rb, spec/features/idv/in_person_spec.rb, spec/features/idv/steps/in_person_opt_in_ipp_spec.rb, spec/presenters/idv/welcome_presenter_spec.rb, spec/support/features/doc_auth_helper.rb, spec/views/idv/how_to_verify/show.html.erb_spec.rb, spec/views/idv/welcome/show.html.erb_spec.rb
[LG-15435](https://cm-jira.usa.gov/browse/LG-15435)
Updates copy on the IdV Welcome page, conditionally saying passports are an option.
Updates copy on the IdV How to Verify page, conditionally saying passports may be used for online verification, but not for In Person.
Updated translations with new copy.
- [solipet:identity-verified](https://idp.solipet.identitysandbox.gov/openid_connect/authorize?client_id=urn%3Agov%3Agsa%3Aopenidconnect%3Asp%3Asinatra-test&nonce=ad07e9d47b2e244257ec41dbb8198e72&prompt=select_account&redirect_uri=https%3A%2F%2Fsp-oidc-sinatra.test.identitysandbox.gov%2Fauth%2Fresult&response_type=code&scope=openid+email+profile+social_security_number+phone+address+x509&state=3e4ef06285903b7942f2f3113652c97e&vtm=https%3A%2F%2Fdeveloper.login.g …
=> LG-15435: Conditionally show passport as option if available on Welcome and How to Verify

app/controllers/openid_connect/logout_controller.rb, spec/controllers/openid_connect/logout_controller_spec.rb, spec/features/openid_connect/openid_connect_spec.rb
[!159](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/159)
Following #6936 and #7017, we added support for the OpenID Logout `client_id` parameter as a step to deprecating the `id_token_hint` parameter. Part of the [OpenID Connect RP-Initiated Logout 1.0](https://openid.net/specs/openid-connect-rpinitiated-1_0.html) includes:
> Logout requests without a valid id_token_hint value are a potential means of denial of service; therefore, OPs should obtain explicit confirmation from the End-User before acting upon them.
> At the Logout Endpoint, the OP SHOULD ask the End-User whether to log out of the OP as well. Furthermore, the OP MUST ask the End-User this question if an id_token_hint was not provided or if the supplied ID Token does not …
=> Always require confirmation of user logout in OIDC Logout

config/application.yml.default, lib/identity_config.rb
[LG-15960: Add ID-IPP Passport feature flag](https://cm-jira.usa.gov/browse/LG-15960)
- Add feature flag `in_person_passports_enabled`
- Look at `application.yml.default`.  Observe that `in_person_passports_enabled` is false.
=> LG-15960: IPP Passport Feature Flag

app/views/two_factor_authentication/_locked.html.erb
[LG-15489: Add countdown on "Account temporarily locked" screen](https://cm-jira.usa.gov/browse/LG-15849)
This ticket addresses a bug where the countdown was not announcing the time remaining
These steps apply for a newly created account or an existing account
https://github.com/user-attachments/assets/84724c0b-1af4-4263-8f0a-b7208ba787f5
=> LG-15489: Add countdown on "Account temporarily locked" screen

app/forms/concerns/piv_cac_form_helpers.rb, app/forms/user_piv_cac_login_form.rb, app/forms/user_piv_cac_setup_form.rb, app/forms/user_piv_cac_verification_form.rb, app/services/analytics_events.rb, spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb, spec/controllers/users/piv_cac_login_controller_spec.rb, spec/forms/user_piv_cac_login_form_spec.rb, spec/forms/user_piv_cac_setup_form_spec.rb, spec/forms/user_piv_cac_verification_form_spec.rb
[162](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/162)
This code change:
- Adds more standard errors to the different pivcac forms
- Prevents the errors from being overwritten by event_type
- makes some tests a little more expressive
=> Update pivcac to use standard errors

app/controllers/idv/in_person/ready_to_verify_controller.rb, app/mailers/user_mailer.rb, app/presenters/idv/in_person/ready_to_verify_presenter.rb, app/services/usps_in_person_proofing/enrollment_helper.rb, app/views/idv/in_person/ready_to_verify/show.html.erb, app/views/user_mailer/shared/_in_person_ready_to_verify.html.erb, spec/mailers/previews/user_mailer_preview.rb, spec/mailers/user_mailer_spec.rb, spec/support/shared_examples_for_mailer_template.rb, spec/views/idv/in_person/ready_to_verify/show.html.erb_spec.rb, spec/views/layouts/mailer.html.erb_spec.rb
[LG-16042: Eng: Add Partner logo/name to the barcode reminder emails](https://cm-jira.usa.gov/browse/LG-16042)
- Ready to verify reminder emails have been updated.
- If the service provider has a png logo, the service provider *logo* will display at the top of the email.
- If the service provider has a svg logo, the service provider *name* will display at the top of the email.
<details>
<summary>Service Provider with a png logo:</summary>
</details>
<details>
<summary>Service Provider with a svg logo:</summary>
</details>
=> LG-16042: Display partner logo or name at top of reminder emails

app/decorators/service_provider_session.rb, spec/decorators/service_provider_session_spec.rb
The IRS currently uses a param `tid` across all their systems. They requested that they be able to rely on that value, rather than adding a second, identical `attempts_api_session_id`. I am updating the code to allow that as a fallback.
=> Allow tid param for session_id

Gemfile, Gemfile.lock, app/controllers/idv/in_person/ready_to_verify_controller.rb, app/decorators/service_provider_session.rb, app/mailers/user_mailer.rb, app/presenters/idv/how_to_verify_presenter.rb, app/presenters/idv/in_person/ready_to_verify_presenter.rb, app/services/usps_in_person_proofing/enrollment_helper.rb, app/views/idv/in_person/ready_to_verify/show.html.erb, app/views/idv/in_person/state_id/show.html.erb, app/views/user_mailer/shared/_in_person_ready_to_verify.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/decorators/service_provider_session_spec.rb, spec/mailers/previews/user_mailer_preview.rb, spec/mailers/user_mailer_spec.rb, spec/support/shared_examples_for_mailer_template.rb, spec/views/idv/how_to_verify/show.html.erb_spec.rb, spec/views/idv/in_person/ready_to_verify/show.html.erb_spec.rb, spec/views/layouts/mailer.html.erb_spec.rb
- In-Person Proofing: Include service provider logo or name in reminder emails ([#12069](https://github.com/18F/identity-idp/pull/12069))
- Maintenance: Update valid_email gem ([#12077](https://github.com/18F/identity-idp/pull/12077))
- Attempts API: Allow tid param for session_id (#12078) ([#12078](https://github.com/18F/identity-idp/pull/12078))
- Doc Auth: Updating text for ipp for required ID type (#12068) ([#12068](https://github.com/18F/identity-idp/pull/12068))
- In-person proofing: Display IPP passport content on How to Verify View if in_person_passport_enabled is true ([#12067](https://github.com/18F/identity-idp/pull/12067))
=> Deploy RC 469 to Production

lib/tasks/check_for_pending_migrations.rake
Discussion [here](https://gsa-tts.slack.com/archives/C03N6KQBAKS/p1744746769681479) had me looking at this rake task, and I saw that we were using a config option that's no longer used as of [!4858](https://gitlab.login.gov/lg/identity-devops/-/merge_requests/4858). This PR removes it.
=> Remove unnecessary config check when checking for pending migrations

app/controllers/idv/choose_id_type_controller.rb, app/controllers/idv/hybrid_mobile/choose_id_type_controller.rb, app/controllers/idv/in_person/choose_id_type_controller.rb, app/controllers/idv/in_person_controller.rb, app/policies/idv/flow_policy.rb, app/presenters/idv/choose_id_type_presenter.rb, app/presenters/idv/hybrid_mobile/choose_id_type_presenter.rb, app/presenters/idv/in_person/choose_id_type_presenter.rb, app/services/analytics_events.rb, app/services/idv/session.rb, app/views/idv/shared/choose_id_type.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, config/routes.rb, spec/controllers/idv/in_person/choose_id_type_controller_spec.rb, spec/controllers/idv/in_person_controller_spec.rb, spec/features/idv/analytics_spec.rb, spec/features/idv/in_person/passport_scenario_spec.rb, spec/i18n_spec.rb, spec/policies/idv/flow_policy_spec.rb, spec/presenters/idv/choose_id_type_presenter_spec.rb, spec/presenters/idv/hybrid_mobile/choose_id_type_presenter_spec.rb, spec/presenters/idv/in_person/choose_id_type_presenter_spec.rb, spec/services/idv/session_spec.rb
[LG-15970](https://cm-jira.usa.gov/browse/LG-15970)
Add choose ID type to ID-IPP passport flow and integration tests.
**Ensure hybrid flow is checked**
**Scenario: Global passports and In-Person Passports is enabled**
Setup: Ensure the following environment variables are set
```text
in_person_proofing_enabled: true
in_person_proofing_opt_in_enabled: true
in_person_passports_enabled: true
doc_auth_passports_enabled: true
```
**Scenario: Global passports are enabled and in-person passports is disabled**
```text
in_person_proofing_enabled: true
in_person_proofing_opt_in_enabled: true
in_person_passports_enabled: false
doc_auth_passports_enabled: true
```
**Scenario: Global passports are disabled and …
=> LG-15970 Add choose id type page to ID-IPP flow

app/models/duplicate_profile_confirmation.rb, db/primary_migrate/20250416181519_create_duplicate_profile_confirmations.rb, db/schema.rb
changelog: Upcoming Features, One Account, Add table to record user confirmation of duplicate profiles
=> Add table to record user confirmation of duplicate profiles

db/primary_migrate/20250422182109_add_document_type_to_in_person_enrollments.rb, db/schema.rb
[LG-15974](https://cm-jira.usa.gov/browse/LG-15974)
- Sub-task [LG-16126](https://cm-jira.usa.gov/browse/LG-16126)
Adds a new, unindexed `document_type` column to in_person_enrollments to pass along the type of photo ID used for an in-person proofing enrollment to our vendors.
=> LG-15974: Add document_type column to in_person_enrollments table

app/controllers/concerns/idv/choose_id_type_concern.rb, app/controllers/concerns/idv_step_concern.rb, app/controllers/idv/choose_id_type_controller.rb, app/controllers/idv/hybrid_mobile/choose_id_type_controller.rb, app/controllers/idv/in_person/choose_id_type_controller.rb, app/controllers/idv/welcome_controller.rb, app/views/idv/shared/choose_id_type.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/controllers/idv/choose_id_type_controller_spec.rb, spec/controllers/idv/hybrid_mobile/choose_id_type_controller_spec.rb, spec/controllers/idv/in_person/choose_id_type_controller_spec.rb, spec/features/idv/doc_auth/choose_id_type_spec.rb, spec/features/idv/hybrid_mobile/hybrid_choose_id_type_spec.rb
[LG-16000](https://cm-jira.usa.gov/browse/LG-16000)
Call health check api on choose id type screen, disable passport option and show alert text described in ticket.
Provide a checklist of steps to confirm the changes. Test process involves editing `application.yml` halfway through a idv flow. The reason for this is to let the health check pass for the welcome controller and fail for the choose id type controllers (tested on the specs)
Next steps for manual testing
> doc_auth_passports_enabled: true
<details>
</details>
=> Lg-16000 implement vendor outage error for dos api

app/services/duplicate_accounts_report.rb, lib/tasks/duplicate_accounts.rake, spec/lib/tasks/duplicate_accounts_rake_spec.rb, spec/services/duplicate_accounts_report_spec.rb
[LG-16022](https://cm-jira.usa.gov/browse/LG-16022)
Adds a manually-run Rake report that generates a CSV and outputs a comma separated list of accounts that have logged in "yesterday", and share the same ssn_signature (assumed in part to mean they have the same ssn)
```
userfoo.identities.last.update(last_authenticated_at: Date.yesterday.middle_of_day)
userfoo.save
```
=> LG-16022 Create daily ssa accounts report capability

app/controllers/concerns/idv/verify_info_concern.rb, app/services/attempts_api/tracker_events.rb, spec/controllers/idv/verify_info_controller_spec.rb
[163](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/163)
this change:
-  updates a typo
- adds the idv-tmx-fraud-check attempts event
- adds tests
=>  Add idv-tmx-fraud-check event

app/controllers/concerns/idv/choose_id_type_concern.rb, app/controllers/idv/choose_id_type_controller.rb, app/controllers/idv/document_capture_controller.rb, app/controllers/idv/hybrid_mobile/choose_id_type_controller.rb, app/controllers/idv/in_person/choose_id_type_controller.rb, app/controllers/idv/in_person/passport_controller.rb, app/services/analytics_events.rb, app/views/idv/shared/choose_id_type.html.erb, config/routes.rb, spec/controllers/concerns/idv/choose_id_type_concern_spec.rb, spec/controllers/idv/in_person/choose_id_type_controller_spec.rb, spec/features/idv/in_person/passport_scenario_spec.rb, spec/support/flow_policy_helper.rb
[LG-16050](https://cm-jira.usa.gov/browse/LG-16050)
Added submit logic to the in-person choose id type controller
Setup: Ensure the following environment variables are set for passport to work in IPP.
```text
in_person_proofing_enabled: true
in_person_proofing_opt_in_enabled: true
in_person_passports_enabled: true
doc_auth_passports_enabled: true
```
**Scenario: User selects passport option on the choose ID type page**
**Scenario: User selects state-id option on the choose ID type page**
**Scenario: User selects no ID type o the choose ID type page**
<details>
<summary>Choose ID type page</summary>
</details>
<details>
<summary>Choose ID type page: State-ID selected</summary>
</details>
<details>
<summary>Choose ID type page: …
=> LG-16050 Add submit logic to IPP choose id type controller

app/jobs/reports/api_transaction_count_report.rb, lib/reporting/api_transaction_count_report.rb, spec/lib/reporting/api_transaction_count_report_spec.rb
[LG-67](https://gitlab.login.gov/lg-teams/Team-Data/reporting/-/issues?assignee_username%5B%5D=kolawole.oseni&first_page_size=20&sort=created_date&state=opened&show=eyJpaWQiOiI2NyIsImZ1bGxfcGF0aCI6ImxnLXRlYW1zL1RlYW0tRGF0YS9yZXBvcnRpbmciLCJpZCI6MTUyNTh9)
- Change date range to use time format as opposed to date format which caused an error 
- Removed title from emailable report function 
=> Api transaction count fix

Gemfile.lock
To address the vulnerability [here](https://github.com/advisories/GHSA-j3g3-5qv5-52mj), this PR updates our version of `net-imap`. We don't use the IMAP functionality, so our exposure to the vulnerability is limited.
=> Update net-imap gem

app/controllers/account_reset/delete_account_controller.rb, app/controllers/users/reset_passwords_controller.rb, app/services/attempts_api/tracker_events.rb, spec/controllers/account_reset/delete_account_controller_spec.rb, spec/controllers/users/reset_passwords_controller_spec.rb
[161](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/161)
Somehow these changes got lost in the shuffle! I implemented them a couple weeks ago but forgot to put them up for review because I'm doing too much at once.
This change:
- adds `account-reset-account-deleted`
- adds `forgot-password-email-confirmed`
- adds `forgot-password-new-password-submitted`
- adds tests
=> Account recovery events

app/controllers/idv/in_person/state_id_controller.rb, app/controllers/idv/in_person/usps_locations_controller.rb, app/models/in_person_enrollment.rb, spec/controllers/idv/in_person/state_id_controller_spec.rb, spec/controllers/idv/in_person/usps_locations_controller_spec.rb, spec/factories/in_person_enrollments.rb, spec/features/idv/end_to_end_idv_spec.rb, spec/support/features/in_person_helper.rb
[LG-15974](https://cm-jira.usa.gov/browse/LG-15974) - Story
Subtask: [LG-16127: Write ID type to InPersonEnrollment.document_type](https://cm-jira.usa.gov/browse/LG-16127)
- This work enables writing `document_type` on the `InPersonEnrollment` model on _successful_ submission of the `StateIdForm` in the state id controller.
- On "undo" or backwards navigation, which will take the applicant back to the "Pick a post office screen", the `enrollment.document_type` should set or reset to nil.
- Cancelling the enrollment after successful submission of the state ID information does not clear the `document_type` field.
**Notes:**
This will be standard behavior for IPP flow and is not predicated on passports being enabled globally or for IPP specifically.
=> LG-15974: Set document type on new IPP enrollments

app/controllers/idv/by_mail/enter_code_controller.rb, app/controllers/idv/enter_password_controller.rb, app/forms/gpo_verify_form.rb, app/jobs/get_usps_proofing_results_job.rb, app/services/attempts_api/tracker_events.rb, docs/attempts-api/schemas/events/identity-proofing/IdvEnrollmentComplete.yml, lib/action_account.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/forms/gpo_verify_form_spec.rb, spec/jobs/get_usps_proofing_results_job_spec.rb, spec/lib/action_account_spec.rb, spec/services/gpo_reminder_sender_spec.rb, spec/views/idv/by_mail/enter_code/index.html.erb_spec.rb
[163](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/163)
This change adds the `idv-enrollment-complete` event.
This is a new event that was added to fulfill the `Enrollment complete` milestone requirement.
It is a little tricky since there are several different pathways for users to finish their identity proofing journey, two of which are not part of the user flow.
The places where we activate a profile (thereby indicating that a profile's enrollment is "complete") is:
- `EnterPasswordController`-  where a user encrypts their data with their password
- `GpoVerifyForm` - where a user submits their mail code
- `GetUSPSProofingResultsJob` - where a user's IPP job is processed
- `ActionAccount::ReviewPass` - where a user is cleared as valid …
=> IdV enrollment complete event

config/application.yml.default, config/initializers/ab_tests.rb, lib/identity_config.rb, spec/config/initializers/ab_tests_spec.rb
[LG-16117](https://cm-jira.usa.gov/browse/LG-16117)
Set up the initial A/B testing for disabling manual document upload.
=> LG-16117 Create A/B test toggle to support manual upload removal

app/controllers/users/sessions_controller.rb, app/forms/sign_in_recaptcha_form.rb, spec/forms/sign_in_recaptcha_form_spec.rb
[LG-15936: Bug: captcha_validation_performed is false even though reCAPTCHA was performed](https://cm-jira.usa.gov/browse/LG-15936)
This PR adds logic to check for an existing device at the point of reCAPTCHA verification
Testing is unavailable on local machines. To verify, watch the data over time in CloudWatch to see if bug has been addressed.
=> Bug: captcha_validation_performed is false even though reCAPTCHA was performed

app/controllers/idv/in_person/address_controller.rb, app/controllers/idv/in_person/passport_controller.rb, app/views/idv/in_person/verify_info/_address_section.html.erb, app/views/idv/in_person/verify_info/_ssn_section.html.erb, app/views/idv/in_person/verify_info/_state_id_section.html.erb, app/views/idv/in_person/verify_info/show.html.erb, config/routes.rb, lib/idp/constants.rb, spec/controllers/idv/in_person/address_controller_spec.rb, spec/controllers/idv/in_person/passport_controller_spec.rb, spec/features/idv/in_person/passport_scenario_spec.rb, spec/support/features/in_person_helper.rb
[LG-16086](https://cm-jira.usa.gov/browse/LG-16086)
Add address, ssn, and verify info to IPP passport flow
Setup: Ensure the following environment variables are set for passport to work in IPP.
```text
in_person_proofing_enabled: true
in_person_proofing_opt_in_enabled: true
in_person_passports_enabled: true
doc_auth_passports_enabled: true
```
**Scenario: User selects passport option and completes update verify info**
**Note: Verify info was out of scope for this story so no content needs to be verified on that page**
**Scenario: User selects ~~passport option~~ driver's license or state ID and completes update verify info**
**Note: Verify info was out of scope for this story so no content needs to be verified on that page**
=> LG-16086 Add address, ssn, and verify info to IPP passport flow

app/controllers/concerns/ial2_profile_concern.rb, app/services/analytics_events.rb, app/services/pii/cacher.rb, spec/services/pii/cacher_spec.rb
changelog: Bug Fixes, Profiles, Update ssn fingerprint with normalized form
See https://cm-jira.usa.gov/browse/LG-16195
=> Update ssn fingerprint with normalized form

app/services/agency_identity_linker.rb, app/services/attempts_api/tracker.rb, spec/services/agency_identity_linker_spec.rb, spec/services/attempts_api/tracker_spec.rb
[!90](https://gitlab.login.gov/lg-teams/FIE/partner-portal-prod-edition/-/issues/90)
The current reliance on only using existing `AgencyIdentity` rows when logging `user_uuid` means we may have significant gaps in the `user_uuid` attribute. There is some history here described more in the ticket, but the conclusion is it should be safe to create new rows here and limit the risk by excluding certain events.
=> Allow creating AgencyIdentity if it does not exist when creating Attetempts API event

app/models/profile.rb
changelog: Bug Fixes, Profile, Delete related DuplicateProfileConfirmations when deleting Profile
This was missed when adding DuplicateProfileConfirmation.
See https://cm-jira.usa.gov/browse/LG-16224.
In my opinion, a test is not needed as the solution is just a missed declaration.
=> Delete related DuplicateProfileConfirmations when deleting Profile

Gemfile.lock
Addresses the following:
> Name: rack
> Version: 3.0.14
> CVE: CVE-2025-46727
> GHSA: GHSA-gjh7-p2fx-99vx
> Criticality: High
> URL: https://github.com/rack/rack/security/advisories/GHSA-gjh7-p2fx-99vx
> Title: Rack has an Unbounded-Parameter DoS in Rack::QueryParser
> Solution: update to '\~> 2.2.14', '~> 3.0.16', '>= 3.1.14'
>
> Name: rack-session
> Version: 2.0.0
> CVE: CVE-2025-46336
> GHSA: GHSA-9j94-67jr-4cqj
> Criticality: Medium
> URL: https://github.com/rack/rack-session/security/advisories/GHSA-9j94-67jr-4cqj
> Title: Rack session gets restored after deletion
> Solution: update to '>= 2.1.1'
=> Update dependencies with vulnerabilities

app/jobs/create_new_device_alert_job.rb
Based on investigation and discussion [here](https://gsa-tts.slack.com/archives/C16RSBG49/p1747059922558459?thread_ts=1746564508.559359&cid=C16RSBG49), we should limit the number of emails we send to reduce the chances of scheduled instances of this job running concurrently.
=> Limit batch size and total size for CreateNewDeviceAlertJob

app/controllers/concerns/two_factor_authenticatable_methods.rb, app/controllers/two_factor_authentication/otp_verification_controller.rb, app/controllers/users/backup_code_setup_controller.rb, app/controllers/users/piv_cac_authentication_setup_controller.rb, app/controllers/users/totp_setup_controller.rb, app/controllers/users/two_factor_authentication_controller.rb, app/controllers/users/webauthn_setup_controller.rb, app/models/anonymous_user.rb, app/services/attempts_api/tracker.rb, app/services/attempts_api/tracker_events.rb, spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb, spec/controllers/users/backup_code_setup_controller_spec.rb, spec/controllers/users/piv_cac_authentication_setup_controller_spec.rb, spec/controllers/users/totp_setup_controller_spec.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb, spec/controllers/users/webauthn_setup_controller_spec.rb, spec/features/users/sign_up_spec.rb
[Fraud Mitigation 2](https://gitlab.login.gov/lg-teams/FIE/fraud-mitigation/-/issues/2)
This change continues to complete Attempts API events.
This change adds
- mfa-enrolled
- mfa-login-phone-otp-sent-rate-limited
- includes pii
- mfa-enrolled-phone-otp-sent-rate-limited
- includes pii
This change removes (because they are now included in the mfa-enrolled event)
- mfa-enroll-backup-code
- mfa-enroll-totp
- mfa-enroll-webauthn-platform
- mfa-enroll-webauthn-roaming
=> mfa-enrolled events and some phone rate limiters

app/jobs/create_new_device_alert_job.rb
The job is still taking too long which creates a concurrency issue. 
This should hopefully reduce the size to 1k users at a time so that we don't have that issue when we decrease the time range to look for suers.
=> Lower Create Alert Job total size

app/controllers/users/two_factor_authentication_controller.rb, app/services/attempts_api/tracker_events.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb
[Fraud Mitigation 2](https://gitlab.login.gov/lg-teams/FIE/fraud-mitigation/-/issues/2)
This change adds:
- mfa-enroll-phone-otp-sent
- mfa-login-phone-otp-sent
- associated tests
=> Add enroll and login phone-otp-sent events

app/jobs/data_warehouse/table_summary_stats_export_job.rb, config/initializers/job_configurations.rb, spec/jobs/data_warehouse/table_summary_stats_export_job_spec.rb
Update tableSummaryStatsExport job to check cloudwatch counts for log groups of interest.
[issue-393](https://gitlab.login.gov/lg-teams/Team-Data/data-warehouse-ag/-/issues/393)
The tableSummaryStatsExport will now query cloudwatch and get the count of records from the production.log & events.log log groups of the idp application, followed by writing them to S3.
=> Update tableSummaryStatsExport job to check cloudwatch on top of idp

app/jobs/data_warehouse/table_summary_stats_export_job.rb
Follow up to [PR-12165](https://github.com/18F/identity-idp/pull/12165), to fix the datetime filter being used for idp table count query.
[issue-393](https://gitlab.login.gov/lg-teams/Team-Data/data-warehouse-ag/-/issues/393)
The prior PR was returning a count of records that have a timestamp of before yesterday but it needs to return count of records that have a timestamp of before END of yesterday.
=> Fixing datetime filter for idp tables after refactor

app/controllers/idv/in_person/verify_info_controller.rb, app/models/in_person_enrollment.rb, app/presenters/idv/in_person/ready_to_verify_presenter.rb, app/presenters/idv/in_person/verify_info_presenter.rb, app/views/idv/in_person/verify_info/_address_section.html.erb, app/views/idv/in_person/verify_info/_passport_section.html.erb, app/views/idv/in_person/verify_info/_ssn_section.html.erb, app/views/idv/in_person/verify_info/_state_id_section.html.erb, app/views/idv/in_person/verify_info/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/features/idv/in_person/passport_scenario_spec.rb, spec/i18n_spec.rb, spec/models/in_person_enrollment_spec.rb, spec/presenters/idv/in_person/verify_info_presenter_spec.rb, spec/support/features/in_person_helper.rb, spec/views/idv/in_person/verify_info/show.html.erb_spec.rb
[LG-15980](https://cm-jira.usa.gov/browse/LG-15980)
Add passport info section to verify info form
**Scenario: Verify Info page in IPP Passport Flow**
**Scenario: Verify Info page in IPP State-ID Flow**
<details>
<summary>Verify Info for Passport</summary>
</details>
<details>
<summary>Verify Info for State-ID</summary>
</details>
=> LG-15980 Add passport info section to verify info form

app/jobs/reports/irs_verification_report.rb, lib/reporting/irs_verification_report.rb, spec/lib/reporting/irs_verification_report_spec.rb, spec/mailers/previews/report_mailer_preview.rb
[LG-47](https://gitlab.login.gov/lg-teams/Team-Data/reporting/-/issues?assignee_username%5B%5D=kolawole.oseni&first_page_size=20&sort=created_date&state=opened&show=eyJpaWQiOiI0NyIsImZ1bGxfcGF0aCI6ImxnLXRlYW1zL1RlYW0tRGF0YS9yZXBvcnRpbmciLCJpZCI6MTUxMTZ9)
Changed location of definition table 
Updated export file to use csv 
=> Irs verification report update

config/application.yml.default
While doing some configuration maintenance, I noticed that this configuration key was removed in #11957 but perhaps mistakenly added back in #11962
=> Remove unused feature_pending_in_person_password_reset_enabled configuration

app/services/duplicate_profile_checker.rb, config/application.yml.default, lib/identity_config.rb, spec/services/duplicate_profile_checker_spec.rb
changelog: Internal, One Verified Account, Use separate feature flag for logging duplicate profiles
[LG-16260](https://cm-jira.usa.gov/browse/LG-16260)
=> Use separate feature flag for logging duplicate profiles

app/controllers/idv/in_person/ssn_controller.rb, app/controllers/idv/ssn_controller.rb, app/forms/idv/ssn_format_form.rb, app/services/attempts_api/tracker_events.rb, spec/controllers/idv/in_person/ssn_controller_spec.rb, spec/controllers/idv/ssn_controller_spec.rb, spec/forms/idv/ssn_format_form_spec.rb
[FIE Epic 367](https://gitlab.login.gov/groups/lg-teams/FIE/-/epics/367)
- adds the idv-ssn-submitted event
- associated tests
this is added in both the usual idv flow and IPP
=> changelog: Upcoming Features, Attempts API, Add idv-ssn-submitted event

app/controllers/api/attempts/events_controller.rb, app/services/analytics_events.rb, app/services/attempts_api/redis_client.rb, app/services/attempts_api/request_token_validator.rb, spec/controllers/api/attempts/events_controller_spec.rb, spec/services/attempts_api/redis_client_spec.rb
[!19](https://gitlab.login.gov/lg-teams/FIE/fraud-mitigation/-/issues/19)
Adds a new event for logging requests to the Attempts API polling endpoint. I've also done some slight changes to other classes to accommodate the metadata needed for logging.
=> Log event for Attempts API event polling

app/services/attempts_api/attempt_event.rb, app/services/attempts_api/tracker.rb, spec/services/attempts_api/tracker_spec.rb
TIGTA requirements include the language a user has selected. 
This change
- adds the language attribute
- if a user exists, then their selected `email_language` value is used
- if not, then it falls back on the default `I18n.locale`
=> Add language attribute to shared event properties

app/controllers/concerns/idv/verify_info_concern.rb, app/controllers/idv/agreement_controller.rb, app/controllers/idv/enter_password_controller.rb, app/controllers/idv/in_person/ssn_controller.rb, app/controllers/idv/ssn_controller.rb, app/controllers/users/sessions_controller.rb, app/services/attempts_api/tracker_events.rb, docs/attempts-api/schemas/events/identity-proofing/IdvSsnSubmitted.yml, spec/controllers/idv/agreement_controller_spec.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/controllers/idv/in_person/ssn_controller_spec.rb, spec/controllers/idv/ssn_controller_spec.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/controllers/users/sessions_controller_spec.rb
I'm doing some cleanup work.
This change:
- renames two `social_security` attributes to `ssn` to be clearer and more aligned with the rest of the codebase
- updates the name of an event method from `email_and_password_auth` to `login_email_and_password_auth` to be aligned with the rest of the attempts events
- moves the `idv_reproof` event from the back of the funnel to the front (it represents the initiation of identity verification for a user who has proofed previously)
=> small event fixes

app/services/marketing_site.rb, app/views/devise/passwords/new.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/views/devise/passwords/new.html.erb_spec.rb
[LG-16124](https://cm-jira.usa.gov/browse/LG-16124)
Adds troubleshooting links (via a troubleshooting help component) to the location found at `/users/password/new`.
=> LG-16124: Add password reset help

app/services/duplicate_profile_checker.rb, config/application.yml.default, lib/identity_config.rb, spec/services/duplicate_profile_checker_spec.rb
The code has been deployed and found to be working correctly. There is no need to protect it with a feature flag any longer.
changelog: Internal, One Verified Account, Remove feature flag no longer needed
[LG-16286](https://cm-jira.usa.gov/browse/LG-16286)
=> Remove feature flag feature_one_verified_account_log_duplicate_profiles

app/views/users/piv_cac_authentication_setup/error.html.erb, app/views/users/piv_cac_login/error.html.erb
[LG-16312](https://cm-jira.usa.gov/browse/LG-16312)
This pull request adds an error icon to two pages: at the point where a user does not sign in successfully using their PIV card and at unsuccessful PIV card setup
Error when signing in using PIV card
You will see the error icon once login is unsuccessful
Error when setting up PIV/CAC
You will see an icon indicating an error
This is a new template, so one screenshot will be provided
<details>
</details>
<details>
</details>
=> LG-16312: Add error icon to PIV/CAC error page on sign in failure screen

app/controllers/idv/agreement_controller.rb, app/controllers/idv/how_to_verify_controller.rb, app/controllers/idv/hybrid_handoff_controller.rb, app/presenters/idv/how_to_verify_presenter.rb, app/views/idv/hybrid_handoff/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/controllers/idv/agreement_controller_spec.rb, spec/controllers/idv/how_to_verify_controller_spec.rb, spec/controllers/idv/hybrid_handoff_controller_spec.rb, spec/features/accessibility/idv_pages_spec.rb, spec/features/idv/cancel_spec.rb, spec/features/idv/doc_auth/document_capture_spec.rb, spec/features/idv/doc_auth/how_to_verify_spec.rb, spec/features/idv/doc_auth/hybrid_handoff_spec.rb, spec/features/idv/doc_auth/redo_document_capture_spec.rb, spec/features/idv/in_person/passport_scenario_spec.rb, spec/features/idv/in_person_spec.rb, spec/features/idv/steps/in_person_opt_in_ipp_spec.rb, spec/support/features/doc_auth_helper.rb, spec/views/idv/hybrid_handoff/show.html.erb_spec.rb
[LG-16188](https://cm-jira.usa.gov/browse/LG-16188)
Updating hybrid handoff page and updating routing to use hybird handoff as new how to verify in the hybrid (non-mobile) flow. 
<details>
<details>
<summary>Non Selfie:</summary>
</details>
<details>
<summary>Selfie:</summary>
</details>
</details>
=> Lg 16188 update how to verify page

lib/reporting/api_transaction_count_report.rb, spec/lib/reporting/api_transaction_count_report_spec.rb
🎫 Ticket
[Ticket 123](https://gitlab.login.gov/lg-teams/Team-Data/reporting/-/issues?assignee_username%5B%5D=kolawole.oseni&first_page_size=20&sort=created_date&state=opened&show=eyJpaWQiOiIxMjMiLCJmdWxsX3BhdGgiOiJsZy10ZWFtcy9UZWFtLURhdGEvcmVwb3J0aW5nIiwiaWQiOjE4MTAwfQ%3D%3D)
Creating a new weekly report for Api transaction count. 
Created report is created by querying cloudwatch and sending an email to the recdepients defined in the config 
=> API Transaction Count Report Bug Fix 

app/jobs/data_warehouse/table_summary_stats_export_job.rb
changelog: Internal, Reporting,add timestamp_column to deleted_user
https://gitlab.login.gov/lg-teams/Team-Data/data-warehouse-ag/-/issues/1042
We're seeing count discrepancies between the IDP and Redshift deleted_user tables. This PR will address that by updating the job to consider the deleted_at column when getting counts for the deleted_user table.
=> 1042 Added column deleted_at  as timestamp with TableSummaryStatsExportJob

lib/reporting/irs_fraud_metrics_lg99_report.rb, spec/jobs/reports/irs_fraud_metrics_report_spec.rb, spec/lib/reporting/irs_fraud_metrics_lg99_report_spec.rb
GL-110
[GL-110](https://gitlab.login.gov/lg-teams/Team-Data/reporting/-/issues/110)
--> Update names of the metric in irs_fraud_metrics_lg99_report
> Changed "Fraudulent credentials disabled" to read "Credentials disabled" in both the metrics and the definitions.
> Changed "Fraudulent credentials reinstated" to read "Credentials reinstated" in both the metrics and the definitions
--> Removed all "Average Days" rows under the "monthly suspended user metrics" and "monthly reinstated user metrics"
--> Removed the separate tables for "Monthly Suspended Users Metrics" and "Monthly Reinstated User Metrics" and list "Fraud Rules Catch Count", "Credentials Disabled", and "Credentials Reinstated" all under the heading …
=> changelog: Internal, Reporting, Update IRS Fraud Metric Report

app/jobs/socure_docv_results_job.rb, app/jobs/socure_image_retrieval_job.rb, app/services/attempts_api/tracker_events.rb, app/services/doc_auth/dos/request.rb, app/services/doc_auth/socure/responses/docv_result_response.rb, app/services/encrypted_doc_storage/doc_writer.rb, app/services/idv/idv_images.rb, docs/attempts-api/schemas/events/identity-proofing/IdvImageRetrievalFailed.yml, spec/jobs/socure_docv_results_job_spec.rb, spec/jobs/socure_image_retrieval_job_spec.rb, spec/services/doc_auth/socure/requests/images_request_spec.rb, spec/services/encrypted_doc_storage/doc_writer_spec.rb, spec/services/idv/idv_images_spec.rb
[Fraud mitigation 28](https://gitlab.login.gov/lg-teams/FIE/fraud-mitigation/-/issues/28)
This change:
- Preemptively creates the encryption key and file name of the images
- Creates a `SocureImageRetrievalJob` class to handle retrieving and storing the images
- Adds a new event for indicating that the image retrieval has failed, if there is a network error of some sort
- Adds tests for `ImageRequests` as well as `SocureImageRetrievalJob`
=>  Pull Socure Doc Escrow into a job

app/controllers/concerns/idv/document_capture_concern.rb, app/controllers/concerns/idv/socure_errors_concern.rb, app/controllers/idv/socure/errors_controller.rb, app/presenters/socure_error_presenter.rb, app/services/doc_auth/socure/responses/docv_result_response.rb, spec/fixtures/socure_docv/selfie_fail.json, spec/presenters/socure_error_presenter_spec.rb, spec/views/idv/socure/errors/show.html.erb_spec.rb
[LG-16231](https://cm-jira.usa.gov/browse/LG-16231)
Added specific error messaging for selfie verification failures in the Socure IAL2 document capture flow. When users successfully upload their ID but their selfie doesn't match the ID photo, they now see a clear "We couldn't match the photo of yourself to your ID" error message instead of a generic failure.
[ ] Update `config/application.yml` with` idv_socure_reason_codes_docv_selfie_fail: '["R810"]'` and `facial_match_general_availability_enabled: true`
[ ] Trigger Socure DocV flow with portrait matching failure (reason code R810) and verify "We couldn't match the photo of yourself to your ID" error displays
[ ] Verify error message appears in all supported languages (English, Spanish, French, Chinese)
=> LG-16231: display ial2 selfie error

app/controllers/api/attempts/events_controller.rb, spec/controllers/api/attempts/events_controller_spec.rb
[FIE Fraud mitigation 34](https://gitlab.login.gov/lg-teams/FIE/fraud-mitigation/-/issues/34)
This change adds a validation to make sure that the number of events returned is throttled at 1k.
=> changelog: Upcoming Features, Attempts API, Add error handling for incorrect params

app/controllers/concerns/idv/document_capture_concern.rb, app/forms/idv/api_image_upload_form.rb, app/models/document_capture_session.rb, app/services/document_capture_session_result.rb, spec/controllers/concerns/idv/document_capture_concern_spec.rb, spec/services/document_capture_session_result_spec.rb
[LG-16176](https://cm-jira.usa.gov/browse/LG-16176)
Added MRZ validation gate for passport documents. When users submit a passport, the system now verifies the MRZ data with DoS before allowing them to proceed to SSN entry. If MRZ validation fails, users remain on the document capture screen.
- Submit a passport → MRZ validation runs and blocks/allows progression accordingly
- Submit a state ID → Proceeds normally (no MRZ check)
- Tests pass: `bundle exec rspec spec/controllers/concerns/idv/document_capture_concern_spec.rb`
- Submit a passport → MRZ validation runs and blocks/allows progression accordingly
- Submit a state ID → Proceeds normally (no MRZ check)
- Tests pass: `bundle exec rspec …
=> LG-16176 handle mrz check passport

app/services/proofing/resolution/plugins/aamva_plugin.rb, app/services/proofing/resolution/progressive_proofer.rb, lib/idp/constants.rb, spec/services/proofing/resolution/plugins/aamva_plugin_spec.rb, spec/services/proofing/resolution/progressive_proofer_spec.rb
changelog: Upcoming Features, Doc Auth, Skip aamva state ID check for passport proofing
[LG-16169](https://cm-jira.usa.gov/browse/LG-16169)
Skip AAMA state ID check when the document type is passport in the progressive proofer 
Scenario: Passport flow verify info
Scenario: State ID flow verify info
=> LG-16169 Skip aamva state ID check for remote passport proofing

app/controllers/application_controller.rb, spec/controllers/application_controller_spec.rb, spec/factories/duplicate_profile_confirmations.rb
[LG-16340](https://cm-jira.usa.gov/browse/LG-16340)
This ensures that when a user does not have an active profile we don't return anything for that particular user.
=> LG-16340: Make sure to not expect an empty profile. 

app/controllers/idv/hybrid_handoff_controller.rb, app/controllers/idv/in_person/address_controller.rb, app/controllers/idv/in_person/ssn_controller.rb, app/controllers/idv/in_person/state_id_controller.rb, app/controllers/idv/in_person/verify_info_controller.rb, app/presenters/idv/in_person/verify_info_presenter.rb, spec/controllers/idv/in_person/address_controller_spec.rb, spec/controllers/idv/in_person/ssn_controller_spec.rb, spec/controllers/idv/in_person/state_id_controller_spec.rb, spec/controllers/idv/in_person/verify_info_controller_spec.rb, spec/policies/idv/flow_policy_spec.rb
[LG-16288](https://cm-jira.usa.gov/browse/LG-16288)
We have seen some errors where the enrollment passed to the IPP verify_info_presenter is nil. 
In #11939 we started cancelling enrollments upon _visiting_ the Welcome page which is how, we believe, the user ended up with a nil enrollment. That change doesn't align with the work we did previously on Team Ada with the [FlowPolicy](https://handbook.login.gov/articles/identity-verification-flow-policy.html) which intended for controllers in the idv flow to define a StepInfo that includes preconditions and a proc to clean up (undo) the action. The FlowPolicy work was intentionally done to allow users to use the back/forward buttons at will.
This PR updates the IPP controllers preconditions to ensure that if an …
=> LG-16288: Guard against nil enrollment

app/controllers/concerns/idv/verify_info_concern.rb, app/services/attempts_api/tracker_events.rb, app/services/proofing/ddp_result.rb, app/services/proofing/resolution/result_adjudicator.rb, docs/attempts-api/schemas/events/identity-proofing/IdvDeviceRiskAssessment.yml, spec/controllers/idv/verify_info_controller_spec.rb, spec/services/proofing/ddp_result_spec.rb
[FIE fraud mitigation 35](https://gitlab.login.gov/lg-teams/FIE/fraud-mitigation/-/issues/35)
this change:
- updates the `idv-device-risk-assessment` documentation to include a `fingerprint_device` attribute
- updates the tracker event to include the `fingerprint_device` attribute that is returned from threatmetrix
- adds the attribute to `pii_like_keypaths` to ensure it's not logged
=> Add device_fingerprint to idv-device-risk-assessment event

app/components/webauthn_input_component.rb, app/controllers/users/two_factor_authentication_setup_controller.rb, app/javascript/packages/webauthn/webauthn-input-element.spec.ts, app/javascript/packages/webauthn/webauthn-input-element.ts, app/presenters/two_factor_authentication/set_up_selection_presenter.rb, app/presenters/two_factor_authentication/set_up_webauthn_platform_selection_presenter.rb, app/presenters/two_factor_options_presenter.rb, config/application.yml.default, config/initializers/ab_tests.rb, lib/identity_config.rb, spec/components/webauthn_input_component_spec.rb, spec/config/initializers/ab_tests_spec.rb, spec/controllers/users/two_factor_authentication_setup_controller_spec.rb, spec/features/webauthn/hidden_spec.rb
Ticket: [LG-16160](https://cm-jira.usa.gov/browse/LG-16160)
This PR removes references of the desktop F/T unlock A/B test now that we plan on rolling this out to the general audience.
=> LG-16160: Remove face/touch unlock A/B test

app/forms/idv/doc_pii_form.rb, app/forms/idv/doc_pii_passport.rb, app/services/doc_auth/lexis_nexis/doc_pii_reader.rb, app/services/doc_auth/lexis_nexis/responses/true_id_response.rb, spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_passport_tampering_failure.json, spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_success_passport.json, spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_success_passport_card.json, spec/forms/idv/doc_pii_form_spec.rb, spec/forms/idv/doc_pii_passport_spec.rb, spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb, spec/support/lexis_nexis_fixtures.rb
[LG-16384](https://cm-jira.usa.gov/browse/LG-16384)
Check for the DocIssueType to see if the presented id is a passport card and set the id_doc_type appropriately.
Fails doc auth when passport card and fails doc auth when passport presented but passports are not enabled.
Specs pass
=> LG-16384: passport cards are not state ids

app/services/proofing/ddp_result.rb, spec/fixtures/proofing/lexis_nexis/ddp/successful_response.json, spec/services/proofing/ddp_result_spec.rb
[FIE Fraud Mitigation 35](https://gitlab.login.gov/lg-teams/FIE/fraud-mitigation/-/issues/35)
Small bug fix discovered in testing. The response body is in JSON, and so would be accessible via a string rather than a symbol.
This change:
- Fixes the code
- Updates the tests to reduce confusion in the future
- Adds fuzzy_device_id to mock threatmetrix response
=> changelog: Bug Fixes, Attempts API, Update key to string from symbol

app/controllers/users/piv_cac_recommended_controller.rb, app/controllers/users/two_factor_authentication_setup_controller.rb, app/services/threat_metrix_helper.rb, app/views/users/piv_cac_recommended/show.html.erb
[LG-16403](https://cm-jira.usa.gov/browse/LG-16403)
We need to ensure that users that dont go through MFA setup page first due to the piv cac recommended option needs to 
- Ensure u load federal domains locally with `rake federal_email_domains:load_to_db`
- Create an account with a valid .gov domain
- Ensure that can go through and add pivcac without issue.
=> LG-16403: TMX session id

app/forms/idv/api_image_upload_form.rb, spec/forms/idv/api_image_upload_form_spec.rb
[LG-16344](https://cm-jira.usa.gov/browse/LG-16344)
This PR fixes a crash when a passport document passes initial authentication but fails PII validation.
The issue was that `failed_passport_fingerprint` was declared inside a conditional block and accessed in a different scope, causing a NameError. I moved the variable declarations outside the conditional blocks to ensure they’re always available.
I added a test case to verify this scenario works without errors. The fix follows the same pattern used elsewhere in the file for similar variable scoping.
=> LG-16344-passport-validation-patch

app/forms/idv/api_image_upload_form.rb, spec/forms/idv/api_image_upload_form_spec.rb
[LG-16389](https://cm-jira.usa.gov/browse/LG-16389)
Ensure that DOS MRZ validation is only performed if a passport is requested at the "choose your id" step and that it only occurs if the document uploaded is a passport.
=> LG-16389 MRZ validation only performed if passport is requested and submitted

db/primary_migrate/20250714184424_add_notes_to_device_profiling_result.rb, db/schema.rb, lib/tasks/device_profiling.rake
[LG-16404](https://cm-jira.usa.gov/browse/LG-16404)
adds a rake task to update users that were impacted by the tmx launch when going through the piv cac recommended flow.
=> LG-16404: Tmx impacted users cleanup

app/controllers/idv/hybrid_handoff_controller.rb, app/forms/idv/api_image_upload_form.rb, app/presenters/duplicate_profiles_detected_presenter.rb, app/services/idv/proofing_components.rb, app/views/duplicate_profiles_detected/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, db/primary_migrate/20250714184424_add_notes_to_device_profiling_result.rb, db/schema.rb, docs/attempts-api/schemas/events/shared/EventProperties.yml, lib/idp/constants.rb, lib/tasks/device_profiling.rake, spec/controllers/idv/link_sent_controller_spec.rb, spec/features/idv/analytics_spec.rb, spec/features/idv/cancel_spec.rb, spec/features/idv/doc_auth/hybrid_handoff_spec.rb, spec/features/idv/end_to_end_idv_spec.rb, spec/features/idv/proofing_components_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb, spec/services/idv/agent_spec.rb, spec/services/idv/analytics_events_enhancer_spec.rb, spec/services/idv/proofing_components_spec.rb
- One account: Dupe account design update ([#12328](https://github.com/18F/identity-idp/pull/12328))
- Document Authentication: Fix crash when passport fails PII validation ([#12325](https://github.com/18F/identity-idp/pull/12325))
- Account creation, tmx account creation rake task to un-suspend users ([#12330](https://github.com/18F/identity-idp/pull/12330))
- Attempts API: Update device_id documentation ([#12332](https://github.com/18F/identity-idp/pull/12332))
- Document Authentication: ensure MRZ validation only occurs when passport is requested and submitted ([#12316](https://github.com/18F/identity-idp/pull/12316))
- Document Authentication: Updating document_type in proofing component to support passport ([#12315](https://github.com/18F/identity-idp/pull/12315))
=> Deploy RC 495 to Production

app/controllers/idv/agreement_controller.rb, spec/features/idv/doc_auth/socure_document_capture_spec.rb, spec/support/features/doc_auth_helper.rb
[LG-16388](https://cm-jira.usa.gov/browse/LG-16388)
Allow non-IPP flows to reach choose_id_type screen from agreement controller an remove unnecessary tests.
=> Bug Fixes, Passports, Allow non-IPP flows to reach choose_id_type screen

app/jobs/socure_docv_results_job.rb, app/services/doc_auth/socure/requests/docv_result_request.rb, app/services/doc_auth/socure/responses/docv_result_response.rb, spec/jobs/socure_docv_results_job_spec.rb, spec/services/doc_auth/socure/requests/docv_result_request_spec.rb
[LG-16372](https://cm-jira.usa.gov/browse/LG-16372)
Adding passport requested attribute to docv to check if user submitted the requested document
> doc_auth_selfie_desktop_test_mode: true
doc_auth_vendor: mock_socure
doc_auth_vendor_default: mock_socure
socure_docv_enabled: true
socure_idplus_api_key: 'nope-not-a-valid-key'
socure_docv_webhook_secret_key: 'sekret-key'
Video Demo: https://drive.google.com/file/d/1NbDci8TkY4oxLB6-X0kmnwbtd72eMNOn/view?usp=sharing
<details>
</details>
=> Lg-16372 docv user must submit id requested

app/forms/idv/api_image_upload_form.rb, lib/feature_management.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb
[FIE 46](https://gitlab.login.gov/lg-teams/FIE/secure-protocols/-/issues/46)
We had [an incident](https://gsa-tts.slack.com/archives/C5QUGUANN/p1753112196260859) with the Attempts API where all Acuant proofing images were being saved to the s3 Bucket, rather than just images for the allowed service providers.
This change checks to make sure that the service provider is on the Attempts API allowlist before encrypting and saving the images.
=> Only encrypt and write images for integrations that are on the allowlist

app/controllers/concerns/mfa_setup_concern.rb, app/services/funnel/registration/add_mfa.rb, spec/controllers/users/backup_code_setup_controller_spec.rb, spec/controllers/users/webauthn_setup_controller_spec.rb, spec/services/funnel/registration/add_mfa_spec.rb, spec/services/funnel/registration/total_registered_count_spec.rb
[LG-XXXXX](https://cm-jira.usa.gov/browse/LG-XXXXX)
Ensure only users in account creation flow is going through and tmx 
- Go through and create user without webauthn platform
- Sign in again and be suggested webauthn platform
- successfully sign in without an issue.
=> LG-16510: Tmx session id error fix

app/forms/idv/api_image_upload_form.rb, app/jobs/socure_docv_results_job.rb, app/services/encrypted_doc_storage/doc_writer.rb, app/services/encrypted_doc_storage/local_storage.rb, app/services/idv/idv_images.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb, spec/services/encrypted_doc_storage/doc_writer_spec.rb, spec/services/idv/idv_images_spec.rb
[!49](https://gitlab.login.gov/lg-teams/FIE/secure-protocols/-/issues/49)
To better structure the storage, this prefixes the issuer as a "folder" to the name of the document objects.
=> Include issuer in document escrow document name

Gemfile, Gemfile.lock
changelog: Internal, Security, Update ruby-saml gem
=> Upgrade saml_idp to 0.23.9-18f

app/models/profile.rb, app/services/idv/duplicate_ssn_finder.rb, spec/jobs/resolution_proofing_job_spec.rb
=> Undo unintended resolution proofing change

lib/reporting/fraud_metrics_lg99_report.rb, lib/reporting/irs_fraud_metrics_lg99_report.rb, spec/lib/reporting/fraud_metrics_lg99_report_spec.rb, spec/lib/reporting/irs_fraud_metrics_lg99_report_spec.rb
Report has been wrong since May due to a typo/case issue.
Changes upper case to lower case for "IDV: final resolution" CloudWatch event.
See https://gitlab.login.gov/lg-teams/Team-Data/reporting/-/issues/184
=> Fix LG-99 metric in Fraud Report | GL-Data-184

Gemfile, Gemfile.lock, app/controllers/concerns/idv/choose_id_type_concern.rb, app/controllers/idv/welcome_controller.rb, app/models/profile.rb, app/services/analytics_events.rb, app/services/doc_auth/dos/requests/health_check_request.rb, app/services/duplicate_profile_checker.rb, app/services/idv/duplicate_ssn_finder.rb, app/services/reporting/irs_credential_tenure_report.rb, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, lib/reporting/fraud_metrics_lg99_report.rb, lib/reporting/irs_fraud_metrics_lg99_report.rb, spec/controllers/concerns/idv/choose_id_type_concern_spec.rb, spec/features/idv/doc_auth/choose_id_type_spec.rb, spec/features/idv/doc_auth/document_capture_spec.rb, spec/features/idv/doc_auth/welcome_spec.rb, spec/i18n_spec.rb, spec/jobs/reports/irs_fraud_metrics_report_spec.rb, spec/jobs/resolution_proofing_job_spec.rb, spec/lib/reporting/fraud_metrics_lg99_report_spec.rb, spec/lib/reporting/irs_fraud_metrics_lg99_report_spec.rb, spec/services/doc_auth/dos/requests/health_check_request_spec.rb, spec/services/duplicate_profile_checker_spec.rb, spec/services/idv/duplicate_ssn_finder_spec.rb
- Resolution Proofing: Undo unintended changes from One Account work ([#12390](https://github.com/18F/identity-idp/pull/12390))
- Doc Auth: Adding logging for step in dos api health check ([#12387](https://github.com/18F/identity-idp/pull/12387))
- Doc Auth: Adding spec to confirm mobile flow routes from how to verify to doc capture after ipp canceled (#12393) ([#12393](https://github.com/18F/identity-idp/pull/12393))
- Maintenance: Update json gem ([#12386](https://github.com/18F/identity-idp/pull/12386))
- Reporting: Fix IRS Credential Tenure Metric query anb combine report with IRS Fraud Metric ([#12394](https://github.com/18F/identity-idp/pull/12394))
- Reporting: Fix LG-99 metric in Fraud Report ([#12396](https://github.com/18F/identity-idp/pull/12396))
- Security: Update ruby-saml …
=> Deploy RC 502 to Production

app/controllers/application_controller.rb, config/application.yml.default, config/initializers/ab_tests.rb, lib/identity_config.rb, spec/controllers/application_controller_spec.rb
[LG-16540](https://cm-jira.usa.gov/browse/LG-16540)
Adds A/B test functionality for the one verified account information
=> LG-16540: A/B Framework One account 

db/primary_migrate/20250808215829_remove_foreign_key_duplicate_profile_confirmation.rb, db/schema.rb
We will be dropping `duplicate_profile_confirmations`. This prepares for that by dropping the foreign key constraint first.
changelog: Upcoming Features, One Account, Remove foreign key preparatory to dropping table
=> Remove foreign key preparatory to dropping table

app/controllers/idv/phone_errors_controller.rb, app/views/idv/phone_errors/warning.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/views/idv/phone_errors/warning.html.erb_spec.rb
[LG-16481](https://cm-jira.usa.gov/browse/LG-16481)
Updated French and Chinese translations for phone pages in idv.
<details>
</details>
=> Lg-16481 update french chinese translations for idv

spec/features/accessibility/idv_pages_spec.rb
It looks like we inadvertently removed accessibility testing in some IDV tests in #12221, this re-enables them.
=> Re-enable accessibility testing on IDV pages test

app/models/duplicate_profile.rb, db/primary_migrate/20250811221924_create_duplicate_profiles.rb, db/schema.rb
This will replace duplicate_profile_confirmations.
changelog: Upcoming Features, One Account, Create table to hold duplicate profiles
=> Create table to hold duplicate profiles

app/models/profile.rb
We will be dropping `duplicate_profile_confirmations`. This prepares for that by dropping the association.
changelog: Upcoming Features, One Account, Remove association with table to be dropped
=> Remove association with table to be dropped

app/jobs/alert_user_duplicate_profile_discovered_job.rb, app/services/marketing_site.rb, config/locales/telephony/en.yml, config/locales/telephony/es.yml, config/locales/telephony/fr.yml, config/locales/telephony/zh.yml, lib/telephony.rb, lib/telephony/alert_sender.rb, spec/jobs/alert_user_duplicate_profile_discovered_job_spec.rb
[LG-16538](https://cm-jira.usa.gov/browse/LG-16538)
Add Sms notifications for sign in or text attempts. 
=> LG-16538: sms one account notifications

spec/features/idv/cancel_spec.rb, spec/support/idv_examples/sp_requested_attributes.rb, spec/support/matchers/accessibility.rb
An additional check was added in #7640 to better ensure HTML markup validity. It requires some more complex uses of Capybara drivers, and one of the (unintuitive) side effects is that the cookie that is set in the rack driver can persist beyond the current test. For a consistent reproduction, I have been running:
```sh
./bin/rspec spec/features/idv/in_person_threatmetrix_spec.rb:75 spec/features/idv/cancel_spec.rb:23 --seed 17897
```
The result of the existing behavior is a test that follows one that calls `expect_page_to_have_no_accessibility_violations` may have an existing session. It is not a more consistent issue as the data in the session is frequently overwritten (especially warden-based elements). The specific issue for [this more common …
=> Reset cookie when validating HTML markup in accessibility test to improve reliability

app/controllers/concerns/idv/verify_info_concern.rb, app/controllers/idv/address_controller.rb, app/controllers/idv/by_mail/request_letter_controller.rb, app/services/idv/session.rb
[LG-16446](https://cm-jira.usa.gov/browse/LG-16446)
This PR removes the old field, `gpo_letter_requested`, from the codebase now that the PR to add the new field,
`gpo_request_letter_visited`, has been deployed.
=> LG-16446: Rename gpo_letter_requested (Part 2)

app/controllers/idv/welcome_controller.rb, spec/controllers/idv/welcome_controller_spec.rb, spec/features/idv/doc_auth/welcome_spec.rb, spec/features/idv/in_person/passport_scenario_spec.rb
changelog: Internal, IdV Passports, Remove DoS health check from welcome page
[LG-16693](https://cm-jira.usa.gov/browse/LG-16693)
Remove DoS health check from welcome page
**Scenario: Passports Enabled and 100 precent enabled**
```yaml
doc_auth_passports_enabled: true
```
**Scenario: Passports Enabled and 0 precent enabled**
```yaml
doc_auth_passports_enabled: true
doc_auth_passports_percent: 0
```
**Scenario: Passports Disabled**
```yaml
doc_auth_passports_enabled: false
```
=> LG-16693 Remove DoS health check on welcome page

app/controllers/idv/choose_id_type_controller.rb, spec/controllers/idv/choose_id_type_controller_spec.rb
Users were able to use browser back button to get to the choose_id_type step when they didn't have a document capture session.
changelog: Bug Fixes, IdV mobile flow, Fix navigation bug on choose_id_type page
[LG-16688](https://cm-jira.usa.gov/browse/LG-16688)
Users were able to use browser back button to get to the choose_id_type step when they didn't have a document capture session. I updated the choose_id_type controller to use confirm step allowed before hook to prevent users from navigating to the step without the required state set.
Also, I added more test coverage to the choose_id_type controller spec
=> LG-16688 Fix choose_id_type flow policy

app/controllers/application_controller.rb, app/decorators/null_service_provider_session.rb, app/decorators/service_provider_session.rb, app/jobs/get_usps_proofing_results_job.rb, app/jobs/socure_docv_results_job.rb, app/jobs/socure_image_retrieval_job.rb, app/services/attempts_api/tracker.rb, docs/attempts-api/schemas/events/shared/EventProperties.yml, lib/action_account.rb, spec/controllers/application_controller_spec.rb, spec/decorators/service_provider_session_spec.rb, spec/services/attempts_api/tracker_spec.rb
We have a new partner interested in using the Attempts API that is using SAML. The `application_url` value was designed for OIDC applications, so this PR updates it to work for SAML
This change also renames an internal parameter and attribute in order to make it clearer that this field is capturing a redirect uri, so that the SP can know where a user is going after authentication (useful for integrations with multiple `redirect_uri`s)
=> Adapt attempts for saml

app/services/attempts_api/attempt_event.rb, spec/services/attempts_api/attempt_event_spec.rb
Our partners are having trouble reading the signature correctly. They are seeing an issue with the Base64 Encoding, although they also noted that they are seeing extra backticks in their message response.
We recently moved from signing a a JWT, then encrypting it into a JWE. The ruby-JWE library [expects a payload string](https://github.com/jwt/ruby-jwe), so originally, we were passing a hash that we turned into json via `to_json` into the `JWE.encrypt` method call.
The ruby-JWT library, on the other hand, expects a [hash](https://github.com/jwt/ruby-jwt) of data to be input. When we moved to sign the JWT first, we did not update the code correspondingly, so that is why this `to_json` needs to be removed. It is unclear if this will fix the other issue the partner is seeing on their side, …
=> Pass hash rather than json into JWT library

app/services/attempts_api/redis_client.rb, app/services/attempts_api/tracker.rb
🔒 [GL-Data-1105](https://gitlab.login.gov/lg-teams/Team-Data/data-warehouse-ag/-/issues/1105)
In preparation to leverage the attempts API tracker for the Data Warehouse ingestion, we need to break up `track_event` in `tracker.rb`. Also need to break out various methods in `redis_client.rb`
In tracker, defined the following new methods
- jwe
- extra_attributes
- event_metadata
- extra_metadata
- failure_metadata
In redis_client, defined the following: 
- initialize - sets a new @redis_pool variable to wrap `REDIS_ATTEMPTS_API_POOL`
- event_ttl_seconds - wraps `IdentityConfig.store.attempts_api_event_ttl_seconds`
=> Modularize Attempts API Tracker - FCMS Prework

lib/reporting/irs_verification_demographics_report.rb, spec/lib/reporting/irs_verification_demographics_report_spec.rb
[211 Bugfix: IRS demographics report](https://gitlab.login.gov/lg-teams/Team-Data/reporting/-/issues/211#top)
Following [#163 (closed)](https://github.com/lg-teams/Team-Data/reporting/-/issues/163), we discovered that we're not calculating events where IdV doc auth verify proofing results is successful, and pulling birth year and state data only from successful events.
This work is to split the cloudwatch queries in the IRS demographics report to:
1. Gather the list of users that were redirected to IRS at IAL2 level (sp redirect, ial=2, sp_request:facial.match=1)
2. Gather the state ID and birth year from idv doc auth verify proofing results where the events are successful
From there, we can:
- With ruby, join the user's that were redirected to IRS at IAL2 to …
=> Irs verification demographic report update - GL-Reporting-211

app/services/proofing/lexis_nexis/ddp/response_redacter.rb, lib/reporting/api_transaction_count_report.rb, spec/features/idv/analytics_spec.rb, spec/fixtures/proofing/lexis_nexis/ddp/successful_redacted_response.json, spec/fixtures/proofing/lexis_nexis/ddp/successful_response.json, spec/jobs/socure_shadow_mode_proofing_job_spec.rb, spec/services/proofing/lexis_nexis/ddp/response_redacter_spec.rb
[LG-16690](https://cm-jira.usa.gov/browse/LG-16690)
Removed FraudPoint data collection from IDV flow. FraudPoint was collected from ThreatMetrix DDP but was unused in fraud decisions - only `review_status` matters for fraud detection.
commands to run
- DDP tests: `bundle exec rspec spec/services/proofing/lexis_nexis/ddp/ spec/services/proofing/ddp_result_spec.rb`
- IDV tests: `bundle exec rspec spec/services/idv/profile_maker_spec.rb spec/services/fraud_review_check_spec.rb`
- LexisNexis tests: `bundle exec rspec spec/services/proofing/lexis_nexis/instant_verify/ spec/services/proofing/lexis_nexis/phone_finder/`
=> LG-16690: Remove unused FraudPoint logic from IDV flow

docs/frontend.md
Our links to frontend guides and documentation are broken, so this fixes them.
=> Fix broken links in frontend documentation

app/jobs/reports/irs_credential_tenure_report.rb, app/services/reporting/irs_credential_tenure_report.rb, lib/reporting/irs_fraud_metrics_lg99_report.rb, spec/jobs/reports/irs_fraud_metrics_report_spec.rb, spec/lib/reporting/irs_fraud_metrics_lg99_report_spec.rb
GL_Data_Reporting-238
[GL_Data_Reporting-238](https://gitlab.login.gov/lg-teams/Team-Data/reporting/-/issues/238)
--> Remove Credential Tenure Metric report from IRS Fraud Metric report
--> Remove Credential Tenure Metric from IRS Fraud Metric report spec files
<details>
</details>
<details>
</details>
=> GL_Data_reporting: remove cred tenure from Fraud metric

spec/support/idv_examples/sp_handoff.rb
The tests that call `expect_successful_oidc_handoff ` rely on the `code` parameter returned in the OIDC redirect, but there is a rarer race condition that can happen where the redirect does not complete and the test fails ([example](https://gitlab.login.gov/lg/identity-idp/-/jobs/1990486)). The fix is to assert that the browser is currently at the SP return path with the `validate_return_to_sp` helper (which makes use of Capybara's built-in wait functionality).
Example test failure:
```
Failures:
1) IdV SP handoff with oidc behaves like sp handoff after identity verification unverified user sign in requires idv and hands off successfully
Failure/Error:
@oidc_decoded_id_token ||= JWT.decode(
oidc_decoded_token[:id_token],
Rails.application.config.oidc_public_key,
true,
algorithm: 'RS256', …
```
=> Fix flaky SP handoff feature tests

app/controllers/idv/address_controller.rb, app/controllers/idv/ssn_controller.rb, app/services/pii/passport.rb, app/services/pii/state_id.rb, spec/services/pii/passport_spec.rb, spec/services/pii/state_id_spec.rb
Added methods to Pii passport and state_id structs for determining if residential address is needed and constructing Pii address from internal object data.
changelog: Internal, Remote IdV, Add helper methods to Pii passport and state_id structs
[LG-16724](https://cm-jira.usa.gov/browse/LG-16724)
Added methods to Pii passport and state_id structs for determining if residential address is needed and constructing Pii address from internal object data.
=> LG-16724 Add methods to pii passport and state_id structs

.gitlab-ci.yml, spec/bin/aamva-test-cert_spec.rb, spec/requests/headers_spec.rb, spec/services/barcode_outputter_spec.rb, spec/services/encrypted_redis_struct_storage_spec.rb
There is potential for string literals to be [frozen by default](https://bugs.ruby-lang.org/issues/20205) in future Rubies, so this enables the flag in CI during test runs.
=> Enable freezing string literals when running tests in CI

app/services/idv/session.rb, app/services/pii/usps_applicant.rb, app/services/usps_in_person_proofing/applicant.rb, app/services/usps_in_person_proofing/enrollment_helper.rb, app/services/usps_in_person_proofing/proofer.rb, config/application.yml.default, lib/identity_config.rb, lib/tasks/dev.rake, spec/controllers/idv/enter_password_controller_spec.rb, spec/features/idv/in_person/usps_opt_in_ipp_applicant_expanded_payload_spec.rb, spec/services/idv/session_spec.rb, spec/services/pii/usps_applicant_spec.rb, spec/services/usps_in_person_proofing/applicant_spec.rb, spec/services/usps_in_person_proofing/enrollment_helper_spec.rb, spec/services/usps_in_person_proofing/proofer_spec.rb
changelog: Internal, Upcoming Feature, Add document attributes to USPS enrollment request. Attributes are behind a feature flag to be enabled in the future.
[LG-16718](https://cm-jira.usa.gov/browse/LG-16718)
Automated:
Manual:
=> LG-16718 Add document attributes to USPS enrollment request

app/services/pii/attributes.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/features/idv/doc_auth/idv_flow_spec.rb, spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_success_passport_without_tamper.json, spec/support/lexis_nexis_fixtures.rb
changelog: Internal, IDV, Add issuing country code to pii bundle
[LG-16803](https://cm-jira.usa.gov/browse/LG-16803)
Add issuing country code to pii bundle.
Manual Testing:
Scenario: Passport
=> LG-16803 Add issuing country code to pii bundle

app/controllers/openid_connect/authorization_controller.rb, app/controllers/saml_idp_controller.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb
[LG-16675](https://cm-jira.usa.gov/browse/LG-16675)
Makes it so users cannot bypass suspension by trying to request SP sign in a secodn time. 
- Sign in with suspended user
- See please call page
- Go back to sp 
- Click sign in from SP
- expect to be redirected to please call url instead of success login.
=> LG-16675: Prevent suspended user attempts to go through SP 

spec/features/idv/doc_auth/socure_document_capture_spec.rb, spec/features/idv/doc_auth/socure_internal_error_spec.rb, spec/features/idv/hybrid_mobile/entry_spec.rb, spec/features/idv/hybrid_mobile/hybrid_socure_mobile_spec.rb
[LG-16720](https://cm-jira.usa.gov/browse/LG-16720)
Removed mocks on DocAuthRouter for IdV feature specs
=> LG-16720 Unmock A/B bucket routing in feature tests

app/presenters/duplicate_profiles_detected_presenter.rb, spec/presenters/duplicate_profiles_detected_presenter_spec.rb
[LG-16741](https://cm-jira.usa.gov/browse/LG-16741)
We were previously populating the 'last logged in' field, displayed on the duplicate profile page, with the `last_signed_in` on from the `EmailAddress` model.  It is inaccurate for a few reasons so we updated it to be populated with `last_authenticated_at` from the `ServiceProviderIdentity`.
=> [LG-16741] Fix last logged in on duplicate profile page

app/forms/idv/api_image_upload_form.rb, spec/forms/idv/api_image_upload_form_spec.rb
[LG-16853](https://cm-jira.usa.gov/browse/LG-16853)
In a recent change, we modified the Acuant SDK to not crop images. These un-cropped images need to go through a different TrueID flow.
=> LG-16853: Autocapture no longer crops images
