- .travis.yml
- code/upaya/README.md
- code/upaya/bin/setup
- code/upaya/config/application.rb
My first PR!  Updated the readme + a few other cleanups.
> Update setup instruction

- app/assets/stylesheets/_base.scss
- app/assets/stylesheets/_variables.scss
i accidentally used the `$body-color` sass variable instead of `$body-background-color`; this PR fixes this
> fix misused body color variable

- .travis.yml
**How**:
- gem install travis
- travis encrypt CODECLIMATE_REPO_TOKEN=the_token_from_codeclimate.com
- paste the secure token in .travis.yml
> Add Code Climate test coverage token to .travis.yml

- .csslintrc
- .eslintignore
- app/assets/stylesheets/application.css.scss
- vendor/assets/stylesheets/normalize.css
**why**
* it ensures cross-browser consistency in default styling of HTML elements
> add normalize.css

- app/assets/javascripts/app/edit_user.js
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_util.scss
- app/assets/stylesheets/components/all.scss
- app/helpers/devise/two_factor_authentication_setup_helper.rb
- app/views/devise/account_type/type.html.slim
- app/views/devise/confirmations/new.html.slim
- app/views/devise/sessions/new.html.slim
- app/views/devise/shared/_links.html.slim
- app/views/shared/_navigation_links.html.slim
- config/initializers/simple_form.rb
- config/locales/simple_form.en.yml
- spec/features/visitors/password_recovery_spec.rb
**why**
* to provide a nice user experience
> implement basic design concepts

- app/assets/stylesheets/components/_form.scss
> Add max width for submit button

- Dockerfile
- README.md
- docker-compose.yml
Simplifies instructions in README for getting up and
running quickly.
Ensures rubygems and bundler is up to date in VM
Reorganizes nodes in docker-compose
Notes required version of Docker Toolbox
> Updates README and Dockerfile

- config/locales/en.yml
- spec/features/visitors/sign_up_spec.rb
- spec/support/features/session_helper.rb
Password expiry was completely removed in a recent commit.
> Remove password expiry messages

- config/service_providers.yml
The wrong cert was referenced in service_providers.yml
> Updates reference to demo_sp cert

- docs/security/opencontrol.yaml
Beginning of compliance masonry based SSP for the ATO. CC @mzia
> Draft SSP for login.gov

- app/views/devise/two_factor_authentication/show.html.slim
- app/views/devise/two_factor_authentication_setup/index.html.slim
**Why**: to save some clicks :)
> Add input focus

- app/views/layouts/_messages.html.slim
- app/views/shared/_branding.html.slim
- app/views/shared/_navigation_links.html.slim
**Why**: improves messaging layout (adds a little padding on the side)
preview:
> Tweak flash messaging layout

- .bummr-build.sh
- Gemfile
- Gemfile.lock
**Why**:
To automate the process of updating gems one by one
See the README for more details: https://github.com/lpender/bummr
> Add bummr gem and shell script

- app/views/devise/shared/_links.html.slim
**Why**: this link should be discoverable on login page
> Add confirm instruction link

- config/locales/devise.en.yml
**Why**: remove references to "Upaya"
re: https://github.com/18F/identity-private/issues/420
> Tweak flash message copy

- app/views/layouts/application.html.slim
**Why**: using latest name (login.gov) :)
> Upaya -> login.gov page title, desc

- docs/frontend.md
Also updated based on conversation in #152
> Moved front end architecture to docs directory

- app/assets/javascripts/app/pw-toggle.js
- app/assets/javascripts/application.js
- app/assets/stylesheets/components/_password.scss
- spec/features/visitors/sign_up_spec.rb
**Why**: to allow user to view what they typed
(if they want to check before submitting)
Preview:
> Add password visibility toggle

- config/application.yml.example
**Why**:
18F has paid Mandrill account.
> Change SMTP config to use Mandrill

- .travis.yml
- Dockerfile
**Why**: We forgot to remove these references to it when we last
removed the dependency.
> Remove remaining traces of libxmlsec1

- app/assets/javascripts/misc/pw-strength.js
- app/assets/stylesheets/components/_tooltip.scss
- app/assets/stylesheets/components/all.scss
- app/views/devise/shared/_password_strength.html.slim
- spec/features/visitors/sign_up_spec.rb
**Why**: to give users context, feedback, and
suggestions as they are choosing their password
preview:
> Add pw strength tooltip

- config/locales/devise.en.yml
> Clear unneeded flash msg

- spec/controllers/devise/two_factor_authentication_controller_spec.rb
- spec/features/two_factor_authentication/sign_in_spec.rb
**Why**: There were some actions in the controller
that were not being tested.
> Add more specs for two_factor_authentication_controller

- app/controllers/application_controller.rb
- app/controllers/concerns/saml_idp_logout_concern.rb
- app/controllers/devise/two_factor_authentication_controller.rb
- app/controllers/saml_idp_controller.rb
- spec/controllers/saml_idp_controller_spec.rb
**Why**: So the session is completely cleared on sign_out
> Fix sign_out call so that all warden scopes are signed out

- Gemfile
**Why**:
Orderliness is a virtue.
> Alphabetize gems

- Gemfile
- Gemfile.lock
- Update bummr to the latest version
- Remove unnecessary version restrictions
> Prepare bummr for automated gem updates

- app/assets/images/check.svg
- app/assets/stylesheets/_base.scss
- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_heading.scss
- app/views/devise/confirmations/new.html.slim
- app/views/devise/passwords/new.html.slim
- app/views/devise/sessions/_form.html.slim
- app/views/devise/shared/_links.html.slim
- app/views/layouts/application.html.slim
- app/views/shared/_branding.html.slim
- app/views/shared/_messages.html.slim
- config/initializers/simple_form.rb
- config/locales/devise.en.yml
- config/locales/en.yml
- spec/features/visitors/password_recovery_spec.rb
- spec/lib/rails_logger_spec.rb
**Why**: improve look and feel of app
**What**:
* add icon to alert module (for flash messages)
* better placement of 'forgot password' link
* make logo clickable (links to homepage)
* small spacing tweaks
> Make UI tweaks

- app/assets/javascripts/app/pw-toggle.js
- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_password.scss
- spec/features/users/sign_in_spec.rb
- spec/features/users/user_edit_spec.rb
**Why**: we want this functionality on
all pages with a password input
> Add pw toggle to login / edit pages

- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/initializers/two_factor_auth_controller_override.rb
**Why**: We switched away from using letter_opener a while ago.
Also, remove some other duplicate and redundnat action_mailer
settings.
> Remove last traces letter_opener

- docs/frontend.md
**Why**: simplify front-end writeup to
better reflect our process and philosophy
> Update front end docs

- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/components/_util.scss
- app/helpers/form_helper.rb
- app/views/idv/confirmations/index.html.slim
- app/views/idv/questions/_multiple_choice.html.slim
- app/views/idv/questions/index.html.slim
- app/views/idv/sessions/index.html.slim
- app/views/session_timeout/_warning.html.slim
- config/locales/en.yml
- spec/features/idv/question_cycle_spec.rb
**Why**: unify look and feel within app
preview:
> Iterate on proofing UI

- .slim-lint.yml
- .travis.yml
- Gemfile
- app/mailers/user_mailer.rb
- app/views/dashboard/admin/_navigation.html.slim
- app/views/dashboard/index.html.slim
- app/views/devise/confirmations/new.html.slim
- app/views/devise/mailer/confirmation_instructions.html.slim
- app/views/devise/mailer/reset_password_instructions.html.slim
- app/views/devise/password_expired/show.html.slim
- app/views/devise/passwords/new.html.slim
- app/views/devise/sessions/_form.html.slim
- app/views/devise/shared/_auth_nav.html.slim
- app/views/devise/two_factor_authentication/show.html.slim
- app/views/layouts/_debug.html.slim
- app/views/layouts/application.html.slim
- app/views/layouts/user_mailer.html.slim
- app/views/saml_idp/shared/saml_post_binding.html.slim
- app/views/session_timeout/_warning.html.slim
- app/views/shared/_branding.html.slim
- app/views/shared/_user_search.html.slim
- app/views/test/saml_test/decode_response.html.slim
- app/views/user_mailer/email_changed.html.slim
- app/views/user_mailer/password_changed.html.slim
- app/views/user_mailer/signup_with_your_email.html.slim
- app/views/users/_user.html.slim
- config/locales/en.yml
**Why**: To keep our views nice and clean, and to be able to run
slim-lint on Travis since Code Climate does not have an engine for it
yet.
> Fix Slim offenses and remove unused views

- config/service_providers.yml
**Why:**
- Rails app needs entries.
**How:**
- Add entries in file.
> Add service_providers.yml entries for rails app.

- app/views/layouts/_debug.html.slim
- config/initializers/git_sha.rb
**Why**: The wrong URL was being displayed
**How**: Define the correct URL in single location
> Fix github URLs shown in debug mode

- app/views/dashboard/admin/_navigation.html.slim
**Why**: fixes wonky style/position
> Fix admin nav style

- Gemfile
- Gemfile.lock
- app/controllers/users/registrations_controller.rb
- app/views/devise/registrations/start.html.slim
- config/experiments.yml
- config/i18n-tasks.yml
- config/initializers/split.rb
- config/locales/en.yml
- config/locales/experiments.en.yml
- config/routes.rb
- spec/ab_testing/yaml_config_spec.rb
- spec/controllers/users/registrations_controller_spec.rb
- spec/views/devise/registrations/start.html.slim_spec.rb
**Why**: to support running a/b experiments to optimize experience
> Add A/B testing gem

- config/service_providers.yml
**Why**:
sp-rails demo app now supports SLO
see https://github.com/18F/identity-sp-rails/pull/15
> Add SLO links to sp-rails app

- .codeclimate.yml
- .reek
**Why**: To detect code smells. More info here:
https://github.com/troessner/reek
And a great talk by Sandi Metz about code smells:
https://www.youtube.com/watch?v=PJjHfa5yxlU
> Add reek engine to Code Climate

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_heading.scss
- app/assets/stylesheets/components/_nav.scss
- app/assets/stylesheets/components/all.scss
- app/assets/stylesheets/variables/_web.scss
- app/views/layouts/application.html.slim
- app/views/shared/_branding.html.slim
- app/views/shared/_nav.html.slim
- app/views/shared/_navigation_links.html.slim
**Why**: to integrate branding with navigational links
**Preview**:
> Add signed in/out navbar

- app/views/devise/passwords/edit.html.slim
- app/views/devise/passwords/new.html.slim
- app/views/devise/shared/_links.html.slim
- spec/controllers/devise/two_factor_authentication_setup_controller_spec.rb
- spec/factories/users.rb
- spec/features/saml/saml_spec.rb
- spec/features/two_factor_authentication/sign_in_spec.rb
- spec/features/users/sign_in_spec.rb
- spec/features/users/sign_out_spec.rb
- spec/features/users/user_edit_spec.rb
- spec/features/visitors/password_recovery_spec.rb
- spec/features/visitors/sign_up_spec.rb
- spec/support/features/session_helper.rb
- spec/support/saml_auth_helper.rb
- spec/views/devise/passwords/edit.html.slim_spec.rb
- spec/views/devise/passwords/new.html.slim_spec.rb
- spec/views/devise/two_factor_authentication/show.html.slim_spec.rb
**How**:
- Use Warden to sign in users instead of filling in forms with Capybara
- Replace feature specs with faster view specs and controller specs
> Speed up tests

- Dockerfile
- README.md
- bin/setup
**Why**:
- To reduce the amount of commands needed to set up Docker
- To use the official and latest Docker images
- To make it easier to deal with database changes, by using db:reset
> Improve Docker and local setup

- public/401.html
- public/404.html
- public/422.html
- public/500.html
- public/css/static.css
**Why**: DRYing error page stylez
> Add error pages css file

- config/service_providers.yml
**Why**: sp-sinatra app now has logout feature.
> Add SLO url for sp-sinatra app

- app/controllers/devise/two_factor_authentication_controller.rb
- app/controllers/devise/two_factor_authentication_setup_controller.rb
**Why**: To remove duplicate code
> Remove duplicate implementation of authenticate_scope!

- app/forms/update_user_profile_form.rb
- app/models/profile.rb
With this change we are now once again rubocop clean
> Fix rubocop warnings

- app/controllers/application_controller.rb
- app/controllers/devise/two_factor_authentication_controller.rb
- app/controllers/users/confirmations_controller.rb
- config/routes.rb
- spec/controllers/devise/two_factor_authentication_controller_spec.rb
- spec/controllers/users/omniauth_callbacks_controller_spec.rb
- spec/controllers/users/phone_confirmation_controller_spec.rb
- spec/features/users/sign_in_spec.rb
- spec/features/users/user_profile_spec.rb
- spec/features/visitors/password_recovery_spec.rb
- spec/features/visitors/sign_up_spec.rb
- spec/support/features/session_helper.rb
**Why**: Our routes are getting more complex and
confusing. This is a first pass and cleaning them
up.  More work to be done here.
> Reorganize and document config/routes.db

- spec/models/user_spec.rb
**Why**: Consistent rspec style
ref https://github.com/18F/identity-idp/pull/277/files/a72dad63862e258fc623d9c43a09854951f60ca8#r72084010
> Use is_expected.to rather than should

- app/controllers/concerns/saml_idp_auth_concern.rb
- lib/saml_idp_constants.rb
- spec/support/saml_auth_helper.rb
**Why**: This IdP is designed to support only LOA1 and
LOA3 (i.e. IAL1 and IAL2)
fixes: https://github.com/18F/identity-private/issues/550
> Remove support for LOA2

- app/views/home/index.html.slim
- config/locales/en.yml
- config/routes.rb
- spec/views/home/index.html.slim_spec.rb
**Why**:
* display welcome message and sign out link when signed in
* display sign in / up links when signed out
Preview:
> Add dynamic nav bar content

- config/initializers/devise.rb
**Why**: FedRAMP ATO requirement
> Set session timeout to 15 minutes

- .reek
- app/controllers/users/registrations_controller.rb
- app/forms/update_user_profile_form.rb
- app/views/users/registrations/edit.html.slim
- config/locales/en.yml
- config/routes.rb
- spec/controllers/users/registrations_controller_spec.rb
- spec/features/users/user_edit_spec.rb
- spec/forms/update_user_profile_form_spec.rb
- spec/requests/edit_user_spec.rb
- spec/services/user_flash_updater_spec.rb
- spec/views/profile/index.html.slim_spec.rb
- spec/views/users/registrations/edit.html.slim_spec.rb
This reverts commit 4ee002e426f490db4adbb88a9d0ee795c5348ccb.
Moncef has some feedback on this change that I want
to address before re-landing.
> Revert "Remove #edit and #update from registrations_controller (#303)"

- .codeclimate.yml
- app/controllers/concerns/saml_idp_logout_concern.rb
- app/controllers/idv/sessions_controller.rb
- app/controllers/test/saml_test_controller.rb
- app/controllers/users/passwords_controller.rb
- app/helpers/form_helper.rb
- app/models/profile.rb
- config/initializers/secure_headers.rb
**Why**: Its important to understand why each suppresion
is there so we know which ones needs fixing and which
ones don't (and why they don't).
> Add explanations to all rubocop suppressions

- config/initializers/omniauth.rb
- spec/controllers/saml_idp_controller_spec.rb
- spec/features/saml/saml_spec.rb
- spec/lib/service_provider_spec.rb
- spec/support/saml_auth_helper.rb
- spec/support/saml_response_helper.rb
**Why**: Technical debt repayment day.
**How**: Fixes SP-vs-IdP cert+fingerprint configuration for all tests.
> Implement pending tests

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_heading.scss
- app/assets/stylesheets/components/_scaffolding.scss
- app/assets/stylesheets/variables/_web.scss
- app/controllers/application_controller.rb
- app/controllers/home_controller.rb
- app/controllers/profile_controller.rb
- app/helpers/application_helper.rb
- app/views/devise/confirmations/show.html.slim
- app/views/devise/two_factor_authentication/show.html.slim
- app/views/home/index.html.slim
- app/views/layouts/_debug.html.slim
- app/views/layouts/application.html.slim
- app/views/layouts/card.html.slim
- app/views/layouts/card_wide.html.slim
- app/views/profile/index.html.slim
- app/views/session_timeout/_warning.html.slim
- app/views/shared/_footer.html.slim
- app/views/shared/_nav.html.slim
- app/views/shared/_nav_lite.html.slim
- app/views/users/phone_confirmation/show.html.slim
- app/views/users/totp_setup/new.html.slim
- config/application.rb
- config/locales/en.yml
- spec/features/two_factor_authentication/sign_in_spec.rb
- spec/views/devise/two_factor_authentication/show.html.slim_spec.rb
- spec/views/layouts/user_mailer.html.slim_spec.rb
- spec/views/shared/_nav.html.slim_spec.rb
**Why**:
* accomodate new layouts / body content widths
* DRYing nav + footer
* clean up & simplify copy
> Iterate on UI

- app/views/devise/registrations/verify_email.html.slim
- config/locales/en.yml
- spec/views/devise/registrations/verify_email.html.slim_spec.rb
**Why**: confirm email resend link was off; fixed and added test
> Fix link on verify email page

- app/views/shared/_nav.html.slim
**Why**: was taking up too much vertical space
> Make top nav slimmer

- app/assets/stylesheets/components/_tooltip.scss
- app/views/profile/index.html.slim
**Why**: minor visual improvements
> Tweak tooltips

- app/assets/stylesheets/components/_number.scss
- app/assets/stylesheets/components/all.scss
- app/controllers/idv/sessions_controller.rb
- app/controllers/idv_controller.rb
- app/views/idv/index.html.slim
- app/views/idv/sessions/index.html.slim
- app/views/idv/sessions/show.html.slim
**Why**: better layout, improved design
Preview:
> Update proofing UI

- config/service_providers.yml
**Why** 
The `issuer` is now using hostname in the [dashboard](https://github.com/18F/identity-dashboard/blob/master/config/saml.yml#L4) application
**How** 
Add entries for each stage in the production SP entries
> Updates dashboard SP entries

- app/controllers/application_controller.rb
- app/models/user.rb
- spec/models/user_spec.rb
**Why**: Encourage use of UserDecorator by making it easier
to construct.
Note this is conceptually like a Draper-lite pattern. Maybe we should just use Draper instead? https://github.com/drapergem/draper
> Add User.decorate method

- .reek
- Gemfile.lock
- app/controllers/concerns/saml_idp_logout_concern.rb
- app/controllers/saml_idp_controller.rb
- app/models/identity.rb
- app/models/null_identity.rb
- app/models/user.rb
- app/services/logout_response_handler.rb
- app/services/single_logout_handler.rb
- spec/controllers/saml_idp_controller_spec.rb
- spec/models/identity_spec.rb
**Why**: So our code smells better
> Fix reek offenses in SamlIdp-related files

- app/controllers/concerns/saml_idp_auth_concern.rb
- app/controllers/concerns/saml_idp_logout_concern.rb
- app/controllers/devise/two_factor_authentication_controller.rb
- app/controllers/users/confirmations_controller.rb
- app/decorators/user_decorator.rb
- app/mailers/custom_devise_mailer.rb
- app/models/identity.rb
- app/services/attribute_asserter.rb
- app/services/single_logout_handler.rb
- app/services/user_otp_sender.rb
- config/initializers/saml_idp.rb
- db/migrate/20160801193239_add_identity_uuid.rb
- db/schema.rb
- db/seeds.rb
- lib/service_provider.rb
- spec/controllers/saml_idp_controller_spec.rb
- spec/controllers/users/totp_setup_controller_spec.rb
- spec/decorators/user_decorator_spec.rb
- spec/features/saml/saml_spec.rb
- spec/lib/service_provider_spec.rb
- spec/models/authorization_spec.rb
- spec/models/identity_spec.rb
- spec/services/attribute_asserter_spec.rb
- spec/services/identity_linker_spec.rb
- spec/views/devise/mailer/confirmation_instructions.html.slim_spec.rb
- spec/views/devise/two_factor_authentication/show.html.slim_spec.rb
**Why**: NIST requires MBUN per user per service provider.
> MBUN is unique per Service Provider

- CONTRIBUTING.md
> Update development guide links in CONTRIBUTING.md

- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_splash.scss
- app/assets/stylesheets/pages/all.scss
- app/views/splash/index.html.slim
**Why**: inline styles are blocked
> Remove inline style

- app/views/splash/index.html.slim
**Why**: per feedback from Joel
> Make landing page tweaks

- config/service_providers.yml
The Rails demo SP has the wrong endpoints
Update the endpoints to match the current URL structure
> Updates endpoints for sp-rails demo

- app/validators/form_email_validator.rb
- spec/forms/update_user_email_form_spec.rb
> Remove unnecessary conditionals from email form

- app/assets/javascripts/app/form-field-format.js
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_heading.scss
- app/assets/stylesheets/components/_password.scss
- app/controllers/users/totp_setup_controller.rb
- app/views/devise/two_factor_authentication/show.html.slim
- app/views/devise/two_factor_authentication_setup/index.html.slim
- app/views/idv/sessions/index.html.slim
- app/views/profile/index.html.slim
- app/views/users/phone_confirmation/show.html.slim
- app/views/users/totp_setup/new.html.slim
- config/locales/en.yml
**Why**: Continued improvements based on visual design feedback
> Iterate on visual design cont.

- config/initializers/rack_attack.rb
- config/initializers/secure_headers.rb
- config/initializers/simple_form.rb
This PR fixes 3 different deprecation warnings in 3 commits. Please don't squash the commits.
> Fix various deprecation warnings

- app/controllers/test/saml_test_controller.rb
- app/services/test/single_logout_service.rb
- app/services/test/slo_response_decoder.rb
**Why**: To address Reek and Rubocop offenses
> Refactor SamlTestController

- .reek
- app/controllers/concerns/valid_email_parameter.rb
- app/controllers/users/passwords_controller.rb
- app/controllers/users/phone_confirmation_controller.rb
- app/controllers/users/totp_setup_controller.rb
- app/decorators/user_decorator.rb
- app/forms/password_form.rb
- app/services/omniauth_authorizer.rb
- config/initializers/devise_mailer_helpers.rb
**Why**: To improve performance.
> Fix DuplicateMethodCall Reek offenses

- .reek
- app/controllers/users/passwords_controller.rb
- app/models/null_user.rb
- app/policies/user_policy.rb
- app/services/request_password_reset.rb
- spec/policies/user_policy_spec.rb
- spec/services/request_password_reset_spec.rb
**Why**: To fix Reek and Rubocop offenses
> Refactor PasswordsController#create

- app/assets/javascripts/app/form-validation.js
- app/assets/stylesheets/components/_btn.scss
- app/assets/stylesheets/components/_disclaimer.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/variables/_web.scss
- app/views/idv/sessions/index.html.slim
> Visual tweaks

- app/assets/stylesheets/components/_margin.scss
- app/assets/stylesheets/components/all.scss
- app/assets/stylesheets/variables/_web.scss
- app/views/profile/index.html.slim
- app/views/users/edit_email/edit.html.slim
- app/views/users/edit_phone/edit.html.slim
**Why**: Small visual tweaks requested in https://github.com/18F/identity-private/issues/594
> Visual design feedback

- app/views/splash/index.html.slim
**Why**: Small copy updates for https://github.com/18F/identity-private/issues/590
> Update copy on splash page

- app/assets/stylesheets/components/_btn.scss
> Tweak to login / signup header

- app/assets/stylesheets/components/_btn.scss
- app/assets/stylesheets/components/_space-misc.scss
- app/assets/stylesheets/variables/_web.scss
- app/views/shared/_footer_lite.html.slim
- app/views/shared/_nav.html.slim
> Nav, footer, btn tweaks

- app/assets/javascripts/app/pw-toggle.js
- app/assets/stylesheets/components/_form.scss
- app/views/idv/sessions/show.html.slim
- spec/features/users/sign_in_spec.rb
- spec/features/visitors/sign_up_spec.rb
**Why**: As per visual design, implemented wtf-forms css for checkbox and radio inputs
> Improve checkbox and radio inputs

- app/controllers/idv_controller.rb
- app/views/idv/cancel.html.slim
- config/locales/en.yml
> Proofing cancel copy

- app/assets/javascripts/app/form-validation.js
- app/assets/stylesheets/components/_form.scss
**Why**: Remove use of pseudo css classes for better IE9 support
> Fix IE9 form validation

- app/views/shared/_footer.html.slim
- app/views/shared/_footer_lite.html.slim
**Why**: footer was missing class, not getting flex:none
> Fix footer appearance

- app/assets/images/clock.svg
- app/assets/stylesheets/components/_modal.scss
- app/assets/stylesheets/components/_scaffolding.scss
- app/assets/stylesheets/components/all.scss
- app/views/layouts/application.html.slim
- app/views/session_timeout/_warning.html.slim
- app/views/shared/_messages.html.slim
- config/locales/en.yml
- spec/features/users/sign_in_spec.rb
**Why**: too easy to miss before
Preview:
> Update session timeout display

- app/mailers/user_mailer.rb
> Change default From email address

- app/views/shared/_messages.html.slim
**Why**: serif font only for short messages
> Tweak alert message

- app/mailers/user_mailer.rb
- config/application.yml.example
- config/initializers/devise.rb
**Why**: All environment vars in central place
> Email From in application.yml

- app/views/idv/cancel.html.slim
- config/locales/en.yml
**Why**: per latest ux / content guidance
> Tweak idv cancel page

- bin/setup
> Add branding flair :)

- app/forms/idv/finance_form.rb
- app/forms/idv/profile_form.rb
- config/locales/en.yml
- spec/forms/idv/finance_form_spec.rb
- spec/forms/idv/profile_form_spec.rb
**Why**: Form validation should happen client- and server-side.
**How**: Add checks for DOB and finance account string (CCN).
> Add server-side IdV validation

- app/helpers/form_helper.rb
**Why**: If we ask for state, we want a valid value.
> Always require state from dropdown

- app/forms/idv/profile_form.rb
- db/migrate/20160908195301_profile_dob_date.rb
- db/schema.rb
- spec/forms/idv/profile_form_spec.rb
**Why**: Adding db constraint prevents bad data.
> Migrate profiles.dob to date column

- app/assets/stylesheets/components/_tooltip.scss
- app/views/profile/index.html.slim
- config/locales/en.yml
**Why**: per latest designs / content
> Add idv section tooltip on profile

- app/views/shared/_messages.html.slim
**Why**: For better accessibility
> Add alert role to flash messages

- app/views/profile/index.html.slim
**Why**: improves look & feelz
> Fix spacing/style re: account history in profile

- app/assets/javascripts/app/idv-finance-helper.js
- app/assets/javascripts/application.js
- app/controllers/idv/finance_controller.rb
- app/decorators/finance_form_decorator.rb
- app/views/idv/finance/new.html.slim
- config/initializers/simple_form.rb
- config/locales/en.yml
- spec/features/idv/flow_spec.rb
**Why**: when users select a radio option, the text input
below should update accordingly
> Add styles / js to IDV finance form

- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_space-misc.scss
- app/assets/stylesheets/components/_typography.scss
- app/assets/stylesheets/email.css.scss
- app/controllers/contact_controller.rb
- app/forms/contact_form.rb
- app/mailers/user_mailer.rb
- app/views/contact/new.html.slim
- app/views/user_mailer/contact_request.html.slim
- config/application.yml.example
- config/initializers/figaro.rb
- config/initializers/simple_form.rb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/contact_controller_spec.rb
- spec/forms/contact_form_spec.rb
- spec/mailers/user_mailer_spec.rb
**Why**: so people can easily get in touch
**How**: user fills out form -> info gets emailed to us -> :)
> Add contact page

- app/jobs/sms_sender_number_change_job.rb
**Why**: Trailing period is causing a 404 error. https://github.com/18F/identity-private/issues/817
> Update sms message

- config/locales/en.yml
**Why**: To adhere to content style guide, https://github.com/18F/identity-private/issues/819
> Update page titles to sentence case

- public/429.html
**Why**: Updated path to location of images/css. https://github.com/18F/identity-private/issues/808
> Fix rate limit error page styles

- spec/services/idv/session_spec.rb
**Why**: 100% test coverage is a virtue
> Add test coverage for Idv::Session

- app/assets/javascripts/app/pw-toggle.js
- app/assets/stylesheets/components/_heading.scss
- app/assets/stylesheets/components/_password.scss
- app/assets/stylesheets/components/_space-misc.scss
- app/views/devise/confirmations/show.html.slim
- app/views/devise/registrations/new.html.slim
- app/views/devise/registrations/start.html.slim
- app/views/devise/shared/_password_strength.html.slim
- app/views/devise/two_factor_authentication/show.html.slim
- app/views/shared/choose_delivery_method.html.slim
- app/views/users/edit.html.slim
- app/views/users/edit_email/edit.html.slim
- app/views/users/edit_password/edit.html.slim
- app/views/users/edit_phone/edit.html.slim
- app/views/users/phone_confirmation/show.html.slim
- app/views/users/show.html.slim
- app/views/users/totp_setup/new.html.slim
- app/views/users/totp_setup/start.html.slim
- config/initializers/simple_form.rb
- config/locales/en.yml
- spec/features/idv/flow_spec.rb
**Why**: lots of little improvements
> Visual design tweaks

- README.md
Our README is out of date
Updates instructions
> Updates README for deployments

- app/assets/stylesheets/components/_border.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_typography.scss
- app/views/devise/two_factor_authentication/show.html.slim
- app/views/devise/two_factor_authentication_setup/index.html.slim
- app/views/shared/choose_delivery_method.html.slim
- app/views/two_factor_authentication/_phone_confirmation_fallback.html.slim
- app/views/two_factor_authentication/otp_verification/show.html.slim
- app/views/two_factor_authentication/recovery_code/show.html.slim
- app/views/users/edit_email/edit.html.slim
- app/views/users/edit_password/edit.html.slim
- app/views/users/edit_phone/edit.html.slim
- app/views/users/phone_confirmation/_phone_confirmation_fallback.html.slim
- app/views/users/phone_confirmation/show.html.slim
- app/views/users/totp_setup/new.html.slim
- config/locales/devise.two_factor_authentication.en.yml
- config/locales/en.yml
- spec/features/saml/saml_spec.rb
- spec/features/two_factor_authentication/sign_in_spec.rb
- spec/features/visitors/sign_up_spec.rb
- spec/support/features/session_helper.rb
- spec/views/two_factor_authentication/otp_verification/show.html.slim_spec.rb
- spec/views/users/phone_confirmation/show.html.slim_spec.rb
**Why**: per end-to-end walkthrough feedback
> UI touch-ups

- config/application.rb
- package.json
**Why**: messing up deploys (possibly)
> Remove es2015-loose transpile

- app/assets/javascripts/application.js
- app/assets/javascripts/misc/pw-strength.js
- config/locales/en.yml
- package.json
- spec/features/visitors/sign_up_spec.rb
Precompiling assets is failing inexplicably on demo
Remove extra interpolation
Revert to previous babel-preset
Add an empty line, because obviously
> Fixes issue with compiling assets remotely

- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_list.scss
- app/assets/stylesheets/components/_space-misc.scss
- app/views/idv/finance/new.html.slim
- app/views/idv/index.html.slim
- app/views/idv/phone/new.html.slim
- app/views/idv/review/new.html.slim
- app/views/idv/sessions/new.html.slim
- config/initializers/simple_form.rb
- config/locales/en.yml
- spec/features/idv/flow_spec.rb
- spec/features/saml/saml_spec.rb
**Why**: Based on walkthrough session
> Iterate visual design

- app/assets/stylesheets/components/_password.scss
- app/assets/stylesheets/components/_space-misc.scss
- app/views/devise/shared/_password_strength.html.slim
> Fix pw strength module spacing

- app/assets/stylesheets/components/_list.scss
**Why**: Browser compatability fix
> Fix list item bullets in IE

- README.md
* Need to see emails in order to complete sign up process
> Add info about mailcatcher to README

- app/views/idv/sessions/new.html.slim
- config/locales/en.yml
**Why**: Small visual and copy changes for Basic information IDV page
> Clean up basic info page

- config/application.rb
- config/environments/test.rb
- config/initializers/active_job.rb
**Why**:
This is where it lives more typically and where ppl would go to find
it
> Move active job config to `application.rb`

- app/controllers/users/phone_confirmation_controller.rb
**Why**: I like to DO the TODOs
> Small refactor in controller method

- app/views/contact/new.html.slim
- config/initializers/simple_form.rb
- config/locales/en.yml
- spec/features/visitors/contact_spec.rb
- spec/views/contact/new.html.slim_spec.rb
**Why**: crossing the t's, dotting the i's, making it pretty
> Add testz and tweak UI for 'contact us' page

- Capfile
- config/deploy.rb
- Remove commented whenever require from Capfile
- Add New Relic notification to Capistrano deploy pipeline
Should we add a `newrelic.yml` config with ENV vars or an example file?
> New Relic deployment notifications

- app/views/devise/sessions/new.html.slim
- app/views/devise/two_factor_authentication/show.html.slim
- app/views/idv/phone_confirmation/show.html.slim
- app/views/layouts/application.html.slim
- app/views/layouts/card.html.slim
- app/views/shared/_footer_lite.html.slim
- app/views/shared/_nav_lite.html.slim
- app/views/shared/choose_delivery_method.html.slim
- app/views/two_factor_authentication/otp_verification/show.html.slim
- app/views/users/phone_confirmation/show.html.slim
- app/views/users/totp_setup/start.html.slim
- config/initializers/simple_form.rb
**Why**: better scaling for small screenz
> UI spacing & misc tweaks

- app/views/layouts/application.html.slim
- config/application.yml.example
- config/initializers/figaro.rb
- config/routes.rb
- lib/feature_management.rb
- lib/figaro_yaml_validator.rb
- spec/lib/figaro_yaml_validator_spec.rb
**What**:
Use "true" and "false" instead of "yes" and "no"
Raise RuntimeError if yes or no pop up
**Why**:
Consistency ensures we are setting up features correctly
Closes https://github.com/18F/identity-private/issues/851
> Make Figaro values more consistent

- .rubocop.yml
- app/controllers/concerns/saml_idp_auth_concern.rb
- app/views/idv/cancel.html.slim
- app/views/idv/finance/new.html.slim
- app/views/idv/index.html.slim
- app/views/idv/phone_confirmation/show.html.slim
- app/views/idv/questions/index.html.slim
- app/views/idv/review/new.html.slim
- app/views/idv/sessions/new.html.slim
- app/views/profile/index.html.slim
- app/views/users/_user.html.slim
- app/views/users/index.html.slim
- config/routes.rb
**Why**: I just flipped through most of the view templates and saw that
we had extra newlines in some places and my natural instinct was to
remove them.
I also have my dotfiles set up to show a line at 80 chars, but I
realized after a bit that the limit on this proj is 100 so I made that
clearer in our rubocop config file.
The third small change is to put called methods below the methods in
which they are called. There is a name for that, but I am not able to
recall it at this moment...
> Small formatting stuff

- config/locales/en.yml
Reverts 18F/identity-idp#559
Nothing to see here, just fine-tuning our workflows.
> Revert "editted a button"

- config/service_providers.yml
**Why**: better demo experience
> Add sp fields to config for demo app

- app/assets/javascripts/misc/i18n-mode.js
**Why**:
* js scripts in misc dir are not being transpiled, thus cant use things like "let"
* this was breaking deploys (asset pre-compilation)
> Tweak non babelified js

- app/views/devise/sessions/new.html.slim
- config/initializers/simple_form.rb
- config/locales/en.yml
- spec/views/devise/sessions/new.html.slim_spec.rb
**Why**: need to have it!
preview:
> Add login text / link re: privacy consent

- app/controllers/pages_controller.rb
- app/views/devise/registrations/new.html.slim
- app/views/devise/sessions/new.html.slim
- app/views/pages/privacy_policy.html.slim
- config/locales/en.yml
- config/routes.rb
- spec/support/features/session_helper.rb
- spec/views/devise/registrations/new.html.slim_spec.rb
- spec/views/devise/sessions/new.html.slim_spec.rb
- spec/views/pages/privacy_policy.html.slim_spec.rb
**Why**: gotta have it
preview:
> Terms of service beginnings

- app/views/shared/_nav_branded.html.slim
- app/views/shared/_nav_lite.html.slim
> Fix nav logo spacing

- config/application.rb
What: Switch default timezone to UTC
How: Change application.rb
Why: UTC is fairly standard for server things, let's be standard!
> Switch default timezone to UTC

- app/helpers/session_timeout_warning_helper.rb
- spec/features/users/sign_in_spec.rb
- spec/helpers/session_timeout_warning_helper_spec.rb
**Why**:
* Otherwise, you will see this modal every 8 seconds :(
> Use `.minutes` for Figaro env var

- app/views/devise/registrations/start.html.slim
- config/locales/devise.en.yml
- config/locales/devise.two_factor_authentication.en.yml
- config/locales/en.yml
- config/locales/experiments.en.yml
- spec/features/visitors/navigation_spec.rb
- spec/features/visitors/password_recovery_spec.rb
- spec/mailers/user_mailer_spec.rb
- spec/views/devise/mailer/confirmation_instructions.html.slim_spec.rb
- spec/views/layouts/user_mailer.html.slim_spec.rb
**Why**:
* We've been wanting these for a while
* Contains most of the fixes for authentication; leaves verification
mostly untouched
> Round of content changes

- Gemfile.lock
**Why**: To get the latest and greatest
> Update overcommit from 0.35.0 to 0.37.0

- spec/features/users/sign_in_spec.rb
**Why**: travis-ci may experience network slowness that causes
the session to time out too soon during capybara javascript
tests. We need the session TTL to be long enough for a real
HTTP request/response in a high load environment.
> Bump session TTL for capybara tests

- config/locales/devise.en.yml
- config/locales/devise.two_factor_authentication.en.yml
- config/locales/en.yml
- config/locales/simple_form.en.yml
**Why**:
* Consistency FTW
**How**:
* Use multi-line yml for all strings over 100 chars
* Use smart quotes everywhere
* Do not put translations in quotations unless required (eg: contains
colon)
> Fix locales formatting

- README.md
Separates `brew start` commands
> Updates getting started instructions

- app/views/devise/passwords/edit.html.slim
- config/locales/forms/en.yml
- config/locales/links/en.yml
cc: https://github.com/18F/identity-private/issues/981
> Remove unnecessary link

- app/views/devise/registrations/verify_email.html.slim
- config/locales/notices/en.yml
cc: https://github.com/18F/identity-private/issues/1011
> Add link to verify email page

- spec/features/visitors/sign_up_spec.rb
**Why**:
* Want to make it clear that users without a password will not receive
this email
> Clarify scenario in feature spec

- .reek
- app/decorators/service_provider_session_decorator.rb
- app/decorators/session_decorator.rb
- app/views/devise/sessions/new.html.slim
- app/views/layouts/application.html.slim
- config/locales/headings/en.yml
- config/locales/links/en.yml
- spec/views/devise/sessions/new.html.slim_spec.rb
**Why**:
- We not have these nifty session decorators that allow us to use
polymorphism instead!
> Move sp-related conditionals out of views

- app/assets/javascripts/app/form-validation.js
**Why**:
* we need to re-validate form fields as people update
their inputs (and before they submit the form)
> Fix client side form validation

- app/decorators/user_decorator.rb
- config/locales/mailer/en.yml
- spec/decorators/user_decorator_spec.rb
- spec/views/devise/mailer/confirmation_instructions.html.slim_spec.rb
> Fix "Account" typo

- app/views/shared/_nav_auth.html.slim
- config/locales/shared/en.yml
**Why**:
* Was accidentally removed
https://github.com/18F/identity-idp/commit/44349df995f51897f37f9688384476dedf64c6f4#commitcomment-19664904
> Re-add bold style to welcome message in header

- app/views/user_mailer/signup_with_your_email.html.slim
- config/locales/user_mailer/en.yml
**Why**: To match most recent content docs
> Deletes mailer footer

- app/views/two_factor_authentication/totp_verification/show.html.slim
**Why**: UI components need space
> Fix authenticator UI

- Gemfile
- Gemfile.lock
- app/models/authorization.rb
- spec/forms/contact_form_spec.rb
- spec/forms/idv/finance_form_spec.rb
- spec/forms/idv/profile_form_spec.rb
- spec/forms/otp_delivery_selection_form_spec.rb
- spec/forms/password_form_spec.rb
- spec/forms/two_factor_setup_form_spec.rb
- spec/forms/update_user_password_form_spec.rb
- spec/models/authorization_spec.rb
- spec/rails_helper.rb
- spec/support/shared_examples_for_phone_validation.rb
- spec/support/shoulda_matchers.rb
**Why**: To use the latest and greatest
**How**:
- Add RSpec config per 3.x instructions
- Update specs
> Update shoulda-matchers from 2.8.0 to 3.1.1

- config/locales/devise/en.yml
- config/locales/jobs/en.yml
- config/locales/user_mailer/en.yml
**Why** Clarify instructions to users who try to sign up with an email already in use. Also a few minor updates for brevity and plain language throughout.
> Update email copy

- app/views/idv/activated.html.slim
- app/views/idv/cancel.html.slim
- app/views/idv/fail.html.slim
- app/views/idv/finance/new.html.slim
- app/views/idv/index.html.slim
- app/views/idv/phone/new.html.slim
- app/views/idv/review/new.html.slim
- app/views/idv/sessions/new.html.slim
- app/views/profile/index.html.slim
- config/locales/headings/en.yml
- config/locales/profile/en.yml
**Why**: just a few small tweaks around spacing, header sizing, et al.
> UI tweaks & fixes

- config/locales/idv/en.yml
**Why**: Because typos are not good
> Make a few minor text changes

- app/controllers/pages_controller.rb
**Why**: Forgot to remove it before
> Remove cruft from CORS integration

- app/views/pages/privacy_policy.html.slim
- config/locales/headings/en.yml
- config/locales/pages/en.yml
- config/routes.rb
- spec/views/pages/privacy_policy.html.slim_spec.rb
**Why**:
Lorem ipsum is distracting
screenie:
> Add current working copy for privacy policy

- config/locales/notices/en.yml
- spec/features/visitors/password_recovery_spec.rb
**Why**: To bring them in line with our styleguide
> Update notification messages

- app/views/profile/index.html.slim
- config/locales/tooltips/en.yml
> Replace placeholder tooltip for 2FA

- config/initializers/filter_parameter_logging.rb
**Why**: Do not leak PII into logs
> Add IdV form params to filtered list

- config/service_providers.yml
**Why**: To get the full branded experience
> Add more attribute to sp.dev YAML entry

- app/decorators/service_provider_session_decorator.rb
- app/decorators/session_decorator.rb
- app/views/idv/_hardfail4.html.slim
- app/views/idv/fail.html.slim
- config/locales/idv/en.yml
- spec/views/idv/fail.html.slim_spec.rb
**Why**: Implements new guidance from content
> Update IDV error messages

- Procfile
- bin/pretty-json-logs
- config/application.yml.example
**Why**:
Makes development easier with foreman
cc @hursey013
> Print Rails logs to STDOUT in development

- .rubocop.yml
- app/views/idv/activated.html.slim
- app/views/idv/review/new.html.slim
- app/views/idv/sessions/dupe.html.slim
- app/views/profile/index.html.slim
- app/views/session_timeout/_expired.html.slim
- app/views/two_factor_authentication/otp_verification/show.html.slim
- app/views/two_factor_authentication/recovery_code_verification/show.html.slim
- app/views/two_factor_authentication/totp_verification/show.html.slim
- config/initializers/time_formats.rb
- config/locales/idv/en.yml
- config/locales/notices/en.yml
- lib/rspec/formatters/user_flow_formatter.rb
**Why**: So that Code Climate reports Rails offenses.
> Enable Rails cops in rubocop.yml

- app/controllers/devise/two_factor_authentication_setup_controller.rb
- app/controllers/idv/finance_controller.rb
- app/controllers/idv/phone_controller.rb
- app/controllers/idv/review_controller.rb
- app/controllers/idv/sessions_controller.rb
- app/controllers/two_factor_authentication/otp_verification_controller.rb
- app/controllers/two_factor_authentication/recovery_code_controller.rb
- app/controllers/users/registrations_controller.rb
- app/services/analytics.rb
- spec/controllers/users/registrations_controller_spec.rb
**Why**: for easier analysis, funnel tracking
> Add more analytics events

- app/decorators/service_provider_session_decorator.rb
- app/decorators/session_decorator.rb
- app/views/devise/passwords/new.html.slim
- app/views/devise/sessions/new.html.slim
- config/locales/devise/en.yml
- config/locales/headings/en.yml
- config/locales/idv/en.yml
- config/locales/instructions/en.yml
- config/locales/links/en.yml
- config/locales/pages/en.yml
- config/locales/user_mailer/en.yml
- config/locales/zxcvbn/en.yml
- spec/features/visitors/password_recovery_spec.rb
- spec/views/devise/sessions/new.html.slim_spec.rb
**Why**:
* Few unfinished items
**What**:
* Make "with sp" and "without sp" locales consistent with others
* "Forget your password?" -> "Forgot your password?"
* Use smartquotes everywhere
> Follow up on localization PR #709

- app/assets/stylesheets/components/_alert.scss
- app/views/profile/index.html.slim
**Why**: needed a little love
Preview:
> Tweak UI around new recovery code

- db/migrate/20161027215500_add_users_salt.rb
- db/migrate/20161031210117_add_encryption_key_to_users.rb
- db/migrate/20161109203414_limit_sessions.rb
- db/migrate/20161116193316_set_user_password_salt.rb
- db/migrate/20161118150203_add_recovery_salt.rb
- db/migrate/20161118150204_add_scrypt_cost.rb
- db/migrate/20161118150205_add_user_email_fingerprint.rb
- db/migrate/20161121183402_add_user_email_fingerprint_index.rb
- db/schema.rb
**Why**: Devise method conflicts because columns change
from email -> email_fingerprint.
> Fix migrations for User email encryption

- .reek
- app/controllers/two_factor_authentication/otp_verification_controller.rb
- app/controllers/users/registrations_controller.rb
- app/forms/register_user_email_form.rb
- app/services/analytics.rb
- spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
- spec/controllers/users/registrations_controller_spec.rb
- spec/forms/register_user_email_form_spec.rb
- spec/forms/update_user_email_form_spec.rb
- spec/support/shared_examples_for_email_validation.rb
**Why**: To better group registration events and their properties.
> Consolidate Registration analytics

- app/views/session_timeout/_expired.html.slim
- spec/features/users/sign_in_spec.rb
**Why**: For a better user experience
> Link to current page in session expired modal

- db/migrate/20161118150205_add_user_email_fingerprint.rb
**Why**: When doing a rake db:rollback and the db:migrate,
non-unique emails may have been introduced.
This came up when testing encryption problems in qa env.
> Improve email encryption rollback resiliency

- config/service_providers.yml
The dashboard application expects the email attribute
Adds email to the default bundle for the dashboard SP
> Adds email to attribute bundle

- app/views/pages/page_not_found.html.slim
- public/401.html
- public/422.html
- public/429.html
- public/500.html
- spec/features/accessibility/static_pages_spec.rb
**Why**: Accessibility requires it
> Add `alt` tag to all login.gov logos

- config/locales/contact/en.yml
- config/locales/devise/en.yml
- config/locales/errors/en.yml
- config/locales/event_types/en.yml
- config/locales/experiments/en.yml
- config/locales/forms/en.yml
- config/locales/headings/en.yml
- config/locales/idv/en.yml
- config/locales/instructions/en.yml
- config/locales/jobs/en.yml
- config/locales/links/en.yml
- config/locales/mailer/en.yml
- config/locales/notices/en.yml
- config/locales/pages/en.yml
- config/locales/profile/en.yml
- config/locales/shared/en.yml
- config/locales/simple_form/en.yml
- config/locales/titles/en.yml
- config/locales/tooltips/en.yml
- config/locales/user_mailer/en.yml
- config/locales/zxcvbn/en.yml
**Why**: `i18n-tasks normalize` is MAGIC
> Alpha order and "normalize" locales

- app/services/analytics.rb
- spec/forms/password_form_spec.rb
This is a quick PR that removes unused code and adds a missing spec. Please preserve both commits.
> Code cleanup

- db/migrate/20161122160523_drop_user_email_plain.rb
- db/schema.rb
#759 is successfully deployed on all AWS envs.
> Drop User.email_plain

- Procfile
- config/sidekiq.yml
**Why**:
Lets us add new queues and change priorities without having to
make a separate PR to the devops repo
> Move sidekiq config into config/sidekiq.yml

- app/validators/form_password_validator.rb
- spec/forms/password_form_spec.rb
- spec/forms/reset_password_form_spec.rb
**Why**:
The benefit to having the custom dictionary is pretty negligable and
keeping it means having to duplicate code on the client side, and keep
the code in sync
> Removes custom password dictionary from server

- app/controllers/users/totp_setup_controller.rb
- app/forms/totp_setup_form.rb
- app/services/analytics.rb
- spec/controllers/users/totp_setup_controller_spec.rb
- spec/forms/totp_setup_form_spec.rb
**Why**: To track success and failure in the same event
> Consolidate TOTP setup analytics

- config/application.yml.example
**Why**:
"Comments are lies waiting to happen"
The PeriodicalQuery() function has been gone since 63b01113551d3
> Remove out-of-date information from application.yml comments

- docs/pii-encryption.md
**Why**: Narrative explanation of how we encrypt PII, for public review.
> Add PII encryption documentation

- .rubocop.yml
- config/routes.rb
**Why**: Makes it easier to read / refactor
> Alpha order routes file

- config/initializers/sidekiq.rb
- lib/sidekiq_logger_formatter.rb
- spec/lib/sidekiq_logging_formatter_spec.rb
**Why**: Sidekiq logs job arguments by default, and those arguments
may contain PII like email address or phone number.
> Redact PII from Sidekiq logs

- app/views/idv/index.html.slim
- app/views/idv/sessions/new.html.slim
- config/locales/idv/en.yml
**Why**: We do not support Individual Tax Identification Number for
proofing purposes.
> Remove Individual Tax Identification Number refs

- config/locales/mailer/en.yml
- config/locales/user_mailer/en.yml
**Why**: Very minor copy tweaks based on latest content guidance.
> Copy tweaks for emails

- .eslintrc
- Gemfile
- Gemfile.lock
- Makefile
- README.md
- app/assets/javascripts/app/utils/countdown-timer.js
- app/views/session_timeout/_ping.js.erb
- app/views/two_factor_authentication/shared/max_login_attempts_reached.html.erb
- config/application.rb
- config/initializers/assets.rb
- config/initializers/secure_headers.rb
- config/initializers/teaspoon.rb
- package.json
- spec/javascripts/app/utils/countdown-timer_spec.js
- spec/javascripts/app/utils/ms-formatter_spec.js
- spec/javascripts/spec_helper.js
- spec/teaspoon_env.rb
**Why**: To enable JavaScript unit tests
> Adds teaspoon and mocha

- app/views/devise/passwords/new.html.slim
- config/locales/forms/en.yml
- config/locales/instructions/en.yml
- spec/features/visitors/password_recovery_spec.rb
**Why**: Updated copy and call to action
**Before:**
**After:**
> Update forgot password form

- app/assets/stylesheets/components/_form.scss
- app/views/devise/two_factor_authentication/show.html.slim
- app/views/devise/two_factor_authentication_setup/index.html.slim
**Why**: Improves ux and readability
> Makes radio buttons vertical

- config/locales/idv/en.yml
- config/locales/profile/en.yml
**Why**: Latest and greatest from content team
> Copy updates for identity verification

- config/locales/activerecord/es.yml
- config/locales/contact/es.yml
- config/locales/devise/es.yml
- config/locales/errors/en.yml
- config/locales/errors/es.yml
- config/locales/event_types/es.yml
- config/locales/experiments/es.yml
- config/locales/forms/es.yml
- config/locales/headings/es.yml
- config/locales/idv/es.yml
- config/locales/instructions/es.yml
- config/locales/jobs/es.yml
- config/locales/links/es.yml
- config/locales/mailer/es.yml
- config/locales/notices/es.yml
- config/locales/pages/es.yml
- config/locales/profile/es.yml
- config/locales/saml_idp/es.yml
- config/locales/shared/es.yml
- config/locales/simple_form/es.yml
- config/locales/titles/es.yml
- config/locales/tooltips/es.yml
- config/locales/user_mailer/es.yml
- config/locales/users/es.yml
- config/locales/valid_email/es.yml
- config/locales/voice/es.yml
- config/locales/zxcvbn/es.yml
**Why**: Seems like i18n-tasks wanted all files in Spanish. Will make
it easer for Jamie, too.
> Prep app for Spanish translation

- app/forms/idv/finance_form.rb
- app/validators/form_finance_validator.rb
> Use different constant for CCN HTML validation

- lib/tasks/dev.rake
> Use Rails.logger.warn instead of puts

- lib/tasks/rotate.rake
- spec/lib/tasks/rotate_rake_spec.rb
**Why**: Rotation class was re-named
> Fix rotation:attribute_encryption_key naming

- app/views/layouts/application.html.slim
- app/views/shared/_nav_auth.html.slim
- config/i18n-tasks.yml
- spec/views/layouts/application.html.slim_spec.rb
- spec/views/shared/_nav_auth.html.slim_spec.rb
**Why**: Its the intended design!
> Removes white nav bar unless user fully auth'd

- spec/models/null_identity_spec.rb
> Add NullIdentity spec

- lib/tasks/dev.rake
- spec/lib/tasks/dev_rake_spec.rb
> Add dev:random_users rake task spec

- app/assets/javascripts/app/idv-finance-helper.js
- app/controllers/verify/finance_controller.rb
- app/controllers/verify/finance_other_controller.rb
- app/forms/idv/finance_form.rb
- app/services/analytics.rb
- app/views/verify/finance/new.html.slim
- app/views/verify/finance_other/new.html.slim
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/routes.rb
- spec/controllers/verify/finance_controller_spec.rb
- spec/features/accessibility/idv_pages_spec.rb
- spec/features/idv/flow_spec.rb
- spec/support/idv_helper.rb
- spec/views/verify/finance_other/new.html.slim_spec.rb
**Why**: We want to encourage CCN
---
this is the "ugly" version, so @hursey013 can follow up with a prettier version to match the comps
---
> Focus financial information on credit card, separate page for others

- app/assets/javascripts/app/radio-btn.js
- app/assets/javascripts/application.js
- app/assets/stylesheets/components/_btn.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/variables/_web.scss
- app/views/users/two_factor_authentication/show.html.slim
- app/views/users/two_factor_authentication_setup/index.html.slim
**Why**: Based on design audit, increased border radius of all buttons and created new button style for radio buttons.  Also a few small content tweaks to 2fa pages.
> Update button styles

- app/views/devise/passwords/new.html.slim
- app/views/mfa_confirmation/new.html.slim
- app/views/shared/_cancel.html.slim
- app/views/two_factor_authentication/otp_verification/show.html.slim
- app/views/two_factor_authentication/recovery_code_verification/show.html.slim
- app/views/two_factor_authentication/totp_verification/show.html.slim
- app/views/users/emails/edit.html.slim
- app/views/users/passwords/edit.html.slim
- app/views/users/phones/edit.html.slim
- app/views/users/totp_setup/new.html.slim
- app/views/users/totp_setup/start.html.slim
- app/views/users/two_factor_authentication/show.html.slim
- app/views/verify/finance/new.html.slim
- app/views/verify/finance_other/new.html.slim
- app/views/verify/index.html.slim
- app/views/verify/phone/new.html.slim
- app/views/verify/review/new.html.slim
- app/views/verify/sessions/new.html.slim
- config/locales/forms/en.yml
- config/locales/forms/es.yml
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- spec/features/idv/flow_spec.rb
- spec/features/users/recovery_code_spec.rb
**Why**: Make the location and style of cancel links consistent
> Update cancel link style

- docs/security/markdowns/system_documentation/system-data.md
> Fix Amos' email in markdown

- app/controllers/openid_connect/authorization_controller.rb
- app/forms/openid_connect_authorize_form.rb
- app/helpers/session_timeout_warning_helper.rb
- app/services/analytics.rb
- app/services/identity_linker.rb
- app/services/uri_service.rb
- app/views/openid_connect/authorization/error.html.slim
- app/views/openid_connect/authorization/index.html.slim
- config/application.yml.example
- config/initializers/secure_headers.rb
- config/locales/openid_connect/en.yml
- config/locales/openid_connect/es.yml
- config/routes.rb
- config/service_providers.yml
- db/migrate/20170111142846_add_nonce_to_identities.rb
- db/schema.rb
- spec/controllers/openid_connect/authorization_controller_spec.rb
- spec/features/openid_connect/openid_connect_spec.rb
- spec/forms/openid_connect_authorize_form_spec.rb
- spec/services/identity_linker_spec.rb
- spec/services/uri_service_spec.rb
**Why**: support OpenID Connect 1.0
--
This is super bare-bones <del>and missing a lot of test coverage</del>, would love some feedback <del>on how much test coverage we want to add now vs follow up with in order to finish outlining</del>
> Outline OpenID Connect 1.0 authorization endpoint

- config/service_providers.yml
**Why**: They were incorrect....again
> Fix URLs....again

- app/views/verify/sessions/new.html.slim
- config/initializers/simple_form.rb
- config/locales/idv/en.yml
- config/locales/idv/es.yml
**Why**: To provide additional guidance
> Update DOB form input

- app/controllers/openid_connect/token_controller.rb
- app/forms/openid_connect_token_form.rb
- app/services/analytics.rb
- app/services/id_token_builder.rb
- app/services/request_key_manager.rb
- config/initializers/omniauth.rb
- config/initializers/saml_idp.rb
- config/locales/openid_connect/en.yml
- config/locales/openid_connect/es.yml
- config/routes.rb
- config/service_providers.yml
- lib/service_provider.rb
- spec/controllers/openid_connect/token_controller_spec.rb
- spec/features/openid_connect/openid_connect_spec.rb
- spec/forms/openid_connect_token_form_spec.rb
- spec/services/id_token_builder_spec.rb
This is a <del>WIP</del> <ins>ready to go</ins>, it builds on #936, make sure to review that first. It adds the token endpoint.
<del>
Here's the incremental diff: https://github.com/18F/identity-idp/compare/margolis-openid-connect-authorize...margolis-openid-token-endpoint
</del>
> Outline OpenID Connect token endpoint

- app/assets/images/ico-print.svg
- app/assets/javascripts/app/print-recovery-code.js
- app/assets/javascripts/app/utils/mobile-user-agent.js
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/components/_border.scss
- app/assets/stylesheets/components/_icon.scss
- app/assets/stylesheets/components/all.scss
- app/assets/stylesheets/print.css.scss
- app/views/sign_up/recovery_codes/show.html.slim
- config/locales/users/en.yml
- config/locales/users/es.yml
- spec/javascripts/app/utils/mobile-user-agent_spec.js
- spec/views/sign_up/recovery_codes/show.html.slim_spec.rb
**Why**: WIP, allow users to print personal key.
> Add print btn to personal key

- app/controllers/openid_connect/user_info_controller.rb
- app/forms/openid_connect_token_form.rb
- app/presenters/openid_connect_user_info_presenter.rb
- app/services/analytics.rb
- app/services/id_token_verifier.rb
- config/locales/openid_connect/en.yml
- config/locales/openid_connect/es.yml
- config/routes.rb
- spec/controllers/openid_connect/user_info_controller_spec.rb
- spec/factories/identities.rb
- spec/features/openid_connect/openid_connect_spec.rb
- spec/presenters/openid_connect_user_info_presenter_spec.rb
- spec/services/id_token_verifier_spec.rb
This is <del>a second WIP</del> <ins>ready to go</ins>, it builds off my second PR
Here's the incremental diff: https://github.com/18F/identity-idp/compare/margolis-openid-token-endpoint...margolis-openid-userinfo
> Outline OpenID Connect userinfo endpoint

- .travis.yml
- Gemfile
- Gemfile.lock
- README.md
**Why**: It's time to get real.
> Add docs describing how to use proofing vendor gem

- app/assets/javascripts/misc/page-unload-warning.js
- app/views/verify/review/new.html.slim
- app/views/verify/sessions/new.html.slim
**Why**: Causes confusing behavior
--
Follow-up to https://github.com/18F/identity-idp/pull/990, cc @jessieay
> Remove page-unload-warning

- lib/tasks/dev.rake
**Why**: Missed this spot in #1003
> Set verified_at for loa3 test user in dev:prime

- lib/tasks/dev.rake
**Why**: Config names have changed.
> Fix documentation in dev rake task

- app/assets/javascripts/app/pw-toggle.js
- app/assets/javascripts/app/radio-btn.js
- app/assets/javascripts/misc/i18n-strings.js.erb
- app/assets/stylesheets/components/_btn.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/print.scss
- app/views/devise/sessions/new.html.slim
- app/views/shared/_personal_key.html.slim
- app/views/users/two_factor_authentication/show.html.slim
- app/views/users/two_factor_authentication_setup/index.html.slim
- config/locales/forms/en.yml
- config/locales/forms/es.yml
**Why**: To align with latest visual designs.  I made use of an existing css class `radio-btn` and repurposed it to not be so specific, so a number of the edits also pertain to that change.
**Before:**
**After:**
> Update Show Password toggle

- app/views/shared/_nav_branded.html.slim
- spec/views/shared/_nav_branded.html.slim_spec.rb
**Why**: To avoid a redirect to the 404 page
> Don't try to fetch agency logo if not present

- app/decorators/service_provider_session_decorator.rb
- app/decorators/session_decorator.rb
- app/helpers/application_helper.rb
- app/views/shared/_nav_branded.html.slim
- app/views/shared/_nav_branded_logo.html.slim
**Why**: Keep it clean. Adhere to our established principles.
> Move logic from view to session decorator

- Dockerfile
**Why**: To match the one the app uses.
> Update Ruby version in Docker to 2.3.3

- Dockerfile
- Gemfile.lock
- bin/setup
- docker-compose.yml
**Why**: To allow running the app inside Docker.
> Fix Docker config

- spec/decorators/service_provider_session_decorator_spec.rb
**Why**: If a method has logic, we should test it!
> Add specs for ServiceProviderSessionDecorator

- Capfile
- config/deploy.rb
- config/deploy/demo.rb
- config/deploy/dev.rb
- config/deploy/int.rb
- config/deploy/qa.rb
Based on this blog post, I believe this is what we need to proxy SSH via a bastion for deploys, hat tip: @amoose 
http://www.randomerrata.com/articles/2015/deploying-via-a-bastion-host-with-capistrano-3/
(having trouble verifying this at the moment because I can't SSH as myself to the bastions)
> Capistrano: SSH via Bastion

- app/controllers/openid_connect/authorization_controller.rb
- app/forms/openid_connect_authorize_form.rb
- app/services/id_token_builder.rb
- app/views/openid_connect/authorization/index.html.slim
- spec/controllers/openid_connect/authorization_controller_spec.rb
- spec/features/openid_connect/openid_connect_spec.rb
- spec/forms/openid_connect_authorize_form_spec.rb
- spec/services/id_token_builder_spec.rb
Updating to conform to specs better
> OpenID Connect Cleanup

- spec/decorators/service_provider_session_decorator_spec.rb
- spec/decorators/session_decorator_spec.rb
> Backfill test for session decorators

- .reek
- app/controllers/openid_connect/authorization_controller.rb
- app/forms/openid_connect_authorize_form.rb
- app/services/secure_headers_whitelister.rb
- config/application.yml.example
- config/service_providers.yml
- spec/features/openid_connect/openid_connect_spec.rb
- spec/forms/openid_connect_authorize_form_spec.rb
- spec/services/secure_headers_whitelister_spec.rb
**Why**: CSP was blocking redirects to other domains
---
I made a Sinatra OpenID Connect SP (creating a repo soon) and verified this locally in Chrome
> Fix CSP to work with OpenID Connect

- app/controllers/verify/sessions_controller.rb
- app/views/verify/finance/new.html.slim
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- spec/features/idv/flow_spec.rb
**Why**: To make information and form intent clearer to the end user
New screen:
> Restyles idv finance form, adds flash message

- app/controllers/verify/confirmations_controller.rb
- config/routes.rb
- spec/controllers/verify/confirmations_controller_spec.rb
**Why**: Unused is as unused does
> Remove unused route and related specs

- app/controllers/concerns/two_factor_authenticatable.rb
- app/controllers/openid_connect/authorization_controller.rb
- app/services/identity_linker.rb
- spec/controllers/openid_connect/authorization_controller_spec.rb
- spec/features/openid_connect/openid_connect_spec.rb
- spec/services/identity_linker_spec.rb
> OpenID Connect: auto-redirect after already authorized

- app/assets/javascripts/app/components/accordion.js
- app/assets/javascripts/misc/i18n-strings.js.erb
- app/assets/javascripts/misc/previous-address.js
- app/helpers/accordion_helper.rb
- app/views/shared/_accordion.html.slim
- app/views/verify/sessions/new.html.slim
- config/i18n-tasks.yml
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/links/en.yml
- config/locales/links/es.yml
- spec/features/idv/flow_spec.rb
**Why**: Only show the previous address block to those that need it.
> Add accordion to previous address input

- app/assets/javascripts/app/components/modal.js
- app/assets/javascripts/misc/recovery-page-controller.js
- app/assets/javascripts/misc/verify-modal.js
- app/assets/stylesheets/components/_modal.scss
- app/views/session_timeout/_warning.html.slim
- app/views/shared/_modal_layout.slim
- app/views/shared/_modal_verification.slim
- app/views/shared/_personal_key.html.slim
- app/views/sign_up/recovery_codes/_confirmation_modal.html.slim
- spec/support/shared_examples_for_recovery_codes.rb
**Why**: To make sure all modals are displayed consistently.
> Use shared partial for all modals

- app/controllers/openid_connect/authorization_controller.rb
- app/decorators/openid_connect_authorize_decorator.rb
- app/forms/openid_connect_authorize_form.rb
- app/helpers/application_helper.rb
- app/services/openid_connect_attribute_scoper.rb
- app/views/openid_connect/authorization/index.html.slim
- config/locales/openid_connect/en.yml
- config/locales/openid_connect/es.yml
- config/service_providers.yml
- spec/decorators/openid_connect_authorize_decorator_spec.rb
- spec/services/openid_connect_attribute_scoper_spec.rb
- spec/views/openid_connect/authorization/index.html.slim_spec.rb
**Why**: Improve UX
**How**: Add app name, logo and list of requested attributes
----
> Update OpenID Connect authorization page

- config/locales/saml_idp/es.yml
Continued Spanish translation work.
> translate saml_idp into spanish

- config/locales/shared/es.yml
Continued Spanish translation work.
> translate shared into spanish

- config/initializers/_service_providers.rb
- db/seeds.rb
- spec/controllers/service_provider_controller_spec.rb
- spec/features/saml/saml_spec.rb
- spec/services/service_provider_updater_spec.rb
> Add missing specs for ServiceProviderUpdater

- app/services/idv/phone_step.rb
- spec/controllers/verify/phone_controller_spec.rb
- spec/services/idv/phone_step_spec.rb
**Why**: For complete test coverage
> Add missing PhoneStep specs

- app/views/pages/privacy_policy.html.slim
- spec/views/pages/privacy_policy.html.slim_spec.rb
**Why**: For a consistent experience
> Make sure external links open in new windows

- app/controllers/users/two_factor_authentication_controller.rb
- app/forms/otp_delivery_selection_form.rb
- spec/controllers/users/two_factor_authentication_controller_spec.rb
- spec/forms/otp_delivery_selection_form_spec.rb
**Why**: For consistency with our other Form Objects.
> Let OtpDeliverySelectionForm return FormResponse

- app/controllers/two_factor_authentication/otp_verification_controller.rb
- app/forms/otp_verification_form.rb
- spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
> Return FormResponse in OtpVerificationForm

- app/views/user_mailer/email_changed.html.slim
- app/views/user_mailer/password_changed.html.slim
- app/views/user_mailer/phone_changed.html.slim
- app/views/user_mailer/signup_with_your_email.html.slim
- config/application.rb
- config/locales/user_mailer/en.yml
- spec/mailers/user_mailer_spec.rb
> Update mailers to use new contact us content

- .reek
- app/controllers/sign_up/registrations_controller.rb
- app/forms/register_user_email_form.rb
- spec/controllers/sign_up/registrations_controller_spec.rb
- spec/forms/register_user_email_form_spec.rb
> Return FormResponse in RegisterUserEmailForm

- app/views/verify/sessions/new.html.slim
**Why**: To better support screen readers
> Add fieldsets to basic info form

- app/controllers/verify/confirmations_controller.rb
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- spec/controllers/verify/confirmations_controller_spec.rb
**Why**: Better message clarity
> Updates loa3 copy on password and review pages

- app/controllers/two_factor_authentication/recovery_code_verification_controller.rb
- app/forms/recovery_code_form.rb
- spec/controllers/two_factor_authentication/recovery_code_verification_controller_spec.rb
- spec/forms/recovery_code_form_spec.rb
> Return FormResponse in RecoveryCodeForm

- app/controllers/users/totp_setup_controller.rb
- app/forms/totp_setup_form.rb
- spec/controllers/users/totp_setup_controller_spec.rb
- spec/forms/totp_setup_form_spec.rb
> Return FormResponse in TotpSetupForm

- app/controllers/two_factor_authentication/totp_verification_controller.rb
- app/forms/totp_verification_form.rb
- spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb
- spec/forms/totp_verification_form_spec.rb
> Return FormResponse in TotpVerificationForm

- app/controllers/users/two_factor_authentication_setup_controller.rb
- app/forms/two_factor_setup_form.rb
- spec/controllers/users/two_factor_authentication_setup_controller_spec.rb
- spec/forms/two_factor_setup_form_spec.rb
**Why**: For consistency with our other Form Objects
> Return FormResponse in TwoFactorSetupForm

- app/controllers/users/emails_controller.rb
- app/forms/update_user_email_form.rb
- spec/controllers/users/emails_controller_spec.rb
- spec/forms/update_user_email_form_spec.rb
**Why**: For consistency with our other Form Objects
> Return FormResponse in UpdateUserEmailForm

- app/views/verify/fail.html.slim
- config/locales/idv/en.yml
- config/locales/idv/es.yml
**Why**: Revised content
**Before:**
**After:**
> Update verification failure view

- app/controllers/users/passwords_controller.rb
- app/forms/update_user_password_form.rb
- app/services/active_profile_encryptor.rb
- app/services/update_user_password.rb
- spec/controllers/users/passwords_controller_spec.rb
- spec/forms/update_user_password_form_spec.rb
- spec/services/active_profile_encryptor_spec.rb
- spec/services/update_user_password_spec.rb
**Why**: To adhere to controller best practices
**How**:
- Move all business logic to external classes
- Create a new UpdateUserPassword class to handle the POST request
and make the necessary calls to additional classes when the password
is valid.
- Make the `UpdateUserPassword` class return a FormResponse for
consistency
> Refactor PasswordsController

- spec/features/saml/loa1_sso_spec.rb
- spec/support/features/session_helper.rb
**Why**: Sign up flow uses JS!
> Add JS spec for sign up recovery code flow

- app/assets/stylesheets/components/_personal-key.scss
- app/assets/stylesheets/components/all.scss
- app/views/partials/personal_key/_entry_fields.html.slim
- app/views/partials/personal_key/_key.slim
- app/views/sign_up/recovery_codes/_confirmation_modal.html.slim
- app/views/two_factor_authentication/recovery_code_verification/show.html.slim
- spec/features/visitors/password_recovery_spec.rb
- spec/support/features/session_helper.rb
**Why**: We are moving to a single string of characters instead of an array of multiple words.
**Desktop:**
**Mobile:**
> Update personal key UI

- config/locales/profile/en.yml
**Why**: To replace placeholder text
> Update profile reactivation copy

- app/views/layouts/application.html.slim
- app/views/profile/index.html.slim
- spec/features/saml/loa1_sso_spec.rb
- spec/views/layouts/application.html.slim_spec.rb
- spec/views/profile/index.html.slim_spec.rb
**WHY**: We want people to finish sign up!
> Do not show logout / my account header during signup flow

- app/views/user_mailer/email_changed.html.slim
- app/views/user_mailer/password_changed.html.slim
- app/views/user_mailer/phone_changed.html.slim
- app/views/user_mailer/signup_with_your_email.html.slim
- config/application.rb
- config/locales/user_mailer/en.yml
- config/locales/user_mailer/es.yml
- spec/mailers/user_mailer_spec.rb
**Why**: Phone number not yet in operation
> Send users to Help Center or contact us pages

- config/locales/users/en.yml
**WHY**: This is how we refer to it nwow
> Recovery words -> personal key in flash

- docs/nginx.conf.erb
- docs/nginx_server.conf.erb
addressing issue https://github.com/18F/identity-private/issues/1714
> nginx config from identity-devops repo

- spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/recovery_code_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb
> Stub max login attempts instead of performing request 3x

- config/service_providers.yml
- spec/features/openid_connect/openid_connect_spec.rb
> Add LOA3 sign up spec for OpenIdConnect

- app/controllers/profile_controller.rb
- app/view_models/user_profile/profile_index.rb
- app/views/profile/index.html.slim
- spec/controllers/profile_controller_spec.rb
- spec/views/profile/index.html.slim_spec.rb
**Why**: There is a significant redesign of the profile screen
forthcoming, and having a view_model will make it easier to move logic
out of the profile index view
> Adds view_model class for profile

- app/controllers/concerns/idv_step_concern.rb
> Remove unused `helper_method` ref in `IdvStepConcern`

- app/controllers/verify/finance_controller.rb
- app/controllers/verify/finance_other_controller.rb
- app/view_models/verify/financials_new.rb
- app/views/verify/finance/new.html.slim
- app/views/verify/finance_other/new.html.slim
**WHY**: Keeps logic in one place.
> Use methods on views models instead of `helper_method`

- spec/features/users/sign_up_spec.rb
**Why**: Tests fail otherwise!
> Add `email: true` so test isn't using stale email

- app/controllers/application_controller.rb
- app/controllers/concerns/two_factor_authenticatable.rb
- app/presenters/two_factor_auth_code/authenticator_delivery_presenter.rb
- app/presenters/two_factor_auth_code/generic_delivery_presenter.rb
- app/presenters/two_factor_auth_code/phone_delivery_presenter.rb
- app/views/two_factor_authentication/otp_verification/show.html.slim
- app/views/two_factor_authentication/totp_verification/_reauthn.html.slim
- app/views/two_factor_authentication/totp_verification/show.html.slim
- spec/views/two_factor_authentication/otp_verification/show.html.slim_spec.rb
- spec/views/two_factor_authentication/totp_verification/show.html.slim_spec.rb
**WHY**: Do not need it in views, just controllers, post-refactor
> Make `reauthn?` private

- Gemfile.lock
- package.json
**WHY**: gem updates!
* Version updated in gem at
https://github.com/bitzesty/zxcvbn-js/commit/2eea912587bfba168b2be3fa59ffab0c4c2fef2e#diff-cdefaed50bfc300d17bd871e896a75d5
> Update zxcvbn-js gem

- app/views/profile/_pii.html.slim
- app/views/shared/_address.html.slim
- app/views/verify/review/new.html.slim
- spec/views/shared/_address.html.slim_spec.rb
> Refactor address formatting into a partial

- lib/tasks/rotate.rake
- spec/lib/tasks/rotate_rake_spec.rb
**WHY**: Should be incremented
BONUS: we are no longer showing the progress bar when the specs run!
> Increment progress bar during rotate task

- app/controllers/application_controller.rb
- app/controllers/concerns/saml_idp_auth_concern.rb
- app/controllers/concerns/two_factor_authenticatable.rb
- app/controllers/openid_connect/authorization_controller.rb
- app/controllers/profile_controller.rb
- app/controllers/sign_up/personal_keys_controller.rb
- app/controllers/two_factor_authentication/personal_key_verification_controller.rb
- app/controllers/users/personal_keys_controller.rb
- app/controllers/users/sessions_controller.rb
- app/controllers/users/totp_setup_controller.rb
- app/controllers/users/verify_profile_controller.rb
- app/decorators/user_decorator.rb
- app/view_models/profile_index.rb
- app/views/profile/index.html.slim
- app/views/two_factor_authentication/shared/max_login_attempts_reached.html.erb
- spec/controllers/profile_controller_spec.rb
- spec/controllers/users/totp_setup_controller_spec.rb
- spec/decorators/user_decorator_spec.rb
- spec/views/profile/index.html.slim_spec.rb
- spec/views/two_factor_authentication/shared/max_login_attempts_reached.html.erb_spec.rb
**WHY**: We were using it inconsistently, anyway.
> Remove `decorated_user` global helper method

- .eslintignore
- .eslintrc
- app/assets/javascripts/app/components/index.js
- app/assets/javascripts/app/components/modal.js
- app/assets/javascripts/app/modules/date-formatter.js
- app/assets/javascripts/app/modules/numeric-formatter.js
- app/assets/javascripts/app/modules/zip-code-formatter.js
- app/assets/javascripts/app/pw-toggle.js
- app/assets/javascripts/app/utils/index.js
- app/assets/javascripts/misc/i18n-mode.js
- app/assets/javascripts/misc/previous-address.js
- app/assets/javascripts/misc/pw-strength.js
**WHY**: Code climate shows these as issues
> Update js files to comply with es lint rules

- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/components/_background-images.scss
- app/assets/stylesheets/components/_nav.scss
- app/assets/stylesheets/components/_personal-key.scss
- app/assets/stylesheets/components/all.scss
- app/assets/stylesheets/pages/all.scss
Handful of unused CSS classes and removing `pages` placeholder since our static content has been moved to `identity-site`.
> Remove unused CSS

- app/controllers/application_controller.rb
- app/models/user.rb
- app/services/idv/agent.rb
- spec/support/controller_helper.rb
- spec/support/features/mailer_helper.rb
- spec/support/saml_auth_helper.rb
**WHY**: Playing around with https://github.com/joshuaclayton/unused
> Remove unused code

- config/locales/users/en.yml
**Why**: It is no longer multiple fields.
> Update personal key error

- spec/views/layouts/application.html.slim_spec.rb
**Why**: It was describing the opposite of the expectation
> Fix DAP analytics spec title

- app/assets/stylesheets/components/_btn.scss
- app/assets/stylesheets/variables/_colors.scss
**Why**: Keep code and design in sync
> Updates colors to match updated styleguide

- app/assets/javascripts/app/form-validation.js
- app/assets/javascripts/misc/i18n-strings.js.erb
- config/locales/idv/en.yml
- config/locales/idv/es.yml
This add a custom HTML5 message when the pattern is not matched on the personal key input.
> Add HTML5 validation message for personal key

- config/locales/errors/en.yml
- config/locales/notices/en.yml
**Why** Consistency and clarity are important, and ongoing testing has surfaced some minor issues.
> Updates flash and session timeout messages

- app/controllers/concerns/two_factor_authenticatable.rb
- app/services/uri_service.rb
- spec/controllers/openid_connect/authorization_controller_spec.rb
- spec/forms/openid_connect_authorize_form_spec.rb
- spec/jobs/voice_otp_sender_job_spec.rb
- spec/services/uri_service_spec.rb
**Why**:
Ahead of some additional URI parsing, seemed like a useful refactor
> Clean up URI parameter parsing

- spec/view_models/profile_index_spec.rb
**Why**: More test coverage == more confidence in the app
> Adds specs for ProfileIndex view model

- app/views/devise/sessions/new.html.slim
- config/locales/instructions/en.yml
Shortened password instructions
> update password instructions

- app/forms/reactivate_account_form.rb
- app/forms/verify_account_form.rb
**Why**: Comments usually get out of date
--
This was some feedback on another PR, so I figured we could copy it back to these other forms: https://github.com/18F/identity-idp/pull/1386#discussion_r112304640
> Clarify method name so we don't need a comment

- app/services/usps_exporter.rb
- config/application.yml.example
- spec/services/usps_exporter_spec.rb
**Why**:
Vendor asked for a new field and a header row.
The field indidates the type of row, "01" = header, "02" = content
The header row contains the number of content rows.
---
(I removed the encryption bits from #1269 and tacked on a new format requirement)
> Update PSV generation to match spec

- README.md
- lib/rspec/formatters/user_flow_formatter.rb
- spec/features/flows/sp_authentication_flows_spec.rb
- spec/features/flows/visitor_flows_spec.rb
We want to utilize our user flow specs to document our UX
Updates the current flow specs to conform to the current UX
_Next steps: publishing to federalist!_
> Updates user flows specs to match current UX

- config/deploy/int.rb
**Why**: Discourage capistrano deploys to int environment
> Remove capistrano config for int

- config/locales/mailer/en.yml
- config/locales/user_mailer/en.yml
- spec/views/devise/mailer/confirmation_instructions.html.slim_spec.rb
**Why** Shortens sentences for clarity, especially on mobile
> Edits email copy

- config/locales/sign_up/en.yml
When cancelling account creation, make it a little more clear what happens with the data.
> Update cancellation flash message

- app/decorators/service_provider_session_decorator.rb
- app/forms/openid_connect_authorize_form.rb
- app/models/null_service_provider.rb
- app/models/service_provider.rb
- app/services/openid_connect_redirector.rb
- config/service_providers.yml
- db/migrate/20170531204549_add_multiple_redirect_uris_to_service_providers.rb
- db/schema.rb
- spec/models/null_service_provider_spec.rb
- spec/models/service_provider_spec.rb
- spec/services/openid_connect_redirector_spec.rb
- spec/services/service_provider_updater_spec.rb
**Why**: Makes it easier to manage OIDC Service Providers
> Support multiple redirect_uri values in OIDC

- app/services/marketing_site.rb
- spec/services/marketing_site_spec.rb
> Update link to Help Center question

- config/locales/user_mailer/en.yml
Updated intro for password reset
> Updated intro for password reset

- config/application.yml.example
- config/locales/account/fr.yml
- config/locales/activerecord/fr.yml
- config/locales/devise/fr.yml
- config/locales/errors/fr.yml
- config/locales/event_types/fr.yml
- config/locales/forms/fr.yml
- config/locales/headings/fr.yml
- config/locales/help_text/fr.yml
- config/locales/idv/fr.yml
- config/locales/instructions/fr.yml
- config/locales/jobs/fr.yml
- config/locales/links/fr.yml
- config/locales/mailer/fr.yml
- config/locales/notices/fr.yml
- config/locales/openid_connect/fr.yml
- config/locales/pages/fr.yml
- config/locales/saml_idp/fr.yml
- config/locales/shared/fr.yml
- config/locales/sign_up/fr.yml
- config/locales/simple_form/fr.yml
- config/locales/time/fr.yml
- config/locales/titles/fr.yml
- config/locales/tooltips/fr.yml
- config/locales/user_mailer/fr.yml
- config/locales/users/fr.yml
- config/locales/valid_email/fr.yml
- config/locales/zxcvbn/fr.yml
**Why**: Results back from vendor
> Check in French translations

- config/locales/instructions/en.yml
Updated `go_back_to_mobile_app` i18n entry
> Update go_back_to_mobile_app i18n entry

- config/locales/account/es.yml
- config/locales/activerecord/es.yml
- config/locales/devise/es.yml
- config/locales/errors/es.yml
- config/locales/event_types/es.yml
- config/locales/forms/es.yml
- config/locales/headings/es.yml
- config/locales/help_text/es.yml
- config/locales/idv/es.yml
- config/locales/instructions/es.yml
- config/locales/jobs/es.yml
- config/locales/links/es.yml
- config/locales/mailer/es.yml
- config/locales/notices/es.yml
- config/locales/openid_connect/es.yml
- config/locales/pages/es.yml
- config/locales/saml_idp/es.yml
- config/locales/shared/es.yml
- config/locales/sign_up/es.yml
- config/locales/titles/es.yml
- config/locales/tooltips/es.yml
- config/locales/user_mailer/es.yml
- config/locales/users/es.yml
- config/locales/valid_email/es.yml
- config/locales/zxcvbn/es.yml
- lib/yaml_normalizer.rb
- scripts/i18n-csv-to-yml
- spec/lib/yaml_normalizer_spec.rb
Adds in Spanish translations from our vendor, and the script I used to write the single spreadsheet to all the different YAML files
> Adds in Spanish translations

- config/locales/account/es.yml
- config/locales/devise/es.yml
- config/locales/errors/es.yml
- config/locales/forms/es.yml
- config/locales/idv/es.yml
- config/locales/instructions/es.yml
- config/locales/links/es.yml
- config/locales/mailer/es.yml
- config/locales/notices/es.yml
- config/locales/openid_connect/es.yml
- config/locales/titles/es.yml
- config/locales/user_mailer/es.yml
- config/locales/users/es.yml
- config/locales/zxcvbn/es.yml
- lib/yaml_normalizer.rb
- spec/lib/yaml_normalizer_spec.rb
**Why**: Artifact of our translation process, not needed
> Normalize .yml: remove leading newlines

- config/locales/jobs/fr.yml
**Why**: Completeness
---
translation courtesy of @monfresh
> Translate SMS OTP job into fr

- scripts/load_testing/create_account.py
**Why**: Adding a new field broke the script
> Fix load testing script for new phone form

- config/service_providers.yml
> Add CBP OARS prod config

- config/service_providers.yml
**Why**: Missing colon in URI scheme from #1580
> Update CBP OARS SP config

- .reek
- spec/lib/yaml_normalizer_spec.rb
- spec/models/otp_requests_tracker_spec.rb
**Why**: Consistent code is happy code.
> Fix linter offenses

- app/assets/javascripts/app/i18n-dropdown.js
- app/assets/stylesheets/components/_i18n-dropdown.scss
- app/views/shared/_footer_lite.html.slim
Converting the language selector into and actual link makes it possible to toggle the menu using only a keyboard.
> Improve accessibility of language selector

- Gemfile.lock
- app/jobs/sms_otp_sender_job.rb
- spec/jobs/sms_otp_sender_job_spec.rb
**Why**: To get the latest and greatest.
> Update twilio-ruby from 4.13.0 to 5.1.0

- config/locales/account/fr.yml
- config/locales/devise/fr.yml
- config/locales/forms/fr.yml
- config/locales/headings/fr.yml
- config/locales/instructions/fr.yml
- config/locales/jobs/fr.yml
- config/locales/links/fr.yml
- config/locales/notices/fr.yml
Updating with latest batch of changes provided by translation service.
> Update French translations

- app/controllers/health/database_controller.rb
- app/services/database_health_checker.rb
- config/database.yml
- config/routes.rb
- spec/controllers/health/database_controller_spec.rb
- spec/services/database_health_checker_spec.rb
**Why**: So we can check the database health
> Add /api/health/database endpoint

- app/services/database_health_checker.rb
- spec/services/database_health_checker_spec.rb
**Why**: To increase visibility
---
Realized this might be useful
> Also notify NewRelic when DB health check fails

- config/locales/devise/es.yml
- config/locales/help_text/es.yml
- config/locales/idv/es.yml
- config/locales/instructions/es.yml
- config/locales/notices/es.yml
- config/locales/openid_connect/es.yml
- config/locales/user_mailer/es.yml
- spec/i18n_spec.rb
**Why**: So that we can make sure that all of our translations are being
interpolated correctly.
> Check for missing interpolation args in i18n spec

- app/helpers/session_timeout_warning_helper.rb
- app/views/session_timeout/_expire_session.js.erb
- spec/helpers/session_timeout_warning_helper_spec.rb
- spec/views/layouts/application.html.slim_spec.rb
**Why**:
Bad host values mess up rendering of the page
> Work around bad host values by using relative URL

- config/application.yml.example
> Remove old unused config

- app/services/session_encryptor.rb
- app/services/usps_confirmation_entry.rb
- config/initializers/session_store.rb
- spec/services/session_encryptor_spec.rb
> Add deterministic decryption for session

- app/services/analytics.rb
- config/application.rb
- spec/services/analytics_spec.rb
**Why**: Additional debugging information
> Log PID in requests and events

- app/views/verify/come_back_later/show.html.slim
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- spec/support/idv_examples/usps_verification_selection.rb
- spec/views/verify/come_back_later/show.html.slim_spec.rb
**Why**:
Updating with name of sp in text
and more standard looking button
> Update text and look of come back later screen

- .gitignore
- config/application.yml.example
- config/newrelic.yml
This is one commit on top of the previous S3 secrets branch: https://github.com/18F/identity-idp/pull/1557
View just the incremental diff: https://github.com/18F/identity-idp/compare/margolis-s3-config-bootstrap...margolis-newrelic-config
> Put newrelic config in source control

- Gemfile
- Gemfile.lock
Small changes to use tagged versions of our internal gems.
> Modified Gemfile to use tagged releases of internal gems

- .reek
- app/decorators/service_provider_session_decorator.rb
- app/decorators/session_decorator.rb
- app/views/sign_up/completions/show.html.slim
- config/locales/help_text/en.yml
- config/locales/help_text/es.yml
- config/locales/help_text/fr.yml
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- spec/decorators/service_provider_session_decorator_spec.rb
**Why**:
New language for screen and new
layout
> Update verify success screen

- spec/features/accessibility/visitor_pages_spec.rb
**Why**: Because it is external to the IDP code base. Changes to the
production login.gov static site should not cause issues in our tests or
our CI.
> Remove marketing site contact page from tests

- lib/action_mailer/log_subscriber.rb
**Why**: To protect user privacy
> Filter out emails from ActionMailer job logs

- lib/feature_management.rb
__Why__
* We need this functionality in our test domain as well.
__How__
* Add the identitysandbox domains to the prefill list.
> Add identitysandbox domains to the prefill list

- app/services/basic_auth_url.rb
- spec/services/basic_auth_url_spec.rb
> Deploy RC 45.1 to Prod

- app/models/service_provider.rb
- spec/controllers/application_controller_spec.rb
**Why**: To avoid unnecessary DB calls.
session.
> Return early if no current SP

- Gemfile
- Gemfile.lock
**Why**: So that the version of the applicant in the equifax gem and
proofer gem are compatible.
session.
> Bump equifax gem to v1.1.0

- config/application.rb
**Why**: For enhanced security
Reference:
http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#per-form-csrf-tokens
session.
> Enable per-form CSRF tokens

- app/views/exception_notifier/_session.text.erb
**Why**: It's almost 3 times as fast as the Browser gem.
session.
> Use DeviceDetector for parsing user agents

- app/services/analytics.rb
- spec/services/analytics_spec.rb
**Why**: To make it easier to compare events across browser
versions, platforms, and devices
session.
> Parse user agent in analytics events log

- .reek
- app/decorators/service_provider_session_decorator.rb
- app/decorators/session_decorator.rb
- app/views/devise/passwords/new.html.slim
- app/views/devise/sessions/new.html.slim
- app/views/shared/_sp_alert.html.slim
- app/views/sign_up/registrations/show.html.slim
- config/locales/service_providers/en.yml
- config/locales/service_providers/es.yml
- config/locales/service_providers/fr.yml
- spec/views/devise/passwords/new.html.slim_spec.rb
- spec/views/devise/sessions/new.html.slim_spec.rb
- spec/views/sign_up/registrations/show.html.slim_spec.rb
**Why**:
Add some information for when USA jobs users
access the site.
session.
> Add SP message for USA Jobs users

- app/views/verify/_hardfail4.html.slim
- app/views/verify/_no_sp_hardfail.html.slim
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
**Why**:
To emphasize help center in the messaging
session.
> Bold 'help center' on non sp identity fail

- config/locales/service_providers/en.yml
- config/locales/service_providers/es.yml
- config/locales/service_providers/fr.yml
> Fix typo in USAJOBS name

- config/locales/service_providers/en.yml
- config/locales/service_providers/es.yml
- config/locales/service_providers/fr.yml
- spec/lib/feature_management_spec.rb
> Deploy RC 46 Patch 1 to staging

- config/locales/service_providers/en.yml
- config/locales/service_providers/es.yml
- config/locales/service_providers/fr.yml
Per discussion with @RyanSibley
> Update USAJOBS message

- config/database.yml
- config/locales/service_providers/en.yml
- config/locales/service_providers/es.yml
- config/locales/service_providers/fr.yml
> Deploy RC 46 Patch 2 to staging

- config/locales/service_providers/es.yml
- config/locales/service_providers/fr.yml
**Why**: So that USAJOBS customers don't see "Not translated yet".
session.
> Translate "learn more" in French and Spanish

- config/locales/service_providers/es.yml
- config/locales/service_providers/fr.yml
**Why**: So that USAJOBS customers don't see "Not translated yet".
session.
> Deploy RC 46 Patch 3 to staging

- app/controllers/users_controller.rb
- app/services/analytics.rb
- app/services/parse_controller_from_referer.rb
- spec/controllers/users_controller_spec.rb
- spec/services/parse_controller_from_referer_spec.rb
**Why**: To see how often people cancel account creation, and at
which point in the process they do so.
session.
> Track account deletion in analytics

- config/locales/service_providers/es.yml
- config/locales/service_providers/fr.yml
**Why**: So that users don't see 'NOT TRANSLATED YET'.
session.
> Translate TTP custom text

- config/locales/service_providers/es.yml
- config/locales/service_providers/fr.yml
**Why**: So that users don't see 'NOT TRANSLATED YET'.
session.
> Deploy RC 46 Patch 4 to staging

- app/controllers/verify/sessions_controller.rb
- app/forms/idv/profile_form.rb
- app/helpers/form_helper.rb
- app/jobs/idv/profile_job.rb
- app/jobs/idv/proofer_job.rb
- app/services/idv/agent.rb
- app/validators/idv/form_profile_validator.rb
- app/validators/idv/form_state_id_validator.rb
- app/views/verify/sessions/new.html.slim
- config/application.yml.example
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- package-lock.json
- spec/controllers/verify/sessions_controller_spec.rb
- spec/features/idv/account_creation_spec.rb
- spec/forms/idv/profile_form_spec.rb
- spec/jobs/idv/profile_job_spec.rb
- spec/support/features/idv_helper.rb
- spec/support/idv_examples/state_id_data.rb
**Why**: So that users can collect state id data from users and use it
to confirm their identity
session.
> Add state id proofing to profile step

- app/views/verify/sessions/new.html.slim
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
> Translate state id labels

- Gemfile
- Gemfile.lock
**Why**: To take advantage of the latest features.
session.
> Update two_factor_authentication to version 2.0.1

- config/service_providers.yml
> Add CBP I'm Ready prod config

- config/locales/jobs/en.yml
- config/locales/jobs/es.yml
- config/locales/jobs/fr.yml
- config/locales/voice/en.yml
- config/locales/voice/es.yml
- config/locales/voice/fr.yml
**Why**: Some people try to use their OTP long after it has expired.
session.
> Clarify that OTP expires in 5 minutes.

- config/service_providers.yml
**Why**: In preparation for launch to production
> Add USAJOBS to prod

- Gemfile
- Gemfile.lock
- app/services/idv/upcase_vendor_env_vars.rb
- config/application.yml.example
- spec/services/idv/upcase_vendor_env_vars_spec.rb
**Why**: Now that devops has added the AAMVA IP block to the white list
and setup SSH keys that should allow this gem to be installed, it should
be safe to re-add the AAMVA gem.
This reverts commit 499762628ef2af3f3f14fa96b6b6c061f7a1ba18, reversing
changes made to 51d1d191bb081ef256377d9d3ab0a4b63fea4b97. …
> Re-add AAMVA

- Gemfile
- Gemfile.lock
- config/application.yml.example
**Why**: To take advantage of namespace matching and dynamic message
destination IDs
session.
> Upgrade AAMVA gem to 1.0.1

- .github/PULL_REQUEST_TEMPLATE.md
> added secrets changes to PR checklist

- app/assets/images/get-started/ID.svg
- app/models/user.rb
- app/views/sign_up/registrations/_required_pii_accordion.html.slim
- config/locales/devise/en.yml
- config/locales/devise/es.yml
- config/locales/devise/fr.yml
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- spec/requests/openid_connect_authorize_spec.rb
**Why**: Simpler review of just a small piece of state ID changes.
- [x ] For DB changes, check for missing indexes, check to see if the changes
- [ x] For route changes, make sure GET requests don't change state or result in
- [x ] For encryption changes, make sure it is compatible with data that was
- [ x] For secrets changes, [make sure to update the S3 secrets …
> State ID accordion

- Gemfile
- Gemfile.lock
**Why**: To get better error messages when we receive an error response
from the AAMVA API
session. …
> Update AAMVA API client to v1.0.2

- db/migrate/20180201161105_add_verified_attributes_to_identities.rb
- db/schema.rb
**Why**:
We need to track which attributes have been
approved and verified by the user on identities
session. …
> Add verified attributes to identity table

- app/services/session_encryptor.rb
- app/services/usps_confirmation_entry.rb
- spec/services/session_encryptor_spec.rb
**Why**: This appears to be causing CSRF issues in lower environments.
We should investigate before we roll this out.
> Deploy RC 50 Patch 1 to Prod

- app/assets/javascripts/app/supported-states.js
- app/assets/javascripts/application.js
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/variables/_app.scss
- config/locales/devise/en.yml
**Why**: To pull them out of larger state ID PR
- [x ] For DB changes, check for missing indexes, check to see if the changes
- [x ] For route changes, make sure GET requests don't change state or result in
- [x ] For encryption changes, make sure it is compatible with data that was
- [x ] For secrets changes, [make sure to update the S3 secrets …
> Static asset changes for state ID

- .reek
- app/controllers/application_controller.rb
- app/controllers/sign_up/email_resend_controller.rb
- app/controllers/sign_up/personal_keys_controller.rb
- app/controllers/sign_up/registrations_controller.rb
- app/controllers/users/sessions_controller.rb
- app/forms/password_form.rb
- app/forms/register_user_email_form.rb
- app/forms/resend_email_confirmation_form.rb
- app/helpers/session_timeout_warning_helper.rb
- app/models/concerns/user_encrypted_attribute_overrides.rb
- app/services/uri_service.rb
- app/validators/form_email_validator.rb
- config/application.rb
- lib/utf8_sanitizer.rb
- spec/controllers/application_controller_spec.rb
- spec/controllers/sign_up/email_resend_controller_spec.rb
- spec/controllers/sign_up/registrations_controller_spec.rb
- spec/controllers/users/emails_controller_spec.rb
- spec/controllers/users/reset_passwords_controller_spec.rb
- spec/controllers/users/sessions_controller_spec.rb
- spec/features/users/sign_in_spec.rb
- spec/features/visitors/sign_up_with_email_spec.rb
- spec/forms/password_form_spec.rb
- spec/helpers/session_timeout_warning_helper_spec.rb
- spec/requests/edit_user_spec.rb
- spec/requests/invalid_encoding_spec.rb
- spec/requests/rack_attack_spec.rb
- spec/services/uri_service_spec.rb
* Sanitize improperly encoded form inputs to reduce 500 errors
* Verify that users are authenticated before assigning them a personal key
> Deploy RC 50 Patch 2 to Staging

- .reek
- app/controllers/application_controller.rb
- app/controllers/sign_up/email_resend_controller.rb
- app/controllers/sign_up/personal_keys_controller.rb
- app/controllers/sign_up/registrations_controller.rb
- app/controllers/users/sessions_controller.rb
- app/forms/password_form.rb
- app/forms/register_user_email_form.rb
- app/forms/resend_email_confirmation_form.rb
- app/helpers/session_timeout_warning_helper.rb
- app/models/concerns/user_encrypted_attribute_overrides.rb
- app/services/uri_service.rb
- app/validators/form_email_validator.rb
- config/application.rb
- lib/utf8_sanitizer.rb
- spec/controllers/application_controller_spec.rb
- spec/controllers/sign_up/email_resend_controller_spec.rb
- spec/controllers/sign_up/registrations_controller_spec.rb
- spec/controllers/users/emails_controller_spec.rb
- spec/controllers/users/reset_passwords_controller_spec.rb
- spec/controllers/users/sessions_controller_spec.rb
- spec/features/users/sign_in_spec.rb
- spec/features/visitors/sign_up_with_email_spec.rb
- spec/forms/password_form_spec.rb
- spec/helpers/session_timeout_warning_helper_spec.rb
- spec/requests/edit_user_spec.rb
- spec/requests/invalid_encoding_spec.rb
- spec/requests/rack_attack_spec.rb
- spec/services/uri_service_spec.rb
* Sanitize improperly encoded form inputs to reduce 500 errors
* Verify that users are authenticated before assigning them a personal key
> Deploy RC 50 Patch 2 to Prod

- app/views/shared/_user_verify_password.html.slim
- app/views/verify/sessions/new.html.slim
- config/locales/forms/en.yml
- config/locales/forms/es.yml
- config/locales/forms/fr.yml
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- config/locales/links/en.yml
- config/locales/links/es.yml
- config/locales/links/fr.yml
- config/locales/notices/en.yml
- config/locales/notices/es.yml
- config/locales/notices/fr.yml
- spec/support/features/session_helper.rb
**Why**: To further whittle down overall state ID changes.
- [x ] For DB changes, check for missing indexes, check to see if the changes
- [x ] For route changes, make sure GET requests don't change state or result in
- [x ] For encryption changes, make sure it is compatible with data that was
- [ x] For secrets changes, [make sure to update the S3 secrets …
> State ID messaging changes

- config/service_providers.yml
**Why**: The app needs access to these attributes.
> Add user attributes to RRB Benefit Connect config

- .codeclimate.yml
- .rubocop.yml
**Why**: To use the latest and greatest.
session.
> Update Code Climate config to version 2

- Dockerfile
- bin/setup
- config/database.yml
- docker-compose.yml
**Why**: The DB rake tasks were not able to run
**How**:
- Update `database.yml` to use Docker-specific settings
- Upgrade Node.js
- Use the new `/generate-example-keys` command
- Precompile assets to allow the site to render. For some reason,
even setting the service_timeout to 60 seconds wasn't enough to
get the site to load the first time. Hopefully this won't be an
issue when we move to webpack.
Fixes #1750
Fixes #1644
read, …
> Fix Docker setup

- Gemfile
- Gemfile.lock
**Why**: To pull in the changes that prevent missing verification
attributes from raising an error
session. …
> Update AAMVA gem to version 1.0.3

- public/503.html
- public/css/static.css
**Why**:
Cleaning up the look of the error pages and
adding a 503 error page.
session. …
> Adjust styling of error pages

- app/services/user_access_key.rb
> Deploy RC 51 patch 3 to staging

- package.json
**Why**: We removed it in #2014, but it looks like it is called by chef
when setting up the idp. We'll need to remove it from the idp base
recipe before we remove the script from package.json
instead of the `session` helper so the data …
> Re-add npm build script

- config/locales/service_providers/en.yml
**Why** To help clarify need for new account for USAJOBS
session.
> LG-120 Updated alert messaging

- Gemfile.lock
**Why**: To pick up a fix where comments prevented the entirety of the
text in a REXML node from being read by the `#text` method.
session.
authenticated, …
> Upgrade ruby saml to 1.7.2

- config/application.yml.example
- spec/features/users/sign_in_spec.rb
- spec/jobs/sms_otp_sender_job_spec.rb
**Why**: In order to provide a bit more time for USAJobs users.
session.
> LG-132 Updated OTP and Session timeouts

- config/locales/account/es.yml
- config/locales/account/fr.yml
- config/locales/headings/es.yml
- config/locales/headings/fr.yml
- config/locales/users/es.yml
- config/locales/users/fr.yml
**Why**: Translations are not available for French and Spanish
**How** Update the locale files.
session. …
> LG-1 delete account: Spanish and French translations

- .circleci/config.yml
- Gemfile
- Gemfile.lock
**Why**: To address multiple security vulnerabilities:
https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-3-7-released/
- CVE-2017-17742: HTTP response splitting in WEBrick
- CVE-2018-8777: DoS by large request in WEBrick
- CVE-2018-6914: Unintentional file and directory creation with
directory traversal in tempfile and tmpdir
- CVE-2018-8778: Buffer under-read in String#unpack
- CVE-2018-8779: Unintentional socket creation by poisoned NUL byte in
UNIXServer and UNIXSocket
- CVE-2018-8780: Unintentional directory traversal by poisoned NUL byte
in Dir
- Multiple vulnerabilities in RubyGems
various …
> Upgrade Ruby from 2.3.5 to 2.3.7

- .reek
- .rubocop.yml
- Gemfile
- Gemfile.lock
- config/initializers/devise.rb
**WHY**:
- Prevent local linting errors until Code Climate upgrades Rubocop support (#2054)
- Reduce noise when linting locally
session.
authenticated, make …
> Pin Rubocop version and sync local and code climate lint configuration

- app/controllers/users/totp_setup_controller.rb
- app/models/user.rb
- app/services/analytics.rb
- app/views/users/shared/_otp_delivery_preference_selection.html.slim
- config/locales/links/en.yml
- config/locales/links/es.yml
- config/locales/links/fr.yml
- spec/controllers/users/totp_setup_controller_spec.rb
- spec/features/users/sign_up_spec.rb
- spec/support/features/session_helper.rb
- spec/support/shared_examples/account_creation.rb
**Why**: In some cases, phones are not available.
So we need to handle that.
session. …
> LG-141 Allow use of auth app without phone

- .reek
- Gemfile
- Gemfile.lock
- config/initializers/ahoy.rb
> Upgrade Ahoy from 1.6.1 to 2.0.2

- app/mailers/user_mailer.rb
- app/views/user_mailer/reset_password.html.slim
**Why**: To facilitate sending a one-time email to some users.
session.
> Add temporary mailer

- config/locales/event_types/en.yml
- config/locales/event_types/es.yml
- config/locales/event_types/fr.yml
**Why**: So that the proper text can appear in the Account History
session. …
> LG-232 Localize password changed event text

- app/services/marketing_site.rb
- app/views/users/totp_setup/new.html.slim
- spec/services/marketing_site_spec.rb
**Why**:
The word "authenticator" has been replaced with "authentication".
session. …
> LG-234 Update link to auth app help page

- app/views/shared/google_analytics/_page_tracking.html.erb
- config/initializers/secure_headers.rb
**Why**: It's more secure than the default transport mechanism for
Google Analytics. See this post for more details:
https://githubengineering.com/githubs-post-csp-journey/
instead of the `session` helper so the data does not persist …
> LG-238 Use XHR transport mechanism for GA

- spec/rails_helper.rb
- spec/spec_helper.rb
**Why**: To allow people to use zeus to speed up app development and
testing.
session. …
> Make tests compatible with zeus

- app/services/encryption/encryptors/session_encryptor.rb
- app/services/session_encryptor.rb
- app/services/usps_confirmation_entry.rb
- spec/services/encryption/encryptors/session_encryptor_spec.rb
- spec/services/session_encryptor_spec.rb
**Why**: To modularize the encryption code and make use of the
conventions setup by the attribute and PII encryptors
session.
authenticated, make sure to …
> LG-246 Add session encryptor

- app/services/idv/proofer.rb
- spec/features/flows/sp_authentication_flows_spec.rb
- spec/views/idv/review/new.html.slim_spec.rb
> LG-275 Remove unused financial idv params

- bin/release
**Why**: Anything that is repeated manually more than a few times should
be automated. This also ensures everyone is performing release
management in the same way and reduces discrepancies and human error.
instead of the `session` …
> Add script to automate release management

- .circleci/config.yml
**Why**: It looks like the image comes with bundler, and explicitly
installing it causes some problems with how the pre-installed version is
configured which was causing CI to fail.
instead of the `session` helper so the data does not …
> Remove bundler installation from circle config

- app/services/idv/profile_step.rb
- spec/controllers/idv/sessions_controller_spec.rb
- spec/services/idv/profile_step_spec.rb
This will help debugging proofing stuff
session.
> Add proofing info to analytics

- Gemfile
- Gemfile.lock
- app/services/idv/proofer.rb
- config/initializers/proofer.rb
- spec/services/idv/proofer_spec.rb
> Update proofer and aamva gems

- app/controllers/concerns/unconfirmed_user_concern.rb
- app/controllers/sign_up/email_resend_controller.rb
- app/services/analytics.rb
- spec/controllers/sign_up/email_confirmations_controller_spec.rb
- spec/controllers/sign_up/email_resend_controller_spec.rb
**Why**: Make consistent with similar events
**How**: Rename affected constants, update event type name in message
session.
authenticated, make sure to add …
> LG-222 Prefix email confirmation event with user registration label

- Gemfile
- Gemfile.lock
- config/initializers/proofer.rb
Removes downcasing of env vars, no longer necessary.
session.
> Update to latest aamva gem

- Gemfile
**Why**: So we can use the `safety_assured` method for our migrations in
production
session. …
> Move strong_migrations out of development group

- app/services/encryption/encryptors/pii_encryptor.rb
- app/services/pii/cipher.rb
- spec/controllers/users/sessions_controller_spec.rb
- spec/services/encryption/encryptors/pii_encryptor_spec.rb
**Why**: So that we can start the move towards the new 3L-KMS
method (hamburger encryption)
session. …
> LG-285 Implement 2L-KMS (hotdog encryption)

- .reek
- app/models/concerns/user_access_key_overrides.rb
- spec/models/user_spec.rb
> LG-286 Write encryption inputs to `encrypted_password_digest

- app/assets/stylesheets/components/_jurisdiction.scss
- app/assets/stylesheets/components/all.scss
- app/views/idv/jurisdiction/new.html.slim
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
https://cm-jira.usa.gov/browse/LG-302
session.
> LG-302 update jurisdiction screen

- app/helpers/application_helper.rb
- config/locales/links/en.yml
- config/locales/links/es.yml
- config/locales/links/fr.yml
- spec/features/flows/sp_authentication_flows_spec.rb
- spec/support/idv_examples/cancel_at_idv_step.rb
https://cm-jira.usa.gov/browse/LG-306
session.
> LG-306 Update to match current designs

- app/services/file_encryptor.rb
**Why**: Because our local machines, the hosts where we deploy our app,
and now CircleCI all use gpg2
session.
authenticated, make sure to add …
> Upgrade file encryptor to work with gpg2

- app/services/idv/phone_step.rb
- lib/proofer_mocks/address_mock.rb
- spec/controllers/idv/phone_controller_spec.rb
- spec/services/idv/phone_step_spec.rb
> Add proofer information to result and analytics

- config/service_providers.yml
**Why**: move.mil is adding additional redirect uris
session. …
> LG-313 move.mil SP changes for production

- app/decorators/service_provider_session_decorator.rb
- config/locales/service_providers/en.yml
- config/locales/service_providers/es.yml
- config/locales/service_providers/fr.yml
**Why**: Create support text for SAM users in the sign in/create account
**How**: Update locale files and sp session decorator
session.
authenticated, make …
> LG-321 Support text for SAM.gov users

- app/services/personal_key_generator.rb
- spec/services/personal_key_generator_spec.rb
**Why**: So that we can start migrating personal keys to a system that
works like passwords
session. …
> Write to encrypted personal key digest

- Gemfile
- Gemfile.lock
**Why**: To fix XML sanitization issue
session.
> Upgrade AAMVA to v3.0.1

- app/views/layouts/card_wide.html.slim
Revert bug in card_wide layout  introduced in https://github.com/18F/identity-idp/pull/2231
session. …
> Revert background to blue for card wide layout

- config/service_providers.yml
**Why**: SAM wants to add a redirect uri and a new SP that they can use to test prod from UAT.
session.
authenticated, …
> LG-372 Update SAM SP in production

- .reek
- app/controllers/usps_upload_controller.rb
- app/services/holiday_service.rb
- config/application.yml.example
- config/routes.rb
- spec/controllers/usps_upload_controller_spec.rb
- spec/services/holiday_service_spec.rb
- spec/services/usps_confirmation_spec.rb
Not sure if we need auth around this or not, I don't think the health check endpoints have any auth.
session. …
> LG-402 Add endpoint and holiday service

- .reek
- app/services/personal_key_generator.rb
**Why**: So that we can continue the migration to recovery code digests
that mirror password digests
session.
> Read encrypted_recovery_code_digest column

- config/locales/devise/en.yml
- config/locales/devise/es.yml
- config/locales/devise/fr.yml
**Why**:
The help instructions aren't clear.
**How**:
Update them to make them simpler.
session. …
> [LG-350] Update personal key instructions

- .codeclimate.yml
- spec/controllers/account_reset/cancel_controller_spec.rb
- spec/controllers/account_reset/delete_account_controller_spec.rb
- spec/controllers/account_reset/report_fraud_controller_spec.rb
- spec/controllers/account_reset/request_controller_spec.rb
- spec/jobs/sms_account_reset_notifier_job_spec.rb
- spec/mailers/user_mailer_spec.rb
- spec/models/account_reset_request_spec.rb
- spec/services/account_reset_service_spec.rb
- spec/views/account_reset/confirm_delete_account/show.html.slim_spec.rb
- spec/views/account_reset/delete_account/show.html.slim_spec.rb
- spec/views/account_reset/request/show.html.slim_spec.rb
**Why**: We want tests to adhere to our style guides.
session.
> Allow Code Climate to analyze the spec folder

- config/locales/account_reset/en.yml
> LG-447 Fix typo on account reset page

- app/services/account_reset_service.rb
> LG-451 Remove duplicate SMS sent with account reset delayed notification

- config/application.yml.example
**Why**: This config was used to tail the whenever gem how often to run
the USPS mail batch job. We are moving that outside of the app so it is
no longer necessary to keep this config around
instead of the `session` helper so the data …
> LG-408 Remove USPS mail batch hours config

- spec/features/two_factor_authentication/sign_in_spec.rb
**Why**: This TODO that had been previously removed got added back by
mistake in #2308 and I forgot to remove it before merging the PR.
session. …
> Remove stray TODO

- Gemfile
- Gemfile.lock
- lib/proofer_mocks/address_mock.rb
- lib/proofer_mocks/resolution_mock.rb
- lib/proofer_mocks/state_id_mock.rb
- spec/controllers/idv/confirmations_controller_spec.rb
- spec/controllers/idv/review_controller_spec.rb
- spec/controllers/idv/usps_controller_spec.rb
- spec/services/idv/agent_spec.rb
**Why**: The new changes to the gems include the changes to start using
LexisNexis for address verification. We are going to use them while we
work with AAMVA to improve address verification with them.
instead of the `session` helper …
> LG-436 Update gems to verify addresses with LN

- config/service_providers.yml
**Why**: Agency request
session.
> LG-482 Add a new redirect uri to DOT portal SP

- .reek
- app/controllers/concerns/two_factor_authenticatable.rb
- app/controllers/idv/sessions_controller.rb
- app/controllers/sign_up/personal_keys_controller.rb
- app/decorators/user_decorator.rb
- app/models/concerns/user_access_key_overrides.rb
- app/models/user.rb
- app/services/encryption/password_verifier.rb
- app/services/personal_key_generator.rb
- spec/factories/users.rb
- spec/features/two_factor_authentication/sign_in_spec.rb
- spec/features/users/regenerate_personal_key_spec.rb
- spec/forms/password_reset_email_form_spec.rb
- spec/services/encryption/password_verifier_spec.rb
- spec/services/personal_key_generator_spec.rb
- spec/support/shared_examples_for_personal_keys.rb
This reverts commit 050a9984c95d61b03c51ccbd7a6dc186d07c39cd.
I didn't rebase this before merging and broke the 2fa options menu. This commit reverts so that master is green again while I fix it.
> Revert "Stop reading personal key columns (#2313)"

- spec/jobs/sms_reply_sender_job_spec.rb
**Why**: Job isn't tested directly
**How**: Cover job performance
session. …
> Add SMS opt-out reply job spec

- .gitignore
> Ignore saml_*.txt files generated by tests

- config/valid_email.yml
**Why**: qq.com is on our list of banned disposable email services and should not be.
**How**: Remove it from our list
session.
authenticated, make sure to …
> LG-455 User can't create account because their email is "invalid"

- app/presenters/idv/cancellation_presenter.rb
**Why**: Better readability and maintainability
session.
> Cleanup idv cancel path formation

- app/controllers/two_factor_authentication/personal_key_verification_controller.rb
- app/services/openid_connect_redirector.rb
- config/routes.rb
- spec/features/two_factor_authentication/remember_device_spec.rb
- spec/features/two_factor_authentication/sign_in_spec.rb
- spec/features/users/sign_in_spec.rb
- spec/services/openid_connect_redirector_spec.rb
This adds two fixes to the 20 July 2018 RC:
1. Fix 500 errors on bad personal key
2. Match host on redirect URIs
> Deploy RC62.1 to staging

- app/controllers/two_factor_authentication/personal_key_verification_controller.rb
- app/services/openid_connect_redirector.rb
- config/routes.rb
- spec/features/two_factor_authentication/remember_device_spec.rb
- spec/features/two_factor_authentication/sign_in_spec.rb
- spec/features/users/sign_in_spec.rb
- spec/services/openid_connect_redirector_spec.rb
This adds two fixes to the 20 July 2018 RC:
1. Fix 500 errors on bad personal key
2. Match host on redirect URIs
> Deploy RC62.1 to Prod

- app/decorators/service_provider_session_decorator.rb
- app/decorators/session_decorator.rb
- app/views/shared/_sp_alert.html.slim
- config/locales/service_providers/en.yml
- config/locales/service_providers/es.yml
- config/locales/service_providers/fr.yml
**Why**: To provide clear agency specific instructions on account creation
**How**: Update the locale files.
session.
authenticated, make sure to add …
> LG-483 Update USAJOBS / TTP instructions on create account

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
**Why**: To ensure our code stays consistent and to reduce issues during
and after deployments.
session. …
> Update PR template and contribution guidelines

- config/service_providers.yml
**Why**: Per request from the agency.
of [indexes in …
> LG-533 Add a New Redirect URI for the DOE - Fossil Energy SP

- app/assets/stylesheets/components/_profile-section.scss
**Why**: Broken corners are bad and we should feel bad.
**How**: Hide the overflow.
of [indexes in …
> LG-555 Fix border radius on Account boxes

- config/service_providers.yml
**Why**: To be able to test SP-initiated logout locally
in the various …
> Update redirect_uri list for OIDC Sinatra dev app

- config/service_providers.yml
**Why**: Per request from the agency due to new logout uri restrictions.
of …
> LG-562 Add a new redirect_uri for logout with the CBP ROAM SP

- config/service_providers.yml
**Why**: Per request from the agency.  This is in preparation for exact matching on post_logout_redirect_uri
will warn you about unsafe migrations and has great step-by-step …
> LG-582 Add a logout redirect uri for the Trusted Traveler Program SP

- spec/services/otp_rate_limiter_spec.rb
**Why**: The OTP rate limiter was doing an exact match on
`second_factor_locked_out` after rate limitting a user. If the system
clock advances to the next second between the user being locked out and
the check against the current time, this test fails. This happens
frequently on CI. This commit uses rspec's `be_within.of` matcher
instead of using an exact match.
as the …
> Fix a flickering spec in the OTP rate limiter

- config/service_providers.yml
> Change return to sp url for RRB LOA3 in Production

- app/services/idv/proofer.rb
**Why**:
We want to start with the right set of vendors for
proofing.
**How**:
We initialize `@vendor` to `nil` rather than a truthy
value. …
> Int: Fix Idv::Proofer vendor initialization

- app/services/idv/proofer.rb
**Why**:
We want to start with the right set of vendors for
proofing.
**How**:
We initialize `@vendor` to `nil` rather than a truthy
value. …
> Staging: Fix Idv::Proofer vendor initialization

- bin/release
**Why**:
Sometimes our gem bundle isn't in sync when we fetch the most
recent `master` of `identity-devops`. This fixes that.
**How**:
Run `bundle install` after fetching the most recent `master` of
`identity-devops` …
> Run `bundle install` in devops repo when releasing

- app/models/anonymous_user.rb
**Why**:
Sometimes, we have an anonymous user. They don't have
any configured phones.
**How**:
Add a method that returns `nil`
for various …
> Add nil phone_configuration to anonymous user

- app/decorators/service_provider_session_decorator.rb
> LG-640 Add Railroad Retirement Board Branding

- spec/features/users/webauthn_management_spec.rb
**Why**:
As part of the move to multiple phones for a user, we changed how
we build out users in factories when they also have a phone
configured. This causes some PRs to break master if they didn't
rebase.
**How**:
Fix failing tests.
deploys to avoid production errors. The [strong_migrations](https://github.com/ankane/strong_migrations#the-zero-do …
> Fix tests using users with phones

- app/views/accounts/_pii.html.slim
**Why**: These are the most sensitive digits. A variety of identity proofing operations often require only the last 4 digits, including for things like pulling a credit report.
**How**: Replace the last four digits with asterisks.
deploys to avoid production errors. The [strong_migrations](https://github.com/ankane/strong_migrations#the-zero-downti …
> LG-654 Redact entire SSN from /account page

- config/service_providers.yml
> Add TTP exact matching logout redirect uri

- config/application.yml.example
> Enable webauthn in prod

- config/service_providers.yml
> LG-702 Add redirect uris for Forest Service SP

- app/javascript/packs/webauthn-setup.js
**Why**: To allow for optional greater security while still offering broad compatibility.
**How**: Add the algorithms to the pubKeyCredParams hash which is fed to the navigator.credentials.create API call.
will warn …
> LG-696 Add webauthn algorithms

- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
**Why**: We no longer include periods at the end of actions links
in the various environments right before deploying, taking into account the users
who might not have interacted with this column yet (such as users who have not
set a password yet)
production database. See #2127 for an example when a migration caused deployment
issues. In that case, all the migration did was add a new column and an index to
the …
> Remove period from end of "Send me another letter"

- app/services/account_reset/validate_cancel_token.rb
- spec/controllers/account_reset/cancel_controller_spec.rb
**Why**: The event property `event` was set to `visit`, which is wrong.
This particular event corresponds to the user clicking a link in their
email to cancel the account deletion request. This only validates the
token, and if the token is valid, it displays a page where the user
can click a button to process the cancellation.
deploys to avoid …
> Update Account Reset Cancel analytics

- .circleci/config.yml
- Gemfile
- Gemfile.lock
**Why**: To pcik up bug fixes in the latest patch version
in the …
> LG-792 Upgrade to ruby v2.5.3

- lib/deploy/activate.rb
> Make the geo DB world-readable by default

- package.json
**Why**: To use the latest and greatest and because this is the version
the CircleCI container we are using has pre-installed
in the various environments right before deploying, taking into account the users
who might not have interacted with this column yet (such as users who have not
set a password yet)
production database. See #2127 for an example when a migration caused deployment
issues. In that case, all …
> Upgrade to node v10

- yarn.lock
**Why**: To pick up most recent updates and bug fixes
> Update npm packages

- app/services/marketing_site.rb
- app/views/devise/mailer/confirmation_instructions.html.slim
- app/views/layouts/user_mailer.html.slim
- config/locales/mailer/en.yml
- config/locales/mailer/es.yml
- config/locales/mailer/fr.yml
- spec/views/layouts/user_mailer.html.slim_spec.rb
**Why**: To enhance visual appeal.
**How**: Reword and move things around.  Get rid of the big blue box that dominated the design.  Update the user_mailer template along with the confirmation_instructions.
will warn …
> LG-571 Update email template

- app/decorators/service_provider_session_decorator.rb
- config/service_providers.yml
**Why**: Agency wants to remove help text and update a staging redirect uri
**How**: Update service_providers.yml with the new uri and remove the sp from ServiceProviderSessionDecorator to remove help text.
will warn …
> LG-885 Update DOL Foreign Labor Gateway SP

- package.json
- yarn.lock
**Why**: We don't appear to use it has a bug that is causing noise in
our GH security alerts.
> Remove webpack dev server

- app/controllers/two_factor_authentication/webauthn_verification_controller.rb
- app/models/webauthn_configuration.rb
- app/policies/two_factor_authentication/webauthn_policy.rb
- config/application.yml.example
- config/routes.rb
- lib/feature_management.rb
- spec/controllers/two_factor_authentication/options_controller_spec.rb
- spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
- spec/lib/feature_management_spec.rb
- spec/models/webauthn_configuration_spec.rb
**Why**: Because webauthn is enabled everywhere and we do not have plans
to disable it
> Remove webauthn_enabled feature flag

- README.md
> Added Yarn to list of dependencies that must be installed.

- config/application.yml.example
**Why**: DOJ would like to use PIVs as second factors.
**How**: Add the usdoj.gov domain to the list of email domains we support. fbi.gov was also requested but is already in the list.
will warn you about unsafe …
> Add usdoj.gov to list of supported email domains

- docker-compose.yml
Enables rails app to send mail to mailcatcher when running in docker-compose, similar to other local development configuration.
in the various environments right before deploying, taking into account the users
who might not have interacted with this column yet (such as users who have not
set a password yet)
production database. See #2127 for an example when a migration caused deployment
issues. In that case, all …
> Connect docker-compose web container to mailcatcher container

- app/controllers/events_controller.rb
> Use `render_not_found` helper in events controller

- config/application.yml.example
**Why**: due to DHS request
in the various environments right before …
> Add *.dhs.gov to piv/cac supported email domains

- app/services/google_analytics_measurement.rb
> Fix google analytics 500 error on server to server call

- app/javascript/app/form-validation.js
**Why**: To cleanup up console errors
> Only invoke ga function if it is defined

- app/services/idv/steps/doc_auth_base_step.rb
> Add more IAL2 test credential mime types

- app/services/idv/steps/send_link_step.rb
> Fix doc auth invalid phone error

- spec/features/multiple_emails/sign_in_spec.rb
**Why:** Test sign-in from more than one email address for the same user, to make sure that feature continues to work.
> LG-1276 Add test for sign-in with multiple email addresses

- app/controllers/sign_up/passwords_controller.rb
- app/forms/password_reset_email_form.rb
- app/models/nonexistent_user.rb
- app/models/user.rb
- app/presenters/confirmation_email_presenter.rb
- app/services/request_password_reset.rb
- config/locales/mailer/en.yml
- config/locales/mailer/es.yml
- config/locales/mailer/fr.yml
- spec/controllers/sign_up/passwords_controller_spec.rb
- spec/controllers/users/reset_passwords_controller_spec.rb
- spec/factories/users.rb
- spec/forms/password_reset_email_form_spec.rb
- spec/models/nonexistent_user_spec.rb
- spec/services/request_password_reset_spec.rb
- spec/views/devise/mailer/confirmation_instructions.html.slim_spec.rb
**Why**: We are not using roles currently, so this code is unused.
> Remove roles from users

- config/service_providers.yml
> Update return_to_sp_url for FMCSA National Registry/Appian

- app/controllers/two_factor_authentication/backup_code_verification_controller.rb
> LG-1332 Sign in with backup codes needs redirect to SP

- app/services/analytics.rb
- config/service_providers.yml
- db/migrate/20190529120309_fix_backup_code_configuration_index.rb
- db/schema.rb
- spec/services/analytics_spec.rb
> Deploy RC 84.1 to staging (final)

- app/services/analytics.rb
- config/service_providers.yml
- db/migrate/20190529120309_fix_backup_code_configuration_index.rb
- db/schema.rb
- spec/services/analytics_spec.rb
> Deploy RC 84.1 to production (final)

- spec/features/webauthn/sign_up_spec.rb
**Why**: So we have coverage of the places where webauthn can be setup
> Test webauthn sign up for first and second mfa option

- app/controllers/two_factor_authentication/backup_code_verification_controller.rb
- spec/features/two_factor_authentication/backup_code_sign_up_spec.rb
Right now it is forcing the user to MFA again.
in the various …
> LG-1408 Sign in with last backup code should regenerate backup codes

- app/controllers/users/emails_controller.rb
- app/mailers/user_mailer.rb
- app/views/user_mailer/email_deleted.html.erb
- config/locales/user_mailer/en.yml
- config/locales/user_mailer/es.yml
- config/locales/user_mailer/fr.yml
- spec/features/multiple_emails/email_management_spec.rb
- spec/mailers/user_mailer_spec.rb
WHY:
As a user I want to receive an email notification to all my confirmed email addresses when I delete an email address.
> send email notification when email deleted

- config/locales/errors/en.yml
- config/locales/errors/es.yml
- config/locales/errors/fr.yml
**Why**:  So users understand that they own the phone and are adding an additional one.
of [indexes in …
> LG-1404 Change message "This phone number is already in use."

- spec/support/capybara.rb
**Why**: To pass the options in a way that is supported
> Update chromedriver invocation

- app/views/accounts/_emails.html.slim
- config/locales/account/en.yml
- config/locales/account/es.yml
- config/locales/account/fr.yml
**Why**: So that it says "Email address" instead of "Email addresses"
> LG-1474 Change the text on the email address label

- app/views/accounts/_emails.html.slim
> LG-1418 Remove visual remnants when you can no longer add emails

- app/views/users/emails/confirm_delete.html.slim
- config/locales/email_addresses/en.yml
- config/locales/email_addresses/es.yml
- config/locales/email_addresses/fr.yml
> LG-1445 Messaging for users about to delete an email

- config/initializers/new_relic_tracers.rb
- spec/services/encryption/encryptors/pii_encryptor_spec.rb
**Why**: So we know how these are performing. I was looking at some transactions in NR and realized these are not being traced.
> Trace encryptor methods

- app/models/concerns/deprecated_user_attributes.rb
- app/models/user.rb
- config/application.yml.default
**Why**: So we can see how often they are being used as we start getting rid of them
> Add ability to show deprecation warnings when using email attributes

- config/locales/user_mailer/en.yml
- config/locales/user_mailer/es.yml
- config/locales/user_mailer/fr.yml
To match the screenshot in this pr https://github.com/18F/identity-idp/pull/3105
> LG-1639 Fix copy for account creation email

- app/views/users/shared/_phone_number_edit.html.erb
**Why**: Because it shouldn't be there.
> Remove git push from phone form

- config/locales/doc_auth/en.yml
- config/locales/doc_auth/es.yml
- config/locales/doc_auth/fr.yml
- config/locales/forms/en.yml
- spec/support/features/cac_proofing_helper.rb
**Why:** so users better understand identity verification
> Update Doc Auth welcome screen content

- app/services/reports/omb_fitara_report.rb
Report was new users for the month.  It should be total cumulative counts for that month.
> Change OMB Fitara report to total cumulative users per month

- app/views/users/shared/_phone_number_edit.html.erb
- config/locales/forms/en.yml
- config/locales/forms/es.yml
- config/locales/forms/fr.yml
Originally PR https://github.com/18F/identity-idp/pull/2359 recently broken
> LG-1819 Fix confusing placeholder phone number

- app/controllers/concerns/unconfirmed_user_concern.rb
- app/controllers/sign_up/email_confirmations_controller.rb
- app/controllers/sign_up/passwords_controller.rb
- spec/controllers/sign_up/email_confirmations_controller_spec.rb
- spec/support/features/session_helper.rb
**Why:** in order to prevent 500 errors on password validation
> LG-1710 validating that the token has not expired in order to prevent 500 errors on password validation

- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/variables/_app.scss
- app/views/layouts/base.html.slim
- config/initializers/assets.rb
**Why**: Because we aren't using them
> Remove unused assets

- app/services/capture_doc/create_request.rb
- spec/features/idv/doc_auth/link_sent_step_spec.rb
- spec/services/capture_doc/create_request_spec.rb
> LG-1902 Clear previous session when proofing with hybrid flow

- app/views/accounts/actions/_disable_piv_cac.html.slim
- app/views/accounts/actions/_disable_totp.html.slim
**Why**: Because right now they look back and it drives me crazy
> Style the buttons to disable PIV and TOTP as links

- app/controllers/openid_connect/authorization_controller.rb
- app/controllers/saml_idp_controller.rb
- app/models/sp_return_log.rb
- app/services/db/sp_return_log/add_return.rb
- app/services/db/sp_return_log/create_request.rb
- app/services/db/sp_return_log/success_rate_by_sp.rb
- app/services/reports/sp_success_rate_report.rb
- app/services/service_provider_request_handler.rb
- config/initializers/job_configurations.rb
- db/migrate/20190914191524_create_sp_return_logs.rb
- db/schema.rb
- spec/config/initializers/job_configurations.rb
- spec/features/reports/sp_success_rate_report_spec.rb
**Why**: So we can determine if login.gov is meeting expectations.
> LG-1772 Successful handoff rate by SP report

- app/controllers/idv/usps_controller.rb
- app/models/proofing_cost.rb
- app/services/db/proofing_cost/add_user_proofing_cost.rb
- app/services/db/proofing_cost/proofing_costs_summary.rb
- app/services/idv/phone_step.rb
- app/services/idv/send_phone_confirmation_otp.rb
- app/services/idv/steps/doc_auth_base_step.rb
- app/services/idv/steps/verify_step.rb
- app/services/reports/proofing_costs_report.rb
- config/initializers/job_configurations.rb
- db/migrate/20190907063344_create_proofing_costs.rb
- db/schema.rb
- spec/config/initializers/job_configurations.rb
- spec/features/reports/proofing_costs_report_spec.rb
**Why**: So login.gov can determine the exact cost per user
> LG-1796 Track Proofing Costs

- app/services/idv/steps/send_link_step.rb
- spec/features/idv/doc_auth/send_link_step_spec.rb
**Why**: It needs to be formatted or Pinpoint won't send the message
> LG-1954 Format the hybrid flow phone number

- spec/features/users/user_edit_spec.rb
**Why**: So we aren't logging things that don't need logging
> Cleanup log statement

- config/service_providers.yml
- Add redirect URI
- fix help text typo
> `DOT - FMCSA - Drug and Alcohol Clearinghouse` fixes

- app/assets/stylesheets/components/_form.scss
- app/javascript/app/checkbox.js
- app/javascript/packs/application.js
WHY: As a user on Windows 10 in High Contrast, I want to see when check-boxes are checked.
Edge on Windows 10 High Contrast Mode:
Edge on Windows 10 Normal Mode
Chrome on Mac:
> LG-1802 fixed checkboxes in high contrast mode

- app/controllers/users/piv_cac_login_controller.rb
- app/forms/user_piv_cac_login_form.rb
- app/forms/user_piv_cac_setup_form.rb
- config/locales/titles/en.yml
- config/locales/titles/es.yml
- config/locales/titles/fr.yml
- config/locales/two_factor_authentication/en.yml
- config/locales/two_factor_authentication/es.yml
- config/locales/two_factor_authentication/fr.yml
- spec/forms/user_piv_cac_setup_form_spec.rb
Continuation of this PR https://github.com/18F/identity-idp/pull/3344
> LG-915 LG-1928 PIV/CAC certificate timeout and ocsp errors

- app/services/service_provider_seeder.rb
- config/service_providers.localdev.yml
Creating a new PR for https://github.com/18F/identity-idp/pull/3395 based on RC 96 branch
> New base branch for pull/3395 - Pulling out use of yaml aliases

- app/services/service_provider_seeder.rb
- config/service_providers.localdev.yml
Merging changes from:
Pulling out use of yaml aliases #3395
> Rc 96 merg pull #3396 into master

- Makefile
- Procfile_dev
> Remove Procfile_dev

- app/forms/openid_connect_authorize_form.rb
- config/application.yml.default
- lib/saml_idp_constants.rb
- spec/controllers/saml_idp_controller_spec.rb
**Why**: Broke IAL2 flow https://github.com/18F/identity-idp/pull/3384
> Revert LG-1896

- app/forms/openid_connect_authorize_form.rb
- config/application.yml.default
- lib/saml_idp_constants.rb
- spec/controllers/saml_idp_controller_spec.rb
**Why**: Broke IAL2 flow https://github.com/18F/identity-idp/pull/3384
> Patch release RC 96.1 - Revert LG-1896 (#3403)

- package.json
- yarn.lock
**Why**: To pick up support for new Canadian and US area codes that are only recognized by the latest version.
> LG-2323 Update libphone-js

- app/services/funnel/doc_auth/register_step.rb
- spec/features/reports/doc_auth_funnel_report_spec.rb
**Why**: We only want to create an entry for the welcome screen otherwise we update an existing entry
> Fix blank doc_auth_log entries

- config/locales/two_factor_authentication/en.yml
- config/locales/two_factor_authentication/es.yml
- config/locales/two_factor_authentication/fr.yml
**Why**: So that it is more clear what each method is and does
> LG-1649 Update design and copy for MFA more info

- docs/encryption-and-key-rotation.md
Adds disclaimer
Removes broken link
> Adds disclaimer about outdated information

- config/application.yml.default
Why: 
We get 5 total doc auth attempts when:
acuant_max_attempts = 10 (2 uploads per attempt)
We will get 10 total doc auth attempts with:
acuant_max_attempts = 20
> Change max doc auth attmepts to 10

- app/controllers/concerns/saml_idp_auth_concern.rb
- app/forms/openid_connect_authorize_form.rb
- app/presenters/saml_request_presenter.rb
- app/services/attribute_asserter.rb
- app/services/saml_request_validator.rb
- app/services/service_provider_request_handler.rb
- app/services/store_sp_metadata_in_session.rb
- config/application.yml.default
- lib/saml_idp_constants.rb
- spec/controllers/saml_idp_controller_spec.rb
- spec/features/users/sign_in_spec.rb
- spec/support/features/idv_helper.rb
- spec/support/saml_auth_helper.rb
**Why:** We want to accept IAL2 assertions and still keep backwards compatibility with LOA3 assertions.
> LG-2410  Accept IAL2 and LOA3 assertions

- app/services/piv_cac_service.rb
- config/application.yml.default
- config/initializers/secure_headers.rb
- lib/feature_management.rb
- spec/lib/feature_management_spec.rb
- spec/services/piv_cac_service_spec.rb
> Revert "Lg 2310 run locally with piv cac"

- config/initializers/secure_headers.rb
Why:
Fix error when passing verification token on Add PIV/CAC page
> Added piv_cac domains to CSP

- .reek.yml
- app/controllers/concerns/saml_idp_auth_concern.rb
- app/controllers/concerns/saml_idp_logout_concern.rb
- app/controllers/test/piv_cac_authentication_test_subject_controller.rb
- app/forms/edit_phone_form.rb
- app/forms/idv/phone_form.rb
- app/forms/new_phone_form.rb
- app/services/analytics.rb
- app/services/encryption/contextless_kms_client.rb
- app/services/encryption/kms_client.rb
- app/services/encryption/password_verifier.rb
- app/services/flow/base_step.rb
- app/services/push_notification/account_delete.rb
- db/migrate/20190212163140_drop_password_metrics.rb
- It was being ignored very often, which I think is a sign that it was
too strict
I checked with @jmhooper who was also in favor of this (just look at the number of exceptions there were!). I'd love to talk about other lints to re-evaluate!
> Remove FeatureEnvy lint

- app/controllers/application_controller.rb
- app/controllers/saml_idp_controller.rb
- app/services/db/sp_cost/add_sp_cost.rb
- app/services/db/sp_cost/sp_cost_summary.rb
- app/services/db/sp_cost/total_sp_cost_summary.rb
- app/services/identity_linker.rb
- app/services/idv/phone_step.rb
- app/services/idv/send_phone_confirmation_otp.rb
- app/services/idv/steps/doc_auth_base_step.rb
- app/services/reports/base_report.rb
- app/services/reports/sp_cost_report.rb
- app/services/reports/total_sp_cost_report.rb
- app/services/usps_confirmation_maker.rb
- config/initializers/job_configurations.rb
- db/migrate/20200115142141_add_ial_to_sp_costs.rb
- db/schema.rb
- spec/config/initializers/job_configurations.rb
- spec/services/db/sp_cost/add_sp_cost_spec.rb
- spec/services/reports/sp_cost_report_spec.rb
- spec/services/reports/total_sp_cost_report_spec.rb
- spec/support/features/idv_from_sp_helper.rb
**Why**: So we can so a breakdown in cost on a per sp and total basis.
**How**: Create two reports for total and per sp and run the report for the current month.  The files are timestamped with the day in S3.
> LG-2515 SP Cost Reports

- app/controllers/health/health_controller.rb
- app/controllers/users/piv_cac_authentication_setup_controller.rb
- app/policies/mfa_policy.rb
- spec/services/saml_endpoint_manager.rb
**Why**: To get the linters green
> Cleanup lingering rubocop issues

- app/controllers/idv/cac_controller.rb
- app/controllers/test/piv_cac_authentication_test_subject_controller.rb
- app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
- app/controllers/users/piv_cac_authentication_setup_controller.rb
- app/controllers/users/piv_cac_login_controller.rb
- app/presenters/two_factor_auth_code/piv_cac_authentication_presenter.rb
- app/services/piv_cac_service.rb
- app/views/idv/cac/present_cac.html.erb
- config/routes.rb
- spec/controllers/test/piv_cac_authentication_test_subject_controller_spec.rb
- spec/services/piv_cac_service_spec.rb
- spec/support/features/session_helper.rb
**Why**: To implement the new API setup by 18F/identity-pki#110
> Specify the redirect URI in the request to the PKI server

- app/controllers/users/two_factor_authentication_setup_controller.rb
- app/presenters/two_factor_authentication/auth_app_selection_presenter.rb
- app/presenters/two_factor_authentication/backup_code_selection_presenter.rb
- app/presenters/two_factor_authentication/selection_presenter.rb
- app/presenters/two_factor_authentication/webauthn_selection_presenter.rb
- app/presenters/two_factor_options_presenter.rb
- app/views/users/two_factor_authentication_setup/index.html.erb
- config/locales/errors/en.yml
- config/locales/errors/es.yml
- config/locales/errors/fr.yml
- config/locales/two_factor_authentication/en.yml
- config/locales/two_factor_authentication/es.yml
- config/locales/two_factor_authentication/fr.yml
- spec/features/accessibility/user_pages_spec.rb
- spec/features/users/sign_up_spec.rb
- spec/presenters/two_factor_options_presenter_spec.rb
**Why**
- Two factor choices currently do not give insight on the security benefits for each option
**How**:
- Use labels that inform about security
> Recommend more secure MFA methods

- bin/docker_setup
Small docker change based on my local environment
> Docker: Use "rm -f" so that if the file doesn't exist, there is no error

- .dockerignore
- .gitignore
- Dockerfile
- Makefile
- README.md
- bin/docker_setup
- bin/setup
- docker-compose.yml
- spec/support/capybara.rb
- spec/support/database_cleaner.rb
Working docker-compose up. There are still manual steps to fold in, but this should work for some initial feedback.
> WIP : LG-2562 : Create IDP container with Docker

- app/controllers/idv/cac_controller.rb
- spec/features/idv/cac/present_cac_step_spec.rb
- spec/support/features/cac_proofing_helper.rb
**How**: Was parsing the wrong field (dn instead of subject)
> LG-2622 Fix CAC error when attempting to proof

- db/migrate/20200210235313_drop_service_provider_requests.rb
- db/schema.rb
**Why**: Drop the table now that we stopped using it
> LG-2025 Move service_service_provider_requests to redis part 3

- package.json
- spec/javascripts/app/components/focus-trap-proxy_spec.js
- Fix globbing/quoting in npm test command (without this, my machine only ran one test file...not all of them)
- Fix proxy spec that was failing locally (it was skipped on my machine without the globbing)
- I *think* I fixed it, the test had so many layers of stubs and proxies, it was a little tough for me to figure out what was actually the goal of the test, so I took a guess
> Fix JS tests

- app/assets/stylesheets/components/_list.scss
- app/controllers/sign_up/completions_controller.rb
- app/forms/openid_connect_authorize_form.rb
- app/models/identity.rb
- app/presenters/openid_connect_user_info_presenter.rb
- app/services/attribute_asserter.rb
- app/services/openid_connect_attribute_scoper.rb
- app/view_models/sign_up_completions_show.rb
- app/views/sign_up/completions/_requested_attributes.html.erb
- app/views/sign_up/completions/_requested_attributes.html.slim
- config/locales/help_text/en.yml
- config/locales/help_text/es.yml
- config/locales/help_text/fr.yml
- spec/controllers/openid_connect/authorization_controller_spec.rb
- spec/controllers/sign_up/completions_controller_spec.rb
- spec/features/openid_connect/openid_connect_spec.rb
- spec/forms/openid_connect_authorize_form_spec.rb
- spec/presenters/openid_connect_user_info_presenter_spec.rb
- spec/services/attribute_asserter_spec.rb
- spec/services/openid_connect_attribute_scoper_spec.rb
This is a WIP PR so I can get some feedback on parts I'm stuck on, have questions about
> LG-2672: verified_at attribute (freshness value)

- README.md
- app/javascript/app/webauthn.js
- spec/javascripts/app/webauthn_spec.js
**Why**: So my Yubikey works in Windows
- Additional configuration supports Windows devices
- prevent `excludeCredentials` from returning empty data object
> LG-2596: Better webauthn Windows support

- app/controllers/users/two_factor_authentication_controller.rb
- spec/features/sp_cost_tracking_spec.rb
**Why**: Tracking was hooked up in the wrong spot
> LG-2735 Fix cost tracking for sms and voice underreporting

- app/controllers/concerns/verify_sp_attributes_concern.rb
- app/controllers/sign_up/completions_controller.rb
- app/models/identity.rb
- app/services/identity_linker.rb
- app/view_models/sign_up_completions_show.rb
- config/locales/titles/en.yml
- config/locales/titles/es.yml
- config/locales/titles/fr.yml
- db/migrate/20200303202931_add_last_consented_at_to_identities.rb
- db/schema.rb
- spec/controllers/concerns/verify_sp_attributes_concern_spec.rb
- spec/controllers/sign_up/completions_controller_spec.rb
- spec/features/openid_connect/openid_connect_spec.rb
- spec/services/identity_linker_spec.rb
- spec/view_models/sign_up_completions_show_spec.rb
- spec/views/sign_up/completions/show.html.slim_spec.rb
This is ready for review! Still waiting on final copy
> LG-2675: Re-prompt for consent to share with SPs after a year

- config/locales/titles/en.yml
- config/locales/titles/es.yml
- config/locales/titles/fr.yml
- spec/view_models/sign_up_completions_show_spec.rb
> Update expired consent copy

- config/environments/test.rb
- lib/tasks/test.rake
Show views not rendered during a test run
**Why**: To track accessibility test coverage in app views
More details in Jira ticket: https://cm-jira.usa.gov/browse/LG-2774
> LG-2774 Figure out the gap in accessibility test coverage

- app/services/id_token_builder.rb
- spec/services/id_token_builder_spec.rb
**Why**: Inject "now" as a dependency so the code can be
tested in a more deterministic way
(I got another test flake in CI)
> Fix another flaky test depending on "now"

- app/models/profile.rb
- lib/feature_management.rb
- spec/models/profile_spec.rb
- spec/services/key_rotator/hmac_fingerprinter_spec.rb
- spec/services/pii/cacher_spec.rb
We confirmed we're OK to store this
> Remove feature flag that guarded compound PII fingerprinting

- docker-compose.yml
- docs/Docker.md
Instructions and configuration for debugging the Rails app in Docker
> Instructions for debugging in Docker Compose

- app/presenters/two_factor_authentication/auth_app_selection_presenter.rb
- app/presenters/two_factor_authentication/phone_selection_presenter.rb
- app/presenters/two_factor_authentication/piv_cac_selection_presenter.rb
- app/presenters/two_factor_authentication/webauthn_selection_presenter.rb
- app/views/devise/sessions/new.html.slim
- config/locales/links/en.yml
- config/locales/links/es.yml
- config/locales/links/fr.yml
- config/locales/titles/en.yml
- config/locales/two_factor_authentication/en.yml
- config/locales/two_factor_authentication/es.yml
- config/locales/two_factor_authentication/fr.yml
- config/locales/user_authorization_confirmation/en.yml
- config/locales/user_authorization_confirmation/es.yml
- config/locales/user_authorization_confirmation/fr.yml
**Why**: Minimizing barrier to entry on IDP
Summary:
- Styling for increased findability of "Create account" flow
- Label change for discoverability of backup codes MFA options
- Copy changes
> **Why**: To eliminate barriers of entry for new users

- app/services/flow/flow_state_machine.rb
- app/services/idv/steps/send_link_step.rb
- config/routes.rb
- spec/features/idv/doc_auth/send_link_step_spec.rb
This is an adaptation of: https://github.com/18F/identity-idp/pull/3701
I cherry-picked the commit, but cause of some docauth v2 stuff, the changes didn't apply cleanly, I think I got them
(cherry picked from commit b8ea29e1a0cd9b0eaabd26321f4d8944d374df1e)
> Staging RC 107.1

- app/services/flow/flow_state_machine.rb
- app/services/idv/steps/send_link_step.rb
- config/routes.rb
- spec/features/idv/doc_auth/send_link_step_spec.rb
This is an adaptation of: #3701
I cherry-picked the commit, but cause of some docauth v2 stuff, the changes didn't apply cleanly, I think I got them
(cherry picked from commit b8ea29e)
> Prod RC 107.1

- app/javascript/app/acuant/document_capture.js
- app/javascript/app/acuant/document_capture_dom.js
- app/javascript/app/acuant/document_capture_fallback.js
- app/javascript/packs/acuant_document_capture.js
- app/views/idv/_acuant_sdk_document_capture_form.html.erb
- config/locales/doc_auth/en.yml
- config/locales/doc_auth/es.yml
- config/locales/doc_auth/fr.yml
- spec/javascripts/app/acuant/document_capture_fallback_spec.js
- spec/javascripts/app/acuant/document_capture_spec.js
- spec/javascripts/support/acuant/document_capture_dom.js
**Why**: So that users who are having trouble with the Acuant SDK upload experience can opt for the file input fallback
**How**: Add a link to show the fallback form that appears on screen after 5 seconds
> LG-2904 Add an Acuant escape hatch

- .circleci/config.yml
Adding support for building the production-grade IDP container when there is a release. Cleaned up whitespacing.
```sh
λ  identity-idp ci/add-release-workflow ✓ git log -n1
commit be6e6056744e70fd2a8c4311041382223bbdf519 (HEAD -> ci/add-release-workflow, origin/ci/add-release-workflow)
Author: Mike Lloyd <mike.lloyd@gsa.gov>
Date:   Wed Apr 22 16:47:45 2020 -0600
added workflow for release.
Signed-off-by: Mike Lloyd <mike.lloyd@gsa.gov>
λ  identity-idp ci/add-release-workflow ✓ circleci config validate
Config file at .circleci/config.yml is valid.
```
Signed-off-by: Mike Lloyd <mike.lloyd@gsa.gov>
> added containerization workflow for release.

- app/javascript/app/acuant/document_capture_dom.js
- app/views/idv/_acuant_sdk_document_capture_form.html.erb
- spec/javascripts/app/acuant/document_capture_spec.js
- spec/javascripts/support/acuant/document_capture_dom.js
**Why**: It is required to show the image capture experience on a mobile phone
> Add the Acaunt image capture canvas

- app/controllers/concerns/idv_session.rb
- app/controllers/concerns/verify_sp_attributes_concern.rb
- app/controllers/idv_controller.rb
- app/controllers/openid_connect/authorization_controller.rb
- app/decorators/service_provider_session_decorator.rb
- app/decorators/session_decorator.rb
- spec/controllers/concerns/verify_sp_attributes_concern_spec.rb
- spec/decorators/service_provider_session_decorator_spec.rb
- spec/decorators/session_decorator_spec.rb
- spec/features/openid_connect/openid_connect_spec.rb
- spec/support/features/idv_helper.rb
- spec/support/features/session_helper.rb
~This is still a draft, I'm trying to sort out the acceptance tests~
*This is ready to go!*
Builds on #3732 adds the `verified_within` param
> LG-2677: Reproof logic

- app/models/null_service_provider.rb
- app/services/idv/steps/doc_auth_base_step.rb
- app/views/accounts/_connected_app.html.erb
- spec/views/accounts/show.html.erb_spec.rb
Patch to fix data with null service provider
> RC 108.2 (Staging)

- app/models/null_service_provider.rb
- app/views/accounts/_connected_app.html.erb
- spec/views/accounts/show.html.erb_spec.rb
Patch to fix data with a null service provider
> RC 108.2 (Prod)

- production.Dockerfile
Bundler needs this to run properly.
> fix bundler config to work for production.Dockerfile

- app/views/shared/_accordion.html.slim
- app/views/users/delete/show.html.slim
- app/views/users/totp_setup/new.html.erb
- spec/views/users/delete/show.html.slim_spec.rb
- spec/views/users/totp_setup/new.html.erb_spec.rb
A smattering of accessibility fixes that a partner found by going through our app
> Various accessibility Fixes

- app/models/null_service_provider.rb
- spec/models/null_service_provider_spec.rb
**Why**: So we don't get any 500s from method missing errors
(Same goal as #3792)
> Make sure NullServiceProvider matches columns on ServiceProvider

- production.Dockerfile
The app gets sad if it can't open log/*.log for writing.
> added log dir until we get the ability to send logs to stdout

- app/services/idv/steps/cac/enter_info_step.rb
- config/application.yml.default
- spec/controllers/idv/cac_controller_spec.rb
- spec/features/idv/cac/choose_method_step_spec.rb
- spec/features/idv/cac/enter_info_step_spec.rb
- spec/features/idv/cac/present_cac_step_spec.rb
- spec/features/idv/cac/success_step_spec.rb
- spec/features/idv/cac/use_cac_step_spec.rb
- spec/features/idv/cac/verify_step_spec.rb
- spec/features/idv/cac/welcome_step_spec.rb
- spec/support/features/cac_proofing_helper.rb
> Staging patch: RC 110.2 - Fix proofing with CAC

- app/services/idv/steps/cac/enter_info_step.rb
- config/application.yml.default
- spec/controllers/idv/cac_controller_spec.rb
- spec/features/idv/cac/choose_method_step_spec.rb
- spec/features/idv/cac/enter_info_step_spec.rb
- spec/features/idv/cac/present_cac_step_spec.rb
- spec/features/idv/cac/success_step_spec.rb
- spec/features/idv/cac/use_cac_step_spec.rb
- spec/features/idv/cac/verify_step_spec.rb
- spec/features/idv/cac/welcome_step_spec.rb
- spec/support/features/cac_proofing_helper.rb
> Prod patch: RC 110.2 - Fix proofing with CAC

- production.Dockerfile
Working towards being able to get the IDP running and configurable in kubernetes.
> add RDS cert bundle for production use

- app/views/shared/_banner.html.erb
- config/locales/shared/en.yml
- config/locales/shared/es.yml
- config/locales/shared/fr.yml
- spec/views/shared/_banner.html.erb_spec.rb
Fixes issue that was reported on Twitter
https://twitter.com/rwcorty/status/1270391772775165956
> Fix HTML escaping of info banner (LG-3098)

- app/controllers/idv/capture_doc_controller.rb
- spec/controllers/idv/capture_doc_controller_spec.rb
- spec/controllers/idv/doc_auth_controller_spec.rb
> LG-3091 Fix liveness not loading in hybrid flow

- app/services/service_provider_request_handler.rb
- spec/features/openid_connect/openid_connect_spec.rb
- spec/support/features/session_helper.rb
* Add test to get back most recent nonce
* Remove early-abort for storing request info
> Deploy RC 111.3 to Staging

- app/services/service_provider_request_handler.rb
- spec/features/openid_connect/openid_connect_spec.rb
- spec/support/features/session_helper.rb
* Add test to get back most recent nonce
* Remove early-abort for storing request info
> Deploy RC 111.3 to Prod

- app/models/service_provider_request.rb
- spec/services/service_provider_request_proxy_spec.rb
(cherry picked from commit d69053637c49abf34546502a09fe6dc20a2e7d10)
> Deploy RC 112.1 to Staging

- app/controllers/concerns/saml_idp_auth_concern.rb
- app/controllers/openid_connect/authorization_controller.rb
- app/forms/openid_connect_authorize_form.rb
- app/services/attribute_asserter.rb
- app/services/ial_context.rb
- app/services/store_sp_metadata_in_session.rb
- spec/forms/openid_connect_authorize_form_spec.rb
- spec/services/attribute_asserter_spec.rb
- spec/services/ial_context_spec.rb
- spec/services/store_sp_metadata_in_session_spec.rb
~WIP branch to run some tests, get early feedback~
This is good to go now
> IAL context cleanup (LG-3106)

- app/views/voice/otp/show.xml.erb
- app/views/voice/otp/show.xml.slim
- spec/controllers/voice/otp_controller_spec.rb
One down! See commits for the test I added to help me make sure I matched things correctly
> XML slim → erb

- app/services/marketing_site.rb
- app/views/users/phone_setup/index.html.erb
- config/locales/two_factor_authentication/en.yml
- config/locales/two_factor_authentication/es.yml
- config/locales/two_factor_authentication/fr.yml
- spec/services/marketing_site_spec.rb
https://cm-jira.usa.gov/browse/LG-2124
**Why**: To comply with Legal and inform users
**How**: Added link to policy page section of marketing site
> Added mobile terms of service to phone setup page

- app/services/idv/flows/doc_auth_flow.rb
- app/services/idv/steps/doc_auth_base_step.rb
- app/services/idv/steps/document_capture_step.rb
- app/services/idv/steps/welcome_step.rb
- app/views/idv/doc_auth/document_capture.html.erb
- config/application.yml.default
- spec/features/idv/doc_auth/document_capture_step_spec.rb
- spec/support/features/doc_auth_helper.rb
**Why**: So we can start working on the combined form and react component on it
> LG-3022: Add a view for the combined document capture step

- .circleci/config.yml
The sample SPs in dev don't work, fixing that here: https://github.com/18F/identity-idp-config/pull/144
Otherwise, this is it! All we need to smoketest dev
> Add smoketest config for dev environment

- .circleci/config.yml
- This will start only after the stages/staging and stages/prod
branches are updated
> Add smoke test config for production

- spec/support/monitor/monitor_email_helper.rb
We had some flakes overnight due to slower SMS, I think this will be more generous. The whole "suite" runs pretty quickly so I think this should be fine
> Update smoke test email check to try a few more times

- app/assets/images/close-white-alt.svg
- app/assets/stylesheets/components/_full-screen.scss
- app/assets/stylesheets/components/all.scss
- app/javascript/app/acuant/document_capture_dom.js
- app/services/idv/steps/back_image_step.rb
- app/services/idv/steps/capture_mobile_back_image_step.rb
- app/services/idv/steps/link_sent_step.rb
- app/services/idv/steps/mobile_back_image_step.rb
- app/services/idv/steps/selfie_step.rb
- app/views/idv/_acuant_sdk_document_capture_form.html.erb
- config/locales/image_description/en.yml
- config/locales/image_description/es.yml
- config/locales/image_description/fr.yml
- spec/features/idv/doc_auth/back_image_step_spec.rb
- spec/features/idv/doc_auth/mobile_back_image_step_spec.rb
- spec/features/idv/doc_auth/selfie_step_spec.rb
- spec/features/idv/doc_capture/mobile_back_image_step_spec.rb
- spec/features/idv/doc_capture/selfie_step_spec.rb
- spec/javascripts/app/acuant/document_capture_spec.js
- spec/javascripts/support/acuant/document_capture_dom.js
This adds 2 commits that IRS needs to test liveness
> Deploy RC 114.1 to staging

- app/views/idv/doc_auth/welcome.html.erb
- spec/views/idv/doc_auth/welcome.html.erb_spec.rb
**Why**: So users can cancel from here and go back to their SP
> Add the correct cancel link to the welcome step

- config/service_providers.localdev.yml
Development version of https://github.com/18F/identity-idp-config/pull/149
> Add dashboard logout URI to redirect_uris

- Gemfile
- Gemfile.lock
- config/boot.rb
- lib/deploy/activate.rb
- spec/lib/deploy/activate_spec.rb
Modeled after https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/20743 to avoid using in production
> Add bootsnap to development and test environments

- Gemfile
- Gemfile.lock
- lib/deploy/activate.rb
- spec/lib/deploy/activate_spec.rb
> Remove fakefs

- app/services/doc_auth_client.rb
- app/services/idv/steps/back_image_step.rb
- app/services/idv/steps/capture_mobile_back_image_step.rb
- app/services/idv/steps/doc_auth_base_step.rb
- app/services/idv/steps/front_image_step.rb
- app/services/idv/steps/link_sent_step.rb
- app/services/idv/steps/mobile_back_image_step.rb
- app/services/idv/steps/mobile_front_image_step.rb
- app/services/idv/steps/selfie_step.rb
**Why**: @ironman5366 introduced this pattern in that PR. It is very helpful for moving to the API. It can stands on its own and cleans things up. I moved the changes to this PR to help decompose that one a bit.
> Import the doc auth client code from #3985

- app/controllers/application_controller.rb
**Why**: We tried adjusting this logic in #4014. We introduced a bug where a user coming from a service provider sees an error message when they are not signed in. This commit reverts to the old logic for the part of the code that introduced that bug.
> Revert logic used to determine if a user should redirect to new session w/ a request ID

- app/views/accounts/_delete_account_item_heading.html.erb
- app/views/accounts/_delete_account_item_heading.html.slim
- app/views/accounts/actions/_delete_action_button.html.erb
- app/views/accounts/actions/_delete_action_button.html.slim
- app/views/forgot_password/_resend_alert.html.erb
- app/views/forgot_password/_resend_alert.html.slim
- app/views/idv/cancel.html.erb
- app/views/idv/cancel.html.slim
- app/views/idv/usps/_address_on_file.html.erb
- app/views/idv/usps/_address_on_file.html.slim
- app/views/shared/_no_pii_banner.html.erb
- app/views/shared/_no_pii_banner.html.slim
- app/views/shared/_password_accordion.html.erb
- app/views/shared/_password_accordion.html.slim
- app/views/sign_up/registrations/_registration_heading.html.erb
- app/views/sign_up/registrations/_registration_heading.html.slim
- app/views/two_factor_authentication/totp_verification/_reauthn.html.erb
- app/views/two_factor_authentication/totp_verification/_reauthn.html.slim
- app/views/user_mailer/doc_auth_desktop_link_to_sp.html.erb
- app/views/user_mailer/doc_auth_desktop_link_to_sp.html.slim
Should be all of the 0, 1 and 2 line templates and a few others
> Convert short slim templates to erb

- .eslintrc
- app/javascript/packages/document-capture/components/acuant-capture.jsx
- app/javascript/packages/document-capture/components/document-capture.jsx
- app/javascript/packages/document-capture/components/file-input.jsx
- app/javascript/packages/document-capture/components/form-steps.jsx
- app/javascript/packages/document-capture/components/full-screen.jsx
- app/javascript/packages/document-capture/components/selfie-step.jsx
- app/javascript/packages/document-capture/components/submission-pending.jsx
- app/javascript/packages/document-capture/components/suspense-error-boundary.jsx
- app/javascript/packages/document-capture/context/acuant.jsx
- app/javascript/packages/document-capture/hooks/use-history-param.js
- package.json
- tsconfig.json
- yarn.lock
**Why**: To avoid errors which can occur when attempting to access `null` properties, and to provide better guarantees that the types we're working with are the types we're expecting.
Previously: https://github.com/18F/identity-idp/pull/4057#issuecomment-673531235
> Configure TypeScript strict null checking

- app/services/idv/data_url_image.rb
Incorporating review feedback from @esparta in https://github.com/18F/identity-idp/pull/4074#discussion_r470877541
> Clean up regex matching to use predicate method

- Gemfile
- Gemfile.lock
This update to the LN gem incorporates changes made to the LN gem for both LG-3280 and LG-3289 by @amathews-fs and @mitchellhenke.
> LG-3280 Update LN gem to latest version.

- db/migrate/20200821173230_add_occurred_at_to_security_events.rb
Whoopsidoodle --- surprised CI didn't catch this 🙈  ... see #4106
> Add missing DB migration from #4106

- spec/features/saml/saml_spec.rb
Feel free to merge at any time
> fixing test text that was swapped

- config/locales/errors/en.yml
- config/locales/errors/es.yml
- config/locales/errors/fr.yml
**Why**: Plain language
See: https://github.com/18F/identity-idp/pull/4122
> Rephrase Acuant error message "initialize" to "start"

- db/migrate/20200828162147_remove_redundant_indices.rb
- db/schema.rb
Cleaning up old branches, and forgot I had done this (follow up to #3966)
> Remove redundant database indices

- app/views/idv/doc_auth/welcome.html.erb
- config/locales/doc_auth/en.yml
- config/locales/doc_auth/es.yml
- config/locales/doc_auth/fr.yml
- spec/views/idv/doc_auth/welcome.html.erb_spec.rb
> LG-3266 Update doc auth to conditionally include selfie instructions

- app/services/doc_auth/acuant/responses/get_results_response.rb
- spec/services/doc_auth/acuant/responses/get_results_response_spec.rb
I got this to happen by covering my ID's barcode with a few layers of tape and got this response from the Acuant sandbox
> Update Acuant code to pass "attention" results with blurry barcode (LG-3368)

- app/presenters/two_factor_options_presenter.rb
- app/views/users/two_factor_authentication_setup/index.html.erb
- config/locales/two_factor_authentication/en.yml
- config/locales/two_factor_authentication/es.yml
- config/locales/two_factor_authentication/fr.yml
Received "official" translations for a couple of keys related to the "Need additional authentication page".
> Updated two factor locale translations to es/fr (LG-3162)

- app/assets/stylesheets/components/_nav.scss
- app/views/layouts/account_side_nav.html.erb
> update new account page banner with mobile design changes

- app/services/maintenance_window.rb
- app/views/devise/sessions/new.html.erb
- app/views/idv/cac/choose_method.html.erb
- app/views/idv/doc_auth/welcome.html.erb
- app/views/shared/_alert.html.erb
- app/views/shared/_maintenance_window_alert.html.erb
- config/application.yml.default
- config/locales/notices/en.yml
- config/locales/notices/es.yml
- config/locales/notices/fr.yml
- config/locales/time/en.yml
- config/locales/time/es.yml
- config/locales/time/fr.yml
- spec/features/idv/doc_auth/welcome_step_spec.rb
- spec/services/maintenance_window_spec.rb
- spec/views/devise/sessions/new.html.erb_spec.rb
- spec/views/idv/doc_auth/welcome.html.erb_spec.rb
- spec/views/shared/_alert.html.erb_spec.rb
- spec/views/shared/_maintenance_window_alert.html.erb_spec.rb
Patches maintenance window notification for Acuant (LG-3451) (#4202) to staging
> Deploy RC 118.1 to Staging

- app/services/maintenance_window.rb
- app/views/devise/sessions/new.html.erb
- app/views/idv/cac/choose_method.html.erb
- app/views/idv/doc_auth/welcome.html.erb
- app/views/shared/_alert.html.erb
- app/views/shared/_maintenance_window_alert.html.erb
- config/application.yml.default
- config/locales/notices/en.yml
- config/locales/notices/es.yml
- config/locales/notices/fr.yml
- config/locales/time/en.yml
- config/locales/time/es.yml
- config/locales/time/fr.yml
- spec/features/idv/doc_auth/welcome_step_spec.rb
- spec/services/maintenance_window_spec.rb
- spec/views/devise/sessions/new.html.erb_spec.rb
- spec/views/idv/doc_auth/welcome.html.erb_spec.rb
- spec/views/shared/_alert.html.erb_spec.rb
- spec/views/shared/_maintenance_window_alert.html.erb_spec.rb
Patches maintenance window notification for Acuant (LG-3451) (#4202) to prod
> Deploy RC 118.1 to Prod

- app/javascript/app/form-validation.js
**Why**: The markup which had relied on this code has been removed, and the associated JavaScript is no longer relevant.
Added in 46b8bdd2b0cfbaa3c5c59cabf548cd5627fa89e9. Removed in 512c836a6b30da648b957f241940b3da3617ef3a (#3187, cc @stevegsa).
Via `git log -Gif-checked`
> LG-3339: Remove unused "if checked" JavaScript form validation

- spec/features/monitor/create_account_spec.rb
- spec/support/monitor/monitor_idv_steps.rb
Smoke test has been failing, this will cut down on noise
> Fix failing smoke test on INT

- app/views/shared/_dap_analytics.html.erb
Per https://gsa-tts.slack.com/archives/C5AUR5XUK/p1601392684044100
> Add TTS as DAP subagency

- app/jobs/vendor_proof_job.rb
- app/models/document_capture_session.rb
- app/services/doc_auth/mock/doc_auth_mock_client.rb
- app/services/document_capture_session_result.rb
- app/services/encrypted_redis_struct_storage.rb
- app/services/flow/base_flow.rb
- app/services/flow/base_step.rb
- app/services/flow/flow_state_machine.rb
- app/services/idv/flows/doc_auth_flow.rb
- app/services/idv/session.rb
- app/services/idv/steps/verify_base_step.rb
- app/services/idv/steps/verify_step.rb
- app/services/idv/steps/verify_wait_step.rb
- app/services/idv/steps/verify_wait_step_show.rb
- app/services/proofing_document_capture_session_result.rb
- app/views/idv/doc_auth/verify_wait.html.erb
- config/application.yml.default
- spec/models/document_capture_session_spec.rb
- spec/services/document_capture_session_result_spec.rb
- spec/services/encrypted_redis_struct_storage_spec.rb
- spec/services/proofing_document_capture_session_result_spec.rb
**How**: Add optional show steps to flow state machine for doc auth, async, etc.
> LG-3274 Make resolution proofing calls async

- config/application.yml.default
**Why**: That will be the default in all envs up to production soon.
> Make the document capture step enabled by default

- app/services/db/proofing_cost/add_user_proofing_cost.rb
- package.json
- spec/services/db/add_document_verification_and_selfie_costs_spec.rb
- yarn.lock
To get fixes from https://github.com/18F/identity-idp/pull/4287
> Update RC 120 in Staging

- Gemfile.lock
- app/services/lambda_jobs/git_ref.rb
**Why**: Removes eager ENV.fetch that caused issues for
inline job execution
> Bump identity-idp-functions

- Gemfile.lock
- app/services/lambda_jobs/git_ref.rb
> Update RC 121 in Staging

- app/services/phone_number_capabilities.rb
I was in this area of the code for some upcoming tickets and this seemed simple enough to just make its own PR
> Use a key lookup for phone capabilities

- app/services/idv/steps/cac/verify_wait_step_show.rb
- app/services/idv/steps/recover_verify_wait_step_show.rb
- app/services/idv/steps/verify_wait_step_show.rb
I found an issue where a user may not be able to resubmit to try again after failing
> Always delete async after done

- .gitignore
- config/locales/account/es.yml
- config/locales/account/fr.yml
- config/locales/cac_proofing/fr.yml
- config/locales/doc_auth/en.yml
- config/locales/doc_auth/es.yml
- config/locales/doc_auth/fr.yml
- config/locales/errors/es.yml
- config/locales/errors/fr.yml
- config/locales/forms/es.yml
- config/locales/forms/fr.yml
- config/locales/headings/es.yml
- config/locales/headings/fr.yml
- config/locales/help_text/es.yml
- config/locales/help_text/fr.yml
- config/locales/idv/es.yml
- config/locales/instructions/en.yml
- config/locales/instructions/es.yml
- config/locales/instructions/fr.yml
- config/locales/two_factor_authentication/en.yml
- config/locales/two_factor_authentication/es.yml
- config/locales/two_factor_authentication/fr.yml
- config/locales/user_authorization_confirmation/es.yml
- config/locales/user_authorization_confirmation/fr.yml
- spec/support/features/session_helper.rb
Translations made per the following spreadsheet: https://docs.google.com/spreadsheets/d/1PHrXSH47IGcm0g2UwKHGye__dUAiY34R3Vjdc27Y1vQ/edit#gid=0
> Updated translations for AAL3 and IAL2 (LG-3617)

- .eslintrc
- app/javascript/packages/document-capture/components/document-capture.jsx
- app/javascript/packages/document-capture/components/form-steps.jsx
- app/javascript/packages/document-capture/components/prompt-on-navigate.jsx
- spec/javascripts/packages/document-capture/components/document-capture-spec.jsx
- spec/javascripts/packages/document-capture/components/form-steps-spec.jsx
- spec/javascripts/packages/document-capture/components/prompt-on-navigate-spec.jsx
**Why**: As a user that tries to refresh or go back during document capture, I want a warning that I will lose work when refreshing and need to re-upload documents.
> LG-3613: Show a warning when user refreshes or uses back button during document capture

- config/locales/errors/en.yml
- config/locales/errors/es.yml
- config/locales/errors/fr.yml
- config/locales/friendly_errors/en.yml
- config/locales/friendly_errors/es.yml
- config/locales/friendly_errors/fr.yml
https://docs.google.com/spreadsheets/d/1PHrXSH47IGcm0g2UwKHGye__dUAiY34R3Vjdc27Y1vQ/edit#gid=0
> <NO CHANGELOG> came to consensus on a few more translations (LG-3617)

- app/views/sign_up/registrations/new.html.erb
Re: https://github.com/18F/identity-idp/pull/4365#discussion_r518937459
> Move email error closer to email field

- Gemfile
- Gemfile.lock
- app/services/doc_auth_router.rb
- spec/services/doc_auth_router_spec.rb
See https://github.com/18F/identity-doc-auth/pull/4
> Update identity-doc-auth to remove i18n dependency (LG-3728)

- Gemfile.lock
- app/services/lambda_jobs/git_ref.rb
See https://github.com/18F/identity-idp-functions/pull/31
> Update identity-idp-functions to resolve ActiveSupport errors

- spec/support/monitor/monitor_helper.rb
Adding https://github.com/18F/identity-idp/pull/4420 to staging
> Staging RC 123 patch: fix smoke tests

- db/migrate/20201118115231_add_document_capture_step_to_doc_auth_logs.rb
See: https://github.com/18F/identity-idp/commit/09e0ae2e48934e8674d40cb931d71d8fd7b98deb#r44314623
Fixes migration error:
```
NameError: uninitialized constant AddDocumentCaptureStepToDocAuthLogs
```
> Name AddDocumentCaptureStepToDocAuthLogs according to file name

- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/idv/phone_controller.rb
- app/controllers/idv/usps_controller.rb
- app/services/flow/base_step.rb
- app/services/idv/agent.rb
- app/services/idv/phone_step.rb
- app/services/idv/steps/cac/verify_step.rb
- app/services/idv/steps/recover_verify_step.rb
- app/services/idv/steps/verify_step.rb
- app/services/lambda_jobs/git_ref.rb
- spec/controllers/lambda_callback/address_proof_result_controller_spec.rb
- spec/controllers/lambda_callback/resolution_proof_result_controller_spec.rb
- spec/features/idv/doc_auth/verify_step_spec.rb
- spec/services/idv/agent_spec.rb
- spec/services/idv/phone_step_spec.rb
- spec/services/idv/steps/verify_step_spec.rb
- spec/support/identity_idp_functions.rb
> Update identity-idp-functions, pass X-Amzn-Trace-Id header for tracing

- app/javascript/packages/document-capture/components/acuant-capture.jsx
- app/javascript/packages/document-capture/context/analytics.jsx
- app/javascript/packages/document-capture/context/upload.jsx
- app/javascript/packages/document-capture/higher-order/with-background-encrypted-upload.jsx
- app/javascript/packages/document-capture/index.js
- app/javascript/packs/document-capture.jsx
- spec/javascripts/packages/document-capture/components/acuant-capture-spec.jsx
- spec/javascripts/packages/document-capture/components/document-capture-spec.jsx
- spec/javascripts/packages/document-capture/components/selfie-step-spec.jsx
- spec/javascripts/packages/document-capture/higher-order/with-background-encrypted-upload-spec.jsx
- tsconfig.json
**Why**: As a user, I want a smooth experience and the ability of the login team to identify when I have issues, so that the experience can continue to improve.
Includes a bit of code reorganization, described in commit messages. Pardon the noise!
> LG-3736: Log async upload attempts from client

- app/controllers/concerns/two_factor_authenticatable.rb
This should have been removed in #4456
> remove unused method

- app/decorators/service_provider_session_decorator.rb
- spec/decorators/service_provider_session_decorator_spec.rb
- spec/factories/service_providers.rb
Potentially introduced by #4418 ?
> do not show alert if sp help text is a blank string

- config/country_dialing_codes.yml
re-enables SMS for countries where it was disabled (#4424, #4430)
> re-enable SMS in countries where it was disabled

- lib/tasks/data_requests.rake
**Why**: Because it is preventing me from running the data request rake tasks correctly
> Fix a typo

- app/services/usps_in_person_proofer.rb
> use keyword init for USPS IPP struct

- config/locales/account/en.yml
- config/locales/account/es.yml
- config/locales/account/fr.yml
- config/locales/headings/en.yml
- config/locales/headings/es.yml
- config/locales/headings/fr.yml
> LG-3511 MFA devices prominence in MyAccount

- app/controllers/frontend_log_controller.rb
Forgot to add this but discovered it when testing locally.
> skip verify_authenticity_token (LG-3975)

- app/javascript/packages/document-capture/components/acuant-capture.jsx
- app/javascript/packages/document-capture/context/analytics.jsx
- app/javascript/packages/document-capture/higher-order/with-background-encrypted-upload.jsx
- app/javascript/packs/document-capture.jsx
- app/views/idv/shared/_document_capture.html.erb
- spec/javascripts/packages/document-capture/components/acuant-capture-spec.jsx
- spec/javascripts/packages/document-capture/higher-order/with-background-encrypted-upload-spec.jsx
Cherry-picks e9d66f6 from #4581 to `stages/prod`.
> LG-4040: Log doc auth events to event.log (#4581)

- app/controllers/concerns/saml_idp_auth_concern.rb
- app/controllers/openid_connect/authorization_controller.rb
- app/controllers/users/service_provider_inactive_controller.rb
- app/forms/openid_connect_authorize_form.rb
- app/models/service_provider.rb
- app/services/analytics.rb
- app/services/saml_request_validator.rb
- app/views/users/service_provider_inactive/index.html.erb
- config/locales/service_providers/en.yml
- config/locales/service_providers/es.yml
- config/locales/service_providers/fr.yml
- config/routes.rb
- config/service_providers.localdev.yml
- spec/controllers/saml_idp_controller_spec.rb
- spec/features/openid_connect/redirect_uri_validation_spec.rb
- spec/support/saml_auth_helper.rb
...supported both through SAML and OIDC.
> LG-3951 Added friendly error page for inactive SPs 

- Gemfile.lock
- lib/lambda_jobs/git_ref.rb
See: https://github.com/18F/identity-idp-functions/pull/56
> Update lambda ref to get x-ray tracing functionality (LG-4045)

- Gemfile
- Gemfile.lock
Follow-up to https://github.com/18F/identity-lexisnexis-api-client-gem/pull/21
Luckily since in staging we don't have lambda enabled, this should log right in the IDP for us
> Bump lexisnexis gem for some additional logging

- app/javascript/packages/document-capture/components/acuant-capture.jsx
- app/javascript/packages/document-capture/components/documents-step.jsx
- app/javascript/packages/document-capture/components/review-issues-step.jsx
- app/javascript/packages/document-capture/components/selfie-step.jsx
- package.json
- spec/javascripts/packages/document-capture/components/acuant-capture-spec.jsx
- spec/javascripts/spec_helper.js
- yarn.lock
**Why**: To give us insight to more detail of the actual metrics the AcuantSDK is providing to allow us to tune the front end failure threshold.
> LG-4107: Log additional metrics for Acuant Web SDK result

- app/assets/stylesheets/components/_background.scss
- app/views/idv/doc_auth/verify.html.erb
- spec/features/idv/doc_auth/verify_step_spec.rb
> LG-3957 Add ability for user to unmask SSN on verify step

- app/models/agreements/iaa_gtc.rb
- app/models/agreements/iaa_order.rb
- app/models/agreements/iaa_status.rb
- app/models/agreements/integration.rb
- app/models/agreements/integration_status.rb
- app/models/agreements/integration_usage.rb
- app/models/agreements/partner_account.rb
- app/models/agreements/partner_account_status.rb
- db/migrate/20210203002937_add_partnerships_data.rb
- db/schema.rb
- spec/factories/agreements.rb
- spec/models/agreements/iaa_gtc_spec.rb
- spec/models/agreements/iaa_order_spec.rb
- spec/models/agreements/iaa_status_spec.rb
- spec/models/agreements/integration_spec.rb
- spec/models/agreements/integration_status_spec.rb
- spec/models/agreements/integration_usage_spec.rb
- spec/models/agreements/partner_account_spec.rb
- spec/models/agreements/partner_account_status_spec.rb
Resolves LG-3973
Adds migration and models/specs for Partnerships data.
> [LG-3973] Add Partnerships data models

- README.md
- spec/support/capybara.rb
Added this to help me debug some specs
> Add SHOW_BROWSER environment variable for acceptance specs

- app/javascript/packs/ial2-consent-button.js
- app/views/idv/doc_auth/welcome.html.erb
- spec/support/shared_examples/ial2_consent.rb
> LG-3946 Continue button is disabled (not greyed) on first consent screen

- app/controllers/idv/cancellations_controller.rb
- app/helpers/go_back_helper.rb
- app/presenters/idv/usps_presenter.rb
- app/services/idv/actions/cancel_link_sent_action.rb
- app/services/idv/actions/cancel_send_link_action.rb
- app/services/idv/flows/doc_auth_flow.rb
- app/views/idv/address/new.html.erb
- app/views/idv/doc_auth/_back.html.erb
- app/views/idv/doc_auth/link_sent.html.erb
- app/views/idv/doc_auth/send_link.html.erb
- app/views/idv/usps/index.html.erb
- spec/features/idv/actions/cancel_link_sent_action_spec.rb
- spec/features/idv/actions/cancel_send_link_action_spec.rb
- spec/features/idv/clearing_and_restarting_spec.rb
- spec/features/idv/doc_auth/address_step_spec.rb
- spec/features/idv/doc_auth/link_sent_step_spec.rb
- spec/features/idv/doc_auth/send_link_step_spec.rb
- spec/features/idv/steps/phone_otp_delivery_selection_step_spec.rb
- spec/features/idv/steps/phone_step_spec.rb
- spec/features/idv/steps/usps_step_spec.rb
- spec/helpers/go_back_helper_spec.rb
- spec/presenters/idv/usps_presenter_spec.rb
- spec/support/features/doc_auth_helper.rb
- spec/views/idv/doc_auth/_back.html.erb_spec.rb
- spec/views/idv/usps/index.html.erb_spec.rb
**Why**: As an end user, I want a Back button on the page so that I can easily change my mind about taking an action.
Adds back button to the following screens:
- "Take a photo with a phone" (`send_link` step)
- Navigates to "How would you like to verify your identity?" (`upload` step)
- "We sent a message to your phone" (`link_sent` step)
- Navigates to "How would you like to verify your identity?" (`upload` step)
- "Mailing Address"
- Navigates to "Please verify your information" (`verify` step)
- "Want a letter?"
- Navigates to "Enter a phone number with your name on the plan"
- The pending variant of this "Want another letter?" will navigate back to the OTP confirmation screen "Enter the ten-character code in the letter we sent you"
See original ticket for more detail, including Figma …
> LG-3838: Add "Back" links to IAL2 branch pages

- app/presenters/cancellation_presenter.rb
- app/views/account_reset/confirm_delete_account/show.html.erb
- app/views/account_reset/delete_account/show.html.erb
- app/views/users/delete/show.html.erb
- config/locales/account_reset/en.yml
- config/locales/account_reset/es.yml
- config/locales/account_reset/fr.yml
- config/locales/user_mailer/en.yml
- config/locales/user_mailer/es.yml
- config/locales/user_mailer/fr.yml
- config/locales/users/en.yml
- config/locales/users/es.yml
- config/locales/users/fr.yml
- spec/mailers/user_mailer_spec.rb
- spec/views/users/delete/show.html.erb_spec.rb
> LG-3853 Add consent to transmit UUID verbiage to delete account

- config/initializers/saml_idp.rb
- spec/controllers/saml_idp_controller_spec.rb
Requested by a partner - not sure if there are any concerns!
> Update org info in SAML metadata

- Gemfile
- Gemfile.lock
- app/services/db/sp_cost/add_sp_cost.rb
- app/services/idv/steps/doc_auth_base_step.rb
- app/services/idv/steps/verify_base_step.rb
- db/migrate/20210223232534_add_transaction_id_to_sp_costs.rb
- db/schema.rb
- lib/lambda_jobs/git_ref.rb
- spec/features/sp_cost_tracking_spec.rb
- spec/services/idv/agent_spec.rb
Depends on:
- https://github.com/18F/identity-aamva-api-client-gem/pull/35
- https://github.com/18F/identity-idp-functions/pull/60
> Add sp_costs.transaction_id, populate it for vendors (LG-4257)
