Gemfile, Gemfile.lock
Include changes from https://github.com/18F/identity-aamva-api-client-gem/pull/36
=> Update AAMVA for better transaction id logging

app/services/encrypted_redis_struct_storage.rb, spec/services/encrypted_redis_struct_storage_spec.rb
A funky error from a vendor resulted in this [NewRelic Exception](https://one.newrelic.com/launcher/nr1-core.explorer?pane=eyJiYXJjaGFydCI6ImJhcmNoYXJ0IiwidG9wRmFjZXQiOiJ0cmFuc2FjdGlvblVpTmFtZSIsInBhZ2UiOiJzaG93IiwicHJpbWFyeUZhY2V0IjoiZXJyb3IuY2xhc3MiLCJ0cmFjZUlkIjoiNWFlN2EzMGItN2I4ZS0xMWViLWJiY2EtMDI0MmFjMTEwMDA5XzE2ODIyXzM1NjQ2IiwibmVyZGxldElkIjoiZXJyb3JzLXVpLm92ZXJ2aWV3IiwiZW50aXR5SWQiOiJNVE0zTmpNM01IeEJVRTE4UVZCUVRFbERRVlJKVDA1OE5USTBORFk1T0RZIn0=&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5SWQiOiJNVE0zTmpNM01IeEJVRTE4UVZCUVRFbERRVlJKVDA1OE5USTBORFk1T0RZIiwic2VsZWN0ZWROZXJkbGV0Ijp7Im5lcmRsZXRJZCI6ImVycm9ycy11aS5vdmVydmlldyJ9fQ==&platform[accountId]=1376370&platform[timeRange][duration]=1800000) when trying to store data
=> Make sure data is UTF-8 encoded before encrypting and storing

lib/deploy/activate.rb
Resolves LG-3974
Thought this was in the devops repo, otherwise would have done this in the other PR, whoops!
**NOTE:** I couldn't find tests for the symlinking and couldn't think of a reasonably clean way to test this so I'm going to test this in my personal sandbox.
=> [LG-3974 part 2] Update deploy/active to copy in additional YAML files

Gemfile.lock, lib/lambda_jobs/git_ref.rb
Includes some updates to identity-doc-auth from https://github.com/18F/identity-idp-functions/pull/61
=> update lambda version

db/migrate/20210303182041_validate_add_null_constraint_to_agencies_abbreviation.rb
Apparently the migration in #4744 wasn't working for everyone 😢.
=> Ensure migration passes strong_migrations

spec/support/saml_response_doc.rb
Resolves LG-4324
Thanks @zachmargolis! (based on [this comment](https://github.com/18F/identity-idp/pull/4752#pullrequestreview-605619413))
=> [LG-4324] Refactor SAML Response Doc test helper

Gemfile, Gemfile.lock, app/services/idv/agent.rb, app/services/lambda_jobs/runner.rb, lib/lambda_jobs/git_ref.rb, spec/services/lambda_jobs/runner_spec.rb
see https://github.com/18F/identity-idp-functions/pull/63/files and https://github.com/18F/identity-aamva-api-client-gem/pull/37
=> Pass explicit config to AAMVA gem

app/presenters/openid_connect_user_info_presenter.rb, app/services/attribute_asserter.rb, spec/presenters/openid_connect_user_info_presenter_spec.rb, spec/services/attribute_asserter_spec.rb
Similar to https://github.com/18F/identity-idp/pull/4771
=> Limit zipcode to 5 digits

app/controllers/idv/capture_doc_status_controller.rb, app/services/idv/actions/cancel_capture_doc_action.rb, app/services/idv/flows/capture_doc_flow.rb, app/services/idv/steps/link_sent_step.rb, app/services/idv/steps/send_link_step.rb, app/views/idv/doc_auth/_start_over.html.erb, app/views/idv/doc_auth/_start_over_or_cancel.html.erb, app/views/idv/shared/_document_capture.html.erb, config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml, db/migrate/20210302110431_add_cancelled_at_to_document_capture_sessions.rb, db/schema.rb, spec/controllers/idv/capture_doc_status_controller_spec.rb, spec/features/idv/actions/cancel_doc_capture_action_spec.rb
=> LG-4130 Improve exception case handling for hybrid doc auth flow

.circleci/config.yml, README.md, app/assets/images/sp-logos/README.md
**Why**: Everything should be building off of the main branch now
=> Remove straggling "master" references

app/helpers/form_helper.rb, app/javascript/app/phone-internationalization.js, spec/features/phone/add_phone_spec.rb, tsconfig.json
| --- | --- |
|  <img width="571" alt="Screen Shot 2021-03-10 at 1 31 52 PM" src="https://user-images.githubusercontent.com/458784/110702858-e9fb1580-81a7-11eb-87e8-c198bffe86f5.png"> | <img width="585" alt="Screen Shot 2021-03-10 at 1 37 20 PM" src="https://user-images.githubusercontent.com/458784/110702875-eebfc980-81a7-11eb-8a1c-d336e2e55eac.png"> |
=> Fix phone dropdown, make sure it disables options correctly (LG-4144)

Gemfile, Gemfile.lock
See: https://github.com/18F/identity-lexisnexis-api-client-gem/pull/26
=> Update LexisNexis gem for partial DOB logging

app/services/agreements/base_seeder.rb, app/services/agreements/iaa_order_seeder.rb, spec/fixtures/bad/partner_account_statuses.yml, spec/fixtures/bad/partner_accounts.yml, spec/services/agreements/iaa_gtc_seeder_spec.rb, spec/services/agreements/iaa_order_seeder_spec.rb, spec/services/agreements/iaa_status_seeder_spec.rb, spec/services/agreements/integration_seeder_spec.rb, spec/services/agreements/integration_status_seeder_spec.rb, spec/services/agreements/partner_account_seeder_spec.rb, spec/services/agreements/partner_account_status_seeder_spec.rb
Also fixed a consistent set of typos in the test labels 🤦.
=> Improve error handling in Agreements seeders

spec/lib/deploy/activate_spec.rb
These comments were resolved but not addressed in https://github.com/18F/identity-idp/pull/4797#discussion_r593404062
=> Fix typos in spec description

app/forms/openid_connect_authorize_form.rb, app/models/concerns/deprecated_user_attributes.rb, app/models/service_provider.rb, app/services/db/service_provider_quota_limit/notify_if_any_sp_over_quota_limit.rb, app/services/identity_config.rb, app/services/reports/base_report.rb, app/services/saml_endpoint.rb, config/initializers/rack_attack.rb, lib/feature_management.rb, lib/job_runner/runner.rb, lib/saml_idp_constants.rb, spec/controllers/service_provider_controller_spec.rb, spec/features/saml/saml_spec.rb, spec/forms/openid_connect_authorize_form_spec.rb, spec/lib/feature_management_spec.rb, spec/models/service_provider_spec.rb, spec/services/usps_confirmation_uploader_spec.rb
- Updates boolean, JSON conversions at callsites too (`.to_i` will be fine on its own)
- Also add "options" to converters, use it for JSON options
=> Config: Add types to some configs

Gemfile, Gemfile.lock
see: https://github.com/18F/identity-lexisnexis-api-client-gem/pull/27
=> Update lexisnexis gem to have better timeout settings

Gemfile.lock, lib/lambda_jobs/git_ref.rb
**Why**: To correctly pass in timeout configs
---
See https://github.com/18F/identity-idp-functions/pull/65
=> Update identity-idp-functions for LexisNexis timeouts

Gemfile.lock, lib/lambda_jobs/git_ref.rb
see: https://github.com/18F/identity-idp-functions/pull/67
just like #4822 but for the other job 😭
=> Update identity-idp-functions to get more timeout fixes

app/controllers/users/verify_account_controller.rb, app/models/throttle.rb, app/views/users/verify_account/throttled.html.erb, config/application.yml.default, config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml, spec/controllers/users/verify_account_controller_spec.rb
Similar to #4820, but for entering GPO keys for verification
=> Rate limit GPO key attempts (LG-4383)

config/application.yml.default, config/initializers/telephony.rb
All environments now use the new JSON format that supports multiple configs, so we can drop the old one.
=> simplify pinpoint config

config/newrelic.yml
Copies changes from https://github.com/18F/identity-devops/pull/3215
=> include MimeType error in ignored errors in newrelic.yml

config/initializers/job_configurations.rb
=> Fix typo from #4837

app/mailers/user_mailer.rb, app/models/service_provider.rb, app/services/db/service_provider_quota_limit/notify_if_any_sp_over_quota_limit.rb, app/services/encryption/encryptors/attribute_encryptor.rb, app/services/encryption/multi_region_kms_client.rb, app/services/event_disavowal/find_disavowed_event.rb, app/services/funnel/doc_auth/register_campaign.rb, app/services/idv/duplicate_ssn_finder.rb, app/services/idv/steps/verify_base_step.rb, app/services/key_rotator/utils.rb, app/services/pii/fingerprinter.rb, app/services/reports/deleted_user_accounts_report.rb, app/services/saml_endpoint.rb, config/application.rb, config/application.yml.default, config/initializers/app_config.rb, lib/identity_config.rb, lib/job_runner/runner.rb, lib/saml_idp_constants.rb, spec/features/idv/doc_auth/verify_step_spec.rb, spec/models/service_provider_spec.rb, spec/services/encryption/encryptors/attribute_encryptor_spec.rb, spec/services/encryption/kms_client_spec.rb, spec/services/encryption/multi_region_kms_client_spec.rb, spec/services/pii/fingerprinter_spec.rb, spec/services/reports/deleted_user_accounts_report_spec.rb, spec/support/key_rotation_helper.rb
Discussed new strategy with @jmhooper on migrating configuration keys over in groups instead of all at once, and this is the first pass.
=> Configuration type checks

config/locales/errors/es.yml, config/locales/errors/fr.yml, config/locales/two_factor_authentication/en.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml
Updated translations from the [spreadsheet](https://docs.google.com/spreadsheets/d/1PHrXSH47IGcm0g2UwKHGye__dUAiY34R3Vjdc27Y1vQ/edit#gid=0).
=> LG-4052: updated translations

Procfile
**Why**: So these processes will run in local dev
=> Add a worker and job_runs process to the Procfile

app/controllers/concerns/verify_sp_attributes_concern.rb, spec/controllers/concerns/verify_sp_attributes_concern_spec.rb
**Why**: Underlying issue was likely a timed out session
but at least this will be more graceful in the future
[NewRelic Link](https://one.newrelic.com/launcher/nr1-core.explorer?platform[accountId]=1376370&platform[timeRange][duration]=604800000&pane=eyJiYXJjaGFydCI6ImJhcmNoYXJ0IiwidG9wRmFjZXQiOiJ0cmFuc2FjdGlvblVpTmFtZSIsInBhZ2UiOiJzaG93IiwicHJpbWFyeUZhY2V0IjoiZXJyb3IuY2xhc3MiLCJ0cmFjZUlkIjoiNzU1OTUyYjAtOThhOS0xMWViLWExOGItMDI0MmFjMTEwMDA4XzBfMTY3ODciLCJmaWx0ZXJzIjpbeyJrZXkiOiJlcnJvci5leHBlY3RlZCIsInZhbHVlIjoibm90IHRydWUifSx7ImtleSI6ImVycm9yLmNsYXNzIiwidmFsdWUiOiJOb01ldGhvZEVycm9yIiwibGlrZSI6ZmFsc2V9XSwibmVyZGxldElkIjoiZXJyb3JzLXVpLm92ZXJ2aWV3IiwiZW50aXR5SWQiOiJNVE0zTmpNM01IeEJVRTE4UVZCUVRFbERRVlJKVDA1OE5USXhNelk0TlRnIn0&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5SWQi …
=> Handle nil sp_session[:requested_attributes]

app/views/two_factor_authentication/totp_verification/show.html.erb
=> Translate TOTP MFA sign-in submit button

app/controllers/test/push_notification_controller.rb, app/services/push_notification/http_push.rb, app/services/push_notification/local_event_queue.rb, app/views/test/push_notification/index.html.erb, config/application.yml.default, config/routes.rb, lib/identity_config.rb, spec/controllers/test/push_notification_controller_spec.rb, spec/rails_helper.rb
Created while trying to figure out the issue in #4917 
Borrowed heavily from the `/test/telephony` route and template
=> Add test push notification queue

app/controllers/concerns/effective_user.rb, spec/controllers/concerns/effective_user_spec.rb
save ourselves a (fast) query if we can 🙂
=> do not query for user if it is already present in effective_user_id

app/assets/stylesheets/components/_block-link.scss, app/assets/stylesheets/components/_troubleshooting-options.scss, app/assets/stylesheets/components/all.scss, app/javascript/packages/document-capture/components/documents-step.jsx, app/javascript/packages/document-capture/components/review-issues-step.jsx, app/views/idv/doc_auth/no_camera.html.erb, app/views/idv/doc_auth/upload.html.erb, app/views/idv/doc_auth/welcome.html.erb, app/views/idv/shared/_document_capture.html.erb, app/views/shared/_troubleshooting_options.html.erb, config/js_locale_strings.yml, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml, spec/views/idv/doc_auth/upload.html.erb_spec.rb, spec/views/idv/doc_auth/welcome.html.erb_spec.rb, spec/views/shared/_troubleshooting_options.html.erb_spec.rb
**Why**: As an end user, if I don't have the required information to complete identity verification, I want to clearly understand what my options are as soon as possible, so that I can get help or try something else.
This is the first of two pull requests for LG-4370 "Troubleshooting Component" ticket. It includes the implementation of the component, and text updates to migrate texts for help regarding worn or non-existent IDs to the first step. The second pull request will update IAL2 warning and error pages to use the troubleshooting component.
Location|Before|After
---|---|---
Welcome (Desktop)|![welcome-desktop-before](https://user-images.githubusercontent.com/1779930/115600900-293e7b00-a2ab-11eb-9c56-a0d5bcd75a04.png)|![welcome-desktop-after](https://user-images.githu …
=> LG-4370: Move IAL2 ID requirements troubleshooting to first step

app/forms/idv/api_document_verification_form.rb, app/forms/idv/api_image_upload_form.rb, app/services/idv/steps/doc_auth_base_step.rb, app/views/idv/session_errors/_throttled.html.erb, app/views/idv/session_errors/recovery_throttled.html.erb, app/views/idv/session_errors/throttled.html.erb, config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml, spec/controllers/idv/image_uploads_controller_spec.rb, spec/forms/idv/api_document_verification_form_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb, spec/presenters/image_upload_response_presenter_spec.rb, spec/views/idv/session_errors/_throttled.html.erb_spec.rb, spec/views/idv/session_errors/recovery_throttled.html.erb_spec.rb, spec/views/idv/session_errors/throttled.html.erb_spec.rb
=> LG-4370: Update throttled error to use troubleshooting component

config/deploy/demo.rb
**Why**: This is an old capistrano file that is no longer used
=> Remove old config/deploy files

app/assets/stylesheets/components/_troubleshooting-options.scss, app/views/idv/phone_errors/_warning.html.erb, app/views/idv/phone_errors/jobfail.html.erb, app/views/idv/phone_errors/timeout.html.erb, app/views/idv/phone_errors/warning.html.erb, app/views/idv/session_errors/exception.html.erb, app/views/idv/session_errors/recovery_exception.html.erb, app/views/idv/session_errors/recovery_warning.html.erb, app/views/idv/session_errors/warning.html.erb, app/views/idv/shared/_warning.html.erb, app/views/shared/_troubleshooting_options.html.erb, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml, spec/views/idv/phone_errors/_warning.html.erb_spec.rb, spec/views/idv/phone_errors/jobfail.html.erb_spec.rb, spec/views/idv/phone_errors/timeout.html.erb_spec.rb, spec/views/idv/phone_errors/warning.html.erb_spec.rb, spec/views/idv/session_errors/_throttled.html.erb_spec.rb, spec/views/idv/session_errors/exception.html.erb_spec.rb, spec/views/idv/session_errors/recovery_exception.html.erb_spec.rb, spec/views/idv/session_errors/recovery_throttled.html.erb_spec.rb, spec/views/idv/session_errors/recovery_warning.html.erb_spec.rb, spec/views/idv/session_errors/throttled.html.erb_spec.rb, spec/views/idv/session_errors/warning.html.erb_spec.rb, spec/views/idv/shared/_warning.html.erb_spec.rb, spec/views/shared/_troubleshooting_options.html.erb_spec.rb
**Why**: As an end user, if I fail one of the IAL2 verification steps, I want to clearly understand what my other options are if I keep failing this step, so that I can get help or try something else if I have already tried to verify my information and failed.
---|---|---
Phone Jobfail|![phone-jobfail-before](https://user-images.githubusercontent.com/1779930/115783509-f1a70000-a38a-11eb-9889-3d541f93e8bf.png)|![phone-jobfail-after](https://user-images.githubusercontent.com/1779930/115783508-f10e6980-a38a-11eb-85a4-5e7ec91dfc88.png)
Phone timeout|![phone-timeout-before](https://user-images.githubusercontent.com/1779930/115783511-f1a70000-a38a-11eb-9da3-caca6a77eaaf.png)|![image](https://user-images.githubusercontent.com/1779930/115875707-7dfd0580-a413-11 …
=> LG-4370: Update IAL2 warning screens to use troubleshooting component

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_form.scss, app/controllers/users/two_factor_authentication_controller.rb, app/javascript/app/form-field-format.js, app/javascript/packages/one-time-code-input/index.js, app/javascript/packages/one-time-code-input/package.json, app/javascript/packages/one-time-code-input/types.d.ts, app/javascript/packs/one-time-code-input.js, app/services/idv/send_phone_confirmation_otp.rb, app/views/idv/otp_verification/show.html.erb, app/views/shared/_one_time_code_input.html.erb, app/views/two_factor_authentication/otp_verification/show.html.erb, app/views/two_factor_authentication/totp_verification/show.html.erb, app/views/users/totp_setup/new.html.erb, spec/controllers/test/telephony_controller_spec.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb, spec/features/two_factor_authentication/change_factor_spec.rb, spec/javascripts/packages/one-time-code-input/index-spec.js, spec/services/idv/send_phone_confirmation_otp_spec.rb, spec/views/shared/_one_time_code_input.html.erb_spec.rb, spec/views/two_factor_authentication/totp_verification/show.html.erb_spec.rb, tsconfig.json
Adding https://github.com/18F/identity-idp/pull/4915 into https://github.com/18F/identity-idp/pull/4965
Related: https://github.com/18F/identity-telephony/pull/46
=> Alphanumeric sms... with origin

Gemfile
Accidentally included this in #5018
=> Revert Ruby version change

Gemfile, Gemfile.lock
Picking up the bug fix from https://github.com/18F/saml_idp/pull/40
=> pick up updated saml-idp gem (LG-4181)

Gemfile, Gemfile.lock, app/services/data_requests/write_cloudwatch_logs.rb, app/services/user_seeder.rb, app/services/uuid_reporter.rb
**Why**: To remove dependency on HTTParty
=> Update saml_idp gem (LG-3524)

app/models/user.rb, db/migrate/20210427184118_drop_users_unlock_token.rb, db/schema.rb
Depends on #4988 being released
=> drop users unlock token column

app/models/user.rb, db/migrate/20210428145328_drop_users_unconfirmed_email_encrypted_otp_secret_key.rb, db/schema.rb
Should not be merged until #4999 has been deployed
=> drop users unconfirmed_email and encrypted_otp_secret_key columns

app/views/accounts/_phone.html.erb, app/views/accounts/_pii.html.erb, app/views/shared/_pii_review.html.erb, spec/views/accounts/show.html.erb_spec.rb
- Format for US numbers is `+1 123-456-7890`
- We already had `Phoneformatter.format` -- lucky us!
=> Format phone numbers consistently on account page (and others) (LG-4412)

app/controllers/idv/review_controller.rb, app/controllers/users/verify_account_controller.rb, app/mailers/user_mailer.rb, app/services/user_alerts/alert_user_about_account_verified.rb, app/views/user_mailer/account_verified.html.erb, config/locales/time/en.yml, config/locales/time/es.yml, config/locales/time/fr.yml, config/locales/user_mailer/en.yml, config/locales/user_mailer/es.yml, config/locales/user_mailer/fr.yml, spec/controllers/idv/review_controller_spec.rb, spec/controllers/users/verify_account_controller_spec.rb, spec/mailers/user_mailer_spec.rb, spec/services/user_alerts/alert_user_about_account_verified_spec.rb
=> Send email notification when identity is verified (LG-4486)

app/controllers/idv/otp_delivery_method_controller.rb, app/controllers/idv/phone_controller.rb, app/views/idv/otp_delivery_method/new.html.erb, app/views/idv/phone/new.html.erb
For both the phone screen and OTP delivery method screen
Before
Before|After
---|---
Before|After
---|---
=> do not show GPO option if it is not available due to spam (LG-4208)

app/services/phone_confirmation/confirmation_session.rb
=> Release RC 139.2 to Production

app/models/gpo_confirmation_code.rb, db/migrate/20210512141236_usps_confirmation_codes_drop_letter_expired_sent_at.rb, db/schema.rb
Depends on #5052 being deployed
=> drop letter_expired_sent_at column (LG-4565)

spec/controllers/idv/confirmations_controller_spec.rb
One missed context to be removed. Missed in PR #5102
=> missed one ial2 step indicator context

app/services/db/monthly_sp_auth_count/total_monthly_auth_counts_within_iaa_window.rb, app/services/db/monthly_sp_auth_count/unique_monthly_auth_counts_by_iaa.rb, spec/services/db/monthly_sp_auth_count/total_monthly_auth_counts_within_iaa_window_spec.rb, spec/services/db/monthly_sp_auth_count/unique_monthly_auth_counts_by_iaa_spec.rb
**Why**: There will always be partial_months but full_months might be empty causing an empty in clause `IN ()` SQL syntax error
=> Fix invoice supplement reports

db/migrate/20210526024526_drop_iaa_statuses.rb, db/migrate/20210526024753_validate_add_null_check_constraint_to_iaa_dates.rb, db/schema.rb
Resolves LG-4567
Blocked on #5096 being deployed
=> [LG-4567] Drop iaa_statuses table and enable null constraints on IAA dates

app/services/db/doc_auth_log/doc_auth_funnel_summary_stats.rb, app/services/idv/steps/verify_base_step.rb, db/migrate/20210607215515_add_aamva_to_doc_auth_logs.rb, db/schema.rb, spec/features/idv/doc_auth/document_capture_step_spec.rb, spec/features/idv/doc_auth/verify_step_spec.rb
**Why**: Update to LG-4344 https://github.com/18F/identity-idp/pull/5091
=> Add AAMVA tracking

Gemfile, Gemfile.lock, app/jobs/document_proofing_job.rb, app/jobs/job_helpers/faraday_helper.rb, app/services/outbound_health_checker.rb, app/services/piv_cac_service.rb, app/services/proofing/aamva/request/authentication_token_request.rb, app/services/proofing/aamva/request/security_token_request.rb, app/services/proofing/aamva/request/verification_request.rb, app/services/push_notification/http_push.rb, config/initializers/faraday.rb
Working on updating dependencies that also use Faraday to instrument those as well
=> log faraday instrumentation (LG-4651)

Gemfile, Gemfile.lock, spec/support/lexis_nexis_fixtures.rb
=> LG-4606: actually remove the lexisnexis gem from the Gemfile

app/services/user_seeder.rb, spec/fixtures/valid_user_csv.csv
=> [LG-4709] Remove reference to middle_name in UserSeeder

config/application.yml.default, lib/identity_config.rb, lib/saml_idp_constants.rb
Clean up from LG-4666
Blocked on #5145, should not be merged until that is deployed
=> [LG-4666] Remove issuers_with_email_nameid_format config

app/jobs/backup_code_backfiller_job.rb
Discovered this omission by testing in staging
=> Fix backup code backfiller job with query order (LG-4716)

app/controllers/concerns/saml_idp_auth_concern.rb
=> Deploy RC 145.1 to Prod

app/controllers/openid_connect/token_controller.rb
=> Skip session on oidc token requests

app/controllers/sign_up/completions_controller.rb, app/services/date_parser.rb, app/view_models/account_show.rb, app/views/shared/_pii_review.html.erb, spec/controllers/sign_up/completions_controller_spec.rb, spec/services/date_parser_spec.rb, spec/view_models/account_show_spec.rb, spec/views/idv/review/new.html.erb_spec.rb
- Based on errors observed in NewRelic in INT
NewRelic errors:
- [completions controller](https://one.newrelic.com/launcher/nr1-core.explorer?platform[timeRange][duration]=86400000&platform[accountId]=1376370&pane=eyJiYXJjaGFydCI6ImJhcmNoYXJ0IiwidG9wRmFjZXQiOiJ0cmFuc2FjdGlvblVpTmFtZSIsInBhZ2UiOiJzaG93IiwicHJpbWFyeUZhY2V0IjoiZXJyb3IuY2xhc3MiLCJ0cmFjZUlkIjoiZmZlYzdmYzUtZDc5NC0xMWViLWFlMzMtMDI0MmFjMTEwMDA3XzBfMTY3NzAiLCJuZXJkbGV0SWQiOiJlcnJvcnMtdWkub3ZlcnZpZXciLCJlbnRpdHlHdWlkIjoiTVRNM05qTTNNSHhCVUUxOFFWQlFURWxEUVZSSlQwNThNVEEwTkRFd01EWTEifQ==&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwic2VsZWN0ZWROZXJkbGV0Ijp7Im5lcmRsZXRJZCI6ImVycm9ycy11aS5vdmVydmlldyJ9LCJlbnRpdHlHdWlkIjoiTVRNM05qTTNNSHhCVUUxOFFWQlFURWxEUVZSSlQwNThNVEEwTkRFd01EWTEifQ==&state=0dbe7323-c3ff-69d4-c177-0e27f4e3a635) …
=> Add more parsing of american-style dates

Gemfile, Gemfile.lock, app/controllers/sign_up/completions_controller.rb, app/forms/idv/doc_pii_form.rb, app/models/profile.rb, app/presenters/openid_connect_user_info_presenter.rb, app/services/attribute_asserter.rb, app/services/date_parser.rb, app/services/expired_license_allower.rb, app/services/proofing/lexis_nexis/date_formatter.rb, app/view_models/account_show.rb, app/views/shared/_pii_review.html.erb, spec/controllers/sign_up/completions_controller_spec.rb, spec/services/date_parser_spec.rb, spec/services/proofing/lexis_nexis/date_formatter_spec.rb, spec/services/proofing/lexis_nexis/instant_verify/verification_request_spec.rb, spec/services/proofing/lexis_nexis/phone_finder/proofing_spec.rb, spec/view_models/account_show_spec.rb, spec/views/idv/review/new.html.erb_spec.rb
Roll-forward version of https://github.com/18F/identity-idp/pull/5190
=> Add more complete date parsing to LexisNexis code

spec/services/service_provider_request_proxy_spec.rb
Follow up to https://github.com/18F/identity-idp/pull/5195
=> add empty string test for service provider request proxy

app/controllers/concerns/secure_headers_concern.rb, app/controllers/saml_idp_controller.rb, app/services/db/proofing_component/add.rb, app/services/db/proofing_cost/add_user_proofing_cost.rb, app/services/db/sp_cost/add_sp_cost.rb, app/services/funnel/doc_auth/register_step.rb, app/services/secure_headers_allow_list.rb, spec/services/secure_headers_allow_list_spec.rb
=> replace whitelist with allowlist

config/initializers/app_artifacts.rb
This reverts commit f285042b20a0e5dc2602cb1ef4a7695d1e725b55.
=> Revert "Revert "Merge branch 'jp/play-it-again-saml'""

app/services/proofing/base.rb, spec/services/proofing/base_spec.rb
AI from incident review, this gives us more visibility than just in the logs
=> Send proofing exceptions to NewRelic (LG-4798)

app/services/service_provider_request_proxy.rb
Similar to https://github.com/18F/identity-idp/pull/5195
=> skip blank redis query

app/services/proofing/aamva/request/templates/verify.xml.erb, app/services/proofing/aamva/request/verification_request.rb, spec/fixtures/proofing/aamva/requests/verification_request.xml
**Why**: We don't look at the result this provides anyways
=> Stop sending DocumentCategoryCode to AAMVA (LG-4612)

config/country_dialing_codes.yml, config/pinpoint_overrides.yml
* Disable SMS for Iraq
**Why**: We are observing a large amount of SMS spam going to Iraq
=> Deploy RC 150.1 to prod

app/services/idv/steps/verify_base_step.rb
A little Friday micro-optimzation
=> Turn list of AAMVA states into a set

app/controllers/sign_up/completions_controller.rb, app/controllers/users/authorization_confirmation_controller.rb, app/controllers/users/sessions_controller.rb
Changing the CSP appeared to make things worse and not better
=> Deploy RC 150.3

.gitlab-ci.yml, Gemfile, config/database.yml, spec/support/capybara.rb
Now that we are pulling GitHub as a mirror, this PR adds the GitLab-specific details, and is hopefully backwards compatible with CircleCI
Includes the whole GitLab CI configuration, a few ENV configuration things, and moved a gem to production that was causing issues in CI
=> GitLab CI changes

.circleci/config.yml, .codeclimate.yml, .gitlab-ci.yml, Gemfile, Gemfile.lock, Makefile
CodeClimate is limited in what version of Brakeman it can run, so we should run it ourselves
https://docs.codeclimate.com/docs/brakeman
=> Run brakeman in CircleCI/GitLab CI instead of CodeClimate

.gitlab-ci.yml
=> Add a template for jobs that run on pushes, and get images from GCR.

spec/features/users/sign_in_spec.rb
=> Fix typo from #5291

config/country_dialing_codes.yml, config/pinpoint_supported_countries.yml, lib/pinpoint_supported_countries.rb
see info in Slack: https://gsa-tts.slack.com/archives/CR2SSAFRQ/p1629127800000100
=> Add Jordan to sender ID countries list (LG-4980)

Gemfile, Gemfile.lock, app/helpers/aws_s3_helper.rb, app/jobs/reports/base_report.rb, app/services/agreements/reports/base_report.rb, spec/helpers/aws_s3_helper_spec.rb
Related: https://github.com/18F/identity-hostdata/pull/33
=> Clean up how S3 bucket names are built with helper method

app/models/monthly_auth_count.rb, app/policies/mfa_policy.rb, app/policies/two_factor_authentication/auth_app_policy.rb, app/policies/two_factor_authentication/backup_code_policy.rb, app/policies/two_factor_authentication/phone_policy.rb, app/policies/two_factor_authentication/piv_cac_policy.rb, app/presenters/piv_cac_authentication_setup_base_presenter.rb, spec/policies/two_factor_authentication/piv_cac_policy_spec.rb
It doesn't appear these functions are used anywhere
=> Remove unused functions

config/initializers/job_configurations.rb, lib/tasks/delayed_job_stub.rake
Do not merge until https://github.com/18F/identity-devops/pull/3687 has been deployed all the way through devops/infra
=> Remove lingering DelayedJob references

config/country_dialing_codes.yml, config/pinpoint_overrides.yml
- Confirmed manually that it works, this is a stopgap
until we get LG-5060 implemented to fix how we send
the sender ID
Since I already tested this manually in prod this week, man plan is to patch this in to the RC 155 branch
=> Re-enable SMS for India

config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml
*Why?* 
Updated language to be clearer for users.
=> LG-4699: update verify address language

config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml
slack convo that prompted this: https://gsa-tts.slack.com/archives/C0184P9SCJ0/p1630685026000600
=> Update toll/premium rate error message copy

config/application.yml.default
To make it clearer that the credentials are not intentionally not secret
=> Clarify Acuant SDK config comment

app/assets/stylesheets/components/_footer.scss, app/javascript/app/components/index.js, app/views/layouts/base.html.erb, config/locales/shared/en.yml, config/locales/shared/es.yml, config/locales/shared/fr.yml
**Why**: to adhere to accessibility best practices--screen reader users can skip over repetitive content to main content
=> LG-4920: Add skip link to IdP

app/views/partials/personal_key/_key.html.erb, app/views/shared/_personal_key_confirmation_modal.html.erb
**Why** 
some of the styling on the confirmation page has some accessibility issues when it comes to screen readers, so updating them to properly reflect.
=> LG-4964: design/accessibility fixes for confirmation page. 

Gemfile, Gemfile.lock
Brings in a fix for 500s during telephony operations from https://github.com/18F/identity-telephony/pull/52
=> Increment Telephony version

app/services/idv/agent.rb, app/services/push_notification/http_push.rb, config/application.rb, config/application.yml.default, config/initializers/good_job.rb, config/initializers/job_configurations.rb, lib/identity_config.rb, lib/tasks/job_runs.rake
This will let us roll out various async parts separately
=> Add separate feature flags for cron jobs, IDV jobs (LG-5059)

Gemfile, Gemfile.lock
Pulls in https://github.com/18F/identity-telephony/pull/53
=> update telephony gem to better handle errors

app/controllers/idv/confirmations_controller.rb, app/services/idv/session.rb, spec/controllers/idv/confirmations_controller_spec.rb
https://github.com/18F/identity-idp/pull/5433 to prod
=> Release RC 157.2 to Production

spec/controllers/idv/confirmations_controller_spec.rb
follow up to some regression spec additions in #5433  that makes it slightly stricter
=> check pii matches and that personal key digest matches in personal key spec

config/country_dialing_codes.yml, config/pinpoint_overrides.yml, config/pinpoint_supported_countries.yml
- Via make update_pinpoint_supported_countries
Looks like AWS fixed a few typos, which is great
=> Update pinpoint supported countries

app/jobs/remove_old_throttles_job.rb, spec/jobs/remove_old_throttles_job_spec.rb
- Must be deployed at least 30 days after #5353
=> Also delete old throttles with NULL updated_at

db/primary_migrate/20211014225944_drop_job_runs.rb, db/schema.rb
Needs https://github.com/18F/identity-idp/pull/5506 to be deployed to prod (and for us to be happy with it) before merging
=> Drop job_runs table

.circleci/config.yml, db/seeds.rb
**Why**: Clean up log output in specs
Small cleanup to #5581
=> Move logging to logfile

bin/job_runs.sh
Needs this devops PR to be deployed all the way through prod: https://github.com/18F/identity-devops/pull/3874
=> Completely remove job_runs.sh executable

app/views/idv/doc_auth/agreement.html.erb, app/views/idv/doc_auth/welcome.html.erb, config/locales/titles/en.yml, config/locales/titles/es.yml, config/locales/titles/fr.yml
LG-5372 Follow on minor update to titles that was missed in the original PR.
=> LG-5372 Follow on minor update to titles

app/jobs/reports/agreement_summary_report.rb, config/initializers/job_configurations.rb, spec/jobs/reports/agreement_summary_report_spec.rb
=> Add new report that summarizes IAA information (LG-5433)

app/views/users/webauthn_setup/new.html.erb, config/locales/forms/en.yml, config/locales/forms/es.yml, config/locales/forms/fr.yml
This pull request updates the text for add security key and add an authentication app page.
=> Lg 5419 update security text

app/services/iaa_reporting_helper.rb
Thanks @aduth for reporting: https://github.com/18F/identity-idp/pull/5665#discussion_r763279146
=> IaaHelper returns items in a sorted order

db/primary_migrate/20211206205035_add_issuer_returned_at_index_to_sp_return_logs.rb, db/schema.rb
Add index to sp_return_logs to speed up reporting queries (#5670)
(cherry picked from commit bbf4f4bf4dfe76590ab4bc720716a375adc27d5b)
=> Deploy RC 168.1 to Production

spec/jobs/reports/combined_invoice_supplement_report_spec.rb
Another follow-up to https://github.com/18F/identity-idp/pull/5665#discussion_r763279146
=> Make combined invoice supplement report less order-dependent

app/jobs/reports/combined_invoice_supplement_report.rb, spec/jobs/reports/combined_invoice_supplement_report_spec.rb
Some feedback from ticket acceptance:
1. Remove "dates billed start/end" -- it was confusing
2. Add new unique IAL2 (by issuer, it already existed by IAA)
=> Combined report CSV feedback

app/views/accounts/_connected_app.html.erb, spec/views/accounts/connected_accounts/show.html.erb_spec.rb
=> Deploy RC 170.1 to Production

app/services/idv/steps/verify_base_step.rb, app/services/proofing/mock/state_id_mock_client.rb
This commit uses [this reference](https://www.aamva.org/DLDV/) to add the following states since they are now supported: `{"KS", "NC", "OH", "OR", "TN"}`
=> Add additional AAMVA states

app/controllers/users/phones_controller.rb, app/forms/new_phone_form.rb, app/services/flow/base_flow.rb, spec/fixtures/data_request.json, spec/lib/linters/mail_later_linter_spec.rb, spec/services/data_requests/write_user_events_spec.rb, spec/services/data_requests/write_user_info_spec.rb
Adds a few specs to cover behavior that was previously untested, and removes a few unused methods.
=> Add tests for data requests and mail linter

.circleci/config.yml, .gitlab-ci.yml, spec/simplecov_merger.rb
This PR fixes [test coverage visualization](https://docs.gitlab.com/ee/user/project/merge_requests/test_coverage_visualization.html) in GitLab merge requests, and adds test coverage to CircleCI artifacts
=> Fix GitLab coverage merge and support code coverage in CircleCI artifacts

app/forms/concerns/piv_cac_form_helpers.rb, spec/forms/user_piv_cac_login_form_spec.rb
[NR Link](https://one.newrelic.com/launcher/nr1-core.explorer?platform[accountId]=1376370&platform[timeRange][duration]=86400000&pane=eyJuZXJkbGV0SWQiOiJlcnJvcnMtdWkub3ZlcnZpZXciLCJiYXJjaGFydCI6ImJhcmNoYXJ0IiwidG9wRmFjZXQiOiJ0cmFuc2FjdGlvblVpTmFtZSIsInBhZ2UiOiJzaG93IiwicHJpbWFyeUZhY2V0IjoiZXJyb3IuY2xhc3MiLCJ0cmFjZUlkIjoiMDI2ZmRkMDktNjBhZS0xMWVjLTlhNzItMDI0MmFjMTEwMDE2XzBfMTY4NTIiLCJlbnRpdHlHdWlkIjoiTVRNM05qTTNNSHhCVUUxOFFWQlFURWxEUVZSSlQwNThOVEl4TXpZNE5UZyJ9&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5R3VpZCI6Ik1UTTNOak0zTUh4QlVFMThRVkJRVEVsRFFWUkpUMDU4TlRJeE16WTROVGciLCJzZWxlY3RlZE5lcmRsZXQiOnsibmVyZGxldElkIjoiZXJyb3JzLXVpLm92ZXJ2aWV3In19&state=6e24151c-8504-31de-5749-129949d090f5)
=> Fix PIV/CAC 500 on empty token

app/services/status_page.rb
(do not merge while we wait for some HTTPS issues to get sorted out)
=> Update status page link to point at new domain (LG-5512)

app/controllers/application_controller.rb, app/controllers/concerns/verify_sp_attributes_concern.rb, app/controllers/openid_connect/authorization_controller.rb, app/controllers/saml_idp_controller.rb, app/controllers/sign_up/completions_controller.rb, spec/controllers/concerns/verify_sp_attributes_concern_spec.rb
This struck me as I was reading the diff of #5736
=> Minorly refactor VerifySpAttributesConcern

.circleci/config.yml
We don't use them, so we can skip installing them
=> Do not install Firefox or geckodriver in CircleCI

db/schema.rb
Follow up to #5769 where I forgot to check in the schema change
=> Update db schema

db/primary_migrate/20220105143347_create_extension_pg_stat_statements.rb
Database upgrade is done, we can enable this everywhere!
=> enable pg_stat_statements extension

.rubocop.yml, app/controllers/concerns/saml_idp_logout_concern.rb, app/controllers/saml_idp_controller.rb, app/forms/security_event_form.rb, app/mailers/user_mailer.rb, app/models/user.rb, app/services/account_reset_health_checker.rb, app/services/saml_endpoint.rb, lib/tasks/data_requests.rake, spec/features/remember_device/totp_spec.rb, spec/features/two_factor_authentication/change_factor_spec.rb, spec/jobs/reports/iaa_billing_report_spec.rb, spec/presenters/utc_time_presenter_spec.rb
Rubocop had been warning on this so I decided to take a stab at fixing it
~I went with `NewCops: enabled` so that every time we upgrade Rubocop, we get opted in to the new defaults, which could get spicy.~
__updated to do `NewCops: disabled`__
My thinking is, a lot of the new ones are good and when we upgrade Rubocop we can decide if we want to disable them as we go
This is the old warning message, it's gone now ☺️ 
```
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file.
Please also note that you can opt-in to new cops by default by adding this to your config:
AllCops:
NewCops: enable
Rails/ActiveRecordCallbacksOrder: # new in 2.7
Enabled: true
Rails/AddColumnIndex: # new in 2.11
Enabled: true …
```
=> Enable NewCops and fix warnings

app/controllers/openid_connect/logout_controller.rb, app/controllers/openid_connect/token_controller.rb, app/controllers/two_factor_authentication/totp_verification_controller.rb, lib/telephony/pinpoint/sms_sender.rb, spec/controllers/openid_connect/logout_controller_spec.rb, spec/controllers/openid_connect/token_controller_spec.rb, spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb
Some fixes to prevent some 500s from NewRelic and regression specs
[TOTP](https://one.newrelic.com/launcher/nr1-core.explorer?platform[accountId]=1376370&platform[timeRange][duration]=259200000&pane=eyJuZXJkbGV0SWQiOiJlcnJvcnMtdWkub3ZlcnZpZXciLCJiYXJjaGFydCI6ImJhcmNoYXJ0IiwidG9wRmFjZXQiOiJ0cmFuc2FjdGlvblVpTmFtZSIsInBhZ2UiOiJzaG93IiwidHJhY2VJZCI6IjBjNzA4NmM1LTc1MzYtMTFlYy1iOWMwLTAyNDJhYzExMDAwNl8wXzE2MjM5IiwiZW50aXR5R3VpZCI6Ik1UTTNOak0zTUh4QlVFMThRVkJRVEVsRFFWUkpUMDU4TlRJeE16WTROVGcifQ==&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwic2VsZWN0ZWROZXJkbGV0Ijp7Im5lcmRsZXRJZCI6ImVycm9ycy11aS5vdmVydmlldyJ9LCJlbnRpdHlHdWlkIjoiTVRNM05qTTNNSHhCVUUxOFFWQlFURWxEUVZSSlQwNThOVEl4TXpZNE5UZyJ9&state=1620d256-18cd-598e-7fa3-b786eedb2501)
[OIDC …
=> Fix a handful of 500s

config/environments/development.rb
**Why**: It sped up rake assets:compile for me locally
- Follow-up to #5812, wasn't sure if we missed it on accident
=> Skip Gzipping assets in development

.circleci/config.yml, CHANGELOG.md
Following up to #5836, but enabling the CI check
(I'll be testing some of the CircleCI parts here before this is ready for review)
=> Enable Changelog CI checks

CHANGELOG.md, config/locales/help_text/en.yml, config/locales/help_text/es.yml, config/locales/help_text/fr.yml
Had this branch sitting around with a few other message updates, but incorporated those into other pull requests. This is the only one that had nowhere else go to 😬
=> LG-4792: Update punctuation in messages

config/application.rb, spec/requests/api_cors_spec.rb
=> Allow CORS from handbook for analytics events

Makefile
We currently pass this check (I think since #5889), so now may be the most opportune time to add it if we want?
=> Run yarn audit in CI

app/controllers/account_reset/cancel_controller.rb, app/services/analytics.rb
Includes a small patch to fix a bug with account reset
=> Release RC 181.1 to Production

app/services/browser_cache.rb
Follow up to https://github.com/18F/identity-idp/pull/6036#discussion_r824867830
=> Avoid using magic number when truncating user-agent

app/jobs/phone_number_opt_out_sync_job.rb
=> Deploy RC 181.2 to Prod

app/javascript/packages/eslint-plugin/CHANGELOG.md, app/javascript/packages/eslint-plugin/package.json
**Why:** So that we can use it in our other repositories.
Changelog:
>## v2.0.0 (2022-03-14)
>
>### Breaking changes
>
>- Updated peer dependencies to require ESLint >= 8 ([see migration guide](https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0)).
>- Updated base Airbnb shared configurations, introducing newly-enforced rules (see [`airbnb` changelog](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/CHANGELOG.md), [`airbnb-base` changelog](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/CHANGELOG.md)).
>- Removed Babel auto-configuration. As an alternative, consider [configuring ESLint to use modern syntax and/or JSX](https://eslint.org/docs/user-guide/configuring/language-options#specifying-parser-options), or use …
=> Prepare v2.0.0 release of ESLint plugin

app/services/analytics_events.rb
=> Fix analytics events documentation typo

app/javascript/packages/compose-components/index.js, app/javascript/packages/document-capture/components/acuant-capture.jsx, app/javascript/packages/document-capture/components/document-capture.jsx, app/javascript/packages/document-capture/components/file-input.jsx, app/javascript/packages/document-capture/components/submission.jsx, app/javascript/packages/document-capture/context/acuant.jsx, app/javascript/packages/document-capture/context/failed-capture-attempts.jsx, app/javascript/packages/document-capture/hooks/use-if-still-mounted.js, app/javascript/packages/masked-text-toggle/index.js, app/javascript/packages/normalize-yaml/cli.js, app/javascript/packages/normalize-yaml/package.json, app/javascript/packages/phone-input/index.js, app/javascript/packages/rails-i18n-webpack-plugin/rails-i18n-webpack-plugin.spec.js, app/javascript/packages/step-indicator/index.js, app/javascript/packs/doc-capture-polling.js, app/javascript/packs/webauthn-unhide.js, package.json, spec/javascripts/packages/document-capture-polling/index-spec.js, webpack.config.js, yarn.lock
**Why**: Since formatting can change version-to-version, it's best to keep on top of it to avoid future maintenance headaches.
=> Upgrade Prettier from 2.2 to 2.6

app/services/analytics_events.rb
See: https://github.com/18F/identity-idp/pull/6084#discussion_r832512758
=> Add param to match documentation

app/services/analytics_events.rb
=> Fix YARD syntax

app/controllers/event_disavowal_controller.rb, app/controllers/events_controller.rb, app/controllers/redirect/redirect_controller.rb, app/controllers/users/forget_all_browsers_controller.rb, app/services/analytics.rb, app/services/analytics_events.rb, spec/controllers/event_disavowal_controller_spec.rb, spec/controllers/redirect/help_center_controller_spec.rb, spec/controllers/users/forget_all_browsers_controller_spec.rb, spec/features/idv/doc_auth/welcome_step_spec.rb
=> Document additional analytics events (LG-5926)

config/locales/two_factor_authentication/en.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml
changelog: Improvements, Content, Change "Don't have access to your
phone right now?" to "Can't use your phone?"
=> LG-5745 Can't use your phone?

.gitlab-ci.yml
=> Update idp/ci image to one with healthcheck

spec/features/sp_cost_tracking_spec.rb
=> Remove unused test helper

.rubocop.yml, scripts/artifact-upload
Embarrassing follow up to #6207
=> fix bug from syntax error in artifact upload script

app/controllers/two_factor_authentication/otp_verification_controller.rb, app/controllers/users/two_factor_authentication_controller.rb, lib/telephony/pinpoint/sms_sender.rb, spec/controllers/two_factor_authentication/options_controller_spec.rb, spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb
Pulls in a couple of bug fixes for bugs that are causing issues
=> Release RC 189.1 to Production

config/routes.rb, spec/requests/saml_requests_spec.rb
[skip-changelog]
Reverting part of #5676
=> Permit GET requests for SAML Remote logout

app/controllers/idv/forgot_password_controller.rb, app/controllers/idv_controller.rb, app/services/analytics.rb, app/services/analytics_events.rb, spec/controllers/idv/forgot_password_controller_spec.rb, spec/controllers/idv_controller_spec.rb
Why?: Documenting more analytics events.
=> LG 5930 Document Analytics 12

app/views/users/mfa_selection/index.html.erb, config/routes.rb
Updated routes. Realized that during the deploy it would try to redirect to "authentication method setup" first which would create 500s. So splitting up the creating of the url with the updating to reroute to that url.
=> LG-6043: update routes to make more sense to users 

app/presenters/two_factor_authentication/phone_selection_presenter.rb, spec/presenters/two_factor_authentication/phone_selection_presenter_spec.rb
We need to move phone description under Kantara phone feature toggle.
=> changelog: Upcoming Feature, move phone description under kantara phone feature toggle

app/controllers/concerns/two_factor_authenticatable_methods.rb, app/controllers/two_factor_authentication/options_controller.rb, app/controllers/users/phone_setup_controller.rb, app/services/analytics.rb, app/services/analytics_events.rb, spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb, spec/controllers/two_factor_authentication/options_controller_spec.rb, spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb, spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb, spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb, spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb, spec/controllers/users/phone_setup_controller_spec.rb
changelog: Improvements, Analytics, Updated analytics events
=> LG-5938-document-analytics-19

scripts/changelog_check.rb, spec/fixtures/git_log_changelog.yml, spec/scripts/changelog_check_spec.rb
Small tweak, I've done this manually for a few releases, I like the end result
=> Update changelog script to alphabetize within a category

config/locales/idv/en.yml
This came up as a request in acceptance testing of [LG-6342](https://cm-jira.usa.gov/browse/LG-6342). The Spanish and French translations already include the period
=> LG-6342: Add missing period

app/services/analytics_events.rb
changelog: Improvements, Analytics, Update analytics
=> Analytics 22 update

app/models/in_person_enrollment.rb, app/models/profile.rb, app/models/user.rb, db/primary_migrate/20220622232047_create_in_person_enrollments.rb, db/schema.rb, spec/factories/in_person_enrollments.rb, spec/models/in_person_enrollment_spec.rb, spec/models/profile_spec.rb, spec/models/user_spec.rb
This adds the model and migration specified in [LG-6339](https://cm-jira.usa.gov/browse/LG-6339).
=> LG-6339: Create new migration and model for enrollments

db/primary_migrate/20220705200821_drop_totp_timestamp_from_users.rb
**Why**: I forgot to add it in #6549
=> Commit migration file

app/controllers/application_controller.rb, app/controllers/two_factor_authentication/sms_opt_in_controller.rb, app/controllers/users/sessions_controller.rb, app/services/analytics.rb, app/services/analytics_events.rb, spec/controllers/two_factor_authentication/sms_opt_in_controller_spec.rb, spec/controllers/users/sessions_controller_spec.rb, spec/features/session/timeout_spec.rb
Why? Documenting more analytics
=> LG-5950 analytics 29

app/services/analytics_events.rb, app/services/doc_auth_router.rb, app/services/idv/actions/cancel_update_ssn_action.rb, app/services/idv/steps/doc_auth_base_step.rb, app/services/idv/steps/ssn_step.rb, spec/services/doc_auth_router_spec.rb
- Identity verification: Fix 500 error when handling invalid state in SSN step ([#6589](https://github.com/18F/identity-idp/pull/6589))
- Identity verification: Return the default doc_auth ([#6587](https://github.com/18F/identity-idp/pull/6587))
=> Deploy RC 199.1 to Production

scripts/va-api-test.rb
Script to test accessing the VA api for inherited proofing. 
```
bin/rails runner scripts/va-api-test.rb
```
=> LG-6815 test script to test VA api

db/worker_jobs_schema.rb
I failed to include this in #6610, apologies!
=> Update worker jobs schema

docs/backend.md
Starting small! With just networking
=> Add documentation on our app's backend

app/controllers/users/sessions_controller.rb, app/services/irs_attempts_api/tracker_events.rb, spec/controllers/users/sessions_controller_spec.rb
Add IRS Attempts API Logout Event and track the logout event in the Sessions Controller.
=> LG_6949 Add AttemptsAPI Logout: SessionsController

db/schema.rb, db/worker_jobs_schema.rb
=> add precision values to datetime columns in schema

app/forms/idv/inherited_proofing/va/form.rb, spec/forms/idv/inherited_proofing/va/form_spec.rb
https://cm-jira.usa.gov/browse/LG-6900
=> [LG-6900] Add a form to validate payload fields returned from VA inherited proofing

.gitlab-ci.yml
May switch this to running on main or a daily job that sends an email, etc. but just trying to establish basic functionality first 🙂
=> Add Pinpoint Check to GitLab CI

spec/views/shared/_one_time_code_input.html.erb_spec.rb
This was an oopsie from me in https://github.com/18F/identity-idp/pull/6562
=> Remove puts in test

app/controllers/concerns/unconfirmed_user_concern.rb, app/services/irs_attempts_api/tracker_events.rb, spec/controllers/sign_up/email_confirmations_controller_spec.rb, spec/controllers/sign_up/passwords_controller_spec.rb
=> LG-6978 : Implement Confirm email event

app/controllers/application_controller.rb, app/controllers/users/totp_setup_controller.rb, app/services/irs_attempts_api/tracker_events.rb, spec/controllers/users/totp_setup_controller_spec.rb, spec/rails_helper.rb, spec/support/fake_attempts_tracker.rb, spec/support/features/irs_attempts_api_tracking_helper.rb
=> LG-6984 TOTP Enroll Submit & stub_attempts_tracker

Makefile, app/components/README.md, app/javascript/app/README.md, app/javascript/packages/README.md, app/javascript/packages/eslint-plugin/package.json, app/javascript/packages/normalize-yaml/package.json, app/javascript/packages/phone-input/package.json, app/javascript/packages/rails-i18n-webpack-plugin/package.json, app/javascript/packages/stylelint-config/package.json, app/javascript/packages/verify-flow/package.json, app/javascript/packs/README.md, docs/frontend.md, scripts/validate-workspaces.js, tsconfig.json, yarn.lock
**Why**: To improve the developer onboarding experience, include documentation colocated with these folders, as they're a common source of questions or confusion.
=> Add basic documentation for JavaScript and component directories

app/controllers/users/two_factor_authentication_controller.rb, app/services/irs_attempts_api/tracker_events.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb, spec/features/irs_attempts_api/event_tracking_spec.rb
Also includes ticket: [LG-6982](https://cm-jira.usa.gov/browse/LG-6982)
1. Added MFA Phone OTP Verification Attempt Event
2. Added MFA Phone OTP Enrollment Attempt Event
3. Updated rspec test for `two_factor_authentication_controller.rb` to reflect new attempt events.
=> LG7040 - MFA Phone OTP Verification and Enrollment Attempt Events

Makefile, yarn.lock
Out of sync after #6701
Linter based on [similar in identity-style-guide](https://github.com/18F/identity-style-guide/blob/4540133fef84c3ba891aefe1cd2811b2fd3e79ff/Makefile#L20-L30).
1. `git checkout 21f8152`
2. `make lint_lockfiles`
_Expected:_
```
Error: There are uncommitted changes after running 'yarn install'
make: *** [lint_yarn_lock] Error 1
```
=> Sync yarn.lock (and add linter)

app/controllers/users/backup_code_setup_controller.rb, app/services/irs_attempts_api/tracker_events.rb, spec/controllers/users/backup_code_setup_controller_spec.rb
=> LG-6987 Back-up code enroll event tracking

app/forms/otp_verification_form.rb, app/models/concerns/user_otp_methods.rb, app/views/two_factor_authentication/otp_verification/show.html.erb, config/application.yml.default, lib/identity_config.rb, spec/forms/otp_verification_form_spec.rb
=> Remove numeric authentication OTP configurations

app/controllers/two_factor_authentication/backup_code_verification_controller.rb, app/services/irs_attempts_api/tracker_events.rb, spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb
=> LG-7046 Back-up code verification event tracking

app/controllers/idv/capture_doc_controller.rb, app/controllers/idv/doc_auth_controller.rb, app/controllers/idv/in_person_controller.rb, app/services/flow/flow_state_machine.rb
https://cm-jira.usa.gov/browse/LG-7239
Rename to avoid confusing acronyms that can tend to be a source of
confusion for new developers.
changelog: Internal, Improvements, Change FSM_SETTINGS to FLOW_STATE_MACHINE_SETTINGS (LG-7239)
=> [LG-7239] Change FSM_SETTINGS to FLOW_STATE_MACHINE_SETTINGS

Makefile, app/services/irs_attempts_api/tracker_events.rb, lib/analytics_events_documenter.rb, spec/lib/analytics_events_documenter_spec.rb, spec/spec_helper.rb
First commit adds script changes, lints etc, and then a2aa498edfda1ba556f84080f9ecf6c2a5189ff2 fixes errors we had
=> Documentation checking for Attempts API events (LG-7134)

app/controllers/users/webauthn_setup_controller.rb, app/services/irs_attempts_api/tracker_events.rb, spec/controllers/users/webauthn_setup_controller_spec.rb
=> LG-6986 Add Event for WebAuthn_Platform enrollment

app/controllers/two_factor_authentication/webauthn_verification_controller.rb, app/services/irs_attempts_api/tracker_events.rb, spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
=> LG-7045 add Event: MFA WebAuthn_Platform verify

app/controllers/users/sessions_controller.rb, spec/controllers/users/sessions_controller_spec.rb
Includes the patch in #6735 to fix an increasingly frequent 500 error
- Security: Fix 500 error when handling unsafe redirects ([#6735](https://github.com/18F/identity-idp/pull/6735))
=> Deploy RC 203.1 to Production

app/controllers/test/piv_cac_authentication_test_subject_controller.rb, app/controllers/users/piv_cac_authentication_setup_controller.rb, app/controllers/users/piv_cac_setup_from_sign_in_controller.rb, app/services/irs_attempts_api/tracker_events.rb, spec/controllers/users/piv_cac_authentication_setup_controller_spec.rb
=> LG-6985 Add Attempts API PIV/CAC enrollment event tracking

app/controllers/two_factor_authentication/otp_verification_controller.rb, app/services/irs_attempts_api/tracker.rb, app/services/irs_attempts_api/tracker_events.rb, spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb
1. Added mfa_phone_verification_otp_submitted event
2. Added mfa_phone_enrollment_otp_submitted event
3. Added unit tests for the above events.
Note: This PR covers tickets: LG-6983, LG-7041
=> LG-7041 - MFA Phone Submitted Events

app/services/idv/steps/ipp/ssn_step.rb, app/services/idv/steps/ssn_step.rb, app/views/idv/doc_auth/ssn.html.erb, app/views/idv/in_person/ssn.html.erb, app/views/idv/shared/_ssn.html.erb, spec/services/idv/steps/ipp/ssn_step_spec.rb, spec/services/idv/steps/ssn_step_spec.rb, spec/views/idv/shared/_ssn.html.erb_spec.rb
changelog: Bug Fix, Threat Metrix, move threatmetrix session id on ssn
step to extra variables.
=> LG-7014 moved threatmetrix_session_id to extra variables

app/jobs/resolution_proofing_job.rb, config/application.yml.default, lib/identity_config.rb, spec/jobs/resolution_proofing_job_spec.rb
**Why**: We need to test this in dev environment with threatmetrix live
=> Let threatmetrix not respect the global mock

app/controllers/two_factor_authentication/piv_cac_verification_controller.rb, app/services/irs_attempts_api/tracker_events.rb, spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb
=> LG-7044 Add Attempts API PIV/CAC verify event tracking

app/jobs/resolution_proofing_job.rb
Add parameters for changes to resolution proofing job to allow it to be forward-compatible
=> Deploy RC 203.2 to Production

app/views/idv/gpo_verify/index.html.erb, config/locales/forms/en.yml, config/locales/forms/es.yml, config/locales/forms/fr.yml
Update content for GPO Welcome Back page. 
**Pull request changes look like:**
**Mockup in Jira:**
=> Lg 7142 gpo welcome back

config/application.yml.default
=> Update default irs_attempt_api_csp_id

app/views/idv/gpo/index.html.erb, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml
This PR deals with changes for LG-7141, which provides some styling and content (and localization) updates for the "Want a Letter?" page of the IdV GPO flow.
=> LG-7141 Better Context in Verify By Mail Workflow

app/services/flow/base_flow.rb, app/services/idv/steps/send_link_step.rb, app/services/irs_attempts_api/tracker_events.rb, spec/features/idv/doc_auth/send_link_step_spec.rb
=> LG-7097 add Event: IDV phone upload link sent

app/controllers/users/sessions_controller.rb, lib/telephony/pinpoint/sms_sender.rb
- Multi-factor authentication: Handle errors from vendors better ([#6835](https://github.com/18F/identity-idp/pull/6835))
=> Deploy RC 204.2 to Production

app/services/idv/steps/inherited_proofing/get_started_step.rb
Slight oversight on recent PR that was approved and merged.
=> LG-6970 fix class inheritance of inherited proofing GetStartedStep

app/jobs/resolution_proofing_job.rb, app/services/proofing/lexis_nexis/ddp/proofer.rb, spec/jobs/resolution_proofing_job_spec.rb
**Why**: provide more info to debug network errors vs
logic errors, etc
changelog: Internal, Logging, Update logging from network requests to vendors
=> Update ResolutionProofingJob TMX logging

spec/models/in_person_enrollment_spec.rb
A couple of linting issues slipped in when #6832 landed after #6875
=> Resolve linting errors

app/services/account_reset/delete_account.rb, app/services/analytics_events.rb, spec/services/account_reset/delete_account_spec.rb
**Why**: caused a few 500s in production
changelog: Bug fixes, Account reset, Fixed exception on account reset
[Newrelic link](https://one.newrelic.com/nr1-core/errors/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=43200000&state=8787daa7-3c60-9b7c-020c-5b6f28184794)
=> Bug fix: deleting an account with nil confirmed_at

.rubocop.yml, app/forms/idv/address_form.rb, app/forms/idv/ssn_format_form.rb, app/jobs/reports/combined_invoice_supplement_report.rb, app/jobs/risc_delivery_job.rb, app/views/users/backup_code_setup/create.html.erb, lib/analytics_events_documenter.rb, spec/lib/utf8_sanitizer_spec.rb
=> Enable Rubocop SpaceInsideArrayLiteralBrackets

app/components/memorable_date_component.rb
No functional changes, only fixing docs and style issues.
=> LG-6497: Minor style/doc fixes related to memorable date change

app/controllers/users/delete_controller.rb, app/services/irs_attempts_api/tracker_events.rb, spec/controllers/users/delete_controller_spec.rb
=> LG-7194 Add Event: Account purged

.gitlab-ci.yml
=> Trigger devops on merges to main.

app/controllers/mfa_confirmation_controller.rb, app/services/irs_attempts_api/tracker_events.rb, spec/controllers/mfa_confirmation_controller_spec.rb
=> LG-7547-Password-Change-Reauthentication-Rate-Limit

app/controllers/mfa_confirmation_controller.rb, app/services/irs_attempts_api/tracker_events.rb, spec/controllers/mfa_confirmation_controller_spec.rb
=> Update Password Change to Profile Change

app/services/irs_attempts_api/tracker.rb, spec/services/irs_attempts_api/tracker_spec.rb
changelog: Internal, Attempts API, Omit failure reason when not relevant
=> LG-7418 Omit failure reason when not relevant

app/jobs/resolution_proofing_job.rb
This helps us give a breakdown of how much time is spent per-vendor, the job already logs `timer.results` in an `ensure` block
=> Log timing info for TMX inside ResolutionProofingJob

app/services/idv/steps/upload_step.rb, app/services/irs_attempts_api/tracker_events.rb, spec/features/idv/doc_auth/upload_step_spec.rb
changelog: Internal, Attempts API, Standardize events name
=> LG-7469 Standardize naming conventions

app/controllers/two_factor_authentication/otp_verification_controller.rb
=> Fix short-circuiting in OTP confirmation controller

app/views/user_mailer/add_email.html.erb
- Email Confirmation: Fix link in email when confirming new email address for existing account (#7019) ([#7019](https://github.com/18F/identity-idp/pull/7019))
=> Deploy RC 211.1 to Production

app/javascript/packages/phone-input/index.js
Reverts a small change from #7016 since it appears to not be a concern
=> Remove isConnected check in phone input JavaScript

app/forms/idv/phone_confirmation_otp_verification_form.rb, app/services/irs_attempts_api/tracker_events.rb, spec/forms/idv/phone_confirmation_otp_verification_form_spec.rb
=> Standardize phone_number name

.rubocop.yml, Gemfile, Gemfile.lock, app/services/flow/flow_state_machine.rb, spec/models/agreements/iaa_spec.rb
Just a regular update of a dependency
=> Upgrade rubocop-performance

package.json, spec/javascripts/packages/document-capture/components/acuant-capture-spec.jsx, spec/javascripts/packages/document-capture/components/documents-step-spec.jsx, spec/javascripts/packs/form-steps-wait-spec.js, yarn.lock
Follow-up to #7066 which, as noted in the pull request description, omitted this dependency to some complexities of the upgrade. This pull request seeks to address those requirements.
=> Upgrade testing-library/dom to latest version

app/controllers/account_reset/pending_controller.rb, app/controllers/idv/gpo_controller.rb, app/controllers/idv/personal_key_controller.rb, app/services/idv/steps/in_person/ssn_step.rb, app/services/idv/steps/ssn_step.rb, app/services/irs_attempts_api/tracker_events.rb, app/services/request_password_reset.rb, spec/controllers/account_reset/pending_controller_spec.rb, spec/controllers/idv/forgot_password_controller_spec.rb, spec/controllers/idv/gpo_controller_spec.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/controllers/users/reset_passwords_controller_spec.rb, spec/services/idv/steps/ssn_step_spec.rb, spec/services/request_password_reset_spec.rb
=> Remove Unnecessary Success parameters

app/mailers/user_mailer.rb, spec/mailers/user_mailer_spec.rb
- Mailers: Resolve unhandled errors by correcting error class name ([#7162](https://github.com/18F/identity-idp/pull/7162))
=> Deploy RC 218.1 to Prod

app/controllers/users/emails_controller.rb, app/services/analytics_events.rb, spec/controllers/users/emails_controller_spec.rb
=> Deploy RC 218.2 to Production

app/jobs/threat_metrix_js_verification_job.rb, spec/jobs/threat_metrix_js_verification_job_spec.rb
N/A
[Slack context](https://gsa-tts.slack.com/archives/C0184P9SCJ0/p1666189592115189)
**Why**: Some environments don't have signatures configured, so it's not an error we need to alert on
=> Update JS verification job to not re-raise for some errors

config/country_dialing_codes.yml, config/locales/countries/en.yml, config/locales/countries/es.yml, config/locales/countries/fr.yml, config/pinpoint_overrides.yml, config/pinpoint_supported_countries.yml
changelog: Internal, API improvements, add and update information for American Samoa [(LG-7789)](https://github.com/18F/identity-idp/pull/7154)
=> Deploy RC 218.3 to Production

db/worker_jobs_schema.rb
update schema for changes in #7196
=> update schema for changes in #7196

config/locales/in_person_proofing/en.yml, config/locales/in_person_proofing/es.yml, config/locales/in_person_proofing/fr.yml
[Lg-7183](https://cm-jira.usa.gov/browse/LG-7183)
Update translations
<details>
<summary>En Before:</summary>
</details>
<details>
<summary>En After:</summary>
</details>
<details>
<summary>Es Before:</summary>
</details>
<details>
<summary>Es After:</summary>
</details>
<details>
<summary>fr After:</summary>
</details>
<details>
<summary>FR After:</summary>
</details>
=> Lg-7183 update string translations to reflect new content

app/assets/stylesheets/components/all.scss, app/assets/stylesheets/utilities/_border.scss, app/javascript/packages/document-capture/components/location-collection-item.scss, app/javascript/packages/document-capture/styles.scss
Rearranges some styles:
- Avoids duplicate style definitions (`border-dashed` is defined by USWDS)
- Keeps styles colocated with relevant JavaScript package components, and ensures consistency with other such styles
=> Reorganize some CSS to reduce size of application stylesheet

app/assets/stylesheets/components/_alert.scss
https://cm-jira.usa.gov/browse/LG-7972
Changed the font-weight for this style from 500 to 'bold'
=> Updated bolden style for .usa-alert--info-important

app/decorators/user_decorator.rb, app/views/sign_up/cancellations/new.html.erb, config/locales/users/en.yml, config/locales/users/es.yml, config/locales/users/fr.yml, spec/decorators/user_decorator_spec.rb, spec/views/users/delete/show.html.erb_spec.rb
[LG-7880](https://cm-jira.usa.gov/browse/LG-7880)
Tech debt cleanup: there are some lingering references to LOA1 and LOA3 in our codebase that we can remove
N/A
N/A
N/A
=> remove LOA1 and LOA3 references

app/views/idv/doc_auth/welcome.html.erb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, spec/features/idv/doc_auth/welcome_step_spec.rb
[LG-7680](https://cm-jira.usa.gov/browse/LG-7680)
Update text on the "Getting Started" screen of the IDV flow.
- Start the IDV flow and verify the text
<table>
<thead>
<tr>
<th></th>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<th>English</th>
<td>
</td>
<td>
</td>
</tr>
<tr>
<th>Spanish</th>
<td>
</td>
<td>
</td>
</tr>
<tr>
<th>French</th>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
N/A
=> Update phone language on IDV Getting Started screen

app/controllers/concerns/unconfirmed_user_concern.rb, app/controllers/sign_up/email_confirmations_controller.rb, spec/controllers/sign_up/email_confirmations_controller_spec.rb, spec/controllers/sign_up/passwords_controller_spec.rb
=> LG-8044 De-duplicate email_confirmation event

app/jobs/irs_attempts_events_batch_job.rb, config/initializers/job_configurations.rb, spec/jobs/irs_attempts_events_batch_job_spec.rb
This seemed to be failing because of a lulzy kwargs issue
changelog: Internal, Attempts API, fix batch job error
=> LG-8078 | Fix IrsAttemptsEventsBatchJob

app/jobs/irs_attempts_events_batch_job.rb, config/initializers/job_configurations.rb, spec/jobs/irs_attempts_events_batch_job_spec.rb
Patches #7331 into prod to stop the errors
- Attempts API: Fix batch job error ([#7331](https://github.com/18F/identity-idp/pull/7331))
=> Deploy RC 226.1 to Prod

app/jobs/irs_attempts_events_batch_job.rb, app/services/analytics_events.rb, app/services/flow/base_flow.rb, app/services/flow/flow_state_machine.rb, app/services/idv/flows/capture_doc_flow.rb, app/services/idv/flows/doc_auth_flow.rb, config/initializers/job_configurations.rb, db/primary_migrate/20221108182937_drop_monthly_sp_auth_counts.rb, db/schema.rb, pull_request_template.md, spec/controllers/idv/capture_doc_controller_spec.rb, spec/controllers/idv/doc_auth_controller_spec.rb, spec/factories/monthly_sp_auth_counts.rb, spec/features/idv/analytics_spec.rb, spec/features/idv/inherited_proofing/analytics_spec.rb, spec/jobs/irs_attempts_events_batch_job_spec.rb, spec/support/features/inherited_proofing_helper.rb
- Inherited Proofing: Analytics ([#7326](https://github.com/18F/identity-idp/pull/7326))
=> Deploy RC 227 to Prod

config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml
[Lg-7528](https://cm-jira.usa.gov/browse/LG-7528)
Update strings to remove first sentence. 
<details>
<summary>En Before:</summary>
</details>
<details>
<summary>En After:</summary>
</details>
<details>
<summary>Es Before:</summary>
</details>
<details>
</details>
<details>
<summary>Fr Before:</summary>
</details>
<details>
<summary>Fr After:</summary>
</details>
=> lg-7528/update strings

app/jobs/irs_attempts_events_batch_job.rb, spec/jobs/irs_attempts_events_batch_job_spec.rb
changelog: Internal, Attempts API, bugfix
This should hopefully fix the alerting issues in int.
=> unticketed-batchjob-alert-fix

app/services/idv/steps/send_link_step.rb, package.json, spec/services/idv/steps/send_link_step_spec.rb, yarn.lock
https://cm-jira.usa.gov/browse/LG-7421
Added the telephony response to the return value from the send_link step, so that it is logged in the events log
=> First change to send_link_step

app/models/service_provider.rb, db/primary_migrate/20221114155325_drop_service_provider_quota_limit.rb, db/primary_migrate/20221114155332_drop_ial2_quota.rb, db/schema.rb
[LG-7768](https://cm-jira.usa.gov/browse/LG-7768)
Follow-up to https://github.com/18F/identity-idp/pull/7337, do not merge until that PR has been deployed.
=> Drop ial2_quota tables (LG-7768)

app/forms/new_phone_form.rb, config/application.yml.default, config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml, lib/identity_config.rb, spec/forms/new_phone_form_spec.rb
- Phone Registration: Add configurable phone carrier registration blocklist ([#7366](https://github.com/18F/identity-idp/pull/7366))
=> Deploy RC 228.1 to Production

config/locales/telephony/es.yml
- Voice OTP: Fix voice MFA OTP errors for Spanish-language visitors
=> Deploy RC 231.1 to Prod

app/decorators/service_provider_session_decorator.rb, spec/decorators/service_provider_session_decorator_spec.rb, spec/features/irs_attempts_api/event_tracking_spec.rb, spec/support/oidc_auth_helper.rb
changelog: Internal, Attempts API, Update irs_attempts_api_session_id
=> LG-8293 Attempts API contingency plan

app/controllers/api/irs_attempts_api_controller.rb, app/services/analytics_events.rb, spec/controllers/api/irs_attempts_api_controller_spec.rb
This is to support the work for alarms in https://github.com/18F/identity-devops/issues/5388
=> Add IRS events authentication logging

app/services/analytics_events.rb, app/views/idv/gpo_verify/index.html.erb, config/locales/account/en.yml, config/locales/account/es.yml, config/locales/account/fr.yml, config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml, config/locales/forms/en.yml, config/locales/forms/es.yml, config/locales/forms/fr.yml, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml, config/locales/user_mailer/en.yml, config/locales/user_mailer/es.yml, config/locales/user_mailer/fr.yml, spec/features/idv/steps/gpo_otp_verification_step_spec.rb
changelog: Improvement, IdV, Update GPO to reflect one-time code"
Updated GPO to reflect "one-time code" replacing "confirmation code"
=> LG-8314 Update GPO to reflect "one-time code"

app/controllers/concerns/inherited_proofing_presenter_concern.rb, app/controllers/idv/inherited_proofing_controller.rb, app/controllers/idv/inherited_proofing_errors_controller.rb, app/presenters/idv/inherited_proofing/inherited_proofing_presenter.rb, app/views/idv/inherited_proofing/get_started.html.erb, app/views/idv/inherited_proofing/verify_info.html.erb, app/views/idv/inherited_proofing_errors/failure.html.erb, app/views/idv/inherited_proofing_errors/warning.html.erb, config/locales/inherited_proofing/en.yml, config/locales/inherited_proofing/es.yml, config/locales/inherited_proofing/fr.yml, spec/features/idv/inherited_proofing/verify_info_step_spec.rb, spec/views/idv/inherited_proofing/get_started.html.erb_spec.rb
Make VA-specific references service provider/partner agency agnostic.
[https://cm-jira.usa.gov/browse/LG-8011](https://cm-jira.usa.gov/browse/LG-8011)
=> LG-8011 Make reference to service provider web site name dynamic

app/views/idv/inherited_proofing/get_started.html.erb, config/locales/inherited_proofing/en.yml, config/locales/inherited_proofing/es.yml, config/locales/inherited_proofing/fr.yml, spec/views/idv/inherited_proofing/get_started.html.erb_spec.rb
[LG-7454](https://cm-jira.usa.gov/browse/LG-7454)
Updated text on the get started page for english, spanish, and french
=> Lg 7454 - Get started text translations

app/javascript/packages/document-capture/components/documents-step.jsx, app/views/idv/doc_auth/upload.html.erb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml, config/locales/inherited_proofing/en.yml
[LG-8082](https://cm-jira.usa.gov/browse/LG-8082)
<details>
<summary>English</summary>
<table>
<tr>
<th></th>
<th>Before</th>
<th>After</th>
<th>Diff</th>
</tr>
<tr>
<th>Getting started</th>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>How it works</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>How to upload...</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>Add your state ID</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>Cancel (no SP)</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>Cancel (with SP)</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
</details>
<details>
<summary>Spanish</summary>
<table>
<tr>
<th></th>
<th>Before</th>
<th>After</th>
<th>Diff</th>
</tr>
<tr>
<td>Getting Started</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>How it …
=> Language updates related to document escrow (LG-8082)

config/locales/inherited_proofing/en.yml, config/locales/inherited_proofing/es.yml, config/locales/inherited_proofing/fr.yml, spec/support/features/inherited_proofing_helper.rb
changelog: Internal, Inherited Proofing, Text Updates
[LG-7486](https://cm-jira.usa.gov/browse/LG-7486)
Update text and translations on the How Verifying Works page
=> LG-7486 How Verifying text and translations

app/views/idv/inherited_proofing/_verify.html.erb, config/locales/inherited_proofing/en.yml, config/locales/inherited_proofing/es.yml, config/locales/inherited_proofing/fr.yml
changelog: Internal, Inherited Proofing, Text Updates
[LG-7494](https://cm-jira.usa.gov/browse/LG-7494)
- Updated text for Inherited Proofing Please Verify view
- Added French and Spanish translations for Please Verify view
https://user-images.githubusercontent.com/4822313/206711613-6a316049-61bf-41f5-9e6b-7b3ad1007117.mov
https://user-images.githubusercontent.com/4822313/206711617-d75528c5-e47c-4aa4-a3a3-a5ba58a31f0b.mov
https://user-images.githubusercontent.com/4822313/206711618-27c329b4-e873-4daf-a106-1a19a32e0048.mov
=> LG-7494 Add text and translations to Please Verify

app/controllers/users/two_factor_authentication_controller.rb, app/services/irs_attempts_api/tracker_events.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb
=> LG-8220 Add Failure Reason to phone_otp_sent_event

app/controllers/application_controller.rb, spec/features/idv/steps/gpo_step_spec.rb, spec/support/features/session_helper.rb
=> LG-8178 GPO Pending and SP Password Reset Login

app/controllers/api/irs_attempts_api_controller.rb, app/services/analytics_events.rb, spec/controllers/api/irs_attempts_api_controller_spec.rb
changelog: Internal, Attempts API, logging and monitoring
[LG-7821](https://cm-jira.usa.gov/browse/LG-7821)
Added elapsed_time as a property to the analytics event: irs_attempts_api_events
=> added elapsed_time to analytics irs_attempts_api_events

app/controllers/concerns/saml_idp_auth_concern.rb, app/controllers/saml_idp_controller.rb, spec/controllers/saml_idp_controller_spec.rb, spec/support/saml_auth_helper.rb
This reverts commit a7577b6de1355ae6f00f8e71ba2fc14e1db42c62.
=> Revert "LG-8432: SAML - Update ForceAuthn check (#7514)"

config/locales/instructions/en.yml, config/locales/instructions/es.yml, config/locales/instructions/fr.yml, spec/features/phone/default_phone_selection_spec.rb
[LG-8122](https://cm-jira.usa.gov/browse/LG-8122) & [LG-8438](https://cm-jira.usa.gov/browse/LG-8438)
Content changes related to OTP.
Test registration and login flows surrounding sms/phone call.
<details>
</details>
=> LG-8438: Update language on pages related to OTP

Makefile
Updates the `make lintfix` task so that it fixes ERB, javascript, and CSS files in addition to ruby files.
=> Make `lintfix` fix erb, javascript, and CSS files too

app/jobs/irs_attempts_events_batch_job.rb, spec/jobs/irs_attempts_events_batch_job_spec.rb
changelog: Internal, Attempts API, Events Batch Job Metrix
=> LG-7822 Attempt Events Background Job Metrix

package.json, yarn.lock
changelog: Internal, Dependencies, Upgrade Node dependencies to patch json5 security advisory
Upgrades `@babel/core` to address the vulnerability in `json5`:
```
--- yarn audit ---
yarn audit --groups dependencies; test $? -le 7
yarn audit v1.22.19
│ high          │ Prototype Pollution in JSON5 via Parse Method                │
│ Package       │ json5                                                        │
│ Patched in    │ >=2.2.2                                                      │
├───────────────┼──────────────────────────────────────────────── …
```
=> Upgrade Node dependencies to patch json5 security advisory

app/controllers/idv/gpo_verify_controller.rb
=> LG-8221 Fix GPO Rate Limit Event

Gemfile.lock
changelog: Internal, Security, Update PG dependency to allow build
=> Update PG in Gemfile.lock

app/services/account_reset/grant_requests_and_send_emails.rb
This job can be quite long running and should be in the long running queue so it can make use of the alarms/monitoring related to that queue.
=> Move Account Reset job to long running queue

config/country_dialing_codes.yml, config/pinpoint_overrides.yml, config/pinpoint_supported_countries.yml, spec/features/two_factor_authentication/sign_in_spec.rb, spec/forms/idv/phone_form_spec.rb, spec/services/phone_number_capabilities_spec.rb
This is not a net change in behavior, just a refresh to more closely match our dynamic configurations.
=> Update Pinpoint override configuration to more closely match deployed environments

app/jobs/irs_attempts_events_batch_job.rb, app/jobs/reports/base_report.rb
changelog: Internal, Attempts API, Integrating with s3
=> LG-8421 Designate client for new 'S3_Resource's

app/jobs/reports/daily_auths_report.rb, spec/jobs/reports/daily_auths_report_spec.rb
[Slack thread for context](https://gsa-tts.slack.com/archives/C5E7EJWF7/p1673287141100929?thread_ts=1672944571.408869&cid=C5E7EJWF7)
**Why**: so that checking our dashboards matches what we bill on
**Note**: this will require backfilling the report for consistency after deploy
=> Update daily report for data.login.gov to use "billable" data

db/primary_migrate/20230109171633_add_index_to_status_check_attempted_at_in_person_enrollments.rb, db/schema.rb
[Lg-8283](https://cm-jira.usa.gov/browse/LG-8283)
Add index for status_check_attempted_at column in InPersonEnrollments table to improve query time.
=> Lg-8283 add index to status_check_attempted_at

app/services/data_requests/lookup_shared_device_users.rb, spec/lib/data_requests/lookup_shared_device_users_spec.rb
=> Reduce default shared device lookup depth for data requests

app/jobs/reports/daily_auths_report.rb, app/services/db/monthly_sp_auth_count/total_monthly_auth_counts.rb, app/services/db/monthly_sp_auth_count/total_monthly_auth_counts_within_iaa_window.rb, app/services/db/monthly_sp_auth_count/unique_monthly_auth_counts_by_iaa.rb, db/primary_migrate/20230113202352_create_sp_return_logs_returned_at_date_issuer_index.rb, db/primary_migrate/20230113202809_remove_sp_return_logs_requested_at_date_issuer_index.rb, db/schema.rb, spec/jobs/reports/total_monthly_auths_report_spec.rb
[See 📝  SBAR for additional context](https://docs.google.com/document/d/1jXuRJNocY5P_bcOJTWu9rpbRyPVfc55sFN7lqROcBRE/edit#)
[LG-8623](https://cm-jira.usa.gov/browse/LG-8623)
Updates reporting to work around a recently-discovered but where `requested_at` is occasionally set to very far in the past ([LG-8625](https://cm-jira.usa.gov/browse/LG-8625))
=> Update reports to use returned_at instead of requested_at (LG-8623)

lib/good_job_connection_pool_size.rb, spec/lib/good_job_connection_pool_size_spec.rb
Follow up to #7636 that fixes a bug because I didn't write enough tests! This PR adds the fix and regression specs.
=> Fix bug in calculating database connection pool sizes for workers

app/components/one_time_code_input_component.html.erb, config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml, spec/features/two_factor_authentication/sign_in_spec.rb
[LG-8067](https://cm-jira.usa.gov/browse/LG-8067)
Screenshots
<details>
English
Spanish
</details>
=> LG-8067: Add OTP validation message

lib/pinpoint_supported_countries.rb
=> Add Mexico to the list of Sender ID countries

lib/pinpoint_supported_countries.rb
- Telephony: Add Mexico to the list of Sender ID countries ([#7664](https://github.com/18F/identity-idp/pull/7664))
=> Deploy RC 244.2 to Production

app/services/doc_auth/lexis_nexis/responses/true_id_response.rb, spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb
This field was accidentally left off as part of #7646
=> Log an additional classification detail

app/javascript/packages/document-capture/components/acuant-capture.tsx, app/javascript/packages/document-capture/components/file-input.tsx
[LG-8030](https://cm-jira.usa.gov/browse/LG-8030)
Conversion of the FileInput React component file to Typescript.
=> LG-8030 FileInput Component to Typescript

app/javascript/packages/document-capture/components/file-input.tsx
Follow up to #7700, implementing some of the changes suggested [here](https://github.com/18F/identity-idp/pull/7700#discussion_r1087862356).
=> LG-8030 Follow Up

Gemfile, Gemfile.lock, app/controllers/idv/verify_info_controller.rb, app/forms/register_user_email_form.rb, app/javascript/packages/document-capture/components/file-input.tsx, config/initializers/rack_timeout.rb, config/locales/doc_auth/en.yml, spec/controllers/idv/verify_info_controller_spec.rb, spec/forms/register_user_email_form_spec.rb
- Doc Auth: Fix typo in translation file. ([#7704](https://github.com/18F/identity-idp/pull/7704))
- Email: Do not send registration emails to invalid email addresses ([#7708](https://github.com/18F/identity-idp/pull/7708))
- Flow State Machine: Check throttles in VerifyInfo controller ([#7705](https://github.com/18F/identity-idp/pull/7705))
- Logging: Reduce Rack::Timeout logging to Error level ([#7697](https://github.com/18F/identity-idp/pull/7697))
- Security: Update zxcvbn gem ([#7714](https://github.com/18F/identity-idp/pull/7714))
=> Deploy RC 247 to Production

config/locales/in_person_proofing/en.yml, config/locales/in_person_proofing/es.yml, config/locales/in_person_proofing/fr.yml
Example address text should now read: 1234 N Example St., Allentown, PA 12345
Previous text was:  1960 W Chelsea Ave Allentown PA 18104
<details>
</details>
<details>
</details>
=> LG-8503: Add commas to example search text

app/controllers/account_reset/cancel_controller.rb, spec/controllers/account_reset/cancel_controller_spec.rb
changelog: Internal, Attempts API,  Account reset cancel request event
=> LG-8522: Account reset cancel request event

app/controllers/idv/in_person/address_search_controller.rb, app/javascript/packages/document-capture/components/address-search.tsx, app/javascript/packages/document-capture/components/in-person-location-post-office-search-step.spec.tsx, app/javascript/packages/document-capture/components/in-person-location-post-office-search-step.tsx, app/services/analytics_events.rb, spec/controllers/idv/in_person/address_search_controller_spec.rb
[Link to the relevant ticket.](https://cm-jira.usa.gov/browse/LG-8808)
- User now sees "try again" error message when the request to ArcGIS API errs
=> LG-8808: display try again message when ArcGIS API errs

spec/services/idv/steps/verify_wait_step_show_spec.rb
=> Followup change to LG-8257

app/controllers/users/verify_password_controller.rb, spec/controllers/users/verify_password_controller_spec.rb
=> LG-8532 Shore up IDV Account Reactivation Events

app/presenters/openid_connect_user_info_presenter.rb, spec/features/openid_connect/openid_connect_spec.rb
Patches #7791 in to production to stem issues partners are experiencing
=> Deploy RC 250.1 to Prod

app/views/idv/doc_auth/agreement.html.erb, app/views/idv/doc_auth/welcome.html.erb, app/views/idv/shared/_ssn.html.erb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml
[LG-8809](https://cm-jira.usa.gov/browse/LG-8809)
Update privacy-related "Learn more" links in IdV to be more accessible, expanding them out to a full sentence instead of just the text "Learn More".
<details>
<summary>English</summary>
<table>
<tr>
<th>Page</th>
<th>Screenshot</th>
</tr>
<tr>
<td>Welcome</td>
<td>
</td>
</tr>
<tr>
<td>Getting started</td>
<td>
</td>
</tr>
<tr>
<td>SSN</td>
<td>
</td>
</tr>
</table>
</details>
<details>
<summary>Spanish</summary>
<table>
<tr>
<th>Page</th>
<th>Screenshot</th>
</tr>
<tr>
<td>Welcome</td>
<td>
</td>
</tr>
<tr>
<td>Getting started</td>
<td>
</td>
</tr>
<tr>
<td>SSN</td>
<td>
</td>
</tr>
</table>
</details>
<details>
<summary>French</summary>
<table>
<tr>
<th>Page</th> …
=> LG-8809: Improve a11y of "Learn more" links in IdV

app/views/idv/gpo_verify/index.html.erb, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml
changelog: User-Facing Improvements, IdV GPO, Updated text for come_back_later
=> LG-7144 UI fixes

app/services/analytics.rb, spec/controllers/openid_connect/user_info_controller_spec.rb, spec/services/analytics_spec.rb
After discussing this a bit with @jmhooper this morning, it didn't appear that these values were used in any analytics, dashboards, etc. so it should be safe to remove them.
=> Remove unused analytics data in session

Gemfile, Gemfile.lock, app/components/base_component.rb, app/views/layouts/component_preview.html.erb, spec/components/base_component_spec.rb, spec/components/previews/base_component_preview.rb, spec/components/previews/step_indicator_component_preview.rb, spec/components/previews/validated_field_component_preview.rb
Includes a handful of fixes and maintenance tasks related to the [component preview environment](https://idp.dev.identitysandbox.gov/components/):
* Bump Lookbook and ViewComponent dependencies to latest versions
* Fix truncated preview white background when scrollbar present
* Hide "Base" component superclass from preview navigation
* Update Step Indicator preview to show selected step
* Fix error for Validated Field workbench "Email" input type
* Show Validated Field text input as single-line text, not textarea
1. Go to http://localhost:3000/components/
2. Observe all revisions noted above
=> Improve component previews and upgrade related dependencies

app/controllers/concerns/two_factor_authenticatable_methods.rb
Inspired by https://github.com/18F/identity-idp/pull/7868#discussion_r1114666505
=> Unpack a dynamic send to make code easier to trace

app/views/idv/doc_auth/_combined_upload.html.erb
h/t @aduth
changelog: Internal, Styling, Combinded Hybrid Screen Styling
=> Fixing missed grid gap sizing (follow up to LG-8901)

app/services/google_policy_site.rb, app/views/shared/_recaptcha_disclosure.html.erb, config/locales/two_factor_authentication/en.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml, spec/views/phone_setup/index.html.erb_spec.rb
Adds translations for the Google Recaptcha on the phone screen.
=> Lg 8796 add translations for Google Disclosure on recaptcha

app/controllers/concerns/two_factor_authenticatable_methods.rb, spec/presenters/two_factor_auth_code/phone_delivery_presenter_spec.rb
- Authentication: Fix "Choose another authentication method" link on phone setup confirmation step
=> Deploy RC 256.1 to Prod

app/views/layouts/user_mailer.html.erb, config/locales/mailer/en.yml, config/locales/mailer/es.yml, config/locales/mailer/fr.yml
- Emails: Add sent at timestamp to email footers ([#7886](https://github.com/18F/identity-idp/pull/7886))
=> Deploy RC 256.2 to Production

Makefile
Now these tasks will show up in `make help`
=> Add additional Makefile documentation

app/controllers/sign_up/completions_controller.rb, spec/controllers/sign_up/completions_controller_spec.rb
changelog: Internal, Attempts API, Fixes in tracking event
=> LG-8215 Update Event: IDV Reproof - logs two events

app/jobs/reports/duplicate_ssn_report.rb, config/initializers/job_configurations.rb, spec/jobs/reports/duplicate_ssn_report_spec.rb
[LG-9191](https://cm-jira.usa.gov/browse/LG-9191)
Adds a new daily report for the fraud team that matches this [Google Sheets template](https://docs.google.com/spreadsheets/d/1GZ9sCHeZtowpCH65LdjxrQVWaV12nAciZZXgaOUf8jY/edit#gid=0)
=> Add report that monitors duplicate SSNs (LG-9191)

Gemfile.lock
This update includes a few changes for more comprehensive checks with [Rails 7](https://github.com/presidentbeef/brakeman/blob/main/CHANGES.md#541---2023-02-21)
=> Update brakeman gem

app/services/user_event_creator.rb
This PR wraps a couple coupled database writes in a single transaction for both improved consistency and performance.
=> Reduce device/event transactions by wrapping multiple writes in one transaction

app/views/idv/shared/_ssn.html.erb, app/views/idv/ssn/show.html.erb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml
[LG-9020](https://cm-jira.usa.gov/browse/LG-9020)
Updated content in first paragraph to reflect milestone 2 changes. Content update made to shared ssn view as well as remote flow ssn view.
<details>
<summary>Before En:</summary>
</details>
<details>
<summary>After En:</summary>
</details>
<details>
<summary>Before Es:</summary>
</details>
<details>
<summary>After Es:</summary>
</details>
<details>
<summary>Before Fr:</summary>
</details>
<details>
<summary>After Fr:</summary>
</details>
<details>
<summary>Remote flow</summary>
</details>
=> LG-9020 update ssn content

app/components/phone_input_component.html.erb, app/javascript/packages/phone-input/index.spec.ts, app/javascript/packages/phone-input/index.ts, spec/features/two_factor_authentication/sign_in_spec.rb
[LG-9023
](https://cm-jira.usa.gov/browse/LG-9023)
Removes phone number example text per design request.
=> LG-9023: Remove phone helper text

app/controllers/redirect/policy_controller.rb, app/services/analytics_events.rb, config/routes.rb, config/service_providers.localdev.yml, spec/controllers/redirect/contact_controller_spec.rb, spec/controllers/redirect/policy_controller_spec.rb
=> Lg 9089 user data ack

lib/tasks/review_profile.rake, lib/tasks/users_lookup.rake, spec/lib/tasks/review_profile_spec.rb
- Utilities: Request more information from users when calling investigative rake tasks ([#8001](https://github.com/18F/identity-idp/pull/8001))
=> Deploy RC 262.1

app/controllers/application_controller.rb, app/controllers/idv/image_uploads_controller.rb, app/jobs/irs_attempts_events_batch_job.rb, spec/services/irs_attempts_api/attempt_event_spec.rb, spec/services/irs_attempts_api/tracker_spec.rb
changelog: Internal, Attempts API, Rename Vars
=> Standardaize usage of Attempts vs. Attempt

app/controllers/event_disavowal_controller.rb
- Authentication: Fully sign out user when resetting password via event disavowal ([#8042](https://github.com/18F/identity-idp/pull/8042))
=> Deploy RC 264.1 to Production

app/controllers/idv/setup_errors_controller.rb, app/views/idv/setup_errors/show.html.erb, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml, spec/controllers/idv/setup_errors_controller_spec.rb, spec/views/idv/setup_errors/show.html.erb_spec.rb
LG-9152
Notify user to call by two weeks after being put in fraud review.
=> LG-9152 add call-by date to fraud review screen

lib/reporting/command_line_options.rb, spec/lib/reporting/command_line_options_spec.rb
See [Slack conversation](https://gsa-tts.slack.com/archives/C01SU3NB9T3/p1679514077083549?thread_ts=1679420203.210389&cid=C01SU3NB9T3) for confirmation
=> Update weekly Cloudwatch specs for clarity

config/locales/step_indicator/en.yml, config/locales/step_indicator/es.yml, config/locales/step_indicator/fr.yml
[LG-9173](https://cm-jira.usa.gov/browse/LG-9173)
Update to language in verify info portion of the StepIndicator
<details>
</details>
<details>
</details>
<details>
</details>
=> LG-9173 Updating verify info language in StepIndicator

config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml
[Link to the relevant ticket.
](https://cm-jira.usa.gov/browse/LG-9051)
Replace copy, plus translations
=> Lg 9051 new copy

config/service_providers.localdev.yml
changelog: Internal, Attempts API, Local development configs
=> LG-9220 Update languages for Local testing of SPs

app/controllers/saml_completion_controller.rb, config/application.yml.default, spec/controllers/saml_completion_controller_spec.rb
We've gotten a handful of unhandled exceptions here from not being quite as strict as we could be ([NewRelic](https://one.newrelic.com/nr1-core/errors/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=259200000&state=5d32d670-229a-c18e-e4ca-44dc8b66a86d)). This PR adds additional validation to ensure the route we are generating exists and is on the controller/action we expect.
=> Fix SamlCompletionController 500 (LG-8837)

spec/jobs/irs_attempts_events_batch_job_spec.rb
changelog: Internal, Attempts API, Batch Job improvements
=> LG-9146 Fix intermittent infinity loop

app/jobs/reports/base_report.rb, app/jobs/reports/sp_user_counts_report.rb, lib/identity_job_log_subscriber.rb, spec/jobs/reports/sp_user_counts_report_spec.rb
[LG-9415](https://cm-jira.usa.gov/browse/LG-9415)
Originally added in #5744, has been unused
=> Stop writing data to reports.log (LG-9415)

app/services/backup_code_generator.rb, spec/services/backup_code_generator_spec.rb
We got a couple 500 errors ([NewRelic](https://onenr.io/0KQXpGx75Qa)) because we try to do string operations on `nil` in this function.
=> Fix error when verifying nil backup code

app/controllers/saml_post_controller.rb, spec/controllers/saml_completion_controller_spec.rb, spec/controllers/saml_post_controller_spec.rb
=> Revert "Add safer parsing of dynamic SAML urls (LG-8837)"

app/controllers/saml_post_controller.rb, spec/controllers/saml_completion_controller_spec.rb, spec/controllers/saml_post_controller_spec.rb
- SAML: Fix a problem with SAML signature validation errors ([#8181](https://github.com/18F/identity-idp/pull/8181))
=> Deploy RC 271 to Prod (continued)

Gemfile.lock
Patches new release to address https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-pxvg-2qj5-37jq
=> Update nokogiri to patch reported vulnerability

config/locales/in_person_proofing/es.yml, config/locales/in_person_proofing/fr.yml
changelog: User-Facing Improvements, In-person proofing, French and Spanish language text update in PO locations
=> LG-8500: Minor copy update for French and Spanish language selection

db/schema.rb
=> Update schema timestamp

app/controllers/two_factor_authentication/otp_verification_controller.rb, app/controllers/two_factor_authentication/webauthn_verification_controller.rb, app/controllers/users/piv_cac_login_controller.rb, app/presenters/two_factor_auth_code/authenticator_delivery_presenter.rb, app/presenters/two_factor_auth_code/piv_cac_authentication_presenter.rb, config/locales/instructions/en.yml, config/locales/instructions/es.yml, config/locales/instructions/fr.yml, spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
=> Fix 500 due to undefined two_factor_authentication_method method

README.md, docs/local-development.md, docs/mobile.md
[LG-9361](https://cm-jira.usa.gov/browse/LG-9361)
Document mobile development / testing steps
Co-authored-by: Eric Gade <eric.gade@gsa.gov>
=> Jskinne3 lg 9361 mobile local md

app/javascript/packages/document-capture/components/back-button.spec.tsx, app/javascript/packages/document-capture/components/back-button.tsx
changelog: User-Facing Improvements, In-person proofing, Added Aria Label to the back button in PO locations
=> LG-8565: Screen reader: Fix back button reading

README.md, docs/sdk-upgrade.md, scripts/generate_readme.rb
[https://cm-jira.usa.gov/browse/LG-9414](https://cm-jira.usa.gov/browse/LG-9414)
Instructions on how to upgrade the Acuant SDK, linked from the repo README
=> Jskinne3 lg 9414 upgrade sdk instructions

spec/services/idv/steps/in_person/state_id_step_spec.rb
changelog: Internal, Bug Fixes, update state id step spec
Fixes: https://gitlab.login.gov/lg/identity-idp/-/jobs/425732
=> Test against new local address variables

app/views/idv/address/new.html.erb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml
https://cm-jira.usa.gov/browse/LG-9527
PR PR = Puerto Rico Pull Request
- Exchange position of h1 and banner
- Change text in 3 languages
Perform workflow using (or switching to) a Puerto Rico address and verify banner looks like [the figma](https://www.figma.com/file/rVSsBQD594Sqj9LE1Iwu6b/PR-address-edit?node-id=209-1177)
=> Jskinne3 lg 9527 update puerto rico banner

Gemfile.lock, spec/services/usps_in_person_proofing/transliterator_spec.rb
Updates i18n to bring in some performance improvements.
https://github.com/ruby-i18n/i18n/pull/627 includes a few transliteration changes, and I've done my best to adjust the specs for our transliteration accordingly.
=> Update i18n gem

docs/sdk-upgrade.md
changelog: Internal, Documentation, updating SDK upgrade documentation
=> SDK Upgrade Docs Final Steps

app/javascript/packages/document-capture/components/document-capture-troubleshooting-options.spec.tsx, app/javascript/packages/document-capture/components/document-capture-troubleshooting-options.tsx, app/javascript/packages/document-capture/components/review-issues-step.tsx, spec/javascript/packages/document-capture/components/review-issues-step-spec.jsx
[LG-9297](https://cm-jira.usa.gov/browse/LG-9297)
Add the standard IdV cancel link to the Verify ID warning page (review-issues component), and remove extra link to SP.
<details>
</details>
<details>
</details>
=> LG-9297 Add Cancel Link

app/controllers/idv/session_errors_controller.rb, app/views/idv/session_errors/throttled.html.erb, spec/controllers/idv/session_errors_controller_spec.rb
- Identity Verification: Do not show step indicator concern in hybrid flow ([#8339](https://github.com/18F/identity-idp/pull/8339))
This Brings in a Fix for https://github.com/18F/identity-idp/pull/8291
=> Deploy RC 277.1 to Prod

config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml
[LG-9646](https://cm-jira.usa.gov/browse/LG-9646) [LG-9647](https://cm-jira.usa.gov/browse/LG-9647) [LG-9649](https://cm-jira.usa.gov/browse/LG-9649)
Update success banners on the SSN page, Verify Phone page, and Personal Key pages. (The banner update for LG-9648 turned out to be a bit more involved, so it will have its own PR.)
<details>
<summary>Ssn page</summary>
</details>
<details>
<summary>Verify phone page</summary>
</details>
<details>
<summary>Personal Key page</summary>
</details>
=> LG-9646 LG-9647 LG-9649 success banners

lib/pinpoint_supported_countries.rb
- Telephony: Fix telephony deliverability for France ([#8419](https://github.com/18F/identity-idp/pull/8419))
=> Deploy RC 280.1 to Prod

app/controllers/concerns/idv/document_capture_concern.rb, app/controllers/idv/document_capture_controller.rb, app/controllers/idv/hybrid_mobile/document_capture_controller.rb, app/controllers/idv/link_sent_controller.rb
=> remove effective user from document capture concern

app/controllers/concerns/remember_device_concern.rb, app/services/analytics_events.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb
Small logging change to help us better understand how remembered device is used.
=> Log expiration of remembered device cookie when it is used

app/views/idv/gpo_verify/index.html.erb
[LG-9662](https://cm-jira.usa.gov/browse/LG-9662)
Swap order of start over link and view profile link.
<details>
</details>
<details>
</details>
=> LG-9662: Welcome back screen should have updated link order

spec/features/idv/steps/gpo_step_spec.rb
[LG-9883](https://cm-jira.usa.gov/browse/LG-9883)
Our existing Verify by Mail feature specs cover up to "Come Back Later" and then a separate set of specs covers entering the OTP. This spec covers issues where the profile data generated and expected don't match in the two parts of the process. This extends an existing feature spec rather than adding another long spec.
I checked, and this test would have caught the issue with deactivation reason that we fixed in #8442 on Friday.
=> LG-9883 Add a full end to end GPO feature test

app/controllers/idv/link_sent_controller.rb, spec/controllers/idv/link_sent_controller_spec.rb
Test the update action method in the LinkSentController
=> Test LinkSentController update action

app/mailers/user_mailer.rb, app/views/user_mailer/in_person_outage_notification.html.erb, config/locales/user_mailer/en.yml, config/locales/user_mailer/es.yml, config/locales/user_mailer/fr.yml, spec/mailers/previews/user_mailer_preview.rb
[LG-9901](https://cm-jira.usa.gov/browse/LG-9901)
Adds outage email template
<details>
<summary>English</summary>
</details>
<details>
<summary>Spanish</summary>
</details>
<details>
<summary>French</summary>
</details>
=> LG-9901: Add outage email template

app/controllers/idv/document_capture_controller.rb
=> document capture controller use document_capture_session_uuid for consistency

app/controllers/concerns/idv/document_capture_concern.rb, app/controllers/concerns/idv/hybrid_mobile/hybrid_mobile_concern.rb, app/controllers/idv/document_capture_controller.rb, app/controllers/idv/hybrid_mobile/document_capture_controller.rb, app/controllers/idv/link_sent_controller.rb
[LG-9756](https://cm-jira.usa.gov/browse/LG-9756)
Create DocumentCaptureConcern to remove duplicate code in DocumentCapture controllers and LinkSentController.
=> LG-9756: Create a document capture concern for post-FSM world

app/services/service_provider_seeder.rb
Resolves LG-6146
changelog: Internal, Deployment, Remove ERB processing of configuration file
Follow-up to #7742, should only be merged after https://github.com/18F/identity-idp-config/pull/1256 is merged
=> [LG-6146] Remove ERB processing when reading service_providers.yml

spec/controllers/idv/agreement_controller_spec.rb, spec/features/idv/doc_auth/agreement_spec.rb
Crossed paths with PR #8563 Disable RSpec monkeypatching.
=> Add RSpec in front of describe and feature

app/views/idv/agreement/show.html.erb, spec/features/idv/doc_auth/agreement_spec.rb
[LG-10016](https://cm-jira.usa.gov/browse/LG-10016) addendum
<details>
</details>
=> Add step indicator to new Agreement template

lib/action_account.rb, lib/script_base.rb, spec/lib/action_account_spec.rb
=> LG-100069 Add Messages to Slack Output

lib/action_account.rb, lib/script_base.rb, spec/lib/action_account_spec.rb
=> LG-100069 Adjust Slack Message Formatting

app/controllers/idv/agreement_controller.rb, spec/controllers/idv/agreement_controller_spec.rb
[LG-10017](https://cm-jira.usa.gov/browse/LG-10017)
=> LG-10017 Removing 404 from agreement step

app/controllers/concerns/idv/verify_info_concern.rb, app/controllers/idv/hybrid_mobile/document_capture_controller.rb, app/controllers/idv/otp_verification_controller.rb, app/controllers/idv/personal_key_controller.rb, app/controllers/idv/phone_controller.rb, app/controllers/idv/review_controller.rb, app/javascript/packs/form-steps-wait.tsx, app/views/idv/hybrid_mobile/capture_complete/show.html.erb, app/views/idv/phone/new.html.erb, spec/controllers/idv/personal_key_controller_spec.rb, spec/controllers/idv/review_controller_spec.rb, spec/features/idv/steps/phone_step_spec.rb, spec/features/idv/steps/review_step_spec.rb
=> LG-9700 Success Banners as Flash Messages

lib/action_account.rb, spec/lib/action_account_spec.rb
=> LG-9799: Update action-account script to add Account Suspension subtask

config/application.rb, config/application.yml.default, lib/identity_config.rb, lib/version_headers.rb
Small PR based on brief discussion in Slack [here](https://gsa-tts.slack.com/archives/C0NGESUN5/p1685021996984229)
=> Add configuration for including git SHA in response headers

app/models/user.rb, lib/script_base.rb, spec/lib/action_account_spec.rb, spec/models/user_spec.rb
[Link to the relevant ticket.
](https://cm-jira.usa.gov/browse/LG-9929)
=> LG-9929 Log suspended user out of active sessions

lib/action_account.rb, lib/script_base.rb, spec/lib/action_account_spec.rb
=> Lg 100069 slack message formatting

spec/features/idv/doc_auth/redo_document_capture_spec.rb
These tests have been a bit flaky recently, so this PR disables them for now.
=> Disable flaky tests until they can be fixed

config/locales/forms/en.yml
closes #8663 
Change `lettter` to `letter`
=> fix: fix letter typo

.rubocop.yml, lib/makefile_help_parser.rb
Disable the IfUnlessModifier because it is annoying
=> Disable the IfUnlessModifier cop

app/mailers/user_mailer.rb, app/services/send_sign_up_email_confirmation.rb, app/views/user_mailer/suspended_create_account.html.erb, config/locales/user_mailer/en.yml, config/locales/user_mailer/es.yml, config/locales/user_mailer/fr.yml, spec/mailers/previews/user_mailer_preview.rb, spec/mailers/user_mailer_spec.rb, spec/services/request_password_reset_spec.rb, spec/services/send_sign_up_email_confirmation_spec.rb
changelog: User-Facing Improvements, Suspension, Add email send on create account
https://cm-jira.usa.gov/browse/LG-10214
=> LG-10214 Suspended User Create Account Flow

app/controllers/concerns/idv_step_concern.rb, app/controllers/idv/agreement_controller.rb, app/controllers/idv/document_capture_controller.rb, app/controllers/idv/hybrid_handoff_controller.rb, app/controllers/idv/link_sent_controller.rb, app/controllers/idv/verify_info_controller.rb
[LG-9335](https://cm-jira.usa.gov/browse/LG-9335)
Remove references of flow_path stored in flow_session which were maintained for IcV continuity during the 50/50 state.
=> LG-9335 - post release 50 50 cleanup

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_modal.scss
- Session Timeout: Fix appearance of session timeout modal ([#8743](https://github.com/18F/identity-idp/pull/8743))
=> Deploy RC 294.1 to Prod

app/controllers/concerns/idv/hybrid_mobile/hybrid_mobile_concern.rb, spec/controllers/idv/hybrid_mobile/document_capture_controller_spec.rb
- Hybrid Flow Document Capture: Delete session data when hybrid session is invalid ([#8747](https://github.com/18F/identity-idp/pull/8747))
=> Deploy RC 294.2 to Production

app/forms/backup_code_verification_form.rb, spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb
Adds 0951555766d0ff289b87b54840d322f79dfe9916 to https://github.com/18F/identity-idp/pull/8748
=> Deploy RC 295.1 to Prod

app/views/idv/gpo_only_warning/show.html.erb, config/locales/vendor_outage/en.yml, config/locales/vendor_outage/es.yml, config/locales/vendor_outage/fr.yml
[LG-9526](https://cm-jira.usa.gov/browse/LG-9526)
Updated the pinpoint/phone finder outage error screen text.
<details>
</details>
<details>
</details>
<details>
</details>
=> LG-9526 pinpoint outage error page updates

app/views/idv/shared/_document_capture.html.erb, config/application.yml.default, lib/identity_config.rb
- In-Person Proofing: Add flag for UI flow ([#8787](https://github.com/18F/identity-idp/pull/8787))
=> Deploy RC 296.1

app/forms/register_user_email_form.rb, app/services/send_sign_up_email_confirmation.rb, spec/forms/register_user_email_form_spec.rb, spec/services/send_sign_up_email_confirmation_spec.rb
changelog: User-Facing Improvements, Suspension, Add email send on create account
https://cm-jira.usa.gov/browse/LG-10214
=> LG-10214 Move Suspended User Create Account Email

config/application.yml.default
[LG-10128](https://cm-jira.usa.gov/browse/LG-10288): remove duplicated entries
Remove several doc auth related duplicates from application.yml.default.
No specific additional testing is needed, original test suites should cover.
=> LG-10288: Remove duplication of doc_auth_* threshold variables from application.yml

app/javascript/packages/components/index.ts, app/javascript/packages/components/select-input.spec.tsx, app/javascript/packages/components/select-input.tsx, app/javascript/packages/document-capture/components/document-capture.tsx, app/javascript/packages/document-capture/components/in-person-full-address-search.spec.tsx, app/javascript/packages/document-capture/components/in-person-full-address-search.tsx, app/javascript/packages/document-capture/components/in-person-location-full-address-entry-post-office-search-step.spec.tsx, app/javascript/packages/document-capture/components/in-person-location-full-address-entry-post-office-search-step.tsx, app/javascript/packages/document-capture/components/in-person-location-post-office-search-step.spec.tsx, app/javascript/packages/document-capture/components/in-person-outage-alert.spec.tsx, app/javascript/packages/document-capture/components/in-person-prepare-step.spec.tsx, app/javascript/packages/document-capture/components/select-error.scss, app/javascript/packages/document-capture/context/in-person.ts, app/javascript/packages/document-capture/styles.scss, app/javascript/packages/form-steps/form-steps.tsx, app/javascript/packages/validated-field/validated-field.spec.tsx, app/javascript/packages/validated-field/validated-field.tsx, app/javascript/packs/document-capture.tsx, app/views/idv/shared/_document_capture.html.erb, config/application.yml.default, config/locales/in_person_proofing/en.yml, config/locales/in_person_proofing/es.yml, config/locales/in_person_proofing/fr.yml, lib/identity_config.rb, spec/features/idv/in_person_spec.rb, spec/support/features/in_person_helper.rb
- In-person full address entry: Add full address PO search form ([#8808](https://github.com/18F/identity-idp/pull/8808), [#8829](https://github.com/18F/identity-idp/pull/8829))
=> Deploy RC 298.1 to Prod

spec/services/email_normalizer_spec.rb
Follow-up to #8818
I realized that locally, we run without `RAILS_OFFLINE` but in CI we run with it on, which could lead to a split of behaviors. 
Adding these extra steps stubs the ENV to give us a bit more branch coverage and consistent behavior
=> Increase code coverage for offline mode of EmailNormalizer

spec/forms/backup_code_verification_form_spec.rb
[LG-10314](https://cm-jira.usa.gov/browse/LG-10314)
Adds tests for BackupCodeVerificationForm.
=> LG-10314:  Add test coverage for BackupCodeVerificationForm

app/forms/openid_connect_authorize_form.rb, app/forms/openid_connect_token_form.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/openid_connect/token_controller_spec.rb, spec/forms/openid_connect_authorize_form_spec.rb, spec/forms/openid_connect_token_form_spec.rb
To better understand PKCE usage across partner applications, this PR adds extra analytics to both OIDC Authorization and Token requests
=> Add logging of PKCE usage

config/locales/in_person_proofing/es.yml
[LG-10080](https://cm-jira.usa.gov/browse/LG-10080)
Update Spanish translations for 3 strings on state-issued id page
<details>
</details>
<details>
</details>
=> LG-10080 Update  es translations on state-issued id page

config/locales/two_factor_authentication/en.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml
[LG-10455](https://cm-jira.usa.gov/browse/LG-10455)
The content change is visible from two routes:
- `/authentication_methods_setup`
- `/second_mfa_setup`
=> LG-10455: Change MFA selector description of face or touch unlock

app/controllers/idv/in_person/ssn_controller.rb, spec/controllers/idv/in_person/ssn_controller_spec.rb
[LG-10185](https://cm-jira.usa.gov/browse/LG-10185)
Remove 404 for ssn page
=> LG-10185 remove 404 for ssn page

config/locales/in_person_proofing/es.yml
[LG-10088](https://cm-jira.usa.gov/browse/LG-10088)
Remove double period 
=> LG-10088 update es barcode

config/locales/step_indicator/es.yml, config/locales/step_indicator/fr.yml
[LG-10087](https://cm-jira.usa.gov/browse/LG-10087)
Update es and fr translations for the step indicator. 
Es:
Fr:
<details>
<summary>Es Before:</summary>
</details>
<details>
<summary>Es After:</summary>
</details>
<details>
<summary>Fr Before:</summary>
</details>
<details>
<summary>Fr After:</summary>
</details>
=> LG-10087 update strings step indicator

spec/forms/backup_code_verification_form_spec.rb
Fixes a build failure on main due to branch merge timing conflict between #8922 and #8891.
```
rspec spec/forms/backup_code_verification_form_spec.rb
```
=> Fix error on main with backup code spec

.gitlab-ci.yml
Swap the key to check from `.imageScanFindings.findings` to `imageScanFindings.enhancedFindings` to properly check length
=> changelog: Internal, Bug Fix, Updating scan check to enhancedFindings

app/javascript/packages/document-capture/components/document-capture-review-issues.tsx, app/javascript/packages/document-capture/components/document-capture-warning.tsx, app/javascript/packages/document-capture/components/documents-step.jsx, app/javascript/packages/document-capture/components/review-issues-step.tsx, app/javascript/packages/document-capture/components/tip-list.tsx, spec/javascript/packages/document-capture/components/review-issues-step-spec.jsx, spec/javascript/packages/document-capture/components/tip-list-spec.jsx
[LG-10363: cleaup ReviewIssuesStep ](https://cm-jira.usa.gov/browse/LG-10363
)
Consolidate logic of ReviewIssuesstep screen logic.
Minor refactor to a separate component showig capturing tips list.
=> LG-10363 review issues step cleanup

app/controllers/idv/hybrid_handoff_controller.rb, spec/controllers/idv/hybrid_handoff_controller_spec.rb, spec/features/idv/steps/review_step_spec.rb
[LG-10603](https://cm-jira.usa.gov/browse/LG-10603)
If a user visits the document capture redo after verify info complete, they are redirected to the next step.
=> LG-10603: 500 error in review controller because applicant is nil

.gitlab-ci.yml, config/application.yml.default.docker
Currently the output is the literal `$CI_ENVIRONMENT_SLUG` which is not the intent.
=> Fix output for running console in review application

.gitlab-ci.yml
Testing only - do not review or merge
=> Troubleshooting workflow triggers for review-app

.gitlab-ci.yml, charts/Chart.yaml, charts/templates/_helpers.tpl, charts/values.yaml
Helm chart in identity-idp-helm-chart has updated names of services. Gitlab-ci.yml needs to be updated with these same changes.
=> Updating .gitlab-ci.yml for chart name changes and testing

lib/telephony/otp_sender.rb, spec/lib/telephony/otp_sender_spec.rb
[LG-8289](https://cm-jira.usa.gov/browse/LG-8289)
Add a pause after the last OTP digit is announced.
[Listen to recording](https://drive.google.com/file/d/1_tDt0ldg3sOkDV7XYdmfzSGi9gw2xZdn/view?usp=drive_link)
=> LG-8289 OTP clarity

app/forms/security_event_form.rb, spec/controllers/risc/security_events_controller_spec.rb
This PR adds the event_type to the existing analytics call to help us better understand what types of events we are receiving
=> Log event_type for incoming RISC events

bin/oncall/download-piv-certs, bin/oncall/email-deliveries, bin/oncall/otp-deliveries, bin/query-cloudwatch, lib/reporting/cloudwatch_client.rb
- Tested with bin/query-cloudwatch, bin/oncall/*
=> One more attempt to fix requires for bin/ scripts

.gitlab-ci.yml
The existing one was deleted due to lifecycle policies (which we are continuing to tune). This PR should fix build issues while we work through that.
=> Update CI Docker image

app/models/suspended_email.rb, app/models/user.rb
Spotted this typo while reviewing #9153
=> Fix typo in SuspendedEmail class

lib/reporting/proofing_rate_report.rb
=> Tried reorganizing proofing rate report

app/controllers/concerns/idv/verify_info_concern.rb, app/controllers/concerns/idv_step_concern.rb, app/controllers/concerns/rate_limit_concern.rb, app/controllers/idv/in_person/ssn_controller.rb, app/controllers/idv/in_person/verify_info_controller.rb, app/controllers/idv/session_errors_controller.rb, app/controllers/idv/ssn_controller.rb, app/controllers/idv/verify_info_controller.rb, spec/controllers/concerns/rate_limit_concern_spec.rb, spec/controllers/idv/in_person/ssn_controller_spec.rb, spec/controllers/idv/in_person/verify_info_controller_spec.rb, spec/controllers/idv/session_errors_controller_spec.rb, spec/controllers/idv/ssn_controller_spec.rb, spec/controllers/idv/verify_info_controller_spec.rb
=> Revert "LG-10886 remove ssn from flow session"

lib/reporting/identity_verification_report.rb, lib/reporting/proofing_rate_report.rb, spec/lib/reporting/identity_verification_report_spec.rb, spec/lib/reporting/proofing_rate_report_spec.rb
Adds "industry rate" ([see definition](https://docs.google.com/document/d/1O6sw0_83EeOGX0QtUiYoHfm-m0VQCJqYQXgsgXuOU1M/edit#bookmark=id.budguol4yf)) to Proofing Rate Report
- Do not merge until #9186 is merged
- Redo of #9190
=> Add Industry Rate to Proofing Rate Report (LG-10621)

lib/reporting/proofing_rate_report.rb
- Runs queries for each 30d batch in parallel, combines them after
I'm not 100% sure of an effective way to test this, but existing tests pass so it was at least not a broken refactor!
=> Add additional parallellism to ProofingRateReport (LG-10621) 

.gitlab-ci.yml
Updates the image SHA to one that exists
=> Update CI image SHA

app/views/idv/review/new.html.erb
[LG-10919](https://cm-jira.usa.gov/browse/LG-10919)
Change banner margins to match Figma, followup to #9223.
=> Fix banner margins

app/javascript/packages/address-search/package.json
[LG-10785](https://cm-jira.usa.gov/browse/LG-10785?filter=-1)
Bumps the minor version so I can publish a new version of @18f/identity-address-search. This is a follow-up to #9234 (would've been nice to do it in that PR but I didn't think that far ahead).
=> LG-10785: Bump @18f/identity-address-search minor version

app/views/layouts/account_side_nav.html.erb, config/locales/account/en.yml, config/locales/account/es.yml, config/locales/account/fr.yml
[LG-10797](https://cm-jira.usa.gov/browse/LG-10797)
Deleted html markup for the Your Account dashboard banner area. Deleted YML localization text.
Before:
After:
=> LG-10797 Remove banner and link from Your Account dashboard for desktop

app/jobs/multi_region_kms_migration/profile_migration_job.rb, app/jobs/multi_region_kms_migration/user_migration_job.rb
We got a few alerts about the length of time needed to run these jobs, and this PR puts them on the long running job queue to fix that.
=> Queue KMS Migration Jobs as long running

app/assets/stylesheets/_uswds-core.scss, app/assets/stylesheets/utilities/_typography.scss, app/javascript/packages/clipboard-button/package.json, package.json, yarn.lock
Updates `@18f/identity-design-system` (the Login.gov Design System) to the latest version (from v7.0.1 to v8.0.0)
See release notes:
- [`@18f/identity-design-system@7.1.0`](https://github.com/18F/identity-design-system/releases/tag/v7.1.0)
- [`@18f/identity-design-system@8.0.0`](https://github.com/18F/identity-design-system/releases/tag/v8.0.0)
- [`@uswds/uswds@3.5.0`](https://github.com/uswds/uswds/releases/tag/v3.5.0)
- [`@uswds/uswds@3.6.0`](https://github.com/uswds/uswds/releases/tag/v3.6.0)
- [`@uswds/uswds@3.6.1`](https://github.com/uswds/uswds/releases/tag/v3.6.1)
Notable impact here may be the removal of explicit antialiasing effect on fonts, which may cause text to appear more bolded in certain browser combinations (especially Apple operating systems).
Verify that stylesheet …
=> Upgrade identity-design-system to v8.0.0

app/jobs/reports/monthly_key_metrics_report.rb, app/services/reporting/account_deletion_rate_report.rb, spec/jobs/reports/monthly_key_metrics_report_spec.rb, spec/services/reporting/account_deletion_rate_report_spec.rb
[Link to the relevant ticket.](https://cm-jira.usa.gov/browse/LG-10815)
=> LG-10815: Account deletion for monthly reporting

app/jobs/reports/monthly_key_metrics_report.rb, app/services/reporting/monthly_active_users_count_report.rb, spec/jobs/reports/monthly_key_metrics_report_spec.rb, spec/services/reporting/monthly_active_users_count_report_spec.rb
[Link to the relevant ticket.](https://cm-jira.usa.gov/browse/LG-11149)
=> LG-11149: Number of Monthly Active Users for monthly reporting

spec/mailers/previews/report_mailer_preview.rb
changelog: Internal, Reporting, Update Report Mailer Preview
https://cm-jira.usa.gov/browse/LG-11305
=> LG-11305 Get Report Mailer Preview up to date

app/jobs/reports/monthly_key_metrics_report.rb, spec/mailers/previews/report_mailer_preview.rb
The idea is that we replace each comment with the report as we complete them.
=> Organize mkmr reports

db/worker_jobs_migrate/20231018163220_create_good_job_executions.rb, db/worker_jobs_migrate/20231018163221_create_good_jobs_error_event.rb, db/worker_jobs_schema.rb
Follow-up to #9394 to silence deprecation warnings
=> Add good_job migrations for gem upgrade

config/locales/titles/en.yml, config/locales/titles/es.yml, config/locales/titles/fr.yml
[LG-10813](https://cm-jira.usa.gov/browse/LG-10813)
Revised localized text for heading on the It's been a year landing page.
=> LG-10813 Implement improvements to "it's been a year" landing page

app/jobs/reports/monthly_key_metrics_report.rb, config/application.yml.default, lib/identity_config.rb, spec/jobs/reports/monthly_key_metrics_report_spec.rb, spec/mailers/previews/report_mailer_preview.rb
1. Links to new handbook article (https://github.com/18F/identity-handbook/pull/475)
2. Updates recipients to include contractors (per Eng Huddle item)
| screenshot |
| --- |
| <img width="626" alt="Screenshot 2023-10-23 at 10 17 01 AM" src="https://github.com/18F/identity-idp/assets/458784/ec07b829-dbd6-4389-b887-89c746e89806"> |
=> Updates to Monthly Key Metrics Report

app/jobs/reports/base_report.rb, app/jobs/reports/sp_active_users_report.rb
Share fiscal year start date calculations
=> Fiscal Year Start Date Calculations with Calendar Service

Gemfile, Gemfile.lock
It looks like we removed usage in #7136 and it is no longer needed
=> Remove unused uglifier gem

config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml
[LG-11360](https://cm-jira.usa.gov/browse/LG-11360)
Update error message when the user enters the wrong code for verify by mail to use new 'verification code' language
<details>
|English|Spanish|French|
|--------|--------|---------|
|<img width="414" alt="Enter code error en" src="https://github.com/18F/identity-idp/assets/2381438/df539b9f-be30-44c1-b6ef-f6583f8c5ba8">|<img width="415" alt="Enter code error es" src="https://github.com/18F/identity-idp/assets/2381438/d5c70758-a825-444f-949a-4741b46377d5">|<img width="416" alt="Enter code error fr" src="https://github.com/18F/identity-idp/assets/2381438/af7b8864-7734-4813-baac-ff23cde31fd8">|
</details>
=> LG-11360 Update Enter Code error message for incorrect code

app/views/two_factor_authentication/sms_opt_in/new.html.erb, spec/controllers/two_factor_authentication/sms_opt_in_controller_spec.rb
- SMS Opt-In: Fix error for SMS opt-in missing title
=> Deploy RC 328.1 to Prod

app/jobs/reports/monthly_key_metrics_report.rb, app/services/calendar_service.rb, app/services/reporting/account_reuse_and_total_identities_report.rb, app/services/reporting/active_users_count_report.rb, config/initializers/job_configurations.rb, spec/mailers/previews/report_mailer_preview.rb, spec/services/calendar_service_spec.rb, spec/services/reporting/account_reuse_and_total_identities_report_spec.rb, spec/services/reporting/active_users_count_report_spec.rb
[LG-11156](https://cm-jira.usa.gov/browse/LG-11156)
- Updates report to run starting yesterday (makes datetime math easier)
- Adds fiscal quarter methods to CalendarService
| --- | --- |
| <img width="696" alt="Screenshot 2023-10-31 at 4 19 48 PM" src="https://github.com/18F/identity-idp/assets/458784/98ba0095-48c0-4417-be56-1492d047f6db">  | <img width="703" alt="Screenshot 2023-10-31 at 4 19 28 PM" src="https://github.com/18F/identity-idp/assets/458784/5024c8db-7c79-4298-8d27-c94108d06539"> |
=> Add cumulative quarterly counts to key metrics report (LG-11156)

app/jobs/reports/monthly_key_metrics_report.rb, app/services/db/identity/sp_active_user_counts.rb, app/services/reporting/active_users_count_report.rb, spec/jobs/reports/monthly_key_metrics_report_spec.rb, spec/services/db/identity/sp_active_user_counts_spec.rb, spec/services/reporting/active_users_count_report_spec.rb
[LG-11156](https://cm-jira.usa.gov/browse/LG-11156)
- Adds APG (Agency Priority Goals) version of active users report
- Adds a *separate* section to the MKMR email
| table | screenshot|
| --- | ---- |
| existing |  <img width="681" alt="Screenshot 2023-11-01 at 3 47 40 PM" src="https://github.com/18F/identity-idp/assets/458784/22e80f16-9ea5-4ca8-bc9f-a51e0f931c81"> |
| 🆕  APG table | <img width="684" alt="Screenshot 2023-11-01 at 3 47 34 PM" src="https://github.com/18F/identity-idp/assets/458784/d359adcb-ea34-43f0-b7f4-4e27c585b886"> |
=> Adds APG (Agency Priority Goals) user counts (LG-11156)

app/views/two_factor_authentication/sms_opt_in/error.html.erb
Similar to #9493, but for the other sms_opt_in template
=> Fix error for SMS opt-in missing title

app/forms/idv/api_image_upload_form.rb, app/javascript/packs/document-capture.tsx, app/services/analytics_events.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/features/idv/analytics_spec.rb, spec/features/idv/doc_auth/phone_question_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb
[LG-11427](https://cm-jira.usa.gov/browse/LG-11427)
1. upload form to send phone_with_camera in payload
2. image upload form to log phone_with_camera value in analytics
Complete document capture in the IdV and verify the following events contain a phone_with_camera attribute:
IdV: doc auth image upload form submitted
IdV: doc auth image upload vendor submitted
=> LG-11427 add phone with camera to image upload

lib/tasks/disposable_domains.rake
LG-11208
Add statement timeout to reduce the timeout issue.  when doing insert all
=> LG-11208: Statement timeout fix

.gitlab-ci.yml, config/application.yml.default.docker, dockerfiles/idp_review_app.Dockerfile, scripts/review_app_service_providers.rb
Adds the dashboard integration to service_providers.yml in the review app provisioning.
=> Add dashboard integration to IDP review app

app/controllers/idv/in_person/ssn_controller.rb, app/controllers/idv/ssn_controller.rb, app/presenters/idv/ssn_presenter.rb, app/services/idv/steps/threat_metrix_step_helper.rb, app/views/idv/shared/ssn.html.erb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, spec/controllers/idv/in_person/ssn_controller_spec.rb, spec/controllers/idv/ssn_controller_spec.rb, spec/features/idv/end_to_end_idv_spec.rb, spec/views/idv/shared/ssn.html.erb_spec.rb
[LG-11258](https://cm-jira.usa.gov/browse/LG-11258)
Add paragraph in the middle of Ssn page for both remote and IPP flows with offramp if user does not have a Social Security number. Add `step: 'ssn_offramp'` to the cancel url so that clicks can be tracked separately from the cancel url at the bottom of the page which has `step: 'ssn'`.
Add shared SsnPresenter to help manage the shared template between remote and IPP Ssn pages.
<details>
</details>
<details>
|English|Spanish|French|
|------|------|------|
|![Ssn offramp en](https://github.com/18F/identity-idp/assets/2381438/d8eff024-b1da-4555-ad1d-d9b03e688034)|![Ssn offramp es](https://github.com/18F/identity-idp/assets/2381438/e15552 …
=> LG-11258 Ssn page off ramp

bin/aamva-test-cert, bin/aamva-test-connectivity, spec/bin/aamva-test-cert_spec.rb
Follow-up to #9588, changes from testing in staging
1. 🤦 fixes missing require
2. switches to `p`/`pp` (pretty print) to show better output
3. Adds specs for the `bin/` that exercises optparsing, I got lazy before
=> Update AAMVA test scripts

config/application.yml.default
=> LG-11395: flag_off for development.

app/javascript/packages/document-capture/components/in-person-prepare-step.spec.tsx, app/javascript/packages/document-capture/components/in-person-prepare-step.tsx, config/locales/in_person_proofing/en.yml, config/locales/in_person_proofing/es.yml, config/locales/in_person_proofing/fr.yml
[LG-11638 ](https://cm-jira.usa.gov/browse/LG-11638)Revert PO-related content changes in DocAuth error and Prepare pages
- Revert **most** of the changes in [PR#9494](https://github.com/18F/identity-idp/pull/9494) (I kept a few new tests that and just removed some of the assertions, I kept lower casing of Post Office in Spanish translation file)
- Revert content & translations on /verify/document_capture view
- Revert content & translations on /verify/doc_auth/document_capture#prepare
<details>
<summary>👀 Screenshots for verify/document_capture</summary>
</details>
<details>
<summary>👀 Screenshots for verify/document_capture#prepare</summary>
</details>
=> LG-11638 Revert PO Related Content

config/locales/links/fr.yml
[LG-11367](https://cm-jira.usa.gov/browse/LG-11367)
Changes the French translation for the word "sign out".
=> LG-11367: Correct French translation for Sign out

app/services/reporting/account_reuse_report.rb, spec/services/reporting/account_reuse_report_spec.rb
changelog: Internal, Reporting, Fixes account reuse report header month
=> MKMR Account reuse report header month fixes

Brewfile
Upgrade node to version 18.
[See this conversation for context](https://github.com/18F/identity-idp/pull/9694#discussion_r1412589345).
=> Upgrade node to version 18

app/services/analytics_events.rb, config/initializers/session_limitable.rb, spec/features/users/sign_in_spec.rb
So that we can better understand the impact of the concurrent session limit for issues like #9407
Will coordinate to avoid conflicts with #9692
=> Add event logging for concurrent session logout

lib/reporting/identity_verification_report.rb, lib/reporting/proofing_rate_report.rb, spec/lib/reporting/proofing_rate_report_spec.rb
changelog: Internal, Reporting, Expand MKMR Proofing Rate Report
https://cm-jira.usa.gov/browse/LG-11095
=> LG-11095 Add MKMR Proofing Fraud Rejects

app/jobs/risc_delivery_job.rb, app/services/analytics_events.rb, spec/jobs/risc_delivery_job_spec.rb, spec/services/push_notification/http_push_spec.rb
https://cm-jira.usa.gov/browse/LG-11866
https://docs.google.com/document/d/10-zYRPbN16vIqx1hIpbYrkOztDutM2BfibbH1CIPkRY/edit#bookmark=id.v5hneim797n9
Add an event to track RISC push notifications so that we have a better sense of the volume of requests. This will also help debug partners that are have trouble adding a push notification url.
=> LG-11866 Add RISC event

app/presenters/two_factor_auth_code/webauthn_authentication_presenter.rb, app/presenters/webauthn_setup_presenter.rb, config/locales/forms/en.yml, config/locales/forms/es.yml, config/locales/forms/fr.yml, config/locales/instructions/en.yml, config/locales/instructions/es.yml, config/locales/instructions/fr.yml, config/locales/two_factor_authentication/en.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml, spec/presenters/two_factor_auth_code/webauthn_authentication_presenter_spec.rb, spec/presenters/webauthn_setup_presenter_spec.rb
[LG-11615: Update content for FT unlock
](https://cm-jira.usa.gov/browse/LG-11615)
Update the content on F/T Unlock for adding one and signing in.
=> LG-11615: Update content for FT unlock

.gitlab-ci.yml, app/forms/openid_connect_authorize_form.rb, app/models/federated_protocols/oidc.rb, app/models/federated_protocols/saml.rb, app/models/service_provider_request.rb, app/services/service_provider_request_handler.rb, app/services/service_provider_request_proxy.rb, app/services/store_sp_metadata_in_session.rb, app/views/pages/not_acceptable.html, app/views/pages/page_not_found.html, app/views/pages/page_took_too_long.html.erb, config/application.yml.default, docs/local-development.md, public/401.html, public/406.html, public/422.html, public/429.html, public/500.html, public/503.html, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/forms/openid_connect_authorize_form_spec.rb, spec/services/store_sp_metadata_in_session_spec.rb
- Code Quality: Remove unused style reference from error page markup ([#9799](https://github.com/18F/identity-idp/pull/9799))
- Continuous Integration: Add temporary continuous integration check to fail on content changes ([#9803](https://github.com/18F/identity-idp/pull/9803))
- Documentation: Document RISC push notifications for local development ([#9796](https://github.com/18F/identity-idp/pull/9796))
=> Deploy RC 341

config/application.yml.default, lib/identity_config.rb
LG-11845
New feature flag for future use.
=> LG-11845:  feature flag doc_auth_custom_ui_enabled.

Gemfile, Gemfile.lock
Updates [Lookbook](https://lookbook.build/) dependency to the latest version.
**Why?**
- Incorporate latest features and bug fixes ([see release notes](https://github.com/ViewComponent/lookbook/releases))
- Support ongoing effort to display embeddable previews within developer documentation
- Of particular note may be the "Add copy button to embed drawer toolbar" feature added in [v2.1.0](https://github.com/ViewComponent/lookbook/releases/tag/v2.1.0)
- Help mitigate or rule out potential conflicts with issues observed in local development ([related Slack discussion](https://gsa-tts.slack.com/archives/C0NGESUN5/p1703253148274639?thread_ts=1703081492.217739&cid=C0NGESUN5))
1. `bundle`
2. `make run`
3. Go to http://localhost:3000/components/
4. Observe no regressions in component previews
=> Update Lookbook to latest version (2.2)

.github/pull_request_template.md
We always find ourselves copy and pasting the same JIRA link for the relevant ticket. Adding this to the PR template allows us to just replace the X's with the ticket number.
=> Update the PR template for easier JIRA ticket entry

Gemfile.lock, spec/controllers/openid_connect/authorization_controller_spec.rb
[LG-XXXXX](https://cm-jira.usa.gov/browse/LG-XXXXX)
Update the `form_component` gem per [advisory](https://github.com/ViewComponent/view_component/security/advisories/GHSA-wf2x-8w6j-qw37)
=> Update form_component gem to 3.9

app/jobs/reports/identity_verification_report.rb, lib/reporting/identity_verification_report.rb, spec/jobs/reports/identity_verification_report_spec.rb
changelog: Internal, IdV Reports, fix typo in daily idv email
Fixed a typo in the report email and changed the attachment format to xlsx.
=> Fixes for Daily IdV report

app/jobs/reports/identity_verification_report.rb, app/jobs/resolution_proofing_job.rb, app/services/idv/agent.rb, app/services/proofing/resolution/progressive_proofer.rb, lib/reporting/identity_verification_report.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/jobs/reports/identity_verification_report_spec.rb
- IdV Reports: Fix typo in daily idv email ([#9884](https://github.com/18F/identity-idp/pull/9884))
=> Deploy RC 345.1 to Prod

app/services/reporting/account_reuse_report.rb, spec/services/reporting/account_reuse_report_spec.rb
changelog: Internal, Reporting, Fix Reuse Rate Queries
[LG-12007](https://cm-jira.usa.gov/browse/LG-12007)
Fixed Reuse Rate queries to accurately distinguish between All users and IDV users
=> LG-12007 Fix bug in calculating Reuse Rates

Gemfile.lock
[9.7.0](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/CHANGELOG.md#v970) includes ViewComponent instrumentation, which should be neat.
=> Update New Relic

spec/factories/users.rb, spec/services/reporting/account_reuse_report_spec.rb
[LG-12140](https://cm-jira.usa.gov/browse/LG-12140)
This addresses the intermittent unit test failures [reported here](https://gsa-tts.slack.com/archives/C03N6KQBAKS/p1705508709105049).
=> LG-12140 Fix Reuse Rates Unit Test failure

config/application.yml.default, spec/components/previews/login_button_component_preview.rb
Just a quick follow up from PR #9840 
Since this component is being embedded in the User Guide in our dev docs it made sense to add descriptions for the parameters.
=> Add descriptions to Login Button Component

spec/javascript/packages/document-capture/components/review-issues-step-spec.jsx
Remove clean up, refer https://github.com/18F/identity-idp/pull/9856#pullrequestreview-1804900894
=> LG-11985: Cleanup leftover.

app/controllers/redirect/policy_controller.rb
Small change to fix indentation, not sure why it wasn't caught by rubocop.
=> Fix indenting in PolicyController

app/controllers/concerns/idv_session_concern.rb, app/controllers/concerns/idv_step_concern.rb, app/controllers/idv/by_mail/enter_code_controller.rb, app/controllers/idv/by_mail/enter_code_rate_limited_controller.rb, app/controllers/idv/by_mail/letter_enqueued_controller.rb, app/controllers/idv/cancellations_controller.rb, app/controllers/idv/confirm_start_over_controller.rb, app/controllers/idv/forgot_password_controller.rb, app/controllers/idv/in_person/ready_to_verify_controller.rb, app/controllers/idv/in_person/verify_info_controller.rb, app/controllers/idv/in_person_controller.rb, app/controllers/idv/mail_only_warning_controller.rb, app/controllers/idv/resend_otp_controller.rb, app/controllers/idv/session_errors_controller.rb, app/controllers/idv/sessions_controller.rb, app/controllers/idv_controller.rb, spec/controllers/concerns/idv/step_indicator_concern_spec.rb, spec/controllers/concerns/rate_limit_concern_spec.rb, spec/controllers/idv/by_mail/request_letter_controller_spec.rb, spec/controllers/idv/cancellations_controller_spec.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/controllers/idv/forgot_password_controller_spec.rb, spec/controllers/idv/otp_verification_controller_spec.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/controllers/idv/phone_controller_spec.rb, spec/controllers/idv/phone_errors_controller_spec.rb, spec/controllers/idv/resend_otp_controller_spec.rb, spec/controllers/idv/session_errors_controller_spec.rb
[LG-11966](https://cm-jira.usa.gov/browse/LG-11966)
Inside IdV we have two idv session files. One being `idv/session.rb` and the other being `concerns/idv_session.rb`. To avoid confusion, this PR has renamed the concern to `idv_session_concern.rb` and the corresponding class to `IdvSessionConcern`
=> LG-11966 Rename IdV Session concern

app/forms/openid_connect_authorize_form.rb, app/models/federated_protocols/oidc.rb, app/models/federated_protocols/saml.rb, app/services/analytics_events.rb, app/services/service_provider_request_handler.rb, app/services/store_sp_metadata_in_session.rb, config/application.yml.default, config/locales/openid_connect/en.yml, config/locales/openid_connect/es.yml, config/locales/openid_connect/fr.yml, lib/identity_config.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/forms/openid_connect_authorize_form_spec.rb, spec/services/store_sp_metadata_in_session_spec.rb
This reverts commit 0145c7eded9ff0be1ed78442b6ce3f11b7752154.
=> Revert "LG-12190 Store vtr and acr_values in sp_session (#10004)"

config/country_dialing_codes.yml, config/pinpoint_supported_countries.yml, lib/pinpoint_supported_countries.rb
Change to fix the build.  No ticket associated.  Thank you to @night-jellyfish, @dawei-nava, and @zachmargolis for your debugging help!
=> Debug make lint country dialing code

app/services/document_capture_session_result.rb, spec/controllers/idv/capture_doc_status_controller_spec.rb, spec/models/document_capture_session_spec.rb, spec/services/document_capture_session_result_spec.rb
[LG-12040](https://cm-jira.usa.gov/browse/LG-12040)
Removing reading of `success` field of session result.
=> LG-12040: remove success filed in session result - read part

lib/reporting/mfa_report.rb
Spotted some code that was unused in #10076 after a refactor
=> Remove unused code in MFA Report

app/services/reporting/total_user_count_report.rb, spec/services/reporting/total_user_count_report_spec.rb
changelog: Internal, Reporting, Add count of fully registered users in Total User table
[Link to the relevant ticket:](https://cm-jira.usa.gov/browse/LG-12065)
=> LG-12065 Add "full registered users count" to Monthly Key Metric Report

app/services/doc_auth/lexis_nexis/requests/true_id_request.rb, app/services/doc_auth/lexis_nexis/responses/true_id_response.rb, app/services/doc_auth/mock/result_response.rb, app/services/document_capture_session_result.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb, spec/services/doc_auth/lexis_nexis/requests/true_id_request_spec.rb, spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb, spec/services/doc_auth/mock/result_response_spec.rb
[LG-12296](https://cm-jira.usa.gov/browse/LG-12296)
Add `workflow` to event `IdV: doc auth image upload vendor submitted`.
=> LG-12296: log trueid workflow

bin/oncall/email-deliveries, spec/bin/oncall/email-deliveries_spec.rb
Follow up to #10048. This adds the `email_address_id` field when displaying results in the `email-deliveries` script to show which email addresses were the destination, if there were different email addresses in the timeframe, etc. to help debug issues with email delivery.
```
+--------------------------------------+------------------+-------------------------+--------------------------------------------------------------+-----------------------------+----------------+
| user_id                              | email_address_id | timestamp               | message_id                                                   | email_action                | events         |
+--------------------------------------+------------------+-------------------------+----------------------------- …
```
=> Add email_address_id field to oncall/email-deliveries script

bin/oncall/email-deliveries
=> Fix require in email-deliveries script

bin/oncall/download-piv-certs
- Query 2 weeks like the help text says
- Use correct property for user_id
=> Fix download-piv-certs script

Gemfile.lock
https://github.com/18F/identity-idp/security/dependabot/69
=> Update yard gem to address security vulnerability

app/controllers/users/sessions_controller.rb, spec/requests/csp_spec.rb
See [Slack thread](https://gsa-tts.slack.com/archives/C5E7EJWF7/p1709755279457439) for context
=> Update CSP rules to allow newer DAP (GA 4)

app/jobs/reports/fraud_metrics_report.rb, lib/reporting/fraud_metrics_lg99_report.rb, spec/jobs/reports/fraud_metrics_report_spec.rb, spec/lib/reporting/fraud_metrics_lg99_report_spec.rb, spec/mailers/previews/report_mailer_preview.rb
https://cm-jira.usa.gov/browse/LG-12414
Add LG-99 unique user report for fraud metric report
=> LG-12414 Fraud Metrics LG-99 report

lib/reporting/fraud_metrics_lg99_report.rb
=> LG-12414 Fraud Metrics LG-99 report bug fix

config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml, spec/features/webauthn/management_spec.rb
[LG-12606](https://cm-jira.usa.gov/browse/LG-12606)
Revise translated text for webauthn_setup error messages.
**Already registered key**
**General error**
**Not supported**
**Unique name**
=> LG-12606 Security Key Error flow content and workflow improvements

config/puma.rb
Similar to the changes [here](https://github.com/18F/identity-dashboard/blob/52efcfcae6ff115355c0d64b8779b9a56a08e6d6/config/puma.rb#L27-L30) for the dashboard. Allows us to better see the logs in a deployed environment.
=> Add ability to configure file destinations for Puma logs

Gemfile.lock
Based on seeing some issues with installation [here](https://gsa-tts.slack.com/archives/C0NGESUN5/p1711040056307879)
=> Update cbor gem

config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, config/locales/errors/es.yml
[LG-12120](https://cm-jira.usa.gov/browse/LG-12120)
Selfie related translation(DoS) changes.
Sample test yaml file.
```yaml
portrait_match_results:
FaceMatchResult: Fail
FaceErrorMessage: 'Liveness: NotLive'
doc_auth_result: Passed
document:
first_name: Jane
last_name: Doe
middle_name: Q
address1: 1800 F Street
address2: Apt 3
city: Bayside
state: NY
zipcode: '11364'
dob: 10/06/1938
phone: +1 314-555-1212
state_id_jurisdiction: 'ND'
state_id_number: 'S59397998'
state_id_type: drivers_license
```
| | After |
|-| - |
|Warning page | <img src="https://github.com/18F/identity-idp/assets/130466753/6215623b-8c82-43ac-ab14-f15424ec4750" width="300" />|
|Review page | <img …
=> LG-12120: liveness inline error messages

Procfile
Small followup to #10287 to remove the process when using foreman. This is still very much experimental, and it creates more noise than is useful at this point.
=> Remove prometheus_exporter from Procfile

config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml
[LG-12060](https://cm-jira.usa.gov/browse/LG-12060)
Update the copy on the Agreement Step page of the IdV flow.
<details>
</details>
<details>
</details>
=> LG-12060 Update How verifying your identity works copy

Gemfile, Gemfile.lock, app/helpers/script_helper.rb, spec/rails_helper.rb
Ran into some issues, so this reverts 18F/identity-idp#10304
=> Revert "Refactor ScriptHelper class to be thread-safe"

app/forms/new_phone_form.rb, config/application.yml.default, lib/identity_config.rb, spec/forms/new_phone_form_spec.rb
Follow up to #7366 to allow a more flexible representation of the list
=> Add JSON-formatted phone carrier configuration

app/forms/new_phone_form.rb, config/application.yml.default, lib/identity_config.rb, spec/forms/new_phone_form_spec.rb
- Rate Limiting: Add JSON-formatted phone carrier configuration ([#10346](https://github.com/18F/identity-idp/pull/10346))
=> Deploy RC 367.1 to Production

app/javascript/packages/document-capture/context/acuant.tsx
Suggestion missed in #10368 that I think is a good addition.
=> Add comment clarifying use of the new callback and log

Gemfile, Gemfile.lock
changelog: Internal, SAML, bump to latest saml-idp version
=> Bump saml-idp version to 0.20.0-18f

config/application.yml.default, lib/identity_config.rb
[LG-10357](https://cm-jira.usa.gov/browse/LG-10357)
Add feature flag for state-id controller page
=> LG-10357 FSM/state-id Add feature flag

db/primary_migrate/20240411163520_remove_postgis_extension.rb
Forgot to check this in as part of https://github.com/18F/identity-idp/pull/10410#discussion_r1561394936
=> Add missing DB migration from removing PostGIS

Gemfile.lock
`redis-client` recently made some pretty significant [performance improvements](https://github.com/redis-rb/redis-client/pull/184), and this PR updates our Redis gems to make use of it.
=> Update Redis gems

config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, config/locales/in_person_proofing/fr.yml
[LG-12903](https://cm-jira.usa.gov/browse/LG-12903)
Update copy with [translations from DoS](https://cm-jira.usa.gov/browse/LG-12903).
<details>
</details>
=> LG-12903: translation updates on hybrid handoff page

app/services/proofing/resolution/result.rb
I happened to come across this file, so I'm fixing it.
I couldn't find any additional Rubocops that would catch/error on this unfortunately.
=> Fix indentation

config/locales/doc_auth/fr.yml
[LG-12903](https://cm-jira.usa.gov/browse/LG-12903)
Text edit removing: "Si non,"
<details>
</details>
<details>
</details>
=> LG-12903: text edit for IPP page in fr

app/javascript/packages/build-sass/CHANGELOG.md, app/javascript/packages/build-sass/package.json
Prepares code for publish of pending changes to `@18f/identity-build-sass`.
I need the pending bug fix in `@18f/identity-design-system` to fix rebuilds after failed compilation.
=> Publish @18f/identity-build-sass v3.1.0 NPM package

app/services/iaa_reporting_helper.rb, spec/services/iaa_reporting_helper_spec.rb
[LG-13012](https://cm-jira.usa.gov/browse/LG-13012)
Added partneragreement helper function to existing iaa_reporting_helper.rb
Updated iaa_reporting_helper_spec.rb to unit test the helper function
=> Partneragreement helper-billingreport

app/controllers/concerns/billable_event_trackable.rb, app/models/sp_return_log.rb, spec/controllers/concerns/billable_event_trackable_spec.rb
=> Fix type error: issuer (string) vs ServiceProvider (model class)

config/locales/doc_auth/es.yml
[LG-12829](https://cm-jira.usa.gov/browse/LG-12829)
Update copy from "su rostro" to "usted mismo" as specified in JIRA ticket comment.
<details>
</details>
<details>
</details>
=> LG-12829: update copy provided by DoS

.gitlab-ci.yml
Config options to abstract parts of the env vars
=> Refactor ci config for reviewapps to use the new helm chart settings

app/controllers/component_preview_controller.rb
Updates component previews to support viewing localized previews.
1. Go to http://localhost:3000/fr/components/inspect/time/preview
2. See time formatted in French
=> Support localization for component previews

config/locales/doc_auth/es.yml
[LG-13232](https://cm-jira.usa.gov/browse/LG-13232)
Small spanish translation fix for the checkbox in the agreement step of IdV.
<details>
</details>
<details>
</details>
=> Update "How verifying your identity works" for LQA spanish translation

config/locales/step_indicator/en.yml, config/locales/step_indicator/es.yml, config/locales/step_indicator/fr.yml, config/locales/step_indicator/zh.yml, spec/i18n_spec.rb
[LG-13044](https://cm-jira.usa.gov/browse/LG-13044)
Updates from LQA for the step indicator content.
<details>
<summary>Happy Path:</summary>
French|Spanish|Chinese
---|---|---
</details>
<details>
<summary>Request a letter:</summary>
French|Spanish|Chinese
---|---|---
</details>
<details>
<summary>In-Person Proofing:</summary>
French|Spanish|Chinese
---|---|---
</details>
<details>
<summary>In-Person Proofing - Request a letter:</summary>
French|Spanish|Chinese
---|---|---
</details>
=> LG-13044: Step indicator LQA updates

app/services/db/monthly_sp_auth_count/new_unique_monthly_user_counts_by_partner.rb, app/services/db/monthly_sp_auth_count/unique_monthly_auth_counts_by_iaa.rb, spec/services/db/monthly_sp_auth_count/new_unique_monthly_user_counts_by_partner_spec.rb, spec/services/db/monthly_sp_auth_count/unique_monthly_auth_counts_by_iaa_spec.rb
changelog: Internal, Reporting, fix the date range nil check for both billing reports
[LG-13334](https://cm-jira.usa.gov/browse/LG-13334)
Added date range nil check on billing reports to avoid  monthly helper exception.
Added date range check in helper functions to avoid checking on date range nil
=> lg-13334 implement date range nil check for billing reports

.gitlab-ci.yml
- Fixes a missing values.yaml override for `env` which is now set to `reviewapps` which was preventing deployment of the application for previewing.
- Fix is working if the review-app deployment works for this PR
=> changelog: Internal, CI, set env for reviewapp deployment

.gitlab-ci.yml
Per discussion [here](https://gsa-tts.slack.com/archives/C023LB27CCQ/p1716233714034549?thread_ts=1716233375.737709&cid=C023LB27CCQ), this PR updates the name used for EKS review apps.
=> Fix command for review app configuration in GitLab job

config/locales/es.yml, config/locales/fr.yml
[LG-13043](https://cm-jira.usa.gov/browse/LG-13043)
Update Spanish and French translations for the agreement step page
<details>
</details>
<details>
</details>
=> LG-13043 Update translations for "How verifiying your identity works" screen

app/controllers/concerns/saml_idp_auth_concern.rb, app/services/saml_request_validator.rb, lib/saml_idp_constants.rb, spec/controllers/saml_idp_controller_spec.rb
This reverts commit 30cb0f374f7e66aa0a930d244cb0dc3e4d22f549.
changelog: Bug Fixes, SAML, Revert validation of NameID formats
=> Revert "Validate requested NameID formats and return appropriate response (#10629)"

lib/reporting/identity_verification_report.rb, spec/lib/reporting/identity_verification_report_spec.rb
[Link to the relevant ticket:](https://cm-jira.usa.gov/browse/LG-13359)
For the proofing rate report included unique counts for verified users
=> LG-13359: MKMR Proofing rate verified users count fixes

.gitlab-ci.yml
After adding more contexts that Gitlab could access it is now choosing the wrong context to deploy to, this updates the context selection to use the correct one
If the review-app deploys correctly then the check is working.
=> Fix kube context for pipeline deploys

lib/reporting/protocols_report.rb, spec/lib/reporting/protocols_report_spec.rb
[[LG-XXXXX](https://cm-jira.usa.gov/browse/LG-XXXXX)](https://gitlab.login.gov/lg-people/lg-people-appdev/protocols/backlog-fy24/-/issues/11)
1. Add "Count of issuers" column to the Protocols section.
2. Rename attempts to requests
3. Rename integrations to issuers
=> Refine protocols report

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_language-picker.scss, app/services/marketing_site.rb, app/views/shared/_footer_lite.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/i18n_spec.rb, spec/services/marketing_site_spec.rb
[LG-13269](https://cm-jira.usa.gov/browse/LG-13269)
Updates the layout footer to include a mandatory link to [Login.gov's Accessibility Statement](https://login.gov/accessibility/).
Validate the appearance and functionality of the page footer at various device sizes
<table>
<thead><tr><th>Device Size</th><th>Before</th><th>After</th></tr></thead>
<tbody>
<tr>
<td>Mobile (0-640px)</td>
<td>
<table><thead><tr><th>Closed</th><th>Open</th></tr></thead><tbody><tr><td><img width="100" alt="before mobile closed" src="https://github.com/18F/identity-idp/assets/1779930/df7d2499-ded9-4d2c-bdb0-97e51a140005"></td><td><img width="100" alt="before mobile open" src="https://github.com/18F/identity-idp/assets/1779930/729149cc-0748-4b92-8725-bcf51819fc0e"></td></tr></tbody>< …
=> LG-13269: Add Accessibility Statement link to footer

spec/services/sp_handoff_bouncer_spec.rb
- Accidentally forgot to commit as part of #10720
changelog: Internal, Source code, Increase unit test coverage
=> Add missing specs for SpHandoffBouncer class

app/views/shared/_personal_key_input.html.erb
[LG-12466](https://cm-jira.usa.gov/browse/LG-12466)
Before 
After
=> LG-12466: Add personal key input

Gemfile, Gemfile.lock
This has been prepped just in case it is necessary to rollback the saml_idp update.
Reverts 18F/identity-idp#10734
=> Revert "Update to newest saml_idp"

yarn.lock
This commit addresses the following issue: https://github.com/advisories/GHSA-grv7-fg5c-xmjg
=> Upgrade braces to 3.0.3

config/locales/zh.yml, spec/i18n_spec.rb
Add several missing translations identified in the [06/10 spreadsheet tab](https://docs.google.com/spreadsheets/d/1Bfeg6vyqhNPtmbu7uMWqmIYX8n9uvcAtejnfQ62iYCU/edit#gid=621088966).
- Row 10
- Row 11
- Row 15
- Row 17
- Row 18
- Row 22
=> Add 06/10 Bulk Translations - Set 01

spec/jobs/reports/combined_invoice_supplement_report_v2_spec.rb
changelog: Internal, Reporting, more robust unit testing for combined billing report
* lg-13506 added more robust unit testing for better scenario coverage before consumer sees report
[LG-13506](https://cm-jira.usa.gov/browse/LG-13506)
* added more robust unit testing for better scenario coverage on combined billing report
=> More robust unit testing for better scenario coverage on combined billing report v2

config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/i18n_spec.rb
These are a combination of existing translations and were missed in the initial set.
=> Update missing Chinese translations

Gemfile, Gemfile.lock, app/controllers/saml_idp_controller.rb, app/services/proofing/resolution/progressive_proofer.rb, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, lib/reporting/identity_verification_report.rb, spec/controllers/saml_idp_controller_spec.rb, spec/i18n_spec.rb, spec/jobs/reports/combined_invoice_supplement_report_v2_spec.rb, spec/services/identity_linker_spec.rb, spec/services/proofing/resolution/progressive_proofer_spec.rb
- Analytics: Fix small bug in tracking metrics ([#10789](https://github.com/18F/identity-idp/pull/10789))
- Continuous Integration: Fix flaky IdentityLinker test ([#10807](https://github.com/18F/identity-idp/pull/10807))
- Internationalization: Add quotes to punctuation check in tests ([#10803](https://github.com/18F/identity-idp/pull/10803))
- Reporting: More robust unit testing for combined billing report ([#10799](https://github.com/18F/identity-idp/pull/10799))
- Translations: Update missing Chinese translations ([#10797](https://github.com/18F/identity-idp/pull/10797), [#10800](https://github.com/18F/identity-idp/pull/10800), [#10804](https://github.com/18F/identity-idp/pull/10804))
=> Deploy RC 389 to Production

.gitlab-ci.yml, Makefile
This PR adds a test to guard against changes to migrations that are not reflected in schema files.
=> Add test to ensure schema files are consistent with migrations

config/locales/zh.yml
=> Update Chinese translations

Makefile, docs/frontend.md, package.json, yarn.lock
Per https://github.com/18F/identity-idp/pull/10854#issuecomment-2183352910
=> Enforce yarn-deduplicate as part of the build

config/application.yml.default, spec/models/user_spec.rb
[LG-13397](https://cm-jira.usa.gov/browse/LG-13397)
Update `rules_of_use_horizon_years` from 6 to 5.
(Note that in practice, `rules_of_use_updated_at` is updated more often than every 5 years, this is crossing t's and dotting i's for assessment purposes.)
=> LG-13397: Update rules_of_use_horizon_years to 5

app/components/one_time_code_input_component.scss, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
[LG-13450](https://cm-jira.usa.gov/browse/LG-13450)
Update Language for error messaging.
=> LG-13450: Update error language

app/controllers/idv/in_person/public/usps_locations_controller.rb, app/controllers/idv/in_person/usps_locations_controller.rb, app/presenters/idv/in_person/ready_to_verify_presenter.rb, app/services/usps_in_person_proofing/enrollment_helper.rb, spec/controllers/idv/in_person/usps_locations_controller_spec.rb
Reverts #10882 
There were some small issues that need to be addressed before re-deploying. This is not a complete reversion as there were conflicts (mostly with #10894)
=> Revert "Translate Post Office search results"

spec/controllers/users/sessions_controller_spec.rb, spec/features/visitors/bad_password_spec.rb
=> Fix flakey specs.. 

config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
Updates locale files to remove abnormal line breaks.
The intent is to avoid confusion and human error, and bring consistency to the format of the file. Consistency also allows for better code searchability.
Verify no regressions in the display of affected content.
=> Normalize newlines in locale data

app/controllers/users/sessions_controller.rb, app/services/analytics_events.rb, spec/controllers/users/sessions_controller_spec.rb
- Code Revert: Revert changes introduced in a64bcaa9c232532434499b52a5e89a92f4c5bd7a ([#10957](https://github.com/18F/identity-idp/pull/10957))
=> Deploy RC 398.1 to Production

config/initializers/job_configurations.rb, spec/jobs/reports/protocols_report_spec.rb
changelog: Internal, Reporting, Ensure parameter correctness
=> Call the report with a proper "Time"

app/javascript/packages/document-capture/components/document-capture.tsx
[LG-11361](https://cm-jira.usa.gov/browse/LG-11361)
Adjusted step code in doc capture to match description listed https://cm-jira.usa.gov/browse/LG-10881?focusedId=1738579&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1738579
=> Refactored step code according to ticket description

.gitlab-ci.yml
Swaps the review apps from using the `reviewapp` dns zone to the `reviewapps` zone
=> Swap to new DNS zone for review apps

config/locales/telephony/es.yml, config/locales/telephony/fr.yml, config/locales/telephony/zh.yml, spec/i18n_spec.rb
We received new translations for these scripts including new words for "digit" and "characters". This commit puts the new translations in place.
=> LG-13580 Update voice call script for 10-digit OTP

app/javascript/packages/document-capture/components/acuant-camera.tsx, app/javascript/packages/document-capture/context/acuant.tsx, spec/javascript/packages/document-capture/components/acuant-capture-spec.jsx
[LG-12726](https://cm-jira.usa.gov/browse/LG-12726)
Removed some of the code that was only for past versions of the Acuant SDK that are no longer needed.
=> LG-12726 Remove code from outdated Acuant SDK versions

config/routes.rb
[LG-13150](https://cm-jira.usa.gov/browse/LG-13150)
Removal of the deprecated routes
=> LG-13150: remove deprecated address route

app/assets/stylesheets/email.css.scss, app/views/user_mailer/account_reset_granted.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
[LG-13871](https://cm-jira.usa.gov/browse/LG-13871)
This updates the CTA for account delete granted to be clearer.
=> LG-13871: Update Account Deletion granted CTA

app/models/doc_auth_log.rb, spec/controllers/idv/image_uploads_controller_spec.rb
Updates a test to resolve a build failure on `main` due to competing merges #11024 and #10995.
=> Fix spec expectation of issue_year logging

lib/reporting/fraud_metrics_lg99_report.rb, spec/lib/reporting/fraud_metrics_lg99_report_spec.rb
changelog Internal, Proofing Metrics, optimized proofing query
[LG-12819](https://cm-jira.usa.gov/browse/LG-12819)
Optimized query in light of knowing that an active Profile is going to be the most recent verified profile. Including validations ensuring there will only be one active profile for a user.
=> [LG-12819] Optimized proofing query

.gitlab-ci.yml
Adds labels to review app resources for easier tracing of environments to branches.
=> Adding labels to kubernetes resources for easier tracing

spec/features/idv/doc_auth/document_capture_spec.rb
[LG-12510](https://cm-jira.usa.gov/browse/LG-12510)
Renamed variable according to https://github.com/18F/identity-idp/pull/10042/files#r1491779684
=> Renamed variable

docs/sdk-upgrade.md
Copies commits from #11019 to be run in continuous integration.
=> Update configuration link in SDK upgrade documentation

spec/views/accounts/show.html.erb_spec.rb
This is a follow-up to PR #11105.
=> LG-14231: Add regression spec for earlier bug fix [skip changelog]

app/views/accounts/_pii.html.erb, app/views/idv/in_person/ready_to_verify/show.html.erb, app/views/idv/in_person/state_id.html.erb, app/views/idv/in_person/state_id/show.html.erb, app/views/shared/_personal_key.html.erb, spec/views/idv/in_person/ready_to_verify/show.html.erb_spec.rb, spec/views/shared/_personal_key.html.erb_spec.rb
[LG-13947](https://cm-jira.usa.gov/browse/LG-13947)
This ticket performs a sweep for additional help center links that can be updated safely. One of the links identified for an update was fixed earlier.
=> LG-13947: Update links

Gemfile.lock, spec/services/proofing/aamva/verification_client_spec.rb
Addresses vulnerability: https://www.ruby-lang.org/en/news/2024/08/22/dos-rexml-cve-2024-43398/
=> Update rexml gem

app/jobs/reports/monthly_key_metrics_report.rb, app/services/reporting/active_users_count_report.rb, spec/services/reporting/active_users_count_report_spec.rb
changelog: Internal, Reporting, Update APG Report with Current Month
[LG-14149](https://cm-jira.usa.gov/browse/LG-14149)
Add "Current Month" Row to Monthly Key Metrics Report APG Report.
<details>
<summary>Before:
</details>
<details>
<summary>After:
</summary>
</details>
=> LG-14149 Update MKMR APG Report with Current Month stats

spec/features/sign_in/piv_recommended_after_sign_in_spec.rb
=> Remove unnecessary allowed_extra_analytics

db/primary_migrate/20240828182041_add_aaguid_to_webauthn_configuration.rb, db/schema.rb
[LG-14198](https://cm-jira.usa.gov/browse/LG-14198)
Migration for https://github.com/18F/identity-idp/pull/11138
=> LG-14198: Migration

Gemfile, Gemfile.lock
changelog: Internal, SAML, Update saml_idp version to 0.22.0
=> Update saml_idp version to 0.22.0

lib/reporting/fraud_metrics_lg99_report.rb, spec/lib/reporting/fraud_metrics_lg99_report_spec.rb
changelog: Internal, reporting, fix flaky test failures
[LG-14421](https://cm-jira.usa.gov/browse/LG-14421)
Reduced the floating point accuracy to accommodate discrepancies of time in test specs.
<details>
</details>
<details>
</details>
<details>
<summary>User Log during test:</summary>
</details>
=> LG-14421 Fix Flaky tests in LG99 fraud report

config/locales/fr.yml
=> undo changes from #11235

config/service_providers.localdev.yml
This service provider can be configured for the sample OIDC app for PKCE.
changelog: Internal, Local Development, Add PKCE service provider
=> Add PKCE service provider for local development

app/jobs/reports/mfa_report.rb, config/application.yml.default, config/initializers/job_configurations.rb, lib/identity_config.rb, spec/jobs/reports/mfa_report_spec.rb
[LG-12572](https://cm-jira.usa.gov/browse/LG-12572)
Add new cron variable for monthly report. Add new config attribute. Add mfa_report to jobs/reports for emails. Add specs. Schedule MFA Report with new variable.
=> Schedule MFA Report job to run once per month

app/javascript/packages/document-capture/components/_file-input.scss, app/javascript/packages/document-capture/components/document-capture.tsx, app/javascript/packages/document-capture/components/documents-step.tsx, app/javascript/packages/document-capture/components/file-input.tsx, app/javascript/packages/document-capture/components/selfie-step.tsx, config/application.yml.default.docker, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/javascript/packages/document-capture/components/documents-and-selfie-step-spec.tsx
Reverts 18F/identity-idp#11245
This change was merged without approval from a member of login engineering
=> Revert "changelog: User-Facing Improvments, doc auth, split doc auth content …"

Gemfile.lock
Background
Address vulnerability: https://github.com/advisories/GHSA-6f62-3596-g6w7
=> update webrick gem

app/forms/register_user_email_form.rb, app/mailers/user_mailer.rb, spec/mailers/previews/user_mailer_preview.rb, spec/mailers/user_mailer_spec.rb
[LG-14204](https://cm-jira.usa.gov/browse/LG-14204)
Add request id to already signed up email that is sent
=> LG-14204: Add Request id to sign up email

config/locales/fr.yml
[LG-14513](https://cm-jira.usa.gov/browse/LG-14513)
Updated french text during camera capture.
=> Lg-14513 update selfie text french

config/locales/zh.yml
[LG-14047](https://cm-jira.usa.gov/browse/LG-14047) [LQA fixes] Biometric Opt-in Chinese content fixes
- Update Chinese content for doc_auth.info.verify_online_instruction_selfie
<details>
Continue in person has already been handled.
</details>
<details>
Zoomed in so you can see characters better
Zoomed in so you can see characters better
No other views are affected by this change -6 instances of this found; used once in the code, 4 in translations files, and once in the spec
</details>
=> LG-14047 Biometric Opt-in Chinese content fixes

.gitlab-ci.yml, dockerfiles/application.yaml
Updates the echo statement to point at the correct service name, as well as add in a few more environment variables to add the test banners to the sites.
=> Fixing service naming, adding more environment variables

app/mailers/user_mailer.rb, spec/mailers/user_mailer_spec.rb
No ticket, but fixes a bug introduced in PR #11353
=> Add default keyword arg for user_mailer visited_location_name

db/primary_migrate/20241023191918_add_socure_docv_capture_app_url_to_document_capture_sessions_w_comment.rb, db/schema.rb
[LG-14805](https://cm-jira.usa.gov/browse/LG-14805)
Adding migration to track socure_docv_capture_app_url during doc auth flow
=> lg-14805 add socure_docv_capture_app_url to document_capture_sessions table

app/controllers/concerns/saml_idp_auth_concern.rb, app/controllers/openid_connect/authorization_controller.rb, app/controllers/sign_up/completions_controller.rb, app/controllers/sign_up/select_email_controller.rb, spec/controllers/sign_up/select_email_controller_spec.rb
[LG-14353](https://cm-jira.usa.gov/browse/LG-14353)
Improve readability of session key created for https://cm-jira.usa.gov/browse/LG-13001 (pr: https://github.com/18F/identity-idp/pull/10951)
=> LG-14353 Re-label selected email session key

docs/local-development.md
changelog: Internal, Automated Testing, Improve documentation
=> Document how to force real browser on feature test

db/primary_migrate/20241029152408_index_socure_doc_v_transaction_token.rb, db/schema.rb
[LG-14838](https://cm-jira.usa.gov/browse/LG-14838)
index socure docv transaction token. Defined up/down method due to concurrency algorithm error message.
=> Lg 14838 index socure docv transaction token

app/controllers/socure_webhook_controller.rb, spec/controllers/socure_webhook_controller_spec.rb
Increment rate limiter per ID submission
[LG-14801](https://cm-jira.usa.gov/browse/LG-14801)
Updated webhook route to check for document_submitted webhook and increment corresponding rate limiter. Also updated rspec tests for this.
=> lg-14801 Increment rate limiter per ID submission

app/services/idv/aamva_state_maintenance_window.rb
changelog: Internal, AAMVA, Update Montana's maintenance window
[LG-14830](https://cm-jira.usa.gov/browse/LG-14830)
While working on LG-14830 I received updated documentation which included the listing of Montana's scheduled maintenance window. Adding it while I'm in here.
Someone please check my timezone math.
=> LG-14830 | Adds MT DMV maintenance window

.gitlab-ci.yml, dockerfiles/application.yaml
=> separate db into its own argo app

app/controllers/idv/hybrid_mobile/socure/document_capture_controller.rb, app/controllers/idv/socure/document_capture_controller.rb, app/views/idv/hybrid_mobile/socure/document_capture/show.html.erb, app/views/idv/shared/_doc_capture_interstitial.html.erb, app/views/idv/socure/document_capture/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/controllers/idv/hybrid_mobile/socure/document_capture_controller_spec.rb, spec/controllers/idv/socure/document_capture_controller_spec.rb
[LG-14690](https://cm-jira.usa.gov/browse/LG-14690)
Added an interstitial screen before entering Socure's DocV portal.
=> LG-14690 Socure DocV Interstitial

app/jobs/data_warehouse/daily_sensitive_column_job.rb, config/application.yml.default, config/initializers/job_configurations.rb, db/primary_migrate/20241025221705_update_sensitive_columns.rb, db/schema.rb, lib/identity_config.rb, spec/jobs/data_warehouse/daily_sensitive_column_report_spec.rb
MR covers  new jobs to export sensitive column details  and update few columns sensitive tag.
changelog: Internal, Reporting,add new daily sensitive job
[LG-14425](https://cm-jira.usa.gov/browse/LG-14425)
New jobs to export sensitive column details to an S3 bucket,Includes column comments indicating sensitivity (true/false).
Updates the IDP database schema to add sensitive: true tags to specific columns.
=> lg-14425 new  daily sensitive job 

.gitlab-ci.yml, dockerfiles/application.yaml
Testing out using the same image as everything else for review apps
=> Testing out using the same image as everything else

config/locales/en.yml, config/locales/zh.yml
[LG-15022](https://cm-jira.usa.gov/browse/LG-15022)
changelog: User-Facing Improvements, Translations, Fix errant piv/cac capitalization
Context: Noticed this in https://github.com/18F/identity-idp/pull/11461/files#r1833336813
French and Spanish already have it capitalized.
=> LG-15022 | Fix piv/cac capitalization

config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
[LG-14386](https://cm-jira.usa.gov/browse/LG-14836)
Update the translations for the IPP option on the doc auth error page.
<details>
<h3>English:</h3>
<h3>Spanish:</h3>
<h3>French:</h3>
<h3>Chinese:</h3>
</details>
<details>
<h3>English:</h3>
<h3>Spanish:</h3>
<h3>French:</h3>
<h3>Chinese:</h3>
</details>
=> LG-14836 Update translations for IPP on doc auth error page

config/application.yml.default, spec/features/idv/doc_auth/socure_document_capture_spec.rb, spec/features/idv/hybrid_mobile/entry_spec.rb, spec/features/idv/hybrid_mobile/hybrid_socure_mobile_spec.rb, spec/fixtures/socure_docv/pass.json, spec/support/features/doc_auth_helper.rb, spec/support/features/document_capture_step_helper.rb, spec/support/socure_docv_fixtures.rb
[LG-15016](https://cm-jira.usa.gov/browse/LG-15016)
* add init feature tests for socure standard and hybrid flow
=> LG-15016: Socure document capture feature specs starter

app/jobs/data_warehouse/base_job.rb, app/jobs/data_warehouse/table_summary_stats_export_job.rb, config/application.yml.default, lib/identity_config.rb, spec/jobs/data_warehouse/table_summary_stats_export_job_spec.rb
[LG-15160](https://cm-jira.usa.gov/browse/LG-15160)
Adding a feature flag to the data warehouse job table_summary_stats
=> LG-15160 adding feature flag to table_summary job

app/services/saml_request_validator.rb, spec/controllers/saml_idp_controller_spec.rb, spec/services/saml_request_validator_spec.rb
- SAML Integration: Adding condition to allow no certs if integration has block_encryption set to none
=> Deploy RC 437.1 to Production

app/controllers/openid_connect/logout_controller.rb
I didn't rebase my [previous change](https://github.com/18F/identity-idp/pull/11615) and caused a linting error 🙈
=> changelog: Internal, Linting, Fix dot position

bin/summarize-user-events, lib/event_summarizer/idv_matcher.rb
=> [HACKATHON] Minor tweaks

dockerfiles/idp_deploy.Dockerfile
=> missed a spot in ruby dockerfile

dockerfiles/application.yaml
=> fix service providers in dbsetup reviewapps

config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/i18n_spec.rb
[LG-15398: Add translations for all copy about 1/9 Post Office closure](https://cm-jira.usa.gov/browse/LG-15398)
- I added translations for the temporary copy.  Translations [here](https://docs.google.com/spreadsheets/d/191yZ5GO9MhZKA-lU2T7LATQk8p0EHPDeHWh_8-OYiac/edit?gid=0#gid=0).
Screenshots and testing plan to come.
Verify translations.  Follow the testing plans from PR #11707  and PR #11702.
PR #11702 testing plan:
PR #11707 testing plan:
1. http://localhost:3000/rails/mailers/user_mailer/in_person_ready_to_verify
2. http://localhost:3000/rails/mailers/user_mailer/in_person_ready_to_verify_enhanced_ipp_enabled
3. http://localhost:3000/rails/mailers/user_mailer/in_person_ready_to_verify_reminder
4. http://localhost:3000/rails/mailers/user_mailer/in_person_ready_to_verify_reminder_enhan …
=> LG-15398: Add translations for all copy about 1/9 Post Office closure

dockerfiles/nginx.Dockerfile
https://gitlab.login.gov/lg-teams/mary/team-mary/-/issues/190
=>   Pin Alpine image to 3.20

config/locales/fr.yml, config/locales/zh.yml
[LG-15386](https://cm-jira.usa.gov/browse/LG-15386)
Updates content to address LQA. for french and simplified chinese
- Sign in via SP
- create or sign in to an account throough flow
- Get to select email page for sp
- Verify new langugae matches LQA corrections.
=> LG-15386: LQA updates

spec/support/shared_examples/mailer_preview.rb
This was added to support changing the name of a template in #11604 and is no longer needed.
=> Remove preview_methods_that_can_be_missing

app/javascript/packages/document-capture/components/acuant-capture.tsx
[LG-13668](https://cm-jira.usa.gov/browse/LG-13668)
Updated aria label for selfie capture to use preferred text according to UX.
=> lg-13668 change aria label for selfie capture

app/assets/fonts/glyphs.txt, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/i18n_spec.rb
changelog: User-Facing Improvements, Translations, Update translations from LQA
[LG-15508](https://cm-jira.usa.gov/browse/LG-15508)
Screenshots are attached to the ticket
=> Update translations from LQA

app/controllers/concerns/idv/doc_auth_vendor_concern.rb, app/services/idv/socure_user_set.rb, spec/controllers/idv/document_capture_controller_spec.rb, spec/controllers/idv/hybrid_mobile/entry_controller_spec.rb
[LG-15275](https://cm-jira.usa.gov/browse/LG-15275)
Checking the count of socure user set to determine if we need to force the user into LexisNexis flow. Adding tests to confirm
=> LG-15275 enforce limit of allowed Socure users

docs/frontend.md
Adds an introductory section to the existing [front-end documentation](https://github.com/18F/identity-idp/blob/main/docs/frontend.md) with sections detailing how JavaScript and CSS are compiled from source files during deployment.
This is prompted partly by a recent request by a team to better understand our JavaScript build pipeline.
Related to #11807
Review [updated information](https://github.com/18F/identity-idp/blob/aduth-frontend-build-tooling/docs/frontend.md) for accuracy and helpfulness.
=> Add build tooling sections to frontend documentation

lib/reporting/identity_verification_report.rb, spec/lib/reporting/identity_verification_report_spec.rb
Here's Gitlab ticket
[15411](https://gitlab.login.gov/lg-teams/agnes/data-warehouse-ag/-/issues/585)
There was a difference in the date being passed and checking for the full days worth of records. 
=> update end of day bug

app/mailers/report_mailer.rb
- Options were removed as part of refactor in #9408
=> Remove param documentation for since-removed options

Gemfile.lock
The [recent updates](https://github.com/premailer/css_parser/compare/v1.19.1...v1.21.0) include some performance improvements that I think should benefit us.
=> Update css_parser gem

app/presenters/socure_error_presenter.rb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/features/idv/doc_auth/socure_document_capture_spec.rb, spec/views/idv/socure/errors/show.html.erb_spec.rb
[LG-14066](https://cm-jira.usa.gov/browse/LG-14066)
Updating language of rate limit page in doc auth. Also updated test that checked use of other yml variable.
<details>
<summary>After/As-Built:</summary>
</details>
=> Lg-14066 implement new language for rate limit screen

app/models/user.rb, app/presenters/confirmation_email_presenter.rb, app/services/send_sign_up_email_confirmation.rb, config/initializers/new_relic_tracers.rb, lib/ab_test.rb, lib/mailer_sensitive_information_checker.rb
These are all methods we have been tracing for some time, but we don't appear to have any specific need for at the moment.
=> Remove some NewRelic method tracing

config/newrelic.yml
We don't use distributed tracing, so this PR disables it.
=> Disable distributed tracing in NewRelic

app/components/tab_navigation_component.html.erb, app/components/tab_navigation_component.rb, app/components/tab_navigation_component.scss, app/javascript/packages/analytics/README.md, app/views/devise/sessions/new.html.erb, app/views/sign_up/registrations/new.html.erb, spec/components/tab_navigation_component_spec.rb, spec/features/saml/saml_spec.rb, spec/features/visitors/password_recovery_spec.rb, spec/support/features/session_helper.rb, spec/views/devise/sessions/new.html.erb_spec.rb
- Sign In: Improve design clarity of "Sign In" / "Create an Account" tabs ([#11898](https://github.com/18F/identity-idp/pull/11898))
=> Deploy RC 453.1 to Production

app/services/doc_auth/dos/request.rb, app/services/doc_auth/dos/requests/mrz_request.rb, config/application.yml.default, lib/identity_config.rb, spec/services/doc_auth/dos/request_spec.rb, spec/services/doc_auth/dos/requests/mrz_request_spec.rb
[LG-15675](https://cm-jira.usa.gov/browse/LG-15675), subtask to [LG-15670](https://cm-jira.usa.gov/browse/LG-15670)
Initial request classes for MRZ check with DoS.
=> LG-15675: Request class for MRZ check API calls

app/forms/idv/api_image_upload_form.rb, app/jobs/recaptcha_annotate_job.rb, app/models/recaptcha_assessment.rb, app/services/recaptcha_annotator.rb, app/services/usps_in_person_proofing/enrollment_helper.rb, db/primary_migrate/20250224134110_create_recaptcha_assessments.rb, db/schema.rb, spec/factories/recaptcha_assessments.rb, spec/forms/idv/api_image_upload_form_spec.rb, spec/jobs/recaptcha_annotate_job_spec.rb, spec/services/recaptcha_annotator_spec.rb, spec/support/passport_api_helpers.rb
- Performance: Offload reCAPTCHA annotations to worker job ([#11883](https://github.com/18F/identity-idp/pull/11883))
=> Deploy RC 456 to Production

app/jobs/account_creation_threat_metrix_job.rb, spec/jobs/account_creation_threat_metrix_job_spec.rb
[LG-15714](https://cm-jira.usa.gov/browse/LG-15714)
Adds a Param to worker argument. Needs to be merged before https://github.com/18F/identity-idp/pull/11934
=> LG-15714: Add param to worker argument

Gemfile, Gemfile.lock
I updated ruby-saml to respond to this security vulnerability.   https://nvd.nist.gov/vuln/detail/CVE-2025-25292
=> update ruby-saml [skip changelog]

app/controllers/accounts/connected_accounts/selected_email_controller.rb, app/controllers/concerns/saml_idp_auth_concern.rb, app/controllers/openid_connect/authorization_controller.rb, app/controllers/sign_up/select_email_controller.rb, app/controllers/users/email_confirmations_controller.rb, app/models/service_provider_identity.rb, app/views/accounts/_connected_app.html.erb, app/views/sign_up/completions/show.html.erb, config/application.yml.default, lib/identity_config.rb, spec/controllers/accounts/connected_accounts/selected_email_controller_spec.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/controllers/sign_up/select_email_controller_spec.rb, spec/controllers/users/email_confirmations_controller_spec.rb, spec/features/openid_connect/authorization_confirmation_spec.rb, spec/features/saml/authorization_confirmation_spec.rb, spec/models/service_provider_identity_spec.rb, spec/services/attribute_asserter_spec.rb, spec/views/accounts/connected_accounts/show.html.erb_spec.rb, spec/views/sign_up/completions/show.html.erb_spec.rb
[LG-14534](https://cm-jira.usa.gov/browse/LG-14534)
Removes feature flag and any code involved with leveraging it to enable toggling the share email with partner feature.
Specs should pass and feature will continue to function without error.
=> LG-14534 Remove Share email with partner flag

lib/reporting/sp_proofing_events_by_uuid.rb, spec/lib/reporting/sp_proofing_events_by_uuid_spec.rb
The partner who receives this report requested that the issuer and app differentiator be included in the table. This commit adds them.
=> LG-15923 Add the issuer and app differentiator to the UUID report

app/controllers/idv/ssn_controller.rb, spec/controllers/idv/ssn_controller_spec.rb
[LG-15730](https://cm-jira.usa.gov/browse/LG-15730)
Add state id type check to ssn controller next step url to send user to adddress step if passport.
=> lg-15730 send doc auth user to address step if passport

app/services/attempts_api/request_token_validator.rb, spec/controllers/api/attempts/events_controller_spec.rb, spec/services/attempts_api/request_token_validator_spec.rb
In doing some testing for the Attempts API interface, I found a bug in how the allowed_attempts_providers configuration calls.
=> changelog: Internal, Attempts Api, Fixing configuration access

config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
[LG-15441](https://cm-jira.usa.gov/browse/LG-15441)
Updating content and translations for 'Verify your information' and 'Verify your phone number' screens.
<details>
</details>
=> lg-15441 Update 'Verify your information' and 'Verify your phone number' screens for passports

app/views/idv/address/new.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
[LG-15446](https://cm-jira.usa.gov/browse/LG-15446)
Made some changes to our 'Update you address' screen to encourage users to verify with their current residential address.
=> LG-15446 changes to update address screen

app/controllers/users/sessions_controller.rb, config/application.yml.default, config/routes.rb, lib/identity_config.rb, spec/controllers/users/sessions_controller_spec.rb, spec/features/ialmax/saml_sign_in_spec.rb
A very late followup to https://github.com/18F/identity-idp/pull/8998, but this has been enabled and can safely be removed now.
=> Remove GET /logout path

app/javascript/packages/components/link.tsx, app/javascript/packages/document-capture/components/acuant-capture.tsx, app/javascript/packages/document-capture/components/document-capture-review-issues.spec.tsx, app/javascript/packages/document-capture/components/document-capture-review-issues.tsx, app/javascript/packages/document-capture/components/document-capture-troubleshooting-options.tsx, app/javascript/packages/document-capture/components/document-capture-warning.tsx, app/javascript/packages/document-capture/components/document-capture.tsx, app/javascript/packages/document-capture/components/in-person-location-full-address-entry-post-office-search-step.spec.tsx, app/javascript/packages/document-capture/components/in-person-outage-alert.spec.tsx, app/javascript/packages/document-capture/components/in-person-prepare-step.spec.tsx, app/javascript/packages/document-capture/components/review-issues-step.tsx, app/javascript/packages/document-capture/context/in-person.ts, app/javascript/packs/document-capture.tsx, app/services/doc_auth_router.rb, app/views/idv/shared/_document_capture.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/features/idv/doc_auth/document_capture_spec.rb, spec/features/idv/doc_auth/redo_document_capture_spec.rb, spec/javascript/packages/document-capture/components/acuant-capture-spec.jsx, spec/javascript/packages/document-capture/components/document-capture-warning-spec.jsx, spec/javascript/packages/document-capture/components/review-issues-step-spec.jsx, spec/javascript/packages/document-capture/components/tip-list-spec.jsx, spec/services/doc_auth_router_spec.rb
[LG-15450](https://cm-jira.usa.gov/browse/LG-15450)
Updating content on errors and doc auth pages to support passport
<details>
</details>
=> Lg 15450 update state id content and document errors to support passport

app/controllers/idv/phone_controller.rb
While looking at some rate-limiting functionality as part of other work, I noticed that a couple of methods in the `Idv::PhoneController` may not be used. This PR removes them.
=> Remove unused methods in Idv::PhoneController

app/views/idv/in_person/state_id/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
[LG-15443](https://cm-jira.usa.gov/browse/LG-15443)
<details>
</details>
=> lg-15443 Alert for IPP users on required ID type for passports

lib/data_requests/deployed/create_mfa_configurations_report.rb, lib/data_requests/local/write_user_info.rb, spec/lib/data_requests/deployed/create_mfa_configurations_report_spec.rb, spec/lib/data_requests/local/write_user_info_spec.rb
changelog: Internal, IG Report, Remove unnecessary internal id in report
=> Remove unnecessary internal id in report

app/controllers/idv/in_person/ssn_controller.rb, app/controllers/idv/ssn_controller.rb, lib/idp/constants.rb, spec/controllers/idv/in_person/ssn_controller_spec.rb, spec/controllers/idv/in_person/verify_info_controller_spec.rb, spec/controllers/idv/ssn_controller_spec.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/features/idv/end_to_end_idv_spec.rb, spec/jobs/resolution_proofing_job_spec.rb, spec/jobs/socure_shadow_mode_proofing_job_spec.rb, spec/services/proofing/resolution/plugins/phone_finder_plugin_spec.rb, spec/services/proofing/socure/id_plus/input_spec.rb, spec/support/features/doc_auth_helper.rb, spec/support/idv_examples/sp_requested_attributes.rb
This is required to make any comparisons of ssn_signature meaningful.
changelog: Bug Fixes, Profiles, Normalize SSN before save
=> Normalize SSN before save

app/controllers/idv/enter_password_controller.rb, app/models/user.rb, app/services/attempts_api/tracker_events.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/models/user_spec.rb
[163](https://gitlab.login.gov/lg-teams/Melba/protocols-backlog/-/issues/163)
This change:
- adds the new idv-reproof event
- adds tests
-->
=> Add idv-reproof event

Gemfile.lock, app/controllers/concerns/idv/verify_info_concern.rb, app/controllers/idv/enter_password_controller.rb, app/models/user.rb, app/services/attempts_api/tracker_events.rb, lib/event_summarizer/idv_matcher.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/models/user_spec.rb
- Developer tooling: Bugfix for summarize-user-events ([#11941](https://github.com/18F/identity-idp/pull/11941))
- Gemfile Update: Update to fix vulnerability (#12113) ([#12113](https://github.com/18F/identity-idp/pull/12113))
- Attempts API: Add idv-reproof event ([#12103](https://github.com/18F/identity-idp/pull/12103))
- Attempts API: Add tmxreview event ([#12099](https://github.com/18F/identity-idp/pull/12099))
=> Deploy RC 473 to Production

app/controllers/concerns/idv/verify_info_concern.rb, app/controllers/idv/address_controller.rb, app/controllers/idv/by_mail/request_letter_controller.rb, app/presenters/idv/address_presenter.rb, app/services/idv/session.rb, app/views/idv/address/new.html.erb, app/views/idv/by_mail/request_letter/index.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/features/idv/confirm_start_over_spec.rb, spec/features/idv/steps/request_letter_step_spec.rb, spec/views/idv/address/new.html.erb_spec.rb
[LG-15447](https://cm-jira.usa.gov/browse/LG-15447)
Updating page content and routing to support re-entering mailing address for verify by mail.
<details>
</details>
=> Lg-15447 support re enter mail address for verify by mail

app/services/idv/duplicate_ssn_finder.rb, lib/data_pull.rb, spec/lib/data_pull_spec.rb, spec/services/idv/duplicate_ssn_finder_spec.rb
Link to the relevant tickets:
[!877](https://gitlab.login.gov/lg-teams/agnes/data-warehouse-ag/-/issues/877)
[LG-16135](https://cm-jira.usa.gov/browse/LG-16135)
This PR implements a report for reviewing SSN signatures across profiles. Example output:
```
+--------------------------------------+------------+--------+------------------------------------------------------------------+---------------------+-------------------------+-----------------+------------------------------------+--------------------------------+---------------------------+
| uuid                                 | profile_id | status | ssn_signature                                                    | idv_level           | activated_timestamp     | disabled_reason | gpo_verification_pending_timestamp | …
```
=> Create SSN Signature Report

spec/features/idv/cancel_spec.rb, spec/support/features/doc_auth_helper.rb
Updating cancel_spec to check for page content to load, giving JS time to load items causing flakey behavior. 
=> Fix flakey cancel spec

app/controllers/application_controller.rb, app/services/attempts_api/tracker.rb, app/services/attempts_api/tracker_events.rb, spec/services/attempts_api/tracker_spec.rb
Addresses a couple bugs from #12155
=> Fix incorrect event exceptions and nil users

lib/reporting/api_transaction_count_report.rb, spec/lib/reporting/api_transaction_count_report_spec.rb
🎫 Ticket
[Ticket 88](https://gitlab.login.gov/lg-teams/Team-Data/reporting/-/issues?assignee_username%5B%5D=kolawole.oseni&first_page_size=20&sort=created_date&state=opened&show=eyJpaWQiOiI4OCIsImZ1bGxfcGF0aCI6ImxnLXRlYW1zL1RlYW0tRGF0YS9yZXBvcnRpbmciLCJpZCI6MTc3MDB9)
Added additional query to report
=> Added additional query

app/controllers/idv/in_person/passport_controller.rb, app/forms/idv/in_person/passport_form.rb, app/services/analytics_events.rb, app/validators/idv/in_person/form_passport_validator.rb, app/views/idv/in_person/passport/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/controllers/idv/in_person/passport_controller_spec.rb, spec/features/idv/in_person/passport_scenario_spec.rb, spec/forms/idv/in_person/passport_form_spec.rb, spec/i18n_spec.rb, spec/views/idv/in_person/passport/show.html.erb_spec.rb
[LG-15985](https://cm-jira.usa.gov/browse/LG-15985)
Add passport submit without DoS surname check
**Scenario: User submits passport with valid info** 
**Scenario: User submits passport with invalid info** 
**Scenario: User submits passport with blank form** 
<details>
<summary>Errors with invalid info</summary>
<summary>Invalid passport number</summary>
<summary>Expired passport book</summary>
</details>
<details>
<summary>Errors for blank page</summary>
</details>
=> LG-15985 Add passport submit without DoS surname check

config/initializers/ab_tests.rb
This changes the Manual Upload A/B test to allow for tracking on all events.
=> Change logging for Manual Upload A/B tests

app/jobs/reports/monthly_irs_verification_report.rb, config/initializers/job_configurations.rb, spec/jobs/reports/monthly_irs_verification_report_spec.rb, spec/mailers/previews/report_mailer_preview.rb
🎫 Ticket
GL-79
[Gitlab Issue #79](https://gitlab.login.gov/lg-teams/Team-Data/reporting/-/issues/79)
🛠 Summary of changes
--> Created the MonthlyIrsVerificationReport the job for monthly irs verification report that will create report for monthly range
--> Updated job_configurations.rb to schedule that job to run at every month using the existing CRON schedular
-->  Added spec files containing unit tests for rails job
--> Add MonthlyIrsVerificationReport job to report_mailer_preview.rb for manual local testing
📜 Testing Plan
<details>
</details>
<details> …
=> 79 irs monthly verification report

app/services/email_masker.rb, spec/services/email_masker_spec.rb
Upcoming Features, One Verified Account, Improve email masking
[LG-16287](https://cm-jira.usa.gov/browse/LG-16287)
=> Avoid exposing length of username part of email

app/jobs/reports/irs_verification_report.rb
[LG-47](https://gitlab.login.gov/lg-teams/Team-Data/reporting/-/issues?assignee_username%5B%5D=kolawole.oseni&first_page_size=20&sort=created_date&state=opened&show=eyJpaWQiOiI0NyIsImZ1bGxfcGF0aCI6ImxnLXRlYW1zL1RlYW0tRGF0YS9yZXBvcnRpbmciLCJpZCI6MTUxMTZ9)
Changed location of definition table 
Updated export file to use csv 
=> Report fix

spec/jobs/socure_docv_results_job_spec.rb
The `document_capture_session` var in the `SocureDocvResultsJob` spec was not set up correctly, which was exposed in a recent change where the stub_request got more specific. This updates the spec to set up the var correctly.
=> Update document_capture_session var

config/initializers/job_configurations.rb
🎫 Ticket
[Issue-60](https://gitlab.login.gov/lg-teams/Team-Data/reporting/-/issues/60)
Cron job to run monthly report that is already deployed
<!--
📜 Testing Plan
=> monthly cron job for irs credentials

app/views/users/emails/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
changelog: User-Facing Improvements, Account Management, Update browser title
Fixes https://cm-jira.usa.gov/browse/LG-16271.
[LG-16271](https://cm-jira.usa.gov/browse/LG-16271)
=> Update browser title to be consistent with page heading

app/presenters/idv/how_to_verify_presenter.rb, app/views/idv/how_to_verify/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/features/idv/doc_auth/document_capture_spec.rb, spec/features/idv/doc_auth/redo_document_capture_spec.rb, spec/support/features/doc_auth_helper.rb, spec/views/idv/how_to_verify/show.html.erb_spec.rb
[LG-16308](https://cm-jira.usa.gov/browse/LG-16308)
Updated the How to Verify page on mobile to make it more clear and consistent. If you are on a mobile device you will not get prompts to switch to a phone.
<details>
<summary>Before Enhanced IAL2:</summary>
</details>
<details>
<summary>After Enhanced IAL2:</summary>
</details>
=> LG-16308 choose how to verify update

app/jobs/reports/monthly_irs_verification_report.rb
<
GL-79
[GL issue #79](https://gitlab.login.gov/lg-teams/Team-Data/reporting/-/issues/79)
--> Fix the monthly IRS verficationm report job by removing the title argument from ReportMailer
<details>
</details>
<details>
</details>
=> changelog: Internal, Reporting,fix Monthly IRS Verification Report job

app/controllers/idv/hybrid_handoff_controller.rb, app/controllers/users/piv_cac_recommended_controller.rb, app/controllers/users/two_factor_authentication_setup_controller.rb, app/presenters/duplicate_profiles_detected_presenter.rb, app/services/threat_metrix_helper.rb, app/views/duplicate_profiles_detected/_account_information.html.erb, app/views/duplicate_profiles_detected/show.html.erb, app/views/users/piv_cac_recommended/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/controllers/idv/hybrid_handoff_controller_spec.rb, spec/jobs/socure_docv_results_job_spec.rb, spec/presenters/duplicate_profiles_detected_presenter_spec.rb
- TMX: Adds tmx session id for piv cac recommended users ([#12323](https://github.com/18F/identity-idp/pull/12323))
- One Account: Initial designs for users with duplicate profiles ([#12309](https://github.com/18F/identity-idp/pull/12309))
=> Deploy RC 494 to Production

docs/attempts-api/schemas/events/shared/EventProperties.yml
=> changelog: Internal, Attempts API, Update device_id documentation

app/jobs/reports/irs_monthly_cred_metrics_report.rb
[Gitlab - 60](https://gitlab.login.gov/lg-teams/Team-Data/reporting/-/issues/60)
New definitions of metrics accepted by the IRS.
=> "changelog: Internal, Reporting, IRS Monthly Credential Metrics Report"

Gemfile, Gemfile.lock, spec/controllers/two_factor_authentication/sms_opt_in_controller_spec.rb
Troubleshooting some AWS API issues [here](https://gsa-tts.slack.com/archives/C16RSBG49/p1752597696371669), so this updates our AWS gems (as well as Bundler).
=> Update Bundler and AWS gems

app/controllers/idv/agreement_controller.rb, spec/features/idv/doc_auth/socure_document_capture_spec.rb, spec/support/features/doc_auth_helper.rb
Reverts 18F/identity-idp#12324
=> Revert "Bug Fixes, Passports, Allow non-IPP flows to reach choose_id_type screen"

app/controllers/duplicate_profiles_detected_controller.rb, app/controllers/users/sessions_controller.rb, app/jobs/alert_user_duplicate_profile_discovered_job.rb, app/mailers/user_mailer.rb, app/services/duplicate_profile_checker.rb, app/views/user_mailer/dupe_profile_account_review_complete_locked.html.erb, app/views/user_mailer/dupe_profile_account_review_complete_success.html.erb, app/views/user_mailer/dupe_profile_account_review_complete_unable.html.erb, app/views/user_mailer/dupe_profile_created.erb, app/views/user_mailer/dupe_profile_sign_in_attempted.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/controllers/duplicate_profiles_detected_controller_spec.rb, spec/jobs/alert_user_duplicate_profile_discovered_job_spec.rb, spec/mailers/previews/user_mailer_preview.rb, spec/services/duplicate_profile_checker_spec.rb
[LG-16415](https://cm-jira.usa.gov/browse/LG-16415)
Add one account Email notifications, added to the email previewer for now
Also added notification for dupe profile discovered on sign in. 
**Dupe Profile Verified email**
**Dupe profile Sign in attempted email** 
**Account Locked email** 
**Account Review Successfully completed**
**Account Review unable to sign user in**
=> LG-16415: One account Email notifications

app/controllers/concerns/idv/choose_id_type_concern.rb, app/controllers/idv/welcome_controller.rb, app/services/analytics_events.rb, app/services/doc_auth/dos/requests/health_check_request.rb, spec/controllers/concerns/idv/choose_id_type_concern_spec.rb, spec/features/idv/doc_auth/choose_id_type_spec.rb, spec/features/idv/doc_auth/welcome_spec.rb, spec/services/doc_auth/dos/requests/health_check_request_spec.rb
[LG-16484](https://cm-jira.usa.gov/browse/LG-16484)
Adding logs for step in health check request log.
Demo Video of existing banner that matched desired content: https://drive.google.com/file/d/1UugA_IlrqUR6PdIfvkCqiWw8R34ZuWRs/view?usp=sharing
=> Lg-16484 create new alert banner for dos api down

config/locales/zh.yml
[LG-15918](https://cm-jira.usa.gov/browse/LG-15918)
Updating chinese tranaslation for account page
=> lg-15918 update chinese translations for account page

config/locales/en.yml
changelog: Upcoming Features, One Account, Fix minor typo in content
=> Fix minor typo in content

app/services/marketing_site.rb, app/views/duplicate_profiles_detected/show.html.erb, app/views/users/duplicate_profiles_please_call/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml
[LG-16547](https://cm-jira.usa.gov/browse/LG-16547)
Updates translated copy for the duplicate_profiles_detected view.
<details>
</details>
<details>
</details>
<details>
</details>
<details>
<summary>Chinese</summary>
</details>
=> LG-16547 Implement translations for LG-16261

app/controllers/api/attempts/events_controller.rb, docs/attempts-api/schemas/PollParameters.yml, spec/controllers/api/attempts/events_controller_spec.rb
[secure protocols #53](https://gitlab.login.gov/lg-teams/FIE/secure-protocols/-/issues/53#description)
Updates `acks` paramter to `ack` to conform to [spec](https://www.rfc-editor.org/rfc/rfc8936.html#name-poll-with-acknowledgement)
=> Update param to be conformant to spec

app/models/duplicate_profile.rb, app/models/profile.rb, spec/models/profile_spec.rb
changelog: Upcoming Features, One Account, Check only against "open" DuplicateProfile
=> Check only against "open" DuplicateProfile

config/locales/zh.yml
[LG-16649](https://cm-jira.usa.gov/browse/LG-16649)
Updating Chinese error content for phone error screen
<details>
</details>
=> lg-16649 update chinese translations for phone error screen

app/controllers/concerns/one_account_concern.rb, app/controllers/users/delete_controller.rb, app/controllers/users/service_provider_revoke_controller.rb, app/models/duplicate_profile_set.rb, app/services/account_reset/delete_account.rb, app/services/analytics_events.rb, spec/controllers/users/delete_controller_spec.rb, spec/controllers/users/service_provider_revoke_controller_spec.rb, spec/services/account_reset/delete_account_spec.rb
[LG-16449](https://cm-jira.usa.gov/browse/LG-16449)
add metrics to account linking or account deletion to mark users who are going through and disconnecting their accounts from software. 
=> LG-16449: measure self service metrics 

app/controllers/concerns/idv/id_concern.rb, app/controllers/idv/in_person/passport_controller.rb, app/controllers/idv/in_person/state_id_controller.rb, app/forms/idv/state_id_form.rb, app/validators/idv/form_state_id_validator.rb, app/views/idv/in_person/state_id/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, lib/idp/constants.rb, spec/controllers/idv/in_person/state_id_controller_spec.rb, spec/features/idv/steps/in_person/state_id_spec.rb, spec/forms/idv/state_id_form_spec.rb, spec/i18n_spec.rb, spec/services/proofing/aamva/request/verification_request_spec.rb, spec/support/features/in_person_helper.rb, spec/views/idv/in_person/state_id/show.html.erb_spec.rb
[LG-16717](https://cm-jira.usa.gov/browse/LG-16717)
Adds expiration date as a required field when entering state ID information. Date is saved in pii bundle to be sent to AAMVA.
Go through the IPP flow. You should not be able to continue unless you enter an expiration date at least 2 days in the future.
If you add a breakpoint in the `proof` method of the mock proofers (e.g., `IdMockClient`, `AddressMockClient`, etc.) you can see that the applicant includes the `state_id_expiration`.
<details>
<summary>en:</summary>
| Expired | Required | Incomplete |
|--------|----------|-------------|
| <img width="415" height="1493" alt="LG-16727-expired" …
=> LG-16717: Collect state ID expiration date for IPP

Gemfile.lock, db/worker_jobs_migrate/20251006145302_add_index_good_jobs_job_class.rb, db/worker_jobs_schema.rb
good_job has had a few releases including a performance improvement via a new migration. This PR updates good_job and adds the new migration.
=> Update good_job with new migrations
