Gemfile, Gemfile.lock
**Why**: To pick up a change that allows hostdata configs to be overriden or specified with ENV vars
=> Update identity-hostdata to v3.0.0

app/controllers/concerns/unconfirmed_user_concern.rb
Seeing some infrequent errors related to casting this parameter
=> use strong params when confirming confirmation token

app/forms/idv/api_image_upload_form.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb
**Why**: Since the purpose of including the client-side image metadata is to better compare front-end and back-end metrics, it's sensible to structure them in such a way that they're identifiably separate, but organizationally similar.
<table>
<thead><tr><th>Before</th><th>After</th></tr></thead>
<tbody>
<tr><td><pre><code>{
front_image_metadata: {
glare: 99.99,
mimeType: 'image/jpeg',
// ...
},
back_image_metadata: {
// ...
},
image_metrics: {
front: {
GlareMetric: 99,
// ...
},
back: {
// ...
}
}
}</code></pre></td><td><pre><code>{
client_image_metrics: {
front: {
glare: 99.99,
mimeType: 'image/jpeg',
// ...
},
back: {
// ...
},
},
image_metrics: {
front: {
GlareMetric: 99,
// ...
},
back: {
// ...
}
}
}</code></pre></td></tr>
</tbody>
</table>
=> LG-4387: Restructure image metrics to align to backend metrics

app/controllers/users/email_confirmations_controller.rb, app/forms/add_user_email_form.rb, spec/forms/add_user_email_form_spec.rb
**Why**: Adding an email should not fire the RISC event until the email is confirmed. Follow up to https://github.com/18F/identity-idp/pull/4909
=> Fix email changed RISC event

app/javascript/packages/step-indicator/index.js, spec/javascripts/packages/step-indicator/index-spec.js
**Why**: While `scrollIntoView` is a convenient abstraction to center the current step in the view, it is designed to scroll elements with the _viewport_, not within any scrollable container. As such, the behavior can cause undesirable effects depending if the user has scrolled beyond the step indicator before the JavaScript has finished initializing, since it will forcibly bring the current step back into the viewport.
Operating on the scrollable container's `scrollLeft` property is more cumbersome and math-heavy, but maintains the same effect of horizontal centering without risk of shifting the user's viewport.
=> Step Indicator: Improve current step scroll centering

app/javascript/packages/document-capture/components/acuant-capture-canvas.jsx
Follow-up to: #4929
**Why**: As of Acuant SDK v11.4.4, the SDK now sets width and height attributes based on a desirable aspect ratio (see `setDimens` function, [Acuant SDK v11.4.4](https://github.com/Acuant/JavascriptWebSDKV11/blob/11.4.4/SimpleHTMLApp/webSdk/dist/AcuantJavascriptWebSdk.js) L828). Inline styles conflict with these attributes because they are of higher specificity, which can cause unexpected behavior.
Relevant documentation: https://github.com/Acuant/JavascriptWebSDKV11/tree/master/SimpleHTMLApp#start-live-capture
=> LG-4392: Set Acuant canvas width as HTML attribute

.codeclimate.yml, .rubocop.yml, Gemfile.lock, app/decorators/mfa_context.rb, app/policies/mfa_policy.rb
The old implementation of checking if a user has a two factor method enabled queried and loaded all of the different two factor types before checking if one existed. This change checks each two factor method one by one to reduce the number of queries.
Old implementation is effectively:
```ruby
(phone_configurations + webauthn_configurations + backup_code_configurations +
piv_cac_configurations + auth_app_configurations).any?(&:mfa_enabled?)
```
=> Be lazier when checking if two factor is enabled

Gemfile, Gemfile.lock
**Why**: To pick up a fix to hostdata that was preventing migration instances from working
=> Bump identity-hostdata to 3.1.2

app/models/service_provider.rb, spec/models/service_provider_spec.rb
**Why**: Our production data includes `cert: ""`
Causing errors in production :[
=> Update ServiceProvider#ssl_certs to handle empty string

app/models/service_provider.rb, spec/models/service_provider_spec.rb
Patch to include:
> Update ServiceProvider#ssl_certs to handle empty string (#4961)
> 
> **Why**: Our production data includes `cert: ""`
=> Deploy RC 137.2

app/validators/form_password_validator.rb, spec/forms/password_form_spec.rb, spec/support/shared_examples/password_strength.rb
We currently count codepoints when determining password length. NIST only describes "characters" when counting password length and a conservative interpretation would be to count graphemes instead of codepoints. This may lead to longer requirements for passwords in languages where glyphs are combined to create what appears to be one "character".
Example:
The 🇺🇸 emoji is two unicode codepoints  (🇺and 🇸) that would be three graphemes when separated by a space that become one grapheme when placed next to one another.
```ruby
"🇺 🇸".grapheme_clusters
"🇺 🇸".gsub(" ", "").grapheme_clusters
```
The password "123456🇺🇸🇺🇸🇺🇸" would be valid before these changes despite only appearing to be 9 characters. We would now require 3 more "characters".
=> validate password character length by graphemes (LG-4523)

app/javascript/packs/form-steps-wait.jsx, spec/javascripts/packs/form-steps-wait-spec.js
**Why**: So that Internet Explorer doesn't throw an error when clicking wait buttons.
See: https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation/createHTMLDocument
(Specifically, note about "Except in IE" for otherwise-optional `title` argument)
Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1619123286193700
=> Pass IE-required title argument for createHTMLDocument

app/controllers/users/two_factor_authentication_controller.rb
Found shortly after merging #4944 
Potentially save a roundtrip to the database by checking whether the device is mobile first
=> check device constraints for PIV/CAC before querying database

app/controllers/users/two_factor_authentication_controller.rb, app/services/idv/send_phone_confirmation_otp.rb, app/views/idv/otp_verification/show.html.erb, app/views/two_factor_authentication/otp_verification/show.html.erb, spec/controllers/test/telephony_controller_spec.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb, spec/features/two_factor_authentication/change_factor_spec.rb, spec/services/idv/send_phone_confirmation_otp_spec.rb
Previously: #4965, #4915
In #4965, we initially disabled the WebOTP behavior for OTP inputs, since it wasn't yet working in Android. Further testing revealed this was because the domain was too broad ("identitysandbox.gov" regardless of sandbox), and using the most specific host allows auto-fill to work as expected.
=> LG-3993: Enable WebOTP for OTP verification

app/jobs/address_proofing_job.rb, app/jobs/document_proofing_job.rb, app/jobs/resolution_proofing_job.rb, config/application.rb, config/initializers/zxcvbn_overrides.rb, spec/jobs/document_proofing_job_spec.rb, spec/jobs/resolution_proofing_job_spec.rb
Before:
- Log messages from the jobs went to `production.log`
- They were formatted with like `[ActiveJob] [blah] {:foo => true}`
After
- Log messages from the jobs goes to `worker.log`
- Example log message has correct formatting:
```
{"name":"ProofDocument","trace_id":"Root=1-60871e1c-445195a90aa4e4d11a218247","success":true,"timing":{"download.front":141.2,"decrypt.front":1.91,"download.back":39.25,"decrypt.back":0.46,"download.selfie":30.87,"decrypt.selfie":0.86,"proof_documents":2.75}}
```
=> Update worker log formatting

app/controllers/application_controller.rb, spec/controllers/application_controller_spec.rb
**Why**: This cookie is here to allow the ALB to sort out requests by issuer. If the session has ended then the request is no longer associated with that issuer.
This config does not appear to be set anywhere so currently the cookie has no expiration
=> Use the session expiration for the sp issuer cookie timeout

config/initializers/ahoy.rb
**Why**: We moved the session timeout in minutes into IdentityConfig
=> Convert a left over AppConfig session timeout call

config/application.yml.default
**Why**: Since they don't have a top-level value, removing them means they are still nil
=> Put the USPS configs back and make them empty strings

app/models/user.rb
This column isn't used, and has an index on it, so we should drop it 🙂
=> ignore users unlock token column

config/initializers/secure_headers.rb
Follow-up to #4984 (see https://github.com/18F/identity-idp/pull/4984#issuecomment-827834210)
**Why**: We should keep CSP domains strictly limited to required usage. These two domains are used by Recaptcha, which was removed in #4984. DAP Universal Analytics is expected to suffice with google-analytics.com.
See: https://developers.google.com/tag-manager/web/csp#universal_analytics_google_analytics
=> Remove Recaptcha domains from CSP

.circleci/config.yml
**Why**: Parallism of 8 seems a touch too high. Queue times are up when there are lots of builds and it is gumming up the works.
=> Reduce parallelism to 5

app/models/user.rb
Similar to #4988, these columns appear to be old and unused
=> ignore users unconfirmed_email and encrypted_otp_secret_key columns

app/views/idv/doc_auth/no_camera.html.erb, app/views/idv/shared/_error.html.erb, spec/views/idv/shared/_error.html.erb_spec.rb
**Why**: So that the page is styled consistently with other warning pages in the IAL2 flow.
Before|After
---|---
=> LG-4370: Refactor "No Camera" warning to use error partial

app/javascript/packages/document-capture/components/acuant-capture.jsx, package.json, spec/javascripts/packages/document-capture/components/acuant-capture-spec.jsx, spec/javascripts/spec_helper.js, spec/javascripts/support/sinon.js, yarn.lock
**Why**: To understand how many users are bouncing from the document capture step without ever beginning to try capturing or uploading images of their state-issued ID.
=> LG-4442: Log user clicks on document capture front, back images

spec/lib/feature_management_spec.rb
**Why**: The body of these specs actually uses the new IdentityConfig tooling
=> Rename specs that spuriosly referred to AppConfig

app/forms/idv/api_image_upload_form.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb
We want to be able to detect if certain state licenses are having more trouble than others. This PR adds the `state` found in the PII bundle, returned from the doc_auth client, to the logged event.
=> Add the ID's state to the vendor response event log (LG-4395)

.circleci/config.yml
**Why**: We're not using it right now
If we *really* wanted to be bold... would drop our `production.Dockerfile` too 😈
=> Remove building release container from CI pipeline

app/services/db/establish_connection/read_replica_connection.rb
**Why**: To wrap up the migration to IdentityConfig from AppConfig
=> Convert the read only database connection configs to IdentityConfig

app/views/idv/session_errors/throttled.html.erb, config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml, spec/views/idv/session_errors/throttled.html.erb_spec.rb
**Why**: If the verification does not require liveness, it is confusing to the user if we tell them we cannot verify the "photo of you", since they would not be prompted to capture a photo. We should only show this text if liveness is required.
Before|After
---|---
=> LG-4370: Update throttled error heading to account for liveness requirement

app/jobs/resolution_proofing_job.rb, app/services/idv/steps/verify_base_step.rb, app/services/idv/steps/verify_wait_step_show.rb, spec/jobs/resolution_proofing_job_spec.rb, spec/services/idv/agent_spec.rb
We currently lose a lot of information from the resolution proofing step, making it hard to understand dropoff and the types of errors users see in the proofing flow. The verify step is tricky since it may call one or both of AAMVA and LexisNexis in any order, and we want to preserve each individual call's results while still maintaining the format that the FlowStateMachine steps expect to be returned as a response.
This ends up duplicating a lot sometimes, but I'd rather err on the side of too much logging for now. We can pare it back if needed.
This does change the format of the context and stages, but I talked with @stevegsa and it doesn't sound like they are used for any reports. I also am assuming the reports don't depend on it since data is missing a lot of the time.
Example of …
=> log more things in the resolution proofing step (LG-4266)

public/robots.txt
Got a notification that `/api/saml/auth2021` was scraped by the Google search crawler and had empty content, which is kind of expected, seems easier to remove this from the index
=> Remove SAML API endpoints from being scraped by bots

app/javascript/packages/one-time-code-input/index.js, spec/javascripts/packages/one-time-code-input/index-spec.js
**Why**: Since we give users the choice to not remember the current browser so that they will be prompted for OTP on subsequent login attempts. With auto-submit, most users will not know that this option exists, since the prompt to auto-fill shows nearly instantaneously on page load. This is also more consistent with how iOS's "From Messages" OTP auto-fill behaves.
=> LG-3993: Avoid auto-submit for WebOTP autofill

app/assets/stylesheets/components/_btn.scss
This restores the fix from #4881, which was prematurely removed in #5014, as it had not been ported upstream to `identity-style-guide`. This is fixed in [USWDS v2.11.2](https://designsystem.digital.gov/about/releases/#version-2112) (https://github.com/uswds/uswds/pull/4077), so a future USWDS version sync in `identity-style-guide` will resolve it and allow us to remove it from the IdP.
**Why**: When an unstyled button is used as the submit button in a form, it can cause an issue where clicking the button would make it both disabled and active. This is because our default form validation will disable all submit buttons when a form is submitted. Since this happens at the same time as the link activation, and since the USWDS default disabled button styles conflict with the unstyled link …
=> Fix active, disabled, unstyled button background color (again)

config/application.yml.default, lib/identity_config.rb, lib/otp_code_generator.rb, spec/lib/otp_code_generator_spec.rb
Now that https://github.com/18F/identity-idp/pull/4965 is in prod, we can clean up this code
=> Cleanup: remove otp_use_alphanumeric feature flag

app/controllers/concerns/saml_idp_auth_concern.rb, config/application.yml.default, lib/identity_config.rb, spec/controllers/saml_idp_controller_spec.rb, spec/support/fake_saml_request.rb, spec/support/saml_auth_helper.rb
The flag has been turned on in all environments so we no longer need it or the conditional context it brings.
=> Remove AuthnContextClassRef AAL feature flag (LG-3486)

Gemfile, Gemfile.lock, app/services/doc_auth_router.rb, spec/jobs/document_proofing_job_spec.rb, spec/services/doc_auth_router_spec.rb
Update doc_auth gems and send Acuant and TrueID errors through the same error translation now that they go through the same error generation.
=> LG-4253 Combine Acuant and TrueID error translation

spec/support/fake_analytics.rb
A question in https://github.com/18F/identity-idp/pull/5042/files#r628487526 got me digging around to see what we actually log from the frontend, found this unused method ... with contants that no longer exist 🙊
=> Remove unused method on FakeAnalytics

app/services/analytics.rb, spec/features/visitors/i18n_spec.rb, spec/services/analytics_spec.rb
**Why**: To better understand what the language breakdowns look like for our flows, and so that we can identify abnormalities or discrepancies in metrics based on language.
=> LG-4397: Include locale in default logging data

Gemfile, Gemfile.lock
Includes changes from https://github.com/18F/identity-doc-auth/pull/16
=> increment identity-doc-auth version to handle physical document presence error

app/views/idv/gpo/_address_on_file.html.erb, app/views/idv/gpo/index.html.erb, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml
Just a couple of updates to the `Verify phone` and `Verify by mail` pages.
The updated pages (mobile view):
Verify Phone:
English|Spanish|French
---|---|---
Request a letter:
English|Spanish|French
---|---|---
=> LG-4524: updates to the copy on phone verification and gpo letter request

Gemfile, Gemfile.lock, app/services/doc_auth_router.rb, spec/services/doc_auth_router_spec.rb
Brings in https://github.com/18F/identity-doc-auth/pull/17
=> allow exception notifier to use :expected option to avoid false alerts

app/services/data_requests/lookup_shared_device_users.rb
**Why**: We need to add an index on cookie_uuid.  In the meantime this script worked on a failing data request.  Postgres appears to be throwing an exception after a certain level of nesting.  We also removed the join on users and devices.
=> LG-4602 Remove recursion and join on lookup shared device users

.rubocop.yml, app/forms/idv/consent_form.rb, app/validators/account_reset/cancel_token_validator.rb, app/validators/account_reset/granted_token_validator.rb, lib/linters/localized_validation_message_linter.rb, spec/lib/linters/localized_validation_mesasge_linter_spec.rb
**Why**: So that as a user navigating login.gov in a language other than English, error messages are translated in my preferred language.
Before|After
---|---
=> Fix untranslated custom validation error messages

app/services/phone_confirmation/confirmation_session.rb
From https://github.com/18F/identity-idp/pull/4965, our OTP codes are alphanumeric and should be case-insensitive. If you confirm your phone during the proofing process, the OTP check is currently case sensitive
=> ensure OTP phone confirmation is case-insensitive during identity proofing

app/forms/idv/api_document_verification_form.rb, app/jobs/document_proofing_job.rb, app/services/analytics.rb, app/services/idv/actions/verify_document_action.rb, app/services/idv/actions/verify_document_status_action.rb, app/services/idv/agent.rb, spec/forms/openid_connect_token_form_spec.rb, spec/jobs/document_proofing_job_spec.rb, spec/services/idv/actions/verify_document_status_action_spec.rb, spec/services/phone_confirmation/confirmaton_session_spec.rb, spec/support/fake_analytics.rb
Adds the `IDV_DOC_AUTH_SUBMITTED_IMAGE_UPLOAD_FORM` and `IDV_DOC_AUTH_SUBMITTED_PII_VALIDATION` events to the async document step flow. Moves the `IDV_DOC_AUTH_SUBMITTED_IMAGE_UPLOAD_VENDOR` event to be in the proofing job, and to pass the browser and client image metadata to the job for inclusion in the event data.
=> Async doc auth analytics (LG-4488)

app/controllers/application_controller.rb, app/controllers/users/piv_cac_login_controller.rb, app/controllers/users/sessions_controller.rb, app/models/monthly_sp_auth_count.rb, app/services/db/sp_cost/add_sp_cost.rb, app/services/ial_context.rb, spec/features/reports/authorization_count_spec.rb, spec/services/ial_context_spec.rb, spec/support/features/idv_from_sp_helper.rb, spec/support/oidc_auth_helper.rb, spec/support/saml_auth_helper.rb
Why
LG-4204 is a [follow up story to this PR ](https://github.com/18F/identity-idp/pull/4661) where we fixed the monthly auth counts.
This PR moves IAL2_STRICT and IAL_MAX to IalContext. This also fixes the monthly authentication counts and adds test coverage.
=> LG-4204 count ial2_strict and ial_max authentications

app/blueprints/agreements/iaa_blueprint.rb, app/models/agreements/iaa.rb, app/models/agreements/iaa_gtc.rb, app/models/agreements/iaa_order.rb, app/models/agreements/iaa_status.rb, app/services/agreements/db/iaas_by_agency.rb, app/services/agreements/reports/agency_iaas_report.rb, app/services/agreements/reports/partner_api_report.rb, spec/blueprints/agreements/iaa_blueprint_spec.rb, spec/models/agreements/iaa_gtc_spec.rb, spec/models/agreements/iaa_order_spec.rb, spec/models/agreements/iaa_spec.rb, spec/models/agreements/iaa_status_spec.rb, spec/services/agreements/db/iaas_by_agency_spec.rb, spec/services/agreements/reports/agency_iaas_report_spec.rb
* Update Agreements::Reports::PartnerApiReport to retrieve all IAAs and
upload them to S3
* Add associated query object, serializer, and reports
* Add abstract Iaa model to encapsulate a paired IaaGtc and IaaOrder
Nested on #5054
=> Add Partner API endpoint for IAAs (without usage)

app/blueprints/agreements/iaa_blueprint.rb, app/models/agreements/iaa.rb, app/models/agreements/iaa_order.rb, app/services/agreements/db/iaas_by_agency.rb, app/services/agreements/db/sp_return_log_scan.rb, app/services/agreements/iaa_usage.rb, app/services/agreements/reports/partner_api_report.rb, app/services/agreements/usage_summarizer.rb, spec/blueprints/agreements/iaa_blueprint_spec.rb, spec/models/agreements/iaa_order_spec.rb, spec/models/agreements/iaa_spec.rb, spec/models/sp_return_log_spec.rb, spec/services/agreements/db/sp_return_log_scan_spec.rb, spec/services/agreements/iaa_usage_spec.rb, spec/services/agreements/usage_summarizer_spec.rb
Part of LG-4236
* Add an SpReturnLogScan query object that does a table scan of the
sp_return_logs table and yields each record
* Add an IaaUsage service object that is instantiated with an IaaOrder
and implements a #count method to take an sp_return_log record and
update an authentications array and ial2_users set if appropriate
* Add a UsageSummarizer service object that users the SpReturnLogScan
and IaaUsage to reduce all of the sp_return_log records into a
collection of IaaUsages
* Add ial2_auths and authentications attributes to Iaa model and
serializer
* Add #in_pop? method to IaaOrder
* Modify the PartnerApiReport to run the usage summary and update the
list of IAAs with the relevant usage data
* Add model spec for SpReturnLog
=> Add usage to Partner API endpoint for IAAs

app/controllers/saml_idp_controller.rb, spec/controllers/saml_idp_controller_spec.rb
Resolves LG-4624
**Why:** so we can more easily identify which SPs are using which SAML endpoints
=> [LG-4624] Track SAML endpoint in the SAML Auth event

spec/support/monitor/monitor_idp_steps.rb
**Why**: Smoke tests run outside of Rails, so I18n
is not available
---
Small problem with #4968
Error
```
1) smoke test: sign in and out creates account, signs out, signs back in
Failure/Error: check t('sign_up.terms')
NoMethodError:
undefined method `t' for #<RSpec::ExampleGroups::SmokeTestSignInAndOut:0x0000558ab874b3d0>
```
=> Fix smoke tests

spec/support/monitor/monitor_idp_steps.rb
**Why**: Smoke tests run outside of rails,
so path helpers are not available
---
This time, from https://github.com/18F/identity-idp/pull/5040
(Deja vu? Last one was https://github.com/18F/identity-idp/pull/5084 for #4968)
Error
```
5) smoke test: SP initiated sign in OIDC redirects back to SP
Failure/Error: if current_path == rules_of_use_path
NameError:
undefined local variable or method `rules_of_use_path' for #<RSpec::ExampleGroups::SmokeTestSPInitiatedSignIn::OIDC:0x000056038d95ada8>
```
=> Fix smoke tests again

app/forms/register_user_email_form.rb, spec/forms/register_user_email_form_spec.rb
https://github.com/18F/identity-idp/pull/4968/files#diff-2219765553b20c3a8eda4854f307ca5e4b0ef35264cdae827216d0cdef8d3b3cL94 leads to the user not being created if Rules of Use is disabled
=> fix user not being saved when rules of use is disabled

.erb-lint.yml, app/views/idv/activated.html.erb, app/views/idv/fail.html.erb, app/views/idv/phone_errors/_warning.html.erb, app/views/idv/phone_errors/failure.html.erb, app/views/idv/session_errors/exception.html.erb, app/views/idv/session_errors/failure.html.erb, app/views/idv/session_errors/throttled.html.erb, app/views/idv/session_errors/warning.html.erb
**Why**: So that we lint .erb files the same way we lint .rb files.
You're probably going to want to [hide whitespace changes](https://user-images.githubusercontent.com/1779930/119189407-0a6a0a80-ba4a-11eb-8443-90aa06bd09a3.png) for review, though it may be worth considering if the sorts of whitespace changes are changes we're okay with.
=> Try enabling Rubocop linter for ERBLint

app/controllers/idv/capture_doc_controller.rb, app/controllers/idv/doc_auth_controller.rb, app/views/idv/capture_doc/document_capture.html.erb, app/views/idv/doc_auth/document_capture.html.erb, app/views/idv/doc_auth/welcome.html.erb, config/routes.rb, spec/features/idv/doc_auth/document_capture_step_spec.rb, spec/features/idv/doc_auth/welcome_step_spec.rb, spec/features/idv/doc_capture/document_capture_step_spec.rb
**Why**: So that we have better insight into steps where users are dropping off in the proofing flow. Centralizing to controllers allows for simplified coverage in proofing flows.
In practical terms, adds `step` detail for the "Welcome" screen "Get help at SP" link. It doesn't yet include:
- Cancellations
- Failures
=> LG-4504: Track Return to SP step via FlowStateMachine#next_step

app/views/idv/phone_errors/_warning.html.erb, app/views/idv/phone_errors/failure.html.erb, app/views/idv/phone_errors/jobfail.html.erb, app/views/idv/phone_errors/timeout.html.erb, app/views/idv/session_errors/exception.html.erb, app/views/idv/session_errors/failure.html.erb, app/views/idv/session_errors/throttled.html.erb, app/views/idv/session_errors/warning.html.erb, spec/views/idv/phone_errors/_warning.html.erb_spec.rb, spec/views/idv/phone_errors/failure.html.erb_spec.rb, spec/views/idv/phone_errors/jobfail.html.erb_spec.rb, spec/views/idv/phone_errors/timeout.html.erb_spec.rb, spec/views/idv/phone_errors/warning.html.erb_spec.rb, spec/views/idv/session_errors/exception.html.erb_spec.rb, spec/views/idv/session_errors/failure.html.erb_spec.rb, spec/views/idv/session_errors/throttled.html.erb_spec.rb, spec/views/idv/session_errors/warning.html.erb_spec.rb
**Why**: So we have better insight into where users are falling off in the proofing flow.
=> LG-4504: Log step for phone / verify warning screens Return to SP link

config/initializers/job_configurations.rb
Looks like it uses `.run` instead of `.call` 🙂
=> Fix PartnerApiReport job call

.erb-lint.yml, app/controllers/idv/cancellations_controller.rb, app/services/idv/actions/cancel_capture_doc_action.rb, app/views/idv/cancellations/destroy.html.erb, app/views/idv/cancellations/new.html.erb, app/views/idv/doc_auth/_start_over_or_cancel.html.erb, app/views/idv/doc_auth/agreement.html.erb, app/views/idv/doc_auth/email_sent.html.erb, app/views/idv/doc_auth/no_camera.html.erb, app/views/idv/doc_auth/ssn.html.erb, app/views/idv/doc_auth/upload.html.erb, app/views/idv/doc_auth/verify.html.erb, app/views/idv/doc_auth/welcome.html.erb, app/views/idv/otp_delivery_method/new.html.erb, app/views/idv/otp_verification/show.html.erb, app/views/idv/phone/new.html.erb, app/views/idv/review/new.html.erb, app/views/idv/shared/_document_capture.html.erb, spec/controllers/idv/cancellations_controller_spec.rb, spec/features/idv/doc_auth/cancel_spec.rb, spec/features/idv/doc_auth/welcome_step_spec.rb, spec/support/idv_examples/cancel_at_idv_step.rb
**Why**: So that we have better insight into where users are dropping from the proofing flow.
This should be the last of the pull requests related to this ticket, and covers cases where a user chooses "Cancel" from a step. There are multiple screens where a user is asked to confirm the cancellation before returning to the service provider. To track step, we retain this in a query parameter passed along between these screens.
Note that this uses [proposed updated canonical names](https://gsa-tts.slack.com/archives/CNCGEHG1G/p1621606419027400) for steps (e.g. "device_choice" instead of "upload"), but I don't feel strongly about keeping this if there's worry it might cause confusion from the inconsistency.
=> LG-4504: Track step from IAL2 cancellation

app/services/agreements/reports/agencies_report.rb, app/services/agreements/reports/agency_iaas_report.rb, app/services/agreements/reports/agency_partner_accounts_report.rb, app/services/agreements/reports/base_report.rb, spec/services/agreements/reports/agencies_report_spec.rb, spec/services/agreements/reports/agency_iaas_report_spec.rb, spec/services/agreements/reports/agency_partner_accounts_report_spec.rb
**Why:** There's a discrepancy between the two existing reports (agreements and accounts) that resulted in the agreements endpoint having uppercase agency paths (e.g. `GSA` instead of `gsa`). I'm going to try and make the paths all lowercase so that it's easier to have Lambda@Edge make the CloudFront distribution case-insensitive so needed to add this here.
=> [LG-4634] Downcase agency in Partner API agreements path

app/models/federated_protocols/saml.rb, app/services/service_provider_request_handler.rb, spec/support/saml_auth_helper.rb, spec/support/shared_examples/sign_in.rb
If a SAML SP is configured with IAL2, then a 500 error is displayed when authenticating with the "Sign in with your government employee ID" link
**Reproduction steps:**
1. Ensure you have an IAL2 verified account, configured with your PIV card
1. Go to the sample SAML app, choose `ServiceProvider configuration` for IAL level and sign in
1. Select "Sign in with your government employee ID"
1. Login with a PIV card
**Observed behaviour:**
A 500 error is displayed "undefined method `[]' for nil:NilClass"
**Expected behaviour:**
The user should be prompted for their password so PII can be decrypted
=> LG-4472: defer to the SP for default IAL level

app/jobs/heartbeat_job.rb, config/initializers/job_configurations.rb, spec/jobs/heartbeat_job_spec.rb
Creates a regularly scheduled heartbeat job for use by metrics to be able to ensure jobs are moving
=> Heartbeat Job (LG-4613)

Gemfile, Gemfile.lock, app/services/doc_auth_router.rb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, spec/services/doc_auth_router_spec.rb
LG-3452 Updating the doc-auth gem and adding the acuant http status code error translations.
=> LG-3452 Updating the doc-auth gem and adding the acuant http error translations

app/controllers/idv/capture_doc_status_controller.rb, app/javascript/packages/document-capture-polling/index.js, spec/controllers/idv/capture_doc_status_controller_spec.rb, spec/javascripts/packages/document-capture-polling/index-spec.js, spec/javascripts/support/dom.js
**Why**: As a user, I expect that if I encounter rate-limiting within the mobile document capture session that my desktop "Link sent" screen is updated to reflect this, so that I'm kept informed of the current progress of the hybrid session, and that I'm not waiting for the page to update if there's no chance that it will.
=> LG-4365: Redirect desktop session to error page when throttled in hybrid flow

app/controllers/idv/confirmations_controller.rb, app/controllers/idv/review_controller.rb, app/services/flow/flow_state_machine.rb, app/views/idv/address/new.html.erb, app/views/idv/come_back_later/show.html.erb, app/views/idv/confirmations/show.html.erb, app/views/idv/gpo/index.html.erb, app/views/idv/otp_delivery_method/new.html.erb, app/views/idv/otp_verification/show.html.erb, app/views/idv/phone/new.html.erb, app/views/idv/review/new.html.erb, app/views/users/verify_account/index.html.erb, config/application.yml.default, lib/identity_config.rb, spec/controllers/idv/confirmations_controller_spec.rb, spec/features/idv/doc_auth/address_step_spec.rb, spec/features/idv/doc_auth/document_capture_step_spec.rb, spec/features/idv/doc_auth/email_sent_step_spec.rb, spec/features/idv/doc_auth/link_sent_step_spec.rb, spec/features/idv/doc_auth/send_link_step_spec.rb, spec/features/idv/doc_auth/ssn_step_spec.rb, spec/features/idv/doc_auth/upload_step_spec.rb, spec/features/idv/doc_auth/verify_step_spec.rb, spec/features/idv/doc_capture/capture_complete_step_spec.rb, spec/features/idv/doc_capture/document_capture_step_spec.rb, spec/features/users/verify_profile_spec.rb, spec/support/idv_examples/confirmation_step.rb, spec/views/idv/come_back_later/show.html.erb_spec.rb, spec/views/idv/review/new.html.erb_spec.rb
Now that the step indicator is deployed, turned on in all environments, and loved by all, we no longer have a need to be able to turn it off. Thus the feature flag that controlled it's display has served its purpose, and is ready to retire to the feature flag farm in the country where it can spend its days relaxing with its friends.
Once this PR is deployed, we will need to go through all of the envs' settings to remove it there as well.
=> LG-4598: Remove the step indicator feature flag

app/models/profile.rb, app/services/key_rotator/hmac_fingerprinter.rb, app/services/pii/cacher.rb, spec/services/device_tracking/create_device_spec.rb
Found a small bug during the stale check for compound PII where we were comparing the signature to the fingerprint of the fingerprint, leading to the PII to always be considered stale. This meant updating all of the signatures, etc. any time a user with a profile logged in.
The impact is relatively low, we'll save maybe tens of milliseconds on session creation for the small percentage of users that have a profile.
=> Fix always stale pii fingerprint

app/models/service_provider.rb, spec/models/service_provider_spec.rb
**Why**: During a deploy, a cert may be named in the database
but not exist on the disk for older boxes.
Next steps: load these certs into the DB and stop relying on files on disk
=> Load ServiceProvider#ssl_certs more gracefully

app/services/service_provider_seeder.rb, spec/services/service_provider_seeder_spec.rb
**Why**: So we can share config data faster, instead of
having to wait on the local filesystem of each host to
update
Note:
Existing code already handles reading both cert names and PEMs from the DB (we use the PEM behavior mainly in INT/lower environments already):
https://github.com/18F/identity-idp/blob/main/spec/models/service_provider_spec.rb#L73-L100
=> Seed ServiceProvider PEMs directly to database certs column

app/services/email_confirmation_token_validator.rb
Postgres does not like null bytes
=> email confirmation token check should reject null byte in strings

app/services/document_capture_session_async_result.rb, app/services/idv/steps/link_sent_step.rb, spec/features/idv/doc_auth/link_sent_step_spec.rb, spec/features/idv/doc_capture/document_capture_step_spec.rb, spec/services/document_capture_session_async_result.rb, spec/support/features/doc_capture_helper.rb
**Why**: In the current sync flow, we assume presence of a result is sufficient to determine success. In the in-development async flow, we may have a result which is unsuccessful. Thus, we should expand consideration of success to include checking the result.
=> Align success consideration for async document capture result

app/services/data_requests/create_user_report.rb, spec/services/data_requests/create_user_report_spec.rb
**Why**: So that when agencies have many service providers, we can get a UUID they will recognize by searching with only the requesting service provider.
=> Use the agency UUID instead of the SP UUID in the user report

app/services/push_notification/http_push.rb, spec/services/push_notification/http_push_spec.rb
**Why**: These failures are more informative than urgent errors
=> Warn instead of notify for push notification delivery failures (LG-4553)

lib/tasks/db_rebuild_cookie_uuid_index.rake
**Why**: The migration to create this index timed out, leaving behind an invalid database index.
=> Add a rake task to rebuild the device cookie_uuid index

spec/factories/agencies.rb
Sometimes a test fails with:
```
Failures:
1) PushNotification::HttpPush#deliver with a non-200 response from a push notification url logs a warning
Failure/Error: agency { association :agency }
ActiveRecord::RecordInvalid:
Validation failed: Abbreviation has already been taken
```
Example: https://app.circleci.com/pipelines/github/18F/identity-idp/41317/workflows/4c734e9a-dbf1-46ce-90e6-a6ce80a5534e/jobs/66890/parallel-runs/2?filterBy=ALL
This appends the id to the abbreviation to avoid that kind of failure.
It happens because the list of industries and how we interpolate them can clash with our seeded agencies (mostly DOI and DOT):
https://github.com/18F/identity-idp/blob/main/spec/factories/agencies.rb#L3-L23
https://github.com/18F/identity-idp/blob/main/config/agencies.localdev.yml#L17 …
=> fix flaky test by ensuring agency abbreviation is unique

.circleci/config.yml
Currently we run the JS tests and asset precompilation in our parallel Ruby tests, so they get run 5 times instead of once. The changes here create a required initial setup step that does dependency installation and asset precompilation. JS tests are also split into their own step.
Dependencies are already cached, but they can still take some time when they are updated since we re-download all of them. Moving the dependency installation up into the initial setup ensures that the Lint, JS test, and Ruby test steps have a warm cache and don't all re-download the same dependencies.
The asset precompilation is required for some feature tests and the files are passed from the setup step to the Ruby build step via `persist_to_workspace`.
=> Reduce CI duplication to improve speed

app/presenters/two_factor_authentication/backup_code_selection_presenter.rb, config/locales/two_factor_authentication/en.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml
As a user, when presented with the choice of MFA options, I want to know that Backup Codes are considered the least secure option, so that if I'm given the choice between Phone and Backup Codes, I'm not motivated to choose Backup Codes out of convenience absent any indication they're considered relatively less secure.
This is an action item out of the analysis of LG-3791, where it was discovered that we saw an uptick in selections of "Backup Code" as an MFA option after we had changed the label of "Phone" to be described as equally "Less Secure". Since we consider Phone to be relatively more secure than Backup Codes, we should avoid presenting them as equally secure.
To do this, we changed the label of Backup Codes to "Least Secure". We also refreshed the translation of all labels, with …
=> LG-4632: Mark backup codes as "Least secure" to discourage use

app/controllers/concerns/saml_idp_auth_concern.rb, app/models/null_service_provider.rb, app/services/saml_request_validator.rb, config/application.yml.default, db/migrate/20210614145845_add_email_name_id_format_to_service_providers.rb, db/schema.rb, spec/controllers/saml_idp_controller_spec.rb, spec/services/saml_request_validator_spec.rb, spec/support/saml_auth_helper.rb
Resolves LG-4666
* Add allow_email_nameid_format column to the service_providers table,
defaulting to false, and populate all of the currently configured SPs
to be true
* Update SAML controller to use this column instead of comparing against
the list of issuers in the config
* Update specs as necessary
I'll add a PR to remove the old config separately and it should only be merged after this is deployed.
=> [LG-4666] Move email NameID format config to the DB

app/services/agreements/reports/agencies_report.rb, app/services/agreements/reports/agency_iaas_report.rb, app/services/agreements/reports/agency_partner_accounts_report.rb, app/services/agreements/reports/base_report.rb, app/services/reports/agency_invoice_iaa_supplement_report.rb, app/services/reports/agency_invoice_issuer_supplement_report.rb, app/services/reports/agency_user_counts_report.rb, app/services/reports/base_report.rb, app/services/reports/doc_auth_drop_off_rates_per_sprint_report.rb, app/services/reports/doc_auth_drop_off_rates_report.rb, app/services/reports/doc_auth_funnel_report.rb, app/services/reports/gpo_report.rb, app/services/reports/iaa_billing_report.rb, app/services/reports/monthly_gpo_letter_requests_report.rb, app/services/reports/omb_fitara_report.rb, app/services/reports/proofing_costs_report.rb, app/services/reports/sp_active_users_over_period_of_performance_report.rb, app/services/reports/sp_active_users_report.rb, app/services/reports/sp_cost_report.rb, app/services/reports/sp_success_rate_report.rb, app/services/reports/sp_user_counts_report.rb, app/services/reports/sp_user_quotas_report.rb, app/services/reports/total_monthly_auths_report.rb, app/services/reports/total_sp_cost_report.rb, app/services/reports/unique_monthly_auths_report.rb, app/services/reports/unique_yearly_auths_report.rb, spec/features/reports/omb_fitara_report_spec.rb
As part of LG-4648, I'm going to update the dropoff reports to have JSON versions as well, this takes the current ✌️  JSON ✌️  files and labels them as `txt` appropriately
=> Update reports in S3 to have correct extensions

app/javascript/packages/document-capture/components/acuant-capture-canvas.jsx, app/javascript/packages/document-capture/components/acuant-capture.jsx, app/javascript/packages/document-capture/components/full-screen.jsx, app/javascript/packages/document-capture/hooks/use-focus-trap.js, app/javascript/packages/document-capture/hooks/use-immutable-callback.js, app/javascript/packages/document-capture/hooks/use-toggle-body-class-by-presence.js, app/javascript/packages/document-capture/package.json, config/js_locale_strings.yml, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, spec/javascripts/packages/document-capture/components/acuant-capture-spec.jsx, spec/javascripts/packages/document-capture/components/full-screen-spec.jsx, spec/javascripts/packages/document-capture/hooks/use-focus-trap-spec.jsx, spec/javascripts/packages/document-capture/hooks/use-immutable-callback-spec.jsx, spec/javascripts/packages/document-capture/hooks/use-toggle-body-class-by-presence-spec.jsx, spec/javascripts/spec_helper.js, spec/javascripts/support/sinon.js
**Why**: As a user who relies on assistive technology, I expect that the document capture element is labelled in a way that I can understand its purpose.
**Changes:**
- ~Acuant capture canvas has accessible label describing purpose ([G68](https://www.w3.org/WAI/WCAG21/Techniques/general/G68))~
- This was removed in 1a85a24, to be addressed separately as part of LG-4539 (#5126)
- Full screen dialog prefers shifting focus to first interactive element in given children if present, rather than always the "Close" button
- Acuant capture canvas is focusable so that canvas becomes focused element upon opening dialog
- Avoid using `aria-modal` ([poor support](https://a11ysupport.io/tech/aria/aria-modal_attribute), [buggy](https://bugs.webkit.org/show_bug.cgi?id=174667))
- While dialog is present, …
=> LG-4536: Add accessible label for Acuant SDK camera canvas

app/services/reports/base_report.rb, app/services/reports/daily_auths_report.rb, config/initializers/job_configurations.rb, spec/services/reports/daily_auths_report_spec.rb
* Aggregates sp_return_logs for a single day
* Can be run with past days to backfill to S3
Next steps:
- Figure out how to build similar daily summary for proofing rates, GPO
After deploy:
- If it looks good, backfill for as long as we have sp_return_logs table in prod
=> Add daily auths report (LG-4648)

app/javascript/packages/document-capture/components/acuant-capture-canvas.jsx, config/js_locale_strings.yml, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, spec/javascripts/packages/document-capture/components/acuant-capture-canvas-spec.jsx
**Why:** As a user who leverages assistive technology, I expect that all non-text content is accompanied by a text alternative, including visual states of the Acuant SDK video capture, so that I can understand its purpose in the page.
Builds on #5126 and #5123.
=> LG-4536: Announce frame states for Acuant SDK to assistive technology

.circleci/config.yml, config/webpacker.yml
**Why**: In CI, [we already precompile assets before running tests](https://github.com/18F/identity-idp/blob/5d1b84cb0b6b7040a08d7e9efa45e24ea9e4a886/.circleci/config.yml#L125-L128), so as with disabling this `compile` setting in production, in theory we may see speedup by disabling on-demand compilation.
This may not be shippable as-is, since we may still want on-demand compilation for tests run in local development. Currently testing to see if there's enough noticeable difference to warrant further exploration.
=> Try disabling Webpacker compile for test environments

app/services/service_provider_seeder.rb, config/service_providers.localdev.yml, spec/services/service_provider_seeder_spec.rb
- find_or_create only calls its block for new records,
so updates to existing records need to go outside the block
Eagle eye @orenyk noticed some records weren't updating the way we expected 😬 🤦
=> Fix ServiceProviderSeeder data for certs

Gemfile, Gemfile.lock, app/controllers/concerns/saml_idp_auth_concern.rb, app/services/saml_request_validator.rb, lib/saml_idp_constants.rb, spec/services/saml_request_validator_spec.rb, spec/support/fake_saml_request.rb
Resolves LG-4725
* Add PasswordProtectedTransport (non-duo version) to SamlIdp variables
* Take requested_auth_context_comparison attribute from saml request and
pass it to the SamlRequestValidator service object during
authentication requests
* Allow SamlRequestValidator to pass requests sending the
PasswordProtectedTransport AuthnContext if the RequestAuthnContext
element includes the Comparison attribute set to either "minimum" or
"better" (section 3.3.2.2.1 of the SAML Core 2.0 spec)
Tested locally with [this SAML request](http://localhost:3000/api/saml/auth2021?SAMLRequest=lVJdj9owEPwrkd8TOx8NlRVyoqCqSFyLgFanvpyMvRyWYju1HUL%2FfU3I3b3Qu%2FbJ0np2dmZ2q7uzaqITWCeNnqI0IeiurmadP%2BoN%2FOrA%2BSgAtKNnJ6bo6H1LMe77PunzxNgnnBGS4of71ZYfQTH0Apbvg2OpnWeaA4qWiyl6PBQTMvmYsfiQ5SIuCl7GezbJ4n3JSJ6XkyJlJ …
=> [LG-4725] Add support for limited step-up AuthnContext behavior

app/controllers/concerns/saml_idp_auth_concern.rb, app/models/null_service_provider.rb, db/migrate/20210622182910_add_use_legacy_name_id_behavior_to_s_ps.rb, db/schema.rb, lib/saml_idp_constants.rb, spec/controllers/saml_idp_controller_spec.rb
Resolves LG-4734
* Add use_legacy_name_id_behavior attribute to service_providers to
preserve current behavior for impacted SPs
* Update the SamlIdpAuthConcern to only pass through supported NameID
formats and otherwise use the default (except for currently impacted
SPs)
=> [LG-4734] Fix handling of unsupported NameID formats

.rubocop.yml, app/helpers/aws_s3_helper.rb, spec/helpers/aws_s3_helper_spec.rb
**Why**: To avoid a situation where the S3 URL becomes expired after 15 minutes while the user's session is still active, set the URL to expire aligning to the maximum session duration.
Reference: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Presigner.html#presigned_url-instance_method
>**`:expires_in`** (`Integer`) — default: `900` — The number of seconds before the presigned URL expires. Defaults to 15 minutes. As signature version 4 has a maximum expiry time of one week for presigned URLs, attempts to set this value to greater than one week (604800) will raise an exception.
=> LG-4590: Set expiration for S3 presigned URL

Gemfile, Gemfile.lock, app/forms/idv/doc_pii_form.rb, app/models/profile.rb, app/presenters/openid_connect_user_info_presenter.rb, app/services/attribute_asserter.rb, app/services/date_parser.rb, app/services/expired_license_allower.rb, spec/services/date_parser_spec.rb
* Add DateParser class to parse legacy persisted data
(Branched off https://github.com/18F/identity-idp/pull/5157, I think I want that merged before this gets merged, but they can also go together I think)
=> Remove american_date gem (LG-4628)

app/javascript/packs/webauthn-authenticate.js, app/views/two_factor_authentication/webauthn_verification/show.html.erb, config/locales/forms/en.yml, config/locales/forms/es.yml, config/locales/forms/fr.yml, config/locales/two_factor_authentication/en.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml
**Why**: https://github.com/18F/identity-idp/issues/5132  In summary user has to trigger an action for navigator.credentials.get to work.
**How**: Add button to trigger action that used to happen onload
=> LG-4690 Fix FIDO/Webauthn Sign In on Safari

app/controllers/concerns/saml_idp_auth_concern.rb
it only implements `use_legacy_name_id_behavior`, not `use_legacy_name_id_behavior?`
=> fix NullServiceProvider method call

app/services/push_notification/http_push.rb, spec/services/push_notification/http_push_spec.rb
1. "detail" needs to be a JSON string, so put the JWT inside a JSON object
2. errors were getting silently swallowed, this turns them into warnings
similar to HTTP deliver errors
=> RISC EventBridge fixes

app/controllers/users/sessions_controller.rb, app/models/email_address.rb, app/presenters/openid_connect_user_info_presenter.rb, app/services/openid_connect_attribute_scoper.rb, spec/controllers/openid_connect/user_info_controller_spec.rb
in working on #5177, I noticed some potentially extraneous KMS and database calls. Turns out we always load IAL2 profiles and PIV/CAC information (for x509 attributes), even if none of them are requested!
SAML has some similar logic around this in the [attribute asserter](https://github.com/18F/identity-idp/blob/fa22268/app/services/attribute_asserter.rb), so mostly I copied that to avoid the unnecessary database and KMS requests.
=> do not always load x509 and IAL2 attributes in OIDC userinfo/token requests

app/javascript/packages/components/alert.jsx, app/javascript/packages/document-capture/components/acuant-capture.jsx, app/javascript/packages/document-capture/components/document-side-acuant-capture.jsx, app/javascript/packages/document-capture/components/documents-step.jsx, app/javascript/packages/document-capture/components/file-image.jsx, app/javascript/packages/document-capture/components/form-error-message.jsx, app/javascript/packages/document-capture/components/form-steps.jsx, app/javascript/packages/document-capture/components/full-screen.jsx, app/javascript/packages/document-capture/components/review-issues-step.jsx, app/javascript/packages/document-capture/higher-order/with-background-encrypted-upload.jsx, app/javascript/packages/document-capture/hooks/use-focus-trap.js, app/javascript/packages/document-capture/hooks/use-if-still-mounted.js, config/js_locale_strings.yml, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, spec/javascripts/packages/components/alert-spec.jsx, spec/javascripts/packages/document-capture/components/acuant-capture-spec.jsx, spec/javascripts/packages/document-capture/components/form-error-message-spec.jsx, spec/javascripts/packages/document-capture/components/form-steps-spec.jsx, spec/javascripts/packages/document-capture/components/full-screen-spec.jsx, spec/javascripts/packages/document-capture/higher-order/with-background-encrypted-upload-spec.jsx, spec/javascripts/packages/document-capture/hooks/use-focus-trap-spec.jsx
**Why**: As a user, I expect that if Acuant fails to start because they do not have permission to use the camera (denied either explicitly by the user, or at the system-level), the messaging clearly indicates if there's a permissions problem, so that I'm not left confused about the reason for the failure, and so that I don't waste my time repeatedly trying to "Try again" if there's a systems permissions issue.
This adds support for steps to declare their own errors. Part of the requirement from the ticket is to transition focus to the error when rendered. This proved rather difficult due to how Acuant is shown in a full-screen modal, and how the [`focus-trap` library](https://www.npmjs.com/package/focus-trap) tries to both keep focus within the …
=> LG-4671: Messaging for when camera access is declined

app/controllers/idv/confirmations_controller.rb, app/controllers/idv/review_controller.rb, spec/controllers/idv/confirmations_controller_spec.rb, spec/controllers/idv/review_controller_spec.rb
Slack thread: https://gsa-tts.slack.com/archives/CEUQ9FXNJ/p1625064906009000
During identity proofing, if you choose to receive a GPO letter for address verification, you will see a `Your letter is on its way` before the letter is actually queued, leading to confusing and drop-off. This PR is a smaller fix that moves the message until after the password has been entered and the letter has been queued.
------|-----
|![image](https://user-images.githubusercontent.com/1430443/123988577-bed24700-d98d-11eb-9004-84d90699783d.png)|![image](https://user-images.githubusercontent.com/1430443/123988577-bed24700-d98d-11eb-9004-84d90699783d.png)|
|![image](https://user-images.githubusercontent.com/1430443/123988768-e6291400-d98d-11eb-82d3-55dce6c91ad8.png)|![image](https://user-image …
=> Do not show "Your letter is on its way" during GPO verification before the letter has been queued

app/javascript/packages/document-capture/components/file-input.jsx, app/javascript/packages/document-capture/context/acuant.jsx, app/javascript/packages/document-capture/context/analytics.jsx, app/javascript/packages/document-capture/context/asset.js, app/javascript/packages/document-capture/context/device.js, app/javascript/packages/document-capture/context/file-base64-cache.js, app/javascript/packages/document-capture/context/i18n.js, app/javascript/packages/document-capture/context/index.js, app/javascript/packages/document-capture/context/service-provider.jsx, app/javascript/packages/document-capture/context/upload.jsx, app/javascript/packages/document-capture/higher-order/with-background-encrypted-upload.jsx, app/javascript/packages/document-capture/index.js, spec/javascripts/packages/document-capture/context/index-spec.js, spec/javascripts/packages/document-capture/higher-order/with-background-encrypted-upload-spec.jsx
**Why**: So that developers can better visualize the component hierarchy using [React dev tools](https://github.com/facebook/react/tree/main/packages/react-devtools).
Related:
- https://reactjs.org/docs/context.html#contextdisplayname
- https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging
Before|After
---|---
=> Improve React component display names

app/services/service_provider_request_proxy.rb
Minor optimization to avoid hitting Redis unnecessarily. When checking for an SP request, the uuid defaults to `""`, not `nil`, which leads to a lot of Redis queries like this:
```
1625233088.659499 [0 127.0.0.1:65419] "get" "spr:"
```
This PR changes the logic to also skip if the query if the uuid is an empty string.
=> Do not check Redis for SP request if string is blank

app/jobs/resolution_proofing_job.rb, app/services/proofing/lexis_nexis/proofer.rb, app/services/proofing/mock/resolution_mock_client.rb, app/services/proofing/result.rb, spec/jobs/resolution_proofing_job_spec.rb, spec/services/proofing/result_spec.rb, spec/support/shared_examples/lexis_nexis.rb
**Why**: So that it is included in logging and we can associate requests with responses.
=> LG-4143: Include reference in InstantVerify result

lib/utf8_sanitizer.rb, spec/lib/utf8_sanitizer_spec.rb
As part of https://github.com/18F/identity-idp/pull/5187, that removes a common method that checks for null bytes in Service Provider issuer field
So we have a few approaches:
1. keep `ServiceProvider.from_issuer` so we can check null bytes there, and hope nobody tries to send null bytes to our DB any other spot
2. block all null bytes in params
3. monkeypatch ActiveRecord to elide null bytes when writing to the DB
This goes for approach (2)
Draws inspo from: http://joshfrankel.me/blog/recursively-validate-application-requests-with-rack/
=> Block null bytes at the middleware layer

app/forms/idv/api_image_upload_form.rb, app/services/idv/steps/verify_base_step.rb, app/services/idv/steps/verify_wait_step_show.rb, app/services/proofing/aamva/request/verification_request.rb, spec/features/idv/doc_auth/verify_step_spec.rb
This PR includes the state with the logged aamva data. There aren't existing unit tests for the verify_wait_step_show so testing this is much more work than doing the work. Future work to write unit specs should be considered.
=> LG-4263: log state with aamva results

spec/features/monitor/sp_signin_spec.rb
**Scenario**: the smoke test accounts are running against the the 1-year consent page
- We have code to handle this scenario, but only with a straight quote
- As of #4954 we started using curly quotes in copy, so this messes up the code
**Solution**: remove "it's" from the copy we check for
=> Fix smoke tests to not worry about curly/straight quotes

config/initializers/app_artifacts.rb
Since we're (finally!) retiring the 2019 and 2020 SAML certs, these files [were removed from the `build-keys` file in `identity-devops`](https://github.com/18F/identity-devops/pull/3611/files), so they're no longer copied from `dev` when running `create-sandbox`. As a result, however, the IdP deploy/activate fails on new hosts -- in a new sandbox -- trying to obtain those artifacts.
This PR takes care of things on the application side, removing them from the list of artifacts to obtain during initialization.
Addresses https://github.com/18F/identity-devops/issues/3165
=> remove checks for SAML 2019/2020 artifacts

app/services/db/sp_cost/add_sp_cost.rb
The first `ServiceProvider.find_by(issuer: issuer)` short circuits if the issuer is blank, and we can do it for the same query later in the method.
Somewhat related question, do we need to log SP costs when no SP is present?
=> skip sp query if issuer is blank

config/initializers/app_artifacts.rb
**Why**: So that people know they need to update the config when adding/removing SAML keys and certs
=> Add a comment to warn about the `saml_endpoint_configs` config

Gemfile, Gemfile.lock, app/forms/idv/api_image_upload_form.rb, app/jobs/document_proofing_job.rb, app/services/analytics.rb, app/services/doc_auth_router.rb, app/services/idv/steps/document_capture_step.rb, spec/features/idv/doc_capture/document_capture_step_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb, spec/jobs/document_proofing_job_spec.rb
- Before, these would be reported as exceptions to
NewRelic, which could be noisy, since they are not
necessarily critical.
- This, along with 18f/identity-doc-auth#25, updates
to add a new warning_notifier config option we can pass
around.
=> Send doc auth warnings to events.log (LG-4799)

app/helpers/application_helper.rb, app/services/idv/steps/doc_auth_base_step.rb, app/views/idv/session_errors/throttled.html.erb, spec/helpers/application_helper_spec.rb, spec/views/idv/session_errors/throttled.html.erb_spec.rb
**Why**: In environments where liveness is enabled, change default to require liveness only if explicitly requested by the SP. Absent an associated SP for the current session (e.g. password reset reverification), require selfie only if it had been checked previously.
General notes:
- The duplication between ApplicationHelper and DocAuthBaseStep isn't great. I'd initially wanted to remove this method from ApplicationHelper altogether, as it doesn't seem like something we should need to have globally available. However, we reference it in quite a few places, so it's non-trivial to move elsewhere. And it's not entirely clear where a best place for it would be. It might be nice if we could initialize this computed value at the start of the proofing flow and reference it from there (e.g. …
=> LG-4443: Set default liveness requirement by previous profile

Gemfile, Gemfile.lock, app/forms/idv/api_image_upload_form.rb, app/jobs/document_proofing_job.rb, app/services/idv/actions/verify_document_action.rb, app/services/idv/agent.rb, app/services/idv/steps/document_capture_step.rb, spec/features/idv/doc_auth/document_capture_step_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb, spec/jobs/document_proofing_job_spec.rb
Depends on: https://github.com/18F/identity-doc-auth/pull/26
**Why**: The "automatic" cropping mode currently used is not recommended and may return more "Unknown" results. Instead, set cropping mode to one or the other of "None" or "Always" based on whether the image was captured using Acuant SDK (where cropping is assumed).
=> LG-4796: Set Acuant cropping mode by image source

Gemfile, Gemfile.lock, app/controllers/concerns/saml_idp_auth_concern.rb
See https://github.com/18F/saml_idp/pull/46
=> Update saml_idp with better logic for matching_cert

app/controllers/concerns/saml_idp_auth_concern.rb, spec/controllers/saml_idp_controller_spec.rb
Previously: #5220
[NewRelic link](https://one.newrelic.com/launcher/nr1-core.explorer?platform%5BaccountId%5D=1376370&platform%5BtimeRange%5D%5Bduration%5D=1800000&platformVersion=release-2886&env=production&pane=eyJiYXJjaGFydCI6ImJhcmNoYXJ0IiwidG9wRmFjZXQiOiJ0cmFuc2FjdGlvblVpTmFtZSIsInBhZ2UiOiJ0YWJsZSIsIm5lcmRsZXRJZCI6ImVycm9ycy11aS5vdmVydmlldyIsImVudGl0eUd1aWQiOiJNVE0zTmpNM01IeEJVRTE4UVZCUVRFbERRVlJKVDA1OE1UQTBOREV3TURZMSJ9&sidebars%5B0%5D=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5R3VpZCI6Ik1UTTNOak0zTUh4QlVFMThRVkJRVEVsRFFWUkpUMDU4TVRBME5ERXdNRFkxIiwic2VsZWN0ZWROZXJkbGV0Ijp7Im5lcmRsZXRJZCI6ImVycm9ycy11aS5vdmVydmlldyJ9fQ)
=> Bring back a default cert, to fix NoMethodErrors on nil

.erdconfig
**Why**: We removed the ERD in https://github.com/18F/identity-idp/pull/4960
=> Remove .erdconfig

Gemfile, Gemfile.lock, app/forms/idv/api_image_upload_form.rb, app/jobs/document_proofing_job.rb, app/services/idv/steps/document_capture_step.rb, spec/features/idv/doc_auth/document_capture_step_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb, spec/jobs/document_proofing_job_spec.rb
Related: https://github.com/18F/identity-idp/pull/5219, https://github.com/18F/identity-doc-auth/pull/27
**Why**: We currently hard-code this value as "Mobile" sensor, which could be causing higher failure rates for images not captured using the Acuant SDK. Instead, set "Mobile" only if the image source is Acuant SDK, otherwise "Unknown".
=> LG-4837: Set Acuant sensor type parameter by image source

app/jobs/address_proofing_job.rb, app/jobs/resolution_proofing_job.rb, config/application.yml.default
We've had a couple issues with LN this week with periods of extremely slow responses that led to users experiencing the request timeout page.
We could extend the timeout for these paths like we do for doc auth, but the 99.9% response time for LN is under 10 seconds. I think it's preferable to tailor our request timeout to that, and show users the message that we're having internal issues rather than the 503 page.
It probably makes sense to re-evaluate bringing the retry back once async is live.
Relevant slack thread: https://gsa-tts.slack.com/archives/C0NGESUN5/p1626982530079500
=> reduce lexis nexis timeout and do not retry

app/javascript/packs/form-steps-wait.jsx, spec/javascripts/packs/form-steps-wait-spec.js
**Why**
Currently users are seeing a weird functionality where the button spinner still spins when the phone number validation fails for the input, this will make it so on form errors it will not keep spinning the buttons. 
**How**
Form will now check to see when its invalid and when it is via an input it will stop the spinner from spinning .
=> LG-4812: dont maintain button spinner when validation error

Gemfile, Gemfile-dev.example, Gemfile.lock
In #5236, I forgot to actually remove identity-doc-auth gem from the Gemfile.
=> LG-4537: actually stop including the doc auth gem

config/country_dialing_codes.yml, config/pinpoint_overrides.yml, config/pinpoint_supported_countries.yml
**Why**: We are observing a large amount of SMS spam going to Iraq
=> Disable SMS for Iraq

app/services/phone_number_capabilities.rb, config/country_dialing_codes.yml, config/pinpoint_overrides.yml, spec/services/phone_number_capabilities_spec.rb
Follow up to #5250 to allow SMS for Iraq only for already confirmed numbers
=> allow sending SMS only to confirmed numbers

app/javascript/packages/document-capture/context/acuant.jsx, spec/javascripts/packages/document-capture/context/acuant-spec.jsx
**Why**: To be able to have insight into how many users should encounter the Acuant camera capture vs. Acuant's own internal fallback image upload.
Review changes ignoring whitespace: https://github.com/18F/identity-idp/pull/5247/files?w=1
=> LG-4706: Log Acuant SDK camera support with loaded event

app/services/idv/steps/document_capture_step.rb, spec/features/idv/doc_auth/document_capture_step_spec.rb
**Why**: The result may be loaded via `load_result` or `load_doc_auth_async_result` depending on whether async doc capture is enabled.
Without these changes, the user can still proceed to the next step because VerifyDocumentStatusAction#async_state_done will mark the step as complete, but the field validation result from DocumentCaptureStep#form_submit will cause a validation message "This field is required" to be shown on the next screen. The validation is remarking on the absence of front_image and back_image form fields.
Before|After
---|---
Precedent: https://github.com/18F/identity-idp/blob/1b75022/app/controllers/idv/capture_doc_status_controller.rb#L40-L44
=> LG-4502: Consider async result for stored doc capture result

app/controllers/pages_controller.rb, spec/controllers/pages_controller_spec.rb
It looks like we were attempting to skip the session load, but it does not appear to have been working. Sort of a followup to #5177
=> skip session load on 404

app/controllers/sign_up/completions_controller.rb, app/controllers/users/authorization_confirmation_controller.rb, app/controllers/users/sessions_controller.rb
**Why**: The lack of the form action CSP directive on the response to POST / appears to be causing an issue with chrome on Android
=> Apply insecure header overrides to POST and GET requests involved in redirects to SPs

app/services/doc_auth/lexis_nexis/config.rb, app/services/doc_auth/lexis_nexis/request.rb, app/services/doc_auth/lexis_nexis/requests/true_id_request.rb, app/services/doc_auth_router.rb, config/application.yml.default, lib/identity_config.rb
Why: the current `lexisnexis_timeout` used for phone finder and instant verify is set to 10 seconds. The call to true_id requires a greater timeout, so this PR will add another config entry for `lexisnexis_trueid_timeout`
=> LG-4149: allow a separate config for trueid timeout

app/helpers/accordion_helper.rb, app/javascript/app/components/index.js, app/views/shared/_accordion.html.erb, app/views/shared/_email_languages.html.erb, package.json, yarn.lock
~Blocked by: https://github.com/18F/identity-style-guide/pull/235~
Prepared in anticipation of upcoming `identity-style-guide@6.0.0`, via [`yarn link`](https://classic.yarnpkg.com/en/docs/cli/link/).
Notable changes:
- Accordion no longer has "Close" button
- Updated usage and appearance of bordered checkbox and radio buttons
=> Update identity-style-guide to 6.0.0

app/decorators/service_provider_session_decorator.rb, app/services/doc_auth/acuant/request.rb, spec/decorators/service_provider_session_decorator_spec.rb, spec/services/doc_auth/acuant/request_spec.rb
New Relic calls `.has_key?` on the options passed in, which makes the nil default raise an error ([New Relic error](https://one.newrelic.com/launcher/nr1-core.explorer?platform[accountId]=1376370&platform[timeRange][duration]=86400000&platformVersion=release-2986&env=production&pane=eyJiYXJjaGFydCI6ImJhcmNoYXJ0IiwidG9wRmFjZXQiOiJ0cmFuc2FjdGlvblVpTmFtZSIsInBhZ2UiOiJ0YWJsZSIsInByaW1hcnlGYWNldCI6ImVycm9yLmNsYXNzIiwiZmlsdGVycyI6W3sia2V5IjoiZXJyb3IuZXhwZWN0ZWQiLCJ2YWx1ZSI6Im5vdCB0cnVlIn0seyJrZXkiOiJlcnJvci5jbGFzcyIsInZhbHVlIjoiTm9NZXRob2RFcnJvciIsImxpa2UiOmZhbHNlfV0sIm5lcmRsZXRJZCI6ImVycm9ycy11aS5vdmVydmlldyIsImVudGl0eUd1aWQiOiJNVE0zTmpNM01IeEJVRTE4UVZCUVRFbERRVlJKVDA1OE5USXhNelk0TlRnIn0&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5R3VpZCI6Ik1UTTNOak0zTUh4QlVFMThRVkJRVEVsRFFW …
=> fix 500 from nil options

app/controllers/sign_up/completions_controller.rb, app/javascript/packages/masked-text-toggle/index.js, app/javascript/packages/masked-text-toggle/package.json, app/javascript/packs/masked-text-toggle.js, app/services/ssn_formatter.rb, app/views/idv/doc_auth/verify.html.erb, app/views/shared/_masked_text.html.erb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml, spec/controllers/sign_up/completions_controller_spec.rb, spec/features/idv/doc_auth/verify_step_spec.rb, spec/features/users/sign_in_spec.rb, spec/javascripts/packages/masked-text-toggle/index-spec.js, spec/services/ssn_formatter_spec.rb, spec/views/shared/_masked_text.html.erb_spec.rb, tsconfig.json
~Blocked by: #5257~
**Why**:
As a user, I want to know how my Social Security number will be protected during proofing so that I feel comfortable providing it to verify my identity on login.gov's IAL2 flow.
As a user, I want my Social Security number to be masked by default throughout the process, so that my information is protected if I am using a public computer.
Verify|Confirmation
---|---
Small screen text wrapping on verify screen:
=> LG-4502: Update IAL2 SSN masking and content

app/controllers/test/saml_test_controller.rb, config/service_providers.localdev.yml, spec/controllers/saml_idp_controller_spec.rb, spec/controllers/saml_signed_message_spec.rb, spec/features/idv/liveness/upgrade_to_strong_ial2_spec.rb, spec/features/idv/steps/review_step_spec.rb, spec/features/reports/authorization_count_spec.rb, spec/features/saml/aal3_required_spec.rb, spec/features/saml/authorization_confirmation_spec.rb, spec/features/saml/ial1/account_creation_spec.rb, spec/features/saml/ial1_sso_spec.rb, spec/features/saml/ial2_sso_spec.rb, spec/features/saml/saml_logout_spec.rb, spec/features/saml/saml_relay_state_spec.rb, spec/features/saml/saml_spec.rb, spec/features/users/sign_in_spec.rb, spec/services/attribute_asserter_spec.rb, spec/support/features/idv_helper.rb, spec/support/saml_auth_helper.rb, spec/support/saml_response_doc.rb, spec/support/shared_examples/sign_in.rb
Working on making the saml spec helpers configurable, so that we can have the configuration live with the spec, not be obfuscated in a web of largely pointless helper methods. This does make the specs more verbose, but also easier to understand what the intent is.
This PR eliminates the vast majority of the saml helper methods as they made it very difficult to determine what was actually being tested against, and in many cases were being used incorrectly anyway, e.g., calling a helper to get saml settings that are different from the default by only the issuer, only to then set the issuer to something else. There is a lot to review, but if it is easier, the entire PR is a series of commits with each commit completing a specific refactoring, e.g., removing one custom settings method at a …
=> LG-4644: refactoring saml specs

app/jobs/address_proofing_job.rb, app/jobs/document_proofing_job.rb, app/jobs/resolution_proofing_job.rb, config/initializers/good_job.rb
- StaleJobError added in #5244
I got paged in `dev` because of a lot of stale job errors, I think there was one old job that was being constantly retried. I went through proofing manually and it was fine
=> Make sure we don't retry stale jobs

Gemfile, Gemfile.lock, config/country_dialing_codes.yml, config/initializers/telephony.rb, config/pinpoint_overrides.yml, config/pinpoint_supported_countries.yml, lib/identity_config.rb, lib/pinpoint_supported_countries.rb, spec/features/users/sign_in_spec.rb, spec/lib/pinpoint_supported_countries_spec.rb
Builds on: https://github.com/18F/identity-telephony/pull/50
- I found out that AWS changed the format of "sender ID supported" SMS supported countries table, so I updated the script to handle and our test fixtures
- For now it seems like we just have one sender ID rather than a per-country one
Going to deploy to my personal env to make sure adding a sender ID doesn't break anything
=> Update parsing of Pinpoint supported countries, send sender ID

app/jobs/application_job.rb, app/jobs/gpo_daily_job.rb, app/jobs/reports/base_report.rb, app/services/account_reset/grant_requests_and_send_emails.rb, app/services/agreements/reports/partner_api_report.rb
Spotted this line in the workers.log on a worker instance in my personal env:
```
Retrying AccountReset::GrantRequestsAndSendEmails in 19 seconds, due to a GoodJob::ActiveJobExtensions::Concurrency::ConcurrencyExceededError.
```
which makes it sound like these jobs are not being immediately discarded the way I was thinking
=> Discard jobs due to concurrency errors

config/pinpoint_overrides.yml
I noticed in #5291 that we had some redundant overrides for pinpoint, ex some configs that were the same as what we parsed from the support docs
1. I believe the overrides may have come from poor parsing (since the docs changed how the document sender ID requirements)
2. Now that we have updated the parsing we can remove these
This is what I ran to help enumerate the dupes, maybe worth turning into a script and linting on it the same way we do with the country support?
```ruby
require 'yaml'
original = YAML.load_file('config/pinpoint_supported_countries.yml')
overrides = YAML.load_file('config/pinpoint_overrides.yml')
redundant = []
overrides.each { |country, vals| (original[country] || {}).each { |k, v| redundant << [country, k, v] if vals[k] == v } }
redundant
[["AE", "supports_sms", …
```
=> Remove redundant entries in pinpoint_overrides.yml

app/views/accounts/_personal_key_item_heading.html.erb, app/views/idv/come_back_later/show.html.erb, app/views/shared/_nav_branded.html.erb, app/views/shared/_personal_key.html.erb
***Why***
Currently the Login.gov logo has no alt text when associated with a Service Provider. This solves that issue.
=> LG-4927: include login.gov logo alt text

app/decorators/user_decorator.rb, app/helpers/session_timeout_warning_helper.rb, app/presenters/account_reset/pending_presenter.rb, app/presenters/confirmation_email_presenter.rb, config/locales/dotiw/en.yml, config/locales/dotiw/es.yml, config/locales/dotiw/fr.yml
Extracted from #5301 ([context](https://github.com/18F/identity-idp/pull/5301#discussion_r690665001))
**Why**: Makes distance_of_time_in_words less error-prone and verbose, and aligns to [library documented defaults](https://github.com/radar/distance_of_time_in_words#two_words_connector). It had previously been implemented this way largely due to [limitations of YAML normalization](https://github.com/18F/identity-idp/pull/3780#discussion_r431246132) resolved by #5066.
=> Set two_words_connector at locale string data

app/assets/stylesheets/components/_i18n-dropdown.scss, app/javascript/app/i18n-dropdown.js, app/views/shared/_footer_lite.html.erb, spec/features/visitors/i18n_spec.rb
This PR changes language links to a button.
Why: The language link was following an accessibility anti-pattern as it did not re-direct a user to another page.
=> LG-4925: Change language link to a button

app/jobs/reports/daily_auths_report.rb, spec/jobs/reports/daily_auths_report_spec.rb
I originally included this in https://github.com/18F/identity-idp/pull/5313, but that will wait on our bucket to be set up, so I think this can go in sooner
=> Add in agency name, app friendly name to daily auths report

app/assets/stylesheets/components/_form.scss, app/javascript/app/pw-toggle.js, app/javascript/app/ssn-field.js, app/views/devise/passwords/new.html.erb, app/views/idv/doc_auth/agreement.html.erb, app/views/shared/_banner.html.erb, app/views/users/edit_phone/_make_default_number.html.erb, app/views/users/shared/_otp_make_default_number.html.erb
This ticket addresses parsing issues that were found during the audit of the IAL2 flow.
Why: Parsing is all about writing a clean code “HTML, CSS OR JavaScript” in a manner that is understood by browsers & assistive technologies. If the code is not written according to standards it can break the user experience of the application & assistive technology users will have a lot of problems to deal with. ([Source](https://www.digitala11y.com/understanding-sc-4-1-1-parsing/))
Note: the only warning that is not addressed is `Attribute aria-required is unnecessary for elements that have attribute required.`. My theory on is that if an input field is marked as required, the `aria-required` attribute is also created. If anyone has any thoughts on this theory, I am open to hearing any discussion …
=> LG-4940: Address parsing issues

app/services/account_reset/grant_requests_and_send_emails.rb, config/initializers/job_configurations.rb, spec/services/account_reset/grant_requests_and_send_emails_spec.rb
- Job runs every 5 minutes, but was locking for an entire day
See [Slack thread](https://gsa-tts.slack.com/archives/C42TZ3K5H/p1629819255012500?thread_ts=1629817645.008900&cid=C42TZ3K5H)
=> Fix AccountReset::GrantRequestsAndSendEmails job locking

app/services/account_reset/grant_requests_and_send_emails.rb, spec/services/account_reset/grant_requests_and_send_emails_spec.rb
While fixing #5324, I noticed a few things that could be cleaned up
- Send an analytics event, using an anonymous user
- Inject `now`, switch tests to set up events beforehand instead of after
=> Clean up GrantRequestsAndSendEmails

config/application.yml.default
This reverts commit 26cc476f6fc6a91cccbf09f3443c0a786f6a814d,
which in turn reverts b07ef999eb572e887020586cb22ff3f7d3547833
I think this is causing errors in DM because we're parsing the string incorrectly
See: https://github.com/bensheldon/good_job#optimize-queues-threads-and-processes
=> Fix queue syntax for good_job

app/jobs/backup_code_backfiller_job.rb
- This queue name will not be alerted on for long delays
See https://github.com/18F/identity-devops/pull/3687/commits/75c66787ffecb57e4add62037a2fddf92b11487d
=> Switch BackupCodeBackfiller job to long_running queue

app/javascript/app/i18n-dropdown.js, app/views/shared/_footer_lite.html.erb
This ticket adds the language attribute to language link text that is in different language.
**Why**
To follow accessibility best practices: Any text that is in a different language should be annotated with the `lang` attribute
=> Add language attribute to language dropdown links

app/controllers/application_controller.rb, app/services/analytics.rb, lib/identity_config.rb, spec/controllers/application_controller_spec.rb, spec/features/account_reset/cancel_request_spec.rb, spec/features/account_reset/delete_account_spec.rb, spec/services/analytics_spec.rb
This is a precursor to a better way of observing deploys go out.
I realize it's kind of uncouth to run `git` during the load of the application, but it will ideally be replaced by something like system environment variables in the future.
=> Include git tag and sha in logs and events

app/controllers/two_factor_authentication/options_controller.rb, app/presenters/two_factor_login_options_presenter.rb, app/services/user_session_context.rb, app/views/two_factor_authentication/options/index.html.erb, spec/features/two_factor_authentication/change_factor_spec.rb, spec/features/users/sign_in_spec.rb, spec/presenters/two_factor_login_options_presenter_spec.rb, spec/services/user_session_context_spec.rb, spec/support/features/session_helper.rb, spec/views/two_factor_authentication/options/index.html.erb_spec.rb
**Why**: So that a user isn't unexpectedly signed out simply because they choose to cancel the reauthentication process.
The MFA options page is hard-coded to direct the user to sign out when they click the "Cancel" link. This makes sense when choosing MFA during sign-in, but not when reauthenticating such as when modifying account settings (edit password, etc).
Steps to reproduce:
1. Sign in
2. Wait 2 minutes
3. Click "Edit password" on account dashboard
4. Enter password when prompted
5. When prompted for MFA, click "choose another option" link
6. Click "Cancel"
Before: Signed out
After: Redirected to account page
=> LG-4259: Return user to account page when canceling reauthn MFA selection

app/jobs/document_proofing_job.rb, app/services/doc_auth/acuant/acuant_client.rb, app/services/doc_auth/lexis_nexis/lexis_nexis_client.rb, app/services/doc_auth/lexis_nexis/request.rb, app/services/doc_auth/lexis_nexis/requests/true_id_request.rb, app/services/doc_auth/mock/doc_auth_mock_client.rb, app/services/idv/actions/verify_document_action.rb, app/services/idv/agent.rb, app/services/idv/steps/doc_auth_base_step.rb, spec/services/doc_auth/lexis_nexis/requests/true_id_request_spec.rb
When we send data to LexisNexis, we provide a reference id. For phone finder and instant verify, we prefixed the id (the user's uuid) with the SP app id, so that we could differentiate requests by SP. This PR adds the same functionality to trueid requests.
To do this, we had to capture both the uuid and uuid_prefix, and pass them through a string of classes to get them into the request. To best follow the logic, review the diffs in the following order:
| file | change |
|-|-|
| app/services/idv/steps/doc_auth_base_step.rb | adds uuid_prefix to flow_session[:pii_from_doc] |
| app/services/idv/actions/verify_document_action.rb | combines the pii and doc attributes in the applicant |
| app/services/idv/agent.rb | encrypts the applicant data |
| app/jobs/document_proofing_job.rb | decrypts …
=> LG-4959: add uuid_prefix to reference sent to LexisNexis

app/forms/register_user_email_form.rb, config/locales/sign_up/en.yml, config/locales/sign_up/es.yml, config/locales/sign_up/fr.yml, spec/forms/register_user_email_form_spec.rb
Follow up to https://github.com/18F/identity-idp/pull/3079 / [LG-1535](https://cm-jira.usa.gov/browse/LG-1535) to allow the form to accept a bad `request_id`, but not include the `request_id` in the email that gets sent since that appears to be the core concern.
We received reports of users receiving the "The email form is invalid" error and not understanding why, and I suspect it's due to the `request_id` expiring out of the cache. Further investigation suggests that this error is not uncommon ([slack thread with numbers](https://gsa-tts.slack.com/archives/C0NGESUN5/p1630088027067100?thread_ts=1630062000.047200&cid=C0NGESUN5))
=> Allow expired or fake request_id on email registration

Gemfile, Gemfile.lock, config/initializers/redis.rb, spec/jobs/risc_delivery_job_spec.rb
**Why**: To migrate off of the Readthis gem without
colliding with the same keys
=> Add redis-namespace (LG-5030)

app/controllers/idv/session_errors_controller.rb, app/services/idv/steps/verify_step.rb, config/routes.rb, spec/controllers/idv/session_errors_controller_spec.rb, spec/services/idv/steps/verify_step_spec.rb
**Why**: So that each throttle error screen corresponds to exactly one throttle type, to accommodate accurate time labels proposed in #5301 (LG-4637).
=> LG-5025: Create separate throttle error screen for proof_ssn throttle type

app/services/doc_auth/error_generator.rb, app/services/doc_auth/lexis_nexis/responses/true_id_response.rb, spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb
Change how we handle TrueID failures where no details are provided. These we now understand encompass Acuant HTTP responses like 438/439/440 so returning a technical difficulties message is not correct.
=> LG-5042 Fix TrueID error message for responses without failure details.

config/initializers/good_job.rb
**Why**: Avoid errors in local development with ruby_workers_enabled: false since we start good_job process, even if the application won't be configured to use it.
Context: https://gsa-tts.slack.com/archives/C0NGESUN5/p1630086894061900
=> Always set GoodJob initializer config, even when workers disabled

app/models/throttle.rb, app/services/idv/steps/doc_auth_base_step.rb, spec/models/throttle_spec.rb
- Also add type checking to prevent this error in the future
Spotted by @aduth in https://github.com/18F/identity-idp/pull/5302#discussion_r698692260
=> Fix DocAuthBaseStep throttle target

.eslintrc
**Why**: It was previously added in #1363 to resolve a compatibility issue with CodeClimate, but we no longer use CodeClimate to run ESLint as of #3923. Continuing to include it risks falling out of sync and could be a source of confusion for developers.
The [setting itself](https://github.com/import-js/eslint-plugin-import#importcore-modules) is meant to allow raw imports of specific package names, but the way these files are referenced is by file path:
https://github.com/18F/identity-idp/blob/f0e850d639eee236f749ed006ef9f585b85c70eb/app/javascript/packs/application.js#L1-L10
=> Remove unnecessary ESLint core-modules setting

app/jobs/application_job.rb, app/jobs/remove_old_throttles_job.rb, app/services/account_reset/grant_requests_and_send_emails.rb, app/services/time_service.rb, config/initializers/job_configurations.rb, db/primary_migrate/20210830171646_add_timestamps_to_throttles.rb, db/primary_migrate/20210830171713_add_index_on_updated_at_to_throttles.rb, db/schema.rb, spec/factories/throttles.rb, spec/jobs/remove_old_throttles_job_spec.rb, spec/services/time_service_spec.rb
This adds a job that will delete old Throttle rows, based on `updated_at`
Unfortunately, most rows will not have `updated_at` because that was just added in https://github.com/18F/identity-idp/pull/5352, so this job will no-op for about 30 days until it has rows old enough to delete
=> Remove old throttle rows

app/controllers/idv/phone_errors_controller.rb, app/controllers/idv/session_errors_controller.rb, app/controllers/users/verify_account_controller.rb, app/controllers/users/verify_personal_key_controller.rb, app/models/throttle.rb, app/services/idv/steps/send_link_step.rb, app/views/idv/phone_errors/failure.html.erb, app/views/idv/session_errors/failure.html.erb, app/views/idv/session_errors/throttled.html.erb, app/views/users/verify_account/throttled.html.erb, app/views/users/verify_personal_key/throttled.html.erb, config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml, spec/controllers/idv/phone_errors_controller_spec.rb, spec/controllers/idv/session_errors_controller_spec.rb, spec/controllers/users/verify_personal_key_controller_spec.rb, spec/features/idv/doc_auth/document_capture_step_spec.rb, spec/features/idv/doc_auth/send_link_step_spec.rb, spec/models/throttle_spec.rb, spec/support/idv_examples/max_attempts.rb, spec/views/idv/phone_errors/failure.html.erb_spec.rb, spec/views/idv/session_errors/failure.html.erb_spec.rb
**Why**: As a user, I expect that if I encounter an error screen informing me that I am unable to proceed due to too many attempts, the text on the page will let me know when I can try again, so that I know when to return to try again, and so that I'm not waiting longer than necessary if I can try again sooner than the text would otherwise imply.
---|---|---
Session Error|![Screen Shot 2021-08-17 at 3 17 37 PM](https://user-images.githubusercontent.com/1779930/129787520-3a570a20-6995-4bfe-95ac-52f5b8fa1f44.png)|![Screen Shot 2021-08-17 at 3 17 25 PM](https://user-images.githubusercontent.com/1779930/129787519-60a62b57-6d29-40e3-ac97-3d22121bf61d.png)
SSN Error|![Screen Shot 2021-08-17 at 3 17 37 …
=> LG-4637: Show accurate time remaining for IAL2 throttle screens

lib/pinpoint_supported_countries.rb, spec/lib/pinpoint_supported_countries_spec.rb
**Why**: So that inconsistencies between voice and SMS markup are tolerated and correctly combined / mapped.
=> Normalize newlines in Pinpoint supported countries script

app/services/analytics.rb
so we can tie errors to boxes during a canary deploy
=> Add git SHA to NewRelic traces

app/services/doc_auth/acuant/responses/get_results_response.rb, spec/fixtures/acuant_responses/get_results_response_failure.json, spec/fixtures/acuant_responses/get_results_response_success.json, spec/jobs/document_proofing_job_spec.rb, spec/services/doc_auth/acuant/responses/get_results_response_spec.rb
Small addition to the Acuant logging payload. TamperResult was added by Acuant awhile back, but we never added it to logging.
=> Add TamperResult to Acuant logging.

app/services/doc_auth/lexis_nexis/responses/true_id_response.rb, spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_success_2.json, spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb
DOBs with single digit month or day were being formatted without padding to two digits. For IAL2 identity verification involving AAMVA, this malformed date fails to pass.
This PR creates a new Date object with the year, month and day and converts to an iso8061 String.
=> LG-5081: trueid response date parsing

app/controllers/idv/cancellations_controller.rb, app/services/idv/flows/doc_auth_flow.rb, app/services/idv/session.rb
Builds on #5339 to remove session values unused after changes proposed in that branch, left temporarily to avoid deploy issues with live sessions.
Should only be merged after deploy including #5339.
Additional context: https://github.com/18F/identity-idp/pull/5339#discussion_r696963980
=> Remove session phone attempt count initialization

spec/features/monitor/create_account_spec.rb, spec/features/monitor/sp_signin_spec.rb, spec/support/monitor/monitor_sp_steps.rb
**Why**: We have our own sample apps deploy now,
so we can reduce external dependencies
--
I already updated CircleCI to use our apps for smoke tests in staging and prod, luckily the code we already had works for them, this is just cleaning up old, now-unused, code
=> Remove code for usajobs.gov in smoke tests (LG-4816)

spec/services/redis_rate_limiter_spec.rb
Example warning:
> Passing 'flushdb' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at identity-idp/spec/services/redis_rate_limiter_spec.rb:7:in `block (3 levels) in <top (required)>')
=> Fix call to flushdb on namespaced redis, fix deprecation warning

app/controllers/idv/image_uploads_controller.rb, app/forms/idv/api_image_upload_form.rb
Found another code pathway that needs to pass the uuid_prefix through to the TrueID request. This is simply a patch to #5323
=> LG-4959: alternate pathway to get uuid_prefix in

app/forms/idv/api_image_upload_form.rb, app/jobs/document_proofing_job.rb, app/services/doc_auth/acuant/pii_from_doc.rb, app/services/doc_auth/lexis_nexis/responses/true_id_response.rb, app/services/doc_auth/response.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb, spec/jobs/document_proofing_job_spec.rb, spec/services/doc_auth/acuant/pii_from_doc_spec.rb, spec/services/doc_auth/acuant/responses/get_results_response_spec.rb, spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb
*Why?* 
We need to move to logging the Id type properly sent back to us by Acuant. Right now we just hard coded it to drivers license.
=> LG-4611: Replace state id type

Gemfile.lock, Makefile, app/controllers/users/two_factor_authentication_controller.rb, app/services/doc_auth_router.rb, app/services/idv/data_url_image.rb, app/views/shared/_block_link.html.erb, spec/features/idv/doc_auth/send_link_step_spec.rb, spec/features/idv/hybrid_flow_spec.rb, spec/lib/deploy/activate_spec.rb, spec/services/idv/data_url_image_spec.rb, spec/support/oidc_auth_helper.rb
Follow up to #5364 that addresses all but one Ruby 3 issue.
We currently use `URI.decode` which has been deprecated for a bit, and is removed in Ruby 3:
https://github.com/18F/identity-idp/blob/68480831403a4fa993bc5fb7a4ecb0d57f42a60f/app/services/idv/data_url_image.rb#L21-L25
None of the replacement methods have the same behavior that keeps the `+` character, so this test can't pass:
https://github.com/18F/identity-idp/blob/68480831403a4fa993bc5fb7a4ecb0d57f42a60f/spec/services/idv/data_url_image_spec.rb#L38-L40
Do we know if the client side of image upload uses URI encoded data?
=> Pre-Ruby 3 fixes (part two)

app/services/doc_auth/acuant/request.rb, app/services/doc_auth/lexis_nexis/request.rb, app/services/doc_auth/lexis_nexis/responses/true_id_response.rb, spec/services/doc_auth/acuant/request_spec.rb, spec/services/doc_auth/lexis_nexis/request_spec.rb, spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb
LG-5100 Make sure vendor is logged for all submission responses and some minor refactors to clean up.
=> LG-5100 Log vendor for all docauth responses

app/services/doc_auth/lexis_nexis/responses/true_id_response.rb, spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb
**Why**: So that we log and track for billing in the same way as we do with Acuant.
=> LG-5101: Include billed property in TrueID response hash

spec/features/idv/doc_auth/verify_step_spec.rb, spec/features/users/sign_in_spec.rb, spec/support/capybara.rb, spec/support/features/session_helper.rb, spec/support/monitor/monitor_idp_steps.rb, spec/support/monitor/monitor_idv_steps.rb
**Why**: To avoid developer confusion when [`Capybara::Node::Actions#check`](https://rubydoc.info/github/jnicklas/capybara/master/Capybara%2FNode%2FActions:check) fails when called on a USWDS checkbox, since USWDS styles replace the native checkbox with a stylized pseudo-element, and the native element is placed offscreen. This requires "allow_label_click" option to be passed. Since we can assume most checkboxes/radios should be USWDS checkboxes/radios, set this as the default behavior.
See: https://rubydoc.info/github/jnicklas/capybara/master/Capybara#configure-class_method
=> Configure Capybara to always click checkbox label

Makefile
The "-R" ("--rails") option was removed as of RuboCop 0.72.
See: https://github.com/rubocop/rubocop/releases/tag/v0.72.0
=> Fix lintfix Makefile target to remove invalid argument

app/views/sign_up/passwords/new.html.erb, config/locales/forms/en.yml, config/locales/forms/es.yml, config/locales/forms/fr.yml, spec/support/features/session_helper.rb, spec/views/sign_up/passwords/new.html.erb_spec.rb
*Why?* 
Language has been updated. now password is translated properly.
=> LG-4953: update language for password

spec/monitor_spec_helper.rb
Previously: https://github.com/18F/identity-idp/pull/5385
Smoke tests use a separate configuration for Capybara, so it needs to be set as well.
=> Configure smoke tests for automatic label click

app/views/idv/doc_auth/send_link.html.erb, app/views/shared/_personal_key.html.erb
This PR adds the `<strong>` element to bolded text in the IAL2 flow
**Why**: To make sure that we are following accessibility best practices.
- End result: "User agents can then make the structure perceivable to the user, for example using a different visual presentation for different types of structures or by using a different voice or pitch in an auditory presentation."
Note: There are areas across the IAL1 flow that should also be updated. This PR specifically addresses the items that were highlighted during the [IAL2 accessibility audit](https://docs.google.com/spreadsheets/d/1GeotAc3zqed0WiQIibPNsZKZ8yIlhKpHSW-gQ9IO3Jg/edit#gid=1982542849)
=> LG-4963: Send link page, emphasis for text

.circleci/config.yml, Makefile, deploy/build
Ignores dev dependencies and ensures the lock file is not modified or out of sync
Deployed this change to my sandbox and the install and asset compilation still work as expected
=> do a production yarn install in the build step

app/assets/stylesheets/components/_external-link.scss, app/assets/stylesheets/utilities/_typography.scss, package.json, yarn.lock
Blocks #5279
**Why**: So that we can use updated tile checkbox and radio button styling, and remove temporary patches which are now incorporated upstream.
Release notes: https://github.com/18F/identity-style-guide/releases/tag/v6.1.0
=> Upgrade Login.gov Design System to 6.1.0

spec/features/account/backup_codes_spec.rb
**Why**: To match actual logic of the view, in case the set of backup codes aren't all created in a timeframe before the next minute elapses.
View logic:
https://github.com/18F/identity-idp/blob/3a3dac6ae701d4d56a3735a07afd78341074cd8f/app/view_models/account_show.rb#L33-L35
Example failing build: https://app.circleci.com/pipelines/github/18F/identity-idp/51886/workflows/c48b25c2-c872-4aba-86c5-fa33ff42757a/jobs/81045/parallel-runs/1
=> Fix flakey backup codes spec

lib/deploy/activate.rb
Similar to https://github.com/18F/identity-devops/pull/3765, but for `identity-idp-config`
We really only care about the most recent version, so we may as well limit our download to that. I tested in my sandbox and everything works as expected. Tagged all of the partnerships engineers as this does have some effect on service provider config loading.
From a deployed instance with this patch:
```
root@idp-i-01749cc0308ae7963:/srv/idp/current# cd /srv/idp/current/identity-idp-config/
root@idp-i-01749cc0308ae7963:/srv/idp/current/identity-idp-config# git log
commit db068af98c8e6f700e411d2d9f24a5e4850cca5c (grafted, HEAD -> main, origin/main, origin/HEAD)
Author: Tianna Woodson <tianna24@vt.edu>
Date:   Thu Sep 9 14:51:58 2021 -0400
[LGN0000385 ] Add new Order for HHS (#488)
* Add new Order …
```
=> Shallow clone identity-idp-config

spec/support/features/document_capture_step_helper.rb
**Why**: To try to reduce flakiness. Since this happens async, there's quite some variability in how long it takes to complete.
=> Increase allowable wait time for RSpec doc auth submit

deploy/activate, deploy/build
This change is to facilitate some changes infrastructure-side in how we cache and install dependencies. It also includes fixing the deprecated bundle behavior.
It should not affect the current behavior of a deployment, and I've deployed this change to my sandbox to confirm that the logs show it using the same directory and re-using some of the gems already in the shared bundle cache.
Logs from a build step with this patch:
<details>
<summary>Log</summary>
```
+ which bundle
/opt/ruby_build/shims/bundle
+ : /srv/idp/shared/bundle
+ bundle config build.nokogiri --use-system-libraries
+ bundle config set --local deployment true
+ bundle config set --local path /srv/idp/shared/bundle
+ bundle config set --local without 'deploy development doc test'
+ bundle install --jobs 4
Fetching gem …
```
=> Allow configurable bundle directory in deploy step

app/assets/stylesheets/utilities/_background.scss, app/assets/stylesheets/utilities/_border.scss, app/assets/stylesheets/utilities/_color.scss, app/assets/stylesheets/utilities/_position.scss, app/assets/stylesheets/utilities/_space-addon.scss, app/assets/stylesheets/utilities/_space-misc.scss, app/assets/stylesheets/utilities/_typography.scss, app/assets/stylesheets/utilities/_util.scss, app/assets/stylesheets/utilities/all.scss, app/assets/stylesheets/variables/_app.scss, app/assets/stylesheets/variables/_colors.scss, vendor/assets/stylesheets/basscss/_typography.scss
**Why**:
- Moves us toward design system utilities, removing temptation of use for developers and facilitating future substitution work.
- Reduces size of stylesheets, producing smaller bundle sizes for users (faster page loads) and lower mental overhead for developers.
=> Remove unused CSS utility classes

app/jobs/reports/daily_auths_report.rb, spec/jobs/reports/daily_auths_report_spec.rb
Big whoops, discovered in dev ([newrelic link](https://one.newrelic.com/launcher/nr1-core.explorer/?platform[accountId]=1376370&platform[filters]=Iihkb21haW4gPSAnQVBNJyBBTkQgdHlwZSA9ICdBUFBMSUNBVElPTicpIg==&platform[timeRange][duration]=1800000&platform[$isFallbackTimeRange]=true&pane=eyJuZXJkbGV0SWQiOiJlcnJvcnMtdWkub3ZlcnZpZXciLCJlbnRpdHlHdWlkIjoiTVRNM05qTTNNSHhCVUUxOFFWQlFURWxEUVZSSlQwNThNVEEwTkRBNE1qVTQifQ==&cards[0]=eyJuZXJkbGV0SWQiOiJlcnJvcnMtdWkuZXJyb3ItdHJhY2VzIiwiZmlsdGVyU2V0TnJxbCI6IihgZXJyb3IuY2xhc3NgID0gJ0FyZ3VtZW50RXJyb3InIEFORCB0cmFuc2FjdGlvblVpTmFtZSA9ICdSZXBvcnRzOjpEYWlseUF1dGhzUmVwb3J0L2V4ZWN1dGUnKSIsInRpbWVab25lIjoiQW1lcmljYS9Mb3NfQW5nZWxlcyIsImVudGl0eUd1aWQiOiJNVE0zTmpNM01IeEJVRTE4UVZCUVRFbERRVlJKVDA1OE1UQTBOREE0TWpVNCIsInRyYWNlSWQiOiI2ZmQ4YjNhNC0xNTc3LTExZWMtOWI1ZC0wMjQy …
=> Fix wrong argument for bucket name in DailyAuthsReport

app/jobs/heartbeat_job.rb, spec/jobs/heartbeat_job_spec.rb
This is just an idea, very open to better places to put this
We don't have any examples I've seen of submitting Cloudwatch metrics directly, so I opted to go with a Rails.logger like we do for the Faraday metrics
We also don't have a consistent place to submit these (inside each job might be a little much) but a ~5 minute check on these seems not too bad?
The queries come from the GoodJob dashboard so I hope they are not too taxing on the DB
=> Update HeartbeatJob to log queue metrics

app/controllers/idv/gpo_controller.rb, app/controllers/idv/phone_controller.rb, app/models/document_capture_session.rb, app/services/analytics.rb, app/services/idv/phone_step.rb, app/services/idv/steps/doc_auth_base_step.rb, spec/controllers/idv/capture_doc_controller_spec.rb, spec/controllers/idv/doc_auth_controller_spec.rb, spec/controllers/idv/phone_controller_spec.rb, spec/jobs/document_proofing_job_spec.rb, spec/models/document_capture_session_spec.rb, spec/services/idv/phone_step_spec.rb, spec/services/idv/steps/verify_step_spec.rb
**Why**: We are seeing a lot of reuse session events probably due to jobs not finishing and retries. Need to prevent a job from starting before one finishes or allow the latest to rewrite a previous one.  Reverts this https://github.com/18F/identity-idp/pull/5113
=> Backout reuse doc auth sessions

app/forms/new_phone_form.rb, spec/features/phone/add_phone_spec.rb, spec/forms/new_phone_form_spec.rb
Looks like we switched which error is shown for VOIP phones. We wanted to show the first when there's an error checking if it's VOIP phone, and the second when it's a VOIP phone:
```
voip_check_error: There was an error checking your phone, please try again
voip_phone: This number is a web-based (VOIP) phone service. Please select a
different number and try again
```
https://github.com/18F/identity-idp/blob/main/config/locales/errors/en.yml#L104-L106
This patch switches it so we show the right error.
=> fix which error is shown for VOIP phones

app/jobs/reports/daily_auths_report.rb, spec/jobs/reports/daily_auths_report_spec.rb
the `report_body` is not memoized, so it would issue the query twice :yikes:
=> Daily Auths Report: only one query once per destination

.erb-lint.yml, app/assets/stylesheets/_vendor.scss, app/views/idv/doc_auth/welcome.html.erb, app/views/idv/otp_delivery_method/new.html.erb, app/views/partials/personal_key/_key.html.erb, app/views/shared/_footer_lite.html.erb, app/views/shared/_no_pii_banner.html.erb, app/views/sign_up/registrations/_registration_heading.html.erb, app/views/sign_up/registrations/_sp_registration_heading.html.erb, app/views/two_factor_authentication/options/index.html.erb, app/views/two_factor_authentication/otp_verification/show.html.erb, app/views/two_factor_authentication/totp_verification/show.html.erb, app/views/two_factor_authentication/webauthn_verification/show.html.erb, app/views/users/piv_cac_authentication_setup/new.html.erb, app/views/users/totp_setup/new.html.erb, app/views/users/two_factor_authentication_setup/index.html.erb, app/views/users/webauthn_setup/new.html.erb, config/initializers/simple_form.rb
**Why**: To improve page load speed by reducing CSS bundle size, to eliminate developer confusion by choice of styling, to improve developer experience by reducing SASS compilation times, to standardize on design system styles, and to attach semantics to brand "primary" color as possibly changing over time and not fixed to specific colors.
Reference for removal: https://github.com/basscss/basscss-sass/blob/v3.0.0/_colors.scss
=> LG-3880: Remove BassCSS "colors" module

app/views/idv/doc_auth/welcome.html.erb, spec/features/idv/doc_auth/welcome_step_spec.rb
Adds a location parameter for the "Get help at..." link on the IAL2 welcome page to ensure we have an accurate number for Cancel
=> LG-5073: add location to "Get Help at SP" link on welcome page

deploy/build
Allows the instance build process to tell the IDP to only attempt to install Ruby/JS dependencies from local sources (artifact) without making any HTTP requests.
[bundle install](https://bundler.io/v2.2/man/bundle-install.1.html)'s `--local` option:
>Do not attempt to connect to rubygems.org. Instead, Bundler will use the gems already present in Rubygems' cache or in vendor/cache. Note that if an appropriate platform-specific gem exists on rubygems.org it will not be found.
[yarn install](https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install-offline)'s `--offline` option:
>Run yarn install in offline mode.
dev-ops changes are in https://github.com/18F/identity-devops/pull/3778
=> support local-only install in build script via environment variables

app/jobs/risc_delivery_job.rb, spec/jobs/risc_delivery_job_spec.rb
This currently results in a 500 to end users that are resetting their password or doing something else that generates an event. Instead, we should rescue and retry on these errors.
[SSL NR Link](https://one.newrelic.com/launcher/nr1-core.explorer?platform[accountId]=1376370&platform[timeRange][duration]=43200000&pane=eyJiYXJjaGFydCI6ImJhcmNoYXJ0IiwidG9wRmFjZXQiOiJ0cmFuc2FjdGlvblVpTmFtZSIsInBhZ2UiOiJzaG93IiwicHJpbWFyeUZhY2V0IjoiZXJyb3IuY2xhc3MiLCJ0cmFjZUlkIjoiM2U1ODI2YmMtMWEzMi0xMWVjLTk2MGYtMDI0MmFjMTEwMDA4XzBfMjQ4OTMiLCJmaWx0ZXJzIjpbeyJrZXkiOiJlcnJvci5leHBlY3RlZCIsInZhbHVlIjoibm90IHRydWUifSx7ImtleSI6ImVycm9yLmNsYXNzIiwidmFsdWUiOiJGYXJhZGF5OjpTU0xFcnJvciIsImxpa2UiOmZhbHNlfV0sIm5lcmRsZXRJZCI6ImVycm9ycy11aS5vdmVydmlldyIsImVudGl0eUd1aWQiOiJNVE0zTmpNM01IeEJVRTE4UVZCUVRFbERRVlJKVDA1OE5USXhNelk0T …
=> Do not raise during RISC job if server returns SSL error

app/controllers/two_factor_authentication/otp_verification_controller.rb, spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
We received a submission with a missing parameter, which led to a 500. This patch coerces the parameter into a string and ensures we don't call `strip` on `nil`
[NR link](https://one.newrelic.com/launcher/nr1-core.explorer?platform[accountId]=1376370&platform[timeRange][duration]=43200000&pane=eyJiYXJjaGFydCI6ImJhcmNoYXJ0IiwidG9wRmFjZXQiOiJ0cmFuc2FjdGlvblVpTmFtZSIsInBhZ2UiOiJzaG93IiwicHJpbWFyeUZhY2V0IjoiZXJyb3IuY2xhc3MiLCJ0cmFjZUlkIjoiZGE3MGIzMTUtMWEyZi0xMWVjLTk2MGYtMDI0MmFjMTEwMDA4XzBfMTY4NTkiLCJuZXJkbGV0SWQiOiJlcnJvcnMtdWkub3ZlcnZpZXciLCJlbnRpdHlHdWlkIjoiTVRNM05qTTNNSHhCVUUxOFFWQlFURWxEUVZSSlQwNThOVEl4TXpZNE5UZyJ9&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5R3VpZCI6Ik1UTTNOak0zTUh4QlVFMThRVkJRVEVsRFFWUkpUMDU4TlRJeE16WTROVGciLCJzZWxlY3RlZE5lcmRsZXQiOnsibmVyZGxldElkIjoi …
=> Avoid raising 500 when OTP verification code is nil

app/assets/stylesheets/components/_abbr.scss, app/assets/stylesheets/components/all.scss
**Why**: Because they're unused.
The styles themselves are very old, introduced in #73. While the pull request hadn't specifically implemented any `abbr` elements, it's likely they were targeted at "required" asterisks which were removed as of #4855. From what I can tell, we do not render any `abbr` currently in the IdP. The default styles with text underline would be desirable for any future usage, an example of which can be seen [on the developer site](https://developers.login.gov/security-events/) ([screenshot](https://user-images.githubusercontent.com/1779930/134213324-980cc51f-f453-44cb-84f3-6960a21d3f42.png)).
=> Remove unused abbreviation styles

app/javascript/packs/ial2-consent-button.js, app/views/idv/doc_auth/agreement.html.erb, app/views/sign_up/registrations/new.html.erb, config/locales/forms/en.yml, config/locales/forms/es.yml, config/locales/forms/fr.yml, config/locales/sign_up/en.yml, config/locales/sign_up/es.yml, config/locales/sign_up/fr.yml
This PR adds a "please check this box to continue" warning to the doc auth agreement page.
**Why**: So that users are error messages are more consistent and easily identifiable to the user.
Before | After 
--- | --- |
=> LG-5115:Refactor the check/select box behavior across the IAL2 flow

app/controllers/idv/confirmations_controller.rb, app/services/idv/session.rb, spec/controllers/idv/confirmations_controller_spec.rb
(#5230)
This reverts commit 57308972fd615821a84dd51943923a195ec0190f
---
these changes resulted in double-generation of personal keys, so the personal key shown to the user does not work to recover PII
- We will need to find a way to find affected users, and come up with a flow for them to re-generate their personal keys
=> Revert changes to IDV personal key generation

.erb-lint.yml, app/assets/stylesheets/_vendor.scss, app/assets/stylesheets/utilities/_background.scss, app/views/idv/doc_auth/welcome.html.erb, app/views/partials/personal_key/_key.html.erb, app/views/shared/_no_pii_banner.html.erb, app/views/users/piv_cac_authentication_setup/new.html.erb, app/views/users/totp_setup/new.html.erb
**Why**: To improve page load speed by reducing CSS bundle size, to eliminate developer confusion by choice of styling, to improve developer experience by reducing SASS compilation times, to standardize on design system colors and semantics, and to resolve broken visual appearances for backgrounds.
Reference for removal: https://github.com/basscss/basscss-sass/blob/v3.0.0/_border-colors.scss
Design system color reference: https://design.login.gov/utilities/color/
Page Element|Before|After
---|---|---
No PII Banner|![Screen Shot 2021-09-21 at 10 52 39 AM](https://user-images.githubusercontent.com/1779930/134195382-14ed7ab3-09d8-419e-8949-e9424f454662.png)|![Screen Shot 2021-09-21 at 10 52 16 AM](https://user-images.githubusercontent.com/1779930/134195422-a512fd99-3102-4aca-9924-97d7d79eea44 …
=> LG-3880: Remove BassCSS "background-colors" module

app/views/idv/address/new.html.erb
This PR moves the zip code input to its own line per the [Figma designs](https://www.figma.com/file/g8SrhXQC67JiNaUeaDBACl/Investigate-instructions-for-zip-code-across-flows-%5BLG-4946%5D?node-id=11%3A82). This will help with a future ticket to add the error message "Enter a 5-digit or 9-digit zip code".
=> LG-5141: Move zip code to its own line

config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml
This PR changes wording from verification code to confirmation code.
**Why**: To be consistent with GPO language
=> LG-5066:Update "verification code" to "confirmation code" on "Come back soon" page

app/jobs/reports/base_report.rb, app/jobs/reports/daily_auths_report.rb, app/jobs/reports/daily_dropoffs_report.rb, app/models/doc_auth_log.rb, app/services/db/doc_auth_log/drop_off_rates_helper.rb, config/initializers/job_configurations.rb, spec/factories/doc_auth_logs.rb, spec/jobs/reports/daily_dropoffs_report_spec.rb
This is a new report that is based heavily on the existing DropoffHelper classes
New report looks like:
```csv
issuer,friendly_name,iaa,agency,start,finish,welcome,agreement,capture_document,cap_doc_submit,ssn,verify_info,verify_submit,phone,encrypt,personal_key,verified
issuer1,The App,iaa123,The Agency,2021-03-01T00:00:00+01:00,2021-03-01T23:59:59+01:00,3,2,2,2,2,2,2,2,2,2,1
issuer2,The Other App,iaa123,The Agency,2021-03-01T00:00:00+01:00,2021-03-01T23:59:59+01:00,5,4,3,2,1,0,0,0,0,0,0
```
The existing reports look like:
```
Sprint
'09-09-2021' <= date user starts doc auth < '09-23-2021'
step  users %users dropoff
welcome 120960   100%      6%
agreement 113265    94%      7%
capture_document 105000    87%     17%
cap_doc_submit  87634    72%     19%
ssn  70887    59%      0% …
```
=> Add daily dropoffs report, for the dashboard (LG-4649)

app/services/doc_auth/lexis_nexis/responses/true_id_response.rb, spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb
In testing the TrueID interface, we noticed a 500 that appears to be due to some malformed dates coming back from LexisNexis. This PR ensures that the day, month and year all parse to integers greater than 0.
=> LG-5140: guard against improper date data returned from LN

bin/activate, config/application.yml.default, deploy/activate, lib/deploy/activate.rb, lib/tasks/activate.rake
Most of our build setup scripts are implemented as rake tasks that are called from scripts, with the exception of `activate`. This moves activate into a rake task and combines it into a single `bundle exec rake` so the bundle only has to be exec-ed once.
=> Convert bin/activate to rake task

Gemfile, config/boot.rb
This PR enables the ability to use Bootsnap in production. I have been testing this in my sandbox for a bit and haven't seen any ill effects. The primary benefit is we make multiple calls to rake tasks which load the Rails environment, and it becomes a lot faster after the first time with this change.
=> allow bootsnap in production

.rubocop.yml, app/controllers/application_controller.rb, app/controllers/users/sessions_controller.rb, app/controllers/users/two_factor_authentication_controller.rb, app/controllers/users/two_factor_authentication_setup_controller.rb, lib/linters/redirect_back_linter.rb, spec/controllers/application_controller_spec.rb, spec/lib/linters/redirect_back_linter_spec.rb
This changeset was deployed earlier today to patch the vulnerability before disclosing it.
Previously, an attacker could redirect users to malicious external sites by rewriting the Referer header during the request/response cycle. These changes prevent redirects to external sites and falling back to a specified page (usually root) if it is attempted.
`redirect_back` uses the Referer header to redirect back to the previous page, but Rails does not yet support globally preventing external host redirects, so I've also added a Rubocop that will fail if we try to do a `redirect_back` without disabling external hosts and including a fallback location.
=> Do not allow redirects via Referer to external hosts

.erb-lint.yml, app/views/accounts/_nav_auth.html.erb
**Why**: To fix visual appearance in IE11 due to SVG scaling.
Before|After
---|---
=> Account Header: Add height attribute to logo image

app/services/gpo_daily_test_sender.rb, spec/services/gpo_daily_test_sender_spec.rb
**Why**: Remove useless exceptions in lower envs
=> Update GpoDailyTestSender to warn, not error when missing configs

lib/deploy/activate.rb
Enables https://github.com/18F/identity-devops/pull/3813 to work as expected. `File.exist?` is `false` for symlinks, so we need to check for both.
=> Check file or symlink exists during S3 download in deploy/activate

app/controllers/two_factor_authentication/otp_verification_controller.rb, app/javascript/app/phone-internationalization.js, app/validators/otp_delivery_preference_validator.rb, app/views/idv/otp_delivery_method/new.html.erb, app/views/users/edit_phone/_delivery_preference_selection.html.erb, app/views/users/shared/_otp_delivery_preference_selection.html.erb, config/locales/two_factor_authentication/en.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml, spec/controllers/users/phone_setup_controller_spec.rb, spec/features/two_factor_authentication/sign_in_spec.rb, spec/features/users/sign_in_spec.rb
**Why**:
- So that we consistently show a hint text for both situations of SMS or Voice being unavailable in a country.
- So that if the selected option is disabled after changing countries, the other option becomes selected as long as it is not also disabled.
1. Log in
2. Click "Add a phone number" in the account dashboard sidebar
3. Observe: Both options are enabled, SMS is selected
4. Change country to Vietnam
5. Observe: SMS is disabled, Voice is now the selected option, hint text indicates SMS unavailable to Vietnam.
6. Change country to Canada
7. Observe: Voice is disabled, SMS Is now the selected option, hint text indicates Voice unavailable to Canada.
8. Change country to Algeria
9. Observe: Both options are disabled, neither is selected, hint text …
=> LG-4991: Improve phone OTP disabling behavior

app/javascript/packages/document-capture/components/selfie-capture.jsx, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml
This PR adds alt text to the user's selfie image
**Why**: The selfie is a meaningful image and should have an alt text associated with it so that the user knows what it is.
=> LG-4935: Add alt text to selfie image

app/javascript/packages/document-capture/components/acuant-capture.jsx, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, spec/javascripts/packages/document-capture/components/acuant-capture-spec.jsx
Looking at data over the past four weeks, we found that BMP and TIFF image submissions make up a tiny fraction of all submissions, and of those the success rate is much lower than the overall success rate.
Specifically, out of 418693 total submissions:
* BMP: 115 submissions (0.027%) with 14 successes (12.17%)
* TIFF: 370 submissions (0.088%) with 39 successes (10.54%)
Another reason to drop support is just the increased file size, e.g., in testing with my drivers license, starting with the jpg version and converting from that to other image types, my file sizes were as follows:
* JPG: 2.2 MB
* BMP: 36.6 MB or scaled to 50%: 9.1 MB
* TIFF: 48.8 MB or scaled to 50%: 12.3 MB
=> LG-5142: remove tiff, bmp as options for document upload

app/views/idv/doc_auth/verify.html.erb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml
This PR adds an `aria-label` to the change button/link on the "Verify your Identity" page.
**Why**:So that screen readers announce that the elements are to change address and change social security number
=> LG-5114: Update link text to be more comprehensive

dependabot.yml
**Why**: To reduce confusion and maintenance overhead incurred by version drift, to simplify the sync process, and to take advantage of the latest features and bug fixes as quickly as they're made available.
Reference: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates#enabling-github-dependabot-version-updates
Per [configuration options](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem), `npm` is the correct "ecosystem" even though we use Yarn.
h/t @zachmargolis for [suggestion](https://github.com/18F/identity-style-guide/pull/254#pullrequestreview-767017227)
=> Configure auto-updates for identity-style-guide

app/javascript/packages/document-capture/components/acuant-capture.jsx, app/javascript/packages/document-capture/hooks/use-counter.js, spec/javascripts/packages/document-capture/components/acuant-capture-spec.jsx, spec/javascripts/packages/document-capture/hooks/use-counter-spec.jsx
**Why**: To have a better understanding of how many attempts that users are making before submitting images, so that we can get a better idea of burden users are experiencing.
=> LG-4737: Include attempts in Acuant SDK analytics

spec/controllers/users/sessions_controller_spec.rb
**Why**: Because the keepalive response depends on relative times, so we should freeze time during test execution to avoid off-by-X if the test takes slightly longer to complete.
Example failure: https://app.circleci.com/pipelines/github/18F/identity-idp/54398/workflows/1c09446f-0e10-4f58-8a9d-271394f69ff6/jobs/84633/parallel-runs/2
=> Try to fix flakey keepalive test

app/forms/idv/api_image_upload_form.rb, app/jobs/document_proofing_job.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb, spec/jobs/document_proofing_job_spec.rb
**Why**: So that we can easily determine number of attempts to assess user burden, especially in matching to client-side analytics (#5463), and so that the numbers can be interpreted irregardless changes to the configured maximum attempts.
Relevant Slack conversation: https://gsa-tts.slack.com/archives/CNCGEHG1G/p1633109940058200
=> LG-4737: Include attempts in vendor submitted payload

.gitignore
This creates the `geo_data` directory with a `.gitkeep` file in it so that there is a blank directory available on a fresh clone. 
The goal is to make it easier to symlink or copy data into the `geo_data` directory during the deploy process without having to create or check that the directory already exists.
=> Create geo_data directory

app/jobs/risc_delivery_job.rb, spec/jobs/risc_delivery_job_spec.rb
- Add handling for ERRNO:EConnRefused (this repros when trying something like `localhost:9999` that does not exist
- Added tests to confirm behavior for non-200 responses (just warn)
=> Add additional error handling in RiscDeliveryJob (LG-5130)

babel.config.js, package.json, yarn.lock
**Why**: Because the [class fields proposals](https://github.com/tc39/proposals/blob/master/finished-proposals.md) are now part of the [ES2022 specification](https://tc39.es/ecma262/), it is no longer necessary to use a plugin to support the syntax.
Example affected code:
https://github.com/18F/identity-idp/blob/2ff0846221fdc0dd3e580a6cfbf8ac473829cccb/app/javascript/packages/one-time-code-input/index.js#L2
=> Bump Babel dependencies, drop class properties plugin

spec/support/monitor/monitor_email_helper.rb
* Should add ~15 seconds more every time we check
Would love to see if we can log IDs on the IDP side and some sort of received timestamp in S3 so we can see what our actual email delivery delays are
=> Increase number of email checks for smoke tests

app/assets/stylesheets/components/_form.scss
This PR adjusts the styling of the exclamation mark/checkmark to align to the top. This is so that all errors can be aligned with the first line of a validation message.
Error state
Success state
Note:
- This change has been implemented in the design system, but it has not been released as of the creation of this PR. Once the design system has been updated, we will refactor the styles accordingly.
=> add styling for validation errors to IdP

config/locales/doc_auth/en.yml
**Why**: Because it's incorrect.
=> LG-5213: Fix alt image typo for "Back of an ID"

spec/features/monitor/create_account_spec.rb, spec/support/monitor/monitor_email_helper.rb
So we can check if the email was ever delivered. I also changed the pending tests to being skipped since there's no point in running them
=> Log temporary email address in smoketest error

spec/support/monitor/monitor_email_helper.rb
By only getting 100 unsorted objects from S3, there was always a chance the email we were looking for wouldn't be returned, so I've upped the number of objects returned to the maximum and added paging
=> Page through S3 for smoke test emails

app/services/flow/flow_state_machine.rb, spec/controllers/idv/capture_doc_controller_spec.rb, spec/controllers/idv/doc_auth_controller_spec.rb, spec/features/idv/doc_auth/agreement_step_spec.rb, spec/features/idv/doc_auth/document_capture_step_spec.rb, spec/features/idv/doc_capture/document_capture_step_spec.rb
Retires the older `Doc Auth visited|submitted` event names.
**Why?** We moved to the more consistent naming scheme (`IdV: doc auth <step> visited|submitted`) last February. Any instances of dashboards that are still using the old names and will break can and should be updated to the new names.
=> LG-4815: retire legacy event names

config/application.rb, config/application.yml.default, lib/identity_config.rb, spec/requests/openid_connect_cors_spec.rb
This is a very hot codepath, so caching this helps us alleviate pressure on the DB
=> CORS: cache redirect uris from DB

app/services/idv/steps/document_capture_step.rb, config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml
**Why**: Because they're never actually presented to the user, who will instead see the message derived from the failing response.
Also helps for a few points of general cleanup:
- `bold` is a BassCSS class and is deprecated in favor of design system.
- Per https://github.com/18F/identity-idp/pull/5565#issuecomment-958146515, these sorts of notice content with embedded HTML may need to be opted-in to `html_safe`, so this eliminates one point of update.
This logic is only used for the no-JavaScript document capture. In practice, what happens is that the same error message which would be presented in the React application is presented to no-JavaScript.
Example:
If you follow the flow of logic, you can see that the `failure` method does capture this as "extra", but that extra is not used for …
=> Remove unused document capture notice text

config/application.yml.default, db/seeds.rb, lib/identity_config.rb
**Why:** https://gsa-tts.slack.com/archives/C01SU3NB9T3/p1636035938073500
We need to make sure we turn this setting on in production `application.yml` before deploying.
=> Add configuration to turn off agreements data seeding if desired

lib/tasks/dev.rake, spec/lib/tasks/dev_rake_spec.rb
**Why:** this will help make local development on the Dashboard easier (since that application seeds the DB with an admin user with that email address)
=> Add admin@gsa.gov to the dev:prime rake task

app/controllers/users/verify_password_controller.rb, app/controllers/users/verify_personal_key_controller.rb, app/forms/verify_personal_key_form.rb, app/models/profile.rb, app/services/reactivate_account_session.rb, spec/forms/verify_personal_key_form_spec.rb, spec/services/reactivate_account_session_spec.rb
- Minimize chances of accidental logging by using redacted struct
=> Pass around Pii::Attributes around instead of a string (LG-5294)

db/primary_migrate/20211104171549_drop_backup_code_configurations_unique_index_on_code_fingerprint.rb, db/primary_migrate/20211104172508_change_backup_code_configurations_allow_null_code_fingerprint.rb, db/primary_migrate/20211104173202_change_backup_code_configurations_allow_null_encrypted_code.rb, db/schema.rb
- Make columns nullable so we can stop writing
- Remove unique index so we can stop writing
=> Prepare to drop encrypted_code columns (LG-4427)

app/assets/stylesheets/_vendor.scss
**Why**: Because none of these classes are currently in use.
I noticed that all classes in this file are already covered by banned ERBLint deprecated class pattern.
https://github.com/18F/identity-idp/blob/70f46e021b291101075f60417f48f87a1c45d488/.erb-lint.yml#L131
https://regex101.com/r/nl5J6U/1
Source: https://github.com/basscss/basscss-sass/blob/v3.0.0/_responsive-white-space.scss
=> Remove unused BassCSS responsive white space module

lib/identity_job_log_subscriber.rb, spec/lib/identity_job_log_subscriber_spec.rb
Was looking at worker logs and noticed:
```
NameError: undefined local variable or method `wait' for #<IdentityJobLogSubscriber:0x00005576f49b9270>
/srv/idp/releases/chef/lib/identity_job_log_subscriber.rb:88
```
This PR should fix that
=> Fix error in job log subscriber

.circleci/config.yml
(cherry picked from commit e3943af3e5a08718c83a6e368bab37906659a657)
I Googled the error and just copied this StackOverflow answer: https://stackoverflow.com/a/59669110
Discovered that on https://github.com/18F/identity-idp/pull/5592, the tests kept failing, this fixed them
=> Fix CodeCoverage in CircleCI

.circleci/config.yml, app/jobs/reports/agency_invoice_issuer_supplement_report.rb, app/services/db/monthly_sp_auth_count/total_monthly_auth_counts_within_iaa_window.rb, spec/jobs/reports/agency_invoice_issuer_supplement_report_spec.rb, spec/services/db/monthly_sp_auth_count/total_monthly_auth_counts_within_iaa_window_spec.rb
I copied logic I wrote in `UniqueMonthlyAuthCountsByIaa` which has a switch between `SUM` and `COUNT(DISTINCT user_id)`, so it didn't come from out of nothing...
I suspect this might result in some longer running queries so we may want keep an eye on this
=> Add unique users per-month to issuer supplement report (LG-5319)

spec/javascripts/support/console.js
Extracted from: #5590
**Why**: So that it's easier to debug the root cause of a console log, which may use format arguments to describe the callsite.
API reference: https://developer.mozilla.org/en-US/docs/Web/API/console/error
`util.format`: https://nodejs.org/api/util.html#utilformatformat-args
_Before:_
```
1) "after each" hook for "ends on unmount":
AssertionError: Unexpected console logging: Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s: expected [ Array(1) ] to be empty
at Context.<anonymous> (spec/javascripts/support/console.js:55:43)
at processImmediate (internal/timers.js:461:21)
```
_After:_
```
1) "after each" hook for …
```
=> Support formatted message arguments in console.error test spy

app/services/analytics.rb, spec/controllers/openid_connect/user_info_controller_spec.rb, spec/services/analytics_spec.rb, spec/support/fake_request.rb
**Why**: Current funnel stats track by event.  However events are reused in different contexts at different endpoints.  Rather than parse other state markers for each which is highly brittle simply create a new success state token that combines endpoint/path, event, and verb.  This will give us finer grain tracking and allow us to track subfunnels.  ie 'POST:/api/openid_connect/userinfo:OpenID Connect: bearer token authentication'
=> Finer grained funnel tracking

config/i18n-tasks.yml, spec/i18n_spec.rb
Figured out why the i18n-tasks gem thought a bunch of keys were unused
=> Configure i18n-tasks to look inside lib/ dir as well

app/models/concerns/user_otp_methods.rb, spec/models/user_spec.rb
**Why**: [RFC 4226](https://datatracker.ietf.org/doc/html/rfc4226) specifies that the length should meet or exceed 128 bits.
=> Increase TOTP secret length from 80 bits to 160 bits

config/initializers/geocoder.rb
We see a few occasional geocoder timeouts in prod while reading from disk, my hypothesis was that the Geocoder gem lazily loads its datasource.
- [Example NewRelic error](https://onenr.io/0kLwGZ6DvQ6)
In a fresh Rails console in INT, I believe I confirmed this. The first lookup is ~0.1 seconds, and subsequent lookups are at least 200x faster, no matter the order or values, so I am pretty sure the first one forces a lookup
```ruby
> timing = %w[0.0.0.0 1.2.3.4 8.8.8.8 192.168.1.1].map { |ip| Benchmark.realtime { Geocoder.search(ip) } }
=> [0.08297044999926584, 0.00040709099994273856, 0.0003728679985215422, 0.00019449899991741404]
timing[1..].map { |x| timing.first / x }
=> [203.81302954606332, 222.51963249260257, 426.58548390735075]
```
The first commit …
=> Preload geocoder database, to minimize timeouts

app/jobs/reports/doc_auth_drop_off_rates_report.rb
**How**: By making sure all queries are wrapped in a
transaction timeout block
[Friday pairing w/ @jauschalley]
=> Fix query timeout in DocAuthDropOffRatesReport (LG-5288)

app/controllers/users/authorization_confirmation_controller.rb, app/views/users/authorization_confirmation/show.html.erb, spec/features/openid_connect/authorization_confirmation_spec.rb, spec/features/saml/authorization_confirmation_spec.rb, spec/support/features/session_helper.rb
The authorization screen shows `current_user.email`, but that's not the one we send to the SP. This PR corrects it to show the email that will be sent to the SP.
=> Show correct email address in authorization confirmation screen

app/jobs/reports/gpo_report.rb
**How**: Without the transaction_with_timeout block,
it runs against the primary DB, but the same query against
the read replica is fine
=> Fix report timeout in GPO Report (LG-5289)

app/forms/webauthn_setup_form.rb, config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml, spec/forms/webauthn_setup_form_spec.rb
*Why?*
Trying to remove all reference to Hello@login.gov in IDP.
=> LG-4826: Remove reference to hello@login.gov

Gemfile, Gemfile.lock
See: https://github.com/18F/redis-session-store/pull/5
When https://github.com/roidrage/redis-session-store/pull/125 is merged, we'll be able to go back to the rubygems version
=> Update redis-session-store to fork with security fixes (LG-5369)

app/views/shared/_no_pii_banner.html.erb
**Why**: To help ensure that people see it and don't enter PII
Screenshot:
=> Make the no PII banner comically large

app/views/idv/doc_auth/welcome.html.erb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml
[LG-5372](https://cm-jira.usa.gov/browse/LG-5372) - Updating the content and styling of the welcome step based on UX user research.
[Figma here](https://www.figma.com/file/PTB99GHGAVtD5YeW69vg05/IAL2-Troubleshooting-options-(LG-5209%2C-LG-4202%2C-LG-4309)?node-id=801%3A4783)
[Translations here](https://docs.google.com/document/d/16AuBsj1UJeImdQe9Ac8ujFNqwIX4Ru0cgHbYCCnJ4nE)
=> LG-5372 Minor content and styling update for IAL2 welcome and agreement steps.

app/javascript/packages/normalize-yaml/visitors/smart-punctuation.js, app/javascript/packages/normalize-yaml/visitors/smart-punctuation.spec.js, config/locales/doc_auth/en.yml, config/locales/doc_auth/fr.yml, config/locales/errors/fr.yml, config/locales/idv/fr.yml, config/locales/telephony/en.yml, config/locales/telephony/fr.yml, config/locales/titles/fr.yml, config/locales/vendor_outage/fr.yml, spec/lib/telephony/otp_sender_spec.rb
Related: https://github.com/18F/identity-idp/pull/5617/files#r752657699
**Why**: So that we're normalizing YAML consistently.
The previous regular expression would match content up to and within HTML tags, but would not match in cases where the string contains no HTML, or where text occurred _after_ an HTML tag.
=> YAML normalization: Fix non-HTML fragment smart punctuation replacement

spec/javascripts/packages/document-capture/components/acuant-capture-spec.jsx, spec/javascripts/spec_helper.js, spec/javascripts/support/dom.js
**Why**: To avoid needing to cherry-pick individual window properties to promote to the global namespace, which often comes as a surprise, and likely won't be clear how to resolve when the need arises. Instead, assign all window properties as global properties, which is essentially how it behaves in a browser environment.
=> Simplify spec DOM globals assignment

config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml
This PR is to implement content changes to two error messages in the IAL2 flow.
The send_link_throttle error text in the hybrid flow needs to be changed because it references the "Start Over" button, which no longer appears on that page. Instead, the user should go back to try uploading images with their computer.
The 438 error text is changed to avoid saying "something is wrong" with the image the user submitted, which can cause cognitive burden to the user.
=> LG-4888: updated IAL2 error messaging

Gemfile, Gemfile.lock, app/components/base_component.rb, app/helpers/script_helper.rb, spec/components/base_component_spec.rb
Extracted from: #5619
**Why**: Because it's expected that a component with a "sidecar" JavaScript file will load that file, regardless whether the component is rendered as nested within another component.
Upgrades `view_component` gem from 2.40.0 to latest (2.43.1) to fix related bug where `helpers` reference was not consistent ([see v2.42.0 release notes](https://viewcomponent.org/CHANGELOG.html#2420)).
=> Fix support for nested ViewComponent scripts

app/forms/idv/phone_form.rb, spec/forms/idv/phone_form_spec.rb
Extracted from: #5619
**Why**:
- Fixes an issue where if the phone number is used in a PhoneInputComponent (in LG-5333, and after LG-5399), the intl-tel-input library could have trouble parsing the country of an arbitrary, user-entered number value, resulting in a scenario where the flag dropdown appears as an empty gray box.
- Presumably it is easier to read a nicely-formatted phone number than a string of 6-14 numbers (cc @anniehirshman-gsa)
- It matches how the number is actually saved and sent with the attributes bundle, allowing a user to make corrections if they spot an issue
- It matches the behavior where a user's existing phone number automatically pre-fills the input
Screenshots taken with revisions in #5619 to use PhoneInputComponent on IAL2 address …
=> Format phone numbers for PhoneForm initial value

app/assets/stylesheets/components/_form.scss, config/initializers/simple_form.rb
Extracted from: #5619
Related upstream PR: 18f/identity-style-guide#275
**Why**:
- For improved consistency of presentation of error messages in the application
- Favoring design system over redundant, ad-hoc implementations
- Unblocking new behaviors in #5619 where form-level `has-error` class error styling would take precedence over field-level validity state styling
Before|After
---|---
1. From root page, click "Create an account"
2. Enter "example@example" as email address
3. Click checkbox to confirm Rules of Use
4. Click "Submit"
5. Observe error message
**Notes:**
For the most part, these error messages are not seen too often by end-users, due to client-side validation, both custom and browser native validation.
=> Update SimpleForm configuration to use design system error styling

app/controllers/concerns/saml_idp_auth_concern.rb, app/controllers/saml_idp_controller.rb, app/controllers/saml_post_controller.rb, app/services/saml_endpoint.rb, app/views/saml_post/auth.html.erb, config/routes.rb, spec/controllers/saml_idp_controller_spec.rb, spec/controllers/saml_post_controller_spec.rb, spec/requests/saml_post_spec.rb, spec/support/saml_auth_helper.rb
Currently, an external POST request to the IdP will not have access to
an existing session since the cookie is blocked due to `SameSite=Lax`.
This results in users with an active session having to sign in again if
sent back to the IdP with a POST SAML request.
However, if the POST request comes _from_ the IdP the session will be
available in that request. Therefore, this commit inserts a new action
within our SAML POST handling that captures the SAML parameters of the
original POST request, populates a form with them (with appropriate CSRF
handling), and then submits that form with JS to create an "internal"
POST request with access to the session. This new action skips session
handling so it does not override an existing IdP session cookie.
=> Ensure SAML POST requests preserve an existing session

app/javascript/packs/form-validation.js, app/views/users/phone_setup/index.html.erb, app/views/users/phones/add.html.erb, spec/javascripts/packs/form-validation-spec.js
Extracted from: #5619
**Why**:
- To avoid conflicts between form-validation custom validation and other custom validation which may apply to an input (e.g. a component implementation).
- For consistency of form rendering to include baseline validation (e.g. required field validation).
- To restore test coverage for remaining pattern type validation in `form-validation.js`.
- To reflect latest changes where SSN validation is handled by adjacent visible text element as of #5468.
Previously, changing the value of an input within a form subject to `form-validation.js` behavior would reset custom validity, and often introduced race conditions where a custom implementation's custom validity behavior would be unexpectedly reset.
Steps to reproduce:
1. Log in
2. On Account dashboard, click "Add …
=> Form Validation: Limit custom validation reset to own validation

app/javascript/packages/components/troubleshooting-options.jsx, app/javascript/packages/components/troubleshooting-options.spec.jsx, app/javascript/packages/document-capture/components/warning.jsx, app/views/idv/doc_auth/welcome.html.erb, app/views/shared/_troubleshooting_options.html.erb, spec/views/shared/_troubleshooting_options.html.erb_spec.rb
There was a styling bug in the TroubleShooting React component. So after a quick discussion the missing style class was added and the ability to customize the header tag in the component was introduced. This brings the react troubleshooting component in line with the ruby implementation.
=> Fix for react troubleshooting component heading style

config/application.rb
Sample error running locally:
```
11:57:37 web.1         | bundler: failed to load command: rackup (.rbenv/versions/2.7/bin/rackup)
11:57:37 web.1         | identity-idp/config/application.rb:61:in `<class:Application>': good_job.queues does not contain *, but it should (RuntimeError)
```
=> Throw an error at boot if good_job does not have '*' queue (LG-5352)

app/controllers/concerns/billable_event_trackable.rb, app/controllers/openid_connect/authorization_controller.rb, app/controllers/saml_idp_controller.rb, spec/features/openid_connect/authorization_confirmation_spec.rb, spec/features/saml/authorization_confirmation_spec.rb
**Why:** this doesn't make sense for the step up flows since it's disruptive to users.
Currently, when a user authenticates with an active Login.gov session,
they are taken to an account selection screen as per the OIDC spec. In
order to provide a more seamless "step-up" flow from IAL1 to IAL2, we
are going to only take a user to that screen on their first visit to a
given SP, and skip it on subsequent visits.
=> Skip select account screen on return visits

app/views/idv/doc_auth/agreement.html.erb, app/views/idv/doc_auth/welcome.html.erb
LG-5372 Follow on minor update to action button top and bottom white space.
=> LG-5372 Follow on minor update to action button whitespace

app/jobs/reports/agency_invoice_iaa_supplement_report.rb, app/jobs/reports/agency_invoice_issuer_supplement_report.rb, app/jobs/reports/combined_invoice_supplement_report.rb, app/services/db/monthly_sp_auth_count/total_monthly_auth_counts_within_iaa_window.rb, app/services/iaa_reporting_helper.rb, config/initializers/job_configurations.rb, spec/jobs/reports/agency_invoice_iaa_supplement_report_spec.rb, spec/jobs/reports/combined_invoice_supplement_report_spec.rb, spec/services/db/monthly_sp_auth_count/total_monthly_auth_counts_within_iaa_window_spec.rb, spec/services/iaa_reporting_helper_spec.rb
See JIRA for example spreadsheet that billing team requested that this implements
- Extracts out GTC to IAA logic from old reports
- Repurposes old reporting classes
- Builds a CSV! (much easier to parse as a spreadsheet than JSON)
=> Create combined IAA/issuer billing report as CSV (LG-4975)

Gemfile, Gemfile.lock, app/controllers/concerns/saml_idp_auth_concern.rb, spec/controllers/saml_idp_controller_spec.rb, spec/support/fake_saml_request.rb
The SAML specification (section 3.4.1) includes an attribute
`ForceAuthn` for the `AuthnRequest` element that can be used by an SP to
require that a user be authenticated again, rather than relying on a
previous security context. This change allows the IdP to respect that
attribute and force authentication when an SP includes
`ForceAuthn='true'` in the SAML request.
Blocked on https://github.com/18F/saml_idp/pull/50
=> Respect the ForceAuthn attribute in SAML AuthnRequests

.circleci/config.yml
We get pretty infrequent smoke test errors in the form of:
```
parse error: Invalid numeric literal at line 1, column 7
```
This adds an echo to print the response to see what went wrong
=> echo deploy.json response to debug SHA checkout errors in smoke tests

.rubocop.yml
**Why**: The configuration was intended to allow the Capybara "page.find_by_id" method within feature specs. However, this wasn't working correctly for several reasons:
- "Include" should have been "Exclude", to exempt feature specs while still enforcing elsewhere.
- "AllowedMethods" is still called "Whitelist" in the version of Rubocop we use, so it was emitting a warning about invalid configuration.
- The "Include" path was wrong, since we have our tests in "spec", not "tests"
The result of these is that the rule was not being applied _anywhere_, since it was only including files that don't actually exist in the project.
=> Fix Rubocop DynamicFindBy excludes

app/javascript/packages/document-capture/components/form-steps.jsx
*Why?*
Looks like we enabled a way to disable this if we add class name 'read-after-submit' to the form. I added it and I do not see aria-hidden=true to the body anymore.  
https://github.com/18F/identity-idp/blob/main/app/javascript/app/accessible-forms.js#L12
=> LG-4576: add class name to ignore accessibility-form.js

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_phone-input.scss, app/components/phone_input_component.html.erb, app/javascript/packages/phone-input/index.spec.js, app/views/shared/_ssn_field.html.erb, config/initializers/simple_form.rb
**Why**: As a step toward USWDS as the standard for form building. We don't appear to be using SimpleForm's `hint` behavior anyways as-is, but this would change the configured default to use the USWDS class, and refactors existing ad-hoc usage of USWDS to take advantage of the form builder to simplify implementation of standard defaults.
There is not intended to be any visual changes as a result of these revisions, but screenshots below show the affected code:
Screen|Screenshot
---|---
Add Phone|![Screen Shot 2021-11-30 at 9 34 53 AM](https://user-images.githubusercontent.com/1779930/144067496-bee8e168-368e-4867-b593-99f7c9a539ac.png)
Enter SSN|![Screen Shot 2021-11-30 at 9 34 35 AM](https://user-images.githubusercontent.com/1779930/144067531-f77ef6e4-29aa-4e3a-83b5-9cbeed5771d2.png)
=> Configure USWDS "usa-hint" class for form hints

app/services/proofing/aamva/request/verification_request.rb, app/services/proofing/lexis_nexis/instant_verify/verification_request.rb, app/services/proofing/lexis_nexis/phone_finder/verification_request.rb, lib/telephony/configuration.rb, lib/telephony/otp_sender.rb, lib/telephony/pinpoint/sms_sender.rb, lib/telephony/pinpoint/voice_sender.rb
I thought Rubocop warned on unnecessary disables, but I guess not. The Rubocop rules were different across repos, so we can make them closer to the IDP rules now that they're here.
=> Remove outdated rubocop disables

.rubocop.yml, lib/linters/translation_linter.rb, spec/lib/linters/translation_linter_spec.rb
**Why**: Since it's easy to overlook, and not otherwise caught during standard pull request CI, therefore likely to cause surprise (and Slack channel noise) when it inevitably fails post-merge.
Context: https://github.com/18F/identity-idp/pull/5650/files#r759674528
=> Add custom Rubocop cop to prevent translation in smoke tests

app/javascript/packages/one-time-code-input/index.js, spec/javascripts/packages/one-time-code-input/index-spec.js
**Why**: [By specification](https://html.spec.whatwg.org/multipage/dom.html#global-attributes:the-id-attribute-2), an ID "must not contain any ASCII whitespace".
It's unclear what (if anything) this affects, though it doesn't seem to be an intended behavior regardless.
=> Remove whitespace from OneTimeCodeInput altered input ID

app/controllers/application_controller.rb, app/javascript/packs/form-steps-wait.jsx, spec/controllers/application_controller_spec.rb
The issue is that `response.url` comes back blank in our `fetch` polyfill (used here), so the Verify and Address steps that poll end up failing.
https://github.com/18F/identity-idp/blob/02d60d09ba99d9712a56c9c56063efe386c45b11/app/javascript/packs/form-steps-wait.jsx#L109
So the polyfill authors recommend this workaround https://www.npmjs.com/package/whatwg-fetch#user-content-obtaining-the-response-url
Confirmed this works in my personal sandbox
=> Fix IDV in IE (LG-4526)

app/javascript/packages/validated-field/index.js, app/javascript/packages/validated-field/index.spec.js
**Why**: Since the component is meant to emulate (and eventually replace) the behaviors currently present in `form-validation.js`, this should include `aria-invalid` attribute setting behavior.
=> Set aria-invalid on ValidatedFieldComponent for invalid field

db/primary_migrate/20211206205035_add_issuer_returned_at_index_to_sp_return_logs.rb, db/schema.rb
**Note**: My goal is to deploy this index as a patch release (today?) so that it if goes poorly, we can revert it and clean it up well before the scheduled Thursday deploy
**Background**:
We're getting consistent timeouts in the new, Combined IAA report see below is one of the queries that's timing out (inside of `TotalMonthlyAuthCountsWithinIaaWindow`)
The `sp_return_logs` table is very big, and even using the `requested_at` index still yields too many rows, so our current hypothesis is that a new index would help to speed things up, assuming the query planner doesn't pick the wrong one.
```sql
SELECT
sp_return_logs.user_id
, '202109' AS year_month
, sp_return_logs.ial
, COUNT(sp_return_logs.id) AS auth_count
FROM sp_return_logs
WHERE
sp_return_logs.requested_at BETWEEN '2021-09-01' AND …
```
=> Add index to sp_return_logs to speed up reporting queries

.gitlab-ci.yml
Incorporates the changes in https://github.com/18F/identity-idp/pull/5391 into Gitlab CI
=> Bring GitLab CI up to date with CircleCI

lib/tasks/db_sp_return_logs_index.rake
**Why**: Index took too long to create, timed out and left
partial index in production
- Index added in https://github.com/18F/identity-idp/pull/5670
- Copied approach from https://github.com/18F/identity-idp/pull/5127
=> Add rake task to help with manual index management

lib/tasks/db_sp_return_logs_index.rake
**Why**: Index took too long to create, timed out and left
partial index in production
(cherry picked from commit 808e45bb6bb1120e547500a75c9f06111a1a79ea)
=> Deploy RC 168.2 to Production 

.bummr-build.sh, .fasterer.yml
Previously: #4481
**Why**: Because we don't use these gems anymore, we should no longer have need for configuration files.
=> Remove configuration files for unused gems

.erb-lint.yml, app/views/account_reset/delete_account/show.html.erb, app/views/accounts/_webauthn.html.erb, app/views/idv/doc_auth/_back.html.erb, app/views/idv/doc_auth/link_sent.html.erb, app/views/idv/doc_auth/upload.html.erb, app/views/idv/doc_auth/verify.html.erb, app/views/idv/phone/new.html.erb, app/views/idv/shared/_document_capture.html.erb, app/views/shared/_banner.html.erb, app/views/user_mailer/account_verified.html.erb, app/views/users/service_provider_inactive/index.html.erb
**Why**: To make incremental progress toward fixing up ERBLint exclusions, so that the changes don't need to be incorporated in unrelated ticket work.
Approach, for future reference:
1. Remove [all excluded files](https://github.com/18F/identity-idp/blob/808e45bb6bb1120e547500a75c9f06111a1a79ea/.erb-lint.yml#L7-L104)
2. Replace [`inherit_from`](https://github.com/18F/identity-idp/blob/808e45bb6bb1120e547500a75c9f06111a1a79ea/.erb-lint.yml#L106-L107) with:
```
AllCops:
DisabledByDefault: true
```
3. Copy a specific [Rubocop configuration](https://github.com/18F/identity-idp/blob/main/.rubocop.yml) to [`rubocop_config:`](https://github.com/18F/identity-idp/blob/808e45bb6bb1120e547500a75c9f06111a1a79ea/.erb-lint.yml#L105)
4. If the cop is auto-correctable, run `bundle exec erblint app/views …
=> Fix ERB trailing comma errors

app/jobs/reports/agreement_summary_report.rb, spec/jobs/reports/agreement_summary_report_spec.rb
Background:
- Issuers are generated by `SecureRandom.uuid` in factories: https://github.com/18F/identity-idp/blob/62ed7b475aa72a98b0ba0ff865b9bcfd7225a22b/spec/factories/service_providers.rb#L7
- We're now sorting by issuers as of this PR: https://github.com/18F/identity-idp/pull/5669/files#diff-dff005bc5b24ed4b3d86658e47c5a0ce9028e780f9282be6ed60a65f4c02d5c8R30
So to make the build reliable, I am giving this test (that depends on row order) consistent issuers
=> Use deterministic issuer names for ordered tests

app/controllers/idv/gpo_controller.rb, app/presenters/idv/gpo_presenter.rb, spec/controllers/idv/gpo_controller_spec.rb
**Why**: So that we can track how often a user interacts with the "Send another letter" link on the GPO letter code entry page.
=> LG-5241: Log GPO letter code resend

db/primary_migrate/20211207125122_drop_user_index_in_sp_return_logs.rb, db/schema.rb
**Why**: This is our most used and biggest table.  We need to keep the amount of indexes small.  The user request history can be gleaned from the cloudwatch logs and does not need to be fetched programatically
=> Drop sp_return_logs unused user index

app/javascript/packages/document-capture/components/document-capture.jsx, app/javascript/packages/document-capture/components/submission-complete.jsx, spec/javascripts/packages/document-capture/components/submission-complete-spec.jsx
This ticket removes the re-rendering of the `<SubmissionInterstitial>` component from the document capture and submission complete screen.
**Why**: So that a screen reader does not re-read "We are processing your images" multiple times
=> Document capture interstitial heading announced multiple times

app/views/idv/come_back_later/show.html.erb, spec/views/idv/come_back_later/show.html.erb_spec.rb
**Why**: So that we can track user progression through the flow.
This approach simply takes advantage of existing "location" logging parameter support on the rendered `return_to_sp_cancel_path` link, such that we could query link clicks as `filter name = 'Return to SP: Cancelled' and properties.event_properties.location = 'come_back_later'`. An alternative could be to create a new controller action in `ComeBackLaterController` for the redirect logic, and log an explicit new event.
=> LG-5262: Add logging to continue button on letter wait page

config/routes.rb
Previously: #5662 ([discussion](https://github.com/18F/identity-idp/pull/5662#discussion_r762137156))
**Why**: Because they exist only as a stopgap for mid-deploy routing, they are no longer needed as of RC169.
**Do not merge until after RC169 is fully deployed.**
=> Remove temporary routes for SP redirects

app/views/idv/doc_auth/_ssn_init.html.erb, app/views/idv/doc_auth/_ssn_update.html.erb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml
**Why**: So that users in the test envs will know not to enter real SSNs and how to enter valid test SSNs
=> Show a message in lower envs explaining how to use test SSNs

.gitlab-ci.yml
Implements a minimal subset of the CircleCI smoke tests.
Things that are intentionally excluded:
- Checking out the deployed SHA
- Staging and Prod smoke tests
GitLab's configuration of CI schedules doesn't allow specifying the job in the schedule configuration, so it's handled by setting environment variables and checking it in the `rules` of the job.
=> Smoke tests in GitLab CI

app/javascript/packs/form-validation.js, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml, spec/javascripts/packs/form-validation-spec.js
**Why**: Because it's unused.
Personal key fields are rendered in three places, none of which use this logic:
- [**IAL2 confirmation**](https://github.com/18F/identity-idp/blob/c2e26ec11670d6ee4dbbe2ff3c44235e08eb281b/app/views/shared/_personal_key_confirmation_modal.html.erb#L19) and [**post-password reset profile restore**](https://github.com/18F/identity-idp/blob/c2e26ec11670d6ee4dbbe2ff3c44235e08eb281b/app/views/users/verify_personal_key/new.html.erb#L11) are not rendered within a `validated_form_for`, and therefore `form-validation.js` is not loaded at all.
- [**Personal key MFA login**](https://github.com/18F/identity-idp/blob/c2e26ec11670d6ee4dbbe2ff3c44235e08eb281b/app/views/partials/personal_key/_entry_fields.html.erb) is rendered within a `validated_form_for`, but because it has …
=> Remove unused personal-key pattern validation message

.erb-lint.yml, app/assets/stylesheets/_vendor.scss, app/views/shared/_footer_lite.html.erb, app/views/two_factor_authentication/otp_verification/show.html.erb
**Why**:
- Standardize on design system
- Smaller bundled output, and faster generation
- Avoid ambiguity for developers choosing flex styling
References:
- BassCSS classes: https://github.com/basscss/basscss-sass/blob/v3.0.0/_flex-object.scss
- Design system classes: https://designsystem.digital.gov/utilities/flex/
=> Remove BassCSS flex-object styling

app/services/vendor_status.rb, spec/controllers/vendor_outage_controller_spec.rb, spec/services/vendor_status_spec.rb
**Why**: So that we're consistently logging status for all vendors, not just for a subset of them.
These should have been included in #5550.
=> Log all vendor status in VendorStatus#track_event

app/forms/idv/api_document_verification_form.rb, app/forms/idv/api_image_upload_form.rb, app/javascript/packages/document-capture/components/document-capture.jsx, app/jobs/document_proofing_job.rb, app/jobs/resolution_proofing_job.rb, app/services/idv/actions/verify_document_action.rb, app/services/idv/actions/verify_document_status_action.rb, app/services/idv/agent.rb, app/services/idv/steps/doc_auth_base_step.rb, app/services/idv/steps/verify_step.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/features/idv/doc_auth/verify_step_spec.rb, spec/javascripts/packages/document-capture/components/document-capture-spec.jsx, spec/jobs/document_proofing_job_spec.rb, spec/services/idv/steps/verify_step_spec.rb
Our logging for flow path don't include flow path for `IdV: doc auth image upload form submitted`, `IdV: doc auth image upload vendor submitted`, and `IdV: doc auth image upload vendor pii validation`. 
By not having this we can't differentiate in the logs between hybrid and normal flow for these events.
=> Add flow path to post doc capture submission events (LG-5257)

app/controllers/idv/cancellations_controller.rb, app/services/analytics.rb, app/services/idv/session.rb, app/views/idv/cancellations/new.html.erb, config/routes.rb, spec/controllers/idv/cancellations_controller_spec.rb, spec/features/idv/doc_capture/document_capture_step_spec.rb, spec/support/idv_examples/cancel_at_idv_step.rb, spec/views/idv/cancellations/new.html.erb_spec.rb
**Why**: So that we can more easily track the user's path through IAL2.
Very open to implementation feedback, specifically around...
1. Do we really want this as a separate controller action?
2. Does "Go back" make sense to make as the `PUT` verb of the `CancellationsController` this way?
3. Are we okay to store the "go back" path in session like this?
4. Any other options to reconcile hybrid vs. no-hybrid session storage?
5. Naming of the event: "go back" is rather awkward, but felt less awkward than "cancellation cancelled" 🤷
=> LG-5261: Add cancel page logging to "Go Back" button

.prettierrc, docs/frontend.md
**Why**:
- We don't recommend BassCSS
- Link to tools (Sass, Stylelint, etc) as a resource for those who may not already be familiar with them
- Light explanation of difference between USWDS and LGDS
- Mention BEM naming convention for CSS classes
- Hints to developers:
- Where they learn about available design system components and utilities
- Editor integrations for Stylelint & Prettier, to make their lives easier
**Preview:** https://github.com/18F/identity-idp/blob/aduth-update-frontend-docs-css/docs/frontend.md
**Note for review:** Content edits were only made to the "CSS + HTML" section of the document. The remainder of changes to the file were from applying Prettier formatting for consistent 100-column wrapping (open to debate whether we want this).
=> Update "Frontend" CSS docs to reflect current approach

app/controllers/concerns/saml_idp_logout_concern.rb, app/controllers/saml_idp_controller.rb, app/services/analytics.rb, config/routes.rb, spec/controllers/saml_idp_controller_spec.rb
**Why:** This will allow partners to send back-channel SAML Logout
requests instead of redirecting users as part of their logout flow. This
controller action leverages the `<SessionIndex>` element of the SAML
request to receive a user's agency UUID and uses the unique_session_id
attribute to remotely log out a user from any active session.
=> Add remote SAML Logout endpoint

.rubocop.yml, app/helpers/form_helper.rb, app/services/attribute_asserter.rb, app/services/doc_auth/error_generator.rb, app/services/doc_auth/mock/doc_auth_mock_client.rb, app/services/encryption/multi_region_kms_client.rb, lib/telephony/pinpoint/sms_sender.rb, spec/features/idv/doc_auth/verify_step_spec.rb, spec/services/proofing/base_spec.rb, spec/support/acuant_fixtures.rb
**Why**: Because the inline configuration should only be used in cases where we're expecting a cop failure to otherwise occur.
Resources:
- https://docs.rubocop.org/rubocop/cops_lint.html#lintredundantcopdisabledirective
- https://docs.rubocop.org/rubocop/cops_lint.html#lintredundantcopenabledirective
=> Configure and fix Rubocop redundant disabling/enabling

app/javascript/packages/document-capture/components/document-capture.jsx, app/javascript/packages/document-capture/components/review-issues-step.jsx, app/javascript/packages/document-capture/context/upload.jsx, app/javascript/packages/document-capture/services/upload.js, app/presenters/image_upload_response_presenter.rb, app/services/doc_auth/error_generator.rb, app/services/doc_auth/error_result.rb, app/services/doc_auth/errors.rb, app/services/doc_auth_router.rb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, spec/controllers/idv/doc_auth_controller_spec.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/presenters/image_upload_response_presenter_spec.rb, spec/services/doc_auth/acuant/responses/get_results_response_spec.rb, spec/services/doc_auth/error_generator_spec.rb, spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb, spec/services/doc_auth/mock/result_response_builder_spec.rb
Doc Auth: Added the ability to hide and show capture hints for the user depending on error returned from the backend. Also added field level errors where applicable for the user.
=> LG-5325 Doc Auth: Error dependent hints and enhanced field level errors

app/views/accounts/_connected_app.html.erb, spec/views/accounts/connected_accounts/show.html.erb_spec.rb
https://github.com/18F/identity-idp/pull/5683 introduced a regression that broke displaying times, this PR reverts that change
=> Fix regression in displaying connected account times (LG-5472)

app/components/button_component.html.erb, app/components/button_component.rb, app/components/clipboard_button_component.html.erb, app/components/clipboard_button_component.js, app/components/clipboard_button_component.rb, app/javascript/packages/clipboard-button/index.js, app/javascript/packages/clipboard-button/index.spec.js, app/javascript/packages/clipboard-button/package.json, app/javascript/packages/polyfill/index.js, app/javascript/packages/polyfill/package.json, app/views/shared/_personal_key.html.erb, package.json, spec/components/button_component_spec.rb, spec/components/clipboard_button_component_spec.rb, spec/support/shared_examples_for_personal_keys.rb, yarn.lock
**Why**: Since "Print" and "Copy" are not navigable, they should not be rendered as links, since (a) this has the effect of scrolling the user to the top of the page when clicking the buttons and (b) they are announced to assistive technology as links. Since they behave as buttons, they should be rendered as such.
**Implementation notes:**
This refactors a fair bit of how these elements are rendered:
1. Replaces BassCSS grid with USWDS
2. Use margins instead of line breaks
3. Implements and renders a new `ClipboardButtonComponent`
Notes on `ClipboardButtonComponent`:
- This will be useful for upcoming implementation in LG-5456 for success indicators for clipboard buttons
- While this introduces a (seemingly-redundant) [new dependency](https://github.com/lgarron/clipboard-polyfill) for …
=> LG-4682: Resolve confirmation step button scroll-to-top, role

app/controllers/idv/phone_controller.rb, app/presenters/idv/otp_verification_presenter.rb, app/services/analytics.rb, app/views/idv/otp_delivery_method/new.html.erb, spec/controllers/idv/phone_controller_spec.rb, spec/features/idv/steps/phone_step_spec.rb
Currently "use a different phone number" links on both the IAL2 phone OTP pages aren't logged at all. This PR adds a `location` param to the link on each page with the path it is coming from, and if that location param is present, logs a new event.
=> [Logging] Log an event when the user chooses to use a different number. (LG-5259)

spec/services/doc_auth_router_spec.rb
I had a test run fail due to the randomness not working out in my favor ([CircleCI link](https://app.circleci.com/pipelines/github/18F/identity-idp/61567/workflows/8263ab44-7cbc-4f3b-9495-fbf9950e8d5c/jobs/95566/parallel-runs/3?filterBy=FAILED))
Setting the random seed would allow us to be exact in the expectations of how many end up in each category if we want to go that route. I'm very open to suggestions though.
There was some discussion in the original PR here on potential for flakiness: https://github.com/18F/identity-idp/pull/5296/files#r693164038
=> Fix flaky DocAuthRouter tests

app/controllers/concerns/saml_idp_logout_concern.rb, app/controllers/saml_idp_controller.rb, spec/controllers/saml_idp_controller_spec.rb
**Why:** We weren't testing this case explicitly and in the course of
writing said test this refactor in the concern seemed cleaner than the
original.
=> Refactor remote SAML logout user lookup

app/services/doc_auth/acuant/request.rb, app/services/doc_auth/lexis_nexis/request.rb, app/services/proofing/lexis_nexis/request.rb, spec/rails_helper.rb
Fixes some deprecations from #5694 
Ex:
```
2021-12-17 14:59:55 WARN Selenium [DEPRECATION] Manager#logs is deprecated. Use Chrome::Driver#logs instead.
WARNING: `Faraday::Connection#basic_auth` is deprecated; it will be removed in version 2.0.
While initializing your connection, use `#request(:basic_auth, ...)` instead.
See https://lostisland.github.io/faraday/middleware/authentication for more usage info.
```
=> Fix deprecations

app/jobs/risc_delivery_job.rb
**Why**: Retry less on network errors: 2 instead of 5.  Discard exception after retries. ( GoodJob.retry_on_unhandled_error = false) already set
=> LG-5450 update RiscDeliveryJob retry handling

app/jobs/profile_proofing_components_backfill_job.rb, app/models/profile.rb, app/services/idv/profile_maker.rb, config/environments/test.rb, spec/helpers/application_helper_spec.rb, spec/jobs/profile_proofing_components_backfill_job_spec.rb, spec/models/profile_spec.rb, spec/services/idv/profile_maker_spec.rb
- The column is jsonb column, which ActiveRecord serializes already
- We were basically double-encoding JSON objects
- Adds a backfill job so we can clean up existing data and simplifying
=> Clean up Profile.proofing_components column encoding

app/services/proofing/mock/resolution_mock_client.rb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml
This is the implementation for the notice going out to sandbox partners today. The dev docs notice is in https://github.com/18F/identity-dev-docs/pull/208 and this is a follow up to https://github.com/18F/identity-idp/pull/5576
It should not be merged prior to Dec 20th
=> Also allow 666 prefix in mock proofer

Makefile, config/locales/telephony/en.yml, config/locales/telephony/fr.yml
Reverts some of the changes in https://github.com/18F/identity-idp/pull/5621 because Pinpoint treats smart quotes differently than simple quotes.
=> Remove smart quotes from SMS message templates

app/javascript/packs/clipboard.js, app/views/users/backup_code_setup/create.html.erb, app/views/users/totp_setup/new.html.erb, package.json, spec/features/users/sign_up_spec.rb, spec/helpers/script_helper_spec.rb, yarn.lock
Builds upon: #5705, #5730 (temporarily merges to #5730)
**Why**:
- Better isolation of concerns
- Fewer dependencies
- Smaller bundle size
- Polyfill-based implementation of ClipboardButtonComponent allows targeting native browser APIs with eventual removal of polyfill (see #5705 for details)
- Fixes instance of inappropriate `link` role for copy button ([related](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_link_role#notes))
=> Migrate ClipboardJS to ClipboardButtonComponent

app/presenters/image_upload_response_presenter.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/presenters/image_upload_response_presenter_spec.rb
**Why**: As a user, I expect that I am redirected as soon as I've exhausted all attempts at document capture, so that I don't waste my time with a final attempt to capture that will be guaranteed to fail (even if the document was perfect).
This leverages the fact that the document capture upload handler will short circuit by the presence of a `redirect` property on the response:
https://github.com/18F/identity-idp/blob/9f863e54e2fc8b433e674c3f1d34d9f726aa0b0a/app/javascript/packages/document-capture/services/upload.js#L76-L82
=> LG-4670: Redirect document capture to throttled when no remaining attempts

app/models/concerns/user_otp_methods.rb, app/views/users/totp_setup/new.html.erb, spec/models/user_spec.rb
Follow-up to #5604, which had a small visual regression
| | before | after |
| -- | --- | --- |
| mobile | <img width="242" alt="Screen Shot 2021-12-21 at 11 06 43 AM" src="https://user-images.githubusercontent.com/458784/146984819-a7554b70-45f1-42eb-9bbd-f5e2f75ff2fa.png"> | <img width="242" alt="Screen Shot 2021-12-21 at 11 06 51 AM" src="https://user-images.githubusercontent.com/458784/146984823-1924d4e4-d4be-444c-8f1f-82bfbceeaebb.png"> |
| desktop | <img width="677" alt="Screen Shot 2021-12-21 at 11 06 20 AM" src="https://user-images.githubusercontent.com/458784/146984833-89a1363e-ad5b-4f12-a25f-a1a5724dab2f.png"> | <img width="677" alt="Screen Shot 2021-12-21 at 11 06 08 AM" src="https://user-images.githubusercontent.com/458784/146984837-ff7b62bc-326d-494e-951a-1aa6704e054b.png"> |
=> Fix TOTP copy button layout with longer code (LG-5436)

app/javascript/packages/components/troubleshooting-options.jsx, app/javascript/packages/components/troubleshooting-options.spec.jsx, app/javascript/packages/document-capture/components/capture-advice.jsx, app/javascript/packages/document-capture/components/document-capture-troubleshooting-options.jsx, app/javascript/packages/document-capture/components/review-issues-step.jsx, app/javascript/packages/document-capture/components/warning.jsx, app/views/idv/gpo/index.html.erb, app/views/idv/otp_delivery_method/new.html.erb, app/views/idv/phone/new.html.erb, app/views/idv/shared/_error.html.erb, config/locales/components/en.yml, config/locales/components/es.yml, config/locales/components/fr.yml, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml, spec/javascripts/packages/document-capture/components/document-capture-troubleshooting-options-spec.jsx, spec/javascripts/packages/document-capture/components/documents-step-spec.jsx, spec/javascripts/packages/document-capture/components/review-issues-step-spec.jsx, spec/javascripts/packages/document-capture/components/warning-spec.jsx, spec/views/idv/shared/_error.html.erb_spec.rb
**Why**: So that we are consistent in the options that we show users during document capture.
Before|After
---|---
=> LG-5468: Update IAL2 full-page ID error to show three troubleshooting options

app/controllers/concerns/saml_idp_logout_concern.rb, spec/controllers/saml_idp_controller_spec.rb
**Why**: Previously we were rendering a template with JS to make a post request to the ACS url. This does not make sense in a back channel logout request. Since the request is server to server there is no javascript to make the post request.
In this case, the IdP should render the logout request, and then make a best effort back channel post request to the ACS url. This PR makes the change to render the logout request. The ability to post to the ACS url may be problematic because of the need to work through firewall changes. I will leave that for a follow-on if a customer requests that change.
=> Render the logout response on remote logout

app/services/data_requests/write_user_events.rb, lib/tasks/data_requests.rake, spec/services/data_requests/write_user_events_spec.rb
- Also use the CSV library to generate the entire file
I handled an OIG request recently, and they wanted to combine the various `events.csv` files, but since the UUID was outside the file, it was a lot of manual work to combine. Including the UUID helps combine more easily
=> Add requesting user UUID to reports for the OIG reports

.circleci/config.yml, .gitlab-ci.yml
We'll be upgrading to 13 very soon, so we should run CI tests against 13!
=> Upgrade CI Postgres to 13

app/views/layouts/base.html.erb, app/views/shared/_banner.html.erb, spec/views/shared/_banner.html.erb_spec.rb
This PR is a refactor of the banner in that:
- The navigation has been moved inside the banner;
- The `<div>` for the banner has been replaced with a `<header>` element. The header element has an implicit role of `banner`, so the `role=banner` has been removed;
- The navigation now uses the `<nav>` element. The nav element has an implicit role of `navigation`, therefore `role=navigation` has been removed
With these changes, the navigation will no longer be read twice. Also, the top banner and the navigation will be grouped semantically.
=> Refactor banner

app/controllers/accounts/connected_accounts_controller.rb, app/controllers/accounts/history_controller.rb, app/controllers/accounts/two_factor_authentication_controller.rb, app/controllers/accounts_controller.rb, app/controllers/application_controller.rb, app/controllers/concerns/secure_headers_concern.rb, app/controllers/events_controller.rb, app/controllers/sign_up/completions_controller.rb, app/controllers/users/authorization_confirmation_controller.rb, spec/controllers/application_controller_spec.rb, spec/features/visitors/i18n_spec.rb, spec/support/features/session_helper.rb, spec/support/shared_examples/account_creation.rb, spec/support/shared_examples/sign_in.rb
Steps to reproduce the bug:
- Start from an SP that requires IAL2, get passed over to the IDP signin screen
- Before signing in, **change the locale**
- After signing in in that new locale, the locale will revert to the default locale (wrong)
The problem appears to be how we save the authorization URL `/openid_connect/authorize?param=...` and we redirect back there. However if the locale was changed after the URL is saved, the locale will be missing when we redirect to it, so this change adds in the locale before we redirect and preserve locale the rest of the flow
Since I was updating the behavior of the existing helper method, I decided to rename it too, which added some diff noise
=> Preserve locale change in identity verification (LG-5329)

lib/telephony.rb, lib/telephony/otp_sender.rb, spec/lib/telephony/otp_sender_spec.rb, spec/lib/telephony/telephony_spec.rb
Following #5732, we identified some missing guardrails around SMS message lengths and splitting. Using the documentation from AWS[^1], this PR implements tests and functionality to count and automate testing of how long our messages are so we get notified if they've changed.
Twilio is not our telephony provider, but they have helpful documentation as well[^2][^3][^4]. Their [Message Segment Calculator](https://twiliodeved.github.io/message-segment-calculator/) is also very good.
I tried to include more documentation around the tests and implementation, but it still feels kind of lacking.
[^1]: https://docs.aws.amazon.com/pinpoint/latest/userguide/channels-sms-limitations-characters.html#channels-sms-limitations-characters-gsm-alphabet
[^2]: …
=> Add specs around SMS message lengths

app/controllers/two_factor_authentication/webauthn_verification_controller.rb, app/forms/webauthn_setup_form.rb, app/forms/webauthn_verification_form.rb, spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb, spec/forms/webauthn_setup_form_spec.rb, spec/forms/webauthn_verification_form_spec.rb
Currently, MFA and MFA setup events for platform authenticators will have `multi_factor_auth_method: 'webauthn'`, which obscures our ability to see the usage of platform authenticators
=> Log WebAuthn Platform setups/authentications differently than roaming

app/controllers/idv/cancellations_controller.rb, app/services/idv/steps/send_link_step.rb, spec/features/idv/hybrid_flow_spec.rb
This fixes a really weird bug, when trying to re-enter the hybrid flow after cancelling on mobile
To reproduce:
1. Start IDV on desktop
2. Go through the Use Phone/Hybrid flow
3. From mobile, hit cancel
4. Back on desktop, go through Use Phone/Hybrid again
5. Then:
- **Before**: the desktop would show the desktop upload form (but would still send an SMS)
- **After**: desktop correctly shows the "waiting for mobile" screen
The core issue was that the code that detects which step to go to next was relying on a key being missing in the `flow_session`, which was not being reset correctly (see except below). It's tricky because the mobile flow gets a separate rails session from the desktop session, so we can't just delete that key from mobile …
=> Fix bug with IDV hybrid flow handoff after cancellation (LG-5367)

config/locales/forms/en.yml
The WebAuthn platform authenticator screen has a grammar typo - it uses "on to access your account" instead of "to access your account". I fixed this in the two places I saw it in `forms/en.yml`.
=> Grammar typo - "on to" to "to"

config/application.yml.default
**Why**: Low timeouts consistently trigger a segfault in
sassc, it happens even more often in Ruby 3 than it did
before
=> Increase rack timeout in development to fix assets locally

db/primary_migrate/20211230164415_drop_delayed_jobs.rb, db/primary_migrate/20211230165320_drop_otp_requests_trackers_on_updated_at_index.rb
We don't use delayed_job and the index on otp requests isn't used anywhere 🙂
=> Drop delayed_jobs table and otp requests tracker index

.circleci/config.yml
- Use CircleCI commands instead of YAML reference
Small cleanup follow-up to https://github.com/18F/identity-idp/pull/5770
=> CircleCI cleanup for browser tools

app/controllers/idv/cancellations_controller.rb, app/services/idv/steps/link_sent_step.rb, app/services/idv/steps/send_link_step.rb
=> Clean up SendLinkStep

config/locales/zxcvbn/en.yml, config/locales/zxcvbn/es.yml, config/locales/zxcvbn/fr.yml
@aduth Do we have existing spec tests that are related to this which would catch this type of missing error message in the yml file?
=> Add missing error messages to zxcvbn en.yml

app/javascript/packages/document-capture/components/acuant-capture.jsx, app/javascript/packages/document-capture/hooks/use-cookie.js, spec/javascripts/packages/document-capture/hooks/use-cookie-spec.jsx, spec/javascripts/support/console.js
Extracted from: #5747
**Why**: As observed in #5747, the current logic can be prone to race conditions when multiple instances of the hook exist (mostly affecting specs). The implementation overriding the global was meant to support a use-case where a component would re-render in response to an external script modifying a cookie (e.g. Acuant SDK). Since our current sole usage is to get the cookie value at the time of a user initiating a capture, this live-updating support isn't necessary and unnecessarily complicates the implementation.
=> Change useCookie hook to getter, avoid global override

app/jobs/reports/base_report.rb, app/jobs/reports/sp_user_counts_report.rb, app/services/analytics.rb, spec/jobs/reports/sp_user_counts_report_spec.rb
**Why**: Log all JSON reports to analytics for time based reporting and visualization
=> LG-5477 Log total users counts w/breakdowns to analytics

app/presenters/piv_cac_error_presenter.rb, app/services/piv_cac_service.rb, config/locales/instructions/en.yml, config/locales/instructions/es.yml, config/locales/instructions/fr.yml, spec/services/piv_cac_service_spec.rb
Follow up to #5782 
Error messages borrowed from https://github.com/18F/identity-idp/blob/e189165d07757e1f8dffd641024b075d8fd5837e/config/locales/errors/en.yml#L26
=> Handle pivcac token timeout

app/jobs/reports/daily_auths_report.rb, app/services/db/monthly_sp_auth_count/total_monthly_auth_counts_within_iaa_window.rb, app/services/db/monthly_sp_auth_count/unique_monthly_auth_counts_by_iaa.rb, db/primary_migrate/20220105143455_create_sp_return_logs_requested_at_date_issuer_index.rb, db/primary_migrate/20220105143540_drop_sp_return_logs_requested_at_indexes.rb, db/schema.rb, lib/tasks/db_sp_return_logs_index.rake
Currently, we frequently query this table by `request_id` in the application, and query by date ranges or date ranges and issuers for daily reports. This PR drops these two indexes and replaces them with a partial index on the date of `requested_at` and `issuer`, excluding rows that do not have `returned_at` set. This reduces the total index size by ~96% and should yield a very slight improvement in the queries used in the reports (more details [here](https://gsa-tts.slack.com/archives/C0NGESUN5/p1641409220067200)).
=> Reduce sp_return_logs index size

db/primary_migrate/20220105174343_drop_index_devices_user_id_cookie_uuid.rb, db/schema.rb
We have indexes on `cookie_uuid`, `user_id, cookie_uuid`, and `user_id, last_used_at` for the `devices` table. The `user_id, cookie_uuid` index is mostly redundant because querying by `cookie_uuid` or `user_id` should be able to fall back to one of the other two indexes without significant loss in performance (more details [here](https://gsa-tts.slack.com/archives/C0NGESUN5/p1641409752069400)).
=> Drop device_user_id_cookie_uuid index

.gitlab-ci.yml, Makefile, scripts/build_artifact
- Move build_artifact into a script
```
> make help
--- Help ---
brakeman             Runs brakeman
check                Runs lint tests and spec tests
check_asset_strings  Checks for strings
docker_setup         Setup script for Docker development
fast_setup           Abbreviated setup script that skips linking some files
fast_test            Abbreviated test run, runs RSpec tests without accessibility specs
help                 Show this help
lint                 Runs all lint tests
lint_country_dialing_codes Checks that countries supported by Pinpoint for voice and SMS are up to date
lint_erb             Lints ERB files
lint_optimized_assets Checks that assets are optimizes
lint_yaml            Lints YAML files
lintfix              Runs rubocop fix
normalize_yaml …
```
=> Implement self-documenting Makefile (LG-4635)

app/assets/config/manifest.js, app/assets/stylesheets/_required.scss, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/document-capture.scss, app/assets/stylesheets/variables/_app.scss, app/javascript/packages/document-capture/components/acuant-capture-canvas.jsx, app/javascript/packages/document-capture/components/acuant-capture.jsx, app/javascript/packages/document-capture/components/form-steps.jsx, app/javascript/packages/document-capture/components/review-issues-step.jsx, app/javascript/packages/document-capture/components/selfie-capture.jsx, app/javascript/packages/document-capture/styles.scss, app/views/idv/shared/_document_capture.html.erb, app/views/layouts/base.html.erb, config/webpack/environment.js, spec/javascripts/support/mocha.js
**Why**: To simplify ongoing work in #5746, to avoid double-processing of SASS files, and to consolidate in preparation for future CSS bundling refactoring ([cssbundling-rails](https://github.com/rails/cssbundling-rails)).
=> Standardize SASS processing to Sprockets

app/javascript/packages/document-capture/components/button-to.jsx, app/javascript/packages/document-capture/context/upload.jsx, app/javascript/packages/document-capture/services/upload.js, app/javascript/packs/document-capture.jsx, spec/javascripts/packages/document-capture/components/button-to-spec.jsx, spec/javascripts/packages/document-capture/context/upload-spec.jsx, spec/javascripts/packages/document-capture/services/upload-spec.js
**Why**: As discovered in #5746 (e40b020b2ec5256cf2103a4ff183424073f77d03), if request forgery protection is disabled (e.g. test environment), then there is no CSRF token meta tag on the page. Thus, our assumptions that this would always be present are mistaken. To avoid appending an invalid null token to relevant requests in an environment where forgery protection is disabled, we should properly handle the possibility of its absence.
=> Change document capture CSRF handling to optional

app/services/idv/steps/verify_base_step.rb, app/services/idv/steps/verify_wait_step_show.rb
To help get better insight into AAMVA verification issues, it'd be helpful to log both the state from the address, and the state from the ID jurisdiction
=> log state_id_jurisdiction in verify step

app/controllers/idv/personal_key_controller.rb, app/controllers/idv/phone_controller.rb, app/controllers/idv/review_controller.rb, app/javascript/packs/personal-key-page-controller.js, app/services/analytics.rb, app/services/funnel/doc_auth/register_step_from_analytics_view_event.rb, app/views/idv/personal_key/show.html.erb, config/routes.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/controllers/idv/phone_controller_spec.rb, spec/controllers/idv/review_controller_spec.rb, spec/features/accessibility/idv_pages_spec.rb, spec/features/idv/steps/review_step_spec.rb
An overhaul of the event logging on the personal key page.
Started with renaming the associated controller to fit the actual role the controller plays, then moves the existing event `IdV: final resolution` to the ReviewController where it better indicates the end of the IdV process.
Added new events for the entry/exit of this page (`IdV: personal key visited/submitted`) and also log the showing/hiding of the modal requiring the user to enter their personal key.
By keeping the final resolution event, no updates to any dashboards are necessary.
=> LG-5221 logging for personal key page

config/application.rb
Spotted by @aduth, we were adding when after it adds itself, so there were two Rack::Attacks in the middleware. Luckily Rack::Attack early-aborts if it has already run, but this should a small amount of memory/CPU time nonetheless
=> De-duplicate Rack::Attack when rate limiting is enabled

spec/monitor_spec_helper.rb, spec/support/capybara.rb
Should resolve:
```
WARN Selenium [DEPRECATION] [:browser_options] :options as a parameter for driver initialization is deprecated. Use :capabilities with an Array of value capabilities/options if necessary instead
```
=> Fix Selenium deprecation

app/services/backup_code_generator.rb, spec/services/backup_code_generator_spec.rb
I was looking at backup code success rate and it was at 100% because we log success as null instead of false, so this PR changes it to return a boolean in all cases
=> return false instead of nil for invalid backup code in analytics

.rubocop.yml, app/presenters/image_upload_response_presenter.rb, app/views/accounts/_phone.html.erb, spec/lib/deploy/activate_spec.rb, spec/services/marketing_site_spec.rb, spec/services/phone_confirmation/confirmaton_session_spec.rb
**Why**: So that we use consistent spacing for parentheses.
=> Enable Rubocop Layout/SpaceInsideParens cop

app/jobs/heartbeat_job.rb, lib/identity_job_log_subscriber.rb
So our worker metrics go to `workers.log` instead of `production.log`
=> Log worker metrics to workers.log

app/services/idv/steps/upload_step.rb, spec/features/idv/doc_auth/upload_step_spec.rb, spec/support/fake_analytics.rb
**Why**: So we can differentiate where the user will be lead as a result of the submission event.
=> LG-5251: Add location to logging for upload submitted event

config/environments/production.rb, config/environments/test.rb
**Why**: Because we don't use them currently, it's a waste of time.
Docs: https://guides.rubyonrails.org/asset_pipeline.html#gzipping-your-assets
Related: 18F/identity-devops#3486
=> Skip generating GZIP assets

app/views/idv/doc_auth/_ssn_init.html.erb, app/views/idv/doc_auth/_ssn_update.html.erb, app/views/idv/doc_auth/send_link.html.erb, app/views/idv/otp_verification/show.html.erb, app/views/two_factor_authentication/otp_verification/show.html.erb
**Why**: Because the class would already be applied, and in some cases we aren't applying the option correctly, since it must be passed as part of the `html` keyword option of `simple_form_for`.
See: https://github.com/18F/identity-idp/blob/3945fb03030d5c3569d824e6bd7498e5c796fc7a/config/initializers/simple_form.rb#L8
=> Remove redundant simple_form default class assignment

app/views/accounts/_auth_apps.html.erb, app/views/accounts/_manage_personal_key.html.erb, app/views/accounts/_phone.html.erb, app/views/accounts/_piv_cac.html.erb, app/views/accounts/_webauthn_platform.html.erb, app/views/accounts/_webauthn_roaming.html.erb, app/views/password_capture/new.html.erb, app/views/sign_up/passwords/new.html.erb, app/views/users/delete/show.html.erb, app/views/users/two_factor_authentication_setup/index.html.erb, app/views/users/webauthn_setup/new.html.erb
**Why**: Since `div` carries no semantics, and these elements have no other attributes or classes, the only purpose would have been to create a [block formatting context](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context), but this is not necessary for the changed files due their existing placement and/or surrounding content.
Going to be easiest to review with ignoring whitespace: [`?w=1`](https://github.com/18F/identity-idp/pull/5813/files?w=1)
=> Remove redundant empty div wrappers

app/controllers/accounts/personal_keys_controller.rb, app/controllers/users/personal_keys_controller.rb, app/view_models/account_show.rb, config/routes.rb, spec/controllers/accounts/personal_keys_controller_spec.rb, spec/controllers/users/personal_keys_controller_spec.rb
I'm about to do some bigger cleanup to the personal key sections of the account page, and I noticed some things I could clean up and break into a smaller PR
- Simplifying the `AccountShow` object
- Splitting `Users::PersonalKeysController` into two separate controllers
- One is used inline with the authentication flow to generate a new personal key when the old one is used (legacy flow)
- The other is more in the direction of the feature work we're doing, to let users regenerate their personal keys when they choose to (LG-5664 work)
=> Simplify account page personal key logic

Makefile
**Why**: Since the Webpack configuration has special considerations† for test environment (specifically, checking absence of i18n keys), ensure that the `yarn build` would be run with the correct environment.
---
†:
https://github.com/18F/identity-idp/blob/33e3781d4306869c355048b19bc0bc97731c3677/webpack.config.js#L70-L76
=> Correctly set RAILS_ENV for Make test target

app/helpers/script_helper.rb, config/application.rb, lib/asset_sources.rb, spec/helpers/script_helper_spec.rb, spec/lib/asset_sources_spec.rb
Related: https://github.com/18F/identity-idp/pull/5746#discussion_r781272048
**Why**: To avoid touching the filesystem for every request in production, since the manifest will never change during the lifetime of the application. Also, by loading the manifest at initialization, we can fail an instance quickly if, for some reason, the manifest file is not available.
In the discussion at https://github.com/18F/identity-idp/pull/5746#discussion_r781272048, it was considered if caching should only apply to production. However, since we aren't currently using fingerprinting in development, it may be fine to cache in development as well. The only downside is that _newly-added_ entrypoints would require an application restart, though this seems to be a reasonable compromise.
=> Persist Webpack assets manifest between requests

lib/tasks/users_lookup.rake
Does what it says on the tin! Addresses https://github.com/18F/identity-devops/issues/4162
Tested in my sandbox `idp`:
```
root@idp-i-018374.bleachbyte:~# sudo -H -u websrv env "app=idp" sh -euxc "cd '/srv/idp/current'; bundle exec rails users:lookup_by_email"
+ cd /srv/idp/current
+ bundle exec rails users:lookup_by_email
Enter the email address to look up: jonathan.pirro@gsa.gov
uuid: <REDACTED>
root@idp-i-018374.bleachbyte:~# sudo -H -u websrv env "app=idp" sh -euxc "cd '/srv/idp/current'; bundle exec rails users:lookup_by_email"
+ cd /srv/idp/current
+ bundle exec rails users:lookup_by_email
Enter the email address to look up: john.wong@example.com
No user found
```
=> create rake task to look up UUID by email address

app/javascript/packages/document-capture/components/acuant-capture.jsx, app/javascript/packages/document-capture/hooks/use-cookie.js, spec/javascripts/packages/document-capture/components/acuant-capture-spec.jsx, spec/javascripts/packages/document-capture/hooks/use-cookie-spec.jsx
**Why**: To fix a bug where if the Acuant camera fails to start due to iOS 15 "sequence-break" error, subsequent attempts to capture would result in the captured image not being set correctly.
This fixes a regression introduced in #5778 where the cookie value tracked by AcuantCapture falls out of date after Acuant handles the error, since we never refresh the value after it is [set internally by Acuant's error handling](https://github.com/Acuant/JavascriptWebSDKV11/blob/9a5387576a33710188501ad6233f986b1b6bb1cb/SimpleHTMLApp/webSdk/dist/AcuantCamera.js#L616). Thus, the next time the user clicks  "Take Photo", the [cookie value logic](https://github.com/18F/identity-idp/blob/eceea0f4df59cf3bb934b561e1d141edf1276174/app/javascript/packages/document-capture/components/acuant-capture.jsx#L400) …
=> Fix Acuant sequence-break error cookie sync issue

Makefile, Procfile, config/environments/development.rb, webpack.config.js
**Why**:
- To prevent caching in development with the Rails public file server
- To avoid writing webpack-dev-server URLs into the asset manifest when the app is requested across the network
- To automatically recompile JavaScript while running "make run-https"
Specifically, I've experienced some challenges following our [mobile device testing documentation](https://github.com/18F/identity-idp#testing-on-a-mobile-device-or-in-a-virtual-machine) since the changes introduced in #5746. While it would be possible to run `yarn webpack --watch` in a separate terminal process, it would be nice to streamline this. Additionally, without adjusted public file server headers, Safari caching is particularly aggressive, even when trying to reload without cache.
I had also experimented with letting the …
=> Improve "make run-https" asset workflow

config/application.yml.default
This is used to trigger users to accept the new rules of use. Relates to: https://github.com/18F/identity-site/pull/792
This is for LG-5520
=> Update rules_of_use_updated_at timestamp

app/views/reactivate_account/_modal.html.erb, app/views/session_timeout/_warning.html.erb, app/views/shared/_modal_layout.html.erb, app/views/shared/_personal_key_confirmation_modal.html.erb
This PR makes it so that text in the "Confirm personal key" dialog is announced by the screen reader. 
**Why**: So that a screen reader user can receive all instructions as well as have parity between experiences.
| Current state | Change after fix |
|---------------|------------------|
|![image](https://user-images.githubusercontent.com/17969963/148998142-54e15854-7d95-41b2-85f9-300a21da084e.png)| ![Screen Shot 2022-01-11 at 1 16 33 PM](https://user-images.githubusercontent.com/17969963/148998953-b0be6533-9f1b-42ea-932d-8695654f0bb1.png)|
Follow up work:
- Audit all custom dialog modals to make sure that text is read by screen readers.
- Ensure that **all** validation and error messages in modals are read by a screen reader once generated (work for the personal key dialog is captured in …
=> make text readable in personal key custom dialog

app/components/accordion_component.html.erb, app/components/accordion_component.rb, app/views/idv/review/new.html.erb, app/views/shared/_password_accordion.html.erb, app/views/sign_up/passwords/new.html.erb, spec/components/accordion_component_spec.rb
**Why**: As part of typographical refinement in LG-4792, accordions throughout the application should use a consistent vertical margin.
- This has been split as its own pull request, since it includes improvements to the `Accordion` component to improve support for custom classes, along with support for the borderless variant.
---|---|---
Update Password|![password-before](https://user-images.githubusercontent.com/1779930/149972830-0d6840ef-66a1-44ea-b99c-5748f642bb5f.png)|![password-after](https://user-images.githubusercontent.com/1779930/149972889-53ecb33c-c1f8-429b-a6d0-7795e61fa0a5.png)
IAL2 Review|![review-before](https://user-images.githubusercontent.com/1779930/149971386-6fa951a7-e0ec-41f2-84bb-6e82b475bc5f.png)|![review …
=> LG-4792: Use consistent Accordion spacing

app/services/idv/steps/doc_auth_base_step.rb, spec/features/idv/doc_auth/verify_step_spec.rb
I had used `self.class.class_name` which gives just the name of the class, without the prepended modules. Unfortunately, `class_name` is not defined on `Class` but is added in the `yard` gem which is only available in `development` and `test`. Thus it works locally, and passes CI, but does not actually work when deployed. 🤦‍♂️
=> LG-5222: follow on to fix error

app/services/secure_headers_allow_list.rb, spec/controllers/saml_idp_controller_spec.rb, spec/features/openid_connect/openid_connect_spec.rb, spec/services/secure_headers_allow_list_spec.rb
**Why**: Schemes are meant to be rendered with a colon and no slashes, e.g. `http:` instead of `http://`
=> Properly specify schemes in the CSP

app/controllers/saml_idp_controller.rb, app/services/saml_request_validator.rb, spec/controllers/saml_idp_controller_spec.rb, spec/services/saml_request_validator_spec.rb
**Why:** Because we want to ensure that partners won't run into issues
when we launch the IALMAX implementation using the Comparison attribute
of the RequestedAuthnContext element in the auth request (#5652). This will
allow us to analyze how partners are sending us their SAML requests and
can also be used for troubleshooting in the future.
=> Add additional metadata to SAML Auth event

config/initializers/secure_headers.rb
Re: https://github.com/18F/identity-idp/pull/5844#issuecomment-1020297806
The Rails mailer previews use inline CSS style, so we need to allow them in order to have previews work. Would be nice if we could scope these changes to certain URLs, but this works for now:
| --- | --- |
| <img width="590" alt="Screen Shot 2022-01-24 at 12 56 04 PM" src="https://user-images.githubusercontent.com/458784/150863624-a43085c6-b6e5-46da-9fa2-9696a724d941.png"> | <img width="590" alt="Screen Shot 2022-01-24 at 12 53 45 PM" src="https://user-images.githubusercontent.com/458784/150863654-1a052c42-04fd-460f-8736-7e075f1c4821.png"> |
| <img width="590" alt="Screen Shot 2022-01-24 at 12 56 14 PM" src="https://user-images.githubusercontent.com/458784/150863676-1e42dfbd-9625-4aef-9bc4-3fa028ef …
=> Fix CSP for Rails mailer previews

.rubocop.yml, app/jobs/reports/base_report.rb, app/services/doc_auth/error_generator.rb, app/views/idv/address/new.html.erb, app/views/shared/_dap_analytics.html.erb, app/views/users/edit_phone/edit.html.erb, spec/controllers/idv/doc_auth_controller_spec.rb, spec/controllers/idv/gpo_verify_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/forms/user_piv_cac_verification_form_spec.rb, spec/services/doc_auth/error_generator_spec.rb, spec/services/encrypted_redis_struct_storage_spec.rb, spec/views/idv/shared/_error.html.erb_spec.rb
**Why:** Because it's conventional already, it keeps our code consistent and readable, and it matches other similar rule configurations (`Layout/SpaceInsideBlockBraces`, `Layout/SpaceInsideParens`).
Docs: https://docs.rubocop.org/rubocop/cops_layout.html#layoutspaceinsidehashliteralbraces
=> Enable Rubocop Layout/SpaceInsideHashLiteralBraces

app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/components/_list.scss, app/assets/stylesheets/components/_loading.scss, app/assets/stylesheets/components/_modal.scss, app/assets/stylesheets/components/_personal-key.scss, app/assets/stylesheets/components/_profile-section.scss, app/assets/stylesheets/components/all.scss, app/assets/stylesheets/utilities/_space-misc.scss, app/assets/stylesheets/utilities/_util.scss
**Why**: Because they aren't referenced anywhere, they unnecessarily inflate the size of our (quite large) stylesheet.
=> Remove some unused styles

.circleci/config.yml, .gitattributes, .gitlab-ci.yml, CHANGELOG.md, scripts/changelog-check
This PR implements a check for pull requests against this repo that requires a line be added to CHANGELOG.md in the form of:
`+- CATEGORY: CHANGE_DESCRIPTION (#PULL_REQUEST_NUMBER)`
```diff
+-  Maintenance: Update Node.js to v14 (#5786)
```
It can be skipped with a commit message in the PR that contains `[skip changelog]`.
=> Require Changelog on Pull Requests (LG-5631)

Makefile, Procfile
Regression of #5835
**Why**: So that a developer can follow the instructions for accessing the IdP across a network as documented.
Documentation: https://github.com/18F/identity-idp#testing-on-a-mobile-device-or-in-a-virtual-machine
Observed by @peggles2 in Slack conversation: https://gsa-tts.slack.com/archives/C01710KMYUB/p1643133502021400?thread_ts=1643129805.019900&cid=C01710KMYUB
Issue is that #5835 uses a different environment variable for Foreman host binding, so that `run-https` target can specify a `ssl:` scheme host. This wasn't accounted for in the normal `make run` workflow, which was still expecting to be able to pass the `HOST` environment variable.
=> Fix HTTP host binding

.eslintignore
- When present, the coverage directory contains a 203kb minified JS file that
eslint gets sidetracked by
=> Ignore coverage directory when running eslint

CHANGELOG.md, app/views/users/delete/show.html.erb, config/locales/users/en.yml, config/locales/users/es.yml, config/locales/users/fr.yml, spec/views/users/delete/show.html.erb_spec.rb
**Why**: As a user, I want all information to be displayed in a clear visual hierarchy without visual design issues, so that I am not distracted while I am signing in or verifying my identity.
Before|After
---|---
=> LG-4792: Update "Delete Account" confirmation page layout

app/controllers/concerns/two_factor_authenticatable_methods.rb, app/presenters/idv/otp_verification_presenter.rb, app/presenters/two_factor_auth_code/phone_delivery_presenter.rb, app/views/idv/otp_verification/show.html.erb, app/views/two_factor_authentication/otp_verification/show.html.erb, config/locales/instructions/en.yml, config/locales/instructions/es.yml, config/locales/instructions/fr.yml, spec/presenters/two_factor_auth_code/phone_delivery_presenter_spec.rb, spec/views/two_factor_authentication/otp_verification/show.html.erb_spec.rb
**Why**: Typographical and margin improvements ahead of switch to Public Sans font. Also serves as a general simplification and avoids unnecessary HTML interpolation to locale strings.
---|---|---
Add Phone|![localhost_3000_login_two_factor_sms_otp_make_default_number=false reauthn=false (1)](https://user-images.githubusercontent.com/1779930/150863468-35616dd6-821d-4051-811c-65f410a832cd.png)|![localhost_3000_login_two_factor_sms_otp_make_default_number=false reauthn=false](https://user-images.githubusercontent.com/1779930/150863469-e88e7bc3-a1eb-437a-83cc-98d726cd0207.png)
IAL2 Phone|![localhost_3000_verify_phone_confirmation (1)](https://user-images.githubusercontent.com/1779930/150863470-08573f6b-8252-46ac-a843-7db90612f60b.png)|![localhost_3000_veri …
=> LG-4792: Split "Use another phone number" to newline

CHANGELOG.md, app/assets/stylesheets/_required.scss, app/assets/stylesheets/components/_external-link.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/variables/_vendor.scss, app/views/shared/_footer_lite.html.erb, package.json, yarn.lock
**Why**: To take advantage of the latest features and bug fixes, to eliminate backported styles, and as a prerequisite for implementing the new Process List component (LG-4791).
Release notes: https://github.com/18F/identity-style-guide/releases/tag/v6.3.0
=> Upgrade identity-style-guide to 6.3.0

app/view_models/account_show.rb, spec/view_models/account_show_spec.rb
The `#personal_key_generated_at` was raising a `NoMethodError` when the user did not have an active profile. This led to `verified_at` being called on `nil`. This commit adds safe navigation operator so the method is falsy when there is no verified_at date. This should be okay since the caller guards against nil in the template.
=> Fix a NoMethodError in the AccountShow view model

.erb-lint.yml, app/assets/stylesheets/utilities/_typography.scss, app/views/shared/_cancel.html.erb, app/views/shared/_fallback_links.html.erb, app/views/two_factor_authentication/webauthn_verification/show.html.erb, config/locales/forms/en.yml, config/locales/forms/es.yml, config/locales/forms/fr.yml
**Why**: In anticipation of upcoming font change to Public Sans, this pull request updates typography and layout of the webauthn MFA screen based on Figma guidance included in the associated ticket.
~_Draft while I confirm revisions to shared partials like "Fallback Links" and "Cancel" on other screens._~
State|Before|After
---|---|---
Initial|![Screen Shot 2022-01-21 at 4 08 59 PM](https://user-images.githubusercontent.com/1779930/150600560-41b02990-a815-42ac-a335-063347dc258b.png)|![image](https://user-images.githubusercontent.com/1779930/150601033-25abdc58-4bc1-4848-937d-f81e71f39536.png)
Authenticating|![Screen Shot 2022-01-21 at 4 09 05 PM](https://user-images.githubusercontent.com/1779930/150600567-f6408451-4e39-4527-8030-33a591150175.png)|![image](https://user-images.githubuserconte …
=> LG-4792: Update webauthn MFA screen layout

CHANGELOG.md, app/forms/idv/phone_form.rb, spec/controllers/idv/phone_controller_spec.rb
This adds the Pinpoint Phone Info call to the IdV OTP form. It will give us more context, but does not implement any change in behavior
=> call phone_info check on idv otp

app/views/idv/doc_auth/_start_over_or_cancel.html.erb
Regression introduced in: #5845
"Cancel" partial top margin was increased from `1rem` to `2rem` in #5845. This is correct, though had the unintended side-effect of creating a bigger-than-intended gap in the "Start over or cancel" partial.
Before|After
---|---
=> Fix IAL2 Start Over/Cancel visual margin regression

CHANGELOG.md, Gemfile, Gemfile.lock
The security patch we had in our fork was merged & released! https://github.com/roidrage/redis-session-store/pull/125
=> Switch back to mainline redis-session-store gem

CHANGELOG.md, Makefile, package.json, spec/javascripts/packages/document-capture/hooks/use-async-spec.jsx, svgo.config.js, yarn.lock
GitHub reminds me daily of our vulnerable JS packages (that are not vulnerabilities in the deployed environment as far as I understand them), so I wanted to fix them.
`svgo` was the most significant change with a major version upgrade that includes a new configuration format.
<details>
<summary>
Yarn Audit Before PR
</summary>
```
│ moderate      │  Inefficient Regular Expression Complexity in                │
│               │ chalk/ansi-regex                                             │
│ Package       │ ansi-regex                                                   │
├───────────────┼───────────────────────────────────────────── …
```
=> Update yarn dependencies to fix moderate JS vulnerabilities

CHANGELOG.md, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_personal-key.scss, app/assets/stylesheets/utilities/_typography.scss, app/assets/stylesheets/variables/_app.scss, app/views/accounts/_personal_key.html.erb, app/views/partials/personal_key/_key.html.erb, app/views/shared/_one_time_code_input.html.erb, app/views/shared/_personal_key_input.html.erb, app/views/test/piv_cac_authentication_test_subject/new.html.erb, app/views/users/piv_cac_authentication_setup/new.html.erb, app/views/users/piv_cac_setup_from_sign_in/prompt.html.erb, app/views/users/totp_setup/new.html.erb, app/views/users/webauthn_setup/new.html.erb
**Why**: As a user, I want to see a consistent font and brand across all login.gov sites, including the IdP, so that I can trust that this website is legitimate.
Before|After
---|---
=> LG-4795: Switch monospace font to design system default (Roboto Mono)

app/components/icon_component.rb, spec/components/icon_component_spec.rb
**Why**: Icon sprites consumed via SVG `<use>` [cannot reference cross-domain resources](https://oreillymedia.github.io/Using_SVG/extras/ch10-cors.html), so it must be served from the same host.
Related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1643749421139809
_Draft and configured to merge to `aduth-process-list` while testing._
=> Bypass asset_host configuration for icon sprite

CHANGELOG.md, app/services/secure_headers_allow_list.rb, spec/services/secure_headers_allow_list_spec.rb
**Why**: So that apps that use hash routing will have their redirect URIs properly reduced.
=> Strip the fragment from URIs

CHANGELOG.md, scripts/changelog-check
**Why**: So that developers are aware of this workaround.
=> Include skip trigger in CHANGELOG warning messge

app/assets/stylesheets/utilities/_typography.scss, app/views/accounts/_header.html.erb, app/views/reactivate_account/_modal.html.erb, app/views/reactivate_account/index.html.erb, app/views/session_timeout/_warning.html.erb
**Why**: So that we standardize on design system utilities and reduce references to hard-coded font stack variables.
I had hoped to get rid of these variables altogether, but based on how these are used in BassCSS and the load order of our CSS vendor assets, it doesn't seem viable for the short-term.
There are no visual changes expected from this refactor.
(Skipping changelog for now, will group together as part of overall Public Sans work of LG-4795 once it's ready)
=> LG-4795: Replace font-family classes using design system

CHANGELOG.md, app/controllers/concerns/two_factor_authenticatable_methods.rb, app/decorators/user_decorator.rb, app/forms/edit_phone_form.rb, app/models/phone_configuration.rb, app/presenters/two_factor_authentication/phone_selection_presenter.rb, app/views/users/edit_phone/edit.html.erb, spec/decorators/user_decorator_spec.rb, spec/features/phone/default_phone_selection_spec.rb, spec/features/sign_in/two_factor_options_spec.rb, spec/models/phone_configuration_spec.rb, spec/presenters/two_factor_authentication/phone_selection_presenter_spec.rb, spec/views/two_factor_authentication/otp_verification/show.html.erb_spec.rb
(broken out of https://github.com/18F/identity-idp/pull/5894)
- Method was defined 4 times before, now it's only defined once
- Updated it to leverage Phonelib for better grouping of digits
(improves support for international numbers, removes USA assumption)
The phone gem knows to add parens around US area codes, so we get a nice pretty change like this:
| --- | --- |
| <img width="621" alt="Screen Shot 2022-02-01 at 8 29 25 PM" src="https://user-images.githubusercontent.com/458784/152093341-08854872-f2a8-4329-a6ec-39d95c59cc56.png"> |  <img width="621" alt="Screen Shot 2022-02-01 at 8 29 03 PM" src="https://user-images.githubusercontent.com/458784/152093368-b7e54220-377f-48c2-91cc-3c19a64600da.png"> |
=> Update phone number masking

CHANGELOG.md, app/views/idv/doc_auth/_ssn_init.html.erb, app/views/idv/doc_auth/link_sent.html.erb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml
**Why**: As a user, I want all information to be displayed in a clear visual hierarchy without visual design issues, so that I am not distracted while I am signing in or verifying my identity.
This is a hodgepodge of miscellaneous fixes to various screens within the IAL2 flow as we wrap up this part of LG-4792.
---|---|---
**Welcome**<br>Revision: "Learn more" link icon placement<br>See: https://github.com/18F/identity-style-guide/pull/289|![Screen Shot 2022-02-01 at 8 33 55 AM](https://user-images.githubusercontent.com/1779930/151980458-f06afc98-db1b-43e9-b731-66b203365ce0.png)|![Screen Shot 2022-02-01 at 8 33 13 AM](https://user-images.githubusercontent.com/1779930/151980474-0635cfac-b4fb-4ef4-84b3-1e2921fc0cc1.png)
**Hybrid Send Link**<br>Revision: …
=> LG-4792: Update IAL2 layout, typography consistency

spec/requests/rack_attack_spec.rb
**Why**: Hopefully resolve intermittent failures.
Related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1643901241547609
=> Freeze time for throttling spec

config/application.yml.default
Previously we had been using this value to update the one in prod and sync with a deploy.
As of this today I've updated the value in prod's S3 config directly, so this note serves to remind our future selves that updates should go to S3 because it will override the ones here
=> Update rules of use timestamp with note

app/services/proofing/aamva/request/verification_request.rb
This line makes it look like we send the address to this vendor...but we do not
=> Remove no-op line in AAMVA verification request

CHANGELOG.md, app/assets/stylesheets/utilities/_space-misc.scss, app/views/shared/_email_languages.html.erb, app/views/sign_up/registrations/new.html.erb
**Why**: As a user, I want all information to be displayed in a clear visual hierarchy without visual design issues, so that I am not distracted while I am signing in or verifying my identity.
State|Device|Before|After
---|---|---|---
Default|Desktop|![localhost_3000_sign_up_enter_email (3)](https://user-images.githubusercontent.com/1779930/152366091-5866ea97-a3cb-4488-9d5c-bc779685a7d1.png)|![localhost_3000_sign_up_enter_email (5)](https://user-images.githubusercontent.com/1779930/152367323-87f5a43a-6b61-4746-892a-4b6f7a469c3e.png)
Long Text|Desktop|![localhost_3000_sign_up_enter_email (2)](https://user-images.githubusercontent.com/1779930/152366088-0cf4d8a7-266e-453e-9b26-8156d8d1adea.png)|![localhost_3000_sign_up_enter_email (1)](https://user-images.githubusercontent.com/1779930/1523660 …
=> LG-4792: Revise email languages layout to avoid text wrapping

CHANGELOG.md, app/assets/stylesheets/components/_list.scss, app/assets/stylesheets/components/all.scss, app/assets/stylesheets/utilities/_space-misc.scss, app/assets/stylesheets/utilities/_typography.scss, app/components/process_list_component.html.erb, app/components/process_list_component.rb, app/components/process_list_item_component.html.erb, app/views/idv/doc_auth/welcome.html.erb, app/views/shared/_one_time_code_input.html.erb, app/views/test/piv_cac_authentication_test_subject/new.html.erb, app/views/users/piv_cac_authentication_setup/new.html.erb, app/views/users/totp_setup/new.html.erb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, spec/components/process_list_component_spec.rb, spec/support/capybara.rb, spec/views/users/totp_setup/new.html.erb_spec.rb
**Why**: As a user, I want to see the steps of instructions or processes presented in a consistent visual way, so that I clearly understand what I need to do next and am not distracted by visual issues.
Component reference: https://design.login.gov/components/process-list/
For review, split diff may be easiest: [?diff=split](https://github.com/18F/identity-idp/pull/5863/files?diff=split&w=0)
---|---|---
TOTP Setup|![localhost_3000_authenticator_setup (1)](https://user-images.githubusercontent.com/1779930/151558805-bd2c2b98-f87a-4228-aff7-e45923bb72f7.png)|![localhost_3000_authenticator_setup](https://user-images.githubusercontent.com/1779930/151558807-2bcab077-5754-4988-a447-7cd27f993139.png)
PIV Setup|![localhost_3000_piv_cac …
=> LG-4791: Add and use Process List component

app/assets/stylesheets/components/_icon.scss, app/components/button_component.html.erb, app/components/button_component.rb, app/components/clipboard_button_component.rb, app/views/accounts/_emails.html.erb, app/views/accounts/_phone.html.erb, app/views/idv/otp_verification/show.html.erb, app/views/shared/_personal_key.html.erb, app/views/two_factor_authentication/otp_verification/show.html.erb, app/views/users/backup_code_setup/create.html.erb, spec/components/button_component_spec.rb, spec/components/clipboard_button_component_spec.rb, spec/features/multiple_emails/add_email_spec.rb, spec/features/phone/add_phone_spec.rb
**Why**: So that we're consistently using icons in buttons, and toward an eventual removal of the `prefix_with_plus` helper.
Also fixes an issue where `type` attribute was being wrongly assigned to link implementations of these icon buttons.
Before|After
---|---
=> Use ButtonComponent for new account actions

lib/tasks/users_lookup.rake
Follow-up to https://github.com/18F/identity-idp/pull/5822 -- this is so that email addresses won't show up in the CloudWatch SSM logs.
Tested in my sandbox `idp` (hard to show, since it's obscured, but 🤷‍♂️):
Valid email:
```
$ sudo -H -u websrv env "app=idp" sh -euxc "cd '/srv/idp/current'; bundle exec rails users:lookup_by_email"
+ cd /srv/idp/current
+ bundle exec rails users:lookup_by_email
Enter the email address to look up:
uuid: <REDACTED>
```
Invalid email:
```
$ sudo -H -u websrv env "app=idp" sh -euxc "cd '/srv/idp/current'; bundle exec rails users:lookup_by_email"
+ cd /srv/idp/current
+ bundle exec rails users:lookup_by_email
Enter the email address to look up:
No user found
```
=> hide STDIN for users:lookup_by_email with io/console

app/views/shared/_troubleshooting_options.html.erb, app/views/two_factor_authentication/sms_opt_in/error.html.erb, lib/telephony/pinpoint/sms_sender.rb, spec/lib/telephony/pinpoint/sms_sender_spec.rb, spec/views/two_factor_authentication/sms_opt_in/error.html.erb_spec.rb
Some follow-ups to #5894 based on testing we did today
- Update links to help at SP to be external (give them the little ➡️ and open in new tab)
- Update SmsSender to fail faster (don't retry OPT_OUT errors across regions)
=> SMS opt-in fixes

app/views/idv/cancel.html.erb, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml
**Why**: Because it's unused since the route was removed in #2341.
=> Remove unused IdV cancel view

app/views/devise/passwords/new.html.erb, app/views/idv/activated.html.erb, app/views/idv/gpo_verify/index.html.erb, app/views/mfa_confirmation/new.html.erb, app/views/test/piv_cac_authentication_test_subject/new.html.erb, app/views/two_factor_authentication/backup_code_verification/show.html.erb, app/views/two_factor_authentication/personal_key_verification/show.html.erb, app/views/two_factor_authentication/piv_cac_verification/show.html.erb, app/views/users/backup_code_setup/index.html.erb, app/views/users/passwords/edit.html.erb, app/views/users/two_factor_authentication_setup/index.html.erb, app/views/users/webauthn_setup/new.html.erb
**Why**: To simplify markup, and toward removal of non-standard utility classes like `mt-tiny`.
These classes are unnecessary/redundant due to how [margin collapse](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing) will behave in these contexts.
- A `p.mt-tiny` preceded by `PageHeadingComponent` would always have 1rem margin between, from [the heading's bottom margin](https://github.com/18F/identity-idp/blob/69e9db5d4a683a38456ce4455fa0dd4d07109a18/app/assets/stylesheets/components/_page-heading.scss#L3)
- A `p.margin-bottom-0` or `p.margin-bottom-4` followed by a `simple_form_for` or `validated_form_for` would always have 2rem margin between, from [the configured SimpleForm default top margin](https://github.com/18F/identity-idp/blob/69e9db5d4a683 …
=> Remove safe collapsed margins

app/views/accounts/_mobile_nav.html.erb, app/views/accounts/_side_nav.html.erb, app/views/shared/_banner-lock-icon.html.erb, app/views/shared/_banner.html.erb, config/locales/account/en.yml, config/locales/account/es.yml, config/locales/account/fr.yml, config/locales/shared/en.yml, config/locales/shared/es.yml, config/locales/shared/fr.yml
**Why**: So that a user navigating the site in a language other than English can read the content in their preferred language.
Tangentially related to #5930, #5926.
Also improves labeling for overlapping landmark types, toward [ARIA11](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA11):
>There are cases when a particular landmark role could be used more than once on a page, such as on primary and secondary navigation menus. In these cases, identical roles should be disambiguated from each other using a valid technique for labelling region
=> Add translations for hard-coded English labels

spec/lib/telephony/test/sms_sender_spec.rb
**Why**: Because it was likely for local debugging and not intended to be committed, since it will output during the spec run.
=> Remove debugging code from SMS spec

app/assets/stylesheets/components/_modal.scss, app/javascript/app/components/modal.js, app/views/shared/_modal_layout.html.erb, spec/javascripts/app/components/modal-spec.js
**Why**:
- For consistency of backdrop overlay styling
- As an incremental step toward replacing ad hoc modal implementation with [equivalent design system component](https://designsystem.digital.gov/components/modal/)
- To reduce the size of our stylesheet bundle, for faster end-user page load experience
- To fix a markup error with stray `</div>` in `app/views/shared/_modal_layout.html.erb`
Eventually, we should aim to customize this component to use it as provided by the design system. This pull request is aimed only at the overlay, and includes necessary styles to match the overlay shown when mobile side navigation is visible. 
Behavior|Before|After
---|---|---
Mobile navigation|![Screen Shot 2022-02-10 at 9 05 08 …
=> Adopt design system overlay backdrop styles for modal

.erb-lint.yml, app/assets/stylesheets/_vendor.scss, app/assets/stylesheets/components/_nav.scss, app/assets/stylesheets/components/_password.scss, app/assets/stylesheets/variables/_vendor.scss, app/views/accounts/_nav_auth.html.erb, app/views/accounts/_personal_key.html.erb, app/views/devise/sessions/_return_to_service_provider.html.erb, app/views/idv/come_back_later/show.html.erb, app/views/idv/doc_auth/upload.html.erb, app/views/idv/gpo_verify/index.html.erb, app/views/idv/otp_verification/show.html.erb, app/views/layouts/base.html.erb, app/views/reactivate_account/_modal.html.erb, app/views/session_timeout/_warning.html.erb, app/views/shared/_banner.html.erb, app/views/shared/_footer_lite.html.erb, app/views/shared/_nav_branded.html.erb, app/views/shared/_nav_lite.html.erb, app/views/shared/_personal_key_confirmation_modal.html.erb, app/views/test/piv_cac_authentication_test_subject/new.html.erb, app/views/two_factor_authentication/otp_verification/show.html.erb, app/views/two_factor_authentication/totp_verification/show.html.erb, app/views/users/backup_code_setup/create.html.erb, app/views/users/emails/verify.html.erb, app/views/users/piv_cac_setup_from_sign_in/prompt.html.erb, app/views/users/verify_personal_key/new.html.erb, app/views/users/webauthn_setup/new.html.erb, config/initializers/simple_form.rb, spec/views/layouts/application.html.erb_spec.rb
**Why**: As a user, I expect that login.gov has a consistent visual style, and that my page load times are not prolonged by loading redundant CSS. As a developer, I expect that existing references to BassCSS module classes are replaced with equivalent USWDS or ad hoc alternatives, so that we can successfully migrate away from and eliminate our dependency on BassCSS.
Styles being removed: https://github.com/basscss/basscss-sass/blob/v3.0.0/_utility-layout.scss
=> LG-3879: Remove BassCSS layout utilities

app/assets/stylesheets/_vendor.scss
**Why:** As a user, I expect that login.gov has a consistent visual style, and that my page load times are not prolonged by loading redundant CSS. As a developer, I expect that existing references to BassCSS module classes are replaced with equivalent USWDS or ad hoc alternatives, so that we can successfully migrate away from and eliminate our dependency on BassCSS.
Styles being removed: https://github.com/basscss/basscss-sass/blob/v3.0.0/_default.scss
All of the variables defined in the `defaults` module of BassCSS have been copied/redefined in the idp stylesheets, namely `variables/_app.scss` and `variables/_colors.scss`. We can simply delete the inclusion of the BassCSS module.
=> LG-3870: remove BassCSS Module "defaults"

app/views/users/backup_code_setup/confirm_delete.html.erb, app/views/users/backup_code_setup/edit.html.erb, app/views/users/piv_cac_setup/confirm_delete.html.erb, app/views/users/totp_setup/confirm_delete.html.erb, app/views/users/webauthn_setup/delete.html.erb
**Why**:
- For consistency across warning page layouts, where revised designs (notably IAL2) do not use this layout element
- For LG-3879, remove instances of BassCSS grid classes
- Improve markup semantics (avoid `br`, use `p` in place of `div` for content).
Additional context in Slack: https://gsa-tts.slack.com/archives/CNCGEHG1G/p1644852033522339
---|---|---
Backup Codes Delete|![hr-backup-code-delete-before](https://user-images.githubusercontent.com/1779930/153910524-162f314d-c802-47cb-aa2e-d42b665299b7.png)|![hr-backup-code-delete-after](https://user-images.githubusercontent.com/1779930/153910522-9dea94c3-0ae4-424c-baeb-47535362bc7a.png)
Backup Codes Renegerate|![hr-backup-code-new-before](https://user-images.githubusercontent.com/1779930/153910525 …
=> Remove yellow border from warning page layouts

app/assets/stylesheets/components/_modal.scss, app/views/shared/_modal_layout.html.erb, spec/javascripts/app/components/modal-spec.js
Fixes regression of: #5928 (not yet live in production)
Related discussion: https://github.com/18F/identity-idp/pull/5947#discussion_r806210414
**Why**: To fix an issue where body content which is styled with a (small) z-index can appear above the modal, and so that the markup of  the modal follows design system guidance.
Before|After
---|---
=> Add design system overlay wrapper

app/forms/register_user_email_form.rb, spec/forms/register_user_email_form_spec.rb
Currently, we do not validate the email language, but the database has a limited size of varchar(10), and invalid submissions longer than that cause a 500
We do validate similarly in https://github.com/18F/identity-idp/blob/9b87bd75f30b72249057f59de901b4241dd365cb/app/forms/update_email_language_form.rb#L6, so this is mostly copied from there
=> Validate Email Language on Registration

.circleci/config.yml, scripts/changelog-check
This PR implements a proposal to require a commit in a PR to contain a line in the form of:
```
changelog: CATEGORY, SUBCATEGORY, CHANGE_DESCRIPTION
```
example:
```
changelog: Improvements, Authentication, Updating Authentication (LG-9998)
```
As before, the check can be skipped by including `[skip changelog]` in the commit message.
A set of release notes can be generated by calling the script with different base and source branches, say for a production release candidate:
```
./scripts/changelog-check -b stages/prod -s stages/rc-2022-02-07
```
I made up some fake commits on this branch that I'll squash/rebase later to simulate generating release notes from a branch:
```
- Logging: Add logging for identities ([#9001](https://github.com/18F/identity-idp/pull/9001), …
```
=> Commit-based release notes

scripts/changelog-check
**Why**: So that I, as a developer, am aware of the categories I'm expected to use.
Output:
```
A valid changelog line was not found.
A commit message should contain a line in the form of:
changelog: CATEGORY, SUBCATEGORY, CHANGE_DESCRIPTION
example:
changelog: Improvements, Authentication, Updating Authentication (LG-9998)
categories:
- Improvements
- Accessibility
- Bug Fixes
- Internal
Include "[skip changelog]" in a commit message to bypass this check.
```
=> List available categories in changelog help

config/initializers/secure_headers.rb, spec/requests/headers_spec.rb
The bulk of this PR is setting up regression specs so we can remove SecureHeaders gem confidently
- The configs: https://github.com/18F/identity-idp/blob/27742c514ce4c06939195445e56b00fa1f7ce881/config/initializers/secure_headers.rb#L4-L9
- Looks like most of our desired headers match with the defaults for Rails: https://edgeguides.rubyonrails.org/configuring.html#config-action-dispatch-default-headers
The way SecureHeaders is implemented, it stomps on the `default_headers` config very late in the game: https://github.com/github/secure_headers/blob/ce2ad139646f9775061159fe5c4707638fbe45c1/lib/secure_headers/railtie.rb#L21-L31
so the only way to test this code was to comment out/remove secure_headers gem entirely and make sure the specs worked as expected
This does mean that this test …
=> Add config to use Rails for secure headers options (LG-5771)

app/javascript/app/pw-toggle.js
**Why**: So that the password toggle appears within its intended container.
Fixes regression of #5930, where "relative" class was removed. There are two separate checks for the `relative` deprecated class: one applying to ERBLint and the one that checks for the existence of a deprecated class in a monkey-patched Rails tag builder. Neither of these would have discovered this instance of the class name, since it is applied dynamically through JavaScript at runtime.
Before|After
---|---
=> Fix password toggle positioning

app/presenters/two_factor_authentication/phone_selection_presenter.rb, app/presenters/two_factor_authentication/selection_presenter.rb, app/views/idv/otp_delivery_method/new.html.erb, config/locales/two_factor_authentication/en.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml, spec/features/two_factor_authentication/backup_code_sign_up_spec.rb, spec/presenters/two_factor_authentication/phone_selection_presenter_spec.rb
Follow-up to: https://github.com/18F/identity-idp/pull/5937#discussion_r805006993
**Why**: To limit HTML unescaping of strings to only those which require it, and as a clean-up task to #5706, where previously these strings needed to be named consistently due to being referenced using string interpolation.
=> Remove unnecessary MFA "_html" unescape suffixes

.rubocop.yml, spec/forms/register_user_email_form_spec.rb
**Why**: So that our code is linted as we expect it to be.
`Include` overrides the default, meaning it _only_ scans for the specified files.
Before|After
---|---
<code>Inspecting 5 files</code>|<code>Inspecting 1733 files</code>
Example: https://app.circleci.com/pipelines/github/18F/identity-idp/70138/workflows/b8b5a0dd-4597-47c0-95b6-6e947827c2bf/jobs/110926
The `.rake` file is scanned with the default configuration ([source](https://github.com/rubocop/rubocop/blob/9f82e0fb2a581283e588a7161839a10c77a2509c/config/default.yml#L27)), confirmed locally with artificial errors.
=> Fix Rubocop to inspect all files

app/views/sign_up/completions/show.html.erb
**Why**: To simplify markup and to standardize on design system utilities.
**Visual change:** Previously, the page was constrained to be centered 10 column (of 12) on mobile. It's not clear to me what's unique about this page to justify deviating from standard mobile content padding, so I'm proposing to remove this grid. Thoughts, @anniehirshman-gsa ?
**Review notes:** Change is much more trivial than it appears when [hiding whitespace](https://github.com/18F/identity-idp/pull/5957/files?&w=1), as it's simply removing the grid wrapper element.
Size|Before|After
---|---|--
Desktop|![grid-completion-desktop-before](https://user-images.githubusercontent.com/1779930/154287041-e70a8cc2-0e9e-4781-8dfd-5c3e823cfe8f.png)|![grid-completion-desktop-after](https://user-images.githubu …
=> LG-3879: Use design system grid for completion screen

app/presenters/account_show_presenter.rb, app/views/accounts/_badges.html.erb, app/views/accounts/_header.html.erb, app/views/accounts/show.html.erb
Partly a regression of #5900
This fixes a handful of issues related to how the account header is shown:
- Removes empty space for identity-verified accounts, since previously `showing_any_partials?` would account for `show_pii_partial?` despite the fact this is not rendered in the account header
- Restores extra spacing on mobile for "Welcome" message when badge is visible, regressed in #5900
- This time, however, the extra spacing is **only** added when badges are visible. Previously, it was always shown.
- Reduces margin between account header and the subsequent page heading, from 4rem to 2rem.
_Desktop:_
State|Before|After
---|---|---
Verified|![localhost_3000_account (2)](https://user-images.githubusercontent.com/1779930/154120943-7bd72143-9798-4f96-92c7-c3b5b855e268.p …
=> Fix account header spacing when badges present

app/views/sign_up/registrations/_required_pii_accordion.html.erb
**Why**: To simplify markup and to standardize on design system utilities.
Visually, should be mostly identical, with the exception that previous artificial column constraints no longer apply, so the image is slightly scaled up to its natural size. Vertical offset of images are also improved.
May be easier to review with whitespace hidden: [`?w=1`](https://github.com/18F/identity-idp/pull/5956/files?w=1)
Before|After
---|---
=> LG-3879: Use design system grid for PII accordion

app/views/accounts/_personal_key_item_heading.html.erb
**Why**: Because it's unused, and because continuing to maintain it would cause additional work for LG-3879 to migrate non-standard CSS classes.
While I was here, i also checked to confirm that [all other partials in `app/views/accounts`](https://github.com/18F/identity-idp/tree/main/app/views/accounts) remain in use.
Last referenced in #4169.
=> Remove unused account personal key partial

spec/controllers/two_factor_authentication/sms_opt_in_controller_spec.rb
- PhoneFormatter adds a default country vs #formatted_phone which does not
See: https://github.com/18F/identity-idp/pull/5939#discussion_r809221076
=> Fix flaky specs around phone formatting

scripts/changelog-check
https://stackoverflow.com/questions/7251477/what-are-the-differences-between-double-dot-and-triple-dot-in-git-dif shows the difference between `..` and `...`
`...` includes the commits on `main` that are not yet on `feature-branch`, and since the changelog is only interested in including changes on the current branch regardless common ancestor commit is, it seems like `..` is more appropriate, otherwise we may be checking the wrong commits.
Example of this bug in the wild: https://app.circleci.com/pipelines/github/18F/identity-idp/70199/workflows/05c4446a-b92d-47d7-9442-0282589beaad/jobs/111262
=> Use correct git range operator for changelog

app/assets/stylesheets/utilities/_typography.scss, app/assets/stylesheets/utilities/_util.scss, app/assets/stylesheets/variables/_app.scss, app/views/accounts/_connected_app.html.erb, app/views/idv/doc_auth/upload.html.erb, app/views/idv/gpo/_new_address.html.erb, app/views/password_capture/new.html.erb, app/views/reactivate_account/index.html.erb, app/views/saml_idp/shared/saml_post_binding.html.erb, app/views/saml_post/auth.html.erb, app/views/shared/_personal_key_confirmation_modal.html.erb, app/views/shared/_personal_key_input.html.erb, app/views/test/saml_test/decode_response.html.erb, app/views/two_factor_authentication/webauthn_verification/show.html.erb, app/views/users/edit_phone/_remove_phone.html.erb, spec/features/account_connected_apps_spec.rb
**Why**: To simplify markup and to standardize on design system utilities.
Doesn't yet remove / deprecate styles, since there are still lingering classes to be resolved with #5962 and #5953.
**Expected visual changes (cc @anniehirshman-gsa):**
- Text can expand to fill more of the available space on desktop. 
Size|Before|After
---|---|---
Desktop|![grid-connected-desktop-before](https://user-images.githubusercontent.com/1779930/154519599-08f527fc-2ee6-4852-bf7b-37436ee296ea.png)|![grid-connected-desktop-after](https://user-images.githubusercontent.com/1779930/154519594-e2f80dc9-e282-446a-8185-2031cddb8fc1.png)
Mobile|![grid-connected-mobile-before](https://user-images.githubusercontent.com/1779930/154519603-dc17527a-5c0c-441b-8ded-d9e3bb1bda7b.png)|![grid-connected-mobile-after](https://us …
=> LG-3879: Use design system grid in place of BassCSS grid

spec/features/webauthn/sign_in_spec.rb
A test failed on main yesterday due to a non-unique email in a test that should only be creating one user
https://app.circleci.com/pipelines/github/18F/identity-idp/70205/workflows/52775fc0-fa6c-42ae-a86f-635e39cc7c94/jobs/111293/parallel-runs/1?filterBy=FAILED
`create(:webauthn_configuration)` creates an associated user by default, and we then were creating another user and re-associating the webauthn configuration. This PR reorders that so only one user is created. Two users being created with the same email address should be very rare, so I'm surprised it happened.
=> Fix flaky test

spec/controllers/two_factor_authentication/sms_opt_in_controller_spec.rb, spec/requests/rack_attack_spec.rb
Naturally the main branch test failed with a flaky test after I merged #5970 https://app.circleci.com/pipelines/github/18F/identity-idp/70230/workflows/c912e280-b664-4b11-9c7d-50c55dc86ad6/jobs/111420/parallel-runs/4?filterBy=FAILED
This PR fixes a handful more of the flaky tests
The phone test had a fix applied in #5966, but there seems to be an inconsistency in how the phones get formatted?
I got a failure with:
```
assigns an in-memory phone configuration (FAILED - 1)
Failures:
1) TwoFactorAuthentication::SmsOptInController#new when loaded while adding a new phone assigns an in-memory phone configuration
Failure/Error:
expect(PhoneFormatter.format(assigns[:phone_configuration].phone)).
to eq(PhoneFormatter.format(phone))
expected: "+14590108499"
got: "+45 90 10 84 99"
```
the variables …
=> Fix more flaky tests

Gemfile, Gemfile.lock
```
Name: nokogiri
Version: 1.12.5
CVE: CVE-2021-30560
GHSA: GHSA-fq42-c5rg-92c2
Criticality: High
URL: https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-fq42-c5rg-92c2
Title: Update packaged libxml2 (2.9.12 → 2.9.13) and libxslt (1.1.34 → 1.1.35)
Solution: upgrade to >= 1.13.2
```
=> Update Nokogiri to patch vulnerability

Gemfile.lock
Mostly because https://github.com/podigee/device_detector/pull/84 was merged and significantly reduces the size of the gem
from 870400 bytes to 251392 bytes
=> Update device_detector gem

Gemfile, Gemfile.lock, spec/support/capybara.rb
**Why**: No longer used as of c2e39bf7a26, removing dependencies we no longer need
changelog: Internal, Dependencies, Remove unused dependencies
=> Remove capybara-screenshot gem

app/assets/stylesheets/components/_profile-section.scss, app/assets/stylesheets/utilities/_background.scss, app/assets/stylesheets/variables/_colors.scss, app/views/accounts/_header.html.erb, app/views/accounts/_pii.html.erb, app/views/layouts/application.html.erb, app/views/layouts/base.html.erb, app/views/shared/_footer_lite.html.erb
**Why**:
- Avoid duplicate styles
- Use only standard colors, by token name
- Conform to naming conventions for responsive variations (`tablet:`, not `sm-`)
There is not expected to be any visual changes here, with one exception: since the previous `bg-gray-lighter` was using a non-standard color (`#fafafa`), it was replaced with the closest equivalent value `base-lightest` (`#f0f0f0`), affecting one instance of PII "locked" messaging. (FYSA @anniehirshman-gsa @nickttng)
Before|After
---|---
=> Migrate background styles to design system

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_password.scss, app/assets/stylesheets/utilities/_space-misc.scss, app/assets/stylesheets/variables/_app.scss, app/views/devise/shared/_password_strength.html.erb, app/views/forgot_password/show.html.erb, app/views/shared/_footer_lite.html.erb, app/views/sign_up/emails/show.html.erb
**Why**:
- Remove duplicate styles
- Use only standard sizes, by unit
- Avoid pixel-based sizing, leverage rem-based instead
There should not be any visual changes with these revisions.
Additional context for review:
- In the design system, `1 unit` = `0.5rem`
- In the design system, half-units are reflected in utility classes with `05` suffix
- e.g. `margin-105` = `margin: units(1.5)` = `margin: 0.75rem;`
- The previous "tiny" size was `0.25rem`, which is equivalent to 0.5 units in the design system
- Unlike other "`$space-`" variables which are inherited from BassCSS, `$space-tiny` is custom to the IdP
- `1rem` = `16px`
=> Migrate spacing styles to design system

app/assets/stylesheets/_vendor.scss
**Why**: Because these styles were deprecated and removed as of #4650 (LG-3864), but the import remained.
=> Remove BassCSS white-space stylesheet import

lib/telephony/pinpoint/aws_credential_builder.rb
https://one.newrelic.com/nr1-core/errors-ui/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=86400000&state=ea97169c-da9c-9dcd-7f13-0c371551c819
https://one.newrelic.com/nr1-core/errors-ui/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=86400000&state=e313d64e-a16c-cf22-d7ff-c1ccb20d0836
From [this issue](https://github.com/aws/aws-sdk-ruby/issues/1301#issuecomment-261117898):
>Commonly this is caused by the aggressive defaults in attempting to load credentials from the instance metadata service. Once credentials expire, they must be refreshed, but if the metadata service fails to respond, a missing credentials error is raised. I've just push a small change that will go out with the next release where you can configure expanded …
=> Fix 500 error when sending phone OTP

app/controllers/concerns/saml_idp_logout_concern.rb, app/services/out_of_band_session_accessor.rb, app/services/pii/session_store.rb, spec/controllers/saml_idp_controller_spec.rb, spec/services/out_of_band_session_accessor_spec.rb
**Why:** the way this currently worked led to the user's session being
cleared on subsequent visits, which meant that any authentication
request information was lost. This correctly deletes the session from
the Redis cache.
=> Correctly invalidate session for SAML Remote Logout

Makefile, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/design-system-waiting-room.scss, package.json
**Why**: The way that we are passing paths using globstars does not behave the same in CircleCI as it does locally, likely due to differences in shell / shell options. This results in some files (at least those in the root `stylesheets/` directory) not being linted.
~Draft while initial commit verifies that errors are found.~
=> Fix Stylelint enforcement consistency

app/javascript/packages/build-sass/cli.js
**Why**: So that the build does not pass if Sass cannot be compiled (e.g. syntax error).
Discovered in pairing with @solipet . Regression of #5915.
=> Produce non-0 exit code on Sass build failure

app/jobs/phone_number_opt_out_sync_job.rb, lib/telephony/pinpoint/opt_out_manager.rb, spec/lib/telephony/pinpoint/opt_out_manager_spec.rb
**Why**: This is just syntax sugar, but it's easier to work with
when testing in the rails console (no need for a block)
```ruby
numbers = []; opt_out_manager.each_opted_out_number { |n| numbers << n }; numbers
=> ['+12345']
opt_out_manager.opted_out_numbers.to_a
=> ['+12345']
```
=> Clean up opted out phone number iteration

app/forms/idv/doc_pii_form.rb, app/services/doc_auth/mock/result_response_builder.rb, spec/forms/idv/doc_pii_form_spec.rb, spec/services/doc_auth/mock/result_response_builder_spec.rb
There is an issue in sandbox environments where we accept YAML files, which can parse to return integers where we expect strings [New Relic error](https://onenr.io/0dBj3g4axjX)
We perform some string operations on zipcode later in the login process when passing the PII bundle [here](https://github.com/18F/identity-idp/blob/da8dde0718594a92f1b6be3195a7e4c9d01ba3ac/app/presenters/openid_connect_user_info_presenter.rb#L100) or [here](https://github.com/18F/identity-idp/blob/da8dde0718594a92f1b6be3195a7e4c9d01ba3ac/app/services/attribute_asserter.rb#L98) so we should ensure that it is a String
=> Validate zipcode is a string in PII bundle

app/controllers/application_controller.rb, app/controllers/concerns/personal_key_concern.rb, app/controllers/two_factor_authentication/webauthn_verification_controller.rb, app/controllers/users/sessions_controller.rb, app/controllers/users/webauthn_setup_controller.rb, config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml, spec/controllers/accounts/personal_keys_controller_spec.rb, spec/controllers/application_controller_spec.rb, spec/controllers/users/personal_keys_controller_spec.rb, spec/controllers/users/sessions_controller_spec.rb, spec/controllers/users/webauthn_setup_controller_spec.rb, spec/features/users/sign_in_spec.rb, spec/features/webauthn/sign_in_spec.rb, spec/requests/i18n_spec.rb
[New Relic Error](https://one.newrelic.com/nr1-core/errors-ui/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=259200000&state=11ba84d7-9a2e-2404-5540-553bcc32fc61)
This fixes a 500 where the webauthn configuration queried from the database is `nil`
I also renamed the "invalid_authenticity_token" error message to `general` to reflect its more general usage
=> Fix 500 on prompting deletion of invalid webauthn configuration

app/assets/stylesheets/components/_nav.scss, app/views/accounts/_nav_auth.html.erb, app/views/events/show.html.erb, app/views/layouts/account_side_nav.html.erb, app/views/shared/_banner.html.erb, config/locales/shared/en.yml, config/locales/shared/es.yml, config/locales/shared/fr.yml, spec/views/layouts/application.html.erb_spec.rb
**Why**: So that Login.gov looks good in all browsers (even the buggy, outdated ones).
Related: https://github.com/philipwalton/flexbugs#flexbug-3
These were [previously set to explicit heights](https://github.com/18F/identity-idp/blob/101e9b75fa78d883c9b4aac61ac6c1084b2b5688/app/assets/stylesheets/components/_nav.scss#L1-L31), updated in #5926 with the intention of improving flexibility of the container. But it shouldn't be strictly necessary to allow the containers to grow in height.
Before|After
---|---
=> Fix vertical centering of logo in Internet Explorer

app/services/db/deleted_user/create.rb, spec/services/account_reset/delete_account_spec.rb, spec/services/db/deleted_user/create_spec.rb
We see uncommon transaction errors around account deletion in NewRelic in a couple different ways ([here](https://onenr.io/0EPwJ422Dj7) and [here](https://onenr.io/0VKQXqPPawa)) which can cause 500 errors when resetting an account or deleting an account while authenticated.
We have a test intended to catch this case [here](https://github.com/18F/identity-idp/blob/886e98db6d3a81d3804963d9d039cb768675ab96/spec/services/db/deleted_user/create_spec.rb#L20-L25), but according to the [ActiveRecord docs](https://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html#module-ActiveRecord::Transactions::ClassMethods-label-Nested+transactions) trying to rescue while executing in a database transaction requires a separate savepoint and re-raising to rollback.
This PR adds failing …
=> Fix 500 from database error while deleting account

app/javascript/app/utils/auto-logout.js, app/javascript/app/utils/index.js, app/javascript/packs/session-timeout-ping.ts, webpack.config.js
**Why**:
- Avoid window globals
- Reduce size and scope of critical-path application pack
- Limit indirection
=> Absorb autoLogout into session timeout pack

app/javascript/app/pw-toggle.js, app/javascript/app/utils/ms-formatter.js, app/javascript/packages/i18n/index.ts, app/javascript/packages/rails-i18n-webpack-plugin/extract-keys-webpack-plugin.js, app/javascript/packages/rails-i18n-webpack-plugin/rails-i18n-webpack-plugin.spec.js, app/javascript/packages/rails-i18n-webpack-plugin/spec/fixtures/common.js, app/javascript/packs/application.js, app/javascript/packs/document-capture.jsx, app/javascript/packs/form-validation.js, app/javascript/packs/otp-delivery-preference.js, app/javascript/packs/pw-strength.js, app/javascript/packs/ssn-field.js, spec/javascripts/app/utils/countdown-timer_spec.js, spec/javascripts/app/utils/ms-formatter_spec.js, spec/javascripts/packs/form-validation-spec.js, spec/javascripts/packs/pw-strength-spec.js, spec/javascripts/spec_helper.js
**Why**:
- Standardize package as interface for translations
- Avoid global variables, because:
- They create a fragile order of dependencies
- It creates interoperability challenges with TypeScript types
- It is cumbersome to mock in specs
The main challenge with implementing this 'til now is that our Webpack plugin for extracting translation keys has been incompatible with how Webpack transforms calls to imported functions, e.g.
```js
(0,_18f_identity_i18n__WEBPACK_IMPORTED_MODULE_0__.t)('forms.button.cancel');
```
Our key extraction is rather naive and looks for a simple pattern of `t('string')`, thus failing to find this. While a more robust implementation would operate on either the original source code or an AST representation, initial attempts to do so were unsuccessful. Instead, …
=> Remove i18n window global in favor of i18n package

Gemfile, Gemfile.lock, app/views/layouts/component_preview.html.erb, config/application.yml.default, config/environments/development.rb, config/initializers/content_security_policy.rb, config/initializers/secure_headers.rb, config/routes.rb, lib/identity_config.rb, spec/components/previews/alert_component_preview.rb, spec/components/previews/button_component_preview.rb, spec/components/previews/process_list_component_preview.rb, spec/requests/headers_spec.rb
**Why:** So that as a developer or UX designer, I can see what options are available to me for using a view component, including interactive previews and copy-able source code.
This uses [Lookbook](https://github.com/allmarkedup/lookbook), a [Storybook](https://storybook.js.org/)-like preview environment that extends [ViewComponent's default component previews](https://viewcomponent.org/guide/previews.html). I've been eager to explore something like Storybook, especially with how these components are implemented in the design system. Lookbook is obviously tied specifically to ViewComponent/Rails and therefore not broadly applicable to static markup implementations of components. However, given how simple it is to integrate the tool, it's an easy enough lift to implement without too much …
=> Add view component previews using Lookbook

app/controllers/concerns/saml_idp_auth_concern.rb, app/controllers/concerns/saml_idp_logout_concern.rb, app/controllers/saml_idp_controller.rb, app/services/out_of_band_session_accessor.rb, app/services/pii/session_store.rb, config/service_providers.localdev.yml, spec/controllers/saml_idp_controller_spec.rb, spec/features/saml/saml_logout_spec.rb, spec/services/out_of_band_session_accessor_spec.rb, spec/support/saml_auth_helper.rb
**Why:** The recent updates were not actually working - we were using
the incorrect session key to invalidate the session in redis. This
update stores the session ID on the SP identity record during SAML
authentication (similar to OIDC) so that it can be retrieved during
remote logout. This is actually a safer behavior since it means that a
user will only be logged out if the session they logged in with is still
valid (whereas before they would have been logged out regardless if they
had started a new Login.gov session after authenticating to the SP).
[skip changelog] # covered by entry in #5990
=> Fix SAML remote logout

app/controllers/users/emails_controller.rb, spec/controllers/users/emails_controller_spec.rb
Fixes a 500 in [NewRelic](https://one.newrelic.com/nr1-core/errors-ui/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&begin=1645488886000&end=1645748086000&state=627e8ace-0e87-3bbe-331f-4c41c6a803a5)
We should probably move the email out of the session and pass the id as a parameter or something instead and do the lookup that way
=> Fix Resend Email 500

app/presenters/openid_connect_certs_presenter.rb, spec/presenters/openid_connect_certs_presenter_spec.rb
The JWK spec supports optionally including the [use](https://datatracker.ietf.org/doc/html/rfc7517#section-4.2) and [alg](https://datatracker.ietf.org/doc/html/rfc7517#section-4.4) attributes, but we don't currently send them
Our key is RS256 and is intended for use in verifying the signature of our tokens, so this PR adds those attributes to the response!
=> Add use and alg keys to OIDC certificate endpoint

lib/secure_cookies.rb, spec/requests/secure_cookies_spec.rb
Reports of this breaking Safari in local development (where we don't use HTTPS normally)
=> Only add "; Secure" to cookies served over HTTPS

app/javascript/packs/pw-strength.js, spec/javascripts/packs/pw-strength-spec.js
Previously: #5776 (LG-5461)
This improves a few things around password strength feedback:
- Marks the password strings as used in the JavaScript bundles, to ensure they're included in the locale bundles generated by `RailsI18nWebpackPlugin` (29021415d378de0eb900f4e56991efe9cc97b278)
- Joins multiple password strength feedback strings as individual sentences, so that they don't create a run-on sentence (24b2ddca750ecb4aa44d210f9de4381ed901b0dd, [before](https://user-images.githubusercontent.com/1779930/156021247-8a1f234f-58c4-451e-9ae8-e213fa31fd62.png), [after](https://user-images.githubusercontent.com/1779930/156021275-bd536bce-8c97-4054-8087-adc38b7098c0.png))
- Generates password strength feedback only if password is non-empty, so that the feedback matches the initial state on a new …
=> Fix password strength feedback for empty password

app/javascript/packages/rails-i18n-webpack-plugin/extract-keys-webpack-plugin.js, app/javascript/packages/rails-i18n-webpack-plugin/spec/fixtures/in1.js
**Why**: Due to how the plugin operates on the post-transpiled code, string template literals may be wrongly considered as candidates for extraction, despite the fact that the complete string includes runtime logic (`String#concat`) which cannot be accounted for at the extraction phase.
The changes here expect to see an additional argument or closing parenthesis of the `t()` call.
I noticed this by the presence of a `"datetime.dotiw."` key in: https://static.secure.login.gov/packs/js/application-26ddcb1a.en.js
Robustness commentary from #6001 still applies here, re: operating on built output.
=> Improve JS string extraction to exclude template literals

.rubocop.yml, app/jobs/reports/iaa_billing_report.rb, app/jobs/resolution_proofing_job.rb, app/presenters/openid_connect_user_info_presenter.rb, app/services/doc_auth/acuant/acuant_client.rb, app/services/doc_auth/mock/doc_auth_mock_client.rb, app/services/idv/agent.rb, app/services/idv/steps/verify_step.rb, lib/app_artifacts.rb, lib/identity_config.rb, lib/telephony/pinpoint/sms_sender.rb, lib/telephony/pinpoint/voice_sender.rb, lib/telephony/test/sms_sender.rb, lib/telephony/test/voice_sender.rb, scripts/changelog-check, spec/features/idv/doc_auth/verify_step_spec.rb, spec/models/backup_code_configuration_spec.rb, spec/services/idv/steps/verify_step_spec.rb, spec/support/features/doc_capture_helper.rb, spec/support/features/personal_key_helper.rb, spec/support/saml_auth_helper.rb
I thought we had this enabled, but I guess not!
I'm doing some experimentation on analytics logging, and I assumed some errors would be caught by this, but they weren't! So I fixed it
=> Add unused method argument lint

app/javascript/packages/rails-i18n-webpack-plugin/extract-keys-webpack-plugin.js, app/javascript/packages/rails-i18n-webpack-plugin/rails-i18n-webpack-plugin.spec.js, app/javascript/packages/rails-i18n-webpack-plugin/spec/fixtures/common.js, app/javascript/packages/rails-i18n-webpack-plugin/spec/fixtures/dynamic.js, app/javascript/packages/rails-i18n-webpack-plugin/spec/fixtures/expected452.en.js, app/javascript/packages/rails-i18n-webpack-plugin/spec/fixtures/expected452.es.js, app/javascript/packages/rails-i18n-webpack-plugin/spec/fixtures/expected452.fr.js, app/javascript/packages/rails-i18n-webpack-plugin/spec/fixtures/locales/forms/en.yml, app/javascript/packages/rails-i18n-webpack-plugin/spec/fixtures/locales/forms/es.yml, app/javascript/packages/rails-i18n-webpack-plugin/spec/fixtures/locales/forms/fr.yml
**Why**: To allow translations occurring in dynamically-imported scripts to be loaded.
Currently, string extraction works by adding additional assets associated with the Webpack chunk immediately associated with where the translation occurs. However, the runtime script loader responsible for dynamic script imports is not aware of these assets, therefore translations would not be loaded. The workaround is to associate the extracted translations with the closest entrypoint(s) from where the translation is found, so that the translations are loaded alongside the script which would perform the dynamic script import, via [`AssetSources.get_sources`](https://github.com/18F/identity-idp/blob/060e6fc25226891bb69334d015f17ba2c52a6218/lib/asset_sources.rb#L14-L21).
Specifically, this will support …
=> Improve support for JS string extraction from dynamic imports

app/javascript/packages/eslint-plugin/configs/recommended.js
**Why:** So that we don't get [`no-undef`](https://eslint.org/docs/rules/no-undef) lint errors when using e.g. DOM TypeScript helpers, and because the sorts of issues which would be identified through `no-undef` are already accounted for by TypeScript.
Example:
```ts
const inputs: NodeListOf<HTMLInputElement> = document.querySelectorAll('input');
// error  'NodeListOf' is not defined  no-undef
```
See: https://github.com/typescript-eslint/typescript-eslint/blob/main/docs/linting/TROUBLESHOOTING.md#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
I intentionally did not add a note to the [package changelog](https://github.com/18F/identity-idp/blob/main/app/javascript/packages/eslint-plugin/CHANGELOG.md), since this …
=> Disable ESLint no-undef for TypeScript files

app/services/expired_license_allower.rb, app/services/proofing/lexis_nexis/date_formatter.rb, spec/features/idv/doc_auth/document_capture_step_spec.rb, spec/jobs/document_proofing_job_spec.rb, spec/services/expired_license_allower_spec.rb, spec/services/proofing/lexis_nexis/date_formatter_spec.rb
**Why**: Since #5191, data in pii_from_doc should be the
international/ISO YYYY-MM-DD format
Thanks for [the reminder](https://github.com/18F/identity-idp/pull/5191#discussion_r817919645) @aduth
=> Remove a few legacy date parsing instances

app/controllers/concerns/remember_device_concern.rb, config/application.yml.default, lib/identity_config.rb, spec/features/remember_device/cookie_expiration_spec.rb
**Why:** Our current implementation sets a 30-day expiration on the
remember device cookie, which means that it persists even after the
browser is closed. This switches the cookie to session expiration so
that it expires when the browser closes to conform with 800-63B section
7.2:
> "Session secrets SHALL be non-persistent. That is, they SHALL NOT be
> retained across a restart of the associated application or a reboot of
> the host device."
=> Switch remember device cookie to session expiration

app/views/two_factor_authentication/sms_opt_in/error.html.erb, app/views/two_factor_authentication/sms_opt_in/new.html.erb, spec/views/two_factor_authentication/sms_opt_in/error.html.erb_spec.rb, spec/views/two_factor_authentication/sms_opt_in/new.html.erb_spec.rb
Two changes from testing:
- Remove "get help at SP" link
- Fix cancel link location (the partial is aimed at IDV, this is not the same thing)
=> Fix links on SMS opt-in pages

Gemfile
Warning:
> DEPRECATION WARNING: This manually engine loading is deprecated
> and will be removed in v3.0.0. Remove `require "view_component/engine"`.
=> Remove view_component gem require to fix deprecation warning

app/forms/openid_connect_authorize_form.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/forms/openid_connect_authorize_form_spec.rb
**Why**: So we can use the event log to see what SPs are requesting
=> Log ACR values and scopes form the OIDC auth request

config/application.rb
- Lets us set log level to minimize STDOUT output
from Identity::Hostdata (downloading files from S3, etc)
=> Add LOGIN_TASK_LOG_LEVEL env var

app/forms/reset_password_form.rb, spec/forms/reset_password_form_spec.rb
Kind of circuitous, but very possible way to get a 500 ([NewRelic](https://one.newrelic.com/nr1-core/errors-ui/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=259200000&state=ba16a0da-9bd2-2291-376c-21844327d596))
1. Register with EMAIL1 (do not confirm)
2. Reset password on EMAIL1
3. Register with EMAIL2
4. Confirm EMAIL2 via email received
5. Add 2FA
6. Go to account page logged in as EMAIL2
7. Click add email
8. Add EMAIL1
9. Open the recently received EMAIL1 confirmation email sent on behalf of EMAIL2
10. Log out
11. Open reset password email received in step 2
12. Enter new password and submit
13. 500
The index collision happens because we only allow one record with a given email address to be confirmed. The reset password token is generated for the …
=> Do not 500 when resetting password for account with an unconfirmed email address that has since been confirmed by another account

app/controllers/account_reset/cancel_controller.rb, app/services/analytics.rb
Partially reverts to fix a bug introduced in #6014 that causes a 500 during account reset
=> Fix 500 during account reset

db/primary_migrate/20220307214616_postgre_sql_autovacuum_config.rb, db/schema.rb
DB config change needed to support https://github.com/18F/identity-devops/issues/4175
Tested in `pt` env
```
== 20220307214616 PostgreSqlAutovacuumConfig: migrating =======================
-- execute("        ALTER TABLE \"devices\" SET (autovacuum_vacuum_scale_factor = 0.02,\n                                        autovacuum_analyze_scale_factor = 0.01,\n                                        autovacuum_vacuum_threshold = 0);\n\n        ALTER TABLE \"users\" SET (autovacuum_vacuum_scale_factor = 0.02,\n                                        autovacuum_analyze_scale_factor = 0.01,\n                                        autovacuum_vacuum_threshold = 0);\n")
-> 0.0036s
== 20220307214616 PostgreSqlAutovacuumConfig: migrated (0.0089s) ==============
deploy/migrate finished
```
=> Modify autovacuum config for devices and users tables

app/controllers/application_controller.rb, app/controllers/idv/gpo_controller.rb, app/controllers/idv/sessions_controller.rb, app/controllers/openid_connect/authorization_controller.rb, app/controllers/saml_idp_controller.rb, app/controllers/sign_up/completions_controller.rb, app/controllers/users/passwords_controller.rb, app/services/pii/cacher.rb, app/services/pii/session_store.rb, spec/controllers/saml_idp_controller_spec.rb, spec/controllers/users/passwords_controller_spec.rb
On the road to different methods of encrypting/decrypting user data and being more precise in our usage of KMS, changing how we interface with accessing PII bundles opens up some more opportunities with how we can handle it.
With a common interface, it becomes possible for us to do things like lazily decrypt sensitive data, which will reduce the amount of time and number of times where a request is holding sensitive decrypted data.
These changes remove all of the instances where `decrypted_pii` is checked in place of using the `Pii::Cacher#fetch`. Some areas still need to use the decrypted string rather than `Pii::Attributes`, so a `fetch_string` method was added to support those cases.
=> Create common interface for accessing PII bundle in session

app/controllers/application_controller.rb, app/controllers/concerns/idv_session.rb, app/controllers/idv/gpo_controller.rb, app/controllers/idv/image_uploads_controller.rb, app/forms/idv/api_image_upload_form.rb, app/jobs/address_proofing_job.rb, app/services/db/add_document_verification_and_selfie_costs.rb, app/services/db/sp_cost/add_sp_cost.rb, app/services/flow/base_flow.rb, app/services/flow/base_step.rb, app/services/gpo_confirmation_maker.rb, app/services/gpo_daily_test_sender.rb, app/services/identity_linker.rb, app/services/idv/phone_step.rb, app/services/idv/send_phone_confirmation_otp.rb, app/services/idv/session.rb, app/services/idv/steps/doc_auth_base_step.rb, spec/controllers/concerns/idv_step_concern_spec.rb, spec/controllers/idv/gpo_controller_spec.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/controllers/idv/review_controller_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb, spec/jobs/address_proofing_job_spec.rb, spec/services/db/add_document_verification_and_selfie_costs_spec.rb, spec/services/gpo_confirmation_maker_spec.rb, spec/services/idv/phone_step_spec.rb, spec/services/idv/send_phone_confirmation_otp_spec.rb, spec/services/idv/session_spec.rb, spec/support/controller_helper.rb
`User.find` and `ServiceProvider.find` are two of our most frequent queries. Though they're fast, they make up a [significant portion](https://onenr.io/0qwL2xZKgj5) of total Postgres time
Part of that is due to querying for a ServiceProvider by issuer and User by id when adding SP cost. This PR lifts the queries out of `Db::SpCost::AddSpCost` and puts the responsibility on callers of the function to provide all of the data ahead of time. For the most part, we are querying the issuer in `sp_session`, which `current_sp` has probably already done.
It gets a little weird in doc auth with having to adjust the delegation and moving `current_sp` to a public method, but I think it's worth it.
There's opportunity to apply a similar pattern to `IdentityLinker` which accepts an `issuer`, but that …
=> Avoid duplicated hot-path User and ServiceProvider queries

app/controllers/concerns/saml_idp_auth_concern.rb, app/controllers/concerns/verify_sp_attributes_concern.rb, app/forms/openid_connect_authorize_form.rb, app/services/identity_linker.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/openid_connect/token_controller_spec.rb, spec/controllers/risc/security_events_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/controllers/users/service_provider_revoke_controller_spec.rb, spec/features/account_reset/delete_account_spec.rb, spec/features/openid_connect/openid_connect_spec.rb, spec/features/remember_device/session_expiration_spec.rb, spec/features/users/user_profile_spec.rb, spec/forms/openid_connect_token_form_spec.rb, spec/forms/security_event_form_spec.rb, spec/services/identity_linker_spec.rb, spec/services/push_notification/http_push_spec.rb, spec/services/uuid_reporter_spec.rb, spec/support/features/session_helper.rb, spec/support/saml_auth_helper.rb, spec/support/shared_examples/remember_device.rb
Builds on #6058 to avoid duplicating a `ServiceProvider.find` query in `IdentityLinker`
=> Avoid duplicated ServiceProvider queries in IdentityLinker

Makefile, app/controllers/accounts/personal_keys_controller.rb, app/controllers/idv/gpo_controller.rb, app/controllers/idv/phone_controller.rb, app/services/analytics.rb, app/services/analytics_events.rb, app/services/idv/actions/verify_document_status_action.rb, lib/analytics_events_documenter.rb, spec/controllers/accounts/personal_keys_controller_spec.rb, spec/controllers/idv/gpo_controller_spec.rb, spec/controllers/idv/phone_controller_spec.rb, spec/lib/analytics_events_documenter_spec.rb, spec/services/idv/actions/verify_document_status_action_spec.rb
- Adds new `@identity.idp.previous_event_name` tag, exports it for documentation (LG-5915)
- Migrates a batch of events, including 2 with previous names (LG-5944)
=> Add tags for previous event names, migrate more events (LG-5915, LG-5944)

.erb-lint.yml
**Why**: Because BassCSS is removed altogether as of #6067, we shouldn't need to worry about references to legacy classes being introduced, and we should want to avoid any references to BassCSS at all to avoid confusion for future maintainers.
=> Remove DeprecatedClasses ERBLint configuration for BassCSS

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_btn.scss, app/assets/stylesheets/components/_general.scss, app/assets/stylesheets/components/all.scss, app/assets/stylesheets/utilities/_util.scss
**Why**: So that our stylesheets remain lean, and so that we have as few ad hoc design system overrides as possible.
Specifics:
- `usa-banner`: Redundant, since background is applied by inner child `usa-banner__header`.
- `usa-banner__button::before`: Unused, since there is no `::before` pseudo-class styles associated with this element.
- `usa-button--disabled`: Addressed upstream in https://github.com/uswds/uswds/pull/4132
- `html`: Unnecessary, because layout of the page is such that footer will always be pushed to bottom of page viewport, thus not necessary to reset the [default "overscroll" background color](https://github.com/18F/identity-style-guide/blob/c6b9e555e3cd179df1c804185d2aa9d6008f6b3b/src/scss/components/_general.scss#L1-L4)
- `vertical-align`: Unused.
=> Remove some unnecessary/unused CSS

app/services/idv/actions/verify_document_status_action.rb, app/services/idv/steps/doc_auth_base_step.rb, app/services/idv/steps/document_capture_step.rb, app/services/idv/steps/link_sent_step.rb, app/services/idv/steps/verify_base_step.rb, app/services/idv/steps/verify_wait_step_show.rb
In working on #6054, I noticed that we save the PII bundle in partial or whole states during the proofing process in places where it will never be read. This is not a significant change from a security or privacy perspective, except in that it reduces the copies of PII held in the session during the proofing process.
This PR addresses two of those instances. The first is when calling `extract_pii_from_doc`, which puts the PII from doc auth into the `pii_from_doc` key in `flow_session`. If we are in the hybrid flow, we are in a separate and temporary session, and `extract_pii_from_doc` will be called in the `LinkSentStep` and stored properly there. With that, we don't need to save it twice.
The other instance is in the transition from the …
=> Do not save additional PII to session when not needed

app/assets/stylesheets/components/_form.scss
**Why**: So that the red border shows as expected.
Fixes a small regression from #6067, where rearrangement of [`.field` styles](https://github.com/18F/identity-idp/blob/4d7ccc73eb1dee61d3b341e7ca0c454e7277e902/app/assets/stylesheets/components/_form.scss#L26-L28) cause them to take precedence over design system.
`stages/prod`|`main`|`aduth-lg-3877-error-border`
---|---|---
=> Restore error border styling for design system fields

lib/tasks/db_readonly_user.rake
IFF a read replica of the `idp` RDS database is stood up in an environment (which previously did not have one/is being newly created), the readonly user is not created by default, as the `db:create_readonly_user` task does not run. `deploy/migrate` does attempt to run `db:grant_readonly_access`, but this fails since the readonly user doesn't exist:
```
ActiveRecord::StatementInvalid: PG::UndefinedObject: ERROR:  role "[READONLY_USERNAME]" does not exist
```
This PR updates `db:grant_readonly_access` to check for the readonly user (via both `username` key and existence in `pg_roles`), and create it if it doesn't already exist, before granting `SELECT` to it. If the readonly user already exists, the task simply executes the `GRANT SELECT` action, as it normally does.
Deployed and tested in …
=> add check and user creation to grant_readonly_access task

app/controllers/concerns/two_factor_authenticatable_methods.rb, app/controllers/two_factor_authentication/backup_code_verification_controller.rb, app/controllers/two_factor_authentication/piv_cac_verification_controller.rb, app/controllers/two_factor_authentication/webauthn_verification_controller.rb, app/presenters/two_factor_auth_code/generic_delivery_presenter.rb, app/presenters/two_factor_auth_code/webauthn_authentication_presenter.rb, spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb, spec/presenters/two_factor_auth_code/authenticator_delivery_presenter_spec.rb, spec/presenters/two_factor_auth_code/backup_code_presenter_spec.rb, spec/presenters/two_factor_auth_code/generic_delivery_presenter_spec.rb, spec/presenters/two_factor_auth_code/phone_delivery_presenter_spec.rb, spec/presenters/two_factor_auth_code/piv_cac_authentication_presenter_spec.rb, spec/presenters/two_factor_auth_code/webauthn_authentication_presenter_spec.rb, spec/views/two_factor_authentication/otp_verification/show.html.erb_spec.rb, spec/views/two_factor_authentication/totp_verification/show.html.erb_spec.rb, spec/views/users/totp_setup/new.html.erb_spec.rb
Kind of a follow up to #6058 and #6061
=> Save a ServiceProvider.find query during two factor authentication

app/views/shared/_sp_alert.html.erb
**Why:** partners will likely want links to go to a new page/tab.
=> Allow target attribute in SP help text

app/assets/stylesheets/variables/_vendor.scss, app/views/accounts/_auth_apps.html.erb, app/views/accounts/_pii.html.erb, app/views/accounts/_piv_cac.html.erb, app/views/accounts/_webauthn_platform.html.erb, app/views/accounts/_webauthn_roaming.html.erb, app/views/users/backup_code_setup/create.html.erb, app/views/users/email_language/show.html.erb
**Why**:
- So that we're consistently using "tablet" (640px) as breakpoint to switch from small-screen to large-screen styling
- To improve performance of bundled CSS, both build-time (generating fewer styles) and user-facing runtime download size
This is similar to what we did in #5953 to disable `desktop` utility class generation.
This impacts the following screens:
- Account: TOTP listing table grid (collapses to 2 column at larger size)
- Account: IAL2 verified PII details table grid (collapses to 2 column at larger size)
- Account: PIV listing table grid (collapses to 2 column at larger size)
- Account: Security key listing table grid (collapses to 2 column at larger size)
- Account: Touch unlock listing table grid (collapses to 2 column at larger size)
- Account: Backup code setup …
=> Disable mobile-lg design system utility breakpoint

app/assets/stylesheets/utilities/_typography.scss, app/assets/stylesheets/variables/_app.scss, app/views/shared/_no_pii_banner.html.erb
**Why**: So that we're leveraging the design system as much as possible.
It's only used for the "No PII" banner shown in lower environments.
Before|After
---|---
=> Remove custom line-height CSS utility class

app/controllers/application_controller.rb, app/controllers/concerns/billable_event_trackable.rb, app/controllers/saml_idp_controller.rb, app/decorators/service_provider_session_decorator.rb, app/models/monthly_sp_auth_count.rb, config/service_providers.localdev.yml, spec/features/saml/saml_logout_spec.rb, spec/models/monthly_auth_count_spec.rb
Eventually we'll find them all (followup to https://github.com/18F/identity-idp/pull/6058, https://github.com/18F/identity-idp/pull/6061, and #6087)
=> Save a ServiceProvider.find query during authentication

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_icon.scss, app/assets/stylesheets/components/_modal.scss, app/assets/stylesheets/components/_profile-section.scss, app/assets/stylesheets/design-system-waiting-room.scss, app/assets/stylesheets/variables/_app.scss
**Why**: So we use the design system consistently, and to avoid confusion from multiple available options.
Reference: https://designsystem.digital.gov/design-tokens/spacing-units/
tl;dr `1 unit = 0.5rem`
=> LG-5990: Replace BassCSS space variables with design system tokens

app/controllers/banned_user_controller.rb, app/controllers/users/email_confirmations_controller.rb, app/services/analytics.rb, app/services/analytics_events.rb
This is an extension of: https://github.com/18F/identity-idp/pull/6014
The story is: https://cm-jira.usa.gov/browse/LG-5923
Please note that the events ADD_EMAIL, ADD_EMAIL_CONFIRMATION_RESEND , ADD_EMAIL_VISIT were never utilized so they have been removed from the events list.
The only events that are still there are ADD_EMAIL_CONFIRMATION and BANNED_USER_VISITED
=> Document analytics events part 5

scripts/changelog-check
**Why**: To reduce toil for changelog checks ([example](https://github.com/18F/identity-idp/pull/6088#event-6268164227)).
```
scripts/changelog-check -b 3d7455f~1 -s 3d7455f
```
Before:
```
A valid changelog line was not found.
```
After:
```
- Content: Make the content more clear
```
=> changelog-check: Auto-capitalize message

Gemfile, Gemfile.lock, lib/query_tracker.rb, spec/features/openid_connect/openid_connect_spec.rb, spec/lib/query_tracker_spec.rb
Inspired by https://github.com/18F/identity-idp/pull/6091#issuecomment-1072640101
~I didn't apply this to any tests yet, but we should be able to to use this in feature tests or controller tests if we want~
I just added one example usage, we can add more specific usages if we want to later
=> Add query tracker that lets us track queries by table

app/assets/stylesheets/design-system-waiting-room.scss
Regression of #6092
**Why**: So that stylesheets only include valid syntax.
In practice, this likely would not have had any noticeable impact, since (a) browsers ignore the invalid syntax, and (b) the inherited default value for the style is equivalent (`margin-block-end: 1em`, [source](https://browserdefaultstyles.com/#p)).
This happened because the `design-system-waiting-room.scss` stylesheet is [loaded before the design system mixins](https://github.com/18F/identity-idp/blob/5ca8bb65e9f81db8a834699f597799472654c3be/app/assets/stylesheets/application.css.scss#L4-L5). Since the only other stylesheets loaded before the design system are variable definitions which don't call any mixins, the impact should be limited to this one file.
```
NODE_ENV=production yarn build:css && grep 'units(' …
```
=> Fix stylesheet missing mixin raw output

app/assets/stylesheets/components/_i18n-dropdown.scss, app/views/shared/_footer_lite.html.erb
**Why**: So that the link contrast is shown with enough contrast relative to its background.
Before|After
---|---
**Implementation notes:**
USWDS support for explicit reverse link styling isn't very consistent currently, tracked at https://github.com/uswds/uswds/issues/4582. In the meantime, ~this copies styles from [`.usa-section--dark`](https://github.com/uswds/uswds/blob/7349ddfc07f3814be51f6e6143fd16b0530771f8/src/stylesheets/components/_section.scss#L33-L43)~ **Edit:** In [5db77dc](https://github.com/18F/identity-idp/pull/6099/commits/5db77dc0f7efc71970164d17a3db2325f9397c46), changed approach to use `usa-dark-background` + `bg-` utility, for consistency with other reverse link styling in the partial.
Future work should aim to refactor/componentize the dropdown, which is tangentially …
=> Fix hover color for language picker dropdown

app/services/displayable_pii_formatter.rb, config/locales/help_text/en.yml, config/locales/help_text/es.yml, config/locales/help_text/fr.yml, spec/features/openid_connect/openid_connect_spec.rb, spec/features/saml/ial1_sso_spec.rb, spec/presenters/completions_presenter_spec.rb, spec/services/displayable_pii_formatter_spec.rb
This pull request is to not display 'Updated on' for profiles that have not been verified in the stepup flow as it confuses the user. 
Before:
After:
=> lg-5736-stepup flow: update verified_at

Makefile
**Why**:
- Since we're primarily concerned with dependencies which are part of the production toolchain
- To unblock current branches, which are affected by [unpatched prototype pollution in "minimist" dependency](https://www.npmjs.com/advisories/1067259) (transitive dependency via `@babel/core`, `babel-loader`, `eslint-plugin-import`)
**Implementation notes:**
`yarn audit` returns a status code depending on severity level of vulnerabilities. Checking `<= 8` means to only fail on critical vulnerabilities. We may want to change this to `<= 4` (moderate) once a patched version of `minimist` is available, or remove the `test` altogether.
See: https://classic.yarnpkg.com/lang/en/docs/cli/audit/
=> Update Yarn audit build step to check critical production dependencies

app/views/users/two_factor_authentication_setup/index.html.erb, config/application.yml.default, config/locales/two_factor_authentication/en.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml, lib/identity_config.rb
This is the first step in creating a prototype for multi-factor authentication. The user test will ask users to select and provide multiple authentication methods. After testing is completed, work can/will be done to implement in production.
This PR creates the feature flag and logic on whether or not users will be shown the checkbox selection vs. radio buttons. On testing on this current PR, you should only see the radio buttons as the feature flag is currently set to false.
Future considerations for creating the feature/prototype:
- Would it be worth creating a feature branch to further develop and write tests against?
=> Add feature flag and interface for MFA prototype

Makefile, package.json, yarn.lock
**Why**: To resolve a prototype pollution vulnerability, and to allow us to be stricter with package auditing (flag "High" issues, in addition to "Critical").
Uses [Yarn resolutions feature](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/), since our direct dependencies which rely on it haven't all yet updated to the newest version.
Related:
- https://github.com/18F/identity-idp/pull/6101
- https://github.com/advisories/GHSA-xvch-5gv4-984h
changelog: Internal, Continuous Integration, Check for "High" severity vulnerability advisories at build step
=> Resolve minimist to patched version

.gitlab-ci.yml, Makefile
Updates the pipeline to:
- Only run for PRs/MRs and `main` or `stages/prod`
- Removes scheduled/on_push rules since we don't need them anymore
- Switches the artifact building to use the build pool
- Renames the cache key to avoid applying the cache by default
=> Update GitLab CI Pipeline

app/services/flow/base_step.rb, app/services/idv/steps/ssn_step.rb, app/services/idv/steps/verify_step.rb, spec/services/idv/steps/ssn_step_spec.rb, spec/services/idv/steps/verify_step_spec.rb
We had a few errors in [New Relic](https://one.newrelic.com/nr1-core/errors-ui/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?duration=259200000&state=4ee2a622-c1a9-7d7e-cb54-5471cc110ef8)
I suspect there may be other paths to get into this state, but I was able to reproduce with:
1. Start proofing process, and proceed up to the resolution/verify step
2. Open the page in another tab
3. Click "Start over" in one of the tabs
4. In the other tab, click "Continue", and the server will 500
It's likely an uncommon path towards a 500, but the result is:
=> Fix 500 during proofing verify step when expected information is not present

app/controllers/accounts/personal_keys_controller.rb, spec/controllers/accounts/personal_keys_controller_spec.rb
Currently if you log in with a PIV without entering your password, and then attempt to regenerate your personal key, you will not be prompted for your password first
This PR ensures that if you have an account with an active profile that your PII is decrypted with your password before being re-encrypted with a new personal key
=> Request password to decrypt PII before regenerating personal key

.gitlab-ci.yml
#6115 may have been a bit too strict
=> Run GitLab CI for all MRs/PRs

app/helpers/script_helper.rb, spec/helpers/script_helper_spec.rb
**Why**: To prevent issues where React is unable to access error details in development mode, in combination with assets served cross-origin via `webpack-dev-server`.
Steps to reproduce: Follow ["Testing identity proofing" process](https://developers.login.gov/testing/#testing-identity-proofing) to upload an error document to the document capture step. Without these changes, you would see a generic "technical difficulties" message.
Related docs: https://reactjs.org/docs/cross-origin-errors.html
=> Add crossorigin script attribute for local development Webpack assets

app/javascript/packages/document-capture/components/form-steps.jsx, spec/javascripts/packages/document-capture/components/document-capture-spec.jsx, spec/javascripts/packages/document-capture/components/form-steps-spec.jsx, spec/javascripts/packages/document-capture/components/review-issues-step-spec.jsx
**Why**: So that the user is shown a detailed alert message describing steps to take to resolve permissions issues preventing us from being able to capture a photo.
This appears to have been a regression of #5593. As part of those changes, the "unknown field errors" we receive from the server were [adapted to be shown as plain text](https://github.com/18F/identity-idp/pull/5593/files#diff-1a8fab239c87a31f300dd5508931b29bc06e5c65735f8211d1e19d72290b843bR96-R97), [in place of the alert banner](https://github.com/18F/identity-idp/pull/5593/files#diff-5fca9a27b2b1401b5c7fe26cdb6834d01c26a259a8281e81e27e550c12b5a870L255-L259) that had existed previously. However, this should have only applied for the "unknown field errors" received from the server, _not_ also to the step errors which we use …
=> LG-5911: Fix detailed camera access error alert display

app/controllers/sign_up/completions_controller.rb, app/decorators/service_provider_session_decorator.rb, spec/controllers/sign_up/completions_controller_spec.rb
We get a pretty rare 500 on the consent screen where the `requested_attributes` are `nil` ([NewRelic](https://one.newrelic.com/nr1-core/errors-ui/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?duration=1800000&state=969483dc-0fa5-9bbb-0b3e-4e24d7d51c7c)).
The cause is not quite clear, but this PR has a couple changes to potentially mitigate and also log some more information to help debug if it happens again:
1. The 500 was happening before the analytics call, so we weren't able to get as much information about the context, so one change is to swap the analytics call to come first.
2. We check both `sp_session` and `service_provider_request` for other SP-related information like [issuer](https://github.com/18F/identity-idp/blob/b813c8c/app/controllers/application_controller.rb#L109-L …
=> More analytics and more sources for requested_attributes on SP handoff

app/controllers/users/backup_code_setup_controller.rb, spec/controllers/users/backup_code_setup_controller_spec.rb
Currently, if you navigate to https://idp.int.identitysandbox.gov/backup_code_refreshed while logged in, you can trigger a 500 (NR Link)
This PR adds the `refreshed` route to the `ensure_backup_codes_in_session` check
=> Ensure backup codes exist before rendering refreshed template to fix 500

app/forms/webauthn_verification_form.rb, spec/forms/webauthn_verification_form_spec.rb
When verifying a WebAuthn signature, we sometimes get an exception from within OpenSSL, which causes a 500 ([NR Link](https://one.newrelic.com/nr1-core/errors/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=604800000&state=9045272a-f3d2-50b6-5acd-4db11e83246a))
=> Do not 500 when verifying webauthn key

app/services/db/sp_return_log.rb, spec/services/db/sp_return_log_spec.rb
Follows up #6141 to make sure that during the deploy when both versions of the code are running that we also attempt to update existing rows instead of just failing to create the row.
The potential pattern this fixes is:
1. Person arrives from a service provider and hits a server running the old version, which creates a partial sp_return_log
2. Person is getting redirected back to the service provider on a server running the new version, which attempts to create the row, and fails to create it because a row with that `request_id` already exists
3. The partial row remains and does not have `returned_at` set despite the person being returned to the service provider
=> Ensure service provider return logs is backwards compatible with previous behavior

app/models/user.rb
We have 5 columns created for Devise's `:trackable` module:
1. `sign_in_count`
1. `current_sign_in_at`
1. `last_sign_in_at`
1. `current_sign_in_ip`
1. `last_sign_in_ip`
We currently update these columns, but do not reference them in code or use them for any reports, so we can safely stop writing them and then later drop them.
This goes wayyyyyyyyy back to @jgrevich's #2 (which will be celebrating it's 6th birthday next week!), but I'm not sure when we may have stopped using these columns.
=> Remove Devise :trackable module

app/controllers/openid_connect/authorization_controller.rb, app/controllers/saml_idp_controller.rb, config/application.yml.default, lib/identity_config.rb, spec/features/openid_connect/authorization_confirmation_spec.rb, spec/features/saml/authorization_confirmation_spec.rb
Was reminded about this by some Slack chatter, hoping to pay down some technical debt now that this feature has been turned on in all environments.
=> Remove unused feature flag for Select Account screen

app/views/mfa_confirmation/index.html.erb, app/views/users/two_factor_authentication_setup/index.html.erb, config/locales/headings/en.yml, config/locales/headings/es.yml, config/locales/headings/fr.yml, config/locales/multi_factor_authentication/en.yml, config/locales/multi_factor_authentication/es.yml, config/locales/multi_factor_authentication/fr.yml, config/locales/titles/en.yml, config/locales/titles/es.yml, config/locales/titles/fr.yml, config/locales/two_factor_authentication/en.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml, config/routes.rb, spec/views/mfa_confirmation/index.html.erb_spec.rb
This PR creates the confirmation page that will inform the user that they have successfully set up one of their selected MFA methods.
Notes:
- Currently, there is no path to go from the "Choose your method page" to "You've created your first authentication method". This is expected because [routing is the next piece of the functionality](https://cm-jira.usa.gov/browse/LG-5988) that we are adding for the MFA feature.
- Another next step is to add "You've added your second method", "You've added your third method", etc. The logic is not here because the routing has not been set up. A presenter will be added to facilitate that logic once routing and the data structure is in place
- "You've added your first authentication method", "Add phone", and "Face ID has been added to your account" is …
=> Create "You've created your [x] authentication method!" page

Makefile
**Why**: To save myself the extra two seconds of effort when I inevitably make this mistake several times per week.
Note: "No, you're the only one who makes this mistake and we don't want this" is a valid review comment 😉
=> Add shortcut for common "make run" typo

app/controllers/saml_idp_controller.rb, app/services/analytics_events.rb, spec/controllers/saml_idp_controller_spec.rb, spec/features/saml/saml_spec.rb, spec/support/fake_saml_request.rb
Currently, we log OIDC auth requests with the `OPENID_CONNECT_REQUEST_AUTHORIZATION` event. SAML has a similar event in `SAML_AUTH`, but it's not quite the same. SAML will redirect internally and this event is only logged when a user is completely authenticated. This means we capture the event later in the process, and also potentially multiple times for one authentication request.
This PR creates a `'SAML Auth Request'` event which aims to be a closer match to the behavior on the OIDC side of logging where we log the external request only and before user authentication is required. The authentication gate on the original event is what prevented from adding `external` as an attribute rather than creating a new event.
=> Log External SAML Auth Requests

Gemfile, Gemfile.lock, app/controllers/idv/personal_key_controller.rb, app/javascript/packs/personal-key-page-controller.js, app/views/shared/_personal_key.html.erb, config/routes.rb, spec/views/shared/_personal_key.html.erb_spec.rb
Problem: the personal key partial is used in a few places outside of IDV, but always linked to the IDV version's of the `#download` action (which means it would trigger an IDV proofing process if used outside of IDV... very undesirable)
Solution: stop using the `#download` action
- Another solution would be to add a `#download` action to other personal key controllers
- However, we've had multiple bugs in the past due to the `#download` action and its dependency on data in the session, so I think we're better off completely removing it
Next steps: completely remove `#download`
=> Fix downloading personal keys outside of IDV (LG-5882)

Gemfile, Gemfile.lock, app/controllers/idv/personal_key_controller.rb, app/javascript/packs/personal-key-page-controller.js, app/views/shared/_personal_key.html.erb, config/routes.rb, spec/views/shared/_personal_key.html.erb_spec.rb
Fix downloading personal keys outside of IDV (LG-5882) (#6161)
* download personal key via data: URL or JS fallback for Internet Explorer
* add specs and removal notes
changelog: Bug Fixes, Personal keys, Fixes downloading personal keys outside of identity verification
=> Deploy RC 184.2 to Production

app/controllers/idv/personal_key_controller.rb, app/services/analytics.rb, app/services/analytics_events.rb, config/routes.rb, spec/controllers/idv/personal_key_controller_spec.rb
**Why**: Unused as of #6161
changelog: Internal, Source code, Remove unused download code
=> Remove idv/personal_key#download action

app/javascript/packages/document-capture/components/acuant-capture.jsx, app/javascript/packages/document-capture/components/capture-troubleshooting.jsx, app/javascript/packages/document-capture/components/file-image.jsx, app/javascript/packages/document-capture/components/form-steps.jsx, app/javascript/packages/document-capture/components/full-screen.jsx, app/javascript/packages/document-capture/components/review-issues-step.jsx, app/javascript/packages/document-capture/components/selfie-capture.jsx, app/javascript/packages/react-hooks/README.md, app/javascript/packages/react-hooks/index.ts, app/javascript/packages/react-hooks/package.json, app/javascript/packages/react-hooks/use-did-update-effect.spec.tsx, app/javascript/packages/react-hooks/use-did-update-effect.ts, app/javascript/packages/react-hooks/use-if-still-mounted.spec.tsx, app/javascript/packages/react-hooks/use-if-still-mounted.ts
**Why:** Preparatory work ahead of upcoming FlowStateMachine v2 work, where it's expected a new form-steps package would need to share usage of these hooks with the existing document-capture package.
=> Extract common React hooks to package

app/services/db/sp_return_log.rb, config/initializers/job_configurations.rb, spec/services/db/sp_return_log_spec.rb
Follow up to #6141 and #6147 to drop the code that enables backwards compatibility since it won't be needed any longer
=> Stop updating sp return logs for backwards compatibility

app/assets/stylesheets/components/_step-indicator.scss, app/javascript/packages/step-indicator/index.spec.ts, app/javascript/packages/step-indicator/index.ts, app/javascript/packages/test-helpers/README.md, app/javascript/packages/test-helpers/index.ts, app/javascript/packages/test-helpers/use-define-property.spec.ts, app/javascript/packages/test-helpers/use-define-property.ts, app/javascript/packages/test-helpers/use-property-value.spec.ts, app/javascript/packs/step-indicator.js, app/views/shared/_step_indicator.html.erb, spec/javascripts/packs/form-steps-wait-spec.js, spec/javascripts/packs/webauthn-setup-spec.js, spec/javascripts/packs/webauthn-unhide-spec.js, spec/views/shared/_step_indicator.html.erb_spec.rb
**Why**: So it's more easily implemented in the context of a React component, with the expectation it will be used in ongoing work for the IdV API epic.
The current implementation of `StepIndicator` is "plain JavaScript", but written in a form which predates the use of custom elements. The previous implementation largely assumed the element would be rendered on a static page that is not long-lived, thus did not implement "tear down" behaviors common to custom elements and React usage.
=> Adapt StepIndicator script to custom element

app/controllers/event_disavowal_controller.rb, app/controllers/users/email_language_controller.rb, app/controllers/users/emails_controller.rb, app/services/analytics.rb, app/services/analytics_events.rb, spec/controllers/event_disavowal_controller_spec.rb, spec/controllers/users/email_language_controller_spec.rb
Why? Documenting more analytics events.
=> LG-5925 Document analytics 7

app/components/password_toggle_component.html.erb, app/components/password_toggle_component.rb, spec/components/password_toggle_component_spec.rb
Related: #6081
**Why**: Since it may have a negative impact on form usability, revert until we have a chance to think about this more holistically.
=> Revert tab placement change for password toggle checkbox

app/models/user.rb, db/primary_migrate/20220406155240_drop_users_sign_in_at_sign_in_ip_sign_in_count.rb, db/schema.rb
Follow up to #6148, but this should not be merged until the previous PR is deployed everywhere
=> Drop unused users columns

app/services/analytics.rb, spec/services/analytics_spec.rb
**Why**: This will allow us to track average times to various steps in cloudwatch vs db and eventually get rid of registration_logs, funnel step times, etc.
=> Add session duration to analytics

app/javascript/app/components/modal.js, app/javascript/app/i18n-dropdown.js, package.json
**Why**:
- Because polyfills are intended to be confined to the polyfill package (#6060)
- So that it's not included in modern browsers (#6068, -0.9kb gzipped)
- To reduce surface area of dependencies shared with USWDS (related to https://github.com/18F/identity-style-guide/pull/312#issuecomment-1097156590)
- Because the polyfill is not even needed for these scripts, as they are only using simple features of `classList#add`, `classList#remove`, and `classList#toggle` supported by Internet Explorer
=> Remove classlist-polyfill from app scripts

app/javascript/packages/components/button.spec.tsx, app/javascript/packages/components/button.tsx, app/javascript/packages/document-capture/components/document-capture.jsx, app/javascript/packages/document-capture/components/documents-step.jsx, app/javascript/packages/document-capture/components/review-issues-step.jsx, app/javascript/packages/document-capture/components/selfie-step.jsx, app/javascript/packages/form-steps/form-steps-context.tsx, app/javascript/packages/form-steps/form-steps-continue-button.tsx, app/javascript/packages/form-steps/form-steps.spec.tsx, app/javascript/packages/form-steps/form-steps.tsx, spec/javascripts/packages/document-capture/components/document-capture-spec.jsx, spec/javascripts/packages/document-capture/components/review-issues-step-spec.jsx
**Why**: For consistency with other submit buttons, which are always shown as enabled and validate upon submission. Since this button will be used as part of ongoing identity verification work (LG-4159), changing this default behavior ensures we don't exacerbate the inconsistency.
This effectively reverts #4501
Before|After
---|---
FYSA @anniehirshman-gsa
=> Remove visually-disabled effect from FormStepsContinueButton

app/views/idv/session_errors/failure.html.erb, spec/views/idv/session_errors/failure.html.erb_spec.rb
**Why**: We think this error page is shown when identity
resolution fails, which means IPP is not a viable option
to get verified
Small follow-up to #6192
=> Remove IPP links from "failures" page

app/controllers/idv/phone_controller.rb, spec/controllers/idv/phone_controller_spec.rb
[LG-5225 Validation Errors not shown in IAL2](https://cm-jira.usa.gov/browse/LG-5225) 
**Why**:
- A good bug PR to get my hands dirty as a new dev on team ada 
- Possible edge cases (disabling JS?) where this bug might still occur, but adding this line of code doesn't do any harm 
**How**:
- Adding a flash[:error] in rails in the phone controller create function 
**Testing Instructions**
1. Go to http://localhost:3000/verify
2. Create account, follow steps until you get to verify phone
3. In the developer tools DOM, edit `<form> `and add `novalidate `
4. Add a phone number that is **not** US (ie: 3065551234) 
5. You should see the error as it appears in the screenshot below 
**Screenshot**
=> LG-5225 validation error IAL2 

app/controllers/users/two_factor_authentication_controller.rb, app/jobs/phone_number_opt_out_sync_job.rb, config/application.yml.default, lib/identity_config.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb, spec/jobs/phone_number_opt_out_sync_job_spec.rb
**Why**: It's been enabled for a few weeks with no major issues
=> Remove sms_resubscribe_enabled feature flag

app/controllers/verify_controller.rb, app/javascript/packages/form-steps/form-steps.spec.tsx, app/javascript/packages/form-steps/form-steps.tsx, app/javascript/packages/verify-flow/index.tsx, app/javascript/packages/verify-flow/steps/personal-key/personal-key-step.tsx, app/javascript/packs/verify-flow.tsx, app/views/verify/show.html.erb
**Why**: As an incremental step toward getting actual personal key initialized into the page, for feature parity with existing step.
Markup reference: https://github.com/18F/identity-idp/blob/main/app/views/partials/personal_key/_key.html.erb
1. Set `idv_api_enabled: "true"` in local `config/application.yml`
2. Go to: http://localhost:3000/verify/v2/personal_key
3. See personal key and "Generated on [Today's Date]"
Before|After
---|---
=> LG-6066: Initialize personal key value and render badge content

app/jobs/remove_old_throttles_job.rb
We get some failures every so often because the statement timeout is reached, this increases it to 30 seconds
=> Reduce limit for RemoveOldThrottlesJob

app/jobs/address_proofing_job.rb, app/jobs/document_proofing_job.rb, app/jobs/resolution_proofing_job.rb, app/models/gpo_confirmation.rb, app/services/encrypted_redis_struct_storage.rb, app/services/encryption/encryptors/background_proofing_arg_encryptor.rb, app/services/idv/agent.rb, spec/features/idv/doc_auth/document_capture_step_spec.rb, spec/jobs/address_proofing_job_spec.rb, spec/jobs/document_proofing_job_spec.rb, spec/jobs/resolution_proofing_job_spec.rb, spec/lib/identity_job_log_subscriber_spec.rb, spec/services/encryption/encryptors/background_proofing_arg_encryptor_spec.rb, spec/services/gpo_confirmation_spec.rb
**Why**: Currently we use the session encryptor to encrypt args for async proofing activities and sessions. This adds a complication to modifying the way sessions are encrypted because it is coupled to the way background job arguments are encrypted. Adding this new encryptor (which is a clone of the session encryptor) decouples them and enables us to make changes to the session encryptor.
=> Add a background job encryptor

app/forms/openid_connect_token_form.rb, config/initializers/ext_digest.rb, spec/config/initializers/ext_digest_spec.rb, spec/features/openid_connect/openid_connect_spec.rb, spec/forms/openid_connect_token_form_spec.rb
**Why**: adheres to OIDC spec better
Fixes #5991
=> Use URL-safe base64 encoding of SHA256 digest in examples

app/javascript/packages/document-capture/components/file-input.jsx, app/javascript/packages/document-capture/components/selfie-capture.jsx, app/javascript/packages/form-steps/form-steps-continue-button.spec.tsx, app/javascript/packages/form-steps/form-steps-continue-button.tsx, app/javascript/packages/modal/README.md, app/javascript/packages/modal/index.ts, app/javascript/packages/modal/modal.tsx, app/javascript/packages/modal/package.json, app/javascript/packages/react-hooks/index.ts, app/javascript/packages/react-hooks/use-instance-id.spec.ts, app/javascript/packages/react-hooks/use-instance-id.ts, app/javascript/packages/verify-flow/package.json, app/javascript/packages/verify-flow/steps/index.ts, app/javascript/packages/verify-flow/steps/personal-key-confirm/personal-key-confirm-step.tsx, app/javascript/packages/verify-flow/steps/personal-key-confirm/personal-key-input.spec.tsx, app/javascript/packages/verify-flow/steps/personal-key-confirm/personal-key-input.tsx, app/javascript/packages/verify-flow/steps/personal-key/personal-key-step.tsx
**Why**: So that a user can proceed from the personal key step to confirm their personal key and complete the proofing process.
This is an incomplete but functional implementation. I will add inline review comments where additional follow-up tasks are expected.
=> LG-6066: Add personal key confirmation modal to IDV v2 app

app/javascript/packages/components/button.spec.tsx, app/javascript/packages/components/button.tsx, app/javascript/packages/verify-flow/steps/personal-key/download-button.spec.tsx, app/javascript/packages/verify-flow/steps/personal-key/download-button.tsx, app/javascript/packages/verify-flow/steps/personal-key/personal-key-step.tsx
**Why**: So that a user can download their personal key to their computer.
Reuses and reimplements logic from #6161.
=> LG-6066: Implement download button for personal key step (IdV app)

app/javascript/packages/assets/spec/fixtures/assets.js, app/javascript/packages/assets/spec/fixtures/in.js, app/javascript/packages/assets/webpack-plugin.js, app/javascript/packages/assets/webpack-plugin.spec.ts
**Why**: So that the asset manifest plugin correctly identifies all assets.
This improves the plugin introduced in #6198, and addresses a similar peculiarity of Webpack code generation as in #6001. Similar to #6001, the regular expression should match the Webpack output pattern of `(0,getAssetPath)('path.svg'))`. Unlike #6001, we must account for [the "comment" fragment](https://github.com/webpack/webpack/blob/4abf353fbc6e702cf1768e8bbbeafe38ced33df7/lib/RuntimeTemplate.js#L892-L895) which may be output as part of the code generation (`(0,assets/* getAssetPath */.K)('id-card.svg'),`). The reason this happens here and not in the translation plugin is because the translation export `t` is already one character, and as such [the Webpack mangling logic will not rename …
=> Fix Webpack asset manifest generation for production exports

app/controllers/users/two_factor_authentication_controller.rb, app/models/throttle.rb, config/application.yml.default, config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml, lib/identity_config.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb, spec/features/users/sign_up_spec.rb
This PR adds a per-account rate limit for sending new phone number confirmation OTPs to augment the existing per-phone-number rate limits.
=> Rate limit phone confirmation attempts (LG-5492)

app/controllers/users/two_factor_authentication_controller.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb, spec/features/users/sign_up_spec.rb
follow up to #6216
`login_two_factor_options_url` is for choosing an existing 2FA when the intention was to redirect to setting up 2FA for _new_ accounts
=> fix redirect in phone confirmation throttle

app/forms/openid_connect_token_form.rb
**Why**: Good security practice to avoid timing attacks
=> Use secure_compare for OIDC code_challenge

app/javascript/packages/form-steps/form-steps.spec.tsx, app/javascript/packages/form-steps/form-steps.tsx, app/javascript/packages/verify-flow/steps/personal-key-confirm/personal-key-confirm-step.spec.tsx, app/javascript/packages/verify-flow/steps/personal-key-confirm/personal-key-confirm-step.tsx
**Why**: To allow the user to return to the personal key step to record their personal key, since they need it to be able to complete the confirmation step.
1. Set `idv_api_enabled: "true"` in local `config/application.yml`
2. Go to: http://localhost:3000/verify/v2/personal_key_confirm
3. Press "Back"
4. Observe that you are returned to the previous step ("personal key"), reflected both in page content and URL
=> LG-6160: Implement personal key confirmation modal "Back" button

app/javascript/packages/components/icon.tsx, app/javascript/packages/document-capture/components/selfie-capture.jsx, app/javascript/packages/document-capture/components/selfie-capture.scss
Refactoring follow-up to https://github.com/18F/identity-idp/pull/6212#discussion_r852983720
**Why**: As a simplification, since we can use it directly from the design system.
1. Have both the IdP and an instance of a local [sample app](https://github.com/18F/identity-oidc-sinatra) running
2. Start at http://localhost:9292
3. Under "Options" in the top-right, select "IAL 2 (strict)"
4. Click "Sign in"
5. Complete proofing flow up to document capture
6. Upload photos of document
7. Click "Continue"
8. Grant access to your camera
9. Observe camera icon appears same as before
=> Remove custom camera icon implementation

app/javascript/packages/verify-flow/steps/personal-key-confirm/personal-key-confirm-step.tsx, app/javascript/packages/verify-flow/steps/personal-key/personal-key-step.tsx
[LG-6159: Add and place images in Personal Key step](https://cm-jira.usa.gov/browse/LG-6159)
**Why:** Image assets need to be incorporated into personal key step in order for that step to have the same look/feel as the original 
**Testing Instructions** 
1.  Set `idv_api_enabled: "true"` in `local config/application.yml`
2. Go to: http://localhost:3000/verify/v2/personal_key
3. Observe that lock image is present at the bottom (see screenshot) 
4.  Click "continue"
5. Observe that red logo image is present at the top of the modal (see screenshot) 
**Note:**  One thing that differs from the [original implementation](https://github.com/18F/identity-idp/blob/a682e958fce7cbb60f90a7a12a95927e861a6de0/app/assets/stylesheets/components/_modal.scss#L37), the image at the top of the modal was a …
=> LG-6159: add and place images in personal key step

app/controllers/idv/cancellations_controller.rb, app/controllers/idv/come_back_later_controller.rb, app/services/analytics.rb, app/services/analytics_events.rb, app/services/idv/steps/doc_auth_base_step.rb, spec/controllers/idv/cancellations_controller_spec.rb, spec/controllers/idv/come_back_later_controller_spec.rb, spec/features/idv/doc_auth/welcome_step_spec.rb, spec/features/idv/doc_capture/document_capture_step_spec.rb, spec/support/idv_examples/cancel_at_idv_step.rb
- IDV_CANCELLATION (renamed to idv_cancellation_visit)
- IDV_CANCELLATION_GO_BACK
- IDV_CANCELLATION_CONFIRMED
- IDV_COME_BACK_LATER_VISIT
- IDV_DOC_AUTH_EXCEPTION_VISITED
=> Document additional analytics events (LG-5928)

.gitlab-ci.yml
=> Pin idp/ci to the current sha

app/controllers/verify_controller.rb, app/javascript/packages/form-steps/form-steps.spec.tsx, app/javascript/packages/form-steps/form-steps.tsx, app/javascript/packages/verify-flow/index.tsx, app/javascript/packages/verify-flow/steps/index.ts, app/javascript/packs/verify-flow.tsx
**Why**:
- As a user, I expect that each page is uniquely titled, so that I can understand its purpose.
- Feature parity with existing step implementation.
1. Set `idv_api_enabled: "true"` in local `config/application.yml`
2. Go to: http://localhost:3000/verify/v2
3. Observe browser tab title is "Save your personal key - Login.gov"
Based on current implementation:
https://github.com/18F/identity-idp/blob/e8555810d4a18870f233d3330e5ae6b3931c2bcd/app/views/layouts/base.html.erb#L20-L23
https://github.com/18F/identity-idp/blob/e8555810d4a18870f233d3330e5ae6b3931c2bcd/app/views/idv/personal_key/show.html.erb#L10
=> LG-6199: Show current IdV app step as page title

db/primary_migrate/20220421183611_drop_account_recovery_requests.rb, db/schema.rb
It looks like we intended to drop it after https://github.com/18F/identity-idp/pull/4980, so it should be ok to drop it now
=> Drop unused account_recovery_requests_table

app/models/user.rb
=> Skip querying unused user columns

app/controllers/sign_up/completions_controller.rb, app/controllers/users/two_factor_authentication_setup_controller.rb, app/views/mfa_confirmation/index.html.erb, app/views/sign_up/completions/show.html.erb, app/views/users/two_factor_authentication_setup/index.html.erb, config/locales/mfa/en.yml, config/locales/mfa/es.yml, config/locales/mfa/fr.yml, spec/features/multi_factor_authentication/mfa_cta_spec.rb, spec/support/features/session_helper.rb, spec/views/mfa_confirmation/index.html.erb_spec.rb, spec/views/sign_up/completions/show.html.erb_spec.rb
This PR adds a CTA for users to add a second authentication banner in order to best secure their account. This is part of the "sad path" when a user does not select more than one method.
Note:
- This will not render in production at this time;
- The banner should only be displayed if multiple factors are enabled
=> Create warning banner CTA to add a second authentication method

app/controllers/account_reset/cancel_controller.rb, app/controllers/account_reset/delete_account_controller.rb, app/controllers/account_reset/request_controller.rb, app/services/account_reset/cancel.rb, app/services/account_reset/delete_account.rb, app/services/account_reset/grant_requests_and_send_emails.rb, app/services/account_reset/validate_cancel_token.rb, app/services/account_reset/validate_granted_token.rb, app/services/analytics.rb, app/services/analytics_events.rb, spec/controllers/account_reset/cancel_controller_spec.rb, spec/controllers/account_reset/delete_account_controller_spec.rb, spec/controllers/account_reset/request_controller_spec.rb
The  "Account Reset" event was wearing a lot of hats... it had an `event` key and was basically combining a bunch of different separate events. There were some fields in common across these, but I think it's easier to reason about if we separate them. 
- cancel
- delete
- request
- cancel token validation
- granted token valdiation
- notifications
Bonus: migrated `ACCOUNT_RESET_VISIT` while I was here
=> Split up "Account Reset" analytics event (LG-5910)

app/controllers/users/verify_personal_key_controller.rb, app/services/analytics.rb, spec/controllers/users/verify_personal_key_controller_spec.rb, spec/support/fake_analytics.rb
Prompted by: https://github.com/18F/identity-idp/pull/6237#discussion_r856185655
**Why**: Since we don't want to be including this detail in any logs, as it is password-like.
=> Include "personal_key" as alertable key in analytics PiiDetector

app/javascript/packages/verify-flow/steps/personal-key-confirm/personal-key-input.spec.tsx, app/javascript/packages/verify-flow/steps/personal-key-confirm/personal-key-input.tsx, spec/support/features/personal_key_helper.rb, spec/support/features/session_helper.rb, spec/support/shared_examples_for_personal_keys.rb
**Why**: So that a user is not prevented from submitting the personal key confirmation step due to case sensitivity, for feature parity with the existing screen.
=> LG-6160: Validate personal key value as case-insensitive, Crockford base32

config/locales/titles/en.yml
The verb `requested` was using the wrong tense in English. This commit fixes that. The other translations appear to be correct
changelog: Bug Fixes, Content, A typo on the completions page was fixed
=> Fix a typo on the completions page

app/models/doc_auth_record.rb, app/models/user.rb, db/primary_migrate/20220422190622_drop_doc_auths.rb, db/schema.rb, spec/models/doc_auth_record_spec.rb, spec/models/user_spec.rb
Looks like the last usage was removed in https://github.com/18F/identity-idp/pull/4368
=> drop unused doc_auths table

app/javascript/packages/verify-flow/index.tsx, app/javascript/packages/verify-flow/steps/personal-key/personal-key-step.tsx
[LG-6192  Add alert banner for successful completion of Password Entry](https://cm-jira.usa.gov/browse/LG-6192)
**Why:** We need to let the user know that their data has been encrypted after they enter their password
**Testing Instructions**
1. Make sure idv_api_enabled is set to true in application.yml.default
2. Go to http://localhost:3000/verify/v2/personal_key
3. Observe that the alert is present per screenshot
**Screenshot**
**Note** 
This is a draft PR because I'm not sure about my idea for handling the fact that users can reset their personal key after they go through the steps. Since we don't want to display the alert in that scenario, I thought this maybe could be handled by simply checking if the step indicator element is present or not. Major assumption being that resetting the …
=> LG-6192  Add alert banner for successful completion of Password Entry

app/services/idv/actions/verify_document_status_action.rb, spec/services/idv/actions/verify_document_status_action_spec.rb
**Why**: So that we are consistently tracking costs between sync and async implementations.
Discovered in #6229, via failing "SP Costing" feature spec when run against identity verification with JavaScript enabled.
https://github.com/18F/identity-idp/blob/a013cede5d029ea4edb38a92223cca1ae19280c1/spec/features/sp_cost_tracking_spec.rb#L23-L29
=> Add missing costs tracking for async doc auth

app/decorators/service_provider_session_decorator.rb, spec/features/remember_device/sp_expiration_spec.rb, spec/support/saml_auth_helper.rb
https://cm-jira.usa.gov/browse/LG-5905 
Updates were made to require AAL2 if partners request it.
=> Fix tests for aal2

app/controllers/application_controller.rb, app/controllers/concerns/billable_event_trackable.rb, app/controllers/users/sessions_controller.rb, app/controllers/users/two_factor_authentication_controller.rb, app/services/db/sp_cost/add_sp_cost.rb, app/services/identity_linker.rb, app/services/idv/send_phone_confirmation_otp.rb, spec/controllers/saml_idp_controller_spec.rb, spec/features/sp_cost_tracking_spec.rb
We create a lot of rows in `sp_costs` but do not currently use them for any reporting. The removed types account for around 79% of the total rows, so this should save a significant amount of overhead on the database side.
=> Drop unused types for sp_costs

app/controllers/concerns/saml_idp_auth_concern.rb, app/forms/openid_connect_authorize_form.rb, app/models/service_provider.rb, app/services/ial_context.rb, spec/features/idv/liveness/upgrade_to_strong_ial2_spec.rb, spec/services/attribute_asserter_spec.rb, spec/services/ial_context_spec.rb
Liveness checking specific functionality is being discarded in favor of a full IAL2 compliant flow which may include additional deltas. That makes this flag confusing and hopefully unnecessary so this commit removes it.
A follow on commit will be required to drop the column.
=> Retire the liveness_checking_required flag on service providers

app/javascript/packages/device/index.js, spec/features/idv/doc_auth/document_capture_step_spec.rb, spec/support/features/doc_auth_helper.rb, spec/support/features/document_capture_step_helper.rb
**Why**: Because it appears we did not have coverage for this flow previously, evidenced by the fact that the current test helpers are currently broken.
=> Add and fix spec coverage for JS-enabled, IAL2 strict doc auth

app/forms/totp_setup_form.rb, spec/controllers/users/totp_setup_controller_spec.rb, spec/features/remember_device/totp_spec.rb, spec/features/remember_device/user_opted_preference_spec.rb, spec/features/users/totp_management_spec.rb, spec/forms/totp_setup_form_spec.rb, spec/support/features/session_helper.rb
**Why**: For consistency with other MFA setup, and for consistency with the JS-enabled user experience, where the input is rendered as required.
This was discovered in #6229, where the `set_up_2fa_with_authenticator_app` spec helper would not work as expected in a JavaScript-enabled browser, since the browser validation would prevent submission without a valid name.
The previous implementation seemed to be intentionally allowing an absent name. While this may be reasonable if applied consistently, the revisions bring alignment to client-side and server-side validation, and across different MFA types (e.g. [PIV/CAC](https://github.com/18F/identity-idp/blob/1181c82ea441439a01c12fb572636ff1a7eb4c09/app/forms/user_piv_cac_setup_form.rb#L12)).
=> Add form validation for present TOTP name

app/models/profile.rb, spec/models/profile_spec.rb
The letter flow as it is implemented may not meet the bar for strict IAL2. This commit adds a method for checking whether a letter was used to verify a user to enable building conditionals around that in a future change.
=> Add a `includes_phone_check?` method to Profile

app/controllers/saml_idp_controller.rb, app/presenters/saml_request_presenter.rb, lib/saml_idp_constants.rb, spec/controllers/saml_idp_controller_spec.rb
**Why**: So that an IAL2 strict request behaves similar to a standard IAL2 request, particularly in how a user should be directed to enter their password to decrypt PII if encrypted.
Discovered in #6229, via failing feature specs where user would not be prompted to enter their password to decrypt profile when authenticating as IAL2 strict.
=> Fix SAML auth context handling for IAL2 strict request

spec/factories/profiles.rb
**Why**: Because `encrypt_recovery_pii` is already called as part of the preceding `encrypt_pii`.
https://github.com/18F/identity-idp/blob/0b56e2ed05744190357eb224dbc9b896fe6d4f5b/app/models/profile.rb#L57
=> Avoid redundant recovery PII encrypt in profile spec factory

app/models/user.rb, db/primary_migrate/20220422193820_drop_unused_user_columns.rb, db/schema.rb
Follow up to #6235, but this should not be merged until after that change is deployed
=> Drop unused user columns

app/controllers/saml_idp_controller.rb, spec/controllers/saml_idp_controller_spec.rb
We got a couple 500s in [NewRelic](https://one.newrelic.com/nr1-core/errors/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=259200000&state=a9990bf8-b008-34ff-88f1-2b7c69ac157a) in the form of `URI::InvalidURIError: bad URI(is not URI?):` on SAML authentication
This patch uses https://github.com/rails/rails/blob/3520cc77df1b52a6c808083214b583c769e9a4b2/actionpack/lib/action_controller/metal/redirecting.rb#L197-L201 as a reference
=> Fix 500 error when parsing malformed referer header

app/services/idv/session.rb, app/services/pii/cacher.rb, app/services/reactivate_account_session.rb
Follow up to #6054 to update places where we store a PII bundle to use the `Pii::Cacher`:
- Gpo Confirmation
- End of IDV where we move PII from the IDV part to the main PII bundle location
- Account reactivation
=> Move more PII bundle usage to the common interface in Pii::Cacher

app/javascript/packages/test-helpers/use-property-value.spec.ts, app/javascript/packages/test-helpers/use-property-value.ts
**Why**: So that `key in obj` tests don't wrongly report `true` after a test has completed.
Observed in #6257 (see [example test failure](https://app.circleci.com/pipelines/github/18F/identity-idp/72541/workflows/49afb4fd-27fc-4308-a051-53b5021846c8/jobs/121923), [root cause](https://github.com/18F/identity-idp/blob/efa887fb8ad9ecf820299add99010a5044cde731/app/javascript/packages/verify-flow/steps/personal-key/download-button.spec.tsx#L57), [impacted code](https://github.com/18F/identity-idp/blob/efa887fb8ad9ecf820299add99010a5044cde731/app/javascript/packages/verify-flow/steps/personal-key/download-button.tsx#L23))
=> Test Helpers: Fix usePropertyValue for previously-undefined value

app/controllers/users/verify_password_controller.rb, app/services/reactivate_account_session.rb, spec/controllers/users/verify_password_controller_spec.rb, spec/controllers/users/verify_personal_key_controller_spec.rb, spec/services/reactivate_account_session_spec.rb
A slight followup to #6273. The primary motivation is to rename the key so it doesn't give the appearance of holding a personal key, and it's also an opportunity to rename to something slightly more descriptive.
This will also be a two-part change where we write to both keys on the next deploy, and then start reading the new location and stop writing the old one in the deploy after.
=> Rename reactivate account session :personal_key key to be more descriptive

app/javascript/packages/form-steps/form-steps.spec.tsx, app/javascript/packages/form-steps/form-steps.tsx, app/javascript/packages/verify-flow/index.spec.tsx, app/javascript/packages/verify-flow/index.tsx, app/javascript/packages/verify-flow/steps/personal-key-confirm/personal-key-confirm-step.spec.tsx, app/javascript/packages/verify-flow/steps/personal-key-confirm/personal-key-confirm-step.tsx, app/javascript/packages/verify-flow/steps/personal-key/personal-key-step.spec.tsx, app/javascript/packages/verify-flow/steps/personal-key/personal-key-step.tsx
[LG-6201](https://cm-jira.usa.gov/browse/LG-6201)
**What**
Adding logs for personal_key step based on [event log documentation in Figma](https://www.figma.com/file/vtgBsP61slpBopu8ixXB0K/IAL2-Event-Logs?node-id=3357%3A16150)
Also adding test coverage for all logging events. 
**Why**
We need to add logging to the personal key step to match the existing logging in production.
**Testing Instructions**
1. In `application.yml.default`, set `idv_api_enabled` to `true `
2. Go through initial steps to create new account (set up password, click link in email) on localhost
3. Navigate to localhost:3000/verify/v2
4. Open dev tools Network tab, check that logger event from Figma doc is called  (personal key visited) 
5. Click on download button, check that logger event (download personal key) is …
=> LG 6201 audit/implement logs

app/jobs/reports/base_report.rb, app/jobs/reports/sp_active_users_report.rb, app/services/db/identity/sp_active_user_counts.rb, spec/jobs/reports/sp_active_users_report_spec.rb
After speaking with folks in billing, they said it would be easier if the first day in the new fiscal year ran the report for all of the previous fiscal year, rather than for the partial day of the first day in the current fiscal year
=> Run report for full fiscal year on October 1st for SP Active Users report

app/controllers/frontend_log_controller.rb, app/services/analytics_events.rb, lib/analytics_events_documenter.rb, spec/lib/analytics_events_documenter_spec.rb
**Why**: This allows any arguments, so if callers passed args,
they would go undocumented and also not make it to the logs
- It turns out `*` is invisible to YARD as parameter because it doesn't have a name, so we had to look at the signature for it
=> Disallow * as analytics_event param name

app/controllers/idv/phone_controller.rb, app/services/analytics.rb, app/services/analytics_events.rb, spec/controllers/idv/phone_controller_spec.rb
- IDV_PERSONAL_KEY_DOWNLOADED	(done previously)
- IDV_PERSONAL_KEY_VISITED	
- IDV_PERSONAL_KEY_SUBMITTED	
- IDV_PHONE_CONFIRMATION_FORM	
- IDV_PHONE_CONFIRMATION_VENDOR
=> LG-5931 Document the rest of analytics events #13

app/controllers/frontend_log_controller.rb, app/services/analytics_events.rb
Follow-up to #6285
**Why**: Toward the objective that all "visited" and "submitted" events associated with step progress in the IDV API application should be unprefixed (no "Frontend:" prefix for events).
1. Set `idv_api_enabled: true` in local `config/application.yml`
2. Sign in with an un-proofed user, or create a new account
4. Complete the entire proofing process, including submitted personal key confirmation
5. In your terminal, run `tail -2 log/events.log`
6. Observe the first of two events is `"name":"IdV: personal key confirm submitted"` (previously, `"name":"Frontend: IdV: personal key confirm submitted"`)
As an alternative, I considered collapsing "Personal Key" and "Personal Key Confirm" …
=> LG-6201: Add personal confirm step submitted as frontend unprefixed event

app/controllers/api/base_controller.rb, app/controllers/application_controller.rb, app/controllers/concerns/render_condition_concern.rb, app/controllers/idv/review_controller.rb, app/controllers/verify_controller.rb, app/javascript/packages/verify-flow/index.tsx, app/javascript/packs/verify-flow.tsx, config/application.yml.default, lib/feature_management.rb, lib/identity_config.rb, spec/controllers/api/verify/complete_controller_spec.rb, spec/controllers/concerns/render_condition_concern_spec.rb, spec/controllers/idv/review_controller_spec.rb, spec/controllers/verify_controller_spec.rb, spec/lib/feature_management_spec.rb
**Why**: So that we have the option to enable specific polished steps in deployed environments without needing to enable them all.
=> LG-6220: Split IdV app feature flags to per-step

spec/rails_helper.rb
**Why**: So that URL helpers use the correct, expected host name for the running server, rather than "example.com".
Reference: https://github.com/rspec/rspec-rails/issues/1275
I had originally planned to leave this in #6229, but coincidentally, @SammySteiner had run into the same issue for specs for #6278.
=> Override default_url_options to set correct host, port in JS specs

docs/frontend.md
**Why**: So that it's accurate and useful for onboarding.
As I discovered when recently sharing this, the document has fallen slightly out-of-date.
Refer to commit history for specific updates, as well as rationale in extended commit description.
=> Update Frontend documentation overview

app/services/funnel/doc_auth/register_step_from_analytics_submit_event.rb
**Why**: So that the build passes, and so that we don't have 500 errors.
Context: https://github.com/18F/identity-idp/pull/6288/files#r864759689
There's probably a more elegant way to implement this than to repeat the event name string, but I'm most concerned with restoring the passing build.
=> Fix 500 in analytics logging from missing constant

app/javascript/packages/document-capture/components/acuant-capture.jsx, app/javascript/packages/document-capture/components/capture-troubleshooting.jsx, app/javascript/packages/document-capture/components/review-issues-step.tsx, app/javascript/packages/document-capture/components/warning.jsx, app/javascript/packages/document-capture/context/acuant.jsx, app/javascript/packages/document-capture/context/analytics.jsx, app/javascript/packages/document-capture/higher-order/with-background-encrypted-upload.jsx, app/javascript/packs/document-capture.jsx, spec/javascripts/packages/document-capture/components/acuant-capture-spec.jsx, spec/javascripts/packages/document-capture/components/capture-advice-spec.jsx, spec/javascripts/packages/document-capture/components/capture-troubleshooting-spec.jsx, spec/javascripts/packages/document-capture/components/review-issues-step-spec.jsx, spec/javascripts/packages/document-capture/components/warning-spec.jsx, spec/javascripts/packages/document-capture/context/acuant-spec.jsx, spec/javascripts/packages/document-capture/higher-order/with-background-encrypted-upload-spec.jsx
**Why**:
- Because it's redundant with logging via FrontendLogController and presumably runs up our bill
- For improved developer ergonomics, and for alignment with other event tracking methods
**For follow-up:**
=> Remove NewRelic frontend event logging

spec/factories/profiles.rb, spec/factories/users.rb, spec/features/reports/authorization_count_spec.rb
~Blocked by: #6253~
**Why:**
- To unblock and limit the scope of #6229
- For improved compatibility with JS-enabled proofing, where authorization counts rely on an "Agree and continue" redirect back to the SP. With the JavaScript browser, there is no server to redirect to, resulting in an error.
- Improved performance, since proofing involves many steps
- To limit the concern of the specs to authorization counts, not to the ability to successfully proof
=> Use stubbed profile for authorization_count_spec

app/javascript/packages/countdown-element/index.spec.ts, app/javascript/packages/spinner-button/spinner-button-element.spec.ts, app/javascript/packages/spinner-button/spinner-button.spec.tsx, app/javascript/packages/test-helpers/index.ts, app/javascript/packages/test-helpers/package.json, app/javascript/packages/test-helpers/use-sandbox.spec.ts, app/javascript/packages/test-helpers/use-sandbox.ts, spec/javascripts/app/components/modal-spec.js, spec/javascripts/app/webauthn_spec.js, spec/javascripts/packages/analytics/index-spec.js, spec/javascripts/packages/document-capture-polling/index-spec.js, spec/javascripts/packages/document-capture/components/document-capture-spec.jsx, spec/javascripts/packages/document-capture/components/review-issues-step-spec.jsx, spec/javascripts/packages/document-capture/components/selfie-capture-spec.jsx, spec/javascripts/packages/document-capture/components/submission-complete-spec.jsx, spec/javascripts/packages/document-capture/context/upload-spec.jsx, spec/javascripts/packages/document-capture/higher-order/with-background-encrypted-upload-spec.jsx, spec/javascripts/packages/document-capture/services/upload-spec.js, spec/javascripts/packages/one-time-code-input/index-spec.js, spec/javascripts/packs/form-steps-wait-spec.js, spec/javascripts/packs/webauthn-setup-spec.js, spec/javascripts/packs/webauthn-unhide-spec.js, spec/javascripts/support/sinon.js
**Why**:
- It already exists in `spec`, but isn't currently accessible to package specs
- For convenience:
- Automatic clean-up after spec
- Delayed initialization of fake timers
- Support sustained reference to destructured functions
- Useful for `userEvent.setup({ advanceTimers: clock.tick })`
- Improved testability for the behavior of the helper itself
=> test-helpers: Add useSandbox test helper

app/services/analytics_events.rb
I have some additional review feedback for https://github.com/18F/identity-idp/pull/6293 but it seemed easier to just make this PR instead of leave a bunch more comments
See commits for reasoning, the most important is d1961a106c4161df083d555e7c35000cc40dce63 because once the changes land on `main` they would break without it
=> Patch: analytics events 11

app/controllers/concerns/idv/phone_otp_rate_limitable.rb, app/controllers/idv/otp_delivery_method_controller.rb, app/controllers/idv/resend_otp_controller.rb, app/services/analytics.rb, app/services/analytics_events.rb, spec/controllers/idv/otp_delivery_method_controller_spec.rb, spec/controllers/idv/resend_otp_controller_spec.rb
Migrates the follow events:
- IDV_PHONE_CONFIRMATION_OTP_RATE_LIMIT_ATTEMPTS
- IDV_PHONE_CONFIRMATION_OTP_RATE_LIMIT_LOCKED_OUT
- IDV_PHONE_CONFIRMATION_OTP_RATE_LIMIT_SENDS
- IDV_PHONE_CONFIRMATION_OTP_RESENT
- IDV_PHONE_CONFIRMATION_OTP_SENT
=> Migrate analytics events, batch 14 (LG-5932)

app/controllers/idv/gpo_controller.rb, spec/controllers/idv/gpo_controller_spec.rb
Similar 500 to the one in https://github.com/18F/identity-idp/pull/6121 where we should request password to unlock PII before trying to access the PII bundle when people log in with PIV ([New Relic](https://one.newrelic.com/nr1-core/errors/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=43200000&state=0742e810-3099-3fc9-6993-0a4b3e1d474b))
=> Fix 500 when resending GPO letter

app/controllers/application_controller.rb, app/controllers/concerns/billable_event_trackable.rb, app/controllers/users/sessions_controller.rb, app/controllers/users/two_factor_authentication_controller.rb, app/services/db/sp_cost/add_sp_cost.rb, app/services/identity_linker.rb, app/services/idv/send_phone_confirmation_otp.rb, spec/controllers/saml_idp_controller_spec.rb, spec/features/sp_cost_tracking_spec.rb
Reverts #6264 and #6266 for now
=> Revert dropping some sp_costs

app/forms/idv/api_image_upload_form.rb, app/services/analytics_events.rb
These are changes missed on the original document analytics 11 PR: https://github.com/18F/identity-idp/pull/6293
=> document-analytics-11-updates

app/javascript/packages/verify-flow/verify-flow-step-indicator.spec.tsx, app/javascript/packages/verify-flow/verify-flow-step-indicator.tsx, app/javascript/packages/verify-flow/verify-flow.tsx
**Why**: So that labels are shown in the user's preferred language.
Related: https://github.com/18F/identity-idp/pull/6183#discussion_r865348814
**Screenshot**
Before|After
---|---
=> Translate labels for IdV app step indicator

app/services/reactivate_account_session.rb, spec/services/reactivate_account_session_spec.rb
Follow up to #6273 and #6283
Drops the now deprecated fields from the session and reads the new value, but should not be merged until after the next deploy
=> Remove references to deprecated and renamed session keys

app/controllers/api/verify/complete_controller.rb, app/controllers/verify_controller.rb, app/javascript/packages/verify-flow/verify-flow.tsx, app/javascript/packs/verify-flow.tsx, app/services/idv/user_bundle_tokenizer.rb, spec/controllers/api/verify/complete_controller_spec.rb, spec/services/idv/user_bundle_tokenizer_spec.rb
Captures the current state of the user's pii (and a few other session state variables) and packs them in a JWT that is used to initialize the React app for the new IdV flow.
As we work our way back in the flow from the end, we will eventually be managing the user PII in the client, though we will be passing the JWT back and forth since it will contain the verified data and will be signed by the server.
The pii in the JWT is added to the initial values that are given to the React app.
=> LG-6204/LG-6220: capture user pii in a signed JWT and pass to frontend

app/javascript/packages/verify-flow/index.tsx, app/javascript/packages/verify-flow/verify-flow-alert.spec.tsx, app/javascript/packages/verify-flow/verify-flow-alert.tsx, app/javascript/packages/verify-flow/verify-flow.spec.tsx, app/javascript/packages/verify-flow/verify-flow.tsx
**Why**: So that the personal key success alert message won't be shown for all steps, as we continue to expand the flow.
This builds on #6239, where a goal was to avoid including success banner in the implementation of the step itself, since steps could possibly be reused elsewhere (e.g. account dashboard personal key reset) and the display of a success banner is more a reflection of _transition between steps_ as opposed to the step itself.
**Screenshot**
(Note: There's not expected to be any visual effect of these changes)
=> Show IdV app alert message relevant for current step

lib/telephony/pinpoint/sms_sender.rb
Converts the catching of Pinpoint errors to use the superclass mentioned [here](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Pinpoint/Errors.html) ([NR link](https://one.newrelic.com/nr1-core/errors/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=259200000&state=09226acb-42b9-dc3c-aeb8-3e98675340b9))
=> Use superclass to improve catching possible Pinpoint errors and avoid 500s

app/controllers/two_factor_authentication/otp_verification_controller.rb, app/controllers/users/two_factor_authentication_controller.rb, spec/controllers/two_factor_authentication/options_controller_spec.rb, spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb
I suspect this is limited to people manually editing the form to specify a different (invalid) ID, but it caused some 500s ([NR](https://one.newrelic.com/nr1-core/errors/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=259200000&state=ea51363b-e7fe-5509-daed-6df4e93ef4be))
This PR adds validation and additional tests around this case.  I'm not overly worried about getting the redirect exactly right in case where we redirect back to the homepage.  The user in question could be signing up or authenticating, but either way something funky is going on 🙂
=> Fix 500 when trying to display invalid phone numbers

app/controllers/concerns/billable_event_trackable.rb, app/controllers/concerns/saml_idp_auth_concern.rb, app/controllers/openid_connect/authorization_controller.rb, app/controllers/saml_idp_controller.rb, app/forms/openid_connect_authorize_form.rb, app/presenters/saml_request_presenter.rb, app/services/attribute_asserter.rb, app/services/ial_context.rb, spec/controllers/saml_idp_controller_spec.rb, spec/features/ialmax/saml_sign_in_spec.rb, spec/presenters/saml_request_presenter_spec.rb, spec/services/attribute_asserter_spec.rb, spec/services/ial_context_spec.rb, spec/support/saml_auth_helper.rb, spec/support/shared_examples/sign_in.rb
Detailed description TBD
Tested locally using https://github.com/18F/identity-saml-sinatra, with small modifications to app.rb to set the `Comparison` attribute to `minimum`. Before testing, I modified the SP record to set the default attribute bundle to include IAL2 attributes. The following scenarios were tested:
1. Send authentication request at `IAL1`, sign in with un-proofed user ==> response back at IAL1 with only IAL1 attributes
2. Send authentication request at `IAL2`, sign in with un-proofed user ==> sent through proofing flow
3. Send authentication request at `IAL1`, sign in with proofed user ==> response back at IAL2 with default attribute bundle
I have some controller tests for this use case that appear to all pass, but this is desperately in need of tests across the board. …
=> Support IALMAX using the Comparison attribute in SAML

app/services/saml_endpoint.rb, config/application.yml.default, lib/identity_config.rb, spec/features/saml/multiple_endpoints_spec.rb, spec/services/saml_endpoint_spec.rb
**Why:** We require logout requests to be signed but not all SAML
clients send signed logout requests by default. Turning this on caused
certain SAML clients that weren't previously sending SLO requests to us
to start sending SLO requests, so this allows us to ease into this.
=> Add feature flag for including SLO in SAML metadata

app/views/devise/passwords/new.html.erb
**Why**: So that it matches the expected layout via Figma flow designs, and is consistent with other "Submit" (2.5rem vertical margin) + "Page Footer" (2rem top margin) combinations.
Refer to "Authentication for Partners" Figma document for reference design.
I've been resetting my password a lot as part of ongoing identity verification work, and it's been bothering me to look at it 😉 
Before|After
---|---
=> Fix margins for "Forgot Password" form

app/controllers/verify_controller.rb, app/javascript/packages/form-steps/form-steps.spec.tsx, app/javascript/packages/form-steps/form-steps.tsx, app/javascript/packages/form-steps/index.ts, app/javascript/packages/form-steps/use-history-param.spec.tsx, app/javascript/packages/form-steps/use-history-param.ts, app/javascript/packages/verify-flow/hooks/use-initial-step-validation.spec.ts, app/javascript/packages/verify-flow/hooks/use-initial-step-validation.ts, app/javascript/packages/verify-flow/hooks/use-session-storage.spec.ts, app/javascript/packages/verify-flow/hooks/use-session-storage.ts, app/javascript/packages/verify-flow/verify-flow.spec.tsx, app/javascript/packages/verify-flow/verify-flow.tsx, spec/controllers/verify_controller_spec.rb, spec/javascripts/support/dom.js
**Why**:
* So that we can push user to the correct step in the flow if the user enters at the root path
* So that we can prevent a user from reaching steps which they don't yet have the prerequisites
* So that the URL always reflects the current step (`/verify/v2` vs. `/verify/v2/personal_key`)
Kinda difficult to test before we've got the password confirmation step implemented, but you can at least verify that the URL updates itself to reflect the current step:
1. Set `idv_api_steps_enabled: '["personal_key","personal_key_confirm"]'` in local `config/application.yml`
2. Sign in
4. Complete proofing flow up to personal key page
5. Observe URL is `/verify/v2/personal_key` (previously `/verify/v2`)
=> LG-6271: Validate IdV app values to push user to the correct first step

app/forms/api/profile_creation_form.rb, app/javascript/packages/document-capture/components/document-side-acuant-capture.jsx, app/javascript/packages/document-capture/services/upload.js, app/javascript/packages/form-steps/form-error.spec.ts, app/javascript/packages/form-steps/form-error.ts, app/javascript/packages/verify-flow/services/api.spec.ts, app/javascript/packages/verify-flow/services/api.ts, app/javascript/packages/verify-flow/steps/password-confirm/password-confirm-step.tsx, app/javascript/packages/verify-flow/steps/password-confirm/submit.spec.ts, app/javascript/packages/verify-flow/steps/password-confirm/submit.ts, spec/controllers/api/verify/password_confirm_controller_spec.rb, spec/forms/api/profile_creation_form_spec.rb
**Why**: So that the user only proceeds to the next step with a valid submission, and so that they know what they need to do to correct the issue.
1. Set `idv_api_enabled_steps: '["password_confirm","personal_key","personal_key_confirm"]'` in local `config/application.yml`
2. Sign in
4. Complete proofing flow up to password confirmation page
5. Submit the page with an empty field, or an incorrect password
6. Observe that an error alert message is shown
In the screenshot below, note that "Before" shows that the application would previously crash, due to assumptions that the API request would have been successful.
Before|After
---|---
=> LG-6139: Handle and display password confirm errors

app/javascript/packages/form-steps/form-steps.spec.tsx, app/javascript/packages/form-steps/form-steps.tsx, spec/javascripts/packages/document-capture/components/document-capture-spec.jsx, spec/javascripts/packages/document-capture/components/selfie-capture-spec.jsx
Regression of #6222
**Why**: Since not all "fields" will be associated with an input element, as is the case in the desktop strict liveness selfie capture step.
This resolves an issue where it is not possible to continue identity proofing for the **unshipped, disabled** strict liveness step of document capture.
**Steps to reproduce:**
1. On desktop, go to https://int-identity-oidc-sinatra.app.cloud.gov/?ial=2
2. Click "Sign in"
3. Complete proofing up to document capture
4. Add fake images and click "Continue"
5. Capture a photo of yourself
6. Click "Submit"
Before: Nothing happened. Error in console "TypeError: o.checkValidity is not a function".
After: Form submits.
Relevant code:
https://github.com/18F/identity-idp/blob/f25da61cc45455d1791d68b0d4c81bb520eef4ab/app/javascript/packages/do …
=> Support non-input element ref assignment for FormSteps

app/views/forgot_password/show.html.erb, app/views/sign_up/emails/show.html.erb, config/initializers/simple_form.rb
**Why**: So that hidden inputs don't affect the page layout.
Notably, this removes an unexpectedly-large gap between the password field and "Sign In" button on the Sign In page which is not intended, per Figma design references (see "Authentication for Partners").
Most all SimpleForm inputs use the same "wrapper", which applies default styling for inputs, including a bottom margin of 2rem. Since hidden inputs are expected to be... well, hidden... they should not affect page layout.
This does impact a number of existing inputs using `as: :hidden`. A "safer" (lazier) option would have been to [use `input_field` instead](https://github.com/heartcombo/simple_form#stripping-away-all-wrapper-divs), or `wrapper: false` as we already do in a few places. But since it seems reasonable this should …
=> Remove default wrapper and margin from hidden inputs

app/services/doc_auth/mock/result_response_builder.rb, app/services/pii/cacher.rb, config/application.yml.default, config/initializers/session_store.rb, lib/identity_config.rb, lib/idp/constants.rb, lib/legacy_session_encryptor.rb, lib/session_encryptor.rb, spec/factories/profiles.rb, spec/features/idv/doc_auth/verify_step_spec.rb, spec/lib/session_encryptor_spec.rb, spec/services/analytics_spec.rb, spec/services/doc_auth/mock/result_response_builder_spec.rb, spec/support/fake_analytics.rb, spec/support/features/doc_auth_helper.rb, spec/support/idv_examples/sp_requested_attributes.rb
Currently, we double encrypt the entire web session for a user.  When saving a session, first it is converted to JSON, then encrypted with AES, then with KMS, and then put into Redis.  The reverse process happens when the session is loaded.
This safe-by-default method is straightforward conceptually and in implementation, but imposes costs and friction in other ways.  We have added more and more to session storage, and KMS can only encrypt 4kB per API call, which leads to us [chunking the string](https://github.com/18F/identity-idp/blob/7c1ecde/app/services/encryption/kms_client.rb#L44-L50) and having to make multiple calls to KMS.  Certain values we store can be quite large, which inflates the session size significantly in some contexts.  The KMS API calls now take up a sizeable portion …
=> Partial KMS session encryption

app/components/page_footer_component.rb, app/javascript/packages/verify-flow/start-over-or-cancel.tsx, app/views/devise/sessions/new.html.erb, app/views/idv/doc_auth/_start_over_or_cancel.html.erb, app/views/idv/doc_auth/welcome.html.erb, app/views/idv/gpo_verify/index.html.erb, app/views/shared/_cancel.html.erb, app/views/shared/_cancel_or_back_to_options.html.erb, app/views/two_factor_authentication/sms_opt_in/error.html.erb, app/views/two_factor_authentication/sms_opt_in/new.html.erb, app/views/users/phone_setup/index.html.erb, app/views/users/piv_cac_authentication_setup/error.html.erb
**Why**:
- Because the implemented layout should conform to design specifications
- Updating to use common page footer component ensures consistency and allows for single point of update for future revisions
General expectation is:
- 2rem top margin for footer section
- 1rem padding for contents of footer section (including top "contents", such as "Start Over")
I'd observed this imbalance when implementing "Start Over" and "Cancel" for the IdV application in #6350.
Note that identity proofing layout may be subject to more changes pending implementation of LG-5258, as well as FSMv2 refactor of LG-4159. As such, I didn't spend the time trying to refactor "Start Over or Cancel" links to use the page footer component, and instead adjusted the layout ad hoc.
A couple examples: …
=> Adjust page footer spacing to match layout design specs

app/components/clipboard_button_component.ts, app/components/password_toggle_component.ts, app/components/print_button_component.ts, app/components/spinner_button_component.ts, app/components/validated_field_component.js, app/javascript/packages/clipboard-button/README.md, app/javascript/packages/clipboard-button/index.ts, app/javascript/packages/password-toggle/index.ts, app/javascript/packages/print-button/README.md, app/javascript/packages/print-button/index.ts, app/javascript/packages/spinner-button/index.ts, app/javascript/packages/step-indicator/README.md, app/javascript/packages/step-indicator/index.ts, app/javascript/packages/validated-field/index.ts, app/javascript/packs/step-indicator.js
**Why**: So that React is not included in bundles which are expecting to use only the native custom element implementation.
There isn't expected to be a net reduction in bundle size (i.e. no celebration warranted), but instead resolves a regression in the form of inflated bundle sizes, caused by the introduction of a pattern of workspace packages which export both custom element and React component implementations of a UI component.
Ideally, this could also be addressed using [Webpack tree shaking features](https://webpack.js.org/guides/tree-shaking/). In particular, the custom element definition is expected to be the only side-effecty file of the package. Thus, it would be expected that defining something like `"sideEffects": ["./print-button-element.ts"]` in `package.json` would suffice …
=> Reduce JavaScript size by importing custom element definitions directly

app/javascript/packages/verify-flow/verify-flow-alert.spec.tsx, app/javascript/packages/verify-flow/verify-flow-alert.tsx, app/javascript/packages/verify-flow/verify-flow.tsx
**Why**: For feature parity with the existing password confirmation step, we should show a success alert message for users who have just confirmed their address by phone verification.
You will need to set the step as enabled in your local `config/application.yml`:
```yml
development:
idv_api_enabled_steps: '["password_confirm","personal_key","personal_key_confirm"]'
```
2. Sign in
4. Complete proofing flow up to password confirmation step
6. Observe success alert at the top of the password confirmation step
Before|After
---|---
=> IdV app: Add alert message for password confirmation step

config/i18n-tasks.yml, config/locales/account/en.yml, config/locales/account/es.yml, config/locales/account/fr.yml, config/locales/forms/en.yml, config/locales/forms/es.yml, config/locales/forms/fr.yml, config/locales/service_providers/en.yml, config/locales/service_providers/es.yml, config/locales/service_providers/fr.yml
**Why**:
- So that the list is an accurate reflection of used keys
- So that all translation data is expected to be used in the application
- To minimize and discourage use of this override in favor of inline configuration
The general approach here was to comment out the configuration, running `i18n-tasks` and adding back only the keys confirmed to be in use.
Since some translations are referenced dynamically (typically why one would use this configuration), I'd appreciate a second set of eyes that the removed translation strings are actually unused.
=> Remove unnecessary or outdated i18n-tasks unused keys

app/javascript/packages/verify-flow/steps/personal-key-confirm/personal-key-confirm-step.tsx, app/views/shared/_footer_lite.html.erb, app/views/sign_up/registrations/_required_pii_accordion.html.erb, config/locales/devise/en.yml, config/locales/devise/es.yml, config/locales/devise/fr.yml, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml, config/locales/shared/en.yml, config/locales/shared/es.yml, config/locales/shared/fr.yml
[LG-6120](https://cm-jira.usa.gov/browse/LG-6120)
**What**
This is the last and final subtask of[ LG-5774](https://cm-jira.usa.gov/browse/LG-5774), reviewing images with empty alt tags to check if they are decorative or informative. This [Figma link](https://www.figma.com/file/uIfsIZTFPPQSbe0hMpo6oL/Confirm-whether-images-are-decorative-or-informative-(LG-6118)?node-id=0%3A1) includes the images which were reviewed, and this [translation doc](https://docs.google.com/document/d/1iwIwxLeMoOo_VSI7bhxm8cGO6HIq5rKVNURIpiuZynM/edit) includes which words were added to the yml locale files.
**Testing Instructions**
1. Go to localhost:3000/verify and create an account
2. While following through the steps, look out for the images in the Figma file listed as Informative 
3. For those listed as …
=> LG-6120 update alt text

app/javascript/packages/document-capture/context/acuant.jsx, app/javascript/packages/document-capture/context/upload.jsx, app/javascript/packages/react-hooks/index.ts, app/javascript/packages/react-hooks/use-object-memo.spec.ts, app/javascript/packages/react-hooks/use-object-memo.ts, app/javascript/packages/verify-flow/verify-flow.tsx
**Why**:
- More concise
- Less error-prone in case of forgotten dependency key
- May encourage memoization of objects when appropriate, by making it less tedious to accomplish
The original idea with this pattern is to try to avoid unnecessary renders of context consumers, where object context values would _always_ be strictly unequal between renders unless memoized (`{} !== {}`). However, when trying to find some resources justifying the pattern, I found more resources in favor of avoiding "premature" memoization, or finding alternative ways to reduce re-renders ([[1]](https://github.com/facebook/react/issues/15156#issuecomment-474590693)[[2]](https://overreacted.io/before-you-memo/)[[3]](https://kentcdodds.com/blog/usememo-and-usecallback)). That being said, I still think there is some …
=> Refactor React object memoization using custom hook

.gitlab-ci.yml
GitLab uses a different Redis host and this fixes the URL so that the Redis URL added by #6351 works in GitLab
=> Fix Redis URLs in GitLab CI

app/services/revoke_service_provider_consent.rb, spec/services/revoke_service_provider_consent_spec.rb
Fixes a bug where a verified user who revokes consent from an SP, then re-consents to IAL1 has their full original list of consented fields marked as consented.
**Steps to replicate**:
1. Set up verified Login.gov account and sign in to an SP at IAL2 (including consent for attributes like name, SSN, etc)
2. Visit account page on Login.gov and "Disconnect" from that SP
3. Sign in to that SP at IAL1, consent to share email during authentication
4. Sign in to that SP at IAL2 (with additional attributes requested)
**Expected**: User is prompted to consent to share additional verified attributes with the SP
**Actual**: No consent prompt for IAL2 attributes but they are sent anyway
Note: can also test using the new `Step-up` IAL option in the sample apps.
=> Clear the verified attributes when a user disconnects from an app (LG-5981)

scripts/changelog_check.rb
**Why**: to make it clear to developers that they need to separate the changelog message from the rest of the commit message.
=> update changelog_check error message

app/assets/stylesheets/components/_spinner-button.scss, app/components/spinner_button_component.html.erb, app/components/spinner_button_component.rb, app/controllers/api/verify/password_reset_controller.rb, app/controllers/verify_controller.rb, app/javascript/packages/spinner-button/spinner-button.spec.tsx, app/javascript/packages/spinner-button/spinner-button.tsx, app/javascript/packages/verify-flow/context/flow-context.tsx, app/javascript/packages/verify-flow/services/api.ts, app/javascript/packages/verify-flow/start-over-or-cancel.spec.tsx, app/javascript/packages/verify-flow/steps/password-confirm/forgot-password.tsx, app/javascript/packages/verify-flow/steps/password-confirm/password-reset-button.spec.tsx, app/javascript/packages/verify-flow/steps/password-confirm/password-reset-button.tsx, app/javascript/packages/verify-flow/verify-flow.spec.tsx, app/javascript/packages/verify-flow/verify-flow.tsx, app/javascript/packs/verify-flow.tsx, config/routes.rb, spec/components/spinner_button_component_spec.rb, spec/controllers/api/verify/password_reset_controller_spec.rb
**Why**: So that a user will receive an email to reset their password after confirming to do password reset during identity proofing.
You will need to set the step as enabled in your local `config/application.yml`:
```yml
development:
idv_api_enabled_steps: '["password_confirm","personal_key","personal_key_confirm"]'
```
2. Sign in
4. Complete proofing flow up to password confirmation step
5. Click "Follow these instructions" (adjacent "Forgot your password?")
6. Click Reset Password button
7. Observe that you're redirected to a page confirming password reset, including the correct email for the current user
**Screen recording:** …
=> LG-6205: Add endpoint, button to trigger password reset (IdV app)

app/controllers/concerns/saml_idp_auth_concern.rb, app/controllers/openid_connect/authorization_controller.rb, app/controllers/saml_idp_controller.rb, app/forms/openid_connect_authorize_form.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/forms/openid_connect_authorize_form_spec.rb
**Why:** With the introduction of IALMAX to SAML using the Comparison
attribute, it is now impossible to filter "SP Redirect Initiated" log
events by the actual IAL that was sent back, since the IALContext
returns an IAL of zero by default. This change adds an additional
attribute to SP Redirect Initiated events for SAML and OIDC requests to
track the actual billable IAL (based on whether or not the user has
proofed). This also adds some more comprehensive controller specs for
IALMAX behavior for OIDC.
changelog: Improvements, Authentication, Track billable "IAL" in the event log for successful requests
=> Add tracking of billable IAL to SP Redirect events

lib/session_encryptor.rb, spec/lib/session_encryptor_spec.rb
Previously, we were referencing the attribute encryptor, which uses the `attribute_encryption_key`, but we should not use that for session encryption!
This does not affect production as this encryption format is not enabled yet
=> Ensure correct encryption key is used for new session format

app/javascript/packages/verify-flow/steps/password-confirm/personal-info-summary.spec.tsx, app/javascript/packages/verify-flow/steps/password-confirm/personal-info-summary.tsx
**Why**: To match the existing screen.
Before|After
---|---
=> LG-6202: Collapse excess line break for single-line address

config/routes.rb, spec/features/idv/steps/forgot_password_step_spec.rb, spec/features/idv/steps/review_step_spec.rb
**Why**: So that we can be aware of potential issues sooner than later, we should re-run existing feature specs for IdV screens on the feature-flagged implementations.
These specs caught two issues already, addressed separately in #6374 and #6381.
=> Run integration specs for feature-flagged password confirm step

app/javascript/packages/components/index.ts, app/javascript/packages/components/link.spec.tsx, app/javascript/packages/components/link.tsx, app/javascript/packages/form-steps/history-link.spec.tsx, app/javascript/packages/form-steps/history-link.tsx, app/javascript/packages/form-steps/index.ts, app/javascript/packages/form-steps/use-history-param.spec.tsx, app/javascript/packages/form-steps/use-history-param.ts, app/javascript/packages/verify-flow/steps/password-confirm/forgot-password.tsx, app/javascript/packages/verify-flow/steps/password-confirm/password-confirm-step.spec.tsx, app/javascript/packages/verify-flow/steps/password-confirm/password-confirm-step.tsx, spec/features/idv/steps/forgot_password_step_spec.rb
**Why**: Because it looks and behaves like a link, it should carry semantics of a link, supporting native behavior such as opening in a new tab.
=> Revise password confirmation "Forgot Password" as link

app/models/email_address.rb, spec/models/email_address_spec.rb
(discovered during our wargames exercise today)
**Why**: To ensure smoother key rotations
changelog: Bug Fixes, Attribute encryption, Update behavior for rotated keys for email
=> Look up emails by previous key fingerprints

app/jobs/reports/combined_invoice_supplement_report.rb, spec/jobs/reports/combined_invoice_supplement_report_spec.rb
**Why**: This data exists at the IAA level in the report, but
breaking it down by issuer helps with more complex agreements
=> Add per-issuer unique user columns to combined invoice report (LG-6333)

app/jobs/reports/verification_failures_report.rb, app/services/verification_failures_report.rb, config/initializers/job_configurations.rb, db/primary_migrate/20220517103312_add_back_image_submit_at_to_doc_auth_logs.rb, db/schema.rb, spec/features/reports/doc_auth_funnel_report_spec.rb, spec/jobs/reports/verification_failures_report_spec.rb
**Why**: Right now DOCUMENT_FAIL conditions are triggered when the entire image set is rejected by the back end vendor.   We are going to add to that users that at least attempted to submit a back image to make it behave more like the drop offs report.  Technically they will not be the same because the drop offs report just looks at counts and a welcome timestamp in range (so technically it's reporting the furthest the user ever got) and not the daily errors.  I'm also adding in a little buffer to allow for users that submit for the day but then restart the process either within the same session or within the buffer of 23 hours since the report currently runs every 24 hours. (ie welcome step will actually have a greater timestamp then the failed submit). Also renaming the report …
=> LG-6293 Add more DOCUMENT_FAIL conditions to verification failures report

Makefile, spec/rails_helper.rb
**Why**: So that developers don't need to be aware of and expend the effort to run `yarn build` every time before running a JavaScript-enabled feature spec, in order to avoid CSP errors related to the external Webpack dev server host.
1. Run `rspec spec/features/visitors/i18n_spec.rb:68`
2. Observe in output...
```
Bundling JavaScript...
yarn build
...
```
=> Bundle JavaScript on-demand for JS feature specs

app/forms/two_factor_options_form.rb, spec/forms/two_factor_options_form_spec.rb
This ticket fixes a bug that emerged after #6278 and #6276 were completed
Current state: In setting up an account, the user would select one 2FA method (except for phone due to Kantara requirements). Once setup is complete, if the user selects the option to add a second MFA method, they will not be proceed with phone setup due to the validation added for 
Future state: If the user selects phone as their sole additional authentication method, the user will be able to select the phone option and proceed with setup.
After
=> LG-6274: Allow users to select phone as their sole second option

app/views/sign_up/registrations/_required_pii_accordion.html.erb
One tweak for LG-6120 found during acceptance, we were missing an alt tag for ssn key image even though alt tags were added for all images next to it. Since image is the same as one above, I used the same yaml translation reference [See slack thread here](https://gsa-tts.slack.com/archives/CNCGEHG1G/p1653057149438159?thread_ts=1652897560.434099&cid=CNCGEHG1G).
=> LG-6120 SSN alt image

app/controllers/users/backup_code_setup_controller.rb, app/controllers/users/piv_cac_authentication_setup_controller.rb, app/controllers/users/totp_setup_controller.rb, app/controllers/users/webauthn_setup_controller.rb, app/decorators/mfa_context.rb, app/policies/mfa_policy.rb, app/views/accounts/_auth_apps.html.erb, app/views/accounts/_backup_codes.html.erb, app/views/accounts/_piv_cac.html.erb, app/views/accounts/_webauthn_platform.html.erb, app/views/accounts/_webauthn_roaming.html.erb, app/views/users/edit_phone/_remove_phone.html.erb, spec/controllers/users/backup_code_setup_controller_spec.rb, spec/decorators/mfa_context_spec.rb, spec/policies/user_mfa_policy_spec.rb, spec/views/accounts/two_factor_authentication/show.html.erb_spec.rb, spec/views/users/edit_phone/remove_phone.html.erb_spec.rb
When the multi-mfa-selection feature is turned on we will want to prevent a user's ability to remove their last unrestricted mfa method.
We currently do not display the option to remove an mfa method if it is their last one. I added a method that checks the multi-mfa feature flag, and if it is set to true, does not include phone configurations when determining how many mfa methods they have configured.
=> Lg 6219 prevent removing last non restricted mfa

app/services/data_requests/lookup_shared_device_users.rb, lib/tasks/data_requests.rake, spec/services/data_requests/lookup_shared_device_users_spec.rb
**Why**: We've had issues with this script running into infinite recursion or large groups of related users. This commit prevents that by stopping at a certain depth instead of building a full map of shared devices.
When we wrote this script, we did not have an index on the cookie_uuid column which mean that querying against cookie_uuids was slow and expensive. We now have that index so we can afford to take a more simple approach here.
changelog: Internal, Data requests, The script for looking up users who share devices was changed to avoid infinite recursion.
=> Use a depth instead of recursion in the lookup shared device users tooling

config/locales/forms/en.yml, config/locales/forms/es.yml, config/locales/forms/fr.yml
Ticket for change is here: https://cm-jira.usa.gov/browse/LG-6357
Figma for change is here: https://www.figma.com/file/wIOL0ZP4aZvMUjKKuCG2u2/LG-6344-Backup-codes-copy-changes?node-id=0%3A1
Translations are from Gengo.
Running locally:
Deployed to https://idp.ssteiner.identitysandbox.gov/ for testing.
=> changelog: content, backup codes, LG-6357

app/controllers/mfa_confirmation_controller.rb, app/controllers/password_capture_controller.rb, app/controllers/sign_up/passwords_controller.rb, app/controllers/users/passwords_controller.rb, app/controllers/users/reset_passwords_controller.rb, app/services/analytics.rb, app/services/analytics_events.rb, spec/controllers/mfa_confirmation_controller_spec.rb, spec/controllers/sign_up/passwords_controller_spec.rb, spec/controllers/users/passwords_controller_spec.rb, spec/controllers/users/reset_passwords_controller_spec.rb
In this batch:
- PASSWORD_CHANGED
- PASSWORD_CREATION
- PASSWORD_MAX_ATTEMPTS
- PASSWORD_RESET_EMAIL
- PASSWORD_RESET_PASSWORD
=> Migrate analytics events, batch 21 (LG-5940)

spec/rails_helper.rb
**Why**: Avoid potential conflicts for...
1. Environment variables which can affect intended build output expecting Webpack dev server ([source](https://github.com/18F/identity-idp/blob/d7d303fdd55577ccc00e055674b455f19f47a7c1/webpack.config.js#L41-L42))
2. False negatives for Make "nothing to do" if environment variable would impact build artifact, by instead always running the build
Previously: #6392
Slack context: https://gsa-tts.slack.com/archives/C0NGESUN5/p1653077779604529
=> Run feature specs prebuild with unset Webpack env

.rubocop.yml, app/forms/idv/api_image_upload_form.rb, app/jobs/address_proofing_job.rb, app/jobs/resolution_proofing_job.rb, app/models/throttle.rb, app/services/analytics_events.rb, app/services/doc_auth/error_result.rb, app/services/idv/actions/verify_document_action.rb, app/services/idv/actions/verify_document_status_action.rb, app/services/secure_headers_allow_list.rb, app/views/idv/shared/_error.html.erb, lib/identity_job_log_subscriber.rb, lib/tasks/convert_application_yml_to_proper_types.rake, lib/telephony/pinpoint/sms_sender.rb, scripts/changelog_check.rb, spec/controllers/sign_up/completions_controller_spec.rb, spec/controllers/users/backup_code_setup_controller_spec.rb, spec/features/two_factor_authentication/multiple_mfa_sign_up_spec.rb, spec/forms/two_factor_options_form_spec.rb, spec/presenters/two_factor_authentication/piv_cac_selection_presenter_spec.rb, spec/views/accounts/show.html.erb_spec.rb, spec/views/partials/multi_factor_authentication/_mfa_selection.html.erb_spec.rb
**Why**: So that we can more easily ensure consistent indentation, improving readability.
Most of this is pretty straight-forward. The one notable exception is conditional assignment, which expects indentation of the next line to match the assignment operator, leading to some tight column width constraints. For a few of these, I refactored them to ternaries, which don't have the same expectation of alignment to the assignment operator.
Certainly easiest to review with whitespace changes hidden: https://github.com/18F/identity-idp/pull/6395/files?w=1
=> Enable Rubocop IndentationWidth cop

spec/features/idv/steps/phone_otp_delivery_selection_step_spec.rb, spec/features/idv/steps/phone_otp_verification_step_spec.rb, spec/features/idv/steps/phone_step_spec.rb, spec/features/idv/steps/review_step_spec.rb
**Why**: To reduce build time, and since the shared behavior isn't really particular about the specific SP, just that there may be different behavior by the mere presence of some SP ([see source](https://github.com/18F/identity-idp/blob/main/spec/support/idv_examples/cancel_at_idv_step.rb)).
=> Try limiting IdV cancellation shared examples to single SP

db/schema.rb
**Why**: So that there aren't local changes after a developer runs migrations.
Context: https://github.com/18F/identity-idp/pull/6382#discussion_r879570448
=> Sync schema.rb

config/locales/account/en.yml, config/locales/forms/en.yml, config/locales/headings/en.yml, config/locales/instructions/en.yml, config/locales/notices/en.yml, config/locales/two_factor_authentication/en.yml
We're moving mfa labels from title case to sentence case throughout the application. 
1. Face or Touch Unlock becomes Face or touch unlock
2. Security Key becomes Security key
3. Government Employee ID becomes Government employee ID
4. Federal Employee ID becomes Federal employee ID
5. Authentication Application becomes Authentication application
6. Text or Voice Message becomes Text or voice message
7. Backup Codes becomes Backup codes
=> Lg 6428 sentence case for mfa labels

scripts/changelog_check.rb
**Why**: Because otherwise there is effectively no validation for categories, since the previous logic would pick the closest category, regardless if that category was meaningfully "close".
Discussed during Engineering Huddle 2022-05-25
=> Changelog Script: Increase strictness for category validation

app/forms/idv/api_image_upload_form.rb, app/services/idv/data_url_image.rb, spec/services/idv/data_url_image_spec.rb
**Why**: Because in the real world, this class deals with very large image data (high-quality document images), can be called multiple times per proofing attempt (front, back, maybe eventually selfie), and is part of a high-traffic flow (identity proofing).
Specific optimizations:
* Avoid constructing and deconstructing a URI instance from the data URL
* Avoid re-casting the parsed data string to a string (in benchmarking, I observed ~30% degraded performance from `data.to_s` when `data` is already a string)
* Minor optimizations:
* Use `String#end_with?` over regular expression to test for header substring
* ~Limit splits on header when checking content type, assuming only one `;`~ **Edit:** Turns out we don't use `content_type` at all, so it was removed altogether
**Result**
~24x …
=> Optimize DataUrlImage read

app/javascript/packages/secret-session-storage/index.spec.ts, app/javascript/packages/secret-session-storage/index.ts, app/javascript/packages/verify-flow/hooks/use-initial-step-validation.ts, app/javascript/packages/verify-flow/hooks/use-session-storage.spec.ts, app/javascript/packages/verify-flow/hooks/use-session-storage.ts, app/javascript/packages/verify-flow/verify-flow.spec.tsx, app/javascript/packages/verify-flow/verify-flow.tsx, app/javascript/packs/verify-flow.tsx
**Why**: So that lingering values don't remain beyond the completion of identity verification, even if those values would have been encrypted.
=> Clear session values when flow is complete (IdV app)

app/controllers/sign_up/cancellations_controller.rb, app/models/concerns/email_address_callback.rb, app/models/user.rb, app/services/send_sign_up_email_confirmation.rb, app/views/sign_up/cancellations/new.html.erb, config/application.yml.default, config/routes.rb, lib/identity_config.rb, spec/controllers/sign_up/cancellations_controller_spec.rb, spec/controllers/sign_up/email_confirmations_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/factories/users.rb, spec/features/saml/ial1/account_creation_spec.rb, spec/features/users/sign_up_spec.rb, spec/services/send_sign_up_email_confirmation_spec.rb, spec/support/features/session_helper.rb
This PR is the intersection of a couple things.  Initially, the goal was to continue reducing the number of `DeprecatedUserAttributes` and I noticed the only place the `confirmation_token` on the `users` table was being directly queried was when cancelling account sign up.  The column is already unused and null, meaning the account cancellation was not working as intended.  There is also a bit of crossover with #6247 (where we were not properly validating the email confirmation token).
The combination of problems resulted in a few changes:
1. Fixing the account cancellation to read the confirmation token from `EmailAddress` instead of `User`
2. Adding proper validation to ensure we don't delete accounts based on on invalid token
3. Moving the deletion route into the same controller as the …
=> Fix account sign up cancellation

app/components/javascript_required_component.rb
**Why**: Because a user would expect those support links to go to the correct destination.
The two links were accidentally switched places 🙃 (h/t @Kamal-Munshi for spotting)
=> LG-6351: Fix support links for Edge, Firefox

app/javascript/packages/password-toggle/password-toggle.spec.tsx, app/javascript/packages/password-toggle/password-toggle.tsx, app/javascript/packages/validated-field/validated-field.spec.tsx, app/javascript/packages/validated-field/validated-field.tsx, app/javascript/packages/verify-flow/steps/password-confirm/password-confirm-step.spec.tsx, app/javascript/packages/verify-flow/steps/password-confirm/password-confirm-step.tsx, app/javascript/packages/verify-flow/steps/password-confirm/submit.ts, package.json, yarn.lock
**Why**: For improved consistency with the existing screen, to avoid flashing content and perform validation client-side when possible (e.g. don't send empty password).
**Specifics:**
- Use `required` on the password field in combination with `ValidatedField` to prevent submission for empty field
- Always show the phone success alert (will confirm, but I believe this is how it works in production today, since otherwise it can be awkward and jarring to juggle when/if to show success, error, or no alert messaging)
- Allow display of errors at field-level when not associated with form submission (i.e. required validation)
**Screen recording:**
https://user-images.githubusercontent.com/1779930/170705300-62beb626-0084-4533-9e03-8e0657d6a357.mov
=> Improve form validation for password confirm step

app/policies/two_factor_authentication/webauthn_policy.rb, app/views/accounts/show.html.erb, spec/policies/webauthn_login_option_policy_spec.rb, spec/views/accounts/show.html.erb_spec.rb
We've had a couple of reported instances ([1](https://gsa-tts.slack.com/archives/C0NGESUN5/p1647610831587719), [2](https://gsa-tts.slack.com/archives/CG64NU5C7/p1652806389709729?thread_ts=1643736538.278459&cid=CG64NU5C7)) where users with multiple different 2FA methods have not been able to find where they can manage their existing non-phone 2FA methods.  The current account home page lists a handful of account aspects, and distinctly includes only the phone management template, even if you have none configured, and does not display other methods.
This PR aims to fix this inconsistency and improve clarity by switching the account page to list all _existing_ 2FA methods.
| Old | New |
|----|------|
| ![image](https://user-images.githubusercontent.com/1430443/169170390-7fc0767e-0ae6-401d-a9c …
=> Show configured 2FA on account page (LG-6366)

config/routes.rb, spec/controllers/users/sessions_controller_spec.rb
Relevant [Slack thread](https://gsa-tts.slack.com/archives/C0NGESUN5/p1654010545842009) where the issue was raised that a destructive action should probably not be behind a GET route
To softly deprecate the GET route and keep backwards compatibility, this PR only adds the route.  The next set of changes can switch existing references within Login.gov.
=> Add DELETE route for session logout

app/controllers/verify_controller.rb, app/javascript/packages/verify-flow/context/address-verification-method-context.spec.tsx, app/javascript/packages/verify-flow/context/address-verification-method-context.tsx, app/javascript/packages/verify-flow/index.ts, app/javascript/packages/verify-flow/steps/password-confirm/password-confirm-step.spec.tsx, app/javascript/packages/verify-flow/steps/password-confirm/password-confirm-step.tsx, app/javascript/packages/verify-flow/steps/personal-key/personal-key-step.spec.tsx, app/javascript/packages/verify-flow/steps/personal-key/personal-key-step.tsx, app/javascript/packages/verify-flow/verify-flow-step-indicator.spec.tsx, app/javascript/packages/verify-flow/verify-flow-step-indicator.tsx, app/javascript/packages/verify-flow/verify-flow.tsx, app/javascript/packs/verify-flow.tsx, spec/controllers/verify_controller_spec.rb, spec/features/idv/steps/confirmation_step_spec.rb, spec/support/idv_examples/confirmation_step.rb
**Why**: For parity with the existing experience, users should expect to see content specific for the GPO verification method (e.g. status alerts, "Come back later" page after completion, pending step indicator status).
Also, this addresses an issue where previously, the absence of a phone value was used in determining method, but this isn't accurate, since phone may be assigned if the user already have a verified phone number ([source](https://github.com/18F/identity-idp/blob/d9da3df889d87e4b2e917a394330487346280b13/app/services/idv/steps/doc_auth_base_step.rb#L63)).
1. With locally-running IdP, go to http://localhost:3000
1. Sign in
1. Go to http://localhost:3000/verify
1. Complete proofing flow up to phone address verification step
1. Choose to verify your …
=> LG-6499: Update missing GPO-specific content (IdV app)

app/javascript/packages/verify-flow/steps/personal-key-confirm/personal-key-input.spec.tsx, app/javascript/packages/verify-flow/steps/personal-key-confirm/personal-key-input.tsx, spec/support/shared_examples_for_personal_keys.rb
**Why**: Because the primary user interaction we expect here is for the user to paste the personal key after clicking the "Copy" button on the personal key display page.
2. Sign in
4. Complete proofing flow up to personal key screen
5. Copy personal key
6. Click Continue
7. Paste personal key **by some other means than <kbd>Cmd + V</kbd>**, e.g. right-click or Mac "Edit" dropdown
Before: Content is not pasted
After: Content is pasted
This may be a bug in Cleave.js, where after the input value is changed, it tries to format the value, and expects to use the _last_ input value ([[1]](https://github.com/nosir/cleave.js/blob/e3fa6f3637fa6d8ea97ef66ac1957950632b72ab/src/Cleav …
=> Fix paste for personal key confirmation (IdV app)

app/controllers/idv/review_controller.rb, app/controllers/verify_controller.rb, app/javascript/packs/verify-flow.tsx, spec/controllers/idv/review_controller_spec.rb, spec/controllers/verify_controller_spec.rb
**Why**: It was originally implemented with the expectation that we might ship the personal key step independently, but with stabilization of the password re-entry step, it's most likely we'd ship them together now. This allows for some simplification of the handling for initializing the IdV application.
=> Remove support for password confirm as first step of IdV app

spec/features/idv/doc_auth/document_capture_step_spec.rb, spec/features/idv/doc_capture/document_capture_step_spec.rb, spec/features/visitors/set_password_spec.rb, spec/support/shared_examples_for_personal_keys.rb
**Why**: Since the concern of these assertions is common, and to reduce the runtime of the specs, since each test case will spin up a fresh browser tab and complete all the pre-steps required to get to these screens.
Discovered with some regex searching in `spec/support` and `spec/features` directories: `do[\s\n]+expect\(page\).to have_content`
=> Merge content-only JavaScript-enabled feature spec cases

spec/controllers/users/two_factor_authentication_controller_spec.rb
**Why**: Assertions which rely on precise timing are likely to fail due to slow processing. Instead, freeze time to avoid bounding timeframes.
Example: https://app.circleci.com/pipelines/github/18F/identity-idp/73937/workflows/ed474cae-09a5-4fed-b055-b1664e0365e3/jobs/128324/parallel-runs/1
I was tempted to fix more of these, since there are quite a few `be_within` assertions which are testing in much the same way this was. But for the sake of pragmatism and effort, I limited it to the one I encountered for now.
=> Fix flakey OTP lockout spec

app/services/doc_auth/mock/result_response_builder.rb, lib/idp/constants.rb, lib/session_encryptor.rb, spec/controllers/api/verify/password_confirm_controller_spec.rb, spec/factories/profiles.rb, spec/features/idv/doc_auth/verify_step_spec.rb, spec/lib/session_encryptor_spec.rb, spec/services/analytics_spec.rb, spec/services/doc_auth/mock/result_response_builder_spec.rb, spec/support/fake_analytics.rb, spec/support/features/doc_auth_helper.rb, spec/support/idv_examples/sp_requested_attributes.rb
**Why**:
- We have automated tests which [attempt to detect PII leaks in event logging](https://github.com/18F/identity-idp/blob/92e2fe738c21d3cb2571ad44276db84e3977dacd/spec/support/fake_analytics.rb#L6-L69), and it's only effective if we use the same PII consistently
- Convenient single source of truth for applicant data at various stages of the proofing process
- Less error-prone
- Real-world example fixed here: The phone number associated with an applicant is expected to follow [a specific normalized format](https://github.com/18F/identity-idp/blob/92e2fe738c21d3cb2571ad44276db84e3977dacd/app/services/idv/phone_step.rb#L80-L85) which wasn't being used correctly in stubbing
=> Use IdV mock PII data consistently

app/javascript/packages/components/index.ts, app/javascript/packages/components/scroll-into-view.spec.tsx, app/javascript/packages/components/scroll-into-view.tsx, app/javascript/packages/verify-flow/steps/password-confirm/password-confirm-step.spec.tsx, app/javascript/packages/verify-flow/steps/password-confirm/password-confirm-step.tsx
**Why**: So that the user isn't left confused about why the page hasn't changed when submitting the password confirmation step with an incorrect password.
This was discovered in a recent bug bash, and regresses the current production behavior, where the server-side form submission would reset the scroll position of the page.
**Screen recording:**
_Before:_
https://user-images.githubusercontent.com/1779930/171874590-94045d0d-342c-48c0-8e1a-2aa6e20f178d.mov 
_After:_
https://user-images.githubusercontent.com/1779930/171874597-c74d6faf-7134-4e1d-87f1-54b7cd13333e.mov
=> Scroll alert into view on password confirm error (IdV app)

app/controllers/two_factor_authentication/webauthn_verification_controller.rb, spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
Currently all webauthn authentications are logged as `webauthn_platform` due to a small bug in checking whether we are verifying a platform or roaming authenticator.  We pass in an empty `platform=` parameter, which leads `params[:platform]` to be a truthy empty string.
This PR makes the check a little stricter and adds the param to the spec to better mirror the usage in deployed environments.
=> Fix logging of webauthn authentications
