18F/identity-idp

app/presenters/navigation_presenter.rb
spec/factories/users.rb
spec/presenters/navigation_presenter_spec.rb

If a user has a personal key, but does not have an active perofile (ex: has reset their password), we should not offer the option to regenerate the personal key
[Relevant slack thread](https://gsa-tts.slack.com/archives/C0NGESUN5/p1654281440310989)

Only show reset personal key if user has an active profile

---

config/application.yml.default

This has been enabled in deployed environments (including prod) and appears to be stable, so it should be safe to enable by default now

Enable Session Encryption v2 everywhere

---

app/controllers/users/two_factor_authentication_controller.rb
app/services/analytics_events.rb
app/services/idv/send_phone_confirmation_otp.rb
spec/controllers/idv/resend_otp_controller_spec.rb
spec/controllers/users/two_factor_authentication_controller_spec.rb

We currently depend on a bit of the surrounding events to analyze telephony like `OTP: Delivery Selection`, but those events are a bit removed from the actual API call to send the OTP.  This PR adds the attributes that appear in other events to `Telephony: OTP sent` so that important context is logged alongside the result of the call to send an OTP via telephony.  It should be very helpful in improving our troubleshooting and understanding of telephony usage patterns.
These changes make `Telephony: OTP sent` and `IdV: phone confirmation otp sent` more similar, and we could eventually consider merging them (with the `context` attribute to distinguish IDV).  This also documents the OTP sent event in the new format.

Include more context when logging telephony sent events

---

app/presenters/two_factor_authentication/auth_app_selection_presenter.rb
app/presenters/two_factor_authentication/backup_code_selection_presenter.rb
app/presenters/two_factor_authentication/phone_selection_presenter.rb
app/presenters/two_factor_authentication/piv_cac_selection_presenter.rb
app/presenters/two_factor_authentication/selection_presenter.rb
app/presenters/two_factor_authentication/webauthn_platform_selection_presenter.rb
app/presenters/two_factor_authentication/webauthn_selection_presenter.rb
app/presenters/two_factor_options_presenter.rb
config/locales/two_factor_authentication/en.yml
config/locales/two_factor_authentication/es.yml
config/locales/two_factor_authentication/fr.yml

**Why**: Because they're unused since #5989

Remove unused MFA security labels

---

spec/features/users/sign_in_spec.rb

**Why**: These take a long time, instead of the full
matrix of { IAL1, IAL2 } x { OIDC, SAML }, we cover
one of each which should catch major regressions

Remove duplicative tests

---

spec/services/funnel/doc_auth/log_document_error_spec.rb

I spotted something fishy in some CI output, tracked it down and cleaned it up
```
.......................................................................................................................................................................................................................................................................................................................................................................................................................true
................................................................................................................................................................................................................................................................................................................. …
```

Remove an extra puts statement in specs

---

config/application.yml.default

**Why**: There was a misunderstanding about support coverage, which is in-fact unchanged.
This keeps the config-based implementation introduced in #6444, while reverting the list of states to its previous values.
It's planned to patch this into the deploy branch (#6464), for convenience to avoid configuring individual environments.

Revert AAMVA supported states

---

scripts/changelog_check.rb
spec/scripts/changelog_check_spec.rb

**Why**: Since it avoids adding an extra flag in the common use-case of generating a changelog for the current staging branch.
Related discussion: https://github.com/18F/identity-handbook/pull/267#discussion_r891334994

Changelog script: Use current branch as default source

---

app/controllers/application_controller.rb
app/controllers/mfa_confirmation_controller.rb
app/controllers/users/mfa_selection_controller.rb
app/controllers/users/two_factor_authentication_controller.rb
app/presenters/mfa_confirmation_presenter.rb
app/services/marketing_site.rb
app/views/mfa_confirmation/show.html.erb
config/locales/mfa/en.yml
config/locales/mfa/es.yml
config/locales/mfa/fr.yml
config/routes.rb
spec/controllers/application_controller_spec.rb
spec/controllers/users/mfa_selection_controller_spec.rb
spec/presenters/mfa_confirmation_presenter_spec.rb
spec/views/mfa_confirmation/show.html.erb_spec.rb

When we turn on the kantara non restricted feature flag, we want to prevent anyone from signing into their account page with just a phone configured. They will be forced to set up an mfa configuration with something other than phone before they can log in to their account page.
Figma with user flow: https://www.figma.com/file/S1VeH2rR8Xas4aPB9XtSn9/LG-6166-Design-interaction-for-required-second-MFA-(Kantara)?node-id=103%3A4937
Sandbox: https://idp.ssteiner.identitysandbox.gov/

Lg 6218 enforce non restricted mfa

---

app/controllers/test/session_data_controller.rb
config/application.rb
config/initializers/session_store.rb
config/routes.rb
lib/session_store_migration.rb
spec/requests/session_store_migration_spec.rb

Feeling slightly bolder, builds on #6478 to attempt to smoothly rename the last item, the session store key

Rename session key and middleware to migrate existing cookies (LG-6584)

---

app/models/concerns/deprecated_user_attributes.rb
app/models/concerns/user_encrypted_attribute_overrides.rb
app/models/user.rb
lib/tasks/dev.rake
spec/features/users/sign_in_spec.rb

Following up to #6474 to skip reading the `email_fingerprint` and `encrypted_email` columns

Stop querying unused user email columns

---

app/controllers/api/verify/base_controller.rb
app/controllers/api/verify/document_capture_controller.rb
app/controllers/api/verify/password_confirm_controller.rb
app/javascript/packages/verify-flow/services/api.spec.ts
app/javascript/packages/verify-flow/services/api.ts
app/javascript/packages/verify-flow/steps/password-confirm/password-confirm-step.spec.tsx
app/javascript/packages/verify-flow/steps/password-confirm/submit.spec.ts
app/javascript/packages/verify-flow/steps/password-confirm/submit.ts
spec/controllers/api/verify/base_controller_spec.rb
spec/controllers/api/verify/document_capture_controller_spec.rb
spec/controllers/api/verify/password_confirm_controller_spec.rb

Partially extracted from #6483
**Why:** So that usage is more predictable.
This does a few things:
- Consistently renders errors using `render_errors` base controller helper
- In doing so, updates all references to consistently use "errors" (plural) response property
- Allows `required_step` to be explicitly `nil` to avoid requiring feature flag step enabled (alternative to issue described in #6492)
- Only allow "effective user" (hybrid document capture session) in document capture endpoints by splitting overridable `user_authenticated_for_api?` base controller method

Reconcile inconsistencies with verify API implementations

---

app/controllers/application_controller.rb
app/controllers/users/sessions_controller.rb
app/decorators/service_provider_session_decorator.rb
app/decorators/session_decorator.rb
app/services/irs_attempts_api/attempt_event.rb
app/services/irs_attempts_api/tracker.rb
app/services/irs_attempts_api/tracker_events.rb
db/primary_migrate/20220613174442_add_irs_attempts_api_enabled_to_service_provider.rb
db/schema.rb
spec/controllers/api/irs_attempts_api_controller_spec.rb
spec/decorators/service_provider_session_decorator_spec.rb
spec/features/irs_attempts_api/event_tracking_spec.rb
spec/rails_helper.rb
spec/requests/irs_attempts_api_spec.rb
spec/services/irs_attempts_api/attempt_event_spec.rb
spec/services/irs_attempts_api/redis_client_spec.rb
spec/services/irs_attempts_api/tracker_spec.rb
spec/support/features/irs_attempts_api_tracking_helper.rb
spec/support/oidc_auth_helper.rb

This commit includes a number of changes to implement features of the attempts API:
1.) A boolean is added to Service Providers to indicate whether they can use the Attempts API
2.) A param is supported on the OIDC auth endpoint to specify an Attempts API session ID
3.) Logic is added to track events if the SP is Attempts API enabled and a session ID was included in the auth request
4.) Code was added to track email/password attempts in the Attempts API so we can make sure it all works

Add the ability for IRS service providers to start tracking events

---

app/models/user.rb
db/primary_migrate/20220621170346_drop_users_email_columns.rb
db/schema.rb

Should not be merged until #6474 and #6480 are deployed everywhere

Drop users email columns

---

app/javascript/packages/verify-flow/index.ts
app/javascript/packages/verify-flow/user-bundle.spec.ts
app/javascript/packages/verify-flow/user-bundle.ts
app/javascript/packs/verify-flow.tsx

**Why**: To avoid crashes when loading the verify flow.
- Problem 1: JWTs are encoded using base64url, not base64, which uses a modified alphabet and crashes when naively trying to parse with `atob` (see [RFC 7519, Section 7.2](https://datatracker.ietf.org/doc/html/rfc7519#section-7.2) and [RFC 4648, Section 5](https://datatracker.ietf.org/doc/html/rfc4648#section-5))
- Problem 2: Decoded values could display incorrect characters for some unicode character values
**Open Questions:**
- Maybe we should use a library instead of rolling our own? 🙃
Repeat "Steps to reproduce" as outlined in LG-6576 and verify expected outcome.

LG-6576: Fix JWT parse for base64url characters, unicode encoding

---

app/models/user.rb

**Why**: It's been moved to the phone_configurations table
See https://github.com/18F/identity-idp/pull/6488/files#r898215327
"do not merge" because this is a PR into https://github.com/18F/identity-idp/pull/6488, so let's have that merge before trying this (to minimize merge conflicts)

Ignore users.encrypted_phone column

---

app/controllers/users/backup_code_setup_controller.rb
config/routes.rb
spec/controllers/users/backup_code_setup_controller_spec.rb

Related to LG-6112, https://github.com/18F/identity-idp/pull/6498
Wait for that to be deployed before merging.
This PR removes related controller method and tests for server side backup code downloads.

Remove server side controller for backup code download, LG-6173

---

app/javascript/packages/verify-flow/context/secrets-context.tsx
spec/features/idv/steps/confirmation_step_spec.rb

**Why**: So that the user can finish the flow after refreshing once receiving the completion URL.
**Testing instructions:**
2. Sign in
4. Complete proofing flow up to personal key step
5. Refresh page
6. Finish proofing flow
_Before_: Clicking "Continue" on the confirmation modal does nothing
_After_: User can continue to next screen

LG-6697: Sync completion URL to session storage

---

app/javascript/app/i18n-dropdown.js
app/views/shared/_footer_lite.html.erb
spec/javascripts/app/i18n-dropdown-spec.js
spec/javascripts/support/dom.js

[LG-6572](https://cm-jira.usa.gov/browse/LG-6572)
**Why**
When a user clicked on a different language in the language dropdown from the FSMv2 flow, they would get redirected back to the first step in FSMv2 because the language dropdown lives in rails and wasn't updated 
As mentioned in [associated Google Doc comment](https://docs.google.com/document/d/1X0V_Tjr97jMNQXAnLU4yyAeQjnVTWDn5z35lOaleWOU/edit?disco=AAAAZ5NRh20), "the problem is that the language picker is static content, so it's already determined where the user should be redirected on the initial page load, which will always be the first step in the React-based flow. We're not updating this as the user progresses through the flow"
**How**
Because we are managing routes using window.history in FSMv2, we monkey patched the …

LG-6572 update language urls to reflect correct path in JS

---

app/controllers/two_factor_authentication/totp_verification_controller.rb
spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb

Context: https://github.com/18F/identity-idp/pull/6368#discussion_r906288807
**Why**:
- For consistency with other MFA verification screens
- So that the analytics method is used
- To prevent an error when visiting the page in local development, since the previous method call was missing the required `context` argument
Previously, the early return based on a feature flag used for local development meant that the event was not being logged in most cases. And when it was being logged, the missing argument raised an exception.

Fix TOTP verification page visit logging

---

app/services/identity_linker.rb

The find and then create sequence has the potential to 500 from a race condition ([NR link](https://one.newrelic.com/nr1-core/errors/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?duration=604800000&state=21e53e46-e7fb-dea8-6c6f-26d2388c1e9d))

Fix 500 when creating new identity

---

app/services/idv/steps/document_capture_step.rb
spec/services/idv/steps/document_capture_step_spec.rb

The stored result may not exist, and we should handle that error appropriately ([NR link 1](https://one.newrelic.com/nr1-core/errors/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?duration=604800000&state=b2736ea6-c54e-4bc8-1656-c4b4174d66a4), [NR link 2](https://one.newrelic.com/nr1-core/errors/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?duration=604800000&state=a8c70fe5-3e3c-f656-18b7-c17d1d73c3e2))

Fix 500 in document capture step

---

app/javascript/packages/build-sass/cli.js
app/javascript/packages/build-sass/index.js
app/javascript/packages/build-sass/package.json
yarn.lock

Previously: https://github.com/18F/identity-idp/pull/5862#issuecomment-1023221169
**Why**: Improve performance of Sass compilation, using an official native Dart binary instead of the compiled-to-JavaScript `sass` implementation.
We had previously been blocked by https://github.com/sass/embedded-host-node/issues/117, which was causing issues with downloading the binary in our build environments. This has since been resolved as of v1.53.0 ([see changelog](https://github.com/sass/embedded-host-node/blob/main/CHANGELOG.md#1530)).
**Performance Impact:**
Average of 5 runs of `yarn build:css`:
_Before:_ 9.9s
_After:_ 4.4s

Switch from sass to sass-embedded

---

app/javascript/packages/document-capture/context/analytics.jsx
app/javascript/packages/document-capture/higher-order/with-background-encrypted-upload.jsx
app/javascript/packs/document-capture.jsx
spec/javascripts/packages/document-capture/higher-order/with-background-encrypted-upload-spec.jsx

Builds on: #6509
**Why**: So that we don't need to maintain multiple separate implementations for tracking errors.

Consolidate JavaScript error tracking

---

app/views/idv/in_person/state_id.html.erb

Increase the width of the ID number field on the in-person proofing state ID page from 268 to 306, as per comment from @lizzieamanning on LG-6091.
**screenshots:**
<details>
<summary>Desktop</summary>
</details>
<details>
<summary>Mobile</summary>
(375px wide)
</details>

LG-6091 Increase width of ID number field on in-person proofing state ID page

---

app/components/block_link_component.html.erb
app/components/block_link_component.rb
app/views/idv/session_errors/warning.html.erb
config/locales/idv/en.yml
config/locales/idv/es.yml
config/locales/idv/fr.yml
spec/components/block_link_component_spec.rb
spec/features/idv/actions/redo_document_capture_action_spec.rb
spec/views/idv/session_errors/warning.html.erb_spec.rb

**Why**: When a user receives a barcode attention result, there's a higher likelihood they will fail the verify step. Allowing them to retake photos may allow them to successfully pass this step.
2. Sign in
5. As front and back image, download and use the YAML file contents at the end of this comment description
6. Press Continue when prompted "We couldn’t read the barcode on your ID."
8. As SSN, use a value which would trigger a verification failure (e.g. `111-11-1111`)
9. Press Continue
10. Press Continue
11. Observe new troubleshooting option
12. Clicking troubleshooting option should take you back to allow you to repeat document capture step …

LG-6402: Add troubleshooting option to retake photos

---

app/javascript/packages/document-capture/components/barcode-attention-warning.spec.tsx
app/javascript/packages/document-capture/components/barcode-attention-warning.tsx

**Why**: So that we can have more insight into the choice that a user is making when presented with a barcode attention warning.

Add analytics for barcode attention warning actions

---

app/javascript/packages/verify-flow/context/flow-context.tsx
app/javascript/packages/verify-flow/start-over-or-cancel.spec.tsx
app/javascript/packages/verify-flow/steps/password-confirm/password-reset-button.spec.tsx
app/javascript/packages/verify-flow/steps/password-confirm/password-reset-button.tsx
app/javascript/packages/verify-flow/verify-flow.tsx
app/javascript/packs/session-timeout-ping.ts
app/javascript/packs/verify-flow.tsx
spec/javascripts/packs/verify-flow-spec.ts
tsconfig.json

**Why**: So that we're consistently handling flow completion behaviors, reducing risk profile by proactively removing the encrypted `sessionStorage` value.
Specifically, this covers:
- Clear session storage on session timeout (03ea9e12004cb2b16ef428fbf1fc4fed29127b0e)
- Handle IdV forgot password confirmation as flow completion (df329fa7412fb6c3e75b6a1cb0e254dcdcc6ecb4)
This is easier to test by configuring `config/application.yml` setting `session_timeout_in_minutes` to a low number (e.g. `session_timeout_in_minutes: 2`).
2. Sign in
4. Complete proofing flow up to password re-entry
5. In developer tools console, enter `sessionStorage.length` and observe value is `1`
6. Perform …

Clear session storage on additional IdV flow exit paths (FSMv2)

---

app/javascript/app/i18n-dropdown.js
app/javascript/packages/form-steps/use-history-param.spec.tsx
app/javascript/packages/form-steps/use-history-param.ts
spec/javascripts/app/i18n-dropdown-spec.js

**Why**: Since NewRelic also patches history in a way which conflicts with our initial implementation. Patching is more all-encompassing, but also more fragile (case in point).
Previously: https://github.com/18F/identity-idp/pull/6519

Use custom event for pushState URL changes

---

app/jobs/reports/sp_user_counts_report.rb
app/services/analytics.rb
app/services/analytics_events.rb
app/services/idv/steps/verify_wait_step_show.rb
config/initializers/rack_attack.rb
spec/features/idv/doc_auth/verify_step_spec.rb
spec/jobs/reports/sp_user_counts_report_spec.rb
spec/requests/rack_attack_spec.rb

**Why**: PROOFING_RESOLUTION_RESULT_MISSING, RATE_LIMIT_TRIGGERED, REPORT_REGISTERED_USERS_COUNT, 
REPORT_IAL1_USERS_LINKED_TO_SPS_COUNT, REPORT_IAL2_USERS_LINKED_TO_SPS_COUNT
**How**: REPORT events go to reports.log and are thus not currently documented

LG-5945 Document the rest of analytics events #26

---

app/views/idv/otp_verification/show.html.erb
app/views/shared/_one_time_code_input.html.erb
app/views/two_factor_authentication/otp_verification/show.html.erb
app/views/two_factor_authentication/totp_verification/show.html.erb
app/views/users/totp_setup/new.html.erb
spec/views/shared/_one_time_code_input.html.erb_spec.rb

**Why**:
- Standardize on `ValidatedFieldComponent` as canonical validation approach in effort to move away from `display-if-invalid` and toward the eventual removal of the `form-validation.js` pack.
- Improve accessibility by leveraging advanced features of `ValidatedFieldComponent`
- Relationship between field and error message via `aria-describedby`
Verify no regressions in the behavior of OTP code entry, including OTP and TOTP (and setup processes for each).
**Next steps:**
The only two remaining usages of `display-if-invalid` after these changes are:
- IdV address form
- IdV GPO address form (disabled in production)

Refactor one_time_code_input partial to use ValidatedFieldComponent

---

app/presenters/cancellation_presenter.rb
app/presenters/idv/gpo_presenter.rb
app/presenters/navigation_presenter.rb
app/presenters/piv_cac_authentication_login_presenter.rb
lib/linters/url_options_linter.rb
spec/lib/linters/url_options_linter_spec.rb

Extracted from #6542
**Why**: So that a class needn't define an explicit method just to access the instance variable, where an `attr_reader` would be more conventional and concise.

Support attr methods for url_options linter

---

app/components/status_page_component.html.erb
app/javascript/packages/components/status-page.tsx
app/javascript/packages/verify-flow/steps/password-confirm/forgot-password.tsx
app/views/idv/shared/_error.html.erb

Extracted from https://github.com/18F/identity-idp/pull/6542
**Why:** Based on Figma designs, there should be 2.5rem of top margin above status page action buttons not 2rem.
Refactors `ForgotPassword` component to use `StatusPage` component to consolidate layout updates for these screens.

Update status page layout margins to correct value

---

app/models/user.rb
db/primary_migrate/20220705195340_drop_encrypted_phone_from_users.rb
db/schema.rb

**Why**: It was unused and normalized to the phone_configurations
table. Previously ignored in #6501

Drop users.encrypted_phone column

---

app/javascript/packages/document-capture/components/barcode-attention-warning.tsx
app/views/idv/address/new.html.erb
app/views/idv/in_person/address.html.erb
app/views/idv/in_person/state_id.html.erb
app/views/idv/phone/new.html.erb
app/views/idv/shared/_ssn.html.erb
app/views/idv/shared/_verify.html.erb
config/locales/account/en.yml
config/locales/doc_auth/en.yml
config/locales/doc_auth/es.yml
config/locales/doc_auth/fr.yml
config/locales/forms/en.yml
config/locales/headings/en.yml
config/locales/headings/es.yml
config/locales/headings/fr.yml
config/locales/help_text/en.yml
config/locales/idv/en.yml
config/locales/idv/es.yml
config/locales/idv/fr.yml
config/locales/titles/en.yml
config/locales/titles/es.yml
config/locales/titles/fr.yml
spec/features/idv/doc_auth/address_step_spec.rb
spec/features/idv/doc_auth/verify_step_spec.rb
spec/features/idv/hybrid_flow_spec.rb
spec/features/idv/in_person_spec.rb
spec/support/features/doc_auth_helper.rb

* Updates the verify page's labels to use sentence case ("First name") instead of title case ("First Name")
* Changes "Social Security Number" to "Social Security number" per designs
* Changes "Zip Code" to "ZIP Code"
* Updates the pages where users update their address, state ID information, and Social Security number to have an "Update" button instead of "Continue" button
* Changes the HTML semantics of the verify page key/value pairs to be [HTML description lists](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl) instead of just divs with text
* Moves a bunch of content strings that were previously only used in the doc auth flow but are now also used in the in-person proofing flow. I moved them from doc auth namespaces/files into idv namespaces/files
* Back/cancel/start …

LG-6349 Consistently use 'Update' language on verify and update pages

---

app/controllers/sign_up/registrations_controller.rb
app/controllers/users/phone_setup_controller.rb
app/services/analytics.rb
app/services/analytics_events.rb
spec/controllers/users/phone_setup_controller_spec.rb
spec/controllers/users/two_factor_authentication_setup_controller_spec.rb

Why? More documenting of analytics.

LG-5954 document analytics 33

---

app/javascript/packages/components/block-link.tsx
app/javascript/packages/components/troubleshooting-options.spec.tsx
app/javascript/packages/components/troubleshooting-options.tsx
app/javascript/packages/document-capture/components/barcode-attention-warning.spec.tsx
app/javascript/packages/document-capture/components/barcode-attention-warning.tsx
app/javascript/packages/document-capture/components/document-capture-troubleshooting-options.tsx
app/javascript/packages/document-capture/services/upload.ts
app/javascript/packages/url/README.md
app/javascript/packages/url/add-search-params.spec.ts
app/javascript/packages/url/add-search-params.ts
app/javascript/packages/url/force-redirect.spec.ts
app/javascript/packages/url/force-redirect.ts
app/javascript/packages/url/index.ts
app/javascript/packages/url/remove-unload-protection.spec.ts
app/javascript/packages/url/remove-unload-protection.ts
app/javascript/packs/session-timeout-ping.ts
spec/javascripts/packages/document-capture/components/document-capture-troubleshooting-options-spec.jsx

**Why**: A user who chooses to verify their identity in person should not be warned about leaving the page, since they have already made the choice to leave.
2. Sign in
5. Submit document capture with a [failing ID document](https://developers.login.gov/testing/#testing-identity-proofing)
6. Click option to proof in-person
Before: Prompted about leaving page
After: No prompt when leaving page
The prompt in the following screenshot is the one being removed:

LG-6406: Disable "Leave site?" prompt when starting IPP

---

app/assets/stylesheets/components/_form.scss
app/javascript/packs/form-validation.js
app/views/idv/address/new.html.erb
app/views/idv/gpo/_new_address.html.erb
app/views/idv/gpo_verify/index.html.erb
app/views/idv/in_person/address.html.erb

**Why:** For consistency, improved developer ergonomics, and reduced risk of accessibility regressions.
This continues the work toward an eventual removal of `display-if-invalid` behaviors. After this pull request, only one usage remains in `_validation_message.html.erb` (used by IdV personal key page). The changes here also remove validation-specific handling (e.g. "value missing" or "pattern mismatch"), since only basic support is needed for this last remaining usage.
**Testing instructions:**
Verify no regressions in IdV address field, IdV GPO bounced address field, and GPO verification page:
2. Sign in
4. Complete proofing flow up to "Verify your information" screen
5. Click "Update" in the address section
6. Observe …

Refactor forms to use ValidatedFieldComponent

---

app/controllers/users/piv_cac_authentication_setup_controller.rb
app/controllers/users/piv_cac_login_controller.rb
app/controllers/users/webauthn_setup_controller.rb
app/services/analytics.rb
app/services/analytics_events.rb
app/services/vendor_status.rb
spec/controllers/users/webauthn_setup_controller_spec.rb
spec/services/vendor_status_spec.rb

changelog: Improvements, Analytics, Updated analytics

document-analytics-34

---

app/controllers/api/verify/password_confirm_controller.rb
app/forms/api/profile_creation_form.rb
spec/controllers/api/verify/password_confirm_controller_spec.rb
spec/forms/api/profile_creation_form_spec.rb

**Why**: So that a developer can complete the GPO proofing flow locally.
2. Sign in
4. Complete proofing flow, opting to verify address by mail at the phone step
5. On "Come back later" screen, click Continue
6. On account screen, click to enter the GPO code received by mail
7. Observe there is a code pre-filled
8. Submit the form
9. Observe the profile is confirmed
**Notes:**
Referenced here: 
https://github.com/18F/identity-idp/blob/1e0f7646aa37804f9f4dd42ff1c1d6952985de00/app/controllers/idv/gpo_verify_controller.rb#L13
Assigned in previous flow here:
https://github.com/18F/identity-idp/blob/1e0f7646aa37804f9f4dd42ff1c1d6952985de00/app/controllers/idv/review_controller.rb#L52-L53

IdV API: Set last GPO code for auto-fill in local development

---

app/services/idv/actions/redo_document_capture_action.rb
app/services/idv/steps/doc_auth_base_step.rb
spec/features/idv/actions/redo_document_capture_action_spec.rb
spec/support/features/doc_auth_helper.rb

**Why**: Per the expected behavior in LG-5918, a user should not have to repeat entry of SSN if they choose to retake photos on the "Verify' step after a barcode attention document capture result.
2. Sign in
5. Use barcode attention result YAML test file for fields (see bottom of comment)
6. Submit document capture
7. Press "Continue" when prompted about attention result
8. Complete proofing flow up to "Verify your information step"
9. Click link in warning alert to retake photos
10. Complete proofing flow up to and including document capture
_Before:_ You are on the SSN page
_After:_ You are on the "Verify your information" page, with …

LG-5918: Skip SSN step when retaking doc auth photos after barcode attention

---

app/controllers/openid_connect/authorization_controller.rb
app/controllers/users/backup_code_setup_controller.rb
app/controllers/users/service_provider_inactive_controller.rb
app/controllers/users/sp_handoff_bounced_controller.rb
app/services/analytics.rb
app/services/analytics_events.rb

(This is a re-do of #6569, this time not from a fork.)
Document the following analytics events:
- `SP_HANDOFF_BOUNCED_DETECTED`
- `SP_HANDOFF_BOUNCED_VISIT`
- `SP_INACTIVE_VISIT`
- `BACKUP_CODE_CREATED`

LG-5948: Document more analytics events

---

lib/telephony/pinpoint/sms_sender.rb
spec/lib/telephony/pinpoint/sms_sender_spec.rb

Per conversations with AWS Support, specifying an origination number when using Sender ID may cause problems

Do not specify origination number when sending SMS with Sender ID

---

lib/telephony/pinpoint/sms_sender.rb
spec/lib/telephony/pinpoint/sms_sender_spec.rb

Includes #6572 
- Telephony: Do not specify origination number when sending SMS with Sender ID ([#6572](https://github.com/18F/identity-idp/pull/6572))

Release RC 198.1 to Production

---

spec/features/idv/in_person_spec.rb

Don't check for address 2 precense in in person flow if the test value is nil
Currently this test renders this warning:
```
Checking for expected text of nil is confusing and/or pointless since it will always match. Please specify a string or regexp instead. /builds/lg/identity-idp/spec/features/idv/in_person_spec.rb:61
```
...and it does have a point. This commit adds a conditional which only runs the check if address 2 is present. Alternatively we could just remove that line entirely.

Don't check for address 2 presence in in person flow if the test value is nil

---

app/javascript/packages/verify-flow/steps/personal-key-confirm/personal-key-confirm-step.spec.tsx
app/javascript/packages/verify-flow/steps/personal-key-confirm/personal-key-confirm-step.tsx
app/javascript/packages/verify-flow/steps/personal-key-confirm/personal-key-input.spec.tsx
app/javascript/packages/verify-flow/steps/personal-key-confirm/personal-key-input.tsx

Prior to this commit, when a user cancels personal key entry the personal key is not preserved in the confirmation dialog. This commit makes a change to preserve that value so it remains so the user does not have to re-type.

LG-6562 Preserve personal key after the user cancels personal key confirmation

---

app/controllers/idv/in_person_controller.rb
app/controllers/verify_controller.rb
app/decorators/service_provider_session_decorator.rb
app/decorators/session_decorator.rb
app/services/idv/in_person_config.rb
app/views/idv/session_errors/_in_person_proofing_options.html.erb
app/views/idv/shared/_document_capture.html.erb
config/application.yml.default
lib/identity_config.rb
spec/controllers/idv/in_person_controller_spec.rb
spec/controllers/verify_controller_spec.rb
spec/features/idv/in_person_spec.rb
spec/services/idv/in_person_config_spec.rb
spec/views/idv/session_errors/exception.html.erb_spec.rb
spec/views/idv/session_errors/failure.html.erb_spec.rb
spec/views/idv/session_errors/throttled.html.erb_spec.rb
spec/views/idv/session_errors/warning.html.erb_spec.rb
spec/views/idv/shared/_document_capture.html.erb_spec.rb

**Why**: So that we can have more discrete control over which users will be presented with and allowed to leverage the in-person proofing flow.
1. Start the proofing flow
- With an associated SP: Run [`identity-oidc-sinatra`](https://github.com/18F/identity-oidc-sinatra) in a separate process and begin from http://localhost:9292/?ial=2
- Without an associated SP: Sign in at http://localhost:3000, then navigate to http://localhost:3000/verify
2. Complete proofing flow up to one of the in-person proofing options
- e.g. use a [failing test document](https://developers.login.gov/testing/#testing-identity-proofing) for document capture 
3. Observe that the proofing option is only shown if allowed for the configured service providers
Edit `config/application.yml` to …

LG-6439: Allow per-SP access to IPP option

---

lib/telephony/pinpoint/sms_sender.rb
spec/lib/telephony/pinpoint/sms_sender_spec.rb

Follow up to #6572 because AWS has clarified that we should drop the configuration keys in the API call, rather than setting to `nil`

Do not specify sender_id and origination_number configuration together

---

app/controllers/concerns/two_factor_authenticatable.rb
app/decorators/user_decorator.rb
app/forms/otp_verification_form.rb
app/models/concerns/user_otp_methods.rb
app/services/db/auth_app_configuration.rb
app/services/phone_confirmation/code_generator.rb
app/views/idv/otp_verification/show.html.erb
app/views/shared/_one_time_code_input.html.erb
app/views/two_factor_authentication/otp_verification/show.html.erb
app/views/two_factor_authentication/totp_verification/show.html.erb
app/views/users/totp_setup/new.html.erb
config/application.yml.default
lib/identity_config.rb
lib/otp_code_generator.rb
spec/forms/otp_verification_form_spec.rb
spec/lib/otp_code_generator_spec.rb
spec/services/phone_confirmation/confirmaton_session_spec.rb
spec/views/shared/_one_time_code_input.html.erb_spec.rb

This PR is a late followup to #6545 which contains much of the context.  The motivations are also described in this [RFC](https://docs.google.com/document/d/1d7Cdrd9oHIxLlPGsglBIg1ixV0K96FA3uNSBWb6zEKM/edit).

Add support and configuration for sending 6-digit authentication OTPs

---

app/services/analytics_events.rb
app/services/doc_auth_router.rb
app/services/idv/steps/doc_auth_base_step.rb
spec/services/doc_auth_router_spec.rb

Workaround for the case where the discriminator is nil for whatever
reason. In this case the check will return the default vendor and log an
event that this occurred.

Don't require a discriminator for randomized doc auth vendors.

---

app/services/idv/actions/cancel_update_ssn_action.rb
app/services/idv/steps/ssn_step.rb

Fixes a 500 from [New Relic](https://one.newrelic.com/nr1-core/errors/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=259200000&state=3f08d13b-64f5-5b0e-bb2c-5a502ff37af6)

Fix 500 error when handling invalid state in SSN step

---

app/controllers/concerns/saml_idp_auth_concern.rb
app/controllers/saml_idp_controller.rb
app/controllers/users/backup_code_setup_controller.rb
app/controllers/users/sessions_controller.rb
app/services/analytics.rb
app/services/analytics_events.rb
spec/controllers/saml_idp_controller_spec.rb
spec/controllers/users/sessions_controller_spec.rb

LG-5949
https://cm-jira.usa.gov/browse/LG-5949
analytics events number 28, replaces these 5 constants with methods:
1. BACKUP_CODE_DELETED
2. BACKUP_CODE_SETUP_VISIT
3. BACKUP_CODE_SETUP_SUBMITTED
4. SAML_AUTH
5. SESSION_TIMED_OUT
Found that numbers 1 and 3 were not used; these were simply removed.
Tested with:
```
bundle exec rspec spec/controllers/users/backup_code_setup_controller_spec.rb
bundle exec rspec spec/controllers/saml_idp_controller_spec.rb
bundle exec rspec spec/controllers/users/sessions_controller_spec.rb
```

Jskinner lg5949 analytics events 28

---

app/controllers/users/mfa_selection_controller.rb
app/forms/two_factor_options_form.rb
spec/controllers/users/mfa_selection_controller_spec.rb
spec/features/two_factor_authentication/multiple_mfa_sign_up_spec.rb
spec/forms/two_factor_options_form_spec.rb

If a person selects setting up multiple MFA, and later changes their mind or is unable to set up a method following the first, they may be unable to continue with account setup unless they set up another MFA

Do not require a second MFA if multiple are selected and one is set up

---

app/controllers/users/mfa_selection_controller.rb
app/forms/two_factor_options_form.rb
spec/controllers/users/mfa_selection_controller_spec.rb
spec/features/two_factor_authentication/multiple_mfa_sign_up_spec.rb
spec/forms/two_factor_options_form_spec.rb

Pulls in bug fix in #6600 
Changelog:
- Account setup: Do not require a second MFA if multiple are selected and one is set up ([#6600](https://github.com/18F/identity-idp/pull/6600))

Deploy RC 199.2 to Production

---

app/controllers/api/irs_attempts_api_controller.rb
spec/controllers/api/irs_attempts_api_controller_spec.rb
spec/services/irs_attempts_api/attempt_event_spec.rb

**Why:** This is an API endpoint not using cookies, and doesn't actually work as-is without this change. Adds a test to prevent regression. (Kudos to Osman for catching this issue.)
Also sneaks in a minor typo fix in another test.
[skip changelog] because this is a temporary special-purpose endpoint. Is this the appropriate way to go with these, or should I code it as a bug fix?

LG-6809: IRS Attempt API controller skips CSRF protection

---

app/controllers/concerns/mfa_setup_concern.rb
app/services/analytics_events.rb
spec/controllers/users/webauthn_setup_controller_spec.rb

To be able to better understand how users are using the new multi-MFA process

Log mfa methods metrics when user finishes MFA setup

---

app/controllers/concerns/inherited_proofing_concern.rb
app/controllers/openid_connect/authorization_controller.rb
app/decorators/service_provider_session_decorator.rb
spec/controllers/openid_connect/authorization_controller_spec.rb
spec/decorators/service_provider_session_decorator_spec.rb

When the VA initiates inherited proofing with Login.gov, it passes an auth code that is necessary for subsequent requests to the VA. This change simply retrieves the auto code and persists it for subsequent requests.
https://cm-jira.usa.gov/browse/LG-6798
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Inherited%20Proofing/MHV%20Inherited%20Proofing/inherited-proofing-interface.md

[LG-6798] Persist the VA Authorization Code during the inherited proofing process

---

app/models/concerns/user_encrypted_attribute_overrides.rb
app/models/email_address.rb
app/services/request_password_reset.rb
spec/services/request_password_reset_spec.rb

Also makes the function reliability deterministic within the database by issuing only one query to avoid race conditions

Optimize finding EmailAddress for reset password process

---

config/initializers/job_configurations.rb

Run the `GetUspsProofingResultsJob` every 10 minutes instead of every hour.
**Why**
I had originally asked that it be set to a very conservative once an hour; having it run every ten minutes will make testing easier.

run GetUspsProofingResultsJob every 10 minutes

---

app/jobs/get_usps_proofing_results_job.rb
app/services/analytics_events.rb
spec/fixtures/usps_ipp_responses/request_passed_proofing_unsupported_status_results_response.json
spec/jobs/get_usps_proofing_results_job_spec.rb
spec/support/usps_ipp_fixtures.rb
spec/support/usps_ipp_helper.rb

use `Analytics` instead of `IdentityJobLogSubscriber` to log `GetUspsProofingResultsJob` events
**Why**
We typically look for log events in `events.log`, which is logged to via the Analytics class. The `IdentityJobLogSubscriber` is used for logging timing information.

use Analytics instead of IdentityJobLogSubscriber to log GetUspsProofingResultsJob events

---

app/controllers/api/verify/password_confirm_controller.rb
app/controllers/idv/in_person/ready_to_verify_controller.rb
spec/controllers/idv/in_person/ready_to_verify_controller_spec.rb
spec/factories/in_person_enrollments.rb
spec/factories/users.rb
spec/features/idv/in_person_spec.rb

#6615 made it so that when a user completes the IPP flow we will create a pending in-person enrollment record with the enrollment code we receive from the USPS. This PR updates the "Ready to verify" page to use that enrollment code rather than using a hard-coded value

LG-6872: Create USPS barcode using the user's enrollment code

---

spec/controllers/users/sessions_controller_spec.rb

Failing to record the event should cause a test failure, but did not.
Commenting the call to the tracker out:
```ruby
def track_authentication_attempt(email)
user = User.find_with_email(email) || AnonymousUser.new
success = user_signed_in_and_not_locked_out?(user)
analytics.email_and_password_auth(
success: success,
user_id: user.uuid,
user_locked_out: user_locked_out?(user),
stored_location: session['user_return_to'],
sp_request_url_present: sp_session[:request_url].present?,
remember_device: remember_device_cookie.present?,
)
end
```
This now triggers a failure:
```
RSpec::Mocks::MockExpectationError: Exactly one instance should have received the following message(s) but didn't: email_and_password_auth
0) Users::SessionsController POST / tracks the successful authentication for existing …
```

LG-6949 | Add test for email_and_password_auth event

---

yarn.lock

```
mitchellehenke:identity-idp/ (main*) $ yarn audit
yarn audit v1.22.17
│ high          │ Terser insecure use of regular expressions before v4.8.1 and │
│               │ v5.14.2 leads to ReDoS                                       │
│ Package       │ terser                                                       │
│ Patched in    │ >=5.14.2                                                     │
│ Dependency of │ webpack …
```

Upgrade webpack and terser to patch vulnerability

---

app/jobs/get_usps_proofing_results_job.rb
spec/jobs/get_usps_proofing_results_job_spec.rb

Updates the USPS IPP polling job so that when a user successfully completes in-person proofing we mark their profile as activated. This is the final step which allows them to continue to the service provider's website with a verified account.

LG-7003: Activate the user's profile when they pass USPS in-person proofing

---

app/controllers/two_factor_authentication/otp_verification_controller.rb
app/services/analytics_events.rb
spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb

Builds on #6460 to continue adding context to better understand telephony authentication failures

Add additional dimensions to telephony-based one-time passcode verification attempts

---

docs/backend.md

I was trying to create an updated version of this old wiki article: https://github.com/18F/identity-private/blob/main/doc/identity-idp-rails-controller-design.md
I tried to keep it as simple as possible, which makes it easier to ingest and harder to get out of date? But maybe I missed something, or the examples aren't clear

Document our controller-form-analytics pattern

---

app/views/idv/in_person/ready_to_verify/show.html.erb
spec/features/idv/in_person_spec.rb

**Why**: Every image should include an alt value.
This image:
Setting as draft because we need to decide whether this should be treated as a [decorative image](https://www.w3.org/WAI/tutorials/images/decorative/) or whether we need to create content to use as [text alternative](https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html).

Add alt attribute for "Ready to verify" illustration

---

app/jobs/get_usps_proofing_results_job.rb
spec/jobs/get_usps_proofing_results_job_spec.rb

Don't store proofing post office or city in logs for now.

remove proofing post office and city from log

---

app/controllers/api/verify/password_confirm_controller.rb
spec/controllers/api/verify/password_confirm_controller_spec.rb

**Why**: As a public user trying to proof online I want to see the details of my newly scheduled in-person proofing visit to the USPS as an email so that I can reference it later.
2. Sign in
4. Complete proofing process up to document capture
5. Use [attention result test YAML file](https://developers.login.gov/testing/#document-upload) for field upload
6. Click "Submit"
7. On warning screen, opt to verify in person
8. Complete proofing process up to "You're ready to verify in person"
9. Navigate to http://localhost:1080
10. Observe there is an email message with details of in-person verification
**Implementation notes:**
- Currently, this is only implemented in the …

Send "Ready to verify" email when IPP enrollment is created

---

app/controllers/concerns/mfa_setup_concern.rb
app/controllers/mfa_confirmation_controller.rb
app/controllers/users/additional_mfa_required_controller.rb
app/controllers/users/mfa_selection_controller.rb
spec/controllers/users/additional_mfa_required_controller_spec.rb

Slack thread with original issue: https://gsa-tts.slack.com/archives/C0NGESUN5/p1658765266167019

LG-6992: resolve secure header issues

---

spec/services/inherited_proofing/va/service_spec.rb

Just a small change to be less redundant

6796 - VA IP - Small cleanup per PR review

---

app/jobs/get_usps_proofing_results_job.rb
app/services/analytics_events.rb
spec/jobs/get_usps_proofing_results_job_spec.rb

Log successful status updates and add enrollment code to all logs in the `GetUspsProofingResultsJob` job.

LG-6331 in GetUspsProofingResultsJob log success, add enrollment code to events

---

app/controllers/idv/gpo_controller.rb
app/services/idv/flows/in_person_flow.rb
app/services/proofing/mock/resolution_mock_client.rb
spec/services/idv/agent_spec.rb

**Why**: Because it's a required attribute for the real resolution vendor implementation, which otherwise fails without it.

Initialize IPP pii_from_user with user UUID

---

app/forms/api/profile_creation_form.rb
app/presenters/idv/in_person/ready_to_verify_presenter.rb
app/services/idv/session.rb
app/services/usps_in_person_proofing/enrollment_helper.rb
spec/features/idv/in_person_spec.rb
spec/forms/api/profile_creation_form_spec.rb
spec/presenters/idv/in_person/ready_to_verify_presenter_spec.rb
spec/services/idv/session_spec.rb
spec/services/usps_in_person_proofing/enrollment_helper_spec.rb

Context: https://github.com/18F/identity-idp/pull/6635#discussion_r932220492
**Why**: Because the user's selection should be respected.

Use selected location details from session

---

app/views/user_mailer/in_person_ready_to_verify.html.erb

Make two small adjustments to email copy:
1. Number the third item in the process list `3` instead of `4`.
2. Remove the line "We have emailed this information to the email you used to log in."
<details>
<summary>Screenshot</summary>
</details>

LG-7605 Small changes to in-person enrollment email copy

---

app/controllers/idv/sessions_controller.rb
spec/controllers/idv/sessions_controller_spec.rb
spec/features/idv/in_person_spec.rb
spec/support/features/in_person_helper.rb

**Why**: So that a user can start over from the beginning and not be skipped past other steps.

LG-7035: Clear in-person proofing session when starting over

---

app/controllers/idv/gpo_verify_controller.rb
app/controllers/idv/review_controller.rb
spec/controllers/idv/gpo_verify_controller_spec.rb
spec/controllers/idv/review_controller_spec.rb

**Why**: The user's profile is not verified until they finish proofing in person.

LG-7063: Avoid sending account verified email for in-person proofing

---

config/application.yml.default
lib/identity_config.rb

changelog: Upcoming Features, Config,  Add feature flags for Device
Profiling
Why? We are adding feature flags to enable collecting information from devices that we will send to LexisNexis' ThreatMetrix platform.
* proofing_device_profiling_collecting_enabled enables the device profiling integration with
ThreatMetrix
* proofing_device_profiling_decisioning_enabled enables decisioning
based on the results from ThreatMetrix

LG-7005 Add feature flags for Device Profiling

---

lib/linters/errors_add_linter.rb

**Why**: The description was copy-pasted from another linter,
causing more confusion

Fix comments on ErrorsAddLinter

---

config/locales/in_person_proofing/es.yml

**Why**: So that a Spanish user sees Spanish content, not French.

Use correct Spanish label for "Retail hours"

---

app/views/idv/in_person/address.html.erb
app/views/idv/in_person/state_id.html.erb

**Why**: Per designs, a user should have an opportunity to cancel or start over at any point in the flow.

Show "Cancel" links for in-person proofing steps

---

app/controllers/idv/in_person/usps_locations_controller.rb
app/javascript/packages/document-capture/components/in-person-location-step.tsx
app/javascript/packages/document-capture/components/in-person-prepare-step.tsx
config/routes.rb
spec/controllers/idv/in_person/usps_locations_controller_spec.rb

Pass location selection between pages instead of loading the location from `UspsLocationsController`.
<details>
<summary>Screenshot:</summary>
</details>

LG-6089: Pass location selection between pages

---

config/application.yml.default

This is now enabled in production, so we can enable it by default in all deployed environments

Enable Numeric OTP by default

---

app/controllers/users/passwords_controller.rb
app/controllers/users/reset_passwords_controller.rb
app/services/push_notification/password_reset_event.rb
config/service_providers.localdev.yml
spec/controllers/users/passwords_controller_spec.rb
spec/controllers/users/reset_passwords_controller_spec.rb
spec/services/push_notification/password_reset_event_spec.rb

Resolves LG-7075
Adds a new security event for when users change their passwords, both
for account recovery as well as for intentional password changes.
Also updates the default SP config to include a push notification URL
for the local Dashboard in development.
changelog: Improvements, Security, Add security event for password resets

[LG-7075] Add security event for password resets

---

app/javascript/packages/document-capture/components/in-person-prepare-step.tsx
app/views/idv/in_person/address.html.erb
app/views/idv/in_person/ready_to_verify/show.html.erb
app/views/user_mailer/in_person_ready_to_verify.html.erb

Hide links to help content that has not been created yet. They will be restored as a part of LG-6875, when the help content is published. The links have been removed in these four places:
<details>
<summary>Prepare page</summary>
</details>
<details>
<summary>Address page</summary>
</details>
<details>
<summary>Ready to verify page</summary>
</details>
<details>
<summary>Ready to verify email</summary>
</details>

hide broken help links on in-person proofing pages

---

app/controllers/application_controller.rb
app/services/analytics_events.rb
spec/controllers/application_controller_spec.rb

Seeing a couple of 500s in [staging](https://onenr.io/0MR2A7VzYwY) and [int](https://onenr.io/0Zw0Zn30ejv) that appear to be partly a result of the Rails 7 upgrade

Fix 500 errors when handling unsafe redirects

---

app/services/doc_auth/acuant/responses/get_results_response.rb
app/services/doc_auth/lexis_nexis/responses/true_id_response.rb
app/services/doc_auth/processed_alert_to_log_alert_formatter.rb
spec/services/doc_auth/acuant/responses/get_results_response_spec.rb
spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb
spec/services/doc_auth/processed_alert_to_log_alert_formatter_spec.rb

This pull request adds a safe guard so that if the alert had failed and passed, that the failed alert is logged and not written over. The chances currently of this happening is zero because the 'Passed alerts are processed first' but as a safeguard, I added a check to ensure failed is always logged and updated the test.
Currently a work in progress and not review for review just yet.

LG-6668 safeguard failed message

---

app/services/usps_in_person_proofing/proofer.rb

So that we can have better visibility into the volume, success rate, and timing of the requests
(documentation for this added in https://github.com/18F/identity-idp/pull/6686)

Instrument HTTP requests for In-Person-Proofing

---

docs/backend.md

Adds an example to the Faraday documentation in backend.md
(prompted by https://github.com/18F/identity-idp/pull/6685)

Document Faraday instrumentation

---

spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb

looks like #6683 and #6647 may have had an unexpected interaction?

Fix broken specs

---

spec/services/inherited_proofing/va/service_spec.rb

It looks like the expiration time encoded in the token is causing failures since it doesn't always match exactly:
```json
{
"inherited_proofing_auth": "mocked-auth-code-for-testing",
"exp": 1659640373
}
```
```json
{
"inherited_proofing_auth": "mocked-auth-code-for-testing",
"exp": 1659640374
}
```
This PR freezes the time to hopefully help it be a bit more reliable.

Fix flaky VA Service spec

---

app/javascript/packages/build-sass/index.js
app/javascript/packages/build-sass/package.json
yarn.lock

**Why**:
- Improved performance, both at build time and runtime.
- Fewer dependencies to manage and maintain
I had tried this once before and the feature support with autoprefixing didn't have what we needed at the time (especially [CSS mask](https://developer.mozilla.org/en-US/docs/Web/CSS/mask#browser_compatibility) used by a lot of USWDS icons), but it looks like this has since improved. Will be worth testing a bit more exhaustively to check overall support.
I also want to confirm more closely that the browserlist configuration is being used as expected.
**Resources:**
- https://github.com/parcel-bundler/parcel-css
**Impact:**
`yarn build:css` (development bundling)
_Before:_ ~3.5s
_After:_ ~2.2s
`NODE_ENV yarn build:css` (production bundling with minification)
_Before:_ ~5.3s
_After:_ …

Switch from PostCSS/Autoprefixer/CSSNano to Parcel CSS

---

spec/controllers/idv/doc_auth_controller_spec.rb
spec/controllers/idv/sessions_controller_spec.rb
spec/models/user_spec.rb
spec/support/features/in_person_helper.rb

**Why**: Since this test coverage should have been included in its initial introduction in #6634, #6661.

Improve test coverage for in-person proofing

---

app/controllers/concerns/saml_idp_logout_concern.rb
app/controllers/openid_connect/logout_controller.rb
app/controllers/sign_out_controller.rb
app/controllers/users/sessions_controller.rb
app/services/irs_attempts_api/tracker_events.rb
spec/controllers/openid_connect/logout_controller_spec.rb
spec/controllers/saml_idp_controller_spec.rb
spec/controllers/sign_out_controller_spec.rb
spec/controllers/users/sessions_controller_spec.rb

LG-7304 Add Attempts API Logout Initiated tracking

---

app/components/troubleshooting_options_component.html.erb
app/components/troubleshooting_options_component.rb
app/controllers/idv/session_errors_controller.rb
app/controllers/verify_controller.rb
app/javascript/packages/verify-flow/cancel.spec.tsx
app/javascript/packages/verify-flow/context/flow-context.tsx
app/javascript/packages/verify-flow/verify-flow-troubleshooting-options.spec.tsx
app/javascript/packages/verify-flow/verify-flow-troubleshooting-options.tsx
app/javascript/packages/verify-flow/verify-flow.tsx
app/javascript/packs/document-capture.jsx
app/javascript/packs/verify-flow.tsx
app/services/idv/actions/verify_document_status_action.rb
app/services/idv/steps/doc_auth_base_step.rb
app/services/idv/steps/ipp/verify_wait_step_show.rb
app/services/idv/steps/verify_base_step.rb
app/services/proofing/mock/resolution_mock_client.rb
app/views/idv/session_errors/_in_person_proofing_options.html.erb
app/views/idv/session_errors/exception.html.erb
app/views/idv/session_errors/throttled.html.erb
spec/components/troubleshooting_options_component_spec.rb
spec/controllers/idv/session_errors_controller_spec.rb
spec/controllers/verify_controller_spec.rb
spec/features/idv/doc_auth/verify_step_spec.rb
spec/features/idv/in_person_spec.rb
spec/javascripts/packs/verify-flow-spec.ts
spec/services/idv/steps/ipp/verify_wait_step_show_spec.rb
spec/services/proofing/mock/resolution_mock_client_spec.rb
spec/views/idv/session_errors/exception.html.erb_spec.rb
spec/views/idv/session_errors/throttled.html.erb_spec.rb

**Why**: So that the user doesn't get stuck in a loop of attempting to troubleshoot by verifying in-person.
2. Sign in or create an account
4. Complete proofing flow, optionally choosing to proof in-person
5. At SSN step, use value "000-00-0000"
6. Continue to "Verify your information" step
7. Click "Continue"
8. Observe that the in-person proofing troubleshooting option is only visible if you are not already in the in-person proofing flow
Before|After
---|---

LG-6927: Omit in-person troubleshooting option when already in flow

---

app/controllers/idv/review_controller.rb
app/forms/api/profile_creation_form.rb
app/services/idv/profile_maker.rb
app/services/idv/session.rb
spec/controllers/idv/personal_key_controller_spec.rb
spec/services/idv/profile_maker_spec.rb
spec/services/idv/session_spec.rb

Context: https://github.com/18F/identity-idp/pull/6634#discussion_r931178284
**Why**: So that deactivation_reason can be assigned in initial creation of the profile, rather than as an immediate follow-on transaction.

Collapse profile creation to single method

---

app/forms/gpo_verify_form.rb
spec/controllers/idv/gpo_verify_controller_spec.rb
spec/forms/gpo_verify_form_spec.rb

This will allow us to bin letter sent and code entered events based on when the letter was sent

Log the enqueued_at date when a user enters a code

---

app/controllers/idv/doc_auth_controller.rb
app/controllers/idv/in_person_controller.rb
app/services/idv/session.rb
app/services/idv/steps/doc_auth_base_step.rb
app/services/idv/steps/ipp/ssn_step.rb
app/services/idv/steps/ipp/verify_step.rb
app/services/idv/steps/ipp/verify_wait_step_show.rb
app/services/idv/steps/ssn_step.rb
app/services/idv/steps/verify_base_step.rb
app/services/idv/steps/verify_step.rb
app/services/idv/steps/verify_wait_step_show.rb
spec/controllers/idv/doc_auth_controller_spec.rb
spec/controllers/idv/in_person_controller_spec.rb
spec/services/idv/actions/verify_document_status_action_spec.rb
spec/services/idv/session_spec.rb
spec/services/idv/steps/ipp/ssn_step_spec.rb
spec/services/idv/steps/ipp/verify_step_spec.rb
spec/services/idv/steps/ssn_step_spec.rb
spec/services/idv/steps/verify_wait_step_show_spec.rb

**Why**: Since a user will need to select a location as part of establishing an enrollment before proceeding with the in-person flow.

LG-7167: Verify establishing enrollment for in-person flow

---

app/controllers/sign_up/registrations_controller.rb
app/controllers/users/reset_passwords_controller.rb
app/services/irs_attempts_api/tracker_events.rb
spec/controllers/sign_up/registrations_controller_spec.rb
spec/controllers/users/reset_passwords_controller_spec.rb
spec/support/fake_analytics.rb

LG-6977 : Implement email submitted event

---

app/controllers/concerns/mfa_setup_concern.rb
spec/controllers/users/webauthn_setup_controller_spec.rb

Currently, the `next_setup_path` is called after any MFA setup, which includes MFA setups _after_ account registration, and this event was only intended to be logged during registration.
To fix that, this event should only be logged if there are MFA selections (which only exist during account registration).

Fix duplicate event logging for MFA Setup Complete event

---

app/views/devise/passwords/edit.html.erb
config/locales/instructions/en.yml
config/locales/instructions/es.yml
config/locales/instructions/fr.yml
spec/views/devise/passwords/edit.html.erb_spec.rb

Why: To notify users that if they verified their identity and wish to reset their password, they must have their 16 character personal key, or else they will have to reverify their identity.
Screenshots
| Before      | After |
| ----------- | ----------- |
| ![Screen Shot 2022-08-04 at 12 04 34 PM](https://user-images.githubusercontent.com/17969963/183144905-25e8c99b-7fe5-49ae-9d87-d5b2d78505d4.png) | ![Screen Shot 2022-08-05 at 1 12 00 PM](https://user-images.githubusercontent.com/17969963/183144978-b569f8d8-9455-4336-b61c-d34d17b46a30.png) |

LG-6103: add warning about personal key to password reset screen

---

app/controllers/idv/gpo_controller.rb
app/controllers/idv/review_controller.rb
app/services/analytics_events.rb
spec/services/analytics_spec.rb

This change allows us to sort between users requesting a new letter and users who are requesting their first letter. This allows us to group users requesting letters into cohorts based on when they requested their first letter by filtering out resends.

Log whether a requested GPO letter is being resent

---

app/controllers/frontend_log_controller.rb
app/controllers/idv/review_controller.rb
app/services/analytics_events.rb
spec/controllers/idv/review_controller_spec.rb

This change will allow us to track how much toil there is at this step

Track unsuccessful IdV password confirmation attempts

---

app/controllers/two_factor_authentication/totp_verification_controller.rb
app/services/irs_attempts_api/tracker_events.rb
spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb

LG-7043 TOTP-Verify-Submit event

---

app/assets/stylesheets/components/_btn.scss
app/javascript/packs/form-validation.js
app/javascript/packs/form-validation.ts
spec/javascripts/packs/form-validation-spec.js

**Why:**
- For consistency with spinner button activation, which shows with dark blue background while awaiting completion
- To reduce the abruptness of transitioning from an active to disabled button on submission
**Screen recording:**
_Before:_
https://user-images.githubusercontent.com/1779930/183421143-47473cf9-e5ee-47a6-8d90-ccdb20fe39d5.mov
_After:_
https://user-images.githubusercontent.com/1779930/183421151-f6dfd601-23c8-4a18-bc15-5f86af6e0a80.mov
**Background:**
Previously, this pull request was aimed at removing the disable-on-submit effect altogether:
<details><summary>Click to see previous summary</summary>
**Why**:
- Improve consistency: Currently, this behavior happens in some forms and not others. This makes it so that a button is never disabled on form submission.
- It's …

Update disable-on-submit styling to use active styling

---

app/services/doc_auth_router.rb
app/services/idv/steps/verify_base_step.rb
lib/idp/constants.rb
spec/features/idv/doc_auth/verify_step_spec.rb
spec/services/doc_auth_router_spec.rb

Context: https://github.com/18F/identity-idp/pull/6576#discussion_r919085206
**Why**: So that we're referencing vendor names consistently.
Temporarily merges to #6576.
Requires configuration changes which cannot be made for at least the next couple days ([see related Slack discussion](https://gsa-tts.slack.com/archives/C0NGESUN5/p1657655307643849)).

Rename LexisNexis constant from "lexisnexis" to "lexis_nexis"

---

config/application.yml.default

We looked at the data. 95% of users don't make more than 5 attemtps and very few people are not successful after the 3rd attempts

LG-7140 Set max doc auth attempts to 5

---

lib/telephony/pinpoint/voice_sender.rb
lib/telephony/test/voice_sender.rb
spec/controllers/users/two_factor_authentication_controller_spec.rb
spec/lib/telephony/pinpoint/voice_sender_spec.rb
spec/lib/telephony/test/voice_sender_spec.rb

**Why**: So we can triage which phone numbers are associated
with errors on the customer side

Log origination phone number for voice calls

---

app/controllers/idv/in_person/usps_locations_controller.rb
app/mailers/user_mailer.rb
app/models/in_person_enrollment.rb
app/models/service_provider.rb
app/presenters/idv/in_person/verification_results_email_presenter.rb
app/services/sp_return_url_resolver.rb
app/services/usps_in_person_proofing/enrollment_helper.rb
app/views/shared/_in-person-verification-results-email-lower.html.erb
app/views/user_mailer/in_person_failed.html.erb
app/views/user_mailer/in_person_verified.html.erb
config/locales/user_mailer/en.yml
config/locales/user_mailer/es.yml
config/locales/user_mailer/fr.yml
db/primary_migrate/20220808140030_add_issuer_to_in_person_enrollments.rb
db/schema.rb
spec/controllers/idv/in_person/usps_locations_controller_spec.rb
spec/mailers/previews/user_mailer_preview.rb
spec/presenters/idv/in_person/verification_results_email_presenter_spec.rb
spec/services/sp_return_url_resolver_spec.rb

**Why**: As a user, I want to receive an email notification so that I know if my identity verification was successful or not. Those emails should direct me to the original service provider so that I can access the services I had originally sought to access.
<table>
<tr><td></td><td colspan="2">With service provider</td><td>Without service provider</td></tr>
<tr><td></td><td>With homepage</td><td>Without home page</td><td></td></tr>
<tr><td>Success</td><td><img alt="screenshot" src="https://user-images.githubusercontent.com/1779930/183980036-4cedf94f-63e3-4802-ae52-07fff949f781.png"></td><td><img alt="screenshot" src="https://user-images.githubusercontent.com/1779930/183980147-a2406167-e7a2-43ec-b87a-5d64c685117b.png"></td><td><img alt="screenshot" …

LG-7076: Include partner links in in-person proofing emails

---

app/controllers/users/sessions_controller.rb
config/initializers/content_security_policy.rb
spec/requests/csp_spec.rb
spec/views/idv/shared/_document_capture.html.erb_spec.rb

Currently, we only attempt to load the Digital Analytics Program (DAP) and Google Analytics (GA) on the unauthenticated home page.  The Content Security Policy, however, permits the domains across the site.
This PR brings the CSP in line with the implementation and expectations for DAP/GA.

Create stricter Content Security Policy (CSP) rules for Google Analytics

---

app/controllers/concerns/idv/document_capture_concern.rb
config/initializers/content_security_policy.rb
spec/requests/csp_spec.rb
spec/views/idv/shared/_document_capture.html.erb_spec.rb

Currently, we include `idscangoweb.acuant.com` in the CSP `img_src`, but it is not used.  It was included in changes in https://github.com/18F/identity-idp/pull/3671/files#diff-66cc7258886071348febbf60314501e02948b7d31e616fe88121ccc338ddb449R18.  Most of those changes were undone in https://github.com/18F/identity-idp/commit/3b1772cdf918f314d1862e482076109429f88356.  The removed script included a reference to that domain: https://github.com/18F/identity-idp/blob/28d480fa69dd5fd86284041991941f752ee3e881/public/idscan-go.js#L58 so this should be safe to remove.
`us.acas.acuant.net` is used in a token call when the SDK is loaded, and we can more precisely allow the host by making use of the existing CSP overrides we do for document capture.

Create stricter Content Security Policy (CSP) for document capture hosts

---

app/controllers/two_factor_authentication/backup_code_verification_controller.rb
app/controllers/two_factor_authentication/totp_verification_controller.rb
app/controllers/users/backup_code_setup_controller.rb
app/controllers/users/totp_setup_controller.rb
app/controllers/users/two_factor_authentication_controller.rb
app/services/irs_attempts_api/tracker_events.rb
spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb
spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb
spec/controllers/users/backup_code_setup_controller_spec.rb
spec/controllers/users/totp_setup_controller_spec.rb
spec/controllers/users/two_factor_authentication_controller_spec.rb
spec/features/irs_attempts_api/event_tracking_spec.rb

Rename and reorganize MFA events to one standard

Rename / Reorg for standard

---

app/controllers/concerns/idv/threat_metrix_concern.rb
app/controllers/idv/doc_auth_controller.rb
spec/controllers/concerns/idv/threat_metrix_concern_spec.rb

This PR selectively pokes holes in our Content Security Policy (CSP) to allow ThreatMetrix to do its thing. Updated CSP headers are only included on pages using the ThreatMetrix JS (currently SSN entry form).
Updates to headers include:
| Directive | New value(s) | Why? | 
| -- | -- | -- |
| `script-src` | `h.online-metrix.net`, `"unsafe-eval"` | TM javascript is loaded from this domain; the JS itself uses `eval()` as part of its source obfuscation |
| `style-src` | `"unsafe-inline"` | TM adds inline styles to DOM elements it creates as part of the fingerprinting process |
| `img-src` | `*.online-metrix.net` | TM loads images from different domains under `online-metrix.net` as part of the fingerprinting process |
| `connect-src` | `h.online-metrix.net` | TM makes XHR requests to this …

LG-7243: Add CSP config for ThreatMetrix JS

---

app/assets/stylesheets/components/_barcode.scss

**Why**: Since apparently table cell background colors are made transparent in default printing behavior, whereas cell border coloring is not.
**Testing instructions:**
2. Sign in
5. Use [attention result test YAML document](https://developers.login.gov/testing/#document-upload)
6. Click "Verify your ID in person"
7. Complete in-person proofing flow
8. Observe barcode is visible on "You're ready to verify" screen
9. Print the barcode
10. Observe barcode is visible and accurate
Browser content (visually unchanged):
Before|After
---|---
Printed content:
Before|After
---|---
(the appearance in the preview seems to be affected by scaling)

LG-7180: Fix printed appearance of Barcode

---

app/controllers/users/sessions_controller.rb
spec/controllers/users/sessions_controller_spec.rb

[New Relic](https://one.newrelic.com/nr1-core/errors/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=43200000&state=03c518c0-abaa-e635-dced-08f57db28f35)
Similar strategy as in #6682, and since this controller does not inherit from `ApplicationController`, we can make similar changes.

Fix 500 error when handling unsafe redirects

---

config/application.yml.default
config/database.yml
lib/identity_config.rb

We've seen a few report jobs fail when they are unable to get a connection. It looks like GoodJob also suggests this sort of approach to db connections.
changelog Internal, Database, More db connections were added to the worker nodes

Add 4 more db connections to the worker connection pool

---

Gemfile

Some tools (in my case it's the VS Code Ruby extension) attempt to load the `Gemfile` when running in  directories other than the project root. When this happens, `Gemfile` can't load `.ruby-version`, since it's not in the directory it's expecting. This leads to errors from tools complaining about missing `.ruby-version` files. 
This commit updates the `Gemfile` to always explicitly load `.ruby-version` from the same directory `Gemfile` is in.

Use full path to load .ruby-version in Gemfile

---

app/assets/stylesheets/components/_btn.scss

Fixes regression introduced in #6564
**Why**: Because the styling was only implemented with the expectation of use with the default button, and conflicts with other button states (e.g. unstyled buttons used as the submit buttons on some forms).
State|Before|After
---|---|---
Default|![Screen Shot 2022-08-15 at 9 42 00 AM](https://user-images.githubusercontent.com/1779930/184647389-3054ed3d-2be3-4688-b57b-8a6dffcec3ec.png)|![Screen Shot 2022-08-15 at 9 42 00 AM](https://user-images.githubusercontent.com/1779930/184647389-3054ed3d-2be3-4688-b57b-8a6dffcec3ec.png)
Pressed|![Screen Shot 2022-08-15 at 9 38 32 AM](https://user-images.githubusercontent.com/1779930/184647384-89caf160-4f76-41d2-bf5a-a9b36e5a55fc.png)|![Screen Shot 2022-08-15 at 9 42 20 …

Limit active disabled button styles to default button

---

app/controllers/idv/gpo_controller.rb
app/controllers/idv/review_controller.rb
app/services/analytics_events.rb

The letter is not necessarily sent when it is requested. At the end of proofing the user requests a letter, but the letter is not sent until the profile is created after the user enters their password. This commit adds different events for requested and enqueueing the letter so we can track both

Create separate events for when a letter is requested and when it is enqueued

---

app/javascript/packages/document-capture/components/in-person-prepare-step.tsx
app/views/idv/in_person/address.html.erb
app/views/idv/in_person/ready_to_verify/show.html.erb
app/views/user_mailer/in_person_ready_to_verify.html.erb

**Why**: So that a user can learn more about how to complete the in-person proofing process.
Related: https://github.com/18F/identity-site/pull/920
---|---|---
Prepare|![7130-prepare-before](https://user-images.githubusercontent.com/1779930/184144544-3fb17001-c885-4513-a2b7-642f4b77d1c5.png)|![7130-prepare-after](https://user-images.githubusercontent.com/1779930/184144542-7c0ad976-9db3-4406-9401-f3305a5f35f2.png)
Address|![7130-address-before](https://user-images.githubusercontent.com/1779930/184144531-75c42fbe-fecb-41ec-8ddf-0246c53d79f5.png)|![7130-address-after](https://user-images.githubusercontent.com/1779930/184144525-9fc05159-8696-4734-9bd0-04a99ec492cd.png)
Ready to Verify|![7130-ready-before](https://user-images.githubusercontent.com/1779930/18 …

LG-7130: Add links to help center articles for in-person proofing

---

app/controllers/api/irs_attempts_api_controller.rb
app/controllers/idv/in_person/usps_locations_controller.rb
app/controllers/idv/in_person_controller.rb
spec/controllers/idv/in_person/usps_locations_controller_spec.rb

Context: https://github.com/18F/identity-idp/pull/6624#discussion_r931071558
**Why**:
- The intent of the concern is to DRY this common behavior
- Include USPS locations controller as feature-guarded by IPP

Use RenderConditionConcern consistently for feature-guarding controllers

---

app/views/idv/shared/_ssn.html.erb
spec/views/idv/shared/_ssn.html.erb_spec.rb

Nonce is required to allow TM to execute.
changelog: Bug Fixes, ThreatMetrix, add nonce to script tag

Add nonce to ThreatMetrix <script> tag

---

app/controllers/frontend_log_controller.rb
app/javascript/packages/document-capture/components/acuant-capture.jsx
app/javascript/packages/document-capture/context/failed-capture-attempts.jsx
app/javascript/packs/document-capture.jsx
app/services/analytics_events.rb
app/views/idv/shared/_document_capture.html.erb
config/application.yml.default
lib/identity_config.rb
spec/javascripts/packages/document-capture/context/failed-capture-attempts-spec.jsx

This pull request will force native camera to do the document capture after the sdk camera has failed twice.

LG-6777 capture native camera after failed twice

---

app/jobs/resolution_proofing_job.rb
lib/identity_config.rb
spec/lib/identity_config_spec.rb

**Why**: Could have prevented #6764 if we had a check like this
in place, can hopefully catch the next one
changelog: Internal, Source code, Add check to catch config type errors

Add basic linting for IdentityConfig types and key names

---

app/services/proofing/lexis_nexis/ddp/verification_request.rb
config/application.yml.default
lib/identity_config.rb
spec/fixtures/proofing/lexis_nexis/ddp/request.json

**Why**: To be able to change the policy we use to call threatmetrix instead of relying on the default.

Add threatmetrix policy config

---

app/jobs/get_usps_proofing_results_job.rb
config/application.yml.default
config/initializers/job_configurations.rb
lib/identity_config.rb
spec/jobs/get_usps_proofing_results_job_spec.rb

This introduces two new configuration values:
- `get_usps_proofing_results_job_cron`
Cron expression for the USPS proofing cron job. Default: `'0/10 * * * *'`
- `get_usps_proofing_results_job_reprocess_delay_minutes`
Minimum delay in minutes between checks for each enrollment for the USPS proofing cron job. Default: `5`
1. Override one or both values in `application.yml`
```
get_usps_proofing_results_job_cron: '0/3 * * * *'
get_usps_proofing_results_job_reprocess_delay_minutes: 2
```
2. Run through the IPP workflow until the review page
3. Repeatedly check the enrollment record's `status_check_attempted_at` field to determine if the frequency with which it was processed matches the configured values.
```
$ psql
psql (14.3)
Type "help" for help.
postgres=# \c identity_idp_development
You …
```

LG-6980: Make USPS proofing results job frequency configurable

---

app/assets/stylesheets/components/_spinner-button.scss

Fixes regression introduced in #6564
**Why**: Because the spinner button retains its original shape by setting the text color to transparent, which was being overridden by the new active styles introduced in #6564.
Before|After
---|---

Fix spinner button active color

---

app/controllers/api/irs_attempts_api_controller.rb
app/services/analytics_events.rb
app/services/irs_attempts_api/redis_client.rb
app/services/irs_attempts_api/tracker.rb
lib/tasks/attempts.rake
spec/controllers/api/irs_attempts_api_controller_spec.rb
spec/features/irs_attempts_api/event_tracking_spec.rb
spec/services/irs_attempts_api/redis_client_spec.rb
spec/services/irs_attempts_api/tracker_spec.rb
spec/support/features/irs_attempts_api_tracking_helper.rb

Drops requesting by count and stores in a Redis hash by hourly timestamp rather than individually by event ID.  This is not a long-term storage solution.
The external API now requires requesting by timestamp (ultimately truncating hours and seconds) per the specification.

Store and fetch IRS Attempts events by timestamp

---

app/javascript/packages/document-capture/components/in-person-troubleshooting-options.tsx
app/services/marketing_site.rb
app/views/idv/in_person/address.html.erb
app/views/idv/in_person/ready_to_verify/show.html.erb
app/views/user_mailer/in_person_ready_to_verify.html.erb

**Why**: Since the URL selected for the help center content is different than the URL we assumed it would be in the code implementation.
Reference: https://github.com/18F/identity-site/pull/920/files#diff-971600dd227c5e00268280c324335790b0945672ba708c65bf5a5f8bc54d402fR4

Fix Help Center article links for in-person proofing

---

app/controllers/frontend_log_controller.rb
app/services/analytics_events.rb
spec/controllers/frontend_log_controller_spec.rb
spec/javascripts/packages/document-capture/context/failed-capture-attempts-spec.jsx

**Why:** Payload would be parsed with string keys, which are incompatible with method kwargs expecting symbols.
See discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1660837978230519

Fix FrontendLogController payload splatting

---

app/controllers/two_factor_authentication/backup_code_verification_controller.rb
app/controllers/two_factor_authentication/otp_verification_controller.rb
app/controllers/two_factor_authentication/totp_verification_controller.rb
app/controllers/two_factor_authentication/webauthn_verification_controller.rb
app/controllers/users/two_factor_authentication_controller.rb
app/services/irs_attempts_api/tracker_events.rb
spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb
spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb
spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
spec/controllers/users/two_factor_authentication_controller_spec.rb
spec/features/irs_attempts_api/event_tracking_spec.rb

LG-7290 Unify naming of irs attempts tracker event

---

app/javascript/packs/form-validation.ts
app/views/devise/sessions/new.html.erb
spec/javascripts/packs/form-validation-spec.js

**Why**:
- They are inconsistent with desired error feedback UX, which should be implemented as design system error messages via ValidatedFieldComponent.
- Improves performance of critical path by reducing JavaScript (and locale data) bundle size.
- For context, the Sign In page loads locale data which includes only this one string for required fields ([screenshot](https://user-images.githubusercontent.com/1779930/185402890-36f4d474-81aa-421d-8e2d-f1f21fd200b3.png)).
- Contributes toward removal of form-validation pack, to be removed between this and https://github.com/18F/identity-idp/pull/6771
- Reduces complexity, where this validation intervention has often conflicted with other validation (specifically, see `data-form-validation-message` handling and related context at #5631) …

Remove custom "Required" form validation message

---

app/services/irs_attempts_api/tracker_events.rb

Alphabetize events

---

app/jobs/resolution_proofing_job.rb
app/services/idv/steps/ipp/ssn_step.rb
app/views/idv/in_person/ssn.html.erb
app/views/idv/shared/_ssn.html.erb
spec/jobs/resolution_proofing_job_spec.rb
spec/services/idv/steps/ipp/ssn_step_spec.rb
spec/views/idv/shared/_ssn.html.erb_spec.rb

To limit scope of ThreatMetrix implementation, this PR removes it from the in-person flow. It also updates the LexisNexis DDP proofer logic to _not_ make an API call if a `threatmetrix_session_id` is not present in `flow_session` (these API calls would fail anyway, so this way we avoid sending data to LN unnecessarily).

LG-7307: Remove ThreatMetrix from In-Person Proofing flow

---

app/controllers/concerns/two_factor_authenticatable_methods.rb
app/controllers/two_factor_authentication/backup_code_verification_controller.rb
app/controllers/two_factor_authentication/otp_verification_controller.rb
app/controllers/two_factor_authentication/personal_key_verification_controller.rb
app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
app/controllers/two_factor_authentication/totp_verification_controller.rb
app/presenters/two_factor_auth_code/max_attempts_reached_presenter.rb
app/services/irs_attempts_api/tracker_events.rb
spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb
spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb
spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb
spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb

1. Added `mfa_enroll_rate_limited` attempt event.
2. Added `mfa_verify_rate_limited` attempt event. EDIT: now `mfa_login_rate_limited`
3. Added tests in various `two_factor_authentication` spec files for the above events.
4. Modified several functions starting with `handle_invalid_otp` in order to support the above events.

LG-7201 - Added attempt events - MFA submitted rate limited

---

app/helpers/script_helper.rb
lib/asset_sources.rb
spec/helpers/script_helper_spec.rb
spec/lib/asset_sources_spec.rb
webpack.config.js

**Why**: For additional protection against script manipulation, particularly in combination with CDN.
See: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
1. `NODE_ENV=production yarn build`
2. `rails s`
3. Go to http://localhost:3000
4. Observe:
a. No errors in console
b. JavaScript still works

Enable subresource integrity for JavaScript packs

---

config/application.yml.default

This commit disables the FSMv2 tooling that was built in React. The work on this stalled and it is unlikely it will get built in this form. Having it in the main path by default in development is confusing.

Disable the FSMv2 react tooling in local dev

---

app/controllers/api/irs_attempts_api_controller.rb
spec/controllers/api/irs_attempts_api_controller_spec.rb

Adds a failing spec and the fix.  Current implementation will 500 with:
```
NoMethodError:
undefined method `split' for nil:NilClass
```

Fix 500 error when not providing Authorization header in Attempts API

---

app/jobs/resolution_proofing_job.rb
app/services/proofing/lexis_nexis/ddp/proofer.rb
app/services/proofing/mock/ddp_mock_client.rb
app/services/proofing/result.rb
spec/jobs/resolution_proofing_job_spec.rb

**Why**: To track what went into a verified profile and also to allow the front end to query the db at the end of the IdV flow to either store the profile as disabled  and present a sad screen if the threatmetrix_review_status is either: 'reject', 'review', or 'challenge' as well as threatmetrix component completely missing.
**How**: Use the new fields we added in proofing_components here https://github.com/18F/identity-idp/pull/6655 Other fields are still undecided.

LG-7302 Record overall result from TMX in the database

---

app/services/idv/in_person_config.rb
spec/services/idv/in_person_config_spec.rb

**Why**: Since it's intended to align to the option being available without an associated service provider only in environments where verification without one is allowed, such as in local development.
See [Slack context](https://gsa-tts.slack.com/archives/C03FA4VBN76/p1660930481297919?thread_ts=1660913820.762729&cid=C03FA4VBN76) for related discussion.

Tie in-person nil issuer condition to SP required config

---

app/controllers/application_controller.rb
app/services/irs_attempts_api/tracker.rb
spec/services/irs_attempts_api/tracker_spec.rb

The Device UUID should remain internal, so this hashes the string to keep the consistency but prevent misuse.
I also renamed the parameter to be a bit more explicit and avoid some ambiguity.

Hash Device UUID for IRS Attempts API

---

app/jobs/resolution_proofing_job.rb
app/services/proofing/lexis_nexis/ddp/proofer.rb
app/services/proofing/lexis_nexis/ddp/verification_request.rb
spec/fixtures/proofing/lexis_nexis/ddp/request.json
spec/jobs/resolution_proofing_job_spec.rb
spec/services/proofing/lexis_nexis/ddp/proofing_spec.rb
spec/services/proofing/lexis_nexis/ddp/verification_request_spec.rb

LG-7303 - send IP address to TMX, LG-7304 - send app_id to TMX
changelog: Internal, DDP Proofer, send ip_address and app_id to API

LG-7303 - send IP address to TMX, LG-7304 - send app_id to TMX

---

app/services/cloud_front_header_parser.rb
spec/services/cloud_front_header_parser_spec.rb
spec/services/irs_attempts_api/tracker_spec.rb

Turns out that if the app is passed 'CloudFront-Viewer-Address',
what get_header() sees is 'HTTP_CLOUDFRONT_VIEWER_ADDRESS'.
This seems hard to express in an automated test...
changelog: Internal, Attempts API, Fixes client port HTTP header

LG-7179 | Refer to HTTP header properly

---

app/services/proofing/mock/ddp_mock_client.rb
spec/services/proofing/mock/ddp_mock_client_spec.rb

This PR adds 3 "magic" SSNs that will trigger `review_status` values from the mock LexisNexis DDP proofer:
| SSN | Status |
| -- | -- |
| 666-77-8888 | `"reject"` |
| 666-77-9999 | `"review"` |
| 666-77-0000 | `nil` |
Any other SSN will return `pass`, as before. This will support testing of the integration of the proofer into the ID verification flow.

Allow triggering different review_status values in mock DDP proofer

---

app/controllers/users/webauthn_setup_controller.rb
app/policies/service_provider_mfa_policy.rb
spec/controllers/users/webauthn_setup_controller_spec.rb

Right now, both roaming/platform are logged as 'webauthn', but it would be helpful for us to distinguish them for this 🙂

Ensure distinction between WebAuthn Roaming and Platform in registration funnel

---

app/javascript/packages/document-capture/components/document-capture.tsx
app/javascript/packages/verify-flow/index.ts
app/javascript/packages/verify-flow/verify-flow-step-indicator.tsx
app/services/flow/flow_state_machine.rb
app/services/idv/steps/document_capture_step.rb
spec/controllers/idv/capture_doc_controller_spec.rb
spec/controllers/idv/doc_auth_controller_spec.rb

**Why**: In support of LG-6308, we'll want the ability to dynamically change the rendered contents of the step indicator while still at the document capture step.
(There isn't expected to be any visual difference in these changes)

Display step indicator in React app for document capture

---

app/javascript/packages/analytics/README.md
app/javascript/packages/document-capture/components/acuant-capture.tsx
app/javascript/packages/document-capture/components/capture-troubleshooting.jsx
app/javascript/packages/document-capture/components/review-issues-step.tsx
app/javascript/packages/document-capture/components/warning.tsx
app/javascript/packages/document-capture/context/acuant.tsx
app/javascript/packages/document-capture/context/analytics.jsx
app/javascript/packages/document-capture/higher-order/with-background-encrypted-upload.jsx
app/javascript/packs/document-capture.jsx
spec/javascripts/packages/document-capture/components/acuant-capture-spec.jsx
spec/javascripts/packages/document-capture/components/capture-advice-spec.jsx
spec/javascripts/packages/document-capture/components/capture-troubleshooting-spec.jsx
spec/javascripts/packages/document-capture/components/review-issues-step-spec.jsx
spec/javascripts/packages/document-capture/components/warning-spec.jsx
spec/javascripts/packages/document-capture/context/acuant-spec.jsx
spec/javascripts/packages/document-capture/context/failed-capture-attempts-spec.jsx
spec/javascripts/packages/document-capture/higher-order/with-background-encrypted-upload-spec.jsx

**Why**:
- For alignment to the Ahoy/CloudWatch-based Ruby `track_event` method, to which it corresponds
- For alignment to [`@18f/identity-analytics` trackEvent](https://github.com/18F/identity-idp/blob/5ed26ee750bd01de983875bac1503fae2be8fecf/app/javascript/packages/analytics/index.ts#L18-L28) method, which it [wraps](https://github.com/18F/identity-idp/blob/5ed26ee750bd01de983875bac1503fae2be8fecf/app/javascript/packs/document-capture.jsx#L98).
- To avoid falsely aligning to [NewRelic's `addPageAction`](https://docs.newrelic.com/docs/browser/new-relic-browser/browser-agent-spa-api/add-page-action/), to which it is **not related** (as of #6302).
I had initially considered removing the `AnalyticsContext` altogether and calling …

Rename JavaScript addPageAction to trackEvent

---

spec/features/idv/in_person_spec.rb

**Why**: The specs should pass regardless of the configured value, as in-person proofing does not depend on FSMv2 and shouldn't be concerned with the configuration. Additionally, we should expect that the default value is the more commonly-desired value (and likely matches the production experience).
I expect this is likely a hold-over from before #6635 where in-person proofing only supported FSMv2.

Remove FSMv2 configuration override in in-person feature specs

---

lib/telephony/pinpoint/sms_sender.rb

**Why**: because other errors were slipping through and
not being rescued correctly
changelog: Bug fixes, Multi-factor authentication, handle errors from vendors better
See: https://one.newrelic.com/nr1-core/errors/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=1800000&state=37783449-3874-df80-5a9f-08fc1def99cb

Rescue more generic pinpoint error

---

app/services/idv/steps/send_link_step.rb
app/services/irs_attempts_api/tracker_events.rb
spec/features/idv/doc_auth/send_link_step_spec.rb

changelog: Internal, Attempts API, Update in tracking event

LG-7097 Update Event: IDV phone upload link sent

---

app/javascript/packages/document-capture/components/document-capture.tsx
app/javascript/packages/verify-flow/index.ts
app/javascript/packages/verify-flow/verify-flow-step-indicator.spec.tsx
app/javascript/packages/verify-flow/verify-flow-step-indicator.tsx
app/services/idv/flows/in_person_flow.rb
spec/features/idv/doc_auth/address_step_spec.rb
spec/features/idv/doc_auth/document_capture_step_spec.rb
spec/features/idv/doc_auth/email_sent_step_spec.rb
spec/features/idv/doc_auth/link_sent_step_spec.rb
spec/features/idv/doc_auth/send_link_step_spec.rb
spec/features/idv/doc_auth/ssn_step_spec.rb
spec/features/idv/doc_auth/upload_step_spec.rb
spec/features/idv/doc_auth/verify_step_spec.rb
spec/features/idv/doc_capture/capture_complete_step_spec.rb
spec/features/idv/doc_capture/document_capture_step_spec.rb
spec/features/idv/in_person_spec.rb
spec/features/idv/steps/confirmation_step_spec.rb
spec/features/users/verify_profile_spec.rb
spec/javascripts/packages/document-capture/components/document-capture-spec.jsx
spec/support/features/idv_helper.rb
spec/support/features/idv_step_helper.rb
spec/support/features/in_person_helper.rb

**Why**: It's expected that the step indicator should update to reflect in-person steps as soon as the user opts to verify in-person, which technically occurs while the user is still at the document capture step.
Step|Before|After
---|---|---
Document Capture|![image](https://user-images.githubusercontent.com/1779930/186463408-32402c40-931a-4b42-9370-3eb4196b3ef2.png)|![image](https://user-images.githubusercontent.com/1779930/186463408-32402c40-931a-4b42-9370-3eb4196b3ef2.png)
Location|![image](https://user-images.githubusercontent.com/1779930/186463490-60072413-a271-4517-9bb1-6958ec86e847.png)|![image](https://user-images.githubusercontent.com/1779930/186463210-2823c4f0-40a6-4cdb-90ad-2e7c8f3705bc.png)
Prepare|![image](https://user-images.githubusercontent.com/1779930/186 …

LG-6308: Show in-person step indicator in initial steps

---

app/controllers/idv/inherited_proofing_controller.rb
app/services/idv/flows/inherited_proofing_flow.rb
app/services/idv/steps/inherited_proofing/get_started_step.rb
app/services/idv/steps/inherited_proofing_base_step.rb
app/views/idv/inherited_proofing/get_started.html.erb
config/application.yml.default
config/locales/inherited_proofing/en.yml
config/locales/inherited_proofing/es.yml
config/locales/inherited_proofing/fr.yml
config/routes.rb
lib/identity_config.rb
spec/controllers/idv/inherited_proofing_controller_spec.rb
spec/views/idv/inherited_proofing/get_started.html.erb_spec.rb

The objective is to create a single landing page with minimal code, that used the FSM (v2) methodology.
technical notes on creating the inherited_proofing_controller.rb and use of FSM (flow state machine):
- user session management is not included
- it does not (use these before hooks):
:confirm_two_factor_authenticated, :redirect_if_pending_in_person_enrollment, :redirect_if_pending_profile,
:extend_timeout_using_meta_refresh_for_select_paths, :redirect_if_flow_completed, :override_document_capture_step_csp,
:update_if_skipping_upload, :check_for_outage, :override_csp_for_threat_metrix
- analytics tracking is not included
- getting_started.html.erb does not include: javascript_packs_tag_once('document-capture-welcome')
- not feature flagged

LG-6970 create inherited proofing basic landing page

---

app/controllers/concerns/two_factor_authenticatable_methods.rb
app/controllers/users/two_factor_authentication_controller.rb
app/services/irs_attempts_api/tracker_events.rb
spec/controllers/users/two_factor_authentication_controller_spec.rb

1. Added `mfa_enroll_phone_otp_sent_rate_limited` attempt event.
2. Added `mfa_login_phone_otp_sent_rate_limited` attempt event.
3. Added unit tests in `two_factor_authentication_controller_spec.rb` for the above events.

LG-7200 - added mfa_phone_otp_sent_rate_limited events for login and enroll

---

app/controllers/api/verify/password_confirm_controller.rb
app/controllers/idv/personal_key_controller.rb
spec/controllers/api/verify/password_confirm_controller_spec.rb
spec/controllers/idv/personal_key_controller_spec.rb

Why? 
If a user fails threatmetrix verification we want to redirect them to a come back later page.

LG -7015 Redirect user to "Sorry" page on TMX verification failure

---

app/javascript/packages/assets/package.json
app/javascript/packages/time-element/index.spec.ts
app/javascript/packages/time-element/index.ts
spec/javascripts/packages/document-capture/components/acuant-capture-spec.jsx
spec/javascripts/packages/document-capture/components/document-capture-spec.jsx
spec/javascripts/support/dom.js

**Why**: As a precursor to #6841, in order to prevent timing issues between upgrading to Node.js v16 in the IdP and in the GitLab CI runner, update specs so that they pass in the current (14) and upgraded (16) versions.
Ensure tests pass in Node.js v14 and Node.js v16:
```
nvm install 16 && nvm use 16 && yarn && yarn test
```
```
nvm install 14 && nvm use 14 && yarn && yarn test
```

Update JavaScript tests for cross-version compatibility (14, 16)

---

app/forms/api/profile_creation_form.rb
app/models/profile.rb
config/application.yml.default
lib/identity_config.rb
spec/controllers/api/verify/password_confirm_controller_spec.rb
spec/forms/api/profile_creation_form_spec.rb

**Why**: To prevent fraudulent verified profiles by using the lexisnexis threatmetrix API saving those profiles that have not passed threatmetrix in a pending state `threatmetrix_review_pending` so they can be reviewed and potentially enabled by the fraud team.
**How**: Threatmetrix review_status must be 'pass' if threatmetrix is enabled and required via new feature flag `lexisnexis_threatmetrix_required_to_verify`.  Otherwise the profile will be created in a pending state.  If threatmetrix is enabled but not required the threatmetrix backend calls will run and store the results but it will NOT disable the verified profile.  Follows from these prs: https://github.com/18F/identity-idp/pull/6806

LG-7305 Make sure ThreatMetrix failure results in disabled account

---

app/services/irs_attempts_api/tracker_events.rb

Alphabetize tracker_events

---

app/controllers/api/verify/document_capture_controller.rb
app/forms/idv/api_document_verification_form.rb
app/forms/idv/api_image_upload_form.rb
app/services/idv/steps/doc_auth_base_step.rb
app/services/irs_attempts_api/tracker_events.rb
spec/features/idv/doc_auth/document_capture_step_spec.rb
spec/forms/idv/api_document_verification_form_spec.rb
spec/forms/idv/api_image_upload_form_spec.rb

LG-7108 Add Event: IDV Document upload rate limited

---

app/forms/idv/api_image_upload_form.rb
spec/controllers/idv/image_uploads_controller_spec.rb

changelog: Internal, Attempts API, Update in tracking event

LG-7096 Update Event: IDV doc upload submitted

---

app/jobs/resolution_proofing_job.rb
app/services/idv/agent.rb
app/services/idv/steps/verify_base_step.rb
app/services/proofing/base.rb
app/services/proofing/lexis_nexis/ddp/proofer.rb
app/services/proofing/mock/ddp_mock_client.rb
spec/features/idv/doc_auth/verify_step_spec.rb
spec/jobs/resolution_proofing_job_spec.rb
spec/services/idv/agent_spec.rb
spec/services/idv/steps/ipp/verify_step_spec.rb
spec/services/idv/steps/verify_step_spec.rb
spec/services/proofing/mock/ddp_mock_client_spec.rb

And a few other fixes:
- updating the mock proofer to be more realistic
- update plumbing
- remove uuid_prefix as a job argument since it's already
inside applicant_pii
changelog: Internal, Bug fixes, Updates data sent to vendors

Fix wiring up of uuid_prefix and request_ip for TMX

---

app/services/proofing/lexis_nexis/ddp/verification_request.rb
spec/fixtures/proofing/lexis_nexis/ddp/request.json
spec/fixtures/proofing/lexis_nexis/ddp/successful_response.json

**Why:** Per LexisNexis email on 19 August 2022 we should use the `national_id_number` param instead of the `ssn_hash` param.
**How:** I have replaced params in the VerificationRequest and fixture file, and added `national_id_type` per [the documentation](https://portal.threatmetrix.us/kb/implementation/apis/session_query_api.htm).
changelog: Internal, ThreatMetrix API, Use non-hashed param

Use non-hashed SSN param, removed hashed version

---

app/services/proofing/aamva/proofer.rb
app/services/proofing/mock/address_mock_client.rb
app/services/proofing/mock/state_id_mock_client.rb
spec/controllers/idv/phone_controller_spec.rb
spec/services/idv/agent_spec.rb
spec/services/idv/phone_step_spec.rb
spec/services/proofing/mock/address_mock_client_spec.rb
spec/services/proofing/mock/ddp_mock_client_spec.rb
spec/services/proofing/mock/resolution_mock_client_spec.rb
spec/services/proofing/mock/state_id_mock_client_spec.rb
spec/support/controller_helper.rb
spec/support/mock_proofer_helper.rb

(adding in Team Ada since this might help your team too)

Add specs to make sure mock/real proofers stay in sync

---

app/forms/api/profile_creation_form.rb
app/forms/gpo_verify_form.rb
app/services/idv/session.rb

**Why**: Since they are duplicated and one is unused. Consolidate on the name without "pending" reference to avoid ambiguity between "establishing" and "pending" enrollment statuses (technically, the enrollment is still "establishing" at this point, not "pending"). Removes feature guard conditions to avoid future clean-up, since it would be safe to check the proofing component with the understanding that it would only be assigned in earlier steps if the feature were enabled.

LG-7383: Remove redundant in-person condition methods

---

app/controllers/sign_up/registrations_controller.rb
app/forms/register_user_email_form.rb
app/services/irs_attempts_api/tracker_events.rb
app/services/request_password_reset.rb
spec/forms/register_user_email_form_spec.rb
spec/views/sign_up/registrations/new.html.erb_spec.rb

LG-6988 Email Submission Rate Limit events

---

app/services/idv/agent.rb

This was a slip up that led to errors in int. The new instances will call without the arg and the old instance will not default to nil. This leads to an argument error.
This commit fixes that

Add the DOB year only arg back to the resolution proofer job call

---

app/services/proofing/lexis_nexis/ddp/verification_request.rb
spec/fixtures/proofing/lexis_nexis/ddp/request.json
spec/services/proofing/lexis_nexis/ddp/proofing_spec.rb
spec/services/proofing/lexis_nexis/ddp/verification_request_spec.rb

LG-7384
**Why:** Per LexisNexis email on 29 August 2022, these three params should be used to transmit drivers' license details:
- `account_drivers_license_issuer`
- `account_drivers_license_number`
- `account_drivers_license_type`
We should replace the `drivers_license_number_hash` which LN FraudPoint cannot process
**How:** I have replaced the params in the VerificationRequest and fixture file, and added `state_id_jurisdiction` to tests
changelog: Internal, ThreatMetrix API, Use non-hashed param

Drivers' license as unhashed params

---

README.md

From some anecdotal feedback I've heard from developers:
- Some have expected that the application would send real emails
- Clarify that the application does not send real emails
- Some would test email template changes by going through the real flows
- Clarify that Rails template previews exist to simplify this process
To better emphasize the common workflows, I also chose to remove some of the details around running Mailcatcher on a different host or port. I think this _could_ be useful information for someone at some point, but I don't think I've ever used it in my time on the program, so it felt like a detail that could be omitted from the top-level documentation.

Clarify email delivery in local development

---

app/controllers/concerns/two_factor_authenticatable_methods.rb
app/services/irs_attempts_api/tracker_events.rb
spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb
spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb
spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb
spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb
spec/controllers/users/two_factor_authentication_controller_spec.rb

1. Moved rate_limited events to be fired before sign out happens, so that session remains valid and they get stored in redis properly by the tracker.
2. Removed the `success` attribute from `mfa_login_phone_otp_sent_rate_limited` and `mfa_enroll_phone_otp_sent_rate_limited` for consistency with other rate_limited events.
3. Changed parameter `type` to `mfa_device_type` to match schema and for consistency between events
changelog: Internal, Attempts API, Bugfix events

LG-7397 - Bugfix: Moved rate_limited events to be called before sign out.

---

scripts/inherited-proofing-va-test.rb

Create test VA script to obtain user PII
Usage:
1) Run with no ARGV and _BASE_URI_ in the Idv::InheritedProofing::Va::Service
will default to: _IdentityConfig.store.inherited_proofing_va_base_url_.
`$ rails r scripts/inherited-proofing-va-test.rb`
2) To override _BASE_URI_ in the _Idv::InheritedProofing::Va::Service_ class:
`$ rails r scripts/inherited-proofing-va-test.rb https://localhost:3000`

[LG-7394] Create test VA script to obtain user PII

---

app/services/idv/steps/ipp/ssn_step.rb
app/services/idv/steps/ssn_step.rb
app/views/idv/in_person/ssn.html.erb
app/views/idv/shared/_ssn.html.erb
spec/services/idv/steps/ipp/ssn_step_spec.rb
spec/views/idv/shared/_ssn.html.erb_spec.rb

**Why?** ThreatMetrix usage will be tied more closely to IPP partners initially.
**How?** Mostly update `ipp/ssn_step.rb` to generate a `threatmetrix_session_id`, and pass that to the front end to ensure the resulting `<script>` tag is generated. There's some DRY work that could be done in a future PR to get the two `SsnStep` classes to share a little more code.
changelog: Upcoming Features, ThreatMetrix, Add ThreatMetrix to In-Person Proofing flow

LG-7410: Add ThreatMetrix back to In-Person Proofing flow

---

app/services/proofing/lexis_nexis/ddp/response_redacter.rb

**Why**: It is echoing the request data which contains PII.
**How**: Remove it from the allowed fields in the response with ResponseRedacter via this PR: https://github.com/18F/identity-idp/pull/6857

Remove integration_hub_results from threatmetrix response (redact)

---

spec/controllers/api/irs_attempts_api_controller_spec.rb
spec/services/irs_attempts_api/envelope_encryptor_spec.rb
spec/services/irs_attempts_api/redis_client_spec.rb
spec/services/irs_attempts_api/tracker_spec.rb

This adds a small additional layer to safeguard against future changes to the API to alert us if we are ever storing events in plaintext in Redis.  It also changes some of the event metadata in tests to be PII to be slightly more precise about the type of data stored.  Using PII also helps in the controller specs since the session class will automatically fail [if it detects plaintext PII](https://github.com/18F/identity-idp/blob/fd71f6babd37a6f2e7d9f082eb7c6a1ff2534cf1/lib/session_encryptor.rb#L54)

Add safeguard tests to ensure IRS events are not stored in plaintext

---

.gitlab-ci.yml
app/services/access_token_verifier.rb
app/services/analytics_events.rb
spec/controllers/openid_connect/user_info_controller_spec.rb

- Logging: Log service provider and IAL for userinfo access token ([#6899](https://github.com/18F/identity-idp/pull/6899))

Deploy RC 206.1 to Production

---

app/services/proofing/lexis_nexis/ddp/verification_request.rb
spec/fixtures/proofing/lexis_nexis/ddp/request.json

LexisNexis advised that we should correct the keys:
- `account_drivers_license_type`
- `account_drivers_license_issuer `
I've hard-coded the first. For the second, we weren't seeing a `state_id_jurisdiction` in the data so I wonder if others feel that `state` is a good fallback?
UPDATE: Per a comment from @zachmargolis I have removed the state fallback. I propose we should verify `state_id_jurisdiction` is working correctly, if we're relying on it.
changelog: Include account_drivers_license_type, alternate way to get state

Include account_drivers_license_type, alternate way to get state

---

app/controllers/users/email_confirmations_controller.rb
app/services/account_reset/delete_account.rb
app/services/analytics_events.rb
spec/controllers/users/email_confirmations_controller_spec.rb
spec/services/account_reset/delete_account_spec.rb

Pulls in a couple bug fixes
- Email confirmation: Do not allow confirming email addresses via add email controller for unconfirmed accounts ([#6897](https://github.com/18F/identity-idp/pull/6897))
- Account reset: Fixed exception on account reset ([#6888](https://github.com/18F/identity-idp/pull/6888))

Deploy RC 206.2 to Production

---

app/services/proofing/result.rb
spec/jobs/resolution_proofing_job_spec.rb

small add-on to https://github.com/18F/identity-idp/pull/6903

Add regression spec for redaction in ResolutionProofingJob

---

app/assets/images/alert/pending.svg
app/assets/stylesheets/components/_step-indicator.scss
app/controllers/idv/personal_key_controller.rb
app/controllers/idv/review_controller.rb
app/javascript/packages/eslint-plugin/CHANGELOG.md
app/javascript/packages/eslint-plugin/configs/recommended.js
app/javascript/packages/step-indicator/step-indicator-step.spec.tsx
app/javascript/packages/step-indicator/step-indicator-step.tsx
app/javascript/packages/verify-flow/verify-flow-step-indicator.spec.tsx
app/javascript/packages/verify-flow/verify-flow-step-indicator.tsx
app/services/idv/flows/doc_auth_flow.rb
app/views/idv/come_back_later/show.html.erb
app/views/idv/gpo_verify/index.html.erb
app/views/shared/_step_indicator_step.html.erb
config/locales/step_indicator/en.yml
config/locales/step_indicator/es.yml
config/locales/step_indicator/fr.yml
spec/controllers/idv/personal_key_controller_spec.rb
spec/controllers/idv/review_controller_spec.rb
spec/features/idv/steps/confirmation_step_spec.rb
spec/features/users/verify_profile_spec.rb
spec/views/idv/come_back_later/show.html.erb_spec.rb
spec/views/shared/_step_indicator.html.erb_spec.rb
spec/views/shared/_step_indicator_step.html.erb_spec.rb

Related: #6846
**Why**: As a user, I want to see a step indicator at the top of the page that shows me moving forward in the flow, so that it's easy to understand that I'm making progress and what I still need to do.
Step|Before|After
---|---|---
GPO Opt-in|![Screen Shot 2022-08-29 at 10 44 23 AM](https://user-images.githubusercontent.com/1779930/187235631-2638acc2-3e8a-4720-a113-1dcf683eea0c.png)|![Screen Shot 2022-08-29 at 10 44 23 AM](https://user-images.githubusercontent.com/1779930/187235631-2638acc2-3e8a-4720-a113-1dcf683eea0c.png)
Password confirm|![Screen Shot 2022-08-29 at 10 44 38 AM](https://user-images.githubusercontent.com/1779930/187235651-dfa81237-a45c-44cc-98ce-9c87ead32f94.png)|![Screen Shot 2022-08-29 at 10 42 28 …

LG-6307: Remove pending steps from step indicator

---

app/components/phone_input_component.rb
app/services/phone_number_capabilities.rb
spec/components/phone_input_component_spec.rb

I noticed we spend a disproportionate amount of time rendering templates on phone input pages in [NewRelic](https://one.newrelic.com/nr1-core/apm-features/transactions/MTM3NjM3MHxBUE18QVBQTElDQVRJT058MTA0NDEwMDY1?account=1376370&begin=1661966100000&end=1661966280000&state=0c2819b1-c4d7-4897-760b-525cba76bd61)
Ex:
I did a bit of profiling and it looks like it is in large part due to many calls to `PhoneNumberCapabilities.translated_international_codes`.  It is not clear that it is an expensive operation that iterates over all of the country codes (currently 220) and translates them.  `PhoneInputComponent#international_phone_codes` calls it for every country code (up to a total of 220^2 times).
I tried two approaches.  The first being caching the results of …

Improve rendering speed of phone input component

---

app/javascript/packages/document-capture/context/device.js
app/javascript/packages/document-capture/context/index.ts
app/javascript/packages/normalize-yaml/index.js
app/javascript/packages/secret-session-storage/index.ts
app/javascript/packages/verify-flow/context/flow-context.tsx
app/javascript/packs/document-capture.jsx
app/javascript/packs/document-capture.tsx
package.json
yarn.lock

**Why**: Take advantage of the latest features and bug fixes.
Errors addressed after upgrade:
```
$ tsc
app/javascript/packages/normalize-yaml/index.js:20:29 - error TS2463: A binding pattern parameter cannot be optional in an implementation signature.
20 function normalize(content, { prettierConfig, exclude } = {}) {
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app/javascript/packages/secret-session-storage/index.ts:110:30 - error TS2345: Argument of type 'ArrayBuffer' is not assignable to parameter of type 'Uint8Array'.
Type 'ArrayBuffer' is missing the following properties from type 'Uint8Array': BYTES_PER_ELEMENT, buffer, byteOffset, copyWithin, and 24 more.
110       return JSON.parse(ab2s(data));
~~~~
app/javascript/packages/secret-session-storage/index.ts:125:84 - error TS2345: Argument of …
```

Upgrade TypeScript from 4.5 to 4.8

---

app/jobs/get_usps_proofing_results_job.rb
app/models/in_person_enrollment.rb
app/services/usps_in_person_proofing/enrollment_helper.rb
spec/factories/in_person_enrollments.rb
spec/jobs/get_usps_proofing_results_job_spec.rb
spec/models/in_person_enrollment_spec.rb
spec/services/usps_in_person_proofing/enrollment_helper_spec.rb

The USPS API requires us to specify a unique ID when we create an enrollment. Initially we did not store that value in the database and instead just grabbed 18 digits of the user's UUID -- this was a temporary workaround until we fleshed out the unique ID generation better
Since that initial workaround we've added a `unique_id` database column on the InPersonEnrollment model. The polling job sets that value and uses it once it's set, but it isn't used when we actually create the enrollment in the USPS API
1. When the user visits the location page we generate an enrollment with status == `establishing`. No unique ID is generated and the field is left empty
2. When the user confirms their password we create an enrollment in the USPS API. For the unique ID we use …

LG-7345: Generate a unique ID when creating enrollments

---

app/controllers/idv_controller.rb
spec/controllers/idv_controller_spec.rb

When a VA user completes authorization through openid_connect, they are redirected to inherited proofing verification.
changelog: Upcoming Features, Inherited proofing, verification step redirects to inherited proofing
Refer to the upper-right portion of this diagram: https://www.figma.com/file/Lj6tqLhohJMTR4IvvoU2BI/VA-Inherited-Proofing-Architecture-Diagram

LG-6959 IDV verify redirects to inherited proofing

---

app/controllers/concerns/verify_sp_attributes_concern.rb
app/controllers/openid_connect/authorization_controller.rb
spec/controllers/concerns/verify_sp_attributes_concern_spec.rb

Currently, `VerifySpAttributesConcern` makes repeated calls to `sp_session_identity`.  The database call is cached after the first call, but there is still a noticeable amount of overhead in doing that.
This PR cleans up the behavior to only maybe hit the database once and passes the result to the functions that follow.
Performance benchmark available in commit https://github.com/18F/identity-idp/commit/b924b5a96b0a5126c1d3f23fbf13fa4679375d52
```
```

Improve speed of VerifySpAttributesConcern

---

app/javascript/packages/device/index.js
app/services/idv/steps/upload_step.rb
spec/features/idv/doc_auth/email_sent_step_spec.rb
spec/features/idv/doc_auth/upload_step_spec.rb
spec/javascripts/packages/device/index-spec.js

This PR deals with [LG-7277](https://cm-jira.usa.gov/browse/LG-7277), for which it was discovered that the Acuant SDK was not being loaded on iPads or Android tablets.
It turns out that Apple has changed the User Agent header for Safari on iPadOS, such that the result indicates a Macintosh running Safari. The workaround that many people have been using is to detect, on the frontend, the `window.navigator.maxTouchPoints`, which on a tablet like the iPad, will be 5 (and usually 0 on a laptop or desktop).
After [updating the checks](https://github.com/18F/identity-idp/commit/8ec1b127f64895fc0442a73077bdbd668b9ccb11#diff-9815e80bb77c594216dcb42905c8df514f096d953b02b5e0db3fb162a26a4895) we use to indicate mobile on the frontend, I found that the frontend sets a hidden input with a …

LG-7277 Acuant Not Working for iPads

---

config/locales/inherited_proofing/es.yml
config/locales/inherited_proofing/fr.yml
spec/views/idv/inherited_proofing/get_started.html.erb_spec.rb

[LG-7244](https://cm-jira.usa.gov/browse/LG-7244)
The Inherited Proofing "Getting Started" page needs (in addition to English), Spanish and French as well. This adds the translation (.yml) files for fr and es (Spanish and French respectfully).

[LG-7244] Translate the getting started page

---

app/services/service_provider_seeder.rb
config/service_providers.localdev.yml

**Why**: no longer used as of #2732
**Note**: 18f/identity-idp-config#1024 needs to be merged first,
otherwise this will break during deploys

Remove last references to uuid_priority

---

app/services/db/proofing_cost/add_user_proofing_cost.rb
app/services/db/sp_cost/add_sp_cost.rb
app/services/idv/steps/verify_base_step.rb
db/primary_migrate/20220906112214_add_threatmetrix_to_proofing_cost.rb
db/schema.rb
spec/features/reports/proofing_costs_report_spec.rb
spec/services/idv/steps/verify_wait_step_show_spec.rb

**Why**: To track threatmetrix costs on a per user, per sp, and global basis.
**How**: Add threatmetrix symbol to the allow list for the generic costing routines, add a field in the db to store counts.  hookup calls.

LG-7442 Add Threatmetrix Costing

---

app/services/idv/session.rb
spec/controllers/idv/review_controller_spec.rb

**Why**: Code was added to password_controller but the password screen is actually called review_controller (another spot where a profile is created)
**How**: Follow up to
https://github.com/18F/identity-idp/pull/6817

LG-7305 Make sure ThreatMetrix failure disables profile Part 2

---

app/controllers/idv_controller.rb
app/services/idv/steps/verify_base_step.rb
app/services/irs_attempts_api/tracker_events.rb
spec/controllers/idv_controller_spec.rb
spec/features/idv/doc_auth/verify_step_spec.rb

LG-7109 Add Event: IDV verification rate limited

---

.rubocop.yml

Context: https://github.com/18F/identity-idp/pull/6713#discussion_r964884841
**Why**: For consistency, and to reduce toil in code review.
Documentation: https://docs.rubocop.org/rubocop/cops_style.html#stylemethoddefparentheses

Enable Rubocop Style/MethodDefParentheses

---

app/assets/stylesheets/components/_memorable-date.scss
app/assets/stylesheets/components/all.scss
app/components/memorable_date_component.html.erb
app/components/memorable_date_component.rb
app/components/memorable_date_component.ts
app/javascript/packages/memorable-date/index.spec.ts
app/javascript/packages/memorable-date/index.ts
app/javascript/packages/memorable-date/package.json
app/javascript/packages/validated-field/validated-field-element.spec.ts
app/javascript/packages/validated-field/validated-field-element.ts
app/javascript/packages/verify-flow/steps/personal-key-confirm/personal-key-confirm-step.spec.tsx
app/services/idv/steps/ipp/state_id_step.rb
app/views/idv/in_person/state_id.html.erb
config/locales/components/en.yml
config/locales/components/es.yml
config/locales/components/fr.yml
config/locales/in_person_proofing/en.yml
config/locales/in_person_proofing/es.yml
config/locales/in_person_proofing/fr.yml
config/locales/time/en.yml
config/locales/time/es.yml
config/locales/time/fr.yml
spec/components/memorable_date_component_spec.rb
spec/features/idv/doc_auth/send_link_step_spec.rb
spec/features/phone/add_phone_spec.rb
spec/services/idv/steps/ipp/state_id_step_spec.rb
spec/support/features/in_person_helper.rb

Reverts https://github.com/18F/identity-idp/pull/6940.
Fix for the issue related to this revert is in https://github.com/18F/identity-idp/pull/6938.

 LG-6497: Reintroduce Memorable Date on IPP State ID Page

---

spec/features/idv/in_person_spec.rb

**Why**: So that our builds pass reliably.
Example: https://gitlab.login.gov/lg/identity-idp/-/jobs/68130
```
1) In Person Proofing allows the user to go back to document capture from prepare step
Failure/Error: expect(page).to have_button(t('doc_auth.buttons.add_new_photos'))
expected to find button "Add new photos" that is not disabled but there were no matches
```
The operating hypothesis is that the "< Back" link on the Location selection screen can shift position on the page as the locations become loaded which may cause some issues with the accuracy of the click interaction, so the changes here waits for the locations to finish loading before proceeding to click "< Back".

Try to fix intermittent failure for in-person feature spec

---

app/controllers/users/passwords_controller.rb
app/services/irs_attempts_api/tracker_events.rb
spec/controllers/users/passwords_controller_spec.rb

LG-7431 Logged In User Change Password

---

scripts/inherited_proofing/va/lexis_nexis/test_script.rb
scripts/inherited_proofing/va/user_attributes/test_script.rb

Qualify script rails executable properly with bin/ which is necessary to run in environments other than local.

Qualify script rails executable properly with bin/

---

app/services/db/monthly_sp_auth_count/total_monthly_auth_counts.rb
spec/jobs/reports/total_monthly_auths_report_spec.rb
spec/services/db/monthly_auth_count/total_monthly_auth_counts_spec.rb

**Why**: We've found some discrepancies with the aggregated monthly table so this helps us have more precise reports
(this is just the monthly auths report part of https://github.com/18F/identity-idp/pull/6935, so it doesn't need a new DB index)

Update total-monthly-auths report to pull from the raw table

---

app/controllers/openid_connect/authorization_controller.rb
app/forms/openid_connect_authorize_form.rb
app/forms/openid_connect_token_form.rb
app/services/analytics_events.rb
spec/controllers/openid_connect/authorization_controller_spec.rb
spec/controllers/openid_connect/token_controller_spec.rb
spec/forms/openid_connect_authorize_form_spec.rb
spec/forms/openid_connect_token_form_spec.rb

**Why**: to assist with debugging requests from partners
changelog: Internal, Logging, Log hash of OpenID Connect "code" param

Log digest of OIDC "code" param (LG-7440)

---

app/presenters/idv/in_person/ready_to_verify_presenter.rb
spec/presenters/idv/in_person/ready_to_verify_presenter_spec.rb

[Ticket](https://cm-jira.usa.gov/browse/LG-7344)
What
This pr updates the ReadyToVerifyPresenter so that it uses the enrollment_established_at date to create the due date that is presented to the user. If there is no enrollment_established_at date attached to the enrollment then the created_at date is used instead. 
Why
This update will ensure that if a user chooses to receive confirmation in the mail the 30 day period they have to complete their in person verification will start AFTER inputting the code they get in the mail rather than starting when they began the process online. This will give such users the full 30 days. 
Here we can see that the enrollment_established_at property is the one used to format the date:

update ready to verify presenter to use enrollment_established_at

---

app/services/idv/steps/send_link_step.rb
app/services/irs_attempts_api/tracker_events.rb
spec/features/idv/doc_auth/send_link_step_spec.rb

1. Added a new event that is tracked whenever the user is locked out by exceeding the rate limit for submitting their phone number repeatedly for instruction links during idv workflow. 
2. The event was renamed from `idv_phone_submitted_rate_limited` to `idv_phone_send_link_rate_limited` as `idv_phone_submitted_rate_limited` is covered already by `idv_phone_otp_submitted_rate_limited`, everywhere else. 

LG-7110 added new event for idv_phone_send_link_rate_limitted

---

app/controllers/idv/setup_errors_controller.rb
app/controllers/redirect/contact_controller.rb
app/services/analytics_events.rb
app/views/idv/setup_errors/show.html.erb
config/routes.rb
spec/controllers/idv/setup_errors_controller_spec.rb
spec/controllers/redirect/contact_controller_spec.rb

Why? Tracking analytics for ThreatMetrix failure proofing page. Also tracking whenever a user accesses the contact page.

LG-7411 Analytics event for TM Proofing Failure Page

---

app/views/idv/in_person/state_id.html.erb
config/locales/time/en.yml

- Set min date for State ID page to January 1, 1900
- Remove leading zero from day (English translation)
- Displays **January 1, 1900**

LG-6497: Set min date for State ID page to January 1, 1900

---

app/services/idv/in_person_config.rb
config/application.yml.default
db/primary_migrate/20220909021833_add_in_person_proofing_enabled_to_service_provider.rb
db/schema.rb
lib/identity_config.rb
spec/controllers/idv/in_person_controller_spec.rb
spec/services/idv/in_person_config_spec.rb
spec/views/idv/shared/_document_capture.html.erb_spec.rb

This supplants the config key `in_person_proofing_enabled_issuers` with a new database field `in_person_proofing_enabled` on each `ServiceProvider` record. This field will be managed elsewhere.
1. Run the migrations in this repo, then start the IDP
2. Setup and run [the Sinatra app](https://github.com/18f/identity-oidc-sinatra)
3. Open the Sinatra app - default local stack URL is http://127.0.0.1:9292
4. Select "IAL2" in the options under the sign-in button, then click "Sign in"
5. Proceed through to the doc auth step of IPP
6. Trigger a non-terminal failure of doc auth, e.g. image resolution error
7.  You should not initially see the option to verify at a post office
8. Run the Rails console in the IDP repo folder via a terminal:
```sh
rails console
```
9. Run this Ruby code in the …

LG-7203: Use DB for service provider IPP feature enablement

---

Makefile
app/services/irs_attempts_api/tracker_events.rb

Turns out when I added #6730, I forgot to wire the check into `make lint` so it wasn't getting run in CI 🤦

Enforce YARD parameter documentation for tracker_events.rb, fix errors

---

app/services/usps_in_person_proofing/proofer.rb

**Why**: It's noisy in development, and STDOUT is ignored in prod
(see [Slack thread for context](https://gsa-tts.slack.com/archives/CUG1ETRKR/p1663257242357579))

Remove Faraday request logging

---

app/controllers/application_controller.rb
app/services/analytics_events.rb
app/services/irs_attempts_api/attempt_event.rb
app/services/irs_attempts_api/tracker.rb
config/application.yml.default
lib/identity_config.rb
spec/services/irs_attempts_api/tracker_spec.rb
spec/support/fake_analytics.rb

Also adds a feature flag in case we discover this has some sort of performance hit to generate and JSONify and throw away all these strings

Log metadata about Attempts API events (LG-7562)

---

app/jobs/get_usps_proofing_results_job.rb
config/application.yml.default
lib/identity_config.rb
spec/jobs/get_usps_proofing_results_job_spec.rb

Adds a configurable delay, in milliseconds, between requests to the USPS API when we are polling for enrollment status updates. The default value is 1 second

LG-7155: Add delay between polling requests to USPS

---

app/services/usps_in_person_proofing/proofer.rb
config/application.yml.default
lib/identity_config.rb
spec/services/usps_in_person_proofing/proofer_spec.rb

This pull request sources the `client_id` value from the config instead of hardcoding it. See [LG-6925](https://cm-jira.usa.gov/browse/LG-6925) for more details.
I plan to have the config deployed with the `client_id` to each environment before or during the deployment of this code (and will coordinate w/ others before merging to make sure that happens).

LG-6925: Move client_id field for USPS API from hardcoded value to config

---

Procfile
README.md

This PR updates the `Procfile` and `application.yml` files in the repository with commented-out options that can be uncommented and modified for running the application in https locally.
Comments also provide context for how to run https locally and how to use the given options.
I have found that having to go back and forth to several docs to find the appropriate keys and values to use is a bit annoying, and I think this might be a little easier for new people coming on also. LMK what you think.

Local Dev Config

---

app/controllers/idv/in_person_controller.rb

**Why**: Because it's unused. This behavior is enforced via the `check_or_render_not_found` defined at the top of the controller:
https://github.com/18F/identity-idp/blob/71f3bd29473eed75af02fcf59920099f3871dcc5/app/controllers/idv/in_person_controller.rb#L5

Remove unused method render_404_if_disabled

---

CONTRIBUTING.md
scripts/changelog_check.rb

**Why**: So that the distinction between the available options is more clearly understood, and so that a developer doesn't need to sift through the implementation of the linter to understand which categories are available.

Document available changelog categories

---

app/views/shared/_in-person-verification-results-email-lower.html.erb

**Why**: Because the results email instructs the user to sign in through the associated service provider, and since it's expected to match the text link immediately following the button. This was intended to be implemented in LG-7076 (#6707).
In the screenshot below, the revisions here change the "Sign in" button to link to the same place as the text following the button. In this example, linking to http://localhost:9292 (the partner homepage) instead of http://localhost:3000/verify (the IdV URL).

Fix "Sign in" button link for IPP results email

---

app/javascript/packages/document-capture/components/in-person-prepare-step.tsx
app/views/idv/in_person/ready_to_verify/show.html.erb
app/views/user_mailer/in_person_ready_to_verify.html.erb
config/locales/in_person_proofing/en.yml
config/locales/in_person_proofing/es.yml
config/locales/in_person_proofing/fr.yml
spec/mailers/previews/user_mailer_preview.rb

**Why**: As I user I want to know if it's ok for me to bring a physical copy or digital of my secondary ID if my current address is not the same as the one printed on my physical address.
---|---|---
Prepare|![lg-7362-prepare-before](https://user-images.githubusercontent.com/1779930/190671240-56e336f9-2769-4eae-9122-2110ce61f423.png)|![lg-7362-prepare-after](https://user-images.githubusercontent.com/1779930/190671237-bf3293a1-7ae8-4d8e-a07e-21797e19b187.png)
Barcode|![lg-7362-barcode-before](https://user-images.githubusercontent.com/1779930/190671224-a1a5c75f-b641-486f-95fd-f916c67217f0.png)|![lg-7362-barcode-after](https://user-images.githubusercontent.com/1779930/190671218-ac878fb5-f725-42c1-bd71-e73e0c2f320b.png) …

LG-7362: Add copy for digital forms of IPP proof of address

---

CONTRIBUTING.md

**Why**:
- For better clarity around the overall form of a changelog message, where it should exist, and details about subcategory and description of the message.
- Create heading anchor for easier reference linking
Builds upon #6977, based on [continued Slack discussion](https://gsa-tts.slack.com/archives/C03FA4VBN76/p1663347610009969?thread_ts=1663340399.121379&cid=C03FA4VBN76).

Expand changelog documentation with more detail

---

app/assets/stylesheets/email.css.scss

**Why**: So that the Process List as displayed in email messages is consistent with the design system reference implementation.
It's assumed this is a side-effect of the revisions in #6736, where an increase in default email line-height of 1.3 to 1.5 caused an offset of the appearance of the text of the list item number. Explicitly assigning the line-height ensures correct math.
Before|After
---|---

Improve display of Process List in email notifications

---

app/decorators/user_decorator.rb
spec/decorators/user_decorator_spec.rb

Currently selects all and only takes the second.  This is a small change to only select up to 2

Limit selection of sign in events to 2 when fetching second_last_signed_in_at

---

app/services/idv/steps/inherited_proofing/phone_step.rb
app/services/idv/steps/inherited_proofing/verify_info_step.rb

This is a quick fix I noticed looking at this code earlier

Fix a typo in the step indicator constants for inherited proofing

---

app/services/idv/session.rb
spec/services/idv/session_spec.rb

**Why:**
- We were sometimes passing Pii::Attribute structs and other times
passing hashes to this function. While it wasn't causing a technical problem now
it is confusing
- The other two places where we use EnrollmentHelper#schedule_in_person_enrollment
we are already passing a Pii::Attributes struct (FSM v1 flow password confirmation page and
the GPO address verification + in-person proofing flow)
changelog: Upcoming Features, In-person proofing, Normalize arguments
for creating an enrollment

LG-7123: Always use Pii::Attribute when creating enrollment

---

app/forms/idv/api_image_upload_form.rb
app/jobs/document_proofing_job.rb
app/services/idv/steps/document_capture_step.rb

PR #6915 added in A/B testing on skipping the Acuant SDK. It appears in testing against `dev` that the class was not properly scoped to the module.

Scope the NativeCameraABTest to the Idv module

---

app/services/proofing/lexis_nexis/ddp/response_redacter.rb

JSON keys appearing in the Production LexisNexis connection JSON return that we want to allow in the log
Each addition was checked in the [Attribute Reference Matrix](https://portal.threatmetrix.us/kb/implementation/attributes/attribute%20reference%20matrix%20(arm).htm) documentation to ensure it does not contain PII

Allow logging of emailage fields including confidence scores

---

.eslintrc
app/javascript/packages/verify-flow/steps/password-confirm/password-reset-button.spec.tsx
package.json
spec/javascripts/packages/document-capture/components/document-capture-spec.jsx
spec/javascripts/support/sinon.ts
yarn.lock

**Why**: Avoid developer confusion associated with race conditions caused by not properly awaiting the completion of a userEvent interaction.
It's not obvious by the changes themselves (especially in the exceptions being ignored), but this has tripped me up on several occasions, resulting in much wasted time for what turns out to be a very simple fix. There are exceptions to this rule and the ESLint selector isn't perfect, but I expect this should have a net positive impact on test authoring.

Add ESLint enforcement of awaited userEvent interaction

---

Gemfile.lock

#7000 included an update to `strscan`, a default gem which has weird interactions with our deployed bundler version (2.20.0) and caused deploys to fail.  This PR reverts the version to the previous version until we update bundler

Revert strscan version upgrade

---

config/application.yml.default
lib/identity_config.rb

https://cm-jira.usa.gov/browse/LG-7623
This change allows us to control whether or not we call the VA API mock proofer or a live VA API endpoint.
changelog: Upcoming Features, Inherited Proofing, Add Feature Flag to Conditionally Call Mock API for VA User Data (LG-7623)

 LG-7623 Add Feature Flag to Conditionally Call VA Mock API

---

app/controllers/openid_connect/logout_controller.rb
spec/controllers/openid_connect/logout_controller_spec.rb
spec/features/openid_connect/openid_connect_spec.rb

It was introduced by https://github.com/18F/identity-idp/pull/3479 / [LG-2441](https://cm-jira.usa.gov/browse/LG-2441), but it's not clear what the intention was since the default action is to try rendering `index.html` which doesn't exist so using `prevent_logout_redirect` will 404 currently.
The parameter does not appear in:
- Production logs
- The JIRA ticket referenced in the Pull Request that introduced it
- Slack chat logs
- Our OIDC Developer documentation
So it seems safe to drop?

Remove unused OpenID Connect Logout prevent_logout_redirect parameter

---

app/controllers/users/delete_controller.rb
app/services/irs_attempts_api/tracker_events.rb
spec/controllers/users/delete_controller_spec.rb

changelog: Internal, Attempts API, Standardize events name

LG-7469 Standardize naming conventions

---

app/javascript/packages/build-sass/cli.js

**Why**: So that a developer has an opportunity to fix a compilation error, and so that they're not confused when their changes are not reflected in the running application process.
Currently, if a developer is running `make run` and introduces a syntax error to a stylesheet, the stylesheet build process will crash and never recover. The application will continue to run, however, causing confusion for the developer.
- Try adding an intentional syntax error to a stylesheet while `make run` is running, observe the error in the console, and observe that the files are recompiled when the syntax error is fixed.
- Note: There is (currently) no feedback for rebuilds in the terminal process, but you should notice changes being reflected in the application after refresh …

Recompile Sass after exception when watching files

---

app/jobs/get_usps_proofing_results_job.rb
spec/jobs/get_usps_proofing_results_job_spec.rb

[LG-7643](https://cm-jira.usa.gov/browse/LG-7643)
Uses `deliver_later` for sending in-person proofing results emails instead of `deliver_now_or_later`.
**Why?**
The `deliver_mail_async` flag is off in production, but we want to send these emails after a delay. This change lets us do that without turning on the feature flag and causing all emails to be sent async.

LG-7643: Use deliver_later for in-person proofing results emails

---

app/forms/idv/inherited_proofing/base_form.rb
app/forms/idv/inherited_proofing/va/form.rb
spec/forms/idv/inherited_proofing/base_form_spec.rb
spec/forms/idv/inherited_proofing/va/form_spec.rb

https://cm-jira.usa.gov/browse/LG-7602
1 of n.
This is simply an existing Form refactor that splits off a FormBase class.
This is a supporting change for the LG-7602 feature for Inherited Proofing (IP) where user PII needs to be stored in session for IP flow steps and subsequent IDV workflow flow steps that need this information for (example) Lexis Phone Finder look ups.
This change exposes a #user_pii method that retuns a Hash suitable to be stored in the idv_session and flow_session[:pii_from_user] (minus :uuid). The data mapped  to the user PII returned from this method is Service Provider (SP)-specific in that the SP API returning the user PII may be returned having data keys that differ from what we need; consequently, create a mapper service for this, but that would disconnect what …

LG-7602 Pull VA IP Data and Store It In Session (Form refactor)

---

app/controllers/concerns/inherited_proofing_concern.rb
app/services/idv/inherited_proofing/va/mocks/service.rb
app/services/idv/inherited_proofing/va/service.rb
scripts/inherited_proofing/va/user_attributes/test_server.rb
spec/controllers/concerns/inherited_proofing_concern_spec.rb
spec/features/services/idv/inherited_proofing/va/mocks/service_spec.rb
spec/services/idv/inherited_proofing/va/mocks/service_spec.rb
spec/services/idv/inherited_proofing/va/service_spec.rb

https://cm-jira.usa.gov/browse/LG-7602
2 of 3.
This is a supporting change for the LG-7602 feature for Inherited Proofing (IP).
The user's PII needs to be obtained from the Service Provider in our Inherited Proofing process Flow Steps. Identifying whether or not an Inherited Proofing SP request is in progress, needs access to the decorated_session, which currently takes place in the InheritedProofingConcern. It makes sense (for how), to serve up the Service Provider Services and Forms in this concern, since we can easily identify the Service Provider here also; we can think about placing this code in a SP Service and Form factory or something similar later.
changelog: Upcoming Features, Inherited Proofing, Pull VA IP Data and Store It In Session (LG-7602)

LG-7602 Pull VA IP Data and Store It In Session (InheritedProofingConcern refactor) 2 of 3

---

app/components/phone_input_component.rb
app/controllers/idv/otp_delivery_method_controller.rb
app/controllers/idv/phone_controller.rb
app/forms/idv/phone_form.rb
app/javascript/packages/phone-input/index.js
app/javascript/packages/phone-input/index.spec.js
app/services/idv/phone_step.rb
app/services/phone_country_codes.rb
app/services/phone_number_capabilities.rb
app/views/idv/otp_delivery_method/new.html.erb
app/views/idv/phone/new.html.erb
config/application.yml.default
config/locales/errors/en.yml
config/locales/errors/es.yml
config/locales/errors/fr.yml
lib/identity_config.rb
spec/controllers/idv/phone_controller_spec.rb
spec/features/idv/steps/phone_otp_delivery_selection_step_spec.rb
spec/forms/idv/phone_form_spec.rb
spec/services/idv/phone_step_spec.rb
spec/views/idv/otp_delivery_method/new.html.erb_spec.rb

**Why:** Since the restriction for phone step is based on the assumption that address verification is only supported for U.S. numbers, and U.S. numbers should include U.S. territories.
Before|After
---|---
Confirm that you can use a U.S. mainland phone number or a U.S. territory phone number at the "Phone" step of the identity verification flow, and not another international phone number.
Sample phone numbers:
- U.S. mainland: `5135551234`
- Puerto Rico: `9395550137`
- Canada: `3065551234`
Steps:
2. Sign in or create an account
4. Complete proofing process up to "Enter a phone number with your name on the plan"
5. Enter a phone number and click Continue
6. Observe …

Include U.S. territories in allowed countries for IdV phone

---

app/components/phone_input_component.rb
app/controllers/idv/otp_delivery_method_controller.rb
app/controllers/idv/phone_controller.rb
app/forms/idv/phone_form.rb
app/javascript/packages/phone-input/index.js
app/javascript/packages/phone-input/index.spec.js
app/services/idv/phone_step.rb
app/services/phone_number_capabilities.rb
app/views/idv/otp_delivery_method/new.html.erb
app/views/idv/phone/new.html.erb
config/application.yml.default
config/locales/errors/en.yml
config/locales/errors/es.yml
config/locales/errors/fr.yml
lib/identity_config.rb
spec/controllers/idv/phone_controller_spec.rb
spec/features/idv/steps/phone_otp_delivery_selection_step_spec.rb
spec/forms/idv/phone_form_spec.rb
spec/services/idv/phone_step_spec.rb
spec/views/idv/otp_delivery_method/new.html.erb_spec.rb

- Identity Verification: Allow U.S. territory numbers for IdV phone step ([#7016](https://github.com/18F/identity-idp/pull/7016))

Deploy RC 211.2 to Production

---

pull_request_template.md

[Create a PR Template for the identity-idp repo
](https://cm-jira.usa.gov/browse/LG-7648)
- Added a proposed PR template to the identity-idp repo
n/a
n/a

LG-7648: Create PR template

---

app/controllers/idv/inherited_proofing_controller.rb
app/services/idv/flows/inherited_proofing_flow.rb
app/services/idv/steps/inherited_proofing/agreement_step.rb
app/services/idv/steps/inherited_proofing/user_pii_managable.rb
app/services/idv/steps/inherited_proofing/user_pii_retrievable.rb
app/services/idv/steps/inherited_proofing_base_step.rb
lib/session_encryptor.rb
spec/controllers/idv/inherited_proofing_controller_spec.rb
spec/features/idv/inherited_proofing/agreement_step_spec.rb

ATTENTION: This branch is blocked/will fail until [this PR is approved/merged](https://github.com/18F/identity-idp/pull/7012)
[https://cm-jira.usa.gov/browse/LG-7602](https://github.com/18F/identity-idp/pull/7012/commits/c2aab30425b422d4602c4a42c50ba6f9f4d080f0)
3 of 3.
This is a supporting change for the LG-7602 feature for Inherited Proofing (IP).
The user's PII needs to be obtained from the Service Provider in our Inherited
Proofing process Flow Steps so that we can process the data and put it into session in such a way so that we can hand the rest of the proofing process to the current IDV workflow in a seamless manner. 
These changes ensure we can do the following in both our IP controller _and/or_ IP Flow Steps: 
1) Know if we are entertaining an Inherited Proofing (IP) request.
2) …

LG-7602 Pull VA IP Data and Store It In Session (Controller and Flow State) 3 of 3

---

app/controllers/account_reset/delete_account_controller.rb
app/controllers/concerns/unconfirmed_user_concern.rb
app/controllers/idv/gpo_verify_controller.rb
app/controllers/idv/phone_controller.rb
app/controllers/sign_up/passwords_controller.rb
app/controllers/sign_up/registrations_controller.rb
app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
app/controllers/users/passwords_controller.rb
app/controllers/users/piv_cac_authentication_setup_controller.rb
app/controllers/users/piv_cac_setup_from_sign_in_controller.rb
app/controllers/users/reset_passwords_controller.rb
app/controllers/users/verify_personal_key_controller.rb
app/services/idv/steps/verify_base_step.rb
app/services/irs_attempts_api/tracker.rb
spec/controllers/account_reset/delete_account_controller_spec.rb
spec/controllers/idv/gpo_verify_controller_spec.rb
spec/controllers/idv/phone_controller_spec.rb
spec/controllers/sign_up/passwords_controller_spec.rb
spec/controllers/sign_up/registrations_controller_spec.rb
spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb
spec/controllers/users/passwords_controller_spec.rb
spec/controllers/users/reset_passwords_controller_spec.rb
spec/controllers/users/verify_personal_key_controller_spec.rb
spec/forms/idv/api_image_upload_form_spec.rb
spec/services/irs_attempts_api/tracker_spec.rb
spec/support/fake_attempts_tracker.rb

LG-7417 Standardize failure responses

---

app/mailers/user_mailer.rb
app/views/user_mailer/add_email.html.erb
spec/mailers/user_mailer_spec.rb

- Follow-up to #7019 to prevent similar bugs in the future

Update add_email to build its URL once and re-use it

---

scripts/changelog_check.rb
spec/fixtures/git_log_changelog.yml
spec/scripts/changelog_check_spec.rb

N/A
Allows case- and whitespace-insensitivity for commit messages, to help avoid developer toil associated with crafting commit messages.
Examples:
- 238f6745af1c4497964cade45210b1d43d4aaa70
- 8dbcf928c52d50e406e5bb6941d7a9ca76593ca7
N/A
N/A

Improve changelog tool flexibility for commit messages

---

app/views/layouts/user_mailer.html.erb
config/locales/mailer/en.yml
config/locales/mailer/es.yml
config/locales/mailer/fr.yml
spec/i18n_spec.rb
spec/views/layouts/user_mailer.html.erb_spec.rb

[Ticket](https://cm-jira.usa.gov/browse/LG-7150)
**What:** This pr adds alt text to the Login.gov logo in order to allow screen reader users to hear text that describes the logo image in emails. 
**How:** Alt tag added to image_tag in the base email used by other emails. 
Note: Did not add this text to the i18l files as the text is the same in the 3 languages we support. 
**Testing:**
* Go to one of the emails, can use ready to verify email for example. `http://localhost:3000/rails/mailers/user_mailer/in_person_verified.html?locale=en`
* Open finder
* Navigate to VoiceOver and enable
* Navigate the email using VoiceOver to ensure that "Login.gov logo" is read out when highlighting the logo
<details>
<summary>Screenshot</summary>
</details>
changelog: Improvement, Accessibility, add alt …

lg-7150 add login icon alt text

---

app/controllers/frontend_log_controller.rb
app/services/analytics_events.rb
spec/features/users/sign_in_spec.rb
spec/support/features/javascript_driver_helper.rb

LG-6143
Context: https://github.com/18F/identity-idp/pull/6946#discussion_r976534843
The intention with the changes in #6946 was to omit the default "Frontend" prefix by defining a corresponding analytics event in `FrontendLogController::EVENT_MAP`. However, since this map is case-sensitive, the matching was not happening as expected, so the event was still logged with the "Frontend" prefix. Additionally, the `path` argument would only be included in the payload if explicitly listed in the keyword arguments of the event method, as of #6927.
N/A
N/A

Fix logging for password visibility toggle

---

app/views/devise/sessions/new.html.erb

While working with @anniehirshman-gsa on #7017, she suggested that the sign-in page buttons could be updated to match other buttons.  This PR is a small style change to make sign-in page buttons use the "big" style to match buttons elsewhere on the site.
|:------:|:-----:|
|   ![image](https://user-images.githubusercontent.com/1430443/192386358-b28fa289-e391-4984-96c4-81c2625702af.png)     |    ![image](https://user-images.githubusercontent.com/1430443/192386329-35133c6c-0bab-4e85-93a8-2502a575d91d.png)   |

Make sign-in page buttons big to improve button style consistency

---

app/views/users/mfa_selection/index.html.erb
spec/features/two_factor_authentication/multiple_mfa_sign_up_spec.rb

[LG-6918: Authentication update CTA](https://cm-jira.usa.gov/browse/LG-6918)
This will change the language of the link at the secondary MFA page to "Skip for now" 
What it will look like after change.

changelog: Improvements, Authentication, Update from cancel to skip for now

---

spec/features/users/sign_in_spec.rb
spec/support/features/javascript_driver_helper.rb

N/A
Resolves intermittent test failures caused by a race condition between user interaction in the feature spec and the JavaScript `fetch` request being settled.
Related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1664317848054629
There _should_ be a way to have the test helper work as expected, but this appears to work as a simpler alternative. The issue with the test helper appears to be that the `Timeout.timeout` loop only loops once and does not actually wait for `window.isFetching` to become `false`.
N/A
N/A

Fix flaky spec for awaited fetch request

---

app/assets/stylesheets/components/_alert-icon.scss
app/views/account_reset/confirm_delete_account/show.html.erb

changelog: Internal, Accessibility, adjusting icon position
Updated the alert-icon component sass to include a new convenience class.
Updated the account confirm deleted view to use the new class, which better centers the icon vertically
<details>
</details>
<details>
</details>

Better Account Deleted Icon Centering

---

app/controllers/openid_connect/logout_controller.rb
app/forms/openid_connect_logout_form.rb
app/services/analytics_events.rb
app/views/devise/sessions/new.html.erb
app/views/openid_connect/logout/index.html.erb
app/views/users/authorization_confirmation/new.html.erb
config/locales/openid_connect/en.yml
config/locales/openid_connect/es.yml
config/locales/openid_connect/fr.yml
config/locales/titles/en.yml
config/routes.rb
spec/controllers/openid_connect/logout_controller_spec.rb
spec/features/openid_connect/openid_connect_spec.rb

[LG-7629](https://cm-jira.usa.gov/browse/LG-7629)
This is a follow-on to PR #6936 which added support for the `client_id` parameter in OIDC Logout.  Per the [OpenID Connect RP-Initiated Logout 1.0 specification](https://openid.net/specs/openid-connect-rpinitiated-1_0.html):
>At the Logout Endpoint, the OP SHOULD ask the End-User whether to log out of the OP as well. Furthermore, the OP MUST ask the End-User this question if an id_token_hint was not provided or if the supplied ID Token does not belong to the current OP session with the RP and/or currently logged in End-User. If the End-User says "yes", then the OP MUST log out the End-User.
>Logout requests without a valid id_token_hint value are a potential means of denial of service; therefore, OPs should obtain explicit confirmation …

Confirm OIDC logout when using client_id parameter (LG-7629)

---

app/views/devise/sessions/new.html.erb
app/views/users/authorization_confirmation/new.html.erb

Fixes bugs introduced in #7017 where the `alt` attribute was replaced with the `height` value.  Mentioned in https://github.com/18F/identity-idp/pull/7017#discussion_r982997675

Fix height and alt attribute on images

---

app/jobs/get_usps_proofing_results_job.rb
spec/jobs/get_usps_proofing_results_job_spec.rb

Fixes a bug where certain errors encountered while checking for enrollment status updates were not being handled. See [this discussion in Slack](https://gsa-tts.slack.com/archives/C03FA4VBN76/p1664312535019919).

Handle StandardError without response in GetUspsProofingResultsJob

---

app/controllers/mfa_confirmation_controller.rb

The 2FA Registration Complete event wasn't being logged when people finish 2FA Registration by skipping the suggestion to add another, so this PR adds it.

Log 2FA Setup Complete Event when skipping adding additional MFA

---

.rubocop.yml
app/controllers/users/sessions_controller.rb
app/services/date_parser.rb
app/services/doc_auth/acuant/pii_from_doc.rb

Updates Rubocop target versions to our current targeted support.
https://github.com/18F/identity-idp/blob/062ac12ce6d70ab711ecd019fd8916dc6e759b7c/.ruby-version#L1
https://github.com/18F/identity-idp/blob/062ac12ce6d70ab711ecd019fd8916dc6e759b7c/Gemfile#L6

Sync Rubocop target platform versions to current versions

---

app/controllers/idv/otp_verification_controller.rb
app/controllers/idv/phone_controller.rb
app/controllers/users/two_factor_authentication_controller.rb
app/services/irs_attempts_api/tracker_events.rb
spec/controllers/idv/otp_verification_controller_spec.rb
spec/controllers/users/two_factor_authentication_controller_spec.rb

Standardize success parameter to always be first

---

app/controllers/openid_connect/logout_controller.rb
app/forms/openid_connect_logout_form.rb
app/views/openid_connect/logout/index.html.erb
spec/features/openid_connect/openid_connect_spec.rb
spec/forms/openid_connect_logout_form_spec.rb

Resolves LG-7684
This brings us in alignment with the spec.
changelog: Improvements, Authentication, Make state optional for OIDC Logout
https://cm-jira.usa.gov/browse/LG-7684
OIDC Logout no longer requires the `state` parameter to match the [spec](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout).
- [] Send OIDC logout request without a state parameter
N/A

[LG-7684] Make state optional for OIDC Logout

---

app/controllers/saml_idp_controller.rb
spec/controllers/saml_idp_controller_spec.rb
spec/support/fake_saml_request.rb
spec/support/saml_auth_helper.rb

Resolves LG-7676
changelog: Improvements, Authentication, Add logging of matching certificate for SAML AuthnRequests
https://cm-jira.usa.gov/browse/LG-7676
Adds a new attribute to successful `SAML Auth` events to track the serial number of the matching cert identified through signature validation. If the signature validation fails, this attribute will be `nil`, indicating that none of the configured SP public certificates could be used to validate the signature in the SAML AuthnRequest.
N/A

[LG-7676] Add logging of matching certificate for SAML AuthnRequests

---

config/application.yml.default

This will be enabled in prod today, so we should enable it everywhere by default!
Prompted by https://github.com/18F/identity-oidc-sinatra/pull/120#issuecomment-1262212781
This should not be merged until prod is done

Enable accepting client_id parameter by default in OIDC Logout

---

app/controllers/idv/otp_delivery_method_controller.rb
app/services/irs_attempts_api/tracker_events.rb
spec/controllers/idv/otp_delivery_method_controller_spec.rb

Remove the `idv_phone_confirmation_otp_sent_rate_limited` event as it duplicates functionality of another event.
Since only one `idv_phone_otp` event contains the word `confirmation` now, remove the word `confirmation` to standardize the `idv_phone_otp` events (and seek to improve the associated unit tests).

Clean up Phone Confirmation Events

---

app/assets/stylesheets/components/_alert-icon.scss

[LG-7691](https://cm-jira.usa.gov/browse/LG-7691)
Updated the alert icon "badge" mode styling to have the correct position attribute, so pseudo-element displays in the correct position across browsers.
<details>
</details>
<details>
</details>
No special notes.

LG-7691 Fixing alert icon badge positioning

---

app/jobs/resolution_proofing_job.rb
package.json
spec/jobs/resolution_proofing_job_spec.rb

[LG-7640](https://cm-jira.usa.gov/browse/LG-7640)
Add the review status to the top level of the threatmetrix logging results for the following event:
"IdV: in person proofing optional verify_wait submitted"
from here:
properties.event_properties.proofing_results.context.stages.threatmetrix.response_body.review_status
to also here:
properties.event_properties.proofing_results.context.stages.threatmetrix.review_status
because cloudwatch has difficulty parsing large packets at depth
None

LG-7640 review_status should be a top-level key

---

app/assets/stylesheets/components/_personal-key.scss
app/views/partials/personal_key/_key.html.erb
spec/support/features/personal_key_helper.rb
spec/support/shared_examples/sign_in.rb

This fixes an issue where the personal key page layout was malformed, as an unintended regression of #6986 due to accidental name collision of the `.separator-text` class added there.
**Desktop:**
Before|After
---|---
**Mobile:**
Before|After
---|---

Fix personal key block display

---

spec/jobs/reports/sp_active_users_report_spec.rb

Fixes build failures occurring for branches created after October 1 (new fiscal year). The job uses the passed date for the reporting range, so it should correspond to the date used in stubbing data, like what's done in other test cases in the file.

Generate report in spec with the stubbed date

---

app/views/idv/session_errors/warning.html.erb
spec/views/idv/session_errors/warning.html.erb_spec.rb

Came across a 500 in [NewRelic](https://one.newrelic.com/nr1-core/errors/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=259200000&state=c38c7388-c40d-b0f3-e548-323f96874398) caused by  `user_session` being nil.  I'm not 100% sure this is the _best_ way to fix it, but it is a way.

Fix 500 error when displaying IDV session error

---

app/controllers/idv/gpo_verify_controller.rb
app/controllers/users/verify_personal_key_controller.rb
app/services/irs_attempts_api/tracker_events.rb
spec/controllers/idv/gpo_verify_controller_spec.rb
spec/controllers/users/verify_personal_key_controller_spec.rb

Standardize the two undocumented Event names to be included in the Schema Doc.

Event standardization work

---

app/services/proofing/lexis_nexis/result_with_exception.rb

Based on a failed job from [New Relic](https://one.newrelic.com/nr1-core/errors/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=259200000&state=972082af-b8a1-364e-a868-f50e94985730), it appears to be an unintentional breakage from #6920, which introduced a new shape for proofing results.
```
undefined method `transaction_id' for #<Proofing::LexisNexis::ResultWithException
```
This PR adds a nil `transaction_id` to ResultWithException so the results have closer behavior.  The `AddressMockClient` [doesn't use ResultWithException](https://github.com/18F/identity-idp/blob/440ba52acff0253384e63edb2f3d17cb5049de34/app/services/proofing/mock/address_mock_client.rb#L30-L41) so it's not straightforward to test.

Fix undefined method transaction_id when LexisNexis PhoneFinder raises an exception

---

docs/frontend.md

The ["Dependencies" section of the Frontend documentation](https://github.com/18F/identity-idp/blob/592623ad6aa9ea4ffc2992fdc98171fbc3067704/docs/frontend.md#dependencies) is inaccurate in how it suggests defining "build tools" as `devDependencies`, which in reality would result in a failing build. While there are now protections in place to prevent this as of #5391, the documentation should still accurately reflect the use of `devDependencies`.
Furthermore, this expands on a few things:
- Installing dependencies to workspace packages
- Working around Yarn's default workspace warning when installing a package without the `-W` flag
- Deduplicating package versions

Improve accuracy of frontend dependencies documentation

---

app/services/proofing/lexis_nexis/instant_verify/check_to_attribute_mapper.rb
spec/services/proofing/lexis_nexis/instant_verify/check_to_attribute_mapper_spec.rb

We had a nil check in here for when the instant verify errors was nil, but not for when 'Items' was nil. This commit adds that protection

Protect against a missing items hash in the LN failure mapper

---

app/javascript/packages/build-sass/index.js
app/javascript/packages/build-sass/package.json
yarn.lock

Upgrades stylesheet build dependencies, in order to...
* Ideally resolve recurring development environment issues with the missing Sass executable ([related Slack comment](https://gsa-tts.slack.com/archives/C0NGESUN5/p1664889737198109)) or missing `lightningcss` (né `@parcel/css`) dependency ([related Slack comment](https://gsa-tts.slack.com/archives/C0NGESUN5/p1664890279659959?thread_ts=1664889737.198109&cid=C0NGESUN5))
* Flatten dependency tree (observe removed lines) due to revised approach for Sass executable installation using `optionalDependencies` ([related upstream change](https://github.com/sass/embedded-host-node/pull/158))
* Avoid developer confusion related to renamed `@parcel/css` dependency
Observe no visual regressions or errors after compiling Sass and running the …

build-sass: Upgrade dependencies

---

app/controllers/idv/gpo_controller.rb
app/controllers/users/verify_personal_key_controller.rb
app/services/irs_attempts_api/tracker_events.rb
spec/controllers/idv/gpo_controller_spec.rb

Add `gpo` to standardize letter based events.  Re-alphabetize tracker events that are now out of order.  Remove an unnecessary parameter.

Standardization clean-up (naming, alphabetizing)

---

lib/analytics_events_documenter.rb
spec/lib/analytics_events_documenter_spec.rb

Analytics methods are expected to contain only keyword arguments and an `**extra` splat, so we should enforce this through the existing lint tooling.
Related example: #7044

Enhance analytics linter to catch non-keyword arguments

---

app/controllers/openid_connect/logout_controller.rb
app/forms/openid_connect_logout_form.rb
app/views/openid_connect/logout/index.html.erb
config/locales/openid_connect/en.yml
config/locales/openid_connect/es.yml
config/locales/openid_connect/fr.yml
spec/controllers/openid_connect/logout_controller_spec.rb
spec/features/openid_connect/openid_connect_spec.rb

To make RP-initiated OIDC Logout clearer for users, we should be explicit that they will return to the SP.  This PR intends to add content to clarify this.
|--------|------|
| ![image](https://user-images.githubusercontent.com/1430443/193920995-a79b857a-bca4-49aa-82f3-913ae17a3e6e.png)  | ![image](https://user-images.githubusercontent.com/1430443/193920712-40ff2a44-3b61-41b5-b800-1ee7f0c9014b.png) |

Include SP name in OIDC logout confirmation

---

app/javascript/packs/personal-key-page-controller.js
spec/support/shared_examples_for_personal_keys.rb

Fixes an error which occurs when the user enters an invalid (non-alphanumeric) character in the personal key step of the identity verification flow.
The [`base32-decode` library](https://github.com/LinusU/base32-decode/) [used in `@18f/identity-personal-key-input`](https://github.com/18F/identity-idp/blob/b1361b41aade947d2a728758afff8541116f70ad/app/javascript/packages/personal-key-input/index.js#L14) [throws an error when encountering an unexpected character](https://github.com/LinusU/base32-decode/blob/fa61c01bc0bbd963a1abcf86cc519f09d70b09e0/index.js#L9). Rather than letting these errors throw unhandled, catch them and treat them as equivalent to an invalid entry.
NewRelic: https://onenr.io/0bRmopb8BQy

Fix error from personal key validation unexpected characters

---

app/assets/stylesheets/components/_location-collection-item.scss
app/javascript/packages/document-capture/components/location-collection-item.tsx

This pull request removes custom styles which had been implemented for the in-person proofing locations screen. Largely this should be visually identical to how it was previously, with the exception of a minor margin correction for the mobile button placement (based on Figma references).
Rationale:
* They can be achieved with existing design system utility classes
* Align class naming for component stylesheets to be consistent with file name
* Avoid ambiguity between design system classes and IdP-specific ad hoc style classes caused by similar naming
* Use standard breakpoints ("tablet")
* Improve performance by reducing CSS stylesheet size
Context:
* https://github.com/18F/identity-idp/pull/6624#discussion_r931016013
* https://github.com/18F/identity-idp/pull/6624#discussion_r931017636
* …

Use design system utility classes for IPP location elements

---

app/controllers/application_controller.rb
app/controllers/concerns/remember_device_concern.rb
app/controllers/concerns/two_factor_authenticatable_methods.rb
app/controllers/two_factor_authentication/otp_verification_controller.rb
app/controllers/users/two_factor_authentication_controller.rb
app/forms/otp_delivery_selection_form.rb
app/services/user_session_context.rb
spec/presenters/two_factor_login_options_presenter_spec.rb
spec/services/user_session_context_spec.rb
spec/views/two_factor_authentication/options/index.html.erb_spec.rb

changelog: Internal, General, Refactored inconsistent function names
[LG-7324](https://cm-jira.usa.gov/browse/LG-7324)
Refactored function names in user_session_context.rb that were a bit confusing. `reauthentication_context?` and `confirmation_context?` both check explicitly for the respective contexts. Intuitively, one would expect `authentication_context?` to do the same, but it was checking either authentication or reauthentication. This renames `authentication_context?` and `intiial_authentication_context?` to more accurately describe what they are doing.

Refactored UserSession context functions

---

config/initializers/ab_tests.rb
spec/config/initializers/ab_tests_spec.rb
spec/features/users/key_pair_generation_spec.rb
spec/services/doc_auth_router_spec.rb
spec/services/idv/steps/document_capture_step_spec.rb
spec/support/fake_ab_test_bucket.rb

N/A
So in the PR that moved AB test bucket creation to an initializer (#6994) I added a duplicated method `reload_ab_test_initializer` as a hacky workaround that let us test logic inside an initializer (because for those two existing tests, we have multiple feature flags)
However, I think reloading initializers is a bad pattern, so I'd like to move as many instances of that as possible to `stub_const` and use the `FakeAbTestBucket` class
It looks like in this case, we were reloading to assign to 100% because we don't know the user ID *a priori* so I think the missing piece was an `#assign_all` method which I added
Anyways this is probably minor but I expect we'll continue to add more AB tests over time so I'd like to start encouraging cleaner ways to have determinism in specs that are …

Add FakeABTestBucket#assign_all

---

app/jobs/reports/agency_invoice_iaa_supplement_report.rb
app/jobs/reports/base_report.rb
app/jobs/reports/combined_invoice_supplement_report.rb
app/services/db/monthly_sp_auth_count/total_monthly_auth_counts_within_iaa_window.rb
app/services/db/monthly_sp_auth_count/unique_monthly_auth_counts_by_iaa.rb

(none)
**Why**: Occasionally we see PG::UnableToSend errors at which point the connection stops receiving queries. [NewRelic link](https://onenr.io/0vjAX7omDRP)
In an attempt to recover the job and continue, we call #reconnect! on the connection. However, this would reset our session-specific timeouts, so there's a big of rejiggering to allow the connection timeout stuff from the reports to be called in to the db query classes

Update long-running report queries to reset connection

---

app/jobs/get_usps_proofing_results_job.rb
spec/jobs/get_usps_proofing_results_job_spec.rb

[LG-7630](https://cm-jira.usa.gov/browse/LG-7630)
Added enrollment.issuer  to enrollment_analytic_attributes in order to allow service_provider to be tracked in CloudWatch.
`u = User.last`
`e = u.in_person_enrollments.last`
<details>
<summary>Console</summary>
</details>

LG-7630 update enrollment attributes to include service provider

---

spec/controllers/users/sessions_controller_spec.rb
spec/rails_helper.rb

Improves reliability of SessionController specs by avoiding race conditions associated with assumed near-instant responses by using [`freeze_time` helper](https://api.rubyonrails.org/v5.2.6/classes/ActiveSupport/Testing/TimeHelpers.html).
Example: https://gitlab.login.gov/lg/identity-idp/-/jobs/92662

Fix flakey spec failures in SessionController

---

app/mailers/user_mailer.rb
app/services/usps_in_person_proofing/enrollment_helper.rb
app/views/user_mailer/in_person_ready_to_verify.html.erb
config/locales/user_mailer/en.yml
config/locales/user_mailer/es.yml
config/locales/user_mailer/fr.yml
spec/controllers/idv/review_controller_spec.rb
spec/mailers/previews/user_mailer_preview.rb
spec/mailers/user_mailer_spec.rb
spec/services/usps_in_person_proofing/enrollment_helper_spec.rb

[LG-7650](https://cm-jira.usa.gov/browse/LG-7650)
For consistency with other in-person proofing emails and to avoid potentially storing PII, this PR removes the `first_name` variable from the content.
|-------|-----|
| ![image](https://user-images.githubusercontent.com/1430443/194612681-e7e1105c-8003-44b3-8610-a99f2154a148.png)  |  ![image](https://user-images.githubusercontent.com/1430443/194612293-f1326d14-6d38-4389-b5b8-d01b337672cb.png)  |

Remove first name from "Ready to Verify" email

---

spec/mailers/user_mailer_spec.rb

Removes a `puts` that snuck into a spec

Remove puts in UserMailer spec

---

app/services/doc_auth/lexis_nexis/responses/true_id_response.rb
spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb

[LG-7764](https://cm-jira.usa.gov/browse/LG-7764)
Previously: we thought that responses of Unknown would not be billed
Now: we confirmed that these are billed

Update TrueID responses to bill for attention: Unknown (LG-7764)

---

.rubocop.yml
spec/rails_helper.rb
spec/support/private_key_file_helper.rb

**Why**: would have caught the slip that lead to #7119
**How**: the spec/ directory is not included by default as part of the cop

Add spec/ directory to Rails/Output cop

---

spec/features/idv/analytics_spec.rb

Previously, the analytics specs for unsupervised "Happy Path" and "GPO" flows would not use or assert the expected analytics values, so effectively we were only testing that the event names were logged. Since we presumably care about the values, this pull request seeks to enforce them, and fix existing inaccuracies.
Observed in #7111

Enforce and fix attribute expectations for analytics spec

---

app/forms/edit_phone_form.rb
app/views/accounts/_phone.html.erb
app/views/users/edit_phone/_make_default_number.html.erb
config/locales/two_factor_authentication/en.yml
config/locales/two_factor_authentication/es.yml
config/locales/two_factor_authentication/fr.yml
spec/features/phone/default_phone_selection_spec.rb
spec/features/phone/edit_phone_spec.rb
spec/forms/edit_phone_form_spec.rb

[LG-4258](https://cm-jira.usa.gov/browse/LG-4258)
If a user has only one phone number set up on their account, they should not be able to select or deselect the "Make default number" checkbox. With this change, the checkbox will be disabled when there is one number associated with an account as well as a messaging that lays out why they cannot change their default number.
|   Before  |   After  |
|--------- | ------- |
|  ![Image of manage phone number before checkbox change is made](https://user-images.githubusercontent.com/17969963/194144174-a6f9217e-4c95-4985-b7d0-996cfe3cdcce.png)   | ![image of change with checkbox …

LG-4258: Changing Default phone number should require multiple numbers associated with account

---

app/jobs/reports/query_helpers.rb
app/services/db/monthly_sp_auth_count/total_monthly_auth_counts_within_iaa_window.rb
app/services/db/monthly_sp_auth_count/unique_monthly_auth_counts_by_iaa.rb
spec/jobs/reports/query_helpers_spec.rb

N/A
Following up to https://github.com/18F/identity-idp/pull/7104#pullrequestreview-1133689290
**Why**: It may not be helping the reports run faster, and it may be making the pg connections more fragile/stateful

Remove query streaming for big reports

---

app/services/analytics_events.rb

Removes analytics events which are no longer used. These were last referenced prior to #7110.
I put together a small script to try to find any other unused, these were the only ones.
```bash
cat app/services/analytics_events.rb | perl -n -e '/def ([a-z_]+)/ && print "$1\n"' | while read LINE; do
count=$(grep --recursive -o $LINE app | wc -l)
if [ "$count" -eq "1" ]; then
echo $LINE
fi
done
```
Automated tests should pass.

Remove unused analytics events

---

app/services/frontend_logger.rb
spec/services/frontend_logger_spec.rb

Removes support for proc methods in `FrontendLogger#track_event`, since we're no longer handling any frontend events as proc methods as of #7110.
Automated tests should pass.

Remove unused support for proc methods in frontend logger

---

app/models/registration_log.rb
app/services/funnel/registration/add_mfa.rb
db/primary_migrate/20221012172457_alter_registration_logs_nullable_submitted_at.rb
db/schema.rb

[LG-6317](https://cm-jira.usa.gov/browse/LG-6317)
- Make registration_logs.submitted_at nullable, stop writing it
- Ignore other columns
- **Next steps**: drop these columns entirely
Must be merged *after* https://github.com/18F/identity-idp/pull/7107 has deployed

Prepare to drop unused registration_logs columns (LG-6317)

---

spec/support/features/in_person_helper.rb

Allows a longer wait delay for in-person feature specs to avoid flakey test failures when run locally. Clicking "Continue" from the "prepare" step will wait for a client-side logging event before continuing to the "State ID" step, which often cannot complete before the 0.5 second tolerance allowed by default in local development environments.
Related discussion: https://github.com/18F/identity-idp/pull/7046#discussion_r983867979
Source for client-side awaited logging:
https://github.com/18F/identity-idp/blob/2a6bc17e50bb3bc23097d9e1aa1d9a82bb85e00f/app/javascript/packages/document-capture/components/in-person-prepare-step.tsx#L39-L40
Example failure:
```
Failures:
1) Analytics Regression in person path records all of the events
Failure/Error:
expect(page).to have_current_path( …
```

Fix flakey local test failures for in-person proofing feature specs

---

config/application.yml.default

[LG-7724](https://cm-jira.usa.gov/browse/LG-7724)
1. set va_inherited_proofing_mock_enabled default value to false for all environments.
<details>
</details>
<details>
</details>

LG-7724: set va_inherited_proofing_mock_enabled default value to false for all environments 

---

app/mailers/user_mailer.rb
spec/mailers/user_mailer_spec.rb

Fixes a typo currently causing unhandled exceptions.
https://github.com/18F/identity-idp/blob/77adb3a7553057b45b76e64537e051ce2a84962c/app/mailers/user_mailer.rb#L19
Slack context: https://gsa-tts.slack.com/archives/C0NGESUN5/p1666063910385719

Fix typo for user mailer validation error class

---

app/services/usps_in_person_proofing/proofer.rb
spec/services/usps_in_person_proofing/proofer_spec.rb

[LG-7814](https://cm-jira.usa.gov/browse/LG-7814)
* Cache the USPS API authorization token as a class variable instead of an instance variable

LG-7814: Cache USPS auth token as class member

---

app/controllers/users/emails_controller.rb
app/services/analytics_events.rb
spec/controllers/users/emails_controller_spec.rb

Follow on to #7106 (and #7162) that addresses some user/email address mismatch issues around email resending.  This PR ensures that the email address record we are using belongs to the current user. It is difficult to write a regression test for this since it depends partially on the database returning the incorrect record, which only happens some of the time.
This PR also adds analytics to the add email/resend email actions which did not exist previously.

Ensure email belongs to account when resending email confirmation email

---

app/views/idv/inherited_proofing/_cancel.html.erb
app/views/idv/inherited_proofing/agreement.html.erb
app/views/idv/inherited_proofing/get_started.html.erb
app/views/idv/inherited_proofing/verify_info.html.erb
app/views/idv/inherited_proofing_cancellations/new.html.erb
spec/features/idv/inherited_proofing/agreement_step_spec.rb
spec/features/idv/inherited_proofing/get_started_step_spec.rb
spec/views/idv/inherited_proofing/agreement.html.erb_spec.rb
spec/views/idv/inherited_proofing/get_started.html.erb_spec.rb

**NOTE: Ignore the first 3 commits, as they are part of the **lg-7446-create-cancel-links-2-of-n** branch _this_ branch was branched off of, and will go away once that branch is merged into main, and this branch is rebased on top if it**
See also PR [LG-7446 Create "Cancel" Links and Supporting Cancellation Code for Identity Proofing Process (1 of n)](https://github.com/18F/identity-idp/pull/7124)
See also PR [LG-7446 Create "Cancel" Links and Supporting Cancellation Code for Identity Proofing Process (2 of n)](https://github.com/18F/identity-idp/pull/7144)
[LG-7446](https://cm-jira.usa.gov/browse/LG-7446)
NOTE: This is feature branch 3 of what most likely be (at most) several feature branches.
In _this_ feature branch:
- Implement "Cancel" links on :agreement and :get_started step views …

LG-7446 Create "Cancel" Links and Supporting Cancellation Code for Identity Proofing Process (3 of n)

---

app/controllers/idv/gpo_controller.rb
app/controllers/idv/personal_key_controller.rb
app/services/analytics.rb
app/services/analytics_events.rb
app/services/frontend_logger.rb
app/services/idv/analytics_events_enhancer.rb
app/services/idv/phone_step.rb
app/services/idv/proofing_components_logging.rb
spec/controllers/application_controller_spec.rb
spec/controllers/concerns/idv/phone_otp_rate_limitable_spec.rb
spec/controllers/idv/cancellations_controller_spec.rb
spec/controllers/idv/come_back_later_controller_spec.rb
spec/controllers/idv/forgot_password_controller_spec.rb
spec/controllers/idv/otp_delivery_method_controller_spec.rb
spec/controllers/idv/otp_verification_controller_spec.rb
spec/controllers/idv/phone_controller_spec.rb
spec/controllers/idv/phone_errors_controller_spec.rb
spec/controllers/idv/resend_otp_controller_spec.rb
spec/controllers/idv/setup_errors_controller_spec.rb
spec/features/idv/analytics_spec.rb
spec/features/idv/cancel_spec.rb
spec/services/idv/analytics_events_enhancer_spec.rb
spec/services/idv/proofing_components_logging_spec.rb
spec/support/fake_analytics.rb

[LG-7582](https://cm-jira.usa.gov/browse/LG-7582)
To provide a means to disambiguate between in-person and unsupervised proofing events, it's proposed to add the user's proofing components to identity verification events, to allow for this and other similar filtering.
```
filter name = 'IdV: review complete' and properties.event_properties.proofing_components.document_check = 'usps'
```

LG-7582: Add proofing components to IdV analytics events

---

app/services/analytics.rb
app/services/idv/analytics_events_enhancer.rb
spec/services/idv/analytics_events_enhancer_spec.rb
spec/support/fake_analytics.rb

N/A
Followup to https://github.com/18F/identity-idp/pull/7111#discussion_r998555203
**Why**: We can avoid creating extra methods via alias_method, avoid a few dynamic #send as well

Switch Idv::AnalyticsEventsEnhancer to use prepend

---

app/services/usps_in_person_proofing/proofer.rb
spec/services/usps_in_person_proofing/proofer_spec.rb

[LG-7814](https://cm-jira.usa.gov/browse/LG-7836)
* Removes the unused instance variable accessors which were overwriting the class variable accessors

LG-7814: Fix issue where USPS API token wasn't being used

---

Gemfile
Gemfile.lock
README.md

LG-7653
https://cm-jira.usa.gov/browse/LG-7653
changelog: Added, README, increase file descriptor limit
I added to the README some instructions for increasing limit of MacOS file descriptors. This resolves "too many open files" errors.
This is does not fix all intermittent test failures I'm experiencing -- this is just the only one I was able to conclusively fix. I suspect there is an underlying issue, like a connection which is failing to close and is not relinquishing its file descriptors.
References:
1. [Maximum limits (in macOS file descriptors)](https://wilsonmar.github.io/maximum-limits/) by Wilson Mar
2. [El Capitan ulimit shenanigans](https://web.archive.org/web/20161223195250/https://blog.dekstroza.io/ulimit-shenanigans-on-osx-el-capitan/) by Dejan Kitic
3. ["Too many open files" …

Jskinne3 lg 7653 intermittent tests 2

---

app/components/download_button_component.rb
app/components/download_button_component.ts
app/javascript/packages/download-button/README.md
app/javascript/packages/download-button/download-button-element.spec.ts
app/javascript/packages/download-button/download-button-element.ts
app/javascript/packages/download-button/package.json
app/javascript/packages/form-link/form-link-element.spec.ts
app/javascript/packs/personal-key-page-controller.js
app/views/partials/personal_key/_key.html.erb
app/views/users/backup_code_setup/create.html.erb
config/locales/components/en.yml
config/locales/components/es.yml
config/locales/components/fr.yml
config/locales/forms/en.yml
config/locales/forms/es.yml
config/locales/forms/fr.yml
spec/components/download_button_component_spec.rb
spec/features/two_factor_authentication/backup_code_sign_up_spec.rb
spec/features/two_factor_authentication/multiple_mfa_sign_up_spec.rb
spec/views/users/backup_code_setup/create.html.erb_spec.rb

Adds a new `DownloadButtonComponent` component to contain the behaviors associated with rendering a button which downloads some content once clicked. This also fixes an issue where backup code downloads would not work in Internet Explorer. While Internet Explorer support will be discontinued before long, the component would still be valuable to simplify and standardize common behaviors.
Between this, #7109, and #7103, I expect we'll also be able to remove `personal-key-page-controller.js` pack altogether and rely exclusively on component-contained behaviors.
Demo screenshots in Internet Explorer:

Create DownloadButtonComponent for download button

---

config/application.yml.default

changelog: Internal, Inherited Proofing, Set va_inherited_proofing_mock_enabled true for development environments
This is so that developers do not have to specifically enable this switch - we should not be attempting to make live calls in our development environments by default.
N/A
Set va_inherited_proofing_mock_enabled to true in development environments.
This is so that developers do not have to specifically enable this switch - we should not be attempting to make live calls in our development environments by default.
N/A
N/A

Set va_inherited_proofing_mock_enabled true for development environments

---

app/controllers/idv/inherited_proofing_controller.rb
app/views/idv/inherited_proofing/no_information.html.erb
app/views/idv/inherited_proofing/phone.html.erb
config/locales/inherited_proofing/en.yml
config/locales/inherited_proofing/es.yml
config/locales/inherited_proofing/fr.yml
config/locales/step_indicator/en.yml
config/locales/step_indicator/es.yml
config/locales/step_indicator/fr.yml
config/routes.rb

[LG-7449](https://cm-jira.usa.gov/browse/LG-7449)
1. Add first error page for inherited proofing when no information is received from API call for any reason
2. Removed unused phone html page and relevant translations.
<details>
</details>
<details>
</details>

LG-7449, Add first error page for inherited proofing when no information is received from API call.

---

app/controllers/concerns/idv_session.rb
app/controllers/concerns/saml_idp_auth_concern.rb
app/controllers/idv_controller.rb
app/controllers/openid_connect/authorization_controller.rb
app/decorators/user_decorator.rb
spec/factories/service_providers.rb
spec/features/users/sign_in_irs_spec.rb
spec/support/features/idv_helper.rb

If a user proofed their identity with a non-IRS SP, then visits an IRS SP, they will be forced to reproof.
changelog: Improvements, Identity Verification, Require users to re-proof on first IRS visit.
[LG-7703: If active profile not verified for SP IRS, send user through reproofing](https://cm-jira.usa.gov/browse/LG-7703)
If the SP the user is signing into is an IRS SP, we check to see if the user's active profile was initiated by an IRS SP. If not, we require them to re-proof to ensure that they are using the most up-to-date criteria.
The specs walk through this best, with the following scenarios:
1. User verified by an IRS SP returns to the same SP - no reproofing
2. User verified by an IRS SP visits a different IRS SP - no reproofing
3. User verified by a non-IRS SP visits an IRS SP - …

LG-7703: Force a user to re-verify their identity for IRS.

---

app/services/irs_attempts_api/attempt_event.rb
spec/services/irs_attempts_api/attempt_event_spec.rb

N/A
**Why**: This was implicitly the default already, and making it explicit helps clarify that this is asymmetric encryption (because the enc: is symmetric)

Add explicit alg: param to JWE encryption

---

app/views/idv/address/new.html.erb
app/views/idv/shared/_verify.html.erb
config/locales/idv/en.yml
config/locales/idv/es.yml
config/locales/idv/fr.yml

Changelog: Features, IdV, Added address line 2 under verify your information
https://cm-jira.usa.gov/browse/LG-7669
Under "Verify your information" in the IdV flow, if a user has a line 2 to their address it is now shown.
Old:
New:
New Update Mailing Address Screen:
<details>
</details>
<details>
</details>

LG-7669 Added address line 2 under verify your information

---

app/services/irs_attempts_api/attempt_event.rb
spec/services/irs_attempts_api/attempt_event_spec.rb

N/A
Adds a Key ID header claim that is in plaintext in the resulting JWE, so it can assist in future key rotations

Add kid "key id" header claim to Attempts API JWEs

---

config/initializers/ext_action_mailer.rb

We only wanted to check in the `perform_later` case because that's when we store it in the database.

Only check email for sensitive info when async

---

config/service_providers.localdev.yml

[LG-7716: Sample apps support IRS reproofing](https://cm-jira.usa.gov/browse/LG-7716)
Adds a Mock IRS SP for testing IRS reproofing.
Paired with [this OIDC Sample App PR](https://github.com/18F/identity-oidc-sinatra/pull/125), for which enabling Attempts API in your request will redirect the auth request to this new mock SP.

LG-7716: adds Mock IRS to sample SPs

---

app/controllers/component_preview_controller.rb

[slack discussion of error](https://gsa-tts.slack.com/archives/C0NGESUN5/p1666632258318099?thread_ts=1666632234.792629&cid=C0NGESUN5)
**Why**: we avoid loading lookbook gem unless the feature flag is on, so the classes to subclass and the mixins will fail due to load errors
**How**: I went with the sneaky trailing if to minimize diff noise
- Deploy to a lower env with the feature disabled (int)

Guard defining ComponentPreviewController on feature flag

---

Gemfile.lock
config/application.rb
config/application.yml.default
db/worker_jobs_migrate/20221024144708_create_index_good_jobs_jobs_on_priority_created_at_when_unfinished.rb
lib/identity_config.rb

During load testing, we found a couple optimizations that have been upstreamed into good_job. This adds a safe default for the select limit (which we may want to make configurable at some point) and removes the preservation of job rows.

Update GoodJob and GoodJob configuration

---

lib/identity_job_log_subscriber.rb
spec/lib/identity_job_log_subscriber_spec.rb

The `ActionMailer` job class does not implement `warning_error_classes` and this can cause issues when sending emails asynchronously. This isn't ideal, so I'm open to other approaches.

Ensure job class defines warning_error_classes before calling it to prevent logging failures

---

app/services/proofing/mock/state_id_mock_client.rb
spec/services/proofing/mock/state_id_mock_client_spec.rb

Our dev docs have a sample YAML file which does not include a state ID number. As a result when partners change the jurisdiction to a supported jurisdiction it causes failures when calling downcase on the nil value.
This commit fixes this bug by protecting against a nil value there. We should also add a state id number and type to the example YAML on the dev docs.

LG-7891 Protect against nil state id numbers in mock proofer

---

app/controllers/api/verify/document_capture_controller.rb
app/controllers/idv/image_uploads_controller.rb
app/views/idv/shared/_document_capture.html.erb
spec/controllers/api/verify/document_capture_controller_spec.rb
spec/features/idv/doc_auth/document_capture_step_spec.rb
spec/features/idv/doc_capture/document_capture_step_spec.rb
spec/features/idv/proofing_components_spec.rb
spec/features/idv/strict_ial2/upgrade_spec.rb
spec/rails_helper.rb

We are retiring IAL2-strict which means we will no longer be asking the React app to collect selfies from the user. This commit sets the flags to be permanently false so we can start working back and removing code to remove the request for selfies.

Stop requesting selfies from the frontend

---

lib/analytics_events_documenter.rb
spec/lib/analytics_events_documenter_spec.rb

**Why**: Lets us link to specific definition of code, as well as link to searching for usages of where it's called
Corresponding handbook PR: https://github.com/18F/identity-handbook/pull/337

Export information about source code for event documentation

---

app/services/idv/steps/inherited_proofing/agreement_step.rb

Why:
Need to track asyn proofing session to accurately track proofing process
changelog: Internal, Inherited Proofing, We are Retrieving API call
[LG-7255](https://cm-jira.usa.gov/browse/LG-7255)
Added a proofing session to accurately capture the proofing process. This copies other similar processes in the app.

LG-7255 - Adds proofing session 

---

app/controllers/api/verify/document_capture_controller.rb
app/jobs/document_proofing_job.rb
app/services/idv/agent.rb
spec/controllers/api/verify/document_capture_controller_spec.rb
spec/jobs/document_proofing_job_spec.rb

The selfie is used to support strict IAL2. The strict IAL2 flow is being retired so we will not be matching selfies here in the near term. This commit retires the code that passes the selfie through the IdV agent to the document proofing job and to the SDK adapter since it is no longer an active code path.

Remove the selfie args from the `Idv::Agent`

---

app/controllers/api/verify/document_capture_controller.rb
app/forms/idv/api_document_verification_form.rb
spec/forms/idv/api_document_verification_form_spec.rb

Removed the liveness check from the ApiDocumentVerification form. The liveness check is a part of selfie verification which is being removed from IdV.

Remove liveness check from ApiDocumentVerification

---

app/controllers/idv/image_uploads_controller.rb
app/forms/idv/api_image_upload_form.rb
spec/controllers/idv/image_uploads_controller_spec.rb
spec/forms/idv/api_image_upload_form_spec.rb

[LG-7711](https://cm-jira.usa.gov/browse/LG-7711)
Remove liveness check and selfie stuff from ApiImageUploadForm and relevant specs

Remove selfie and liveness from ApiImageUploadForm and relevant specs

---

app/assets/stylesheets/email.css.scss
app/components/barcode_component.rb
app/views/user_mailer/in_person_ready_to_verify.html.erb
app/views/user_mailer/in_person_verified.html.erb

This pull request seeks to improve performance of email sends (and the delivered email itself?) by avoiding the inclusion of the full set of design system utility classes. As discovered by @mitchellhenke, email delivery is quite slow, due to how the [premailer gem](https://github.com/premailer/premailer) iterates and detects matches for each selector of the email stylesheet. Thus, we should be careful to limit the size of the email stylesheet as much as possible.
The approach here aims to try to continue usage of the design system utility classes for developer convenience and consistency, but opting-in piecemeal.
This should only be relevant for templates added or updated since July (c8a185b8cf7e3ab2a84bb50b8a6ab7f9c42aabe8), as this is when the utilities were initially introduced.
A …

Avoid importing design system utilities into email CSS

---

lib/tasks/dev.rake
spec/lib/tasks/dev_rake_spec.rb

[LG-7876](https://cm-jira.usa.gov/browse/LG-7876)
- Create a new CLI tool for adding in-person enrollments to users for load testing
- `rails dev:random_in_person_users SCRYPT_COST='800$8$1$' NUM_USERS=10000 ENROLLMENT_STATUS=pending`
- Skips re-adding pending enrollments since only one is allowed per user
- Update existing user generation CLI tool to handle previously generated records
- Skip if already verified
- Skip email/password setup if email is confirmed

LG-7876: Create CLI tool for generating in-person enrollment records

---

app/services/doc_auth/lexis_nexis/config.rb
app/services/doc_auth/lexis_nexis/lexis_nexis_client.rb
app/services/doc_auth/lexis_nexis/requests/true_id_request.rb
app/services/doc_auth/lexis_nexis/responses/true_id_response.rb
app/services/doc_auth_router.rb
spec/services/doc_auth/lexis_nexis/lexis_nexis_client_spec.rb
spec/services/doc_auth/lexis_nexis/requests/true_id_request_spec.rb
spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb
spec/support/features/doc_auth_helper.rb

Why? Removed liveness and selfie from the LexisNexis client.

Remove selfie from Lexis Nexis

---

README.md

While working on [LG-7711](https://cm-jira.usa.gov/browse/LG-7711) discovered missing README items
Updated README with:
1. advice for `cannot load such file -- sassc` error
2. how to lint code
Test the additions to the README:
N/A

Add sassc error message troubleshooting and make lint

---

app/assets/stylesheets/email.css.scss

As a follow-on to #7224, adds a missing CSS class `radius-lg` currently used in email templates.
https://github.com/18F/identity-idp/blob/08b0a7cdab4c0dfdb2b776af9779f8786b092e1e/app/views/user_mailer/in_person_ready_to_verify.html.erb#L18
It may have been missed in part since `.radius` is a class provided by [`foundation-emails`](https://www.npmjs.com/package/foundation-emails) so it may have been assumed the same for `.radius-lg`, but in-fact this is implemented as a design system utility.

Add missing email CSS class

---

app/components/language_picker_component.html.erb
spec/components/language_picker_component_spec.rb

As a follow-on improvement (minor regression fix) to #7188, this updates the language picker component to render as collapsed by default in the initial markup.
While previously the language picker would become collapsed by default, it wouldn't occur until JavaScript had initialized, which could result in some brief flickering of the language picker while the page is loading.
It could be argued that the collapsing _should_ occur in JavaScript in order to support no-JavaScript browsers, however (a) this is not how it behaved prior to #7188 and the changes here seek to restore the original behavior, and (b) due to the styling of the language picker, it's possible for the options to overlap page content in such a way that may worsen the experience for no-JavaScript users. Future work could …

Render language picker as collapsed by default in markup

---

app/services/doc_auth/error_generator.rb
app/services/doc_auth/errors.rb
app/services/doc_auth/lexis_nexis/responses/true_id_response.rb
app/services/doc_auth_router.rb
spec/services/doc_auth/acuant/responses/get_results_response_spec.rb
spec/services/doc_auth/error_generator_spec.rb
spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb
spec/services/doc_auth_router_spec.rb

We are removing the selfie and strict IAL2 tooling 🙅. This commit moves us in that direction ➡️ by removing the distinction between selfie and no selfie general errors in the doc auth error generator.

Stop distinuishing between liveness and no liveness general errors

---

app/views/idv/in_person/address.html.erb
config/locales/in_person_proofing/en.yml
config/locales/in_person_proofing/es.yml
config/locales/in_person_proofing/fr.yml
spec/features/idv/steps/in_person/verify_step_spec.rb
spec/support/features/in_person_helper.rb

[LG-7686](https://cm-jira.usa.gov/browse/LG-7686)
Updates "Address (optional)" to "Address line 2 (optional)" in the in-person proofing address form, for clarity and consistency with unsupervised flow step labels updated in #7180 ([LG-7669](https://cm-jira.usa.gov/browse/LG-7669)).
2. Sign in
5. Use [attention result test document](https://developers.login.gov/testing/#testing-identity-proofing) for front and back
6. Submit
7. Enter in-person proofing flow and complete up to address form
8. Observe that the label for second address line is "Address line 2 (optional)"
---|---|---
Form|![localhost_3000_verify_in_person_address](https://user-images.githubus …

LG-7686: Update address line 2 label for IPP address form

---

app/forms/idv/api_image_upload_form.rb
app/jobs/document_proofing_job.rb
app/services/doc_auth/acuant/acuant_client.rb
app/services/doc_auth/lexis_nexis/lexis_nexis_client.rb

This commit gives us some safety and assurance that things won't break when we start deploying the changes to remove IAL2 strict.
All of the clients _should_ have a default arg for `selfie_image` and `liveness_checking_enabled` and none of the callers should be passing those args. We can follow this up with a commit to configure the clients to stop supporting those args.

Make sure that `selfie_image` and `liveness_checking_enabled` args aren't used and have default values in images clients

---

app/services/doc_auth/error_generator.rb
app/services/doc_auth/errors.rb
app/services/doc_auth_router.rb
config/locales/doc_auth/en.yml
config/locales/doc_auth/es.yml
config/locales/doc_auth/fr.yml
spec/services/doc_auth/error_generator_spec.rb
spec/services/doc_auth_router_spec.rb

We are removing IAL2 strict and selfie match functionality. This commit cleans up the last references to the selfie match portions of the `ErrorGenerator`.
The `ErrorGenerator` produces a takes the reponse and ultimately generates an errors hash data structure which can be used to render errors to the user on specific images (e.g. the front, back, selfie, or entire ID). This commit removes the code that covered special cases for selfie failures.

Remove the last few selfie references in the error generator

---

app/controllers/concerns/fully_authenticatable.rb
app/controllers/openid_connect/logout_controller.rb
app/controllers/users/service_provider_inactive_controller.rb
spec/features/openid_connect/openid_connect_spec.rb

Resolves LG-7878
https://cm-jira.usa.gov/browse/LG-7878
Add an option for `delete_branded_experience` to remove the SP session and use it during OIDC logout to ensure that users that elect not to terminate their Login.gov session don't end up being prompted to return to the SP that logged them out.
**Expected:** There will be no alert prompting the user to return to the SP

[LG-7878] Fully remove SP session during unconfirmed OIDC logout

---

app/decorators/user_decorator.rb
spec/decorators/user_decorator_spec.rb

This is necessary to prevent a bug where the "Reproof for IRS" modal appeared when users where proofing with IRS for the first time.
Also, this makes logical sense since a user who has not proofed before cannot reproof

LG-7944 Return false from reproof_for_irs? if a user has never proofed

---

app/javascript/packages/memorable-date/index.spec.ts

Removes an unnecessary sleep delay from JavaScript tests, to avoid prolonging runtime of the tests. Ideally we should never have a realtime delay in any spec.
Impact should be at least 12 seconds faster test runtime (2x 6 second delay). Assuming an average of 1m30s test runtime in GitLab, should hopefully equate to ~13% faster completion.
Per the inline code comment, I tested to confirm that the tests would fail as expected before and after the removal of the delay with a reversion of the fix in #6938.
I'd like to remove this test group `itIsUnaffectedByNewRelicEventBug ` altogether at some point after this and #7246 are merged, since we ideally shouldn't have to build-in assumed hostile third-party script handling to our specs.
Revert patch:
```diff
diff --git …
```

Remove sleep delay from JavaScript tests

---

.rubocop.yml
app/views/accounts/_pii.html.erb
app/views/accounts/_unphishable_badge.html.erb
app/views/accounts/_verified_account_badge.html.erb
app/views/idv/cancellations/destroy.html.erb
app/views/idv/capture_doc/capture_complete.html.erb
app/views/idv/doc_auth/email_sent.html.erb
app/views/idv/doc_auth/link_sent.html.erb
app/views/idv/doc_auth/upload.html.erb
app/views/idv/inherited_proofing_cancellations/destroy.html.erb
app/views/layouts/account_side_nav.html.erb
app/views/pages/page_took_too_long.html.erb
app/views/shared/_banner.html.erb
app/views/shared/_footer_lite.html.erb
app/views/users/phone_setup/index.html.erb
app/views/users/piv_cac_setup_from_sign_in/success.html.erb
app/views/users/totp_setup/new.html.erb
lib/linters/image_size_linter.rb
spec/lib/linters/image_size_linter_spec.rb

Adds a linter to enforce that any `image_tag` includes either `width` and `height` or a `size` attribute, so as to adhere to best practices to avoid layout shifts.
- https://www.smashingmagazine.com/2020/03/setting-height-width-images-important-again/
- https://www.aleksandrhovhannisyan.com/blog/setting-width-and-height-on-images/
- https://web.dev/optimize-cls/#images-without-dimensions
Visually, there should be no effective difference with these changes. This was made somewhat challenging by how some images are scaled, since adding `width` or `height` where it was previously not set could create issues where the image was scaled down due to constraints of its parent container. I've done a manual review to try to ensure no regressions in the display of images.

Add and enforce image size attributes for rendered images

---

spec/support/fake_analytics.rb

Updates our `have_logged_event` custom matcher to show diffs of unexpected analytics events
I only implemented diffs when we can tell that the expected event occurred exactly once but the attributes are different than expected. This will show diffs for cases when we do a direct comparison of the event's attributes to a hash ([example](https://github.com/18F/identity-idp/blob/73c4379eb613565eaa787b90958706fa4b82162b/spec/jobs/get_usps_proofing_results_job_spec.rb#L16-L38)) and when we use an `include` matcher ([example](https://github.com/18F/identity-idp/blob/73c4379eb613565eaa787b90958706fa4b82162b/spec/jobs/get_usps_proofing_results_job_spec.rb#L89-L99)). Other scenarios will fall back to the existing failure message
This is just a change to our tests. No changes to application code …

Make analytics event matcher show a diff

---

app/forms/idv/inherited_proofing/base_form.rb
app/services/idv/inherited_proofing/va/mocks/service.rb
lib/session_encryptor.rb
spec/controllers/users/mfa_selection_controller_spec.rb
spec/services/idv/inherited_proofing/va/mocks/service_spec.rb

[LG-7738](https://cm-jira.usa.gov/browse/LG-7738)
Returns an error in the Inherited Proofing mock proofer when the incorrect auth code is provided

Lg 7738 - mock errors for inherited proofing mock proofer

---

spec/support/mailer_helper.rb

Implements [RSpec failure aggregation](https://relishapp.com/rspec/rspec-core/docs/expectation-framework-integration/aggregating-failures) to run all assertions against expected email message before failing.
There are some flakey mailer specs ([example](https://gitlab.login.gov/lg/identity-idp/-/jobs/111536)) which are difficult to debug currently since it fails at the first assertion. It's hypothesized that the emails may be sent out of order, and it'd be helpful to have a fuller picture of the actual and expected results.
Easiest to review with whitespace hidden: https://github.com/18F/identity-idp/pull/7251/files?w=1

Aggregate failures for flakey mailer specs

---

app/javascript/packages/document-capture/components/barcode-attention-warning.tsx
app/javascript/packages/document-capture/components/capture-advice.jsx
app/javascript/packages/document-capture/components/document-capture-troubleshooting-options.spec.tsx
app/javascript/packages/document-capture/components/document-capture-troubleshooting-options.tsx
app/javascript/packages/document-capture/components/documents-step.jsx
app/javascript/packages/document-capture/components/review-issues-step.tsx
spec/javascripts/packages/document-capture/components/document-capture-spec.jsx

[LG-7943](https://cm-jira.usa.gov/browse/LG-7943)
Updates display of document capture troubleshooting option to avoid rendering in-person call-to-action when field validation errors exist.
<details>
</details>
<details>
</details>

LG-7943: Avoid showing in-person option for field validation errors

---

app/controllers/idv/inherited_proofing_controller.rb
app/controllers/idv/inherited_proofing_errors_controller.rb
app/views/idv/inherited_proofing_errors/failure.html.erb
app/views/idv/inherited_proofing_errors/warning.html.erb
config/locales/inherited_proofing/en.yml
config/locales/inherited_proofing/es.yml
config/locales/inherited_proofing/fr.yml
config/routes.rb

[LG-7452](https://cm-jira.usa.gov/browse/LG-7452)
1. Add InheritedProoofingErrorsController
2. Move existing first error page to this controller
3. Add new error page after throttle is hit
/verify/inherited_proofing/errors/no_information
/verify/inherited_proofing/errors/failure
<details>
</details>
<details>
</details>

LG-7452 Inherited Proofing Error Controller and new error page

---

app/assets/stylesheets/components/_alert.scss

[https://cm-jira.usa.gov/browse/LG-7970]
Set font-weight style on the style to 500, per slack conversation

Updated .usa-alert--info-important style to bold text.

---

app/models/profile.rb
spec/models/profile_spec.rb

The methods are not longer used since IAL2 strict has been retired

Remove liveness methods from the Profile model

---

app/jobs/get_usps_proofing_results_job.rb
spec/jobs/get_usps_proofing_results_job_spec.rb

[LG-7706](https://cm-jira.usa.gov/browse/LG-7706?filter=-1)
When the USPS polling job encounters an unexpected bad request error begin logging it to NewRelic

LG-7706: Log unexpected bad request errors to new relic

---

app/controllers/api/verify/document_capture_controller.rb
app/services/idv/steps/document_capture_step.rb
app/views/idv/capture_doc/document_capture.html.erb
app/views/idv/doc_auth/document_capture.html.erb
app/views/idv/shared/_document_capture.html.erb
config/initializers/rack_timeout.rb
spec/controllers/idv/capture_doc_controller_spec.rb
spec/controllers/idv/doc_auth_controller_spec.rb
spec/forms/idv/api_image_upload_form_spec.rb
spec/javascripts/packages/document-capture/components/acuant-capture-spec.jsx
spec/services/db/add_document_verification_and_selfie_costs_spec.rb
spec/support/acuant_fixtures.rb
spec/support/doc_auth_image_fixtures.rb
spec/views/idv/shared/_document_capture.html.erb_spec.rb

We are no longer using selfies to proof since IAL2 strict is deprecated and being removed. This commit removes some of the tooling that enabled selfie upload.

Remove a few references to selfies and face images

---

spec/jobs/get_usps_proofing_results_job_spec.rb

This change is necessary since the Faraday upgrade. It looks like it got missed when the Faraday change was merged before this.
This commit fixes a CI failure on main.

Add application/json header to in-person API call

---

app/views/shared/_banner.html.erb

Removes the "banner" hard-coded label assigned to the site's banner header.
**Why?**
* As a user of assistive technology, I expect that labels would be used to provide additional detail beyond a landmark's semantic default and would not otherwise be assigned, so that I am not exposed to duplicate / redundant information
* As a user of assistive technology browsing Login.gov in a language other than English, I expect that labels would be translated in the page's current language, so that I am not confused by labels read in a different language
**Related resources:**
* https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/banner_role
* https://www.w3.org/TR/wai-aria-1.2/#banner
* https://www.w3.org/WAI/WCAG21/Understanding/language-of-page
_English_:
Observe that "banner" is …

Remove redundant, untranslated banner label

---

app/javascript/packs/session-expire-session.js
app/views/layouts/base.html.erb
app/views/session_timeout/_expire_session.html.erb
spec/features/users/sign_in_spec.rb

Reverts 18F/identity-idp#7249
Related Slack conversation: https://gsa-tts.slack.com/archives/C0NGESUN5/p1667331820015699
The changes in #7249, while functionally equivalent to what had existed previously, introduce new errors flagged by accessibility testing tools related to `http-equiv="refresh"`. Future iterations should explore how to allow a user to extend the timeout, while remaining compatible with technical requirements for CSRF token expiration of 15 minutes.
~_(Draft while I undo some of the diff to keep some desirable changes like template comment corrections and spec removal)_~ **Edit:** Edited in 3438c5e.

Revert "Render unauthenticated session expire redirect as meta tag"

---

app/jobs/document_proofing_job.rb
app/services/doc_auth/acuant/acuant_client.rb
app/services/doc_auth/lexis_nexis/lexis_nexis_client.rb
app/services/doc_auth/mock/doc_auth_mock_client.rb

The code that quits calling the document proofing job with the selfie image and liveness enabled args is merged and deployed to prod. As such it should be safe to remove these args form the job.
Additionally, the doc auth clients themselves should no longer be called with these args so they should be safe to remove from those as well.

Remove selfie and liveness enabled job and client args

---

app/services/irs_attempts_api/envelope_encryptor.rb
config/application.rb
lib/base16.rb
lib/tasks/attempts.rake
spec/lib/base16_spec.rb

- `<<` turns out to be faster than `[].join`
See "encode_3" for some improvements over existing. Normally I would not try to pre-optimize this, but we I know that we were planning to do this for multiple megabytes of data at a time
Here's what I did to benchmark this against https://github.com/18F/identity-idp/pull/7204
```ruby
require 'benchmark/ips'
require 'base16'
require 'securerandom'
class PrBase16
def self.encode16(str)
str.bytes.map { |char| char.to_s(16).upcase.rjust(2, "0") }.join
end
def self.decode16(str)
output = ''
str.chars.each_slice(2) do |chars|
output << chars.join.to_i(16).chr
end
output
end
end
class Base16V3
def self.encode16(str)
output = ''
str.bytes.each { |char| output << char.to_s(16).upcase.rjust(2, "0") }
output
end
def self.decode16(str) …
```

Optimize base16 encoding

---

config/locales/forms/es.yml
config/locales/instructions/en.yml
config/locales/instructions/es.yml
config/locales/instructions/fr.yml
config/locales/titles/en.yml
config/locales/titles/es.yml
config/locales/titles/fr.yml
config/locales/two_factor_authentication/en.yml
config/locales/two_factor_authentication/es.yml
config/locales/two_factor_authentication/fr.yml

[LG-7717](https://cm-jira.usa.gov/browse/LG-7717)
Update "Enter your security code" screen to use new "one-time code" wording.
<table>
<thead>
<tr>
<th></th>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<th>English</th>
<td>
</td>
<td>
</td>
</tr>
<tr>
<th>Spanish</th>
<td>
</td>
<td>
</td>
</tr>
<tr>
<th>French</th>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
N/A

OTP language update

---

config/application.yml.default
config/initializers/redis.rb
lib/identity_config.rb

https://github.com/18F/identity-devops/issues/5429
This PR enables adjustable connection pool sizes to redis instances.

Adjustable Redis Connection Pooling

---

app/views/idv/otp_verification/show.html.erb
app/views/two_factor_authentication/sms_opt_in/new.html.erb
app/views/users/phone_setup/index.html.erb
config/locales/forms/en.yml
config/locales/forms/es.yml
config/locales/forms/fr.yml
config/locales/titles/en.yml
config/locales/titles/es.yml
config/locales/titles/fr.yml
spec/features/phone/confirmation_spec.rb
spec/features/phone/rate_limitting_spec.rb
spec/features/remember_device/phone_spec.rb
spec/features/remember_device/sp_expiration_spec.rb
spec/features/remember_device/user_opted_preference_spec.rb
spec/features/saml/saml_spec.rb
spec/features/two_factor_authentication/multiple_mfa_sign_up_spec.rb
spec/features/two_factor_authentication/sign_in_spec.rb
spec/features/users/sign_in_spec.rb
spec/features/users/sign_up_spec.rb
spec/support/features/session_helper.rb
spec/support/shared_examples/phone/rate_limitting.rb

Update translation keys that include `security_code` in their name to now say `one_time_code` to be more consistent with new wording. This was a change identified on #7276 that I didn't get in before hitting the big Merge button.

security_code -> one_time_code

---

README.md

Need for documented knowledge discovered during `#login-situation-practice`
Add good_job command to the README

Jskinne3 add jobs to readme

---

.gitlab-ci.yml
Gemfile
Gemfile.lock

Looks like this might just work without additional changes to GitLab: https://docs.gitlab.com/ee/ci/testing/unit_test_reports.html
**update**: it works! see screenshot below:

Use JUnit outputter in GitLab

---

config/application.yml.default
config/initializers/redis.rb
config/initializers/session_store.rb
lib/identity_config.rb

- Via ConnectionPool::Wrapper which may be slightly slower

Use a connection pool for redis-session-store

---

lib/tasks/attempts.rake

None. This is whim.
* Fixes a small bug breaking `rake attempts:check_enabled`
* Adds `rake attempts:enable_for_sinatra` task, to make life easier
```
$ be rake attempts:check_enabled
✅ Feature flag is enabled
❌ FAILED: Run rake attempts:enable_for_sinatra
✅ abc123 set as auth token
✅ 'keys/attempts_api_private_key.key' exists for decrypting events
Remember to restart Rails after updating application.yml.default!
$ be rake attempts:enable_for_sinatra
$ be rake attempts:check_enabled
✅ Feature flag is enabled
✅ Sinatra app SP has irs_attempts_api_enabled=true
✅ abc123 set as auth token
✅ 'keys/attempts_api_private_key.key' exists for decrypting events
```
N/A - This should not be used in prod.

Adds attempts:enable_for_sinatra and fix minor breakage

---

app/services/encryption/contextless_kms_client.rb
app/services/encryption/multi_region_kms_client.rb
config/application.yml.default
lib/identity_config.rb
spec/services/encryption/contextless_kms_client_spec.rb
spec/services/encryption/multi_region_kms_client_spec.rb
spec/support/aws_kms_client.rb

Hypothesis: creating new clients as often as we does makes too many IAM metadata requests, so this cuts down on that

Use a connection pool for talking to KMS

---

app/javascript/packages/document-capture/components/file-input.jsx
spec/javascripts/packages/document-capture/components/file-input-spec.jsx

[LG-7770](https://cm-jira.usa.gov/browse/LG-7770)
Testing identified that users wanted more detail in the ARIA label attached to the `FileInput` component in the IDV doc auth upload step. The request here was that the label include not only the field name ("Front of ID"  / "Back of ID"), but the next step as well ("drag file here or choose from folder").
Previously, there were two separate hints attached via the [`aria-describedby` attribute](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-describedby): "Drag file here..." and "Must be a JPG or PNG". 
Some screen readers (tested in JAWS) would not read this `aria-describedby` content initially without the user triggering it in some way, leading to a confusing experience where the user would focus the …

Update ARIA labels / described by on IDV doc auth FileInput component

---

package.json
yarn.lock

Upgrades `babel-loader` to latest version to resolve failing lint builds on main related to [security advisory](https://www.npmjs.com/advisories/1084896).
Resources:
- [Release notes](https://github.com/babel/babel-loader/releases)
- [Git comparison 8.2.5 to 9.1.0](https://github.com/babel/babel-loader/compare/v8.2.5...v9.1.0)
Notable breaking changes:
- Supports only Webpack >= 5 (we're already webpack@5.74.0)
- Supports only Node.js >= 14.15.0 (we're already node@16)
- Supports only Babel ^7.12.0 (we're already babel@7.15.5)

Upgrade babel-loader to latest

---

app/views/idv/otp_verification/show.html.erb
app/views/two_factor_authentication/otp_verification/show.html.erb
config/locales/links/en.yml
config/locales/links/es.yml
config/locales/links/fr.yml
spec/features/idv/phone_otp_rate_limiting_spec.rb
spec/features/idv/steps/phone_otp_verification_step_spec.rb
spec/features/two_factor_authentication/change_factor_spec.rb
spec/support/shared_examples/phone/otp_confirmation.rb
spec/support/shared_examples/phone/rate_limitting.rb
spec/views/two_factor_authentication/otp_verification/show.html.erb_spec.rb

[LG-7717](https://cm-jira.usa.gov/browse/LG-7717)
This is a follow-on from #7276. There was an additional language change that was missed in the initial translations doc. The "Get another code" button now reads "Send another code". I also updated the key names in the translation file from `get_another_code` to `send_another_code` to keep them consistent.
There is some additional context in the [Slack Acceptance thread for LG-7717](https://gsa-tts.slack.com/archives/C049E3XJQ1F/p1667510933886289).
N/A

Additional OTP language updates

---

app/controllers/concerns/two_factor_authenticatable_methods.rb
app/controllers/idv/gpo_verify_controller.rb
app/controllers/idv/review_controller.rb
app/controllers/two_factor_authentication/personal_key_verification_controller.rb
app/controllers/users/passwords_controller.rb
app/controllers/users/reset_passwords_controller.rb
app/models/event.rb
app/services/user_event_creator.rb
spec/services/user_event_creator_spec.rb

**Why**: transient attributes on AR models can be confusing, this makes it clear it's not persisted
following up on https://github.com/18F/identity-idp/pull/7301/files#r1015533019

Remove transient Event#diavowal_token, return it as a tuple

---

app/decorators/user_decorator.rb

Optimizes `UserDecorator#reproof_for_irs?` to avoid a database query by short-circuiting on a known value (`service_provider`) when possible. This avoids a database query for every non-IRS service provider.
Inspired by #7279, since we're now logging the value of `reproof_for_irs?` for every analytics event in identity verification.

Microoptimize reproof_for_irs to avoid database query

---

db/primary_migrate/20221104210336_drop_email_addresses_user_id_last_sign_in_at_desc_index.rb
db/schema.rb

This is the follow-up PR to #7298 that drops the large and write-heavy index on `email_addresses`.
This PR should not be merged until #7298 is deployed. It is in theory safe to deploy both changes together since the second migration won't run if the first one fails, but this is erring on the side of caution.

Drop large user_id, last_sign_in_at DESC index on email_addresses

---

Gemfile.lock
config/newrelic.yml

Updates the new relic gem and disables a new enabled-by-default setting that we wouldn't need or use.
Includes changes in https://github.com/newrelic/newrelic-ruby-agent/blob/dev/CHANGELOG.md#v890 and above

Upgrade NewRelic

---

app/jobs/irs_attempts_events_batch_job.rb
config/initializers/job_configurations.rb
spec/jobs/irs_attempts_events_batch_job_spec.rb

changelog: Internal, Attempts API, Add batch job to package events.
[Link to the relevant ticket.](https://cm-jira.usa.gov/browse/LG-7470)
Added a batch job to read attempt events from the previous hour from redis. Writes those events to a file and encrypts the file. File is then stored in a placeholder location until we get an S3 bucket. 
Want to get some early eyes on this. WIP and still needs lots of cleanup.

Adding attempt events packaging batch job.

---

app/assets/stylesheets/components/_password-toggle.scss
app/components/password_toggle_component.html.erb
app/components/password_toggle_component.rb
app/views/devise/passwords/edit.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_password_strength.html.erb
app/views/event_disavowal/new.html.erb
app/views/idv/review/new.html.erb
app/views/mfa_confirmation/new.html.erb
app/views/password_capture/new.html.erb
app/views/shared/_ssn_field.html.erb
app/views/sign_up/passwords/new.html.erb
app/views/users/delete/show.html.erb
app/views/users/passwords/edit.html.erb
app/views/users/verify_password/new.html.erb
spec/components/password_toggle_component_spec.rb
spec/components/previews/password_toggle_component_preview.rb

[LG-7947](https://cm-jira.usa.gov/browse/LG-7947)
Revises all password toggles to display the toggle input _below_ the password field, in order to correct tab order behavior such that the visual placement and tab order of the toggle always occurs after the password field.
Related Slack discussions:
- https://gsa-tts.slack.com/archives/C01JVKYE4KD/p1667415655701599
- https://gsa-tts.slack.com/archives/C01710KMYUB/p1667488908112899
- https://gsa-tts.slack.com/archives/C01710KMYUB/p1667496041397299
---|---|---
Sign in|![7947-sign-in-1](https://user-images.githubusercontent.com/1779930/199790292-4bc860c9-0bf9-464d-ac76-d73329e8d2a0.png)|![7947-sign-in-2](https://user-images.githubusercontent.com/1779930/200584705-afcbf512-e11c-4acb-afdd-1e30e9ddb06f.png)
Sign up …

LG-7947: Remove "top" position option for password toggle

---

app/controllers/api/irs_attempts_api_controller.rb
app/services/irs_attempts_api/envelope_encryptor.rb
spec/controllers/api/irs_attempts_api_controller_spec.rb

https://cm-jira.usa.gov/browse/LG-8050 + https://cm-jira.usa.gov/browse/LG-8051
The IRS is sending us timestamps with milliseconds in them, which currently generates an HTTP 422. Just accept this format.
I'm working in a related change to what we call the generated file, based on their request.

LG-8050 | Attempts API timestamp parsing fix

---

config/application.rb

**Why**: To help make sure that daily scheduled jobs don't get re-run because we use the concurrency_key on old records to check for duplicates
Reverting part of #7196, related to https://github.com/18F/identity-idp/pull/7317

Re-enable GoodJob's preserve_old_records

---

pull_request_template.md

**Why**: Still prompts PR authors to add known sections, but leaves less visual clutter if submitted un-modified
As discussed at [Eng Huddle 11/9](https://docs.google.com/document/d/1g_V2vlT79tScBKIVw7M4UXf15TrG69iUrLHE0yE1GGI/edit?disco=AAAAjoftSFw)

Make PR template text commented out by default

---

app/controllers/reauthn_required_controller.rb
app/views/mfa_confirmation/new.html.erb
config/locales/errors/en.yml
config/locales/errors/es.yml
config/locales/errors/fr.yml
config/locales/help_text/en.yml
config/locales/help_text/es.yml
config/locales/help_text/fr.yml

[LG-7934](https://cm-jira.usa.gov/browse/LG-7934)
Split from #7335
Removes unreachable references to "security code":
1. `errors.messages.otp_failed` is not referenced in code, but also not marked as unused due to [unused exception for `i18n-tasks.yml`](https://github.com/18F/identity-idp/blob/62cf90c750b947f580da8b3e8eba31b9f844bb63/config/i18n-tasks.yml#L99)
2. `ReauthnRequiredController` creates a mapping based on the subclass controller name, but `DeleteController` no longer extends `ReauthnRequiredController` as of 309042c635c3de3ba52bd768ac475716a30e54dc

LG-7934: Remove unreachable references to "security code"

---

app/controllers/idv/inherited_proofing_cancellations_controller.rb
app/controllers/idv/sessions_controller.rb
app/services/analytics_events.rb
spec/controllers/idv/inherited_proofing_cancellations_controller_spec.rb
spec/controllers/idv/sessions_controller_spec.rb
spec/features/idv/inherited_proofing/analytics_spec.rb

also fix analytics name casing (to IdV from Idv) for consistency
changelog: Internal, Analytics, add IdV inherited proofing cancellation analytics
https://cm-jira.usa.gov/browse/LG-7987
Added calls to the existing inherited proofing cancellations controller. Reused existing IdV analytics cancellation methods, but added the IP analytics_id.
Added controller test examples to validate analytics calls are being made with proper parameters.

LG-7987 add IdV inherited proofing cancellation analytics

---

app/views/two_factor_authentication/backup_code_verification/show.html.erb
app/views/two_factor_authentication/otp_verification/show.html.erb
app/views/two_factor_authentication/personal_key_verification/show.html.erb
app/views/two_factor_authentication/totp_verification/show.html.erb
config/locales/telephony/en.yml
config/locales/telephony/es.yml
config/locales/telephony/fr.yml
config/locales/titles/en.yml
config/locales/titles/es.yml
config/locales/titles/fr.yml
config/locales/two_factor_authentication/en.yml
config/locales/two_factor_authentication/es.yml
config/locales/two_factor_authentication/fr.yml
spec/views/two_factor_authentication/otp_verification/show.html.erb_spec.rb
spec/views/two_factor_authentication/personal_key_verification/show.html.erb_spec.rb

[LG-7934](https://cm-jira.usa.gov/browse/LG-7934)
Updates all existing references to "security code" in the context of SMS and Voice authentication codes to "one-time code".

LG-7934: Rename OTP security code to one-time code

---

config/locales/telephony/en.yml
config/locales/telephony/es.yml
config/locales/telephony/fr.yml

[LG-7934](https://cm-jira.usa.gov/browse/LG-7934)
Updates a lingering reference to "security code" in the context of SMS and Voice authentication codes to "one-time code", missed as part of #7335. This text is shown as a fallback error message in the case of telephony send errors.
Related Slack comment: https://gsa-tts.slack.com/archives/C01710KMYUB/p1668540190720279?thread_ts=1668539716.757899&cid=C01710KMYUB

LG-7934: Update another "security code" to "one-time code"

---

app/services/analytics.rb

Removes the logic for `Analytics#track_mfa_submit_event`'s return value, as it is not used. It appears to be originally [used as part of Google Analytics measurements](https://github.com/18F/identity-idp/pull/2835/files#diff-7d70ee23bf46aada63c06abeff7370d8bfc04653e750081f438526e163c15411R23) which have since been removed.

Remove unused return value for MFA analytics method

---

app/services/push_notification/http_push.rb
spec/services/push_notification/http_push_spec.rb

changelog: add kid to JWT
LG-7797
Adds kid (Key ID) to the JWT token we send. This request came from a partner.

Include kid in JWT

---

app/models/concerns/user_otp_methods.rb
config/application.yml.default
lib/identity_config.rb

[LG-8065](https://cm-jira.usa.gov/browse/LG-8065) (supporting refactor)
Updates max OTP login attempts to be defined as an application configuration.
**Why?**
- Consistency with other throttling max values
- Making it easier to find
- Also named with consistent "_max_attempts" suffix
- Supports option for adjustments to live environments without code changes
- Supporting future refactoring:
- Implement OTP attempts as throttle, where this would become the `max_attempts` value in the [throttle configuration](https://github.com/18F/identity-idp/blob/3358791eaa7c3f7a859a7c873308de925c821a69/app/services/throttle.rb#L7-L52)
- Split throttling for non-login OTP confirmations (e.g. [identity verification phone verification](https://github.com/18F/identity-idp/blob/3358791eaa7c3f7a859a7c873308de9 …

Define max login OTP confirmation attempts as configuration

---

app/services/irs_attempts_api/attempt_event.rb
spec/services/irs_attempts_api/attempt_event_spec.rb

LG-8086 Include millisec in the Attempts Timestamp

---

spec/features/two_factor_authentication/sign_in_spec.rb

[LG-8065](https://cm-jira.usa.gov/browse/LG-8065) (supporting refactor)
Implements a feature spec which tests expected real-world rate-limiting behavior for MFA confirmation as a replacement for current spec which stubs lockout. This was originally planned as a refactor to support additional specs for [LG-8065](https://cm-jira.usa.gov/browse/LG-8065), but that ticket may be reprioritized.
**Why?**
* Test real user behavior
* Improve performance by disabling JavaScript (ChromeDriver) for spec

Add feature spec for OTP confirmation rate limiting

---

app/decorators/user_decorator.rb
spec/decorators/user_decorator_spec.rb

Removes a "default" lockout period value which should not ever be reachable given that a configuration value should always be present.
Based on the description of #1507, it appears to stem from a point in time where deployment of configuration values would not occur in sync with the application code and where not all configuration values were explicitly required.
**Why make this change?**
* Assert confidence in the presence of configuration values
* Remove magic number
* Avoid confusion on which lockout period is the correct lockout period
* Marginal performance improvement in a hot path by avoiding redundant check on configuration value
- `rspec spec/features/two_factor_authentication/sign_in_spec.rb:492`

Remove unreachable blank config lockout default logic

---

config/application.yml.default
spec/features/idv/phone_otp_rate_limiting_spec.rb
spec/forms/idv/phone_confirmation_otp_verification_form_spec.rb
spec/support/shared_examples/phone/rate_limitting.rb

[LG-8139](https://cm-jira.usa.gov/browse/LG-8139)
Increases the default configured number of allowed MFA confirmation attempts before lock-out.
Per [NIST usability guidance](https://pages.nist.gov/800-63-3/sp800-63b.html#-101-usability-considerations-common-to-authenticators):
>Allow at least 10 entry attempts for authenticators requiring the entry of the authenticator output by the user.
See ticket description for additional context.
1. Create or sign in to a user which has a code-based authenticator (phone, TOTP, etc)
2. Enter and submit an incorrect value 10 times
3. Observe that lockout occurs after 10th failed attempt

LG-8139: Increase max OTP confirmation attempts

---

spec/features/multiple_emails/add_email_spec.rb

Attempts to resolve an email mailer spec which is commonly failing intermittently.
Example build: https://gitlab.login.gov/lg/identity-idp/-/jobs/157721 
The hypothesis here is that the email address order is not specified so cannot be guaranteed to be an array in the order assumed by the test assertion. Other specs in the same file may not be prone to this since they reference [`User#confirmed_email_addresses`](https://github.com/18F/identity-idp/blob/db385004eb2015ed4859e24d12646ac28e6b592e/app/models/user.rb#L60-L62), which has a built-in order. Because this spec cannot operate on the confirmed email addresses, the changes here instead manually add an order to guarantee the expected outcome.
- `rspec spec/features/multiple_emails/add_email_spec.rb:129`

Try to fix flakey email spec

---

lib/tasks/dev.rake
spec/lib/tasks/dev_rake_spec.rb

Tries to resolve a flakey spec failure caused by other parts of the code also calling `sleep`.
```
The message 'sleep' was received by #<Object:386240 > but has already been received by #<Puma::ThreadPool::Automaton:0x000056521827c098>
```
Example failure: https://gitlab.login.gov/lg/identity-idp/-/jobs/157885
- `rspec spec/lib/tasks/dev_rake_spec.rb`

Fix flakey IPP sample data rake spec

---

app/forms/new_phone_form.rb
config/application.yml.default
config/locales/errors/en.yml
config/locales/errors/es.yml
config/locales/errors/fr.yml
lib/identity_config.rb
spec/forms/new_phone_form_spec.rb

To improve the precision we have to control phone registration and volume, this PR adds a configuration to allow blocking specific carriers.
Example:

Add configurable phone carrier registration blocklist

---

app/javascript/packages/build-sass/CHANGELOG.md
app/javascript/packages/build-sass/LICENSE.md
app/javascript/packages/build-sass/README.md
app/javascript/packages/build-sass/index.js
app/javascript/packages/build-sass/package.json
yarn.lock

Updates dependencies for the `@18f/identity-build-sass` workspace package and prepares it for publishing to NPM (update `package.json`, add changelog, add README).
The plan is to use this in `18F/identity-site` to improve build times, bring consistency of compilation targets.
There shouldn't be any noticeable impact from this, but ensure that the dependencies upgrades incur no regression in expected build behavior.

Prepare build-sass package for publish

---

app/jobs/in_person/email_reminder_job.rb
app/services/analytics_events.rb
spec/jobs/in_person/email_reminder_job_spec.rb

[LG-7185](https://cm-jira.usa.gov/browse/LG-7185)
Add basic error handling and analytics for `InPerson::EmailReminderJob`

LG-7185: Add error handling and analytics to in-person proofing email reminder job

---

spec/features/multiple_emails/add_email_spec.rb

Attempts to resolve an email mailer spec which is commonly failing intermittently.
Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1669069995915509
Same premise as #7359.
There are a couple other occurrences of `User#email_addresses` in this file, but based on how they're used, they shouldn't be prone to the same problem.

Fix flakey email spec

---

spec/services/analytics_spec.rb

https://cm-jira.usa.gov/browse/LG-7987
This single spec file change simply extracts a common hash that is used in most of the examples, thereby showing how each example modifies the hash.

LG-7987 simplify analytics spec

---

app/services/proofing/result.rb

There was an indentation error that slipped through from https://github.com/18F/identity-idp/pull/7349#pullrequestreview-1188913249
I wanted to see if we could use Rubocop to catch these consistently:
```
+Layout/EndAlignment:
+  Enabled: true
+  EnforcedStyleAlignWith: keyword
```
However, the three options for [`Layout/EndAlignment`](https://docs.rubocop.org/rubocop/cops_layout.html#layoutendalignment) produced weird issues for some of our other `if ... end` blocks elsewhere so I think it's just easier to fix this manually for now

Fix alignment in Proofing::Result

---

app/forms/add_user_email_form.rb
app/validators/form_add_email_validator.rb
app/validators/form_email_validator.rb
spec/forms/add_user_email_form_spec.rb
spec/forms/register_user_email_form_spec.rb

We had a few unhandled exceptions from SES when trying to send to non-ASCII domain names ([NR link](https://one.newrelic.com/nr1-core/errors/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=604800000&state=f05676cb-1c5c-6663-133b-2cfa9044e8e4)) with the exception `Aws::SES::Errors::InvalidParameterValue: Domain contains illegal character`.
[SES documentation](https://docs.aws.amazon.com/ses/latest/APIReference/API_Destination.html) confirms this:
>Amazon SES does not support the SMTPUTF8 extension, as described in [RFC6531](https://tools.ietf.org/html/rfc6531). For this reason, the local part of a destination email address (the part of the email address that precedes the @ sign) may only contain [7-bit ASCII …

Validate email domains are ASCII to better align with AWS Simple Email Service (SES) support

---

app/forms/idv/inherited_proofing/base_form.rb
app/forms/idv/inherited_proofing/va/form.rb
app/services/analytics_events.rb
app/services/flow/base_flow.rb
app/services/flow/base_step.rb
app/services/flow/failure.rb
app/services/idv/actions/inherited_proofing/redo_retrieve_user_info_action.rb
app/services/idv/flows/inherited_proofing_flow.rb
app/services/idv/inherited_proofing/va/mocks/service.rb
app/services/idv/inherited_proofing/va/service.rb
app/services/idv/steps/inherited_proofing/agreement_step.rb
app/services/idv/steps/inherited_proofing/user_pii_job_initiator.rb
app/services/idv/steps/inherited_proofing/verify_wait_step_show.rb
app/services/idv/steps/verify_base_step.rb
app/services/throttle.rb
app/views/idv/inherited_proofing_errors/warning.html.erb
config/application.yml.default
config/locales/inherited_proofing/en.yml
config/locales/inherited_proofing/es.yml
config/locales/inherited_proofing/fr.yml
lib/identity_config.rb
spec/features/idv/inherited_proofing/inherited_proofing_cancel_spec.rb
spec/features/idv/inherited_proofing/verify_wait_step_spec.rb
spec/forms/idv/inherited_proofing/base_form_spec.rb
spec/forms/idv/inherited_proofing/va/form_spec.rb
spec/services/idv/inherited_proofing/va/service_spec.rb
spec/support/features/idv_helper.rb
spec/support/features/inherited_proofing_with_service_provider_helper.rb

Display and implement a "Try again" button so that an Inherited Proofing user can attempt to retrieve their PII from their Service Provider a second time, if the first attempt fails.
https://cm-jira.usa.gov/browse/LG-7450
- Add "Try again" button to the "We could not retrieve your information from..." UI. Allows user to try a second time to retrieve their user PII from their respective service provider. IP forces the user to acknowledge (checkbox) retrieval of their PII from the service provider in one step, and retrieves the PII in a subsequent ajax/async step. Subsequent retries _do not_ have to be acknowledged (checkbox).
- Implement error handling and bubbling up from service to form class for VA if errors are encountered during the request or errors encountered decrypting the payload …

LG-7450 Implement "Try Again" Button Functionality on the First Error Page

---

app/services/gpo_confirmation_exporter.rb
spec/services/gpo_confirmation_exporter_spec.rb

[LG-8063](https://cm-jira.usa.gov/browse/LG-8063)
The expiration date printed on GPO letters was being calculated as 30 days after the GPO upload job was run rather than 30 days after the original request was made.
This PR updates the GPO exporter to base expiration dates on the `created_at` field of the `GpoConfirmation` record.

Base GPO expiration on original request date

---

config/locales/telephony/es.yml

Fixes an error which currently occurs when requesting OTP code via voice call when viewing the site in Spanish.

Remove excess double-quote from Spanish voice OTP

---

spec/lib/telephony/otp_sender_spec.rb

Adds a test case which would have helped avoid the introduction of errors fixed in #7396.
1. Run `rspec spec/lib/telephony/otp_sender_spec.rb`
a. Observe success
2. In your local copy of the branch, `git revert 8c40e37`
3. Run `rspec spec/lib/telephony/otp_sender_spec.rb`
b. Observe failure

Add spec for SSML Pinpoint message validation

---

app/services/gpo_confirmation_exporter.rb
spec/services/gpo_confirmation_exporter_spec.rb

Address a flaky test introduced in #7389.
We run tests in CI with a random Timezone each time. This means sometimes the local day and UTC day are different, which was making the updated GPO exporter test fail.
This change updates `GpoConfirmationExporter` to convert dates to UTC before outputting them. This gives us consistency on tests but should not matter in prod, where the Timezone is already set to UTC.
For LG-8233

Fix flaky GPO exporter test

---

spec/lib/telephony/pinpoint/sms_sender_spec.rb

I think https://github.com/18F/identity-idp/pull/7314 introduced some mutation of the constant that can affect other tests and may not always clean it up which can lead to failed specs elsewhere ([example](https://gitlab.login.gov/lg/identity-idp/-/jobs/177055))
To reproduce the flaky test reliably, run `rspec spec/lib/telephony/pinpoint/sms_sender_spec.rb spec/lib/telephony/telephony_spec.rb --seed 8116`, which should result in:
```
Failures:
1) Telephony.phone_info with pinpoint adapter uses the pinpoint adapter
Failure/Error:
response = client.phone_number_validate(
number_validate_request: { phone_number: phone_number },
)
NoMethodError:
undefined method `phone_number_validate' for #<Pinpoint::MockClient:0x00007f94fb854e30 @config=#<struct Telephony::PinpointSmsConfiguration …
```

Fix flaky telephony pool tests

---

app/controllers/users/two_factor_authentication_controller.rb
app/services/idv/send_phone_confirmation_otp.rb
lib/telephony.rb
lib/telephony/otp_sender.rb
spec/controllers/test/telephony_controller_spec.rb
spec/controllers/users/two_factor_authentication_controller_spec.rb
spec/features/two_factor_authentication/change_factor_spec.rb
spec/lib/telephony/otp_sender_spec.rb
spec/services/idv/send_phone_confirmation_otp_spec.rb

To facilitate the usage of existing metrics/alarms, this adds metadata to `telephony.log` despite similar information being available in `events.log` currently.

Add phone metadata to telephony logging

---

app/services/proofing/lexis_nexis/ddp/proofer.rb
spec/services/proofing/lexis_nexis/ddp/proofing_spec.rb

A recent refactor of the DDP proofer failed to include this rescue. As a result exceptions are unhandled and raised to the background job and cause a background job failure.

Add exception handling back to DDP proofer

---

app/services/proofing/lexis_nexis/response.rb
spec/services/proofing/lexis_nexis/response_spec.rb

The LexisNexis response bodies may contain information that we do not wish to be logged or reported to NewRelic (such as PII).
When a JSON parse error is raised it includes the portion of the JSON that resulted in the error. This commit rescues the JSON parse errors that are raised when a LexisNexis response body is being parsed. These error messages may contain sensitive information. As a result a new JSON parse error is raised in their place with a message that does not include the JSON that caused the error.

Scrub the error message from JSON parse errors of LexisNexis response bodies

---

app/components/memorable_date_component.html.erb
config/locales/in_person_proofing/en.yml
config/locales/in_person_proofing/es.yml
config/locales/in_person_proofing/fr.yml
spec/components/memorable_date_component_spec.rb

[Lg-7766](https://cm-jira.usa.gov/browse/LG-7766)
This pr updates the hint text for the memorable date component. It updates the hint text for each of the inputs (month, day and year) by removing the reference to the hint under the label. It replaces that hint with more specific hints for each input. Also updated the label for the component so it matches other components on the form page. 

LG-7766: Update hint text and label for memorable date component

---

app/controllers/users/verify_personal_key_controller.rb
spec/controllers/users/verify_personal_key_controller_spec.rb

changelog: Internal, Attempts API, fixed event trigger bug
[LG-8212 - Ticket](https://cm-jira.usa.gov/browse/LG-8212)
Fixed a bug where `personal_key_reactivation_rate_limited` was not firing

Account Recovery Rate Limit bugfix

---

app/javascript/packages/build-sass/CHANGELOG.md
app/javascript/packages/build-sass/cli.js
app/javascript/packages/build-sass/get-error-sass-stack-paths.js
app/javascript/packages/build-sass/get-error-sass-stack-paths.spec.js

This improves Sass compilation to avoid a scenario where an error prevents Sass from being rebuilt on file changes. Previously, the watch behavior would only monitor the file in which the error occurred. However, it is quite common that the error occurs in a file different from the file which _caused_ the error. With these changes, because the causing file would be included in the stack trace, an update to that file will now trigger a rebuild.
1. Apply the diff below
2. Run `yarn build:css --watch`
3. Observe error
4. Open and save `app/assets/stylesheets/components/_alert.scss`
Before: You'd see nothing, because there wouldn't be a rebuild.
After: You'll see the error at Step 3 repeated, since it was rebuilt but the error still occurred.
Diff:
```diff
diff --git …
```

build-sass: Improve error recovery in watch mode

---

app/forms/idv/doc_pii_form.rb
spec/forms/idv/doc_pii_form_spec.rb

changelog: Internal, make zipcode non-nullable, bugfix
https://cm-jira.usa.gov/browse/LG-8061
Updated to make sure that zip codes are not nullable and added relevant spec

Make sure zip codes are not nil in user form

---

config/locales/forms/en.yml
config/locales/forms/es.yml
config/locales/forms/fr.yml

[LG-8297](https://cm-jira.usa.gov/browse/LG-8297)
Reverts the change in #7330 which revised the hint label from capitalized "Example" to lower-case "example".
Related discussion:
- https://github.com/18F/identity-idp/pull/7330#discussion_r1024338937
- https://gsa-tts.slack.com/archives/CNCGEHG1G/p1670252355858679
- Check that every hint label in the application uses "Example" upper-case (e.g. IdV phone step)
Before|After
---|---

LG-8297: Capitalize "Example" hint labels

---

config/initializers/job_configurations.rb

No relevant ticket, this is a quickfix for an error found in NewRelic for the IRS Weekly Report job
I added the Reports:: prefix in the job configurations which was causing the error. I also changed the job to run every hour temporarily so we can test that this job is working as expected rather than having to wait a whole additional week. @zachmargolis  if there is a better way to do this feel free to comment. 
Error showing in NewRelic that we needed to fix

Fixing IRS weekly report bug

---

app/jobs/reports/month_helper.rb
app/jobs/reports/total_monthly_auths_report.rb
app/services/db/monthly_sp_auth_count/total_monthly_auth_counts.rb
spec/jobs/reports/month_helper_spec.rb
spec/services/db/monthly_auth_count/total_monthly_auth_counts_spec.rb

**Why**: One giant table scan query get cancelled, smaller queries are faster and easier to re-run
- [Bug report in Slack](https://gsa-tts.slack.com/archives/C5E7EJWF7/p1670270166278619)
- [Example error in NewRelic](https://onenr.io/0LwG4L3yzR6)
Query plan before:
```
[{"QUERY PLAN"=>"Finalize GroupAggregate  (cost=44304143.18..63653937.95 rows=64085978 width=133)"},
{"QUERY PLAN"=>"  Group Key: sp_return_logs.issuer, sp_return_logs.ial, (to_char(sp_return_logs.requested_at, 'YYYYMM'::text))"},
{"QUERY PLAN"=>"  ->  Gather Merge  (cost=44304143.18..61250713.77 rows=128171956 width=133)"},
{"QUERY PLAN"=>"        Workers Planned: 2"},
{"QUERY PLAN"=>"        ->  Partial GroupAggregate  (cost=44303143.15..46455489.76 rows=64085978 width=133)"},
{"QUERY PLAN"=>"              Group Key: …
```

Split total-monthly-auths-report into separate queries by month

---

spec/config/initializers/job_configurations_spec.rb

Follow up to #7431 to have an automatic check that validates class names. This is kind of the minimal case, we could add other checks as well.
Catches the current misconfiguration:
```
Run options: include {:locations=>{"./spec/config/initializers/job_configurations_spec.rb"=>[10]}}
Randomized with seed 11193
job_configurations
has valid cron jobs (FAILED - 1)
Failures:
1) job_configurations has valid cron jobs
Failure/Error: config[:class].constantize.new
NameError:
uninitialized constant IrsWeeklySummaryReport
```

Add spec to ensure cron job classes are valid

---

app/controllers/users/two_factor_authentication_controller.rb
app/forms/otp_delivery_selection_form.rb
spec/controllers/users/two_factor_authentication_controller_spec.rb
spec/forms/otp_delivery_selection_form_spec.rb

This change helps with some metrics and observability work in https://github.com/18F/identity-devops/pull/5501 where we want to monitor the number of resends. This parameter is currently logged as a string, but we have it [documented](https://github.com/18F/identity-idp/blob/75f4be473a97af0cf4c044eb5359bfda5a078230/app/services/analytics_events.rb#L2081) as a boolean.
I don't love the form validation and flow of passing the data, so I am super open to feedback!

Convert resend parameter in OTP Delivery Selection to a boolean

---

config/application.yml.default
lib/aws/ses.rb
lib/identity_config.rb
spec/lib/aws/ses_spec.rb

This change allows configuring an optional SES [configuration set](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/SES/Client.html#send_raw_email-instance_method) for when we send email. This is to help with some of the email observability work in https://github.com/18F/identity-devops/issues/2137.

Include configurable SES configuration_set when sending email

---

app/components/language_picker_component.html.erb
app/components/language_picker_component.rb
spec/components/language_picker_component_spec.rb
spec/components/previews/language_picker_component_preview.rb
spec/features/saml/ial1_sso_spec.rb
spec/features/visitors/i18n_spec.rb

Indirectly resolves [LG-8322](https://cm-jira.usa.gov/browse/LG-8322)
Changes the logic of how the language picker generates URL to avoid using URL helpers, so that...
- We can safely retain query parameters to avoid buggy behaviors such as [LG-8322](https://cm-jira.usa.gov/browse/LG-8322) where a query parameter may be dropped when changing locales
- Performance of slow UI elements in critical paths is improved
- We can simplify the supported options of `LanguagePickerComponent` to drop `url_generator`, which was only necessary for compatibility of Lookbook component previews with route lookups
- Check that language picker works as expected when navigating from the default locale to another locale, and vice-versa
- Specs pass
- Verify there is no regression of …

Generate language picker URL by string manipulation of current URL

---

spec/features/idv/doc_auth/address_step_spec.rb
spec/features/idv/doc_auth/document_capture_step_spec.rb
spec/features/idv/doc_auth/link_sent_step_spec.rb
spec/features/idv/doc_auth/send_link_step_spec.rb
spec/features/idv/doc_auth/ssn_step_spec.rb
spec/features/idv/doc_auth/upload_step_spec.rb
spec/features/idv/doc_capture/document_capture_step_spec.rb

These tests were helpful for development to make sure steps were reachable, but now they are covered by the rest of the tests that cover the actual functionality for these steps.

Remove doc auth step specs that test that the user is on the given step

---

app/helpers/link_helper.rb
app/views/shared/_footer_lite.html.erb
spec/helpers/link_helper_spec.rb

Simplifies and optimizes the implementation of `new_window_link_to`, which had been showing as consuming some time on flamegraphs for profiling critical flows.
Side benefits:
- Simpler
- More compatible with `link_to` signature (e.g. support for `class` as an array of strings)
- Adds a space between text and accessible label ("Link(Opens in new window)" ➡️  "Link (Opens in new window)")
- Includes missing test coverage
Benchmark:
```rb
require 'benchmark/ips'
ENV['RAILS_ENV'] = 'production'
require File.expand_path('./config/environment.rb', __dir__)
class BenchmarksController < ActionController::Base
include LinkHelper
end
controller_view = BenchmarksController.new.view_context
Benchmark.ips do |x|
x.time = 10
x.warmup = 2
x.report('before') { …
```

Microoptimize new_window_link_to implementation

---

app/views/shared/_banner-lock-icon.html.erb
config/locales/shared/en.yml
config/locales/shared/es.yml
config/locales/shared/fr.yml

Revises the implementation of the "Official government website" banner to display the "Secure .gov websites use HTTPS" inline lock icon as an external asset.
The intent with these changes is to improve performance, to avoid...
- Translations of multiple strings
- Increasing page size by inlining SVG images
- Allowing for browser caching of the image
- Deferring load of image to only when the user expands "Here's how you know", which is assumed to not be a critical user behavior
For reference, newer versions of [USWDS banner guidance](https://designsystem.digital.gov/components/banner/) use `aria-labelledby` to reference the single description text "Locked padlock icon" for the image, so the combination of `title` and `desc` would not be used anyways, hence the removal of the additional …

Optimize banner to render lock icon as external asset

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_language-picker.scss
app/views/shared/_footer_lite.html.erb

Refactors the footer partial in order to...
1. Remove duplicate renderings between mobile and desktop viewports (e.g. `LanguagePickerComponent` and `new_window_link_to`, see also #7455 and #7451)
2. Simplify the markup itself to reduce size of page and browser processing
It's not expected there should be any visual effect of these changes.
- Spot check the footer

Simplify and optimize footer markup

---

app/helpers/link_helper.rb
app/javascript/packages/components/link.tsx
app/javascript/packages/components/troubleshooting-options.spec.tsx
app/javascript/packages/document-capture/components/document-capture-troubleshooting-options.spec.tsx
spec/helpers/link_helper_spec.rb

This fixes a small regression of #7455, where links which open in a new window would incorrectly display the "External" icon on a separate line, due to how Safari treats the addition of the extra space character added in #7455. This essentially reverts to the previous behavior where the link text and accessible label were combined. In testing, since the accessible label is bounded by parantheses, it does not appear to make a difference whether a space is included when the text is announced by a screen reader.
This also fixes another potential issue where certain calls to `new_window_link_to` with a block and explicitly-nil `html_options` could raise an exception, and also improves test coverage to enforce expected behavior of HTML safety for the concatenated text.
- `rspec …

Fix new_window_link_to link appearance in Safari

---

spec/controllers/idv/review_controller_spec.rb
spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
spec/controllers/users/passwords_controller_spec.rb
spec/features/multiple_emails/add_email_spec.rb
spec/features/multiple_emails/email_management_spec.rb
spec/features/multiple_emails/reset_password_spec.rb
spec/features/new_device_tracking_spec.rb
spec/features/phone/add_phone_spec.rb
spec/features/two_factor_authentication/sign_in_via_personal_key_spec.rb
spec/features/users/regenerate_personal_key_spec.rb
spec/forms/register_user_email_form_spec.rb
spec/services/account_reset/cancel_spec.rb
spec/services/account_reset/notify_user_of_request_cancellation_spec.rb
spec/services/idv/in_person/completion_survey_sender_spec.rb
spec/services/send_sign_up_email_confirmation_spec.rb
spec/services/user_alerts/alert_user_about_account_verified_spec.rb
spec/services/user_alerts/alert_user_about_new_device_spec.rb
spec/services/user_alerts/alert_user_about_password_change_spec.rb
spec/services/user_alerts/alert_user_about_personal_key_sign_in_spec.rb
spec/services/usps_in_person_proofing/enrollment_helper_spec.rb
spec/support/mailer_helper.rb

The `expect_delivered_email` helper allows tests to confirm that an email with a given subject/recipient/body was in fact sent.
Prior to this commit this method took an index as the first argument. This meant that emails had to be sent in a specific, deterministic order for tests to pass. Problems arose when a users emails could be returned in a non-deterministic order. In most cases emails should be returned in the order in which they are used to sign in. However, for users created with a factory this may not always be the case.
After reviewing the tests that use this helper it does not appear that we need to actually worry about the order in which the emails are sent for most cases. This commit changes this helper to be agnostic about the order and applies the new API.

Change the API for `expect_delivered_email` to not include an index

---

spec/features/users/sign_in_spec.rb

The sign in spec changed in this commit waits for a timer to advance. It waits exactly 1 second, which near the boundaries of the current second can lead to an edge case that leads to the following failure:
```
Failures:
1) Sign in session approaches timeout user sees warning before session times out
Failure/Error: expect(time2).to be < time1
expected: < "14 minutes and 56 seconds"
got:   "14 minutes and 56 seconds"
```
This commit modifies the sleep in this test to advance more than a second so that the assertion never runs near the boundary of the recent second.

Add a slightly longer sleep to a test that waits for a timer to advance

---

config/locales/inherited_proofing/en.yml

Small typo I noticed during a demo. Probably a bad rebase at some point.
changelog: Internal, Inherited Proofing, Text Updates

Fix typo in inherited proofing text

---

app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_phone-input.scss
app/components/one_time_code_input_component.html.erb
app/components/one_time_code_input_component.rb
config/initializers/simple_form.rb
config/locales/components/en.yml
config/locales/components/es.yml
config/locales/components/fr.yml
config/locales/forms/en.yml
config/locales/forms/es.yml
config/locales/forms/fr.yml
spec/components/one_time_code_input_component_spec.rb
spec/features/phone/add_phone_spec.rb
spec/features/two_factor_authentication/sign_in_spec.rb
spec/support/features/session_helper.rb
spec/support/matchers/accessibility.rb

[LG-8066](https://cm-jira.usa.gov/browse/LG-8066)
Adds an example hint for one-time code input fields.
(Branch temporarily merges to proposed changes in #7469. The idea would be to merge #7469 first, then rebase this against `main`)
2. Sign in to an account which has OTP or TOTP authenticator enabled
3. (If not prompted for MFA, click "Forget browsers", confirm, sign out, and repeat Step 2)
4. Observe hint example when prompted for MFA
Before|After
---|---

LG-8066: Show example hint for OTP format

---

.rubocop.yml
app/controllers/concerns/two_factor_authenticatable_methods.rb
spec/controllers/idv/in_person/usps_locations_controller_spec.rb
spec/controllers/sign_up/completions_controller_spec.rb
spec/controllers/sign_up/registrations_controller_spec.rb
spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
spec/forms/idv/doc_pii_form_spec.rb
spec/jobs/reports/sp_active_users_report_spec.rb
spec/services/db/identity/sp_active_user_counts_spec.rb
spec/services/gpo_confirmation_maker_spec.rb

Configures Rubocop to enable the [`Layout/MultilineHashKeyLineBreaks` cop](https://docs.rubocop.org/rubocop/cops_layout.html#layoutmultilinehashkeylinebreaks).
Why?
- Legibility
- Maintainability
- Consistency
Prior discussion: https://github.com/18F/identity-idp/pull/7441#discussion_r1041479775
- `bundle exec rubocop` passes

Enforce consistent hash line breaks with Rubocop

---

app/assets/stylesheets/components/_form.scss

Removes unused CSS styles.
There are no textareas in the application, so these styles are irrelevant. We can reconsider if and when they become relevant.
Benefits:
- Reduce size of main application stylesheet, which is the largest asset on the critical path
- Avoid global element CSS selectors
- Migrate toward design system and eventual removal of this file altogether

Remove unused textarea CSS styles

---

app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/variables/_app.scss
app/views/users/edit_phone/_delivery_preference_selection.html.erb
app/views/users/edit_phone/_make_default_number.html.erb
app/views/users/shared/_otp_delivery_preference_selection.html.erb
app/views/users/shared/_otp_make_default_number.html.erb

Removes global styling for `legend` elements.
Benefits:
- Reduce size of main application stylesheet, which is the largest asset on the critical path
- Avoid global element CSS selectors
- Migrate toward design system and eventual removal of this file altogether
- Consistency of radio button display, some of which are already using these styles:
- https://github.com/18F/identity-idp/blob/3a636640bce084f37b19992037c934faae9c1930/config/initializers/simple_form.rb#L52
- Spot-check phone number pages "Make default phone" and "Delivery preference" labels

Consistently render legend elements as design system labels

---

app/views/shared/_banner.html.erb

Covers [LG-5449](https://cm-jira.usa.gov/browse/LG-5449)
Updates the banner markup to conform to [latest design system guidance](https://designsystem.digital.gov/components/banner/).
Why?
* Avoid non-translated and unpronounceable texts as image text alternatives ("Dot gov", "Https")
* Avoid text alternatives for images which are redundant with accompanying text descriptions
* Keep markup in sync with design system component guidance
- Check that markup matches design system guidance
- Check accessibility of the page (automated and/or manual testing)

Improve accessibility and language of banner markup

---

app/jobs/get_usps_proofing_results_job.rb

The `GetUspsProofingResultsJob` is longer-running and should be in the long_running job queue to avoid setting off alarms.

Move GetUspsProofingResultsJob to long running job queue

---

app/controllers/users/emails_controller.rb

When a user deletes an email address, we send email notifications to all email addresses in the account (including the deleted one). This doesn't work so well when we try to send it asynchronously since the EmailAddress record is gone by the time it tries to run ([NewRelic error](https://one.newrelic.com/nr1-core/errors/overview/MTM3NjM3MHxBUE18QVBQTElDQVRJT058MTA0NDEwMDY1?account=1376370&duration=43200000&state=2d14a545-0514-4c13-62cb-6229d93eed52)).

Send email deletion emails synchronously to avoid missing record errors

---

README.md
app/services/proofing/lexis_nexis/instant_verify/verification_request.rb
config/application.yml.default
spec/fixtures/proofing/lexis_nexis/instant_verify/request.json
spec/fixtures/proofing/lexis_nexis/instant_verify/successful_response.json
spec/services/proofing/lexis_nexis/instant_verify/verification_request_spec.rb
spec/services/proofing/lexis_nexis/phone_finder/verification_request_spec.rb
spec/support/lexis_nexis_fixtures.rb
spec/support/shared_examples/lexis_nexis.rb

[LG-6801](https://cm-jira.usa.gov/browse/LG-8260)
1. Change workflow name variable to and updated string provided by LexisNexis; this updates our RDP2 API endpoint connection used for Instant Verify
2. Modify our LexisNexis Instant Verify implementation to transmit drivers license information

Replace workflow name

---

app/javascript/packages/document-capture/components/in-person-prepare-step.tsx
config/locales/in_person_proofing/en.yml
config/locales/in_person_proofing/es.yml
config/locales/in_person_proofing/fr.yml

[Lg-8384](https://cm-jira.usa.gov/browse/LG-8384)
Remove steps that describe what to do to prepare for in person proofing.
<details>
</details>
<details>
</details>
<details>
<summary>Mobile:</summary>
</details>

remove prepare steps on prepare page

---

app/javascript/packages/document-capture/components/in-person-locations.tsx

[Update screen reader implementation](https://cm-jira.usa.gov/browse/LG-8398)
If the user searches for an address on the "Select a location to verify your ID" page.....
<details>
<summary>Screen recording of a search with results returned:</summary>
https://user-images.githubusercontent.com/80347702/207958613-edb4e95e-b8c6-47af-b8a6-d0e58389cf35.mov
</details>
<details>
<summary>Screen recording of a search with no results returned:</summary>
https://user-images.githubusercontent.com/80347702/207958642-1cdbd4c3-5990-460e-a3e9-b6dd8c93a609.mov
</details>

LG-8398 Update screen reader to read headings after user searches for an address

---

Makefile

Resolves an error which occurs when running `make normalize_yaml`.
**Before:**
```
$ make normalize_yaml
find ./config/locales/telephony "./config/locales/telephony*" -type f | xargs yarn normalize-yaml --disable-smart-punctuation
find: ./config/locales/telephony*: No such file or directory
yarn run v1.22.19
```
**After:**
```
$ make normalize_yaml
find ./config/locales/telephony -type f | xargs yarn normalize-yaml --disable-smart-punctuation
yarn run v1.22.19
```

Fix "No such file" error on "make normalize_yaml"

---

app/components/validated_field_component.html.erb
app/components/validated_field_component.rb
app/javascript/packages/validated-field/validated-field-element.spec.ts
app/javascript/packages/validated-field/validated-field-element.ts
spec/components/validated_field_component_spec.rb

Follow-up to #7484
Updates `ValidatedFieldComponent` to ensure `aria-invalid` is a reliable indicator of input validity.
Essentially, this aligns the server-rendered implementation to what the JavaScript implementation was already doing by setting `aria-invalid` based on the validity of the field ([source](https://github.com/18F/identity-idp/blob/69a3016076d6c17bbac8b81b0aed5b9f32e6710d/app/javascript/packages/validated-field/validated-field-element.ts#L92)).
By doing so, it opened up the opportunity to make a small optimization to the JavaScript implementation to avoid continued updates to the element when validity state is not changing. While the logic was not substantial, it was touching the DOM, and doing so on every input event (every keystroke) …

Render ValidatedFieldComponent as aria-invalid when errors exist

---

CONTRIBUTING.md
scripts/changelog_check.rb
spec/fixtures/git_log_changelog.yml
spec/scripts/changelog_check_spec.rb

Updates contributing document to improve changelog guidance:
- Rename "Improvements" to "User-Facing Improvements" ([see related Engineering Huddle notes 2022-12-14](https://docs.google.com/document/d/1g_V2vlT79tScBKIVw7M4UXf15TrG69iUrLHE0yE1GGI/edit#heading=h.4thd69ufrhdw))
- Moves intent and audience description for changelog messages to the "Changelog Messages" section, to optimize for visibility in deeplinking
`rspec spec/scripts/changelog_check_spec.rb`

Rename "Improvements" changelog category

---

spec/features/users/sign_in_spec.rb

Rewrites parts of a sign-in spec to improve reliability. This had previously been attempted for improvement in #7466, but build failures still occur ([example](https://gitlab.login.gov/lg/identity-idp/-/jobs/230794)).
This rewrite also has a few improvements:
- Passes regardless of locale
- Passes regardless of text changes to `datetime/en.yml` string data
- ~Passes regardless of minutes being traversed~ (**Edit:** Removed in 6e5221b, see https://github.com/18F/identity-idp/pull/7512#discussion_r1052374756)
- Passes regardless of config changes to `session_timeout_in_minutes`
`rspec spec/features/users/sign_in_spec.rb:269`

Improve reliability of flakey countdown spec

---

app/javascript/packages/document-capture/components/address-search.spec.tsx
app/javascript/packs/form-steps-wait.tsx
spec/javascripts/packs/form-steps-wait-spec.js
spec/javascripts/spec_helper.js

Replaces default spec behavior of throwing on attempted `fetch` request with working polyfill.
This was originally planned for #7502, but blocked by failures in `form-steps-wait-spec.tsx`, addressed here.
The issue with the specs is that `form-steps-wait.tsx` has special handling for polyfill'd fetch, due to circumstances of real browsers handling of `XMLHttpRequest`. Since we are expecting to fully simulate the network request, we should bypass this workaround handling. (Aside: The workaround will be removed anyways as part of upcoming sunsetting of Internet Explorer support)
```
yarn test
```

Initialize JavaScript tests with polyfilled fetch

---

app/controllers/concerns/saml_idp_auth_concern.rb
app/controllers/saml_idp_controller.rb
spec/controllers/saml_idp_controller_spec.rb
spec/support/saml_auth_helper.rb

https://cm-jira.usa.gov/browse/LG-8432
Our recent updates to the SAML internal flow (see #6922) introduced an issue with our enforcement of the ForceAuthn attribute, where users would be stuck in an indefinite sign-out/sign-in loop for service providers passing ForceAuthn=true in their SAMLRequest. This update fixes that by checking whether we're at the final request which will redirect back to the service provider, and skips signing out if so. The step which the sign-out should be forced precedes that second step. This is also currently behind a feature flag that will eventually be removed once we confirm everything works as expected (covered in another JIRA).
This issue was identified as a part of the rollout of the feature flag `saml_internal_post`, first introduced in #6922 . We have …

LG-8432: SAML - Update ForceAuthn check

---

spec/features/idv/in_person_spec.rb

[LG-8388](https://cm-jira.usa.gov/browse/LG-8388)
Adds a spec to confirm that IPP is not blocked by a ThreatMetrix result of 'Reject'

LG-8388: Confirm ThreatMetrix doesn't block IPP

---

app/javascript/packages/rails-i18n-webpack-plugin/extract-keys-webpack-plugin.js
app/javascript/packages/rails-i18n-webpack-plugin/extract-keys-webpack-plugin.spec.js
app/javascript/packages/rails-i18n-webpack-plugin/rails-i18n-webpack-plugin.spec.js
app/javascript/packages/rails-i18n-webpack-plugin/spec/fixtures/production/in.js

Fixes issue where locale data scripts used the same fingerprint associated with their chunk, so if there were content-only revisions (as in #7501), it would not effectively invalidate the locale script.
The change here adds a hash based on the locale data's own content when compiling for production.
A more elegant solution would probably account for various Webpack options like [`options.output.filename`](https://webpack.js.org/configuration/output/#outputfilename) and/or [`options.output.hashFunction`](https://webpack.js.org/configuration/output/#outputhashfunction).
Test and ensure no errors occur when testing various JavaScript behaviors (notably document capture) when either compiled for development or production.
e.g.
```
NODE_ENV=production yarn build && yarn build:css
rails s
```

Add filename fingerprint to JavaScript locale data script

---

app/views/idv/setup_errors/show.html.erb
config/application.yml.default
config/locales/idv/en.yml
config/locales/idv/es.yml
config/locales/idv/fr.yml
lib/identity_config.rb
spec/views/idv/setup_errors/show.html.erb_spec.rb

changelog: User Facing Improvements, UX, ThreatMetrix failure screen content
[LG-8315: Update "Sad Face" Screen](https://cm-jira.usa.gov/browse/LG-8315)
This PR contains content changes for the ThreatMetrix failure screen (with locales)
Basic steps
<details>
</details>
<details>
</details>

Updating ThreatMetrix failure (sad face) screen content

---

Makefile

Updates `make normalize_yaml` to ignore non-yaml files.
I ran into an issue where I had a swap file for a translation file and running `make normalize_yaml` was failing with a really generic error about not being able to parse a file and then just deleting dozens of file contents. It took a long time to track down why it was failing -- this should save other people that pain.
<details>
<summary>Example of the generic error it surfaced</summary>
This is me running `make normalize_yaml` and then `git status` to show all of the files it edited (it just deleted the contents of all of the files):
```
sbachstein@Sheldons-MacBook-Pro identity-idp % make normalize_yaml
yarn normalize-yaml .rubocop.yml --disable-sort-keys --disable-smart-punctuation
yarn run v1.22.18
$ normalize-yaml .rubocop.yml …
```

Ignore non-yaml files when normalizing yamls

---

spec/features/idv/in_person_spec.rb
spec/support/features/document_capture_step_helper.rb

Resolves a flakey feature test that started failing after #7384 was merged. After that change, it was possible in certain cases for the doc auth image upload interstitial to disappear before it could be detected by capybara matchers.
This PR preserves waiting for the interstitial to disappear before proceeding, but removes the initial expectation that it be present.
```bash
bundle exec rspec spec/features/idv/in_person_spec.rb:314
```

Fix flakey in-person feature test

---

app/views/devise/passwords/new.html.erb
spec/features/multiple_emails/reset_password_spec.rb
spec/features/users/sign_in_spec.rb
spec/features/visitors/password_recovery_spec.rb
spec/support/features/personal_key_helper.rb

`simple_form_for` is helpful by automatically generating labels for inputs, but it can't properly internationalize. I'll be looking to see if other locations are affected by this and if there's a long-term fix.
<details>
</details>
<details>
</details>

Fix untranslated email input in password reset

---

app/controllers/api/irs_attempts_api_controller.rb
app/jobs/irs_attempts_events_batch_job.rb
app/jobs/job_helpers/s3_helper.rb
config/application.yml.default
spec/jobs/job_helpers/s3_helper_spec.rb

changelog: Internal, Attempts API, Events Batch work

LG-8414 Remove flag from batch job

---

app/models/profile.rb
app/models/proofing_component.rb
lib/tasks/review_profile.rake
spec/factories/profiles.rb
spec/factories/proofing_components.rb
spec/factories/users.rb
spec/lib/tasks/review_profile_spec.rb

Wrote a rake task to pass or reject a user that account is deactivated due to threatmetrix status being in review.

LG-8390 Write rake tasks to pass or reject users

---

app/controllers/idv/gpo_verify_controller.rb
app/forms/gpo_verify_form.rb
spec/controllers/idv/gpo_verify_controller_spec.rb
spec/features/idv/steps/gpo_otp_verification_step_spec.rb
spec/forms/gpo_verify_form_spec.rb
spec/support/idv_examples/gpo_otp_verification.rb

[LG-8351](https://cm-jira.usa.gov/browse/LG-8351)
Updates GPO OTP verification such that if the user failed a ThreatMetrix check _before_ verifying their OTP, their account is verified, but created in the `threatmetrix_review_pending` state.
- Verify, selecting "Reject" from the "Mock device profiling behavior" box on the SSN screen
- When prompted to verify using a phone number, select "Verify your address by mail" instead
- After you enter the GPO verification code, you should be redirected to the "sad screen" ("Please give us a call")
- You should _not_ receive the "Your identity has been verified" email

Redirect to TM sad screen after GPO verification

---

app/services/funnel/doc_auth/register_submit_step.rb

Currently `RegisterSubmitStep` potentially updates a column or two and then updates a second set of columns. This behavior doesn't seem to be required and appears to be a small, but unnecessary increase in write load on the database.
I suspect there are steps in the doc auth flow where `RegisterSubmitStep` is called multiple times quickly, so there's potential to improve this further as well.

Avoid double-update to doc_auth_logs table

---

app/controllers/openid_connect/authorization_controller.rb
app/controllers/saml_idp_controller.rb

There is a bug where users will be sent to the review screen despite decisioning being disabled, this is a short-term fix until it can be fully addressed.
[Slack thread](https://gsa-tts.slack.com/archives/C20J64X6V/p1672430569691359)

Remove ThreatMetrix review redirects

---

app/forms/gpo_verify_form.rb
spec/features/idv/steps/gpo_otp_verification_step_spec.rb

We are not intending to disable users with ThreatMetrix currently, so this removes the logic.

Remove ThreatMetrix deactivation

---

app/controllers/openid_connect/authorization_controller.rb
app/controllers/saml_idp_controller.rb
app/forms/gpo_verify_form.rb
spec/features/idv/steps/gpo_otp_verification_step_spec.rb

- Identity Verification: Remove ThreatMetrix review redirects ([#7560](https://github.com/18F/identity-idp/pull/7560))

Deploy RC 239.1 to Production

---

app/controllers/idv/gpo_verify_controller.rb
app/controllers/idv/personal_key_controller.rb
config/application.yml.default
lib/identity_config.rb
spec/controllers/idv/gpo_verify_controller_spec.rb
spec/controllers/idv/personal_key_controller_spec.rb
spec/features/idv/in_person_spec.rb
spec/features/idv/steps/gpo_otp_verification_step_spec.rb
spec/features/idv/threatmetrix_pending_spec.rb
spec/forms/gpo_verify_form_spec.rb

There were 2 feature flags for ThreatMetrix behavior that conflicted:
- `proofing_device_profiling_decisioning_enabled`: This determined whether or not a user saw the "sad face" screen
- `lexisnexis_threatmetrix_required_to_verify`: This determined whether or not a user received an active profile after successful proofing
There is no case where we want one and not the other or vice versa. Thus this commit merges them into a single `lexisnexis_threatmetrix_required_to_verify` config.

Merge duplicate TM feature flags

---

app/controllers/openid_connect/authorization_controller.rb
app/controllers/saml_idp_controller.rb

These were removed in an attempt to fix an issue where decisioning was enabled (#7560). That change actually did not address the issue. The change in #7562 addressed the issue.
This commit puts this code back.

LG-8521 Re-enable ThreatMetrix redirects

---

app/services/user_event_creator.rb
lib/tasks/review_profile.rake
spec/lib/tasks/review_profile_spec.rb

[LG-8392](https://cm-jira.usa.gov/browse/LG-8392)
When operators manually OK a user's ThreatMetrix status, send the "You verified your identity" email.

LG-8392: Email user when OK'ing their ThreatMetrix status

---

app/forms/gpo_verify_form.rb
spec/features/idv/steps/gpo_otp_verification_step_spec.rb
spec/forms/gpo_verify_form_spec.rb

When Threatmetrix is not required for verification we should not require it for verification after success GPO OTP submisison.
This commit fixes a bug where a ThreatMetrix pass was required to receive an active profile after a successful GPO code entry regardless of whether the Threatmetrix requirement was active.

LG-8520 Do not disable profile on GPO OTP verification if threatmetrix is not required to verify

---

app/services/identity_linker.rb
spec/services/identity_linker_spec.rb

~Small proposed change related to #7418  (or possibly the next PR after, where we'll to conditionally create `ServiceProviderIdentity` rows but with fewer attributes)~
Originally started as a patch to #7418, but that may not land, and I think these changes would be good regardless

Remove some indirection in IdentityLinker

---

spec/components/previews/one_time_code_input_component_preview.rb

Adds a component preview for `OneTimeCodeInputComponent`, to further reinforce its intended reusability (particularly highlighting alphanumeric vs. numeric variants).
- Go to http://localhost:3000/components/inspect/one_time_code_input/preview

Add component preview for One Time Code input

---

app/validators/form_email_validator.rb
spec/forms/password_reset_email_form_spec.rb

The `FormEmailValidator` module does not include translation helpers, and raises an exception when calling the `t` translation helper method ([NewRelic error](https://onenr.io/07wk178enjL)).
This was missed when the validation was added in #7380 because the `RegisterUserEmailForm` includes the translation helper itself, the `PasswordResetEmailForm` does not, and no test was written against it.

Fix 500 error when submitting invalid email domain in reset password form

---

app/jobs/resolution_proofing_job.rb

This arg used to be used to determine if ThreatMetrix should be used. This was in place because ThreatMetrix was only active for some service providers. A recent change made Threatmetrix active for all service providers.
This argument was left in place with a `nil` default to prevent ArgumentErrors when the workers were running old and new code during deployment. Now that the code that used this argument is not running in any deployed environment the argument can be safely removed.

Remove unused `issuer` arg from `ResolutionProofingJob`

---

Makefile
app/javascript/packages/normalize-yaml/cli.js

[LG-8489](https://cm-jira.usa.gov/browse/LG-8489)
Improves `@18f/identity-normalize-yaml` CLI to avoid deleting file contents when a parse error occurs.
See prior discussion: https://github.com/18F/identity-idp/pull/7528#issuecomment-1363220406
Changes also include:
- Refactor the CLI script logic to leverage [top-level await](https://v8.dev/features/top-level-await), now available as [stable as of Node.js v14.8+](https://nodejs.org/en/blog/release/v14.8.0/)
- Add `make normalize_yaml` to `make lintfix`, per prior discussion
1. Introduce a syntax error to a YAML file (e.g. `git cherry-pick be410b8`)
2. Run `make normalize_yaml`
3. Observe:
1. File contents are not deleted
2. Process exits with non-zero status code (confirm via `echo $?`)

LG-8489: Improve YAML normalization error tolerance

---

CONTRIBUTING.md
README.md

Per a discussion with @soniaconnolly the repo's README and CONTRIBUTING docs should link to the Login.gov handbook to allow better open-source contributions and better onboarding

Link to the handbook from README and CONTRIBUTING files

---

config/initializers/simple_form.rb

A follow up to #7537 that is intended to address the root problem of implicitly generating labels. This is in part relying on existing tests to find issues like those in #7537. I'm not sure if we want to add some defensiveness by requiring the `label:` parameter on things like `ValidatedFieldComponent`.
The secondary benefit to this is a minor performance improvement when using `simple_form_for`. `simple_form` attempts to find translations for each hint, placeholder and label it may create which results in some additional work. Preliminary testing shows a 2-3% reduction in memory allocation for `GET /`. I'm not expecting a noticeable effect in response time.

Disable automatically generating hints, placeholders and labels for simple_form

---

app/services/analytics_events.rb
lib/analytics_events_documenter.rb
spec/lib/analytics_events_documenter_spec.rb

**Why**: breaks documentation
(currently analytics doc page is broken, because something is null we're not expecting). I may also make a PR to the handbook to make it more resilient

Make sure analytics event params all have types

---

app/services/idv/steps/verify_base_step.rb
spec/features/idv/doc_auth/verify_step_spec.rb

changelog: Internal, Attempts API, Track event when timeout

LG-8185 IDV verification submitted event when timeout

---

lib/tasks/review_profile.rake
spec/lib/tasks/review_profile_spec.rb

Removed the updates to ProofingComponent in the rake task for activating or deactivating a user's profile who is under threatmetrix review.

Removed ProofingComponent updates for TMX in rake task

---

config/initializers/session_store.rb
lib/session_redis_down_error_handler.rb
spec/requests/redis_down_spec.rb

Kind of a sibling PR to #7547. This adds a handler to the Redis session store configuration to re-raise Redis connection errors. This change is intended to ensure that it is apparent to us and end users when a critical piece of the system is down.

Raise exception when session store cannot connect to Redis

---

Gemfile
Gemfile.lock
spec/components/previews/one_time_code_input_component_preview.rb

Updates Lookbook to the latest version, to be able to remove a workaround previously introduced in #7523 due to an [upstream issue](https://github.com/ViewComponent/lookbook/issues/267) related to default toggle values for component previews, which has since been fixed in v1.4.5 ([see changelog](https://github.com/ViewComponent/lookbook/releases/tag/v1.4.5)).
1. Go to http://localhost:3000/components/inspect/one_time_code_input/workbench
2. Observe that the preview shows a numeric one time code input and that the "Params" panel shows the "Numeric" toggle as checked
3. Confirm that toggling the checkbox updates the preview accordingly

Upgrade Lookbook to fix default toggle preview

---

app/services/proofing/lexis_nexis/instant_verify/check_to_attribute_mapper.rb

We started sending driver's license numbers to instant verify a while ago. We are using the check as a "warning" indicator currently. The primary purpose of this is to get visibility into how InstantVerify performs for driver's license checks.
The above change means we have a new item in the products array from the LexisNexis response to handle as a failed attribute. Currently this is labeled as an 'unkown' when processed. The change in this commit will make it visible as a failure on drivers license number and indicate that attribute requires additional verification. This will cause it to appear in our logs.

Add the drivers license number check to the LexisNexis failed attribute mapper

---

app/views/shared/_ssn_field.html.erb
app/views/sign_up/email_resend/new.html.erb
app/views/users/emails/show.html.erb

Related to [LG-5362](https://cm-jira.usa.gov/browse/LG-5362)
Updates a few text fields which still use native form validation error messaging instead of our desired custom error messaging.
**Add email:**
1. Sign in
2. From account dashboard, click "Add new email"
3. Click "Submit" without entering an email address
4. Observe design system (red highlighted) error effect
**Sign up email resend:**
1. Go to http://localhost:3000/sign_up/email/confirm?_request_id=&confirmation_token=
3. Click "Submit" without entering an email address
4. Observe design system (red highlighted) error effect
---|---|---
Add email|![Screen Shot 2023-01-06 at 8 58 54 AM](https://user-images.githubusercontent.com/1779930/211038751-0233b995-ecfe-4360-bd4a-bdf6122a36d9.png)|![Screen Shot …

Update text fields to use ValidatedFieldComponent

---

app/javascript/packages/document-capture/components/location-collection-item.spec.tsx
app/javascript/packages/document-capture/components/location-collection-item.tsx

[Lg-7767](https://cm-jira.usa.gov/browse/LG-7767)
Currently when navigating the location result page using a screen reader the select button is first read out and then the post office information. This does not give screen reader users enough information about what they are selecting. This pr makes changes to the LocationCollectionItem layout so that the post office information will be read first and then the accompanying select button. It changes the layout so that the po info and button are in separate columns in the same row so that the po info proceeds the button in the DOM tree. This is similar to how the form input review page is structured. 
To test w/o search ability: 
To test w/ search ability: 
What the updates to layout look …

Lg-7767 change location item layout to address navigation issue

---

app/services/proofing/lexis_nexis/ddp/verification_request.rb

I noticed an error in [NewRelic](https://onenr.io/0VRV5N67Wwa) where we raise an exception if `state_id_number` is nil:
```
NoMethodError: undefined method `gsub' for nil:NilClass
…vices/proofing/lexis_nexis/ddp/verification_request.rb:   23:in `build_request_body'
```
SSN has a similar operation, but I'm assuming that will always be present.

Fix unhandled exception when state_id_number attribute is missing in DDP Proofer

---

app/services/arcgis_api/geocoder.rb
app/services/usps_in_person_proofing/proofer.rb
spec/services/arcgis_api/geocoder_spec.rb
spec/services/usps_in_person_proofing/proofer_spec.rb

[LG-7918](https://cm-jira.usa.gov/browse/LG-7918)
Moves the caching of USPS API auth tokens from class variables on the UspsInPersonProofing::Proofer class to our redis cache. This allows all server instances and all Rails processes to share the same auth tokens which reduces the number of authentication requests we have to make to the USPS API (a pretty slow request).
I tested this feature branch by performing the following steps in the Joy sandbox:
```ruby
irb(main):003:0> Rails.cache.redis.ttl(:usps_auth_token)
=> 469
Rails.cache.redis.ttl(:usps_auth_token)
=> -2
proofer = UspsInPersonProofing::Proofer.new
=> #<UspsInPersonProofing::Proofer:0x00007f8d0001a880>
irb(main):010:0> proofer.request_enrollment_code('blah')
{"http_method":"POST","host":"cat-services.usps.com","path":"/oauth/aut …
```

LG-7918: Begin caching USPS auth tokens in the redis cache

---

app/views/shared/_footer_lite.html.erb
spec/helpers/go_back_helper_spec.rb

Updates GSA website links to use canonical URL in order to avoid an unnecessary redirect.
Related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1673266030524959
2. Click GSA link in the footer
3. Observe you are shown the GSA website

Update GSA links to use www subdomain

---

config/locales/in_person_proofing/fr.yml
spec/i18n_spec.rb

[Lg-8357](https://cm-jira.usa.gov/browse/LG-8357)
Update distance in fr translations to use the en translation. 
<details>
<summary>Results description before:</summary>
</details>
<details>
<summary>Results description after:</summary>
</details>
<details>
<summary>Distance before:</summary>
</details>
<details>
<summary>Distance after:</summary>
</details>

Lg-8357 Change fr distance translations to en translation

---

app/controllers/users/sessions_controller.rb
spec/controllers/users/sessions_controller_spec.rb

The Devise gem we use has some behavior where you can prefill a form via URL, this disables that behavior
Example: https://idp.mhenke.identitysandbox.gov/?user[email]=abc@abc.com
| --- | --- |
| http://localhost:3000/?user[email]=abc@abc.com&user[password]=abcdef | http://localhost:3000/?user[email]=abc@abc.com&user[password]=abcdef |
|  <img width="911" alt="Screen Shot 2023-01-11 at 10 36 51 AM" src="https://user-images.githubusercontent.com/458784/211890252-57c6ab70-5185-44ff-910f-1eebf30e6e1f.png"> | <img width="911" alt="Screen Shot 2023-01-11 at 10 36 27 AM" src="https://user-images.githubusercontent.com/458784/211890257-38437b20-b1eb-438a-8ddd-9b5f7aa8ef4e.png"> |

Remove email/password prefilling via URL

---

app/javascript/packages/step-indicator/step-indicator-step.spec.tsx
app/javascript/packages/step-indicator/step-indicator-step.tsx

[LG-7771](https://cm-jira.usa.gov/browse/LG-7771)
Add INCOMPLETE StepStatus to StepIndicatorStep custom component and set statusText to step_indicator.status.not_complete

LG-7771 Add correct screenreader tag for incomplete steps

---

app/javascript/packages/step-indicator/step-indicator-step.tsx
config/locales/step_indicator/en.yml
config/locales/step_indicator/es.yml
config/locales/step_indicator/fr.yml

Originally [LG-6307](https://cm-jira.usa.gov/browse/LG-6307)
Removes references to "Pending" status for a step indicator step. This was meant to be handled as part of #6860 / [LG-6307](https://cm-jira.usa.gov/browse/LG-6307), but a few references remained. 
See related discussion: https://github.com/18F/identity-idp/pull/7613#discussion_r1066982082
- Observe no regression in the appearance of the step indicator in the document capture step

Remove lingering references to "Pending" step indicator status

---

app/controllers/two_factor_authentication/webauthn_verification_controller.rb
app/forms/webauthn_verification_form.rb
app/javascript/packs/webauthn-authenticate.ts
app/views/two_factor_authentication/webauthn_verification/show.html.erb
spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
spec/forms/webauthn_verification_form_spec.rb

[LG-8071](https://cm-jira.usa.gov/browse/LG-8071)
Enhances WebAuthn verification to ensure that errors occurring in the front-end are logged as part of the back-end verification.
Previously, the frontend error message was being passed as part of the form submission, but was only used as part of a condition considering whether to validate the assertion response. With these changes, the error is now included in the logged error details.
This changes the specific string being logged from using the full error message to the error name, which avoids differences in error messages between browsers.
For example, a cancelled authentication...
- ...in Chrome: 
- `error.name`: `NotAllowedError`
- `error.message`: `The operation either timed out or was not allowed. See: …

LG-8071: Add logging for WebAuthn frontend error reasons

---

app/javascript/packages/time-element/index.spec.ts
app/javascript/packages/time-element/index.ts

Relates to [LG-8525](https://cm-jira.usa.gov/browse/LG-8525)
Following #7563 and #7624, removes another code snippet providing fallback behavior for Internet Explorer's lack of support for `Intl.DateTimeFormat#formatToParts`.
Related:
- https://caniuse.com/mdn-javascript_builtins_intl_datetimeformat_formattoparts
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatToParts#browser_compatibility
- `yarn test`
- Observe that time displays continue to appear as expected in the local timezone (e.g. "Connected Apps" account page)

Remove Time component IE11 fallback behavior

---

Gemfile
Gemfile.lock
Procfile
README.md
bin/setup
config/application.yml.default
config/environments/development.rb
docker-compose-production.yml
docker-compose.yml
lib/identity_config.rb

After we upgraded to Ruby 3.2 we lost support for mailcatcher. Mailcatcher depends on Fixnum was was previously deprecated and is now removed in Ruby 3.2
This commit removes mailcatcher and adds 2 new options for previewing emails:
1. Letter opener
2. File previews
This commit has letter opener as the default method with the ability to switch to the file method by changing configs in your local `application.yml`.

Retire mailcatcher

---

Gemfile
Gemfile.lock
app/components/language_picker_component.rb
app/controllers/application_controller.rb
app/controllers/users/sessions_controller.rb
app/forms/openid_connect_authorize_form.rb
app/helpers/application_helper.rb
app/helpers/link_helper.rb
app/helpers/script_helper.rb
app/models/anonymous_user.rb
app/services/browser_cache.rb
app/services/encryption/aes_cipher.rb
app/services/encryption/kms_client.rb
app/services/ial_context.rb
app/services/marketing_site.rb
app/services/openid_connect_attribute_scoper.rb
app/services/secure_headers_allow_list.rb
config/application.rb
config/i18n-tasks.yml
config/initializers/ahoy.rb
config/initializers/secure_headers.rb
lib/asset_sources.rb
lib/rack_request_parser.rb
lib/secure_cookies.rb
lib/session_encryptor.rb
lib/utf8_cleaner.rb
lib/utf8_sanitizer.rb

This PR intends to freeze strings and other values in some of the warmer paths and also enables `config.action_view.frozen_string_literal` which will freeze string literals in templates. We could do `# frozen_string_literal: true` everywhere with Rubocop, but I am hoping to start smaller since we may eventually be able to use `RUBYOPT=--enable=frozen-string-literal`
Some preliminary testing suggests this patch could reduce memory allocation by 2-3% on a `GET /` request

Freeze strings and other constants

---

app/forms/idv/phone_form.rb
app/forms/new_phone_form.rb
config/application.yml.default
lib/identity_config.rb
spec/controllers/users/phone_setup_controller_spec.rb
spec/features/phone/add_phone_spec.rb
spec/forms/new_phone_form_spec.rb

Change feature flag name per request.

LG-8529: Change feature flag name

---

spec/models/in_person_enrollment_spec.rb

Sometimes this test [fails](https://gitlab.login.gov/lg/identity-idp/-/jobs/283316) due to time drift, so this patch freezes time to prevent it reliably.
```
1) InPersonEnrollment minutes_since_established returns number of minutes since enrollment was established
Failure/Error: expect(enrollment.minutes_since_established).to be_within(0.01).of(120)
expected 120.03 to be within 0.01 of 120
```

Reduce flakiness of in-person proofing spec

---

app/views/devise/sessions/new.html.erb
spec/features/accessibility/idv_pages_spec.rb
spec/features/accessibility/static_pages_spec.rb
spec/features/accessibility/user_pages_spec.rb
spec/features/accessibility/visitor_pages_spec.rb
spec/support/matchers/accessibility.rb

Updates accessibility feature specs to check for valid ID references for `aria-describedby` and `aria-labelledby`.
Related:
- https://gsa-tts.slack.com/archives/C01C89LM6UF/p1673541645409329
- #7640
- #7484
1. Intentionally introduce errors to page HTML (e.g. `git cherry-pick 84ce1c5`)
2. `rspec ./spec/features/accessibility/visitor_pages_spec.rb:5`
3. Observe failures
Example:
```
1) Accessibility on pages that do not require authentication login / root path
Failure/Error: expect(page).to have_valid_idrefs
Found 1 elements with invalid ID reference links:
[aria-describedby="not-exists"]
```

Enhance automated accessibility tests to check idref validity

---

app/jobs/address_proofing_job.rb
app/jobs/document_proofing_job.rb
app/jobs/resolution_proofing_job.rb
config/application.rb
config/application.yml.default
config/database.yml
lib/good_job_connection_pool_size.rb
spec/lib/good_job_connection_pool_size_spec.rb

This change includes dedicated proofing queues for 3 jobs: 
1. `:high_document_proofing` - `DocumentProofingJob`
2. `:high_resolution_proofing` - `ResolutionProofingJob`
3. `:high_address_proofing` - `AddressProofingJob`
It's a simple mitigation, but it makes a small improvement that should help ensure that some users can move through the linear proofing process even when the default queue is backed up. A dedicated queue for all proofing jobs was also considered, but that could still cause issues with earlier proofing steps eventually taking over the queue and preventing users in later steps from reaching the end. We may or may not use these queues by default.
As we've added more than a couple queues, calculating the number of database connections needed for workers has gotten more …

Separate proofing job queues and dynamic worker database connection pool sizing

---

app/services/service_provider_request_handler.rb
app/services/store_sp_metadata_in_session.rb
spec/services/store_sp_metadata_in_session_spec.rb

`StoreSpMetadataInSession#call` reads the value written to Redis in `ServiceProviderRequestProxy.create!(attributes)` to put the information in the session.
I couldn't find anything that suggested this pattern was necessary since the value returned is the value that was written. To avoid the extra read, this change adds an option to pass the value directly rather than read it from Redis.

Avoid extraneous read for SpMetadataInSession after saving

---

spec/features/accessibility/user_pages_spec.rb
spec/support/matchers/accessibility.rb

Updates accessibility feature specs to check for valid HTML markup.
Related Slack discussion: https://gsa-tts.slack.com/archives/C01C89LM6UF/p1673541645409329
The implementation ended up being more difficult than I expected, due to how the existing specs run using ChromeDriver, and Chrome will try to automatically repair much of the invalid HTML we're interested in.
1. Intentionally introduce errors to page HTML (e.g. `git cherry-pick 226bee4`)
2. `rspec ./spec/features/accessibility`
3. Observe failures
Example:
```
Expected page to have valid markup. Found syntax errors:
#<Nokogiri::XML::SyntaxError:"208:17: ERROR: That tag isn't allowed here  Currently open tags: html, body.\n  <p><div></div></p>\n                ^">
#<Nokogiri::XML::SyntaxError:"209:18: ERROR: Tag contains multiple …
```

Enhance automated accessibility tests to check markup validity

---

app/services/analytics_events.rb
app/services/usps_in_person_proofing/enrollment_helper.rb
spec/services/usps_in_person_proofing/enrollment_helper_spec.rb

[Lg-7695](https://cm-jira.usa.gov/browse/LG-7695)
Analytics event added to track when usps enrollment is created. This occurs in the schedule_in_person_enrollment method of the enrollment helper. 

Lg-7695 enrollment creation event

---

config/application.yml.default
lib/feature_management.rb
lib/identity_config.rb
spec/lib/feature_management_spec.rb

This is a follow-on to #7582. Do not merge until environments have been appropriately configured.
Remove the following configuration keys:
- `lexisnexis_threatmetrix_enabled`
- `lexisnexis_threatmetrix_required_to_verify`
- `proofing_device_profiling_collecting_enabled`
- `proofing_device_profiling_decisioning_enabled` (should not be present, but just in case)
Add a new configuration key, `proofing_device_profiling`, set to one of `disabled`, `collect_only`, or `enabled`.

Fully remove references to old ThreatMetrix config flags (LG-8512)

---

app/javascript/packages/unpolyfill-webpack-plugin/README.md
app/javascript/packages/unpolyfill-webpack-plugin/object-assign.js
app/javascript/packages/unpolyfill-webpack-plugin/package.json
app/javascript/packages/unpolyfill-webpack-plugin/unpolyfill-webpack-plugin.js
scripts/validate-workspaces.js
tsconfig.json
webpack.config.js

Implements a custom Webpack plugin to strip out unnecessary polyfills.
Some of our transitive dependencies (e.g. USWDS's use of [receptor](https://github.com/shawnbot/receptor)) are prebundled with polyfills that we neither need nor want ([source](https://github.com/shawnbot/receptor/blob/de712fd134c5fb1f9c48671579245d58d3296bcd/package.json#L28-L33)). The code here uses Webpack's `NormalModuleReplacementPlugin` to swap them out with either an empty implementation or the native equivalent.
- [`Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#browser_compatibility)
- [`Element#closest`](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#browser_compatibility)
- …

Add custom Webpack plugin to unpolyfill browser features

---

app/javascript/packages/document-capture/components/review-issues-step.tsx
config/i18n-tasks.yml
spec/javascripts/packages/document-capture/components/review-issues-step-spec.jsx

Updates `ReviewIssuesStep` use of localization to use pluralization feature.
Follow-up to #7638 where upgraded `i18n-tasks` detected the direct reference to pluralized string keys as being unused.
`ReviewIssuesStep` predates the introduction of pluralization to the JavaScript implementation in #5950, hence why it was implemented the way it was.
Related Slack discussion: https://gsa-tts.slack.com/archives/C04GA9WQ85B/p1674170306847209
- `yarn mocha spec/javascripts/packages/document-capture/components/review-issues-step-spec.jsx`

Use i18n pluralization to avoid ignored string

---

Gemfile.lock

Updates version of Bundler `bundled_with` in `Gemfile.lock` to remove messages related to `DidYouMean` deprecation:
>Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
1. Run `bundle`
2. Observe no warnings

Fix warnings related to DidYouMean deprecation

---

app/services/irs_attempts_api/attempt_event.rb
app/services/irs_attempts_api/tracker.rb
spec/services/irs_attempts_api/tracker_spec.rb

This event was initially intended for development of the features related to this, but it generates a more significant amount of logs. This change reduces the scope to only the log the metadata when the data will be written to Redis to maintain some of the signal that the log provides without deleting it completely. The amount of data written is also being removed from the log.

Only log IRS Metadata event if the IRS event is being written to Redis

---

app/controllers/idv/session_errors_controller.rb
spec/features/idv/doc_auth/document_capture_step_spec.rb

[LG-6543](https://cm-jira.usa.gov/browse/LG-6543)
Throttle limit being reached for doc auth was not being logged in analytics. This PR rectifies that issue.

LG-6543 Adding doc auth rate triggered analytics call for acuant

---

app/forms/idv/api_image_upload_form.rb
spec/controllers/idv/image_uploads_controller_spec.rb
spec/forms/idv/api_image_upload_form_spec.rb

changelog: Internal, Attempts API, Event bugfix
[LG-8186](https://cm-jira.usa.gov/browse/LG-8186)
Corrected the form response used by doc_auth_submitted event.
Added missing tests to the spec for this event.

LG-8186 - Document Authorization Upload Success Bugfix

---

app/jobs/reports/daily_registrations_report.rb
config/initializers/job_configurations.rb
spec/jobs/reports/daily_registration_report_spec.rb

[LG-8679](https://cm-jira.usa.gov/browse/LG-8679)
Adds a new daily reporting job that loads all-time user registrations (both plain `User.count` and fully registered users)
~In "do not merge" while I still confirm we're OK to launch it~ **Update**: It's ready to go! 🚀

Add cumulative registrations report (LG-8679)

---

app/controllers/concerns/string_redacter.rb
app/controllers/idv/review_controller.rb
app/controllers/idv/verify_info_controller.rb
app/services/analytics_events.rb
app/services/idv/session.rb
app/services/idv/steps/ssn_step.rb
app/views/idv/verify_info/show.html.erb
config/routes.rb
spec/features/idv/doc_auth/verify_info_step_spec.rb

This is the correct set of cherry-picked commits from PR #7661. Recommend merging this one instead. Feedback from prior reviews has been addressed.
*What*
Add update functionality to VerifyInfoController outside Flow State Machine
- After submitting the info on the verify screen it is submitted to the enabled vendor(s)
- Errors from the vendor are rendered to the user
- If there are no errors the user is sent to the phone step
- Rate limiting is enforced on this step
- Async functionality included (LG-7401) because it wasn't feasible to separate it out, but LG-7401 will now be the ticket for adding the Spinner button back in.
All changes are hidden behind doc_auth_verify_info_controller_enabled IdentityConfig feature flag which is false in prod.
LG-7400
Provide a checklist of steps to …

LG-7400 Add update functionality to VerifyInfoController outside Flow State Machine (rebased)

---

app/javascript/packs/pw-strength.js

Removes code which provided fallback behavior for buggy browser behavior in Internet Explorer 9. As of LG-8525 (#7563), we no longer support Internet Explorer.
- Password strength meter continues to work as expected

Remove password strength fallback behavior for IE9

---

app/controllers/frontend_log_controller.rb
app/javascript/packages/analytics/index.spec.ts
app/javascript/packages/analytics/index.ts
app/javascript/packages/password-toggle/password-toggle-element.ts
spec/controllers/frontend_log_controller_spec.rb

Minor refactoring of a few files to simplify and optimize the size of JavaScript bundles, particularly the PasswordToggleElement implementation and its dependencies, toward a goal of reducing overall JavaScript size in critical paths (notably, the Sign In page).
For more detail, refer to individual commits for specific changes and rationale.
Reduces gzipped size of Password Toggle bundle from 933b to 558b (-40.2%).
We're starting to hit a point of diminishing returns, since even though 40.2% reduction sounds impressive, we're talking an absolute difference of about 0.4kb 😅

Micro-optimize bundle size of PasswordToggleElement

---

app/assets/stylesheets/design-system-waiting-room.scss
app/views/idv/inherited_proofing/_verify.html.erb
app/views/idv/shared/_verify.html.erb
app/views/idv/verify_info/show.html.erb

Removes a few styles and style declarations for BassCSS global styles which were left over the removal of BassCSS styles in #5944, toward eventual removal of the `design-system-waiting-room.scss` file.
These styles are redundant:
- The native bottom margin of `p`, `dl`, `ol`, and `ul` is already `1em`, which would be effectively identical to the style we were applying
- All current instances of `<ol>` and `<dl>` elements are customized such that the `margin-top` default would not be applied
- Spot check affected lists and paragraphs for potential regressions

Remove a few redundant BassCSS styles

---

app/controllers/users/sessions_controller.rb
spec/controllers/users/sessions_controller_spec.rb

Following some of the changes in #7621 and #7657, we noticed that the `password=` function can unnecessarily digest and encrypt the password, which is an expensive operation. This PR overrides the `sign_in_params` method from Devise so that we only pass the `email` parameter to avoid an unnecessary call to `password=`

Only allow email parameter in SessionsController#new

---

app/services/otp_rate_limiter.rb
app/services/throttle.rb
config/application.yml.default
lib/identity_config.rb
spec/features/event_disavowal_spec.rb
spec/features/idv/phone_otp_rate_limiting_spec.rb
spec/features/idv/threatmetrix_pending_spec.rb
spec/services/idv/steps/in_person/verify_step_spec.rb
spec/services/idv/steps/verify_step_spec.rb
spec/services/otp_rate_limiter_spec.rb
spec/services/throttle_spec.rb

changelog: Internal, Rate Limiting, Replace database phone one-time password rate limiter with Redis

Replace database phone one-time password rate limiter with Redis

---

app/controllers/idv/phone_controller.rb
app/views/idv/gpo/wait.html.erb
app/views/idv/phone/wait.html.erb

LG-8703, subtask of LG-7401
PhoneController had a duplicate of the VerifyInfo wait.html.erb file, so change to use the shared version.
app/views/idv/gpo also had a duplicate that's unused, so remove it.

LG-8703 use shared wait.html.erb, remove duplicates

---

app/services/irs_attempts_api/redis_client.rb

changelog: Internal, Attempts API, Fetch from Redis in batches
LG-8060
This story was initially for a series of changes to the background job. Ultimately, none gave a performance improvement, except that reading in batches could be slightly faster, depending on batch size.
**But**, @zachmargolis pointed out that, because Redis is single-threaded, it's much kinder to Redis to read in batches rather than one gigantic `hgetall`. That's the big win; the performance improvement is very marginal.
I initially coded this to call `hscan` inside a loop, introduced a lulzy infinite loop where we ran until `counter == 0` when `counter` was actually returned as a string, and then realized while looking at the source that `hscan_each` already did what I wanted. I have progressively whittled this down …

LG-8060 | Fetch from Redis in batches

---

config/initializers/rack_timeout.rb

Rack::Timeout logs for every request, but we'd really only be interested if there is a timeout or other issue.
Lines like the following are not all that useful:
```
source=rack-timeout id=8bb2ab5a-6a27-4468-8e77-a58af46ec06c timeout=600000ms service=29ms state=completed
source=rack-timeout id=51358686-208d-4afe-8e3b-68bdc5d2c02e timeout=600000ms state=ready
```
We'd still get logs where the request timed out:
```
source=rack-timeout id=a8b52429-8602-4f02-ad38-a609bac91ef1 timeout=1000ms service=1005ms state=timed_out
```

Change Rack::Timeout logging to Error level to reduce logging noise

---

config/locales/doc_auth/en.yml

"Your image" instead of "You image"

Fix typo in doc auth translation file

---

app/controllers/idv/verify_info_controller.rb
spec/controllers/idv/verify_info_controller_spec.rb

and redirect to ssn error page for ssn throttle on #show
Co-authored-by: Eric Gade <eric.gade@gsa.gov>
LG-8742
For new VerifyInfo controller, check whether ssn throttling or resolution throttling are in force and redirect to the correct error page if so.
Analytics get logged when the throttle is first triggered, but not on further attempts to update. This can be added if desired. The show action logs a visit before redirecting if throttled, but does not log about the redirect. Show action now redirects to different error pages depending on whether the user has triggered the ssn throttle or resolution throttle.
Added controller tests.

LG-8742 Add throttle checks for VerifyInfo#update

---

app/forms/register_user_email_form.rb
spec/forms/register_user_email_form_spec.rb

Registration emails currently ignore validation errors if the email has already been created, which is kind of confusing. This also means we may send an email if the user has not accepted the terms or to an email domain that is invalid.  This PR reorganizes the logic to _not_ send if it is invalid.
I suspect that this behavior is in part due to the more limited validation that existed when the form was initially implemented.

Do not send registration emails to invalid email addresses

---

scripts/changelog_check.rb
spec/fixtures/git_log_changelog.yml

Allows the `changelog:` prefix of the changelog entry to be detected regardless of its capitalization.
See: https://github.com/18F/identity-idp/pull/7711#issuecomment-1406656814
- Observe that the build here passes despite the capitalization of my own changelog
- `rspec spec/scripts/changelog_check_spec.rb`

Allow changelog prefix fully case-insensitive

---

config/application.yml.default

[LG-8333](https://cm-jira.usa.gov/browse/LG-8333)
changelog: Internal, In-person proofing, Hide the in-person proofing call to action from 75% of viewers and split the rest evenly between variants A and B of the CTA
- Automated test suite succeeds
- Manual verification that sessions were bucketed into all configured categories
Requires PR#7669 / LG-8274, and represents desired values for Feb 1 and later. DO NOT MERGE YET. DRAFT ONLY.

Jess/LG-8333: Configure IPP CTA throttling for nationwide launch

---

app/controllers/idv/verify_info_controller.rb
spec/controllers/idv/verify_info_controller_spec.rb
spec/support/controller_helper.rb

This is a fix for an issue that is a result of an assumption the flow state machine made. It did not allow steps to be re-entrant without using specific "actions" to ensure the state was correct.
This step adds this behavior to the new verify info controller until the actions it can trigger (i.e. change address and update SSN) can be made to work in a re-entrant manner.

Do not allow people to re-enter the verify info step once it is completed

---

app/controllers/openid_connect/authorization_controller.rb
app/models/federated_protocols/oidc.rb
app/models/federated_protocols/saml.rb
app/services/service_provider_request_handler.rb
app/services/store_sp_metadata_in_session.rb

OIDC and SAML auth are one of the hotter request paths, so we did a bit of work today to find opportunities to speed them up. This PR has two commits to implement two separate refactors. Both try to reduce duplicative work.
https://github.com/18F/identity-idp/commit/114f3d03531b60820b47044f8369e20fb4565ab6 adds a parameter to `StoreSpMetadata` to avoid querying the DB (typically ActiveRecord DB cache) for the `ServiceProvider` that has already been fetched. It also memoizes the `service_provider` method to avoid further queries in the class.
11b6cd2998e5c7e35eb7f376ce30004fc8858c2a is the bigger improvement by avoiding [apply_secure_headers_override](https://github.com/18F/identity-idp/blob/25b78167726a5aa03cd4bb2630d7f39c57cffbaa/app/controllers/concerns/secure_headers_concern.rb#L4-L11) …

Improve OIDC Authorization Performance

---

app/controllers/idv/in_person/usps_locations_controller.rb
spec/controllers/idv/in_person/usps_locations_controller_spec.rb

[LG-8776](https://cm-jira.usa.gov/browse/LG-8776)
Update the POST /verify/in_person/usps_locations endpoint so that common USPS failures result in a 422 response code to the front end instead of 500. This is to prevent appdev on-call from being paged. There are so few requests to the endpoint that a very small number of common failure types cause the on-call engineer to be paged.
We attempt to rescue common USPS errors and return a 422 for them which won't cause the on-call engineer to be paged. Other types of errors will continue to raise a 500 and cause a page. I found these types of failures when looking in the prod analytics events logs over the past 6 days:
|count|exception|status code|reason|
|----|-------|----------|--------|
|16|bad request|400|access denied/Failed to establish a …

LG-8776: Change 500 response code to 422 for expected USPS failures

---

app/controllers/idv/in_person/usps_locations_controller.rb
spec/controllers/idv/in_person/usps_locations_controller_spec.rb

- In-person proofing: Stop trigger on-call paging for expected USPS facilities failures ([#7726](https://github.com/18F/identity-idp/pull/7726))

Deploy RC 247.1 to Production

---

app/controllers/idv/verify_info_controller.rb
spec/controllers/idv/verify_info_controller_spec.rb

We recently moved this out of the flow state machine and missed this event. This commit adds it.

Log an event on the verify info update action

---

app/services/proofing/aamva/response/authentication_token_response.rb
app/services/proofing/aamva/response/security_token_response.rb
app/services/proofing/aamva/response/verification_response.rb
spec/services/proofing/aamva/response/authentication_token_response_spec.rb
spec/services/proofing/aamva/response/security_token_response_spec.rb
spec/services/proofing/aamva/response/verification_response_spec.rb

As is, if we get a non-200 back from AAMVA with a non-XML body, we blow up.
changelog: Bug Fixes, Doc auth, Handle non-200 responses from AAMVA

AAMVA: Check for http errors before parsing SOAP

---

webpack.config.js

Changes Webpack JavaScript compilation to generate only SHA512 hashes for resource, overriding [default](https://github.com/webdeveric/webpack-assets-manifest#integrityhashes) which would generate integrity for SHA256, SHA384, and SHA512.
The thinking here being that [the SRI specification requires users agents to include support for all three algorithms](https://w3c.github.io/webappsec-subresource-integrity/#hash-functions), so there should be no risk that a browser would only implement one but not other hash algorithms.
Limiting the number of algorithms could potentially allow for some marginal savings in build time by avoiding unnecessary hashing of file contents†, as well as reducing the overall size of rendered pages.
Of the three, SHA512 was chosen as being the most …

Limit subresource integrity hash to SHA512 for JavaScript compilation

---

app/jobs/get_usps_proofing_results_job.rb
spec/jobs/get_usps_proofing_results_job_spec.rb

- [LG-8739](https://cm-jira.usa.gov/browse/LG-8739)
- Send delayed emails to a separate queue in order to avoid false alarms related to queue time
- Update tests
- Also see https://github.com/18F/identity-devops/pull/5784

LG-8739: Change queue used for USPS proofing job emails to prevent queue alarm

---

app/jobs/get_usps_proofing_results_job.rb
app/services/analytics_events.rb
app/services/usps_in_person_proofing/mock/fixtures.rb
app/services/usps_in_person_proofing/mock/responses/request_unexpected_expired_proofing_results_response.json
app/services/usps_in_person_proofing/mock/responses/request_unexpected_invalid_applicant_response.json
app/services/usps_in_person_proofing/mock/responses/request_unexpected_invalid_enrollment_code_response.json
spec/jobs/get_usps_proofing_results_job_spec.rb
spec/support/usps_ipp_helper.rb

closes [LG-8738](https://cm-jira.usa.gov/browse/LG-8738) and [LG-8737](https://cm-jira.usa.gov/browse/LG-8737)
Handles three types of unexpected error responses when checking enrollment status that we've seen in non-production environments:
- an enrollment has expired after any number of days other than 30
- no matching unique ID was found
- no matching enrollment code was found
This PR catches and logs those errors.

LG-8738: Handle unexpected API responses when checking enrollment status

---

app/components/phone_input_component.js
app/components/phone_input_component.ts
app/javascript/packages/phone-input/index.spec.ts
app/javascript/packages/phone-input/index.ts
app/javascript/packs/otp-delivery-preference.js
package.json
yarn.lock

Prep work for [LG-8771](https://cm-jira.usa.gov/browse/LG-8771)
Refactors phone input component JavaScript implementation to adopt current standards:
- TypeScript
- More assumptions that element is initialized correctly
- Define element within implementation

TypeScript-ify PhoneInput element

---

app/controllers/idv/verify_info_controller.rb
app/views/idv/verify_info/show.html.erb
spec/features/idv/actions/redo_document_capture_action_spec.rb

The verify info controller is a replacement for the verify info step. When it was being built we overlooked a feature that allowed users with barcode errors to recapture an image of their document.
This commit implements that feature for the verify info controller

LG-8816 Implement the redo document capture action for the new verify info controller

---

app/services/redis_rate_limiter.rb
spec/jobs/risc_delivery_job_spec.rb
spec/services/redis_rate_limiter_spec.rb

**Why**: So that throttles/short lived things live in the same instance
**Notes**:
I confirmed that the keyspace for this is empty in prod (it's only used in RISC outgoing notifications which are not super frequent right now), so this should be a very safe migration
```
REDIS_POOL.with { |r| r.scan(0, match: 'redis-rate-limiter*') }
=> ["1152", []]
```

Switch RedisRateLimiter's redis instance

---

app/controllers/idv/gpo_verify_controller.rb
app/controllers/idv/session_errors_controller.rb
app/controllers/idv/verify_info_controller.rb
app/controllers/users/two_factor_authentication_controller.rb
app/controllers/users/verify_personal_key_controller.rb
app/forms/idv/api_document_verification_form.rb
app/forms/idv/api_image_upload_form.rb
app/forms/register_user_email_form.rb
app/services/idv/steps/doc_auth_base_step.rb
app/services/idv/steps/send_link_step.rb
app/services/idv/steps/verify_base_step.rb
app/services/request_password_reset.rb
app/services/throttle.rb
config/application.yml.default
spec/controllers/idv/gpo_verify_controller_spec.rb
spec/controllers/users/verify_personal_key_controller_spec.rb
spec/features/idv/doc_auth/send_link_step_spec.rb
spec/features/idv/doc_auth/verify_info_step_spec.rb
spec/features/visitors/password_recovery_spec.rb
spec/features/visitors/resend_email_confirmation_spec.rb
spec/features/visitors/sign_up_with_email_spec.rb
spec/forms/register_user_email_form_spec.rb
spec/services/idv/steps/in_person/verify_step_spec.rb
spec/services/idv/steps/verify_step_spec.rb
spec/services/request_password_reset_spec.rb
spec/services/throttle_spec.rb
spec/support/features/idv_helper.rb

LG-8773
Replace `Throttle#throttled_else_increment?` everywhere with a call to `increment!` followed by a call to `throttled?` to make the code and usage consistent. 
Since we are now checking if we're throttled after increment rather than before, there may be one less attempt allowed. Adjust specs to match. We can consider raising the related max_attempts config settings to keep the user experience unchanged.
@eric-gade Note that I undid your change in Idv::SessionErrorsController because the analytics and tracking were now happening twice.
Each commit has code changes with related tests, except the feature tests are at the end. Added the VerifyInfoController feature test that was pending in #7720.

LG-8773 replace Throttle#throttled_else_increment with separate calls

---

app/jobs/reports/daily_registrations_report.rb
spec/jobs/reports/daily_registration_report_spec.rb

Currently, the reports do the equivalent of a `User.count` to detect how many users were created. However, users can be deleted so that count could be inaccurate over time.
This PR attempts to use the `deleted_users` table to create a more stable number over time, by including deleted users by the date they were originally created on.
Example: I create an account Monday, but delete it on Tuesday (assuming no other users were created, etc)
- Before:  Monday's report would include me but Tuesday would have subtracted one user 
- Now: Both Monday's and Tuesday's reports would count me and the count should be consistent moving forward
**Open Question**:
- Do we want to change this? Or leave it? This changes the way we calculate total registered users, so if somebody pulled the ["total …

Include deleted users in daily registrations report

---

app/views/user_mailer/shared/_in_person_ready_to_verify.html.erb
spec/mailers/user_mailer_spec.rb

[Lg-8834](https://cm-jira.usa.gov/browse/LG-8834)
Get phone from selected_location_details so that it is included in ready to verify email
<details>
</details>
<details>
</details>

LG-8834 add phone to ready to verify email

---

app/controllers/users/phone_setup_controller.rb
app/controllers/users/phones_controller.rb
app/forms/new_phone_form.rb
spec/components/phone_input_component_spec.rb
spec/controllers/users/phone_setup_controller_spec.rb
spec/forms/new_phone_form_spec.rb
spec/views/phone_setup/index.html.erb_spec.rb
spec/views/users/phones/add.html.erb_spec.rb
spec/views/users/shared/_otp_delivery_preference_selection.html.erb_spec.rb

Extracted from #7761, related to [LG-8771](https://cm-jira.usa.gov/browse/LG-8771).
Minor revisions to `NewPhoneForm` to improve clarity and consistency of arguments, and adopt conventions of instance variable assignment.
* Change `user` from positional argument to keyword argument, so that there's not an unnecessary combination of both, and to improve the clarity of the arguments that the class is expected to receive, since it's not instinctively obvious that `user` would be the first argument of the class's constructor.
* Use `@` instead of `self.` for class instance variable assignment, since it's more conventional.
- `rspec spec/forms/new_phone_form_spec.rb`

Refactor NewPhoneForm class for clarity, consistency, conventions

---

app/services/idv/steps/send_link_step.rb
app/views/idv/doc_auth/send_link.html.erb
spec/features/idv/doc_auth/send_link_step_spec.rb
spec/services/idv/steps/send_link_step_spec.rb

If the user has a mobile number associated with their account, prefill that when showing the handoff screen for hybrid docauth.
[LG-8577](https://cm-jira.usa.gov/browse/LG-8577)
If the user has a phone number associated with their account (from 2fa), use that to prefill the phone number field on the doc auth hybrid handoff screen.

LG-8577: Prefill user's mobile number for hybrid docauth

---

.irbrc

Got nerd-sniped by @tomas-nava [in Slack](https://gsa-tts.slack.com/archives/C0NGESUN5/p1675464934659899)
Verified by creating this file on an int box and loading the console
```bash
sudo echo "IRB.conf[:USE_AUTOCOMPLETE] = false" > /srv/idp/current/.irbrc
sudo chmod +r /srv/idp/current/.irbrc
id-rails-console
```

Add .irbrc, disable autocomplete

---

spec/services/encryption/aes_cipher_spec.rb
spec/services/frontend_logger_spec.rb
spec/services/idv/analytics_events_enhancer_spec.rb

Fix two services tests that failed when the whole services test suite was run locally
- Fix aes_cipher_spec name dependence on SSL library version
- Fix classname collision between frontend_logger_spec and analytics_events_ enhancer_spec

Fix service tests

---

docs/frontend.md

The example file doesn't exist anymore so the command wasn't copy-pasteable. But now it is!

Update frontend.md docs to point to a file that still exists

---

app/mailers/user_mailer.rb
app/services/request_password_reset.rb
app/views/devise/passwords/edit.html.erb
app/views/user_mailer/reset_password_instructions.html.erb
spec/features/irs_attempts_api/event_tracking_spec.rb
spec/mailers/previews/user_mailer_preview.rb
spec/support/features/session_helper.rb

changelog: Internal, Attempts API, Passing request_id in the forget password email link

LG-8232 Update Event: IDV forget password email confirmed

---

app/services/usps_in_person_proofing/mock/fixtures.rb
app/services/usps_in_person_proofing/mock/responses/request_facilities_response_with_duplicates.json
app/services/usps_in_person_proofing/proofer.rb
spec/services/usps_in_person_proofing/proofer_spec.rb
spec/support/usps_ipp_helper.rb

[Deduplicate Post Offices with the same street address for display](https://cm-jira.usa.gov/browse/LG-8510)
Previously, if the USPS API returned the same post office multiple times, our search feature would display duplicate post offices.  This bug was obvious when the user searched for `3775 INDUSTRIAL BLVD WEST SACRAMENTO CA 95799`.
Now, our search feature will only return each post office one time.
<details>
https://user-images.githubusercontent.com/80347702/217022796-b532e8f5-6710-4b0e-8b77-d1b619138945.mov
</details>
<details>
https://user-images.githubusercontent.com/80347702/217023635-ca7ee9d3-53d5-470b-9ece-1ac …

LG-8510: Don't display the same post office multiple times

---

app/jobs/reports/daily_dropoffs_report.rb
spec/jobs/reports/daily_dropoffs_report_spec.rb

Resolves LG-8794
I think I was counting this wrong - this is in line with how we're handling the other submit steps. Once this is merged and deployed I'll backfill the data again and then we'll want to invalidate the CloudFront cache.
```ruby
(Date.new(2020, 9, 28)..Date.yesterday).each { |date| Reports::DailyDropoffsReport.perform_later(date) }
```

[LG-8794] Actually count phone_submit correctly in daily_dropoffs_report

---

config/application.yml.default

changelog: Internal, Attempts Api, Bugfix
[LG-8705](https://cm-jira.usa.gov/browse/LG-8705)
lower max_bad_passwords for the session_controller to a value that is under the Rack Attack value so that Attempts Api login_rate_limited event is properly logged before a Rack Attack.
This should also make security a bit more strict, and Rack Attack will still be in place to catch attackers if the session_controller rate limit is bypassed.

Lower max_bad_passwords

---

app/components/base_component.rb
spec/components/base_component_spec.rb

Extracted from #7761, related to [LG-8771](https://cm-jira.usa.gov/browse/LG-8771).
Revises behavior of base script component to add scripts for the current class implementation, as well as any parent class scripts if the current component is subclassing another.
Essentially, given the following:
```
/components/parent_class_component.rb
/components/parent_class_component.ts
/components/child_class_component.rb
/components/child_class_component.ts
```
**Before:** When rendering `ChildClassComponent`, only `child_class_component.ts` would be added to the page
**After:** Both `child_class_component.ts` and `parent_class_component.ts` would be added to the page
Note that this seemed like an "obvious" behavior to me on Friday, though I'm of a less-strong opinion today, so happy to hear any …

View Components: Recursively add scripts for subclass's parent component

---

app/javascript/packages/document-capture/components/document-capture.tsx
app/javascript/packages/form-steps/form-steps.tsx

Issue: page titles did not match the H1s on the following pages: 
- verify/doc_auth/document_capture
- verify/doc_auth/document_capture#location
- verify/doc_auth/document_capture#prepare
Fix: 
- `title` value added to `inPersonSteps` constant
- `titleFormat` string provided in props to `FormSteps` component

LG 8683 Match document title to H1

---

.gitignore
.irbrc

~Updates the `.irbrc` configuration added in #7770 to avoid `irb` saving history, which is [the default behavior](https://docs.ruby-lang.org/en/master/IRB.html#module-IRB-label-History).~ Saving history is not gitignore'd, so could be accidentally committed, and risks the chance that history contains sensitive information. Alternatively, we could gitignore, though I'm not sure that having history provides much value anyways.
**Edit:** Per discussion at https://github.com/18F/identity-idp/pull/7783#discussion_r1098765287, we're keeping the default history behavior, but adding the history file to `.gitignore` (the "alternatively" option mentioned above).
- Run `irb`
- Enter a command (e.g. `1+1`)
- Observe no `.irb_history` file in project root directory

Add IRB history file to gitignore

---

config/application.rb
spec/requests/openid_connect_cors_spec.rb

I noticed when working on https://github.com/18F/identity-idp/pull/7785, that internal requests were not being skipped as intended, and it seems to be due to the request source including protocol AND domain, and us only comparing it against the domain. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin) has a fuller explanation, but the format and a few examples are:
```
Origin: null
Origin: <scheme>://<hostname>
Origin: <scheme>://<hostname>:<port>
Origin: https://developer.mozilla.org
```
On secure.login.gov, `IdentityConfig.store.domain_name` returns `secure.login.gov`, and I pulled the request headers:
```
Origin: https://secure.login.gov
```
which will never match 🙂
This PR adds `https://` so that we skip the remaining checks as intended.

Include protocol when checking internal domain for cross-origin resource sharing

---

app/controllers/idv/verify_info_controller.rb

Delete :pii_from_doc (unsupervised proofing) as well as :pii_from_user (in person proofing)
It doesn't look like this is having any negative effects, but we were deleting the wrong session attribute when deleting pii after editing the SSN on the Verify step.

Fix VerifyInfoController#delete_pii

---

config/application.rb

This PR lifts the calculation of protocols/domains to store them in the cache rather than storing the redirect URIs themselves and re-calculating on each CORS request.

Pre-calculate CORS domains in cache rather than calculating every time

---

app/controllers/idv/review_controller.rb
spec/controllers/idv/review_controller_spec.rb

Currently we have some code in place to check that a user has completed the verify step in the review controller. This code supports us when both the FSM verify step and the new verify step are in place. It will be removed in this change request: https://github.com/18F/identity-idp/pull/7747
After deploying the IDP with the feature flag enabled we discovered a bug in this code. This code calls `idv_session` in a before action that is added prior to adding the `IdvSession` concern.
The `IdvSessnion` concern adds a before action to confirm the user is authenticated. This concern includes a before action to confirm the user is authenticated since calling `idv_session` with no user session results in a `NoMethodError`. Having the `confirm_verify_info_complete` prior to that before action is …

Check if a user is authenticated before checking whether they have completed the verify info step

---

app/presenters/openid_connect_user_info_presenter.rb
spec/features/openid_connect/openid_connect_spec.rb

PR #7721 created a problem for a partner (https://gsa-tts.slack.com/archives/C01SU3NB9T3/p1675804144125749) so this will revert the changes made so we can review and decide the best path to implement the changes without causing problems for existing partners.

Don’t show ial and aal for now, but leave everything else

---

app/controllers/idv/verify_info_controller.rb
spec/controllers/idv/verify_info_controller_spec.rb

@zachmargolis pointed out that DocAuthLog needs to be updated in controllers that are extracted from the Flow State Machine. Add the calls and tests to VerifyInfoController.

Update DocAuthLog on VerifyInfo show and update

---

config/application.rb
lib/identity_cors.rb
spec/lib/identity_cors_spec.rb
spec/requests/api_cors_spec.rb

As a followup to #7785 and #7786, a [comment](https://github.com/18F/identity-idp/pull/7785#discussion_r1098987881) to consider consolidating some of the logic out of `config/application.rb` and into a dedicated class. This PR intends to do just that.

Refactor CORS origin logic into class

---

app/controllers/reactivate_account_controller.rb
app/models/user.rb
app/presenters/account_show_presenter.rb
app/views/partials/personal_key/_key.html.erb
app/views/reactivate_account/index.html.erb
app/views/shared/_personal_key.html.erb
spec/models/user_spec.rb
spec/views/partials/personal_key/_key.html.erb_spec.rb
spec/views/reactivate_account/index.html.erb_spec.rb

[LG-8653](https://cm-jira.usa.gov/browse/LG-8653)
This change adds the date the user's personal key was generated to the page "Reactivate your account".
It's worth noting that a number of other pages will only show today's date instead of the exact generation date, including:
- /views/idv/personal_key/show.html.erb
- /views/users/personal_keys/show.html.erb
- /views/users/verify_personal_key/new.html.erb
- /views/shared/_personal_key.html.erb
1. Create new account
2. Verify identity at /verify
3. Log out
4. Reset your password via forgot password
5. Log in and click "Reactivate your profile now"
6. Notice there is now a date displayed

LG-8653: Add personal key generation date to "reactivate your account" page

---

app/services/service_provider_seeder.rb
config/service_providers.localdev.yml
spec/services/service_provider_seeder_spec.rb

Resolves LG-6146
Precursor to #7764 to avoid breaking things, should be safe to merge/deploy before the YAML files change.

[LG-6146] Prepare for removing ERB from service_providers.yml

---

app/javascript/packages/document-capture/components/in-person-call-to-action.tsx
app/javascript/packages/document-capture/components/review-issues-step.tsx
config/locales/in_person_proofing/en.yml
config/locales/in_person_proofing/es.yml
config/locales/in_person_proofing/fr.yml

With the advent of the nationwide launch, the default state of the IPP CTA has changed. The previous language referring to D.C. and Baltimore only P.O. locations is irrelevant. So this is a minor change to make the default language that of CTA version A. 
Since the changes to the frontend have already been made, there shouldn't be any changes to the text displayed.

LG-8783 Update IPP CTA with nationwide language on barcode attention error page

---

app/controllers/idv/otp_verification_controller.rb
spec/controllers/idv/otp_verification_controller_spec.rb

LG-8188 Fix double failure reason on idv otp event

---

app/services/analytics_events.rb

[LG-8575](https://cm-jira.usa.gov/browse/LG-8575)
Code comments to clarify analytics events related to hybrid handoff. The comments memorialize things I learned while building the [hybrid handoff dashboard](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#dashboards:name=js-idv-hybrid-handoff) in AWS.

Comment hybrid handoff analytics events

---

scripts/changelog_check.rb
spec/fixtures/git_log_changelog.yml
spec/scripts/changelog_check_spec.rb

Auto-generates commit messages for code reverts, to avoid delays in emergency action for reverts due to changelog restrictions, and to standardize changelogs.
~**Draft:** As I was opening pull request, it occurred to me that squashed pull requests for pull requests which are not strictly intended as a revert can include the line "This reverts commit X" but which should not have their changelog auto-generated as a revert.~ ~**Edit:** Updated in 6b763e2 to search for revert message as fallback to other candidate changelog. This could still technically allow pull requests which include reverts but which should have a dedicated changelog. Another option may be to consider whether the title explicitly starts with "Revert".~ **Edit:** Further updated in a8bf15232 to search revert commits only …

Auto-generate changelog messages for revert

---

lib/tasks/rotate.rake
spec/factories/auth_app_configurations.rb
spec/lib/tasks/rotate_rake_spec.rb

While working on #7800, I noticed that we have some encrypted attributes that were not handled by the existing script. I also added a small script to rotate email fingerprints as well.

Add missing encrypted attributes to encryption key rotation script, and add fingerprinter key rotation script

---

app/models/backup_code_configuration.rb
app/services/pii/cacher.rb
spec/services/pii/cacher_spec.rb

We currently check some fingerprints and encrypted attributes in the `Pii::Cacher` class to see if they need to be rotated. We should be able to rely on https://github.com/18F/identity-idp/blob/71259342275df5f565ca6b1a1a3dda5baf9222a4/lib/tasks/rotate.rake#L7-L28 for rotating encrypted attributes in a complete manner.

Only proactively rotate PII fingerprints when PII is decrypted

---

app/services/recaptcha_validator.rb
spec/services/recaptcha_validator_spec.rb

Related to [LG-8771](https://cm-jira.usa.gov/browse/LG-8771)
Updates reCAPTCHA validator to consider an unsuccessful reCAPTCHA response as a failure by default, with exceptions. In #7761, it was wrongly assumed that an unsuccessful result should only occur due to misconfiguration or other invalid logic in our implementation. However, there are other [error codes](https://developers.google.com/recaptcha/docs/verify#error_code_reference) which could be triggered based on user input which we would want to consider as a failure.
Note: This feature is currently disabled in deployed environments, so the enforcement logic would not apply anyways.
- `rspec spec/services/recaptcha_validator_spec.rb`

Treat unsuccessful reCAPTCHA as failure, with exceptions

---

.codeclimate.yml

Removes FIXME enforcement from CodeClimate configuration, which currently prevents developers from adding terms like "TODO" in code.
While TODO comments should be generally avoided, there may be some sequential chain of pull requests where it's necessary, and the restriction could cause a developer to resort to unconventional synonyms in place of standard "TODO" terminology, thus creating a scenario where that code is even harder to track down than if it had been allowed as "TODO" in the first place.
This can also serve as an incremental step away from CodeClimate toward GitLab as the centralized CI platform.

Disable "FIXME" enforcement in CodeClimate config

---

app/services/arcgis_api/geocoder.rb
config/application.yml.default
lib/identity_config.rb

Adds a configurable timeout for HTTP requests to the ArcGIS API with a default of 5 seconds.

Add configurable request timeout for requests to ArcGIS API

---

config/application.yml.default

Updates default configuration to exempt U.S. territories from reCAPTCHA challenges. Since reCAPTCHA is currently intended to apply only for international numbers, allow phones from U.S. territories to pass unchallenged.
1. Create a new reCAPTCHA site for use in your local environment: https://www.google.com/recaptcha/admin/create
2. Assign credentials as `recaptcha_site_key` and `recaptcha_secret_key` in `config/application.yml`
3. Set `phone_setup_recaptcha_score_threshold` to `1.0` in `config/application.yml`
4. Sign in
5. Add new phone number
6. Enter phone number `7875550100`
7. Click "Continue"
8. Observe that you do not see any errors

Include U.S. territories in default reCAPTCHA exempt countries

---

app/controllers/idv/phone_errors_controller.rb
app/controllers/idv/session_errors_controller.rb
app/javascript/packs/form-steps-wait.tsx
app/services/analytics_events.rb
spec/controllers/idv/phone_errors_controller_spec.rb
spec/controllers/idv/session_errors_controller_spec.rb

[LG-8760](https://cm-jira.usa.gov/browse/LG-8760)
This PR adds event logging to `Idv::SessionErrorsController` and one action of `Idv::PhoneErrorsController`. It also augments the associated controller spec to do more checking for logging / lack-of-logging of events.
During testing, we encountered an issue where two "visited" events would be logged: the first due to [a `fetch()` request made by the form-steps-wait JS](https://github.com/18F/identity-idp/blob/main/app/javascript/packs/form-steps-wait.tsx#L203) and the second made when the user was then sent to the error page [via JS](https://github.com/18F/identity-idp/blob/main/app/javascript/packs/form-steps-wait.tsx#L144).
A long-term fix for that will involve reworking IdV and the form-steps infra to use JSON-based API endpoints (see …

LG-8760: Log events for visiting various IdV error routes

---

app/controllers/idv/gpo_controller.rb
app/controllers/idv/phone_controller.rb
app/services/analytics.rb
app/services/funnel/doc_auth/register_step_from_analytics_submit_event.rb
spec/controllers/idv/gpo_controller_spec.rb
spec/controllers/idv/phone_controller_spec.rb

This reverts commit 1af92c522b930f38700362ef9144b1aedc2565d1 (#7685)
changelog: Internal, Reporting, Revert analytics event refactor
After some digging
- the data.login.gov proofing funnel discrepancies started with the the deploy of the reverted code [(slack thread)](https://gsa-tts.slack.com/archives/C5E7EJWF7/p1675365972982239)
- the code changes how the Phone Submit step event was logged to doc_auth_logs, which was the first 3 subsequent events that started to have off numbers
Next steps:
- take a look at the doc auth logs reports after this is deployed
- if no change: revert it back (because the refactor gets the codebase to a better spot, and it didn't affect reporting)
- if there is a change: try to understand why the refactor wasn't successful

Revert "Remove event-specific hooks in Analytics class"

---

app/controllers/concerns/recaptcha_concern.rb
app/controllers/users/phone_setup_controller.rb
app/controllers/users/phones_controller.rb
spec/controllers/concerns/recaptcha_concern_spec.rb
spec/controllers/users/phone_setup_controller_spec.rb
spec/controllers/users/phones_controller_spec.rb

Refactors reCAPTCHA Content-Security-Policy behaviors to have controllers explicitly responsible for invoking `before_action` to modify headers, rather than overriding the `recaptcha_enabled?` method. The hope is that the explicitness makes it more clear both the association to the concern and the responsibility of the controller to control the behavior based on feature flags.
1. Create a new reCAPTCHA site for use in your local environment: https://www.google.com/recaptcha/admin/create
2. In `config/application.yml`:
1. Assign credentials as `recaptcha_site_key` and `recaptcha_secret_key`
2. Set `phone_setup_recaptcha_score_threshold` to a number between `0.0` and `1.0`
3. Sign in
4. Add a phone
5. Observe no errors about CSP in developer tools console

Call reCAPTCHA CSP before_action explicitly in controller

---

app/controllers/concerns/idv_session.rb
app/controllers/concerns/idv_step_concern.rb
app/controllers/idv/phone_controller.rb
app/controllers/idv/review_controller.rb
app/controllers/idv/verify_info_controller.rb
spec/controllers/concerns/idv_step_concern_spec.rb
spec/controllers/idv/phone_controller_spec.rb
spec/controllers/idv/review_controller_spec.rb
spec/support/controller_helper.rb

Prior to the introduction of the flow state machine, the "applicant" value in the IdV session was created when the proofing process was started. After the introduction of the FSM the applicant was created once the FSM flow was complete.
The IdvStepConcern is intended to route users to the correct step based on the state of proofing. Currently it is empty because the Flow State Machine primarily handles this logic. There is a desire to re-introduce the logic to route users to the correct step to this concern.
The IdvStepConcern has a before action to verify that proofing has started. It does that by checking for the applicant which, as described above, does not make sense in the post-FSM world. This commit removes that before action and adds it explicitly to controllers that require an …

Refactor the IdV step concern to no longer check for an applicant

---

app/javascript/packages/phone-input/index.ts
app/javascript/packages/phone-input/package.json
package.json
spec/features/phone/add_phone_spec.rb
yarn.lock

Related to ongoing reCAPTCHA efforts, e.g. [LG-8771](https://cm-jira.usa.gov/browse/LG-8771)
This pull request aims to resolve an issue where the selected country associated with an entered phone number would not be preserved if the submission yielded errors, such as when trying to add a phone number already associated with an account.
This would prove problematic for reCAPTCHA efforts, where the phone number submission relies on the selected country to determine whether an exemption would apply.
1. Sign in
2. Click "Add a phone number"
3. Enter a phone number already associated with the account
4. Click "Continue"
**Before:** Country flag in phone input would show as grey box.
**After:** Selected country is maintained.
Before|After
---|---

Retain country code in phone initialization

---

app/views/idv/come_back_later/show.html.erb
config/locales/idv/en.yml
config/locales/idv/es.yml
config/locales/idv/fr.yml

[LG-8899](https://cm-jira.usa.gov/browse/LG-8899)
Add alt text to the big graphic in the header on this screen:

LG-8899: Add alt text to GPO header image

---

app/assets/stylesheets/components/_phone-input.scss

[LG-8790](https://cm-jira.usa.gov/browse/LG-8790)
Darkens the text used for the country code number in the phone input country dropdown menu, to improve legibility and consequently accessibility.
- Go to http://localhost:3000/components/inspect/phone_input/preview
- Click flag in phone input to expand
- Observe darker text for country code ([compare to current](https://idp.dev.identitysandbox.gov/components/inspect/phone_input/preview))
Before|After
---|---

LG-8790: Improve contrast of phone input country code

---

app/controllers/concerns/idv/step_utilities_concern.rb
app/controllers/idv/ssn_controller.rb
app/services/idv/session.rb
app/views/idv/verify_info/show.html.erb
spec/features/idv/doc_auth/verify_info_step_spec.rb

LG-8734
Behind the feature flag for the new SsnController, use a direct link to update the SSN on the Verify Info page, rather than a button that looks like a link. This gets rid of a trailing `?` on the url in the browser address bar.
Also added small whitespace changes and renamed `IdvSession#ssn_updated!` to `invalidate_steps_after_ssn!` per feedback from @zachmargolis on #7810 that I saw after merging it.
Note: Once we get rid of the feature flag, a couple more tests will need to change click_button to click_link for ssn update on  the VerifyInfo view.
<details>
</details>

LG-8734 direct link to update ssn from VerifyInfoController when using new SsnController

---

app/assets/stylesheets/components/_recaptcha-badge.scss
app/assets/stylesheets/components/all.scss
app/views/shared/_recaptcha_disclosure.html.erb
app/views/users/phone_setup/index.html.erb
app/views/users/phones/add.html.erb
config/locales/two_factor_authentication/en.yml
config/locales/two_factor_authentication/es.yml
config/locales/two_factor_authentication/fr.yml

https://cm-jira.usa.gov/browse/LG-8796
This adds to the bottom of the screen a recaptcha disclosure letting the user know that this page/site has recaptcha enabled. 
What it would look life after change.

LG-8796: Add recaptcha disclosure form at bottom of phone setup screen for new and existing accounts

---

app/services/user_event_creator.rb

A rather small optimization, but we currently will make a database query for NULL cookie_uuid values when we don't need to since we disallow NULL values in that column. This PR skips the query if `cookie_uuid` is null.
```SQL
SELECT "devices"."id", "devices"."user_id", "devices"."cookie_uuid", "devices"."user_agent", "devices"."last_used_at", "devices"."last_ip", "devices"."created_at", "devices"."updated_at" FROM "devices"
WHERE "devices"."user_id" = $? AND "devices"."cookie_uuid" IS NULL
LIMIT $?
```

Skip devices database query when identifier is null

---

spec/features/users/sign_in_spec.rb

The test was flaky and the flag is unused, per Andrew Duthie.

Removed analytics check from password visibility toggle spec.

---

spec/factories/users.rb

We suspect that using Faker email, rather than explicitly setting sequential emails, was occasionally creating collisions and leading to flaky test failures.

Removed use of Faker email creation in user factory primary email

---

app/controllers/idv/review_controller.rb
app/controllers/sign_up/completions_controller.rb
spec/controllers/idv/review_controller_spec.rb
spec/controllers/sign_up/completions_controller_spec.rb

changelog: Internal, Attempts API, Update in tracking event

LG-8215 Update Event: IDV Reproof using Address verify by Mail

---

app/controllers/api/irs_attempts_api_controller.rb
config/application.yml.default
lib/identity_config.rb
spec/controllers/api/irs_attempts_api_controller_spec.rb

changelog: Internal, Attempts API, Scalability Optimization
Link to the relevant ticket. [LG-8604](https://cm-jira.usa.gov/browse/LG-8604)
WIP at the moment. Code seems to work locally when config is changed to point to an s3 repository with dummy data. Still trying to figure out how the unit test needs to change to reflect the changes in the controller though.
Changed the attempts api controller so that it streams data through a buffer instead of retrieving it all at once. This optimization should allow us to scale to larger files, as the whole file doesn't need to be loaded into memory at once, and also should be faster to retrieve on the user's end, since we will send over the stream immediately rather than waiting for a file to be downloaded entirely before sending it.

LG-8604 - Optimize s3 by streaming data w/ feature flag

---

app/controllers/idv/gpo_controller.rb
app/controllers/idv/phone_controller.rb
app/controllers/idv/review_controller.rb
app/services/funnel/doc_auth/register_step_from_analytics_submit_event.rb
app/services/funnel/doc_auth/register_step_from_analytics_view_event.rb
spec/controllers/idv/gpo_controller_spec.rb
spec/controllers/idv/phone_controller_spec.rb
spec/controllers/idv/review_controller_spec.rb
spec/support/analytics_helper.rb
spec/support/fake_analytics.rb

This is a redo of #7833, but first:
1. Adds tests ahead of time
2. Finds 4 new callsites that were missing analytics hookds
- Before, only two "submit" events in [`register_step_from_analytics_submit_event.rb`](https://github.com/18F/identity-idp/blob/f226bddb2477ef19c2b04ccd32f056c3a5a57dad/app/services/funnel/doc_auth/register_step_from_analytics_submit_event.rb) were included
- Now, 4 more that I missed in a second file [`register_step_from_analytics_view_event.rb`](https://github.com/18F/identity-idp/blob/f226bddb2477ef19c2b04ccd32f056c3a5a57dad/app/services/funnel/doc_auth/register_step_from_analytics_view_event.rb) are included too
3. In terms of the database, this should be a no-op in production, it does not touch anything, but it adds `Rails.logger.info` logging we can check to …

Add logging ahead of removing Analytics logic

---

app/controllers/concerns/two_factor_authenticatable_methods.rb
app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
app/presenters/two_factor_auth_code/generic_delivery_presenter.rb
app/presenters/two_factor_auth_code/phone_delivery_presenter.rb
spec/presenters/two_factor_auth_code/phone_delivery_presenter_spec.rb

The authenticator presenter classes are a little difficult to track, with unstructured data being passed in and converted to instance variables. Long-term, we may want to consider making these structures and methods more explicit, but for now this PR removes the unused data.

Remove unused Authentication Presenter data 

---

app/services/idv/steps/document_capture_step.rb
app/services/idv/steps/link_sent_step.rb
spec/features/idv/hybrid_flow_spec.rb

LG-9025
From the DocumentCaptureStep, we only want to redirect to the new SsnController if we are in the DocAuthFlow. This step is reused from the Hybrid Flow, and we don't want to go to the SsnController on mobile. In hybrid flow, we don't return to the DocumentCaptureStep, so redirect to SsnController from LinkSentStep when the feature flag is true as well.
Duplicate the hybrid flow test with doc_auth_ssn_controller_enabled flag set to true and make sure it passes. Note that on my machine even on main without the feature flag I have to set a binding.pry and delay the mobile browser part of the test to get it to pass.

LG-9025 Go to new SsnController from hybrid flow when feature flag is set

---

app/controllers/idv/ssn_controller.rb
spec/controllers/idv/ssn_controller_spec.rb

This commit removes the 404 from the SSN controller. After this change users can use either the old path or the new path for entering their SSN. This enables continuity in the 50/50 state during deploys.

LG-8910 Remove the 404 from the SSN controller

---

.rubocop.yml
app/controllers/concerns/two_factor_authenticatable_methods.rb
app/services/analytics_events.rb
app/services/irs_attempts_api/tracker_events.rb

There was an old PR that looks like it intended to remove this rule (ref: https://github.com/18F/identity-idp/pull/5135). It eneded up just moving it.
We have a number of modules that are over this length and I don't think it makes sense to enforce on modules and not other files.

Remove the ModuleLength rubocop rule

---

app/services/phone_formatter.rb
spec/features/phone/add_phone_spec.rb
spec/forms/new_phone_form_spec.rb
spec/services/phone_formatter_spec.rb

This aims to resolve a set of compounding issues I noticed while testing #7823:
- The default behavior of PhoneFormatter to use U.S. parsing can negate any default parsing `Phonelib` would be able to accomplish, and subsequently strip formatting for those non-U.S. numbers
- Examples:
- Before: `Phonelib.parse('+13065550100', 'US').international == '+13065550100'`
- After: `Phonelib.parse('+13065550100').international == '+1 306 555 0100'`
- When adding a phone, the `NewPhoneForm` [provides](https://github.com/18F/identity-idp/blob/e28310c64d5589a4691de917d51bbc4fa5e1cd80/app/forms/new_phone_form.rb#L78) `country_code` in the initial entry of a phone number, but the `OtpDeliverySelectionForm` [does not](https://github.com/18F/identity-idp/blob/e28310c64d5589a4691de917d51bbc4fa5e1cd80/app/fo …

Avoid defaulting to U.S. for phone formatter

---

app/controllers/concerns/two_factor_authenticatable_methods.rb
spec/presenters/two_factor_auth_code/phone_delivery_presenter_spec.rb

[LG-9037: Unconfirmed Phone fix](https://cm-jira.usa.gov/browse/LG-9037)

LG-9037: Unconfirmed Phone fix

---

app/controllers/concerns/two_factor_authenticatable_methods.rb
spec/presenters/two_factor_auth_code/phone_delivery_presenter_spec.rb

Removes unused methods `TwoFactorAuthenticatableMethods#voice_otp_delivery_unsupported?` and `TwoFactorAuthenticatableMethods#account_reset_token`, no longer referenced as of #7868 (see https://github.com/18F/identity-idp/pull/7868#discussion_r1117283184).
- `rspec`

Remove unused TwoFactorAuthenticatableMethods methods

---

app/views/layouts/user_mailer.html.erb
config/locales/mailer/en.yml
config/locales/mailer/es.yml
config/locales/mailer/fr.yml

We need our emails to have a bit of uniqueness to improve reliability of delivery, so this is a short fix to add a "sent at" timestamp to all emails.
Translations are incoming once content is approved.

Add sent at timestamp to email footers

---

app/controllers/idv/capture_doc_controller.rb
spec/features/idv/doc_capture/document_capture_step_spec.rb

[LG-8890](https://cm-jira.usa.gov/browse/LG-8890)
Log boolean indication of presence or absence of doc_capture_user_id from the session, adding it to the logging already present in CaptureDocController#ensure_user_id_in_session

Add session's doc_capture_user_id to analytics logged output

---

app/controllers/concerns/two_factor_authenticatable_methods.rb
app/decorators/user_decorator.rb
app/presenters/two_factor_auth_code/authenticator_delivery_presenter.rb
config/locales/instructions/en.yml
config/locales/instructions/es.yml
config/locales/instructions/fr.yml
spec/controllers/users/totp_setup_controller_spec.rb
spec/presenters/two_factor_auth_code/piv_cac_authentication_presenter_spec.rb
spec/views/two_factor_authentication/totp_verification/show.html.erb_spec.rb

Following the work in #7868  and #7869 and a brief discussion in [Slack](https://gsa-tts.slack.com/archives/C01710KMYUB/p1677081279781629), this PR removes the email from the TOTP QR code provisioning URI and the verification page.
The provisioning URI is not quite reliable, as not all authentication apps were able to process it, and it sometimes resulted in showing only the email address without any mention of Login.gov. Accounts can have multiple email addresses and email addresses may change, so the email address that the authentication app was provisioned with may not match the email displayed on the verification page.

Remove email address from verification page for authention apps

---

bin/setup

Removes `tmp/letter_opener` and `tmp/mails` files when bin/setup is run to clean up old temporary files.

Remove all of the temporary files that are created from the letter_opener gem when bin/setup is run.

---

app/controllers/idv/phone_controller.rb
app/forms/idv/phone_form.rb
app/javascript/packages/phone-input/index.spec.ts
app/javascript/packages/phone-input/index.ts
spec/features/idv/doc_auth/send_link_step_spec.rb
spec/forms/idv/phone_form_spec.rb

[LG-8976](https://cm-jira.usa.gov/browse/LG-8976)
(Also a dash of [LG-8839](https://cm-jira.usa.gov/browse/LG-8839), since I was in there.)
A user reported an issue using their Puerto Rican phone number for IdV's hybrid handoff screen. In this case, they had their phone number prefilled, since they were using it for SMS 2FA. It's likely this came in with #7762.

LG-8976: Allow using Puerto Rico phone numbers for hybrid handoff

---

config/locales/forms/en.yml
config/locales/forms/es.yml
config/locales/forms/fr.yml

[LG-8888: Remove reference to face/touch unlock on backup codes warning screen](https://cm-jira.usa.gov/browse/LG-8888)
This PR removes a reference for users to use face/touch unlock in place of backup codes
On your local machine (https://localhost:3000)
- Click "Create your account"
- Enter your email address, select a language, mark checkbox and submit
- Go through process to confirm email address
- Create a password. Continue
- Select "Backup codes" on the authentication methods setup screen
- Observe edited copy
<details>
</details>
<details>
</details>

LG-8888: Remove reference to face/touch unlock on backup codes warning screen

---

app/controllers/concerns/idv/step_utilities_concern.rb

A nil flow session here can result in a 500 if the user navigates to the SSN or address path without starting proofing

Guard against a nil flow sesison in the step utilities concern

---

config/locales/telephony/es.yml
spec/lib/telephony/otp_sender_spec.rb

The average parts per-message for messages sent to Mexico is 3:1.  Digging into the problem, I found that the current OTP and verification messages are the cause and it has everything to do with the word "código" (code) and specifically the character ó, which is not part of the GSM 03.38 character set.
This PR proposes a new set of messages that should still be clear to the user but do not trigger Unicode processing and stay under 1 part in size.
Current message:
* Encoding: Unicode
* SMS parts: 3
* Characters used: 145
Proposed message
* Encoding: 7bit
* SMS parts: 1
* Characters used: 151
This change should reduce spending on Spanish language SMS by over %60.
(Credit: https://messente.com/documentation/tools/sms-length-calculator)
Legend:
Existing language breakdown (OTP):
Proposed new …

Rephrase Spanish OTP and confirmation code messages to stay in GSM 03.38

---

app/controllers/concerns/idv/step_utilities_concern.rb
spec/controllers/idv/ssn_controller_spec.rb

We were getting a 500 if the user creates an account and then redirects to /verify/verify_info, since it tried to go to ssn_controller, which expected the flow session to exist.
changelog: Bug Fixes, Identity Verification, SSN step redirects to Welcome Step without a flow session

If user goes directly to identity proofing, redirect to welcome screen

---

app/controllers/idv/ssn_controller.rb
spec/controllers/idv/ssn_controller_spec.rb

Prior to this commit the SSN controller submitted the SSN form but did not take any action on the result if it was unsuccessful. This commit changes the logic so the page is rendered with an error in that case.
Prior to this change the user would fail downstream on resolution. A frontend validation should prevent this from occurring with frequency.

Enforce SSN form submission in the ssn controller

---

Makefile

Avoids running unnecessary `yarn build` in `make test` before starting JavaScript tests. JavaScript tests should not require built assets.
Discovered while tracing `yarn build` usage for unrelated work.
- `make test`

Remove build prestep from JavaScript Makefile test target

---

app/services/service_provider_request_handler.rb

Currently we read, delete, and re-write Service Provider requests, but in my testing so far it seems redundant. The values are based on parsing the request URL, so we should be able to skip the delete and re-write if they are the same since we'd be deleting and re-writing with the same data.
There is more invasive work that we probably could do around being more precise around when we need to save to Redis and using the session as the primary store for SP requests.

Skip redundant delete and save of service provider authorization requests

---

app/services/doc_auth/acuant/pii_from_doc.rb
app/services/doc_auth/acuant/responses/get_results_response.rb
spec/fixtures/acuant_responses/get_results_response_success.json
spec/jobs/document_proofing_job_spec.rb
spec/services/doc_auth/acuant/acuant_client_spec.rb
spec/services/doc_auth/acuant/pii_from_doc_spec.rb
spec/services/doc_auth/acuant/responses/get_results_response_spec.rb

[LG-9040](https://cm-jira.usa.gov/browse/LG-9040)
* Add _Address Line 2_ to `PiiFromDoc` we generate from Acuant responses
* Log whether or not an address line 2 was present in subsequent IdV-related events (new property is `address_line2_present`

Handle address line 2 coming from Acuant

---

spec/features/idv/doc_auth/verify_info_step_spec.rb
spec/support/features/doc_auth_helper.rb

Undo some of the spec changes from #7847.
Co-authored-by: Luis H. Matos <ThatSpaceGuy@users.noreply.github.com>

Verify info spec refactor

---

app/views/idv/verify_info/show.html.erb
spec/controllers/idv/verify_info_controller_spec.rb

[LG-9016](https://cm-jira.usa.gov/browse/LG-9016)
On Verify Info screen, show Address Line2 even if it is currently blank. This lets the user split their address into two lines if needed, e.g. with Puerto Rico urbanizations.
<details>
</details>
<details>
</details>

LG-9016 Always show Address Line 2 field in Verify Info screen

---

app/forms/idv/api_image_upload_form.rb
spec/controllers/idv/image_uploads_controller_spec.rb

Found while working on [LG-8938](https://cm-jira.usa.gov/browse/LG-8938).
Currently, these events are only logging events that are the results of a _form validation_ failures, but not to vendor errors.
There are actually multiple forms so we missed some events.

CL-8938 - fix idv_document_upload_submitted event

---

app/services/idv/session.rb
spec/controllers/idv_controller_spec.rb

This method is not used at all, so I cleaned it up

Remove unused `#alive?` method from the idv session

---

spec/features/idv/hybrid_flow_spec.rb
spec/rails_helper.rb

Friday test hacking/fix file handles error

---

app/controllers/concerns/idv/verify_info_concern.rb
app/controllers/idv/verify_info_controller.rb
app/javascript/packs/mock-device-profiling.tsx
app/services/idv/steps/threat_metrix_step_helper.rb
app/services/irs_attempts_api/tracker_events.rb
config/application.yml.default
lib/identity_config.rb
spec/controllers/idv/verify_info_controller_spec.rb
spec/features/idv/threatmetrix_pending_spec.rb
spec/fixtures/proofing/lexis_nexis/ddp/error_response.json
spec/fixtures/proofing/lexis_nexis/ddp/successful_redacted_response.json
spec/fixtures/proofing/lexis_nexis/ddp/successful_response.json
spec/support/features/doc_auth_helper.rb

changelog: Internal, Attempts API, Track additional TMX fraud check event

LG-8749: IDV TMX Fraud check event tracking

---

README.md
docs/FixingOpenSSLVersionProblem.md

We found a procedure which fixes an occasional problem in our test suite. Sometimes, for no obvious reason, a developer's machine will start throwing this error:
```
Failure/Error: JWT::JWK.import(certs_response[:keys].first).public_key
OpenSSL::PKey::PKeyError:
rsa#set_key= is incompatible with OpenSSL 3.0
```
on the test file `spec/features/openid_connect/openid_connect_spec.rb`
This PR add documentation on how to correct the problem.

Added doc on how to fix OpenSSL error in tests

---

spec/features/idv/hybrid_flow_spec.rb
spec/rails_helper.rb

We added code to tell Webmock to allow net connect on HTTP start. This was done to prevent too many open files errors from occuring during hybrid flow tests.
This setting stayed in place after the hybrid flow specs ran which could lead to problems with tests making external requests down the line. This commit makes it into an around action to make sure external connections get disabled after the hybrid specs run.

Move the method for allowing net connect on start to an around action

---

app/controllers/concerns/idv_step_concern.rb
app/controllers/idv/review_controller.rb
app/services/idv/session.rb
spec/controllers/concerns/idv_step_concern_spec.rb
spec/controllers/idv/review_controller_spec.rb

The IdV step concern is intended to be used to make certain that previous IdV steps have been completed before allowing a user to complete a step. This commit start the process of implementing these steps by adding an available before action to ensure the address step is complete and using that in the review controller

Add `#confirm_address_step_complete` to the Idv Step Concern

---

app/services/proofing/mock/ddp_mock_client.rb

In #7892 we made "Pass" the default option for the simulated device profiling tooling. Unfortunately the javascript there does not submit anything unless the user actually selects a value from the dropdown. This made sense in the world where "No Result" was the default. With pass as the default it causes the user to fail downstream.
This commit makes 'pass' the default value if 'nil' is submitted. Nil will still be used as the TMx review status value if "no_result" is submitted.

LG-9134 Don't require users to make a selection from the device profiling dropdown

---

app/javascript/packages/document-capture/components/in-person-location-post-office-search-step.spec.tsx
app/javascript/packages/document-capture/components/in-person-location-post-office-search-step.tsx
config/locales/idv/en.yml
config/locales/idv/es.yml
config/locales/idv/fr.yml

[LG-8969](https://cm-jira.usa.gov/browse/LG-8969)
- Update error content for PO search (in English, Spanish, and French)
- Update tests
Create an account or sign in
Go to /verify
Click Continue on verify/doc_auth/welcome
Check radio button and then Continue on /verify/doc_auth/agreement
Click upload from your computer on /verify/doc_auth/upload
Upload and Submit docs to fail ID verification
Click Try in person on /verify/doc_auth/document_capture
Enter any address in the input field and Search on /verify/doc_auth/document_capture#location
<details>
<summary>Before: There was an internal error processing your request. Please try again.</summary>
</details>
<details>
<summary>After: We are having technical difficulties at …

LG-8969: Update error content for po search

---

app/controllers/idv/document_capture_controller.rb
app/views/idv/document_capture/show.html.erb
config/application.yml.default
config/routes.rb
lib/identity_config.rb
spec/controllers/idv/document_capture_controller_spec.rb
spec/features/idv/doc_auth/document_capture_spec.rb

[LG-9097](https://cm-jira.usa.gov/browse/LG-9097)
Add DocumentCaptureController that shows same view as DocumentCapture step for desktop flow, with supporting controller and feature tests. Functionality is behind feature flag `doc_auth_document_capture_controller_enabled`, which defaults to false.
<details>
</details>

LG-9097 document capture show outside FSM

---

app/views/idv/verify_info/show.html.erb
spec/features/idv/doc_auth/verify_info_step_spec.rb
spec/features/idv/steps/in_person/verify_info_spec.rb

[LG-8930](https://cm-jira.usa.gov/browse/LG-8930)
On Verifying Your Information screen, show Date of Birth in full month format. Use the same DateParser being used on Review and Account screens.
<details>
</details>
<details>
</details>

LG-8930 VerifyInfo, show DOB with full month name

---

app/assets/stylesheets/components/_alert-icon.scss
app/views/users/verify_personal_key/new.html.erb

[LG-8896](https://cm-jira.usa.gov/browse/LG-8896)
This pull request fixes a number of accessibility and other visual issues on the personal key reactivation screen:
1. Ensure that headings advance in order
2. Use standard submit button (big, wide)
3. Fix incorrect paddings and margins
4. Simplify stylesheets
1. Create an identity-verified account
2. Reset your password ("Forgot your password?" from the Sign In screen)
3. After resetting password, sign in
4. Click "Reactivate your profile" from account dashboard
5. Click "Yes, I have my personal key" button
Before|After
---|---

LG-8896: Fix heading order for personal key reactivation

---

app/views/users/phone_setup/index.html.erb
app/views/users/phones/add.html.erb

This pull request aims to address some incomplete refactoring started in #7826 and work toward reconciling (and hopefully consolidating) phone creation routes.
In #7826, the new spam protection screen reused POST routes for phone creation with the expectation that we would remove PATCH as a supported verb, reflected in `routes.rb` on `main`:
https://github.com/18F/identity-idp/blob/3a3b3a9de5bf5b6f50e297dbae6e07757222d258/config/routes.rb#L254-L255
However, we never updated the existing reference to the PATCH route in `app/views/users/phone_setup/index.html.erb`, which is updated here.
This also removes a `data-` attribute which, as best I can tell, is not used. (It was added in #3253, though was never used from what I can see)
2. Create a new account …

Use POST route consistently for phone creation

---

app/controllers/concerns/idv_session.rb
app/controllers/concerns/idv_step_concern.rb
app/controllers/idv/phone_controller.rb
app/controllers/idv/review_controller.rb
app/services/idv/session.rb
spec/controllers/concerns/idv_step_concern_spec.rb
spec/controllers/idv/phone_controller_spec.rb
spec/controllers/idv/review_controller_spec.rb
spec/support/controller_helper.rb

With the retirment of the Flow State Machine we will be using the IdV step concern to confirm that steps are completed throughout the proofing flow.
This commit adds a `#confirm_verify_info_step_complete` which can be used as a before action to confirm verify info is complete. If it is not complete it knows to redirect the user either to the remote verify info or in-person verify info depending on whether the user has a in-person enrollmemnt.

Add `#confirm_verify_info_step_complete` to the IdV step concern

---

Gemfile

**Why**: avoids mysterious segfaults on arm machines
changelog: Internal, Development, Skip loading yard gem by default
These commands still work just fine:
- `make lint_analytics_events`
- `bundle exec rspec spec/lib/analytics_events_documenter_spec.rb`
Slack context: https://gsa-tts.slack.com/archives/C0NGESUN5/p1677722613072199

Update Gemfile to not load yard gem by default

---

app/controllers/idv/ssn_controller.rb
app/jobs/reports/daily_dropoffs_report.rb
spec/controllers/idv/ssn_controller_spec.rb
spec/features/idv/analytics_spec.rb

[LG-9150](https://cm-jira.usa.gov/browse/LG-9150)
Log ssn_view_count from SsnController#show.
Pull in @zachmargolis's additional analytics spec to catch log omissions in the future.

LG-9150 add ssn doc auth log

---

app/controllers/idv/ssn_controller.rb
app/jobs/reports/daily_dropoffs_report.rb
spec/controllers/idv/ssn_controller_spec.rb
spec/features/idv/analytics_spec.rb

Internal, Logging, Add regression spec for IDV funnel database logs and log ssn step views
This is from PR #7962 to fix logging

Deploy RC 260.1

---

app/services/doc_auth/processed_alert_to_log_alert_formatter.rb
spec/services/doc_auth/processed_alert_to_log_alert_formatter_spec.rb

I was reading over this code to try to sort through [a question in Slack](https://gsa-tts.slack.com/archives/C5E7EJWF7/p1678378664835909), and these changes helped me read and understand better. They should be 100% no-ops

Clean up DocAuth::ProcessedAlertToLogAlertFormatter and its specs

---

app/services/phone_recaptcha_validator.rb
app/services/recaptcha_validator.rb
spec/features/phone/add_phone_spec.rb
spec/services/phone_recaptcha_validator_spec.rb
spec/services/recaptcha_validator_spec.rb

Adds parsed phone country code to event logging detail for reCAPTCHA phone validation, so that we can do regional analysis of scores.
1. Add a phone to a new or existing account, using an international phone number (e.g. `3065550100`)
2. Look at recent logs with `tail -n10 log/events.log | jq .`
Observe: 'reCAPTCHA verify result received' event includes `country_code` value corresponding to international phone number.

Include parsed phone country code in reCAPTCHA logging

---

config/application.yml.default
config/database.yml
lib/identity_config.rb

To continue our experiment with PgBouncer, it's been helpful to have a separate configuration key from the `database_host` to use in lieu of direct connections to the database.

Add primary database socket configuration

---

Gemfile
Gemfile.lock
app/services/encrypted_redis_struct_storage.rb
app/services/out_of_band_session_accessor.rb
app/services/proofing/mock/device_profiling_backend.rb
app/services/service_provider_request_proxy.rb
config/initializers/redis.rb
config/initializers/session_store.rb
spec/controllers/saml_idp_controller_spec.rb
spec/controllers/test/device_profiling_controller_spec.rb
spec/rails_helper.rb
spec/requests/redis_down_spec.rb
spec/services/encrypted_redis_struct_storage_spec.rb
spec/services/out_of_band_session_accessor_spec.rb
spec/services/proofing/mock/ddp_mock_client_spec.rb
spec/services/proofing/mock/device_profiling_backend_spec.rb

To reduce the total number of connections opened to the primary Redis instance, this PR pulls in the recently resurrected `client_pool` [pull request](https://github.com/18F/redis-session-store/pull/8) in our fork of redis-session-store.
The intersection of using the new `client_pool` and using `REDIS_POOL` everywhere for the primary instance means dropping the use of `redis-namespace`. We may want to consider moving away from the gem long-term anyway as I have an [open pull request](https://github.com/resque/redis-namespace/pull/221) to add unsupported commands to the gem that I'd like to use [elsewhere](https://github.com/18F/identity-idp/pull/7776) in our codebase.

Reduce to using one primary Redis connection pool

---

app/services/usps_in_person_proofing/transliterator.rb
spec/services/usps_in_person_proofing/transliterator_spec.rb

- [LG-7832](https://cm-jira.usa.gov/browse/LG-7832)
- Support multiple characters to be returned from transliteration
- Test behavior around non-ASCII spaces

LG-7832: Support multiple characters for USPS transliteration

---

app/jobs/fraud_rejection_daily_job.rb
app/services/analytics_events.rb
spec/jobs/fraud_rejection_daily_job_spec.rb

changelog: Internal, IdV Fraud, Improve analytics on FraudRejectiondailyJob
Improves the analytics to show the day the profile was rejected to compare with the day the profile entered the fraud_review_pending state

LG-8947 Improve analytics for FraudRejectionDailyJob

---

config/routes.rb
spec/requests/rack_attack_spec.rb

**DO NOT MERGE** until after #7944 has been deployed to production.
Follow-up to #7944 (and #7826) to remove the phone creation `PATCH` route, which has to be removed separately to avoid issues during deployment.

Remove unused phone PATCH route

---

app/jobs/heartbeat_job.rb
spec/jobs/heartbeat_job_spec.rb

The queries in the job currently can result in pretty heavy table scans if the jobs table gets too deep. We do have other metrics that allow us to monitor the health of the job queue that scale better with load and throughput.

Remove querying from good_jobs table in heartbeat job
