- app/jobs/reports/duplicate_ssn_report.rb
- spec/jobs/reports/duplicate_ssn_report_spec.rb
Adds new columns to the report in #7988 based on discussions with fraud team
> Add columns to duplicate SSN reporting (LG-9191)

- app/controllers/concerns/idv/verify_info_concern.rb
- app/services/idv/flows/in_person_flow.rb
- app/services/idv/steps/verify_base_step.rb
- app/services/pii/attributes.rb
- lib/session_encryptor.rb
- spec/services/pii/attributes_spec.rb
changelog: Upcoming features, Double address verification, Allow state ID address fields in user PII
[LG-9138](https://cm-jira.usa.gov/browse/LG-9138)
* Allows new state ID address fields to be stored in the Pii blob in the user session and user profiles
Note: security has approved us beginning development on this feature behind a feature flag. We'll complete security review before collecting this data from users.
> LG-9138: Allow state ID address fields in user PII

- spec/jobs/resolution_proofing_job_spec.rb
The `ResolutionProofingJob` is the class that does much of the legwork during the verify step. Specifically, it does the following:
1. Communicates with ThreatMetrix if necessary
2. Communicates with InstantVerify
3. Communicates with AAMVA
4. Combines results through the `ResolutionResultAdjudicator`
The tests for this class have been sophisticated and have combined a number of different ways of mocking out responses from vendors (e.g. webmocks or stubs of the vendor classes).
This change attempts to simplify some of this by creating a helper for stubbing responses from vendors. Those helpers are used to re-implement simpler examples for the logic the tests test. Ideally this will allow us to more quickly make changes to the `ResolutionProofingJob`.
> Clean up `ResolutionProofingJob` tests

- app/jobs/resolution_proofing_job.rb
- spec/jobs/resolution_proofing_job_spec.rb
- spec/services/idv/agent_spec.rb
We implemented a feature that allowed us to use the response we get from AAMVA to cover attributes that fail the LexisNexis check during resolution. Specifically, the following attributes can be covered by AAMVA:
- Address
- Dob
As part of this change we started sending requests to AAMVA even if the LexisNexis response failed. Previously this occred even if the failed LexisNexis attributes could not be covered by the AAMVA response.
This commit attempts to shed some load on AAMVA's service by not making requests to them if the attributes in a failed LexisNexis response cannot be covered by AAMVA.
> Don't make a request to AAMVA if verification is guaranteed to fail

- config/database.yml
This is a followup to #7967 which was added to enable connecting to the database via a pgbouncer socket in deployed environments. Currently, our setup requires disabling prepared statements if we're using pgbouncer. I wasn't sure if this implicit configuration was a bit too clever, or if something a bit more comprehensive and explicit would be preferred.
> Add configuration for enabling primary database prepared statements

- app/services/proofing/lexis_nexis/instant_verify/proofer.rb
- spec/fixtures/proofing/lexis_nexis/instant_verify/date_of_birth_failure_response.json
Before we use the get-to-yes feature we need to make sure that the base lexis nexis error refers to the scoring model verification. This is what implies that the checks failed and we can fallback to AAMVA.
LexisNexis uses the code priority.scoring.model.verification.fail for some of its workflows. This commit changes the regex we use to match against the code to match that code.
> Change the regular expression we use to determine if get to yes is viable

- config/database.yml
This disables advisory locks when a DB socket is used for the primary database connection.  `pgbouncer` does not support advisory lock use when in transaction mode.
Related PRs #7990 and #7967
> Disable advisory locks when using pgbouncer socket

- app/controllers/concerns/idv/verify_info_concern.rb
- app/services/idv/session.rb
The `skip_legacy_state` method had 2 major problems:
1. The name implies that the new state is somehow a legacy state
2. It is hidden in the `check_ssn` code which makes it difficult to understand how a user moves from the verify info controller to the phone controller
This method attempts to clean this up by removing `skip_legacy_state` method and moving its logic into more reasonable places in the verify info concern or into the `Idv::Session`.
> Remove `skip_legacy_state` method

- lib/tasks/review_profile.rake
- lib/tasks/users_lookup.rake
- spec/lib/tasks/review_profile_spec.rb
https://github.com/18F/identity-devops/issues/5911
related PR with more information [HERE](https://github.com/18F/identity-devops/pull/5963)
Added additional prompts for investigator name, and investigation reason for additional logging. UUID prompt was swapped from getpass to a regular get as we also want to display this information in the logs for security auditing. `STDOUT.sync = true` was added to get the output to show in real time for ssm integration.
> UUID lookup/review rails tasks additional data prompts

- spec/support/matchers/accessibility.rb
Updates the custom RSpec `have_description` matcher to support use in Capybara feature specs.
Previously, this helper assumed `rendered` would be present either as a local variable or as defined during controller specs. This meant it could not be used in Capybara feature specs. The proposed changes would continue to be valid in existing usage, while also being compatible for use in Capybara feature specs.
See previous discussion: https://github.com/18F/identity-idp/pull/7989#discussion_r1138666873
- Existing specs using this matcher should continue to pass: `rspec spec/components`
> Update have_description accessibility matcher for feature spec compatility

- app/javascript/packages/submit-button/submit-button-element.ts
- app/javascript/packs/pw-strength.js
- config/locales/errors/en.yml
- config/locales/errors/es.yml
- config/locales/errors/fr.yml
- spec/features/visitors/password_recovery_spec.rb
- spec/features/visitors/set_password_spec.rb
[LG-9050](https://cm-jira.usa.gov/browse/LG-9050)
This code changes password validation feedback when a user creates a new password for their account. The submit button is no longer disabled and error feedback is immediately applied. Please see the attached Figma for more information.
Create a new account. When entering a new password that is invalid please observe the changes in feedback.
> LG-9050: Add password error handling

- app/controllers/application_controller.rb
- app/services/analytics.rb
- spec/controllers/application_controller_spec.rb
- spec/services/analytics_spec.rb
LG-9206
We are going to need this information in the logs for correlation of fraud data.
> LG-9206 | Analytics logs irs_session_id

- app/jobs/reports/daily_dropoffs_report.rb
- app/jobs/reports/duplicate_ssn_report.rb
- spec/features/idv/analytics_spec.rb
- spec/jobs/reports/duplicate_ssn_report_spec.rb
**Why**: This messes with the jobs being instantiated by the scheduler
changelog: Internal, Reporting, Fix scheduled SSN and Daily Dropoff report jobs
**Background**
I inadvertently created a bad pattern in https://github.com/18F/identity-idp/pull/7960 and copied it to the SSN report
It results in errors like this that prevent these jobs from running
> Remove custom initializers from GoodJob classes

- app/services/analytics_events.rb
The link_sent submitted analytics event was confusingly named send_link submitted. Correct this to get accurate information on whether send_link step is being accessed.
> Correct analytics name send_link to link_sent

- spec/support/shared_examples_for_mailer.rb
Enhances existing mailer shared example specs to include checks for content which may not be broadly supported in email clients. Currently, this includes a check for use of SVG images, which would be encouraged in application views, but which [does not have broad support in email clients](https://www.caniemail.com/features/image-svg/).
Previously:
- https://github.com/18F/identity-idp/pull/7956#discussion_r1139212563
- #6892
- https://github.com/18F/identity-idp/pull/6585#discussion_r922457944
Trigger a failure by adding a violating image to an email template in your local copy of the branch.
Example:
```diff
diff --git a/app/views/user_mailer/add_email.html.erb b/app/views/user_mailer/add_email.html.erb
index 6b31c0f2f..527bcd73c 100644
--- a/app/views/user_mailer/add_email.html.erb
+++ …
```
> Add email support test case to mailer shared examples

- app/services/gpo_confirmation_uploader.rb
- spec/services/gpo_confirmation_uploader_spec.rb
(I also made an unrelated change to stop stubbing `new`)
> Fix spec flake in GpoConfirmationUploader

- app/jobs/get_usps_proofing_results_job.rb
- spec/jobs/get_usps_proofing_results_job_spec.rb
[LG-8836](https://cm-jira.usa.gov/browse/LG-8836), [LG-9176](https://cm-jira.usa.gov/browse/LG-9176)
The Analytics class already logs a user's `uuid` as `user_id` if no alternative is passed; we were overwriting it in `email_analytics_attributes` with the user's `id` which made it harder to match with other events that were using `uuid`.
I also took the opportunity to remove redundant inclusion of `fraud_suspected` in three methods; all three call `response_analytics_attributes` which already includes the `fraud_suspected` value.
And, at @sheldon-b suggestion, I closed LG-9176 by also adding `enrollment_code` to the values logged in `email_analytics_attributes`.
> LG-8836: Don't log custom value for user_id in GetUspsProofingResultsJob

- app/controllers/redirect/contact_controller.rb
- app/controllers/redirect/help_center_controller.rb
- app/presenters/two_factor_auth_code/phone_delivery_presenter.rb
- app/services/marketing_site.rb
- app/views/two_factor_authentication/otp_expired/show.html.erb
- app/views/users/phone_setup/spam_protection.html.erb
- config/application.yml.default
- lib/identity_config.rb
- spec/controllers/redirect/contact_controller_spec.rb
- spec/controllers/redirect/help_center_controller_spec.rb
- spec/services/marketing_site_spec.rb
- spec/views/phone_setup/spam_protection.html.erb_spec.rb
- spec/views/two_factor_authentication/otp_expired/show.html.erb_spec.rb
[LG-9135](https://cm-jira.usa.gov/browse/LG-9135)
Implements tracking for Help Center troubleshooting options shown on the following screens:
- OTP Confirmation
- OTP Expired
- reCAPTCHA Checkbox fallback
As part of ongoing MFA improvements, we want to understand clickthrough rate on troubleshooting flows as part of understanding drop-off on pages where troubleshooting options exist.
Controllers already exist to log redirects to the brochure site, so it's mostly a process of setting the troubleshooting options to link to these controller routes instead of the brochure site directly.
It's easiest to observe logging with a combination of `tail` and `jq` in a separate terminal instance from the IdP:
```
tail -F -n0 log/events.log | jq .
```
To simulate OTP expiration and reCAPTCHA handling, …
> LG-9135: Add logging for Help Center troubleshooting options click-through

- app/services/marketing_site.rb
- spec/services/marketing_site_spec.rb
Updates `MarketingSite` utility methods to include a trailing slash, to avoid an unnecessary redirect hop when users follow links to these destinations.
_Before:_
```
$ curl -i --silent https://www.login.gov/contact | head -n 1
HTTP/2 301 
```
_After:_
```
$ curl -i --silent https://www.login.gov/contact/ | head -n 1
HTTP/2 200 
```
- `rspec spec/services/marketing_site_spec.rb`
- Ensure affected links to Login.gov continue to behave as expected (see links in footer, for example)
> Use canonical URL for MarketingSite URLs

- app/services/throttle.rb
- config/application.yml.default
- config/initializers/redis.rb
- lib/identity_config.rb
This [PR](https://github.com/18F/identity-devops/pull/5692) creates a separate Redis instance for rate limiting because rate limiting has different usage characteristics than our primary instance generally does. There are critical rate limits in the `Throttle` service, and this PR is intended to provide a write-to-both for a period of time, switch to reading from the alternate, and then removing the usage of the primary for rate limiting.
> Add configuration for alternate Redis rate limit pool

- config/newrelic.yml
We get a big spike in these errors every deploy, and they make it harder to tell if a deploy is successful or not. Ignoring them only on the worker should hopefully limit the scope
I opted to take advantage of the ERB in this YML file and make the section more readable across multiple lines
> Update NewRelic config to make errors list more readable

- app/jobs/get_usps_proofing_results_job.rb
- spec/jobs/get_usps_proofing_results_job_spec.rb
This is a follow-on to #8021 that completely closes [LG-9176](https://cm-jira.usa.gov/browse/LG-9176) by adding the enrollment code to the analytics event logged when emails are sent for expired enrollments.
[LG-9176](https://cm-jira.usa.gov/browse/LG-9176)
> LG-9176: Log email analytics attributes when emails are sent for expired enrollments

- app/controllers/event_disavowal_controller.rb
Currently, when resetting your password via event disavowal, you are not signed out, which can lead to unexpected session behavior as a user may or may not be currently signed in.
> Fully sign out user when resetting password via event disavowal

- README.md
- docs/backend.md
- docs/frontend.md
Adds some additional detail for frontend conventions:
- Qualify `package.json` `"private"` field as applying only if the package is not intended for publishing, which is still the most common use-case, but there are some published packages
- Add some some high-level conventions around common React implementation choices (function components, state management, client-side routing)
- Add section for "Localization", linking to [`@18f/identity-i18n` package documentation](https://github.com/18F/identity-idp/blob/main/app/javascript/packages/i18n/README.md)
- Add section describing forms behavior (SimpleForm gem, form validation, ValidatedFieldComponent component)
**Edit:** I added a few more revisions in subsequent commits:
- Cross-link between "backend" and "frontend" forms guidance
- Link …
> Expand on some conventions in frontend documentation

- app/models/in_person_enrollment.rb
- app/services/idv/steps/in_person/state_id_step.rb
- app/views/idv/in_person/state_id.html.erb
- db/primary_migrate/20230320235607_add_capture_secondary_id_enabled_to_in_person_enrollments.rb
- db/schema.rb
- spec/features/idv/in_person_spec.rb
- spec/services/idv/steps/in_person/state_id_step_spec.rb
- [LG-9006](https://cm-jira.usa.gov/browse/LG-9006)
- Create new boolean field `in_person_enrollments.capture_secondary_id_enabled`
- Initialized to `true` if `in_person_capture_secondary_id_enabled` is truthy, otherwise false
- Note: Enrollment creation currently occurs when a PO location is selected
- Display and capture separate state ID address fields if `capture_secondary_id_enabled` is true for the user's `establishing` enrollment
- Was previously determined globally by `in_person_capture_secondary_id_enabled`
- Merging this story will require updates to [LG-9139](https://cm-jira.usa.gov/browse/LG-9139), and vice versa
- https://github.com/18F/identity-idp/pull/8041
- i.e. the feature flag will need to be checked in a different manner than before
Note that the scope of applicable …
> LG-9006: Double Address Verification Feature Toggle

- config/initializers/job_configurations.rb
**Why**: so it collects the previous day's data (runs at UTC midnight)
> Fix schedule for Duplicate SSN report

- Gemfile
I think #8034 now requires that we have the gem available everywhere since the services are loaded by the Rails application.
```
Error: The application encountered the following error: cannot load such file -- aws-sdk-cloudwatchlogs (LoadError)
/bundle/ruby/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/idp/releases/chef/lib/reporting/cloudwatch_client.rb:1:in `<main>'
/bundle/ruby/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/bundle/ruby/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in …
```
> Move aws-sdk-cloudwatchlogs to default gem group

- lib/reporting/authentication_report.rb
- lib/reporting/command_line_options.rb
- lib/reporting/identity_verification_report.rb
- spec/lib/reporting/authentication_report_spec.rb
- spec/lib/reporting/command_line_options_spec.rb
- spec/lib/reporting/identity_verification_report_spec.rb
JIRA: [LG-9254](https://cm-jira.usa.gov/browse/LG-9254)
(Relies on the patterns/refactoring in https://github.com/18F/identity-idp/pull/8040, please review that first)
Adds a `--week=YYYY-MM-DD` option to both the Authentication & IdentityVerification reports
The code will take the one day and expand that to be the Sunday-Saturday that includes the date. So `--week 2023-02-21` and `--week 2023-02-22` would return the same week.
Usage:
```bash
aws-vault exec prod-power -- bundle exec rails runner lib/reporting/authentication_report.rb --week 2023-03-16 --issuer ISSUER
aws-vault exec prod-power -- bundle exec rails runner lib/reporting/identity_verification_report.rb --week 2023-03-16 --issuer ISSUER
```
> Add weekly Cloudwatch reports (LG-9254)

- .gitlab-ci.yml
Following up #8048 / #8052 to try catch the error we ran into before we merge it. This PR is currently opened prior to the fix, so the first CI run is expected to fail.
> Add check for loading rails application in continuous integration to catch usage of uninstalled gems

- app/services/usps_in_person_proofing/proofer.rb
- spec/services/usps_in_person_proofing/proofer_spec.rb
**Note: I suggest starting by disabling whitespace changes when reviewing this PR. A lot of the spec changes were just removing a level of indentation**
[LG-9086](https://cm-jira.usa.gov/browse/LG-9086)
* Fixes a bug where attempting to retrieve a USPS auth token with a memory-backed Rails cache (eg when a dev configures their local environment to communicate with USPS) would fail with an undefined method error
* Changes the USPS preemptive refresh logic to just modify the expires_at cache attribute for the USPS auth token instead of checking when the expiry is within X minutes of expiring
* Reduces the preemptive USPS auth token refresh window from five minutes to one minute. Five minutes seems excessive to me -- that's fully a third of the lifetime of a USPS auth token. The intention of …
> LG-9086: Preemptively refresh USPS auth tokens

- Gemfile
- Gemfile.lock
- Makefile
- bin/docker_setup
- bin/setup
Based on discussion at yesterday's Engineering Huddle and people running into issues with the parallel testing being used by default, this PR removes `parallel_tests` usage from the setup and test commands. It is still available for those who use it, but it will have to be run directly. I've also updated the gem.
> Remove parallel usage in setup and test commands

- app/controllers/idv/in_person/address_search_controller.rb
`ActionController::InvalidAuthenticityToken` is now processed as a [400 error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400) in the Address Search Controller. This will prevent server side errors from firing and triggering alarms.
> Do not return 500 for CSRF token failures for address search controller

- app/assets/stylesheets/components/_alert.scss
- app/views/shared/_sp_alert.html.erb
Follow-up to #8047
This improves the appearance of partner content shown on the sign in, forgot password, or new account setup screens.
Specifically:
- Removes excess margin from the inside bottom of the alert banner
- Adds standard margin (`2rem`) to the outside bottom of the alert banner
1. Start [OIDC sample app](https://github.com/18f/identity-oidc-sinatra/) in a separate process from IdP
2. Visit http://localhost:9292
3. Under "Options", click "Enable attempts api" checkbox
4. Click "Sign in"
5. Observe alert banner on Sign In page
6. Click "Forgot your password?"
7. Observe alert banner on Forgot Password page
8. Click "Cancel"
9. Click "Create an account"
10. Observe alert banner on Forgot Password page
---|---|---
Sign in|![localhost_3000 …
> Improve styling of partner alert content

- config/initializers/01_redis.rb
- config/initializers/rack_attack.rb
Along the same lines as #7968, but for a different pool of Redis connections. `ActiveSupport::Cache::RedisStore` supports taking a pool directly, so we can simply pass the existing pool into the `:redis` option.
The difficulty is the order of loading initializers becomes a problem because they are loaded alphabetically. Rails previously suggested renaming files to guarantee load order, but switched to suggesting combining the dependencies into one file. I've gone with the naming convention since the two aren't specifically related.
https://github.com/rails/rails/commit/9d87a172ca32d60526f2b4c4ace0c5dc333f8489
> Use existing Redis pool for Rack::Attack rate limiting

- app/controllers/users/rules_of_use_controller.rb
- spec/controllers/users/rules_of_use_controller_spec.rb
Bug reported [here](https://gsa-tts.slack.com/archives/C20J64X6V/p1679589807361779) where a user received a CSP error because we redirect back to the relying party in the chain of redirects from the Rules of Use submission request.
This adds the SP domain headers to the response to avoid this error case.
> Fix Content Security Policy errors when redirecting to service provider

- app/controllers/concerns/api/csrf_token_concern.rb
- app/controllers/users/sessions_controller.rb
- app/javascript/packages/request/index.spec.ts
- app/javascript/packages/request/index.ts
- app/javascript/packs/session-timeout-ping.ts
- spec/controllers/concerns/api/csrf_token_concern_spec.rb
- spec/features/users/sign_in_spec.rb
Extracted from #7966
This pull request seek to refresh the form authenticity token when a user's session is renewed by clicking the "Keep me signed in" button when the session expiration modal is shown.
This seeks to be an incremental step toward larger changes in #7966, where this enhances the `request` fetch helper utility without introducing new API endpoints like in #7966.
Related discussions:
- https://github.com/18F/identity-idp/pull/7966/files#r1143978139
- https://gsa-tts.slack.com/archives/C0NGESUN5/p1678740248343529?thread_ts=1678739597.630529&cid=C0NGESUN5
- https://gsa-tts.slack.com/archives/C0NGESUN5/p1679492599039539
1. Sign in
2. Visit a page which has a form to submit (e.g. first step of identity verification)
3. Wait for session timeout modal to appear
4. Click "Keep me …
> Add automatic CSRF refresh on session keepalive

- config/newrelic.yml
[LG-9219](https://cm-jira.usa.gov/browse/LG-9219)
Adds new entries in the NewRelic ignored set of error classes:
- `ActionController::ParameterMissing`
- `ActionDispatch::Http::Parameters::ParseError`
Rationale: We often see errors in the NewRelic errors inbox which appear to be caused by fuzzing, either submitting to an endpoint without the expected parameters, or making a JSON request with invalid JSON.
See related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1679671176539539
This is difficult to test prior to merge.
Once deployed, test to confirm that submitting a request with invalid JSON responds as expected (400 status code) and no error is logged to NewRelic:
```
curl -i -X POST -H 'Content-Type: application/json' -d '{' …
```
> LG-9219: Ignore parameter errors in NewRelic logging

- app/controllers/idv/in_person/address_search_controller.rb
- app/controllers/idv/in_person/usps_locations_controller.rb
- spec/controllers/idv/in_person/usps_locations_controller_spec.rb
Similar to #8060 and #7894, this adds a more general class of errors to avoid returning exceptions on in these controllers.
> Rescue external server errors in location search controllers to avoid exceptions

- app/controllers/idv/in_person/address_search_controller.rb
- app/controllers/idv/in_person/usps_locations_controller.rb
- app/controllers/users/rules_of_use_controller.rb
- spec/controllers/idv/in_person/usps_locations_controller_spec.rb
- spec/controllers/users/rules_of_use_controller_spec.rb
- Authentication: Fix Content Security Policy errors when redirecting to service provider ([#8063](https://github.com/18F/identity-idp/pull/8063))
- In-person Proofing: Rescue external server errors to avoid exceptions ([#8068](https://github.com/18F/identity-idp/pull/8068))
- Source code: Update error checking to allow subclasses ([#8061](https://github.com/18F/identity-idp/pull/8061))
> Deploy RC 265.1 to Production

- app/javascript/packages/captcha-submit-button/captcha-submit-button-element.spec.ts
- app/javascript/packages/captcha-submit-button/captcha-submit-button-element.ts
- app/javascript/packages/spinner-button/spinner-button-element.spec.ts
- app/javascript/packages/spinner-button/spinner-button-element.ts
- app/javascript/packs/form-steps-wait.tsx
- spec/javascripts/packs/form-steps-wait-spec.js
As a follow-on to #7761, this aims to allow SpinnerButton to be self-aware of form validation issues, so that the button will not show the spinning animation if the form is prevented from submitting.
In #7761, the CaptchaSubmitButtonElement was explicitly preventing the SpinnerButton from spinning when the form was invalid, but this could be managed by the SpinnerButton itself.
> Make SpinnerButton form-aware for invalid form submissions

- app/controllers/concerns/idv/document_capture_concern.rb
- app/controllers/concerns/idv/step_utilities_concern.rb
- app/controllers/idv/document_capture_controller.rb
- app/services/idv/session.rb
- config/routes.rb
- spec/controllers/idv/document_capture_controller_spec.rb
- spec/features/idv/doc_auth/document_capture_spec.rb
LG-9098
Add code from existing DocumentCapture step to handle #update method in new DocumentCaptureController, for desktop flow only. The bulk of the document capture work is still done on the front end. Bring over feature tests and make them pass.
<details>
</details>
> LG-9098 DocumentCaptureController#update, desktop flow, feature flagged

- bin/query-cloudwatch
- lib/reporting/cloudwatch_client.rb
- spec/bin/query-cloudwatch_spec.rb
- spec/lib/reporting/cloudwatch_client_spec.rb
- spec/simplecov_merger.rb
This change:
- pulls in the `bin/query-cloudwatch` script from the devops repo.
- adds test coverage for the script
- updates the existing CloudwatchClient to include query time slices
> migrate over bin/query-cloudwatch script:

- app/controllers/concerns/mfa_setup_concern.rb
- app/controllers/concerns/reauthentication_required_concern.rb
- app/controllers/users/piv_cac_authentication_setup_controller.rb
- spec/controllers/users/piv_cac_authentication_setup_controller_spec.rb
- spec/features/two_factor_authentication/change_factor_spec.rb
- spec/support/controller_helper.rb
- spec/support/features/session_helper.rb
Follow-up to #8037 that adds a missing controller and removes the unnecessary change to `confirm_user_authenticated_for_2fa_setup`
> Update re-authentication logic when confirming user is authenticated for 2FA setup

- spec/lib/deploy/activate_spec.rb
[Slack context](https://gsa-tts.slack.com/archives/C04UNV6DDQD/p1679503096818109) (private room)
> Remove realistic example s3 bucket name

- app/javascript/packages/document-capture/context/upload.tsx
- app/javascript/packages/document-capture/services/upload.ts
- app/javascript/packages/request/index.spec.ts
- app/javascript/packages/request/index.ts
- app/javascript/packs/document-capture.tsx
- spec/javascripts/packages/document-capture/components/document-capture-spec.jsx
- spec/javascripts/packages/document-capture/context/upload-spec.jsx
- spec/javascripts/packages/document-capture/services/upload-spec.js
Updates fetch usage in document capture to use the `@18f/identity-request` utility.
Why?
- For consistent handling of CSRF token
- Simplifies behavior within document capture to remove concern for `csrf` React context value
- Ensures that document capture keepalive behavior works the same way to refresh the global CSRF token as introduced with #8067
- Expands features of `@18f/identity-request` to support use-case of raw response handling
- Ensure no regressions in document capture submission
> Update document capture to use request utility

- app/forms/register_user_email_form.rb
- spec/forms/register_user_email_form_spec.rb
[LG-5847](https://cm-jira.usa.gov/browse/LG-5847)
To reproduce:
- Register a new account but do not confirm the account, note the language selected
- Register an account using the same email address as before and change the language preference
- Notice that the second email arrives in the desired language
> LG-5847: Update confirmation email language

- app/controllers/concerns/idv/step_utilities_concern.rb
- app/controllers/concerns/idv_step_concern.rb
- app/controllers/idv/address_controller.rb
- app/controllers/idv/in_person/verify_info_controller.rb
- app/controllers/idv/ssn_controller.rb
- app/controllers/idv/verify_info_controller.rb
- spec/controllers/idv/in_person/verify_info_controller_spec.rb
- spec/controllers/idv/ssn_controller_spec.rb
LG-9099
Refactoring PR, app behavior should be unchanged. The behavior change for this ticket will go into `confirm_document_capture_step_complete` to redirect back from the SSN controller to the DocumentCaptureController for desktop flow when the feature flag is enabled.
This PR might be easier to review by individual commits.
Move and rename two methods from StepUtilitiesConcern to IdvStepConcern, since it is the new place to put before action methods that control ordering of identity verification steps outside the FSM.
- `confirm_pii_from_doc` to `confirm_document_capture_complete`
- Separate implementation in AddressController also renamed. It should eventually call the one in IdvStepConcern.
- `confirm_profile_not_already_confirmed` to `confirm_verify_info_step_needed`
- Separate …
> LG-9099 IdvStepConcern updates

- app/services/analytics_events.rb
- app/services/idv/actions/redo_document_capture_action.rb
- app/services/idv/steps/link_sent_step.rb
- app/services/idv/steps/upload_step.rb
Tail end of LG-8903
The Send Link Step was removed in favor of the Combined Hybrid Handoff screen. This removes some remaining references to that step.
Note that Funnel::DocAuth::RegisterStep still refers to send_link and the doc_auth_logs table still has columns for send_link_view_at and send_link_view_count.
> Remove final references to send_link step

- app/jobs/irs_attempts_events_batch_job.rb
- app/services/irs_attempts_api/redis_client.rb
- config/application.yml.default
- lib/identity_config.rb
- spec/jobs/irs_attempts_events_batch_job_spec.rb
changelog: Internal, Attempts API, Remove events from Redis after background job completed
> LG-8413: Background job should remove events from Redis

- spec/jobs/get_usps_proofing_results_job_spec.rb
Refactor of USPS Proofing job spec to hopefully eliminate flakey tests.
Changes:
1. Remove "minutes_since_establishment" from "it" blocks and instead place in single location within the shared example.
2. Wrap needed tests in `freeze_time` blocks
3. Add specific fields necessary for analytics checks
4. Move some other checks from separate expectations into one expectation, where appropriate.
> Refactor of USPS proofing job spec to eliminate flakey tests

- app/models/proofing_component.rb
- lib/tasks/review_profile.rake
- spec/lib/tasks/review_profile_spec.rb
- spec/models/proofing_component_spec.rb
[LG-9271](https://cm-jira.usa.gov/browse/LG-9271)
- Updates review tasks to check for nil/missing data
- Updates error messaging
- Adds explicit `STDOUT` so that we can `stub_const` it
> Update fraud review rake tasks to handle nil data (LG-9271)

- app/views/idv/doc_auth/welcome.html.erb
- config/locales/doc_auth/en.yml
- config/locales/doc_auth/es.yml
- config/locales/doc_auth/fr.yml
[LG-9820](https://cm-jira.usa.gov/browse/LG-9280)
<details>
</details>
<details>
</details>
<details>
</details>
> LG-9820 Updated Idv Welcome Screen Content

- app/controllers/users/sessions_controller.rb
- spec/controllers/users/sessions_controller_spec.rb
Follow-up to #8084
The work of #8084 was [split](https://github.com/18F/identity-idp/pull/8084#discussion_r1150918192) to two separate changes to avoid issues during deployment. This should only be merged after #8084 is live in production.
- `rspec spec/controllers/users/sessions_controller_spec.rb`
- This should not have any user-facing impact, since the value is no longer used as of #8084
> Remove redundant "remaining" value from session timeout API (Part 2)

- app/forms/gpo_verify_form.rb
- spec/support/idv_examples/gpo_otp_verification.rb
changelog: Internal, IdV GPO, add verified_at when a user completes gpo gpo verification
[LG-9261](https://cm-jira.usa.gov/browse/LG-9261)Link to the relevant ticket.
Made sure when a user goes through GPO flow and verifies their GPO code a `verified_at` timestamp gets placed. This will temporarily be used until we have timestamps for fraud_review and fraud_rejection.
> LG-9261 update verified_at for gpo user

- app/controllers/concerns/idv_step_concern.rb
- app/controllers/idv/address_controller.rb
- app/controllers/idv/document_capture_controller.rb
- app/services/idv/steps/upload_step.rb
- spec/controllers/idv/document_capture_controller_spec.rb
- spec/controllers/idv/ssn_controller_spec.rb
- spec/features/idv/doc_auth/address_step_spec.rb
- spec/features/idv/doc_auth/document_capture_spec.rb
LG-9099
LG-9100
When feature flag is enabled, in desktop flow only, automatically redirect to and from the new DocumentCaptureController for the Document Capture step. Added a test that confirms that mobile-only flow also works.
Notes: 
- Redirect from SSN step when PII is missing from the session goes directly to DocumentCapture if the user had previously chosen standard flow. Once the hybrid step is included we may want to go back to the Upload step instead so the user can choose which flow to use.
- This doesn't include RedoDocumentCapture (triggered by barcode read error).
> LG-9099 LG-9100 Redirects to and from document capture controller

- app/decorators/service_provider_session_decorator.rb
- app/decorators/session_decorator.rb
- app/views/devise/sessions/new.html.erb
- app/views/sign_up/registrations/_registration_heading.html.erb
- app/views/sign_up/registrations/_sp_registration_heading.html.erb
- app/views/users/authorization_confirmation/new.html.erb
- config/locales/headings/en.yml
- config/locales/headings/es.yml
- config/locales/headings/fr.yml
- spec/decorators/session_decorator_spec.rb
Supports [LG-9216](https://cm-jira.usa.gov/browse/LG-9216)
Removes unreachable code for account registration headings for users not associated with a service provider.
`SessionDecorator#registration_heading` varies depending on whether there's an associated service provider, but this heading is only ever rendered in logic paths where a service provider exists. Thus, the changes here simplify to a single view for registrations associated with a service provider and removes unnecessary logic.
There should be no user-facing impact of these changes.
For `app/views/devise/sessions/new.html.erb`:
1. Start from [sample application](https://github.com/18f/identity-oidc-sinatra/)
2. Click "Sign in"
3. Observe heading "Example Sinatra App is using ..."
For …
> Remove code for unused no-SP registration heading

- app/services/usps_in_person_proofing/enrollment_helper.rb
Removes the unused `establishing_in_person_enrollment_for_user` method from `UspsInPersonProofing::EnrollmentHelper`. We stopped using the method in #6707
> Remove unused method from the enrollment helper

- app/forms/idv/in_person/address_form.rb
- app/forms/idv/state_id_form.rb
- app/validators/idv/form_state_id_validator.rb
- spec/features/idv/in_person_spec.rb
[LG-9229](https://cm-jira.usa.gov/browse/LG-9229)
Add transliteration validation for address line 1, address line 2 and city. 
* for address lines `#1 $treet lañe^` should identify `$, ^` as characters that need to be replaced
* for city line `B3st C!ty` should identify `3, !` as characters that need to be replaced
> LG-9229 add transliteration validation to additional fields on state id pg

- app/controllers/idv/gpo_verify_controller.rb
- app/controllers/idv/review_controller.rb
- app/mailers/user_mailer.rb
- app/services/user_alerts/alert_user_about_account_verified.rb
- app/views/user_mailer/account_verified.html.erb
- config/locales/user_mailer/en.yml
- config/locales/user_mailer/es.yml
- config/locales/user_mailer/fr.yml
- lib/tasks/review_profile.rake
- spec/controllers/idv/gpo_verify_controller_spec.rb
- spec/controllers/idv/review_controller_spec.rb
- spec/lib/tasks/review_profile_spec.rb
- spec/mailers/user_mailer_spec.rb
- spec/services/user_alerts/alert_user_about_account_verified_spec.rb
[LG-9285](https://cm-jira.usa.gov/browse/LG-9285)
Updates the link destination for "change your password" to be the "Forgot password" page instead of event disavowal
| --- | --- |
|  <img width="918" alt="Screen Shot 2023-03-31 at 10 41 42 AM" src="https://user-images.githubusercontent.com/458784/229192338-531449ec-97fd-430e-b47a-c00f513661a0.png"> | <img width="911" alt="Screen Shot 2023-03-31 at 10 41 30 AM" src="https://user-images.githubusercontent.com/458784/229192373-210b190f-8495-4866-bed9-1c6d9391b9e8.png"> |
> Update "You verified your identity" email to link to password reset (LG-9285)

- app/javascript/packs/session-timeout-ping.ts
Updates logic for session timeout polling to limit the instances where the next timeout polling would occur early.
When the user's session is about to time out, we schedule a polling request which would occur at the time that the session will time out. However, based on the logic, this could be prone to issues where the computed `timeRemaining` is not in the expected timeframe of 0-30 seconds, which could potentially cause an infinite loop of requests. The changes here ensure that the early timeout is only scheduled in the expected case that the session will expire within the next 0-30 seconds. In the worst case, there is still the request which would happen at [the default 30 second interval](https://github.com/18F/identity-idp/blob/5f586ce02898b469cb7c21c69f8b5d079d186f49/app/javascript/ …
> Add safeguards to early session timeout poll

- app/controllers/concerns/two_factor_authenticatable_methods.rb
- app/forms/idv/phone_confirmation_otp_verification_form.rb
- app/models/user.rb
- spec/controllers/idv/otp_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb
- spec/features/two_factor_authentication/sign_in_via_personal_key_spec.rb
To improve the reliability and performance of 2FA code verification attempts, this PR moves the `second_factor_attempts_count` incrementing and locking into a single transaction rather than potentially doing multiple transactions.
> Improve performance of 2FA verification

- app/controllers/idv/phone_controller.rb
- app/controllers/idv/phone_errors_controller.rb
- app/services/idv/phone_step.rb
- app/views/idv/phone_errors/_warning.html.erb
- app/views/idv/phone_errors/failure.html.erb
- app/views/idv/phone_errors/warning.html.erb
- app/views/idv/shared/_error.html.erb
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- spec/controllers/idv/phone_errors_controller_spec.rb
- spec/features/idv/steps/phone_step_spec.rb
- spec/support/idv_examples/max_attempts.rb
- spec/views/idv/phone_errors/failure.html.erb_spec.rb
- spec/views/idv/phone_errors/warning.html.erb_spec.rb
- spec/views/idv/shared/_error.html.erb_spec.rb
[LG-9026](https://cm-jira.usa.gov/browse/LG-9026)
Update phone finder warning and rate limiting screens with new language and more prominent links to verify by mail.
<details>
<summary> ⚠️ Warning Screen</summary>
<table>
<thead>
<tr><th colspan="2">English</th>
<tr>
<th>
Before
</th>
<th>
After
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
<thead>
<tr><th colspan="2">Spanish</th>
<tr>
<th>
Before
</th>
<th>
After
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
<thead>
<tr><th colspan="2">French</th>
<tr>
<th>
Before
</th>
<th>
After
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<summary> ❌ Rate limited screen</summary>
<table>
<thead> …
> LG-9026: Phone finder failure screen updates

- config/application.rb
This could have been removed quite a bit ago.
https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format
>However Rails 6.1 applications are not able to read this new serialization format, so to ensure a seamless upgrade you must first deploy your Rails 7.0 upgrade with `config.active_support.cache_format_version = 6.1`, and then only once all Rails processes have been updated you can set `config.active_support.cache_format_version = 7.0`.
We don't need to explicitly set `7.0` though since it is the default.
> Use ActiveSupport cache version 7.0

- app/controllers/users/backup_code_setup_controller.rb
- spec/controllers/users/backup_code_setup_controller_spec.rb
- spec/support/matchers/have_actions.rb
This page is currently protected by re-authentication, which we don't want:
This PR removes the re-authentication check from that action.
> Do not prompt for re-authentication on backup code refresh prompt

- app/services/out_of_band_session_accessor.rb
- config/initializers/session_store.rb
- spec/services/access_token_verifier_spec.rb
- spec/services/id_token_builder_spec.rb
Rack::Session has a [defined interface](https://github.com/rack/rack/blob/v2.2.6.4/lib/rack/session/abstract/id.rb#L433-L450), but we use some of the internal `redis-session-store` methods. I'm working on a bit of an internal refactor of our [redis-session-store fork](https://github.com/18F/redis-session-store) and this PR is a precursor to realizing some of those changes.
> Use Rack::Session methods when calling redis-session-store

- app/javascript/packages/document-capture/components/in-person-call-to-action.spec.tsx
- app/javascript/packages/document-capture/components/in-person-call-to-action.tsx
- app/javascript/packages/document-capture/components/in-person-location-post-office-search-step.tsx
- app/javascript/packages/document-capture/components/in-person-prepare-step.spec.tsx
- app/javascript/packages/document-capture/components/in-person-prepare-step.tsx
- spec/features/idv/in_person_spec.rb
- spec/support/features/in_person_helper.rb
- Add role=link to BackButton components  on Prepare Step page. Since the element is already a button, it has the keyboard functionality of a button, but now it is recognized by screen readers as anchor link. 
- Removed href prop for SpinnerButton and Button components rendering both as buttons, the location update occurs in the onclick callback functions.
There should be no visible changes to the UI.
> LG-9345 Maintain material consistency in IPP pages

- config/newrelic.yml
This error popped up twice in NewRelic for verbs like LINK, UNLINK, they're unhandled by Rails so there's not much we can do
> Ignore unhandled HTTP Verb errors

- app/controllers/idv/document_capture_controller.rb
- spec/controllers/idv/document_capture_controller_spec.rb
[LG-9131](https://cm-jira.usa.gov/browse/LG-9131)
Remove 404 action that guards DocumentCaptureController against being used when the feature flag is off.
> LG-9131 Remove DocumentCaptureController 404 before action

- app/controllers/idv/doc_auth_controller.rb
- app/controllers/idv/unavailable_controller.rb
- app/controllers/sign_up/registrations_controller.rb
- app/controllers/vendor_outage_controller.rb
- app/services/analytics_events.rb
- app/services/outage_status.rb
- app/views/idv/unavailable/show.html.erb
- config/application.yml.default
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- config/locales/vendor_outage/en.yml
- config/locales/vendor_outage/es.yml
- config/locales/vendor_outage/fr.yml
- config/routes.rb
- lib/feature_management.rb
- lib/identity_config.rb
- spec/controllers/idv/unavailable_controller_spec.rb
- spec/controllers/sign_up/registrations_controller_spec.rb
- spec/features/idv/outage_spec.rb
- spec/lib/feature_management_spec.rb
- spec/services/outage_status_spec.rb
- spec/views/idv/unavailable/show.html.erb_spec.rb
(This is a do-over of #7970. I took the final state of the PR, cleaned up and re-did the commits against `main`)
[LG-8710](https://cm-jira.usa.gov/browse/LG-8710)
**Provide a way to disable IdV independent of vendor status flags**
There was a desire to be able to keep our existing `vendor_status_*` config infrastructure, but also provide a means for on-call engineers to completely disable identity verification independent of that.
So now, in addition to marking a required vendor as `:full_outage`, setting `idv_available: false` will disable IdV completely.
In code, `FeatureManagement.idv_available?` should be the preferred way of establishing whether identity verification is available to end users.
**Add a new page explaining that Idv is down**
The new page (see screenshots below) …
> LG-8710: New IDV unavailable screen

- app/jobs/get_usps_proofing_results_job.rb
- app/models/in_person_enrollment.rb
- db/primary_migrate/20230403232935_add_status_check_completed_at_to_in_person_enrollments.rb
- db/schema.rb
- spec/jobs/get_usps_proofing_results_job_spec.rb
- spec/models/in_person_enrollment_spec.rb
[LG-9272](https://cm-jira.usa.gov/browse/LG-9272)
- Create DateTime database field `in_person_enrollments.status_check_completed_at`
- Create method `InPersonEnrollment.minutes_since_last_status_check_completed`
- Set `status_check_completed_at` after `GetUspsProofingResultsJob` checks the enrollment status successfully
- Includes:
- Specific 4xx Bad Request errors:
- Enrollment incomplete
- Enrollment expired
- Unsupported ID type
- Enrollment failed
- Enrollment success
- Excludes (except where mentioned above):
- Unsupported status
- Non-hash response
- Standard error
- Faraday error
- Client error
- Server error
- Specific 4xx Bad Request errors:
- Invalid enrollment code
- Invalid applicant
- Log `minutes_since_last_status_check_completed` while running `GetUspsProofingResultsJob` …
> LG-9272: Record in-person enrollment status check completion time

- app/controllers/idv/personal_key_controller.rb
- app/controllers/idv/review_controller.rb
- app/models/profile.rb
- db/primary_migrate/20230403201505_add_fraud_review_pending_at_to_profiles.rb
- db/primary_migrate/20230403201954_add_fraud_rejection_at_to_profiles.rb
- db/schema.rb
- spec/lib/tasks/review_profile_spec.rb
- spec/models/profile_spec.rb
[LG-9398](https://cm-jira.usa.gov/browse/LG-9398)
We have added two timestamp columns to the `Profile` table:
* `fraud_review_pending_at`
* `fraud_rejection_at`
We have also updated the relevant helper methods on the model to use _both_ the older boolean fields (`fraud_review` and `fraud_rejection`) and these new ones. This is an interim phase, and [LG-9075](https://cm-jira.usa.gov/browse/LG-9075) describes the full story for the plan to backfill and remove the older columns.
> LG-9398 Add Fraud Review / Rejection Timestamp Columns

- spec/features/users/sign_up_spec.rb
- spec/views/layouts/application.html.erb_spec.rb
The spec `spec/features/users/sign_up_spec.rb:111`, "rate limits sign-up phone confirmation attempts" was occasionally failing, because a countdown timer that should show up as '10 minutes' was occasionally showing up as ' 9 minutes'.  Investigation showed a previous attempt to fix this using `freeze_time`. This didn't work because the timer is being decremented on the client side, in JavaScript.
We corrected this by removing the call to `freeze_time` and changing the test to accept either 10 or 9.
Participants
john.maxwell@gsa.gov
sonia.connolly@gsa.gov
john.skinner@gsa.gov
alex.bradley@gsa.gov
douglas.price@gsa.gov
> Friday test hacking/fix phone rate limiting test

- spec/services/proofing/aamva/request/verification_request_spec.rb
[[backend] set "issuing state" on AAMVA request](https://cm-jira.usa.gov/browse/LG-9238)
This probably didn't need to be a ticket, because we already set "issuing state" on the request to AAMVA.  I did add one test for this functionality.
- Test that we set "issuing state" on the AAMVA request
- There are no user-facing or internal changes to test.  The one new test can be verified by running it in CI or on a local machine.
> LG-9238: Test that state id jurisdiction is sent to aamva

- .irbrc
**Why**: avoids file permission error
The error looks like this as you close a console, it's benign but looks scary and bad
```
irb(main):036:0> exit
/opt/ruby_build/versions/3.2.0/lib/ruby/3.2.0/irb/ext/save-history.rb:116:in `initialize': Permission denied @ rb_sysopen - /srv/idp/releases/chef/.irb_history (Errno::EACCES)
from /opt/ruby_build/versions/3.2.0/lib/ruby/3.2.0/irb/ext/save-history.rb:116:in `open'
from /opt/ruby_build/versions/3.2.0/lib/ruby/3.2.0/irb/ext/save-history.rb:116:in `save_history'
from /opt/ruby_build/versions/3.2.0/lib/ruby/3.2.0/irb/ext/save-history.rb:60:in `block in extended'
from /opt/ruby_build/versions/3.2.0/lib/ruby/3.2.0/irb.rb:504:in `block in run'
from /opt/ruby_build/versions/3.2.0/lib/ruby/3.2.0/irb.rb:504:in `each'
from …
```
> Avoid writing .irb_history on deployed boxes

- app/views/idv/in_person/state_id.html.erb
- config/locales/in_person_proofing/es.yml
- config/locales/in_person_proofing/fr.yml
[LG-9237: Collect issuing state on state id page](https://cm-jira.usa.gov/browse/LG-9237)
This PR fixes bugs that @daviddsilvanava found during acceptance testing.
[ ] Correct Spanish and French translations for issuing state
[ ] Fix text for radio buttons questions - it previously showed "Same address as" above the actual radio buttons
[ ] Fix radio buttons so that someone using a screen reader will hear the heading
- Follow the testing plan from PR #8121 
<details>
</details>
<details>
</details>
<details>
</details>
> LG-9237: Clean up state id translations and legend text

- app/controllers/idv/phone_errors_controller.rb
- app/views/idv/phone_errors/warning.html.erb
- spec/controllers/idv/phone_errors_controller_spec.rb
- spec/views/idv/phone_errors/warning.html.erb_spec.rb
Guard against phone not being in the IDV session to avoid a `NoMethodError`. Context in Slack thread: https://gsa-tts.slack.com/archives/CNCGEHG1G/p1680882411494599
> Fix 500 error on phone verification warning screen

- .irbrc
- app/controllers/idv/phone_errors_controller.rb
- app/services/backup_code_generator.rb
- app/views/idv/in_person/state_id.html.erb
- app/views/idv/phone_errors/warning.html.erb
- config/locales/in_person_proofing/es.yml
- config/locales/in_person_proofing/fr.yml
- spec/controllers/idv/phone_errors_controller_spec.rb
- spec/services/backup_code_generator_spec.rb
- spec/services/proofing/aamva/request/verification_request_spec.rb
- spec/views/idv/phone_errors/warning.html.erb_spec.rb
- Backup Codes: Fix error when verifying nil backup code ([#8148](https://github.com/18F/identity-idp/pull/8148))
- Identity verification: Prevent a 500 error on the phone warning screen. ([#8152](https://github.com/18F/identity-idp/pull/8152))
- In-person proofing: Fix translations and heading for state id page ([#8150](https://github.com/18F/identity-idp/pull/8150))
- Configuration: Stop recording IRB console history ([#8147](https://github.com/18F/identity-idp/pull/8147))
- In-person proofing: Test state id jurisdiction is sent to aamva ([#8138](https://github.com/18F/identity-idp/pull/8138))
> Deploy RC 270 to Production

- app/jobs/resolution_proofing_job.rb
- app/services/proofing/lexis_nexis/ddp/proofer.rb
- spec/jobs/resolution_proofing_job_spec.rb
- spec/services/proofing/lexis_nexis/ddp/proofing_spec.rb
- spec/support/lexis_nexis_fixtures.rb
We use ThreatMetrix as a tool for device profiling. It gives us a `review_status` result which we store in the database as a proofing component. That proofing component is used later in the process to determine if a profile needs additional review.
We communicate with ThreatMetrix if device profiling is enabled or in collect only mode. We do not communicate with threatMetrix when device profiling is disabled.
Previously, we would write `nil` to the proofing component if we received that or an unexpected review status from ThreatMetrix. This leads to ambiguity later in the process when determining if a user passed the ThreatMetrix check. Specifically, `nil` could mean the ThreatMetrix did not run because device profiling is disabled _or_ it could mean that an error occurred and no …
> LG-9065 Write an exception result when TMx has an invalid review status

- app/controllers/concerns/idv_step_concern.rb
- app/controllers/idv/document_capture_controller.rb
- app/controllers/idv/in_person/verify_info_controller.rb
- app/controllers/idv/verify_info_controller.rb
- spec/controllers/idv/ssn_controller_spec.rb
We have observed a number of 500 errors that are the result of the flow session being nil. There is a new one present in the document capture controller.
This commit fixes all of these issues and hopefully prevents new ones by modifying the non-FSM implementations of `#flow_session` to return an empty hash when the flow session has not been constructed yet.
> Return an empty hash from `#flow_session` if it has not been created

- app/controllers/sign_up/email_confirmations_controller.rb
- app/controllers/sign_up/passwords_controller.rb
- app/controllers/users/reset_passwords_controller.rb
- app/views/sign_up/passwords/new.html.erb
- spec/controllers/sign_up/email_confirmations_controller_spec.rb
- spec/features/irs_attempts_api/event_tracking_spec.rb
- spec/features/session/timeout_spec.rb
- spec/features/visitors/password_recovery_spec.rb
- spec/support/features/session_helper.rb
Fixes an issue where the original partner request would not be maintained through password reset. For example, a user who clicks the link to reset their password on their phone after initiating the password reset on their computer would not be allowed to continue to the service provider.
The SP request ID is only persisted to the session at specific intervals. Most notably, this includes the "Sign in" screen, and the email confirmation screen, but _not_ the password reset screen. The changes here apply the same sort of logic as those other controllers.
https://github.com/18F/identity-idp/blob/3a095866041d563e8da1fc94c4060723f0940c16/app/controllers/users/sessions_controller.rb#L193-L196
https://github.com/18F/identity-idp/blob/3a095866041d563e8da1fc94c4060723f0940c16/app/controllers/sign_u …
> Maintain request ID in password reset

- app/forms/openid_connect_authorize_form.rb
- app/presenters/openid_connect_user_info_presenter.rb
- app/services/identity_linker.rb
- db/primary_migrate/20230324131517_rename_aal_value_to_requested_aal_value.rb
- db/primary_migrate/20230404131517_add_identities_requested_aal_value.rb
- db/schema.rb
- spec/forms/openid_connect_authorize_form_spec.rb
- spec/presenters/openid_connect_user_info_presenter_spec.rb
[LG-9178](https://cm-jira.usa.gov/browse/LG-9178) - Update OIDC token response to include AAL attribute
Adds a new column, `aal_value`, to store the string values of the passed AAL ACR. This ensures that the full AAL is returned in the OIDC user token response including specificity in AAL2 and AAL3 such as `phishing_resistant=true` and `hspd12=true` if applicable.
> Store passed AAL as text to preserve all AAL details

- app/views/idv/verify_info/show.html.erb
- spec/features/idv/doc_auth/verify_info_step_spec.rb
- spec/support/features/doc_auth_helper.rb
[LG-9435](https://cm-jira.usa.gov/browse/LG-9435)
Link directly from VerifyInfo show template to idv_address_url. We no longer need to use the RedoAddressAction in the flow state machine. This is in preparation for deleting the RedoAddressAction.
Note: `idv_doc_auth_redo_address_submitted` analytics event is no longer called. We can add it to AddressController if needed. The same method is called by InPerson::RedoAddressAction, so we don't need to delete the method if we don't use it here.
> Link to idv_address_url from verify_info show template

- app/services/proofing/mock/ddp_mock_client.rb
- spec/services/proofing/mock/ddp_mock_client_spec.rb
[LG-9426](https://cm-jira.usa.gov/browse/LG-9426)
Our production DDP proofer adds errors to its result in these cases:
- The `review_status` is not `"pass"`
- The `request_result` is not `"success"`
This PR updates the mock proofer to behave similarly.
> LG-9426: Update mock DDP proofer results to match the real one

- spec/features/idv/outage_spec.rb
Changes in #8106 included configuration-dependent routing for identity verification.
To test this, the outage spec would stub relevant `IdentityConfig.store` values and call `Rails.application.reload_routes!` to update the routing table. After each test completes, it then calls `Rails.application.reload_routes` once more to clean up.
Unfortunately, the teardown of this process was not working correctly--stubs added using `allow(IdentityConfig.store).to receive(...)` had not been torn down when the routing table was updated. This meant that subsequent tests that relied on those routes being present would fail.
This PR ensures stubs are removed before reloading the routing table on cleanup.
To test this locally, you can use this command to run a subset of the test suite that was [previously …
> Fix flaky IdV outage spec

- app/controllers/concerns/two_factor_authenticatable_methods.rb
- app/controllers/two_factor_authentication/backup_code_verification_controller.rb
- app/controllers/two_factor_authentication/otp_verification_controller.rb
- app/controllers/two_factor_authentication/personal_key_verification_controller.rb
- app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
- app/controllers/two_factor_authentication/totp_verification_controller.rb
- app/controllers/two_factor_authentication/webauthn_verification_controller.rb
- app/controllers/users/piv_cac_login_controller.rb
Currently, the implementation for this is implicitly infers from the URI path, but that limits us in renaming paths going forward, impacts logging of these values, and can make it difficult to understand the different pieces. This PR refactors some of the `auth_method` usage to pass explicit names instead. There will be a followup to remove some of the other implicit uses of the method after this PR.
> Refactor implicit calculation of two-factor authentication methods

- app/models/profile.rb
- db/migrate/20230411160948_remove_phone_confirmed_from_profiles.rb
- db/schema.rb
Part of addressing:
https://cm-jira.usa.gov/browse/LG-9399
The `phone_confirmed` column [was ignored/removed from the `Profile` model in the code nearly 5 years ago](https://github.com/18F/identity-idp/pull/2369). This change actually removes the column from the database.
> Remove phone_confirmed column from profiles table

- app/controllers/concerns/two_factor_authenticatable_methods.rb
- app/controllers/two_factor_authentication/backup_code_verification_controller.rb
- app/controllers/two_factor_authentication/otp_verification_controller.rb
- app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
- app/controllers/two_factor_authentication/totp_verification_controller.rb
- app/controllers/two_factor_authentication/webauthn_verification_controller.rb
This PR is the followup mentioned in #8172 to remove the `two_factor_authentication_method` that infers the 2FA method from a couple different places. The method is replaced by explicitly passing the methods used and moving dynamic calculation of `presenter_for_two_factor_authentication_method` to the controllers where the presenters are used.
> Remove implicit two_factor_authentication_method in favor of explicitly passing the authentication method name

- spec/features/idv/outage_spec.rb
This spec is currently very flaky in CI, and has caused ~30 CI failures today. Skipping it temporarily to unblock other teams.
> Temporarily skip IdV outage spec

- app/controllers/idv/gpo_verify_controller.rb
- app/controllers/idv/personal_key_controller.rb
- app/forms/gpo_verify_form.rb
- spec/controllers/idv/gpo_verify_controller_spec.rb
- spec/controllers/idv/personal_key_controller_spec.rb
- spec/features/idv/steps/gpo_otp_verification_step_spec.rb
- spec/support/idv_examples/gpo_otp_verification.rb
[LG-9362](https://cm-jira.usa.gov/browse/LG-9362)
Moved the sad face fraud review page to after the personal key page in the GPO flow.
> LG-9362 sad face page after personal key page in GPO flow

- app/assets/stylesheets/components/_password.scss
- app/javascript/packs/pw-strength.js
- app/views/devise/shared/_password_strength.html.erb
- app/views/shared/_password_accordion.html.erb
- app/views/sign_up/passwords/new.html.erb
- app/views/users/passwords/edit.html.erb
- config/locales/errors/en.yml
- config/locales/errors/es.yml
- config/locales/errors/fr.yml
- config/locales/instructions/en.yml
- config/locales/instructions/es.yml
- config/locales/instructions/fr.yml
- spec/controllers/event_disavowal_controller_spec.rb
- spec/controllers/sign_up/passwords_controller_spec.rb
- spec/controllers/users/reset_passwords_controller_spec.rb
- spec/features/event_disavowal_spec.rb
- spec/features/users/user_profile_spec.rb
- spec/features/visitors/password_recovery_spec.rb
- spec/features/visitors/set_password_spec.rb
- spec/forms/password_form_spec.rb
- spec/forms/reset_password_form_spec.rb
- spec/javascripts/packs/pw-strength-spec.js
- spec/views/sign_up/passwords/new.html.erb_spec.rb
- spec/views/users/passwords/edit.html.erb_spec.rb
[LG-9232: Improve the usability of the password page](https://cm-jira.usa.gov/browse/LG-9232)
This PR adds copy with information on how users can improve password strength. This includes
- Changing password strength from "So-so" to "Average"
- Adding copy about not reusing passwords
For this ticket, refer to the [designs in Figma](https://www.figma.com/file/dEgQ2CTh2d7AkF6AsQ2ttC/LG-8992-Design%3A-Improve-the-usability-of-the-password-page?node-id=152-1974&t=HpbxKqeqTHapdqgR-0) under "Final Design: Implementation"
On local environments:
<details>
</details>
<details>
</details>
> LG-9232: Improve the usability of the password page

- app/services/proofing/lexis_nexis/instant_verify/proofer.rb
- app/services/proofing/lexis_nexis/response.rb
- spec/services/proofing/lexis_nexis/instant_verify/proofing_spec.rb
- spec/services/proofing/lexis_nexis/response_spec.rb
- spec/support/shared_examples/lexis_nexis.rb
The get-to-yes with AAMVA feature was developed to allow users whose data fails a LexisNexis check to pass if the same attributes pass an AAMVA check. This was done by observing the errors from the LexisNexis transaction and determining which attributes fail and whether they can be covered by AAMVA.
This approaches to determining which attributes fail from the errors turned out to be problematic. The errors are parsed from the LexisNexis InstantVerify product portion of the RDP response and returned as a hash. The structure of that hash has changed occasionally causing this feature to quietly break.
This commit attempts to clean this up by directly inspecting the InstantVerify product instead of looking at the errors hash. This requires parsing out the product in the proofer. There is …
> Use the instant verify product instead of the parsed errors for get-to-yes

- app/services/proofing/lexis_nexis/verification_error_parser.rb
- spec/jobs/resolution_proofing_job_spec.rb
- spec/services/proofing/lexis_nexis/instant_verify/proofing_spec.rb
- spec/services/proofing/lexis_nexis/phone_finder/proofing_spec.rb
- spec/services/proofing/lexis_nexis/response_spec.rb
- spec/services/proofing/lexis_nexis/verification_error_parser_spec.rb
Previously we used the `ProductType` key in the LexisNexis verification error parser as the key for errors. This was done to support the get-to-yes feature with AAMVA. #8176 changes the get-to-yes feature to inspect the response body instead of the errors hash so this is not longer needed to support get-to-yes.
The `ProductType` key is problematic because the LexisNexis response can have multiple products with the same product type. We have observed this with PhoneFinder where responses may contain 2 PhoneFinder products with different `ExecutedStepName` values. Grouping by `ProductType` causes one of the products to be overwritten. This commit attempts to address that issue by grouping by `ExecutedStepName`.
> LG-9209 Use the ExecutedStepName to group LexisNexis errors

- app/controllers/application_controller.rb
Refactors `ApplicationController#user_fully_authenticated?` to defer the check to whether the user has configured two-factor methods, so that it can return early after the Warden session value has been assigned, as part of the critical login path of a user entering their password.
Practically speaking, this removes a database call when submitting the SIgn-in form and being prompted for MFA.
**Open question:** Do we need the `try` call? There was previous discussion about it at https://github.com/18F/identity-idp/pull/4456/files#r530060021, but it's unclear when the session value would be present and it would _not_ be possible to call the accessor.
1. Visit http://localhost:3000
2. Sign in
> Optimize user_fully_authenticated to defer database query

- app/controllers/idv/personal_key_controller.rb
- spec/controllers/idv/personal_key_controller_spec.rb
We recently made a change to show users doing verification by mail the personal key screen after they enter their mailed OTP. Previously these users received their personal key once they entered their password to save their info.
The personal key controller still had some code in it to allow users pending a GPO OTP to access it. Users with a profile that is pending GPO verification should no longer be able to access these controller actions. This commit removes the logic and adds an explicit before action to redirect users.
> LG-9463 Add an explicit redirect from personal key controller for GPO users

- app/controllers/idv/hybrid_mobile/capture_complete_controller.rb
- app/views/idv/hybrid_mobile/capture_complete/show.html.erb
- config/application.yml.default
- config/routes.rb
- lib/identity_config.rb
- spec/controllers/idv/hybrid_mobile/capture_complete_controller_spec.rb
- spec/features/idv/hybrid_mobile/capture_complete_spec.rb
[LG-9431](https://cm-jira.usa.gov/browse/LG-9431)
This is the first part of moving the mobile part of document capture hybrid flow out of the Flow State Machine. There are two steps in the flow, Document Capture and Capture Complete.
- Add feature flag `doc_auth_hybrid_mobile_controllers_enabled` and default to false
- Add HybridMobile::CaptureCompleteController and specs to show the correct view
- Add GET route
Notes:
- Do we want the route to include `/hybrid_mobile/`? What link will we want to text for the hybrid DocumentCaptureController, since `_` causes problems?
- I had to log the user in again in the feature spec. Not sure what's missing there.
- It does not yet have before actions to check where the user is in the flow (future PR)
- This step is currently part of the CaptureDoc …
> LG-9431 new CaptureComplete controller (feature flagged)

- LICENSE.md
Updates LICENSE.md to remove an outdated reference to icons which had previously been embedded in one of our React components:
- We no longer embed the Font Awesome icons, instead using pointers to icon names of the U.S. Web Design System ([source](https://github.com/18F/identity-idp/blob/6f6d56c9562eac19eeba069d76d70e24f001d0a8/app/javascript/packages/components/icon.tsx#L5-L246))
- The file path is inaccurate anyways, since it's been renamed from `icon.jsx` to `icon.tsx`
This restores the copy of LICENSE.md to what it had been prior to #4086
> Remove reference to embedded icons in LICENSE

- app/services/throttle.rb
- config/application.yml.default
- config/initializers/01_redis.rb
- lib/identity_config.rb
The migration described in #8000 has been complete for a bit, so we can remove the configuration values for it.
> Remove unused configuration redis_throttle_alternate_url and redis_throttle_alternate_pool_write_enabled configurations

- app/assets/stylesheets/components/_tag.scss
LG-9313
Per Andrew Duthie the Login style for tags (like "Recommended" on the Hybrid Handoff screen) is Title case and bold, but the design system is still all caps, so override it for idp for now. This is being done as a separate PR because we'll want to undo it when the overall design system is updated.
<details>
<summary>Before: "RECOMMENDED"</summary>
</details>
<details>
<summary>After: "Recommended (bold)</summary>
</details>
> Override tag style to leave case unchanged and make text bold

- app/controllers/idv/ssn_controller.rb
- app/forms/idv/ssn_format_form.rb
- app/views/idv/in_person/ssn.html.erb
- app/views/idv/ssn/show.html.erb
- app/views/shared/_ssn_field.html.erb
- spec/controllers/idv/ssn_controller_spec.rb
- spec/features/idv/doc_auth/verify_info_step_spec.rb
- spec/forms/idv/ssn_format_form_spec.rb
The SSN controller allows a user to enter or update their SSN. Prior to this commit the previous value of the SSN was not maintained when the user was updating their SSN.
This commit attempts to fix that by making use of the SSN form that is used in the controller. The template is changed to eventually read the SSN from the form.
Additionally, the form is used in a pattern that better matches the pattern you expect a form object to be used in. This was not the case before because of constraints that the flow state machine placed on HTML forms.
> LG-9333 Preserve the SSN when returning to the SSN controller

- app/services/proofing/mock/ddp_mock_client.rb
- spec/features/idv/threatmetrix_pending_spec.rb
- spec/services/proofing/mock/ddp_mock_client_spec.rb
In a previous commit we changed the DDP proofer to respond with an exception result when the result from DDP included an unexpected status (ref: #8149). This includes when the result is nil.
This commit changes the DDP mock's behavior to align with the DDP proofer's behavior.
> Configure the DDP mock client to respond with a failed result on `no_result`

- app/views/idv/doc_auth/upload.html.erb
- config/locales/doc_auth/en.yml
- config/locales/doc_auth/es.yml
- config/locales/doc_auth/fr.yml
- spec/features/idv/doc_auth/upload_step_spec.rb
These names were left over from the feature flagged stage of creating the combined hybrid handoff.
Pulled this commit out of closed PR #8213 which was addressing ticket LG-9313.
> Rename translation tags from combined_upload to upload

- app/javascript/packages/phone-input/index.spec.ts
- app/javascript/packages/phone-input/index.ts
[LG-9391](https://cm-jira.usa.gov/browse/LG-9391)
Updates the implementation for PhoneInputComponent to improve how its represented to assistive technology:
- Render as combobox to clarify role (e.g. announced as "list box pop up" in macOS VoiceOver)
- Associate named label "Country code" in addition to value
- Improve ARIA hasPopup semantics to associate as `listbox` (previously `"true"`)
Resources:
- https://w3c.github.io/aria/#combobox
- https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/combobox_role
2. Sign in
3. Add Phone Number in account sidebar
4. Activate screen reader
5. Navigate to dropdown toggle
6. Observe proper announcement of name, role, …
> LG-9391: Improve accessibility for phone dropdown

- app/controllers/idv/document_capture_controller.rb
- app/views/idv/document_capture/show.html.erb
[LG-9106](https://cm-jira.usa.gov/browse/LG-9106)
This is part of the effort to delete unused parts of the FSM DocumentCaptureStep (see also PR #8218)
There is a doc_auth#return_to_sp route that adds the current step to analytics when a user clicks the return_to_sp url, using the Flow State Machine. We can't use that in the new DocumentCaptureController once the DocumentCaptureStep is deleted from DocAuthFlow, so set the return_to_sp url more directly.
> Create return_to_sp url directly for DocumentCapture step (no FSM)

- app/controllers/application_controller.rb
- app/controllers/openid_connect/authorization_controller.rb
- app/controllers/saml_idp_controller.rb
- app/policies/service_provider_mfa_policy.rb
- spec/controllers/openid_connect/authorization_controller_spec.rb
- spec/controllers/saml_idp_controller_spec.rb
- spec/features/openid_connect/openid_connect_spec.rb
- spec/features/saml/ial1_sso_spec.rb
- spec/features/users/sign_in_spec.rb
- spec/policies/service_provider_mfa_policy_spec.rb
- spec/requests/openid_connect_authorize_spec.rb
- spec/support/features/session_helper.rb
- spec/support/shared_examples/sign_in.rb
Updates the logic for redirecting during a partner-initiated authentication in order to remove the `request_id` query parameter, since the request ID will have already been saved to the session at this point.
This is a follow-up to https://github.com/18F/identity-idp/pull/8137#issuecomment-1503250527 :
> I started exploring removing the `request_id` from the redirects initiated by `SamlIdpController` and `OpenidConnect::AuthorizationController`, since the `request_id` will have already been stored at those points, via [`store_saml_request`](https://github.com/18F/identity-idp/blob/111dfd9e6592373488cfe56dabc9f5ccbd2a5ec6/app/controllers/concerns/saml_idp_auth_concern.rb#L75-L82) and [`store_request`](https://github.com/18F/identity-idp/blob/111dfd9e6592373488cfe56dabc9f5ccbd2a5ec6/app/cont …
> Redirect to sign in from authentication controllers

- app/components/one_time_code_input_component.rb
- app/controllers/two_factor_authentication/otp_verification_controller.rb
- app/services/idv/phone_confirmation_session.rb
- app/views/idv/otp_verification/show.html.erb
- spec/components/one_time_code_input_component_spec.rb
- spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
- spec/services/idv/phone_confirmation_session_spec.rb
[LG-8871: Allowing a user to enter “#” before a one-time code](https://cm-jira.usa.gov/browse/LG-8871)
The texts we send to users with a one-time code show the code twice:
- once as is, e.g., '123456'
- once with a '#' in front, e.g., '#123456'
This change allows the user to enter the code either way.
1. Create a new user with SMS set for 2FA
2. When entering the 2FA, prepend a '#' in front of the code
3. Verify that the code was accepted
4. Go through identity verification until you get to the phone step
5. When entering the 2FA, prepend a '#' in front of the code
6. Verify that the code was accepted
> LG-8871: Allow users to prefix otp with '#'

- docs/frontend.md
Improves internal documentation for component naming conventions.
In doing so, it does a light restructuring of the documentation so that...
1. Components are documented separate from "JavaScript" heading, especially since it already included details about ViewComponent implementations
2. The new components section includes references to design system components
3. "Testing" is documented separate from "JavaScript" heading, so that "Stylelint" testing could be moved under it
> Add component naming conventions guidance

- app/services/funnel/doc_auth/register_step.rb
- spec/services/db/add_document_verification_and_selfie_costs_spec.rb
We managed to find a few more references to "selfie" which were left behind when we made an effort to remove all of the selfie capture code.
> Remove the last couple selfie references

- app/controllers/application_controller.rb
- config/initializers/session_store.rb
- spec/requests/openid_connect_userinfo_spec.rb
Currently, a session will be loaded or created on routes that use the `skip_session_load` action when the session is accessed. The current behavior results from the analytics functionality accessing and mutating the session, which causes it to be created.
This change will not delete sessions or remove the session cookie, it should simply ignore it. It makes use of the the `:skip` option outlined in Rack [here](https://github.com/rack/rack-session/blob/c9beee68e974e0e0f52f18e4847edceace8290e3/lib/rack/session/abstract/id.rb#L220-L222):
>     # * :skip will not a set a cookie in the response nor update the session state
>     # * :defer will not set a cookie in the response but still update the session
>     #   state if it is used with a backend
> Skip session more fully when skipping session loading

- app/forms/idv/state_id_form.rb
- app/services/idv/steps/in_person/state_id_step.rb
- app/services/pii/attributes.rb
- app/services/usps_in_person_proofing/enrollment_helper.rb
- app/validators/idv/form_state_id_validator.rb
- app/views/idv/in_person/state_id.html.erb
- app/views/idv/shared/_verify.html.erb
- config/locales/in_person_proofing/en.yml
- config/locales/in_person_proofing/es.yml
- config/locales/in_person_proofing/fr.yml
- lib/idp/constants.rb
- lib/session_encryptor.rb
- spec/features/idv/in_person_spec.rb
- spec/features/idv/steps/in_person/verify_step_spec.rb
- spec/services/idv/steps/in_person/state_id_step_spec.rb
- spec/services/pii/attributes_spec.rb
- spec/services/usps_in_person_proofing/enrollment_helper_spec.rb
- spec/support/features/in_person_helper.rb
- spec/support/features/verify_step_helper.rb
[LG-9404](https://cm-jira.usa.gov/browse/LG-9404)
Renames the DAV PII attributes and session encryptor keys to be forwards compatible with any identity document instead of just state IDs.
> LG-9404: Rename DAV PII fields to be forwards compatible with generic identity documents

- app/controllers/idv/document_capture_controller.rb
- app/views/idv/ssn/show.html.erb
- spec/features/idv/doc_auth/verify_info_step_spec.rb
- spec/features/idv/doc_capture/document_capture_step_spec.rb
The flow state machine made using flash messages difficult. Since it no longer controls to SSN and document capture step we can use the flashes here. The flash messages are handled in the application layout so just adding the message to the flash hash ensures it is rendered.
> Use the flash message for document capture success

- app/forms/gpo_verify_form.rb
- app/models/profile.rb
- app/services/idv/profile_maker.rb
- app/services/idv/session.rb
- spec/controllers/idv/personal_key_controller_spec.rb
- spec/models/profile_spec.rb
- spec/services/idv/profile_maker_spec.rb
[LG-9533](https://cm-jira.usa.gov/browse/LG-9533)
When a user goes through the GPO flow, it will now save a timestamp for `gpo_verification_pending`. When they verify with their one time code, it will set the field to `nil` and activate the profile. 
> LG-9533 Start writing to GPO verification pending column

- Gemfile.lock
> warning: parser/current is loading parser/ruby32, which recognizes 3.2.0-compliant syntax, but you are running 3.2.2.
> Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
> Update parser gem to fix warning

- app/controllers/concerns/saml_idp_logout_concern.rb
- app/controllers/saml_idp_controller.rb
- app/services/analytics_events.rb
- spec/features/saml/saml_logout_spec.rb
To better understand the impact of remote logout on the user experience, this PR adds a log event for when a user's session is deleted from Redis (though it may already be expired).
> Log completed SAML Remote Logout requests

- app/views/idv/doc_auth/welcome.html.erb
- spec/views/idv/doc_auth/welcome.html.erb_spec.rb
[LG-9320](https://cm-jira.usa.gov/browse/LG-9320)
Removed the outage banner from the doc_auth welcome.html template.
<details>
https://user-images.githubusercontent.com/1261794/234040065-a0451f8b-89c9-4811-93ff-057aa8a05e06.mov
</details>
<details>
https://user-images.githubusercontent.com/1261794/234041003-0f9e6374-fc43-4f99-b2b0-672c61d8fef6.mov
</details>
> LG-9320 Remove phone outage banner from IDV welcome page

- app/controllers/users/piv_cac_setup_from_sign_in_controller.rb
The `PivCacSetupFromSignInController` is intended for users that have signed in with another method after not being able to sign in with PIV/CAC, so it should only be accessible by users that are fully and recently authenticated. This is a followup to #8037 to require re-authentication in this controller.
> Require re-authentication for PIV/CAC setup from sign in process

- app/controllers/users/phone_setup_controller.rb
- spec/controllers/users/phone_setup_controller_spec.rb
The `Users::PhoneSetupController` is intended for use by users that are in account registration. Users that are not in account setup use the `Users::PhonesController` and `Users::EditPhoneController`, both of which require recent authentication. To prevent users from managing 2FA without being recently authenticated, this PR adds a check so that only users going through account registration can access this controller.
> Do not allow accessing PhoneSetupController unless you are in account setup

- app/views/idv/gpo_verify/index.html.erb
- config/locales/forms/en.yml
- config/locales/forms/es.yml
- config/locales/forms/fr.yml
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- spec/features/idv/steps/gpo_step_spec.rb
[LG-9563](https://cm-jira.usa.gov/browse/LG-9563)
Previously it said "Cancel and return to your profile" but it does not cancel identity verification, so change to "Return to your profile." Add new translation key `forms.verify_profile.return_to_profile`. Delete now-unused key `idv.buttons.cancel`.
<details>
</details>
<details>
</details>
<details>
</details>
> Update "return to profile" link language on GPO verify page

- config/country_dialing_codes.yml
- config/pinpoint_supported_countries.yml
- Disambiguates between Burundi and Saint Barthélemy
I got a spec failure on an [unrelated PR](https://github.com/18F/identity-idp/pull/8278), so I am fixing this
> Update supported countries to match AWS documentation

- Makefile
- docs/sdk-upgrade.md
- scripts/download_acuant_sdk.sh
This PR adds a new command, `make download_acuant_sdk`, that will download the most recent Acuant SDK version from their Github page, unzip it, and put the relevant files in a subdirectory inside `public/acuant`.
This more or less automates the first couple steps of @jskinne3's [SDK upgrade doc](https://github.com/18F/identity-idp/blob/main/docs/sdk-upgrade.md), which I have updated accordingly.
> Add `make download_acuant_sdk` command

- Gemfile.lock
Something appears to have went wrong in #8271 such that the SHA in Gemfile.lock does not exist anymore:
```
Git error: command `git reset --hard 6bce0e98b3c60f45c990de335386d129a81bc77d` in directory
/Users/mitchellehenke/projects/identity-idp/.gem/ruby/3.2.2/bundler/gems/saml_idp-6bce0e98b3c6 has failed.
fatal: Could not parse object '6bce0e98b3c60f45c990de335386d129a81bc77d'.
```
> Fix updating saml_idp gem

- lib/pinpoint_supported_countries.rb
Fixes an error causing all builds to fail due to missing phone data for the "KV" country code listed on [Pinpoint's documentation](https://docs.aws.amazon.com/pinpoint/latest/userguide/channels-sms-countries.html). The Kosovo country code is "XK" in the Phonelib library, so the changes here introduce a mapping from "KV" to "XK".
- https://docs.aws.amazon.com/pinpoint/latest/userguide/channels-sms-countries.html
- https://en.wikipedia.org/wiki/XK_(user_assigned_code)
Related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1682519068993279
Confirm no errors when running `make lint_country_dialing_codes`
> Remap Pinpoint KV country code

- app/controllers/concerns/idv/hybrid_mobile/hybrid_mobile_concern.rb
- spec/controllers/idv/hybrid_mobile/capture_complete_controller_spec.rb
- spec/controllers/idv/hybrid_mobile/document_capture_controller_spec.rb
- spec/controllers/idv/hybrid_mobile/entry_controller_spec.rb
[LG-9605](https://cm-jira.usa.gov/browse/LG-9605)
The Plan:
1) Deploy Hybrid Mobile code #8243 
2) Merge and deploy this PR to remove 404 action
3) Test 50/50 state in int
4) Turn on feature flag doc_auth_hybrid_mobile_controllers_enabled in production
5) Merge and deploy delete PR for now-unused FSM capture doc flow.
> Remove hybrid mobile 404 action if feature flag disabled

- app/javascript/packages/device/index.js
- app/javascript/packs/document-capture-welcome.ts
- app/views/idv/doc_auth/welcome.html.erb
- spec/features/idv/doc_auth/agreement_step_spec.rb
- spec/features/idv/doc_auth/welcome_step_spec.rb
- spec/support/features/doc_auth_helper.rb
[LG-9567](https://cm-jira.usa.gov/browse/LG-9567)
Followup to #8249 and comments there indicating that the async check for a camera was no longer needed. @aduth pointed out it was unnecessary and @matthinz confirmed, "Looks like over the last 4 weeks, 99.97% of these checks where we called the device "camera capable mobile" also then subsequently reported actually having a camera present."
> Remove async camera check from document-capture-welcome.ts

- config/locales/doc_auth/es.yml
https://cm-jira.usa.gov/browse/LG-9527
Fixes an accidental oversight in PR #8283 — a wrong word in Spanish
Perform workflow using (or switching to) a Puerto Rico address in Spanish language mode and confirm the phrase "Residentes en Puerto Rico" appears in the banner
> Replace word I skipped on accident

- .gitlab-ci.yml
This commit is missing a change log, so it is testing the concept. Clever?  You know, I have been called worse...
This moves the changelog CI step into the `test` phase to allow the full test suite to run while our heroic developers add a conventional commit message.
<details>
</details>
> Move changelog check to test stage to allow other tests to run

- lib/feature_management.rb
- spec/lib/feature_management_spec.rb
[LG-8891](https://cm-jira.usa.gov/browse/LG-8891)
Updates `FeatureManagement.phone_recaptcha_enabled?` to consider "enabled" if secret keys are not provided.
[Secret keys are considered "legacy" with reCAPTCHA Enterprise](https://cloud.google.com/recaptcha-enterprise/docs/create-key#find-key), and are superseded by API key. When enabling the feature added in #8271 in deployed environments, it was observed that this was not working correctly when the secret keys were removed.
A workaround could be to continue providing them, but since they're not required, it makes sense to consider this as part of the logic.
Repeat Testing Plan from #8274
Confirm updated FeatureManagement specs pass:
```
rspec spec/lib/feature_management_spec.rb
```
> LG-8891: Update reCAPTCHA enabled logic to allow blank secret key if Enterprise

- .gitlab-ci.yml
changelog: Internal, CI, Speed deployment by moving prepare_deploy earlier in CI
This moves the `prepare_deploy` step to run in the `test` phase of CI in order to reduce total time to deployment.
There is no need to wait on building deployable artifacts.  They will not be deployed if the test stage fails.  If it passes, they will be ready to deploy.
> Move prepare_deploy step to run in test phase of CI

- app/models/user.rb
- app/services/user_event_creator.rb
- config/initializers/devise.rb
- spec/factories/users.rb
- spec/features/new_device_tracking_spec.rb
- spec/models/user_spec.rb
- spec/services/user_event_creator_spec.rb
- spec/support/features/session_helper.rb
[LG-9429](https://cm-jira.usa.gov/browse/LG-9429)
Updates device notification logic to avoid sending new device notifications prior to the user being fully registered, so that a user doesn't receive a "New Sign-In" notification if they complete account registration on a second device, which is common if they were to start the process on a computer and complete it on their phone.
~**DRAFT:** Leaving this as draft for now because, while I think "fully registered" aligning to the RegistrationLog record makes a lot of sense, it's unclear if this is reliable enough to exist for users who have existed since prior to the introduction of that table in #3121. Instead, it may make more sense to have it reflect the presence of any MFAs, essentially aliasing `fully_registered?` to …
> LG-9429: Avoid sending new device notification before fully registered

- app/presenters/webauthn_setup_presenter.rb
- app/views/users/backup_code_setup/index.html.erb
- app/views/users/webauthn_setup/new.html.erb
- config/locales/titles/en.yml
- config/locales/titles/es.yml
- config/locales/titles/fr.yml
- spec/presenters/webauthn_setup_presenter_spec.rb
- spec/views/users/backup_code_setup/index.html.erb_spec.rb
- spec/views/users/webauthn_setup/new.html.erb_spec.rb
[LG-9390](https://cm-jira.usa.gov/browse/LG-9390)
Changes titles for Webauthn setup page and backup code setup page. Note, the title for Webauthn Platform is still incorrect and is awaiting copy.
> LG-9390: Add page titles

- app/mailers/user_mailer.rb
- app/views/idv/in_person/ready_to_verify/show.html.erb
- app/views/user_mailer/in_person_ready_to_verify.html.erb
- app/views/user_mailer/shared/_in_person_ready_to_verify.html.erb
- config/locales/doc_auth/en.yml
- config/locales/headings/en.yml
- config/locales/idv/en.yml
- config/locales/in_person_proofing/en.yml
- config/locales/in_person_proofing/es.yml
- config/locales/in_person_proofing/fr.yml
- config/locales/user_mailer/en.yml
- config/locales/user_mailer/es.yml
- config/locales/user_mailer/fr.yml
- config/service_providers.localdev.yml
- spec/features/idv/actions/redo_document_capture_action_spec.rb
- spec/features/idv/analytics_spec.rb
- spec/features/idv/doc_auth/document_capture_spec.rb
- spec/features/idv/doc_auth/test_credentials_spec.rb
- spec/features/idv/doc_capture/capture_complete_step_spec.rb
- spec/features/idv/doc_capture/document_capture_step_spec.rb
- spec/features/idv/hybrid_flow_spec.rb
- spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb
- spec/features/idv/in_person_spec.rb
- spec/features/idv/steps/in_person/verify_info_spec.rb
- spec/features/idv/steps/in_person/verify_step_spec.rb
- spec/mailers/user_mailer_spec.rb
- spec/support/features/idv_step_helper.rb
- spec/views/idv/in_person/ready_to_verify/show.html.erb_spec.rb
changelog: User-Facing Changes, In Person Proofing, Barcode Info Updates
> LG-8319 Update IPP Barcode Communication

- app/controllers/concerns/idv/hybrid_mobile/hybrid_mobile_concern.rb
- app/controllers/idv/document_capture_controller.rb
- app/controllers/idv/hybrid_mobile/capture_complete_controller.rb
- app/controllers/idv/hybrid_mobile/document_capture_controller.rb
- spec/controllers/idv/hybrid_mobile/capture_complete_controller_spec.rb
- spec/features/idv/hybrid_flow_spec.rb
- spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb
[LG-9494](https://cm-jira.usa.gov/browse/LG-9494)
Add before action to CaptureCompleteController to redirect if DocumentCapture step was not successful, in the hybrid flow. Also in DocumentCapture#show, redirect to CaptureComplete if document capture is already done.
Set aysnc to false in hybrid flow feature specs.
Note: Do we want/need to check if document capture was successful before leaving DocumentCaptureController#update, or do we rely on the following controller (CaptureComplete or Ssn) to redirect backwards when needed?
> LG-9494 capture complete checks if previous step is done

- app/controllers/concerns/remember_device_concern.rb
- app/controllers/concerns/two_factor_authenticatable.rb
- app/controllers/concerns/two_factor_authenticatable_methods.rb
- app/controllers/two_factor_authentication/backup_code_verification_controller.rb
- app/controllers/two_factor_authentication/personal_key_verification_controller.rb
- app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
- app/controllers/users/piv_cac_login_controller.rb
- app/policies/service_provider_mfa_policy.rb
- spec/controllers/concerns/reauthentication_required_concern_spec.rb
- spec/controllers/saml_idp_controller_spec.rb
- spec/controllers/users/piv_cac_authentication_setup_controller_spec.rb
- spec/policies/service_provider_mfa_policy_spec.rb
- spec/support/controller_helper.rb
Inspired by @zachmargolis' comment [here](https://github.com/18F/identity-idp/pull/8037#discussion_r1143745831) to move away from copying different strings everywhere, this PR defines and uses constants for assigning and checking values in the session's `auth_method` so that we can more easily continue to develop around these pieces of functionality.
This PR should be neutral in terms of behavior.
> Switch to using constants for auth_method values

- app/controllers/concerns/idv/verify_info_concern.rb
- app/controllers/idv/in_person/verify_info_controller.rb
- app/controllers/idv/verify_info_controller.rb
- spec/controllers/idv/in_person/verify_info_controller_spec.rb
- spec/controllers/idv/verify_info_controller_spec.rb
[LG-9439](https://cm-jira.usa.gov/browse/LG-9439)
Generalizes the update method used by the non-FSM versions of the remote and in-person verify info page and moves it into the shared `VerifyInfoConcern`
> LG-9439: Move verify info update to concern

- app/javascript/packages/document-capture/context/acuant.tsx
- config/application.yml.default
- spec/javascript/packages/document-capture/components/acuant-sdk-spec.js
- spec/views/idv/shared/_document_capture.html.erb_spec.rb
[LG-9566](https://cm-jira.usa.gov/browse/LG-9566)
We have a few places in the codebase where we refer to specific versions of the Acuant SDK. This means we have to make additional code updates after upgrading the SDK. This PR attempts to reduce the amount of cleanup work necessary by:
- Updating frontend JS specs to just test all Acuant versions present in git rather than hardcoding a version
- Removing a couple other unnecessary hardcoded references to the Acuant SDK
> Require less cleanup after updating Acuant

- spec/lib/tasks/review_profile_spec.rb
changelog: Internal, Identity Verification, Remove unnecessary fraud review task test
`Profile#verified_at` was previously used to determine a profile's fraud status, but now is no longer needed. The code before this PR reflects that change, and as a result, the enclosing test is now unnecessary and can be safely removed.
> Don't use `verified_at` for pending fraud review

- app/controllers/users/backup_code_setup_controller.rb
- app/controllers/users/piv_cac_authentication_setup_controller.rb
- app/controllers/users/webauthn_setup_controller.rb
- spec/features/users/sign_up_spec.rb
- spec/support/features/session_helper.rb
The `auth_method` value in the session is used for doing re-authentication checks and for checking whether an account's authentication method meets a service provider's authentication level (AAL2, AAL2-phishing-resistant, AAL2-HSPD12). The setting is currently inconsistent, and is not set when registering backup codes or PIV/CAC.
OTP-based 2FA methods ([TOTP](https://github.com/18F/identity-idp/blob/a285c62c5a1b2231efe6edd9310635125cf03268/app/controllers/two_factor_authentication/totp_verification_controller.rb#L26), [phone](https://github.com/18F/identity-idp/blob/a285c62c5a1b2231efe6edd9310635125cf03268/app/controllers/two_factor_authentication/otp_verification_controller.rb#L24)) call [handle_valid_otp](https://github.com/18F/identity-idp/blob/a285c62c5a1b2231efe6edd9310635125cf03268/a …
> Ensure authentication method is stored when setting up backup codes or PIV/CAC

- app/controllers/concerns/remember_device_concern.rb
- app/controllers/concerns/two_factor_authenticatable_methods.rb
- app/controllers/users/passwords_controller.rb
- app/controllers/users/phones_controller.rb
The calls to `bypass_sign_in` removed in this PR seem to be unnecessary and are at best confusing since we should be able to rely on Devise to handle assignment of the user resource. The one exception is when [updating the password](https://github.com/18F/identity-idp/blob/c5c793a8b53c3f6f81dc1f296e9b382d6a4a4a05/app/controllers/users/passwords_controller.rb#L50) while already authenticated because a change in the password hash terminates existing sessions.
> Remove unnecessary bypass_sign_in calls

- app/services/account_reset/delete_account.rb
A similar problem to the one solved in #7495. If accounts and emails are deleted, we will be unable to load them if we try to send the email asynchronously. This PR changes the delivery to only send synchronously to avoid the error.
[NewRelic Error](https://onenr.io/0BR68oxM0QO)
> Ensure account deletion emails get sent even when emails are configured to send asynchronously

- bin/query-cloudwatch
- lib/reporting/authentication_report.rb
- lib/reporting/cloudwatch_query_time_slice.rb
- lib/reporting/command_line_options.rb
- lib/reporting/identity_verification_report.rb
- spec/bin/query-cloudwatch_spec.rb
- spec/lib/reporting/authentication_report_spec.rb
- spec/lib/reporting/cloudwatch_query_time_slice_spec.rb
- spec/lib/reporting/command_line_options_spec.rb
- spec/lib/reporting/identity_verification_report_spec.rb
https://cm-jira.usa.gov/browse/LG-9613
This change:
- adds a --threads, --slice and --month flag to the Reporting::CommandLineOptions class
- updates AuthenticationReport and IdentityVerificationReport to accept those flags
- moves parse_duration method into a shareable module
`aws-vault exec prod-analytics -- bundle exec rails runner lib/reporting/authentication_report.rb --month 2023-04-01 --issuer $ISSUER --threads 10 --slice 1h`
> LG-9613 Add command_line args and move parse_duration method

- app/controllers/idv/session_errors_controller.rb
- app/views/idv/session_errors/throttled.html.erb
- config/locales/errors/en.yml
- config/locales/errors/es.yml
- config/locales/errors/fr.yml
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- spec/controllers/idv/image_uploads_controller_spec.rb
- spec/views/idv/session_errors/throttled.html.erb_spec.rb
[ 🎫 Ticket](https://cm-jira.usa.gov/browse/LG-9294)
Add link to throttled error page enabled rate limited user to link back to SP using defined failure to proof url
- removed the failure to proof url from the action/secondary actions
- added failure to proof url in the paragraph error
- add progress bar
<details>
</details>
<details>
</details>
> LG-9294 Rate limit for 'Verify your ID' must include a link back to SP

- app/javascript/packages/normalize-yaml/package.json
- app/javascript/packages/rails-i18n-webpack-plugin/package.json
- yarn.lock
Resolves the following vulnerability:
```
yarn audit v1.22.19
│ high          │ Uncaught Exception in yaml                                   │
│ Package       │ yaml                                                         │
│ Patched in    │ >=2.2.2                                                      │
│ Dependency of │ @18f/identity-normalize-yaml                                 │
│ Path …
```
> Upgrade JS YAML package to resolve security advisory

- app/javascript/packages/document-capture/components/document-capture-troubleshooting-options.spec.tsx
- spec/javascript/packages/document-capture/components/review-issues-step-spec.jsx
Looks like https://github.com/18F/identity-idp/pull/8321 was merged after https://github.com/18F/identity-idp/pull/8317 and the outdated values are causing tests to fail. This PR updates the tests to use the new `new_tab` content.
> Fix javascript tests using updated new_window/new_tab content

- app/controllers/saml_idp_controller.rb
- app/services/analytics_events.rb
- spec/controllers/saml_idp_controller_spec.rb
- spec/features/saml/saml_spec.rb
Similar to #8261 to add some more information about the types of SAML requests we receive when we log them
> Add SAML authentication request attributes to logging metadata

- app/controllers/idv/ssn_controller.rb
- app/services/idv/steps/in_person/address_step.rb
- app/services/idv/steps/in_person/ssn_step.rb
- app/services/idv/steps/in_person/state_id_step.rb
- app/services/idv/steps/threat_metrix_step_helper.rb
- spec/features/idv/in_person_spec.rb
- spec/forms/idv/ssn_format_form_spec.rb
- spec/services/idv/steps/in_person/address_step_spec.rb
[LG-9326](https://cm-jira.usa.gov/browse/LG-9326)
Handles the following verify scenarios when double address verification is enabled:
[Scenario 3:](https://www.figma.com/file/t3pPLpCfEyHcVoX7QbTpQV/Milestone-2---Double-Address-Verification?node-id=606-19645&t=yKPNADYQSWU1l2j8-0) Given a user who indicated IS LISTED and clicks Update for Current residential address ("Yes" to "No-ish")
- When a user clicks Update on the Verify your info page, change their radio selection from IS LISTED to IS NOT LISTED on both the backend and frontend
- Route user to Update your current residential address page
- When user click Update, route user back to the Verify info page and show their updates to the Residential address section (if any updates were made)
[Scenario …
> LG-9326: Implement DAV verify workflows

- app/services/proofing/aamva/authentication_client.rb
- app/services/proofing/aamva/verification_client.rb
- spec/services/proofing/aamva/authentication_client_spec.rb
- spec/services/proofing/aamva/verification_client_spec.rb
We are seeing some test flakiness due to the token being stored in a mutex that is not cleared between tests and it can create different states for different tests depending on the order they run. This PR moves the token storage to `Rails.cache` and relies on it to handle writing and expiration of the token.
The mutex looks to originate from the [original implementation](https://github.com/18F/identity-aamva-api-client-gem/pull/1/files#diff-4f2b27308e24f75d1c085fe627286b9c10e79fae844a6012d9fe8e0032f22df2R12-R23) of the AAMVA client.
[Slack discussion](https://gsa-tts.slack.com/archives/C0NGESUN5/p1683140569799729?thread_ts=1683140405.486229&cid=C0NGESUN5), [CI Example Failure 1](https://gitlab.login.gov/lg/identity-idp/-/jobs/447217), [CI Example Failure …
> Store AAMVA tokens in Rails.cache instead of behind an application mutex

- .gitlab-ci.yml
- app/services/throttle.rb
- docs/local-development.md
- spec/controllers/idv/phone_errors_controller_spec.rb
- spec/features/users/sign_up_spec.rb
Last week's infrastructure deploy included the upgrade from Redis 6 to Redis 7 (https://github.com/18F/identity-devops/pull/5751). With the upgrade complete and settled in, we can make use of the new Redis 7 command that should be a bit more stable for our usage.
> Use Redis 7 EXPIRETIME command for calculating rate limit state

- app/controllers/idv/session_errors_controller.rb
- app/views/idv/session_errors/throttled.html.erb
- spec/controllers/idv/session_errors_controller_spec.rb
Intends to address a bug in https://github.com/18F/identity-idp/pull/8291 where users viewing a rate limit error would see a 500 error because the step indicator concern relies on session data that doesn't exist when a user is in the hybrid flow
[Slack discussion](https://gsa-tts.slack.com/archives/C0NGESUN5/p1683225941919019?thread_ts=1683224465.791789&cid=C0NGESUN5)
> Remove step indicator concern from idv sessions error

- app/views/partials/multi_factor_authentication/_mfa_selection.html.erb
- app/views/users/mfa_selection/index.html.erb
- app/views/users/two_factor_authentication_setup/index.html.erb
- spec/features/accessibility/user_pages_spec.rb
- spec/support/matchers/accessibility.rb
- spec/views/partials/multi_factor_authentication/_mfa_selection.html.erb_spec.rb
[LG-9424](https://cm-jira.usa.gov/browse/LG-9424)
Updates the labels associated with MFA setup choices so that they are more succinct and non-repetitive, and so that additional descriptive content is read as a descriptor (using `aria-describedby`), allowing essential role information to be shared sooner.
Recommend reviewing with whitespace changes hidden: https://github.com/18F/identity-idp/pull/8327/files?w=1
3. Continue through account creation until the MFA selection screen
4. Activate screen reader
5. Navigate checkbox options
Screenshots via Chrome's Accessibility DevTools inspector:
Before|After
---|---
> LG-9424: Simplify MFA setup option labels

- app/presenters/openid_connect_user_info_presenter.rb
- spec/presenters/openid_connect_user_info_presenter_spec.rb
https://cm-jira.usa.gov/browse/LG-6355
Fixes bug where server throws a 500 if an unverified user tries to log into a service provider using the OIDC protocol and an IALMax service level.
> LG-6355 Update presenter to skip ial2 data if no data is present

- Makefile
- scripts/migration_check
One of the items in our incident review of [2023-04-13 Unsafe Migration](https://docs.google.com/document/d/1a5Blx8a4MMPbhvOBMRYmzJBpEvMJ8RCiozXB0gDjEnA/edit) was to prevent us from using the default migration folder (as in https://github.com/18F/identity-idp/pull/8175) since it will not be run by the migration script.
I've added https://github.com/18F/identity-idp/commit/fefc13cf434eaaf7c81fb93d518694a2619f644f initially to make sure it fails.
> Add lint for migrations folder

- app/controllers/frontend_log_controller.rb
- app/services/analytics_events.rb
- app/views/idv/doc_auth/agreement.html.erb
- spec/features/idv/analytics_spec.rb
- spec/views/idv/doc_auth/agreement.html.erb_spec.rb
[LG-7184](https://cm-jira.usa.gov/browse/LG-7184)
Wrap the consent checkbox on the IdV agreement step in a `ClickObserverComponent` and log an event on toggles. 
The new event will be `IdV: Consent checkbox toggled`.
> LG-7184: Add analytics event for consent checkbox toggles

- app/javascript/packages/components/full-screen.spec.tsx
- app/javascript/packages/components/full-screen.tsx
- app/views/accounts/_mobile_nav.html.erb
- config/locales/account/en.yml
- config/locales/account/es.yml
- config/locales/account/fr.yml
- config/locales/users/en.yml
- config/locales/users/es.yml
- config/locales/users/fr.yml
- spec/javascript/packages/document-capture/components/acuant-capture-spec.jsx
Fixes an issue where the mobile navigation on the account dashboard unintentionally allows horizontal scroll, when only vertical scrolling is expected. This is due to the markup not aligning to the [documented code](https://designsystem.digital.gov/components/header/#component-code-3) for the component.
**Before:**
https://user-images.githubusercontent.com/1779930/236556106-ca376802-be58-43eb-808d-152540473f44.MP4
**After:**
https://user-images.githubusercontent.com/1779930/236556116-73c28e12-68ae-4a48-9830-44fc6dc1e87c.MP4
> Fix mobile navigation to prevent horizontal scroll

- app/assets/stylesheets/_uswds.scss
Fixes a visual regression introduced in #8093, affecting one of the 3 Sign-In page A/B test variants ("Tabbed"). Fortunately, the design system upgrade has not shipped yet in production, so the bug is not live.
#8093 takes advantage of USWDS' new per-component stylesheet optimization feature, opting in to only the components currently in use. Because of overlapping timeframe of #8093 and #8112 and the fact that the A/B test is not shown in all cases, the "Button Group" component was not included.
I also made another pass at trying to find components potentially in use that are not included, and did not find others.
Easier to test when forcing Tabbed variant 100% of the time, adding this to `config/application.yml`:
```
sign_in_a_b_testing: '{"tabbed":100}'
```
Before|After
---|---
> Fix Sign In tabbed A/B variant after LGDS 7

- app/views/idv/phone_errors/warning.html.erb
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- spec/features/idv/steps/phone_step_spec.rb
- spec/views/idv/phone_errors/warning.html.erb_spec.rb
[LG-9299](https://cm-jira.usa.gov/browse/LG-9299)
As a user undergoing IDV who is unsuccessful at the Verify your personal details step, I want to have a clear way to cancel identity verification and return to the requesting SP.
- Remove “Get help at [Partner Agency]” link
- Add “Cancel” experience
<details>
</details>
<details>
</details>
> LG-9299: Add Cancel Link to Phone Error Page

- app/controllers/idv/review_controller.rb
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- spec/controllers/idv/review_controller_spec.rb
[LG-9648](https://cm-jira.usa.gov/browse/LG-9648)
Clearer wording for phone verification success banner on Enter Password screen, and don't show it for users waiting to verify via US mail.
<details>
</details>
> LG-9648 success banner on Enter Password screen

- app/services/proofing/lexis_nexis/authenticated_request.rb
- app/services/proofing/lexis_nexis/ddp/proofer.rb
- app/services/proofing/lexis_nexis/ddp/verification_request.rb
- app/services/proofing/lexis_nexis/instant_verify/proofer.rb
- app/services/proofing/lexis_nexis/instant_verify/verification_request.rb
- app/services/proofing/lexis_nexis/phone_finder/proofer.rb
- app/services/proofing/lexis_nexis/phone_finder/verification_request.rb
- app/services/proofing/lexis_nexis/request.rb
- spec/services/proofing/lexis_nexis/ddp/proofing_spec.rb
- spec/services/proofing/lexis_nexis/ddp/verification_request_spec.rb
- spec/services/proofing/lexis_nexis/instant_verify/verification_request_spec.rb
- spec/services/proofing/lexis_nexis/phone_finder/verification_request_spec.rb
- spec/support/lexis_nexis_fixtures.rb
- spec/support/shared_examples/lexis_nexis.rb
[LG-8115](https://cm-jira.usa.gov/browse/LG-8115)
The ThreatMetrix DDP API does not require any auth headers (basic or hmac) so let's stop sending them.
> LG-8115: don't require any auth headers for DDP.

- app/jobs/get_usps_proofing_results_job.rb
- spec/jobs/get_usps_proofing_results_job_spec.rb
related to [LG-8645](https://cm-jira.usa.gov/browse/LG-8645)
Small refactor to rename a method in GetUspsProofingResultsJob and improve tests for the class.
> LG-8645 – Rename GetUspsProofingResultsJob method and improve tests

- lib/data_pull.rb
- spec/lib/data_pull_spec.rb
Follow-up to https://github.com/18F/identity-idp/pull/8359#issuecomment-1540758837
Example spec failure, this works around it by truncating timestamps to have less drift (usually this comes from roundtrips to the database)
```
(compared using ==)
Diff:
@@ -1,9 +1,9 @@
[["uuid", "email", "confirmed_at"],
["16ccac88-7993-4cbe-9cc1-06ca84948720",
"user246@example.com",
-  2023-05-09 12:53:00.664757000 -0600],
+  2023-05-09 12:53:00.664756000 -0600],
```
> Fix flaky data-pull tests by truncating timestamps

- app/controllers/concerns/idv/threat_metrix_concern.rb
- app/controllers/idv/ssn_controller.rb
- spec/controllers/idv/ssn_controller_spec.rb
[LG-9740](https://cm-jira.usa.gov/browse/LG-9740)
This before action is needed to allow ThreatMetrix to load in browsers that respect Content Security Policies. It was part of the Flow State Machine but not clearly part of the SSN step.
Note: The in_person_controller still uses `override_csp_for_threat_metrix` with the parameter check for the ssn step, so I factored out the main part of the code and made a new method for the remote SsnController. This can be restored to a single method when the in_person FSM SsnStep is removed.
Note2: We need a test that checks that ThreatMetrix is loading without errors, either as part of this PR or as a separate PR.
> LG-9740 Add csp overrides for ThreatMetrix before_action to SsnController

- app/controllers/concerns/idv_step_concern.rb
- app/controllers/idv/link_sent_controller.rb
- app/services/idv/steps/upload_step.rb
- app/views/idv/link_sent/show.html.erb
- config/application.yml.default
- config/routes.rb
- lib/identity_config.rb
- spec/controllers/idv/link_sent_controller_spec.rb
- spec/features/idv/doc_auth/link_sent_spec.rb
- spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb
[LG-9494](https://cm-jira.usa.gov/browse/LG-9494)
New LinkSentController behind feature flag will replace LinkSentStep. 
Note: Continue button is visible when link sent polling is off, which is only in tests.
<details>
<summary>New view:</summary>
</details>
> LG-9568 link sent controller

- lib/data_pull.rb
- spec/lib/data_pull_spec.rb
Enables logging to look like this:
| screenshot |
| --- |
| <img width="577" alt="Screen Shot 2023-05-10 at 8 54 02 AM" src="https://github.com/18F/identity-idp/assets/458784/e7719431-8f3c-4129-9ae6-b018192869e0"> |
> Update data-pull audit logging to format better in Slack

- app/views/layouts/base.html.erb
- spec/views/layouts/application.html.erb_spec.rb
[LG-9531](https://cm-jira.usa.gov/browse/LG-9531)
Changes the separator in the `<title>` from a dash ("-") to a bar ("|").
**Why?**
- For consistency with [Login.gov](https://login.gov/) ([source](https://github.com/18F/identity-site/blob/0e3bb36cb7c257ebf539f31fe8cae4d7cf39f8b9/_includes/meta.html#L23))
- For (marginally) improved accessibility ([related article](https://www.standards-schmandards.com/index.html%3Fp=15.html))
2. Observe text in browser tab
Before|After
---|---
> LG-9531: Change title separate from dash to bar

- app/controllers/idv/session_errors_controller.rb
- app/views/idv/session_errors/failure.html.erb
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- spec/controllers/idv/session_errors_controller_spec.rb
- spec/views/idv/session_errors/failure.html.erb_spec.rb
[LG-9295](https://cm-jira.usa.gov/browse/LG-9295)
Tweaks to the rate limit error screen shown on the "Verify your information" step of IdV. Includes:
- Updated heading
- Tweaked body copy
- More prominent "exit" link
<details>
</details>
<details>
</details>
> LG-9295: Rate limit for “Verify your information” must include a link back to SP

- app/views/idv/in_person/ready_to_verify/show.html.erb
- app/views/user_mailer/shared/_in_person_ready_to_verify.html.erb
- config/locales/in_person_proofing/en.yml
- config/locales/in_person_proofing/es.yml
- config/locales/in_person_proofing/fr.yml
- spec/mailers/user_mailer_spec.rb
- spec/views/idv/in_person/ready_to_verify/show.html.erb_spec.rb
[LG-8319](https://cm-jira.usa.gov/browse/LG-8319)
Re-adds the secondary ID instructions to the Ready to Verify page and emails when appropriate. See [this slack thread](https://gsa-tts.slack.com/archives/C04GA9WQ85B/p1683748251597079) for context.
> LG-8319: Re-add the secondary ID instructions to web page and email

- app/views/sign_up/passwords/new.html.erb
- spec/components/javascript_required_component_spec.rb
- spec/views/sign_up/passwords/new.html.erb_spec.rb
[LG-9710](https://cm-jira.usa.gov/browse/LG-9710)
Adds a hidden field to the password creation screen, so that browsers or password managers can associate the newly-created password as a full credential including the user's email address.
3. Continue account creation to the password entry screen
4. Enter and confirm a password
5. Submit
6. Observe if/how the browser prompts you to save the password you just created
Device|Before|After
---|---|---
Chrome (Desktop)|![chrome-before](https://github.com/18F/identity-idp/assets/1779930/5ad77fdc-da38-4a50-a384-bdb2fa533d7d)|![chrome-after](https://github.com/18F/identity-idp/assets/1779930/f6a78155-b14a-4b2a-a751-f196a5f9c09c)
Chrome …
> LG-9710: Add hidden field to associate password with email

- app/controllers/users/phones_controller.rb
- app/services/analytics_events.rb
- spec/controllers/users/phones_controller_spec.rb
[LG-9445](https://cm-jira.usa.gov/browse/LG-9445)
Add the phone setup analytics to phones controller.
> changelog: Internal, Authentication, Add logging for Additional phone setup

- app/controllers/idv/gpo_controller.rb
- app/controllers/idv/gpo_verify_controller.rb
- app/services/idv/gpo_mail.rb
- app/views/idv/gpo_verify/index.html.erb
- config/application.yml.default
- lib/identity_config.rb
- spec/controllers/idv/gpo_controller_spec.rb
- spec/controllers/idv/gpo_verify_controller_spec.rb
- spec/features/idv/steps/gpo_step_spec.rb
- spec/views/idv/gpo_verify/index.html.erb_spec.rb
[LG-9561](https://cm-jira.usa.gov/browse/LG-9561)
Add a new config, `gpo_max_profile_age_to_send_letter_in_days`, which can be used to limit the amount of time after a profile is first created we allow requesting a GPO letter to verify it. The default value for this config is 30 days, calculated from the `created_at` of the `Profile`.
When the user is outside this window of time, they are no longer offered the option to "Send me another letter" on the GPO verification page--they can either enter the OTP that was already mailed to them or restart the proofing process.
> LG-9561: Limit requesting new GPO codes to 30 days after initial request

- app/jobs/address_proofing_job.rb
[LG-8115](https://cm-jira.usa.gov/browse/LG-8115)
In previous PRs, missed this config for the PhoneFinder proofer.
> LG-8115: configure the PhoneFinder proofer for HMAC auth

- .stylelintrc.json
- app/javascript/packages/build-sass/CHANGELOG.md
- app/javascript/packages/build-sass/README.md
- app/javascript/packages/build-sass/fixtures/css-scss-extension/.gitignore
- app/javascript/packages/build-sass/fixtures/scss-extension/.gitignore
- app/javascript/packages/build-sass/index.js
- app/javascript/packages/build-sass/index.spec.js
Enhances `@18f/identity-build-sass` to remove the requirement for `.css.scss` file naming convention, supporting both `.css.scss` and `.scss`. In either case, output with the basename + `.css`.
This is planned to be used in #8375 to allow components to define accompanying styles with a `.scss` file.
This makes implementations simpler, and avoids tying the tool to Rails asset pipeline conventions.
Included specs pass:
```
yarn mocha app/javascript/packages/build-sass/index.spec.js
```
> build-sass: Add support for ".scss" extension

- app/controllers/idv/link_sent_controller.rb
- spec/controllers/idv/link_sent_controller_spec.rb
[LG-9570](https://cm-jira.usa.gov/browse/LG-9570)
Remove the before action to redirect to 404 page if FF for links controller is disabled.
> LG-9570 Remove LinkSentController 404 action

- app/services/analytics_events.rb
- app/services/usps_in_person_proofing/transliterable_validator.rb
- spec/services/usps_in_person_proofing/transliterable_validator_spec.rb
[LG-9477](https://cm-jira.usa.gov/browse/LG-9477)
Add an analytics event that logs nontransliterable characters that a user submits. An event will be logged for each group of fields where nontransliterable characters are present. The characters are sorted and duplicates are removed. 
> LG-9477 log nontransliterable chars

- app/views/idv/session_errors/warning.html.erb
- config/i18n-tasks.yml
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- spec/features/idv/actions/redo_document_capture_action_spec.rb
- spec/features/idv/doc_auth/verify_info_step_spec.rb
- spec/views/idv/session_errors/warning.html.erb_spec.rb
[LG-9298](https://cm-jira.usa.gov/browse/LG-9298)
- Tweaked heading _could not_ -> _couldn't_
- removed troubleshooting section
-  Removed _to add your ID online_ from the remaining attempts warning message
- added cancel link
<details>
</details>
<details>
</details>
> LG-9298 Warning screen for “Verify your information” should include a way for a user to cancel and return to SP

- app/controllers/concerns/idv_step_concern.rb
- spec/controllers/concerns/idv_step_concern_spec.rb
- spec/factories/users.rb
- spec/features/idv/in_person_spec.rb
- spec/features/idv/steps/gpo_step_spec.rb
[LG-9741](https://cm-jira.usa.gov/browse/LG-9741)
Ensure that users waiting for a letter or in person verification see the correct page when entering Identity Verification. Add before actions to IdvStepConcern, which is included in all the post-FSM controllers. These before actions already existed in doc_auth_controller, where they apply to steps inside the FSM.
Now with added concern and feature specs. Note that the feature specs pass even when the new before actions are commented out because doc_auth_controller still has our backs. These before actions will be needed as we pull more steps out of the FSM.
> LG-9741 Confirm no pending GPO or in person enrollment before actions in IdvStepConcern

- app/controllers/idv/sessions_controller.rb
- app/forms/gpo_verify_form.rb
- app/models/profile.rb
- app/models/user.rb
- app/services/idv/cancel_verification_attempt.rb
- spec/controllers/accounts_controller_spec.rb
- spec/controllers/concerns/idv/step_indicator_concern_spec.rb
- spec/controllers/idv/sessions_controller_spec.rb
- spec/controllers/users/sessions_controller_spec.rb
- spec/features/idv/steps/gpo_otp_verification_step_spec.rb
- spec/features/saml/ial2_sso_spec.rb
- spec/features/users/password_reset_with_pending_profile_spec.rb
- spec/features/users/verify_profile_spec.rb
- spec/forms/gpo_verify_form_spec.rb
- spec/models/profile_spec.rb
- spec/models/user_spec.rb
- spec/presenters/idv/gpo_presenter_spec.rb
- spec/services/idv/cancel_verification_attempt_spec.rb
- spec/support/idv_examples/gpo_otp_verification.rb
[LG-9535](https://cm-jira.usa.gov/browse/LG-9535)
We now read from the new `gpo_verification_pending_at` column for deactivation reasons instead of the old enum.
> LG-9535 Read from new gpo column

- app/views/idv/link_sent/show.html.erb
- spec/features/idv/actions/cancel_link_sent_action_spec.rb
The Back link at the bottom of the new LinkSent page was getting a 404. Needed to set its step_url parameter to idv_doc_auth_step_url instead of idv_doc_auth_url
Also add a feature test for the cancel link sent action with the feature flag enabled.
> LG-9369 Fix new link_sent page back link

- spec/factories/users.rb
- spec/features/idv/threat_metrix_pending_spec.rb
- spec/lib/tasks/review_profile_spec.rb
This commit adds a test that tests that a user who went through fraud review and either expired or was explicitly reject cannot enter the IdV flow.
The tests in the codebase prior to this change cover the fraud pending state. The fraud rejection state is slightly different and we track differently.
> Test that a fraud rejected user cannot enter the IdV flow

- app/assets/stylesheets/_required.scss
- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/components/_icon.scss
- app/assets/stylesheets/components/_language-picker.scss
- app/assets/stylesheets/components/_list.scss
- app/assets/stylesheets/components/_personal-key.scss
- app/assets/stylesheets/components/_phone-input.scss
- app/assets/stylesheets/components/_step-indicator.scss
Changes `url(...)` to reference assets using absolute (slash-prefixed) paths, in hopes of fixing issues observed in deployed environments, and following related migration guidance:
>[...]Propshaft assumes all paths are relative to the path of the file it’s processing. Since it was processing a css file inside the theme folder, it will also look for hero.jpg in the same folder.
>
>By adding a / at the start of the path we are telling Propshaft to consider this path as an absolute path.
https://github.com/rails/propshaft/blob/main/UPGRADING.md#3-migrate-from-sprockets-to-propshaft
2. Observe ⬇️ caret image next to "Here's how you know in banner"
> Try absolute path for Propshaft assets

- app/services/idv/actions/redo_document_capture_action.rb
- app/services/idv/steps/upload_step.rb
- spec/features/idv/actions/redo_document_capture_action_spec.rb
[LG-9369](https://cm-jira.usa.gov/browse/LG-9369)
Check telephony errors when sending text from "Upload" step before redirecting to LinkSent step.
Also explicitly redirect to idv_document_capture_url when skipping upload in RedoDocumentCaptureAction.
> Two fixes for new LinkSentController

- app/decorators/service_provider_session_decorator.rb
- spec/decorators/service_provider_session_decorator_spec.rb
- spec/views/shared/_nav_branded.html.erb_spec.rb
Fixes an error which can happen if the logo associated with a service provider cannot be resolved.
Related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1684269870234819
The problems are:
- The error handler was added in #8387, where previously the method always returned from `image_path`. The logic of `image_path` always returns a string, even if not found ([source](https://github.com/rails/rails/blob/8015c2c2cf5c8718449677570f372ceb01318a32/actionview/lib/action_view/helpers/asset_url_helper.rb#L190)), but we returned `nil` instead in the error handler.
- Spec coverage was lacking:
- We thought we were testing for a string return value, but there was a bug in the assertion (see `.is_a?` change)
- We had no spec coverage for this scenario in the `_nav_branded.html.erb` …
> Fix handling for missing SP logo

- app/models/user.rb
- lib/tasks/review_profile.rake
- spec/models/user_spec.rb
A previous commit (#8397) introduced the `FraudReviewChecker` which includes a method for checking that a user is eligible for fraud review. It did not end up getting used in the rake task where that check is performed. This commit does that and removes the old method from the user model.
> LG-9726 Use the fraud review checker in the place of fraud_review_eligible

- app/services/proofing/aamva/proofer.rb
- spec/services/proofing/aamva/proofer_spec.rb
Continue to log any other errors.
[LG-9596](https://cm-jira.usa.gov/browse/LG-9596)
If the exception raised in the processing of an AAMVA request is a TimeoutError, don't log it to NewRelic.
> LG-9596: Stop logging AAMVA timeout errors to NewRelic

- lib/data_pull.rb
The default is `true` (yes, include missing rows) so this just catches that up
> Update data-pull documentation

- lib/pinpoint_supported_countries.rb
Adds France to Pinpoint Sender ID countries, to fix deliverability.
Related Slack discussion: https://gsa-tts.slack.com/archives/C01710KMYUB/p1684415891996059
> Add France to Pinpoint Sender ID countries

- app/controllers/two_factor_authentication/webauthn_verification_controller.rb
- app/controllers/users/backup_code_setup_controller.rb
- app/controllers/users/phone_setup_controller.rb
- app/controllers/users/totp_setup_controller.rb
- app/controllers/users/webauthn_setup_controller.rb
We currently define `handle_remember_device` 4 times in the exact same, including in the shared `TwoFactorAuthenticatableMethods` module. The same is true for `user_opted_remember_device_cookie` (but 6 times).
This PR removes the extra definitions and pulls in the shared module so they can share a common definition of these methods.
> Consolidate handle remember device method definitions

- app/controllers/concerns/two_factor_authenticatable_methods.rb
- app/controllers/two_factor_authentication/otp_verification_controller.rb
A small follow-up to #8347 to move some phone-specific functionality out of `TwoFactorAuthenticationMethods`. The path is a little bit circuitous with calling `handle_valid_otp` and a `confirmation` state in `UserSessionContext`, but the `track_mfa_method_added` method defined is only used when confirming a phone. The big clue is that the method name sounds general, but turns out to be specific to confirming a phone.
This PR pulls that method definition into the `OtpVerificationController` and calls it when confirming a phone.
> Refactor handling of successful two-factor phone confirmation

- app/jobs/get_usps_proofing_results_job.rb
- app/models/profile.rb
- spec/lib/tasks/review_profile_spec.rb
- spec/support/sp_auth_helper.rb
We should not be activating profiles that have a deactivation reason. The logic for that looks like it got mixed up when we were doing the fraud review work. Specifically the code to check for a deactivation reason does not actually look at the deactivation reason column anymore.
This commit addresses the above.
> Check for a deactivation reason before activating a profile

- docs/local-development.md
When trying to find my IP address on my machine, I had to go through some extra steps to get my IP address. I edited it so that it could help someone else.
Test plan: Follow the below instructions
- Go to System Preferences 
- Click "Network"
- Select "Wi-Fi" or "Ethernet". This will change based on the type of connection you are using
- Click "Details"
From here, you should see your IP address. Change the `domain_name` and `mailer_domain_name` as laid out in `local-development.md`. Run `HOST=0.0.0 make run` to access the site.
> Documentation: Add details on how to find IP address on macOS

- app/services/db/monthly_sp_auth_count/total_monthly_auth_counts.rb
When running `rubocop`, there is a warning that we are using the wrong namespace when enabling/disabling `LineLength`. It looks to have been changed quite awhile ago in `0.78.0` (2019-12-18).
This PR fixes it.
```
$ rubocop
app/services/db/monthly_sp_auth_count/total_monthly_auth_counts.rb: Metrics/LineLength has the wrong namespace - should be Layout
app/services/db/monthly_sp_auth_count/total_monthly_auth_counts.rb: Metrics/LineLength has the wrong namespace - should be Layout
```
> Fix Rubocop namespace warning

- spec/features/idv/confirm_start_over_spec.rb
This PR fixes a test failure that was introduced to main from a recent merged PR. The issue was to do with how user profiles for GPO pending states are now determined (using a timestamp). CI did not catch this because the PR branch was not rebased on main prior to merge, and there were no other conflicts.
> Updating how gpo pending is set in dummy profile

- lib/data_pull.rb
**Why**: -r is "eaten" as a shorthand for --reason in the [calling script in the devops repo](https://github.com/18F/identity-devops/blob/eee825f5d8de2b56a7c0f8520224eb71a7eb5b2d/bin/data-pull#L49)
> data-pull script: Switch -r flag to be -i

- app/views/users/backup_code_setup/create.html.erb
- spec/features/two_factor_authentication/backup_code_sign_up_spec.rb
[LG-9633: Show Backup code download button for mobile users](https://cm-jira.usa.gov/browse/LG-9633)
Mobile users are able to see the download button. 
An example of this now in mobile mode is below.
> LG-9633: make backup code download available in mobile

- app/services/analytics_events.rb
I came across these while looking for something and they bugged me.
None, unless this is a mandatory field?
> Fixes some trivial typos in comments

- app/models/profile.rb
- spec/features/idv/steps/gpo_otp_verification_step_spec.rb
Because otherwise we get a 500 when entering a gpo code and trying to activate the profile.
This is a followup to #8432 which raises an exception if the profile has a deactivation reason when activation is attempted.
We found that the feature test for gpo code activation did not break because the test data does not match the current data model as we change over from deactivation reason to gpo_verification_pending_at.
> Remove deactivation_reason in Profile#remove_gpo_deactivation_reason

- config/routes.rb
With #8393 we introduced a new interstitial screen with its own route, which should be under the GPO namespace. I made a mistake and forgot to include `/verify/` in the path (which for the moment indicates the GPO namespace). This PR rectifies the oversight.
> Bugfix: Updating GPO confirm cancel route path

- app/components/memorable_date_component.html.erb
- spec/components/memorable_date_component_spec.rb
[LG-9767](https://cm-jira.usa.gov/browse/LG-9767)
Adds span to memorable date component groups so that a screen reader reads out "Date of birth" before the month, day and year group.
> LG-9767 add span to groups that allows sr to read out dob before date components

- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
[LG-9805](https://cm-jira.usa.gov/browse/LG-9805)
Update the validation error message for the SSN textfield to not display error message with # and hyphens but to say that a nine digit number is required.
<details>
</details>
<details>
</details>
> LG-9805: SSN input error messaging should be updated

- app/views/idv/gpo_verify/index.html.erb
- spec/features/idv/confirm_start_over_spec.rb
- spec/features/idv/in_person_spec.rb
- spec/support/idv_examples/clearing_and_restarting.rb
Previous commits introduced a new screen for confirming you want to cancel IdV. Unfortunately this is not backwards compatible with the 50/50 state. The proper way to deploy this is:
1. Add the new page at an accessible route
2. Start redirecting users to the new route
3. Tear down any code that supported the old approach
This commit winds everything back to step 1 by making the new functionality available but not redirecting users to the new page.
Note that this particular change does not need step 3 since there actually is not an old route to remove. This adds an interstitial page that contains a form to make a request to a route that users are already using.
> Make the confirrm start over change backwards compatible

- app/services/proofing/aamva/proofer.rb
- app/services/proofing/aamva/response/verification_response.rb
- app/services/proofing/state_id_result.rb
- spec/services/proofing/aamva/proofer_spec.rb
- spec/services/proofing/aamva/verification_client_spec.rb
[LG-9828](https://cm-jira.usa.gov/browse/LG-9828)
Includes `Proofing::StateIdResult#mva_timeout?` to allow checking for MVA timeouts (as opposed to AAMVA timeouts).
BONUS: stop sending VerificationErrors to NewRelic if caused by a MVA timeout
> LG-9828: add mva_timeout? method to AAMVA proofer result

- docs/Docker.md
Finding this Docker documentation on its own, without coming to it from the `local-development.md` note about Docker deprecation, can be confusing. The doc gives the appearance Docker is being actively used by the project.
Adding a link to the deprecation explanation so that it is clear.
[See this Slack thread for more details](https://gsa-tts.slack.com/archives/C0NGESUN5/p1684517846543419).
> Add note about deprecation of Docker use in docs

- app/views/idv/gpo_verify/index.html.erb
- spec/features/idv/confirm_start_over_spec.rb
- spec/features/idv/in_person_spec.rb
- spec/support/idv_examples/clearing_and_restarting.rb
In #8448 I removed the link to the confirm start over screen to maintain backwards compatibility. Now that that change is deployed to production we can start directing users to the new screen. This commit makes that change.
> Re-enabled the confirm start over screen

- app/controllers/concerns/two_factor_authenticatable_methods.rb
- app/controllers/two_factor_authentication/backup_code_verification_controller.rb
- app/controllers/two_factor_authentication/personal_key_verification_controller.rb
- app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
- app/controllers/two_factor_authentication/webauthn_verification_controller.rb
This method is used for more than OTPs and brings it in line with the renaming for `handle_valid_verification_for_confirmation_context` in #8431.
> Rename handle_valid_otp_for_authentication_context to handle_valid_verification_for_authentication_context

- app/controllers/idv/document_capture_controller.rb
- spec/controllers/idv/document_capture_controller_spec.rb
The document capture controller no longer uses the FSM. It does, however, check that the upload step in the flow state machine is complete. Prior to this commit it checks that the step is marked complete in the flow session. This means that we need to continue marking the step complete in an eventual upload step replacement.
This commit changes the way that we check that the step is complete to look that the `flow_path` has been set. This brings the upload step completion in line with the new link sent controller.
> Use the presence of the flow path in the session as a proxy for upload step completion

- app/services/analytics_events.rb
- app/services/idv/flows/in_person_flow.rb
- spec/features/idv/analytics_spec.rb
[LG-7893](https://cm-jira.usa.gov/browse/LG-7893)
This pr adds the appropriate properties to some of the ipp analytics events in order to update the cloud pages handbook documentation on analytics events. The following events should be updated:
idv_in_person_proofing_address_submitted
idv_in_person_proofing_address_visited 
idv_in_person_proofing_cancel_update_address 
idv_in_person_proofing_cancel_update_state_id 
idv_in_person_proofing_redo_state_id_submitted
idv_in_person_proofing_state_id_submitted 
idv_in_person_proofing_state_id_visited
> LG-7893 add properties to analytics events

- app/controllers/application_controller.rb
- app/controllers/concerns/backup_code_reminder_concern.rb
- app/controllers/concerns/verify_profile_concern.rb
The verify profile concern is intened to redirect users with profiles that need additional work to verify or unlock to the appropriate place. The backup code reminder logic got mixed into this which causes a little confusion and indirection. This commit moves that logic into its own concern.
> Remove the backup code logic from the verify profile concern

- app/controllers/application_controller.rb
- app/controllers/concerns/verify_profile_concern.rb
- app/controllers/openid_connect/authorization_controller.rb
- app/controllers/saml_idp_controller.rb
- app/models/user.rb
- spec/controllers/saml_idp_controller_spec.rb
We have made changes to the `pending_profile` concept in the IdP. Previously a profile was pending if the user was waiting on GPO verification. We have added more out of band flows which result in more pending reasons:
1. GPO Verification
2. Fraud review
3. In-person proofing
This logic got spread throughout the codebase in ways that were often kind of tough to follow. This led to lots of bugs trying to send the user to the right place to finish proofing.
This commit collects that logic in the `VerifyProfileConcern`. This was chosen because this is where much of the logic for the GPO confirmation flow lived already.
> Use the verify profile concern to sort through all of the reasons a user may be pending

- app/models/user.rb
- spec/features/idv/steps/gpo_step_spec.rb
- spec/support/idv_examples/clearing_and_restarting.rb
We made changes to the app to do some of the work for finding a pending profile in a SQL query. We inspect this pending profile value frequently in the course of a request. This commit memoizes the value so we aren't making unnecessary trips to the DB.
> Memoize the `pending_profile` value

- app/components/password_confirmation_component.html.erb
- app/components/password_confirmation_component.scss
- app/views/devise/passwords/edit.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/event_disavowal/new.html.erb
- app/views/idv/review/new.html.erb
- app/views/mfa_confirmation/new.html.erb
- app/views/users/delete/show.html.erb
- app/views/users/passwords/edit.html.erb
- app/views/users/verify_password/new.html.erb
- spec/components/password_confirmation_component_spec.rb
- spec/components/previews/password_confirmation_component_preview.rb
[LG-9709](https://cm-jira.usa.gov/browse/LG-9709)
Adds `autocomplete` attributes to every password field in the application, set to either `new-password` or `current-password` based on context of the field's usage.
- https://web.dev/sign-in-form-best-practices/#new-password
- https://web.dev/sign-in-form-best-practices/#current-password
- https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#sect14
- https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#sect15
The practical impact of this can be improved autofill options offered by the browser. See screenshots for an example.
- Verify that autocomplete still works as expected in your browser for affected password fields.
Example showing effect of `[autocomplete=new-password]` in …
> LG-9709: Add autocomplete attribute to password fields

- Makefile
- bin/setup
Do people like this? This is a little bit of a ragecoded thing.
I realized my identity-idp clone was using over 4GB of disk space. The bulk of the ridiculous stuff was:
- More than 1GB of test Attempts API log files, a unique one-off I cleaned up
- 1.6 GB of vendor/bundle/ stuff
- 700MB of logs
I wanted something like `make tidy` to exist, but it was somewhat duplicative of what `make setup` does. I don't like running `make setup` often because it's kind of heavy-handed and I don't want to mess with my DB. So I moved the relevant parts into individual Makefile targets.
This is purely a "I want this to exist" thing, so if it's contentious I'm fine withdrawing it.
> Adds make tidy

- app/views/idv/doc_auth/upload.html.erb
- spec/services/idv/steps/upload_step_spec.rb
[LG-9830](https://cm-jira.usa.gov/browse/LG-9830)
Remove the combined parameter for the upload step page url when send link submissions are rate limited.
Before:
example.com/verify/doc_auth/upload?**combined=true**&type=mobile
After:
example.com/verify/doc_auth/upload?type=mobile
<details>
</details>
<details>
</details>
> Remove combined params from mobile upload step url

- config/initializers/telephony.rb
- lib/telephony/configuration.rb
- lib/telephony/pinpoint/sms_sender.rb
- spec/lib/telephony/pinpoint/sms_sender_spec.rb
- spec/lib/telephony/pinpoint_configuration_spec.rb
- spec/support/shared_contexts/telephony.rb
Adds support for using specific shortcodes for a given country code.
> Allow configuring shortcodes for international country codes (LG-9839)

- app/controllers/concerns/remember_device_concern.rb
- app/controllers/concerns/two_factor_authenticatable_methods.rb
- app/controllers/two_factor_authentication/backup_code_verification_controller.rb
- app/controllers/two_factor_authentication/otp_verification_controller.rb
- app/controllers/two_factor_authentication/personal_key_verification_controller.rb
- app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
- app/controllers/two_factor_authentication/totp_verification_controller.rb
- app/controllers/two_factor_authentication/webauthn_verification_controller.rb
- app/controllers/users/piv_cac_login_controller.rb
- spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
- spec/controllers/users/piv_cac_login_controller_spec.rb
- spec/support/controller_helper.rb
Following up in what is hopefully the last series of changes for this (see #8347, #8316, #8315, #8037, #8031). Currently, the session "confirmation context" is only used by phone OTP verification, so this PR splits that specific functionality out of the shared concern and into the controller. With that, we can call `handle_valid_verification_for_confirmation_context`/`handle_valid_verification_for_authentication_context` explicitly within the 2FA controller depending on whether it is a setup controller or verification controller.
Some of the existing 2FA controllers also implemented their own version of `mark_user_as_fully_authenticated` to set values in the session, and this PR consolidates the behavior into the shared concern and has all of the controllers use that via `handle_valid_`. …
> Remove handle_valid_otp method

- .gitlab-ci.yml
This fixes a problem where using parallelization over 11 caused
account deletion email specs to fail.  
<details> <summary>(Failing account deletion email specs here.)</summary>
~~~
Failures:
1) Account Reset Request: Delete Account as an IAL1 user sends push notifications if push_notifications_enabled is true
Failure/Error: open_last_email
RuntimeError:
No email has been sent!
2) Account Reset Request: Delete Account as an IAL1 user allows the user to delete their account after 24 hours
Failure/Error: open_last_email
RuntimeError:
No email has been sent!
3) Account Reset Request: Delete Account logs IRS attempts api events allows the user to delete their account after 24 hours and log irs event
Failure/Error: open_last_email
RuntimeError:
No email has been sent!
~~~
</details>
Correction …
> CI speedup with support for more parallel jobs

- app/forms/gpo_verify_form.rb
- lib/tasks/fix_in_person_pending_user.rake
- spec/forms/gpo_verify_form_spec.rb
We had a bug where users who are in the GPO pending state did not have that state cleared after entering a successful code and going through in-person proofing. This resulted in an error attempting to activate these users profiles when the enrollments background job runs.
changelog: Improvements, In-person proofing, A bug in which users who were letter and in-person pending did not have their letter pending status cleared after entering a letter code resulting in the user not being proofed after visiting the post office was fixed.
> LG-9959 Fix a bug in which in-person and GPO pending users do not have GPO pending status cleared

- app/assets/stylesheets/_uswds-form-controls.scss
Replaces the [default set of design system form control styles](https://github.com/uswds/uswds/blob/develop/packages/uswds-form-controls/_index.scss) with a subset of those in active use.
Included:
- checkbox
- error-message
- fieldset
- file-input
- form-group
- hint
- input
- label
- legend
- memorable-date
- radio
- select
**Edit:** Included from[ LGDS custom form controls](https://github.com/18F/identity-design-system/blob/main/src/scss/packages/_uswds-form-controls.scss):
- success-message
Excluded:
- character-count
- combo-box
- date-picker
- form
- input-prefix-suffix
- input-mask
- range
- textarea
- time-picker
```
NODE_ENV=production yarn build:css && brotli-size app/assets/builds/application.css
```
Before: 29.4kb
After: 27.2kb
Diff: -2.2kb (-7.5%)
- Check the list above: …
> Cherry-pick design system form control styles

- app/components/one_time_code_input_component.html.erb
- app/components/one_time_code_input_component.rb
- app/views/idv/otp_verification/show.html.erb
- app/views/two_factor_authentication/otp_verification/show.html.erb
- app/views/two_factor_authentication/totp_verification/show.html.erb
- app/views/users/totp_setup/new.html.erb
- spec/components/one_time_code_input_component_spec.rb
- spec/components/previews/one_time_code_input_component_preview.rb
- spec/features/idv/phone_otp_rate_limiting_spec.rb
- spec/features/two_factor_authentication/sign_in_spec.rb
Improves `OneTimeCodeInputComponent`'s pattern and prefix handling:
- Enforces code length in pattern
- Previously, you could enter 5 digits for an OTP and it was considered valid
- Makes prefix behavior opt-in, since this requires special back-end handling
- Previously, TOTP code fields allowed the `#` prefix, but it was not valid, and prevented entering the full code due to `maxlength` restriction
Run included spec revisions:
- `rspec spec/components/one_time_code_input_component_spec.rb`
- `rspec spec/features/two_factor_authentication/sign_in_spec.rb:268`
Verify no regressions in OTP entry.
> Improve one-time code pattern enforcement, prefix handling

- .stylelintrc.json
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_phone-input.scss
Updates Stylelint configuration to report needless inline configuration for disabling rules, to avoid misleading developers with ineffective configuration.
I considered adding this to the `@18f/identity-stylelint-config` common configuration, but since it's a breaking change, it'd be best to wait to group it with some other breaking change for the package.
1. `yarn lint:css` passes.
> Configure Stylelint to report needless disables

- app/controllers/concerns/remember_device_concern.rb
- app/controllers/concerns/two_factor_authenticatable_methods.rb
- app/controllers/password_capture_controller.rb
- app/controllers/two_factor_authentication/backup_code_verification_controller.rb
- app/controllers/two_factor_authentication/otp_verification_controller.rb
- app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
- app/controllers/two_factor_authentication/totp_verification_controller.rb
- app/controllers/two_factor_authentication/webauthn_verification_controller.rb
- app/controllers/users/piv_cac_login_controller.rb
A little bit of cleanup following #8392. The `after_otp_verification_confirmation_url` function only behaves differently in the `OtpVerificationController` when in the confirmation context due to the prior work. The `@next_mfa_setup_path` and `@updating_existing_number` instance variables are only set there, which is what results in the different behavior.
This PR removes those instance variables and replaces the `after_otp_verification_confirmation_url` with the default `after_sign_in_path_for(current_user)` in the other controllers that used it. This should not result in a change in behavior and hopefully results in a little bit less abstraction.
> Remove after_otp_verification_confirmation_url

- app/assets/stylesheets/components/_form.scss
Removes styles associated with `[type="number"]` input fields (see [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-outer-spin-button)).
Why?
- To the best of my knowledge, there are no `[type="number"]` fields in the application
- Reduce size of application stylesheet to improve performance
- Improve maintainability by...
- Eliminating styles where the intended impact is unclear
- Aligning closer to design system defaults
We could reintroduce in the future if the need arises, but I think it's worth a reevaluation anyways, and we'd want to scope it to specific instances (e.g. via component stylesheet).
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#using_number_inputs
- >The `number` input type should only be used …
> Remove styles associated with numeric input fields

- .gitignore
- Brewfile
- bin/setup
- docs/local-development.md
We're looking at adding a dependency soon, which could cause some issues
with local development for folks if they didn't know they need to
manually install it. We thought adding a `Brewfile` and having the setup
script run `brew bundle` would help mitigate the difficulties of that
change. There's a bonus in that it's self documenting too!
It would also:
- make initial setup for new developers much more straightforward
- make future changes to dependencies easier to manage
- prevents a mixture of dependencies installed in different ways (for
instance, I think when I initially set things up I ended up with one
version of postgres downloaded manually from the doc-linked site, and
another via homebrew)
Notes:
- As pointed out by @pauldoomgov, we use [postgres@13 in …
> Brewfile for dependency management

- app/controllers/concerns/idv_session.rb
- app/controllers/concerns/idv_step_concern.rb
- app/controllers/concerns/rate_limit_concern.rb
- app/controllers/idv/document_capture_controller.rb
- app/controllers/idv_controller.rb
- spec/controllers/concerns/idv_step_concern_spec.rb
- spec/controllers/concerns/rate_limit_concern_spec.rb
- spec/controllers/idv/document_capture_controller_spec.rb
- spec/controllers/idv_controller_spec.rb
[LG-9813](https://cm-jira.usa.gov/browse/LG-9813)
Add new RateLimitConcern.
Check in IdvController (`/verify`) and IdvStepConcern (steps after Upload/HybridHandoff) if a user is rate-limited, and show them the appropriate error screen. Rate limits can be from DocumentCapture, VerifyInfo, or PhoneStep.
Do not redirect if the current controller is the one that updates that particular rate limit, because the update action may check for success before rate limiting. PhoneController currently checks for success and the other two don't (yet).
Notes: 
- Decided not to add/change a before_action in DocAuthController (FSM) to catch Welcome through Upload/HybridHandoff for the Phone Step rate limit. IdvController will catch most users.
- Can't check the SSN rate limit because it depends on the SSN …
> LG-9813 Prevent user from starting IdV if currently rate-limited

- bin/action-account
- lib/action_account.rb
- lib/data_pull.rb
- lib/script_base.rb
- lib/tasks/review_profile.rake
- spec/lib/action_account_spec.rb
- spec/lib/data_pull_spec.rb
changelog: Internal, Reporting, Add action-account script with review-reject and review-pass.
> LG-9798: Add a new script to IDP that actions account

- app/services/usps_in_person_proofing/response/request_enroll_response.rb
- spec/controllers/idv/review_controller_spec.rb
- spec/support/usps_ipp_helper.rb
[We encountered](https://gsa-tts.slack.com/archives/C043ZSQ3NUV/p1685153467001539) a case where a `NoMethodError` was being raised upon receiving a response from USPS API in an unexpected format. The error came from a case where we were using `[variable].class.class_name` instead of `[variable].class.name`.
`class_name` is a method [provided by the yard gem](https://rubydoc.info/gems/yard/YARD/Parser/Ruby/ClassNode#class_name-instance_method) that apparently is not available in production.
> Fix NoMethodError on unexpected response from USPS API

- app/controllers/concerns/idv_step_concern.rb
- spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb
[LG-9977](https://cm-jira.usa.gov/browse/LG-9977)
Accessing a standard flow page from the hybrid flow was causing 500 errors in these before actions. The user will see that their session expired instead of a 500 error. If they click the browser back button, they successfully go back where they were.
> LG-9977 Guard IdvStepConcern before_actions for nil current_user

- Makefile
- app/services/analytics_events.rb
`analytics_events.rb` is almost 4000 lines long, and the methods in it are not sorted alphabetically. This bugs me, so I sorted them and added a step to `make lint` that will error out if they're not kept sorted.
Does it make sense that I want to be able to scroll through this 4000 line file rather than just use the search function of my text editor? No, it does not. Is this a transparent attempt to juice my commit stats? Possibly. Is there a better way to do this, like with rubocop or something? Probably!
1. Add a new method to `analytics_events.rb`, but purposefully DO NOT put it in the correct alphabetical position
2. Run `make lint_analytics_events_sorted` and get yelled at
3. Put your new method in the correct place
4. Run `make lint_analytics_events_sorted` again and don't get …
> Sort analytics events

- app/controllers/idv/document_capture_controller.rb
- app/controllers/idv/hybrid_handoff_controller.rb
- app/controllers/idv/link_sent_controller.rb
- app/services/idv/actions/cancel_link_sent_action.rb
- app/services/idv/actions/redo_document_capture_action.rb
- app/services/idv/steps/agreement_step.rb
- spec/controllers/idv/document_capture_controller_spec.rb
- spec/controllers/idv/hybrid_handoff_controller_spec.rb
- spec/features/idv/doc_auth/document_capture_spec.rb
- spec/features/idv/doc_auth/hybrid_handoff_spec.rb
- spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb
[LG-9975](https://cm-jira.usa.gov/browse/LG-9975)
We eventually want the hybrid handoff step to be reentrant. For now, replicate the behavior of the FSM and redirect the user if the step is already complete. Use flow_path to indicate whether the step is complete.
Note: There are some complications because the analytics expect flow_path to be set on :show. We may want to just change that expectation and not set flow_path on show, which would simplify this PR considerably.
> LG-9975 hybrid handoff redirects

- app/controllers/idv/hybrid_handoff_controller.rb
- spec/controllers/idv/hybrid_handoff_controller_spec.rb
In HybridHandoffController, analytics are sent separately from hybrid and standard code paths, and there were no specs on the standard path. Add flow_path back in on the standard path.
Use the telephony_form_response for analytics on the hybrid path. I checked in events.log for UploadStep, and that's what it does.
> LG-9371 Add flow_path back to upload submitted analytics

- app/controllers/idv/review_controller.rb
- app/views/idv/review/new.html.erb
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- spec/controllers/idv/review_controller_spec.rb
- spec/features/idv/in_person_spec.rb
- spec/features/idv/steps/review_step_spec.rb
- spec/views/idv/review/new.html.erb_spec.rb
[LG-9871](https://cm-jira.usa.gov/browse/LG-9871)
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> LG-9871 Password Re-entry Content Changes

- app/views/idv/gpo/index.html.erb
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- spec/features/idv/steps/gpo_step_spec.rb
[LG-9641](https://cm-jira.usa.gov/browse/LG-9641)
Instead of creating a "true" new page (controller, view, tests, etc), we found that re-using the current GPO page (ie the "Want a letter?" page) with a presenter that checks whether or not the user already has a letter pending proved sufficient.
<details>
</details>
<details>
</details>
<details>
</details>
> LG-9641 GPO Resend Confirm Interstitial

- app/controllers/idv/hybrid_handoff_controller.rb
changelog: User-Facing Improvements, Identity Verification, Remove 404 on hybrid handoff
[Remove 404 action from HybridHandoff controller
](https://cm-jira.usa.gov/browse/LG-9786)
Removes `before_action` and method that renders a 404 based on hybrid handoff controller enabled.
> Remove 404 action from HybridHandoff controller

- app/controllers/frontend_log_controller.rb
- app/javascript/packages/document-capture-polling/index.ts
- app/javascript/packages/form-steps/prompt-on-navigate.ts
- app/javascript/packages/prompt-on-navigate/README.md
- app/javascript/packages/prompt-on-navigate/index.spec.ts
- app/javascript/packages/prompt-on-navigate/index.ts
- app/javascript/packages/prompt-on-navigate/package.json
- app/javascript/packages/test-helpers/use-sandbox.ts
- app/services/analytics_events.rb
- spec/javascript/packages/document-capture-polling/index-spec.js
[LG-9848](https://cm-jira.usa.gov/browse/LG-9848)
Team Ada is considering removing some `onbeforeunload` prompts (the ones that say "If you navigate away from this page, your data may not be saved" or something to that effect) from the IdV flow on the grounds that they are annoying. But before we do that, we want actual data about how they are used and if they are doing their job.
- How often do users encounter these prompts?
- Do the prompts keep users on the page?
To that end, this PR refactors `onbeforeunload` code out into its own package and adds some analytics calls:
* `User prompted before navigation` fires when the `onbeforeunload` event handler is called
* `User prompted before navigation and still on page` fires at 5s, 15s, and 30s after to indicate the user stayed on the page
> LG-9848: Add analytics to onbeforeunload

- db/primary_migrate/20230601195606_add_columns_for_user_suspension.rb
- db/schema.rb
As part of our ongoing user suspension work, we are introducing new columns to indicate whether a user is currently suspended or reinstated. This commit implements the necessary changes to add these columns for tracking purposes. It is important to note that writing to these columns should only begin after the migration has been successfully deployed and executed in a production environment.
> LG-9924 Add DB columns for User suspension

- lib/telephony/alert_sender.rb
- spec/features/two_factor_authentication/sign_in_via_personal_key_spec.rb
- spec/lib/telephony/alert_sender_spec.rb
- spec/models/event_spec.rb
- spec/support/i18n_helper.rb
[LG-9872](https://cm-jira.usa.gov/browse/LG-9872)
Fixes #8443
Fixes the notification sent when signing in using Personal Key as the multi-factor authentication method, which previously included the literal `%{app_name}` rather than "Login.gov".
As a proactive step to try to identify these sorts of issues sooner, the changes also include a monkeypatch to the `I18n.t` method when tests are run, raising an exception if the result of the translation includes a lingering interpolation variable.
(Note that this is difficult to test in deployed environments because it relates to a legacy behavior where "personal key" was supported as an MFA method without an existing identity-verified account)
3. Once account creation is complete, go to …
> LG-9872: Add missing interpolation value for personal key alert

- app/components/password_confirmation_component.html.erb
- app/controllers/sign_up/passwords_controller.rb
- app/forms/password_form.rb
- app/validators/form_password_validator.rb
- spec/controllers/sign_up/passwords_controller_spec.rb
- spec/forms/password_form_spec.rb
[LG-9714](https://cm-jira.usa.gov/browse/LG-9714)
This code removes something like a "feature flag" for the password confirmation feature that was implemented to ensure backwards compatibility across servers. Now that the servers are running the new code, the "feature flag" can be removed.
The easiest way to test that everything is working as expected is to sign up and create a new account. After submitting the "Create a strong password" form validations should be performed and it should be possible to create an account.
> LG-9714 - Remove feature flag for password confirmation

- app/controllers/idv/personal_key_controller.rb
- spec/controllers/idv/personal_key_controller_spec.rb
[LG-9858](https://cm-jira.usa.gov/browse/LG-9858)
Users who were going through the verify-by mail flow and had a pending profile due to either fraud_review, or in-person proofing were not reaching the personal key step after they entered in their one-time code. The problem was that our before_action, `:confirm_profile_has_been_created` in the personal_key_controller was only looking at active profiles and not pending profiles also. Since the user is in a new session idv_session did not have the profile.
> LG-9858 GPO Personal Key fix

- app/forms/verify_password_form.rb
- app/models/profile.rb
- spec/models/profile_spec.rb
[LG-10014](https://cm-jira.usa.gov/browse/LG-10014)
Previously, any password reactivation was manually setting the profile to `active` in the database. This is a problem if the profile also has fraud and/or gpo pending. These changes include a new helper that uses the existing `activate` method which does the appropriate checks for all pending/deactivation reasons first.
> LG-10014 [Bugfix] Password Reset Activates Any Profile

- app/controllers/idv/ssn_controller.rb
- spec/controllers/idv/ssn_controller_spec.rb
- spec/features/idv/actions/redo_document_capture_action_spec.rb
- spec/features/idv/doc_auth/verify_info_step_spec.rb
When navigating to earlier pages from VerifyInfo, users previously landed on the SSN page because it allows updates from VerifyInfo and it was not checking the referer. Now check the referer and redirect as appropriate.
This came up in testing for HybridHandoffController, but is not directly related to it.
Test plan:
- Create account, start IdV
- In DocumentCapture, upload a yaml for barcode read error (I can provide)
- Choose to Continue
- Enter 'valid' SSN (900-....)
- In VerifyInfo, click on the link in the banner to redo document capture
- Upload valid yaml or any photo
- Expect to be redirected to VerifyInfo with "We verified your ID" success banner
- Visit `/verify/hybrid_handoff` url
- Expect to stay on VerifyInfo page
> Return to VerifyInfo when attempting to navigate to earlier pages

- app/javascript/packages/document-capture/components/barcode-attention-warning.tsx
Looks like this endpoint was removed in #8377, and I'm seeing 404s in our logs from users still making this API call.
> Remove call to document_capture_errors endpoint

- app/javascript/packages/document-capture/components/barcode-attention-warning.tsx
Quick follow-on to #8540 to address @aduth's feedback. Replace a `<SpinnerButton>` with a regular `<Button>` now that its onclick handler is not async.
> Remove SpinnerButton from barcode warning

- app/models/profile.rb
- spec/models/profile_spec.rb
[LG-10029](https://cm-jira.usa.gov/browse/LG-10029)
Added an optional argument to the Profile#activate method which is used to detail why the account is being activated; and, if it is due to a passoword reset, then verified_at is not set during profile update.
Added an automated test to check this in profile_spec.rb
> LG-10029: verified_at not updated during password reset

- app/controllers/api/internal/sessions_controller.rb
- app/javascript/packages/request/index.spec.ts
- app/javascript/packages/request/index.ts
- app/javascript/packages/session/requests.spec.ts
- app/javascript/packages/session/requests.ts
- app/javascript/packs/session-timeout-ping.ts
- package.json
- spec/controllers/api/internal/sessions_controller_spec.rb
- spec/features/saml/ial1_sso_spec.rb
- yarn.lock
This supports #7966 and #8507, with the goal of improving the resiliency of how a timed-out session behaves:
- Handling a 401 server response generated by Devise for an expired cookie
- Omitting any timeout value for an inactive session
- Previously, it would be set to the current time, which could create issues with considering a timed-out session as being a future time. Even in how it behaves in `main` with [including a small offset](https://github.com/18F/identity-idp/blob/298ce7b5a52e1b1ad866cdf0ef07547d171b47d6/app/controllers/users/sessions_controller.rb#L155), it could run risk of drift between server and frontend. The frontend doesn't currently do anything with `timeout` except in the case that the session is still live, so this is not likely a problem for the moment.
- Further …
> Update session timeout poll response handling to omit timeout on inactive session

- lib/pinpoint_supported_countries.rb
Now that we have international shortcodes from #8486, we can remove MX from the Sender ID country list
> Remove MX from Sender ID countries

- app/controllers/idv/doc_auth_controller.rb
- app/controllers/idv/document_capture_controller.rb
- app/controllers/idv/link_sent_controller.rb
- app/views/idv/hybrid_handoff/show.html.erb
- config/locales/doc_auth/en.yml
- config/locales/doc_auth/es.yml
- config/locales/doc_auth/fr.yml
- config/locales/titles/en.yml
- config/locales/titles/es.yml
- config/locales/titles/fr.yml
- spec/controllers/idv/document_capture_controller_spec.rb
- spec/controllers/idv/link_sent_controller_spec.rb
- spec/features/idv/actions/redo_document_capture_action_spec.rb
- spec/features/idv/analytics_spec.rb
- spec/features/idv/cancel_spec.rb
- spec/features/idv/doc_auth/hybrid_handoff_spec.rb
- spec/features/idv/doc_auth/link_sent_spec.rb
- spec/features/idv/hybrid_mobile/entry_spec.rb
- spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb
- spec/features/idv/in_person_spec.rb
- spec/features/idv/outage_spec.rb
- spec/support/features/doc_auth_helper.rb
Rename all the things! That refer to UploadStep rather than HybridHandoff, that is. These are method names and language tags only. Analytics events will be a separate PR since that involves updating dashboards.
> Update upload code names to hybrid handoff

- lib/reporting/command_line_options.rb
- lib/reporting/monthly_proofing_report.rb
- spec/lib/reporting/command_line_options_spec.rb
- spec/lib/reporting/monthly_proofing_report_spec.rb
[LG-10005](https://cm-jira.usa.gov/browse/LG-10005)
Adds a new report intended to be run monthly. This report is based on the Identity Verification Report added in #8008, but for an internal audience.
Run it like so:
```bash
aws-vault exec prod-power -- ./bin/rails runner ./lib/reporting/monthly_proofing_report.rb --date=2023-05-01
```
> Add monthly proofing report (LG-10005)

- lib/pinpoint_supported_countries.rb
- spec/lib/pinpoint_supported_countries_spec.rb
AWS updated their Supported countries and regions (SMS channel) to say that Australia needs sender ID, but we're not seeing that, so we are adding it to our list of SENDER_ID_COUNTRIES.
https://docs.aws.amazon.com/pinpoint/latest/userguide/channels-sms-countries.html
> Add exception to sender_id requirement for Australia (AU)

- app/models/profile.rb
- spec/models/profile_spec.rb
[LG-10013](https://cm-jira.usa.gov/browse/LG-10013)
Nil out fraud_review_pending_at timestamp when activating a user in-person
Added an automated test to check this in profile_spec.rb
> LG-10013 - nil out fraud_review_pending_at

- app/controllers/idv/hybrid_handoff_controller.rb
- app/views/idv/in_person/verify_info/show.html.erb
- app/views/idv/link_sent/show.html.erb
- app/views/idv/verify_info/show.html.erb
- spec/controllers/idv/hybrid_handoff_controller_spec.rb
- spec/features/idv/actions/cancel_link_sent_action_spec.rb
[LG-8830](https://cm-jira.usa.gov/browse/LG-8830)
Add a redo parameter to hybrid_handoff show, and change the before action to allow redoing hybrid_handoff when it is present. Once this is deployed we can remove RedoDocumentCaptureAction from DocAuthFlow and remove the code.
Similarly replace CancelLinkSentAction on the LinkSent page with a link to hybrid_handoff with redo=true parameter. No longer render _back partial.
<details>
<summary>LinkSent Before:</summary>
</details>
<details>
<summary>LinkSent After:</summary>
</details>
> LG-8830: Replace RedoDocumentCaptureAction with redirect to hybrid handoff

- app/javascript/packages/prompt-on-navigate/index.spec.ts
- app/javascript/packages/prompt-on-navigate/index.ts
- app/services/analytics_events.rb
In #8512 I added some analytics to our `onbeforeunload` handlers. Unfortunately, I neglected to augment the events to say _where_ they were actually occurring (`path` is always set to `/api/logger` for frontend events--I investigated fixing this for frontend events but it's a bigger lift than I'm looking for ATM).
This PR just augments analytics events related to `onbeforeunload` with a `location` parameter (which defaults to `location.pathname`).
> Add location to events logged by promptOnNavigate

- app/controllers/idv/agreement_controller.rb
- app/controllers/idv/hybrid_handoff_controller.rb
- app/services/idv/session.rb
- app/services/idv/steps/welcome_step.rb
- app/views/idv/agreement/show.html.erb
- config/application.yml.default
- config/routes.rb
- lib/identity_config.rb
- spec/controllers/idv/agreement_controller_spec.rb
- spec/controllers/idv/hybrid_handoff_controller_spec.rb
- spec/features/idv/doc_auth/agreement_spec.rb
[LG-10016](https://cm-jira.usa.gov/browse/LG-10016)
New AgreementController behind feature flag to replace FSM AgreementStep.
<details>
</details>
> LG-10016 agreement controller

- app/components/tab_navigation_component.scss
Related to [LG-9973](https://cm-jira.usa.gov/browse/LG-9973)
Updates the TabNavigationComponent stylesheet to avoid loading dependencies associated with [the design system Button Group](https://designsystem.digital.gov/components/button-group/). Loading the bare identifier of a component will load all required dependencies. In the case of Button Group, this means that the Tab Navigation Component stylesheet is produced with all button styles ([source](https://github.com/uswds/uswds/blob/cf8c634b17bf3e41975a19bd50ae8bbb15d36eb7/packages/usa-button-group/_index.scss#L1-L2)), which are already present in the main application stylesheet ([source](https://github.com/18F/identity-idp/blob/62a93d1f2a51b5d0da8d35a063f477981b4564b6/app/assets/stylesheets/_uswds.scss#L8)). Since it should be …
> Avoid loading Tab Navigation component stylesheet dependencies

- .gitlab-ci.yml
- Brewfile
- Gemfile
- Gemfile.lock
- config/database.yml
- db/primary_migrate/20230518221444_add_postgis_extension_to_database.rb
- db/schema.rb
- docs/local-development.md
- docs/troubleshooting.md
[LG-9416](https://cm-jira.usa.gov/browse/LG-9416)
Adds the needed packages, migration, adapater, and updates documentation to use postgis.
> Enable postgis extension

- app/controllers/concerns/idv/verify_info_concern.rb
- spec/features/idv/actions/redo_document_capture_action_spec.rb
[LG-9996](https://cm-jira.usa.gov/browse/LG-9996)
Prevent users who've used the redo document capture link on the verify info step from from going back to verify info, submitting it, then going back to document capture.
> LG-9996: Don't allow redoing doc capture after verify info

- spec/features/account_reset/delete_account_spec.rb
- spec/features/visitors/email_language_preference_spec.rb
PR #8569 attempted to fix delete_account_spec for midnight UTC (5pm PDT) but broke the spec instead. Reverting.
Also add RSpec.describe for spec/features/visitors/email_language_preference_spec.rb
> Fix specs that are broken on main

- app/controllers/idv/document_capture_controller.rb
- app/controllers/idv/hybrid_handoff_controller.rb
- spec/controllers/idv/document_capture_controller_spec.rb
- spec/controllers/idv/hybrid_handoff_controller_spec.rb
- spec/features/idv/actions/redo_document_capture_action_spec.rb
[LG-8830](https://cm-jira.usa.gov/browse/LG-8830)
Now that we don't have a separate RedoDocumentCaptureAction, log that the user is redoing document capture by adding params to the logging for the HybridHandoff and DocumentCapture steps.
We want to log when redo_document_capture happens because it sometimes causes unexpected results for the user. When it was its own action it had its own analytics event, but now we are combining it with document_capture_visited. It will also be added to hybrid_handoff for users who are not on mobile.
> LG-8830 redo_document_capture logging

- app/forms/idv/api_image_upload_form.rb
- app/services/analytics_events.rb
- spec/controllers/idv/image_uploads_controller_spec.rb
- spec/forms/idv/api_image_upload_form_spec.rb
I'm trying to track down whether some long-running image upload requests to vendors are actually succeeding or not. We have good metrics on request duration via our Faraday logging, but I don't believe we have a way to tie request duration to the status code ultimately returned from the vendor.
This PR updates `ApiImageUploadForm` to include a `vendor_request_time_in_ms` when logging the 'IdV: doc auth image upload vendor submitted' event.
> Add request duration to analytics for vendor image uploads

- app/controllers/idv/gpo_controller.rb
- app/controllers/idv/review_controller.rb
- app/models/user.rb
- spec/controllers/idv/gpo_controller_spec.rb
- spec/controllers/idv/review_controller_spec.rb
- spec/features/idv/steps/review_step_spec.rb
[LG-9966](https://cm-jira.usa.gov/browse/LG-9966)
Added code to `ReviewController` to send reminder email on initial enqueue of GPO letter.
Also refactored a bit; there's now a `User` method to send an arbitrary email to all of a user's email addresses.
ToDo: Open a ticket to see where else we can use that method.
<details>
</details>
> LG-9966 send email on gpo letter enqueue

- app/models/user.rb
- app/services/analytics_events.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
This pull request (PR) introduces new functionality that enables the marking of a user as suspended and the ability to mark a suspended user as reinstated. Additionally, it includes the implementation of tracking analytics events.
The following methods have been added:
- suspended?: This method allows for checking whether a user is currently suspended.
- reinstated?: This method allows for checking whether a suspended user has been reinstated.
- suspend: This method is used to suspend a user, marking them as suspended.
- reinstate: This method is used to reinstate a suspended user, reversing their suspended status.
> LG-9928: Implement User suspend and reinstate methods

- config/routes.rb
- spec/presenters/idv/gpo_presenter_spec.rb
- spec/requests/redirects_spec.rb
[LG-9838](https://cm-jira.usa.gov/browse/LG-9838)
Moves a few GPO-related routes to be under `/verify` (like the rest of the IdV code).
- Sign up and verify your address via GPO. 
- Confirm you end up on `/verify/by_mail` to enter your OTP.
- Confirm that if you visit `/account/verify` and confirm you end up redirected to `/verify/by_mail`
- Click the "Clear my information and start over" link and verify you end up on `/verify/by_mail/confirm_start_over`
- Cancel that and confirm you can enter your GPO OTP
> LG-9838: Move GPO routes under /verify

- app/controllers/concerns/idv/verify_info_concern.rb
- app/controllers/idv/agreement_controller.rb
- app/controllers/idv/in_person/verify_info_controller.rb
- spec/controllers/idv/in_person/verify_info_controller_spec.rb
[LG-9865](https://cm-jira.usa.gov/browse/LG-9865) Work for Remove In Person Verify
Add same_address_as_id to in person verify visited analytics
> LG-9865: Add same_address_as_id to in person verify visited analytics

- lib/identity_job_log_subscriber.rb
The rest of our log files respect this config, so `workers.log` should too!
`events.log`: https://github.com/18F/identity-idp/blob/f2f2d1e0917855062a48f5580a50a212caa4a6a7/config/initializers/ahoy.rb#L48-L62
`telephony.log`: https://github.com/18F/identity-idp/blob/f2f2d1e0917855062a48f5580a50a212caa4a6a7/config/initializers/telephony.rb#L7-L11
`production.log`: https://github.com/18F/identity-idp/blob/f2f2d1e0917855062a48f5580a50a212caa4a6a7/config/environments/production.rb#L37-L40
> Log worker logs to STDOUT if configured to log to STDOUT

- app/controllers/users/sessions_controller.rb
- app/helpers/session_timeout_warning_helper.rb
- config/routes.rb
- spec/controllers/users/sessions_controller_spec.rb
- spec/helpers/session_timeout_warning_helper_spec.rb
Removes the session timeout polling behavior which was replaced in #7966, but kept for initial deploy to handle mixed deploy state.
~As such, this should not be merged until #7966 is live in production.~ **Edit:** #7966 is now live in production.
Repeat Testing Plan from #7966.
> Remove legacy session timeout polling behavior

- app/views/idv/gpo_verify/index.html.erb
- config/locales/forms/en.yml
- config/locales/forms/es.yml
- config/locales/forms/fr.yml
- spec/features/idv/steps/gpo_otp_verification_step_spec.rb
[LG-9952](https://cm-jira.usa.gov/browse/LG-9952)
Add a banner to the welcome back page for gpo letter verification that lets the user 
1. know the address their letter was sent
2. opt to cancel idv and start over within the banner.
<details>
</details>
<details>
</details>
> LG-9952 Welcome back screen should have a new information alert banner

- app/models/profile.rb
- app/services/idv/profile_maker.rb
- app/services/idv/session.rb
- spec/controllers/idv/personal_key_controller_spec.rb
- spec/services/idv/profile_maker_spec.rb
[LG-9981](https://cm-jira.usa.gov/browse/LG-9981)
`ProfileMaker#save_profile` no longer activates the profile and only saves the profile; and now.
`IDV::Session#create_profile_from_applicant_with_password` creates the profile using `ProfileMaker#save_profile` and which is then activated based on `Profile#confirm_that_profile_can_be_activated!`.
> LG-9981 IdvSession activates new profile after confirming it can be activated

- app/controllers/concerns/idv/verify_info_concern.rb
- app/controllers/idv/in_person/verify_info_controller.rb
- app/controllers/idv/verify_info_controller.rb
For the deployment of InPerson::VerifyInfoController, in PR #8585 the InPerson::VerifyStep was marked complete at the end of VerifyInfoConcern#update. This method is shared with doc_auth VerifyInfoController. To eliminate the possibility of unintended effects, and to clarify #update for both controllers, give them each their own update method and rename the method in VerifyInfoConcern to shared_update.
In #8576 we recently added code to the shared update method that prevents redoing document capture after VerifyInfo is submitted. This does not apply to InPerson::VerifyInfoController, so this code was moved to the doc_auth VerifyInfoController#update.
> Refactor verify info update

- app/models/service_provider_request.rb
- spec/services/service_provider_request_proxy_spec.rb
The deprecation of this attribute in #3851 will celebrate its 3rd birthday in a few days (🎉). I searched the logs for the warning and do not see any for the past few weeks, so this should be safe to remove now.
For posterity, this attribute was renamed in #3835.
> Remove deprecated "loa" ServiceProviderRequest attribute

- lib/identity_config.rb
As we continue our work on building quickly-deployed review applications, we have the need to read config in via environment variables at boot time.
Assumptions:
- We will be expanding the scope of reading config from environment variables, including different data types
- Configuration via files as we do now will continue to be the primary form of config for the foreseeable future
- No new configuration data types will be introduced
The short implementation in this PR is my proposal to allow a given configuration key to opt-in to specifying an environment variable per-environment. Currently this is only targeted at review environment applications, and we will likely want a fuller evaluation of the options for setting and loading configuration if the scope expands in the future. This …
> Add support for reading configuration from system environment variables

- spec/features/idv/doc_auth/redo_document_capture_spec.rb
We added a new test in #8576 that has been flaky in CI. Ada is investigating, but want to skip the test on main for now to unblock other teams.
> Temporarily skip flaky redo doc capture test

- lib/identity_job_log_subscriber.rb
The default logger isn't in a format that we use and it mostly duplicates a lot of what we have in [IdentityJobLogSubscriber](https://github.com/18F/identity-idp/blob/mitchellhenke/remove-default-activejob-logger/lib/identity_job_log_subscriber.rb)
Example:
```
{"duration_ms":88.27300000190735,"timestamp":"2023-06-15T17:48:40.098Z","name":"enqueue.active_job","job_class":"HeartbeatJob","trace_id":null,"queue_name":"GoodJob(default)","job_id":"d36d287c-d3af-4237-8c76-d477656c2e3c"}
Enqueued HeartbeatJob (Job ID: d36d287c-d3af-4237-8c76-d477656c2e3c) to GoodJob(default)
```
> Remove default ActiveJob logger

- app/controllers/idv/hybrid_handoff_controller.rb
[LG-9367](https://cm-jira.usa.gov/browse/LG-9367)
In a HybridHandoffController before action, redirect to DocumentCaptureController if flow_session[:skip_upload_step] is set. This is needed for outage specs which use :skip_upload_step to indicate that hybrid flow is turned off. The Flow State Machine was taking care of this from the AgreementStep, but now that it is being removed from the FSM, the HybridHandoffController needs to handle it.
We may want to consider checking the FeatureManagement flag directly in the future.
> Redirect from hybrid_handoff to document_capture on :skip_upload_step

- config/application.yml.default
Enables platform authenticators by default in local development, to reduce effort in testing, increase visibility across development team to build familiarity, and (ideally) quickly identify potential bugs.
1. Remove or comment `config/application.yml`
2. Run `make run`
3. Go to http://localhost:3000
4. Create an account
5. At MFA setup screen, you should see Face or Touch Unlock option, assuming your device has hardware support for platform authenticators (e.g. fingerprint reader)
> Enable platform authenticators in local development

- app/controllers/idv/gpo_verify_controller.rb
- spec/controllers/idv/gpo_verify_controller_spec.rb
- spec/features/idv/steps/gpo_step_spec.rb
If a user logs in with a PIV directly (which skips entering their password) with a GPO pending profile, they are taken directly to the verify screen. This screen now shows attributes from the PII bundle as of https://github.com/18F/identity-idp/pull/8582, which means we need to prompt the user for their password first.
This fix is similar to the ones in #6121 #6309 which checks if the PII is missing from the session and redirects to password capture first.
> Fix bug with verifying address by mail when logging in with PIV/CAC by prompting for password first

- app/controllers/idv/agreement_controller.rb
- app/controllers/idv/welcome_controller.rb
- app/controllers/idv_controller.rb
- app/services/idv/session.rb
- app/views/idv/welcome/show.html.erb
- config/application.yml.default
- config/routes.rb
- lib/identity_config.rb
- spec/controllers/idv/welcome_controller_spec.rb
- spec/features/idv/doc_auth/welcome_spec.rb
- spec/support/features/doc_auth_helper.rb
- spec/views/idv/welcome/show.html.erb_spec.rb
[LG-10107](https://cm-jira.usa.gov/browse/LG-10107)
Create WelcomeController behind a feature flag to replace WelcomeStep.
Note: There is additional work required to take DocAuthController (Flow State Machine) entirely out of the loop before the feature flag is turned on.
<details>
<summary>New view </summary>
</details>
> LG-10107 welcome controller

- spec/factories/profiles.rb
- spec/factories/users.rb
- spec/features/idv/pending_profile_password_reset_spec.rb
We have uncovered a number of bugs that occur when a user with a pending profile resets their password. This commit adds tests to cover this behavior and make sure everything works as expected.
Currently if a user with a pending profile resets their profile we deactivate their profile and it is unrecoverable. These tests may need to change if we give users the option to recover these profiles.
> Add tests to cover password resets with a pending profile

- config/locales/account/en.yml
- config/locales/account/es.yml
- config/locales/account/fr.yml
- spec/features/idv/steps/gpo_otp_verification_step_spec.rb
[LG-9815](https://cm-jira.usa.gov/browse/LG-9815)
Peronal key controller checks to see if the address is confirmed in the idv_session in order to display correct banner message.
There are automated test to verify.
Manual:
<details>
</details>
<details>
</details>
> LG-9815: Personal key screen success banner in GPO flow should be updated

- app/models/user.rb
- spec/lib/action_account_spec.rb
- spec/models/user_spec.rb
**Why**: OutOfBandSessionAccessor will error with nil id
Looks like a bad combo of #8618 and #8624 surfaced an issue with nil session IDs being suspended
> Add guard for suspending user with no unique session ID

- app/models/profile.rb
- db/primary_migrate/20230622142018_add_fraud_pending_reason_to_profile.rb
- db/schema.rb
- spec/models/profile_spec.rb
This commit adds a column for holding the reason that a user is fraud pending. This commit also clears the fraud review pending reason if it exists when the profile is activated after fraud review.
In order to maintain consistency the commit that adds the fraud review pending reason will need to follow this one in a different deploy.
> LG-9727 Add a fraud_pending_reason_column

- docs/mobile.md
Update mobile dev docs to
- clarify needed changes in local `application.yml` file
- help troubleshoot USB debugging
- fix one nit in the iPhone/Safari debugging instructions
> Update mobile dev docs

- CONTRIBUTING.md
Adds a new paragraph to `CONTRIBUTING.md` outlining some guidance for code review:
- Encouraging everyone to participate
- Mentioning internal product team handles to request review from your product team
- Mentioning interest group team handles
> Add contributing guidelines for code review

- app/controllers/concerns/idv/threat_metrix_concern.rb
- app/controllers/idv/ssn_controller.rb
- app/views/idv/ssn/show.html.erb
- config/application.yml.default
- lib/identity_config.rb
- spec/controllers/idv/ssn_controller_spec.rb
We have code that modifies the CSP and renders special javascript on the SSN page for device profiling.
We are planning a test to see how this page performs if the CSP changes are not in place or if the device profiling javascript is not enabled.
This commit adds 2 new configs:
- `idv_tmx_test_csp_disabled_emails`: A list of emails for which the CSP changes are not made
- `idv_tmx_test_js_disabled_emails`: A list of emails for which the JS is not loaded
These configs are empty by default. After this commit, adding an email address will cause the desired effect for a user with that email.
These lists are only intended to be populated in the staging environment. After the test this change should be reverted.
> LG-10055 Do not change CSP or render TMx JS for specific users

- app/controllers/concerns/idv_step_concern.rb
- app/controllers/idv/address_controller.rb
- app/controllers/idv/agreement_controller.rb
- app/controllers/idv/document_capture_controller.rb
- app/controllers/idv/hybrid_handoff_controller.rb
- app/controllers/idv/in_person/verify_info_controller.rb
- app/controllers/idv/link_sent_controller.rb
- app/controllers/idv/phone_controller.rb
- app/controllers/idv/ssn_controller.rb
- app/controllers/idv/verify_info_controller.rb
- app/controllers/idv/welcome_controller.rb
- spec/controllers/concerns/idv_step_concern_spec.rb
- spec/controllers/idv/document_capture_controller_spec.rb
- spec/controllers/idv/hybrid_handoff_controller_spec.rb
- spec/controllers/idv/in_person/verify_info_controller_spec.rb
- spec/controllers/idv/link_sent_controller_spec.rb
- spec/controllers/idv/phone_controller_spec.rb
- spec/controllers/idv/ssn_controller_spec.rb
- spec/controllers/idv/verify_info_controller_spec.rb
[LG-10152](https://cm-jira.usa.gov/browse/LG-10152)
- Include OutageConcern and :check_for_outage before_action in IdvStepConcern so it will be included in all post-FSM controllers.
- Remove OutageConcern and :check_for_outage from individual controllers. Add controller specs to ensure it is still indirectly included.
- Extra cleanup: Since IdvSession and :confirm_two_factor_authenticated are also included in IdvStepConcern, remove them from individual controllers. There are already controller specs confirming inclusion of that before action.
Note:
- removed `only: :show` restriction for :check_for_outage. If we put it back, we should include `:new` for the phone_controller.
- personal_key_controller, gpo_controller and gpo_verify_controller don't include IdvStepConcern. Should they? They …
> LG-10152 check for outage in idv step concern

- app/controllers/idv/gpo_only_warning_controller.rb
- app/controllers/idv_controller.rb
- app/services/analytics_events.rb
- app/views/idv/gpo_only_warning/show.html.erb
- spec/controllers/idv/gpo_only_warning_controller_spec.rb
- spec/features/idv/outage_spec.rb
[LG-9365](https://cm-jira.usa.gov/browse/LG-9365)
[LG-10181](https://cm-jira.usa.gov/browse/LG-10181)
This is a followup on #8643 to make GpoOnlyWarningController compatible with the WelcomeController.
- Allow nil flow_session in gpo_only_warning controller
- Add controller specs
- Redirect to idv_url instead of directly to FSM welcome step.
- Initialize flow session in idv_controller before redirecting to idv_welcome_url. Previously base_flow did that.
- Add `IdV: mail only warning visited` analytics event
Note:
- May want to move :skip_vendor_outage out of flow_session in the long run
```
vendor_status_sms: full_outage
doc_auth_welcome_controller_enabled: true
```
> LG-10181 Gpo_only_warning fixes for welcome controller

- app/controllers/concerns/idv/outage_concern.rb
- app/controllers/concerns/idv_session.rb
- app/controllers/concerns/idv_step_concern.rb
- app/controllers/idv/address_controller.rb
- app/controllers/idv/gpo_only_warning_controller.rb
- app/controllers/idv_controller.rb
- spec/controllers/idv/gpo_only_warning_controller_spec.rb
[LG-9365](https://cm-jira.usa.gov/browse/LG-9365)
This is in preparation for no longer going through the Flow State Machine for the Welcome Step. Initialize the doc_auth flow_session to {} when it is first used (if it is nil) rather than expecting the Flow State Machine to initialize it.
(Almost) everywhere that was accessing user_session['idv/doc_auth'] directly is now calling the flow_session method, which has been moved from IdvStepConcern to IdvSession for better access to it.
Note that this does not affect the in_person flow_session which is at user_session['idv/in_person'].
Added an expectation to gpo_only_warning_controller_spec which tests the flow_session method. Expecting feature and controller tests to provide overall coverage of the change.
> Initialize flow_session when it is first used

- Makefile
- audit-ci.jsonc
- package.json
- yarn.lock
Adds [`audit-ci`](https://github.com/IBM/audit-ci) package as a replacement tool for NPM package audits, to work around a [current security advisory flagged for `semver`](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw). This is intended to be a temporary fix for a vulnerability for which the risk is very low, since conflicts between packages make upgrading infeasible (specifically, `semver` is only patched at 7.x, and many other dependencies like `eslint-plugin-import` are pinned to lower versions).
To enforce this being a temporary fix, an expiration has been added for the allowlist to expire on September 1st.
Related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1687791623479719
1. Observe that the build passes
2. Observe that you can run the checks locally:
1. Run …
> Audit yarn dependencies with allowlist

- app/controllers/idv/welcome_controller.rb
- spec/controllers/idv/welcome_controller_spec.rb
[LG-10143](https://cm-jira.usa.gov/browse/LG-10143)
Remove WelcomeController 404 before_action
> LG-10143 Remove WelcomeController 404 before_action

- app/controllers/idv/gpo_verify_controller.rb
- spec/features/idv/steps/gpo_otp_verification_step_spec.rb
The personal key controller was previously always part of the main proofing flow and was always rendered after the password input. Recently we moved it to GPO verification for users in that workflow. This meant that when the user was seeing their personal key for the GPO verification workflow the `idv_session` had been cleared when their session expired. As a result the GPO verification screen needs to setup `idv_session` for the personal key.
When this was done the `address_verification_method` attribute was left off. The personal key controller uses the `StepIndicatorConcern` to determine which steps to show. That looks for the presence of a pending profile or that attribute on `idv_session`. Since the user no longer has a pending profile after confirming their GPO code and the GPO …
> LG-9818 Set the `address_verification_mechanism` for the GPO verify action

- app/forms/gpo_verify_form.rb
- app/models/profile.rb
- app/services/idv/profile_maker.rb
- app/services/idv/session.rb
- spec/controllers/idv/personal_key_controller_spec.rb
- spec/factories/profiles.rb
- spec/models/profile_spec.rb
- spec/services/idv/profile_maker_spec.rb
This commit changes `Idv::Session` and `Idv::ProfileMaker` to write the reason a profile is fraud pending to `fraud_pending_reason`. A previous commit will overwrite the value with nil when the profile is activated after fraud review.
This change depends on #8635. It should not be merged until the changes in that PR are in production.
> LG-9727 Write to the fraud_pending_reason column

- lib/tasks/backfill_fraud_pending_reason.rake
This commit updates the rake task that updates `fraud_pending_reason`. It makes the following changes:
1. The `backfill_fraud_pending_reason` task performs a dry run by default and needs a flag set to commit changes. This allows for a dry-run to be done to preview changes that will be made.
2. A task is added to rollback the operation in case that is necessary.
> LG-9969 Update the `fraud_pending_reason` backfill rake task

- scripts/changelog_check.rb
- spec/fixtures/git_log_changelog.yml
- spec/scripts/changelog_check_spec.rb
I think the initial regular expression was a bit off in its implementation and was supposed to be words, dashes and forward slashes but it created a character class from ASCII character space (32) to forward slash (47) which includes the comma (42). 
This change fixes that so that we can use commas in the changelog.
> Allow commas in changelog changes

- audit-ci.jsonc
Resolves security advisory notices affecting all builds on `main`, related to a a [security advisory](https://github.com/advisories/GHSA-j8xg-fqg3-53r7) in the `word-wrap` dependency.
This is a temporary alternative to #8677 to allow builds to pass again. #8677 is a viable path forward, but requires more work to address issues with upgrades to the affected packages. This is enforced as temporary with an expiration of August 1.
The risk here is quite low due to how packages operate with `optionator` (see related comment https://github.com/gkz/optionator/issues/44#issuecomment-1518171047)
The `audit_yarn_package` exits with a successful exit code:
```bash
make audit_yarn_package
echo $?
```
> Add word-wrap security advisory to audit allowlist

- app/controllers/idv/ssn_controller.rb
- app/forms/idv/ssn_format_form.rb
- spec/controllers/idv/ssn_controller_spec.rb
- spec/features/idv/puerto_rican_address_spec.rb
Users who upload a Puerto Rican document during IdV are redirected to the address controller after they enter their SSN. This differs from the rest of users who are sent to the verify info screen and only see the address controller views if they choose to update their address there. This is because Puerto Rican addresses have been problematic and seeing the address screen gives users with Puerto Rican documents a chance to modify their address if the address is read incorrectly. There are also alerts specific to formatting PR addresses that appear on the address update screen.
To enable the above behavior the SSN controller redirects to the address controller if the jurisdiction for the user's address is "PR". This approach worked well for PR users who are entering their SSN for the first …
> LG-9806 Do not redirect to address controller when a PR user updates their address

- config/application.yml.default.docker
Following today's appdev/devops sync, this brings a few changes to make review apps to be a bit more useful for reviewing changes by making identity proofing possible. It also changes the logs to go to STDOUT (related to #8610)
> Update review application configuration to behave closer to development environment

- app/controllers/concerns/idv/hybrid_mobile/hybrid_mobile_concern.rb
- app/controllers/idv/hybrid_mobile/capture_complete_controller.rb
- app/controllers/idv/hybrid_mobile/document_capture_controller.rb
- app/controllers/idv/image_uploads_controller.rb
- app/presenters/image_upload_response_presenter.rb
- app/views/idv/hybrid_mobile/document_capture/show.html.erb
- spec/controllers/idv/hybrid_mobile/capture_complete_controller_spec.rb
- spec/controllers/idv/image_uploads_controller_spec.rb
- spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb
- spec/presenters/image_upload_response_presenter_spec.rb
[LG-9931](https://cm-jira.usa.gov/browse/LG-9931)
When a user is rate limited on document capture during hybrid flow, they are now shown the CaptureComplete screen (without success banner) instead of rate limit error. Desktop already showed rate limit error.
Note that the before_action on CaptureComplete that requires document capture to be successful has been removed to allow it to be shown on rate limiting.
<details>
</details>
> LG-9931 show capture complete on hybrid rate limit

- config/application.yml.default
We added the v3 session encryptor a while back. This conifg was used to migrate away from the v2 encryptor to the v3 encryptor. This commit flips it on to default not that that migration is done.
This change is in anticipation of removing the legacy session encryptor code which can safely be done 1 release cycle after this change.
> Enable the v3 session encryptor by default

- app/services/arcgis_api/geocoder.rb
- spec/services/arcgis_api/geocoder_spec.rb
- [LG-9449](https://cm-jira.usa.gov/browse/LG-9449)
- This PR removes code that may otherwise need to be updated for the story.
- Remove manual Redis TTL usage
- This is no longer required to workaround Rails cache behavior.
- See the following:
- https://github.com/18F/identity-idp/pull/8035#discussion_r1143376028
- https://github.com/rails/rails/pull/45047
- Automated tests
> Remove Redis-specific code for ArcGIS API token caching

- spec/features/saml/ial1_sso_spec.rb
This tries to improve the reliability of a spec which has seen intermittent failures in builds.
Example failure: https://gitlab.login.gov/lg/identity-idp/-/jobs/541333
The hypothesis is that, because the spec stubs the timeout delay to occur immediately on page load, the `Warden.on_next_request` call in the Ruby code happens _after_ the request in the browser, so the forced session expiration doesn't take effect, as it would be another 30 seconds before a subsequent poll request. 
The proposed solution is to increase the poll frequency so that even if the first request misses the Warden request stubbing, the next request a second later would catch it.
This also adds a couple other unrelated improvements:
- Narrow the effect of the session check delay stubbing to occur only for the single …
> Improve reliability of session timeout spec

- app/services/flow/flow_state_machine.rb
This change makes it such that you see a 404 error if you make a post request to a step that is not allowed. Previously this would 500 as the step handler would not be found resulting in a `NoMethodError`.
> Render a 404 if a step handler is not found on update requests

- app/controllers/concerns/idv/step_indicator_concern.rb
- app/services/idv/flows/doc_auth_flow.rb
- app/views/idv/address/new.html.erb
- app/views/idv/agreement/show.html.erb
- app/views/idv/hybrid_handoff/show.html.erb
- app/views/idv/hybrid_mobile/capture_complete/show.html.erb
- app/views/idv/link_sent/show.html.erb
- app/views/idv/please_call/show.html.erb
- app/views/idv/ssn/show.html.erb
- app/views/idv/welcome/show.html.erb
- spec/controllers/concerns/idv/step_indicator_concern_spec.rb
- spec/views/idv/come_back_later/show.html.erb_spec.rb
- spec/views/idv/gpo/index.html.erb_spec.rb
- spec/views/idv/phone/new.html.erb_spec.rb
- spec/views/idv/review/new.html.erb_spec.rb
- spec/views/idv/shared/_error.html.erb_spec.rb
[LG-10112](https://cm-jira.usa.gov/browse/LG-10112)
Moved the the STEP_INDICATOR_STEPS constants from DocAuthFlow to StepIndicatorConcern.
Verify that the test suite passes without errors; this is a pure refactoring.
> LG-10112 Move STEP_INDICATOR_STEPS and STEP_INDICATOR_STEPS_GPO from DocAuthFlow to StepIndicatorConcern

- app/jobs/arcgis_token_job.rb
- app/services/analytics_events.rb
- config/application.yml.default
- config/initializers/job_configurations.rb
- lib/identity_config.rb
- spec/jobs/arcgis_token_job_spec.rb
- [LG-9449](https://cm-jira.usa.gov/browse/LG-9449)
- Create scheduled job to refresh ArcGIS token regularly before it expires
- Cron is configurable because while the [default expiration](https://developers.arcgis.com/rest/users-groups-and-items/generate-token.htm) is 1 hour, the server can use a different value.
This intentionally excludes the retry and sliding window logic that was attempted in #8662 and #8579. These features can help with availability, but they contribute enough complexity that it doesn't make sense to shoehorn them into the same story.
> LG-9449: Implement and configure ArcGIS API token refresh job

- app/services/encryption/kms_logger.rb
- config/initializers/ahoy.rb
- config/initializers/faraday.rb
- lib/identity_job_log_subscriber.rb
- spec/lib/identity_job_log_subscriber_spec.rb
- spec/services/encryption/kms_logger_spec.rb
We are experimenting with logging all logs to STDOUT in containers, and ensuring they end up in the right log groups in CloudWatch requires a way to disambiguate the lines from one another.
The one that is TBD is the Rails logs, which will likely be our fallback case and may not need the additional metadata.
> Add log filename to logs to disambiguate in STDOUT

- .gitlab-ci.yml
Does what it says
Does what it says, adds allow_failure to the review-app stage. Tested to see when the helm chart would lock and how long it took and decided against adding the retry in to the helm upgrade command since it wouldn't help with actual failures and would just draw the failure out longer.
> Adding in allow_failure for review stage to not disrupt CI checks

- app/javascript/packs/webauthn-authenticate.ts
- spec/features/webauthn/sign_in_spec.rb
[LG-10021](https://cm-jira.usa.gov/browse/LG-10021)
When a successful authentication is passed and the display of the progress and success containers are toggled, if an error alert container is present, it gets removed from the DOM.
With an account that has Security Key or F/T Unlock as a MFA option and does not remember your browser...
> LG 10021 hide error after successful webauth authentication

- .gitlab-ci.yml
Trying to see if we can use the container cache to reduce build time
> Use image caching during Kaniko build for review applications

- app/jobs/reports/sp_issuer_user_counts_report.rb
Follow up from LG-9956 (it didn't work because I was missing `transaction_with_timeout`) 
[Previous PR](https://github.com/18F/identity-idp/pull/8596)
[See error in NewRelic](https://onenr.io/0VjY6Y120Q0)
[Resolution thread in slack ](https://gsa-tts.slack.com/archives/C05E50XNN8Z/p1687795636353019)
> use transaction_with_timeout method

- app/controllers/idv/in_person/address_search_controller.rb
- app/jobs/arcgis_token_job.rb
- app/services/arcgis_api/geocoder_factory.rb
- spec/jobs/arcgis_token_job_spec.rb
- spec/services/arcgis_api/geocoder_factory_spec.rb
- [LG-9449](https://cm-jira.usa.gov/browse/LG-9449)
- Update the ArcGIS token job to respect the mock geocoder setting
> LG-9449: Configure ArcGIS token job to respect mock geocoder setting

- app/models/in_person_enrollment.rb
- app/models/notification_phone_configuration.rb
- app/models/phone_configuration.rb
- app/services/phone_formatter.rb
- db/primary_migrate/20230627213457_add_notification_phone_configurations_table.rb
- db/schema.rb
- spec/factories/notification_phone_configurations.rb
- spec/models/notification_phone_configuration_spec.rb
- spec/services/phone_formatter_spec.rb
[LG-10123](https://cm-jira.usa.gov/browse/LG-10123)
* Added a new data model for storing the SMS phone number to use for SMS notifications related to the in-person proofing flow
* A follow-up PR will add a feature flag and begin saving users' phone numbers to this table
> LG-10123: Add data model for notification SMS numbers

- app/views/users/backup_code_setup/confirm_backup_codes.html.erb
- config/locales/two_factor_authentication/en.yml
- config/locales/two_factor_authentication/es.yml
- config/locales/two_factor_authentication/fr.yml
- spec/features/two_factor_authentication/multiple_mfa_sign_up_spec.rb
This ticket is a bug fix--users will no longer see `&nbsp;` on the English "I need new backup codes" button
Before
After
> fix `_html` on keys

- app/controllers/idv/document_capture_controller.rb
- spec/controllers/idv/document_capture_controller_spec.rb
[LG-10201](https://cm-jira.usa.gov/browse/LG-10201)
Cancels any 'establishing' in-person enrollments when the document capture page is loaded. This fixes a bug where the progressive proofer was trying to follow the double address verification flow even though the user was verifying remotely, because they'd previously begun the in-person flow and then started over.
Once the change is on staging,
1. go to staging and create an account via the OIDC app;
2. fail doc capture & start down the in-person flow, get as far as selecting a location and loading the state ID page;
3. return to doc capture (**do not click 'cancel'**); you can do this by taking one of the below actions:
1. return to the OIDC app and click 'sign in' again;
2. go to the root URL (which will redirect to your profile) and …
> LG-10201: cancel stale enrollments on doc capture visit

- app/controllers/idv/otp_verification_controller.rb
- app/controllers/two_factor_authentication/otp_verification_controller.rb
- config/application.yml.default
- lib/identity_config.rb
- spec/controllers/idv/otp_verification_controller_spec.rb
[LG-10123](https://cm-jira.usa.gov/browse/LG-10123?filter=-1)
* Add a `in_person_send_proofing_notifications_enabled` feature flag to control the new in person notification feature
* Begin saving a user's confirmed SMS phone number as a NotificationPhoneConfiguration record
* Only done when the user is going through the in person flow and when feature the flag is enabled
> LG-10123: Save sms phone number for in person sessions

- app/controllers/users/sessions_controller.rb
- app/views/devise/sessions/new.html.erb
- config/application.yml.default
- config/locales/account/en.yml
- config/locales/account/es.yml
- config/locales/account/fr.yml
- lib/identity_config.rb
We dropped support for IE 11 over 6 months ago, and while we do have some related tickets to display a more comprehensive notice to all unsupported browsers, we can remove this for now.
> Remove IE 11 warning banner

- app/controllers/accounts/personal_keys_controller.rb
- app/controllers/concerns/reauthentication_required_concern.rb
- app/controllers/concerns/remember_device_concern.rb
- app/controllers/users/backup_code_setup_controller.rb
- app/controllers/users/edit_phone_controller.rb
- app/controllers/users/emails_controller.rb
- app/controllers/users/passwords_controller.rb
- app/controllers/users/phones_controller.rb
- app/controllers/users/piv_cac_authentication_setup_controller.rb
- app/controllers/users/piv_cac_setup_controller.rb
- app/controllers/users/piv_cac_setup_from_sign_in_controller.rb
- app/controllers/users/totp_setup_controller.rb
- app/controllers/users/webauthn_setup_controller.rb
- config/application.yml.default
- lib/identity_config.rb
- spec/controllers/accounts/personal_keys_controller_spec.rb
- spec/controllers/concerns/reauthentication_required_concern_spec.rb
This was added in #8037 and has been enabled in the major environments for [awhile](https://gsa-tts.slack.com/archives/C0NGESUN5/p1686322921595399?thread_ts=1686322782.331309&cid=C0NGESUN5), so this PR enables it by default and removes the configuration for it.
> Clean up feature flag for second factor reauthentication

- app/mailers/user_mailer.rb
- app/services/request_password_reset.rb
- app/views/user_mailer/suspended_reset_password.html.erb
- config/application.yml.default
- config/locales/user_mailer/en.yml
- config/locales/user_mailer/es.yml
- config/locales/user_mailer/fr.yml
- lib/identity_config.rb
- spec/mailers/previews/user_mailer_preview.rb
- spec/mailers/user_mailer_spec.rb
- spec/models/user_spec.rb
- spec/services/request_password_reset_spec.rb
https://cm-jira.usa.gov/browse/LG-9934
> LG-9934 Prevent suspended user from reset password

- app/controllers/two_factor_authentication/webauthn_verification_controller.rb
- app/controllers/users/webauthn_setup_controller.rb
- app/forms/webauthn_setup_form.rb
- app/javascript/packages/webauthn/enroll-webauthn-device.spec.ts
- app/javascript/packages/webauthn/enroll-webauthn-device.ts
- app/javascript/packages/webauthn/index.ts
- app/javascript/packages/webauthn/verify-webauthn-device.spec.ts
- app/javascript/packages/webauthn/verify-webauthn-device.ts
- app/javascript/packs/webauthn-authenticate.ts
- app/javascript/packs/webauthn-setup.ts
- app/models/webauthn_configuration.rb
- app/presenters/two_factor_auth_code/webauthn_authentication_presenter.rb
- app/views/two_factor_authentication/webauthn_verification/show.html.erb
- app/views/users/webauthn_setup/new.html.erb
- db/primary_migrate/20230622125954_add_transports_to_webauthn_configurations.rb
- db/schema.rb
- spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
- spec/controllers/users/webauthn_setup_controller_spec.rb
- spec/decorators/mfa_context_spec.rb
- spec/factories/users.rb
- spec/factories/webauthn_configurations.rb
- spec/features/remember_device/webauthn_spec.rb
- spec/features/webauthn/management_spec.rb
- spec/forms/webauthn_setup_form_spec.rb
- spec/models/webauthn_configuration_spec.rb
- spec/presenters/two_factor_auth_code/webauthn_authentication_presenter_spec.rb
[LG-9873](https://cm-jira.usa.gov/browse/LG-9873)
Records `transports` associated with WebAuthn configurations during enrollment and uses those values in the authentication prompt, so that the browser UI will optimize the display for the user to select the correct authenticator device. For example, this should prevent users from being shown options for using a "Security Key" to complete Face or Touch Unlock.
Via WebAuthn spec:
>The [credential request] items SHOULD specify transports whenever possible. This helps the client optimize the user experience for any given situation.
https://w3c.github.io/webauthn/#dom-publickeycredentialrequestoptions-allowcredentials
>When registering a new credential, the Relying Party SHOULD store the value returned from getTransports(). When creating a …
> LG-9873: Use "transports" to optimize platform authentication prompt

- app/services/marketing_site.rb
- app/views/shared/_personal_key.html.erb
- config/locales/forms/en.yml
- config/locales/forms/es.yml
- config/locales/forms/fr.yml
- spec/features/idv/steps/confirmation_step_spec.rb
- spec/support/features/session_helper.rb
[LG-9544](https://cm-jira.usa.gov/browse/LG-9544)
Update copy for personal key acknowledgement partial
**NOTE**: cannot be merged before https://github.com/18F/identity-site/pull/1109
<details>
</details>
<details>
</details>
> LG-9544 - Personal key screen should have simplified content

- app/forms/openid_connect_authorize_form.rb
- app/services/saml_request_validator.rb
- config/application.yml.default
- lib/identity_config.rb
- lib/idp/constants.rb
- spec/controllers/openid_connect/authorization_controller_spec.rb
- spec/features/reports/authorization_count_spec.rb
- spec/features/users/sign_in_spec.rb
- spec/forms/openid_connect_authorize_form_spec.rb
- spec/services/saml_request_validator_spec.rb
[add allow list config for IALMAX](https://cm-jira.usa.gov/browse/LG-9958)
As a first step to deprecating IALMAX, we would like to constrain IALMAX to existing partners/integrations. This change introduces an allowlist of issuers for IALMAX, and if a partner is not on the allowlist, they will be unable to utilize the IALMAX flow.
> LG-9958 add allow list for IALMAX

- config/routes.rb
- spec/controllers/idv/welcome_controller_spec.rb
- spec/requests/redirects_spec.rb
[LG-9939](https://cm-jira.usa.gov/browse/LG-9939)
The previously added legacy route left the user on /verify/doc_auth/welcome which would give them a 404 when they click Continue.
Also moved redirect spec to spec/requests/redirects_spec.rb
> LG-9939 Addendum: Make /verify/doc_auth/:step redirect to /verify/welcome

- app/jobs/usps_auth_token_refresh_job.rb
- app/services/analytics_events.rb
- app/services/usps_in_person_proofing/mock/proofer.rb
- config/application.yml.default
- config/initializers/job_configurations.rb
- lib/identity_config.rb
- spec/jobs/usps_auth_token_refresh_job_spec.rb
- spec/support/usps_ipp_helper.rb
[LG-9433](https://cm-jira.usa.gov/browse/LG-9433)
Right now, the responsibility for renewing the authentication token lies
with the methods calling out to the USPS API for any reason. This can
delay requests to, for example, search for nearby post offices, as they
have to first do the authentication and then do the work.
Creating a USPS authentication token refresh job takes the
responsibility away from the other calls to the API. They still have the
logic and ability to do so as a failsafe in case all the refresh jobs
fail, but if the jobs are working properly they should never need to
make the call.
> LG-9433: Create USPS auth token refresh job

- app/services/usps_in_person_proofing/enrollment_helper.rb
- spec/controllers/idv/review_controller_spec.rb
- spec/services/usps_in_person_proofing/enrollment_helper_spec.rb
[LG-10103](https://cm-jira.usa.gov/browse/LG-10103)
Sends only address line 1 to the USPS API when creating an enrollment, instead sending the combined address lines 1 and 2.
> LG-10103: Send only address line 1 to USPS when creating an enrollment

- app/controllers/idv/gpo_controller.rb
- app/controllers/idv/review_controller.rb
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- spec/features/idv/steps/gpo_step_spec.rb
https://cm-jira.usa.gov/browse/LG-10154
This PR adds 2 new success banners after a user requests to verify by mail.
> LG-10154 letter on the way screen

- app/javascript/packs/webauthn-authenticate.ts
- app/views/two_factor_authentication/webauthn_verification/show.html.erb
[LG-10290](https://cm-jira.usa.gov/browse/LG-10290)
Fixes an issue introduced in #8723 where a user would be redirected to the Security Key version of the WebAuthn MFA verification page if they cancelled the browser dialog for face or touch unlock.
1. Sign in to an account with Face or Touch Unlock configured
2. Click "Use face or touch unlock" when prompted for MFA
3. Click "Cancel" in the browser dialog
**Before:** User is redirected to an error page and prompted to "Connect your security key"
**After:** Error state reflects cancelled Face or Touch Unlock MFA
> LG-10290: Fix F/T unlock cancel sign-in redirect

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_modal.scss
Fixes an issue where the session timeout modal styles are missing.
Likely a regression of #8571, where modal is susceptible to the same issue as Language Picker described in the original pull request description, since it is also [rendered in the base layout](https://github.com/18F/identity-idp/blob/0d55b58169680f06eb7708c7de6b26221549f66c/app/views/layouts/base.html.erb#L87-L100):
>This was originally going to include a refactor of LanguagePickerComponent to have a component stylesheet, but there's an issue with how we [render the "stylesheet once" tags](https://github.com/18F/identity-idp/blob/62a93d1f2a51b5d0da8d35a063f477981b4564b6/app/views/layouts/base.html.erb#L29) which is incompatible with components rendered as part of the base layout. This will need to be fixed first. …
> Fix session timeout modal styles

- app/controllers/idv_controller.rb
- spec/controllers/openid_connect/authorization_controller_spec.rb
[LG-10183](https://cm-jira.usa.gov/browse/LG-10183)
Added some tests to ensure users aren't reaching the "Please call" page before other pending profile reasons are resolved. Also place pending reasons in IdV controller.
> LG-10183 Pending profiles should redirect to proper page

- app/controllers/concerns/idv/hybrid_mobile/hybrid_mobile_concern.rb
- spec/controllers/idv/hybrid_mobile/document_capture_controller_spec.rb
We are currently seeing some odd logging (discussed [here](https://gsa-tts.slack.com/archives/C16RSBG49/p1688752177992979)) where the `doc_capture_user_id` is persisting when it shouldn't. This PR adds a `sign_out` call to delete the session everywhere before redirecting and showing an error message.
> Delete session data when hybrid session is invalid

- app/forms/backup_code_verification_form.rb
- spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb
The form doesn't have a spec and the controller spec stubs the form, which prevented the form logic from actually running and catching this bug. Removing the stub reveals the problem. This analytics attribute was added in #8718.
> Fix bug in backup code verification

- app/controllers/accounts_controller.rb
- app/controllers/application_controller.rb
- app/controllers/users/please_call_controller.rb
- app/services/analytics_events.rb
- app/views/users/please_call/show.html.erb
- config/locales/users/en.yml
- config/locales/users/es.yml
- config/locales/users/fr.yml
- config/routes.rb
- spec/controllers/accounts_controller_spec.rb
- spec/controllers/application_controller_spec.rb
- spec/controllers/users/please_call_controller_spec.rb
- spec/views/users/please_call/show.html.erb_spec.rb
changelog: User-Facing Improvements, Suspension, Contact support page when suspended user signs in
https://cm-jira.usa.gov/browse/LG-10213
> LG-10213: Implement sign-in suspended users process

- lib/telephony.rb
- lib/telephony/alert_sender.rb
- lib/telephony/configuration.rb
- lib/telephony/otp_sender.rb
- lib/telephony/pinpoint/aws_credential_builder.rb
- lib/telephony/pinpoint/pinpoint_helper.rb
- spec/lib/telephony/alert_sender_spec.rb
- spec/lib/telephony/otp_sender_spec.rb
- spec/lib/telephony/pinpoint/aws_credential_builder_spec.rb
- spec/lib/telephony/pinpoint/sms_sender_spec.rb
- spec/lib/telephony/pinpoint/voice_sender_spec.rb
A small followup to #8610 to add `log_filename` to the Telephony logger. This one was a bit more involved than the ones in #8610 since previously calls were being made directly to `Telephony.config.logger`. This PR refactors the logging to put it behind a method so that we can add the metadata to all logging calls.
> Refactor telephony.log logging to use common interface to enable including metadata in logs

- spec/controllers/idv/link_sent_controller_spec.rb
- spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb
- spec/forms/user_piv_cac_verification_form_spec.rb
Related to a bug that snuck in due to stubbing calls to `:new` (fixed in #8756), this PR tries to remove some of the other instances. The `PersonalKeyForm` ones are the riskiest and ones that should be included, this PR fixes an issue in the tests where the value logged was being asserted incorrectly. The rest of the changes are more stylistic and less pressing.
> Refactor some tests to avoid stubbing calls to .new

- app/controllers/application_controller.rb
- app/controllers/frontend_log_controller.rb
- spec/controllers/application_controller_spec.rb
- spec/controllers/frontend_log_controller_spec.rb
- spec/features/idv/doc_auth/redo_document_capture_spec.rb
This fixes [LG-10192](https://cm-jira.usa.gov/browse/LG-10192)
This PR:
- Adds a new filter to ApplicationController called `skip_session_commit`
- Refactors the existing `skip_session_load` filter to use `skip_session_commit`
- Updates the FrontendLogController to opt out of session committing
- Re-enables IdV "Redo document capture" feature tests previously disabled due to flakiness
If you read from the session while processing a request, rack will, by default, write that session data back to the session store when the request ends. This is referred to as ["committing" the session](https://github.com/rack/rack/blob/v2.2.7/lib/rack/session/abstract/id.rb#L373-L405). 
So if:
- Two requests for the same user are processed in parallel AND
- Both requests read from the session AND
- Only one …
> Don't commit sessions for frontend log requests

- app/views/idv/welcome/show.html.erb
- spec/views/idv/welcome/show.html.erb_spec.rb
Some discussion in Slack [here](https://gsa-tts.slack.com/archives/CNCGEHG1G/p1689183454265999) that concluded that since the controller also checks for full authentication, the template doesn't need to as well. This PR removes the conditional.
> Remove duplicative fully authenticated check in welcome template

- app/controllers/two_factor_authentication/webauthn_verification_controller.rb
- app/javascript/packages/webauthn/converters.ts
- config/locales/two_factor_authentication/en.yml
- config/locales/two_factor_authentication/es.yml
- config/locales/two_factor_authentication/fr.yml
- spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
- spec/features/remember_device/user_opted_preference_spec.rb
- spec/features/remember_device/webauthn_spec.rb
- spec/features/two_factor_authentication/sign_in_spec.rb
- spec/features/webauthn/sign_in_spec.rb
- spec/support/features/webauthn_helper.rb
[LG-10225](https://cm-jira.usa.gov/browse/LG-10225)
Adds support for simulating results of WebAuthn in JavaScript-enabled browsers in specs, allowing for more realistic test scenarios running in a real browser.
For example, this may have helped avoid the scenario fixed in #8738.
```
rspec spec/features/webauthn/sign_in_spec.rb
```
> LG-10225: Add JavaScript-enabled WebAuthn feature spec capability

- config/routes.rb
Adds a redirect route for the error page removed in #8764, as a temporary solution to avoid potential issues during deployment.
See: https://github.com/18F/identity-idp/pull/8764#discussion_r1262564677
```
$ curl -I --silent http://localhost:3000/login/two_factor/webauthn_error | grep Location 
Location: http://localhost:3000/login/two_factor/webauthn
```
> Add temporary redirect for WebAuthn error page

- app/components/webauthn_input_component.rb
- app/components/webauthn_input_component.scss
- app/javascript/packages/webauthn/webauthn-input-element.spec.ts
- app/javascript/packages/webauthn/webauthn-input-element.ts
- app/presenters/two_factor_authentication/webauthn_platform_selection_presenter.rb
- config/application.yml.default
- lib/identity_config.rb
- spec/components/webauthn_input_component_spec.rb
Allows Face or Touch Unlock option to be shown in account creation in local development on devices which do not support passkey, with additional effect to indicate that the passkey is not supported. This is intended to help facilitate testing of Face or Touch Unlock outside devices which are supported for the initial relaunch (iOS 16+ and Android).
**Option enabled:**
3. On the "Authentication method setup" screen, observe that the "Face or touch unlock" option is visible, and tinted red if the current device is not iOS 16+ or Android
**Option enabled:**
Add to `config/application.yml`:
```yml
development:
show_unsupported_passkey_platform_authentication_setup: false
```
3. On the …
> Show Face/Touch Unlock setup on unsupported devices in local development

- app/views/idv/gpo_only_warning/show.html.erb
Removed the troubleshooting section from the phone finder/pinpoint outage screen. A fix for https://github.com/18F/identity-idp/pull/8762
> LG-9526 Remove troubleshooting section on pinpoint outage

- config/locales/two_factor_authentication/en.yml
- config/locales/two_factor_authentication/es.yml
- config/locales/two_factor_authentication/fr.yml
[LG-9790](https://cm-jira.usa.gov/browse/LG-9790)
This is a simple content change to swap the phrase "Choose another option" for "Choose another authentication method". The phrase is found in a link on OTP pages.
The change can be seen when adding or using the authentication method OTP at routes such as:
- `/phone_setup`
- `/login/two_factor/sms`
> LG-9790: Content change for OTP pages

- app/views/idv/gpo/_address_on_file.html.erb
- config/routes.rb
It looks like this GPO action was deleted in #6775 and the `app/views/idv/gpo/_address_on_file.html.erb` template partial became unused. I've deleted both in this PR.
> Delete GPO route that no longer has matching controller action

- app/javascript/packages/build-sass/CHANGELOG.md
- app/javascript/packages/build-sass/index.js
Updates CSS compilation utility to avoid situations where the output stylesheet is temporarily emptied while the contents are being written. This frequently resulted in missing styles when attempting to load pages in the IdP in local development during initial startup.
If pressed, I'm not sure I could explain why the implementation would work any differently between `fs.writeFile` and the writable stream, since both `writeFile` and `createWritableStream` should have the same effect of truncating the original file. But these should be functionally equivalent as far as writing to the file.
1. Remove existing stylesheets `rm -f app/assets/builds/*.css`
2. Run `make run`
3. Go to http://localhost:3000
- You may receive an error before first build, this is expected
4. Observe styles (no …
> Avoid missing styles during CSS compilation

- app/services/marketing_site.rb
- app/views/two_factor_authentication/webauthn_verification/show.html.erb
- config/locales/instructions/en.yml
- config/locales/instructions/es.yml
- config/locales/instructions/fr.yml
- spec/views/two_factor_authentication/webauthn_verification/show.html.erb_spec.rb
Adds a troubleshooting link "Learn more about Face or Touch Unlock" when signing in with Face or Touch Unlock.
This is a straight revert of the commit [02c631d](https://github.com/18F/identity-idp/pull/8741/commits/02c631d6f7c26d9c3d651c3f5b6aa03019dfb671) from #8741.
~Blocked by https://github.com/18F/identity-site/pull/1122~ **Edit:** Blocker has been merged.
2. Sign in to an account with Face or Touch Unlock configured
3. When prompted for MFA, observe link "Learn more about Face or Touch Unlock"
4. Click link
5. Observe that a new tab is opened to the related help article
Before|After
---|---
> LG-10233: Add "Learn more" troubleshooting link to Face or Touch sign-in

- app/javascript/packages/document-capture/components/acuant-camera.tsx
- app/javascript/packages/document-capture/components/acuant-capture.tsx
- spec/javascript/packages/document-capture/components/acuant-capture-spec.jsx
[Check ID 'card type' when using SDK](https://cm-jira.usa.gov/browse/LG-10255)
- Correctly capture acuant document types during sdk image capture. Previously, all document types were captured as "undefined" and logged as "none."
- Update the logs to display when a value other than "none," "id," or "passport" is captured.
- Update spec file to use the key "cardtype" instead of "cardType"
- Write a test for the new log option
- Run automated tests.
- N.B. I didn't notice this bug until I made an actual request to acuant, rather than using our mock client.  As a result, I think acceptance testing done in staging will be more effective than manual testing with the mock client.
Here's a screenshot debugger, which shows the cardType/cardtype bug.
<details>
<summary>Screenshot:</summary> …
> LG-10255: Capture cardtype in sdk

- lib/deploy/activate.rb
This is still a bit experimental and I'm working to confirm that the theory below is correct and the proposed solution resolves the problem we're seeing every now and then.
We've run into the situation a couple times where a built application artifact includes symlinks to the identity-idp-config directory. Since identity-idp-config is cloned each time regardless of whether the artifact exists for the SHA, it is possible for an SP logo to be deleted from identity-idp-config which breaks the symlink and can cause build or provisioning issues.
This PR goes through the target `public` directory for SP logos and deletes any symlinks that exist but do not link to an existing file.
Other options:
- Delete all symlinks regardless of whether they are valid since we'll be re-creating them
- This is …
> Delete invalid symlinks referencing identity-idp-config

- app/components/tab_navigation_component.rb
- spec/components/tab_navigation_component_spec.rb
Improves "current path" detection for TabNavigationComponent, fixing an issue where locale specified through a URL parameter would not be reflected.
Example: https://secure.login.gov/?locale=es
Related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1689604911179219
1. Go to all of the following URLs and observe that "Sign in" is shown as the currently-selected link:
- http://localhost:3000
- http://localhost:3000/es/
- http://localhost:3000/?locale=es
Before|After
---|---
> Fix current path detection for locale URL parameter

- app/controllers/openid_connect/authorization_controller.rb
- app/services/analytics_events.rb
- spec/controllers/openid_connect/authorization_controller_spec.rb
Currently we do not log successful OIDC auth requests when they are not ultimately going to redirect. This was changed in #6942, so this maintains that by splitting the events and ensuring we always log the request when we get it.
I'm not 100% happy with this, but want to get CI going
> Separate OpenID Connect Authorization Request and Handoff Logging

- app/javascript/packs/ssn-field.ts
- tsconfig.json
Continues to chip away at our remaining `tsconfig.json` `excludes` exceptions for TypeScript, by porting `ssn-field.js` to TypeScript.
There are more refactoring opportunities with this file, but I kept the changes limited for review sake:
Verify no regressions in the behavior of SSN field formatting.
> TypeScriptify ssn-field pack

- config/routes.rb
Reverts 18F/identity-idp#8773
The changes in #8773 were intended to be temporary for the initial deploy. This pull request removes them, and should only be merged after #8773 is live in production.
> Revert "Add temporary redirect for WebAuthn error page"

- app/components/tab_navigation_component.rb
- spec/components/tab_navigation_component_spec.rb
Fixes a regression introduced in #8792 where the tab navigation would not show the correct selected tab if the request was not a GET request, such as a submission from the Sign In page.
Note: #8792 is not live yet in production, so this should not be affecting users.
2. Enter an email address and an incorrect password for that email address
3. Submit
4. Observe "Sign in" is still selected
Before|After
---|---
> Fix tab navigation current path detection for non-GET request

- app/forms/register_user_email_form.rb
- spec/forms/register_user_email_form_spec.rb
https://cm-jira.usa.gov/browse/LG-10214
> LG-10214 Fix Suspended User Create Account Email send

- app/javascript/packages/document-capture/components/acuant-camera.tsx
- app/javascript/packages/document-capture/components/acuant-capture.tsx
- app/javascript/packages/document-capture/context/failed-capture-attempts.tsx
- config/locales/doc_auth/en.yml
- config/locales/doc_auth/es.yml
- config/locales/doc_auth/fr.yml
- spec/javascript/packages/document-capture/components/acuant-capture-spec.jsx
- spec/javascript/packages/document-capture/components/capture-troubleshooting-spec.jsx
- spec/javascript/packages/document-capture/components/document-capture-spec.jsx
- spec/javascript/packages/document-capture/components/documents-step-spec.jsx
[LG-10255: Check id 'card type' when using SDK](https://cm-jira.usa.gov/browse/LG-10255)
1. Display an error message when the user, using Acuant SDK, captures a photo of something that is not an ID card type.
2. Prevent the user from submitting photos that have triggered this inline error.
In staging, attempt to submit a photo of a passport.  Voila!  Errors.
> LG-10255: Display inline error messages when Acuant SDK recognizes a document is not an ID card type

- app/javascript/packages/document-capture/components/document-capture.tsx
- app/javascript/packages/document-capture/components/in-person-location-full-address-entry-post-office-search-step.spec.tsx
- app/javascript/packages/document-capture/components/in-person-location-full-address-entry-post-office-search-step.tsx
- app/javascript/packages/document-capture/components/in-person-location-post-office-search-step.spec.tsx
- app/javascript/packs/document-capture.tsx
- app/views/idv/shared/_document_capture.html.erb
- config/application.yml.default
- lib/identity_config.rb
[LG-10405](https://cm-jira.usa.gov/browse/LG-10405)
Note: this is one of multiple PRs for this ticket. There will be additional ones after this PR is merged.
* Adds a new feature flag called `in_person_full_address_entry_enabled` which defaults to `false`
* Pulls the `in_person_full_address_entry_enabled` feature flag into the Document Capture React application
* If the `in_person_full_address_entry_enabled` feature flag is enabled then replaces the current verify/document_capture#location page (eg PO search page) with a new placeholder page
* This page has a step indicator, heading, etc. but does not yet have PO search functionality. A future PR will add that functionality
<details>
<summary>Feature flag off:</summary>
</details> …
> LG-10405: Add new placeholder manual address entry page behind a flag

- config/application.yml.default
https://cm-jira.usa.gov/browse/LG-10259
This PR increases the number of times someone can try to capture their document using the Acuant SDK before the app falls back to native camera capture.
To test these changes you should make sure that you have the mobile device testing working per here: https://github.com/18F/identity-idp/blob/main/docs/mobile.md. There are a couple of extra steps though.
```
doc_auth_error_sharpness_threshold: 100
doc_auth_client_sharpness_threshold: 100
doc_auth_error_sharpness_threshold: 100
```
> LG-10259: Increase doc_auth_max_capture_attempts_before_native_camera to 3

- app/forms/gpo_verify_form.rb
- app/models/profile.rb
- spec/forms/gpo_verify_form_spec.rb
- spec/models/profile_spec.rb
When ThreatMetrix decisioning is not enabled we do not put users through the fraud review process after they enter their GPO code. This requires clearing out the fraud review columns on their profile.
Previously, this was done by explicitly overwriting the fraud review columns on their profile. We are trying to move away from this pattern and moved these methods into the profile.
We recently added `fraud_pending_reason` and since the profile was explicitly overwritten by the GPO verify form we missed that we needed to update it in this case.
This commit adds a method to the profile for activating the profile when fraud review is not necessary. That method is used in the GPO verify form instead of explicitly modifying the profile.
> Clear `fraud_pending_reason` when activating fraud pending profiles when TMx is disabled

- app/models/in_person_enrollment.rb
- spec/factories/in_person_enrollments.rb
- spec/models/in_person_enrollment_spec.rb
[LG-10167](https://cm-jira.usa.gov/browse/LG-10167)
If a user cancels their enrollment, we also want to delete their
saved notification phone number.
```ruby
e = InPersonEnrollment.last
e.status
=> "pending"
e.notification_phone_configuration.present?
=> true
```
```ruby
e.reload.status
=> "cancelled"
e.notification_phone_configuration.present?
=> false
NotificationPhoneConfiguration.count
=> 0
```
> LG-10167: Delete notification phone no when associated enrollment canceled

- .gitlab-ci.yml
Grabs the results of the automated ECR scans and converts them to gitlabs `container_scanning` format for visualization on the Merge Request in Gitlab as well as in the `Security and Compliance` tab alongside the rest of our scanning tools with the tool source being `Container Scanning Amazon Web Services`. Related change for pipeline permissions located [HERE](https://github.com/18F/identity-devops/pull/6408)
New ECR job successfully running as part of this PR [HERE](https://gitlab.login.gov/lg/identity-idp/-/jobs/598162)
> Add ECR reporting to gitlab

- app/javascript/packages/document-capture/components/acuant-camera.tsx
- app/javascript/packages/document-capture/components/acuant-capture.tsx
- spec/javascript/packages/document-capture/components/acuant-capture-spec.jsx
- spec/javascript/packages/document-capture/components/document-capture-spec.jsx
- spec/javascript/packages/document-capture/components/documents-step-spec.jsx
Following up with a few more nice things we can do to simplify and extend enum conversion, based on comment: https://github.com/18F/identity-idp/pull/8789#discussion_r1268247849
> Refactor Acuant document detection to use more enum features

- app/controllers/idv/please_call_controller.rb
- spec/controllers/idv/please_call_controller_spec.rb
The please call controller is used to instruct users who are pending fraud review to contact Login.gov to finish verification.
This controller should only be accessible to users who are fraud review. This commit adds a before action to redirect users in the following scenarios:
1. The user is not fraud review pending
2. The user has been fraud rejected (these users get a different message rendered by a different controller)
This commit also fixes a latent 500 error on this controller. A user who signs in but is not fraud pending would encounter a `NoMethodError` at this line:
```ruby
pending_at = current_user.fraud_review_pending_profile.fraud_review_pending_at
```
> Only let users who are fraud review pending visit the please call controller

- app/models/profile.rb
- app/models/user.rb
- spec/controllers/idv/gpo_verify_controller_spec.rb
- spec/features/idv/steps/gpo_otp_verification_step_spec.rb
- spec/models/user_spec.rb
This commit makes the first change to switch over to the new `fraud_pending_reason` column. It reads from the column instead of the `fraud_review_pending_at` timestamp to determine if a profile is fraud review pending. This will allow us to stop writing to the `fraud_review_pending_at` timestamp until the user actually enters the fraud review workflow and go back and make the value nil for users who have not entered fraud review.
Eventually we will need to consider the presence of `fraud_pending_reason` and absence of `fraud_review_pending_at` as a new state (i.e. the user has not started fraud review but is eligible to start fraud review once they verify their address). That is out of scope for this PR which is intended to switch the reads to make that new state possible in a future …
> LG-9968 Read from `fraud_pending_reason` to find fraud pending profiles

- app/services/email_normalizer.rb
- spec/services/email_normalizer_spec.rb
Helper class we can use to block associated emails
(the rest of the blocking work is coming in a separate PR)
> Add EmailNormalizer (LG-10313)

- lib/telephony/alert_sender.rb
- spec/lib/telephony/alert_sender_spec.rb
A missing `event:` named arg results in `wrong number of arguments (given 1, expected 0; required keyword: event)` error.
(The spec was stubbing but not calling the original implementation, which is why the tests were green before.)
I found this while investigating [this Slack thread](https://gsa-tts.slack.com/archives/C056RD1NEHW/p1689874340147939)
> Fix crasher in Telephony::AlertSender

- app/javascript/packages/document-capture/components/in-person-full-address-search.tsx
- app/javascript/packages/document-capture/components/in-person-location-full-address-entry-post-office-search-step.spec.tsx
- app/javascript/packages/document-capture/components/in-person-location-full-address-entry-post-office-search-step.tsx
- app/javascript/packages/document-capture/components/in-person-outage-alert.spec.tsx
- app/javascript/packages/document-capture/components/in-person-prepare-step.spec.tsx
- app/javascript/packages/document-capture/context/in-person.ts
- app/javascript/packages/form-steps/form-steps.tsx
- app/javascript/packs/document-capture.tsx
- app/views/idv/shared/_document_capture.html.erb
- spec/support/features/in_person_helper.rb
[LG-10405](https://cm-jira.usa.gov/browse/LG-10405)
Add state select component to the work on #8824
<details>
<summary>Form with select component</summary>
</details>
<details>
<summary>Form showing validation error</summary>
</details>
<details>
<summary>Form with selected value</summary>
</details>
> LG-10405: Implement state select in manual address entry form

- app/javascript/packages/document-capture/components/review-issues-step.tsx
- spec/javascript/packages/document-capture/components/review-issues-step-spec.jsx
Remove the tag and consistent display when IPP enabled or disabled.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After: with IPP enabled </summary>
</details>
<details>
<summary>After: with IPP disabled</summary>
</details>
> LG-10224: Doc auth error page shows styling tag hypertext to users

- app/presenters/two_factor_auth_code/authenticator_delivery_presenter.rb
- app/presenters/two_factor_auth_code/backup_code_presenter.rb
- app/presenters/two_factor_auth_code/generic_delivery_presenter.rb
- app/presenters/two_factor_auth_code/personal_key_presenter.rb
- app/presenters/two_factor_auth_code/phone_delivery_presenter.rb
- app/presenters/two_factor_auth_code/piv_cac_authentication_presenter.rb
- app/presenters/two_factor_auth_code/webauthn_authentication_presenter.rb
- app/views/shared/_fallback_links.html.erb
- app/views/two_factor_authentication/backup_code_verification/show.html.erb
- app/views/two_factor_authentication/personal_key_verification/show.html.erb
- app/views/two_factor_authentication/piv_cac_verification/show.html.erb
- app/views/two_factor_authentication/totp_verification/show.html.erb
- spec/presenters/two_factor_auth_code/backup_code_presenter_spec.rb
- spec/presenters/two_factor_auth_code/generic_delivery_presenter_spec.rb
- spec/presenters/two_factor_auth_code/personal_key_presenter_spec.rb
- spec/presenters/two_factor_auth_code/piv_cac_authentication_presenter_spec.rb
- spec/presenters/two_factor_auth_code/webauthn_authentication_presenter_spec.rb
- spec/views/two_factor_authentication/otp_verification/show.html.erb_spec.rb
Refactoring related to [LG-10286](https://cm-jira.usa.gov/browse/LG-10286)
Removes the `help_text` class method from MFA delivery presenters and renders it explicitly in the single place it's used (TOTP). This is part of a larger effort to bring consistency to how troubleshooting options are presented, eventually replacing `fallback_links` with a consistent troubleshooting options component.
2. Create or sign in to an account with TOTP (authentication app) configured
3. When prompted for MFA, observe text "Enter the code from your authenticator app"
- If not prompted for MFA, click and confirm "Forget all browsers" from account dashboard, sign out, and repeat steps 1-3
With the changes in this pull request, there are not expected to be any visual effects. …
> Render TOTP help text in verification view

- app/javascript/packages/document-capture/components/document-capture.tsx
- app/javascript/packages/document-capture/components/in-person-full-address-search.spec.tsx
- app/javascript/packages/document-capture/components/in-person-full-address-search.tsx
- app/javascript/packages/document-capture/components/in-person-location-full-address-entry-post-office-search-step.spec.tsx
- app/javascript/packages/document-capture/components/in-person-location-full-address-entry-post-office-search-step.tsx
- app/javascript/packages/document-capture/components/in-person-outage-alert.spec.tsx
- app/javascript/packages/document-capture/components/in-person-prepare-step.spec.tsx
- app/javascript/packages/document-capture/context/in-person.ts
- app/javascript/packs/document-capture.tsx
- app/views/idv/shared/_document_capture.html.erb
- config/locales/in_person_proofing/en.yml
- config/locales/in_person_proofing/es.yml
- config/locales/in_person_proofing/fr.yml
- spec/features/idv/in_person_spec.rb
- spec/support/features/in_person_helper.rb
[LG-10405](https://cm-jira.usa.gov/browse/LG-10405)
Note: there was some confusion on how to go about getting these changes merged in order to make it into a patch release. This code has already been reviewed in #8815, #8825, and #8824. This PR is to merge these changes into main.
<details>
<summary>how did you pull in these commits?</summary>
```
git checkout tbradley/po-search-aggregate-pr
git pull
git checkout -b sbachstein/po-search-aggregate-against-main
git rebase --onto origin/main 80afdc2c941d37b34bc48ad098bc2597cc4a176f
git commit --allow-empty -m 'changelog: User-Facing Improvements, In-person full address entry, Add full address PO search form'
git push origin sbachstein/po-search-aggregate-against-main
```
</details>
* Refactors the feature flag to use the InPersonContext
* …
> LG-10405: Implement full address PO search page behind feature flag

- app/models/profile.rb
- spec/services/idv/profile_maker_spec.rb
changelog: Internal, Maintenance, Remove unused database column
[LG-10190](https://cm-jira.usa.gov/browse/LG-10190)
Profiles schema should not have "reproof_at" attribute
This PR ignores the `reproof_at` column in the `Profile` class
> Lg 10190 remove reproof at from profiles 1 of 2

- app/presenters/two_factor_auth_code/phone_delivery_presenter.rb
- app/views/two_factor_authentication/webauthn_verification/show.html.erb
- app/views/users/phone_setup/spam_protection.html.erb
- config/locales/two_factor_authentication/en.yml
- config/locales/two_factor_authentication/es.yml
- config/locales/two_factor_authentication/fr.yml
- spec/views/phone_setup/spam_protection.html.erb_spec.rb
Refactoring related to [LG-10286](https://cm-jira.usa.gov/browse/LG-10286)
Removes "phone" as a qualifier for the "Learn more about authentication options" troubleshooting text, as refactoring ahead of planned common usage across all MFA types.
1. SIgn in to an account which has a phone configured
2. Observe no regressions in appearance of the troubleshooting text "Learn more about authentication options"
> Generalize MFA learn more locale string key

- app/controllers/concerns/remember_device_concern.rb
- app/controllers/concerns/two_factor_authenticatable_methods.rb
- app/controllers/two_factor_authentication/backup_code_verification_controller.rb
- app/controllers/two_factor_authentication/otp_verification_controller.rb
- app/controllers/two_factor_authentication/totp_verification_controller.rb
- app/controllers/two_factor_authentication/webauthn_verification_controller.rb
- app/controllers/users/totp_setup_controller.rb
- app/controllers/users/webauthn_setup_controller.rb
- app/views/partials/backup_code/_entry_fields.html.erb
- app/views/two_factor_authentication/backup_code_verification/show.html.erb
- spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
- spec/features/two_factor_authentication/backup_code_sign_up_spec.rb
Currently, we do not allow people to select a remembered device preference when logging in with backup codes. This PR adds the ability to do that.
> Allow setting remembered device preference when logging in with backup codes (LG-10434)

- app/forms/gpo_verify_form.rb
- app/models/profile.rb
- app/services/idv/profile_maker.rb
- lib/tasks/backfill_fraud_review_pending_at.rake
- spec/controllers/idv/personal_key_controller_spec.rb
- spec/models/profile_spec.rb
In #8814 we started the process of changing how we manage fraud review pending profiles.
The fraud review workflow takes place after the user has completed all of the other identity verification workflow steps. Functionally this means is comes immediatly after the IdV flow for users who verify with a phone and after GPO code entry for users who verify by mail.
In the old model, users marked for fraud review are considered in "fraud review" from the moment their profile is created up until they complete the fraud review workflow. This is problematic because functionally we do not make the decision about whether a user is in fraud review until the moment they are about to enter the workflow. For the out-of-band verify-by-mail flow this means several months can pass and business logic can …
> LG-9968 Only write to fraud_review_pending_at when a user starts the fraud review process

- app/controllers/sign_up/passwords_controller.rb
- spec/features/users/sign_up_spec.rb
Currently, the rules of use check is only applied when submitting email address and password for an existing account. This change adds the check so that it also applies when initially setting an account password.
> Prompt users to accept rules of use when account was set up prior to rules of use change

- spec/bin/oncall/email-deliveries_spec.rb
Fixes a small warning that we're seeing when running rubocop:
```
spec/bin/oncall/email-deliveries_spec.rb: Metrics/LineLength has the wrong namespace - should be Layout
spec/bin/oncall/email-deliveries_spec.rb: Metrics/LineLength has the wrong namespace - should be Layout
```
> Fix Rubocop namespace deprecation

- app/jobs/get_usps_proofing_results_job.rb
- spec/jobs/get_usps_proofing_results_job_spec.rb
[LG-10248](https://cm-jira.usa.gov/browse/LG-10248)
- This is cleanup prior to implementation of the ticket.
- Move the SMS notification job to the appropriate queue
- This prevents a queue time alarm from being accidentally triggered.
- Remove redundant conditional for performing job
- Jobs scheduled for the past get executed almost immediately.
- Remove redundant record update
- Precise timing will vary until the original story is completed.
Note that this may be more easily simulated for a local dev stack by using a command like the following:
```sh
bundle exec rails dev:random_in_person_users NUM_USERS='1' SCRYPT_COST='800$8$1$' ENROLLMENT_STATUS='passed'
```
> Move SMS job to appropriate queue; remove redundant update

- config/application.yml.default
[LG-10446](https://cm-jira.usa.gov/browse/LG-10446)
- Prevent user from seeing document capture tips after they fail sdk image capture three times.
Here is a screenshot of the page that we DON'T want the user to see
<details>
<summary>Document Capture Tips:</summary>
</details>
> Hide doc capture tips from users

- config/locales/idv/en.yml
- config/locales/idv/fr.yml
- config/locales/instructions/fr.yml
- config/locales/user_mailer/en.yml
- config/locales/user_mailer/es.yml
- config/locales/user_mailer/fr.yml
- spec/i18n_spec.rb
Adds a test case which checks for matching sets of HTML tags across all locales for a given string key, and resolves current issues.
See discussion: https://github.com/18F/identity-idp/pull/8837#discussion_r1272582933
```
rspec spec/i18n_spec.rb
```
Confirm no regressions in affected string usage.
> Add tests to check for matching HTML tags across locales

- app/jobs/get_usps_proofing_results_job.rb
- spec/jobs/get_usps_proofing_results_job_spec.rb
[LG-10248](https://cm-jira.usa.gov/browse/LG-10248)
- Send in-person proofing email and SMS based on the time we received a status update from USPS
- Minor nonfunctional refactoring of the job
- Minor test updates
Note that this may be more easily simulated for a local dev stack by using a command like the following:
```sh
bundle exec rails dev:random_in_person_users NUM_USERS='1' SCRYPT_COST='800$8$1$' ENROLLMENT_STATUS='pending'
```
The details of the associated jobs can be observed by [enabling the GoodJob dashboard](https://github.com/bensheldon/good_job/blob/main/README.md#dashboard) and [preserving job records](https://github.com/bensheldon/good_job/blob/main/README.md#monitor-and-preserve-worked-jobs).
This was tested locally by stubbing the proofer's API response using the …
> LG-10248: Send in-person proofing notifications based on the status update time

- app/controllers/idv/phone_controller.rb
- app/forms/idv/phone_form.rb
- app/javascript/packs/idv-phone-alert.ts
- app/services/idv/phone_step.rb
- app/services/idv/session.rb
- app/views/idv/phone/new.html.erb
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- spec/controllers/idv/phone_controller_spec.rb
- spec/features/idv/end_to_end_idv_spec.rb
- spec/features/idv/steps/phone_step_spec.rb
- spec/services/idv/session_spec.rb
[LG-9499](https://cm-jira.usa.gov/browse/LG-9499)
- add list of failed phone numbers to idv_session which is added to each time a phone verification fails
- add list of failed phone numbers to phone form to determine if inputted number has already failed; and, if so show alert message
<details>
</details>
> LG-9499: Add banner to alert user they already tried to verify with a phone number

- app/jobs/get_usps_proofing_results_job.rb
- app/jobs/in_person/send_proofing_notification_job.rb
- app/models/in_person_enrollment.rb
- app/services/analytics_events.rb
- config/application.yml.default
- spec/jobs/get_usps_proofing_results_job_spec.rb
- spec/jobs/in_person/send_proofing_notification_job_spec.rb
- spec/models/in_person_enrollment_spec.rb
Related to [LG-10126](https://cm-jira.usa.gov/browse/LG-10126)
Follow-up to #8772, refactors related to the implementation of `SendProofingNotificationJob`.
The only functional changes:
- Only invokes the job when we get a pass/fail from the USPS API
- Log notification job 'skipped' when the enrollment can't be found (instead of 'completed')
- Capture exceptions and log them with a new analytics event
- Converts telephony response to a hash before logging it
> LG-10126: SendProofingNotificationJob refactor

- app/forms/reset_password_form.rb
- spec/controllers/users/reset_passwords_controller_spec.rb
- spec/forms/reset_password_form_spec.rb
When a user resets their password it deactivates their active profile. We log that we do that.
Additionally, we invalidate any pending profiles which will encounter a encryption error when the user logs in. This commit adds logging to log that a pending profile is present and the reasons that it is pending so we can measure the impact of this behavior at password reset
> LG-8763 Log that a profile is pending on password reset

- app/forms/register_user_email_form.rb
- app/models/email_address.rb
- app/models/suspended_email.rb
- app/models/user.rb
- db/primary_migrate/20230720183509_create_suspended_emails_table.rb
- db/schema.rb
- spec/factories/suspended_emails.rb
- spec/forms/register_user_email_form_spec.rb
- spec/models/suspended_email_spec.rb
- spec/models/user_spec.rb
[LG-10313](https://cm-jira.usa.gov/browse/LG-10313)
> LG-10313: Blocking associated emails for Gmail when suspended

- app/controllers/idv/hybrid_handoff_controller.rb
- app/controllers/users/two_factor_authentication_controller.rb
- app/forms/idv/api_image_upload_form.rb
- app/javascript/packages/document-capture/components/document-capture.tsx
- app/javascript/packages/document-capture/components/review-issues-step.tsx
- app/services/idv/steps/doc_auth_base_step.rb
- app/views/idv/gpo_verify/throttled.html.erb
- app/views/idv/session_errors/throttled.html.erb
- app/views/users/verify_personal_key/throttled.html.erb
- config/locales/errors/en.yml
- config/locales/errors/es.yml
- config/locales/errors/fr.yml
- config/locales/telephony/en.yml
- config/locales/telephony/es.yml
- config/locales/telephony/fr.yml
- lib/telephony/errors.rb
- lib/telephony/pinpoint/sms_sender.rb
- lib/telephony/pinpoint/voice_sender.rb
- spec/controllers/idv/image_uploads_controller_spec.rb
- spec/controllers/users/two_factor_authentication_controller_spec.rb
- spec/features/idv/doc_auth/document_capture_spec.rb
- spec/features/idv/doc_auth/hybrid_handoff_spec.rb
- spec/features/users/sign_up_spec.rb
- spec/forms/idv/api_image_upload_form_spec.rb
- spec/javascript/packages/document-capture/components/review-issues-step-spec.jsx
- spec/lib/telephony/pinpoint/sms_sender_spec.rb
- spec/lib/telephony/pinpoint/voice_sender_spec.rb
- spec/presenters/image_upload_response_presenter_spec.rb
- spec/views/idv/session_errors/throttled.html.erb_spec.rb
[LG-10252](https://cm-jira.usa.gov/browse/LG-10252)
As a followup to PR #8706, rename translation tags that contained 'throttle'.
And a stray ThrottledError under lib/telephony that I missed before.
Automated tests.
> LG-10252 Rename throttle translation tags

- lib/tasks/remove_verified_at_for_non_verified.rake
[LG-10121](https://cm-jira.usa.gov/browse/LG-10121)
You can see the in-depth roll plan for this in [ROLL-0017](https://docs.google.com/document/d/1-R60EoEy0o3N_aZumirS4iv1EX4ozU4dILGZsq9wJ0I/edit?pli=1#heading=h.hszo4s1dz96d)
We found out that there were profiles that had the verified_at field populated when they shouldn’t. These profiles still had a gpo_verification_pending_at or fraud_review_pending_at timestamp meaning that they haven’t completed verification yet. This roll plan removes the verified_at attribute from those profiles.
> LG-10121 remove verified_at from users who have not finished verification.

- app/javascript/packages/webauthn/index.ts
- app/javascript/packages/webauthn/is-expected-error.spec.ts
- app/javascript/packages/webauthn/is-expected-error.ts
- app/javascript/packages/webauthn/webauthn-verify-button-element.spec.ts
- app/javascript/packages/webauthn/webauthn-verify-button-element.ts
- app/javascript/packs/webauthn-setup.ts
[LG-10457](https://cm-jira.usa.gov/browse/LG-10457)
Adds error tracking for "unexpected" errors that occur during WebAuthn enrollment or authentication. An unexpected error is one not occurring as an outcome of the WebAuthn API ceremony, but rather may point to errors in our own code.
See Slack discussion: https://gsa-tts.slack.com/archives/C01710KMYUB/p1690308232479249
**Test expected errors:**
Add a breakpoint to `trackError`:
```diff
diff --git a/app/javascript/packages/analytics/index.ts b/app/javascript/packages/analytics/index.ts
index 1f0f43d4c..ee31274f3 100644
--- a/app/javascript/packages/analytics/index.ts
+++ b/app/javascript/packages/analytics/index.ts
@@ -33,2 +33,3 @@ export function trackEvent(event: string, payload?: object) {
export function trackError(error: Error) {
+ …
```
> LG-10457: Track unexpected WebAuthn errors

- app/controllers/application_controller.rb
- spec/features/openid_connect/phishing_resistant_required_spec.rb
- spec/features/saml/phishing_resistant_required_spec.rb
[LG-10442](https://cm-jira.usa.gov/browse/LG-10442)
Fixes the behavior of the redirect logic for a partner requesting phishing-resistant MFAs to account for a user which has Face or Touch Unlock configured. Previously, the user would be redirected to authenticate with Security Key which, when combined with the changes introduced in #8795, would prevent the user from being able to successfully authenticate.
3. At MFA setup, select Face or Touch Unlock
- You can select multiple MFA, but avoid Security Key and PIV as your second MFA method for the purpose of this bug
4. Complete account creation
5. Click "Forget all browsers" in account sidebar and confirm prompt
6. Sign out
7. With [sample RP …
> LG-10442: Fix required MFA redirect for platform authenticator

- app/javascript/packages/webauthn/is-expected-error.ts
Addendum for [LG-10457](https://cm-jira.usa.gov/browse/LG-10457)
Revises the exception set for allowable errors introduced in #8859's error tracking to also allow `InvalidStateError`. After testing this in a live environment, it was observed that `InvalidStateError` frequently may occur when a user attempts to enroll an authenticator that's already been registered.
1. Create an account with security key
2. Add a security key from account dashboard
3. In browser DevTools console, add a breakpoint at https://github.com/18F/identity-idp/blob/93ecd59205910b19e72e56a59a90537387d73d2d/app/javascript/packages/analytics/index.ts#L34
4. Assuming it's the same security key, observe breakpoint is not triggered
> Exempt "InvalidStateError" from WebAuthn error tracking

- app/jobs/get_usps_proofing_results_job.rb
- app/jobs/in_person/send_proofing_notification_job.rb
- app/models/in_person_enrollment.rb
- lib/tasks/dev.rake
- spec/controllers/idv/cancellations_controller_spec.rb
- spec/controllers/idv/getting_started_controller_spec.rb
- spec/controllers/idv/review_controller_spec.rb
- spec/controllers/idv/sessions_controller_spec.rb
- spec/controllers/idv/welcome_controller_spec.rb
- spec/forms/gpo_verify_form_spec.rb
- spec/jobs/get_usps_proofing_results_job_spec.rb
- spec/jobs/in_person/send_proofing_notification_job_spec.rb
- spec/lib/tasks/dev_rake_spec.rb
- spec/models/in_person_enrollment_spec.rb
- spec/services/usps_in_person_proofing/enrollment_helper_spec.rb
Related to [LG-10126](https://cm-jira.usa.gov/browse/LG-10126)
Has the `InPersonEnrollment` model delete `NotificationPhoneConfiguration` associated with enrollments when they expire, rather than relying on the `GetUspsProofingResultsJob` or the `SendProofingNotificationJob` to delete them. (see d67c9031eb61ff522acd766540d8b4f1ad7f991e)
Also starts using constants to refer to the in person enrollment states, for clarity when reading and writing code. (see c0e725d0d1cc1c5574d99895eaf8c1c124fb90d5)
> LG-10126: For notification phone configurations; handle expired enrollments outside of jobs

- app/controllers/idv/agreement_controller.rb
- app/controllers/idv/getting_started_controller.rb
- app/javascript/packs/document-capture-welcome.ts
- spec/controllers/idv/agreement_controller_spec.rb
- spec/controllers/idv/getting_started_controller_spec.rb
_Kind of_ related to [LG-10402](https://cm-jira.usa.gov/browse/LG-10402)
We've already renamed "upload" step of IdV to "hybrid handoff". This PR begins the process of renaming an internal parameter from `skip_upload` to `skip_hybrid_handoff`. To handle the 50/50 state during deployment, we'll temporarily send both `skip_upload` and `skip_hybrid_handoff` and let our controllers accept both. A future PR (to be merged after this is deployed) will fully remove support for `skip_upload`.
This PR also adds some test coverage for what happens when `skip_upload` or `skip_hybrid_handoff` is present–the details of this will change with work on LG-10402, but I wanted to capture it as it is here.
_Also_, since we're in the process of A/B testing a new unified "Getting Started" screen, this PR …
> Start renaming skip_upload parameter

- app/services/analytics_events.rb
- spec/jobs/in_person/send_proofing_notification_job_spec.rb
related to [LG-10126](https://cm-jira.usa.gov/browse/LG-10126)
Standardize SendProofingNotificationJob analytics event messages and update tests; no functional changes.
> LG-10126: Standardize event messages

- app/controllers/concerns/idv/verify_info_concern.rb
- app/controllers/concerns/rate_limit_concern.rb
- app/controllers/idv/gpo_verify_controller.rb
- app/controllers/idv/hybrid_handoff_controller.rb
- app/controllers/idv/phone_errors_controller.rb
- app/controllers/users/verify_personal_key_controller.rb
- app/forms/idv/api_image_upload_form.rb
- app/forms/register_user_email_form.rb
- app/services/analytics_events.rb
- app/services/idv/phone_step.rb
- app/services/idv/steps/doc_auth_base_step.rb
- app/services/irs_attempts_api/tracker_events.rb
- app/services/request_password_reset.rb
- spec/controllers/idv/gpo_verify_controller_spec.rb
- spec/controllers/idv/phone_controller_spec.rb
- spec/controllers/idv/phone_errors_controller_spec.rb
- spec/controllers/idv/verify_info_controller_spec.rb
- spec/controllers/idv_controller_spec.rb
- spec/controllers/sign_up/registrations_controller_spec.rb
- spec/controllers/users/reset_passwords_controller_spec.rb
- spec/controllers/users/verify_personal_key_controller_spec.rb
- spec/features/idv/doc_auth/document_capture_spec.rb
- spec/features/idv/doc_auth/hybrid_handoff_spec.rb
- spec/features/idv/doc_auth/verify_info_step_spec.rb
- spec/forms/register_user_email_form_spec.rb
- spec/services/request_password_reset_spec.rb
[LG-10252](https://cm-jira.usa.gov/browse/LG-10252)
- As a followup to PR #8706, rename analytics events and arguments that contain 'throttle'.
- Event `Throttler Rate Limit Triggered` is now `Rate Limit Reached`.
- Also rename irs_attempts_api argument `throttle_context` to `limiter_context`
NOTE:
- This requires coordination with a devops terraform deploy to change any dashboards that use these events
- Searched in identity-devops repo, but it only refers to the rack_attack event `Rate Limit Triggered`, which is separate from the one renamed here.
- Check with @ThatSpaceGuy about change to irs_attempts_api 
- @zachmargolis confirmed that it's not a problem.
- Notify Rodolfo Ornelas of analytics changes.
Automated tests.
> LG-10252 Rename throttle analytics

- app/views/sign_up/emails/show.html.erb
- app/views/users/emails/verify.html.erb
- spec/views/sign_up/emails/show.html.erb_spec.rb
- spec/views/users/emails/verify.html.erb_spec.rb
> Fix 500 Error: Create Account with Suspended User Email Using "+" sign

- bin/query-cloudwatch
- lib/reporting/cloudwatch_client.rb
- spec/bin/query-cloudwatch_spec.rb
Supports [LG-7708](https://cm-jira.usa.gov/browse/LG-7708)
Adds new `--count-distinct` option to `bin/query-cloudwatch` to help produce a total distinct count from a query that may need to be stitched together with the `--complete` functionality.
Example usage:
```
bin/query-cloudwatch --from 1h --env int --app idp --log events.log --count-distinct properties.user_id --query "filter name = 'Multi-Factor Authentication' and properties.event_properties.success = 1"
```
> Add "count distinct" option to CloudWatch query script

- app/controllers/users/sessions_controller.rb
- app/services/analytics_events.rb
- spec/controllers/users/sessions_controller_spec.rb
- spec/features/two_factor_authentication/sign_in_spec.rb
In https://github.com/18F/identity-idp/pull/897, we made the change to log a user out if they went to the root URL while partially authenticated (typically precipitated by clicking the logo at an MFA screen). In gathering some analytics from #8838, it seems as though many users are unintentionally being logged out. Around 50% of users that were logged out in this manner re-authenticated shortly after. Further discussion can be found [here](https://gsa-tts.slack.com/archives/C01710KMYUB/p1690214951246489).
This PR changes the redirect to go to MFA selection.
> Do not log user out when accessing root url while partially authenticated

- app/controllers/concerns/idv/document_capture_concern.rb
- app/services/idv/session.rb
- app/services/idv/steps/doc_auth_base_step.rb
- app/views/idv/in_person/verify_info/show.html.erb
We are working to retire `flow_session` as part of retiring FSM and restoring the back button functionality.
This commit starts to move one of the properties, `had_barcode_read_failure`, into `idv_session`. Another commit will be necessary to start reading from the `idv_session` and then a final commit to stop writing to `flow_session`.
> LG-10439 Add `had_barcode_read_failure` to `idv_session`

- app/javascript/packages/webauthn/enroll-webauthn-device.spec.ts
- app/javascript/packages/webauthn/enroll-webauthn-device.ts
- app/javascript/packs/webauthn-setup.ts
- spec/forms/webauthn_setup_form_spec.rb
[LG-10477](https://cm-jira.usa.gov/browse/LG-10477)
Fixes #8877
Updates WebAuthn enrollment logic to gracefully handle absence of WebAuthn APIs not implemented in all browsers, notably fixing an issue where it is not currently possible to add a Security Key in Firefox.
Recommend reviewing with whitespace changes hidden: https://github.com/18F/identity-idp/pull/8904/files?w=1
1. In Firefox, go to http://localhost:3000
3. At MFA selection screen, choose Security Key
4. Complete account creation, using Security Key as the MFA
Before|After
---|---
> LG-10477: Add checks for WebAuthn browser support

- app/views/idv/phone/new.html.erb
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- spec/features/idv/steps/phone_step_spec.rb
[LG-10511](https://cm-jira.usa.gov/browse/LG-10511)
Update copy for alert that notifies users they are retrying a failed number during IDV phone step.
<details>
</details>
<details>
</details>
> LG-10511: Update copy for banner that notifies user they already tried to verify with a phone number

- app/models/profile.rb
- db/primary_migrate/20230727195406_add_in_person_verification_pending_at_to_profiles.rb
- db/primary_migrate/20230728203252_add_in_person_enrollment_pending_at_to_profiles.rb
- db/schema.rb
[LG-10382](https://cm-jira.usa.gov/browse/LG-10382)
Created two new columns in IdV user's profile for in person verification:
`in_person_verification_pending_at` is a timestamp for when a profile gets "deactivated" for in person verification.
~`in_person_enrollment_pending_at` is a timestamp for when a user has a pending enrollment. This column is meant to~ We can use #user.establishing_in_person_enrollment to replace the `pending_profile&.proofing_components&.[]('document_check') == Idp::Constants::Vendors::USPS` for an in_person_enrollment and make it more explicit in a user's profile.
> LG-10385 Add new columns for in-person proofing pending

- app/controllers/concerns/rate_limit_concern.rb
- app/controllers/idv/capture_doc_status_controller.rb
- app/presenters/image_upload_response_presenter.rb
- app/services/idv/steps/doc_auth_base_step.rb
- config/routes.rb
- spec/controllers/concerns/rate_limit_concern_spec.rb
- spec/controllers/idv/document_capture_controller_spec.rb
- spec/controllers/idv/image_uploads_controller_spec.rb
- spec/controllers/idv_controller_spec.rb
- spec/features/idv/doc_auth/document_capture_spec.rb
- spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb
- spec/presenters/image_upload_response_presenter_spec.rb
Change /verify/session/errors/throttled route to /verify/session/errors/rate_limited
[LG-10252](https://cm-jira.usa.gov/browse/LG-10078)
This is a followup to #8886. Once that's deployed, this one can be merged, to cover the 50/50 state.
> LG-10252 Finish renaming /verify/session/errors/throttled to /rate_limited

- app/assets/stylesheets/utilities/_util.scss
- app/views/accounts/_header.html.erb
- app/views/users/authorization_confirmation/new.html.erb
Removes the `sm-left-align` CSS utility class.
**Why?**
- Reduce size of application stylesheet
- Remove legacy references to "sm" as referring to BassCSS breakpoints, now standardized toward "tablet" USWDS breakpoint token
- Simplify usage leveraging left text alignment as default behavior
Recommend reviewing with whitespace changes hidden: https://github.com/18F/identity-idp/pull/8917/files?w=1
Verify no regressions in the affected usage:
1. Account management page header
2. Authenticating with a partner when already signed-in
There's not expected to be any visual effect of these changes. Below are screenshots noting the affected usage, which should be unaffected.
> Remove sm-left-align custom CSS utility class

- app/controllers/idv/capture_doc_status_controller.rb
- app/controllers/idv/verify_info_controller.rb
- app/services/idv/steps/doc_auth_base_step.rb
We are working on removing the flags that indicate a barcode read error from the `flow_session` and adding them to `idv_session` instead.
The work to write the values to `idv_session` was handled in #8881 and #8889. That has been deployed so it is not safe to start reading the values from `idv_session`. A future commit will stop writing them to `flow_session`.
> LG-10439 Read barcode read error values from the session

- app/presenters/two_factor_options_presenter.rb
- app/views/users/two_factor_authentication_setup/index.html.erb
- config/locales/two_factor_authentication/en.yml
- config/locales/two_factor_authentication/es.yml
- config/locales/two_factor_authentication/fr.yml
[LG-10372](https://cm-jira.usa.gov/browse/LG-10372)
Adds a new method to insert a more concise legend to the MFA option form correcting screen reader experience that was displaying a redundant description of the form as a copy of the intro text above.
`en: <legend class="margin-bottom-2 usa-sr-only">Choose your authentication methods</legend>`
`fr: <legend class="margin-bottom-2 usa-sr-only">Elija sus métodos de autenticación</legend>`
`sp: <legend class="margin-bottom-2 usa-sr-only">Choisissez vos méthodes d'authentification</legend>`
> LG 10372 Shorten Fieldset for MFA option setup

- app/forms/openid_connect_authorize_form.rb
- app/forms/openid_connect_token_form.rb
- spec/controllers/openid_connect/authorization_controller_spec.rb
- spec/controllers/openid_connect/token_controller_spec.rb
- spec/forms/openid_connect_authorize_form_spec.rb
- spec/forms/openid_connect_token_form_spec.rb
A follow-up to #8919 to improve understanding of PKCE usage
> Add logging of PKCE configuration

- config/locales/mfa/en.yml
[LG-10373: Assistive technology reads "two" twice in authentication method setup](jira.usa.gov/browse/LG-10373)
This PR fixes a bug where "two" is read twice by a screen reader. It will now be announced once.
With a screen reader of your choice
After logging on to [localhost:3000](localhost:3000)
https://github.com/18F/identity-idp/assets/17969963/1bf63838-2c61-460c-aeb1-fcb535fae44d
> LG-10373: Assistive technology reads "two" twice in authentication method setup

- config/database.yml
We've been seeing some odd connection errors connecting to the worker database since #8536 ([NewRelic](https://onenr.io/0qwLvPlGkj5)). The major change was postgis adapter for connections to all databases, but since the worker database does not have `postgis` or use it, this PR changes it so the default connection is `postgresql` and the `postgis` databases override the `adapter.
This was tested in my sandbox.
> Only use postgis adapter for primary database

- Gemfile.lock
- app/javascript/packages/phone-input/package.json
- spec/forms/idv/phone_form_spec.rb
- spec/services/phone_formatter_spec.rb
- yarn.lock
We received reports that valid US phone numbers were being rejected, and it is in part due to outdated phone validation libraries. This PR updates them.
> Update phonelib dependencies to add support for newer area codes

- app/controllers/concerns/idv/document_capture_concern.rb
- app/controllers/idv/capture_doc_status_controller.rb
- spec/controllers/idv/capture_doc_status_controller_spec.rb
We are phasing out `flow_session` after retiring the flow state machine. This commit is part of the effort related to that. Specifically it is removing the barcode read errors from flow session.
#8881 and #8889 started writing the barcode read error flags to the `idv_session`. #8925 started reading from `idv_session`. With those steps done and deployed it should be safe to stop writing the value to `flow_session` as a final step.
> LG-10342 Remove the last barcode error writes to flow_session

- app/controllers/idv/agreement_controller.rb
- app/controllers/idv/getting_started_controller.rb
- app/controllers/idv/hybrid_handoff_controller.rb
- app/services/analytics_events.rb
- app/views/idv/hybrid_handoff/show.html.erb
- spec/controllers/idv/agreement_controller_spec.rb
- spec/controllers/idv/getting_started_controller_spec.rb
- spec/controllers/idv/hybrid_handoff_controller_spec.rb
#8894 started writing `skip_hybrid_handoff` to `IdvSession` alongside `flow_session[:skip_upload_step]`. This PR removes references to `flow_session[:skip_upload_step]`. It will be safe to merge once #8894 has been deployed.
[LG-10402](https://cm-jira.usa.gov/browse/LG-10402)
> LG-10402: Finish renaming skip_upload_step

- app/forms/idv/phone_form.rb
- spec/forms/idv/phone_form_spec.rb
This fixes a small non-production-impacting bug where if a user is using a phone in a country where we do not support unregistered numbers, they may be denied due to inconsistent formatting when comparing numbers. This PR ensures they are compared with the same format, similar to how we do [here](https://github.com/18F/identity-idp/blob/5ba3ded47ee1bb997a0caf62263accfa6fffcad0/app/forms/new_phone_form.rb#L120-L122).
> Ensure phone ownership is compared reliably when validating phone numbers

- app/controllers/users/sessions_controller.rb
- spec/controllers/users/sessions_controller_spec.rb
- spec/features/two_factor_authentication/sign_in_spec.rb
- spec/features/users/sign_in_spec.rb
- spec/features/users/sign_up_spec.rb
- spec/support/features/session_helper.rb
- spec/support/sp_auth_helper.rb
Fixes an issue from https://github.com/18F/identity-idp/pull/8895 where the user would be redirected to their (empty) MFA configurations listing when either clicking the logo link or otherwise visiting the homepage after having only partially completed account creation, up to MFA selection.
This should also be more consistent with similar redirect behavior that exists in `ApplicationController#signed_in_url`:
https://github.com/18F/identity-idp/blob/a102eb1158f1adcaf99779ea33b5d62f2d84faca/app/controllers/application_controller.rb#L229
**Account Creation:**
2. Click Create an account
3. At any point in account creation, click the logo
4. Observe that you're redirected to where you might expect to be redirected
- Visiting from password confirmation redirects …
> Fix partial sign-in homepage redirect for account creation

- app/models/profile.rb
- app/services/encryption/encryptors/pii_encryptor.rb
- app/services/encryption/regional_ciphertext_pair.rb
- spec/models/user_spec.rb
- spec/services/encryption/encryptors/pii_encryptor_spec.rb
- spec/support/shared_examples/sign_in.rb
We are working on migrating to a new KMS key that has multi-region capabilities. Migrating to this new key will require storing both single region and multi-region ciphertexts in the database. Moreover, the inner layer of these ciphertexts is expected to match so we cannot have 2 encryptors, 1 with the new key and 1 with the old.
This commit introduces a `RegionalCiphertextPair` struct. It is intended to be returned from the `PiiEncryptor` and eventually the `PasswordVerifier`.
Consumers of the `PiiEncryptor#encrypt` methods can break up the `RegionalCiphertextPair` and store the single region and multi-region ciphertexts independently. On decryption the ciphertext pair can be reconstructed and used as the argument to `PiiEncryptor#decrypt`.
> LG-10342 Introduce ciphertext pair for managing single and multi-region KMS ciphertexts

- app/services/marketing_site.rb
- app/views/user_mailer/please_reset_password.html.erb
Removes `MarketingSite` URL helpers for two outdated URLs which predate the brochure site redesign:
1. `MarketingSite.help_hardware_security_key_url`
- URL: https://www.login.gov/help/signing-in/what-is-a-hardware-security-key/
- The above URL 404s, but fortunately this helper was not used anywhere in the application
- Follow-up to see if the URL was valid at any point and should have a redirect established in `identity-site`
2. `MarketingSite.help_which_authentication_method_url`
- URL: https://www.login.gov/help/authentication-methods/which-authentication-method-should-i-use/
- Updated URL: https://www.login.gov/help/get-started/authentication-options/
`help_authentication_app_url` should also be updated, but this will be handled in LG-9469.
1. Go to …
> Remove legacy/outdated help center URLs

- config/application.yml.default
- config/service_providers.localdev.yml
- spec/controllers/saml_idp_controller_spec.rb
- spec/decorators/service_provider_session_decorator_spec.rb
- spec/features/idv/doc_auth/verify_info_step_spec.rb
- spec/features/openid_connect/openid_connect_spec.rb
- spec/features/remember_device/session_expiration_spec.rb
- spec/features/remember_device/sp_expiration_spec.rb
- spec/features/reports/sp_active_users_report_spec.rb
- spec/features/saml/saml_spec.rb
- spec/features/sign_in/banned_users_spec.rb
- spec/features/sign_in/remember_device_default_spec.rb
- spec/features/users/sign_up_spec.rb
- spec/support/oidc_auth_helper.rb
- spec/support/saml_auth_helper.rb
- spec/support/shared_examples/remember_device.rb
This change was made across our live environments a few months ago ([thread](https://gsa-tts.slack.com/archives/C0NGESUN5/p1675886655627409)), but I never followed up to make it consistent everywhere. This PR changes the default to zero.
[EDIT]
There was quite a bit of testing that assumed different behaviors of AAL2/remembered device, so this PR also applies some changes to hopefully make those easier to maintain going forward. Test coverage difference between this PR and main does not show a reduction (in line or branch-based), which isn't conclusive that we haven't lost certain permutations of some behavior being tested, but is sufficient for me to move forward with the changes.
> Set Remember Device Expiration for AAL2 to 0 hours

- spec/rails_helper.rb
- spec/support/capybara.rb
Chromedriver versions are behind Chrome, so we need to hardcode the version until Chromedriver catches up.
This is affecting more and more devs who want to run feature specs, and it's a hassle to keep an edited rails_helper.rb around without committing it. We can revert this when we get a version of Chromedriver that works.
ETA: Looks like we need to upgrade the version of Chrome that CI uses to make this work. Is that an option?
> Hardcode chromedriver version until we get an upgrade that works

- app/controllers/idv/phone_errors_controller.rb
- spec/controllers/idv/phone_errors_controller_spec.rb
We are investigating whether the GettingStarted page makes a significant difference in the number of errors users get at the phone step.
> Add A/B test buckets to phone errors controller analytics

- config/locales/account/en.yml
Updates capitalization of "Add Face or Touch Unlock" to be consistent with initial capitalization of other MFA methods, and consistent with lower-casing of "face or touch unlock" generally.
Before: "Add Face or Touch Unlock"
After: "Add face or touch unlock"
Slack discussion: https://gsa-tts.slack.com/archives/C01710KMYUB/p1691508095280409?thread_ts=1691446260.169989&cid=C01710KMYUB
1. Sign in to an account
2. From account dashboard, observe link "Add face or touch unlock"
Before|After
---|---
> Fix capitalization for "Add Face or Touch Unlock"

- app/models/profile.rb
Follow-up to #8816/#8831 which removed the `reproof_at` column. This PR removes the `ignored_columns` call since the column has been dropped.
> Remove reference to dropped profiles.reproof_at database column

- spec/features/idv/end_to_end_idv_spec.rb
- spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb
- spec/support/features/idv_helper.rb
[LG-10495](https://cm-jira.usa.gov/browse/LG-10495)
End to end specs help us validate that profile changes will not break IdV in production. Extend hybrid_mobile IdV spec to include starting and ending at the Service Provider
Move `validate_idv_completed_page(user)` and `validate_return_to_sp` to idv_helper
Automated tests.
> LG-10495 Extend hybrid_mobile_spec to include starting and ending at SP

- app/services/encryption/encryptors/pii_encryptor.rb
- spec/models/profile_spec.rb
- spec/services/encryption/encryptors/pii_encryptor_spec.rb
We are working on migrating to a multi-region capable KMS key. As part of the migration we will be temporarily writing ciphertexts encrypted with the current KMS key and the new multi-region key.
This commit makes a change to the PII encryptor such that it encrypts with the multi-region key when the `aws_kms_multi_region_write_enabled` flag is set. This will cause a multi-region ciphertext to be returned and written to the database.
> LG-10342 Encrypt PII with the multi-region encryptor

- app/controllers/application_controller.rb
- app/controllers/users/piv_cac_login_controller.rb
- spec/controllers/users/piv_cac_login_controller_spec.rb
- spec/features/users/sign_in_spec.rb
Similar to #8836, this change enforces rules of use acceptance more consistently across the application (PIV/CAC login in this case).
> Ensure PIV/CAC authentications check rules of use

- lib/data_pull.rb
- spec/lib/data_pull_spec.rb
https://cm-jira.usa.gov/browse/LG-10484
Update the data-pull script in the IDP so that we can get the external partner UUIDs for a user
> LG-10484: Add uuid-export in data-pull script

- .gitlab-ci.yml
Handles a case where if findings is null the scan step will fail. Related work located [HERE](https://github.com/18F/identity-devops/pull/6481) where the behavior has been tested
> Updating scan step to handle nulls

- app/controllers/concerns/idv_step_concern.rb
- app/forms/gpo_verify_form.rb
- app/models/profile.rb
- app/services/idv/profile_maker.rb
- app/services/idv/session.rb
- spec/controllers/idv/personal_key_controller_spec.rb
- spec/factories/profiles.rb
- spec/models/profile_spec.rb
- spec/services/idv/profile_maker_spec.rb
[LG-10383](https://cm-jira.usa.gov/browse/LG-10383)
We are deprecating the `profile#deactivation_reason(:in_person_verification_pending)` enum for a in_person_verification_pending_at timestamp. This PR will write to both for now until we complete a backfill to add timestamps to all users who are undergoing in person verification.
> LG-0385 Write to in_person_verification_pending_at timestamp.

- app/controllers/idv/in_person/address_search_controller.rb
- app/controllers/idv/in_person/usps_locations_controller.rb
- spec/controllers/idv/in_person/address_search_controller_spec.rb
Handles an unexpected response body from the ArcGIS service.
Also:
- raises a `422` instead of a `400` for most errors in `Idv::InPerson::AddressSearchController`, to stay consistent with `Idv::InPerson::UspsLocationsController` – ac417381e2777e4acf9051bfeb70a8a2fbd67df3
- adds a missing test – 45e1df64897ba6e077515197c130931ca6088f81
- [NewRelic error](https://one.newrelic.com/nr1-core/errors-inbox/entity-inbox/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=43200000&filters=%28domain%20IN%20%28%27APM%27%2C%20%27EXT%27%29%20AND%20type%20IN%20%28%27APPLICATION%27%2C%20%27SERVICE%27%29%29&state=d78d8d16-0d2e-429c-af31-c26792923bba)
- [Slack thread](https://gsa-tts.slack.com/archives/C03FA4VBN76/p1691535543563699)
> Handle unexpected ArcGIS response body

- app/controllers/concerns/idv_session.rb
- app/controllers/idv/capture_doc_status_controller.rb
- app/controllers/idv/getting_started_controller.rb
- app/controllers/idv/hybrid_handoff_controller.rb
- app/controllers/idv/welcome_controller.rb
- spec/controllers/idv/capture_doc_status_controller_spec.rb
- spec/controllers/idv/document_capture_controller_spec.rb
- spec/controllers/idv/getting_started_controller_spec.rb
- spec/controllers/idv/hybrid_handoff_controller_spec.rb
- spec/controllers/idv/welcome_controller_spec.rb
[LG-10438](https://cm-jira.usa.gov/browse/LG-10438)
Remove references to `flow_session[:document_capture_session_uuid]` after the variable was moved to `idv_session` in #8906.
> LG-10438: Remove flow_session[:document_capture_session_uuid]

- app/services/encryption/password_verifier.rb
- spec/models/user_spec.rb
- spec/services/encryption/password_verifier_spec.rb
We are working on migrating to a KMS key that supports encryption and decryption across regions. To enable this move we are changing the application to encrypt PII and passwords with both a multi-region and single-region key during the migraiton.
This commit changes the app to encrypt passwords with the single-region key and the multi-region key when the `aws_kms_multi_region_write_enabled` flag is set.
> LG-10342 Encrypt password digests with multi-region key

- app/controllers/users/backup_code_setup_controller.rb
- app/controllers/users/emails_controller.rb
- app/controllers/users/passwords_controller.rb
- app/presenters/two_factor_authentication/piv_cac_selection_presenter.rb
- app/services/analytics_events.rb
- spec/controllers/users/backup_code_setup_controller_spec.rb
- spec/controllers/users/emails_controller_spec.rb
- spec/controllers/users/passwords_controller_spec.rb
[LG-10488](https://cm-jira.usa.gov/browse/LG-10488)
Added analytics methods for when a user visits Add Email Address, Edit Password, and Regenerate Backup Codes pages
> Kmas lg 10488 add missing analytics

- app/views/shared/_dap_analytics.html.erb
Updates DAP script load to occur asynchronously.
**Why?**
- This is how it's [documented](https://github.com/digital-analytics-program/gov-wide-code/blob/master/documentation/GSA%20DAP%204.1%20-%20Quick%20Guide.pdf) to be implemented
- Allows the script to load asynchronously to avoid page-load blocking ([documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attributes))
1. Add `participate_in_dap: true` to `config/application.yml`
2. Start server
3. Go to http://localhost:3000
4. Verify no errors in load†
† There's currently a CSP error related to [GA4 migration](https://digital.gov/guides/dap/common-questions-about-dap/#:~:text=Q%3A%20When%20will%20the%20Digital%20Analytics%20program%20migrate%20to%20Google%20Analytics%204%3F) that may need to be addressed, but …
> Load DAP analytics script asynchronously

- app/controllers/two_factor_authentication/webauthn_verification_controller.rb
- app/controllers/users/webauthn_setup_controller.rb
- app/forms/webauthn_visit_form.rb
- config/locales/errors/en.yml
- config/locales/errors/es.yml
- config/locales/errors/fr.yml
- config/locales/two_factor_authentication/en.yml
- config/locales/two_factor_authentication/es.yml
- config/locales/two_factor_authentication/fr.yml
- spec/features/webauthn/management_spec.rb
- spec/features/webauthn/sign_in_spec.rb
- spec/features/webauthn/sign_up_spec.rb
- spec/forms/webauthn_visit_form_spec.rb
- spec/support/features/webauthn_helper.rb
[LG-10150](https://cm-jira.usa.gov/browse/LG-10150)
Note: we may want to improve the English text further. Please see the latest comments on the Jira ticket.
Error messages related to using a security key as a MFA option have been changed at two locations: during registration and login.
The two locations where the error messages can be encountered are:
- `/webauthn_setup` (registration)
- `/login/two_factor/webauthn` (login)
To get the error messages to display, cancel the security key process (ceremony) during registration or login at the two locations listed above.
> LG-10150: Improve error message for canceled security key

- app/controllers/users/mfa_selection_controller.rb
- app/controllers/users/two_factor_authentication_setup_controller.rb
- app/forms/two_factor_options_form.rb
- app/views/users/mfa_selection/index.html.erb
- app/views/users/two_factor_authentication_setup/index.html.erb
- spec/controllers/users/mfa_selection_controller_spec.rb
- spec/controllers/users/two_factor_authentication_setup_controller_spec.rb
- spec/features/two_factor_authentication/multiple_mfa_sign_up_spec.rb
- spec/features/users/sign_up_spec.rb
- spec/forms/two_factor_options_form_spec.rb
[LG-10050](https://cm-jira.usa.gov/browse/LG-10050)
Updates validation logic for required MFA selection during account creation to prevent the "You must select an authentication method" from lingering unexpectedly after making a selection.
This includes some general refactoring to validation and error handling logic, to reinforce expectations around the shape and value formats of expected parameters and how (and where) error messages are computed.
The fix itself is using `flash.now` instead of `flash` where a redirect is not involved.
3. Complete account creation up to MFA selection screen
4. Click "Submit" without selecting an MFA method
5. Observe the validation error "Select an authentication method"
6. Select an MFA method …
> LG-10050: Prevent MFA setup validation error from persisting

- app/controllers/users/phone_setup_controller.rb
- app/views/users/emails/verify.html.erb
- app/views/users/phone_setup/spam_protection.html.erb
- spec/views/phone_setup/spam_protection.html.erb_spec.rb
Replaces usage of deprecated URLs with their updated equivalent.
These were planned to be removed in #8982, where removing the routes altogether revealed that they're still referenced in a few places.
Expect that links in affected views continue to take the user where they'd expect to arrive.
> Remove usage of deprecated path helpers in user-facing views

- app/controllers/concerns/saml_idp_auth_concern.rb
- app/controllers/saml_idp_controller.rb
- spec/controllers/saml_idp_controller_spec.rb
- spec/features/saml/saml_spec.rb
We added some additional attributes to OIDC auth requests and ensure they are logged consistently in  https://github.com/18F/identity-idp/pull/8684 and #8798. This PR takes a similar approach to SAML auth requests by moving the logging before a few of the other `before_action` calls. Moving it prior to the `sign_out_if_forceauthn_is_true_and_user_is_signed_in` call allows us to log `user_fully_authenticated` like we do for OIDC to better understand the impact of ForceAuthn usage.
> Log user authentication status when logging SAML Auth Request

- lib/data_pull.rb
- spec/lib/data_pull_spec.rb
based on https://gitlab.login.gov/lg/identity-idp/-/jobs/651103
> Data pull script uuid-export spec fixes

- app/services/doc_auth/lexis_nexis/responses/true_id_response.rb
- spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb
[LG-10337:Update error message when doc classification is not  state ID](https://cm-jira.usa.gov/browse/LG-10337)
Check TrueId response.
> LG-10337: Update error message when doc classification ≠ state ID

- app/controllers/idv/document_capture_controller.rb
- app/controllers/idv/hybrid_handoff_controller.rb
- app/controllers/idv/link_sent_controller.rb
- app/controllers/idv/verify_info_controller.rb
- app/services/idv/session.rb
- spec/controllers/idv/document_capture_controller_spec.rb
[LG-10593](https://cm-jira.usa.gov/browse/LG-10593)
We are removing attributes from flow_session now that we are not using the Flow State Machine. The `redo_document_capture` attribute is used to track when someone clicks to redo document capture in VerifyInfo after a barcode read error.
Both the idv_session and flow_session values are being written and read in this PR to cover the 50/50 state during deployment. A followup PR #8992 will remove all references to `flow_session[:redo_document_capture]` and `flow_session['redo_document_capture']`. (flow_session is a hash with indifferent access)
> LG-10593 Move redo_document_capture from flow_session to idv_session

- app/decorators/service_provider_session_decorator.rb
- config/application.yml.default
- lib/identity_config.rb
- spec/features/remember_device/sp_expiration_spec.rb
In #8926, we switched the default to 0 hours, which is now consistent in all live environments. However, using hours as the unit of time is limiting. NIST 800-63B specifies one of the [AAL2 re-authentication limits](https://pages.nist.gov/800-63-3/sp800-63b.html#423-reauthentication) as 30 minutes, which we would not be able to do at the moment. We do not have any timeline for changing the value from zero, but this PR switches the unit of time to minutes to give us flexibility moving forward.
> Switch AAL2 remembered device expiration configuration units from hours to minutes

- app/controllers/idv/gpo_verify_controller.rb
- app/services/analytics_events.rb
- app/views/idv/gpo_verify/index.html.erb
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- spec/controllers/idv/gpo_verify_controller_spec.rb
- spec/features/idv/in_person_spec.rb
- spec/features/idv/steps/gpo_otp_verification_step_spec.rb
- spec/features/idv/steps/gpo_step_spec.rb
- spec/features/users/verify_profile_spec.rb
- spec/support/features/doc_auth_helper.rb
- spec/support/idv_examples/gpo_otp_verification.rb
- spec/views/idv/gpo_verify/index.html.erb_spec.rb
[LG-10545](https://cm-jira.usa.gov/browse/LG-10545)
Add a screen that provides more assistance to users who haven't received their OTP via USPS after a decent chunk of time.
<details>
<summary>English</summary>
</details>
<details>
<summary>French</summary>
</details>
<details>
<summary>Spanish</summary>
</details>
> LG-10545: "Didn't get your letter?" screen

- app/models/service_provider.rb
Added a small comment to explain why Identity relationship doesn't have a `dependent` option
> Add comment about why we do not destroy Identity table

- app/javascript/packages/webauthn/enroll-webauthn-device.spec.ts
- app/javascript/packages/webauthn/enroll-webauthn-device.ts
- app/javascript/packs/webauthn-setup.ts
- app/views/users/webauthn_setup/new.html.erb
- spec/support/features/webauthn_helper.rb
Removes references to WebAuthn credential `id` as a public key. It is not a public key, but it also appears (thankfully) to be unused. The public key is actually contained within the attestation object, which is what's used in the creation of the credential:
https://github.com/18F/identity-idp/blob/3233189e62a4a6de314b0b0c1c78b60c06e9bc18/app/forms/webauthn_setup_form.rb#L115
https://github.com/18F/identity-idp/blob/3233189e62a4a6de314b0b0c1c78b60c06e9bc18/app/forms/webauthn_setup_form.rb#L114
https://github.com/18F/identity-idp/blob/3233189e62a4a6de314b0b0c1c78b60c06e9bc18/app/forms/webauthn_setup_form.rb#L75-L78
Confirm there are no regressions in the creation of a Security Key or Face or Touch Unlock MFA method.
> Remove unused WebAuthn public key value

- app/services/encryption/password_verifier.rb
We changed the name of this method but missed this tracer. As a result our NewRelic stats got a little wonky. This commit fixes that.
> Update the name of the password digest method tracer

- .rubocop.yml
- app/controllers/account_reset/cancel_controller.rb
- app/controllers/concerns/idv_session.rb
- app/controllers/idv/personal_key_controller.rb
- app/controllers/users/totp_setup_controller.rb
- spec/controllers/idv/personal_key_controller_spec.rb
Enables `Rails/ActionControllerFlashBeforeRender` and resolves existing issues.
**Why?**
- This would catch real-world bugs like the one addressed in #8984
Previously:
- https://github.com/18F/identity-idp/pull/8984#pullrequestreview-1573838223
- #8961
```
rubocop
```
> Enable ActionControllerFlashBeforeRender Rubocop

- bin/oncall/email-deliveries
- bin/oncall/otp-deliveries
- lib/reporting/unknown_progress_bar.rb
- lib/script_base.rb
- spec/bin/oncall/otp-deliveries_spec.rb
- spec/lib/reporting/unknown_progress_bar_spec.rb
**Why**: Script to help triage OTP deliveries by pulling message IDs
changelog: Internal, Scripts, Add script to triage OTP delivery
Usage:
```bash
aws-vault exec prod-power -- ./bin/oncall/otp-deliveries uuid1 --csv
[ Querying logs ] --=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---= Time: 00:00:11
user_id,timestamp,message_id,delivery_preference,country_code
uuid1,2023-01-01T00:00:00Z,messageid1,sms,US
```
> Add script to get OTP delivery logs for SMS, Voice

- app/controllers/concerns/idv/verify_info_concern.rb
- app/controllers/idv/address_controller.rb
- app/services/idv/session.rb
- spec/controllers/idv/address_controller_spec.rb
[LG-10656](https://cm-jira.usa.gov/browse/LG-10656)
Start moving `address_edited` from `flow_session` to `idv_session`. This is the first of two PRs, enabling writing to both locations and reading from either. After this is deployed, a subsequent PR will remove reads and writes to `flow_session['address_edited']`
> LG-10656: Start moving address_edited out of flow_session

- app/controllers/service_provider_controller.rb
- app/services/service_provider_updater.rb
- config/routes.rb
- spec/controllers/service_provider_controller_spec.rb
- spec/services/service_provider_updater_spec.rb
https://cm-jira.usa.gov/browse/LG-10062
When a partner on the dashboard side updates their sandbox configurations, those are synced with the [int environment](https://idp.int.identitysandbox.gov/). The updater historically has pinged the dashboard to get a full list of service provider and then synced through the entire list. This no longer scales for the number of sandbox configurations we have and has led to many timeouts.
This change updates the updater to accept a service_provider param, and uses that param to update a single service_provider. It does not remove/alter the existing code, which may be in use in other parts of the application.
It has this [associated PR](https://github.com/18F/identity-dashboard/pull/663) on the Dashboard application.
Open questions:
* Do we still …
> LG-10062 Allow updater to update a single service provider 

- lib/tasks/backfill_in_person_pending_at.rake
Co-authored by: Alexander Bradley <alexander.bradley@gsa.gov>
Added a rake task to backfill the new `in_person_verification_pending_at` column
[document_classification_error.yml.txt](https://github.com/18F/identity-idp/files/12314963/document_classification_error.yml.txt)
must be used for the user's ID images in order to force in-person proofing.
> LG-10384 - backfill in person verification pending at

- app/jobs/usps_auth_token_refresh_job.rb
- app/services/analytics_events.rb
- spec/jobs/usps_auth_token_refresh_job_spec.rb
- spec/support/usps_ipp_helper.rb
- [LG-8886](https://cm-jira.usa.gov/browse/LG-8886)
- This PR only includes a portion of the changes for this ticket.
- Also see #8993 
- Catch and log `Faraday::TimeoutError` and `Faraday::ConnectionFailed` when renewing USPS API auth token
- This prevents these relatively common errors from bubbling up in a way that may trigger other alarms.
- Check that your local stack has the following flag enabled:
- ```sh
rails c
```
- ```ruby
UspsAuthTokenRefreshJob.perform_now
``` 
- Check that `log/events.log` includes the event `UspsAuthTokenRefreshJob: Network error` with the following fields:
> LG-8886: Catch and log network error when renewing USPS API auth token

- app/controllers/concerns/idv/verify_info_concern.rb
- app/services/idv/session.rb
- app/services/idv/steps/threat_metrix_step_helper.rb
- spec/controllers/idv/in_person/ssn_controller_spec.rb
- spec/controllers/idv/ssn_controller_spec.rb
[LG-10576](https://cm-jira.usa.gov/browse/LG-10576)
We are moving data from flow_session to idv_session. Now that both the unsupervised and in person Ssn steps are out of the Flow State Machine, we can move threatmetrix_session_id to idv_session. This PR adds it to idv_session, and a followup PR for the next deploy will remove it from flow_session.
> LG-10576 Add threatmetrix_session_id to idv_session

- app/components/page_footer_component.rb
- app/controllers/users/two_factor_authentication_setup_controller.rb
- app/forms/webauthn_visit_form.rb
- app/presenters/two_factor_options_presenter.rb
- app/services/analytics_events.rb
- app/views/mfa_confirmation/show.html.erb
- app/views/shared/_cancel_or_back_to_options.html.erb
- app/views/sign_up/completions/show.html.erb
- app/views/users/backup_code_setup/confirm_backup_codes.html.erb
- app/views/users/two_factor_authentication_setup/index.html.erb
- spec/components/page_footer_component_spec.rb
- spec/controllers/users/two_factor_authentication_setup_controller_spec.rb
- spec/features/multi_factor_authentication/mfa_cta_spec.rb
- spec/features/remember_device/webauthn_spec.rb
- spec/features/two_factor_authentication/multiple_mfa_sign_up_spec.rb
- spec/forms/webauthn_visit_form_spec.rb
- spec/presenters/two_factor_options_presenter_spec.rb
- spec/views/shared/_cancel_or_back_to_options.html.erb_spec.rb
- spec/views/users/two_factor_authentication_setup/index.html.erb_spec.rb
[LG-10660](https://cm-jira.usa.gov/browse/LG-10660)
Updates links and updates capability of `TwoFactorAuthenticationSetupController` to handle both initial and additional MFA setups, with planned follow-on pull request to remove `MfaSelectionController`.
2. Create an account, up to "Authentication method setup"
3. Observe no visual differences from `main`
4. Set up an MFA method
5. When prompted, choose to "Add another method"
6. On the additional MFA setup screen, observe no visual differences from `main`
Also try a few variations:
- Choosing "Face or touch unlock" as your first MFA should hide the option to skip when setting up second method (#8739)
- MFAs added and single-only restrictions should apply (#8863)
There should be no visual differences, aside …
> LG-10660: Consolidate MFA setup controllers

- app/services/service_provider_updater.rb
- spec/services/service_provider_updater_spec.rb
https://cm-jira.usa.gov/browse/LG-10062
While implementing [single service provider dashboard syncing](https://cm-jira.usa.gov/browse/LG-10062), we discovered conditionals referencing the deprecated `native` attribute. As it is no longer being passed to the IDP via the dashboard, it should be safe to remove these references.
> Remove 'native' attribute references from service_provider_updater

- config/initializers/job_configurations.rb
The GPO reminder job currently has a query that sends an email to users who are GPO pending. Unfortunately it is configured to send an email to every user who has ever been GPO pending. As a result every pending user from all of history will receive an email once it is merged.
This commit temporarily disables the job while we figure that problem out.
> Disable the GPO reminder job

- .github/dependabot.yml
[LG-10628](https://cm-jira.usa.gov/browse/LG-10628)
Adds auto-updater configurations to the existing Dependabot configuration to automatically create pull requests for updates to dependencies which are used for phone metadata and validation:
- `libphonenumber-js` (npm)
- `phonelib` (ruby)
**Why?**
- Outdated phone metadata can prevent users from using certain phone numbers, as was the case with #8932
**Reference:**
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
This is difficult to test, since it would only be expected to take effect once the configuration changes are merged and a dependency update is available.
> LG-10628: Enable Dependabot updates for phone dependencies

- app/views/idv/welcome/_welcome_new.html.erb
- spec/views/idv/welcome/show.html.erb_spec.rb
[LG-10762](https://cm-jira.usa.gov/browse/LG-10762)
Mark links in _welcome_new template with 'welcome_new' to distinguish them in analytics events from the same links on the Getting Started page in an A/B test.
> Mark new welcome template links with step: 'welcome_new'

- app/controllers/concerns/forced_reauthentication_concern.rb
- app/controllers/concerns/saml_idp_auth_concern.rb
- app/controllers/openid_connect/authorization_controller.rb
- app/controllers/users/sessions_controller.rb
- app/views/devise/sessions/new.html.erb
- config/locales/account/en.yml
- config/locales/account/es.yml
- config/locales/account/fr.yml
- spec/controllers/concerns/forced_reauthentication_concern_spec.rb
- spec/features/openid_connect/openid_connect_spec.rb
- spec/features/saml/saml_spec.rb
- spec/support/saml_auth_helper.rb
[LG-10661](https://cm-jira.usa.gov/browse/LG-10661)
Currently, if you are fully authenticated and initiate an authorization request with a service provider that requests forced re-authentication (via login=prompt in OIDC or ForceAuhthn in SAML), the session is terminated without any notification. We are working on other changes to improve this experience, but this is a shorter-term change to try to communicate this behavior better to the end user. The message should not be displayed if the session is not terminated.
Awaiting translations at the moment.
<details>
</details>
<details>
</details>
> Inform user that a service provider request is requiring re-authentication if they are logged out due to it (LG-10661)

- lib/cleanup/destroyable_records.rb
[LG-10679](https://cm-jira.usa.gov/browse/LG-10679)
Adds a message telling the user to manually remove the record when there is an associated In Person Enrollment.
> Add a message when destroying Service Providers with associated In Person Enrollments

- lib/tasks/multi_region_kms.rake
We are in the midst of a migration between KMS keys. We are changing from a single-region only key to a key that supports multi-region use.
As part of this migration we are encrypting data twice: once with each of the keys. Under no circumstance should the data that is encrypted by KMS and stored be different for a given record.
This commit introduces a rake task that confirms that the same data is being encrypted and written. It does so by grabbing a sample of records, removing the KMS encryption, and comparing the contents.
> LG-10344 Add a rake task for detecting mismatch multi-region and single-region KMS records

- app/controllers/concerns/idv/verify_info_concern.rb
- app/services/idv/steps/threat_metrix_step_helper.rb
- spec/controllers/idv/in_person/ssn_controller_spec.rb
- spec/controllers/idv/ssn_controller_spec.rb
[LG-10576](https://cm-jira.usa.gov/browse/LG-10576)
As a followup to #9046, delete `flow_session[:threatmetrix_session_id]` now that it has been moved to `idv_session.threatmetrix_session_id`.
Also, test in the same way in unsupervised and in person ssn controller specs.
Note: merge after #9046 has been deployed.
> LG-10576 delete threatmetrix session id from flow session

- app/services/analytics_events.rb
- lib/reporting/identity_verification_report.rb
- spec/lib/reporting/identity_verification_report_spec.rb
This commit makes a few small changes to the identity verification report:
1. Allow the report to be run without an issuer
2. Change the GPO verification counter to filter users who still new fraud review or in-person proofing
3. Change the final resolution event to filter users who still new fraud review, in-person, or GPO. Previously this used "deactivation_reason" which is not deprecated
> Tweak the IdentityVerificationReport

- app/controllers/concerns/idv/verify_info_concern.rb
[LG-10658](https://cm-jira.usa.gov/browse/LG-10658) (cleanup only)
- AC are implemented in https://github.com/18F/identity-idp/pull/9064
- This cleans up a redundant merge of A/B testing analytics fields into the proofing results log entry.
- The only impacts here are compute time and code complexity, not functionality.
Automated analytics tests.
> LG-10658: Cleanup merge of A/B testing fields into proofing results analytics

- app/controllers/idv/in_person/verify_info_controller.rb
- app/controllers/idv/in_person_controller.rb
- app/services/idv/steps/in_person/address_step.rb
- app/services/idv/steps/in_person/state_id_step.rb
- app/views/idv/in_person/verify_info/show.html.erb
- config/routes.rb
- spec/controllers/idv/in_person_controller_spec.rb
- spec/features/idv/in_person_spec.rb
- spec/features/idv/steps/in_person/state_id_step_spec.rb
[LG-10586](https://cm-jira.usa.gov/browse/LG-10586)
- Direct users to new SSN entry URL for in-person proofing
- Add deprecation warning to the previous routes
- This was intentionally left in for this pull request in order to prevent issues for users who are active during the release process. The routes can be removed after this change is deployed.
- Recommended redirects were modified to ensure that requests are processed seamlessly
> LG-10586: Direct users to new SSN entry URL for in-person proofing

- app/models/concerns/user_access_key_overrides.rb
This method was added to log exceptions that were raised when trying to validate passwords. This was because an invalid password attempt would raise an encryption error; there was concern that this would cause other exceptions to be missed. This was only relevant when we were encrypting passwords with UAKs.
Now that we are not longer using UAKs this method just writes invalid password attempts to production.log. This duplicates what is written to events.log for events where passwords are entered.
I could not find anywhere that we are looking at this log line. This commit removes it.
> Retire `log_password_verification_failure`

- app/services/proofing/aamva/proofer.rb
- spec/services/proofing/aamva/proofer_spec.rb
Currently we do not report MVA timeouts or DLDV connection issues to NewRelic. We do this because this service often has issues and creates a lot of noise.
The issues we observe are generally the result of individual MVA timeouts and not issues connecting to the DLDV service. Moreover, during DLDV outages not having DLDV issues reported limits our visibility.
This commit removes the constraint that prevents DLDV connection issues from being reported so we have visibility. Since the DLDV service itself is generally reliable this should not result in too much noise.
> LG-10823 Report Faraday timeout errors to NewRelic

- lib/reporting/identity_verification_report.rb
- spec/lib/reporting/identity_verification_report_spec.rb
This commit updates the identity verification report to include 3 groups of metrics:
1. Metrics on starting the flow
2. Metrics on completion of the in-line flow
3. Metrics on verified users
These metrics are broken down further to cover specific scenarios we are concerned about.
> LG-10780 Update the metrics in the identity verification report

- app/jobs/reports/identity_verification_report.rb
- spec/jobs/reports/identity_verification_report_spec.rb
This commit takes the existing cloudwatch based identity verification report and adds a job that runs the report for a single day and uploads result to S3.
This commit does not include a configuration in `job_configurations.rb` so that we can verify this works before we enable it.
> LG-10836 Add a report job for the identity verification report

- app/controllers/service_provider_controller.rb
- config/initializers/mime_types.rb
- spec/controllers/service_provider_controller_spec.rb
https://cm-jira.usa.gov/browse/LG-10062
This ticket surfaced an issue where, when JSON requests to sync the service providers are over 20k, they are automatically rejected by nginx. We raised the nginx threshold, but also would like to compress requests to make sure the requests stay below the threshold.
It should be merged before https://github.com/18F/identity-dashboard/pull/667
> LG-10062 register gzip Mime::Type

- config/locales/idv/fr.yml
[LG-10795](https://cm-jira.usa.gov/browse/LG-10795)
The ticket was originally update "Address" to "Address line 1" for the "Update your address" screen. Since that was already present the only thing that needed to be changed was the capitalization of "Linge" form the French translation.
> LG-10795 Update "address" to address line 1

- app/javascript/packages/document-capture/components/acuant-capture.tsx
- spec/javascript/packages/document-capture/components/acuant-capture-spec.jsx
https://cm-jira.usa.gov/browse/LG-10851
This PR adds the `acuantCaptureMode` property to the `'IdV: Image capture failed'` event so we can more easily answer the question: "Are all cropping errors coming from users of the Acuant SDK's 'Tap to capture' mode?
> LG-10851: Log 'TAP' or 'AUTO' when an image upload fails

- lib/reporting/cloudwatch_client.rb
- spec/lib/reporting/cloudwatch_client_spec.rb
Helps avoid permissions issues [like this (slack convo)](https://gsa-tts.slack.com/archives/C16RSBG49/p1693231097015499) in the future, and preserves useful behavior in local development for test queries
> Add more useful default log group for deployed environments

- app/forms/idv/api_image_upload_form.rb
- rubocop.xml
- spec/features/idv/doc_auth/test_credentials_spec.rb
- spec/fixtures/ial2_test_credential_no_address.yml
- spec/support/features/doc_auth_helper.rb
[LG-10828](https://cm-jira.usa.gov/browse/LG-10828)
Reset doc_auth rate limiter after successful 3rd party doc auth verification and successful PIIDocForm validation.  
###Why
Current implementation resets only after successfull 3rd party verification but should also include successful PIIDocForm validation.
> LG-10828 rate limit doc auth when credentials validation fails

- config/application.yml.default
- spec/features/phone/add_phone_spec.rb
- spec/forms/new_phone_form_spec.rb
Adds default reCAPTCHA score threshold configuration overrides for Canada and Mexico, so that they behave consistently across deployed environments.
Enable reCAPTCHA locally with configuration in `config/application.yml`:
```
phone_recaptcha_score_threshold: 0.5
```
3. At MFA setup selection, choose phone
4. Enter a Canadian or Mexican phone number, e.g. `3065550100`
5. In the "reCAPTCHA score" field (internal only), enter a number lower than the threshold defined in configuration, e.g. 0.4 if using the above-defined threshold
6. Submit the page
7. Observe that you pass successfully to the "Enter your one-time code" screen
> Add reCAPTCHA configuration overrides for Canada, Mexico

- app/forms/idv/api_image_upload_form.rb
- app/services/analytics_events.rb
- spec/controllers/idv/image_uploads_controller_spec.rb
- spec/features/idv/analytics_spec.rb
- spec/forms/idv/api_image_upload_form_spec.rb
[LG-10753](https://cm-jira.usa.gov/browse/LG-10753)
To continue investigating GettingStarted A/B test differences in Doc Auth success rates, add the A/B test bucket to analytics events in ApiImageUploadForm
- IdV: doc auth image upload form submitted
- IdV: doc auth image upload vendor submitted
- IdV: doc auth image upload vendor pii validation
- Doc Auth Warning
Note: Looked at adding the bucket to the Frontend events, but got bogged down with getting access to the uuid that's used as the GettingStarted bucket discriminator, and backed out.
> LG-10753 Add GettingStarted A/B test buckets to some image upload analytics events

- lib/reporting/cloudwatch_client.rb
Somehow I broke scripts that use the cloudwatch client by adding this require in #9098
**before:**
```bash
identity-idp:main> aws-vault exec prod-power -- ./bin/oncall/email-deliveries c7abcdef
<internal:/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require': cannot load such file -- identity/hostdata (LoadError)
```
**after:**
```bash
> aws-vault exec prod-power -- ./bin/oncall/email-deliveries abcdef
[ Querying logs ] --=---=---=---=---=---=---=---=-----=---=---
```
> Fix require for oncall scripts

- app/controllers/users/phone_setup_controller.rb
- app/controllers/users/phones_controller.rb
- app/views/users/phone_setup/spam_protection.html.erb
- spec/features/phone/add_phone_spec.rb
- spec/features/users/sign_up_spec.rb
- spec/views/phone_setup/spam_protection.html.erb_spec.rb
Fixes an issue where the reCAPTCHA fallback screen shows incorrect links when adding a phone number to an existing account.
This was an unintended side-effect of the phone consolidation in #8966, since the links were controlled by distinct logic in the two controllers, where one would provide `locals` value to the view to render a link to "Choose another authentication method":
https://github.com/18F/identity-idp/blob/c068dfbdbaaa407f0142eaa495b48663c8a357e4/app/controllers/users/phones_controller.rb#L27
https://github.com/18F/identity-idp/blob/c068dfbdbaaa407f0142eaa495b48663c8a357e4/app/controllers/users/phone_setup_controller.rb#L38
There was not sufficient regression coverage for this behavior, hence why it was not caught previously. …
> Fix reCAPTCHA add phone fallback links

- lib/tasks/backfill_in_person_pending_at.rake
Some profiles for in-person enrollment don't have an an in_person_enrollment associated with them, so use the profile's timestamp instead.
changelog: Internal,In-person proofing,backfill `in_person_pending_at` column
> Use 'profile.updated_at` not `in_person_enrollment.updated_at`

- app/views/idv/verify_info/show.html.erb
[LG-9559](https://cm-jira.usa.gov/browse/LG-9559)
Added document ID number to the 'verify your info' screen.
The updated app may be reached at [test-app](https://review-jmax-lg-95-qmbmwj.review-app.identitysandbox.gov/)
<details>
</details>
<details>
</details>
> LG-9559 Add document ID number to verify info screen

- .gitlab-ci.yml
https://cm-jira.usa.gov/browse/LG-10505
Bug fix - Hardcoding the "main" container tag onto the container built from the main branch. CI_DEFAULT_BRANCH appears to be a protected variable in Prod GitLab and results in an empty tag (all logic using this variable still functions as expected) for the container built from the main branch (this behavior was not see when tested in GitLab Alpha).
> Hardcoding name of container main tag

- app/controllers/idv/hybrid_handoff_controller.rb
- app/controllers/idv/link_sent_controller.rb
- app/views/idv/agreement/show.html.erb
- app/views/idv/doc_auth/_error_messages.html.erb
- app/views/idv/getting_started/show.html.erb
- app/views/idv/hybrid_handoff/show.html.erb
- app/views/idv/link_sent/show.html.erb
- spec/controllers/idv/link_sent_controller_spec.rb
- spec/features/idv/doc_auth/agreement_spec.rb
- spec/features/idv/doc_auth/getting_started_spec.rb
- spec/views/idv/agreement/show.html.erb_spec.rb
- spec/views/idv/getting_started/show.html.erb_spec.rb
[LG-10556](https://cm-jira.usa.gov/browse/LG-9727) 
This PR is the follow-up PR to remove code that displays `flow_session` error messages to the user.
> Lg 10556 move error message out of flow session 2 of 2

- app/services/encryption/multi_region_kms_migration/profile_migrator.rb
- spec/services/encryption/multi_region_kms_migration/profile_migrator_spec.rb
We are working on migrating between KMS keys. The new key will support multi-region encryption. As part of this migration we encrypting records with both keys.
Previous commits added code for encrypting with both keys and writing ciphertexts for both on `INSERT` and `UPDATE`. This commit adds tooling for going back and updating records that are not being changed by normal user behavior.
> LG-10343 Add a class for migrating encrypted PII to the multi-region KMS key

- app/services/usps_in_person_proofing/enrollment_helper.rb
- config/application.yml.default
- lib/identity_config.rb
- spec/services/usps_in_person_proofing/enrollment_helper_spec.rb
[LG-10074](https://cm-jira.usa.gov/browse/LG-10074)
* Adds a new configuration value for the email address that we send to USPS when we create USPS enrollments
* Begins using the new configuration value, including falling back to 'no-reply@login.gov' if the configuration value is set to empty string
> LG-10074: Make usps enrollment email address configurable

- app/controllers/service_provider_controller.rb
- spec/controllers/service_provider_controller_spec.rb
During last week's [contingency planning scenario](https://gsa-tts.slack.com/archives/C03AM5TKWHG/p1692907920840209), we noticed some unrelated 500s when comparing a nil value.
This PR skips the comparison if the value is blank. This should be fine since an attempted timing attack with a zero-length attempt should not be terribly informative.
> Fix 500 with blank token when attempting to update service providers

- app/services/gpo_confirmation_exporter.rb
- app/services/gpo_reminder_sender.rb
- config/application.yml.default
- spec/features/users/verify_profile_spec.rb
- spec/forms/gpo_verify_form_spec.rb
- spec/jobs/gpo_reminder_job_spec.rb
- spec/services/gpo_reminder_sender_spec.rb
- spec/support/idv_examples/gpo_otp_verification.rb
[LG-9565](https://cm-jira.usa.gov/browse/LG-9565)
The original query to retrieve users who need a reminder letter did not respect the 30-day cutoff (we shouldn't remind users if their request for a letter is older than 30 days).
> Jmax/LG-9565 fix GPO reminder query

- app/controllers/concerns/idv_step_concern.rb
- app/controllers/idv/address_controller.rb
- app/controllers/idv/document_capture_controller.rb
- app/controllers/idv/link_sent_controller.rb
- app/controllers/idv/session_errors_controller.rb
- app/controllers/idv/ssn_controller.rb
- app/controllers/idv/verify_info_controller.rb
- app/forms/idv/ssn_format_form.rb
- spec/controllers/idv/address_controller_spec.rb
- spec/controllers/idv/document_capture_controller_spec.rb
- spec/controllers/idv/link_sent_controller_spec.rb
- spec/controllers/idv/session_errors_controller_spec.rb
- spec/controllers/idv/ssn_controller_spec.rb
- spec/controllers/idv/verify_info_controller_spec.rb
- spec/forms/idv/ssn_format_form_spec.rb
[LG-10657](https://cm-jira.usa.gov/browse/LG-10657)
Start the process of moving :pii_from_doc into idv_session. Incidentally clean up some controller spec flow_session values that are no longer used. 
Plan:
1) Align on :pii_from_doc as flow_session key, replacing 'pii_from_doc' where needed (this PR)
2) Make as many reads as possible go through pii_from_doc method in IdvStepConcern (this PR)
3) Move ssn out of pii_from_doc into idv_session, possibly into applicant, or its own key (two separate PRs, [LG-10886](https://cm-jira.usa.gov/browse/LG-10886))
4) Copy pii_from_doc into idv_session (are there session size issues with this?) (future PR)
5) Remove flow_session[:pii_from_doc] (future PR)
> LG-10657 move pii from doc out of flow session STEP 1

- app/javascript/packages/webauthn/is-webauthn-passkey-supported.spec.ts
Removes test setup code that's inconsequential to the application code
I was searching for uses of `isUserVerifyingPlatformAuthenticatorAvailable` and came across this in the tests, despite it not being used in the implementation as of #8723.
`yarn test`
> Remove unused JavaScript test stub

- app/jobs/get_usps_proofing_results_job.rb
- app/services/usps_in_person_proofing/mock/fixtures.rb
- app/services/usps_in_person_proofing/mock/responses/request_passed_proofing_supported_secondary_id_type_results_response.json
- spec/jobs/get_usps_proofing_results_job_spec.rb
- spec/support/usps_ipp_helper.rb
[LG-10832](https://cm-jira.usa.gov/browse/LG-10832)
Passes enrollments with a secondary ID, only if it has a type of "Visual Inspection of Name and Address on Primary ID Match"
Once this PR is merged and in dev
> LG-10832: Pass enrollments with supported secondary ID type

- .gitlab-ci.yml
Copies the logic implemented in https://github.com/18F/identity-devops/pull/6596 to help make the ECR checks more robust to odd responses from AWS
> Improve robustness of Elastic Container Registry container scan status check

- lib/deploy/activate.rb
- spec/lib/deploy/activate_spec.rb
In #8786, we added a section of code to delete invalid symlinks, but it used the wrong method to call for the deletion. This PR adds a spec to cover the behavior and fixes the bug by calling `FileUtils.rm` instead of `File.rm` (which does not exist) 
This PR slightly refactors some of the methods and makes some of them public so it is easier to interact with in the tests.
> Use correct method to delete symlink in activate script

- app/controllers/frontend_log_controller.rb
- app/services/frontend_error_logger.rb
- app/services/frontend_logger.rb
- spec/controllers/frontend_log_controller_spec.rb
- spec/services/frontend_logger_spec.rb
I nerd-sniped myself based on [this comment](https://github.com/18F/identity-idp/pull/8950#discussion_r1309295594) and gave it a shot
> Add custom proc support to FrontendLogger, simplify FrontendLogController

- app/forms/security_event_form.rb
- config/application.yml.default
- lib/identity_config.rb
- spec/forms/security_event_form_spec.rb
Allows us to enable and disable the password reset functionality when we receive authorization fraud security events. Based on discussion [here](https://gsa-tts.slack.com/archives/C03A12WPCLW/p1693516061825139).
> Add feature flag for resetting account passwords when receiving authorization fraud event

- lib/reporting/identity_verification_report.rb
**Problem:**
`Idv: Final Resolution` events from a year ago will not have the same properties are current ones, they'll have `deactivation_reason`
**Solution:**
Add `coalesce()` to default these values to false and check that there isn't the older `deactivation_reason` property
> Update identity verification report to work for older logs (LG-10875)

- app/jobs/reports/monthly_account_reuse_report.rb
- spec/jobs/reports/monthly_account_reuse_report_spec.rb
changelog: Internal, formatting, un-embed the CSV from within JSON
https://cm-jira.usa.gov/browse/LG-10912
> LG-10912 Reformat Account Reuse Report

- app/forms/two_factor_options_form.rb
- spec/forms/two_factor_options_form_spec.rb
[LG-10487](https://cm-jira.usa.gov/browse/LG-10487)
- Added another method specific to phishing resistant required accounts and included it into the selection validation method
- Add spec to cover changes
Locally test with Sinatra running.
You should expect to see the Continue to Example Sinatra App screen and the Agree and continue button.
You should not expect to see the Add MFA form again with the error "Select an additional authentication method."
> LG-10487 Inconsistent enforcement of phishing-required second MFA setup

- app/controllers/accounts_controller.rb
- app/controllers/application_controller.rb
- spec/controllers/accounts_controller_spec.rb
- spec/controllers/application_controller_spec.rb
- spec/features/users/sign_in_spec.rb
I had a chat with @aduth about the suspension we implemented in #8755, and we think that the code would catch users signing directly in, not through an SP
- Moves logic around in `application_controller.rb`, net result should be about the same
- Adds an acceptance spec for suspended users (there were none as far as I could tell)
- check specifically for behavior for signing in from an SP
> Move user suspended check for sign-in

- app/jobs/reports/identity_verification_report.rb
- lib/reporting/authentication_report.rb
- lib/reporting/command_line_options.rb
- lib/reporting/identity_verification_report.rb
- lib/reporting/monthly_proofing_report.rb
- spec/lib/reporting/authentication_report_spec.rb
- spec/lib/reporting/command_line_options_spec.rb
- spec/lib/reporting/identity_verification_report_spec.rb
- Expanding use so we can support a specific one-off request, but seemed easier to expand all reports at once
(tagging Ursula and Ada since sometimes these reports are relevant to those teams, especially the background job version)
> Update IDV report to support multiple issuers (LG-10875)

- app/controllers/users/piv_cac_login_controller.rb
- spec/controllers/users/piv_cac_login_controller_spec.rb
Related to [LG-10022](https://cm-jira.usa.gov/browse/LG-10022) (#9124)
Updates PIV/CAC login logic to avoid a duplicate call to `mark_user_session_authenticated`. [Among other things](https://github.com/18F/identity-idp/blob/ce54c15e713731051d86b98895018db9a7cd2247/app/controllers/concerns/two_factor_authenticatable_methods.rb#L165-L169), this method logs an analytics event for "User marked authenticated", and was used in #9124 as the point at which to increment the user's sign-in count. The duplicate logging was causing double-counting in the logic of #9124.
The call to `mark_user_session_authenticated` removed here is unnecessary because it is already called indirectly a few lines below through `handle_valid_verification_for_authentication_context`: …
> Avoid duplicate analytics event for PIV/CAC login

- docs/mobile.md
This PR updates our mobile docs to include info about using chrome on iOS to debug which is newly possible.
As of July 2023 Chrome on iOS supports the same Web Inspector functionality that Safari does. Here's the official chrome dev blog about it: [link](https://developer.chrome.com/blog/debugging-chrome-on-ios/).
Follow the directions for using iOS and Chrome and make sure they work for you.
> Update Mobile Docs with iOS Chrome Info

- app/controllers/openid_connect/authorization_controller.rb
- spec/controllers/openid_connect/authorization_controller_spec.rb
[LG-10936](https://cm-jira.usa.gov/browse/LG-10936)
This was a bug introduced from the changes in #8684. If an OIDC authorization request is received that uses `prompt=login`, and the user switches languages, they will be logged out and have to authenticate again, which is not intended. The core of the issue is due to the OIDC state session check not being set each time. This was working most of the time because the comparison of the URL [here](https://github.com/18F/identity-idp/blob/507fa1d/app/controllers/openid_connect/authorization_controller.rb#L138) only triggers a log out when the URL has changed from the original request. Because the locale is part of the URL, it falls through that check and logs the user out again.
To address this, this PR ensures the …
> Do not end session when switching languages during forced re-authentication OIDC request (LG-10936)

- app/javascript/packages/document-capture/components/acuant-camera.tsx
- spec/javascript/packages/document-capture/components/acuant-capture-spec.jsx
- spec/javascript/packages/document-capture/components/document-capture-spec.jsx
https://cm-jira.usa.gov/browse/LG-10900
This work changes the name of an error handling function to what the AcuantSDK expects.
Extracted from the slack thread about this bug [here](https://gsa-tts.slack.com/archives/C056RD1NEHW/p1693504572901689?thread_ts=1693489473.008259&cid=C056RD1NEHW).
```yml
idv_acuant_sdk_version_default: '11.9.1'
idv_acuant_sdk_version_alternate: '11.9.1'
```
<details>
<summary>Camera permissions popup</summary>
</details>
<details>
<summary>Before: White screen with X in the corner</summary>
</details>
<details>
<summary>After: Error message</summary>
</details>
> Fix Acuant Error Handler Function Naming

- .gitlab-ci.yml
- app/controllers/idv/personal_key_controller.rb
- app/controllers/idv/review_controller.rb
- app/controllers/openid_connect/authorization_controller.rb
- app/forms/two_factor_options_form.rb
- app/javascript/packages/phone-input/package.json
- app/jobs/reports/monthly_account_reuse_report.rb
- app/models/profile.rb
- app/models/user.rb
- app/services/analytics_events.rb
- bin/oncall/download-piv-certs
- bin/oncall/email-deliveries
- bin/oncall/otp-deliveries
- bin/query-cloudwatch
- lib/reporting/cloudwatch_client.rb
- spec/controllers/idv/personal_key_controller_spec.rb
- spec/controllers/idv/review_controller_spec.rb
- spec/controllers/openid_connect/authorization_controller_spec.rb
- spec/factories/profiles.rb
- spec/features/idv/analytics_spec.rb
- spec/forms/gpo_verify_form_spec.rb
- spec/forms/two_factor_options_form_spec.rb
- spec/jobs/reports/monthly_account_reuse_report_spec.rb
- spec/models/profile_spec.rb
- spec/services/idv/profile_maker_spec.rb
- spec/services/idv/session_spec.rb
- yarn.lock
- MFA Setup: Bug-fix for inconsistent enforcement of phishing-resistant account. ([#9119](https://github.com/18F/identity-idp/pull/9119))
- OpenID Connect: Do not end session when switching languages during forced re-authentication request ([#9157](https://github.com/18F/identity-idp/pull/9157))
- Dependencies: Update dependencies to resolve security advisories ([#9138](https://github.com/18F/identity-idp/pull/9138))
- IdV IPP: Write to in_person_verification_pending_at ([#8971](https://github.com/18F/identity-idp/pull/8971))
- formatting: Un-embed the CSV from within JSON ([#9137](https://github.com/18F/identity-idp/pull/9137))
> Deploy RC 312 to Prod

- config/initializers/job_configurations.rb
We have added code to start writing to profiles with a multi-region KMS key. This is in addition to the single-region key was were using previously. Records that were created before we introduced the multi-region key do not have a value encrypted with the multi-region KMS key.
https://github.com/18F/identity-idp/commit/5506d9e4dfe67283d8bd36f25df333ddd3aa9f31 added a background job for backfilling the empty multi-region ciphertexts. This commit enables it after testing and timing it in lower environments and in production.
> LG-10343 Enable the profile backfill job

- app/jobs/multi_region_kms_migration/user_migration_job.rb
- app/services/analytics_events.rb
- app/services/encryption/multi_region_kms_migration/user_migrator.rb
- spec/jobs/multi_region_kms_migration/user_migration_job_spec.rb
- spec/services/encryption/multi_region_kms_migration/user_migrator_spec.rb
We are in the midst of a migration from a single-region KMS key to a multi-region capable KMS key. That migration involves the following steps:
1. Add new columns for multi-region ciphertexts
2. Start writing to the new columns with multi-region ciphertexts
3. Start opportunistically reading from the multi-region columns
4. Backfill the multi-region columns for old users
5. Stop using the old single-region columns
This commit is part of step number 4.
This commit adds a `UserMigrator` class which takes a user and migrates the single-region encrypted `encrypted_password_digest` and `encrypted_recovery_code_digest` to `encrypted_password_digest_multi_region` and `encrypted_recovery_code_digest_multi_region` respectively. This commit also includes a job to find users that require migration …
> LG-10891 Add a job for migrating user password digests to multi-region KMS

- app/jobs/in_person/send_proofing_notification_job.rb
- config/locales/telephony/en.yml
- config/locales/telephony/es.yml
- config/locales/telephony/fr.yml
- spec/jobs/in_person/send_proofing_notification_job_spec.rb
- spec/lib/identity_config_spec.rb
[LG-10614](https://cm-jira.usa.gov/browse/LG-10614)
Change sms message to match new copy that includes contact number. 
Note for designer reviewing: There are no screenshots available, in lieu of those the string files can be used to confirm the text is correct.  
To be tested after merging into dev.
> LG-10614 Update sms copy

- app/controllers/accounts_controller.rb
- app/controllers/application_controller.rb
- spec/controllers/accounts_controller_spec.rb
- spec/controllers/application_controller_spec.rb
- spec/features/users/password_recovery_via_recovery_code_spec.rb
- spec/support/shared_examples/sign_in.rb
Updates handling of signed-in URL handling:
- Removes proxy methods in favor of inline condition early returns
- The hope here is (a) make the logic clearer by avoiding the indirection and (b) avoid naming gymnastics (and resulting confusion) in generating a URL under only certain conditions (e.g. `accept_rules_of_use_url` returns `rules_of_use_path` only if the user must accept rules of user, otherwise returns `nil`).
- Similar to #9147, moves more interception screens into the expected SP-initiated sign-in flow
- Backup code reminder
- Account reactivation
- Removes a seemingly-redundant check for `user_fully_authenticated?` in `signed_in_url`
Ideally we would be able to eliminate one or the other of `after_sign_in_path_for` and `signed_in_url`, but we currently rely on `signed_in_url` …
> Consolidate / standardize URL handling for after_sign_in_path_for

- app/forms/user_piv_cac_verification_form.rb
Currently, when displaying the PivCacVerificationForm prior to receiving a form submission, there is a database query that will always be blank. We can safely skip this query.
The query looks like:
```
PivCacConfiguration Load (0.3ms)  SELECT "piv_cac_configurations"."id", "piv_cac_configurations"."user_id", "piv_cac_configurations"."x509_dn_uuid", "piv_cac_configurations"."name", "piv_cac_configurations"."created_at", "piv_cac_configurations"."updated_at", "piv_cac_configurations"."x509_issuer" FROM "piv_cac_configurations" WHERE "piv_cac_configurations"."x509_dn_uuid" IS NULL LIMIT $1  [["LIMIT", 1]]
↳ app/forms/user_piv_cac_verification_form.rb:24:in `piv_cac_configuration'
```
> Do not query for PivCacConfiguration when x509_dn_uuid is blank

- app/controllers/concerns/idv/threat_metrix_concern.rb
- app/controllers/idv/in_person/ssn_controller.rb
- app/controllers/idv/in_person_controller.rb
- app/controllers/idv/ssn_controller.rb
- spec/controllers/concerns/idv/threat_metrix_concern_spec.rb
- spec/controllers/idv/in_person_controller_spec.rb
- spec/controllers/idv/ssn_controller_spec.rb
Remove the Flow State Machine version of the ThreatMetrix CSP before_action because both the remote and in_person SSN steps are now out of the FSM.
> Cleanup ThreatMetrix CSP before_action name now that in_person SSN step is out of the FSM

- config/locales/forms/es.yml
- config/locales/forms/fr.yml
Noticed during [LG-10871](https://cm-jira.usa.gov/browse/LG-10871) (#9155)
Updates the Face or Touch Unlock setup screen texts to ensure consistent sentence grammar across all languages.
**Before:**
- English: Two sentences with a space between
- French: Two sentences, no space between
- Spanish: One run-on sentence
**After:** All are two sentences with a space between
2. Sign in or create an account
3. When given the opportunity to add a new MFA method, add a new Face or Touch Unlock authenticator
4. Observe the link in the second paragraph
5. Change the language
6. Notice the grammar is consistent across languages
Language|Before|After
---|---|---
English|![Screenshot 2023-09-07 at 8 42 47 AM](https://github.com/18F/identity-idp/assets/1779930/82a75e2b-d1d0 …
> Fix Face/Touch "Learn more" grammar for French/Spanish

- app/jobs/reports/identity_verification_report.rb
- spec/jobs/reports/identity_verification_report_spec.rb
IdentityVerification job exits immediately when S3 reports are disabled.
> Identity Verification report  job to immediately exit when s3 reports are disabled

- app/services/idv/session.rb
[LG-10273](https://cm-jira.usa.gov/browse/LG-10273)
While @theabrad and I were making a map of how idv_session is used, we noticed that `profile_step_params` and `profile_confirmation` are no longer used. This deletes them.
> LG-10273 idv_session cleanup - remove unused properties

- app/controllers/concerns/idv/verify_info_concern.rb
- app/controllers/idv/in_person/ssn_controller.rb
- app/controllers/idv/in_person/verify_info_controller.rb
- app/controllers/idv/verify_info_controller.rb
- app/views/idv/in_person/verify_info/show.html.erb
- app/views/idv/verify_info/show.html.erb
LG-10886
Missed a couple of places to add idv_session.ssn in #9129, including the verify_info show templates
> Couple more places to add idv_session.ssn

- app/assets/stylesheets/components/_footer.scss
- app/views/shared/_footer_lite.html.erb
[LG-10858](https://cm-jira.usa.gov/browse/LG-10858)
For mobile users the footer text is now upsized and has added padding to increase target area. The GSA logo in that same footer area is also slightly increased in size.
_simulated iPhone SE in MacOS Chrome browser_
Before
After
> LG-10858 Improve tappable area of LDP footer for mobile users

- app/services/encryption/encryptors/background_proofing_arg_encryptor.rb
- app/services/encryption/encryptors/session_encryptor.rb
- config/application.yml.default
- lib/identity_config.rb
- lib/session_encryptor.rb
- spec/services/encryption/encryptors/background_proofing_arg_encryptor_spec.rb
- spec/services/encryption/encryptors/session_encryptor_spec.rb
We are currently migrating from a single-region KMS key to a multi-region capable KMS key.
This commit modifies the SessionEncryptor and BackgroundArgsEncryptor to have to use a configurable key for their KMS client. These encryptors are used in 3 contexts:
1. Encryption of sessions (SessionEncryptor)
2. Encryption of GPO confirmation entries (SessionEncryptor)
3. Encryption of arguments to background jobs (BackgroundArgsEncryptor)
The KMS client's for these encryptors will now use the configured key ID for encryptions. For decryption the client allows KMS to select the key. This means that decryption will not be affected by this change as long as KMS still has access to the keys referenced by the KeyID used for encryption.
Since all of the encryption operations done with these encryptors …
> LG-10347 Make the key ID the session encryptor uses configurable

- app/services/encryption/regional_ciphertext_pair.rb
- config/application.yml.default
- lib/identity_config.rb
- spec/controllers/users/sessions_controller_spec.rb
- spec/features/legacy_passwords_spec.rb
- spec/jobs/multi_region_kms_migration/profile_migration_job_spec.rb
- spec/jobs/multi_region_kms_migration/user_migration_job_spec.rb
- spec/models/profile_spec.rb
- spec/models/user_spec.rb
- spec/services/encryption/encryptors/pii_encryptor_spec.rb
- spec/services/encryption/multi_region_kms_migration/profile_migrator_spec.rb
- spec/services/encryption/multi_region_kms_migration/user_migrator_spec.rb
- spec/services/encryption/password_verifier_spec.rb
The `aws_kms_multi_region_read_enabled` was in place to toggle the changes introduced in #9047. Those changes have been deployed, enabled, and have been running without issue for some time.
This commit removes the tooling to toggle the feature since we will be using it going forward.
> Remove the `aws_kms_multi_region_read_enabled` flag

- app/services/analytics_events.rb
- lib/tasks/review_profile.rake
- spec/lib/tasks/review_profile_spec.rb
We have a script that marks users pending fraud review as passed or rejected. Previously when users are passed or rejected in this way there was not event in events.log to log it.
This commit adds logging so we can track these events in cloudwatch.
> LG-10779 Log analytics events from the fraud review/reject script

- lib/reporting/identity_verification_report.rb
- spec/lib/reporting/identity_verification_report_spec.rb
Adds IDV rejects (doc auth fails, resolution fails, phonefinder fails) to the IDV report, so we can calculate the "industry rate" [(per Google Doc)](https://docs.google.com/document/d/1O6sw0_83EeOGX0QtUiYoHfm-m0VQCJqYQXgsgXuOU1M/edit#bookmark=id.budguol4yf)
This will be a V2 addition to https://github.com/18F/identity-idp/pull/9186
> Add rejections to IDV report (LG-10621)

- lib/reporting/identity_verification_report.rb
- lib/reporting/proofing_rate_report.rb
- spec/lib/reporting/identity_verification_report_spec.rb
- spec/lib/reporting/proofing_rate_report_spec.rb
One more change to #9186
**Problem**:
Currently, to get 30, 60, 90 day lookbacks, we end-up re-querying the most recent 30 days 30x. This adds up and times out locally
**Solution**:
Cache the results and merge them. Normally this might be a premature optimization, but since we're already hitting AWS session timeouts, this is no longer premature.
- Switches underlying `IdentityVerificationReport` to save unique UUIDs instead of just counts (this is similar to what we already to in `AuthenticationReport`
- Adds `#merge` method to reports to combine the underlying data
> Optimize ProofingRateReport

- app/controllers/users/delete_controller.rb
- spec/controllers/users/delete_controller_spec.rb
A follow-up to to complete the missing account management actions described in [this SBAR](https://docs.google.com/document/d/1lhjFcHlh2FmUrPFJ8h6QJmXHN_hDyW113U-ZidhSYNw/edit#heading=h.n0oa4p1mcfvz). Most of these were done in #8037, but account deletion was missed.
> Require recent authentication before deleting account

- app/controllers/idv/by_mail/enter_code_controller.rb
- app/controllers/idv/by_mail/letter_enqueued_controller.rb
- app/controllers/idv/by_mail/request_letter_controller.rb
- app/presenters/idv/by_mail/request_letter_presenter.rb
- config/routes.rb
- spec/presenters/idv/by_mail/request_letter_presenter_spec.rb
Follow-on to #9136. Should not be merged until that is deployed.
> LG-10530: Officially turn on new GPO routes

- config/initializers/content_security_policy.rb
- spec/requests/csp_spec.rb
Removes NewRelic domains from the Content Security Policy.
**Why?**
- We're no longer calling to NewRelic on the frontend as of #8950
- Hardens the security policy
- Check that response headers don't include NewRelic in any environment
- `rspec spec/requests/csp_spec.rb`
> Remove NewRelic domains from CSP

- app/controllers/concerns/idv/verify_info_concern.rb
Add temporary logging to figure out why ssn was not available for resolution proofing job when deploying #9182 to remove the ssn from the flow_session.
Log includes controller name to check whether the user is in remote or in person proofing flow.
Also, add the line that was missing from old instances that caused the problem during the 50/50 state. This needs to be deployed before unreverting the [delete PR](https://github.com/18F/identity-idp/pull/9182/) that caused the issue.
`ResolutionJobDebug: user_uuid=f46901d3-4c7f-4f5c-84bf-b0f76d84b211 old=true new=true controller=Idv::VerifyInfoController`
> Add logging to debug ssn 50/50 state issue.

- app/controllers/two_factor_authentication/webauthn_verification_controller.rb
- spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
[LG-11014](https://cm-jira.usa.gov/browse/LG-11014)
Updates logging for MFA submission for Face/Touch Unlock to always log a creation date on failed attempts, using the latest configuration if the form submission did not include identifiers for a valid authenticator.
As noted in the ticket, there's some complexity here because a user is permitted to use any of the F/T configurations associated with their account, which can be multiple, and in the case of a failure we don't know which F/T credential they'll have wanted to use. But because the intent with logging the date was to be able to effectively compare success rates before and after the enablement of Face/Touch Unlock, we need creation dates for failed attempts.
Prerequisite: Have an account with Face or Touch Unlock.
1. Go to …
> LG-11014: Log created at for latest WebAuthn config for failed attempt

- webpack.config.js
Fixes an issue where [Webpack tree-shaking](https://webpack.js.org/guides/tree-shaking/) (dead code elimination) was not working, inflating the size of JavaScript bundles by including JavaScript for design system components not in use.
This appears to have regressed as part of the revisions to `conditionNames` in #8655, though it's not entirely clear to me the relation between `conditionNames` and tree-shaking, aside from the net result that Webpack was choosing to resolve to CommonJS over ESM. Experimenting with ordering of `conditionNames` did not yield a desired outcome, but it does work correctly using the `...` placeholder [found in Webpack's internal source](https://github.com/webpack/webpack/blob/1f13ff9fe587e094df59d660b4611b1bd19aed4c/lib/config/defaults.js#L101-L102). …
> Fix JavaScript Webpack tree-shaking

- app/controllers/frontend_log_controller.rb
- app/javascript/packages/password-confirmation/password-confirmation-element.spec.ts
- app/javascript/packages/password-confirmation/password-confirmation-element.ts
- app/javascript/packages/password-toggle/password-toggle-element.spec.ts
- app/javascript/packages/password-toggle/password-toggle-element.ts
- app/services/analytics_events.rb
Removes the "Show Password button clicked" frontend event logged when toggling password visibility.
**Why?** It's not being actively monitored, and we should avoid unnecessarily inflating the size of JavaScript bundles.
Verify no regressions in toggling password visibility.
> Remove password toggle click frontend event

- spec/controllers/idv/session_errors_controller_spec.rb
Discovered in #9221 that some of the tests added in https://github.com/18F/identity-idp/pull/5546 were using the incorrect rate limit type. This PR fixes them.
> Fix identity verification session error tests to use the correct rate limiter

- app/services/rate_limiter.rb
- spec/services/rate_limiter_spec.rb
I was reviewing some NewRelic performance data on the `users/two_factor_authentication#show` and `users/two_factor_authentication#send_code` routes ([link](https://onenr.io/0OwvgVLOlRv)) and noticed an unusual amount of calls `del` calls to Redis.
It turns out there is an extra delete going on, and it is due to the `OtpRateLimiter` proactively deleting the value when it has expired. An empty value in Redis currently considers the expiration time to be `Time.zone.now` which will often be the case when someone is logging in. The comparison done in the `expired?` method means we are treating a blank Redis value as expired, which is causing the `OtpRateLimiter` to delete what is likely an empty value.
This PR changes it so that it is only considered expired if the value actually existed and …
> Do not consider a rate limit expired if there is no value

- app/controllers/concerns/idv/verify_info_concern.rb
- app/controllers/concerns/idv_step_concern.rb
- app/controllers/concerns/rate_limit_concern.rb
- app/controllers/idv/in_person/ssn_controller.rb
- app/controllers/idv/in_person/verify_info_controller.rb
- app/controllers/idv/session_errors_controller.rb
- app/controllers/idv/ssn_controller.rb
- app/controllers/idv/verify_info_controller.rb
- spec/controllers/concerns/rate_limit_concern_spec.rb
- spec/controllers/idv/in_person/ssn_controller_spec.rb
- spec/controllers/idv/in_person/verify_info_controller_spec.rb
- spec/controllers/idv/session_errors_controller_spec.rb
- spec/controllers/idv/ssn_controller_spec.rb
- spec/controllers/idv/verify_info_controller_spec.rb
[LG-10886](https://cm-jira.usa.gov/browse/LG-10886)
Fixed 50/50 state issue by adding :ssn to pii going to proof resolution job in deploy 314.2 #9226.
This reverts commit 4f0ad0433e3af392ded077c95749ba7ae58006d3, which reverted the commit to delete ssn from pii_from_doc.
> Finish removing ssn from flow session (revert the revert)

- config/locales/two_factor_authentication/en.yml
- config/locales/two_factor_authentication/es.yml
- config/locales/two_factor_authentication/fr.yml
[LG-10868: Update Backup code language](https://cm-jira.usa.gov/browse/LG-10868)
Updates the language for clearer understanding for users as to what they are entering and using language for backup code that makes sense.
Below Are what they would look like now
> LG-10868: Update Backup code language

- spec/lib/tasks/review_profile_spec.rb
The review profile rake task is used to pass or reject users after fraud review. We have a test case for users who running that task against a user who is not pending fraud review because they have undergone a more recent verification. Previously that test case actually tested a case where a user had an invalid profile state that was pending GPO verification. This should not be possible and raises an exception. It also did not match the spec description.
This commit cleans up the spec to cover the case described in the spec description. In this case the user has reset their password and deactivated the fraud pending profile. Then they have created a new profile that is GPO pending.
A new spec is also introduced to cover the code paths covered by the old test: a case where the profile is …
> LG-10779 Add a specific test case for a profile that cannot pass fraud review

- app/services/analytics_events.rb
- spec/features/idv/doc_auth/verify_info_step_spec.rb
Event renamed to `IdV: proofing resolution result missing` to conform to the other idv events.
Note: the old event name does not appear in any terraformed dashboards/metrics.
[LG-10718
](https://cm-jira.usa.gov/browse/LG-10718)
> LG-10718: rename Proofing Resolution Result Missing event

- lib/action_account.rb
- spec/lib/action_account_spec.rb
The fraud review pass/reject rake task is re-implemented in the ActionAccount tooling. #9194 added logging for the rake task. This commit adds the same logging to ActionAccount
> LG-10779 Add fraud review logging to the action account tooling

- app/javascript/packages/address-search/webpack.config.cjs
For tickets [LG-10330](https://cm-jira.usa.gov/browse/LG-10330) and [LG-10785](https://cm-jira.usa.gov/browse/LG-10785), new versions of `@18f/identity-address-search` were trying to be published on npm but build errors occurred. The solution is to update the webpack.config file for address-search so that dependencies can be resolved. 
Added `conditionNames: ['source']` to the resolve object inside `app/javascript/packages/address-search/webpack.config.cjs`. 
Before this was added, `yarn run webpack` would cause errors when ran inside `app/javascript/packages/address-search`
because webpack didn’t know how to resolve a dependency when that dependency is itself.  The conditionNames tells webpack to resolve its dependencies (one of which is itself!) using the source export. (Explanation & …
> Add conditionalNames to webpack in address-search

- app/controllers/openid_connect/token_controller.rb
- app/forms/openid_connect_token_form.rb
- app/services/analytics_events.rb
- app/services/id_token_builder.rb
- app/services/out_of_band_session_accessor.rb
- spec/controllers/openid_connect/token_controller_spec.rb
- spec/forms/openid_connect_token_form_spec.rb
- spec/services/access_token_verifier_spec.rb
- spec/services/id_token_builder_spec.rb
- spec/services/out_of_band_session_accessor_spec.rb
We currently make two TTL redis calls when responding to OpenID Token requests ([link](https://onenr.io/0oR8bVyneQG))
Since we've upgraded to Redis 7, we can use `expiretime` rather than `ttl` and only make the call once to re-calculate the TTL each time. This change is somewhat similar to https://github.com/18F/identity-idp/pull/7776
> Use Redis expiretime to avoid repeated TTL calls when building IdToken

- lib/cleanup/destroyable_records.rb
- spec/lib/cleanup/destroy_unused_providers_spec.rb
[LG-10920](https://cm-jira.usa.gov/browse/LG-10920)
Fix a bug where you could not use `destroy_unused_records.rb` if the Integration associated with the Service Provider being removed didn't have a Partner Account would fail.
> Don’t crash when integration.partner_acocunt is nil

- lib/reporting/identity_verification_report.rb
- spec/lib/reporting/identity_verification_report_spec.rb
[LG-11027](https://cm-jira.usa.gov/browse/LG-11027)
Add a line to Identity Verification Report for users who have passed fraud review, using the new event added in #9194.
Incidentally fix spelling in the report.
> Add count of users passing fraud review to Identity Verification Report

- app/controllers/concerns/second_mfa_reminder_concern.rb
- spec/controllers/concerns/second_mfa_reminder_concern_spec.rb
Follow-on revision for [LG-10022](https://cm-jira.usa.gov/browse/LG-10022) (#9124)
Updates the second MFA reminder logic to avoid prompting the user if they are authenticating with a partner which requires stricter MFA requirements (i.e. phishing-resistant or PIV-only). This avoids an issue where the user may inadvertently "downgrade" their authentication method, since they may choose to add a second MFA which is less secure than what was required for the request. This could result in the user being prompted excessively to reauthenticate, since the less-secure method would not be valid for the authentication request, and they'd need to reauthenticate with the more secure method.
Per [related Slack discussion](https://gsa-tts.slack.com/archives/C0595QABDS7/p1695058702797529), a separate …
> LG-10022: Avoid second MFA prompt for strict MFA requirement

- config/routes.rb
[LG-10530](https://cm-jira.usa.gov/browse/LG-10530)
* Remove a temporary route added in support of changing verify by mail related routes (see #9136, #9184)
* Keep redirects related to the "Come back later" page and "Enter code" page (but make them 301's for good measure)
The idea here is we want to keep supporting any users who've bookmarked verify by mail pages in anticipation of receiving their letter.
I've added LG-11023 to track the eventual cleanup of these redirects.
> LG-10530: Add redirects for select old GPO routes

- .gitlab-ci.yml
This PR fixes a bug in #9231 where the `build-ci-image` is not added to the pipeline but the `ecr-scan-ci` is in the pipeline and depends on it. There is no built-in functionality to not run a job if it depends on a job that is not being run. This PR attempts to fix it by using the same rules for both jobs.
```
Unable to create pipeline
'ecr-scan-ci' job needs 'build-ci-image' job, but 'build-ci-image' is not in any previous stage
```
> Do not create CI scan job when CI image is not built

- app/jobs/reports/monthly_account_reuse_report.rb
- spec/jobs/reports/monthly_account_reuse_report_spec.rb
**Why**: The tables report mailer expects percent data to be between 0.0 and 1.0,
this also matches how Excel and Sheets treat percents when formatting them
> Un-scale percents in Monthly Account Reuse Report

- app/jobs/in_person/enrollments_ready_for_status_check/enrollment_pipeline.rb
- app/services/analytics_events.rb
- spec/jobs/in_person/enrollments_ready_for_status_check/enrollment_pipeline_spec.rb
[LG-10082](https://cm-jira.usa.gov/browse/LG-10082)
Use either text_part or html_part to retrieve the enrollment code from USPS email and add an analytics event to determine in which part the code was found.
> lg-10082 usps enrollment code email format

- app/forms/register_user_email_form.rb
- app/models/suspended_email.rb
- spec/models/suspended_email_spec.rb
- spec/models/user_spec.rb
why: deleting the SuspendedEmail row cascades and deletes its associated email addresses
> LG-11115: Email Addresses deletion bug fixes in user reinstate

- config/application.yml.default
- spec/controllers/idv/by_mail/enter_code_controller_spec.rb
Most of our rate limiting allows a user 5 attempts so this brings the entering of the GPO verification code in line with the others.
We spoke to security and confirmed that there is no issue with this change.
changelog: User-facing Improvements, Identity Verification By Mail, Increased user's max attempts to enter their verification code before being rate limited.
[LG-10445](https://cm-jira.usa.gov/browse/LG-10445)
> LG-10445: bump up the GPO verification code max attempts to 5

- app/jobs/reports/monthly_key_metrics_report.rb
- spec/jobs/reports/monthly_key_metrics_report_spec.rb
changelog: Internal, Reporting, Manage recipients by config
> LG-10912 Adjust send condition to manage by config

- config/initializers/assets.rb
- lib/extensions/propshaft/asset.rb
This explores overriding Propshaft's default digesting logic in order to produce shorter file names. Since these files names are referenced in stylesheets (e.g. `url(/public/assets/...)`) and are not likely to be well-optimized by [DEFLATE](https://en.wikipedia.org/wiki/Deflate)/[LZ77](https://en.wikipedia.org/wiki/LZ77_and_LZ78)/[Huffman](https://en.wikipedia.org/wiki/Huffman_coding)-based compression, it's theorized that they may be contributing to larger overall file size.
The downside of this is it increases the likelihood of a hash collision, though it's quite unlikely, both that a hash collision would occur in the first place, and that two versions of a collided file hash would be cached in a user's browser such that conflicts could occur.
To my knowledge, Propshaft does not expose …
> Override Propshaft digesting for shorter file names

- app/controllers/idv/agreement_controller.rb
- app/controllers/idv/getting_started_controller.rb
- app/forms/idv/consent_form.rb
- spec/controllers/idv/agreement_controller_spec.rb
- spec/controllers/idv/getting_started_controller_spec.rb
While working on [LG-11041](https://cm-jira.usa.gov/browse/LG-11041) I noticed that, while we store the fact that the user checked the consent checkbox in IdvSession as `idv_consent_given`, we are still using `ial2_consent_given` for the form fields. I'd like to get the naming consistent to help avoid confusion in the future.
This PR renames some _internal_ variables and allows using either `params[:idv_consent_given]` or `params[ial2_consent_given]`. There will be two subsequent PRs required after this one is deployed:
1. Actually change the `ial2_consent_given` form field to `idv_consent_given`
2. Remove references to `ial2_consent_given` entirely
> Rename ial2_consent_given (1/3)

- app/jobs/multi_region_kms_migration/profile_migration_job.rb
- app/jobs/multi_region_kms_migration/user_migration_job.rb
Currently the ProfileMigrationJob and UserMigrationJob make expensive queries to find users to migrate. These queries need a large amount of time to run. To enable this we run them in a transaction with a local statement timeout.
I discovered an issue with this approach. The query was not actually executed in the transaction block. The transaction returned a relation and the query was executed when we attempted to iterated over the records in the relation. This commit adds a `#to_a` call to the relation to ensure the query is run and the records are loaded into memory before the transaction block is complete.
> Read records in KMS migration job while timeout is in effect

- app/controllers/users/backup_code_setup_controller.rb
- spec/controllers/users/backup_code_setup_controller_spec.rb
[LG-10972](https://cm-jira.usa.gov/browse/LG-10972)
Deleted method that clears the remember browser cookie and removed block in spec that looks for that.
> LG-10972 Adding backup codes invalidates remembered browser

- app/javascript/packages/document-capture/components/document-capture-warning.tsx
- app/javascript/packages/document-capture/components/warning.tsx
- spec/javascript/packages/document-capture/components/document-capture-warning-spec.jsx
- spec/javascript/packages/document-capture/components/review-issues-step-spec.jsx
- spec/javascript/packages/document-capture/components/warning-spec.jsx
Ticket: https://cm-jira.usa.gov/browse/LG-10973
Currently, the `Frontend: IdV: warning shown` event does not tell us what error the user saw, only that an error message was displayed. There were a couple of times where a user's uploaded photo has a few errors, and we weren't sure which message they actually saw. For example, a case where this might appear is when the user uploaded a passport image with an unreadable address, we wanted to be sure that they saw the "wrong doc type" messaging and not the "couldn't read address" messaging.
This change logs the heading and error shown so that in the future we can check what the user saw with relative ease.
Not exactly a screenshot, but here is the change in logs for a DOB entry error (log shortened with `[...]`):
<details> …
> LG-10973: Log heading and error message when warning shown

- app/controllers/concerns/second_mfa_reminder_concern.rb
- config/application.yml.default
- lib/identity_config.rb
- spec/controllers/concerns/second_mfa_reminder_concern_spec.rb
[LG-10022](https://cm-jira.usa.gov/browse/LG-10022)
Removes the feature flag added in #9124 to help ensure a smooth 50/50 deployment (see https://github.com/18F/identity-idp/pull/9124#issuecomment-1721221738).
This should only be merged after #9124 is fully deployed in production.
Repeat Testing Plan from #9124.
> LG-10022: Remove feature flag for second MFA reminder

- app/controllers/reactivate_account_controller.rb
- app/services/analytics_events.rb
- spec/controllers/reactivate_account_controller_spec.rb
Based on discussion [here](https://gsa-tts.slack.com/archives/C01SU3NB9T3/p1695761963325599?thread_ts=1695761192.956659&cid=C01SU3NB9T3), it should be much easier to understand patterns of identity verification when these events are present. This PR adds them.
> Add account reactivation event logging

- app/javascript/packages/document-capture/components/submission-complete.tsx
- package.json
- yarn.lock
Upgrades TypeScript from 5.0.x to 5.2.x
Release notes:
- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-1.html
- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html
**Why?**
- Incorporate improvements outlined in release notes above (new features, optimizations)
The `SubmissionComplete` component was ported to TypeScript due to some issues flagged which appeared to be difficult / impossible to resolve in JavaScript syntax.
```
$ tsc
app/javascript/packages/document-capture/components/submission-complete.jsx:10:15 - error TS2304: Cannot find name 'T'.
10  * @prop {()=>T} read Resource reader.
~
app/javascript/packages/document-capture/components/submission-complete.jsx:18:11 - error TS2315: Type 'Resource' is not generic.
18  * @prop …
```
> Upgrade TypeScript to 5.2

- app/views/idv/agreement/show.html.erb
- app/views/idv/getting_started/show.html.erb
- spec/views/idv/agreement/show.html.erb_spec.rb
- spec/views/idv/getting_started/show.html.erb_spec.rb
Follow-on to #9286, removing references to ial2_consent_given from the frontend. Should not be merged until that PR has been deployed.
> Rename ial2_consent_given (2/3)

- app/controllers/concerns/idv/verify_info_concern.rb
- spec/controllers/idv/verify_info_controller_spec.rb
[LG-11089](https://cm-jira.usa.gov/browse/LG-11089)
If this seems familiar from #8599, it's because it might be.
**Problem:** AAMVA's billing doesn't match what we are logging
**Context**:
It turns out we have been recording a cost for the  `UnsupportedJurisdiction`
However, `UnsupportedJurisdiction` is from our own code: https://github.com/18F/identity-idp/blob/794448c60065af9c65ef4b4420e0188002519c3a/app/services/proofing/resolution/progressive_proofer.rb#L195-L202
Meaning we didn't make a call to AAMVA at all, so they can't bill us for it:
https://github.com/18F/identity-idp/blob/794448c60065af9c65ef4b4420e0188002519c3a/app/services/proofing/resolution/progressive_proofer.rb#L166
**Solution**:
Stop recording costs for `UnsupportedJurisdiction`
Checking [Cloudwatch][cloudwatch-query], …
> Update AAMVA billing logic (LG-11089)

- app/presenters/two_factor_login_options_presenter.rb
- spec/features/openid_connect/phishing_resistant_required_spec.rb
- spec/features/saml/phishing_resistant_required_spec.rb
- spec/presenters/two_factor_login_options_presenter_spec.rb
[LG-11110](https://cm-jira.usa.gov/browse/LG-11110)
Fixes an issue where a user's MFA methods are filtered to PIV or phishing-resistant methods when prompted to reauthenticate after making a selection to set up a new, eligible strict AAL2 method, thereby preventing them from continuing if they don't already have one of these methods.
It can help to set `reauthn_window` to a low value in local development to force frequent reauthentication, e.g. 20 seconds in `config/application.yml`:
```
reauthn_window: 20
```
1. Go to http://localhost:3000 in local development
2. Create an account with phishable MFA method(s) (i.e. anything other than face/touch, PIV, or security key)
3. Start [OIDC Sample App](https://github.com/18F/identity-oidc-sinatra) in a separate terminal process
4. Go to …
> LG-11110: Allow user to reauthenticate with any MFA method in strict AAL2 setup

- app/views/accounts/_password_reset.html.erb
- app/views/accounts/_pending_profile_gpo.html.erb
- app/views/accounts/_service_provider_continue.html.erb
- app/views/idv/in_person/ready_to_verify/show.html.erb
- app/views/idv/verify_info/show.html.erb
Updates a few alerts:
- Removes `text_tag` attribute where the alert is displaying simple text and should use the default behavior of rendering the simple text within a `<p>` tag
- Removes explicit margin resets on the last paragraphs within alerts, since this was [added as a global style](https://github.com/18F/identity-idp/blob/f2efbd7b0572767cf7fefb3ce6e27db50d7341cd/app/assets/stylesheets/components/_alert.scss#L19-L21)
This was initially prompted by some recent observation of unnecessary use of `text_tag`. Originally I was trying some more ambitious ideas (replacing `text_tag` with `with_paragraph` [slot](https://viewcomponent.org/guide/slots.html), or adding `AlertComponent#text_tag` as a private method which inspects its own content to decide the appropriate wrapper tag), but those …
> Fix alert paragraph rendering semantics, redundant styling

- .gitignore
Avoid accidentally checking in stray .bak files.
This is a followup to an incident where a backup config file had sensitive information and was accidentally pushed to github.
> Gitignore .bak files

- docs/frontend.md
Updates frontend documentation for guidance on how to debug production JavaScript errors, since the previous guidance became obsolete as of #8950.
Review documentation for accuracy / helpfulness.
> Update guidance for frontend error logging

- app/controllers/idv/agreement_controller.rb
- app/controllers/idv/getting_started_controller.rb
- app/forms/idv/consent_form.rb
- spec/controllers/idv/agreement_controller_spec.rb
- spec/controllers/idv/getting_started_controller_spec.rb
Follow on to #9287, removes all references to / support for ial2_consent_given. Should not be merged until that PR is deployed.
> Rename ial2_consent_given (3/3)

- .gitlab-ci.yml
We have had some red builds on main due to the new secrets detection CI job. I ran it locally and it was flagging the following paths:
- `config/artifacts.example/local/oidc.key`
- `keys.example/saml_test_sp.key`
- `keys.example/saml_test_sp2.key`
- `public/acuant/11.9.1/opencv.min.js`
- `tmp/0.0.0.0-3000.key`
Note that for the OpenCV JS file, it was incorrectly identifying random blobs in a giant base64-encoded string as AWS access keys. The other files are just example keys or temporary keys used in CI itself.
This PR adds exceptions to the secret scanner to allow these paths.
> Exclude certain paths from secrets detection

- app/presenters/two_factor_auth_code/generic_delivery_presenter.rb
- app/presenters/two_factor_auth_code/webauthn_authentication_presenter.rb
- spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
- spec/presenters/two_factor_auth_code/piv_cac_authentication_presenter_spec.rb
- spec/presenters/two_factor_auth_code/webauthn_authentication_presenter_spec.rb
- spec/views/two_factor_authentication/webauthn_verification/show.html.erb_spec.rb
Relates to / simplifies [LG-11101](https://cm-jira.usa.gov/browse/LG-11101)
Removes references to `ServiceProviderMfaPolicy` in `GenericDeliveryPresenter` which appear to be unused.
Previous usage:
- `WebauthnAuthenticationPresenter#multiple_factors_enabled?` reference added in #5976, last reference removed in #8716
- `PivCacAuthenticationPresenter` references added in #4014, last references removed in #8837
- Build should pass.
- Verify no regressions in signing in with MFA methods, particularly WebAuthn and PIV/CAC
> Remove unused ServiceProviderMfaPolicy from GenericDeliveryPresenter

- .rubocop.yml
- app/services/analytics_events.rb
- docs/backend.md
- lib/linters/analytics_event_name_linter.rb
- spec/lib/linters/analytics_event_name_linter_spec.rb
Adds a new custom Rubocop linter to enforce a naming convention for analytics, expecting that the first argument to `track_event` should be a symbol with the same name as the method.
**Good:**
```rb
module AnalyticsEvents
def my_method
track_event(:my_method)
end
end
```
**Bad:**
```rb
module AnalyticsEvents
def my_method
track_event('Some other name')
end
end
```
This was discussed in Engineering Huddle 2023-10-05 ([see notes](https://docs.google.com/document/d/1g_V2vlT79tScBKIVw7M4UXf15TrG69iUrLHE0yE1GGI/edit)).
The proposal here would not retroactively update existing analytics, but would enforce against all new analytics events moving forward. This is done by adding inline Rubocop disabling for existing events.
```
bundle exec rubocop
```
> Add and enforce analytics naming convention

- package.json
- yarn.lock
Updates PostCSS to resolve [a (moderate) security advisory](https://github.com/18F/identity-idp/security/dependabot/63).
Couple notes:
- As of #6591, we no longer use PostCSS directly, so it's removed as an explicit dependency
- We still have a dependency through [stylelint](https://github.com/stylelint/stylelint), and while they have [merged an update](https://github.com/stylelint/stylelint/pull/7218), there's not yet a published version containing this change, so this assigns `resolutions` instead. Per SemVer version ranges, this should be expected to be safe, and is a [designed use-case for `resolutions`](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/#:~:text=A%20sub%2Ddependency%20of%20your%20project%20got%20an%20important%20security%20update%20and%20you%20don% …
> Pin PostCSS to resolve advisory, remove explicit dependency

- app/controllers/concerns/idv/verify_info_concern.rb
- app/controllers/concerns/idv_step_concern.rb
- app/controllers/concerns/rate_limit_concern.rb
- app/controllers/idv/address_controller.rb
- app/controllers/idv/agreement_controller.rb
- app/controllers/idv/document_capture_controller.rb
- app/controllers/idv/getting_started_controller.rb
- app/controllers/idv/hybrid_handoff_controller.rb
- app/controllers/idv/in_person/ssn_controller.rb
- app/controllers/idv/in_person/verify_info_controller.rb
- app/controllers/idv/link_sent_controller.rb
- app/controllers/idv/phone_controller.rb
- app/controllers/idv/phone_question_controller.rb
- app/controllers/idv/review_controller.rb
- app/controllers/idv/ssn_controller.rb
- app/controllers/idv/verify_info_controller.rb
- app/controllers/idv/welcome_controller.rb
- spec/controllers/concerns/idv_step_concern_spec.rb
- spec/controllers/concerns/rate_limit_concern_spec.rb
Currently we have a before action that enforces all of the rate limits that a user might encounter during proofing. This is done so that if a user will encounter a rate limit during a proofing attempt they are sent to an error instead of being put through the process which they will not be able to complete when they reach a rate limited step.
Prior to this commit we would check on all steps for whether a rate limiter has exceeded the maximum. This check was applied to all steps in a before action in `IdvStepConcern`. A consequence of this is we cannot count successful attempts towards the rate limit. In the case where we did that a user would complete a step successfully, then be redirected on the next step since the rate limiter for the previous trip exceeded the number of allowable …
> LG-11187 Don't enforce the rate limits for previous steps during proofing

- spec/controllers/idv/personal_key_controller_spec.rb
- spec/controllers/idv/review_controller_spec.rb
- spec/support/controller_helper.rb
Updates spec controller helper methods to stub `user_session` as an instance of `HashWithIndifferentAccess`.
**Why?**
- It matches the real-world behavior that the session is a hash with indifferent access [[1]](https://github.com/roidrage/redis-session-store#other-notes) [[2]](https://github.com/18F/identity-idp/blob/214b400fd705b50fc64894fb3191afb0cbbda7a3/lib/session_encryptor.rb#L55)
- It resolves inaccuracies in existing specs (`Idv::PersonalKeyController`)
Split from #9335, after discovering unrelated spec failures after introducing the HashWithIndifferentAccess there.
```
rspec
```
> Update specs to initialize session as HashWithIndifferentAccess

- config/locales/help_text/en.yml
- config/locales/help_text/es.yml
- config/locales/help_text/fr.yml
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- config/locales/two_factor_authentication/en.yml
- config/locales/two_factor_authentication/es.yml
- config/locales/two_factor_authentication/fr.yml
- config/locales/user_mailer/en.yml
- config/locales/user_mailer/es.yml
- config/locales/user_mailer/fr.yml
- config/service_providers.localdev.yml
- spec/decorators/service_provider_session_spec.rb
- spec/factories/service_providers.rb
- spec/services/service_provider_updater_spec.rb
[LG-11043](https://cm-jira.usa.gov/browse/LG-11043)
Replace `<b>` tags with `<strong>`. It could be argued that making the service provider name bold is a case of the guideline below, in which case those should be reverted to `<b>`.
```
Note: Docs on when "b" is preferable over "strong" (See "[Usage notes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/b#usage_notes)".) 
Use the <b> for cases like keywords in a summary, product names in a review, or other spans of text whose typical 
presentation would be boldfaced (but not including any special importance)." 
It is unlikely we have any such cases of this but we should be aware of it when making this change.
```
> Change `<b>` tags to `<strong>` for better accessibility and code consistency

- .rubocop.yml
- Gemfile
- Gemfile.lock
- spec/components/base_component_spec.rb
- spec/components/block_link_component_spec.rb
- spec/controllers/concerns/idv/ab_test_analytics_concern_spec.rb
- spec/controllers/concerns/idv_step_concern_spec.rb
- spec/controllers/concerns/rate_limit_concern_spec.rb
- spec/features/remember_device/sp_expiration_spec.rb
- spec/lib/identity_job_log_subscriber_spec.rb
- spec/lib/telephony/pinpoint/sms_sender_spec.rb
- spec/presenters/two_factor_authentication/selection_presenter_spec.rb
- spec/presenters/two_factor_authentication/set_up_selection_presenter_spec.rb
- spec/presenters/two_factor_authentication/sign_in_selection_presenter_spec.rb
- spec/routing/gpo_verification_routing_spec.rb
- spec/services/doc_auth/acuant/request_spec.rb
- spec/services/frontend_logger_spec.rb
- spec/services/usps_in_person_proofing/enrollment_helper_spec.rb
Idea from @aduth, who saw my [repeated comments on another PR](https://github.com/18F/identity-idp/pull/9333#discussion_r1353057306)
Docs: https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecleakyconstantdeclaration
> Enable RSpec/LeakyConstantDeclaration rubocop

- .gitlab-ci.yml
- Makefile
- webpack.config.js
Adds a check in continuous integration that production-compiled JavaScript and CSS sizes are within a reasonable size constraint.
This is a follow-up to #9217, specifically implementing the suggestion made by @allthesignals at https://github.com/18F/identity-idp/pull/9217#issuecomment-1721692585 .
Currently, limits are set to:
- `application.css` must be less than 350kb (currently 299kb)
- `application.js` must be less than 8kb (currently 4kb) 
Observe CI build results for commit history. I'll push a temporary commit shortly to test a revert of #9217, which should fail the check.
> Add lint check for reasonable asset bundle sizes

- app/jobs/reports/combined_invoice_supplement_report.rb
This is a small change that lets us run the report manually as a one-off as needed
([example request in Slack](https://gsa-tts.slack.com/archives/C5E7EJWF7/p1696970801898509))
> Reorganize combined invoice report for easier manual runs

- lib/data_requests/local/fetch_cloudwatch_logs.rb
In discussing results of this report, it can be confusing to include these events since it mentions the IRS and understandably can suggest there is a link with the IRS in the logs (which is rarely the case).
> Exclude 'IRS Attempt API: Event metadata' events from log results

- app/controllers/concerns/rate_limit_concern.rb
- app/controllers/idv/phone_controller.rb
- app/controllers/idv/phone_errors_controller.rb
- spec/controllers/concerns/rate_limit_concern_spec.rb
- spec/controllers/idv/phone_errors_controller_spec.rb
- spec/controllers/idv_controller_spec.rb
- spec/factories/profiles.rb
- spec/features/idv/phone_errors_spec.rb
- spec/features/idv/proof_address_rate_limit_spec.rb
- spec/features/idv/steps/gpo_otp_verification_step_spec.rb
Users are being rate limited and encountering the phone error screen even if they can still verify by mail. This commit changes the rate limit logic to allow users to proceed to the phone step if they can still verify their phone or complete verification by mail.
A side-effect of this change is a bug is fixed where the following situation would exist:
1. A user proofed by mail after exhausting phone attempts
2. The user goes to GPO entry and chooses to cancel and start over
3. The user is redirected to the welcome step to start over
4. The welcome step before action observes the user is phone rate limited and sends the user to the phone errors controller
5. The phone errors controller has a before action to confirm the user has completed the phone errors step; the user has not since in …
> LG-11066 Do not redirect users at the phone step unless they are phone and address rate limited

- app/jobs/reports/month_helper.rb
- spec/jobs/reports/month_helper_spec.rb
- If the first month was a partial month, the code would inadvertently return the whole month instead of just that partial month
- This came up for a one-off reporting request, most production agreements last longer than just a month
> Fix bug in reporting "months" helper

- app/controllers/idv/personal_key_controller.rb
- spec/controllers/accounts_controller_spec.rb
- spec/controllers/idv/personal_key_controller_spec.rb
- spec/controllers/idv/review_controller_spec.rb
[LG-11221](https://cm-jira.usa.gov/browse/LG-11221)
Previously, when the user refreshed the Personal Key page, a new key was generated each time. This could prevent the user from recovering their account if they saved the previous key and didn't notice it had changed. Now, the personal key remains the same when the page is refreshed.
> LG-11221 Personal key doesn't change on page refresh

- app/controllers/idv/phone_controller.rb
- spec/controllers/idv/phone_controller_spec.rb
We do not currently count successful proofing attempts towards the rate limit. This was done to support a feature that prevented users from being rate limited after successfully completing a step. The logic that caused that issue was addressed in #9343.
This commit starts counting successful attempts to towards the rate limit. This protects our vendors from abuse and makes it easier for us to make this step re-entrant to support the back button.
> Count successful phone proofing attempts towards the rate limit

- app/controllers/idv/document_capture_controller.rb
- app/forms/idv/api_image_upload_form.rb
- spec/features/idv/doc_auth/document_capture_spec.rb
Prior to this commit we reset the doc auth rate limiter on success. This was done to prevent users from being rate limited after successfully completing a step. The logic that caused that issue was addressed in #9343.
This commit starts counting successful attempts to towards the rate limit. This protects our vendors from abuse and makes it easier for us to make this step re-entrant to support the back button.
> LG-11189 Count successful doc auth proofing towards the rate limit

- app/controllers/concerns/idv/verify_info_concern.rb
- spec/features/idv/doc_auth/verify_info_step_spec.rb
Prior to this commit we reset the ss rate limiter on success. This was done to prevent users from being rate limited after successfully completing a step. The logic that caused that issue was addressed in #9343.
This commit starts counting successful attempts to towards the rate limit. This protects our users from fraud and makes it easier for us to make this step re-entrant to support the back button.
> LG-11190 Don't reset the SSN rate limit on successful submission

- app/controllers/users/piv_cac_login_controller.rb
- spec/controllers/users/piv_cac_login_controller_spec.rb
Makes a fix similar to #8622, #6121, #6309 where we should only request the password if it is strictly needed. If a user is not logging in during an IAL2 request with an active profile, we should not prompt for a password.
> Do not always prompt for password when logging in with PIV/CAC during identity verification request

- app/controllers/two_factor_authentication/sms_opt_in_controller.rb
- app/views/devise/sessions/_return_to_service_provider.html.erb
- app/views/idv/by_mail/letter_enqueued/show.html.erb
- app/views/idv/phone_errors/failure.html.erb
- app/views/idv/session_errors/warning.html.erb
- app/views/idv/shared/_document_capture.html.erb
- app/views/idv/unavailable/show.html.erb
- app/views/sign_up/completions/show.html.erb
- spec/controllers/two_factor_authentication/sms_opt_in_controller_spec.rb
- spec/features/idv/doc_auth/redo_document_capture_spec.rb
- spec/features/openid_connect/openid_connect_spec.rb
- spec/features/saml/ial1_sso_spec.rb
- spec/features/saml/ial2_sso_spec.rb
- spec/features/saml/redirect_uri_validation_spec.rb
- spec/features/saml/saml_spec.rb
- spec/views/devise/sessions/new.html.erb_spec.rb
- spec/views/idv/by_mail/letter_enqueued/show.html.erb_spec.rb
- spec/views/idv/phone_errors/failure.html.erb_spec.rb
- spec/views/idv/session_errors/warning.html.erb_spec.rb
- spec/views/idv/unavailable/show.html.erb_spec.rb
- spec/views/sign_up/completions/show.html.erb_spec.rb
[LG-11037
](https://cm-jira.usa.gov/browse/LG-11037)
Add missing step name where analytics events logged.
> LG-11037: empty step logged

- app/services/idv/gpo_mail.rb
- spec/features/idv/steps/enter_code_step_spec.rb
- spec/features/idv/steps/request_letter_step_spec.rb
We renamed the code that is used to verify by mail in #9136. This replaced "GPO" with more descriptive names. This commit removes a few lingering references to GPO.
> Remove trailing references to GPO in IdV

- app/jobs/reports/monthly_key_metrics_report.rb
- lib/reporting/monthly_proofing_report.rb
- spec/jobs/reports/monthly_key_metrics_report_spec.rb
https://cm-jira.usa.gov/browse/LG-11183
> Lg 11183 document upload proofing automate

- yarn.lock
Attempts to upgrade dependencies that have known security vulnerabilities.
`yarn audit`:
```
│ critical      │ Babel vulnerable to arbitrary code execution when compiling  │
│               │ specifically crafted malicious code                          │
│ Package       │ @babel/traverse                                              │
│ Patched in    │ >=7.23.2                                                     │
│ Dependency of │ @babel/core …
```
> Upgrade Node packages to patch critical vulnerability in Babel

- bin/query-cloudwatch
- spec/bin/query-cloudwatch_spec.rb
[LG-11257](https://cm-jira.usa.gov/browse/LG-11257)
Adds a new `--date` option to `query-cloudwatch` that allows using the the `time_slices` option of our `CloudwatchClient` to query separate, disjoint dates with the same query, willl help with more efficient use of time in Cloudwatch and lower billing costs.
example:
```bash
> aws-vault exec prod-power -- \
./bin/query-cloudwatch \
--date 2023-09-01,2023-08-01 \ # << NEW OPTION
--env prod --app idp --log events.log \
--query "fields @timestamp | stats count(*) by bin(1d)" \
--no-progress
2023-09-01 00:00:00.000,20914416
2023-08-01 00:00:00.000,25423701
```
> Update query-cloudwatch to be able to query multiple dates (LG-11257)

- lib/data_pull.rb
- spec/lib/data_pull_spec.rb
[LG-11256](https://cm-jira.usa.gov/browse/LG-11256)
Adds a new data-pull task that can export a summary of the events table, intended for fraud team investigations
```bash
> bundle exec bin/data-pull events-summary 593f754d-418d-491b-bbbd-b1c1f2143b72
*Task*: `events-summary`
*UUIDs*: `593f754d-418d-491b-bbbd-b1c1f2143b72`
+--------------------------------------+------------+--------------+
| uuid                                 | date       | events_count |
+--------------------------------------+------------+--------------+
| 593f754d-418d-491b-bbbd-b1c1f2143b72 | 2023-10-13 | 2            |
+--------------------------------------+------------+--------------+
```
> Add events-summary data-pull dask (LG-11256)

- app/controllers/idv/phone_controller.rb
- app/forms/idv/phone_form.rb
- spec/controllers/idv/phone_controller_spec.rb
- spec/features/idv/analytics_spec.rb
- spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb
- spec/forms/idv/phone_form_spec.rb
This commit uses the phone number a user used to complete the hybrid flow if we have the user has no MFA phone number. Hopefully pre-filling the number in this way will help improve success on the phone step.
> LG-10849 Use hybrid flow phone number in phone form

- lib/reporting/monthly_proofing_report.rb
- spec/lib/reporting/monthly_proofing_report_spec.rb
[LG-11320](https://cm-jira.usa.gov/browse/LG-11320)
Rescues errors we're seeing in lower environments due to different retention settings than production
| screenshot |
| --- |
|  <img width="926" alt="Screenshot 2023-10-16 at 3 16 26 PM" src="https://github.com/18F/identity-idp/assets/458784/52c8b3d0-b2b9-408d-9820-213eda8d1ef8"> |
> Handle errors due to Cloudwatch retention in monthly report (LG-11320)

- app/javascript/packages/clipboard-button/package.json
- package.json
- yarn.lock
Updates `@18f/identity-design-system` to the latest version (8.0.1) to resolve an issue affecting the appearance of accordion expander icons.
See release notes: https://github.com/18F/identity-design-system/releases/tag/v8.0.1
2. Sign in
3. Click "Edit password" in account dashboard
4. If prompted, MFA again
5. Hover the "Password safety tips"
6. Observe the icon doesn't change
Alternatively, go to http://localhost:3000/components/inspect/accordion/preview and hover the accordion expander.
Before|After
---|---
> Update 18f/identity-design-system to 8.0.1

- config/application.yml.default.docker
Updates default configuration for review applications to enable component previews.
**Why?**
- It'd be useful for changes like #9393 to be able to direct to a review application component preview link for testing
1. Go to https://review-aduth-revi-9r0xs8.review-app.identitysandbox.gov/components/
2. Hey, look, it works!
> Enable component previews in review applications

- app/controllers/concerns/remember_device_concern.rb
- app/controllers/concerns/two_factor_authenticatable_methods.rb
- app/services/auth_methods_session.rb
- spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
- spec/controllers/users/piv_cac_login_controller_spec.rb
- spec/services/auth_methods_session_spec.rb
[LG-11101](https://cm-jira.usa.gov/browse/LG-11101)
Starts double-tracking authentication events to a new session value, in preparation for #9335 (Part 2) to switch over to that session value for considering whether one of the events would satisfy an authentication request.
Since this is only setting but not reading from a new session value, there should not be an expected change in user behavior.
Verify there are no regressions in allowing the user to be considered authenticated, e.g. by remember device cookie, or AAL2 strict requests. See testing plan in #9335 for example.
> LG-11101: Double-track auth methods session value (Part 1 of 2)

- config/application.rb
- config/initializers/rack_timeout.rb
- lib/idp/constants.rb
Back in March, we experimented with [disabling async proofing](https://gsa-tts.slack.com/archives/C42TZ3K5H/p1678995313038359?thread_ts=1678994905.846599&cid=C42TZ3K5H). It failed due to the Rack::Timeout exception list being out of date. We've had a pretty significant re-structuring of the paths around identity verification since then as well. Now that it has mostly stabilized, this PR removes the routes that no longer exist and updates the routes to reflect valid routes. It also adds the internationalized versions of the routes.
> Update rack-timeout exclusion paths

- app/controllers/users/two_factor_authentication_setup_controller.rb
- app/presenters/two_factor_options_presenter.rb
- app/views/users/two_factor_authentication_setup/index.html.erb
- spec/presenters/two_factor_options_presenter_spec.rb
- spec/views/users/two_factor_authentication_setup/index.html.erb_spec.rb
[LG-11036](https://cm-jira.usa.gov/browse/LG-11036)
The presenter was repurposing code that populated the available mfa in the form to show the list of selected mfa. That caused a bug in AAL2+ Add Second MFA view if the user had a phone option selected or any other phishing vulnerable options it couldn't show there. 
I added a method that collects the selected mfa independent of the options that add checkboxes to the form.
You should expect to see "Your authentication methods" lists authentication methods, and there's no option to skip this step since it's required to sign in to the partner.  Cancel (link) replaces skip for now and signs out.
> LG-11036 unexpected content second mfa requirement for aal2+

- app/mailers/report_mailer.rb
- spec/mailers/report_mailer_spec.rb
Due to some shared behavior, we were attaching the Login.gov logo to emails that don't strictly need them
| | before | after | 
| --| --- | ---- |
| Mailer preview |  <img width="496" alt="Screenshot 2023-10-17 at 2 33 41 PM" src="https://github.com/18F/identity-idp/assets/458784/c5b35145-f670-4d50-9d81-e9ac3e4b2063"> |  <img width="496" alt="Screenshot 2023-10-17 at 2 33 55 PM" src="https://github.com/18F/identity-idp/assets/458784/48a988f9-2182-40ec-97d1-063f25e98696"> |
| GMail |  <img width="289" alt="Screenshot 2023-10-17 at 2 35 54 PM" src="https://github.com/18F/identity-idp/assets/458784/5f36a7c8-7adc-41d8-8168-ddba8b8815ea"> | N/A |
> Remove logo attachment from reporting email

- app/jobs/reports/monthly_key_metrics_report.rb
- spec/jobs/reports/monthly_key_metrics_report_spec.rb
**Why**: So that #initialize matches #perform, just in case this affects the job runner
> Switch MonthlyKeyMetricsReport to use positional args

- app/jobs/reports/authentication_report.rb
- app/jobs/reports/monthly_key_metrics_report.rb
- app/mailers/report_mailer.rb
- app/services/reporting/account_deletion_rate_report.rb
- app/services/reporting/account_reuse_and_total_identities_report.rb
- app/services/reporting/emailable_report.rb
- app/services/reporting/monthly_active_users_count_report.rb
- app/services/reporting/total_user_count_report.rb
- app/views/report_mailer/tables_report.html.erb
- lib/reporting/authentication_report.rb
- lib/reporting/monthly_proofing_report.rb
- spec/jobs/reports/authentication_report_spec.rb
- spec/jobs/reports/monthly_key_metrics_report_spec.rb
- spec/lib/reporting/authentication_report_spec.rb
- spec/mailers/previews/report_mailer_preview.rb
- spec/mailers/report_mailer_spec.rb
- spec/services/reporting/monthly_active_users_count_report_spec.rb
- Removes options hash, makes options first-class propreties
- Refactors existing reports
(I'm branching off of https://github.com/18F/identity-idp/pull/9405 because I didn't want to deal with merge conflicts in the `report_mailer.rb` file)
> Update ReportMailer to use EmailableReports struct

- app/forms/update_user_password_form.rb
- spec/controllers/users/passwords_controller_spec.rb
- spec/forms/update_user_password_form_spec.rb
If a user updates their password with an active profile we re-encrypt the active profile with their password. We do not, however, re-encrypt pending profiles.
We are considering a change that would re-encrypt pending profiles if the data was decrypted and available in the session. Before we do we want to measure the impact this change would have. Currently we do not log if a user has a pendin g profile when updating their password so measuring impace is not possible.
This commit adds the necessary logging to make a decision about the feature described above.
> Log if a user has a pending or active profile when updating their passsword

- app/controllers/concerns/idv/phone_question_ab_test_concern.rb
- config/application.yml.default.docker
- spec/features/idv/doc_auth/hybrid_handoff_spec.rb
LG-11091
Rate limiting has been refactored allowing users to advance to next Idv step for successful final attempts.  If doc auth rate limited,  do no redirect the user back to the phone question page when visiting the hybrid handoff page.
> LG-11091: rate limited hybrid handoff not route to phone question

- app/controllers/concerns/idv/verify_info_concern.rb
- spec/features/idv/doc_auth/verify_info_step_spec.rb
[LG-11042](https://cm-jira.usa.gov/browse/LG-11042)
This commit starts counting successful attempts to verify info towards the idv_resolution rate limit. This affects remote and in-person verify info.
> LG-11042: increment idv_resolution rate limiter on success.

- app/services/reporting/account_deletion_rate_report.rb
- app/services/reporting/monthly_active_users_count_report.rb
- app/services/reporting/total_user_count_report.rb
The reports have been running quietly in prod and timing out because the queries are taking too long, this addresses that
> Add DB timeouts to MonthlyKeyMetricsReports parts

- app/views/accounts/_pii.html.erb
- config/locales/account/en.yml
- config/locales/account/es.yml
- config/locales/account/fr.yml
- config/locales/headings/en.yml
- config/locales/headings/es.yml
- config/locales/headings/fr.yml
- config/locales/help_text/es.yml
- spec/support/idv_examples/clearing_and_restarting.rb
[LG-11197](https://cm-jira.usa.gov/browse/LG-11197)
Updates labels used in the "profile information" (now "verified information") section on the account dashboard to be more accurate.
1. Prerequisite: Have a verified account (go to http://localhost:3000/verify with an unverified account to verify)
3. Sign in
4. On account dashboard, observe labels for verified information
Before|After
---|---
> LG-11197: Update labels for account page verified information

- app/jobs/reports/monthly_key_metrics_report.rb
- app/mailers/report_mailer.rb
- spec/jobs/reports/monthly_key_metrics_report_spec.rb
- spec/mailers/previews/report_mailer_preview.rb
Uses live code but stubs Cloudwatch. It returns some NaN's but that's better than completely fake data
(from team pairing session)
| screenshot |
| --- |
|  <img width="754" alt="Screenshot 2023-10-19 at 12 26 25 PM" src="https://github.com/18F/identity-idp/assets/458784/e7f455ec-3c0e-427d-9f3a-c91900270ea4"> |
> Update report mailer preview to be more realistic

- app/javascript/packages/analytics/README.md
- docs/frontend.md
Adds a new section "Analytics" to the [frontend developer documentation](https://github.com/18F/identity-idp/blob/main/docs/frontend.md), as an action item from the 2023-10-18 Engineering Huddle discussion.
1. Go to https://github.com/18F/identity-idp/blob/aduth-frontend-analytics-docs/docs/frontend.md#analytics
2. See if it reads well enough to cover common usage patterns
> Add analytics section to frontend documentation

- app/controllers/application_controller.rb
- app/controllers/concerns/reauthentication_required_concern.rb
- app/controllers/concerns/remember_device_concern.rb
- app/controllers/concerns/two_factor_authenticatable_methods.rb
- app/policies/service_provider_mfa_policy.rb
- app/services/auth_methods_session.rb
- spec/controllers/concerns/reauthentication_required_concern_spec.rb
- spec/controllers/saml_idp_controller_spec.rb
- spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb
- spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
- spec/controllers/users/piv_cac_authentication_setup_controller_spec.rb
- spec/controllers/users/piv_cac_login_controller_spec.rb
- spec/features/openid_connect/phishing_resistant_required_spec.rb
- spec/features/saml/phishing_resistant_required_spec.rb
- spec/policies/service_provider_mfa_policy_spec.rb
- spec/services/auth_methods_session_spec.rb
- spec/support/controller_helper.rb
- spec/support/features/session_helper.rb
[LG-11101](https://cm-jira.usa.gov/browse/LG-11101)
Updates MFA handling to track multiple MFAs in the current session, to improve reuse and avoid situations where adding an MFA may unintentionally "downgrade" the user's session (such as what prompted the changes in #9263).
Effectively, this changes the session to be able to track all authentications in the session and choose if any would be valid for the scenarios where it is checked.
This depends on (and merges to) changes proposed in #9388 to start tracking the session value, and should not be merged until #9388 is live in production.
Verify new supported behavior to allow strict MFA reuse after adding or authenticating with a "lesser" MFA:
1. (Prerequisite) Create an account with an unphishable method (e.g. PIV, security key, face or …
> LG-11101: Support multiple valid MFA to satisfy authentication request (Part 2 of 2)

- app/controllers/concerns/second_mfa_reminder_concern.rb
- spec/controllers/concerns/second_mfa_reminder_concern_spec.rb
Follow-on to [LG-10022](https://cm-jira.usa.gov/browse/LG-10022) (#9124, #9263) and [LG-11101](https://cm-jira.usa.gov/browse/LG-11101) (#9388, #9335)
Removes the exception to consider service provider MFA requirements as part of the second MFA reminder screen logic.
This is essentially a revert of #9263.
This exception was added in #9263 because, at the time, we only kept record of the user's most recently-used authentication method, and adding an MFA during a strict-AAL2 sign-in could cause the second MFA addition to "downgrade" to a lesser method. This was improved in #9335 by supporting multiple recent authentication methods to be considered as part of the strict-AAL2 sign-in, so it is no longer necessary to exclude these requests from the logic.
Repeat Testing Plan from #9263 and …
> Remove second MFA prompt exception for strict MFA requirement

- app/controllers/idv/hybrid_handoff_controller.rb
- app/views/idv/hybrid_handoff/show.html.erb
- config/locales/doc_auth/en.yml
- config/locales/doc_auth/es.yml
- config/locales/doc_auth/fr.yml
- spec/features/idv/doc_auth/hybrid_handoff_spec.rb
- spec/views/idv/hybrid_handoff/show.html.erb_spec.rb
https://cm-jira.usa.gov/browse/LG-10922
This adds a change of heading text to the Hybrid Handoff page, if `idv_phone_question_a_b_testing` is set to `1`. If it's set to `0`, (the default), the old copy should remain.
<details>
<summary>Before / with `idv_phone_question_a_b_testing: '{"bypass_phone_question":100, "show_phone_question":0}'`:</summary>
</details>
<details>
<summary>After / with `idv_phone_question_a_b_testing: '{"bypass_phone_question":0, "show_phone_question":100}'`</summary>
</details>
> LG-10922: Display new headings for Hybrid Handoff page on AB test

- Gemfile
- Gemfile.lock
- bin/oncall/otp-deliveries
- lib/script_base.rb
- spec/lib/script_base_spec.rb
SSM commands have a max output of about 63kb, and some of our export tasks output more data than that, so they get truncated.
This adds DEFLATE compression which seems to help pack down output, so we can export more. Some notes from example testing [(Slack link)](https://gsa-tts.slack.com/archives/C5E7EJWF7/p1697823732756599?thread_ts=1697751216.934009&cid=C5E7EJWF7):
| Format | Size |
| ---- | ---- |
| ASCII table (current) | 72,449 bytes |
| JSON of table data | 58,721 bytes |
| JSON then DEFLATE | 2,145 bytes (!!!!) |
| JSON then DEFLATE then Base64 | 2,908 bytes |
Other notes:
- The compression defaults to off so the calling script in devops will add it (devops PR coming soon)
- I'm currently deploying this to our sandbox to verify that binary output is OK with SSM-command
> Add --deflate option to data-pull and action-account scripts

- app/controllers/idv/document_capture_controller.rb
- app/controllers/idv/hybrid_mobile/document_capture_controller.rb
- app/controllers/idv/link_sent_controller.rb
- app/javascript/packages/document-capture-polling/index.ts
- app/javascript/packs/doc-capture-polling.ts
- app/javascript/packs/document-capture.tsx
- app/views/idv/document_capture/show.html.erb
- app/views/idv/hybrid_mobile/document_capture/show.html.erb
- app/views/idv/link_sent/show.html.erb
- app/views/idv/shared/_document_capture.html.erb
- spec/features/idv/analytics_spec.rb
- spec/javascript/packages/document-capture-polling/index-spec.js
- spec/views/idv/shared/_document_capture.html.erb_spec.rb
https://cm-jira.usa.gov/browse/LG-11239
This ticket adds information to the FE logs about which group the user is in for our "phone question" A/B test. Each user will either be
- In the "nothing changed", A group, `:bypass_phone_question`
- Or in the the "sees the phone question", B group, `:show_phone_question`
Note: If you're a person without a local dev environment, you can follow the testing steps below in stage or this PR's branch and review the logs in cloudwatch instead of locally.
> LG-11239: Add Phone Question Bucket to FE Logging

- app/components/webauthn_verify_button_component.html.erb
- app/javascript/packages/webauthn/webauthn-verify-button-element.spec.ts
- app/javascript/packages/webauthn/webauthn-verify-button-element.ts
- app/views/users/webauthn_setup/new.html.erb
- spec/components/webauthn_verify_button_component_spec.rb
- spec/support/features/webauthn_helper.rb
[LG-11344](https://cm-jira.usa.gov/browse/LG-11344)
Disables button for Face or Touch Unlock sign-in or setup when clicked, to avoid a scenario where multiple clicks due to a delay in the OS prompt may cause the user to see multiple prompt windows.
Sign-in:
1. Prerequisite: Have a user with Face or Touch Unlock (see "Account creation" instructions)
3. Sign in
4. (If directed immediately to Account page, click "Forget all browsers", confirm, then sign out and start over)
5. When prompted for Face or Touch Unlock, click "Use face or touch unlock" multiple times very quickly, ideally before the prompt is shown
6. Continue signing in
7. Observe that (a) you are still able to sign-in successfully and (b) you only saw a single prompt for your credential
Account …
> LG-11344: Prompt at most once for WebAuthn authentication

- app/views/devise/sessions/new.html.erb
- app/views/sign_up/registrations/new.html.erb
- config/locales/links/en.yml
- config/locales/links/es.yml
- config/locales/links/fr.yml
- spec/features/visitors/password_recovery_spec.rb
- spec/support/features/session_helper.rb
- spec/views/sign_up/registrations/new.html.erb_spec.rb
[LG-10996](https://cm-jira.usa.gov/browse/LG-10996)
Change the localization token from links.next to links.sign_in and update all instances of that token.
Revise [Spanish](https://github.com/18F/identity-site/blob/e6f6ada6b75899310cbf8164322d1b8edd128da9/content/_help/manage-your-account/change-your-email-address._es.md?plain=1#L16) and [French](https://github.com/18F/identity-site/blob/e6f6ada6b75899310cbf8164322d1b8edd128da9/content/_help/manage-your-account/change-your-email-address._fr.md?plain=1#L18) translation. Found in identity-site code.
> LG-10996 Fix Spanish and French translation for Sign In

- app/controllers/idv/enter_password_controller.rb
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- spec/controllers/idv/enter_password_controller_spec.rb
changelog: User-Facing Improvements, IdV, remove obsolete too much mail message
[LG-11270](https://cm-jira.usa.gov/browse/LG-11270)
We removed the too much mail flash error message on the enter password controller.
If testing locally add these config variables
```
minimum_wait_before_another_usps_letter_in_hours: 0
max_mail_events: 1
```
> LG-11270 Remove obsolete too much mail message on enter password controller

- lib/reporting/cloudwatch_client.rb
- spec/lib/reporting/cloudwatch_client_spec.rb
when we run the `./bin/query-cloudwatch` script, we're running outside of Rails, so `Time.zone` is nil, so we get errors like this. Switching to `Time.at` lets us work around this
Example:
```bash
identity-idp/lib/reporting/cloudwatch_client.rb:169:in `rescue in fetch_one': undefined method `at' for nil:NilClass (NoMethodError)
log(:warn, "query end_time=#{end_time} (#{Time.zone.at(end_time)}) is before Cloudwatch Insights availability, skipping")
^^^
from identity-idp/lib/reporting/cloudwatch_client.rb:155:in `fetch_one'
from identity-idp/lib/reporting/cloudwatch_client.rb:88:in `block (2 levels) in fetch'
.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.179.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call': End time should not be before the service was …
```
> Fix CloudwatchClient error when run with a nil timezone

- app/controllers/concerns/mfa_setup_concern.rb
- app/controllers/mfa_confirmation_controller.rb
- app/controllers/sign_up/completions_controller.rb
- spec/features/two_factor_authentication/backup_code_sign_up_spec.rb
- spec/features/two_factor_authentication/multiple_mfa_sign_up_spec.rb
[LG-11006](https://cm-jira.usa.gov/browse/LG-11006)
Adds the event "User registration: complete" to user registration flows where previously missing.
> LG-11006: "User registration complete" event not logged for direct sign-up

- spec/features/accessibility/user_pages_spec.rb
- spec/features/accessibility/visitor_pages_spec.rb
- spec/support/matchers/accessibility.rb
Adds a pair of feature specs which cover expected behavior for skip links in (a) default screens and (b) the account page, which behaves differently by skipping repeated navigation.
I was motivated to add this after noticing in #9436 that specs did not fail, indicating a lack of test coverage for the existence of the skip link.
```
rspec spec/features/accessibility/user_pages_spec.rb spec/features/accessibility/visitor_pages_spec.rb
```
> Add feature specs for expected skip link behavior

- app/controllers/idv/cancellations_controller.rb
- app/javascript/packages/components/checkbox.spec.tsx
- app/javascript/packages/components/checkbox.tsx
- app/javascript/packages/components/field-set-spec.tsx
- app/javascript/packages/components/field-set.tsx
- app/javascript/packages/components/index.ts
- app/javascript/packages/document-capture/components/document-capture-abandon.tsx
- app/javascript/packages/document-capture/components/document-capture-review-issues.tsx
- app/javascript/packages/document-capture/components/documents-step.jsx
- app/javascript/packages/document-capture/components/optional-questions.scss
- app/javascript/packages/document-capture/styles.scss
- app/javascript/packages/verify-flow/cancel.spec.tsx
- app/javascript/packages/verify-flow/context/flow-context.tsx
- app/javascript/packs/document-capture.tsx
- app/views/idv/shared/_document_capture.html.erb
- config/locales/doc_auth/en.yml
- config/locales/doc_auth/es.yml
- config/locales/doc_auth/fr.yml
- config/locales/idv/en.yml
- config/locales/idv/es.yml
- config/locales/idv/fr.yml
- config/routes.rb
- spec/features/idv/doc_auth/document_capture_spec.rb
- spec/javascript/packages/document-capture/components/document-capture-abandon-spec.jsx.tsx
- spec/javascript/packages/document-capture/components/document-capture-abandon-spec.tsx
- spec/javascript/packages/document-capture/components/document-capture-review-issues-spec.jsx
- spec/javascript/packages/document-capture/components/documents-step-spec.jsx
- spec/javascript/packages/document-capture/components/review-issues-step-spec.jsx
- spec/support/features/document_capture_step_helper.rb
[LG-11139: Add optional question about other ID types
](https://cm-jira.usa.gov/browse/LG-11139)
Add optional survey questions to document image capturing page.
Record user submission as analytics events.
Redirect user to SP specific or general account page when user chooses Exit or "Submit and exit".
With Service Provider:
- Step 1: Navigate to document capturing page, with Service Provider
- Step 2: Verify the new content displayed on the page
- Step 3: Click exit link, verify landing to SP failure to proof page
- Step 4: Repeat and choose ID types, click on button
- Step 5: Verify landing to SP failure to proof page and analytics events logged
Without Service Provider:
- Step 1: Navigate to document capturing page, with Service …
> LG-11139: question upon exit

- Makefile
- app/assets/stylesheets/_uswds.scss
- app/components/accordion_component.html.erb
Removes [USWDS Prose component](https://designsystem.digital.gov/components/prose/) styles from the application stylesheet, to further optimize its output size and compile times.
We only had a single reference to this in the accordion component. While the [source example component code for accordion](https://designsystem.digital.gov/components/accordion/#component-code) does prescribe `usa-prose`, the only meaningful impact I could tell is the enforcement of a maximum width on the text. Since our Figma references for the accordion component don't apply this maximum text width (cc @nickttng) and we generally don't use "prose" styling, I think it should be safe and consistent to remove.
This also updates asset size budgets to be more aggressively small.
An upstream pull request to USWDS at …
> Remove USWDS prose styles from application stylesheet

- app/services/doc_auth/acuant/request.rb
- app/services/doc_auth/acuant/requests/get_results_request.rb
- app/services/doc_auth/acuant/requests/upload_image_request.rb
- app/services/doc_auth/errors.rb
- app/services/doc_auth/mock/doc_auth_mock_client.rb
- app/services/doc_auth/mock/result_response.rb
- app/services/doc_auth_router.rb
- config/locales/doc_auth/en.yml
- config/locales/doc_auth/es.yml
- config/locales/doc_auth/fr.yml
- spec/controllers/idv/image_uploads_controller_spec.rb
- spec/features/idv/doc_auth/redo_document_capture_spec.rb
- spec/services/doc_auth/acuant/acuant_client_spec.rb
- spec/services/doc_auth/acuant/requests/get_results_request_spec.rb
- spec/services/doc_auth/acuant/requests/upload_image_request_spec.rb
- spec/services/doc_auth/acuant/responses/get_results_response_spec.rb
- spec/services/doc_auth/mock/doc_auth_mock_client_spec.rb
- spec/services/doc_auth_router_spec.rb
- spec/support/features/doc_auth_helper.rb
[LG-10889](https://cm-jira.usa.gov/browse-LG-10889): Fix bug where user does not see inline errors when Acuant AssureID service encountered errors indicated by http status code 438, 439, 440.
Add inline error message for Acuant response status code specific to 438, 439 and 440.
Testing in dev.
Http status 438:
```yaml
http_status:
back:  438
```
Http status 439:
```yaml
http_status:
front:  439
```
Http status 440:
```yaml
http_status:
front:  440
```
In higher environment:
This is Acuant specific, so testing is not straight forward, basic testing can be done with images not satisfying size requirement which is 2025 x 1275 pixels.
<details>
<summary>Http status 438: image load failure</summary>
English:
Spanish:
French:
</details>
<details>
<summary>Http status 439: pixel depth</summary> …
> LG-10889: image metric error

- Makefile
- app/assets/stylesheets/_uswds-form-controls.scss
- app/assets/stylesheets/components/_index.scss
- app/javascript/packages/document-capture/components/_file-input.scss
- app/javascript/packages/document-capture/styles.scss
Moves default and custom styles for the [File Input component](https://designsystem.digital.gov/components/file-input/) into the document capture stylesheet, to reduce the size of the main application stylesheet, since this component is only used in document capture.
This also updates asset size budgets to be more aggressively small.
```
NODE_ENV=production yarn build:css && brotli-size app/assets/builds/application.css
```
**Before:** 25.3kb
**After:** 24.6kb
**Diff:** -0.7kb (-2.8%)
Verify there are no visual regressions in the appearance of the File Input component in document capture.
> Move File Input component styles to document capture stylesheet
