18F/identity-idp

app/controllers/concerns/idv_session.rb, app/controllers/concerns/idv_step_concern.rb, app/controllers/idv/by_mail/request_letter_controller.rb, app/controllers/idv/enter_password_controller.rb, app/controllers/idv/otp_verification_controller.rb, app/controllers/idv/phone_controller.rb, app/controllers/idv/phone_errors_controller.rb, app/controllers/idv/resend_otp_controller.rb, app/views/idv/enter_password/new.html.erb, app/views/idv/forgot_password/new.html.erb, spec/controllers/idv/by_mail/request_letter_controller_spec.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/controllers/idv/hybrid_handoff_controller_spec.rb, spec/controllers/idv/otp_verification_controller_spec.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/controllers/idv/phone_controller_spec.rb, spec/controllers/idv/phone_errors_controller_spec.rb, spec/controllers/idv/resend_otp_controller_spec.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/features/accessibility/idv_pages_spec.rb, spec/features/idv/end_to_end_idv_spec.rb, spec/features/idv/phone_otp_rate_limiting_spec.rb, spec/features/idv/proof_address_rate_limit_spec.rb, spec/features/idv/steps/forgot_password_step_spec.rb, spec/features/idv/steps/phone_otp_verification_step_spec.rb, spec/features/idv/steps/phone_step_spec.rb, spec/features/idv/steps/request_letter_step_spec.rb, spec/support/features/doc_auth_helper.rb, spec/support/idv_examples/max_attempts.rb
The change in #9375 renamed the review controller to the "enter password" controller. This commit introduced a new path, but did not start using it to support the 50/50 state when that change was deployed.
This commit starts using the new path but does not remove the old ones. This is also to prevent 404s in the 50/50 state. A follow up will be needed to remove the old routes after this is deployed.
=> Start using the new enter password url

bin/query-cloudwatch, spec/bin/query-cloudwatch_spec.rb
Leftover from pairing on [LG-11381](https://cm-jira.usa.gov/browse/LG-11381)
=> Add --num-threads option to query-cloudwatch

docs/frontend.md
Adds a new section "Naming Conventions" to the JavaScript guidance found in the frontend documentation.
This should match reality, so hopefully nothing here is controversial, but open to feedback all the same, or gaps if I missed anything.
Reference discussion: https://github.com/18F/identity-idp/pull/9433#discussion_r1369182903
See preview: https://github.com/18F/identity-idp/blob/javascript-naming-conventions/docs/frontend.md#naming-conventions
=> Add JavaScript naming conventions to frontend documentation

lib/script_base.rb, spec/lib/script_base_spec.rb
[LG-11359](https://cm-jira.usa.gov/browse/LG-11359)
Fixes scripts so that we don't log stacktraces like this
| screenshot |
| ---- |
| <img width="698" alt="Screenshot 2023-10-25 at 12 45 07 PM" src="https://github.com/18F/identity-idp/assets/458784/290c87f3-352c-4bb4-900b-8c999144e869"> |
=> Rescue errors when running remote data-pull, action-account (LG-11359)

lib/pinpoint_supported_countries.rb
[LG-11422](https://cm-jira.usa.gov/browse/LG-11422)
Adds UK to the set of sender ID countries so that the preconfigured sender ID is provided for SMS to the country.
Source for how Sender ID is configured using our single static Sender ID:
https://github.com/18F/identity-idp/blob/a1df4929df4387a55406f2d14fd5d0e1e6b79768/config/initializers/telephony.rb#L16-L19
Reference that Sender ID is supported without registration (see "Yes" under "Supports Sender ID", notably not "Registration required"):
https://docs.aws.amazon.com/pinpoint/latest/userguide/channels-sms-countries.html
Reference that "GB" is the country identifier:
https://github.com/18F/identity-idp/blob/a1df4929df4387a55406f2d14fd5d0e1e6b79768/config/pinpoint_supported_countries.yml#L317-L321
Slack discussion: …
=> LG-11422: Provide Sender ID for UK SMS

app/controllers/concerns/remember_device_concern.rb, spec/features/remember_device/signed_in_sp_expiration.rb
The remember device concern is used to check if the remember device interval is expired requiring a user to re-authenticate. That check is performed on these lines:
https://github.com/18F/identity-idp/blob/f8ee126760a802eaa33de4d0786c120c50f16961/app/controllers/saml_idp_controller.rb#L24
https://github.com/18F/identity-idp/blob/f8ee126760a802eaa33de4d0786c120c50f16961/app/controllers/openid_connect/authorization_controller.rb#L21
It looks like the `expired_for_interval?` was recently changed to return true if remember device was used at any point and is now expired (ref: https://github.com/18F/identity-idp/pull/9335/files#diff-82060fb86bc64910b8186479a6f620e6ba44b007ca059e082c468f29702cf142R56). As a result, a user is prompted to re-authenticate if their remember device session is …
=> Return false from `expired_for_interval?` if the last auth event was not a remember device event

app/jobs/reports/monthly_key_metrics_report.rb, lib/reporting/identity_verification_report.rb, lib/reporting/monthly_proofing_report.rb, lib/reporting/proofing_rate_report.rb, spec/jobs/reports/monthly_key_metrics_report_spec.rb, spec/lib/reporting/proofing_rate_report_spec.rb, spec/mailers/previews/report_mailer_preview.rb
changelog: Internal, Reporting, Add Proofing Rate Metrics
https://cm-jira.usa.gov/browse/LG-11152
=> LG-11152 Add Proofing Rate Metrics to MKMR

app/controllers/concerns/rate_limit_concern.rb, app/controllers/idv/by_mail/enter_code_controller.rb, app/controllers/idv/by_mail/request_letter_controller.rb, app/controllers/idv/phone_controller.rb, app/controllers/idv/phone_errors_controller.rb, app/controllers/vendor_outage_controller.rb, app/services/idv/gpo_mail.rb, app/views/idv/by_mail/enter_code/index.html.erb, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml, spec/controllers/idv/by_mail/request_letter_controller_spec.rb, spec/features/idv/clearing_and_restarting_spec.rb, spec/features/idv/steps/enter_code_step_spec.rb, spec/services/idv/gpo_mail_spec.rb, spec/support/idv_examples/verification_code_entry.rb
[LG-11271](https://cm-jira.usa.gov/browse/LG-11271)
This is a code cleanup PR to align with our current language around rate limits and verification codes.
- Rename `GpoMail#mail_spammed?` to `#rate_limited?`
- Related renaming of translation tags and spec methods
- Rename shared examples `gpo otp verification` to `verification code entry`
Automated testing in CI
=> LG-11271 change mail spammed language to rate_limited 

config/routes.rb
In #9411 we moved all traffic from the old `/verify/review` path to the new `/verify/enter_password` path. We left the old paths around so that users getting redirected by old instances would not encounter a 404 error.
Once the changes in #9411 has been deployed for a day there should not be any more users visiting `/verify/review` and we can merge this change to remove that deprecated path.
=> LG-11403 Remove the old review routes

app/javascript/packages/document-capture/components/document-capture-review-issues.tsx, app/javascript/packages/document-capture/components/documents-step.jsx, spec/features/idv/doc_auth/document_capture_spec.rb, spec/javascript/packages/document-capture/components/document-capture-review-issues-spec.jsx, spec/javascript/packages/document-capture/components/documents-step-spec.jsx, spec/javascript/packages/document-capture/components/review-issues-step-spec.jsx
LG-11425: remove the optional cancel survey questions from doc auth image upload screen.
<details>
</details>
=> LG-11425:  turnoff

app/javascript/packages/document-capture/components/document-capture-review-issues.tsx, app/javascript/packages/document-capture/components/documents-step.jsx, spec/features/idv/doc_auth/document_capture_spec.rb, spec/javascript/packages/document-capture/components/document-capture-review-issues-spec.jsx, spec/javascript/packages/document-capture/components/documents-step-spec.jsx, spec/javascript/packages/document-capture/components/review-issues-step-spec.jsx
- Doc Auth: Remove optional questions from capture screen. ([#9468](https://github.com/18F/identity-idp/pull/9468))
=> Deploy RC 327.1 to Prod

config/routes.rb
Deleted redirects for GET and PUT methods from `/in_person_proofing/ssn`. This route used to handle the old FSM navigation, but with the deprecation and removal of the IPP SSN FSM step and subsequent replacement with a controller, this route is no longer needed. The redirects were put in place to ensure a seamless rollout for users.
=> LG-10913 remove ssn redirects

scripts/changelog_check.rb
Removes code introduced with the renamed "Improvements" category in #7511 which was meant to support developers through a transition period. Since this rename has been live for almost a year, it should be safe to say that we've completed the transition.
```
rspec spec/scripts/changelog_check_spec.rb
```
=> Remove "transitional" compatibility from changelog script

app/assets/stylesheets/components/_btn.scss, app/assets/stylesheets/components/_list.scss
Removes two styles which would have no effect, due to invalid combinations.
I came aware of these with automated validation tools in Chrome and VSCode.
I couldn't easily run an audit over all CSS with Chrome's validator (though I did find [the source](https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/panels/elements/CSSRuleValidator.ts;l=27?q=%22property%20prevents%22&ss=chromium)). Running VSCode's validator over the compiled CSS did reveal another upstream issue in USWDS, tracked at https://github.com/uswds/uswds/pull/5587 .
Verify no regressions in appearance of unstyled buttons and success-bullet lists.
=> Remove ineffective invalid CSS

lib/cleanup/destroyable_records.rb
[LG-10920](https://cm-jira.usa.gov/browse/LG-10920)
There is additional checks required to have the rake task be able to continue through `destroyable_records.rb`. The issue is `integration` is nil, not `integration.partner_account` as I initially assumed based on the error.
=> The issue was actually integration not existing, not partner_account

app/controllers/concerns/idv/ab_test_analytics_concern.rb, app/controllers/concerns/idv/phone_question_ab_test_concern.rb, app/controllers/idv/hybrid_mobile/document_capture_controller.rb, app/controllers/idv/phone_question_controller.rb, app/services/idv/session.rb, spec/controllers/concerns/idv/ab_test_analytics_concern_spec.rb, spec/controllers/concerns/idv/phone_question_ab_test_concern_spec.rb, spec/controllers/idv/hybrid_handoff_controller_spec.rb, spec/controllers/idv/hybrid_mobile/document_capture_controller_spec.rb, spec/controllers/idv/phone_question_controller_spec.rb, spec/features/idv/analytics_spec.rb, spec/features/idv/doc_auth/phone_question_spec.rb
[LG-11427](https://cm-jira.usa.gov/browse/LG-11427)
Store phone_with_camera in idv_session and log in analytics for IdV events.
Bypass phone question page
1. Complete identity verification
2. verify phone_with_camera=nil is logged for most Idv events post agreement step.
Phone question page with camera
1. Complete Idv steps until hybrid handoff page is rendered
3. visit /verify/phone_question
4. Select I have a phone and complete Idv
5. verify phone_with_camera=true is logged for most Idv events post agreement step.
Phone question page without camera
1. Complete Idv steps until hybrid handoff page is rendered
3. visit /verify/phone_question
4. Select I do have a phone and complete Idv
5. verify phone_with_camera=false is logged for most Idv events post agreement step.
NOTE: events not …
=> LG-11427: add phone_with_camera to analytics

lib/reporting/cloudwatch_client.rb, lib/reporting/monthly_proofing_report.rb, spec/lib/reporting/cloudwatch_client_spec.rb, spec/lib/reporting/monthly_proofing_report_spec.rb
[Link to the relevant ticket.](https://cm-jira.usa.gov/browse/LG-11416)
=> LG:11416: Fix CloudwatchClient error for MKMR in dev and int

app/views/idv/in_person/address/show.html.erb
This commit changed the app to require templates to declare a title: https://github.com/18F/identity-idp/commit/4d69e9de84fdfbd44597fa6ec60a355ae448dd08
It looks like this was able to sneak through without a title declaration in the In-Person flow on in the address show template. This commit adds a title declaration to that template.
=> Add a title to the in person address template

app/views/two_factor_authentication/sms_opt_in/new.html.erb, spec/controllers/two_factor_authentication/sms_opt_in_controller_spec.rb
Fixes an error from missing title for SMS opt-in.
Regressed in #9447.
Slack: https://gsa-tts.slack.com/archives/C0NGESUN5/p1698769857824419
```
rspec spec/controllers/two_factor_authentication/sms_opt_in_controller_spec.rb
```
=> Add missing title for SMS opt-in

app/controllers/sign_up/completions_controller.rb, app/services/pii/attributes.rb, app/services/pii/cacher.rb, spec/presenters/completions_presenter_spec.rb
The `Pii::Cacher#fetch_string` method gets the raw PII JSON blob and returns it. This is called by the `#fetch` in the `Pii::Cacher` and converted to `Pii::Attributes`.
Outside of the `Pii::Cacher` this method is called in one place by the IdP. This is in the completions controller to get the PII which is ultimately parsed into a hash. The same can be acheived by taking the result of `Pii::Cacher#fetch` and calling `#to_h` on it. This commit does that so the `#fetch_string` method can be made part of the private API.
Making this method part of the private API will make it easier to modify the way the cacher works to support encrypting and decrypting both active and pending profiles in the future.
=> Make Pii::Cacher#fetch_string a private method

Gemfile.lock
The changes in #9357 included some deprecations that I missed. Example:
```
DEPRECATION WARNING: DeprecatedConstantAccessor.deprecate_constant without a deprecator is deprecated (called from <top (required)> at /Users/andrewmduthie/Documents/Code/identity-idp/config/application.rb:20)
Run options: include {:locations=>{"./spec/features/two_factor_authentication/sign_in_spec.rb"=>[62]}}
```
The deprecation comes from devise and was fixed in https://github.com/heartcombo/devise/pull/5599. Updating devise removes the warning.
=> Update devise to fix deprecation warning

db/schema.rb, db/worker_jobs_schema.rb
Check in schema changes that result from running `make update` on current main from the Rails 7.1 upgrade
=> Check in schema changes for Rails 7.1 upgrade

app/views/users/totp_setup/new.html.erb, spec/features/users/totp_management_spec.rb, spec/support/matchers/accessibility.rb
[LG-11278](https://cm-jira.usa.gov/browse/LG-11278)
Adds a fieldset grouping to the TOTP setup screen, to logically group related fields.
Related resource: https://www.w3.org/TR/WCAG20-TECHS/H71.html
This is a non-visual change, as it labels the fieldset using `aria-labeledby` with an existing text on the page "Set up an authentication app to sign in using temporary security codes.".
Recommended to review with [whitespace changes hidden](https://github.com/18F/identity-idp/pull/9484/files?w=1) due to most view changes being the addition of a wrapping element that increases the tab level of most content.
You can inspect the grouping element with your browser DevTool's "Accessibility" inspector to confirm the named grouping:
You can also confirm with a screen reader that entering the form …
=> LG-11278: Group authentication app setup fields with fieldset

app/services/idv/session.rb, app/services/pii/cacher.rb, app/services/reactivate_account_session.rb, config/environments/test.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/controllers/users/passwords_controller_spec.rb, spec/services/idv/session_spec.rb
The `#save_decrypted_pii_json` method consumed a JSON PII object and wrote it into the session under the `decrypted_pii` key.
This method was called in 2 places:
- The `ReactivateAccountController`
- The `Idv::Session`
In `ReactivateAccountController` the PII is available as `Pii::Attributes` and is converted to JSON to enable a call to `#save_decrypted_pii_json`.
In the `Idv::Session` the PII is available as `Pii::Attributes`, but prior to this commit underwent quite the Rube Goldberg process to find it's way into a JSON string that was then written to the session  by `save_decrypted_pii_json`.
This commit changes `save_decrypted_pii_json` to be `save_decrypted_pii` and take a `Pii::Attributes` instead of a JSON string argument. This will make it easier to implement a version of this …
=> Modify `Pii::Cacher#save_decrypted_pii_json` to be `Pii:Cacher#save_decrypted_pii`

spec/controllers/two_factor_authentication/sms_opt_in_controller_spec.rb, spec/features/two_factor_authentication/sign_in_spec.rb
Adds feature spec coverage for SMS opt-in behaviors introduced in #5894.
**Why?**
- To exercise the expected behaviors of opting in a phone that's previously opted out
- As an alternative regression spec to the fix introduced with #9493
```
rspec spec/features/two_factor_authentication/sign_in_spec.rb:62
```
=> Add feature spec coverage for SMS opt-in

bin/oncall/email-deliveries
The script makes use of `#present?` and fails without the require:
```
/Users/mitchellehenke/projects/identity-idp/lib/reporting/cloudwatch_client.rb:231:in `slice_time_range': undefined method `present?' for nil:NilClass (NoMethodError)
if time_slices.present?
^^^^^^^^^
from /Users/mitchellehenke/projects/identity-idp/lib/reporting/cloudwatch_client.rb:64:in `fetch'
from bin/oncall/email-deliveries:91:in `block in query_data'
from /Users/mitchellehenke/projects/identity-idp/lib/reporting/unknown_progress_bar.rb:24:in `wrap'
from bin/oncall/email-deliveries:90:in `query_data'
from bin/oncall/email-deliveries:60:in `run'
from bin/oncall/email-deliveries:150:in `<main>'
```
=> Fix bug with missing require in email-deliveries script

app/models/in_person_enrollment.rb, spec/models/in_person_enrollment_spec.rb
The issue appears not to be with the spec, but rather with how we were calculating the difference between the start date and the current date. Now using the `Time` object to perform simple subtraction between the start date and current date.
Make sure that `/spec/models/in_person_enrollment_spec.rb` doesn't fail intermittently.
=> LG-11441 - Fix Flakey In-person Enrollment test

Makefile, docs/backend.md
Adds and documents a new `Makefile` helper command used to watch live event logging.
I've had a version of this command in my local `.zshrc` file, and recently I've found myself sharing it with others who are troubleshooting event logging in their local environment.
1. Run `make run` and `make watch_events` in separate terminal processes.
3. Navigate the application
4. Observe as events are pretty-printed as you navigate the application, using `jq`
Appearance may vary by terminal customization settings
=> Add watch_events Makefile target

config/routes.rb
We made changes to the routes for the verify by mail code entry and come back later URLs.
The come_back_later URL has a reasonably low amount of traffic to it. This commit unpublishes it for that reason.
The enter_code URL does have traffic to it. Currently it redirects which strips a query param included in the URL. To support that query param this commit republishes it so that query parameter works.
=> LG-11023 Unpublish old come_back_later URL and republish old enter_code URL

app/mailers/user_mailer.rb, app/models/user.rb, app/services/analytics_events.rb, app/views/layouts/user_mailer.html.erb, app/views/user_mailer/account_reinstated.html.erb, app/views/user_mailer/suspension_confirmed.html.erb, config/locales/mailer/en.yml, config/locales/mailer/es.yml, config/locales/mailer/fr.yml, config/locales/user_mailer/en.yml, config/locales/user_mailer/es.yml, config/locales/user_mailer/fr.yml, lib/action_account.rb, spec/lib/action_account_spec.rb, spec/mailers/previews/user_mailer_preview.rb, spec/mailers/user_mailer_spec.rb, spec/views/layouts/user_mailer.html.erb_spec.rb
[LG-11330](https://cm-jira.usa.gov/browse/LG-11330)
- Adds automated emails for reinstated users
- Adds new task to confirm suspension (just sends an email)
| email | screenshot |
| --- | ---- |
| reinstated |  <img width="583" alt="Screenshot 2023-11-01 at 10 45 23 AM" src="https://github.com/18F/identity-idp/assets/458784/614b72de-0783-4f71-8fcf-3be4822b7702"> |
| confirm suspension | <img width="586" alt="Screenshot 2023-11-01 at 10 45 31 AM" src="https://github.com/18F/identity-idp/assets/458784/0519a853-b2cc-4a2e-ac1c-cf1ceef153e3"> |
=> Add automated communication to account reinstatement (LG-11330)

lib/reporting/cloudwatch_client.rb
Bug report from @Sgtpluck in Slack
> ```
> WARNING: Your progress bar is currently at 3038 out of 3038 and cannot be incremented. In v2.0.0 this will become a ProgressBar::InvalidProgressError.
> ```
I am not able to repro this easily myself but I am nearly certain it's a multithreaded issue, so an easy way to manage this with with a mutex
=> Add mutex around cloudwatch client progress bar

app/jobs/reports/monthly_key_metrics_report.rb, spec/jobs/reports/monthly_key_metrics_report_spec.rb
- After changes in #9503 to make sending reports for the whole month easier, this updates the sending logic to check that for the last day of the month
=> Update Monthly Report email logic to match "yesterday" approach

lib/reporting/cloudwatch_client.rb, lib/reporting/monthly_proofing_report.rb, lib/reporting/proofing_rate_report.rb, spec/lib/reporting/monthly_proofing_report_spec.rb, spec/lib/reporting/proofing_rate_report_spec.rb
- Remove Thread#abort_on_exception and throw first error directly on main thread
- Disable Thread#report_on_exception because it adds a lot of noise to spec running
- Add handling to reports for rate limiting queries that show the errors being hit
=> Update error handling for Cloudwatch

app/helpers/application_helper.rb, app/views/layouts/base.html.erb, config/application.yml.default, lib/identity_config.rb, spec/views/layouts/application.html.erb_spec.rb
Gentler approach to #9447, so hopefully we do not have to rush patches like #9493 or #9521 because of user-facing 500s
=> Hide missing title errors from user

app/views/idv/hybrid_handoff/show.html.erb, spec/features/idv/doc_auth/hybrid_handoff_spec.rb, spec/support/matchers/accessibility.rb, spec/views/idv/hybrid_handoff/show.html.erb_spec.rb
[LG-11302](https://cm-jira.usa.gov/browse/LG-11302)
An accessibility report revealed that the two forms on this page have a
label of `""`. This is not great since they're both the same and empty.
This commit adds an aria label to them, which will make it more
accessible by adding the forms to the landmarks of the page.
<details>
</details>
<details>
</details>
Co-authored-by: John Maxwell <john.maxwell@gsa.gov>
Co-authored-by: Brittany Greaner <brittany.greaner@gsa.gov>
=> LG-11302: Add aria labels to forms on hybrid handoff page

Makefile, app/assets/stylesheets/_uswds.scss, app/components/icon_list_component.html.erb, app/components/icon_list_component.rb, app/components/icon_list_component.scss, app/components/icon_list_item_component.html.erb, app/components/process_list_component.rb, app/views/partials/multi_factor_authentication/_selected_mfa_option.html.erb, app/views/users/two_factor_authentication_setup/index.html.erb, spec/components/icon_list_component_spec.rb, spec/components/previews/icon_list_component_preview.rb
Adds a new `IconListComponent` component implementation.
**Why?**
- Improve developer experience in using a design system component
- Reduce size of main application stylesheet to improve performance
- As a refactoring ahead of planned revisions to consent screen to remove [ad-hoc icon list implementation](https://github.com/18F/identity-idp/blob/main/app/assets/stylesheets/components/_list.scss)
Repeat testing instructions from #8863 to verify no regressions in the display of "Your authentication methods".
See component preview:
- Review app: https://review-aduth-icon-a0jqga.review-app.identitysandbox.gov/components/inspect/icon_list/preview
- Local: http://localhost:3000/components/inspect/icon_list/preview
=> Add IconListComponent ViewComponent

app/jobs/reports/monthly_key_metrics_report.rb, app/services/reporting/total_user_count_report.rb, spec/services/reporting/total_user_count_report_spec.rb
[LG-11164](https://cm-jira.usa.gov/browse/LG-11164)
Updates total users count section of Monthly Key Metrics Report
- "New verified" means new since the last month
- "Annual" means fiscal year-to-date
- Shows "total users" and "verified users" for each of these
| before | after | 
| --- | --- |
|  <img width="611" alt="Screenshot 2023-11-02 at 3 54 37 PM" src="https://github.com/18F/identity-idp/assets/458784/b0fd002c-5b2a-4830-b6a2-962986a62053"> |  <img width="767" alt="Screenshot 2023-11-02 at 3 54 19 PM" src="https://github.com/18F/identity-idp/assets/458784/2cac1f5e-f8ed-423c-8f93-be37d0d66936"> |
=> Add "new verified users" to Monthly Key Metrics Report (LG-11164)

app/mailers/user_mailer.rb, spec/mailers/user_mailer_spec.rb
Fixes translation
| --- | --- |
|  <img width="583" alt="Screenshot 2023-11-03 at 10 22 18 AM" src="https://github.com/18F/identity-idp/assets/458784/ed5ebc0e-9219-43c2-9695-5743ea767da4"> |  <img width="590" alt="Screenshot 2023-11-03 at 10 33 27 AM" src="https://github.com/18F/identity-idp/assets/458784/49cea649-460c-44fe-b580-fa3849f25d1b"> |
=> Fix translation for email footer help text (account suspension)

lib/linters/analytics_event_name_linter.rb, spec/lib/linters/analytics_event_name_linter_spec.rb
As a slight alteration to #9480, exempts legacy methods by their actual names, not the expected name.
This was prompted by [a proposed change](https://github.com/18F/identity-idp/pull/9535/files#diff-d648e6f0a371a7ec4e80299f0a2a000d21e9789ad6601fb8351e7101b346e352L774-R834) which would have been permitted under the previous logic, but such renames are good opportunities to adopt the new naming convention.
1. Edit `app/services/analytics_events.rb` to rename any string event name
2. Run `rubocop app/services/analytics_events.rb`
3. Observe error
=> Lint analytics event exceptions on actual name

app/assets/stylesheets/tables-report.css.scss, app/jobs/reports/monthly_key_metrics_report.rb, spec/jobs/reports/monthly_key_metrics_report_spec.rb
[LG-11418](https://cm-jira.usa.gov/browse/LG-11418)
The email subject lines already have the environment name such as `[prod] Foobar report` however GMail likes to collapse multiple environments into the same thread.
This PR adds alert content to the body of the email so it's clearer without having to click into subject within a message in a GMail thread.
| note | screenshot |
|----| ---- |
| expected rendering |  <img width="627" alt="Screenshot 2023-11-03 at 12 05 05 PM" src="https://github.com/18F/identity-idp/assets/458784/7a0706ae-70d6-4f5d-8f13-5caa055c98bc"> |
| visual glitch when window is too wide |  <img width="713" alt="Screenshot 2023-11-03 at 12 05 14 PM" src="https://github.com/18F/identity-idp/assets/458784/96989801-48bc-4a7b-ac7d-1c138be08dac"> |
=> Add environment to the body of the monthly key metrics report (LG-11418)

config/environments/development.rb, config/environments/production.rb
Updates Lograge configuration to ignore the active session polling route introduced in #7966.
**Why?**
- Avoid referencing a controller action that doesn't exist (`'Users::SessionsController#active'` was removed in #7966)
- The presence of this configuration indicates we intended to ignore the session activity route from request logging, and the updated configuration value is the equivalent controller action
- ~This may actually do the thing that #7966 intended as far as avoiding a database query for the active session route, which ([as I discovered later](https://github.com/18F/identity-idp/pull/7966#issuecomment-1591165493)) wasn't happening as expected _**due to**_ Lograge-related behaviors applying to the route~ **Edit:** See note below. We're not quite there! **Edit 2:** See #9544 …
=> Update Lograge configuration to ignore active ping controller

app/controllers/concerns/ial2_profile_concern.rb, app/controllers/password_capture_controller.rb, app/controllers/users/sessions_controller.rb, app/services/idv/session.rb, app/services/reactivate_account_session.rb, spec/services/reactivate_account_session_spec.rb
This commit builds on #9509. That commit added the ability to write PII to the session under the profile ID associated with that PII.
This commit starts using the functionality added in that PR to start writing both the pending and active profile to the session. Additionally in places where PII is written to the session outside the context of password authentication the corresponding profile ID is passed to the PII cacher.
=> Start writing decrypted PII to the session based on profile ID

app/assets/stylesheets/tables-report.css.scss, app/jobs/reports/monthly_key_metrics_report.rb
In https://github.com/18F/identity-idp/pull/9538, we added an alert info box for non-production environments.
However, email clients don't have good support for SVG usually. A [previous workaround for IPP](https://github.com/18F/identity-idp/pull/6585#issuecomment-1187577858) re-did the alert component and linked an image, so this PR copies that approach and also links an image (PNG).
| --- | ---- |
|  <img width="385" alt="Screenshot 2023-11-06 at 8 17 44 AM" src="https://github.com/18F/identity-idp/assets/458784/49fb5083-32df-4795-a43e-dd73d77b2983"> |  <img width="378" alt="Screenshot 2023-11-06 at 9 26 41 AM" src="https://github.com/18F/identity-idp/assets/458784/e8d629c4-9296-4c80-9e58-ffc15f28e371">| 
| <img width="465" alt="Screenshot 2023-11-06 at 9 27 25 AM" …
=> Fix icon in report mailer email

app/javascript/packages/document-capture/context/acuant.tsx, app/javascript/packs/document-capture.tsx
https://cm-jira.usa.gov/browse/LG-11377
This is PR 2 of 3 that will meet the ACs of LG-11377
1. [#9536](https://github.com/18F/identity-idp/pull/9536) Add the feature flag
2. [#9546](https://github.com/18F/identity-idp/pull/9546) (this PR) Make `AcuantPassiveLiveness` available in the FE (loading the script).
4. (no PR yet) Add the selfie UI.
This PR loads the acuant passive liveness script when the feature flag is turned on. Otherwise the script is not loaded. More useful context is in [this Slack thread](https://gsa-tts.slack.com/archives/C056RD1NEHW/p1699036617111389).
Provide a checklist of steps to confirm the changes. Testing is dev only, since you have to force the feature flag on.
=> Add Selfie to FE: Conditional Passiveliveness Script Load

app/controllers/idv/unavailable_controller.rb, app/controllers/idv/welcome_controller.rb, app/services/outage_status.rb, config/application.yml.default, lib/identity_config.rb, spec/controllers/idv/unavailable_controller_spec.rb, spec/features/idv/outage_spec.rb, spec/services/outage_status_spec.rb
[LG-11306](https://cm-jira.usa.gov/browse/LG-11306)
- Redo of #4202 after it was removed in #8858, to fit with current vendor maintenance configuration
**Background**: We have some upcoming IDV vendor unavailability this weekend, this lets us schedule maintenance without having to manually set configs
=> Bring back scheduled IDV maintenance (LG-11306)

app/javascript/packages/document-capture/components/document-capture-not-ready.tsx, app/javascript/packages/document-capture/components/document-capture-review-issues.tsx, app/javascript/packages/document-capture/components/documents-step.jsx, app/javascript/packages/document-capture/context/feature-flag.tsx, app/javascript/packages/document-capture/context/index.ts, app/javascript/packages/document-capture/context/ui-config.tsx, app/javascript/packs/document-capture.tsx, app/views/idv/shared/_document_capture.html.erb, config/application.yml.default, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, lib/identity_config.rb, spec/features/idv/doc_auth/document_capture_spec.rb, spec/javascript/packages/document-capture/components/document-capture-not-ready-spec.tsx, spec/javascript/packages/document-capture/components/documents-step-spec.jsx
[LG-11260](https://cm-jira.usa.gov/browse/LG-11260): "I'm not ready" experience
Add a section of UI for user not ready to upload photo on capture screen, links to exit to service provider or account page.
Also a add flag to control rendering of this UI block.
<details>
<summary>Without SP:</summary>
English:
Spanish
French:
</details>
<details>
<summary>With SP:</summary>
English:
Spanish:
French:
</details>
=> LG-11260: docauth not ready

app/services/browser_support.rb, spec/services/browser_support_spec.rb, yarn.lock
Enhances `BrowserSupport` to account for Android WebViews.
Previously, WebView user agents were often parsed as "Chrome", and would satisfy constraints for Chrome browser support. However, actual support in these WebView browsers would differ from the native Chrome browser. Since we were not treating these as "unsupported", we were seeing many errors being reported to our frontend error logger from webviews.
Updating the browserslist database also has the effect of including an Android minimum version (119).
The expected result here is that this will silence errors we're seeing from older WebView browsers.
Verify new browser support includes Android target:
1. `make browsers.json`
2. Observe "android 119" exists in `browsers.json`
Run BrowserSupport tests:
```
rspec …
```
=> Support Android WebView for browser support detection

docs/local-development.md
Adds documentation for how to use one of the available sample applications to simulate a true end-to-end user experience.
It occurred to me by the comment at https://github.com/18F/identity-idp/pull/9506#pullrequestreview-1718375702 that we currently have no documentation about this within this repository.
Follow the documented steps to see if you're able to get a partner authentication going.
=> Add documentation for sample applications

app/views/idv/in_person/verify_info/show.html.erb, app/views/idv/verify_info/show.html.erb, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml, spec/features/idv/doc_auth/redo_document_capture_spec.rb, spec/features/idv/doc_auth/verify_info_step_spec.rb, spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb, spec/features/idv/steps/in_person/verify_info_spec.rb, spec/features/idv/threat_metrix_pending_spec.rb, spec/support/features/doc_auth_helper.rb, spec/support/features/idv_helper.rb, spec/support/features/in_person_helper.rb
[LG-11383](https://cm-jira.usa.gov/browse/LG-11383)
We are updating the Verify Info screen to clarify the purpose of the screen.
<details>
</details>
<details>
</details>
=> LG-11383 Update Verify Info Screen

config/application.yml.default
Does what it says on the tin. The key was perhaps mistakenly re-added in #7228 after being removed in #7233.
=> Remove unused key_pair_generation_percent configuration key

app/controllers/idv/enter_password_controller.rb, app/services/analytics_events.rb, app/services/idv/analytics_events_enhancer.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/features/idv/analytics_spec.rb
[LG-11185](https://cm-jira.usa.gov/browse/LG-11185)
Old event names:
`IdV: review info visited`
`IdV: review complete`
The new event names now align with our typical scheme, based on the controller name:
`IdV: enter password visited`
`IdV: enter password submitted`
[This PR in the devops repo ](https://github.com/18F/identity-devops/pull/6789)carries these event names into existing dashboards/funnels.
=> fLG-11185 Rename review events to enter password

lib/linters/errors_add_linter.rb, spec/lib/linters/errors_add_linter_spec.rb
Enhances our `errors.add` linter to allow the expected `type` symbol to be specified as the second argument of the `errors.add` call.
The context for this linter is that we want to have a way to query for errors within logs irrespective of locale, and having a symbol "type" supports this, and it's expected to be logged through the `error_details` property.
Example:
https://github.com/18F/identity-idp/blob/99916caf4f66f443a075cc152cdf3fdcd8348006/spec/services/form_response_spec.rb#L141-L153
In fact, due to an issue with `FormResponse`, _only_ this form of `errors.add` currently works as expected. See #9570 for a pull request fixing that behavior.
Build should have no failures.
=> Enhance errors.add linter to check symbol as second argument

config/application.yml.default, config/initializers/content_security_policy.rb, lib/identity_config.rb
Removes the `disable_csp_unsafe_inline` configuration.
**Why?**
- It does not appear to be used
- It adds unnecessary risk to have a configuration responsible for controlling a security feature which requires a lot of mental gymnastics to navigate the negation and expected impact of the value (a value of "true" means "disabling" which means "not adding the exemption" which means "enforcement applies")
Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1699554919541029
Observe that CSP is unimpacted.
Build should pass.
=> Remove disable_csp_unsafe_inline configuration

docs/frontend.md
Includes TypeScript types in the naming conventions guidance.
This is meant to cover naming of `interface`s, `type`s, and `enum`s (and perhaps others?)
Examples:
https://github.com/18F/identity-idp/blob/71b5a2be9837de48f9676da6d7b25d59cd42dded/app/javascript/packages/i18n/index.ts#L1
https://github.com/18F/identity-idp/blob/71b5a2be9837de48f9676da6d7b25d59cd42dded/app/javascript/packages/i18n/index.ts#L6
https://github.com/18F/identity-idp/blob/71b5a2be9837de48f9676da6d7b25d59cd42dded/app/javascript/packages/memorable-date/index.ts#L5
Extracted from #9564
Review updated guidance and confirm that it promotes expected conventions.
=> Include TypeScript types in frontend naming conventions

app/views/idv/by_mail/enter_code/index.html.erb, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml, spec/features/idv/steps/enter_code_step_spec.rb
[LG-11343](https://cm-jira.usa.gov/browse/LG-11343)
Removes the alert banner telling users the one-time code is now called verification code. Enough time has passed that any letters sent with the "one-time code" language have expired.
<details>
</details>
<details>
</details>
=> LG-11343: removes a no longer needed alert banner

.gitlab-ci.yml, config/initializers/unused_identity_config_keys.rb, lib/identity_config.rb, spec/lib/identity_config_spec.rb
A small follow-up to #9566 to print out one class of unused configuration keys. This is specifically aimed at keys that are not defined in the configuration management, but are still defined in the configuration file. It is very likely this will find unused keys in deployed environments.
It would be better to log this to the log file, but logging is not set up at this point and in the interest of having a partial solution, I think this is an alright start.
```
$ rails s
WARNING: There are defined configuration keys that are not loaded by the application. They are: [:disable_csp_unsafe_inline]
=> Booting Puma
=> Rails 7.1.1 application starting in development
```
=> Warn if there are configuration keys in the configuration file that are not loaded by the configuration store

lib/analytics_events_documenter.rb, spec/lib/analytics_events_documenter_spec.rb
**Why**: The regex got tripped up by a method call on multiple lines
See screenshot below, `idv_enter_password_submitted` got parsed as:
```
name: "idv_enter_password_submitted,\n    success: success,\n    deactivation_reason: deactivation_reason,\n    fraud_review_pending: fraud_review_pending,\n    gpo_verification_pending: gpo_verification_pending,\n    in_person_verification_pending: in_person_verification_pending,\n    fraud_rejection: fraud_rejection,\n    proofing_components: proofing_components,\n    **extra,\n  ",
```
| screenshot |
| --- |
|  <img width="680" alt="Screenshot 2023-11-13 at 9 13 39 AM" src="https://github.com/18F/identity-idp/assets/458784/970bbad5-87dc-4882-858d-839dfa3f1205"> |
=> Fix AnalyticsEventsDocumenter for symbol event names

app/javascript/packages/document-capture/components/document-capture-review-issues.tsx, app/javascript/packages/document-capture/components/documents-step.jsx, app/javascript/packages/document-capture/context/feature-flag.tsx, app/javascript/packs/document-capture.tsx, app/views/idv/shared/_document_capture.html.erb, config/application.yml.default, lib/identity_config.rb, spec/features/idv/doc_auth/document_capture_spec.rb, spec/javascript/packages/document-capture/components/document-capture-review-issues-spec.jsx, spec/javascript/packages/document-capture/components/documents-step-spec.jsx, spec/javascript/packages/document-capture/components/review-issues-step-spec.jsx
[LG-11442](https://cm-jira.usa.gov/browse/LG-11442): feature flag for additional ID exit question.
Feature flag for doc auth additional ID exit questions.
=> LG-11442: exit question flag

app/controllers/idv_controller.rb, spec/controllers/idv_controller_spec.rb
[LG-11464](https://cm-jira.usa.gov/browse/LG-11464)
If the user navigates to the `/verify/activated` URL but still have a `personal_key` in their `idv_session` (meaning they have not yet acknowledged it), redirect them back to the personal key page so they can acknowledge it.
=> LG-11464: Redirect /verify/activated to personal key page if unackowledged

app/jobs/gpo_expiration_job.rb, lib/tasks/backfill_gpo_expiration.rake, spec/jobs/gpo_expiration_job_spec.rb
I ran into some issues with Postgres statement timeouts when attempting to run the GPO expiration rake task I wrote in #9545. So I took the opportunity to clean up a few things, including:
- Make the rake task invoke the job's `.perform` method directly rather than duplicating the loop that the job runs in the rake task itself
- Add a configurable statement timeout so I can tweak it without needing a deploy
- Note earliest + latest timestamps found in rake task output
=> Tweaks to GPO expiration job + rake task

lib/env_irb_prompt.rb, spec/lib/env_irb_prompt_spec.rb
Follow-up to #9585. Open to suggestions on what color things should be! The only one I feel strongly about is that prod is red.
| screenshot | 
| --- |
|  <img width="285" alt="Screenshot 2023-11-14 at 2 00 36 PM" src="https://github.com/18F/identity-idp/assets/458784/b45ec4cc-1217-4fca-9eb0-b40df3e978af"> |
=> Color IRB prompts based on environment

app/javascript/packages/document-capture/components/document-capture-not-ready.tsx, app/javascript/packages/verify-flow/cancel.spec.tsx, app/javascript/packages/verify-flow/context/flow-context.tsx, app/javascript/packs/document-capture.tsx, app/views/idv/shared/_document_capture.html.erb, spec/javascript/packages/document-capture/components/document-capture-not-ready-spec.tsx
[LG-11260](https://cm-jira.usa.gov/browse/LG-11260): Fix account url, language preference.
Not ready section cancel link should keep language preference.
=> LG-11260: Not ready section fix

app/presenters/openid_connect_user_info_presenter.rb, app/services/out_of_band_session_accessor.rb, spec/controllers/openid_connect/user_info_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/forms/openid_connect_token_form_spec.rb, spec/models/user_spec.rb, spec/presenters/openid_connect_user_info_presenter_spec.rb, spec/requests/openid_connect_userinfo_spec.rb, spec/services/access_token_verifier_spec.rb, spec/services/id_token_builder_spec.rb, spec/services/out_of_band_session_accessor_spec.rb
In #9509 we added the ability to specify which profile to fetch PII from when reading PII from the session.
This commit applies that capability to the OpenID Connect UserInfo endpoint to ensure that only the active profile's PII is used there.
The user info endpoint is used by service providers to access PII after auth. As a result it is not a request made by users and does not have a user session. To read PII we use the out-of-band session accessor's `#load_pii` method. This commit adds a `profile_id` arg to that method and passes in the active profile's ID when reading PII.
=> LG-11537 Access the active profile in the userinfo endpoint

app/controllers/sign_up/completions_controller.rb
In #9509 we added the ability to specify which profile to fetch PII from when reading PII from the session.
This commit uses the active profile's ID to fetch PII on the completions screen. The completions screen should always be showing PII of the active profile.
=> LG-11538 Show the PII from the active profile on the completions screen

app/controllers/concerns/idv_step_concern.rb, app/controllers/idv/agreement_controller.rb, app/controllers/idv/document_capture_controller.rb, app/controllers/idv/how_to_verify_controller.rb, app/controllers/idv/hybrid_handoff_controller.rb, app/controllers/idv/link_sent_controller.rb, app/controllers/idv/phone_question_controller.rb, app/controllers/idv/welcome_controller.rb, app/policies/idv/flow_policy.rb, app/policies/idv/step_info.rb, app/services/idv/session.rb, spec/controllers/idv/agreement_controller_spec.rb, spec/controllers/idv/document_capture_controller_spec.rb, spec/controllers/idv/how_to_verify_controller_spec.rb, spec/controllers/idv/hybrid_handoff_controller_spec.rb, spec/controllers/idv/link_sent_controller_spec.rb, spec/controllers/idv/phone_question_controller_spec.rb, spec/controllers/idv/welcome_controller_spec.rb, spec/features/idv/doc_auth/redo_document_capture_spec.rb, spec/features/idv/end_to_end_idv_spec.rb, spec/policies/idv/flow_policy_spec.rb, spec/policies/idv/step_info_spec.rb
[LG-11461](https://cm-jira.usa.gov/browse/LG-11461)
This is an addition to  #9589 to invalidate future steps when a user uses the back button and submits a previous step. We added the new call to `#update` for welcome, agreement, link_sent, hybrid_handoff, how_to_verify, phone_question, and document_capture.
Each step_info now has an undo_step parameter which is a proc that unsets whatever the current step sets. 
FlowPolicy has a new method, `undo_steps_from!` which recursively undoes all of the next steps after the current step.
IdvStepConcern has a new helper method `clear_invalid_steps!` that should be called at the beginning of the #update method of each IdV controller that allows the back button.
=> LG-11461 add FlowPolicy#undo_steps_from! and add to #update through document capture

app/controllers/idv/personal_key_controller.rb, app/services/idv/session.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/services/idv/session_spec.rb
We currently track that the user has viewed / acknowledged their personal key in a couple of ways:
1. If `user_session[:need_personal_key_confirmation] == true`, we know they _have not_ acknowledged their personal key
2. If user has a profile, but `idv_session.personal_key` is blank, then they _probably_ acknowledged their personal key
This PR:
- Adds an `acknowledge_personal_key!` method to `idv_session`
- Updates the personal key controller to call that method
- Adds `personal_key_acknowledged` flag to `idv_session`
(The ultimate goal will be to unify the tracking of personal key acknowledgement in `idv_session`, but there are 50/50 deployment considerations that mean this PR needs to go out first.)
=> Start writing idv_session.personal_key_acknowledged

app/services/out_of_band_session_accessor.rb, spec/controllers/saml_idp_controller_spec.rb, spec/models/user_spec.rb, spec/presenters/openid_connect_user_info_presenter_spec.rb, spec/services/access_token_verifier_spec.rb, spec/services/out_of_band_session_accessor_spec.rb
This reverts commit 8240c4bd63e6db3f553587425f54872db4e497dd (an accidental solo commit)
=> Revert "Switch put_pii to keyword arguments"

app/services/out_of_band_session_accessor.rb, spec/controllers/saml_idp_controller_spec.rb, spec/models/user_spec.rb, spec/presenters/openid_connect_user_info_presenter_spec.rb, spec/services/access_token_verifier_spec.rb, spec/services/out_of_band_session_accessor_spec.rb
Implementing my own post-hoc suggestion in previous PR https://github.com/18f/identity-idp/pull/9596#discussion_r1394530601
**Why**: Provides additional clarity, makes it harder to mix up than ordered arguments
(peer-reviewed version of 8240c4bd63e6db3f553587425f54872db4e497dd, which was reverted in #9604)
=> Switch put_pii to keyword arguments

app/controllers/two_factor_authentication/personal_key_verification_controller.rb, app/services/analytics_events.rb
The `PersonalKeyVerificationController` is used to verify a personal key as an MFA method and allow a user to sign in. When this is done a new personal key is issued.
This controller had code for re-encrypting the users profile with the newly issued personal key. However, a user with an active profile was never able to reach this path. The `check_personal_key_enabled` calls `TwoFactorAuthentication::PersonalKeyPolicy#enabled?`. This method returns false if the user has any profiles.
Since this code path is unreachable this commit removes it.
I was not able to find any tests covering this re-encryption behavior.
=> LG-11553 Remove recovery PII re-encryption from `PersonalKeyVerificationController`

app/controllers/application_controller.rb
In #9509 we added the ability to specify which profile to fetch PII from when reading PII from the session.
This commit uses the active profiles PII when encrypting recovery PII for the active profile when the active profile has a broken personal key.
=> LG-11534 Load the active profile from the session on broken personal key

app/controllers/users/webauthn_setup_controller.rb, spec/controllers/users/webauthn_setup_controller_spec.rb
[LG-11432](https://cm-jira.usa.gov/browse/LG-11432)
Adds a check in the `new` method so that if the user is in the account creation flow and has already set a platform authenticator to redirect them to the authentication methods setup page.
=> LG 11432 Prevent duplicate F/T setup if user hits back button on second MFA prompt

app/forms/webauthn_verification_form.rb, app/services/analytics_events.rb, spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb, spec/forms/webauthn_verification_form_spec.rb
Related to [LG-11399](https://cm-jira.usa.gov/browse/LG-11399)
This adds a new property `frontend_error` to unsuccessful WebAuthn sign-ins. 
While it doesn't appear this property is actively used in any dashboards, the availability of this value inadvertently regressed as part of #9572, which previously logged the specific error name as part of the `error_details` property. 
An alternative implementation could try to incorporate this as the "type" of the error detail, but the case mismatch between e.g. incoming `NotAllowedError` and expected detail type formatting of `not_allowed_error` could create some confusion.
1. (Prerequisite) Have an account with Security Key or Face or Touch Unlock as an associated MFA
2. Run `make watch_events` in a separate terminal process
3. Go to …
=> Add analytics property for WebAuthn sign-in frontend error

app/forms/webauthn_verification_form.rb, spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb, spec/forms/webauthn_verification_form_spec.rb
Builds upon #9572, #9611, and #9613
Uses [ActiveRecord's built-in `absence` validator](https://guides.rubyonrails.org/active_record_validations.html#absence) to validate `webauthn_error`, in place of our ad-hoc validator.
**Why?**
- No need to reinvent the wheel
- More relevant error type descriptor of "present" vs. "webauthn_error"
- Since we're already adjusting `error_details` structure in next RC release, this is a good opportunity to make these sorts of revisions
Repeat testing plan from #9611, observing in event logs: `error_details: { webauthn_error: { present: true } }`
=> Use ActiveRecord built-in validator for WebAuthn error validation

app/javascript/packs/webauthn-setup.ts, package.json, yarn.lock
Update Prettier to v3.1
**Why?**
- Avoid future maintenance burden of version drift
`yarn lint` passes
=> Update Prettier to v3.1

config/initializers/rack_attack.rb, spec/requests/rack_attack_spec.rb
This PR adds the `sp` argument when constructing analytics for the RackAttack `rate_limit_triggered` event.
=> Log service_provider for RackAttack events

config/initializers/job_configurations.rb
[LG-11520](https://cm-jira.usa.gov/browse/LG-11520)
Start running [`GpoExpirationJob`](https://github.com/18F/identity-idp/blob/main/app/jobs/gpo_expiration_job.rb) daily to expire old GPO profiles. See #9545 for more information.
=> LG-11520: Enable daily GPO expiration job

app/javascript/packages/stylelint-config/CHANGELOG.md, app/javascript/packages/stylelint-config/package.json, yarn.lock
Updates dependencies for `@18f/identity-stylelint-config` to prepare to a new published release, in order to support intended usage at https://github.com/18F/identity-site/pull/1082 .
`yarn lint:css` passes
=> Update Stylelint config dependencies in preparation for release publish

app/controllers/frontend_log_controller.rb, app/javascript/packages/analytics/README.md, app/javascript/packages/phone-input/index.spec.ts, app/javascript/packages/phone-input/index.ts, app/services/analytics_events.rb, docs/frontend.md, spec/controllers/frontend_log_controller_spec.rb
[LG-11435](https://cm-jira.usa.gov/browse/LG-11435)
Tracks an analytics event when the selected country is changed in the frontend phone input element.
3. Complete account creation up to MFA selection screen
4. Choose phone as MFA method
5. In a separate process, run `make watch_events` to observe event logging
6. Enter an international phone number by whichever means you want (type, paste, change dropdown, etc)
7. Observe event logged "phone_input_country_changed" once for each time you changed country, with correct `country_code` property
=> LG-11435: Track frontend analytics for changed country in phone input

app/javascript/packages/normalize-yaml/CHANGELOG.md, app/javascript/packages/normalize-yaml/package.json, app/javascript/packages/rails-i18n-webpack-plugin/package.json, yarn.lock
Updates dependencies and version of `@18f/identity-normalize-yaml` in preparation for publishing to NPM.
Supports https://github.com/18F/identity-site/pull/1082, related to #9619.
`make normalize_yaml` passes.
=> Prepare publish normalize-yaml to NPM

app/controllers/idv/how_to_verify_controller.rb, spec/controllers/idv/how_to_verify_controller_spec.rb
[LG-11439](https://cm-jira.usa.gov/browse/LG-11439)
On how to verify page check that agreement step has been completed. If it hasn't the user will now be redirected back to the agreement page. 
=> LG-11439 Opt-in IPP: redirect if agreement step not completed

app/components/webauthn_verify_button_component.html.erb, app/controllers/two_factor_authentication/webauthn_verification_controller.rb, app/forms/webauthn_verification_form.rb, app/javascript/packages/webauthn/is-expected-error.spec.ts, app/javascript/packages/webauthn/is-expected-error.ts, app/javascript/packages/webauthn/is-user-verification-screen-lock-error.spec.ts, app/javascript/packages/webauthn/is-user-verification-screen-lock-error.ts, app/javascript/packages/webauthn/webauthn-verify-button-element.spec.ts, app/javascript/packages/webauthn/webauthn-verify-button-element.ts, config/locales/two_factor_authentication/en.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml, spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb, spec/forms/webauthn_verification_form_spec.rb
[LG-11399](https://cm-jira.usa.gov/browse/LG-11399), and somewhat related to [LG-11135](https://cm-jira.usa.gov/browse/LG-11135) in terms of form error refactoring
Updates error handling for Face or Touch Unlock sign-in to show a specific error message when the browser produces an error informing us that the user is attempting to sign in on a device ineligible due to lack of screen lock for the `userVerification` requirement of authentication.
Note that this error is specific to Chrome, is not a behavior described anywhere in [the relevant WebAuthn specification](https://www.w3.org/TR/webauthn-3/), and could change at any point. See the [related Slack discussion on this point](https://gsa-tts.slack.com/archives/C01710KMYUB/p1699390502877849), but the consensus is that we should still want …
=> LG-11399: Show Face/Touch message for screen lock error

app/assets/stylesheets/components/_btn.scss
[LG-11639](https://cm-jira.usa.gov/browse/LG-11639), [LG-11640](https://cm-jira.usa.gov/browse/LG-11640)
Fixes an issue where unstyled buttons can appear as vertically stacked at smaller viewport sizes.
Regressed in #9478, due to inaccurate DevTools recommendation.
This should ideally be a default style of USWDS. See upstream pull request at https://github.com/uswds/uswds/pull/5631.
Verify that in affected screens, buttons appear as inline at small viewport sizes.
1. Go to http://localhost:300
3. Enter an email address
4. Check Rules of Use
5. Click Submit
6. In "Check your email screen", observe button appears as inline to text.
---|---|---
Email Confirmation|![button-email-before](https://github.com/18F/identity-idp/assets/1779930/70cb3780 …
=> Restore width collapse for unstyled buttons

app/forms/otp_verification_form.rb, spec/forms/otp_verification_form_spec.rb
Removes an unused reference to "otp_code" as a `multi_factor_auth_method` value, in order to avoid confusion for a value that's never logged.
I stumbled across this when searching possible `multi_factor_auth_method` values in the codebase. After verifying there are no results in CloudWatch for `filter properties.event_properties.multi_factor_auth_method = 'otp_code'`, I noticed that this would be unused, due to how the form's extra analytics are overridden:
https://github.com/18F/identity-idp/blob/fb94aadf8d526f02a725df9a8a9f5721fbb87e75/app/controllers/two_factor_authentication/otp_verification_controller.rb#L129
https://github.com/18F/identity-idp/blob/fb94aadf8d526f02a725df9a8a9f5721fbb87e75/app/controllers/two_factor_authentication/otp_verification_controller.rb#L151-L156
This is a …
=> Remove unreachable "otp_code" auth method

app/controllers/concerns/idv_step_concern.rb, app/controllers/idv/by_mail/enter_code_controller.rb, app/controllers/idv/by_mail/request_letter_controller.rb, spec/controllers/concerns/idv_step_concern_spec.rb, spec/features/idv/end_to_end_idv_spec.rb, spec/features/idv/steps/request_letter_step_spec.rb, spec/support/features/doc_auth_helper.rb
[LG-11230](https://cm-jira.usa.gov/browse/LG-11230)
If a user recently requested a letter and reached the letter enqueued page if they pressed the back button they would be taken to the the Enter Code screen. We want them to only reach the enter code screen once they get a letter or start a new session so this redirects them back to the letter enqueued screen.
=> LG-11230 Redirect browser back button to “your letter is on the way”

app/presenters/two_factor_login_options_presenter.rb, config/locales/two_factor_authentication/en.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml, spec/presenters/two_factor_login_options_presenter_spec.rb, spec/views/two_factor_authentication/options/index.html.erb_spec.rb
[LG-11287](https://cm-jira.usa.gov/browse/LG-11287)
Changes content at the page `/login/two_factor/options` when the reauthentication window expires.
=> LG-11287: Update reauthentication page

config/application.yml.default, lib/identity_config.rb
[LG-11569](https://cm-jira.usa.gov/browse/LG-11569)
Adding a feature flag to control whether users see the horizontal or vertical version of the SDK. This change just sets up the feature flag for future work.
I used this format for the flag because we want to be able to split the
number of users who see horizontal or vertical.
<details>
</details>
<details>
</details>
=> LG-11569: Add feature flag for reorienting SDK capture

app/services/doc_auth/lexis_nexis/requests/true_id_request.rb, spec/services/doc_auth/lexis_nexis/requests/true_id_request_spec.rb
[LG-11395](https://cm-jira.usa.gov/browse/LG-11395)
Fix agument order when instantiating TrueIDResponse
=> LG-11395 trueid response argument fix

app/jobs/gpo_expiration_job.rb, spec/jobs/gpo_expiration_job_spec.rb
`GpoExpirationJob`, added in #9545 and enabled in #9622, is [raising a `NoMethodError`](https://onenr.io/08jqZ7LexQl) when it's  run via good_job. This is due to the initializer missing a `super` call.
This PR removes the `initialize` method.
=> Remove GpoExpirationJob::initialize

app/javascript/packages/build-sass/CHANGELOG.md, app/javascript/packages/build-sass/cli.js, app/javascript/packages/build-sass/package.json, yarn.lock
Updates `@18f/identity-build-sass` to use the native [Node.js `util.parseArgs`](https://nodejs.org/api/util.html#utilparseargsconfig) in place of the third-party package polyfill.
This is a public, published package, so there is a consideration of downstream impact of using a feature in a newer version of Node.js. However, since this package is largely for internal projects, and the feature has been supported since 2 LTS releases, I think it's reasonable to drop support for Node.js v16 and older.
The benefit is largely in reducing download size and vulnerability surface area incurred through use of third-party packages.
Observe no regressions in building CSS:
```
make run
```
2. Observe no visual regressions
=> build-sass: Use native Node.js parseArgs utility

app/controllers/concerns/idv_session.rb, spec/controllers/idv/by_mail/request_letter_controller_spec.rb, spec/controllers/idv/cancellations_controller_spec.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/controllers/idv/forgot_password_controller_spec.rb, spec/controllers/idv/otp_verification_controller_spec.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/controllers/idv/phone_controller_spec.rb, spec/controllers/idv/phone_errors_controller_spec.rb, spec/controllers/idv/resend_otp_controller_spec.rb, spec/controllers/idv/session_errors_controller_spec.rb, spec/controllers/idv_controller_spec.rb
In #4634 we restricted the identity verification process to require a service provider for a user to undergo proofing. This commit added other features like a `idv_sp_required` for configuring this behavior to be enabled or disabled. This change  required an SP to be present but did not require the SP to actually request verification.
This commit changes the code so that `IalContext` is invoked to check if verification was in fact requested. This way users can't go to an SP that does not require verification and start the verification process by navigating to `/verify`.
=> Modify the SP requirement for IdV to require the SP to request verification

app/controllers/two_factor_authentication/sms_opt_in_controller.rb, app/presenters/two_factor_auth_code/sms_opt_in_presenter.rb, app/views/two_factor_authentication/sms_opt_in/error.html.erb, app/views/two_factor_authentication/sms_opt_in/new.html.erb, config/locales/links/en.yml, config/locales/links/es.yml, config/locales/links/fr.yml, config/locales/two_factor_authentication/en.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml, spec/controllers/two_factor_authentication/sms_opt_in_controller_spec.rb, spec/features/two_factor_authentication/sign_in_spec.rb, spec/presenters/two_factor_auth_code/sms_opt_in_presenter_spec.rb, spec/views/two_factor_authentication/sms_opt_in/error.html.erb_spec.rb, spec/views/two_factor_authentication/sms_opt_in/new.html.erb_spec.rb
[LG-11517](https://cm-jira.usa.gov/browse/LG-11517)
Updates the SMS opt-in screen to show the troubleshooting options module, always allowing a user to return to "Choose another authentication method" even if they don't have another MFA option available, so that the user can choose to reset (delete) their account if that's their only recourse.
2. Create a new account
3. Add phone as only MFA method
4. Once you complete account creation and reach sign-in page, click "Forget all browsers" and confirm
5. Sign out
6. Sign in
7. Opt-out of SMS
- Simulate this in local development by entering the following into a `rails console` session:
```
PhoneNumberOptOut.create_or_find_with_phone(PhoneFormatter.format('+1 555-555-5555')) # swap with phone
```
- To undo this …
=> LG-11517: Always show "Use another method" option in SMS opt-in

app/controllers/concerns/saml_idp_auth_concern.rb
[LG-11536](https://cm-jira.usa.gov/browse/LG-11536)
For a user signing in from a service provider using  SAML we want to send the active profile pii from the IDP. This commit does this.
=> LG-11536 Use the correct PII in the session for the SAML handoff

spec/controllers/idv/personal_key_controller_spec.rb, spec/support/controller_helper.rb
I am doing some work on PersonalKeyController and found myself needing to restructure this spec a little bit. So here's that restructure in its own PR!
I did a few things in here, including:
- Removed the `stub_idv_session` method in favor of `let` and `before` hooks
- Added `:mint_profile_from_idv_session` let that tests can use to opt out of automatically tying a profile to their idv_session.
- Moved as much `idv_session` twiddling as possible into the main `before` hook
- Removed anything that sets `idv_session.profile_id` directly
- Tried to clarify _which_ profile any given test is checking
=> Refactor PersonalKeyController spec

app/jobs/reports/monthly_key_metrics_report.rb, app/services/reporting/active_users_count_report.rb, config/initializers/job_configurations.rb, spec/services/reporting/active_users_count_report_spec.rb
[LG-11703](https://cm-jira.usa.gov/browse/LG-11703)
Updates the active users count so that the "now" or the end time is fixed. This means we can:
1.  consistently re-run old reports
2. have less skew between generating multiple rows of the report while live data is still being added (problem observed in the ticket)
| --- | ---- |
|  <img width="685" alt="Screenshot 2023-11-28 at 12 37 49 PM" src="https://github.com/18F/identity-idp/assets/458784/5252b275-ebe5-427e-8ec5-7e778a279547"> |   <img width="685" alt="Screenshot 2023-11-28 at 12 37 27 PM" src="https://github.com/18F/identity-idp/assets/458784/15156c4a-ab68-437b-8dd0-04f0af88aa06"> |
=> Pin "now" in the active users report (LG-11703)

deploy/migrate
The database seed task handles a lot more than the readonly_access task and the seed task is allowed to fail. This change moves the readonly_access before the seed task, so that we can more reliably set readonly permissions.
Prompted by the issues in this [Slack thread](https://gsa-tts.slack.com/archives/C0NGESUN5/p1700491992907039).
=> Re-order database migration tasks to run seed last and ensure grant_readonly_access runs

config/locales/forms/en.yml, config/locales/forms/es.yml, config/locales/forms/fr.yml
[LG-11479](https://cm-jira.usa.gov/browse/LG-11479)
Revision to translated text for Backup code label. From 'Security code' to 'Backup code'
Before:
After:
=> LG 11479 relabel form field to Backup code

spec/features/idv/doc_auth/document_capture_spec.rb, spec/support/features/document_capture_step_helper.rb
[LG-11670](https://cm-jira.usa.gov/browse/LG-11670)
Adding a small feature test for the selfie flow, now that we have a selfie back end and front end.
This ticket was more about manual testing and writing tickets and less about changing code, but I did find myself writing this test as part of the work, and figured it might be worth keeping.
Given the tests that were added in https://github.com/18F/identity-idp/pull/9561 and https://github.com/18F/identity-idp/pull/9676, I also wasn't able to come up with many other tests that might be needed. It seems like maybe there's another place for a front / back end integration spec that I'm missing. I'm open to feedback if folks think there are other tests that might be needed.
=> LG-11670: Add small feature test for selfie flow

config/environments/test.rb
Fixes the following deprecation:
```
DEPRECATION WARNING: Setting action_dispatch.show_exceptions to false is deprecated. Set to :none instead. (called from call_with_excludes at /builds/lg/identity-idp/config/initializers/rack_timeout.rb:22)
```
=> Update deprecated action_dispatch test option

app/controllers/idv/otp_verification_controller.rb, app/controllers/idv/phone_controller.rb, app/services/idv/phone_step.rb, app/services/idv/session.rb, spec/controllers/idv/phone_controller_spec.rb
[LG-11463](https://cm-jira.usa.gov/browse/LG-11463)
Add idv_session methods to mark phone step started (user passed lexis_nexis in phone_controller), mark it complete (user entered correct code in otp_verification_controller) and mark it invalid (user just submitted request for a code, starting background job to query lexis_nexis).
We mark the phone step invalid at the beginning of create to follow the same pattern as the verify_info_controllers. We clear prior attempts at the beginning, and then the background job marks the step complete when it succeeds.
=> LG-11463 idv_session methods for phone step started, complete, invalid

app/jobs/reports/monthly_key_metrics_report.rb, spec/jobs/reports/monthly_key_metrics_report_spec.rb, spec/mailers/previews/report_mailer_preview.rb
Fixes a small regression due to switching around the  timestamps in #9672
| --- | --- |
|  <img width="507" alt="Screenshot 2023-12-01 at 10 58 42 AM" src="https://github.com/18F/identity-idp/assets/458784/ce8ea727-238a-4f4d-ac6f-1e1b759feb61"> |  <img width="417" alt="Screenshot 2023-12-01 at 10 57 32 AM" src="https://github.com/18F/identity-idp/assets/458784/ecff37d1-416c-4e75-97e9-49a5cdf7a4df"> |
=> Fix Monthly Key Metrics report email subject

app/services/reactivate_account_session.rb, spec/services/reactivate_account_session_spec.rb
[LG-11548](https://cm-jira.usa.gov/browse/LG-11548)
- Changed call to `Pii::Cacher#fetch` to use the `password_reset_profile` id.
- Added controller specs to verify that behavior
- Verified via debug logging that the feature spec for recovery with a personal key uses the correct profile id.
Code block to be added to `Pii::Cacher#fetch` for testing:
```
logger.debug "Pii::Cacher#fetch(#{profile_id.inspect})"
```
=> Made `ReactivateAccountSession#decrypted_pii` use the `password_reset_profile` id when fetching Pii

CONTRIBUTING.md, scripts/changelog_check.rb, spec/fixtures/git_log_changelog.yml, spec/scripts/changelog_check_spec.rb
Updates changelog script to support use of more symbols in subcategories. Previously, this was limited to `\w -` (most alphanumeric, underscore, dash, and spaces). The current logic allows for everything other than commas.
Related Slack conversation: https://gsa-tts.slack.com/archives/C05MGJ72GU9/p1701709507202099
The commit of this pull request is self-verifying, so observe that build passes.
=> Support symbols in changelog message subcategory

config/environments/development.rb, config/environments/test.rb
Follow up to #9359 where there was an issue with requests failing due to headers not being lowercase. Issue reported [here](https://gsa-tts.slack.com/archives/C0NGESUN5/p1701723236789799).
I wasn't able to find a good way to test the public file server headers though.
=> Fix header casing for Rack 3

bin/query-cloudwatch
This PR adds a new require statement for `bin/query-cloudwatch` to satisfy dependencies. 
<details>
Example Query:
`bin/query-cloudwatch --from 7d --env henrydrich --app idp --log events.log --query "fields @timestamp | limit 20"`
Error Message:
```
bin/query-cloudwatch:260:in `parse!': undefined method `blank?' for "events.log":String (NoMethodError)
if (app = config.app) && (env = config.env) && !(log = config.log).blank?
^^^^^^^
from bin/query-cloudwatch:315:in `<main>'
```
</details>
<details>
Example Query:
`bin/query-cloudwatch --from 7d --env henrydrich --app idp --log events.log --query "fields @timestamp | limit 20"`
Output:
```
Querying log slices 100% [1/1] …
```
=> Active_support blank requirement for bin/query-cloudwatch

app/controllers/idv/by_mail/request_letter_controller.rb, spec/controllers/idv/by_mail/request_letter_controller_spec.rb
[LG-11551](https://cm-jira.usa.gov/browse/LG-11551)
Rails console commands to create duplicate with different address:
```
user = User.find_with_email('[EMAIL_USED_FOR_ACCOUNT]')
profile = user.gpo_verification_pending_profile
profile = profile.dup
pii = profile.decrypt_pii('[PASSWORD]')
pii.address1 = 'Non GPO Pending Profile'
pii.address2 = 'Non GPO Pending Profile'
pii.city = 'Pending Profile'
profile.active = false
profile.gpo_verification_pending_at = nil
profile.created_at = Time.zone.now
profile.encrypt_pii(pii, [PASSWORD])
profile.save!
```
=> LG-11551 Read the correct PII for resend letter

.gitlab-ci.yml
Currently jobs are failing because of a missing identity-dashboard image, swapping the `DASHBOARD_IMAGE_TAG` to `main` similar to `PKI_IMAGE_TAG` so that we won't have to chase tags moving forward
Validated that we are currently building an identity-dashboard image and the latest is tagged with main.
=> changelog: Internal, CI, Update Dashboard Image to main

lib/feature_management.rb, spec/lib/feature_management_spec.rb
Previously, we used an allowlist for specific subdomains on identitysandbox.gov. This means that Gitlab review apps are not able to reveal GPO codes for users testing GPO functionality.
This update makes it so all apps running on identitysandbox.gov reveal their GPO code.
=> Reveal GPO codes on identitysandbox.gov

app/controllers/idv/phone_controller.rb, app/controllers/idv/verify_info_controller.rb, app/services/idv/session.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/controllers/idv/otp_verification_controller_spec.rb, spec/policies/idv/flow_policy_spec.rb, spec/support/flow_policy_helper.rb
Introduces helpers in FlowPolicyHelper to set up the preconditions for idv steps in our specs. Note how much cleaner the flow_policy_spec setup is for all the individual step specs. We plan to use `stub_up_to_key` in the controller specs once this is merged.
Along the way, improved preconditions for PhoneStep and VerifyByMail.
=> FlowPolicy spec helpers for idv_session setup

app/jobs/reports/monthly_key_metrics_report.rb, lib/reporting/proofing_rate_report.rb, spec/lib/reporting/proofing_rate_report_spec.rb
**Why**: We get occasional rate limit errors when running this report in production, reducing the number of concurrent queries should hopefully help avoid hitting this limit
**Background**: The parallelism was added in #9212, when we only ran the report on developer boxes so that it would complete in under the 30min time window for an AWS vault session
[Example error in NewRelic](https://onenr.io/0bRK2VEnEwE)
=> Reduce parallelism of Cloudwatch Queries in key metrics report

app/services/idv/session.rb, spec/features/idv/end_to_end_idv_spec.rb
This is a bug-fix followup to back button work. Mark in person FSM steps incomplete when restarting the flow. Without this fix the in person FSM steps are marked complete the first time they are submitted and cannot be reentered.
Try this on main to confirm the bug, and then on this branch.
=> Allow in person flow to be repeated after resubmitting earlier step

app/models/profile.rb, app/services/idv/profile_maker.rb, spec/factories/profiles.rb, spec/services/idv/profile_maker_spec.rb
[LG-11692](https://cm-jira.usa.gov/browse/LG-11692)
* Update `ProfileMaker` to write the `idv_level` column when it mints Profiles
* Update factory_bot Profile factories to write idv_level as well
=> LG-11692: Start writing Profile idv_level

.gitlab-ci.yml, package.json, yarn.lock
Updates `quibble` dependency to the latest version.
Under the hood, `quibble` uses an experimental Node.js API (module loader hooks), which is subject to change in minor versions. This has happened, and our current version of `quibble` will fail to run on the latest version of Node.js v18.x. Since our [`.nvmrc` specifies only the top-level version](https://github.com/18F/identity-idp/blob/6a87cb7a6986414b68f7a71c6b8f97b440eb661d/.nvmrc), there's a good chance this could cause failures if a developer (i.e. me) runs `nvm install && nvm use` to use the latest valid version for the project. It's also expected this would start triggering failures in build if our GitLab CI were updated to use a new built image for CI.
Relates to (effectively cherry-picks from): #9639
1. Observe build passes
2. …
=> Update Quibble dependency for latest Node.js 18.x, 20.x support

app/jobs/reports/sp_issuer_user_counts_report.rb, app/mailers/report_mailer.rb, app/views/report_mailer/sp_issuer_user_counts_report.html.erb, config/locales/report_mailer/en.yml, config/locales/report_mailer/es.yml, config/locales/report_mailer/fr.yml, lib/reporting/authentication_report.rb, lib/reporting/identity_verification_report.rb, spec/jobs/reports/sp_issuer_user_counts_report_spec.rb, spec/lib/reporting/authentication_report_spec.rb, spec/lib/reporting/identity_verification_report_spec.rb
https://cm-jira.usa.gov/browse/LG-11738
Updates sp user count report to use the table report format
<details>
</details>
<details>
</details>
=> LG-11738 Update sp user count report

app/components/process_list_component.rb, app/components/process_list_item_component.html.erb, app/views/users/totp_setup/new.html.erb, spec/components/process_list_component_spec.rb, spec/features/remember_device/totp_spec.rb, spec/features/remember_device/user_opted_preference_spec.rb, spec/features/two_factor_authentication/multiple_mfa_sign_up_spec.rb, spec/features/users/totp_management_spec.rb, spec/support/features/session_helper.rb, spec/views/users/totp_setup/new.html.erb_spec.rb
[LG11696](https://cm-jira.usa.gov/browse/LG-11696)
Adds `aria-labelledby` to input fields on the page  `/authenticator_setup`.
- See aria attributes added to inputs on /authenticator_setup
=> LG-11696: Associate TOTP setup fields with visual label

spec/features/users/sign_in_spec.rb
This fixes the currently failing RSPEC test around OIDC. 
We dont really need the match check for the setting up of the overall test so removing it.
=> LG-5873: fix failing spec

lib/reporting/authentication_report.rb, lib/reporting/identity_verification_report.rb, spec/lib/reporting/authentication_report_spec.rb, spec/lib/reporting/identity_verification_report_spec.rb
Reverts a change that was made for consistency, but unfortunately would lead to command-line reports having blank values for the date generated cell.
=> Revert to using non-rails method for Date

spec/support/matchers/aria_view_matchers.rb
Fixes an issue where the code to create an error message for an invalid button raises an error due to an invalid operator.
The intent is to push to an array, which should use `<<` instead of `+=`.
Previously: #9508
Extracted from: #9674
This code is only run when there is an accessibility issue present. You can simulate by temporarily removing the fixes introduced with #9508:
```diff
diff --git a/app/views/idv/cancellations/new.html.erb b/app/views/idv/cancellations/new.html.erb
index 492cc9ead..f11b76219 100644
--- a/app/views/idv/cancellations/new.html.erb
+++ b/app/views/idv/cancellations/new.html.erb
@@ -34,7 +34,6 @@
method: :delete,
big: true,
wide: true,
-            form: { 'aria-label': t('idv.cancel.actions.start_over') },
).with_content(t('idv.cancel.actions.start_over'))
%> …
```
=> Fix concatenation for accessibility matcher error message

docs/local-development.md, spec/rails_helper.rb
Adds support for a new `SKIP_BUILD` environment variable which can be used in local development to skip asset compilation for JavaScript-enabled feature tests.
It also includes new documentation which explains the use-case and how to use it.
Previously, I could use `CI=true` for this, but (a) it's not very obvious that this would be an effect, (b) `ENV['CI']` can have many different effects which are intended for continuous integration (CI) environments, and (c) such changes as in #9734 may have adverse effects on the ability to continue using this locally.
Related: #9734
Related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1702322045401739?thread_ts=1702068737.905679&cid=C0NGESUN5
Observe that compilation happens without the flag, and doesn't happen with the flag. You …
=> Add and document environment flag for skipping asset build in local testing

app/services/reactivate_account_session.rb
Remove dead code from `ReactivateAccountSession`
changelog: internal,dead code removal,Verified that some suspected dead code really was, and removed it.
[LG-11757](https://cm-jira.usa.gov/browse/LG-11757)
We suspected that the the `:x509` value being set up in `ReactivateAccountSession#generate_session` was unused. A search through the code revealed that it was indeed not used anywhere. Removed it.
<details>
<summary>There were no uses of 'x509' or "x509". The one use of `:x509`, is as part of a test setup, and not as a session key:</summary>
```
context 'when a piv/cac was used as second factor' do
let(:x509) do
{
subject: x509_subject,
}
end
let(:x509_subject) { …
```
=> LG-11757 - Removed addition of :x509 key from ReactivateAccountSession.

lib/tasks/backfill_idv_level.rake, spec/lib/tasks/backfill_idv_level_rake_spec.rb
[LG-11693](https://cm-jira.usa.gov/browse/LG-11693)
This rake task is meant to backfill the `profiles.idv_level` column, but it was missing some records.
To determine whether a Profile should be tagged as `legacy_in_person`, the task checks whether an `InPersonEnrollment` record exists for the profile.
To determine whether a Profile should be tagged as `legacy_unsupervised`, the task checks whether an `InPersonEnrollment` record **does not** exist for the profile. It was doing this using, essentially:
```sql
SELECT * FROM profiles WHERE id NOT IN (SELECT profile_id FROM in_person_enrollments)
```
However this query will return no records when any `in_person_enrollments.profile_id IS NULL`. The fix is to limit the subquery to exclude null values:
```sql
SELECT * FROM profiles WHERE id NOT …
```
=> Update idv_level backfill to handle cases where profile_id is NULL

app/controllers/api/internal/two_factor_authentication/webauthn_controller.rb, app/controllers/concerns/reauthentication_required_concern.rb, app/controllers/users/webauthn_controller.rb, app/controllers/users/webauthn_setup_controller.rb, app/forms/two_factor_authentication/webauthn_delete_form.rb, app/forms/two_factor_authentication/webauthn_update_form.rb, app/services/analytics_events.rb, app/views/users/webauthn/edit.html.erb, config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml, config/locales/two_factor_authentication/en.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml, config/routes.rb, spec/controllers/api/internal/two_factor_authentication/webauthn_controller_spec.rb, spec/controllers/concerns/reauthentication_required_concern_spec.rb, spec/controllers/users/webauthn_controller_spec.rb, spec/controllers/users/webauthn_setup_controller_spec.rb, spec/forms/two_factor_authentication/webauthn_delete_form_spec.rb, spec/forms/two_factor_authentication/webauthn_update_form_spec.rb, spec/views/users/webauthn/edit.html.erb_spec.rb
Partially implements [LG-11454](https://cm-jira.usa.gov/browse/LG-11454)
Adds new Rails controllers for managing WebAuthn authenticators, to be used as part of [LG-11454](https://cm-jira.usa.gov/browse/LG-11454) to manage (rename or delete) an authenticator.
Currently, these routes are accessible but not exposed anywhere within the application. This is split from #9674, in order to reduce the size of that pull request, and to ensure that the routes are available during the 50/50 deployment state for the deploy which would include the frontend interface revisions.
Ensure build passes.
Optionally, it is expected that the routes for managing an authenticator would be available, including user-facing views and REST API routes. If you know the ID associated with your WebAuthn configuration†, …
=> LG-11454 (1): Add controllers for WebAuthn management

app/controllers/sign_up/completions_controller.rb, app/models/disposable_domain.rb, spec/controllers/sign_up/completions_controller_spec.rb, spec/models/disposable_domain_spec.rb
[LG-11209](https://cm-jira.usa.gov/browse/LG-11209)
Adds the property named `disposable_email_domain` to the event `User registration: complete` when the user registers with a known temporary email domain.
- Create a new account with a domain populated in the model DisposableDomain
- Check for the property `disposable_email_domain` on the event `User registration: complete`
=> LG-11209: Log event when new registered account uses disposable email domain

app/controllers/openid_connect/authorization_controller.rb, app/controllers/openid_connect/logout_controller.rb, app/javascript/packs/openid-connect-redirect.ts, app/views/openid_connect/shared/redirect_js.html.erb, config/application.yml.default, lib/identity_config.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/openid_connect/logout_controller_spec.rb, spec/support/oidc_auth_helper.rb
This is a follow-up to #9669 to add a different option for client-side redirect by using JavaScript rather than the HTTP `meta` tag.
=> Add support for JavaScript-driven client-side OIDC interstitial redirect

spec/lib/linters/analytics_event_name_linter_spec.rb, spec/lib/linters/errors_add_linter_spec.rb, spec/lib/linters/image_size_linter_spec.rb, spec/lib/linters/localized_validation_message_linter_spec.rb, spec/lib/linters/mail_later_linter_spec.rb, spec/lib/linters/redirect_back_linter_spec.rb, spec/lib/linters/url_options_linter_spec.rb
The rubocop linter specs were requiring the `rubocop/rspec/support`. This file is [defined in the Rubocop gem](https://github.com/rubocop/rubocop/blob/master/lib/rubocop/rspec/support.rb) and adds utilities for testing rubocop linters.
The rubocop support configuration _appears_ to make the assumption that the context in which it is included is a test suite for only testing Cops or at least for primarily testing Cops. The main clue for this is this part of the implementation:
```ruby
RSpec.configure do |config|
config.include CopHelper
end
```
The [`CopHelper` module](https://github.com/rubocop/rubocop/blob/master/lib/rubocop/rspec/cop_helper.rb) defines a number of methods for testing a linter. The support file includes that module for _every single example_. As a result all of our tests …
=> Use a more minimal require pattern for linter specs

app/models/service_provider.rb, app/services/reporting/agency_and_sp_report.rb, spec/factories/service_providers.rb, spec/models/service_provider_spec.rb, spec/services/reporting/agency_and_sp_report_spec.rb
[LG-11800](https://cm-jira.usa.gov/browse/LG-11800)
We were reporting on 5 apps that are internal (OIDC example, etc), but we should be excluding those for reporting. Major kudos to @Sgtpluck for finding that all the apps we needed to exclude conveniently had `iaa: 'LGINTERNAL'` on them.
=> Update apps/agencies report to exclude internal apps (LG-11800)

app/controllers/users/delete_controller.rb, app/mailers/user_mailer.rb, app/views/user_mailer/account_delete_submitted.html.erb, spec/controllers/users/delete_controller_spec.rb, spec/mailers/previews/user_mailer_preview.rb, spec/mailers/user_mailer_spec.rb
[LG-10976: Delete Account triggers delete email](https://cm-jira.usa.gov/browse/LG-10976)
Account deletion triggers an email to user email when deleting through Account dashboard
- Create an account
- Go to Account Dashboard
- Delete account
- Ensure that email is sent to user email when account is deleted
=> LG-10976: Delete Account from Dashboard triggers Account deleted email

app/controllers/concerns/idv/ab_test_analytics_concern.rb, app/services/idv/lexis_nexis_instant_verify.rb, app/services/proofing/resolution/progressive_proofer.rb, spec/controllers/concerns/idv/ab_test_analytics_concern_spec.rb, spec/services/idv/lexis_nexis_instant_verify_spec.rb, spec/services/proofing/resolution/progressive_proofer_spec.rb
Capitalization: Rename LexisnexisInstantVerify to LexisNexisInstantVerify
Followup to [comment](https://github.com/18F/identity-idp/pull/9761#discussion_r1427124472) on service name spelling in #9743
=> Capitalization: Rename LexisnexisInstantVerify to LexisNexisInstantVerify

app/forms/openid_connect_authorize_form.rb, app/models/federated_protocols/oidc.rb, app/models/federated_protocols/saml.rb, app/models/service_provider_request.rb, app/services/service_provider_request_handler.rb, app/services/service_provider_request_proxy.rb, app/services/store_sp_metadata_in_session.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/forms/openid_connect_authorize_form_spec.rb, spec/services/store_sp_metadata_in_session_spec.rb
We have not clearly defined how we want service providers to request a biometric comparison. This commit adds a query parameter to the OIDC authorization URL to specify that a biometric is required. This is temporary and intended to enable us to test the selfie / in-person requirement end-to-end before the API for requesting this functionality is fully defined.
This commit stores the attribute in the SP session. It does not make any changes to functionality based on the attribute or apply any changes to the SAML API.
The corresponding change on the sample app is here: https://github.com/18F/identity-oidc-sinatra/pull/149
=> LG-11697 Store whether a biometric comparison is required in the SP session

spec/support/capybara.rb
This fixes local dev for Chromedriver v120. We found that upgrading Chromedriver to v120 in Docker for CI caused all sorts of issues, so for the time being we are not upgrading CI.
This is a workaround from the failures in https://github.com/18F/identity-idp/pull/9734.
[See this documentation for details on the change](https://www.selenium.dev/blog/2023/headless-is-going-away/), [this conversation in Slack for discussion](https://gsa-tts.slack.com/archives/C0NGESUN5/p1702068737905679), and [this issue on Chromedriver](https://bugs.chromium.org/p/chromedriver/issues/detail?id=4440).
=> Fix headless mode used by Selenium locally 

app/views/forgot_password/show.html.erb, config/locales/notices/en.yml, config/locales/notices/es.yml, config/locales/notices/fr.yml, spec/views/forgot_password/show.html.erb_spec.rb
[LG-11782](https://cm-jira.usa.gov/browse/LG-11782)
Removes text from the page `/forgot_password` found during the reset password process.
- Go through the "Forgot your password?" process to reset an account password. Notice the removal of text at the URL `/forgot_password`.
=> LG-11782: Remove create new account from password reset process

app/models/user.rb, spec/controllers/idv/by_mail/enter_code_controller_spec.rb, spec/lib/tasks/dev_rake_spec.rb, spec/models/user_spec.rb
`User::active_profile` and `User::pending_profile` both cache their results in instance variables. This is fine, but sometimes, especially in tests, those caches get stale, and there's not a straightforward way to bust them without creating a new User instance (for example, `User::reload` does not clear those cached instance variables).
This PR updates `active_profile` and `pending_profile` to check whether the cached Profile they're about to return are still active or pending, and busts the cache if something has changed.
=> Bust caches in User::active_profile and User::pending_profile

app/services/reporting/agency_and_sp_report.rb, spec/services/reporting/agency_and_sp_report_spec.rb
Handle query timeouts in Agencies and SPs report
- In #9744, we added more correct queries that took much longer. Even though we added the correct `transaction_with_timeout` wrapper, and even though the queries can succeed, the report still failed in prod. [error link](https://one.newrelic.com/nr1-core/errors-inbox/entity-inbox/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?duration=86400000&state=d3e9c328-f096-a4f1-58c2-184bb0785564)
- Adding this rescue allows the report to complete and send partial results still
=> Rescue errors in Agencies and SPs report

config/application.yml.default, spec/features/openid_connect/phishing_resistant_required_spec.rb, spec/features/saml/phishing_resistant_required_spec.rb, spec/features/two_factor_authentication/change_factor_spec.rb, spec/features/users/regenerate_personal_key_spec.rb, spec/features/webauthn/management_spec.rb, spec/support/features/session_helper.rb
Updates the default configuration for `reauthn_window` to match production.
In testing in review apps and sandbox environments, we'll frequently encounter 2 minute reauthentications, which are overly aggressive and I'll have to explain behaves differently in production ([example 1 from 2 days ago](https://docs.google.com/document/d/1yvxk6ncQ451plF-kMWjMM9n8db7QHLAIhdwi9r37qB8/edit#bookmark=id.hbsyre5jb07e), [example 2 from yesterday](https://gsa-tts.slack.com/archives/C0595QABDS7/p1702580379988289?thread_ts=1702575969.564879&cid=C0595QABDS7)).
Test that this changes reauthentication timeout in default environments:
1. Ensure that you're not overriding `reauthn_window` in your local `config/application.yml`
3. Sign in
4. On account dashboard, wait 3 minutes …
=> Sync default reauthn_window with production value

docs/local-development.md
Replace: broken link within doc => working link to different doc
=> Fix link to troubleshooting

spec/controllers/users/passwords_controller_spec.rb
Adds an assertion to a test case intended to verify that a user event is created upon successful password change.
Previously, this spec would only do the set up to invoke the password change, but didn't include any assertions.
This was noticed in putting together #9780 and looking for examples of other user event spec verifications.
```
rspec spec/controllers/users/passwords_controller_spec.rb
```
=> Add missing spec assertion for password change user event

app/controllers/idv/image_uploads_controller.rb, app/services/doc_auth_router.rb, app/views/idv/shared/_document_capture.html.erb, config/application.yml.default, lib/identity_config.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/features/idv/doc_auth/document_capture_spec.rb, spec/features/idv/doc_auth/redo_document_capture_spec.rb, spec/services/doc_auth_router_spec.rb, spec/views/idv/shared/_document_capture.html.erb_spec.rb
The `doc_auth_selfie_capture` is a JSON hash that was intended to manage multiple configs for document selfie capture. Prior to this commit it contains a single value: `enabled`.
Using an unstructured hash this way means we do not get many of the benefits of using IdentityConfig e.g. type validation for configs and warnings/errors when configs are missing.
This commit moves the enabled config from `doc_auth_selfie_capture` to `doc_auth_selfie_capture_enabled` and deletes the `doc_auth_selfie_capture` config. Future configs for selfie capture can use the `doc_auth_selfie_capture` prefix.
=> Rename `doc_auth_selfie_capture` config to `doc_auth_selfie_capture_enabled`

app/controllers/api/internal/two_factor_authentication/webauthn_controller.rb, app/controllers/users/webauthn_controller.rb, spec/controllers/api/internal/two_factor_authentication/webauthn_controller_spec.rb, spec/controllers/users/webauthn_controller_spec.rb
Relates to [LG-11454](https://cm-jira.usa.gov/browse/LG-11454) (originally #9674)
Restores additional behaviors expected to occur after the successful deletion of a WebAuthn credential.
I noticed these after starting to put together the clean-up pull request to remove the old deletion routes, which implement these behaviors:
https://github.com/18F/identity-idp/blob/8558b0bf244082f39f2c1f6bb282973bce1b48ca/app/controllers/users/webauthn_setup_controller.rb#L148-L152
Verify specs pass:
1. `rspec spec/controllers/api/internal/two_factor_authentication/webauthn_controller_spec.rb spec/controllers/users/webauthn_controller_spec.rb`
You can also verify that behaviors actually happen when deleting Face or Touch Unlock:
1. (Prerequisite) Have an account with Face or Touch Unlock configured
2. Go …
=> LG-11454: Restore successful WebAuthn delete handling user events

spec/controllers/api/internal/two_factor_authentication/webauthn_controller_spec.rb, spec/controllers/users/webauthn_controller_spec.rb
Relates to [LG-11454](https://cm-jira.usa.gov/browse/LG-11454) (originally https://github.com/18F/identity-idp/pull/9674, #9742)
Adds additional test cases for the WebAuthn controllers implemented in #9742 to verify expected behaviors around checking ownership of the configuration.
Some of this was originally intended to be covered by the associated form's specs, with existing coverage for an "invalid" submission scenario being sufficient coverage for the controller's behaviors. However, there are additional controller-specific behaviors not previously covered (e.g. `WebauthnController#validate_configuration_exists`).
These behaviors worked as intended, but additional test cases could help prevent future regressions.
Verify tests pass:
1. `rspec …
=> LG-11454: Improve robustness of WebAuthn controller specs

app/controllers/openid_connect/authorization_controller.rb, app/controllers/openid_connect/logout_controller.rb, config/application.yml.default, lib/identity_config.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/openid_connect/logout_controller_spec.rb, spec/support/oidc_auth_helper.rb
This adds another layer of configuration to help us debug and test changes around client-side redirect
=> Add support for client-side OIDC redirect by UUID

config/application.yml.default, docs/local-development.md
Enables RISC event delivery in local development by default, and documents the test route for viewing delivered notifications.
Related Slack thread: https://gsa-tts.slack.com/archives/C0NGESUN5/p1702907459403909
Follow the proposed documentation and verify that you can view RISC events in local development.
=> Enable, document RISC push notifications for local development 

app/views/pages/not_acceptable.html, app/views/pages/page_not_found.html, app/views/pages/page_took_too_long.html.erb, public/401.html, public/406.html, public/422.html, public/429.html, public/500.html, public/503.html
Removes a reference to a `clearfix` class which does not exist in the context of static error pages.
These error pages load a [reduced, static stylesheet](https://github.com/18F/identity-idp/blob/main/public/css/static.css) which does not implement `.clearfix`.
This is also an incremental step toward removing `clearfix` usage across the application, prompted partly by #9674.
Visit each page and observe no visual regressions, e.g. http://localhost:3000/401.html
=> Remove unimplemented clearfix CSS class from static error pages

.gitlab-ci.yml
As part of the internationalization process changes, we are in a content freeze. To assist in preventing those changes, this PR intends to add a simple CI check that will fail when there is a change in a content file.
=> Add temporary continuous integration check to fail on content changes

app/forms/openid_connect_authorize_form.rb, app/models/federated_protocols/oidc.rb, app/models/federated_protocols/saml.rb, app/models/service_provider_request.rb, app/services/service_provider_request_handler.rb, app/services/service_provider_request_proxy.rb, app/services/store_sp_metadata_in_session.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/forms/openid_connect_authorize_form_spec.rb, spec/services/store_sp_metadata_in_session_spec.rb
This reverts commit 6fee3a0a1d9ac999e0032309cd47135a58fe19e9 because there were issues in the compatibility of the new service provider request model with old hosts.
This commit reverts the problematic change and adds a default arg to ensure compatibility. The commit reverted here can be un-reverted once the change to add the default value has shipped.
=> Revert "LG-11697 Store whether a biometric comparison is required in the SP session (#9759)"

app/forms/openid_connect_authorize_form.rb, app/models/federated_protocols/oidc.rb, app/models/federated_protocols/saml.rb, app/models/service_provider_request.rb, app/services/service_provider_request_handler.rb, app/services/service_provider_request_proxy.rb, app/services/store_sp_metadata_in_session.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/forms/openid_connect_authorize_form_spec.rb, spec/services/store_sp_metadata_in_session_spec.rb
This reverts commit 558ebd6b85d971d053f1a56450b9c1720c8158ed.
The reverted commit here was reverting the changes in #9759. That change had issues with compatibility which were addressed in the changes in the reverted commit and deployed. The deployment of those changes makes this commit safe to merge.
=> Revert "Revert "LG-11697 Store whether a biometric comparison is required in the SP session (#9759)" (#9804)"

config/locales/idv/es.yml, config/locales/idv/fr.yml, spec/i18n_spec.rb
Fixes an issue where French and Spanish content are mismatched, contained within the others' locale data for identity verification information disclosure.
Also adds a new regression spec intended to try to catch these sorts of issues by checking for content patterns which are expected to only exist within specific locales.
See: https://github.com/18F/identity-idp/pull/9392/files#r1431752474
Repeat Testing Plan from #9392 
Verify new tests pass:
```
rspec spec/i18n_spec.rb
```
Also observe that the tests would fail without the included content updates:
```
git checkout main -- config/locales/idv/es.yml config/locales/idv/fr.yml
rspec spec/i18n_spec.rb
```
=> Fix and test for mismatched locale content

app/controllers/concerns/idv/ab_test_analytics_concern.rb, app/controllers/idv/by_mail/request_letter_controller.rb, app/controllers/idv/in_person/address_controller.rb, app/controllers/idv/in_person/ssn_controller.rb, app/controllers/idv/in_person/verify_info_controller.rb, app/controllers/idv/otp_verification_controller.rb, app/controllers/idv/phone_controller.rb, spec/controllers/concerns/idv/ab_test_analytics_concern_spec.rb, spec/controllers/idv/otp_verification_controller_spec.rb, spec/features/idv/analytics_spec.rb
This is a followup to #9646 which added :opt_in_analytics_buckets to some IdV controller analytics. Move the addition to ab_test_analytics_buckets so that it gets added to all the IdV controllers, and tested in ab_test_analytics_concern_spec.rb.
OtpVerificationController didn't have ab_test_analytics_buckets, so add it in.
PersonalKeyController didn't have it either, but it also didn't have IdvStepConcern, which is being added in #9776, so leaving it alone for now to avoid unnecessary conflicts.
=> Move opt in analytics to ab_test_analytics_buckets

app/services/out_of_band_session_accessor.rb, app/services/pii/cacher.rb, lib/session_encryptor.rb, spec/controllers/idv/sessions_controller_spec.rb, spec/lib/session_encryptor_spec.rb
In #9754 the code that depended on the passive encryption of `decrypted_pii` in the session was removed. Some of the code removed here was left behind to ensure that PII remained encrypted.
Once the code in #9754 is deployed to production this should be safe to merge.
=> Remove the passive encryption of encrypted PII in the session

app/forms/idv/doc_pii_form.rb, spec/forms/idv/doc_pii_form_spec.rb
LG-1118: zip code validation
Basic zip code validation for [zip+4](https://faq.usps.com/s/article/ZIP-Code-The-Basics#:~:text=Yes%2C%20when%20using%20a%20ZIP,unable%20to%20deliver%20the%20item.) for US and territories postal code format.
```yaml
document:
type: license
first_name: Susan
last_name: Smith
middle_name: Q
address1: 1 Microsoft Way
address2: Apt 3
city: Bayside
state: NY
zipcode: '113642'
dob: 10/06/1938
phone: +1 314-555-1212
state_id_number: '123456789'
state_id_type: drivers_license
```
=> LG-11118: zip code format validation

Gemfile, Gemfile.lock, spec/components/tab_navigation_component_spec.rb
Updates both brakeman and view_component. Brakeman includes some updates for better static security checks, and view_component is just a little bit behind.
=> Update Brakeman and view_component

app/views/accounts/_pii.html.erb, app/views/accounts/_webauthn_roaming.html.erb
Removes two instances of unnecessary `clearfix`, within the account page Security Key listing and Verified Information security disclosure text.
Historically, these were implemented using [BassCSS grid](https://basscss.com/#basscss-grid), which uses `float` on individual columns. As documented, it's required to define `clearfix` on the column container when using BassCSS grid. In #4169, we migrated from BassCSS to USWDS for these grid layouts. The design system uses flexbox for grids and does not require a `clearfix`.
This is a continuation of the work in https://github.com/18F/identity-idp/pull/9799 to eliminate the few remaining usages of `clearfix`.
Verify no visual regressions in display of Security Key and Verified Information widgets on account dashboard:
1. (Prerequisite: Have an …
=> Remove unnecessary clearfix from account page widgets

app/controllers/frontend_log_controller.rb, app/javascript/packages/document-capture/components/acuant-capture.tsx, app/javascript/packages/document-capture/components/acuant-selfie-camera.tsx, app/services/analytics_events.rb, spec/features/idv/analytics_spec.rb, spec/javascript/packages/document-capture/components/acuant-capture-spec.jsx, spec/javascript/support/document-capture.jsx
[LG-11631](https://cm-jira.usa.gov/browse/LG-11631)
This PR adds 5 logging events:
1. `idv_sdk_selfie_image_capture_opened` (**mobile only** - logs when a user opens the SDK for selfie capture)
2. `idv_sdk_selfie_image_capture_closed_without_photo` (**mobile only** - logs when a user starts to take a selfie with the SDK but exits out without adding one)
3. `idv_sdk_selfie_image_capture_failed` (**mobile only** - logs when an error happens in the process of adding the selfie via the SDK)
4. `idv_sdk_selfie_image_added` (**mobile only** - logs when a user uses the SDK to click the green checkmark and accept their selfie)
5. `idv_selfie_image_file_uploaded` (**desktop only** - logs when a user uses the file picker instead of the SDK to add a selfie)
Co-authored-by: Charles Ferguson …
=> LG-11631: Add front end logging for selfie capture

app/models/profile.rb, spec/models/profile_spec.rb
Remove `Profile::includes_phone_check?`, which does not appear to be referenced anywhere in the code base.
=> Remove unused Profile::includes_phone_check? method

spec/features/users/profile_recovery_for_gpo_verified_spec.rb
[LG-11743](https://cm-jira.usa.gov/browse/LG-11743)
Added a spec to check profile reactivation for GPO-verified users.
This is a bug reported by and believed fixed by Matt Hinz (see LG-11549), but we wanted a feature spec to test this exact scenario.
Co-authored by: Matt Hinz <matt.hinz@gsa.gov>
[ ] Run the new feature spec using the command below
[ ] Verify that the system walks through creating a GPO-verified user, resetting their password, and then re-activating their profile with the personal key generated during GPO verification.
`SHOW_BROWSER=true bundle exec rspec spec/features/users/profile_recovery_for_gpo_verified_spec.rb`
=> LG-11743 - Ensure personal key works for GPO users

spec/features/idv/analytics_spec.rb
It seems I broke something with https://github.com/18F/identity-idp/pull/9795.
Unsure why these passed so many times before merging, but perhaps the
interface changed since last rebase to now.
Edit: it is indeed because I did not rebase before merging. [See this comment for details](https://github.com/18F/identity-idp/pull/9816#issuecomment-1865117300).
=> Fix analytics spec failures

docs/frontend.md
Updates the Frontend Architecture documentation to improve a few inaccuracies:
- We don't require listing sibling package dependencies between Yarn workspace packages
- `private` must be specified in all `package.json` (enforced by `scripts/validate-workspaces.js`), not just for published packages
- Generalize the recommendation around what was intended with the `index.js` documentation, also using the recommended TypeScript file extension, and allowing equivalent `exports` or `main`
- Describe JavaScript package integration using ViewComponents, which is generally preferable to `packs`
- Describe `ALLOWED_EVENTS` accurately as an allowlist, rather than a mapping
Verify that documentation revisions are sensible.
=> Improve accuracy of Frontend packages, events documentation

app/assets/stylesheets/components/_password.scss, app/views/devise/shared/_password_strength.html.erb
Refactors password strength styling, with the only user-facing visual effect being that it adopts standard design system colors for password feedback.
Originally this started as a continuation of the work in #9799 to eliminate the few remaining usages of `clearfix`. Incrementally, this also works toward a broader refactor of the password strength implementation toward [frontend conventions](https://github.com/18F/identity-idp/blob/main/docs/frontend.md) (ViewComponent, TypeScript, BEM CSS class naming, per-component stylesheet).
Verify no regression in the behavior of password feedback being shown:
2. Sign in
3. From account dashboard, click "Edit password"
4. (Reauthenticate if prompted)
5. Enter a "New password" value
6. Observe password strength feedback …
=> Use design sytem colors for password strength meter

app/jobs/reports/duplicate_ssn_report.rb
[LG-11963](https://cm-jira.usa.gov/browse/LG-11963)
This table scan is timing out in prod [(newrelic link)](https://one.newrelic.com/nr1-core/errors-inbox/entity-inbox/MTM3NjM3MHxBUE18QVBQTElDQVRJT058NTIxMzY4NTg?account=1376370&duration=10800000&state=168040d6-8e74-a6c6-e93c-589858217adf), so this updates the timeout to get around that. The other queries in this file are indexed point queries so I figured it was not worth adding timeout exceptions to those.
=> Update query timeout in duplicate SSN report (LG-11963)

config/application.yml.default
It has been off in prod for a while, so let's make development match for everyone. If someone needs it on locally, they can turn it on in their application.yml.
=> Turn off DocumentCapture exit survey in development

app/forms/event_disavowal/password_reset_from_disavowal_form.rb, spec/forms/event_disavowal/password_reset_from_disavowal_form_spec.rb
[LG-11839](https://cm-jira.usa.gov/browse/LG-11839)
If a user goes through IdV and choses to reset their password at the enter password step and then disavow that password reset, their proofing components gets deleted. We want to keep those proofing components until a user completed IdV so that they get minted with the profile. This PR fixes that. This should not matter because if a user resets their password they have to go through IdV again, but this eliminates an edge case.
=> LG-11839 Don't delete proofing_component on password reset for profiles not yet activated

app/controllers/concerns/idv/document_capture_concern.rb, app/controllers/idv/document_capture_controller.rb, app/controllers/idv/hybrid_mobile/document_capture_controller.rb, app/controllers/idv/image_uploads_controller.rb, app/decorators/null_service_provider_session.rb, app/decorators/service_provider_session.rb, app/forms/idv/api_image_upload_form.rb, app/javascript/packs/document-capture.tsx, app/services/doc_auth/acuant/acuant_client.rb, app/services/doc_auth/lexis_nexis/lexis_nexis_client.rb, app/services/doc_auth/lexis_nexis/requests/true_id_request.rb, app/services/doc_auth/mock/doc_auth_mock_client.rb, app/views/idv/document_capture/show.html.erb, app/views/idv/hybrid_mobile/document_capture/show.html.erb, app/views/idv/shared/_document_capture.html.erb, spec/controllers/idv/document_capture_controller_spec.rb, spec/controllers/idv/hybrid_mobile/document_capture_controller_spec.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/decorators/service_provider_session_spec.rb, spec/features/idv/analytics_spec.rb, spec/features/idv/doc_auth/document_capture_spec.rb, spec/features/idv/doc_auth/redo_document_capture_spec.rb, spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb, spec/services/doc_auth/lexis_nexis/requests/true_id_request_spec.rb, spec/views/idv/shared/_document_capture.html.erb_spec.rb
[LG-11873](https://cm-jira.usa.gov/browse/LG-11873)
- determine if doc auth with selfie is required based on the SP Session
- only allow selfie to be sent to doc auth vendor if selfie FF is enabled
- do not allow selfie to be sent to doc auth vendor  if host env is production
- indicate to the FE to display selfie field if hosted env is not production, selfie FF is enabled and requested by SP
=> LG-11873: doc auth w/ selfie in non-prod hosted envs

app/jobs/reports/identity_verification_report.rb, config/application.yml.default, lib/identity_config.rb, lib/reporting/identity_verification_report.rb, spec/jobs/reports/identity_verification_report_spec.rb, spec/lib/reporting/identity_verification_report_spec.rb
[LG-11655](https://cm-jira.usa.gov/browse/LG-11655)
Added the ability to email the IdentityVerificationReport to team Ada members. Added `team_ada_email` config value.
Out of scope for this PR: Add a team Ada mailing list.
Since this job requires cloudwatch wait until this is merged.
=> LG-11655: Added the ability to email IdV reports

lib/data_pull.rb
In trying to run `uuid-export uuid1 uuid2 --requesting-issuer ABC:DEF:GHI` it failed because the option was not parsed correctly. https://handbook.login.gov/articles/devops-scripts.html#uuid-export shows the expected usage, and this PR updates the documentation here to match.
=> Update data pull script documentation

app/javascript/packages/document-capture/components/document-capture-review-issues.tsx, app/javascript/packages/document-capture/components/review-issues-step.tsx
https://cm-jira.usa.gov/browse/LG-11906
This PR is a followup to fix some typing oddness we noticed [here](https://github.com/18F/identity-idp/pull/9827#discussion_r1435405386). It ended up changing the typing in one file to use the same `FormStepComponentProps` utility as we use other places.
1. `yarn run tsc`
2. Run the app locally, check the IDV document upload flow for regressions and/or new console warnings.
=> Rework `review-step` Typing to use Shared Types and Utilities

app/javascript/packages/document-capture/components/document-capture-review-issues.tsx, app/javascript/packages/document-capture/components/documents-step.jsx, app/javascript/packages/document-capture/components/documents-step.tsx, app/javascript/packages/document-capture/components/review-issues-step.tsx
https://cm-jira.usa.gov/browse/LG-11893
These changes extract and reuse a component for both the `document-capture` and `review-issues` step rather than doing it twice in two different places. This is not directly related to the ticket, but this cleanup is in the same file, so doing this first should make the work in coming PRs easier.
Log in to the app, enter the IDV flow on a phone and check that the front/back upload boxes still look and behave as expected.
=> LG-11893: Prep by Continuing Unifying `document-capture` and `review-issues` Steps

bin/oncall/email-deliveries, spec/bin/oncall/email-deliveries_spec.rb
This PR adds a couple additional items from the log to help troubleshoot email issues.
Example of new output:
```
+--------------------------------------+-------------------------+--------------------------------------------------------------+---------------------------------+----------------------------------------------+
| user_id                              | timestamp               | message_id                                                   | email_action                    | events                                       |
+--------------------------------------+-------------------------+--------------------------------------------------------------+---------------------------------+----------------------------------------------+
| 00000000-0000-0000-0000-000000000000 | 2024-01-03 …
```
=> Add addtional bounce information to email-deliveries script

app/javascript/packages/i18n/index.ts, app/javascript/packages/rails-i18n-webpack-plugin/rails-i18n-webpack-plugin.js, app/javascript/packages/rails-i18n-webpack-plugin/rails-i18n-webpack-plugin.spec.js
Replaces a couple instances of custom utility functions with native language alternatives.
- Replace `hasOwn` with [`Object.hasOwn`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn) (relatively new, available since [ES2022](https://262.ecma-international.org/13.0/#:~:text=ECMAScript%202022%2C%20the,prototype.hasOwnProperty.) / [Node.js 16.9.0](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn#browser_compatibility))
- Replace `fromPairs` with [`Object.fromEntries`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries) (no excuse on this one)
**Why?**
- Smaller code size (better maintainability)
- Native implementations is likely more battle-tested than …
=> Replace custom utilities with native JavaScript equivalents

app/javascript/packages/document-capture/components/document-capture-review-issues.tsx, app/javascript/packages/document-capture/components/review-issues-step.tsx
This is a props change in response to Andrew's [comment here](https://github.com/18F/identity-idp/pull/9836#discussion_r1439469761). We expect the `toPreviousStep` prop to be available to steps even if they're not using it. This PR makes that true, by making `toPreviousStep` available to the review step.
=> Type/Props Change PR: Send 'toPreviousStep' Down as A Prop

app/controllers/openid_connect/authorization_controller.rb, config/routes.rb, lib/feature_management.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/features/openid_connect/authorization_confirmation_spec.rb, spec/lib/feature_management_spec.rb, spec/support/oidc_auth_helper.rb
[LG-11962](https://cm-jira.usa.gov/browse/LG-11962)
Added a check to ensure that SP requests for selfies are not permitted in production. This is a temporary measure, until  we are actually ready to handle them properly.
Simulating a production environment on a dev box turned out to be a time sink. After spending Friday afternoon shaving yaks, re-assessed and simulated a production environment via a code change. If desired, we could spin up a sandbox for closer simulation of production. I don't feel that's necessary for code review, but perhaps for acceptance.
The code change is in `lib/feature_management.rb`, lines 167-168:
```
def self.idv_block_biometrics_requests?
true
end
```
If relevant, include a screenshot or screen capture of …
=> LG-11962 return 406 if biometric selected in production

app/controllers/openid_connect/logout_controller.rb, app/controllers/saml_idp_controller.rb, config/initializers/rack_attack.rb, lib/custom_devise_failure_app.rb, spec/controllers/openid_connect/logout_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/features/openid_connect/openid_connect_spec.rb, spec/features/saml/saml_logout_spec.rb, spec/lib/custom_devise_failure_app_spec.rb, spec/requests/rack_attack_spec.rb
[LG-11777](https://cm-jira.usa.gov/browse/LG-11777)
Related issue: #9407
Updates the behavior of the OIDC and SAML logout actions to prevent a user from being sent to the sign-in page if their session is terminated by [the `session_limitable` logic (concurrent browser session)](https://github.com/18F/identity-idp/blob/main/config/initializers/session_limitable.rb), treating them as if they had already been logged-out, and inheriting the existing expected behavior[[1]](https://github.com/18F/identity-idp/blob/61c5e6685f87ee383941d4924ecabd1fab823513/spec/features/saml/saml_logout_spec.rb#L91-L107)[[2]](https://github.com/18F/identity-idp/blob/61c5e6685f87ee383941d4924ecabd1fab823513/spec/controllers/openid_connect/logout_controller_spec.rb#L227-L253) for redirecting a logged-out user.
1. …
=> LG-11777: Handle logout request as already logged out if concurrent session exists

Gemfile.lock, config/puma.rb
We use puma in local development and review applications, but do not include a configuration for it. This change adds a slightly modified version of the puma config that Rails generates in new applications.
=> Add Puma configuration

app/controllers/openid_connect/authorization_controller.rb, app/controllers/sign_up/completions_controller.rb, app/models/profile.rb, app/models/user.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/sign_up/completions_controller_spec.rb, spec/features/idv/end_to_end_idv_spec.rb, spec/models/user_spec.rb
[LG-11695](https://cm-jira.usa.gov/browse/LG-11695)
This is Part 1 of several PRs for this ticket, and addresses AC1: If an SP requests a selfie check and the user has not performed a selfie check, we send the user back to the start of proofing before re-directing to the SP (edge case)
- Add :unsupervised_with_selfie value to Profile idv_level enum
- Add User#identity_verified_with_selfie? which checks the active profile idv_level
- In completions_controller, add before_action that checks whether the user was verified with selfie if the SP requires it and doc_auth_selfie_capture_enabled is true.
- In OpenidConnect::AuthorizationController#index, redirect to idv_url if a selfie is required and user did not verify at that level.
- Leaving out SamlIdpController#auth for now because it's not …
=> LG-11695 enforce selfie capture performed

Gemfile.lock, spec/controllers/openid_connect/authorization_controller_spec.rb
When :doc_auth_selfie_capture_enabled is off, we now render the not_acceptable page. Spec now expects that in oidc_connect/authorization_controller_spec.
=> Spec fix: Expect 406 when selfie flag is off because of production block

app/javascript/packages/build-sass/CHANGELOG.md, app/javascript/packages/build-sass/README.md, app/javascript/packages/build-sass/cli.js, app/javascript/packages/build-sass/cli.spec.js, app/javascript/packages/build-sass/fixtures/default-out-dir/.gitignore, app/javascript/packages/build-sass/index.js
Improves `@18f/identity-build-sass` to allow usage without specifying `--out-dir` flag.
I stumbled upon this when trying to use the package outside the project for reproduction steps for an [unrelated bug report](https://github.com/uswds/uswds/pull/5699).
```
git checkout aduth-build-sass-optional-out-dir
touch example.scss
yarn build-sass example.scss
ls example.css
```
Observe that output file exists.
=> build-sass: Support optional out-dir option

app/javascript/packages/document-capture/components/status-message.tsx
Convert the status-message component form JS to JS by by creating a StatusMesageProps.
=> Convert status-message component from JS to TS

bin/oncall/email-deliveries, lib/reporting/cloudwatch_client.rb
```bash
> aws-vault exec prod-power -- ./bin/oncall/otp-deliveries asdasd
[ Querying logs ] =---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=--- Time: 00:00:00
/identity-idp/lib/reporting/cloudwatch_client.rb:245:in `slice_time_range': undefined method `present?' for nil:NilClass (NoMethodError)
if time_slices.present?
^^^^^^^^^
from identity-idp/lib/reporting/cloudwatch_client.rb:65:in `fetch'
from ./bin/oncall/otp-deliveries:108:in `block in query_data'
from identity-idp/lib/reporting/unknown_progress_bar.rb:24:in `wrap'
from ./bin/oncall/otp-deliveries:107:in `query_data'
from ./bin/oncall/otp-deliveries:79:in `run'
from ./bin/oncall/otp-deliveries:148:in `<main>'
```
```
> aws-vault exec prod-power -- …
```
=> Fix missing require for OTP deliveries script

.eslintrc, app/javascript/packages/address-search/components/address-search.spec.tsx, app/javascript/packages/address-search/components/full-address-search.spec.tsx, app/javascript/packages/document-capture/components/in-person-location-full-address-entry-post-office-search-step.spec.tsx, app/javascript/packages/document-capture/components/in-person-location-post-office-search-step.spec.tsx, app/javascript/packages/form-steps/form-steps.spec.tsx, package.json, spec/javascript/packages/document-capture/components/document-capture-spec.jsx, spec/javascript/packages/document-capture/components/review-issues-step-spec.jsx, yarn.lock
Adds [`eslint-plugin-testing-library`](https://www.npmjs.com/package/eslint-plugin-testing-library) to enforce additional lints surrounding expected usage of [Testing Library](https://testing-library.com/) related features.
**Why?**
- Allows us to remove one of our own custom "restricted syntax" rules which targeted part of what this plugin offers
- It will catch legitimate issues with usage of Testing Library functions, as evidenced by the included changes necessary to get existing tests passing
Verify that both lint and tests pass:
```
yarn lint
```
```
yarn test
```
=> Use testing-library ESLint plugin

spec/features/idv/analytics_spec.rb
I was getting a local chromedriver error that went away when I added `allow_browser_log: true` to specs. Now fixed locally, and should not have been checked in, so removing that.
For some reason feature specs for the in person flow do need `allow_browser_log: true` to pass. Do we know why that is?
Specs pass on CI.
=> Remove browser_log: true from analytics_spec

.github/dependabot.yml
Revises the Dependabot configuration to restore the behavior of automatic update pull requests for security advisories. 
Based on Dependabot logs bailing with "all versions were ignored" messaging, it's suspected that customizations to Dependabot implemented in #9055 and #5462 are taking precedence over the default Dependabot configuration for security advisories, which was not the intent. Our `bundler-audit` and `yarn audit`-based dependency auditing has worked as a fallback option, but it would be nice to configure Dependabot to automatically update dependencies on our behalf when a new version is available.
While GitHub does not provide specific example configurations for our setup, this is based partly on documentation that ["If you only require security updates and want to exclude …
=> Try configuring Dependabot for security updates

.github/dependabot.yml
Reverts 18F/identity-idp#9877
After merging to main, this started failing due to invalid configuration:
>Your .github/dependabot.yml contained invalid details
>
>Dependabot encountered the following error when parsing your `.github/dependabot.yml`:
>
>```
>The property '#/updates/1' is a duplicate. Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'
>The property '#/updates/3' is a duplicate. Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'
>```
>
>Please update the config file to conform with Dependabot's specification.
https://github.com/18F/identity-idp/runs/20273670820
=> Revert "Try configuring Dependabot for security updates"

dockerfiles/idp_review_app.Dockerfile
At the moment review apps are failing to write the pid to `tmp/pids` because that directory is not created as part of the docker image build. This creates that `tmp/pids` directory which allows the puma process to launch again.
=> Create tmp/pids directory for puma

Gemfile.lock
Updates Puma to the latest version (v6.4.2) to resolve a moderate severity security advisory.
See advisory: https://github.com/puma/puma/security/advisories/GHSA-c2f4-cvqm-65w2
See related previous (failed) attempt to automate this upgrade: #9877, #9879
Build should pass and application should run in local development.
=> Update Puma to 6.4.2

app/jobs/resolution_proofing_job.rb, app/services/idv/agent.rb, app/services/proofing/resolution/progressive_proofer.rb, spec/controllers/idv/verify_info_controller_spec.rb
A previous commit (https://github.com/18F/identity-idp/commit/e138a4904af3d7f4ed598d609a502fd8a8c1ae2a) changed the default values for `ipp_enrollment_in_progress` through stack for the vendor calls on the verify info step. This caused a number of `NoMethodError`s when the deploy happened. These errors results from the applicants address being nil when it was transformed for the LexisNexis API.
After some investigation it was discovered that the applicants address was being transformed for in-person proofing outside of in-person contexts. Since the user does not have the `identity_*` prefixed address values outside of in-person proofing this resulted in nil values for the address properties.
The cause of this is that `ipp_enrollment_in_progress` was introduced as a job argument with a …
=> Fix a 50/50 issue in the progress proofer

.gitlab-ci.yml
Swaps from the default pull policy of `IfNotPresent` to `Always` for images that are referencing `main` to prevent stale containers from hanging around and being used.
=> Swap pull policy for external images to Always to prevent staleness

app/controllers/idv/document_capture_controller.rb, app/controllers/idv/link_sent_controller.rb, app/services/idv/session.rb
This is an addendum for [LG-11698](https://cm-jira.usa.gov/browse/LG-11698)
Since we update `idv_session.selfie_check_performed` in DocumentCaptureController and LinkSentController, set it to nil in the respective StepInfo.undo_step so that it's cleared if someone resubmits an earlier step.
Specs deferred to make a more general solution for undo_step.
=> Undo idv_session.selfie_check_performed in undo step for DocumentCapture and LinkSent

package.json, webpack.config.js, yarn.lock
Updates `webpack-dev-server` and its dependencies to their latest versions:
- Bring in [latest features and bug fixes](https://github.com/webpack/webpack-dev-server/releases)
- Indirectly resolve a moderate severity security advisory with `follow-redirects` dependency
Process:
```
yarn remove webpack-dev-server
yarn add -D -W webpack-dev-server
yarn-deduplicate
```
`webpack-dev-server` is used in local development as the asset host for JavaScript files. Verify that there are no regressions in JavaScript behaviors or terminal errors when running `make run`. Bonus points by verifying that changes to JavaScript source files are reflected upon reload.
Verify there are no issues reported by `yarn audit`.
=> Update / reinstall webpack-dev-server to latest

app/services/gpo_reminder_sender.rb, spec/jobs/gpo_reminder_job_spec.rb, spec/services/gpo_reminder_sender_spec.rb
[LG-12015](https://cm-jira.usa.gov/browse/LG-12015)
If a user has an old GPO code that has received a reminder and a new code that is not yet eligible for a reminder, we were sending them an email every day. /o\ This was due to the join where a gpo code had a nil reminder_sent_at and a gpo code created in the reminder window.
Now we only send an email if we find a gpo code that meets all requirements.
Note that the new spec fails on `main` but passes on the branch.
=> LG-12015: stop spamming users who requested letters

package.json
Includes stylesheets located within the `app/components` directory for linting.
This matches build sources:
https://github.com/18F/identity-idp/blob/4c96efb7632de6218ab8c1f273bd0b6be2be3107/package.json#L21
See previous discussion: https://github.com/18F/identity-idp/pull/9840#discussion_r1442374486
Verify `lint:css` passes.
For bonus points, introduce a stylistic error to a `.scss` file within `app/components` and verify the same command fails.
Example:
```diff
diff --git a/app/components/captcha_submit_button_component.scss b/app/components/captcha_submit_button_component.scss
index 545f6b084..83a8d8851 100644
--- a/app/components/captcha_submit_button_component.scss
+++ b/app/components/captcha_submit_button_component.scss
@@ -2,2 +2,3 @@
visibility: hidden;
+  
}
```
```
$ yarn …
```
=> Include components directory in stylesheet linting

config/application.yml.default
`encrypted_document_storage_enabled` is currently `false` in production environments. This change makes it false by default in other environments as well.
=> Turn off encrypted_document_storage_enabled by default

app/services/device_name.rb, spec/decorators/device_decorator_spec.rb, spec/features/account/device_spec.rb, spec/forms/webauthn_setup_form_spec.rb, spec/services/device_name_spec.rb
[LG-11899](https://cm-jira.usa.gov/browse/LG-11899)
Updates `DeviceName.from_user_agent` to exclude the version number from the operating system ~for user agents which do not produce reliable version numbers~. **Edit:** See conversation stemming from https://github.com/18F/identity-idp/pull/9904#issuecomment-1887349723 and [related Slack thread](https://gsa-tts.slack.com/archives/C01710KMYUB/p1704985300785019), the version number is being removed for all devices.
In recent versions, Chromium has started to use a unified platform identifier in its user agent strings, as part of its user agent reduction effort. This means that we shouldn't rely on the version number being accurate. Since we include device names in user notifications for security alerts …
=> LG-11899: Remove unreliable operating system version from device names

dockerfiles/idp_review_app.Dockerfile
Changes the example service_providers.yaml to service_providers.yml to match where the `app/services/service_provider_seeder.rb` is actually looking for it.
=> Change service_providers.yaml to service_providers.yml

spec/features/idv/steps/in_person_opt_in_ipp_spec.rb, spec/support/features/doc_auth_helper.rb, spec/support/features/in_person_helper.rb
With multiple opt-in flags available, we want to test multiple variations of flag values.
[LG-11748](https://cm-jira.usa.gov/browse/LG-11748)
Add new spec file, split some of the logic it requires into helper files.
=> LG-11748 new spec for IPP opt-in flag variations

app/controllers/sign_up/completions_controller.rb, spec/controllers/sign_up/completions_controller_spec.rb
[LG-11882](https://cm-jira.usa.gov/browse/LG-11882)
Updates code paths referencing `DisposableDomain` to reference `DisposableEmailDomain` instead, added in #9894.
This will be followed-up with a pull request dropping the old table, to be merged in a separate deployment.
**Do not merge:** This should only be merged after #9894 is live in production.
Verify tests pass referencing the new table:
2. `rspec spec/controllers/sign_up/completions_controller_spec.rb`
Repeat testing plan from #9747 to verify no regressions in current logging.
=> LG-11882 (Step 2): Update code paths referencing DisposableDomain

app/controllers/concerns/idv/verify_info_concern.rb, config/application.yml.default, lib/identity_config.rb, spec/features/idv/doc_auth/verify_info_step_spec.rb
[LG-11979](https://cm-jira.usa.gov/browse/LG-11979)
Remove `aamva_sp_banlist_issuers` unused config value.
It was empty in application.yml.default, and it doesn't appear in the s3 buckets for any env.
=> LG-11979 remove aamva banlist config

app/javascript/packages/document-capture/components/acuant-capture.tsx, app/javascript/packages/document-capture/context/acuant.tsx, spec/javascript/packages/document-capture/components/acuant-capture-spec.jsx, spec/javascript/packages/document-capture/context/acuant-spec.jsx
[LG-10525](https://cm-jira.usa.gov/browse/LG-10525)
My goal was to reduce the confusing discrepancy between the threshold of `50`, which we get from the backend, and the front-end constants of `DEFAULT_ACCEPTABLE_GLARE_SCORE` and `DEFAULT_ACCEPTABLE_SHARPNESS_SCORE`, which were set to 30.  I wanted to remove those constants, but I am now thinking it may be better to leave them and just change them to 50.  Slack context [here](https://gsa-tts.slack.com/archives/C05HSH9RQ57/p1704834031072889).
=> LG-10525: Refactor AcuantContext

app/controllers/idv/in_person/address_controller.rb, spec/controllers/idv/in_person/address_controller_spec.rb
[LG-10480](https://cm-jira.usa.gov/browse/LG-10480)
Remove 404 action from post-FSM in person address controller to enable testing and eventually turning the feature flag on.
=> LG-10480 Remove in person address_controller 404 action

app/assets/stylesheets/components/_radio-button.scss, app/views/idv/how_to_verify/show.html.erb, spec/features/accessibility/idv_pages_spec.rb
[LG-12109](https://cm-jira.usa.gov/browse/LG-12109) Fix Accessibility Violation on How to Verify View
- Update h2 to so that is has a h3 class to fix accessibility violation on the How To Verify page
Gina Confirmed:
👀 Screenshots
=> Fix Accessibility Violation - Header level

app/services/reporting/account_reuse_report.rb, spec/services/reporting/account_reuse_report_spec.rb
[LG-12108](https://cm-jira.usa.gov/browse/LG-12108)
=> Lg 12108 fix reuse rates bug

app/services/gpo_reminder_sender.rb, spec/services/gpo_reminder_sender_spec.rb
[LG-12100](https://cm-jira.usa.gov/browse/LG-12100)
If a user had an expired gpo code and requested a new letter more than the reminder timeframe ago, the user would not have been sent a reminder for the second letter.
You can run the newly added spec on main, then again on this branch.
=> Fixes a bug in the Verify By Mail reminder logic.

app/controllers/concerns/idv/document_capture_concern.rb, app/controllers/concerns/idv/verify_info_concern.rb, spec/controllers/idv/in_person/verify_info_controller_spec.rb, spec/controllers/idv/verify_info_controller_spec.rb
The `Idv::Session#pii_from_doc` method has a name that suggests it returns the PII that is read from the document. Prior to this commit this was not the case because we merge data that was not read from the document into the `pii_from_doc` hash. This was done as a convenience so it is available when communicating to vendors in downstream steps.
This commit removes the merge and provides the additional data explicitly in down steam step.
=> Stop merging things that aren't PII from the document into `pii_from_doc`

app/forms/idv/api_image_upload_form.rb, app/models/document_capture_session.rb, app/services/doc_auth/acuant/responses/get_results_response.rb, app/services/doc_auth/lexis_nexis/responses/true_id_response.rb, app/services/doc_auth/mock/result_response.rb, app/services/doc_auth/response.rb, app/services/document_capture_session_result.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_success_with_liveness.json, spec/forms/idv/api_image_upload_form_spec.rb, spec/models/document_capture_session_spec.rb, spec/services/doc_auth/acuant/responses/get_results_response_spec.rb, spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb, spec/services/doc_auth/mock/result_response_spec.rb, spec/support/lexis_nexis_fixtures.rb
[LG-12036](https://cm-jira.usa.gov/browse/LG-12036)
Add _doc_auth_success_ and _selfie_success_ to _DocumentCaptureSessionResult_ as part of selfie feature. Also, added the two properties to response hash.
=> LG-12036: capture session props for doc_auth ans selfie

.gitlab-ci.yml
Effectively reverts #9803 now that the content freeze interval has ended
=> Remove temporary continuous integration check on content changes

app/controllers/idv/document_capture_controller.rb, app/javascript/packages/document-capture/components/acuant-capture.scss, app/javascript/packages/document-capture/components/acuant-capture.tsx, app/javascript/packages/document-capture/components/acuant-selfie-camera.tsx, app/javascript/packages/document-capture/components/acuant-selfie-capture-canvas.jsx, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, spec/javascript/packages/document-capture/components/acuant-selfie-camera-spec.jsx
[LG-11984](https://cm-jira.usa.gov/browse/LG-11984)
Display the selfie capture hint text to the user on the acuant capture canvas.
=> LG-11984: document capture selfie hint text

spec/components/previews/login_button_component_preview.rb
Related to #9840 - minor update to the component 
Quick 1 line change. 
Since this component is embedded in the dev doc user guide, we don't want anything that could create an error - but when selecting the empty option in the color params it created a stack trace so I removed it ( caught during acceptance )
=> Remove empty option in Login Button component preview

app/services/doc_auth/lexis_nexis/responses/true_id_response.rb, app/services/doc_auth/mock/result_response.rb, spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_with_face_match_fail.json, spec/services/doc_auth/lexis_nexis/requests/true_id_request_spec.rb, spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb, spec/support/lexis_nexis_fixtures.rb
[LG-12038](https://cm-jira.usa.gov/browse/LG-12038)
Updates the `all_passed?` method to take selfie success into account.
Also updates testing / fixtures.
=> LG-12038: Update all_passed? to consider selfie success

config/locales/countries/en.yml, config/locales/countries/es.yml, config/locales/countries/fr.yml
[Slack thread for context](https://gsa-tts.slack.com/archives/C0NGESUN5/p1705684776537539)
Our translation team identified that "Berundi" is not a recognized country name, nor is the `bl` abbreviation. These seem unused and duplicative of `bi: Burundi`, so we can remove them.
Previous similar cleanup PR: https://github.com/18F/identity-idp/pull/8279
=> Remove typo'd country "Berundi", duplicative of Burundi

app/services/analytics_events.rb, spec/controllers/sign_up/completions_controller_spec.rb
Updates `user_registration_complete` method signature to include the `disposable_email_domain` argument, which may be passed as a result of this code added in #9747:
https://github.com/18F/identity-idp/blob/43e0c4a5029ce159367ed28a272c670103e90308/app/controllers/sign_up/completions_controller.rb#L104-L106
**Why?**
- So that [Analytics Events documentation](https://handbook.login.gov/articles/analytics-events.html) accurately reflects the  available properties
- To enable discoverability based on searches performed within the `analytics_events.rb` (e.g. this was motivated by my own pursuit to jog my memory about which event this was logged on)
After merged, observe the parameter is visible in [Analytics Events documentation](https://handbook.login.gov/articles/analytics-events.html)
Build …
=> Document disposable email domain analytics parameter

lib/tasks/disposable_email_domains.rake
[LG-11882](https://cm-jira.usa.gov/browse/LG-11882)
Makes a few revisions to the Rake script for populating the disposable email domains table.
1. Per intent of the ticket, rename as "disposable **email** domains"
2. Avoid quotes in usage example which can produce an error when included
3. Reword from "URL" to "path" since the expected parameter is not a fully-qualified URL, it is expected to be a path fragment handled by `Identity::Hostdata.secrets_s3.readfile`
Once merged, I will plan to update the [corresponding rollplan document](https://gsa-tts.slack.com/archives/C0NGESUN5/p1705001993549269?thread_ts=1704997019.166689&cid=C0NGESUN5) accordingly.
=> LG-11882: Rename Rake task for disposable email domains

app/views/idv/welcome/show.html.erb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, spec/views/idv/welcome/show.html.erb_spec.rb
[LG-11986](https://cm-jira.usa.gov/browse/LG-11986)
The first bullet on the Welcome page is modified if a selfie check is required.
To see this locally, hard code the method `NullServiceProviderSession#selfie_required?` to return true.
<details>
<summary>Without selfie required (current view on `main`):</summary>
| en | es | fr |
|----|----|----|
| <img width="619" alt="LG-11968-orig" src="https://github.com/18F/identity-idp/assets/2583060/f8b96f8a-9379-4241-a908-e614021e4634"> | <img width="619" alt="LG-11968-orig-es" src="https://github.com/18F/identity-idp/assets/2583060/2fdf382f-aebe-4924-acc3-568816ae1888"> | <img width="619" alt="LG-11968-orig-fr" src="https://github.com/18F/identity-idp/assets/2583060/c1fa8580-54be-47a4-a2d2-9d81ed0cdfd9"> |
</details> …
=> LG-11986: Modify the Welcome screen if selfie required

Gemfile, Gemfile.lock, spec/controllers/saml_idp_controller_spec.rb, spec/features/saml/saml_spec.rb
https://cm-jira.usa.gov/browse/LG-12082
There has been an intermittent NoMethodError observed for SAML Authentication requests that seem to be because some SAML assertions are being sent with a `ds:X509Certificate` element that has is nil.
The `saml_idp` gem has been [updated to handle this case with a ValidationError](https://github.com/18F/saml_idp/blob/main/lib/saml_idp/xml_security.rb#L101-L103). An error will still raise, but it is more specific and we can rescue from it.
The other changes made in the saml_idp gem are:
- Creates an error attribute on the Request object
- While running the `valid?` method on a Request instance, bundles all errors so that they could be returned to the IdP to give partners more information about why their request may not be valid.
Neither of those …
=> LG-12082 Upgrade saml_idp gem

dockerfiles/idp_review_app.Dockerfile
Noticed while reviewing the build process of review app images that this debugging echo invalidates all caching after it. Many layers here should be cacheable, so this should speed up review app image building.
=> Remove echo command in image build that invalidates caching for all following layers

app/models/service_provider.rb, spec/services/push_notification/http_push_spec.rb
[LG-12101](https://cm-jira.usa.gov/browse/LG-12101)
Adds a clause to the `with_push_notification_urls` scope to only allow RISC push notifications to active integrations.
=> LG-12101 Add active to with_push_notification_urls scope

app/javascript/packages/build-sass/CHANGELOG.md, app/javascript/packages/build-sass/README.md, app/javascript/packages/build-sass/cli.js, app/javascript/packages/build-sass/index.js, app/javascript/packages/build-sass/package.json, yarn.lock
Enhances the `@18f/identity-build-sass` Sass compilation tool to use the new [Shared Resources API](https://github.com/sass/sass/blob/main/accepted/shared-resources.d.ts.md) added to Sass in a recent version. This feature is well-suited for our use-case, where we compile many different stylesheets, and each stylesheet shares a number of common resources (USWDS, etc.).
Average of `yarn build:css` on a set of 10 runs:
**Before:** 8.75s
**After:** ~6.71s~ 2.98s after 3fe4d75
**Diff:** ~-2.04s (-23.3%)~ -5.77s (-65.9%) after 3fe4d75
Verify that `yarn build:css` successfully outputs to `app/assets/build`
=> build-sass: Use new Shared Resources API

app/controllers/users/webauthn_controller.rb, app/controllers/users/webauthn_setup_controller.rb, app/forms/two_factor_authentication/webauthn_delete_form.rb, app/forms/two_factor_authentication/webauthn_update_form.rb, app/presenters/two_factor_authentication/webauthn_edit_presenter.rb, app/services/analytics_events.rb, app/views/accounts/_webauthn_roaming.html.erb, app/views/users/webauthn/edit.html.erb, config/locales/account/en.yml, config/locales/account/es.yml, config/locales/account/fr.yml, config/locales/two_factor_authentication/en.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml, spec/components/manageable_authenticator_component_spec.rb, spec/controllers/api/internal/two_factor_authentication/webauthn_controller_spec.rb, spec/controllers/users/webauthn_controller_spec.rb, spec/controllers/users/webauthn_setup_controller_spec.rb, spec/features/webauthn/management_spec.rb, spec/forms/two_factor_authentication/webauthn_delete_form_spec.rb, spec/forms/two_factor_authentication/webauthn_update_form_spec.rb, spec/presenters/two_factor_authentication/webauthn_edit_presenter_spec.rb, spec/views/accounts/_webauthn_roaming.html.erb_spec.rb, spec/views/users/webauthn/edit.html.erb_spec.rb
[LG-11759](https://cm-jira.usa.gov/browse/LG-11759)
Adds a rename/deletion interaction for Security Keys, similar to and extending what was introduced with [LG-11454](https://cm-jira.usa.gov/browse/LG-11454) (#9764).
2. Sign in
3. (If you don't already have a Security Key associated with your account, add one now)
4. On account dashboard, click "Manage" for your Security Key authenticator
5. Observe that you are able to manage the authenticator inline
6. Disable JavaScript and repeat steps 4 and 5, verifying that there is feature parity in the no-JavaScript experience
=> LG-11759: Add inline device nickname editing for security keys

app/controllers/concerns/saml_idp_auth_concern.rb, app/controllers/saml_idp_controller.rb, app/services/saml_request_validator.rb, config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml, spec/controllers/saml_idp_controller_spec.rb
[LG-12085](https://cm-jira.usa.gov/browse/LG-12085)
Adds a validation for whether the assertion has a blank certificate element.
There's probably a better way to do this, but creating a new validation in the `SamlRequestValidator` felt the cleanest in terms of being able to create an expected error for the user and return an event that tracks what's happening. Suggestions on other ways to do it welcome! Thanks.
=> LG-12085 Returns 400 when blank certificate element is passed through assertion

spec/forms/webauthn_setup_form_spec.rb
Revises `webauthn_setup_form_spec.rb` in hopes of reducing some test flakiness.
Example: https://gsa-tts.slack.com/archives/C0NGESUN5/p1706048041505969
The suspected cause is that `let(:user)` is lazily evaluated _after_ the form is already submitted, which is likely not the intent of the test setup. Eagerly assigning `let!(:user)` with existing authenticators should hopefully produce a more reliable result.
Verify the test passes:
```
rspec spec/forms/webauthn_setup_form_spec.rb
```
=> Improve reliability of WebauthnSetupForm spec

docs/sdk-upgrade.md
[LG-11917](https://cm-jira.usa.gov/browse/LG-11917)
Update document.
=> LG-11917: Update doc to use new version for all client in staging.

app/services/pii/attributes.rb, spec/services/pii/attributes_spec.rb
[LG-12027](https://cm-jira.usa.gov/browse/LG-12027)
This PR updates `Pii::Attributes` to normalize whitespace (via [squish](https://api.rubyonrails.org/classes/String.html#method-i-squish)).
=> LG-12027: Normalize whitespace in PII

app/javascript/packages/document-capture/components/in-person-location-full-address-entry-post-office-search-step.spec.tsx, app/javascript/packages/document-capture/components/in-person-location-post-office-search-step.spec.tsx
Improves reliability of JavaScript tests where a user is navigated after selecting a post office in the in-person proofing flow.
Example failure: https://gitlab.login.gov/lg/identity-idp/-/jobs/985447 (via #9972)
The behavior for redirecting after making a selection occurs only after a network request has finished, which may not be instantaneous.
https://github.com/18F/identity-idp/blob/a68df9295ea5f78d9bd4b100fde8a333dcb96514/app/javascript/packages/document-capture/components/in-person-location-post-office-search-step.tsx#L58-L61
```
yarn mocha app/javascript/packages/document-capture/components/in-person-location-post-office-search-step.spec.tsx app/javascript/packages/document-capture/components/in-person-location-full-address-entry-post-office-search-step.spec.tsx
```
=> Fix flakey JavaScript spec for async navigate

app/controllers/api/internal/two_factor_authentication/piv_cac_controller.rb, app/controllers/users/piv_cac_controller.rb, app/forms/two_factor_authentication/piv_cac_delete_form.rb, app/forms/two_factor_authentication/piv_cac_update_form.rb, app/presenters/two_factor_authentication/piv_cac_edit_presenter.rb, app/services/analytics_events.rb, app/views/accounts/_piv_cac.html.erb, app/views/users/piv_cac/edit.html.erb, config/locales/two_factor_authentication/en.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml, config/routes.rb, spec/controllers/api/internal/two_factor_authentication/piv_cac_controller_spec.rb, spec/controllers/users/piv_cac_controller_spec.rb, spec/features/users/piv_cac_management_spec.rb, spec/forms/two_factor_authentication/piv_cac_delete_form_spec.rb, spec/forms/two_factor_authentication/piv_cac_update_form_spec.rb, spec/presenters/two_factor_authentication/piv_cac_edit_presenter_spec.rb, spec/views/accounts/_piv_cac.html.erb_spec.rb, spec/views/accounts/show.html.erb_spec.rb, spec/views/users/piv_cac/edit.html.erb_spec.rb
[LG-11760](https://cm-jira.usa.gov/browse/LG-11760)
Adds the option for a user to manage (rename or delete) the MFA method PIV/CAC from the account dashboard.
=> LG-11760: Add inline device nickname editing for PIV/CAC

lib/action_account.rb, lib/data_pull.rb, lib/script_base.rb, spec/lib/action_account_spec.rb, spec/lib/script_base_spec.rb
We got a request to include the reason (which is currently logged to Slack) in the output of the command line as well
**Before**
```
+--------------------------------------+--------------------------------------------------+
| uuid                                 | status                                           |
+--------------------------------------+--------------------------------------------------+
| 770059eb-eacb-4738-9e0d-e39091c3372b | Error: User does not have a pending fraud review |
+--------------------------------------+--------------------------------------------------+
```
**After**
```
+--------------------------------------+--------------------------------------------------+---------+
| uuid                                 | status …
```
=> Add investigation reason to action-account output (LG-12212)

config/puma.rb
Removes the `bind` configuration from `config/puma.rb` to resolve an issue where `rails s` currently fails with an error:
```
/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/binder.rb:186:in `realdirpath': No such file or directory @ realpath_rec - /Code/identity-idp/shared (Errno::ENOENT)
```
Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1706044143605219
I'm still not entirely certain if `bind` would be necessary for any reason, but in my testing with both `rails s` and `make run` (Foreman), including with different hostname and port parameterization, it works as expected.
Previously: #9848 
Start the server by whichever method you prefer, e.g.
- `rails s` or `make run`
- `HOST=` or `PORT=` variations
- [HTTPS local …
=> Remove bind from Puma configuration

app/javascript/packages/build-sass/CHANGELOG.md, app/javascript/packages/build-sass/package.json, package.json, yarn.lock
Includes changes to prepare for a release of `@18f/identity-build-sass`:
- Bump dependencies
- Bump version
- Include version in `CHANGELOG.md`
Verify no regressions impacted by upgraded dependencies, e.g. can `make run` after installing.
Note that updating `browserslist` will have had an impact on supported browsers, which is intended / expected.
_browsers.json:_
```diff
- ["and_chr 119","and_uc 15.5","android 119","chrome 118","chrome 117","chrome 116","chrome 114","chrome 109","edge 118","edge 117","firefox 118","ios_saf 17.0","ios_saf 16.6-16.7","ios_saf 16.3","ios_saf 16.1","ios_saf 15.6-15.7","op_mob 73","opera 102","safari 17.0","safari 16.6","safari 15.6","samsung 22"]
+ ["and_chr 120","and_uc 15.5","chrome 120","chrome 119","chrome 118","chrome 109","edge 120","edge 119","firefox …
```
=> build-sass: Prepare 3.0.0 release

app/javascript/packages/normalize-yaml/CHANGELOG.md, app/javascript/packages/normalize-yaml/README.md, app/javascript/packages/normalize-yaml/cli.js, app/javascript/packages/normalize-yaml/index.js, app/javascript/packages/normalize-yaml/index.spec.js, app/javascript/packages/normalize-yaml/package.json, app/javascript/packages/normalize-yaml/visitors/collapse-sentence-spacing.js, app/javascript/packages/normalize-yaml/visitors/collapse-spacing.js, app/javascript/packages/normalize-yaml/visitors/index.js, config/locales/account_reset/en.yml, config/locales/errors/en.yml, config/locales/telephony/en.yml, config/locales/titles/fr.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml, config/locales/user_mailer/en.yml, config/locales/user_mailer/es.yml, config/locales/zxcvbn/fr.yml
Adds new behavior to the YAML normalization package to collapse spacing ~between sentences~ in YAML content.
Related discussion: https://gsa-tts.slack.com/archives/CEUQ9FXNJ/p1706111249614589
Verify that `make lint_yaml` is produces a successful exit code.
1. `make lint_yaml`
2. `echo $?`
3. Observe: `0`
Verify that reverting included normalizations and running normalization applies the changes to collapse spaces
1. `git checkout main -- config/locales`
2. `make normalize_yaml`
3. `git add config/locales`
4. `git status`
5. Observe "nothing to commit, working tree clean"
Verify that included specs pass:
1. `yarn mocha app/javascript/packages/normalize-yaml/index.spec.js`
=> normalize-yaml: Enhance to collapse spacing

app/components/manageable_authenticator_component.scss
[LG-12126](https://cm-jira.usa.gov/browse/LG-12126)
Adds appropriate media-based override to scss file pertaining to manageable authenticator component. 
Rename, Delete, Done, Save, and Cancel buttons remove default button component styling.
<details>
</details>
<details>
</details>
=> LG-12126 address buttons for inline MFA editing on mobile devices

app/models/service_provider_request.rb
We are working on imlementing a feature for partners to request identity proofing and authentication features using vectors of trust. This will involve sending param describing the vector of trust in the original SAML or OIDC request. Within the context of OIDC this param is named `vtr`.
This commit adds a `vtr` property to `ServiceProviderRequest`. This property is unused and unset in the persisted service provider request. This will allow us to write to it in the future and initialize `ServiceProviderRequest`s with the value without resulting in an `ArgumentError` (thus avoiding a dreaded 50/50 state bug)
=> Add the requested vectors of trust to `ServiceProviderRequest`

Gemfile.lock
We currently get a deprecation warning due to the Rack 3 upgrade. This PR fixes it by updating capybara.
```
Rack::Handler is deprecated and replaced by Rackup::Handler
```
=> Update capybara to fix Rack 3 deprecation message

Gemfile, Gemfile.lock
This PR is mostly for performance reasons. In https://github.com/rack/rack-attack/pull/597, an improvement was made to reduce the number of Redis calls in rack-attack.
For us, the improvement is pretty significant:
```
❤️ ❤️ ❤️  (Statistically Significant) ❤️ ❤️ ❤️
(0.2698 seconds) "rack attack update"
FASTER 🚀🚀🚀 by:
1.0643x [older/newer]
6.0431% [(older - newer) / older * 100]
(0.2872 seconds) "main"
Iterations per sample: 200
Samples: 200
Test type: Kolmogorov Smirnov
Confidence level: 99.0 %
Is significant? (max > critical): true
D critical: 0.15174271293851463
D max: 0.66
```
I had been planning on waiting for a full release, but it's been a bit over 6 months since the last one. We should revert back to the RubyGems releases once there has been a release that includes this change.
=> Update Rack Attack to reduce Redis calls

app/javascript/packs/click-immediate.ts, app/javascript/packs/openid-connect-redirect.ts, app/javascript/packs/saml-post.js, app/views/layouts/base.html.erb, app/views/openid_connect/shared/redirect_js.html.erb, app/views/saml_idp/shared/saml_post_binding.html.erb, app/views/shared/saml_post_form.html.erb, spec/support/oidc_auth_helper.rb, spec/support/saml_response_doc.rb, tsconfig.json
Consolidates `openid-connect-redirect.ts` and `saml-post.js` packs to a single `click-immediate.ts` which immediately clicks any elements annotated with a `data-click-immediate` attribute.
**Why?**
- The intended behavior of these scripts is essentially the same
- Remove legacy, non-typechecked JavaScript code
- Smaller file size
- Avoid announcing screen reader text for text which would not be visible for a JavaScript-enabled device
Using SAML & OIDC sample applications, verify there are no regressions in signing-in and redirecting back to the partner application.
Repeat testing instructions from #9790 to verify behavior of client-side OIDC redirect.
=> Consolidate SAML/OIDC redirect JavaScript

app/services/user_profiles_encryptor.rb, spec/services/user_profiles_encryptor_spec.rb
[LG-12239](https://cm-jira.usa.gov/browse/LG-12239)
Via CloudWatch monitoring, we determined that we had an edge case in our PII re-encryption code which caused us to occasionally fail when re-encrypting PII for a pending profile. We modified the code to re-encrypt pending profile's PII if present, and deactivate the profile if there is no associated PII.
=> Jmax/lg 12239 Pii re-encryption edge case

app/services/browser_support.rb, spec/services/browser_support_spec.rb
Adjusts browser support detection to consider all iOS browsers as checking their conformance against the iOS platform version, rather than for the specific browser. Since all browsers on iOS run on Safari ([at least for the time being](https://www.theverge.com/2024/1/25/24050478/apple-ios-17-4-browser-engines-eu)), this should produce a more accurate result for browser support.
This refactors the internal logic to force specific platforms to check a subset of the browser mappings rather than the full set, since in the case of Android WebView and iOS browsers, we only want to check Android or iOS Safari supports explicitly. This avoids having to add additional checks to exclude these platforms in other matchers.
Related Slack discussion: …
=> Browser support: Check iOS Safari engine for all iOS browsers

spec/mailers/previews/user_mailer_preview.rb
Updates the content for the new device mailer preview to more realistically match what a real user would receive.
As of #9904 (LG-11899), we no longer include operating system version in device names, so the example content "macOS 123" should be stripped of the version identifier.
An alternative approach could be to use the actual parsed device name from the current request user agent, which would help keep this more guaranteed as in-sync, but is perhaps too real / identifying to the current browser?
1. Go to http://localhost:3000/rails/mailers/user_mailer/new_device_sign_in
2. Observe there is no OS version shown
=> Remove OS version from new device mailer preview

app/javascript/packages/document-capture/components/document-capture-review-issues.tsx, app/javascript/packages/document-capture/components/document-capture-warning.tsx, app/javascript/packages/document-capture/components/document-capture.tsx, app/javascript/packages/document-capture/components/review-issues-step.tsx, app/javascript/packages/document-capture/components/unknown-error.tsx, app/javascript/packages/document-capture/context/upload.tsx, app/javascript/packages/document-capture/services/upload.ts, app/services/doc_auth/errors.rb, app/services/doc_auth/selfie_concern.rb, app/services/doc_auth_router.rb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml, spec/features/idv/doc_auth/document_capture_spec.rb, spec/fixtures/ial2_test_credential_no_liveness.yml, spec/fixtures/ial2_test_credential_poor_quality.yml, spec/services/doc_auth/mock/doc_auth_mock_client_spec.rb
https://cm-jira.usa.gov/browse/LG-11893
- This ticket changes the `<h1>` title of the screen you see after uploading a failing selfie.
- It changes the inline error message on the selfie field when you click `Try again online` and go back to the upload page.
- It also fixes the error handling for selfie errors in `selfie_concern.rb` which is currently broken in `main`.
Here's the related [figma](https://www.figma.com/file/YejFLjUrlzZNjjM8McoudH/MVP%3A-Selfie-UX?type=design&node-id=0-1&mode=design&t=Z8yla5PuEFGLB5Cm-0). And here are screenshots of the result.
Another set of interesting tests: Look at the logs specifically the "IdV: doc auth image upload vendor submitted" event
In that event, you should see for the failing selfie
- …
=> LG-11893: Selfie Liveness Errors on the FE

app/services/reporting/account_reuse_report.rb, spec/services/reporting/account_reuse_report_spec.rb
[LG-12117](https://cm-jira.usa.gov/browse/LG-12117)
This is an example of what the changes will make to the CSV output:
<details>
</details>
<details>
</details>
=> Lg 12117 summarize multiple apps

app/javascript/packages/form-steps/form-steps.spec.tsx, app/javascript/packages/form-steps/form-steps.tsx, app/javascript/packages/form-steps/use-history-param.spec.tsx, app/javascript/packages/form-steps/use-history-param.ts, app/javascript/packs/application.ts
Updates handling for how FormSteps considers step names from URL parameters, to ensure that URL changes which result in an invalid step (e.g. the skipnav navigation) would not have an effect on what's shown to the user, while avoiding bypassing skipnav URL change altogether.
This is an alternative to #7769. The primary goal of these changes is to avoid potential conflicts with default behavior of U.S. Web Design System by keeping the component implementations closer in sync. This also has a secondary effect of reducing the size of the common `application` JavaScript file that is loaded on every screen of the application.
There's a related USWDS issue at https://github.com/uswds/uswds/issues/5133 which may end up being closed as "working as intended", based on recent findings shared at …
=> Silently ignore invalid params for FormSteps 

app/services/reset_user_password.rb, spec/services/reset_user_password_spec.rb
Updates logic of password reset notifications to send to a user's confirmed email addresses, for consistency.
Verify that updated test passes:
```
rspec app/forms/security_event_form.rb
```
Testing this in practice may be more involved, either initializing the class in a `rails console` or enabling the `reset_password_on_auth_fraud_event` feature and sending a RISC event to the local server.
=> Send RISC password reset to confirmed emails

app/helpers/script_helper.rb, app/views/layouts/base.html.erb, app/views/layouts/component_preview.html.erb, spec/helpers/script_helper_spec.rb
Updates the ScriptHelper module to support per-script attributes, to be able to support loading the error tracking script asynchronously.
This is a continuation of the idea raised at https://github.com/18F/identity-idp/pull/8950#discussion_r1309333539 .
Specifically, `async` scripts will allow a page to finish loading before the script has been loaded and evaluated, thus reducing the time to complete page load ([see MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#async)). The effect here will probably not be dramatic, as the `track-errors` script is already the last element of the page (would not block rendering or initialization of other JavaScript) and is reasonably small (1.3kb minified and brotli'd).
Supporting arbitrary attributes could support future work …
=> Load error tracking script asynchronously

app/javascript/packages/document-capture/components/document-capture-warning.tsx, spec/javascript/packages/document-capture/components/document-capture-warning-spec.jsx
https://cm-jira.usa.gov/browse/LG-11893
After [this PR](https://github.com/18F/identity-idp/pull/9975) merged the attempts header started showing up twice in some situations.
This is because we have two very similar (but not identical) headers:
- `idv.failure.attempts_html`
- `idv.warning.attempts_html`
In the situation where the `isFailedDocType == false` and `isFailedSelfieLivenessOrQuality == true` we were sometimes showing both headers.
I wasn't able to reproduce for some reason, so I instead wrote a test.
=> LG-11893: Fix Doubled 'attempts' Warning

app/forms/idv/api_image_upload_form.rb, spec/forms/idv/api_image_upload_form_spec.rb
[LG-12183](https://cm-jira.usa.gov/browse/LG-12183)
During liveness selfie image metadata needs to be captured, logged and used to determine doc auth vendor workflow.
1. Complete doc auth with selfie on Desktop:
in logs, verify that _IdV: doc auth image upload vendor submitted_ analytics event is logged with selfie source: _upload_
2. Complete doc auth with selfie using autocapture on mobile device:
in logs, verify that _IdV: doc auth image upload vendor submitted_ analytics event is logged with selfie source: _acuant_
=> LG-12183: selfie image metadata

app/controllers/concerns/idv_session_concern.rb, app/controllers/idv_controller.rb, spec/controllers/idv_controller_spec.rb, spec/features/idv/step_up_spec.rb, spec/support/features/doc_auth_helper.rb, spec/support/features/idv_helper.rb
Link to the relevant tickets:
* [LG-11699](https://cm-jira.usa.gov/browse/LG-11699)
* [LG-11700](https://cm-jira.usa.gov/browse/LG-11700)
Refines "does this user need idv?" checks to take into account when users need to step up from verified to verified with biometric.
1. Make sure you have `doc_auth_selfie_capture_enabled: true` in your application.yml
2. Go through IdV and verify without a biometric
3. Make a request from an SP with biometric comparison enabled
4. Go back through IdV, this time verifying with a selfie
5. Ensure you get redirected back to the SP
6. Log in again from the SP with biometric comparison enabled and ensure you don't have to re-repeat the idv flow.
=> LG-11699/LG-11700: Allow verified user to repeat idv if they need biometric

app/models/service_provider_request.rb, app/services/service_provider_request_proxy.rb
In #9991 the `vtr` property is added to the `ServiceProviderRequest`. Since the `vtr` property is introduced there it is unsafe to create a `ServiceProviderRequest` record with `vtr` during a deploy since some instances may have code that is unaware of the `vtr` property and will result in an `ArgumentError` when creating a `ServiceProviderRequest`
Once the changes in #9991 are deployed it should be safe to create records with the `vtr` property. This commit does that in the `ServiceProviderRequestProxy`.
This should not be merged until the changes in #9991 are merged and deployed all the way through production.
=> Read `vtr` property while reading and writing `ServiceProviderRequest`

Gemfile.lock
From `bundler-audit`:
```
Name: nokogiri
Version: 1.16.0
GHSA: https://github.com/advisories/GHSA-xc9x-jj77-9p9j
Criticality: Unknown
URL: [GHSA-xc9x-jj77-9p9j](https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-xc9x-jj77-9p9j)
Title: Improper Handling of Unexpected Data Type in Nokogiri
Solution: upgrade to '>= 1.16.2'
```
=> Update nokogiri to 1.16.2

docs/sdk-upgrade.md
[LG-11918](https://cm-jira.usa.gov/browse/LG-11918)
Documentation update to monitor for 3 days instead of two weeks during an SDK upgrade. We found this to be sufficient time to monitor.
=> LG-11918: Update documentation for SDK monitoring length to 3 days

app/forms/openid_connect_authorize_form.rb, app/models/federated_protocols/oidc.rb, app/models/federated_protocols/saml.rb, app/services/analytics_events.rb, app/services/service_provider_request_handler.rb, app/services/store_sp_metadata_in_session.rb, config/application.yml.default, config/locales/openid_connect/en.yml, config/locales/openid_connect/es.yml, config/locales/openid_connect/fr.yml, lib/identity_config.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/forms/openid_connect_authorize_form_spec.rb, spec/services/store_sp_metadata_in_session_spec.rb
The commit on here that was un-reverted was problematic because of a `NoMethodError` when calling `empty?` on `nil` here:
```ruby
validates :acr_values, presence: true, if: ->(form) { form.vtr.empty? }
```
This commit replaces `#empty?` with `#blank?` which will work on nil. Additionally the `#parse_vtr` method was modified to consistently return `nil` if either a `vtr` param is not provided or the `vtr` param is not enabled.
Tests were added to cover this case.
=> Swap `#empty?` with `#blank?` and add tests

app/controllers/application_controller.rb, spec/controllers/application_controller_spec.rb
[LG-12195](https://cm-jira.usa.gov/browse/LG-12195)
Added  `ApplicationController#resolved_authn_context_result` to return an authn context when supplied with the service provider, and vtr and acr values.
=> LG-12195 Add a method to get resolved authn context

app/mailers/user_mailer.rb, app/services/analytics_events.rb, lib/email_delivery_observer.rb, spec/mailers/user_mailer_spec.rb
This adds additional metadata and logs the `email_address` record identifier we sent the email to so that we can better debug issues with email delivery.
=> Include email_address_id when logging that an email was sent

app/services/document_capture_session_result.rb
[LG-12200: Remove the selfie_success field from DocumentCaptureSessionResult](https://cm-jira.usa.gov/browse/LG-12200)
- Follow-up to [LG-12159: Change selfie_success to return a symbol](https://cm-jira.usa.gov/browse/LG-12159) and PR #9953 
- In the above PR, we renamed `selfie_success` to `selfie_status`
- We are removing `selfie_success` in this PR
- As you can see, it is quite a petite PR!
- Run automated tests
=> LG-12200: Remove selfie_success field from DocumentCaptureSessionResult

app/controllers/openid_connect/authorization_controller.rb, app/controllers/saml_idp_controller.rb, app/controllers/sign_up/registrations_controller.rb, app/controllers/users/sessions_controller.rb, app/services/analytics_events.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/features/users/sign_up_spec.rb, spec/support/shared_examples/sign_in.rb
[LG-12249](https://cm-jira.usa.gov/browse/LG-12249)
Updates "SP redirect initiated" to include a detail describing the sign-in flow used to get to that point, either `:sign_in` or `:create_account`.
The intent of this detail is to be able to understand average times to create an account or sign in. This will be used in combination with the `session_duration` property to produce average/median/percentile values for account creation and sign in timings.
1. Have both `identity-idp` and either [OIDC sample app](https://github.com/18F/identity-oidc-sinatra) or [SAML sample app](https://github.com/18F/identity-saml-sinatra) running
2. In a separate terminal tab, run `EVENT_NAME="SP redirect initiated" make watch_events`
3. Start from http://localhost:9292 (OIDC) or http://localhost:4567 (SAML) …
=> LG-12249: Log sign-in flow for SP redirect analytics event

app/services/document_capture_session_result.rb
[LG-12033](https://cm-jira.usa.gov/browse/LG-12033)
Remove the selfie_check_performed attribute from the DocumentCaptureSession result which is no longer used.
=> LG-12033: remove selfie_check_performed attribute from DocumentCaptureSessionResult

app/services/reporting/account_reuse_report.rb, spec/services/reporting/account_reuse_report_spec.rb
changelog: Internal, Reporting, Exclude deleted users from Reuse Rate Report
[LG-12300](https://cm-jira.usa.gov/browse/LG-12300)
The Reuse Rate Report within the Monthly Key Metrics Report had been including deleted users in the results, these changes remove the deleted users from the queries so they are not counted.
=> LG-12300 Exclude Deleted Users from the Reuse Report

app/controllers/openid_connect/authorization_controller.rb, app/controllers/saml_idp_controller.rb, spec/features/openid_connect/openid_connect_spec.rb, spec/features/saml/saml_logout_spec.rb, spec/features/saml/saml_spec.rb
[LG-12070](https://cm-jira.usa.gov/browse/LG-12070)
Related issue: https://github.com/18F/identity-idp/issues/9407
Updates OIDC and SAML controllers to set redirect URL ahead of concurrent session logout, to repeat the authentication request as redirect destination for the logout. This resolves an issue where authentication request details would otherwise be lost during the concurrent session logout.
The solution here is essentially the same as in LG-11777 (#9842), except applied to the authentication endpoints in addition to the logout endpoints handled there. 
Prerequisite: Have both [OIDC](https://github.com/18F/identity-oidc-sinatra) and [SAML](https://github.com/18F/identity-saml-sinatra) sample applications running separate from the IdP
1. Start at http://localhost:9292 (OIDC) or …
=> LG-12070: Maintain incoming request for concurrent session logout

.eslintrc
Updates existing React ESLint overrides to specifically target individual failures in individual files.
Also escalates ESLint warnings to errors. Warnings are ignored; either we care enough to fail the build or they shouldn't be flagged at all.
**Why?**
- Prevent the addition of new files with problems (i.e. avoid directory glob pattern exclusions)
- Prevent the addition of new problems in existing files which don't already have that problem (i.e. per-rule file overrides)
- Avoid maintenance overhead for non-problematic files ([example](https://github.com/18F/identity-idp/pull/10023#pullrequestreview-1860379901))
`yarn lint` passes
=> Target specific failing files for ESLint React overrides

app/forms/idv/doc_pii_form.rb, app/presenters/image_upload_response_presenter.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/features/idv/doc_auth/redo_document_capture_spec.rb, spec/forms/idv/doc_pii_form_spec.rb, spec/presenters/image_upload_response_presenter_spec.rb
[LG-12081](https://cm-jira.usa.gov/browse/LG-12081)
Here I kind of flag it for `front` and `back` error in `DocPiiForm` using `after_validation` callback. This works nicely but it includes the `front` and `back` as the part of `error_details` in event log.
The other way is like hat @amirbey  did to consolidate the error like following, but doing here is kind of scattering the logic around and is not the best for awareness.
https://github.com/18F/identity-idp/blob/a199bdd3545917f941ede1c3c5dc6ce08786a281/app/presenters/image_upload_response_presenter.rb#L15-L17.  
```ruby
if form_response_errors.one? { |k, v| %i[name dob dob_min_age state ... ... ].include?(k) }
form_response_errors.merge!(
front: [I18n.t('doc_auth.errors.general.multiple_front_id_failures')], …
```
=> LG-12081: set inline error when there is pii error.

app/services/doc_auth/lexis_nexis/request.rb, spec/services/doc_auth/lexis_nexis/lexis_nexis_client_spec.rb
Doc auth requests are failing with 400 and analytics do not contain any details as to why.  This change logs the error status code and message provided by the vendor.
https://gsa-tts.slack.com/archives/C05HSH9RQ57/p1706638806036759
[LG-12354](https://cm-jira.usa.gov/browse/LG-12354)
=> LG-12354: Store error code and message for 400 doc auth responses from LN

app/controllers/two_factor_authentication/piv_cac_verification_controller.rb, spec/controllers/sign_up/registrations_controller_spec.rb, spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb, spec/controllers/users/sessions_controller_spec.rb
[LG-12249](https://cm-jira.usa.gov/browse/LG-12249)
Assigns `session[:sign_in_flow]` to `:sign_in` when attempting to authenticate using a PIV.
This builds upon #10029 to cover additional sign-in flows.
Repeat testing instructions from #10029, specifically using PIV to sign in.
=> LG-12249: Set sign-in flow session value for PIV sign-in

config/pinpoint_supported_countries.yml, lib/pinpoint_supported_countries.rb
Fixes an error causing all builds to fail due to missing phone data for the "XV" country code listed on [Pinpoint's documentation](https://docs.aws.amazon.com/pinpoint/latest/userguide/channels-sms-countries.html). The Kosovo country code is "XK" in the Phonelib library, so the changes here introduce a mapping from "XV" to "XK".
- https://docs.aws.amazon.com/sms-voice/latest/userguide/phone-numbers-sms-by-country.html
- https://en.wikipedia.org/wiki/XK_(user_assigned_code)
Confirm no errors when running `make lint_country_dialing_codes`
=> Remap Pinpoint XV country code to XK (Kosovo)

app/services/doc_auth/lexis_nexis/request.rb, spec/services/doc_auth/lexis_nexis/lexis_nexis_client_spec.rb
[LG-12355](https://cm-jira.usa.gov/browse/LG-12355)
Store reference sent in LN request in DocAuth::Response extras for failed requests.
=> LG-12355: store reference in doc auth response extras for failed LN  http requests

app/services/otp_rate_limiter.rb, app/services/rate_limiter.rb, spec/features/idv/steps/request_letter_step_spec.rb, spec/services/rate_limiter_spec.rb
[LG-12134](https://cm-jira.usa.gov/browse/LG-12134)
Changed Redis calls in RateLimiter to always use absolute time values, instead of relative ones.
This change is internal to the timestamp class, and not visible outside it.
=> Jmax/LG-12134 Spike use absolute timestamps for rate limiter Redis timeouts.

app/javascript/packages/document-capture/context/file-base64-cache.ts
Converting `file-base-64-cache.js` to typescript.
=> Convert file-base64-cache.js to typescript

app/services/document_capture_session_result.rb, spec/features/idv/doc_auth/document_capture_spec.rb, spec/fixtures/ial2_test_credential_barcode_attention_no_dob.yml
[LG-12370](https://cm-jira.usa.gov/browse/LG-12370)
success_status to check if pii exists
=> LG-12370: success_status to check if pii exists

app/services/doc_auth/mock/doc_auth_mock_client.rb, app/services/doc_auth/mock/result_response.rb, spec/services/doc_auth/mock/doc_auth_mock_client_spec.rb, spec/services/doc_auth/mock/result_response_spec.rb
[LG-12332](https://cm-jira.usa.gov/browse/LG-12332)
When selfie image(not yaml) attached, mock client failed to pass in dev mode, due to the fact that we default to :not_processed for `selfie_status`.
So we changed to return `:success` if selfie is required and missing` portrait_match_results` in `result_response`.
=> LG-12332: fix mock client to pass when using real image.

.gitlab-ci.yml
Follow-up to #10020 that will hopefully let CI go green on `main`
=> Set allow_failure: true for production_deploy

app/controllers/application_controller.rb, app/helpers/application_helper.rb, app/views/layouts/account_side_nav.html.erb, app/views/layouts/application.html.erb, app/views/layouts/base.html.erb, app/views/layouts/flow_step.html.erb, app/views/layouts/no_card.html.erb, app/views/openid_connect/shared/redirect.html.erb, app/views/openid_connect/shared/redirect_js.html.erb, app/views/shared/saml_post_form.html.erb, spec/features/openid_connect/authorization_confirmation_spec.rb
This updates the "base" layout to be less opinionated, so that it can be used as a—wait for it—_base layout_ by more of our specialized layouts.
This is related to the comment at https://github.com/18F/identity-idp/pull/9985#discussion_r1468167530 .
**Why?**
- **Reduce duplication.** There's already a fair bit of duplication between `base.html` and alternative layouts like `saml_post_form.html.erb`
- **Avoid inconsistencies and errors.** For example, currently in production these specialized layouts lack a `lang` attribute on the `<html>` and therefore may read content in the wrong language for assistive technology
- **Improve compatibility of per-component assets.** I suspect this may indirectly address the issue described in #10065 regarding "automatic component asset loading doesn't …
=> Update base layout to be base-ier

app/controllers/users/sessions_controller.rb, app/views/devise/sessions/new.html.erb, spec/views/devise/sessions/new.html.erb_spec.rb
This ivar is part of a conditional that is used to determine if the link to authenticate with a PIV or CAC is visible.
It was added here: https://github.com/18F/identity-idp/commit/ccc40ed7e41e2f67063b3d7455b0990b0bd11bab
The computation for this value looks like this:
```ruby
def sp_session_ial
sp_session[:ial].presence || 1
end
```
This will always have a truthy value unless the requested IAL is IALMax (the integer value corresponding to IALMax is 0). After reading through the commit history I beleive this IALMax behavior is unintentional.
I believe this value was originally intended to require the user to enter a password if identity proofing was required. It appears this requirement changed but the ivar was left behind. This commit removes it.
=> Remove unused `@ial` ivar from `Users::SessionsController`

app/services/doc_auth/lexis_nexis/responses/true_id_response.rb, spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_attention_barcode_with_face_match_fail.json, spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb, spec/support/lexis_nexis_fixtures.rb
[LG-12445](https://cm-jira.usa.gov/browse/LG-12370)
Remove all_passed which is redundant
Update result_success so that Attention to Barcode does not override portrait match failure.
Unit tests added
=> LG-12445: Attention to Barcode does not override a failed portrait match

app/controllers/users/sessions_controller.rb, spec/features/visitors/bad_password_spec.rb
[LG-12458](https://cm-jira.usa.gov/browse/LG-12458)
Updates session lockout mechanism to use Warden's lock functionality to prevent any accidental sign-ins from occurring in the request.
```
rspec spec/features/visitors/bad_password_spec.rb
```
=> LG-12458: Use Warden lock mechanism for session lockout

app/controllers/concerns/idv/document_capture_concern.rb, app/controllers/idv/document_capture_controller.rb, app/controllers/idv/hybrid_mobile/document_capture_controller.rb, app/controllers/idv/link_sent_controller.rb
[LG-12428](https://cm-jira.usa.gov/browse/LG-12428)
Background
DocumentCaptureConcern#extract_pii_from_doc is a bit misleading.  it declares response in it's signature as if it receives a DocAuth::Response when in fact the argument passed is a DocumentCaptureSessionResult which does not need to be passed as an argument.
1. remove the confusing and unnecessary response argument from the extract_pii_from_doc method
2. remove DocumentCaptureController#document_capture_session_result method that was used to fetch the argument passed in to extract_pii_from_doc
=> LG-12428:  extract_pii_from_doc refactor

app/controllers/application_controller.rb, app/services/vot/parser.rb, spec/controllers/application_controller_spec.rb
Currently when there is no SP present `ApplicationController#resolved_authn_context_result` raises an error when it tries to resolve an Authn Context without a VoT or ACR values. This creates an issue when this method is called outside the context of a service provider request.
In order to let the method be called outside of an SP context this commit introduces a no-SP result which can be returned when no SP is present. This allows the method to be called and requirements for authentication and identity-verification to be inspected without a service provider.
This method opts to base the conditional on whether an SP is present rather than whether ACR values or a VoT is present. This preserves behavior where a missing ACR value and VoT will cause an error to be raised. In the case where …
=> Return a default result from `#resolved_authn_context_result` when no SP is present

app/javascript/packages/analytics/is-trackable-error-event.spec.ts, app/javascript/packages/analytics/is-trackable-error-event.ts
Updates logic of `isTrackableError` to ignore any errors which occur from the same host, but which aren't from JavaScript files.
Following #10027, data for `filename` shows that errors are originating from filenames such as `https://secure.login.gov/`. The hypothesis is that app webviews or browser extensions may be injecting scripts evaluated on the page and throwing errors, which we want to ignore.
1. `echo "setTimeout(() => { throw new Error('example'); }, 100)" >> app/javascript/packages/analytics/index.ts`
2. `NODE_ENV=production yarn build`
3. `rails s`
4. Go to http://localhost:3000
5. Validate NewRelic logging. Easiest way is to add a `binding.pry` at [the `notice_error` call](https://github.com/18F/identity-idp/blob/0f8b27c92021d875eab5bcdb399d229427c29e95/app/services/frontend_er …
=> Ignore frontend errors not originating from application script

app/controllers/frontend_log_controller.rb, app/services/frontend_logger.rb, spec/controllers/frontend_log_controller_spec.rb, spec/services/frontend_logger_spec.rb
Removes fallback logging for frontend events which aren't recognized.
This was added as a temporary measure in #9438 to ensure that we hadn't missed any frontend events.
There are no logs associated with this event, indicating that all of our event names are captured.
```
rspec spec/controllers/frontend_log_controller_spec.rb spec/services/frontend_logger_spec.rb
```
Bonus: Initiate a request to `POST /api/logger` with an unrecognized event name and verify you get a 400 response.
=> Remove fallback logging for unknown frontend event

app/forms/openid_connect_logout_form.rb, app/validators/idv/form_address_validator.rb, app/validators/idv/form_ssn_format_validator.rb, app/validators/idv/form_state_id_validator.rb
I noticed this while doing some testing, but it seems like we only return English error messages for these. I haven't found a good way to detect it comprehensively yet though.
=> Fix static usage of error messages that results in them being untranslated

Makefile, docs/local-development.md, package.json, spec/rails_helper.rb, yarn.lock
Optimizes a few tasks surrounding JavaScript build:
- Runs JavaScript and stylesheet asset compilation in parallel for feature spec pre-build
- Runs `package.json` `build` (now `build:js`) subtasks in parallel
- Takes advantage of Makefile "up to date" to avoid unnecessary `browsers.json` build
- Note that `yarn generate-browsers-json` is already pretty fast (0.22s on average) so the room for optimization is minimal, but an up-to-date `make browsers.json` is faster (0.065s), and the approach allows for some tolerance if ever the work involved in `generate-browsers-json` became more involved / time-consuming.
Diff:
```diff
diff --git a/spec/rails_helper.rb b/spec/rails_helper.rb
index cd31bb0e6..05750c1d3 100644
--- a/spec/rails_helper.rb
+++ b/spec/rails_helper.rb
@@ -80,4 +80,7 @@ …
```
=> Parallelize feature spec build, leverage Make up-to-date for browsers.json

spec/factories/auth_app_configurations.rb, spec/factories/piv_cac_configurations.rb
Updates spec factories for `AuthAppConfiguration` and `PivCacConfigurations` to ensure uniqueness of the generated name.
Previous flakey test failures demonstrate that this isn't always unique ([example](https://gitlab.login.gov/lg/identity-idp/-/jobs/1025178)).
`Faker::Lorem.word` chooses a single word from [a set of 251 words](https://github.com/faker-ruby/faker/blob/main/lib/locales/en/lorem.yml#L4C14-L4C1948), so the likelihood of conflict between two samples is reasonably high.
The Faker library documents how to ensure unique values, using the `.unique` method: https://github.com/faker-ruby/faker#ensuring-unique-values
Build should pass.
=> Guarantee uniqueness of MFA spec factory names

db/primary_migrate/20240215212318_add_vtr_and_acrvalues_to_identities.rb, db/schema.rb
[LG-12150](https://cm-jira.usa.gov/browse/LG-12150)
This PR is the first of a series of steps of getting acr values and vots into the identity token we send back to the service provider. 
We first want to add acr_values and vtr to the identities table so that they will be saved so we can use them later in the creation of the identity token.
=> Lg-12150 add vtr and acr_values to identity table

lib/cleanup/destroyable_records.rb, spec/lib/cleanup/destroyable_records_spec.rb
[LG-11737](https://cm-jira.usa.gov/browse/LG-11737)
When going to delete some unused service providers ran into an error where it tried to loop through integration usages but some of the unused SP's do not have any associated usages (or iaa_orders). Tweaked the script to account for SP's that don't have these associations.
=> LG-11737: delete unused service providers

app/presenters/image_upload_response_presenter.rb, spec/features/idv/doc_auth/document_capture_spec.rb, spec/fixtures/ial2_test_credential_barcode_attention_no_address.yml
[LG-12393](https://cm-jira.usa.gov/browse/LG-12393)
Only present BarcodeWarning when the image upload is successful as in the doc auth and pii validation is successful.
<details>
</details>
<details>
</details>
=> LG-12393: barcode attention should only be shown when image upload is successful

app/assets/stylesheets/components/_language-picker.scss, app/components/language_picker_component.html.erb
Updates footer language picker expander icon to use `IconComponent`.
This is a planned follow-on to #10065.
**Why?**
- Eliminates at least one network request (image) from the common layout
- Simplifies and reduces the size of the application stylesheet
- Consolidates on a common icon glyph for this sort of expander, also used in the "Here's how you know" banner (single "expand_more" icon vs. [six variations of `angle-arrow-*`](https://github.com/18F/identity-design-system/tree/main/src/img)
- Enables us to delete those icons from the design system
- Avoids flickering that can occur initially when expanding, due to network request for separate image (rotates a single image instead)
- Nifty animation! (disabled when [preferred](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers …
=> Implement language picker expander as icon

app/models/monthly_auth_count.rb, db/primary_migrate/20240216184124_drop_monthly_auth_counts.rb, db/schema.rb
[LG-12483](https://cm-jira.usa.gov/browse/LG-12483)
We stopped using this table in #3634, and that PR created `monthly_sp_auth_counts`. That table was dropped in #7312. Along similar lines, this PR drops the `monthly_auth_counts` table.
=> Drop unused monthly_auth_counts table (LG-12483)

app/controllers/users/sessions_controller.rb, app/services/analytics_events.rb, spec/controllers/users/sessions_controller_spec.rb
Removes the `stored_location` analytics property from the 'Sign in page visited' and 'Email and Password Authentication' analytics events.
This references a session value `user_return_to` that is not assigned, last referenced removed in #5413.
Tangentially-related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1706906370684589
**Why?**
- Reduce logging payload size for frequent analytics events
- Avoid misleading developers to imply we track return location for sign-in, since we don't ([LG-3737](https://cm-jira.usa.gov/browse/LG-3737))
1. In a separate terminal process, run `make watch_events`
3. Observe logged event for "Sign in page visited" does not include `stored_location`
4. Sign in
5. Observe logged event for "Email and password …
=> Remove unused stored_location analytics parameter

lib/cleanup/destroyable_records.rb, spec/lib/cleanup/destroyable_records_spec.rb
[LG-11737](https://cm-jira.usa.gov/browse/LG-11737)
Was a little too hasty with #10106 and realized the issue stems not from `nil` `integration_usage` needing to be an empty array but for service providers which have no integrations at all
=> LG-11737 Removing providers without integrations

app/controllers/idv/personal_key_controller.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/features/idv/analytics_spec.rb
[LG-12283](https://cm-jira.usa.gov/browse/LG-12283)
Added code to `PersonalKeyController#show` to catch a situation where we very occasionally have no PII available in the session when we are about to try to encrypt PII from the session.
In this case, we redirect to the code for a missing or bad personal key, which prompts the user for their password and retrieves the PII. We also arrange to return here afterward.
```
idv_session.personal_key = nil
user_session[:encrypted_profiles] = nil
continue
```
```
continue
```
<details>
<summary>Re-entering your password:</summary>
</details>
<details>
<summary>Personal key page:</summary>
</details>
=> LG-12283 handle missing PII in session

app/controllers/concerns/saml_idp_auth_concern.rb, app/controllers/saml_idp_controller.rb, app/models/federated_protocols/saml.rb, app/presenters/saml_request_presenter.rb, app/services/attribute_asserter.rb, app/services/ial_context.rb, app/services/vot/parser.rb, spec/presenters/saml_request_presenter_spec.rb, spec/services/attribute_asserter_spec.rb, spec/services/ial_context_spec.rb
SAML SPs can request IALMax by using an IAL authn context that does not require proofing and including a Authn Context Comparison value of "minimum". This essentially says that the "IAL1" Authn context is the minimum acceptable context so "IAL2" is also acceptable.
This is problematic for the new `AuthnContextResolver` since it does not have visibility into these attributes on the SAML request when resolving the authn context.
This commit addresses the issue by returning the IALMax Authentication Context Reference from `Saml#ial` in this case. This way the IALMax value is picked up downstream by the `AuthnContextResolver`.
This type of request has a few differences from an IALMax request with the IALMax authn context reference:
- If a service provider that cannot make IAL2 requests makes …
=> Recognize SAML IALMax using authn context comparison in SAML protocol

app/javascript/packages/stylelint-config/CHANGELOG.md, app/javascript/packages/stylelint-config/package.json, package.json, yarn.lock
Closes #10124
Updates `@18f/identity-stylelint-config` to support Stylelint v16.
As noted in included revisions to the package's CHANGELOG.md, refer to dependency release notes for full details:
- [`stylelint-prettier`](https://github.com/prettier/stylelint-prettier/blob/main/CHANGELOG.md)
- [`stylelint-config-recommended-scss`](https://github.com/stylelint-scss/stylelint-config-recommended-scss/blob/master/CHANGELOG.md)
- [`stylelint-scss`](https://github.com/stylelint-scss/stylelint-scss/blob/master/CHANGELOG.md)
- [`stylelint-config-recommended`](https://github.com/stylelint/stylelint-config-recommended/blob/main/CHANGELOG.md)
```
yarn lint:css
```
=> Bump Stylelint dependency to support v16

app/forms/openid_connect_authorize_form.rb, app/services/identity_linker.rb, spec/forms/openid_connect_authorize_form_spec.rb, spec/services/identity_linker_spec.rb
[LG-12150](https://cm-jira.usa.gov/browse/LG-12150)
This is part two of being able to create an identity token with acr and vectors of trust values. This writes acr_values and vtr params into the identities table so we will be able to read from them later when creating the id token.
=> LG-12150 Write acr_values and vtr to identites table using identity linker

app/controllers/application_controller.rb, app/controllers/concerns/billable_event_trackable.rb, app/controllers/concerns/idv_session_concern.rb, app/controllers/concerns/verify_sp_attributes_concern.rb, app/controllers/openid_connect/authorization_controller.rb, app/controllers/saml_idp_controller.rb, app/controllers/sign_up/completions_controller.rb, app/controllers/users/passwords_controller.rb, app/controllers/users/piv_cac_login_controller.rb, spec/controllers/concerns/billable_event_trackable_spec.rb, spec/controllers/idv_controller_spec.rb, spec/controllers/sign_up/completions_controller_spec.rb, spec/controllers/users/piv_cac_login_controller_spec.rb
In a previous commit the `resolved_authn_context_result` was introduced to return a `Vot::Parser::Result` object that described the requirements for the current SP request considering SP default options. This is intended to be used to replace the keys in the `sp_session` that serve this purpose including the `ial` key.
This commit replaces places where the `sp_session[:ial]` value is read with new reads to the `resolved_authn_context_result`.
=> LG-12261 Stop reading from `sp_session[:ial]`

app/controllers/sign_up/completions_controller.rb, spec/controllers/sign_up/completions_controller_spec.rb
The `sp_session[:ial2]` and `sp_session[:ialmax]` values are being retired in favor of `resolved_authn_context_result.identity_proofing?` and `resolved_authn_context_result.ialmax?`. This commit does the work of removing these 2 values from `SignUp::CompletionsController`. This removes the last of the references for `sp_session[:ialmax]` so once this is merged and deployed we can stop writing that value.
=> LG-12263 Remove legacy SP-sesison values from completions controller

app/controllers/application_controller.rb, app/controllers/sign_up/completions_controller.rb, app/helpers/application_helper.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/controllers/sign_up/completions_controller_spec.rb, spec/controllers/users/personal_keys_controller_spec.rb, spec/support/features/session_helper.rb
We are replacing the `sp_sesison[:ial2]` value with checks against `resolved_authn_context_result.identity_proofing?`. This commit removes the places where we are reading `sp_sesison[:ial2]`. Once this is merged and fully deployed we can stop writing `sp_session[:ial2]`.
=> LG-12262 Stop reading from `sp_session[:ial2]`

spec/support/shared_examples/password_strength.rb
Updates and unskips a test aimed at checking password strength for a password containing a component of the user's email address.
**Why?**
- We should aim to minimize skipped tests, since:
- There's usually little incentive or accountability to action toward unskipping them (this one has been skipped since 2018)
- They're at a high risk of falling out of sync with application code
- They can indicate a lack of sufficient test coverage
- They create noise in continuous integration build logs
- zxcvbn is unmaintained (last release in 2017) and this feature is likely never going to be implemented
- Part of the intent of this check is supported, namely checking that a password is exactly equal to a component of the user's email address, and we can/should test for this
```
rspec …
```
=> Adapt skipped strong password test for partial match behavior

app/controllers/application_controller.rb, spec/factories/service_providers.rb, spec/features/idv/doc_auth/how_to_verify_spec.rb, spec/features/idv/steps/in_person_opt_in_ipp_spec.rb
[LG-12266](https://cm-jira.usa.gov/browse/LG-12266)
In a previous commit the `resolved_authn_context_result` was introduced to return a `Vot::Parser::Result` object that described the requirements for the current SP request considering SP default options. This is intended to be used to replace the keys in the `sp_session` that serve this purpose including the `phishing_resistant_requested` key.
This commit replaces places where the `sp_session[:phishing_resistant_requested]` value is read with new reads to the `resolved_authn_context_result`.
=> LG-12266: Stop reading from sp_session[:phishing_resistant_requested]

app/controllers/saml_idp_controller.rb, spec/controllers/saml_idp_controller_spec.rb
We introduced a change (ref: https://github.com/18F/identity-idp/pull/10095/files) that started storing the IALMAX ACR value when the IAL1 ACR value is sent with the minimum authn context comparison. Prior to this change the ACR value in the session would be IAL1.
That commit and later commits introduced code that expected that ACR value to be IALMAX when an IALMAX request was made. That led to issues when an IALMAX request was made with the old code that stored the IAL1 value. Specifically issues occurred in the SAML IDP controller when prompting to user to unlock their PII.
This commit makes the code aware of the old approach as well as the new one and handling both.
=> Fix a 50/50 issue in the IALMax code

app/javascript/packages/document-capture/components/file-input.tsx, spec/javascript/packages/document-capture/components/file-input-spec.jsx
https://cm-jira.usa.gov/browse/LG-12520
Show the file name on mobile for yaml files to avoid developer confusion while testing. Also makes the display better while testing. [Slack thread](https://gsa-tts.slack.com/archives/C05HSH9RQ57/p1708542109438079).
These screenshots are not all of the desired state, they're just here to cue you on what we're looking for.
<details>
<summary>Screenshots</summary>
</details>
=> Show YAML File Name on Mobile

app/services/analytics_events.rb, spec/controllers/users/reset_passwords_controller_spec.rb, spec/support/shared_examples/password_strength.rb
Updates method signatures in `AnalyticsEvents` to add missing properties logged for password reset.
Prompted by a [Slack request](https://gsa-tts.slack.com/archives/C05MGJ72GU9/p1708535373643259) made more difficult by lack of full properties documentation.
```
rspec spec/controllers/users/reset_passwords_controller_spec.rb
```
=> Document analytics properties for password reset

app/controllers/application_controller.rb, spec/controllers/application_controller_spec.rb
The `Application#resolved_authn_context_result` method uses the SP session to compute the resolved authn context. The `current_sp` method returns the current SP either by using the issuer in the SP sesison or by using the SP associated with a request ID param.
When `current_sp` is getting an SP associated with a request ID param then there is not an SP session. This leads to an error when computing the resolved authn context.
This change only passes the SP from the session into the `AuthnContextResolver` when computing the resolved authn context.
=> Use `sp_from_sp_session` for `ApplicationController#resolved_authn_context_result`

app/services/proofing/aamva/request/verification_request.rb
I was doing some research and was flummoxed by the hard-coded "P6" in AAMVA verification requests. I did a little research and added what I learned as a comment.
=> Add a comment describing the use of "P6" for AAMVA requests

app/controllers/saml_idp_controller.rb, spec/controllers/saml_idp_controller_spec.rb
A previous change introduced a temporary fix to avoid a 50/50 state issue in the SAML controller (ref: https://github.com/18F/identity-idp/pull/10141).
That was intended to be temporary. Once it is deployed and stable the code can be removed. This change removes that code.
=> Remove temporary 50/50 state fix from the SAML controller

app/controllers/concerns/fraud_review_concern.rb, app/views/idv/not_verified/show.html.erb, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml, spec/controllers/idv/please_call_controller_spec.rb, spec/views/idv/not_verified/show.html.erb_spec.rb
[LG-12172](https://cm-jira.usa.gov/browse/LG-12172)
This simplifies and extends the logic used to implement [LG-11995](https://github.com/18F/identity-idp/pull/10033). The reason I could simplify is that we're targeting both reject and review methods instead of just one. So there's no need to isolate as much code.
<details>
<summary>Completed design:</summary>
</details>
=> LG-12172 implement tmx rejection screen and refactor please call code

app/controllers/application_controller.rb, app/controllers/users/piv_cac_login_controller.rb, app/services/vot/legacy_component_values.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb
[LG-12265](https://cm-jira.usa.gov/browse/LG-12265)
In a previous commit the `resolved_authn_context_result` was introduced to return a `Vot::Parser::Result` object that described the requirements for the current SP request considering SP default options. This is intended to be used to replace the keys in the `sp_session` that serve this purpose including the `piv_cac_requested` key.
This commit replaces places where the `sp_session[:piv_cac_requested]` value is read with new reads to the `resolved_authn_context_result`.
=> LG-12265: Stop reading from sp_session[:piv_cac_requested]

app/services/doc_auth/mock/result_response.rb, spec/features/idv/doc_auth/document_capture_spec.rb, spec/fixtures/ial2_test_credential_barcode_attention_liveness_fail.yml
[LG-12445](https://cm-jira.usa.gov/browse/LG-12445)
- Mock proofer to set the selfie status in DocAuth::Response
- Mock proofer  include selfie status when evaluating success
<details>
</details>
<details>
</details>
=> LG-12445: fix mock proofer to evaluate errors when Attention with Barcode

app/javascript/packages/document-capture/components/acuant-capture.tsx
[LG-12427](https://cm-jira.usa.gov/browse/LG-12427)
Create an analyticsImagePayload for selfie when adding image similar to when other images are added by the user.
=> LG-12427: selfie image metadata

app/controllers/accounts/connected_accounts_controller.rb, app/controllers/accounts/history_controller.rb, app/controllers/accounts/two_factor_authentication_controller.rb, app/controllers/accounts_controller.rb, app/controllers/events_controller.rb, app/controllers/users/passwords_controller.rb, app/controllers/users/verify_password_controller.rb, app/presenters/account_show_presenter.rb, app/views/accounts/_personal_key.html.erb, app/views/accounts/show.html.erb, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml, spec/controllers/accounts_controller_spec.rb, spec/controllers/users/passwords_controller_spec.rb, spec/controllers/users/verify_password_controller_spec.rb, spec/features/users/password_recovery_via_recovery_code_spec.rb, spec/features/users/profile_recovery_for_gpo_verified_spec.rb, spec/features/users/user_profile_spec.rb, spec/presenters/account_show_presenter_spec.rb, spec/support/shared_examples/sign_in.rb, spec/views/accounts/connected_accounts/show.html.erb_spec.rb, spec/views/accounts/history/show.html.erb_spec.rb, spec/views/accounts/show.html.erb_spec.rb, spec/views/accounts/two_factor_authentication/show.html.erb_spec.rb
Prior to this commit there were 2 cases where a personal key was shown to a user in a flash message:
- When the user resets their password and recovers their PII with a personal key
- When the user changes their password from account screen
In both cases the user had to have an identity proofed account for the flash to appear.
The flash had some issues. It was a distinct experience from the typical personal key issuance. The flash was hard to miss and did not include the features we build to ensure users save their personal key.
This commit removes the flash message and redirects the user to the personal key screen when they need to be presented with a personal key in all cases.
This is what the flash looked like:
The personal key screen looks like this:
=> LG-11625 Redirect to new personal key screen instead of show personal key flash

app/javascript/packages/document-capture/components/document-side-acuant-capture.tsx
Part of [LG-12307](https://cm-jira.usa.gov/browse/LG-12307)
As someone who is fairly new to TS, when working on the referenced ticket, I found it difficult to understand the code as I was trying to pass values between a JSX and a TSX file.
I decided to timebox converting this file to TS to see if that would make my other work easier. It was fairly straightforward (I think). I thought it'd be easier to review as its own PR.
=> Setup for LG-12307: Doc Side Acuant to TS

app/services/reporting/active_users_count_report.rb, spec/services/reporting/active_users_count_report_spec.rb
changelog: Internal, Reporting, Query once per time range in MKMR
[LG-11703](https://cm-jira.usa.gov/browse/LG-11703)
Changed the Active Users Reports within the MKMR to only query once per time range instead of re-querying the same time range data multiple times - and risking that the underlying data has changed between duplicate queries.
=> LG-11703 Remove redundant queries from MKMR

app/services/id_token_builder.rb, spec/services/id_token_builder_spec.rb
The `identities.vtr` column has one of the following values:
1. A JSON-encoded representation of the `vtr` param if the `vtr` param is consumed and used
2. `Nil`
The `IdTokenBuilder` uses this value to add a `vot` to the ID token. Prior to this commit this code expected a string representation of a single VoT and not a JSON encoded list. This commit addresses the issue and adjustst the tests to have the correct expectations.
=> Modify the ID token builder to recognize JSON encoded VTR params

Gemfile, Gemfile.lock
Right now all lint tasks are failing in `main` because there's a newly reported file permission vulnerability in `rack-cors` ([link](https://github.com/cyu/rack-cors/issues/274)) version 2.0.1 (latest). This PR addresses that by locking our version to 2.0.0, the latest version of `rack-cors` without this vulnerability ([link](https://github.com/rubysec/ruby-advisory-db/pull/755)).
Presumably we'll be able to use 2.0.1 again once they've patched the problem.
The error:
```ruby
--- bundler-audit ---
bundle exec bundler-audit check --update
Updating ruby-advisory-db ...
From https://github.com/rubysec/ruby-advisory-db
* branch            master     -> FETCH_HEAD
Already up to date.
Updated ruby-advisory-db
ruby-advisory-db:
advisories:   875 advisories
last updated: 2024-02-27 14:25:50 -0800 …
```
=> Lock to `rack-cors 2.0.0` to avoid problem with `rack-cors 2.0.1`

spec/controllers/saml_idp_controller_spec.rb
The `SamlIdpController` tests had a shared example for what happens when a users signs in with an already verified account. This shared example is not actually shared between any examples. It is only used for the IAL2 case. This commit goes ahead and breaks it out into individual tests instead of using a shared example.
=> Remove shared example from SamlIdpController tests

spec/features/openid_connect/openid_connect_spec.rb, spec/support/oidc_auth_helper.rb
This commit adds a feature spec for an OIDC authentication using VTR. This spec makes a request for a proofed user with a VTR and validates everything works as expected including the identity token attributes and user info response.
=> Add an OIDC with VTR feature spec

app/forms/idv/api_image_upload_form.rb, spec/forms/idv/api_image_upload_form_spec.rb
[LG-12308](https://cm-jira.usa.gov/browse/LG-12308)
Add image upload validation to verify tha image files are all sourced by sdk when doc auth with selfie is required.
- complete doc auth with selfie on desktop
- complete doc auth with selfie on mobile (w/ doc_auth_selfie_desktop_test_mode disabled and prior to merge of [PR for LG-12307](https://github.com/18F/identity-idp/pull/10165))
- attempt to upload images and fail
- successfully submit images via sdk
=> LG-12308: validate images are sourced by sdk when liveness check is required

config/application.yml.default
The `use_vot_in_sp_requests` was set twice in the config. Confusingly it was set to 2 different values. This commit removes the first one and lets the previously computed value of `false` prevail.
=> Remove extraneous `use_vot_in_sp_requests` setting

spec/support/oidc_auth_helper.rb
This `tid` arg was used for the IRS attempts API. It has since been retired. These are leftover references and are never used.
=> Remove `tid` argument from OIDC auth helpers

app/forms/idv/api_image_upload_form.rb, app/services/doc_auth/acuant/acuant_client.rb, app/services/doc_auth/lexis_nexis/lexis_nexis_client.rb, app/services/doc_auth/lexis_nexis/requests/true_id_request.rb, app/services/doc_auth/mock/doc_auth_mock_client.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/forms/idv/api_image_upload_form_spec.rb, spec/services/doc_auth/lexis_nexis/lexis_nexis_client_spec.rb, spec/services/doc_auth/lexis_nexis/requests/true_id_request_spec.rb
[LG-12372](https://cm-jira.usa.gov/browse/LG-12372)
Only use TrueID cropped workflows when ID images are cropped (autocaptured via Acuant SDK)
- Tested via unit tests
=> LG-12372: sdk autocaptured id images route to non-cropping workflow

Gemfile.lock
```
Name: yard
Version: 0.9.34
CVE: https://github.com/advisories/GHSA-8mq4-9jjh-9xrc
GHSA: https://github.com/advisories/GHSA-8mq4-9jjh-9xrc
Criticality: Medium
URL: https://github.com/advisories/GHSA-8mq4-9jjh-9xrc
Title: YARD's default template vulnerable to Cross-site Scripting in generated frames.html
Solution: upgrade to '>= 0.9.35'
```
=> Fix yard CVE

config/routes.rb
Removes a route reference to a controller action which does not exist and is not referenced anywhere.
This appears to have been partially implemented in #3405.
See related NewRelic error: https://onenr.io/0KQXoG4XLja
1. Visit http://localhost:3000/backup_code_create
Before: 500 error page
After: 404 error page
=> Remove nonexistent route reference for backup codes

app/controllers/openid_connect/authorization_controller.rb, app/forms/openid_connect_authorize_form.rb, spec/controllers/openid_connect/authorization_controller_spec.rb
In #9837 we modified the IdP to render a 406 if biometric comparison was requested but not allowed for the current environment.
This change applied to the query parameter method for requesting biometric comparison which was the only way to request biometric comparison at the time. Since then we have enabled biometric comparison requests using vectors of trust but did not port over the feature for blocking biometric comparison requests in environments where they are not allowed.
This commit applies the feature to requests that use a vector of trust to request biometric comparison.
=> Render an error when a biometric is requested with a vector of trust

app/controllers/idv/hybrid_handoff_controller.rb, app/views/idv/hybrid_handoff/show.html.erb, spec/features/idv/doc_auth/document_capture_spec.rb
[LG-12305](https://cm-jira.usa.gov/browse/LG-12305)
Only show the Send Link option on the hybrid handoff page when a selfie is req'd and _doc_auth_selfie_desktop_test_mode_ FF is disabled
On Desktop:
- using image upload (doc_auth_selfie_desktop_test_mode: true)
- using hybrid mobile (Send Link)
On Mobile:
=> LG-12305: hybrid handoff image upload for non-selfie doc auth

Gemfile, Gemfile.lock, app/models/disposable_email_domain.rb, app/validators/form_add_email_validator.rb, app/validators/form_email_validator.rb, spec/forms/add_user_email_form_spec.rb, spec/forms/password_reset_email_form_spec.rb, spec/forms/register_user_email_form_spec.rb, spec/models/disposable_email_domain_spec.rb, spec/support/shared_examples_for_email_validation.rb
[LG-12589](https://cm-jira.usa.gov/browse/LG-12589)
Blocks subdomains of blocked domains. Please see JIRA ticket for additional details and context
=> Block subdomains of disposable email domains from signup (LG-12589)

app/javascript/packages/document-capture/components/acuant-capture.tsx, app/services/analytics_events.rb
[LG-11980](https://cm-jira.usa.gov/browse/LG-11980)
Add captureAttempts attribute to the following analytics events:
- idv_sdk_selfie_image_capture_opened
- idv_sdk_selfie_image_capture_closed_without_photo
- idv_sdk_selfie_image_capture_failed
On mobile, attempt Doc Auth with Selfie using AutoCapture
- idv_sdk_selfie_image_capture_opened
- idv_sdk_selfie_image_capture_closed_without_photo
- idv_sdk_selfie_image_capture_failed
=> LG-11980: log captureAttempts for selfie capture opened, closed and failed analytics events

app/controllers/application_controller.rb, app/policies/service_provider_mfa_policy.rb, spec/policies/service_provider_mfa_policy_spec.rb
The `ServiceProviderMfaPolicy` is intended to look at the current SP request context and at the user and determine 2 critical things:
1. Does the user need to authenticate with a different MFA method to satisfy SP requirements? This is done with the `#user_needs_sp_auth_method_verification?` method.
2. Does the user need to setup a new MFA method to statisfy SP requirements? This is done with the `#user_needs_sp_auth_method_setup?` method.
In order to compute this the `ServiceProviderMfaPolicy` needs to consider a number of things:
1. The default AAL of the service provider
2. Parameters specified in the service provider request (phishing-resistant auth or PIV/CAC requirements)
3. The auth methods the user has setup
4. The auth method the user used to authenticate things
The …
=> LG-12374 Integrate `resolved_authn_context_result` into `ServiceProviderMfaPolicy`

app/jobs/get_usps_proofing_results_job.rb, app/models/profile.rb, app/services/analytics_events.rb, spec/jobs/get_usps_proofing_results_job_spec.rb
[LG-12069](https://cm-jira.usa.gov/browse/LG-12069)
- Added logic for deactivating a profile if the deadline passes to visit the post office
```
def request_proofing_results(_unique_id, _enrollment_code)
body = JSON.parse(Fixtures.request_expired_proofing_results_response)
response = { body: body, status: 400 }
raise Faraday::BadRequestError.new('Bad request error', response)
end
```
```
require 'active_support/testing/time_helpers'
include ActiveSupport::Testing::TimeHelpers
freeze_time
now = Time.zone.now
current_enrollment =  InPersonEnrollment.last # Most likely if you haven’t created a new enrollment in the middle of testing cuz that would be weird but if you have just grab the enrollment in your preferred way you rebel you! …
```
=> LG-12069 Deactivate profile if a user never visits the Post Office

app/controllers/concerns/remember_device_concern.rb, app/decorators/null_service_provider_session.rb, app/decorators/service_provider_session.rb, spec/decorators/null_service_provider_session_spec.rb, spec/decorators/service_provider_session_spec.rb
We modified the `mfa_expiration_interval` to use the `AuthnContextResolver` result to determine the SP session expiration. It uses this to determine if a non-AAL2 SP has made an AAL2 request in order to use the AAL2 expiration.
Prior to this commit the result was passed in from the application controller. We do not need to do this, however, since the SP session and the SP are both already passed in to the decorator. This commit uses those to compute the resolved authn context in the decorator.
=> Modify `ServiceProviderSession#mfa_expiration_interval` to not require an argument

app/services/store_sp_metadata_in_session.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/services/store_sp_metadata_in_session_spec.rb
In #10170 we removed all reads to `sp_session[:aal_level_requested]`. Now that the change has been deployed we can safely stop writing to that key in the SP session. This commit reads that write and updates the relevant tests.
=> Stop reading from `sp_session[:aal_level_requested]`

app/services/vot/parser.rb
This method was used to compute the requested AAL level to support cases that had not started using the `#aal2`, `#hspd12?`, and `#phishing_resistant?` properties on `Vot::Parser::Result`.
The following PRs remove the final spots where the numeric AAL value was used:
- #10186
- #10187
- #10194
With those changes there are not more uses of this method and it can be safely removed.
=> Remove `Vot::Parser::Result#aal_level_requested?`

app/services/authn_context_resolver.rb, spec/services/authn_context_resolver_spec.rb
The `AuthnContextResolver` consumes ACR values and VTR values and determine what requirements are for identity and authentication. It also includes SP defaults in this resolution if a value is not requested.
The `AuthnContextResolver` was looking at whether the AAL ACR values contained the substring `aal` to determine if an AAL ACR value was requested. If none was requested it used the SP default AAL. `urn:gov:gsa:ac:classes:sp:PasswordProtectedTransport:duo` is the ACR value for the default AAL (i.e. AAL1) and it does not include the `aal` substring. As a result it was not recognized as a requested AAL value and SP defaults were applied.
This commit fixes the issue above by checking for requested AAL values that include the `aal` substring or are the default AAL value.
=> Fix issue where DEFAULT_AAL ACR value led to SP default AAL resolution

app/controllers/openid_connect/authorization_controller.rb, spec/controllers/openid_connect/authorization_controller_spec.rb
[This commit](https://github.com/18F/identity-idp/commit/fab35dc2accf4f34fbe194baf553abea8e3384d4#diff-7573b68de62ddd44e4f64f6cff7b8df4e7c95e980d037978f18092da163b787bL51) modified the check against `params[:biometric_comparison_required]` in `OpenidConnect::AuthorizationController`. The value of the param is a string so when `'false'` is passed as a param it is truthy.
This commit fixes the issue and adds a test.
=> Fix a bug where OIDC rendered 406 when `biometric_comparison_required` param was false

app/controllers/frontend_log_controller.rb, app/javascript/packages/document-capture/components/acuant-capture.tsx, app/services/analytics_events.rb, spec/features/idv/analytics_spec.rb, spec/javascript/packages/document-capture/components/acuant-capture-spec.jsx
[LG-12074](https://cm-jira.usa.gov/browse/LG-12074)
Rename both:
1.  `idv_selfie_image_file_uploaded`
2. `idv_sdk_selfie_image_added`
events to: `idv_selfie_image_added`.
The rename process also brought up some linting issues, so fixed a few rubocop issues as well. More detail in [the relevant commit](https://github.com/18F/identity-idp/commit/613002fd5af21cd868b5cfbfdc321f0d969ee99c).
<details>
```
{
"name": "idv_selfie_image_file_uploaded",
"properties": {
"event_properties": {
"captureAttempts": 2,
"failedImageResubmission": null,
"fingerprint": "mQn63VZVopk1n6vFCoZSnpLjPSkygU_iQi2zmctKeFo",
"flow_path": "standard",
"height": null,
"mimeType": "application/x-yaml",
"size": 491,
"source": …
```
=> LG-12074: Rename selfie image added events to match naming convention

app/components/badge_component.html.erb, app/views/mfa_confirmation/show.html.erb, app/views/openid_connect/logout/index.html.erb, app/views/partials/multi_factor_authentication/_mfa_selection.html.erb, app/views/shared/_banner.html.erb, app/views/shared/_footer_lite.html.erb, app/views/sign_up/registrations/_sp_registration_heading.html.erb, app/views/users/backup_code_setup/reminder.html.erb, app/views/users/webauthn_setup/new.html.erb, spec/support/matchers/accessibility.rb
[LG-12465](https://cm-jira.usa.gov/browse/LG-12465)
Instead of skipping over SVG images with alt="" attribute, VoiceOver in Safari is reading them as 'image'. Multi-part SVG would read 'image, image, image, etc.' Adding role='img' to the SVG eliminates the bug.
https://a11y-101.com/development/svg
Using MacOS with Safari and VoiceOver capability
Before fix
https://github.com/18F/identity-idp/assets/135744319/6ae9386e-7ef5-4690-b8b1-f74e7b04b24b
After fix
https://github.com/18F/identity-idp/assets/135744319/9891c134-1aa4-4363-8c55-71ad0dc5e808
=> LG-12465 VPAT 1.1.1 Safari VoiceOver svg with null alt

app/javascript/packages/clipboard-button/package.json, app/javascript/packs/navigation.ts, app/views/partials/multi_factor_authentication/_mfa_selection.html.erb, package.json, yarn.lock
Updates the [Login.gov Design System](https://github.com/18F/identity-design-system) to the latest version 9.0.0.
See CHANGELOG: https://github.com/18F/identity-design-system/releases/tag/v9.0.0
This brings in a number of improvements, notably new first-party TypeScript types for JavaScript components, via re-exported [`@types/uswds__uswds`](https://www.npmjs.com/package/@types/uswds__uswds).
[Example](https://github.com/18F/identity-idp/blob/367ee3c7c5dec7942b2aaafad537232901193f49/app/javascript/packages/clipboard-button/clipboard-button-element.ts#L31):
This should provide some marginal savings in stylesheet size, with the removal of raw color tokens.
```
NODE_ENV=production yarn build:css && brotli-size app/assets/builds/application.css  
```
**Before:** 23.2kb
**After:** 22.6kb …
=> Upgrade Login.gov Design System to v9.0

app/assets/stylesheets/components/_language-picker.scss
Removes a few language picker styles leftover after #10098, where prior to that pull request the expander icon was implemented as a background image.
These styles do nothing because the background image is always removed:
https://github.com/18F/identity-idp/blob/ddf78f0bfa51cfa1408924501d6e4fb819092fff/app/assets/stylesheets/components/_language-picker.scss#L46-L49
This was noticed as part of adapting the styles to the brochure site in https://github.com/GSA-TTS/identity-site/pull/1219 .
I also simplified multiple `padding` styles to a single shorthand `Y X` format ([reference](https://developer.mozilla.org/en-US/docs/Web/CSS/padding#syntax)).
Verify no regression in the appearance of the language picker, notably the expander icon, on both desktop and mobile.
=> Remove unnecessary background styles from language picker

app/controllers/api/internal/two_factor_authentication/piv_cac_controller.rb, spec/controllers/api/internal/two_factor_authentication/piv_cac_controller_spec.rb
Adds missing PIV behavior for deleted PIV, expected to remove cached `user_session` detail. This carries forward from the original implementation preceding #9861, removed in #10218.
https://github.com/18F/identity-idp/blob/b456d8556fc684179c015e818539cd3082574ad7/app/controllers/users/piv_cac_authentication_setup_controller.rb#L39
```
rspec spec/controllers/api/internal/two_factor_authentication/piv_cac_controller_spec.rb
```
=> Clean PIV session detail after deletion

spec/features/two_factor_authentication/multiple_mfa_sign_up_spec.rb
Updates flakey specs to use `expect(page).to have_current_path …` instead of `expect(current_path).to eq …`.
These tests have been shown to be occasionally flakey.
Examples:
- https://gitlab.login.gov/lg/identity-idp/-/jobs/1068613
- https://gitlab.login.gov/lg/identity-idp/-/jobs/1057968
Related Slack discussion: https://gsa-tts.slack.com/archives/C01710KMYUB/p1709311154032829
The hypothesis is there's a race condition where the test signs in with a new user and assumes to arrive at the MFA setup screen. This does happen, but only after a series of redirects, where the [`sign_in_before_mfa` helper](https://github.com/18F/identity-idp/blob/d540121ca00697453faca9daef9f4778638f1db1/spec/support/features/session_helper.rb#L189) attempts to visit the account page.
The thought with using …
=> Switch to have_current_path for MFA path comparison

app/controllers/concerns/saml_idp_auth_concern.rb, app/controllers/saml_idp_controller.rb, app/services/attribute_asserter.rb, spec/features/saml/vtr_spec.rb, spec/services/attribute_asserter_spec.rb
In #10178 we added the ability for SAML service providers to make a request with a vector of trust in the AuthnContext. When a SAML SP does this the vector of trust that is used for the authentication transaction should be reflected to the SP in the SAML response.
The authentication context appears in 2 places in the SAML request:
1. In the authn context for the entire transaction:
```xml
<AuthnStatement AuthnInstant="2024-01-01T00:00:00" SessionIndex="_abc-123-def-456">
<AuthnContext>
<AuthnContextClassRef>A1.B2.C3</AuthnContextClassRef>
</AuthnContext>
</AuthnStatement>
```
2. In the attribute statement. With ACR values these appeared as seperated AAL and IAL nodes. For VTRs they appear in a single VTR node:
```xml
<AttributeStatement>
<Attribute Name="vot" …
```
=> Add the `vot` to the SAML response when it is used as an AuthnContext for SAML

app/controllers/idv/welcome_controller.rb, app/presenters/idv/welcome_presenter.rb, app/views/idv/welcome/show.html.erb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, spec/features/idv/end_to_end_idv_spec.rb, spec/features/idv/step_up_spec.rb, spec/presenters/idv/welcome_presenter_spec.rb, spec/views/idv/welcome/show.html.erb_spec.rb
[LG-12492](https://cm-jira.usa.gov/browse/LG-12942)
Changed the welcome screen text for users who are undergoing step-up IdV (they were verified without a selfie, but now must be re-verified with a selfie).
- Create a user and proceed through IdV.
- Verify that the new text does not appear on the getting started
screen
- Stop the app and enable selfies (Change `NullServiceProviderSession#selfie_required?` to return true)
- Restart the app and re-enter IdV
- Verify that the new text appears on the getting started screen.
<details>
<summary>Beginning initial IdV:</summary>
</details>
<details>
<summary>Beginning initial IdV (French):</summary>
</details>
<details>
<summary>Beginning initial IdV …
=> LG-12492 Update getting started screen for legacy selfies

app/services/doc_auth/lexis_nexis/responses/true_id_response.rb, app/services/doc_auth/mock/result_response.rb, app/services/document_capture_session_result.rb, spec/controllers/idv/hybrid_mobile/document_capture_controller_spec.rb, spec/features/idv/doc_auth/document_capture_spec.rb, spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb, spec/services/document_capture_session_result_spec.rb
[LG-12557](https://cm-jira.usa.gov/browse/LG-12557)
- TrueIDResponse only parse and store portrait match when a portrait match was requested
- - Restore use of :success in Document capture result
- unit test coverage
=> LG-12557: portrait match is received when not requested

app/javascript/packages/document-capture/components/acuant-selfie-capture-canvas.jsx
[LG-12655](https://cm-jira.usa.gov/browse/LG-12655)
Allow selfie hints to be read out by screen reader.
=> LG-12655: selfie hints are voiced when voice accessibility is enabled

app/views/devise/sessions/new.html.erb, spec/views/devise/sessions/new.html.erb_spec.rb
Removes no-JavaScript tracking from the Sign In page.
See #9693 for additional context. This effectively reverts #9693, while keeping additional supports for location-specific analytics currently used within identity verification flows.
While the intent of #9693 was toward understanding no-JavaScript usage and this analysis has yet to be performed, it's been live in production long enough to create queryable historical data that could be used for a future analysis.
Repeat Testing Plan from #9693, verifying that you never see "no_js_detect_stylesheet_loaded" event.
=> Remove no-JavaScript tracking from Sign In page

app/components/manageable_authenticator_component.scss
Fixes a minor visual defect which occurs when editing a multi-factor authentication method and there are additional methods that follow, where there should be a top border on items that follow.
Prerequisite: Have an account with 2 or more of the following types MFA: Security key, face or touch unlock, PIV, authenticator app.
1. Go to the account page
2. Edit one of your authenticators where another authenticator exists after
3. Verify no issues with border appearance
Before|After
---|---
=> Fix border on MFA when editing with multiple

app/services/analytics_events.rb, spec/controllers/users/piv_cac_login_controller_spec.rb
Incidentally relates to [LG-12706](https://cm-jira.usa.gov/browse/LG-12706), as it further complicates the issues described there.
Updates `piv_cac_login` method YARDoc to include missing `key_id` method, and revises tests to ensure enforcement using new enforcement features added in #9946.
Build should pass.
=> Add documentation for missing piv_cac_login arguments

app/javascript/packages/document-capture/components/document-side-acuant-capture.tsx, app/javascript/packages/document-capture/context/failed-capture-attempts.tsx, app/javascript/packages/document-capture/context/selfie-capture.tsx, app/javascript/packs/document-capture.tsx, app/views/idv/shared/_document_capture.html.erb, spec/javascript/packages/document-capture/components/document-capture-abandon-spec.tsx, spec/javascript/packages/document-capture/components/document-side-acuant-capture-spec.jsx, spec/javascript/packages/document-capture/components/document-side-acuant-capture-spec.tsx, spec/javascript/packages/document-capture/context/failed-capture-attempts-spec.jsx, spec/javascript/packages/document-capture/context/selfie-capture-spec.jsx, spec/javascript/support/document-capture.jsx, tsconfig.json
[LG-12307](https://cm-jira.usa.gov/browse/LG-12307)
When doc auth with selfie is required, the FE only allows adding ID and selfie images using the Acuant SDK.
(unless `doc_auth_selfie_desktop_test_mode: true`, then we still want to allow uploads)
This one is a bit involved when it comes to testing. This is because between the differences between mobile and desktop, and the two flags:
```
doc_auth_selfie_capture_enabled
doc_auth_selfie_desktop_test_mode
```
... there are 8 different states it can be in. To make it a little easier, I made [an Excel spreadsheet](https://docs.google.com/spreadsheets/d/11S1jxzrPiM1022fGoSjYBkdh1KXTRU2k-KU6lAA7vmU/edit#gid=0) with the 8 states and what their expected result are.
In addition, note that you can fail the SDK capture by trying to take a photo of …
=> LG-12307: don't allow upload when selfie capture is enabled

app/javascript/packages/document-capture/context/acuant.tsx
This work happened because of this [Slack thread](https://gsa-tts.slack.com/archives/C05HSH9RQ57/p1710358553742399?thread_ts=1710277352.607419&cid=C05HSH9RQ57).
This PR updates a comment to be clearer.
=> Improve Acuant Global Code Comment

app/controllers/idv/document_capture_controller.rb, app/controllers/idv/hybrid_handoff_controller.rb, app/views/idv/hybrid_handoff/show.html.erb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, config/routes.rb, spec/features/idv/doc_auth/document_capture_spec.rb, spec/features/idv/doc_auth/hybrid_handoff_spec.rb, spec/views/idv/hybrid_handoff/show.html.erb_spec.rb
[LG-12672](https://cm-jira.usa.gov/browse/LG-12672)
UI update for hybrid handoff page when selfie is required.
On desktop , with `doc_auth_selfie_desktop_test_mode: false`.
<details>
</details>
=> LG-12672: handoff page update when selfie required

app/presenters/two_factor_options_presenter.rb, app/views/accounts/_webauthn_roaming.html.erb, app/views/users/two_factor_authentication_setup/index.html.erb, config/locales/mfa/en.yml, config/locales/mfa/es.yml, config/locales/mfa/fr.yml, config/locales/two_factor_authentication/en.yml, config/locales/two_factor_authentication/es.yml, config/locales/two_factor_authentication/fr.yml
[LG-12597](https://cm-jira.usa.gov/browse/LG-12597)
This PR aligns language regarding security keys on both the "My Account" and "MFA Selection" page
[Figma file](https://www.figma.com/file/DcXhs9QHcCbWt0J4dY0WlL/LG-12477%3A-Security-Key-language-alignment?type=design&node-id=2487%3A6493&mode=design&t=p0rPctz5leQ4UyAQ-1)
<details>
<summary>Authentication options text</summary>
| English | Spanish  | French 
|---|---| --- |
| **BEFORE**  | **BEFORE**  | **BEFORE** |
| ![Screenshot of original instructions for MFA setup in English](https://github.com/18F/identity-idp/assets/17969963/038a05c4-f288-419c-83fe-f4e8941770cc) | ![Screenshot of original instructions for MFA setup in Spanish](https://github.com/18F/identity-idp/assets/17969963/7c9e008a-e489-4a03-b9a5-2f4fcee1555d) | ![Screenshot of …
=> LG-12597: Make revisions on MFA selection screen

app/presenters/openid_connect_user_info_presenter.rb, spec/presenters/openid_connect_user_info_presenter_spec.rb
[LG-12678](https://cm-jira.usa.gov/browse/LG-12678)
We updated the documented values to boolean -- so returning `false` when piv/cac is not used makes more sense, rather than a `nil` return. (Boolean is more straightforward, and easier for partners using typed languages)
=> LG-12678 Updates nil return value to false

app/controllers/users/piv_cac_controller.rb, spec/controllers/users/piv_cac_controller_spec.rb
Adds missing PIV behavior for deleted PIV, expected to remove cached `user_session` detail. This carries forward from the original implementation preceding #9861, removed in #10218.
https://github.com/18F/identity-idp/blob/b456d8556fc684179c015e818539cd3082574ad7/app/controllers/users/piv_cac_authentication_setup_controller.rb#L39
This is the same as #10220, but applied to the no-JS fallback controller (`Users::PivCacController`) in addition to the JavaScript API controller (`Api::Internal::TwoFactorAuthentication::PivCacController`).
```
rspec spec/controllers/api/internal/two_factor_authentication/piv_cac_controller_spec.rb
```
=> Clean PIV session detail after deletion (2)

spec/controllers/idv/image_uploads_controller_spec.rb
Related to work underway for [LG-12657](https://cm-jira.usa.gov/browse/LG-12657)
Over on #10230 I am doing some work that involves touching a lot of analytics-related specs. I noticed that the spec for `Idv::ImageUploadsController` was using syntax like:
```ruby
expect(@analytics).to receive(:track_event).with('event name', { big list of args })
```
This PR updates the spec to use [the `have_logged_event` matcher](https://github.com/18F/identity-idp/blob/main/spec/support/fake_analytics.rb#L180), which will make some of my changes a little easier.
The biggest thing here is that `have_logged_event` needs to be called _after_ the action, rather than before, so this meant moving some code around.
=> Update ImageUploadsController spec to use have_logged_event

app/services/analytics_events.rb
Related to work for 
[LG-12657](https://cm-jira.usa.gov/browse/LG-12657)
There a few methods in analytics_events.rb that are missing `**extra` args and a few `track_event` calls where `**extra` is not passed through. This PR just adds an `**extra` arg where missing and ensures that it is passed through to `track_event`.
=> Add **extra where missing from track_event calls

app/javascript/packages/document-capture/components/acuant-capture.tsx, app/javascript/packages/document-capture/components/acuant-selfie-camera.tsx
https://cm-jira.usa.gov/browse/LG-12671
Slack thread with additional context and reasoning [here](https://gsa-tts.slack.com/archives/C05HSH9RQ57/p1710519415603379?thread_ts=1710518388.562059&cid=C05HSH9RQ57).
This PR removes the code to reset the hint text when selfie capture closes because it may be the cause of the black screen problem. This is not a certain thing, but it's worth trying.
To test this:
- Check out `main` and go to the front/back/selfie page with selfie enabled.
- Open the selfie capture, paying special attention to the hint text and how it changes.
- Open/close selfie capture, again paying attention to how the hint text changes.
- Check out this PR `charley/attempt-to-fix-blackscreen-1` and repeat the earlier steps, looking at the hint text. …
=> Blackscreen Fix Attempt: Remove Hint Text Update from `onPhotoTaken`

app/services/idv/analytics_events_enhancer.rb, spec/services/idv/analytics_events_enhancer_spec.rb
[LG-12657](https://cm-jira.usa.gov/browse/LG-12657)
(This is a redo of #10230 as that had gotten pretty messy.)
In working on #10216, I realized that the list of events that `Idv::AnalyticsEventsEnhancer` enhances has gotten a little stale. Specifically, we haven't been adding new events to it.
This PR converts `Idv::AnalyticsEventsEnhancer` from **opt in** to **opt out**. All `idv_` methods will be "enhanced" UNLESS they are included in the `IGNORED_METHODS` list.
Initially my plan was to increase the scope of of events that are enhanced. However, this resulted in _a lot_ of required spec updates. To keep the scope of this PR a little more manageable, it sets `IGNORED_METHODS` such that there is no actual change in behavior–it is the inverse of the old …
=> Make Idv::AnalyticsEventsEnhancer opt-out

Gemfile, Gemfile.lock
[LG-12758](https://cm-jira.usa.gov/browse/LG-12758)
A partner wrote in https://logingov.zendesk.com/agent/tickets/8122 pointing out that the SAML metadata fails validation against the SAML metadata schema because a few elements are out of order. saml_idp was updated here: https://github.com/18F/saml_idp/pull/92/files#diff-5e1a3c3dbbdd1b6b38ccf8b3ee053f93487579e671c96d76f66be77731942990
This change updates the saml_idp version used so that the idp gets the reordered metadata
=> LG-12758 reorder metadata

docs/sdk-upgrade.md, scripts/download_acuant_sdk.sh
[LG-12342](https://cm-jira.usa.gov/browse/LG-12342)
When testing the new Acuant SDK v11.9.3, I found parts of the selfie functionality didn't work.
After research, I realized that was because we had missing files. Our `download_acuant_sdk` script only copied over `.min.js` and `.wasm` files.
We found after talking with Matt Hinz that this was because previously we only needed the document capture files.
With this change, we should get everything that's needed - there is currently one file we aren't downloading - and that's the `AcuantCamera.js`. There are two reasons I chose not to download that.
1. the same code is already in place and used in `AcuantCamera.min.js`.
2. it seems like it'd be easier to just download everything, but we do want to be mindful of not including more files than …
=> LG-12342 setup: Download files needed for selfie capture

app/javascript/packages/document-capture/components/acuant-selfie-capture-canvas.jsx, app/javascript/packages/document-capture/components/acuant-selfie-capture-canvas.scss
Slack thread bug report is [here](https://gsa-tts.slack.com/archives/C05HSH9RQ57/p1710973400493459).
This PR adds a few lines of CSS to hide an odd black dot that was appearing when the selfie hint text was empty. What was happening is that we style the `<p>` element with the class `.document-capture-selfie-feedback`. But because that styling was always applied, we were essentially getting a black background `<p>` element with padding. This change hides the `<p>` using CSS when it has no text inside it.
<details>
</details>
<details>
<summary>After with padding</summary>
</details>
<details>
<summary>After, no padding</summary>
</details>
=> Bug fix: Hide the selfie hint box when there's no text.

config/locales/step_indicator/en.yml, config/locales/step_indicator/es.yml, config/locales/step_indicator/fr.yml
[LG-12058](https://cm-jira.usa.gov/browse/LG-12058)
On the step counter, the following titles are changed:
- from `Secure your account` to `Re-enter your password`
- from `Verify phone or address`  to `Verify your phone number`
en: Re-enter your password
es: Vuelve a ingresar tu contraseña
fr: Saisir à nouveau votre mot de passe
en: Verify your phone number
es: Verifique su número de teléfono
fr: Vérifier votre numéro de téléphone
<details>
English:
Spanish:
French:
</details>
<details>
English:
Spanish:
French:
</details>
=> LG-12058: reword two of the steps in the step indicator.

app/services/analytics.rb, app/services/idv/analytics_events_enhancer.rb, spec/services/analytics_spec.rb, spec/services/idv/analytics_events_enhancer_spec.rb, spec/support/fake_analytics.rb
[LG-12618](https://cm-jira.usa.gov/browse/LG-12618)
This change logs the resolved authn context in CloudWatch events under the key `sp_request` and provides a hash with the following keys, if they are true:
- `aal2`
- `biometric_comparison`
- `component_values` - `{ 'value' => true, 'value2' => true }`
- `hspd12`
- `ialmax`
- `identity_proofing`
- `phishing_resistant`
If there isn't a vtr or acr_values saved in the session, the `sp_request` will not be included at all.
=> LG-12618: log the sp request components for enhanced idv events.

app/controllers/concerns/effective_user.rb, spec/controllers/concerns/effective_user_spec.rb
[LG-12793](https://cm-jira.usa.gov/browse/LG-12793)
If the user deletes their account, it is possible that the user id stored in the session for document capture will not be valid. This results in analytics events being improperly attributed to `anonymous-uuid`.
=> Don't use stale document capture user ids for effective_user

app/assets/stylesheets/_uswds-core.scss, app/components/icon_component.scss, app/components/tab_navigation_component.scss, app/javascript/packages/clipboard-button/package.json, app/views/layouts/application.html.erb, app/views/layouts/base.html.erb, app/views/shared/_banner.html.erb, config/initializers/assets.rb, package.json, yarn.lock
Upgrades `@18f/identity-design-system` from `9.0.0` to `9.1.0`.
See release notes: https://github.com/18F/identity-design-system/releases/tag/v9.1.0
Additional changes made possible by upstream improvements:
- [Reconcile upstream merged button icon styles](https://github.com/18F/identity-idp/commit/0e9f95f54f0c1ce56e614cc2bbb06dd015677f87)
- [Reconcile upstream merged segmented button group styles](https://github.com/18F/identity-idp/commit/54bb631c17a79f4d165334b99cf03d09e6565c41)
- [Include design system initializer script](https://github.com/18F/identity-idp/commit/2b9fa599c3b9d64d81735bd50578a1408ba8809d)
Verify there are no noticeable visual regressions.
Particular focus:
- Icons in buttons
- Banner shows as collapsed while JavaScript loads
- Segmented button on "Sign in" page is …
=> Upgrade Login.gov Design System to 9.1.0

app/helpers/script_helper.rb, spec/helpers/script_helper_spec.rb
Removes unused `javascript_include_tag_without_preload`.
Last reference removed in #7563.
Removing may simplify upcoming work to refactor this module to be thread-safe.
There should be no user-facing impact of these changes, since the method is unused.
=> Remove unused javascript_include_tag_without_preload

config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml, spec/features/idv/doc_auth/document_capture_spec.rb
[LG-12268: Implement Department of State translation for in-line error message for FaceMatchResult: Fail](https://cm-jira.usa.gov/browse/LG-12268)
1. Update Spanish and French headings for scenario where the FaceMatchResult is Fail.
2. Update English, Spanish, and French body text for scenario where the FaceMatchResult is Fail.
3. For related context, see PR #10042, which implemented Gengo translations.
To test on desktop...
```
doc_auth_selfie_capture_enabled: true
doc_auth_selfie_desktop_test_mode: true
```
<details>
</details>
<details>
</details>
<details>
</details>
=> LG-12268: Use Department of State translations for Face Match Fail

scripts/download_acuant_sdk.sh
[LG-12342](https://cm-jira.usa.gov/browse/LG-12342)
[See details on the reason for this change in this PR](https://github.com/18F/identity-idp/pull/10283).
=> Rm ImageMagick files from download script

app/helpers/script_helper.rb, app/services/idv/steps/threat_metrix_step_helper.rb, config/application.rb, lib/asset_sources.rb, spec/helpers/script_helper_spec.rb, spec/lib/asset_sources_spec.rb
`AssetSources` is currently initialized on boot and not modified afterwards (unless in development). The issue is it's use of the instance variable in class method. This PR refactors them out to be instance variables on an instance of the class that is assigned to the application configuration.
(Somewhat related to #10300)
=> Refactor AssetSources to be thread-safe

Gemfile, Gemfile.lock, app/helpers/script_helper.rb, spec/rails_helper.rb
Builds on #10301 to make `ScriptHelper` explicitly thread-safe as well using `RequestStore`. The current usage is not necessarily thread-unsafe, but this refactors it to use the thread-safe `RequestStore` to protect against future changes that may not be.
=> Refactor ScriptHelper class to be thread-safe

app/components/step_indicator_component.rb, app/views/idv/personal_key/show.html.erb, spec/components/step_indicator_component_spec.rb, spec/features/idv/end_to_end_idv_spec.rb, spec/features/idv/in_person_spec.rb, spec/features/idv/in_person_threatmetrix_spec.rb, spec/features/idv/steps/in_person_opt_in_ipp_spec.rb, spec/support/features/in_person_helper.rb
[LG-12061](https://cm-jira.usa.gov/browse/LG-12061)
In #10280 we reworded the `secure_account` step to "Re-enter your password" so it no longer makes sense to have the final step be current once the user has re-entered their password.
The PR adds a new current_step of `ALL_STEPS_COMPLETED` which can be used to force all steps to render as completed.
<details>
</details>
<details>
</details>
=> LG-12061: All step indicator steps are shown completed on Personal Key page

.gitignore
Uses the same strategy that a `rails new project` would employ.
=> Ensure that the pids directory is present for puma

app/services/analytics_events.rb, spec/controllers/concerns/idv/phone_otp_rate_limitable_spec.rb, spec/controllers/idv/by_mail/letter_enqueued_controller_spec.rb, spec/controllers/idv/by_mail/request_letter_controller_spec.rb, spec/controllers/idv/cancellations_controller_spec.rb, spec/controllers/idv/forgot_password_controller_spec.rb, spec/controllers/idv/otp_verification_controller_spec.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/controllers/idv/phone_controller_spec.rb, spec/controllers/idv/phone_errors_controller_spec.rb, spec/controllers/idv/please_call_controller_spec.rb, spec/controllers/idv/resend_otp_controller_spec.rb, spec/controllers/idv/sessions_controller_spec.rb, spec/features/idv/cancel_spec.rb
Previously: #10258 
This PR:
* Updates several specs to use `have_logged_event` instead of `expect(@analytics).to receive(:track_event)`. 
* Removes `allowed_extra_analytics: [:*]` from a couple of specs and documents the parameters found
=> Analytics-related spec updates

app/decorators/mfa_context.rb, spec/decorators/mfa_context_spec.rb, spec/models/user_spec.rb
Reorders checks in `MfaContext#two_factor_enabled?` to assure higher likelihood of short-circuiting, based on setup rates for common MFAs.
CloudWatch query:
```
filter name = 'Multi-Factor Authentication Setup'
| stats count(*) as method_count by properties.event_properties.multi_factor_auth_method
| sort method_count desc
```
This performs the same checks so it shouldn't have any notable effects.
Verify associated specs pass:
```
rspec spec/decorators/mfa_context_spec.rb
```
=> Order two_factor_enabled short-circuiting by usage

app/javascript/packages/document-capture/components/acuant-capture.tsx, spec/forms/idv/api_image_upload_form_spec.rb
[LG-12280](https://cm-jira.usa.gov/browse/LG-12280)
Send doc auth image file name as part of metadata, so it can be logged.
=> LG-12280: log image file name

app/services/doc_auth/error_generator.rb
[LG-12494](https://cm-jira.usa.gov/browse/LG-12494)
Refactoring `ErrorGenerator`. By creating POROs with single responsibilities. At top level, `ErrorGenerator` is responsible mostly to decide what error to bubble up and what errors to consolidate.
Existing test cases and manual testing for failure scenarios.
=> LG-12494: err gen method

config/initializers/geocoder.rb
Updates geocoder initializer to always load the geocoder file if it exists, regardless of environment.
This is to avoid future confusion like I experienced when following our [instructions to set up geolocation](https://github.com/18F/identity-idp/blob/main/docs/local-development.md#setting-up-geolocation) and it not working as instructed.
1. Follow the instructions to set up geolocation
1. Alternatively, download live database from S3
3. Verify geocoder produces real data
1. `rails c`
2. `Geocoder.search(Faker::Internet.ip_v4_address).first`
4. Verify output is something other than the [fake default](https://github.com/18F/identity-idp/blob/bf24298d61fd53f0ade05f4d048946e1a6c95647/config/initializers/geocoder.rb#L26)
=> Always initialize geocoder if geolocation data file exists

.gitignore
Reverts 18F/identity-idp#10308
This is causing issues in deployed environments due to some weird things we do around symbolic links, so I'm reverting this until we can fix that.
=> Revert "Ensure that the pids directory is present for puma"

app/services/doc_auth/error_generator.rb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, spec/features/idv/doc_auth/document_capture_spec.rb
[LG-12268](https://cm-jira.usa.gov/browse/LG-12268)
- This is an attempt to fix the bug @kellular surfaced in [this slack thread.](https://gsa-tts.slack.com/archives/C05HSH9RQ57/p1711482907389469) (Hat tip to @amirbey for suggesting the fix during the afternoon group work session!)
I know the bug we found wasn't affecting inline error messages, but I am including a screenshot of inline error messages for thoroughness's sake.
<details>
<summary>English errors (body copy):</summary>
</details>
<details>
<summary>English errors (inline errors):</summary>
</details>
<details>
<summary>Spanish errors (body copy):</summary>
</details>
<details>
<summary>Spanish errors (inline errors):</summary>
</details> …
=> LG-12268: Fix bug in face match failure result copy

app/controllers/concerns/saml_idp_auth_concern.rb, app/controllers/openid_connect/authorization_controller.rb, app/controllers/saml_idp_controller.rb, app/services/analytics_events.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/features/saml/saml_spec.rb, spec/features/users/sign_up_spec.rb, spec/support/shared_examples/sign_in.rb
This commit adds logging to ensure we have visibility into the VTR param that is sent by a service provider using SAML or OIDC.
When the param is sent it is expanded to include implied components. For example, “Pb” will be expanded into “C1.C2.P1.Pb”. For debugging purposes we will want visibility into what the service provider actually requests.
Additionally, when looking at SP redirects that are served it may be helpful to see the VTR and ACR values that were operated on.
This addresses this concern on the following events:
- OpenID Connect: authorization request
- SAML Auth
- SAML Auth Request
- SP redirect initiated
This commit also updates the SAML request logging params in `analytics_events` to be inclusive of what is actually logged.
This request already has a `vtr` value that is …
=> LG-12674 Ensure requested VTR is logged in SAML and OIDC endpoints

app/controllers/idv/by_mail/enter_code_controller.rb, spec/controllers/idv/by_mail/enter_code_controller_spec.rb
We have several rate limits that are enforced when the user visits the verify-by-mail code entry screen:
1. _OTP Rate-Limit_: This limit applies to OTP entries. After the user has entered too many OTPs this is enforced and the user is redirected to an error screen.
2. _Letter request limit_: This limit applies to letter requests. After the user has requested too many letters or if the users profile is too old the user no longer sees the option to request a new letter.
The enter code screen enforced these limits but did not add any indicator to the logs that it was doing so. This commit adds properties to the analytics event for each of these cases so we can monitor how the app is behaving.
=> LG-12365 Log rate limit status on verify-by-mail enter-code controller

lib/reporting/drop_off_report.rb, spec/lib/reporting/drop_off_report_spec.rb
[LG-12627](https://cm-jira.usa.gov/browse/LG-12627)
Backs out previous work adding USPS pending to the Drop Off Report erroneously.
Adds Workflow Complete - Total Pending to the Drop Off Report from the IDV Report.
=> Add total pending to drop off report

config.ru
This fix is tied to the issues in #10304 / #10318. `RequestStore` depends on `Rack::BodyProxy`, which depends on the [close method being called](https://github.com/rack/rack/blob/main/lib/rack/body_proxy.rb#L31-L35) on the body so it can run the callbacks. Mysteriously, this wasn't happening, which caused `RequestStore` to not clean up after a request.
After digging a bit and removing as many Rack middlewares as possible and seeing what might causes the change in behavior, the culprit seems to be `use Rack::ContentLength` being called outside the Rails application. In testing this change, Content-Length is returned regardless due to the web server rather than application server handling it, and there should be no impact. I tested `RequestStore` a bit and it seemed to behave as expected …
=> Remove Rack::ContentLength from being loaded outside of Rails

app/controllers/idv/by_mail/enter_code_controller.rb, app/views/idv/by_mail/enter_code/_form.html.erb, config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml, spec/controllers/idv/by_mail/enter_code_controller_spec.rb, spec/features/idv/steps/enter_code_step_spec.rb
Prior to this commit the verify-by-mail OTP submission would add errors to the flash and redirect to the OTP entry path. This lead to a couple problems:
1. The error for the OTP appeared in the flash instead of on the OTP field
2. The `did_not_receive_letter` param was not sticky i.e. when a user submitted the OTP it would switch back to the “Welcome back” UI. This was because the param was not present on the redirected URL.
This commit changes the implementation to closer match what we would expect from a controller using the [Form Object Pattern](https://dev.to/drbragg/rails-design-patterns-form-object-4d47). Specifically the `#create` action no longer redirects, but renders the `index` template with the `GpoVerifyForm` that was used for submission and thus has all of the errors and …
=> Render incorrect verify-by-mail OTP error inline

app/controllers/idv/link_sent_controller.rb, app/views/account_reset/pending/cancel.html.erb, app/views/idv/cancellations/destroy.html.erb, config/locales/account_reset/en.yml, config/locales/account_reset/es.yml, config/locales/account_reset/fr.yml, config/locales/errors/en.yml, config/locales/errors/es.yml, config/locales/errors/fr.yml, config/locales/idv/en.yml, config/locales/telephony/en.yml, config/locales/titles/en.yml, config/locales/titles/es.yml, config/locales/titles/fr.yml, config/locales/two_factor_authentication/en.yml, config/locales/user_mailer/en.yml, spec/controllers/idv/link_sent_controller_spec.rb, spec/features/account_reset/pending_request_spec.rb, spec/i18n_spec.rb
**Why**:
- Use the standard TTS practice of American English spelling everywhere.
**How**:
- Change only the user-facing text in this commit.
changelog: User-Facing Improvements, Messages, Use the American spelling of canceled consistently
=
[LG-12756](https://cm-jira.usa.gov/browse/LG-12756)
=> LG-12756 Spell canceled consistently

app/controllers/idv/document_capture_controller.rb, app/controllers/idv/hybrid_handoff_controller.rb, app/javascript/packages/document-capture/components/document-capture.tsx, app/javascript/packages/document-capture/components/in-person-prepare-step.tsx, app/javascript/packages/document-capture/context/in-person.ts, app/javascript/packs/document-capture.tsx, app/services/idv/session.rb, app/views/idv/document_capture/show.html.erb, app/views/idv/hybrid_handoff/show.html.erb, app/views/idv/hybrid_mobile/document_capture/show.html.erb, app/views/idv/shared/_document_capture.html.erb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, spec/controllers/idv/document_capture_controller_spec.rb, spec/controllers/idv/hybrid_handoff_controller_spec.rb, spec/features/idv/doc_auth/document_capture_spec.rb, spec/features/idv/doc_auth/how_to_verify_spec.rb, spec/features/idv/doc_auth/hybrid_handoff_spec.rb, spec/views/idv/hybrid_handoff/show.html.erb_spec.rb, spec/views/idv/shared/_document_capture.html.erb_spec.rb
[LG-12631](https://cm-jira.usa.gov/browse/LG-12631)
Previous PR with wrong branch name: https://github.com/18F/identity-idp/pull/10260
IPP options on hybrid handoff page when IPP is available. User can select IPP and start document capture from handoff page on desktop.
A new `skip_doc_auth_from_handoff` flag is added for idv_session, simlar to `skip_doc_auth` which works with the optin page.
[Test cases](https://docs.google.com/spreadsheets/d/1ncGqc8X2hh77PC3E5fPT3aL5bqV_xVLOkpca4poU7kQ/edit?usp=sharing) for configuration items combination: 
Please refer the test cases spreadsheet, it may not be realistic to test all combinations in staging environment.
If relevant, include a screenshot or screen capture of …
=> LG-12631: handoff ipp

app/services/vot/legacy_component_values.rb, app/services/vot/supported_component_values.rb
To get closer to being thread-safer, this PR refactors the VoT component values out of a class instance variable into a constant. This value is only written once with what should be the same value, so the current implementation is probably safe, but this is more of moving to best practices around thread-safety.
=> Refactor component values into constant

app/services/phone_number_capabilities.rb, app/services/profanity_detector.rb, app/services/saml_endpoint.rb, config/initializers/rack_timeout.rb, lib/aws/ses.rb
Similar to #10336, this removes class variables and class instance variables, substituting constants where needed and eliminating the variables if they're no longer used.
=> Convert a few classes to be more thread-safe

app/javascript/packages/document-capture/components/acuant-selfie-capture-canvas.jsx
This PR fixes an issue where the hint text was not showing on Android/Chrome by moving the hint text inside the div that the Acuant SDK binds to. Before this PR the hint text would not show up on Android/Chrome most of the time.
I've tested that the hint text appears with this PR for:
- Android/Chrome
- iOS/Chrome
- iOS/Safari
=> Fix Missing Hint Text on Android - Move the hint text inside the capture div

spec/support/fake_analytics_spec.rb, spec/support/have_logged_event_matcher.rb
I made a bunch of changes to how `have_logged_event` works in #10334, but I just found an issue where an error message is slightly weird in cases where an event is logged with extra, unexpected arguments. This PR tweaks the error message and adds a spec to cover the "extra arguments" case.
=> Tweak error message for have_logged_event

app/controllers/concerns/rate_limit_concern.rb, spec/controllers/idv/phone_controller_spec.rb, spec/controllers/idv_controller_spec.rb
Previously: #10258, #10309
This PR:
- Updates `IdvController` to use `have_logged_event` and removes `allowed_extra_analytics`
=> Update IdvController spec to use have_logged_event

app/services/analytics_events.rb, app/services/idv/analytics_events_enhancer.rb, app/services/idv/profile_logging.rb, spec/controllers/idv/by_mail/letter_enqueued_controller_spec.rb, spec/controllers/idv/by_mail/request_letter_controller_spec.rb, spec/controllers/idv/cancellations_controller_spec.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/controllers/idv/otp_verification_controller_spec.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/controllers/idv/phone_controller_spec.rb, spec/controllers/idv/please_call_controller_spec.rb, spec/controllers/idv/resend_otp_controller_spec.rb, spec/controllers/idv/sessions_controller_spec.rb, spec/features/idv/analytics_spec.rb, spec/features/idv/cancel_spec.rb, spec/services/idv/analytics_events_enhancer_spec.rb, spec/services/idv/profile_logging_spec.rb
[LG-12617](https://cm-jira.usa.gov/browse/LG-12617)
This PR updates the `Idv::AnalyticsEventsEnhancer` to add more fields to covered Idv-related events. Previously, we were only adding `proofing_components`. With this update we will add:
* `pending_profile_idv_level`: The verification level associated with the user's pending profile
* `active_profile_idv_level`: The verification level associated with the user's active profile
Additionally, a subset of events will have a new `profile_history` argument added. This argument is an array. Each item is a hash including the following fields:
* `id`
* `active`
* `idv_level`
* `created_at`
* `verified_at`
* `activated_at`
* `in_person_verification_pending_at`
* `gpo_verification_pending_at`
* `fraud_review_pending_at` …
=> LG-12617: Add additional profile-related fields to enhanced Idv events

app/controllers/concerns/fraud_review_concern.rb, app/controllers/concerns/verify_profile_concern.rb, app/models/user.rb, spec/features/idv/in_person_threatmetrix_spec.rb
[LG-12729](https://cm-jira.usa.gov/browse/LG-12729)
- Added new redirect in `verify_profile_concern` for cases where the user has failed IPP and has fraud_review_pending on their profile
- Added a new method on the user model to condense some repeated methods
- Uncommented and passed specs from [LG-12067](https://github.com/18F/identity-idp/pull/10231) 
Complete local testing for Threatmetrix for a passed enrollment:
<hr>
Complete local testing for Threatmetrix for a failed enrollment:
=> LG-12729 Please Call page shows for passed IPP enrollments only

spec/features/idv/doc_auth/how_to_verify_spec.rb, spec/features/idv/doc_auth/hybrid_handoff_spec.rb
No ticket. Noticed a few failing specs and realized they were related to some changes done to the How To Verify page and supporting specs. This pr should get the specs back to green.
=> Fixing spec issues related to How to Verify page changes

app/controllers/idv/by_mail/enter_code_controller.rb, app/views/idv/by_mail/enter_code/_form.html.erb, spec/features/idv/steps/enter_code_step_spec.rb
The verify-by-mail flow’s enter code screen has a hidden field for the “did_not_receive_letter” param. This allowed the “Did not receive letter” UI to be applied after a failed submission by inspecting the param like so:
```ruby
def user_did_not_receive_letter?
!!params[:did_not_receive_letter]
end
```
However, the hidden input submits an empty string when the `@user_did_not_receive_letter` ivar is set to false. The empty string is truthy which made the UI revert to the “Did not receive letter” experience.
This commit fixes the issue by calling `present?` on the param.
=> Fix issue where the “Did not receive letter” UI appears after incorrect submission

app/assets/stylesheets/_uswds.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/variables/_app.scss, app/components/modal_component.html.erb, app/components/modal_component.rb, app/components/modal_component.scss, app/javascript/packages/modal/README.md, app/javascript/packages/modal/modal-element.spec.ts, app/javascript/packages/modal/modal-element.ts, app/javascript/packages/modal/package.json, lib/extensions/capybara/node/simple.rb, spec/components/modal_component_spec.rb, spec/support/capybara.rb, spec/views/layouts/application.html.erb_spec.rb
Reimplements `ModalComponent` as a [native `<dialog>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog).
**Why?**
- Using native functionality helps ensure consistent experience and avoid need for custom implementation of individual behaviors
- Removing `focus-trap` removes a sizable dependency
- Deletes substantial amount of modal styles in favor of browser defaults
**Behavior Differences:**
This should largely behave identically to previous, with a couple minor differences:
- Native `<dialog>` supports pressing <kbd>Escape</kbd> to close the modal, which is a [WAI recommended keyboard interaction](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/#keyboardinteraction), but did not happen in our previous implementation
- The only downside of this is that if a …
=> Implement modal component as native dialog element

spec/features/users/piv_cac_management_spec.rb
Improve PIV CSP test assertion for order independence, to resolve a flakey test.
Example: https://gitlab.login.gov/lg/identity-idp/-/jobs/1114999
The issue is that the previous assertion assumed that the `form-action` directive would never occur last and therefore always be suffixed with `;`. This doesn't appear to always be deterministic. The solution is to split the directives by the semi-colon joiner, which also preserves the expectation that the `form-action` value _only_ includes the asserted text.
```
rspec spec/features/users/piv_cac_management_spec.rb:18
```
=> Improve PIV CSP test assertion for order independence

lib/identity_config.rb, spec/lib/identity_config_spec.rb
Improves `IdentityConfig` converter for `comma_separated_string_list` to support CSV values embedding commas within double-quoted segments.
This is in response to a [recent discovery that this was unsupported](https://gsa-tts.slack.com/archives/C5QUGUANN/p1711990069167089?thread_ts=1710534224.779029&cid=C5QUGUANN), which led to delays implementing a fix, and required a workaround in #10346 and patch deploy of [RC 367.1](https://github.com/18F/identity-idp/releases/tag/2024-04-01T191527). The changes included here could have avoided the need for that.
```
rspec spec/lib/identity_config_spec.rb
```
Validate compatibility of remaining uses of `comma_separated_list_value`:
* `requests_per_ip_cidr_allowlist`
* `requests_per_ip_path_prefixes_allowlist`
* `test_ssn_allowed_list`
=> Parse config CSV values as CSV

lib/identity_config.rb
Swaps `String#parse_csv` monkeypatch with more explicit `CSV.parse_line`, as suggested at https://github.com/18F/identity-idp/pull/10354#discussion_r1550099351 .
```
rspec spec/lib/identity_config_spec.rb
```
=> Use CSV.parse_line for config CSV parse

app/services/doc_auth_router.rb, spec/services/doc_auth_router_spec.rb
A followup to https://github.com/18F/identity-idp/pull/9561 where fallback logic was added to handle vendors and selfies. With only two vendors remaining after https://github.com/18F/identity-idp/pull/10198, this fallback logic no longer seems to be necessary.
=> Remove Doc Auth AB Test Fallbacks

spec/features/accessibility/idv_pages_spec.rb
I did some testing to ensure that the same pages are tested for accessibility, this should only be a reduction in duplicative tests. This is intended to be a speed improvement on #4000 and the intervening changes since then.
I added a small patch to keep track of which pages the test file was running accessibility checks on to be more sure we aren't losing accessibility coverage. We'd expect to see some duplication since the mobile test shares many of the same pages. The results don't suggest that we've lost any coverage, so this change should be a reduction in time spent without any reduction in test coverage.
Before:
```
[["/verify/agreement", 2], ["/verify/cancel", 1], ["/verify/document_capture", 2], ["/verify/enter_password", 3], ["/verify/how_to_verify", 1], …
```
=> Consolidate identity verification accessibility tests to improve test speed

Gemfile.lock, app/views/devise/sessions/new.html.erb, app/views/idv/how_to_verify/show.html.erb, spec/support/matchers/accessibility.rb
Enhances existing accessibility checks to verify that no duplicate IDs exist.
Related WCAG Failure: [F77: Failure of Success Criterion 4.1.1 due to duplicate values of type ID](https://www.w3.org/WAI/WCAG21/Techniques/failures/F77.html)
Previous discussion: https://github.com/18F/identity-idp/pull/10289#discussion_r1543176423
Ideally this would be something our existing Axe-based testing tools could identify (Axe even has [an article for a related rule](https://dequeuniversity.com/rules/axe/4.1/duplicate-id)), but I could not cause an issue to be flagged in my testing with either the Ruby-based Axe tool nor the Chrome browser extension.
Verify that build with commit including demonstrated failure fails (12ae6e40e06165df5473b29aab84e2d8fe64d1ef), and passes without.
(TBD if there's any …
=> Check duplicate element IDs in accessibility tests

Gemfile, Gemfile.lock
This fixes log writing failures of the form
'log writing failed. "\xB5" from ASCII-8BIT to UTF-8'.
=> Use version 0.19.3-18f of saml-idp

spec/rails_helper.rb
Ensures that the JavaScript build which runs when executing a test using the JavaScript driver in tests will invalidate the cached assets manifest.
This resolves an issue where running JavaScript feature specs locally could result in Content-Security-Policy errors in trying to load scripts from http://localhost:3035/ (the Webpack dev server).
This may have been made more prevalent by recent changes in #10301 to eagerly cache the manifest, though likely existed prior.
As outlined in the included inline code comment, the problem is that the application will cache whatever manifest exists at startup, but the JavaScript build happens on-demand. Therefore, the application may try to load incorrect URLs if the on-demand build would produce a different manifest.
1. Run `make run`. This will …
=> Fix manifest cache for local JavaScript feature tests

app/services/event_disavowal/find_disavowed_event.rb
Updates `EventDisavowal::FindDisavowedEvent#event` to avoid loading all events matching token fingerprints.
This is the result of a discussion with @jmhooper stemming from surprise around performance characteristics noted in #2855. While `#first` would still be advisable to avoid here due to built-in ordering (["if no order is defined it will order by primary key"](https://api.rubyonrails.org/v7.1.3.2/classes/ActiveRecord/FinderMethods.html#method-i-first)), `#find_by` will locate at most one record without imposing any order. `#take` would have also worked.
The previous implementation was likely fine enough since the logic producing fingerprints would likely only ever produce 0 or 1 database results, but these revisions are simpler and more semantic, and should hopefully avoid future …
=> Update disavowed event lookup to load one record

app/components/README.md, docs/frontend.md
Updates `docs/frontend.md` and `app/components/README.md` to more accurately describe behaviors associated with script and stylesheet auto-loading.
Specifically, #8375 added support for component-specific stylesheets, but did not include documentation revisions for how it is to be used. That's what this pull request seeks to address.
Validate that you can follow the included documentation to understand how to auto-load a stylesheet accompanying a component.
=> Update component documentation to describe stylesheet auto-loading

app/javascript/packages/build-sass/CHANGELOG.md, app/javascript/packages/build-sass/README.md, app/javascript/packages/build-sass/cli.js, app/javascript/packages/build-sass/get-error-sass-stack-paths.js, app/javascript/packages/build-sass/get-error-sass-stack-paths.spec.js
Fixes `@18f/identity-build-sass` to rebuild stylesheets as expected after saving a file that had previously triggered an error.
This relied on parsing a stack trace produced by Sass. It appears that this stack trace was updated to produce paths relative from the compiler executable.
For future consideration:
- Open an issue to [`sass/embedded-host-node`](https://github.com/sass/embedded-host-node) to provide full compilation result in an error. This is related to https://github.com/sass/embedded-host-node/issues/190 . A failed compilation includes [`loadedUrls`](https://sass-lang.com/documentation/js-api/interfaces/compileresult/#loadedUrls), but there's no way to get at these since the failed result [raises an error without the full result …
=> Fix Sass compilation rebuild after error

app/controllers/idv/address_controller.rb, app/forms/idv/address_form.rb, app/presenters/idv/address_presenter.rb, app/views/idv/address/new.html.erb, spec/controllers/idv/address_controller_spec.rb, spec/forms/idv/address_form_spec.rb, spec/views/idv/address/new.html.erb_spec.rb
While I was working on #10385 I noticed that the `Idv::AddressController` includes a form object but does not implement the Form Object Pattern the way I expected. Specifically the form was only initialized and used to validate input params. As a result a few of the expected features were missing. Namely error messages did not appear on the rendered view. This commit adjusts `Idv::AddressController` to use the pattern as expected.
This commit also adds specs for `Idv::AddressForm` which I noticed were missing despite the form object having some complexity to account for the `address_edited` value in the `FormResponse`.
Now the form looks like this if you submit an error:
Previously this was not the case. The form would not render errors at all. This was not a huge issue since there was …
=> Use form object pattern for `Idv::AddressController` submission

app/javascript/packages/document-capture/components/document-capture-review-issues.tsx, app/javascript/packages/document-capture/components/documents-step.tsx, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, spec/javascript/packages/document-capture/components/documents-step-spec.jsx
[LG-12804](https://cm-jira.usa.gov/browse/LG-12804)
Update instruction and tips for taking ID photos and selfie.
Scenario 1:
Non Selfie Desktop:
Scenario 2:
Non Selfie Mobile:
Scenario 3:
Selfie Mobile:
<details>
| Non Selfie Desktop | Non Selfie Mobile |
| ------------------ | ----------------- |
| ![LG-12804-NonSelfie_Desktop-Before](https://github.com/18F/identity-idp/assets/130466753/3332529b-dcab-4455-b966-e5adaa04416f) | ![LG-12804_NonSelfie_Mobile-Before](https://github.com/18F/identity-idp/assets/130466753/09e678da-eccb-4333-9bb3-4f4848745b81) |
</details>
<details>
Non Selfie …
=> LG-12804: add ID photo and selfie content change.

spec/features/idv/doc_auth/document_capture_spec.rb
Prep for [LG-12994](https://cm-jira.usa.gov/browse/LG-12994)
I will be adding new tests here as a part of this ticket, and found that we had the following selfie test setup twice:
```
context 'when a selfie is required by SP', allow_browser_log: true do
before do
allow_any_instance_of(FederatedProtocols::Oidc).
to receive(:biometric_comparison_required?).
and_return(true)
```
This change removes one of them.
I also:
- added an explicit "selfie passing" context around the relevant test
- had to move `allow_browser_log: true` up the chain for tests to continue to pass.
In github this ends up looking like a big change since I have to change indentation, so I wanted to do it as a separate PR. That way when adding tests what is being changed will be more clear.
All automated tests should …
=> Rm duplicate test setup

Gemfile.lock, app/controllers/idv/address_controller.rb, app/services/idv/session.rb, app/services/pii/address.rb, spec/controllers/idv/address_controller_spec.rb
Currently `Idv::AddressController` collects an updated address from the user and merges it into `pii_from_doc` in `idv_session`. This results in the address that was read from the doc being overwritten. This approach leads to a few issues:
1. It necessitates a `address_edited` property on `Idv::Session` and custom code to maintain the value of that column. This code also has a tricky bug where it does not track address edits if the same data is submitted twice.
2. It differs from the in-person workflow where the document address and the user address are maintained separately for use in double address verification
This commit introduces a new pattern where the PII collected from the user is stored in an immutable object in the `Idv::Session`. This lets us be confident that the PII we have …
=> Add `Pii::Address` and use it store address in `Idv::AddressController`

app/models/user.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/models/user_spec.rb
When a user proofs in-person they satisfy the biometric comparison requirement since that is done when they present their document. This was not recognized as satisfying the biometric requirement in the code. This commit makes adjustments so that it does.
=> LG-13022 Allow in-person proofing to satisfy biometric comparison requirement

config/initializers/geocoder.rb
Updates geocoder initializer to avoid loading the geocoder file in test environments.
This is a partial reversal of #10319, while still allowing the geocoder to be initialized for local development.
This resolves an issue where tests may fail when trying to geocode an IP address.
1. Follow the instructions to set up geolocation
1. Alternatively, download live database from S3
2. Run: `rspec spec/controllers/users/piv_cac_login_controller_spec.rb`
3. Observe all tests pass
Previous failure example:
```
Failure/Error: @geocoded_location ||= Geocoder.search(ip).first
ActionView::Template::Error:
unknown stub request 0.0.0.0
```
=> Avoid initializing geocoder in test environments

app/javascript/packages/webauthn/enroll-webauthn-device.spec.ts, app/javascript/packages/webauthn/enroll-webauthn-device.ts, app/javascript/packs/webauthn-setup.ts
[LG-12571](https://cm-jira.usa.gov/browse/LG-12571)
When enrolling a non-platform webauthn device it passes the value 'security-key' with the `authenticatorSelection` object.
Platform devices will have 'client-device' added.
https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialhints-client-device
Test for enroll-webauthn-device should pass.
Setup should work as before without any issues.
=> LG-12571 Specify "hints" for WebAuthn security key enrollment

config/application.yml.default
We have approval to enable VTRs and we will be preferring them over the old ACR values in most envs. This commit changes the default config to reflect that in the config.
=> Change the default value of `use_vot_in_sp_requests` to true

.gitlab-ci.yml, Brewfile, Gemfile, Gemfile.lock, config/database.yml, db/primary_migrate/20230518221444_add_postgis_extension_to_database.rb, db/schema.rb, docs/local-development.md, docs/troubleshooting.md
- Code that leveraged this never landed on main (https://github.com/18F/identity-idp/pull/7790)
=> Remove PostGIS

Gemfile, Gemfile.lock
This PR reverts the upgrade of `cssbundling-rails` due to issues we ran into in deployed environments. That patch is here: https://github.com/18F/identity-devops/pull/7263.
The upgrade can be re-applied once the above PR is merged.
=> Revert cssbundling-rails upgrade

Makefile, app/assets/stylesheets/_uswds.scss, app/assets/stylesheets/navigation.css.scss, app/views/accounts/_nav_auth.html.erb, app/views/events/show.html.erb, app/views/layouts/account_side_nav.html.erb, app/views/layouts/application.html.erb, app/views/layouts/base.html.erb, spec/views/accounts/_nav_auth.html.erb_spec.rb
Moves header styles out of the critical-path stylesheet (`application.css`) and into the dedicated stylesheet for the account page where the header is implemented (`navigation.css`).
**Why?**
- Reduces size of common application stylesheet
- Avoids bringing in additional unused styles (e.g. `usa-search`), since we only use [the base `usa-header` class](https://github.com/18F/identity-idp/blob/e578719946b2d3c965e7cd41924b6b9c284f1e17/app/views/layouts/application.html.erb#L9)
**Performance Impact:**
```
NODE_ENV=production yarn build:css
brotli-size app/assets/builds/application.css
brotli-size app/assets/builds/navigation.css
```
Stylesheet|Before|After|Net Diff|Percent Diff
---|---|---|---|---
`application.css`|21.3 kB|18.7 kB|-2.6 kB|-12.2%
`navigation.css`|2.27 kB|3.06 kB|+0.79 …
=> Shift header styles to navigation (account) stylesheet

app/components/phone_input_component.html.erb, app/components/phone_input_component.rb, app/javascript/packages/captcha-submit-button/captcha-submit-button-element.spec.ts, app/javascript/packages/captcha-submit-button/captcha-submit-button-element.ts, app/javascript/packages/phone-input/README.md, app/javascript/packages/phone-input/index.spec.ts, app/javascript/packages/phone-input/index.ts, app/services/phone_recaptcha_validator.rb, app/views/users/phone_setup/index.html.erb, spec/components/phone_input_component_spec.rb, spec/services/phone_recaptcha_validator_spec.rb
[LG-12871](https://cm-jira.usa.gov/browse/LG-12871)
Updates client-side reCAPTCHA behavior to always invoke during client-side form submission, regardless of whether the user is exempted from backend validation.
This is based on a recommendation to improve the quality of assessments by avoiding bias toward certain subsets of users.
Prerequisite: You'll need valid reCAPTCHA keys for at least the invisible check. In local development, you can use keys generated yourself with the free version of reCAPTCHA:
1. Go to https://www.google.com/recaptcha/admin
2. Create keys for local development as a "Score based (v3)" type
3. Update configuration in `config/application.yml`, adding your v3 site and secret keys. v2 values need to be present, but they don't need to be valid keys.
``` …
```
=> LG-12871: Remove exceptions for client-side reCAPTCHA execute

app/controllers/concerns/two_factor_authenticatable_methods.rb, app/controllers/users/piv_cac_login_controller.rb, app/models/event.rb, app/services/create_new_device_alert.rb, app/services/user_alerts/alert_user_about_new_device.rb, app/services/user_event_creator.rb, config/locales/event_types/en.yml, config/locales/event_types/es.yml, config/locales/event_types/fr.yml, config/locales/user_mailer/en.yml, config/locales/user_mailer/es.yml, config/locales/user_mailer/fr.yml, spec/controllers/concerns/two_factor_authenticatable_methods_spec.rb, spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb, spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb, spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb, spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb, spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb, spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb, spec/controllers/users/piv_cac_login_controller_spec.rb, spec/factories/users.rb, spec/features/event_disavowal_spec.rb, spec/features/new_device_tracking_spec.rb, spec/features/two_factor_authentication/sign_in_via_personal_key_spec.rb, spec/services/user_alerts/alert_user_about_new_device_spec.rb, spec/services/user_event_creator_spec.rb
[LG-12294](https://cm-jira.usa.gov/browse/LG-12294)
Implements the dispatching of a new aggregated email notification for sign-in, which happens 5 minutes after successful email and password submission, or immediately upon successful MFA, whichever occurs first.
This builds upon ("wires up") previous work in #10314 (email template) and #10317 (worker for delayed notification).
Verify that you are sent an email immediately upon full authentication:
1. In a private browsing session ("Incognito"), visit http://localhost:3000
2. Sign in with email and password
3. Complete MFA step
4. Observe you see an email notification immediately with listed events
- Note that it's likely to show "unknown location" since events save `'::1'` as the IP address in local development
Verify that you are sent an …
=> LG-12294: Send single aggregated email notification for new device sign-in

Makefile, app/assets/stylesheets/_uswds.scss
Removes unused styles for the `usa-form` USWDS form component.
Despite having many forms, we never use the `usa-form` class. We do use `usa-form-group` styles, but these are [included separately](https://github.com/18F/identity-idp/blob/f354510e253243d71712a5d91a8a1f19b6e2537b/app/assets/stylesheets/_uswds-form-controls.scss#L4).
**Performance Impact:**
```
NODE_ENV=production yarn build:css && brotli-size app/assets/builds/application.css
```
**Before:** 18.7 kB
**After** 18.4 kB
**Diff:** -0.3 kB (-1.6%)
Verify there are no instances of `usa-form` class use in the codebase.
=> Remove unused usa-form styles

app/assets/stylesheets/application.css.scss, app/assets/stylesheets/print.css.scss, app/assets/stylesheets/print.scss, app/views/layouts/base.html.erb
Splits print styles to separate stylesheet, so that it's only loaded when printing.
**Why?**
- Reduce size of stylesheet for users browsing the web version of the site
**Performance Impact:**
```
NODE_ENV=production yarn build:css && brotli-size app/assets/builds/application.css
```
_Before:_ 18.4 kB
_After:_ 18.3 kB
_Diff:_ -0.1 kB (-0.5%)
Verify that print styles are preserved:
2. Press <kbd>Cmd+P</kbd>
3. Observe that the preview does not include the "Submit" button
Verify that the print stylesheet is not preloaded:
1. In a separate Terminal process, run: `curl -I --silent http://localhost:3000 | grep 'link:'`
2. Verify that the output does not include `print.css`
=> Split print styles to separate stylesheet

app/services/user_alerts/alert_user_about_new_device.rb, spec/mailers/report_mailer_spec.rb, spec/mailers/user_mailer_spec.rb, spec/support/shared_examples_for_mailer.rb
Supplemental fix for [LG-12294](https://cm-jira.usa.gov/browse/LG-12294)
Fixes an issue where asynchronous delivery of aggregated new device sign-in email notifications raises an error, due to non-serializable arguments.
```
ActiveJob::SerializationError:
Unsupported argument type: ActiveRecord::AssociationRelation
```
Related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1712932922568999
1. Add `deliver_mail_async: true` to `config/application.yml`
2. In a private browsing window (Incognito), go to http://localhost:3000
3. Sign in and MFA
4. Observe no errors after fully authenticated
=> LG-12294: Fix asynchronous email delivery for aggregated sign-in email

yarn.lock
Updates resolved versions of `express` and `follow-redirects` to resolve outstanding security advisories, as transitive dependencies of `webpack-dev-server`.
- CVE-2024-29041
- CVE-2024-28849
This was meant to be addressed in #10350, but the updated version of `webpack-dev-server` did not require a minimum version of `express` and `follow-redirects` to resolve the advisory.
The process for performing this update was to manually remove top-level entries of `express` and `follow-redirects` from `yarn.lock` and running `yarn install` to allow the latest version of the dependencies that satisfies the version constraints of their ancestor dependency (`webpack-dev-server`). This is something that a tool like `npm audit fix` would automate for us, but an equivalent tool does not exist in Yarn …
=> Reinstall Express dependencies for webpack-dev-server advisory

app/models/user.rb
Marks `remember_created_at` on the User model as ignored, as a prerequisite to removing the column in #10429.
See: https://github.com/18F/identity-idp/pull/10429#pullrequestreview-2001135779
Verify that selecting all fields from a user does not produce a query including `remember_created_at`:
```
$ rails c
> User.first
```
=> Add user remember_created_at as ignored column

app/controllers/users/two_factor_authentication_controller.rb, config/application.yml.default, lib/identity_config.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb
Related to #10360. This has been tested and can be enabled everywhere.
=> Remove short_term_phone_otp_rate_limiter_enabled configuration key

app/javascript/packages/document-capture/components/unknown-error.tsx, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml
[LG-12829](https://cm-jira.usa.gov/browse/LG-12829)
Add a link to the error message that directs the user to the help center when selfie match fails.
<details>
<summary>Liveness:</summary>
</details>
<details>
<summary>FaceMatch:</summary>
</details>
=> LG-12829: add conditional links for selfie help center articles

app/services/user_alerts/alert_user_about_new_device.rb, spec/services/user_alerts/alert_user_about_new_device_spec.rb
Supplemental improvement for [LG-12294](https://cm-jira.usa.gov/browse/LG-12294)
Updates logic for aggregated email sign-in notification to prevent stale events from being included in the email.
Related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1713191072377119?thread_ts=1712932922.568999&cid=C0NGESUN5
Examples:
- As discussed in the Slack thread above, enabling in sandbox environments and then quickly disabling to address #10421 produced stale events when re-enabling today
- As discussed in the Slack thread above, starting local development server today (Monday) prompted an email notification for sign-ins that occurred at the end of day Friday
Verify tests pass:
```
rspec spec/services/user_alerts/alert_user_about_new_device_spec.rb
```
Verify you don't get an email …
=> LG-12294: Set maximum delay for aggregated email events

app/models/user.rb, app/presenters/idv/welcome_presenter.rb, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, spec/presenters/idv/welcome_presenter_spec.rb, spec/views/idv/welcome/show.html.erb_spec.rb
[LG-12624](https://cm-jira.usa.gov/browse/LG-12624)
Updated sub-heading text for step-up users.
Updated bullet points 1 and 3, and their associated text.
<details>
<summary>New User (English):</summary>
</details>
<details>
<summary>New User (Spanish):</summary>
</details>
<details>
<summary>New User (French):</summary>
</details>
<details>
<summary>Step-up User (English):</summary>
</details>
<details>
<summary>Step-up User (Spanish):</summary>
</details>
<details>
<summary>Step-up User (French):</summary>
</details>
<details>
<summary>French "Getting Started" screen (new user)</summary>
</details>
<details>
<summary>French "Getting …
=> LG-12624 additional content update for getting started screen

app/controllers/idv/address_controller.rb, app/controllers/idv/verify_info_controller.rb, app/forms/idv/address_form.rb, spec/forms/idv/address_form_spec.rb
In #10385 we started writing the address the user provides in the `Idv::AddressController` to `idv_session.updated_user_address`. This commit starts reading the address from there so that we can eventually stop overwriting the address in `pii_from_doc`.
=> Start reading from `idv_session.updated_user_address`

spec/fixtures/ial2_test_credential_classification_info_no_name.yml, spec/fixtures/ial2_test_portrait_match_success.yml
This does not cause an issue because these failures are empty. But
when copying from them to create new yml files I discovered the
key is wrong and should be fixed.
=> Fix failed_alerts key in test yml files

app/services/idv/steps/doc_auth_base_step.rb
The `add_cost` and `add_costs` methods both create `SpCost` records for `FlowStateMachine` steps that inherit from `Idv::Steps::DocAuthBaseStep`.
We [removed the `FlowStateMachine`](https://github.com/18F/identity-idp/pull/8705) from all paths that lead to the creation of an `SpCost` record about a year ago. The [`FlowStateMachine`](https://github.com/18F/identity-idp/blob/main/app/services/flow/flow_state_machine.rb) and associated [`Idv::Steps::DocAuthBaseStep`](https://github.com/18F/identity-idp/blob/main/app/services/idv/steps/doc_auth_base_step.rb) remain, however, to support the in-person flow. The in-person flow does not create `SpCost` records in the `FlowStateMachine`.
These methods, like many methods in `FlowStateMachine` relics, are unused. We left these unused methods because …
=> Remove `add_cost` and `add_costs` method from `Idv::Steps::DocAuthBaseStep`

app/models/user.rb, db/primary_migrate/20240415125124_drop_remember_created_at_from_users.rb, db/schema.rb
Removes the `remember_created_at` column from the `users` table.
This field is not currently used, and as best I can tell has never been referenced as far back as #1.
Verify migration runs cleanly:
```
rails db:migrate
```
Verify no lingering references to the removed column.
=> Remove unused remember_created_at user column

app/javascript/packages/captcha-submit-button/captcha-submit-button-element.spec.ts, app/javascript/packages/captcha-submit-button/captcha-submit-button-element.ts
Updates `CaptchaSubmitButtonElement` to avoid preventing submission in case reCAPTCHA is unable to load.
This should typically never happen, but error logs indicate that there are a low number of cases where reCAPTCHA is unavailable at the time that it's meant to be executed. It is likely these are caused by ad blockers or other script blockers, but it could also be due to any number of network interruptions.
Regardless the cause, since #10408 removed exceptions to the client-side reCAPTCHA call, it is important that this does not become a blocker to someone's ability to submit the page, particularly if they would be exempt from the backend assessment result validation.
Related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1713294014865199
This is hard to simulate, but …
=> Allow form submission when reCAPTCHA fails to load

app/controllers/idv/address_controller.rb, spec/controllers/idv/address_controller_spec.rb
In #10390 we started using the new `idv_session.updated_user_address` value to represent the user address if it is present. This allows us to stop overwriting the user address that was on the document in `pii_from_doc`. We were not able to actually take this step because of the 50/50 state issues related to session updates.
This commit stops overwriting the PII from the document in `pii_from_doc` when a new address is provided in `Idv::AddressController`
=> Stop adding updated address to `idv_session.pii_from_doc`

app/components/accordion_component.html.erb, spec/components/accordion_component_spec.rb
This updates Accordion component markup, removing invalid `usa-accordion__container` wrapper element, in order to allow the intended improvement from [`@18f/identity-design-system@9.1.0`](https://github.com/18F/identity-design-system/releases/tag/v9.1.0) to prevent flashing content during page load.
This follows a similar change from the introduction of that enhancement in https://github.com/18F/identity-design-system/pull/434 to alter the documented component markup, "[removing] an unnecessary and useless `usa-accordion__container` container element which is not standard to USWDS and would make the JavaScript hiding behavior ineffective".
3. At password entry screen, refresh the page with cache disabled
4. Observe no flash of open …
=> Fix flash of accordion content during page load

config/routes.rb
Follow-up task for [LG-13033](https://cm-jira.usa.gov/browse/LG-13033)
Removes a temporary redirect route added in #10404 for transitionary period during and after deploy.
Since this has been live for a week, it's safe to drop. I've confirmed drop-off in logs in CloudWatch.
1. Go to http://localhost:3000/sign_up/enter_email/resend
2. Observe 404 error
=> Remove temporary redirect route for email resend

Gemfile, Gemfile.lock
Updates `cssbundling-rails` gem dependency to the latest version, from 1.0.0 to 1.4.0.
This reverts #10417, effectively unreverting #10412, now that required infrastructure changes are deployed.
1. Run `SKIP_YARN_INSTALL=true rails assets:precompile`
2. Verify that the first command you see is `yarn run` and not `yarn install`
=> Revert "Revert cssbundling-rails upgrade"

app/controllers/frontend_log_controller.rb, app/javascript/packages/document-capture/components/acuant-capture.tsx, app/javascript/packages/document-capture/components/acuant-selfie-camera.tsx, app/services/analytics_events.rb, spec/javascript/packages/document-capture/components/acuant-capture-spec.jsx
[LG-12177](https://cm-jira.usa.gov/browse/LG-12177)
Add event `idv_sdk_selfie_image_re_taken` of selfie retaken
=> LG-12177: selfie retaken log

db/primary_migrate/20210614145845_add_email_name_id_format_to_service_providers.rb
**Why**: Config values change over time, but migrations should be deterministic. This old migration ran what we would now run as an explicit backfill, based on live data.
Since the config that it depends on is no longer around, we can remove this block of code entirely
=> Remove nondeterministic DB migration code

app/components/button_component.rb, app/views/accounts/_pii.html.erb, app/views/idv/cancellations/new.html.erb, app/views/idv/confirm_start_over/before_letter.html.erb, app/views/idv/confirm_start_over/index.html.erb, app/views/idv/in_person/verify_info/show.html.erb, app/views/idv/verify_info/show.html.erb, app/views/session_timeout/_warning.html.erb, app/views/users/auth_app/edit.html.erb, app/views/users/authorization_confirmation/new.html.erb, app/views/users/backup_code_setup/edit.html.erb, app/views/users/piv_cac/edit.html.erb, app/views/users/webauthn/edit.html.erb, config/brakeman.ignore, spec/components/button_component_spec.rb, spec/views/users/backup_code_setup/edit.html.erb_spec.rb
Supports [LG-12716](https://cm-jira.usa.gov/browse/LG-12716)
Updates the backup codes regenerate confirmation screen primary button to use a link (`<a href="...">`) in place of a `<form action="..." method="get"><button>`.
This is related to the comment at https://github.com/18F/identity-idp/pull/10088#discussion_r1570623056, where it's theorized there may be misbehaving browser versions which incorrectly handle the form submission. By using an anchor tag link, it's hoped this resolves the unexpected requests we're seeing to the route planned for removal in #10088.
Related Slack thread: https://gsa-tts.slack.com/archives/C05MGJ72GU9/p1713455028604359
This also includes minor refactoring to use common conventions for rendering buttons and status pages.
Verify there is no regression in the …
=> Replace GET form with link for regenerating backup codes

config/application.rb, config/application.yml.default, config/initializers/rack_timeout.rb, lib/identity_config.rb, lib/idp/constants.rb, lib/telephony/pinpoint/voice_sender.rb, spec/lib/telephony/pinpoint/voice_sender_spec.rb
As we move towards supporting more languages, we will want to be able to enable locales per-environment so that we can continue working on content without yet displaying to end users.
=> Allow configuration of available locales

app/components/button_component.rb, app/components/download_button_component.rb, app/components/manageable_authenticator_component.html.erb, app/components/tab_navigation_component.html.erb, app/views/accounts/_auth_apps.html.erb, app/views/accounts/_emails.html.erb, app/views/accounts/_phone.html.erb, app/views/accounts/_piv_cac.html.erb, app/views/accounts/_webauthn_platform.html.erb, app/views/accounts/_webauthn_roaming.html.erb, app/views/accounts/actions/_generate_backup_codes.html.erb, app/views/accounts/actions/_regenerate_backup_codes.html.erb, app/views/idv/forgot_password/new.html.erb, app/views/idv/mail_only_warning/show.html.erb, app/views/idv/otp_verification/show.html.erb, app/views/idv/phone_errors/failure.html.erb, app/views/idv/phone_errors/warning.html.erb, app/views/idv/session_errors/warning.html.erb, app/views/idv/unavailable/show.html.erb, app/views/sign_up/cancellations/new.html.erb, app/views/two_factor_authentication/otp_verification/show.html.erb, app/views/two_factor_authentication/piv_cac_verification/show.html.erb, app/views/users/backup_code_setup/confirm_backup_codes.html.erb, app/views/users/piv_cac_login/new.html.erb, app/views/users/piv_cac_recommended/show.html.erb, app/views/users/piv_cac_setup_from_sign_in/prompt.html.erb, app/views/users/second_mfa_reminder/new.html.erb, app/views/users/verify_personal_key/new.html.erb, spec/components/button_component_spec.rb, spec/components/previews/button_component_preview.rb
Refactoring after #10464, which supports [LG-12716](https://cm-jira.usa.gov/browse/LG-12716)
Updates instances of `ButtonComponent` `action` to use the new `url` & `method` shorthand introduced in #10464.
Related comment: https://github.com/18F/identity-idp/pull/10464#discussion_r1571457278
Verify no regressions in the impacted buttons.
=> Update ButtonComponent usage to use url/method abstraction

app/controllers/openid_connect/user_info_controller.rb, app/services/access_token_verifier.rb, spec/controllers/openid_connect/user_info_controller_spec.rb, spec/services/access_token_verifier_spec.rb
[LG-13139](https://cm-jira.usa.gov/browse/LG-13139)
Fixes an issue where a token may become invalid between the time [it's initially validated](https://github.com/18F/identity-idp/blob/712c0ec191dd9746c3cf0f522143567ac59cecb1/app/controllers/openid_connect/user_info_controller.rb#L20) and when the [identity is referenced](https://github.com/18F/identity-idp/blob/712c0ec191dd9746c3cf0f522143567ac59cecb1/app/controllers/openid_connect/user_info_controller.rb#L24), since [each independently triggers validation to run](https://github.com/18F/identity-idp/blob/712c0ec191dd9746c3cf0f522143567ac59cecb1/app/services/access_token_verifier.rb#L14-L25).
~The proposed solution is to memoize the validity result, since the submission is not parameterized, so the result on an instance would not be …
=> LG-13139: Fix race condition with token verifier expired validity

app/services/doc_auth/mock/result_response.rb, spec/fixtures/ial2_test_credential_barcode_attention_no_address.yml, spec/fixtures/ial2_test_credential_no_address.yml, spec/fixtures/ial2_test_credential_no_dob.yml, spec/services/doc_auth/mock/doc_auth_mock_client_spec.rb, spec/services/doc_auth/mock/result_response_spec.rb
The `pii_from_doc` method in `DocAuth::Mock::ResultsResponse` is intended to mock the behavior of the `pii_from_doc` method on the LexisNexis TrueID client. That method uses [`DocAuth::LexisNexis::DocPiiReader`](https://github.com/18F/identity-idp/blob/a2b3cfcf78b127f6d8a7d8b5fbd27141add52159/app/services/doc_auth/lexis_nexis/doc_pii_reader.rb) to construct its response. As a result the response will always contain the same keys.
The `pii_from_doc` method in the mock client returns a set of default PII described by [`Idp::Constants::MOCK_IDV_APPLICANT`](https://github.com/18F/identity-idp/blob/a2b3cfcf78b127f6d8a7d8b5fbd27141add52159/lib/idp/constants.rb#L94) if an image is uploaded. If a user uploads a YAML file, however, the YAML can dictate what PII is returned. This commit makes …
=> Return default values for missing fields in `DocAuth::Mock::ResultsResponse#pii_from_doc`

Gemfile, Gemfile.lock, lib/deploy/activate.rb
- Only used in one place, easy to check response status
- [Kernel#system](https://ruby-doc.org/core-3.0.2/Kernel.html#method-i-system) returns true/false, we can just check that and throw an error as needed
=> Remove subprocess gem

Makefile, app/javascript/packages/assets/package.json, app/javascript/packages/build-sass/package.json, app/javascript/packages/eslint-plugin/package.json, app/javascript/packages/stylelint-config/package.json, scripts/enforce-typescript-files.mjs
Adds a new lint step as part of continuous integration to prevent the addition of new non-TypeScript script files.
This follows from our documented convention that ["all new code is expected to be written using TypeScript"](https://github.com/18F/identity-idp/blob/main/docs/frontend.md#at-a-glance-1), and motivated by observations that we're not always consistent in following this guideline.
Listing legacy files should hopefully also provide some incentive to port legacy files to TypeScript equivalents.
`make lint_new_typescript_files` should pass.
Try adding a new `.js` or `.jsx` file within `app/javascript`, `app/components`, or `spec/javascript`, and observe that `make lint_new_typescript_files` fails.
=> Lint to prevent additions of new non-TypeScript scripts

app/controllers/frontend_log_controller.rb, app/javascript/packages/document-capture/components/acuant-capture.tsx, app/javascript/packages/document-capture/components/acuant-selfie-camera.tsx, app/services/analytics_events.rb, spec/javascript/packages/document-capture/components/acuant-capture-spec.jsx
[LG-11981](https://cm-jira.usa.gov/browse/LG-11981)
Add `idv_sdk_selfie_image_capture_initialized` event.
=> LG-11981: selfie capture initialized

lib/identity_cors.rb, spec/requests/api_cors_spec.rb
This allows us to recreate the [Analytics Events](https://handbook.login.gov/articles/analytics-events.html) article behind internal login
=> Allow Gitlab pages sites to access via CORS

app/services/gpo_reminder_sender.rb, spec/jobs/gpo_reminder_job_spec.rb
[LG-13167](https://cm-jira.usa.gov/browse/LG-13167)
Fixes an issue in production where we get a NoMethodError when sending GPO reminder emails because we currently have a user with both a GPO pending profile and an active profile.
=> Don't send GPO reminders to users with active profiles

app/forms/idv/api_image_upload_form.rb, app/models/document_capture_session.rb, app/presenters/image_upload_response_presenter.rb, app/services/doc_auth/mock/result_response.rb, app/services/pii/state_id.rb, spec/forms/idv/api_image_upload_form_spec.rb, spec/services/doc_auth/mock/doc_auth_mock_client_spec.rb, spec/services/doc_auth/mock/result_response_spec.rb
In #10478 I modified the mock proofer to always return the full set of keys that the TrueID client returns from the `#pii_from_doc` method.
This commit continues on the work by introducing `Pii:StateId` to hold the data that is returned from `#pii_from_doc`. It is an immutable struct that holds the data and provides assurances about its shape by ensuring that data is present for every key.
In follow-up commits this data structure will be returned from the TrueID client and used to represent the PII from the document in `Idv::Session`.
=> Return a `Pii::StateId` object from `pii_from_doc` on the mock proofer

spec/i18n_spec.rb
While working on #10291, I was working on some improvements to the i18n tests and pulled them out here to make them easier to review. This PR makes a few changes:
- Check whether keys in ALLOWED_UNTRANSLATED_KEYS are used in untranslated keys test. It's kind of goofy to mutate the hashes in the constant and check it in the same test, but it was straightforward. I'm very open to suggestions here.
- Similar to above, check whether ALLOWED_INTERPOLATION_MISMATCH_KEYS are all used
The above will hopefully help in keeping the list of exceptions up-to-date.
I've also made some smaller changes to the checks in `allowed_untranslated_key?` so that we don't use a Regexp unless it is explicitly one, and otherwise use strict equality.
=> Increase strictness and improve ability to keep internationalization tests up-to-date

app/jobs/gpo_reminder_job.rb
This job pretty regularly takes more than 50s to run, which causes it to trigger the [worker perform time alarm](https://gsa-tts.slack.com/archives/C06M08T8LE5/p1714003668307909). Queuing it as `:long_running` will make it not trigger that alarm.
The job execution time scales with the number of reminder emails it needs to send. Average time / email over the last month or so is 0.3s. It may be possible to optimize this, but there are some basic I/O constrains (email sending and analytics logging) that will make that challenging.
=> Queue GpoReminderJob as long_running

app/controllers/frontend_log_controller.rb, app/javascript/packages/document-capture/components/acuant-capture.tsx, app/services/analytics_events.rb, spec/javascript/packages/document-capture/components/acuant-capture-spec.jsx
changelog: Internal, Doc Auth, Analytics event for selfie image taken.
[LG-12176](https://cm-jira.usa.gov/browse/LG-12176)
Analytics event `idv_sdk_selfie_image_taken`.
=> LG-12176: register and emit idv_sdk_selfie_image_taken event.

app/services/proofing/resolution/progressive_proofer.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/jobs/resolution_proofing_job_spec.rb, spec/services/proofing/resolution/progressive_proofer_spec.rb
=> LG-13025 - ThreatMetrix check should fail if we don't have a ThreatMetrix session id.

app/controllers/concerns/remember_device_concern.rb, app/decorators/null_service_provider_session.rb, app/decorators/service_provider_session.rb, spec/controllers/concerns/remember_device_concern_spec.rb, spec/decorators/null_service_provider_session_spec.rb, spec/decorators/service_provider_session_spec.rb
[LG-13037](https://cm-jira.usa.gov/browse/LG-13037)
Moved `ServiceProviderSession#mfa_expiration_interval` to `RememberDeviceConcern#mfa_expiration_interval`
Added a spec for it in the concern.
Removed as much associated plumbing from sp_session as was obvious.
=> LG-13037 Remove `mfa_expiration_interval` from sp session

app/services/doc_auth/lexis_nexis/doc_pii_reader.rb
This commit is in response to feedback on #10498 [ref](https://github.com/18F/identity-idp/pull/10498#discussion_r1578427544).
This method rebuilds the `#read_pii` method so it no longer maintains a map of keys to values and instead reads everything in-line where it can. I am hopeful this makes it a bit more succinct and readable.
=> Cleanup `DocPiiReader#read_pii`

app/controllers/openid_connect/authorization_controller.rb, app/forms/openid_connect_authorize_form.rb, app/services/store_sp_metadata_in_session.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/features/idv/doc_auth/document_capture_spec.rb, spec/features/idv/doc_auth/redo_document_capture_spec.rb, spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb, spec/features/openid_connect/authorization_confirmation_spec.rb, spec/forms/openid_connect_authorize_form_spec.rb, spec/services/store_sp_metadata_in_session_spec.rb, spec/support/features/idv_helper.rb, spec/support/features/idv_step_helper.rb, spec/support/oidc_auth_helper.rb
[LG-12576](https://cm-jira.usa.gov/browse/LG-12576)
Removes support for passing `?biometric_comparison_required=1` in the OIDC flow in favor of using a vector of trust including `Pb`.
=> Remove support for ?biometric_comparison_required

lib/pinpoint_supported_countries.rb
Fixes an issue where we get an error running `make lint_country_dialing_codes`. It looks like the `Sender ID support` section was updated to be a table, and our xpath query was a little too permissive and was getting the columns for all tables.
Stacktrace:
```
/builds/lg/identity-idp/lib/pinpoint_supported_countries.rb:116:in `block in load_country_dialing_codes': no phone_data for '', maybe it needs to be remapped? (RuntimeError)
```
=> Fix Pinpoint Maintenance Script

app/javascript/packages/document-capture/components/document-side-acuant-capture.tsx, app/javascript/packages/form-steps/form-error.ts, app/javascript/packages/form-steps/form-steps.tsx, config/locales/doc_auth/en.yml, config/locales/doc_auth/es.yml, config/locales/doc_auth/fr.yml, config/locales/doc_auth/zh.yml, spec/javascript/packages/document-capture/components/document-capture-spec.jsx
[LG-12824](https://cm-jira.usa.gov/browse/LG-12824)
Update the camera permission message.
Refactor form step error message processing(Alert), add a messageProcessor to format/process the configured message.
<details>
| En | Es | Fr | Zh |
| -- | -- | -- | -- |
| ![Permission_En](https://github.com/18F/identity-idp/assets/130466753/9880c82b-5788-48ca-ab19-71f2d74b9b99) | ![Permission_Es](https://github.com/18F/identity-idp/assets/130466753/0b606851-9a97-433d-9b25-33525c8f26c3) | ![CamPerm_Fr](https://github.com/18F/identity-idp/assets/130466753/82a4f062-48ff-4875-9673-41351c0d3109) | …
=> LG-12824: camera perm msg

Gemfile.lock
Updates `browser` gem to v6.0.0.
This adds support for a `chromium_based?` method which could be useful for our browser support detection. I requested this via https://github.com/fnando/browser/issues/541 with the intention of using it, though I can't recall exactly what I had planned to use it for.
Regardless, there seems to be some nice potential performance optimizations here that we could take advantage of in the meantime.
Notable code improvements are:
- [Using `instance_of?` vs. creating new instances when detecting browsers](https://my.diffend.io/gems/browser/5.3.1/6.0.0#d2h-913577)
- [Short-circuit return of relevant matcher in initialization](https://my.diffend.io/gems/browser/5.3.1/6.0.0#d2h-251020)
Build should pass.
=> Update browser gem to 6.0.0

app/controllers/idv/address_controller.rb, app/controllers/idv/ssn_controller.rb, app/controllers/idv/verify_info_controller.rb, app/services/idv/session.rb, spec/controllers/concerns/idv_step_concern_spec.rb, spec/controllers/idv/address_controller_spec.rb, spec/controllers/idv/enter_password_controller_spec.rb, spec/controllers/idv/link_sent_controller_spec.rb, spec/controllers/idv/otp_verification_controller_spec.rb, spec/controllers/idv/phone_errors_controller_spec.rb, spec/controllers/idv/ssn_controller_spec.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/controllers/idv/welcome_controller_spec.rb, spec/policies/idv/flow_policy_spec.rb, spec/support/flow_policy_helper.rb
Previous commits added the `Pii::StateId` data class. This is intended to hold the data that is read from the state ID. This has several advantages over the old approach (holding this data in a Hash):
1. It is immutable so it will error if you try to add data not from the state ID
2. It has defined attributes that are all required so you know what data will be present
This commit takes the next step in integrating this tool which is modifying `idv_session#pii_from_doc` to serialize the PII before it is written to the session and then deserialize it into `Pii::StateId` on read.
=> Return a `Pii::StateId` object from `idv_session.pii_from_doc`

.gitlab-ci.yml
It's managed by a secret in the helm chart now
changelog: Internal, reviewapps, remove postgres creds from config to make the new helm chart version happy
=> Remove postgres creds from config

app/forms/new_phone_form.rb, app/services/phone_recaptcha_validator.rb, app/services/recaptcha_enterprise_validator.rb, app/services/recaptcha_mock_validator.rb, app/services/recaptcha_validator.rb, spec/forms/new_phone_form_spec.rb, spec/services/phone_recaptcha_validator_spec.rb, spec/services/recaptcha_enterprise_validator_spec.rb, spec/services/recaptcha_mock_validator_spec.rb, spec/services/recaptcha_validator_spec.rb
Supports [LG-12873](https://cm-jira.usa.gov/browse/LG-12873)
Refactors reCAPTCHA validator classes to behave and validate as a [form class](https://github.com/18F/identity-idp/blob/main/docs/backend.md#forms-formresponse-analytics-and-controllers).
See previous discussion: https://github.com/18F/identity-idp/pull/10522#discussion_r1583611284
Validate that there are no regressions in the expected behavior of reCAPTCHA phone validation.
Configure reCAPTCHA score threshold in `config/application.yml`
```yml
phone_recaptcha_score_threshold: 0.5
```
3. When prompted to select MFA, choose phone
4. Enter an international phone number, e.g. `+610491570006`
5. In the reCAPTCHA score debugger tool, enter a value between 0.0 and 1.0
6. Click "Send …
=> Refactor reCAPTCHA validator as form model

app/models/gpo_confirmation_code.rb, db/primary_migrate/20240502192930_drop_bounced_at_column_from_usps_confirmation_code.rb, db/schema.rb
Drops the `bounced_at` column from the `usps_confirmation_codes` (`GpoConfirmationCode`) table.
Follow-up to #6775, which ignored the column, but it was never removed.
Verify migration applies cleanly:
```
rails db:migrate:primary
```
=> Drop unused bounced_at column from GpoConfirmationCode

config/application.yml.default
Adds a default score threshold for reCAPTCHA assessments in local development, to avoid having to require reviewers to specify this manually in `application.yml` in order to test related work (e.g. see Testing Plan in #10540).
3. When prompted to select MFA, choose phone
4. Enter an international phone number, e.g. +610491570006
5. In the reCAPTCHA score debugger tool, enter a value between 0.0 and 1.0
6. Click "Send code"
7. Observe that you are blocked if the score you entered was less than 0.5
=> Configure reCAPTCHA score threshold for local development

knapsack_rspec_report.json, spec/features/phone/rate_limiting_spec.rb, spec/support/shared_examples/phone/rate_limiting.rb
Fixes a few occurrences of a typo of the word "limiting", misspelled as "limitting".
=> Fix typo "limitting" ➡️ "limiting"

app/decorators/null_service_provider_session.rb, app/decorators/service_provider_session.rb, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml, config/locales/idv/zh.yml, spec/decorators/null_service_provider_session_spec.rb, spec/decorators/service_provider_session_spec.rb
Removes an unused method `SerivceProvider#verification_method_choice`
Added in #1227, and last reference removed in #2206.
=> Remove unused method verification_method_choice

app/views/idv/by_mail/enter_code/_enter_code.html.erb, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml, config/locales/idv/zh.yml, spec/features/idv/confirm_start_over_spec.rb, spec/features/idv/in_person_spec.rb, spec/features/idv/steps/enter_code_step_spec.rb, spec/features/idv/steps/request_letter_step_spec.rb, spec/support/idv_examples/clearing_and_restarting.rb, spec/support/idv_examples/verification_code_entry.rb
This commit makes changes to the Enter Code screen in the welcome back flow. It updates the address and “Clear my information and start over” link to be in an accordion, makes content updates, and rearranges some of the elements.
=> LG-11753 Update Enter Code (formerly, Welcome Back) Screen

app/views/idv/by_mail/enter_code/_did_not_receive_letter.html.erb, config/locales/idv/en.yml, config/locales/idv/es.yml, config/locales/idv/fr.yml, config/locales/idv/zh.yml, spec/features/idv/steps/enter_code_step_spec.rb, spec/features/idv/steps/request_letter_step_spec.rb, spec/views/idv/by_mail/enter_code/index.html.erb_spec.rb
This commit makes changes to the "Didn't get your letter" screen in the welcome back flow. It updates the address and “Clear my information and start over” link to be in an accordion, makes content updates, and rearranges some of the elements.
=> LG-12064 Update "Didn't get your letter?" screen

config/locales/doc_auth/es.yml
[LG-13106](https://cm-jira.usa.gov/browse/LG-13106)
Fixing one word in the translation.
In your local testing environment, add the following to your `application.yml`:
```
doc_auth_selfie_capture_enabled: true
proofing_device_profiling: enabled
```
then restart your server and do the following:
The resulting screen:
=> LG-13106: Post-LQA Content Error Fix | Step-up user GS in Spanish

app/controllers/two_factor_authentication/otp_verification_controller.rb, app/controllers/users/phone_setup_controller.rb, app/controllers/users/two_factor_authentication_controller.rb, app/forms/new_phone_form.rb, app/forms/recaptcha_enterprise_form.rb, app/forms/recaptcha_form.rb, app/forms/recaptcha_mock_form.rb, app/services/analytics_events.rb, app/services/recaptcha_annotator.rb, spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb, spec/controllers/users/phone_setup_controller_spec.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb, spec/features/phone/add_phone_spec.rb, spec/forms/new_phone_form_spec.rb, spec/forms/recaptcha_enterprise_form_spec.rb, spec/forms/recaptcha_form_spec.rb, spec/forms/recaptcha_mock_form_spec.rb, spec/services/recaptcha_annotator_spec.rb
[LG-12873](https://cm-jira.usa.gov/browse/LG-12873)
Updates phone setup flow to annotate a reCAPTCHA assessment after the user initiates and completes phone setup.
- https://cloud.google.com/recaptcha-enterprise/docs/annotate-assessment
Verify that you see events for annotating an assessment upon initiating and completing phone setup:
1. Have `make run` and `make watch_events` running in parallel in two separate terminal processes
2. Visit http://localhost:3000
3. Sign in or create an account
4. When possible, add a phone to your account (clicking "Add phone number" at the account dashboard if signing in, or choosing "Text or voice message" at the MFA selection screen during account creation)
5. Enter an international phone number, e.g. `+610491570006`
6. Click "Send …
=> LG-12873: Annotate reCAPTCHA assessments with MFA results

app/javascript/packages/stylelint-config/CHANGELOG.md, app/javascript/packages/stylelint-config/index.js, app/javascript/packages/stylelint-config/package.json
Partially addresses #10545 (cc @anselmbradford)
Updates Stylelint configuration to specify [optional `resolveNestedSelectors` property](https://stylelint.io/user-guide/rules/selector-class-pattern/#resolvenestedselectors-true--false-default-false) of the configured `selector-class-pattern` rule.
Verify `yarn lint:css` passes.
Optional: Validate that interpolated selector names consistently enforce the selector name validation:
Example:
```diff
diff --git a/app/javascript/packages/document-capture/components/_file-input.scss b/app/javascript/packages/document-capture/components/_file-input.scss
index 8967e4e1f9..8dcafd7c8e 100644
--- a/app/javascript/packages/document-capture/components/_file-input.scss
+++ b/app/javascript/packages/document-capture/components/_file-input.scss
@@ -10,2 …
```
=> stylelint-config: Resolve nested selectors with selector-class-pattern

spec/i18n_spec.rb
This PR makes a small proposed change to the error message around unused allowed untranslated keys from #10508 to give clearer instructions on the source of the failure and how to resolve it.
Old message:
```
Failure/Error:
expect(unused_allowed_untranslated_keys).to(
be_empty,
"unused allowed untranslated i18n keys: #{unused_allowed_untranslated_keys}",
)
unused allowed untranslated i18n keys: [{:key=>"titles.piv_cac_setup.upsell", :locales=>[:fr]}, {:key=>"titles.piv_cac_setup.upsell", :locales=>[:es]}]
```
Proposed message:
```
Failure/Error:
expect(unused_allowed_untranslated_keys).to(
be_empty,
<<~EOS,
ALLOWED_UNTRANSLATED_KEYS contains unused allowed untranslated i18n keys.
The following keys can be removed from ALLOWED_UNTRANSLATED_KEYS: …
```
=> Improve failure message for unused allowed untranslated keys test

lib/reporting/protocols_report.rb, spec/lib/reporting/protocols_report_spec.rb
https://gitlab.login.gov/lg-people/lg-people-appdev/protocols/common/-/issues/1
Added a CloudWatch report of:
1. authentication requests by protocol
2. SAML signatures - missing and invalid
=> Protocols report

lib/reporting/protocols_report.rb, spec/lib/reporting/protocols_report_spec.rb
Link to the relevant ticket: https://gitlab.login.gov/lg-people/lg-people-appdev/protocols/common/-/issues/2
Created a report of integrations using deprecated LOA ACR values.
=> Create a report of integrations using deprecated LOA ACR values

app/controllers/idv/in_person/state_id_controller.rb, spec/controllers/idv/in_person/state_id_controller_spec.rb
[LG-12376](https://cm-jira.usa.gov/browse/LG-12376)
This pr fixes a bug introduced into the 1st pr addressing the update route for the state id controller. We are now also checking that there is an ssn for the user as a means to determine if the user is updating their id information. Previously we did not check the ssn value and so if a user had entered their name on the page but validation failed the page would change to show the appropriate view for someone who is now updating the page. 
=> LG-12376 state id update - check ssn

app/views/idv/mail_only_warning/show.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/i18n_spec.rb, spec/views/idv/mail_only_warning/show.html.erb_spec.rb
I caught a hardcoded `Login.gov` in the translation YMLs which we should have caught with a lint. So this fixes that, and updates the corresponding linter too.
- Updates i18n_spec to correctly iterate over arrays
- Updates i18n_spec to handle new flatter files
=> Remove harcoded "Login.gov" and switch to interpolation

config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/i18n_spec.rb
With a few exceptions, we are rendering content in HTML where whitespace is not significant and won't be displayed. This PR adds a test to alert when we include such whitespace. Cases where we concatenate content like the following is a case where removal of whitespace would cause a change in the display, and will be validated prior to merging.
```ruby
"#{t('content1')}#{t('content2')}"
```
=> Add internationalization test against leading and trailing whitespace

.github/dependabot.yml
Attempts to fix Dependabot configuration issues introduced in #10576:
```
The property '#/updates/0/groups/sync-all-versions' contains additional properties ["allow"] outside of the schema when none are allowed
The property '#/updates/0/groups/sync-all-versions' of type object did not match one or more of the required schemas
The property '#/updates/0/groups/sync-major-versions' contains additional properties ["allow"] outside of the schema when none are allowed
The property '#/updates/0/groups/security' of type object did not match one or more of the required schemas
The property '#/updates/1/groups/sync-all-versions' contains additional properties ["allow"] outside of the schema when none are allowed
The property '#/updates/1/groups/sync-all-versions' of type object did not match one or …
```
=> Use patterns syntax for Dependabot groups

.github/dependabot.yml
Continues to attempt to fix Dependabot configuration issues introduced in https://github.com/18F/identity-idp/pull/10576:
```
The property '#/updates/0/groups/security' of type object did not match one or more of the required schemas
The property '#/updates/1/groups/security' of type object did not match one or more of the required schemas
```
https://github.com/18F/identity-idp/runs/24825325838
Reference documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
>You must use the `patterns`, `exclude-patterns`, `dependency-type`, or `update-types` options to define the group, or any combination thereof.
As before, it's not possible to test prior to merge (see …
=> Fix Dependabot security group schema

config/locales/en.yml
Fixeees an typo with an excess "e" in the word "exceeded".
2. Fail sign-in more than the configured maximum ([5 attempts](https://github.com/18F/identity-idp/blob/236075767aa531add5dfd865773d0d6a6a7667a3/config/application.yml.default#L209) in [60 seconds](https://github.com/18F/identity-idp/blob/236075767aa531add5dfd865773d0d6a6a7667a3/config/application.yml.default#L210))
3. Observe error message does not include a typo
Before|After
---|---
=> Fix typo "exceeded" for maximum sign-in error

app/services/idv/session.rb
[LG-13006](https://cm-jira.usa.gov/browse/LG-13006)
Adding a new property for session.rb for the eventual renaming `skip_doc_auth` to `skip_doc_auth_from_how_to_verify`.
This is the first step in getting the renamed property into session.rb.
=> changelog: internal, in-person-proofing, add new skip_doc_auth name

app/controllers/idv/cancellations_controller.rb, app/javascript/packages/verify-flow/cancel.spec.tsx, app/javascript/packages/verify-flow/context/flow-context.tsx, app/javascript/packs/document-capture.tsx, app/views/idv/shared/_document_capture.html.erb, config/routes.rb
[LG-13007](https://cm-jira.usa.gov/browse/LG-13007)
Covered by unit and feature test.
=> LG-13007: clean up exit survey related.

app/jobs/reports/identity_verification_report.rb, spec/jobs/reports/identity_verification_report_spec.rb
Fix an error in IdentityVerificationReport job where a nil email array returns false when it should return true to not send out the email.
=> fix error in report job where nil email array returns false

app/services/user_event_creator.rb, spec/controllers/users/sessions_controller_spec.rb, spec/services/user_event_creator_spec.rb
[LG-12214](https://cm-jira.usa.gov/browse/LG-12214)
Ensures that the "permanent" device cookie is effectively permanent by re-assigning it on each user event.
Additional background from the ticket:
>When a user signs in to Login.gov, we [set a cookie](https://github.com/18F/identity-idp/blob/32826b1f54581dbc3f9b9e2ea41c99d356f35915/app/services/user_event_creator.rb#L120-L122) to uniquely identify that device so that it is remembered for subsequent sign-ins. As seen in the linked code, the cookie is intended to be permanent, which is [documented as expiring "in 20 years from now"](https://api.rubyonrails.org/v7.0/classes/ActionDispatch/Cookies.html). However, some browsers may impose limits on the duration of cookies. [Chrome sets a maximum cookie expiration to 400 …
=> LG-12214: Refresh device cookie on every user event

app/controllers/idv/document_capture_controller.rb, app/services/idv/session.rb, app/views/idv/document_capture/show.html.erb, app/views/idv/hybrid_mobile/document_capture/show.html.erb, app/views/idv/shared/_document_capture.html.erb, spec/views/idv/shared/_document_capture.html.erb_spec.rb
[LG-13006](https://cm-jira.usa.gov/browse/LG-13006)
Adds the new field name `skip_doc_auth_from_how_to_verify` in preparation for the name switch.
=> Lg 13006 rename skip doc auth, add scaffolding

spec/requests/rack_attack_spec.rb
Removes an unnecessary `allowed_extra_analytics`.
This is being caught by new checks added in #10571, but not failing on `main` in all cases. It fails locally, and [sometimes in other pull requests](https://github.com/18F/identity-idp/pull/10560#discussion_r1599041326).
Further investigation is needed to determine why it only fails in some cases, but this should help unblock any branches impacted by the test failure.
Related Slack discussion: https://gsa-tts.slack.com/archives/C0NGESUN5/p1715632785782359
Verify `rspec spec/requests/rack_attack_spec.rb` passes.
=> Remove unnecessary allowed_extra_analytics

app/helpers/script_helper.rb, app/helpers/stylesheet_helper.rb, app/views/devise/sessions/new.html.erb, app/views/layouts/application.html.erb, app/views/layouts/base.html.erb, app/views/session_timeout/_expire_session.html.erb, spec/helpers/script_helper_spec.rb, spec/helpers/stylesheet_helper_spec.rb, spec/views/devise/sessions/new.html.erb_spec.rb
Updates asset rendering in common layouts and critical paths to optimize loading and deprioritize non-blocking assets.
Specifically:
- Exclude `nopush` from preload headers ([related resource](https://www.keycdn.com/blog/http-preload-vs-http2-push), [related documentation](https://edgeapi.rubyonrails.org/classes/ActionView/Helpers/AssetTagHelper.html#method-i-javascript_include_tag)) (c57441e816763326db9d732b89181dc9266a4159)
- Avoid preload headers for non-critical assets (undocumented, [related code](https://github.com/rails/rails/blob/a6e2bb04ddc845e425ee0e9cdcdfa5a51d98846d/actionview/lib/action_view/helpers/asset_tag_helper.rb#L117)) (12bad512aa517c8e5d3031472201048fb00f02f1)
- Shorten font preload to use path instead of full URL (e22a83b53a25abe035b6bad5be22d8fcf1e4b46a)
These …
=> Optimize preload response headers to prioritize critical assets

app/controllers/users/piv_cac_login_controller.rb, spec/controllers/users/piv_cac_login_controller_spec.rb, spec/support/analytics_helper.rb
[LG-12706](https://cm-jira.usa.gov/browse/LG-12706)
Updates logging of `piv_cac_login` to ensure that a non-`nil` `user_id` is included in the logged result.
1. Run `EVENT_NAME=piv_cac_login make watch_events` in a separate terminal process to the IdP
3. Click "Sign in with your government employee ID"
4. Sign in with PIV
5. Observe log entry "piv_cac_login" has a `user_id` for the user which logged in
=> LG-12706: Include user_id in piv_cac_login event

app/presenters/openid_connect_user_info_presenter.rb, spec/presenters/openid_connect_user_info_presenter_spec.rb
The `OpenidConnectUserInfoPresenter` is responsible for building the user info hash. This is stored in the identity token and exposed at the user info endpoint as part of the OIDC protocol.
The `OpenidConnectUserInfoPresenter` is reponsible for looking at the parameters of the request to determine which attributes to include in the hash. This can include things like the level of service for identity proofing and the requested scopes.
Prior to this commit the `OpenidConnectUserInfoPresenter` was using the `ServiceProviderIdentity#ial` to determine whether identity proofing was performed. This approach does not work when using multiple vectors of trust determine the authentication context. The `#ial` column represents the level of service that was set when the identity was linked when the …
=> Refactor `OpenidConnectUserInfoPresenter` to use `AuthnContextResolver`

app/controllers/idv/link_sent_poll_controller.rb, app/views/idv/link_sent/show.html.erb, config/routes.rb, spec/controllers/idv/link_sent_poll_controller_spec.rb
changelog: Internal, Tech Debt, Renames CaptureDocStatusController to LinkSentPollController
[LG-12086](https://cm-jira.usa.gov/browse/LG-12086)
From the ticket:
> The name is left over from the FlowStateMachine. What it does is poll to see if hybrid flow DocumentCapture is complete. The route has already been renamed to /link_sent/poll
This updates the name to match.
=> LG-12086 | Renames CaptureDocStatusController

lib/reporting/authentication_report.rb, spec/jobs/reports/authentication_report_spec.rb, spec/lib/reporting/authentication_report_spec.rb
[LG-12566](https://cm-jira.usa.gov/browse/LG-12566)
Removes the AAL2 lines from the Authentication Funnel report.
=> Remove AAL2 lines from Authentication Funnel report

app/services/store_sp_metadata_in_session.rb, spec/controllers/openid_connect/authorization_controller_spec.rb, spec/controllers/saml_idp_controller_spec.rb, spec/services/store_sp_metadata_in_session_spec.rb
In #10531 we stopped reading from `sp_session[:biometric_comparison_required]`. In that commit we switched to using the `AuthnContextResolver` result to determine if biometric comparison is required.
This removes the unread value from `sp_session`.
=> Stop writing to `sp_session[:biometric_comparison_required]`

app/controllers/concerns/billable_event_trackable.rb, app/controllers/openid_connect/authorization_controller.rb, app/forms/openid_connect_authorize_form.rb, spec/forms/openid_connect_authorize_form_spec.rb
The `OpenidConnectAuthorizeForm` class is a form object that validates an OpenID Connect authorization request. This includes validating things like whether the scopes and ACR values requested by the service provider are allowed. For example, if an SP that is not allowed to request identity proofing requests scopes that required identity proofing this form responds with an error.
The `IalContext` class provides a number of helper methods helper methods for determining the IAL of a request by consuming either the integer IAL or the ACR values from the request and considering that along with SP defaults to determine a requests IAL. The `IALContext` can optionally consider the user context to make determinations about IAL2 requests. Since this is optional it leads to inconsistent results. …
=> Refactor `OpenidConnectAuthorizeForm` to remove `IalContext`

config/initializers/rack_attack.rb, spec/config/initializers/rack_attack_spec.rb
Does what it says on the tin. This is a late follow up to @aduth's https://github.com/18F/identity-idp/pull/10472#issuecomment-2077147966
=> Use configured locales when building path-based rate limits

config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/i18n_spec.rb
This adds the translation so that we show the Chinese language translation in the language picker.
<details>
</details>
<details>
</details>
=> Update translations for Chinese in language pickers

spec/factories/users.rb
Removes unused (non-functional?) traits in the user model factories for specs:
- `admin`
- `tech_support`
These originate from #2943, though it's unclear that they were ever used.
These changes only affect specs, so it should suffice to verify that the build passes.
=> Remove unused spec user factory traits

app/assets/stylesheets/design-system-waiting-room.scss, app/javascript/packages/validated-field/validated-field-element.spec.ts, app/javascript/packages/validated-field/validated-field-element.ts, app/views/idv/by_mail/enter_code/_form.html.erb
[LG-13259](https://cm-jira.usa.gov/browse/LG-13259)
Input field error message should be the width of the app, not the width of the input field.
<details>
</details>
<details>
</details>
=> LG-13259: Input field error message should be the width of the app

spec/services/identity_linker_spec.rb
The `IdentityLinker` seems to be setting the following attributes on `ServiceProviderIdentities` for reporting purposes:
- `last_ial2_authenticated_at`
- `last_ial1_authenticated_at`
- `verified_at`
These fields seems to be queried for a number of reports and aren't used by any business logic in the IdP.
This behavior is untested without this commit. You could remove this entire method and the test suite would still be green. This commit tests the current behavior. The current behavior does not appear to account for a number of edge cases e.g. users who sign in with IALMax or users who are signing into multiple service providers. This commit addresses none of those edge cases because I do not understand the ramifications of addressing those edge cases for our reporting.
=> Add tests for `IdentityLinker#process_ial` logic

config/locales/zh.yml
Removes a presumed-unintended extra curly brace from locale files.
1. Go to http://localhost:3000/rails/mailers/user_mailer/account_verified.html?locale=zh
2. See "Example App" in body content
3. Observe no "}" character
Before|After
---|---
=> Remove stray curly brace in Chinese verified text

app/views/layouts/application.html.erb, spec/requests/asset_sri_spec.rb
Manually adds subresource integrity hash for a script contained within the design system dependency, with spec coverage to ensure it is kept in sync should the contents of the file change.
Most of our JavaScript is compiled through Webpack, where the subresource integrity hashes are computed as part of the Webpack compilation. This script is loaded directly from the `@18f/identity-design-system` NPM package, and therefore cannot take advantage of this.
To ensure broad coverage of subresource integrity of all JavaScript assets loaded in critical paths, this manually assigns the integrity value. Test coverage ensures that this value is correct, in case a future update of `@18f/identity-design-system` changes the content of the script.
Alternative solutions:
- We could create a new …
=> Add subresource integrity for design system initializer script

webpack.config.js
Updates subresource integrity hashes produced by the Webpack configuration to use SHA256 instead of SHA512.
This is a continuation of improvements around resource hints started in #10612, where Rails' hard cap of 1kb resource hints also includes integrity hashes, which you can see in production today for all preloaded JavaScript (except `init.js`):
```
curl -I https://secure.login.gov | grep link
```
The intent of these changes is to use a hash with a smaller byte size, without meaningfully sacrificing security. By using smaller hashes, the hope is that more assets can fit within the 1kb resource hint limit.
Additional considerations:
- This also reduces the overall size of the markup produced on every page of the application, since integrity hashes are included in each `<script>` tag …
=> Use SHA256 for JavaScript subresource integrity

app/javascript/packages/document-capture/components/document-capture-review-issues.tsx, app/javascript/packages/document-capture/components/document-capture-warning.tsx, app/javascript/packages/document-capture/components/unknown-error.tsx, app/services/doc_auth/error_generator.rb, app/services/doc_auth/errors.rb, app/services/doc_auth_router.rb, app/views/idv/session_errors/warning.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/features/idv/doc_auth/document_capture_spec.rb, spec/features/idv/doc_auth/verify_info_step_spec.rb, spec/fixtures/ial2_test_credential_multiple_doc_auth_failures_back_side_only.yml, spec/fixtures/ial2_test_credential_multiple_doc_auth_failures_both_sides.yml, spec/fixtures/ial2_test_credential_multiple_doc_auth_failures_front_side_only.yml, spec/javascript/packages/document-capture/components/document-capture-warning-spec.jsx, spec/javascript/packages/document-capture/components/review-issues-step-spec.jsx, spec/javascript/packages/document-capture/components/unknown-error-spec.jsx, spec/services/doc_auth/error_generator_spec.rb, spec/services/doc_auth/lexis_nexis/requests/true_id_request_spec.rb, spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb, spec/support/features/doc_auth_helper.rb, spec/views/idv/session_errors/warning.html.erb_spec.rb
[LG-12994](https://cm-jira.usa.gov/browse/LG-12994)
Adding tests and updating code to match the expectations in our [error documentation](https://docs.google.com/document/d/1KM6nUEaVUF3vmdADX_KtuFaYsX_Wgf7Pm3CiuSOk7vs/edit#heading=h.ggzn01m55pyr) for conditions where we have multiple failures:
1. when there are multiple doc auth errors on front and back
2. when there are multiple front doc auth errors
3. when there are multiple back doc auth errors
and IPP is enabled.
This is likely easiest to review in commits:
- [Add and update specs to reflect doc + add ymls](https://github.com/18F/identity-idp/pull/10635/commits/c03dbdac9e6a15788c1825fe306390ca688823e5)
- [Restore previous default error message](https://github.com/18F/identity-idp/pull/10635/commits/918db1495efbcde7838e5ed2a698f570d383 …
=> LG-12994: fix messages when there are multiple doc auth errors

app/controllers/concerns/idv/verify_info_concern.rb, app/jobs/address_proofing_job.rb, app/services/db/add_document_verification_and_selfie_costs.rb, app/services/db/sp_cost/add_sp_cost.rb, app/services/gpo_confirmation_maker.rb
These arguments are confusing for the following reasons:
1. We never actually pass in a user. We use the user to initialize an `IalContext` (see below)
2. We use the IAL to initialize an `IalContext`. We use this to call `bill_for_ial_1_or_2` which is intended to consider billing impacts of IALMax if the user is proofed. We always pass a nil user (see above) and we always pass an `ial` argument of 2 so this code always returns `2`.
We can shortcut all of this by hardcoding `2` for the `ial` attribute.
=> Remove `user` and `ial` arguments from `AddSpCost` service

app/controllers/openid_connect/authorization_controller.rb, app/forms/openid_connect_authorize_form.rb, spec/forms/openid_connect_authorize_form_spec.rb
Both the `OpenidConnect::AuthorizationController` and `SamlIdpController` have logic that ultimately invokes the `IdentityLinker` to link a user to a service provider. This code consumes an `ial` value which is used to set values on the `ServiceProviderIdentity` record that are eventually used for analytics and reporting purposes.
In the `SamlIdpController` the `ial` value is computed using `resolved_authn_contenxt_result`. This means that it considers the SP defaults and the content of the SP request. Eventually this will also include the user context when multiple vectors of trust support is added.
Prior to this commit the `OpenidConnect::AuthorizationController` did not use the `resolved_authn_contenxt_result` and instead computed the value itself in its form object. Its computation …
=> Modify `OpenidConnect::AuthorizationController#link_identity_to_service_provider` to match pattern in `SamlIdpController`

app/forms/idv/doc_pii_form.rb, spec/controllers/idv/image_uploads_controller_spec.rb, spec/features/idv/analytics_spec.rb, spec/forms/idv/doc_pii_form_spec.rb
[LG-13214](https://cm-jira.usa.gov/browse/LG-13214)
Adds two keys to the `IdV: doc auth image upload vendor pii validation` event: `:id_issued_status` and `id_expiration_status`. Possible values are 'missing' or 'present'.
=> LG-13214: Log presence of issue date and exp date

app/assets/stylesheets/components/_step-indicator.scss, app/javascript/packages/step-indicator/step-indicator-step.spec.tsx
Removes unused `step-indicator__step-subtitle` styles.
**Why?**
- Unused code creates technical debt
- Reduce size of stylesheets
- Limit divergence with underlying U.S. Web Design System components
- Eliminate an instance of italics text
- For context, this was discovered while auditing current use of italic text, since [italic text is not intended to be supported for Chinese content](https://en.wikipedia.org/wiki/Chinese_punctuation#:~:text=For%20emphasis%2C%20Chinese%20uses%20emphasis,hand%20side%20of%20each%20character).).
Added in #6817, last reference removed in #7623.
Verify no regressions in the appearance of Step Indicator in the identity verification flow.
=> Remove unused Step Indicator component styles

config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/i18n_spec.rb
[LG-13200](https://cm-jira.usa.gov/browse/LG-13200)
=> LG-13200: DOS translations

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_index.scss, app/views/shared/_banner.html.erb
Refactors the banner to use the "centered" variant introduced to the design system in [`@18f/identity-design-system@9.1.0`](https://github.com/18F/identity-design-system/releases/tag/v9.1.0), to avoid redundant, ad-hoc styles.
2. Verify no regressions in appearance of USA banner
There are not expected to be any visual differences:
=> Use design system centered variant for banner

spec/jobs/get_usps_proofing_results_job_spec.rb
[LG-13367 ](https://cm-jira.usa.gov/browse/LG-13367 )
Added a top level mock config value so the spec doesn't break on launch. This spec could maybe use a refactor once the config value (in_person_enrollments_ready_job_enabled) is toggled to true. 
Make sure the specs are all green.
=> Prevent USPS Proofing Results Job from failing when in_person_enrollments_ready_job_enabled is true

app/assets/stylesheets/_uswds-core.scss
Configures the design system to avoid outputting `@font-face` declarations for unused light weight font copy.
We only use normal and bold face text in the application, so this declaration is wasted bytes. This also controls the output of a few utility helpers related to light text.
```diff
23a24,31
>   font-weight: 300;
>   font-display: fallback;
>   src: url("/roboto-mono/roboto-mono-v5-latin-300.woff2") format("woff2");
> }
> 
> @font-face {
>   font-family: Roboto Mono Web;
>   font-style: normal;
39a48,55
>   font-weight: 300;
>   font-display: fallback;
>   src: url("/roboto-mono/roboto-mono-v5-latin-300italic.woff2") format("woff2");
> }
> 
> @font-face {
>   font-family: Roboto Mono Web;
>   font-style: italic;
55a72,79
>   font-weight: 300;
>   font-display: fallback;
>   src: …
```
=> Avoid outputting font-face for unused light font weight

app/controllers/two_factor_authentication/backup_code_verification_controller.rb, app/controllers/two_factor_authentication/otp_verification_controller.rb, app/controllers/two_factor_authentication/personal_key_verification_controller.rb, app/controllers/two_factor_authentication/piv_cac_verification_controller.rb, app/controllers/two_factor_authentication/totp_verification_controller.rb, app/controllers/two_factor_authentication/webauthn_verification_controller.rb, spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb, spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb, spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb, spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb, spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb, spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
Updates references to `user_session[:new_device]` with `NewDeviceConcern#new_device?`.
This is a refactoring following #10628 to consistently use the concern abstractions in place of direct references to the session.
One difference is that `new_device?` will default to `true` on an absent session value. In the real-world, this should never realistically happen when verifying 2FA after sign-in.
Repeat Testing Plan from #9784
=> Use NewDeviceConcern consistently for session value

.gitlab-ci.yml
Previously all reviewapps were being put mistakenly in the same `reviewapps`
cloudwatch log group.
This change fixes it so they're put in cloudwatch log groups named after the
reviewapp.
In cloudwatch you can search for your branch to find the log groups for your
reviewapp again.
-------
=> Fix logging envs all being put in the same log group

app/controllers/application_controller.rb, app/controllers/openid_connect/authorization_controller.rb, app/forms/openid_connect_authorize_form.rb, app/models/anonymous_user.rb, app/presenters/openid_connect_user_info_presenter.rb, app/services/analytics.rb, app/services/attribute_asserter.rb, app/services/authn_context_resolver.rb, app/services/id_token_builder.rb, spec/controllers/concerns/remember_device_concern_spec.rb, spec/factories/users.rb, spec/features/sign_in/multiple_vot_spec.rb, spec/forms/openid_connect_authorize_form_spec.rb, spec/policies/pending_profile_policy_spec.rb, spec/services/authn_context_resolver_spec.rb
The `AuthnContextResolver#resolve` takes the ACR values and VTR param for a request and returns an `Vot::Parser::Result` object. This object has predicate methods such as `aal2?` and `#identity_proofing?` which describe the requirements for the given service provider request. This is necessary because these requirements are a function of the service provider settings that are stored in the database and the request from the service provider.
When using vectors of trust a service provider is able to make a request with multiple valid vectors. Prior to this commit we used the first vector in the list for the service provider request. This commit makes a change to show the following preference:
1. If a SP requests biometric comparison and the user has completed proofing with biometric …
=> LG-13038 Add user context to the `​​AuthnContextResolver`

app/controllers/idv/document_capture_controller.rb, app/controllers/idv/how_to_verify_controller.rb, app/controllers/idv/hybrid_handoff_controller.rb, app/views/idv/document_capture/show.html.erb, app/views/idv/shared/_document_capture.html.erb, spec/controllers/idv/how_to_verify_controller_spec.rb, spec/controllers/idv/hybrid_handoff_controller_spec.rb, spec/support/flow_policy_helper.rb, spec/views/idv/shared/_document_capture.html.erb_spec.rb
[LG-13006](https://cm-jira.usa.gov/browse/LG-13006)
Added `skip_doc_auth_from_how_to_verify` alongside `skip_doc_auth` for eventual removal of `skip_doc_auth`.
=> lg-13006 rename skip_doc_auth

app/javascript/packages/document-capture/components/acuant-capture.tsx, app/javascript/packages/document-capture/components/acuant-selfie-capture-canvas.jsx, spec/javascript/packages/document-capture/components/acuant-selfie-capture-canvas-spec.jsx
https://cm-jira.usa.gov/browse/LG-13363
Fix a problem where when using a screenreader focus would jump away from the capture button in selfie capture. Slack thread [here](https://gsa-tts.slack.com/archives/C056RD1NEHW/p1716225740192659).
=> LG-13363: Fix Screenreader Focus Jumping During Selfie Capture

Gemfile, Gemfile.lock, app/controllers/concerns/saml_idp_auth_concern.rb, app/controllers/saml_idp_controller.rb, app/models/federated_protocols/saml.rb, app/services/analytics_events.rb, app/services/attribute_asserter.rb, app/services/saml_request_validator.rb, spec/features/sign_in/multiple_vot_spec.rb, spec/services/saml_request_validator_spec.rb, spec/support/fake_saml_request.rb
We added support for sending multiple vectors of trust using the OIDC interface in #10517. This commit adds the same feature to the SAML interace.
To send multiple vectors using SAML partners can include multiple AuthnContextNodes with a vector in each. This was enabled in https://github.com/18F/saml_idp/pull/100.
=> LG-13313 Add multiple vector of trust support for SAML

app/services/proofing/aamva/request/templates/verify.xml.erb, app/services/proofing/aamva/request/verification_request.rb, spec/fixtures/proofing/aamva/requests/verification_request.xml, spec/lib/aamva_test_spec.rb, spec/services/proofing/aamva/request/verification_request_spec.rb, spec/services/proofing/aamva/verification_client_spec.rb
[LG-13216](https://cm-jira.usa.gov/browse/LG-13216)
#10653 added two new fields to our requests to AAMVA's DLDV service: issue date and expiration date. In manual testing in our staging environment, I discovered that these fields weren't being processed by AAMVA because I used the incorrect namespace in the SOAP XML we were sending. I found it was difficult to keep track of what namespaces our code was referring to because we were labeling them differently from the [AAMVA DLDV documentation](https://drive.google.com/file/d/1TsYeL0xpqfqcL9V3lw5BF-WOy21CytZ3/view?usp=sharing).
This PR:
1. Updates the namespace abbreviations used in DLDV verification requests to match those used in the AAMVA documentation
2. Fixes the issue date + expiration date fields to use …
=> LG-13216: Gaze into the AAMVA SOAP abyss.

app/forms/backup_code_verification_form.rb, app/models/backup_code_configuration.rb, app/services/backup_code_generator.rb
This PR borrows a bit of the logic from #8118 to improve the performance and reliability of verifying backup codes by wrapping the verification and usage update in a transaction. It was prompted by work in #10686.
=> Verify and consume backup code in single database transaction

app/services/reporting/total_user_count_report.rb, lib/reporting/proofing_rate_report.rb, spec/lib/reporting/proofing_rate_report_spec.rb, spec/services/reporting/total_user_count_report_spec.rb
changelog: Internal, Reporting,key metrics user counts
[LG-13193](https://cm-jira.usa.gov/browse/LG-13193)
For the proofing rate report included the last day end date in the query for 30,60 and 90 days trailing and verified user counts in Total user counts(updated to verified_at from activated_at
=> LG-13193 key metrics user count updates

app/services/saml_request_validator.rb
When I was working on the code to parse a VTR in the SAML request validator I copied the code from the OIDC form object. This included a check that the `vtr` is an array. In OIDC that is necessarily because we are directly parsing the result of calling `JSON.parse` on the param. In SAML that is not the case; the vtr is parsed out of the authn request and will be an array or nil. For this reason we can use `#blank?` in the SAML implementation.
=> Remove `#is_a?` call from VTR in SAML request validator

app/controllers/users/backup_code_setup_controller.rb, app/views/users/backup_code_setup/edit.html.erb, config/application.yml.default, lib/identity_config.rb, spec/controllers/users/backup_code_setup_controller_spec.rb, spec/features/account/backup_codes_spec.rb, spec/views/users/backup_code_setup/edit.html.erb_spec.rb
Clean-up for [LG-13402](https://cm-jira.usa.gov/browse/LG-13402)
Removes the temporary feature flag added in #10685 which was included to facilitate the 50/50 deploy state. Now that the feature is fully deployed, the feature flag is no longer necessary.
Repeat Testing Plan from #10685
=> LG-13402: Remove temporary feature flag for backup code confirmation

app/controllers/two_factor_authentication/backup_code_verification_controller.rb, app/controllers/two_factor_authentication/otp_verification_controller.rb, app/controllers/two_factor_authentication/personal_key_verification_controller.rb, app/controllers/two_factor_authentication/piv_cac_verification_controller.rb, app/controllers/two_factor_authentication/totp_verification_controller.rb, app/controllers/two_factor_authentication/webauthn_verification_controller.rb, app/services/analytics.rb, app/services/analytics_events.rb, spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb, spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb, spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb, spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb, spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb, spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb, spec/support/fake_analytics.rb
Removes `Analytics#track_mfa_submit`, updating call-sites to call `AnalyticsEvents#multi_factor_auth` directly.
**Why?**
- It's only purpose was to provide `pii_like_keypaths` for specific personal key verification properties, which is reasonable to expect to be passed in the one place it's necessary (`PersonalKeyVerificationController`)
- The method is the only one of its kind, and it causes confusion to what's actually being logged, since the method name does not correspond directly to an `AnalyticsEvents` module method or actual event name
- It is incompatible with `have_logged_event`, which is the preferred way to ensure that events are logged as expected, contains no PII, and all properties are documented
- See included revision to document `error_details` now that it is correctly …
=> Remove track_mfa_submit analytics pass-through method

app/controllers/users/two_factor_authentication_controller.rb, spec/controllers/users/two_factor_authentication_controller_spec.rb
In #10480 we added an A/B test that made voice OTPs 10-digits for IdV phone confirmation for some percentage of users. This was to test whether a 10-digit numeric code sees more success than a 6-digit alphanumeric code.
This included a change to the message for the voice OTP since the message includes the length, e.g. "Your 10-digit Login.gov one time code is 1234567890". The translation for the 10-digit code was erroneously applied to 6-digit codes when auth users chose voice calls to confirm phones during sign up. This commit fixes that issue.
=> LG-13424 Fix phone confirmation OTP length message during sign up in auth

app/controllers/concerns/saml_idp_auth_concern.rb, app/services/saml_request_validator.rb, lib/saml_idp_constants.rb, spec/controllers/saml_idp_controller_spec.rb
https://gitlab.login.gov/lg-people/lg-people-appdev/protocols/saml/-/issues/2
-->
- Refactored tests to remove duplication and make contexts explicit
- Fail on unsupported NameID formats unless service provider is configured with `use_legacy_name_id_behavior`.
- Use `persistent` as default NameID format when the requested NameID format is "unspecified" or there is no requested NameID format. In particular, don't send back email even if the service provider is configured for using email, unless email is explicitly requested.
=> Ensure proper behavior for default and invalid NameID format requests

app/models/user.rb, spec/models/user_spec.rb
Removes `User#new_device?`, as it is currently unused.
Recent work in #10628 has shifted how we consider new device for sign-in notifications to using the `User#authenticated_device?` method, leaving this unused.
Future work could consider renaming either `NewDeviceConcern#new_device?` or `User#authenticated_device?` to use consistent naming.
Verify there is no usage of `User#new_device?` anywhere in code, and that the build passes.
=> Remove unused User#new_device? method

app/services/vot/component_expander.rb, app/services/vot/parser.rb, app/services/vot/supported_component_values.rb, spec/services/vot/component_expander_spec.rb
The `Vot::Parser` class consumes a VoT or ACR values string and parses it into a set of requirements to satisfy the vector.
Some vectors have dependencies on other vectors. For example, the biometric proofing vector (`Pb`) depends on the identity proofing vector (`P1`). In the [vector component value definitions](https://github.com/18F/identity-idp/blob/5442bbdb9af5421dcb4fabc7a8ec4ce9ab307526/app/services/vot/supported_component_values.rb#L4) these are described as “implied components” i.e. vector Pb implies vector P1.
When a partner requests a vector with a component that implies another component we expand the vector to include the implied component. For example, a partner may request `C1.Pb` which we will expand to `C1.C2.P1.Pb` since `Pb` implies `P1` and `P1` implies `C2`.
Prior to …
=> Remove infinite recursion in `Vot::Parser`

app/components/countdown_alert_component.rb, app/javascript/packages/countdown/countdown-alert-element.spec.ts, app/javascript/packages/countdown/countdown-alert-element.ts
Removes code related to a redirect option for `CountdownAlertComponent` which was meant to have been removed with #8701.
This code is unused, but verify there are no regressions in the countdown alert component preview:
http://localhost:3000/components/inspect/countdown_alert/preview
=> Remove unused redirect URL code for CountdownAlertComponent

app/services/marketing_site.rb, app/views/idv/how_to_verify/show.html.erb, app/views/idv/welcome/show.html.erb, spec/features/idv/doc_auth/welcome_spec.rb, spec/views/idv/welcome/show.html.erb_spec.rb
Prior to this commit the welcome screen at the beginning of IdV links to a page explaining how to verify your identity. The overview page on the static site is the more appropriate page for people trying to learn more about identity verification. This commit updates the URL to link to the correct place.
=> LG-13434 Link to overview article from IdV welcome

app/presenters/openid_connect_user_info_presenter.rb, config/application.yml.default, lib/identity_config.rb, spec/presenters/openid_connect_user_info_presenter_spec.rb
https://gitlab.login.gov/lg-people/lg-people-appdev/protocols/backlog-fy24/-/issues/16
This change is removing vestigial code left over from fixing the [x509:presented attribute bug](https://cm-jira.usa.gov/browse/LG-12678). The changes include:
- removing the backwards compatibility conditional
- removing the configuration key from the IdentityConfig and application.yml.default
- removing the now unnecessary test
=> Remove all code related to the x509_presented_hash_attribute_requested_issuers

.rubocop.yml, app/services/encryption/user_access_key.rb, app/services/proofing/aamva/hmac_secret.rb, app/services/x509/attribute.rb, config/initializers/rack_timeout.rb, lib/aws/ses.rb, spec/controllers/concerns/remember_device_concern_spec.rb, spec/support/features/idv_step_helper.rb
I was a little surprised to see `alias` instead of `alias_method` in our codebase. `alias_method` has more predictable behavior compared to `alias`. This updates our rules and corrects the codebase
Related: https://github.com/rubocop/ruby-style-guide/issues/821 and the [explainer blog post](https://www.bigbinary.com/blog/alias-vs-alias-method) that it links
=> Update RuboCop rules: prefer alias_method

app/controllers/frontend_log_controller.rb, app/services/analytics_events.rb, app/services/idv/analytics_events_enhancer.rb
Removes unused analytics methods.
- `proofing_document_result_missing`: Last reference removed in #8292
- `irs_attempts_api_events`: Last reference removed in #8660
- `idv_phone_otp_delivery_selection_visit`: Last reference removed in #7590
- `idv_phone_otp_delivery_selection_submitted`: Last reference removed in #7590
- `idv_mobile_device_and_camera_check` (`"IdV: Mobile device and camera check"`): Last reference removed in #8267
The process for identifying these essentially amounted to a grep of analytics methods call patterns in code, combined with a listing of methods in `app/services/analytics_events.rb`, and then a manual review of the remaining diff.
- `ag -s --nofilename --nobreak "analytics\." app`
- `File.write('methods.txt', AnalyticsEvents.instance_methods(true).join("\n"))` …
=> Remove unused analytics methods

app/controllers/openid_connect/logout_controller.rb, app/forms/openid_connect_logout_form.rb, app/services/analytics_events.rb, app/views/openid_connect/logout/confirm_logout.html.erb, config/routes.rb, spec/controllers/openid_connect/logout_controller_spec.rb
[LG-7434](https://cm-jira.usa.gov/browse/LG-7434): Add support for POST OIDC logout requests (this ticket has been superseded by [this GitLab issue](https://gitlab.login.gov/lg-people/lg-people-appdev/protocols/backlog-fy24/-/issues/20)).
- Updated the controller to use separate methods for `GET` and `POST`
- The `POST` route redirects to the `GET` route for better UX when using browser navigation
- Added analytics field `original_method` to capture redirected method for `OIDC Logout Requested` event. See https://github.com/18F/identity-idp/pull/10697#discussion_r1617923237 for details
- Updated tests
- Updated doc comments
Requires:
- A modified sample OIDC app to sign-out users with POST
- `identity-idp` app to have `reject_id_token_hint_in_logout: true` in …
=> LG-7434: Allow cross origin for POST OIDC Logout

app/services/idv/agent.rb, spec/services/idv/agent_spec.rb
In #10722 we added an argument for passing the service provider issuer to the `ResolutionProofingJob` eventually this will be used for things like computing SP costs, creating `DocAuthLog` records, and determining the UUID prefix in the job.
This commit starts passing the issuer to the job but does not start using it. In order to ensure that results are consistent a future commit will start reading the issue once all of the web hosts are passing it to the job.
This can only be safely merged once #10722 is fully deployed.
=> LG-13383 Pass SP issuer to the ResolutionProofingJob

app/models/account_reset_request.rb, db/primary_migrate/20240531175935_drop_reported_fraud_at_from_account_reset_requests.rb, db/schema.rb
Drops the `reported_fraud_at` column from the `account_reset_requests` database table.
This was last used and marked ignored in #2528, but the field was never dropped from the database.
Verify that migration applies cleanly (`rails db:migrate`) and the application runs without errors.
=> Remove unused reported_fraud_at column from account_reset_requests

app/services/analytics_events.rb, spec/controllers/account_reset/request_controller_spec.rb, spec/controllers/sign_up/completions_controller_spec.rb, spec/features/ialmax/saml_sign_in_spec.rb, spec/features/remember_device/cookie_expiration_spec.rb, spec/features/remember_device/revocation_spec.rb, spec/features/remember_device/session_expiration_spec.rb, spec/features/reports/sp_active_users_report_spec.rb, spec/features/saml/multiple_endpoints_spec.rb, spec/features/saml/saml_logout_spec.rb, spec/features/saml/saml_relay_state_spec.rb, spec/features/saml/saml_spec.rb, spec/features/sign_in/banned_users_spec.rb, spec/features/sign_in/remember_device_default_spec.rb, spec/features/sign_in/sp_return_log_spec.rb, spec/features/two_factor_authentication/backup_code_sign_up_spec.rb, spec/features/two_factor_authentication/second_mfa_reminder_spec.rb, spec/features/visitors/bad_password_spec.rb, spec/requests/openid_connect_authorize_spec.rb
Adds missing documentation for analytics methods called in an end-to-end partner authentication for a fully-registered user authenticating with phone.
This builds upon #10571, identifying a common flow as low-hanging fruit for fixing the largest possible number of specs which only need `allowed_extra_analytics` due to exercising a critical user flow.
=> Document analytics methods in end-to-end sign-in flow

app/controllers/concerns/new_device_concern.rb, app/controllers/concerns/two_factor_authenticatable_methods.rb, app/controllers/users/piv_cac_login_controller.rb, app/controllers/users/sessions_controller.rb, spec/controllers/concerns/new_device_concern_spec.rb, spec/controllers/users/piv_cac_login_controller_spec.rb, spec/controllers/users/sessions_controller_spec.rb, spec/features/new_device_tracking_spec.rb
[LG-13419](https://cm-jira.usa.gov/browse/LG-13419)
Fixes an issue where a user may receive a second notification about a new-device authentication when reauthenticating from a device that was considered new at the start of their session.
The change here will update the session value for tracking a new device after the user fully authenticates.
This feature is not currently enabled in production.
1. In a new private browsing session, go to http://localhost:3000
2. Sign in and complete MFA
3. Once you arrive at the account dashboard, wait at least 2 minutes (this would be 20 minutes in production)
4. Click "Add phone number" to add a phone
5. You should see "Reauthentication required"
6. Complete reauthentication
7. Observe that you don't receive an email (in local development, an email …
=> LG-13419: Fix new device notification on reauthentication

app/controllers/sign_up/completions_controller.rb, app/services/analytics_events.rb, spec/controllers/sign_up/completions_controller_spec.rb
Removes `sp_request_requested_attributes` from `'User registration: complete'` and `'User registration: agency handoff visited'` analytics events.
These values are never assigned (see https://github.com/18F/identity-idp/pull/10736#discussion_r1622830805), and are prone to confusion with the `sp_session_requested_attributes` analytics property.
Previous discussion: https://github.com/18F/identity-idp/pull/10736#discussion_r1622793203
Verify that this property is never logged in production analytics.
=> Remove sp_request_requested_attributes from completion events

app/controllers/concerns/idv/verify_info_concern.rb, app/services/idv/steps/threat_metrix_step_helper.rb
This supports [LG-13382](https://cm-jira.usa.gov/browse/LG-13382)
This is a minor refactor, clearing the way to move some proofing cost calculation code out of the way in a future PR.
I'm taking `log_irs_threatmetrix_fraud_check_event` out of `ThreatMetrixStepHelper` and splitting it into two methods in `VerifyInfoConcern`, then moving the calls to those methods out of `add_proofing_costs`. The idea is that I want the `add_proofing_costs` method to ultimately only be concerned with adding proofing costs so that it's easier to move.
=> Move log_irs_threatmetrix_fraud_check_event to VerifyInfoConcern

app/controllers/concerns/idv/verify_info_concern.rb, app/models/doc_auth_log.rb, app/services/idv/steps/threat_metrix_step_helper.rb, spec/features/idv/doc_auth/verify_info_step_spec.rb, spec/features/idv/end_to_end_idv_spec.rb
Supporting [LG-13382](https://cm-jira.usa.gov/browse/LG-13382)
The `track_aamva` method in `VerifyInfoConcern` only does anything if the `state_tracking_enabled` feature flag is `true`. This flag has never been true in prod, so this is a no-op. 
I created [LG-13461](https://cm-jira.usa.gov/browse/LG-13461) to track completely removing the flag, but this specific method is in my way as I work on [LG-13382](https://cm-jira.usa.gov/browse/LG-13382).
=> Remove unused AAMVA DocAuthLog tracking

app/controllers/concerns/idv/verify_info_concern.rb, spec/controllers/idv/verify_info_controller_spec.rb
[LG-13382](https://cm-jira.usa.gov/browse/LG-13382)
We'd like to move SP cost tracking out of VerifyInfoConcern and into the background job. To handle the 50/50 state, we need to make sure that VIC is not doing SP cost tracking if the worker already did.
A future PR will add SP cost tracking to the worker and will ensure that `sp_costs_added` is set on the resolution result.
=> LG-13382: Don't add SP costs again if worker already did it

spec/features/accessibility/user_pages_spec.rb
Removes an unnecessary `alowed_extra_analytics` from `spec/features/accessibility/user_pages_spec.rb`.
This can occasionally cause builds to fail in unrelated pull requests, see https://github.com/18F/identity-idp/pull/10740#issuecomment-2145141042.
I'm still not totally positive what's causing this. My leading theory is what was mentioned in #10730 about parallelizing across runners, where the checks running `after(:all)` may not accurately assess if a spec file is split across runners. Without an obvious solution, I'm inclined to push forward to work toward continuing to eliminate all (most) `allowed_extra_analytics`. These false negatives are a mild inconvenience with a one-time fix in each instance.
Verify that build passes.
=> Remove unnecessary allowed_extra_analytics in accessibility specs

lib/saml_idp_constants.rb, spec/controllers/saml_idp_controller_spec.rb
**Why**:
1. The tests are hard to understand and do not clearly show the different contexts
2. The tests assert on a side effect (the analytics event posted) rather than the actual desired behavior (the return values)
3. The tests are actually misleading - they conflate "unspecified" and unsupported
**How**:
- Refactor tests with clear contexts and shared examples
- Assert on actual return value and not on a side effect
- Clean up test case descriptions
changelog: Internal, Automated Testing, Refactor NameID format related tests
=> Refactor NameID format related tests

app/jobs/resolution_proofing_job.rb, spec/jobs/resolution_proofing_job_spec.rb, spec/services/idv/agent_spec.rb
In #10726 started passing the service provider issuer to the `ResolutionProofingJob`. This commit uses it to compute the UUID and UUID prefix for downstream proofers. This will eventually supersede the logic that does the same in the `VerifyInfoConcern`.
The logic is left in the `VerifyInfoConcern` since we will still need to pass the UUID and UUID prefix to jobs until this is fully deployed. Once this is fully deployed that logic can be removed.
This cannot be safely merged until all of the jobs are receiving the service provider issuer. That change is made in #10726
=> LG-13383 Use the SP issuer to compute the UUID and UUID prefix in the `ResolutionProofingJob`

app/controllers/saml_idp_controller.rb, app/services/analytics_events.rb, spec/controllers/saml_idp_controller_spec.rb
changelog: User-Facing Improvements, Analytics, Log the requested NameID format
https://gitlab.login.gov/lg-people/lg-people-appdev/Melba/backlog-fy24/-/issues/33
Write the NameID format _requested_ in the SAML Request _in addition to_ the NameID format responded with.
=> Log the requested NameID format

app/jobs/resolution_proofing_job.rb, app/services/proofing/resolution/progressive_proofer.rb, lib/aamva_test.rb, spec/services/proofing/resolution/progressive_proofer_spec.rb
The `ProgressiveProofer` class has a `#proof` method which does the bulk of the footwork when it comes to orchestrating proofing API calls on the Verify-Your-Info step. This includes things like double address verification, get-to-yes, and skipping necessary API calls for users who cannot pass.
Prior to this commit this class did not store any instance variables. This meant that the child methods in the job needed all of the context necessary to do their work passed in as arguments. This led to long lists of keyword arguments for these methods which distracted from the methods' purpose.
This commit refactors the `ProgressiveProofer` to take the arguments that were passed to `#proof` in an initializer and store them as ivars. It also makes a change to store the vendor results as ivars. …
=> Use ivars to clean up `ProgressiveProofer` methods

docs/frontend.md
Updates frontend documentation to clarify language around resolving optimized fonts lint failures.
The instructions included the necessary steps to produce changes to `glyphs.txt`, but it was not clear that changes needed to be committed, and particularly changes to both the font files themselves as well as `glyphs.txt`. These changes seek to clarify this.
Related: https://github.com/18F/identity-idp/pull/10755#issuecomment-2155106672
Read [the updated "Fonts" documentation](https://github.com/18F/identity-idp/blob/aduth-clarify-frontend-fonts/docs/frontend.md#fonts) and verify that it makes sense.
=> Clarify instructions for committing optimized fonts and glyphs.txt

app/components/base_component.rb
Updates `BaseComponent` to use `Random.hex` instead of `SecureRandom.hex`.
These IDs are not security-sensitive, and merely need to be reasonably unique within instances of the component of a single request, to satisfy HTML validation of unique IDs across elements ([ref](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id)).
Benchmark:
```rb
require 'benchmark/ips'
require 'securerandom'
Benchmark.ips do |x|
x.report('SecureRandom.hex') do
SecureRandom.hex(4)
end
x.report('Random.hex') do
Random.hex(4)
end
x.compare!
end
```
Results:
```
Warming up --------------------------------------
SecureRandom.hex   317.139k i/100ms
Random.hex   506.735k i/100ms
Calculating -------------------------------------
SecureRandom.hex      3.170M (± 0.4%) i/s -     15.857M in   5.002178s …
```
=> Use Random.hex for base component unique ID

app/services/analytics_events.rb, spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb, spec/controllers/users/totp_setup_controller_spec.rb, spec/controllers/users/webauthn_setup_controller_spec.rb, spec/features/account_creation/multiple_browsers_spec.rb, spec/features/account_creation/sp_return_log_spec.rb, spec/features/new_device_tracking_spec.rb, spec/features/openid_connect/authorization_confirmation_spec.rb, spec/features/phone/add_phone_spec.rb, spec/features/phone/confirmation_spec.rb, spec/features/phone/default_phone_selection_spec.rb, spec/features/phone/rate_limiting_spec.rb, spec/features/remember_device/phone_spec.rb, spec/features/remember_device/signed_in_sp_expiration_spec.rb, spec/features/remember_device/sp_expiration_spec.rb, spec/features/remember_device/totp_spec.rb, spec/features/saml/authorization_confirmation_spec.rb, spec/features/saml/ial1_sso_spec.rb, spec/features/two_factor_authentication/change_factor_spec.rb, spec/features/users/sign_up_spec.rb, spec/features/users/totp_management_spec.rb, spec/features/visitors/email_confirmation_spec.rb, spec/features/visitors/sign_up_with_email_spec.rb
This documents a few more analytics methods, intended to address low-hanging fruit of common analytics logged during account creation:
- `multi_factor_auth_setup`
- `multi_factor_auth_added_phone`
- `multi_factor_auth_added_totp`
This is similar in purpose to #10736, where #10736 addressed common analytics during sign-in.
**Why?**
- Improve discoverability of the availability of these properties
- Highlight potential redundancies or inconsistencies in logged analytics
Verify build passes. This should not have any impact on user-facing behavior.
=> Document critical-path MFA setup analytics methods

config/locales/zh.yml, spec/i18n_spec.rb
This PR adds a test that any paired punctuation like parentheses and brackets have an equal number.
=> Add test that ensures punctuation pairs match correctly 

Gemfile.lock
Updating fixes the following warning when running tests:
> warning: ruby/3.3.0/observer.rb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add observer to your Gemfile or gemspec. Also contact author of factory_bot-6.2.1 to add observer into its gemspec.
=> Update factory_bot to fix deprecation warning

Gemfile, Gemfile.lock, app/controllers/concerns/saml_idp_auth_concern.rb, app/controllers/saml_idp_controller.rb, app/services/analytics_events.rb, spec/controllers/saml_idp_controller_spec.rb
[Add SAML request validation matching certificate logging](https://gitlab.login.gov/lg-people/lg-people-appdev/Melba/backlog-fy24/-/issues/36)
Adds logging so that we can determine which partners, if any, may experience breaking changes when we deploy the code that accurately finds the DigestMethod for SAML request assertions that are not using the `ds` namespace. 
This change:
- Adds a field to the Saml Auth event if the request is successful and signed. This field indicates whether the certificate that is being used to encrypt the response is the same certificate that is being found via the code that fixes a bug where the DigestMethod will be found.
- Updates and adds tests
- Updates the saml_idp version
=> log whether "matching cert" is consistent with the bug fix

spec/i18n_spec.rb
Addresses the comment here https://github.com/18F/identity-idp/pull/10758#discussion_r1626275135 where we were not failing as expected when we have unused exceptions to mismatched interpolation arguments. I'm not super happy with the logic at this point, but it does seem to work correctly.
The initial run in https://github.com/18F/identity-idp/pull/10783/commits/cc0fb0207421c1d26a9aba8fb85111c7ceb56502 is expected to fail.
=> Fix internationalization test to fail when there are unused allowed interpolation mismatches

app/jobs/reports/identity_verification_report.rb, spec/jobs/reports/identity_verification_report_spec.rb
=> Fix exception in IdentityVerificationReport when email configuration is blank

db/primary_migrate/20240604173515_add_sponsor_id_to_in_person_enrollment.rb, db/schema.rb
[LG-13233](https://cm-jira.usa.gov/browse/LG-13233)
As a part of the Enhanced IPP effort, we'll need a way to check whether an enrollment was created during the Enhanced IPP flow during the background jobs. Adding the `sponsor_id` to the enrollment model will allow us to derive whether the flow - sponsor_id == usps_ipp_sponsor_id means Enhanced IPP
=> LG-13233: add sponsor_id to in_person_enrollments model

app/controllers/saml_idp_controller.rb, spec/controllers/saml_idp_controller_spec.rb
https://gitlab.login.gov/lg-people/lg-people-appdev/Melba/backlog-fy24/-/issues/36
The `encryption_cert_matches_matching_cert?` method did not consider conditions where `matching_cert` might evaluate to `nil`, and therefore be comparing `nil` to the encryption_certificate, which will always be not `nil`. This change updates the code to ensure both matching_cert falls back on the first registered cert value if `nil`
=> Fix small bug in matching cert tracking metrics

config/locales/zh.yml, spec/i18n_spec.rb
This adds a few translations that were translated but were missed in manual and automatic updates.
=> Update missing Chinese translations

app/services/proofing/resolution/progressive_proofer.rb, spec/services/proofing/resolution/progressive_proofer_spec.rb
I was looking at the changes in #10786 for the move of SP cost tracking from the `VerifyInfoConcern` to the `ProgressiveProofer` when I noticed this condition that was not accounted for:
https://github.com/18F/identity-idp/pull/10786/files#diff-5d8b1370b1c579364bb79a0813ca9bf9a15c65e7a974829886ab3e00f3441cedL310
This logic prevents a AAMVA cost from being added if an AAMVA exception occurs. Presumably this is because we are not billed for AAMVA exception which happen frequently. This commit applies that logic to the `ProgressiveProofer` where SP costs are now tracked.
=> Do not track SP costs in AAMVA exception case

lib/reporting/identity_verification_report.rb
When the identity verification report was built the fraud-review functionality did not apply to in-person pending. This was changed in #9928, but the report was not updated to filter fraud-pending users out of the successfully verified count for in-person events.
This commit modifies the cloudwatch query to filter those users who are not verified from being counted as successfully verified.
=> LG-13593 Update the cloudwatch query for identity verification report to filter fraud-pending in-person users

spec/services/identity_linker_spec.rb
I got a test [failure](https://gitlab.login.gov/lg/identity-idp/-/jobs/1253467) this morning due to a time-based flakiness:
```
Failures:
1) IdentityLinker#link_identity identity.verified_at the request is includes identity proofing and verified_at is not null does not set the timestamp
Failure/Error:
expect(
user.last_identity.verified_at,
).to be_within(1.second).of(1.week.ago)
expected 2024-06-05 00:46:12.000000000 +0200 to be within 1 of 2024-06-05 00:46:13.011929850 +0200
```
This PR freezes time for the test to make it more reliable
=> Fix flaky IdentityLinker test

config/locales/zh.yml, spec/i18n_spec.rb
Adds the smart quote pair to the recent punctuation check we added
=> Add quotes to punctuation check in i18n test

app/javascript/packages/document-capture/components/acuant-capture-canvas.jsx, app/javascript/packages/document-capture/higher-order/observable-property.tsx, spec/javascript/packages/document-capture/components/acuant-capture-canvas-spec.jsx, spec/javascript/packages/document-capture/higher-order/observable-property-spec.tsx
[LG-11285](https://cm-jira.usa.gov/browse/LG-11285)
The call to `defineObservableProperty` is happening twice, and since the object property in question (`canvas.callback`) is not configurable, we raise a TypeError on the second call.
This PR makes the property configurable, and resets the property in the cleanup call for the `useEffect` where it is used.
**Before applying this change:**
To reproduce the error using your phone configured for [mobile local development](https://github.com/18F/identity-idp/blob/main/docs/mobile.md), go through IdV until document capture, then note that when the Acuant SDK starts up, we see the error `Uncaught TypeError: Cannot redefine property: callback` in the browser console.
**On this branch:**
Again, go through IdV up until the Acuant SDK starts up for …
=> LG-11285: Reset the callback property descriptor on cleanup of useEffect.

app/controllers/concerns/idv/verify_info_concern.rb, app/controllers/idv/in_person/verify_info_controller.rb, app/controllers/idv/verify_info_controller.rb, spec/controllers/idv/in_person/verify_info_controller_spec.rb, spec/controllers/idv/verify_info_controller_spec.rb, spec/services/idv/agent_spec.rb
In #10728 we started passing the service provider ID to the resolution proofing job. Since the job has the user ID this allows us to compute UUID and UUID prefix in the job instead of having to pass them through the applicant. Once that commit is deployed we can stop passing the UUID and UUID prefix via the applicant.
This commit removes the code that looks up the UUID prefix and UUID and merges them into the applicant. This should not be merged until #10728 is fully deployed to production.
=> LG-13383 Stop passing UUID and UUID prefix to `Idv::Agent`

app/controllers/idv/address_controller.rb, app/forms/idv/address_form.rb
I found some code referencing `address_edited` on the `AddressForm` response. We removed that so there is not reason to inspect it.
This commit also does some touch-ups to the form and the controller to clean up the logic.
=> Remove dead code in the `Idv::AddressController`

.gitlab-ci.yml, Makefile
**Why**: This is prep work that enables running these checks on a schedule on main branch, instead of on feature branches
=> Move dependency audit checks into own task in Gitlab CI

db/schema.rb
#10759 included `db/schema.rb` changes that differed slightly from the result of running migrations.
=> Update db/schema.rb to match migrations

config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/zh.yml, spec/features/account_email_language_spec.rb, spec/i18n_spec.rb
Updating the language email preference is displayed in the language it is describing. This is similar practice in the language picker and should be consistent in both places.
Ref https://github.com/18F/identity-idp/pull/10291#discussion_r1579992009
=> Update email language preference to its associated language

Gemfile, Gemfile.lock, app/controllers/saml_idp_controller.rb, app/services/analytics_events.rb, spec/controllers/saml_idp_controller_spec.rb
https://gitlab.login.gov/lg-people/lg-people-appdev/Melba/backlog-fy24/-/issues/42
- Updates the version of saml_idp gem 
- Updates logging to include `cert_error_details` to log specific certificate errors if the request is signed and successful
- Adds tests
=> Add logging for certificate errors

.gitlab-ci.yml
Switches the kubectl context to instead use the new reviewapp cluster, and modifies the dns names to use the new zone for that cluster.
=> Cutover review-apps to new cluster

.gitlab-ci.yml
Adds the coverage percentage metric as described in https://docs.gitlab.com/ee/ci/testing/code_coverage.html#view-code-coverage-results-in-the-mr
<details>
</details>
<details>
</details>
=> Add coverage metric to GitLab CI

app/controllers/test/oidc_test_controller.rb
A quick update to change the SP used for the Test OIDC links from /test/oidc/login.
I found the existing SP failed with errors for me. This changes makes the links work again.
Note: the test routes are disabled in production envs (i.e., deployed envs)
Run your local server and go to /test/oidc/login and try the links.
=> A quick update to change the SP used for the Test OIDC links from /test/oidc/login.

app/jobs/risc_delivery_job.rb
https://gitlab.login.gov/lg-people/lg-people-appdev/Melba/backlog-fy24/-/issues/37
Don't bubble up the network errors. Let ActiveJob retry based on its configuration.
=> Remove RISC network errors from NewRelic

app/controllers/concerns/idv/verify_info_concern.rb, app/jobs/resolution_proofing_job.rb, app/services/idv/agent.rb, app/services/proofing/resolution/progressive_proofer.rb, spec/controllers/idv/in_person/verify_info_controller_spec.rb, spec/features/idv/doc_auth/verify_info_step_spec.rb, spec/jobs/resolution_proofing_job_spec.rb, spec/services/idv/agent_spec.rb, spec/services/proofing/resolution/progressive_proofer_spec.rb
Prior to this commit we have been passing `should_proof_state_id` from the `VerifyInfoConcern` down to the `ProgressiveProofer` through the async proofing tooling. This requires this argument to be passed down the call stack and stored as a background job argument.
The `should_proof_state_id` value is determined by configuration that is available to the IdP and the workers. It is not clear why it needs to be computed in the `VerifyInfoConcern` and passed down through the job to the `ProgressiveProofer`. This commit shortcuts everything by moving the logic closer to where the value is actually inspected.
=> Determine whether an AAMVA check is required in the progressive proofer

config/locales/zh.yml
We received part of the first round of Chinese LQA feedback. 
This PR covers the changes:
- Account creation: Typo in "PIV/CAC"
- Account Rules of Use: Delete an English content in the Chinese translation
- Account Expiration Modal: Revise the Chinese content
- Account dashboard: Revise the Chinese content
=> Chinese LQA: Round 01 - Rev 01

app/jobs/risc_delivery_job.rb, app/services/analytics_events.rb, app/services/push_notification/http_push.rb, config/application.yml.default, lib/identity_config.rb, spec/jobs/risc_delivery_job_spec.rb, spec/services/push_notification/http_push_spec.rb
=> Remove inline RISC job

app/views/accounts/show.html.erb, spec/views/accounts/show.html.erb_spec.rb
Updates account page email language preference to render `lang` attribute when showing content in a language other than the page's current language, following #10808 and to satisfy [WCAG SC 3.1.2 Language of Parts](https://www.w3.org/WAI/WCAG21/Understanding/language-of-parts).
Previously: https://github.com/18F/identity-idp/pull/10808#pullrequestreview-2130329877
2. Sign in
3. On account dashboard, change email language preference to a language other than English (or conversely, change the current page language to a language other than English)
4. Activate screen reader
5. Navigate to the text value for current email language preference
6. Observe that screen reader announces language value in that language
(You may need to unmute video player for audio to …
=> Render lang attribute for email language preference

app/components/alert_component.rb, app/views/idv/by_mail/request_letter/index.html.erb, app/views/idv/in_person/ready_to_verify/show.html.erb, app/views/shared/_sp_alert.html.erb, spec/components/alert_component_spec.rb, spec/components/previews/alert_component_preview.rb
Updates `AlertComponent` to replace the explicit `:other` variant to be used as the default, instead of `:info`.
For additional context, refer to https://github.com/18F/identity-design-system/pull/449
Stylistically, there is visual difference in the previous `type: :other` compared with the new default appearance, since we never actually applied the `usa-alert--other` class. This works to our benefit, since there's effectively no change as a result of the upcoming design system release, and no logic changes needed to remove the application of a `usa-alert--other` class.
As part of these changes, I searched code for existing usage of `AlertComponent` not specifying `type` with the assumption of rendering an `:info` alert banner and passed an explicit `type: :info` to avoid regressions. …
=> Replace Alert component "other" as default style

app/controllers/users/webauthn_setup_controller.rb, app/forms/webauthn_setup_form.rb, spec/controllers/users/webauthn_setup_controller_spec.rb, spec/forms/webauthn_setup_form_spec.rb
Refactors `WebauthnSetupForm` to validate parameters in a standardized manner:
- `submit` accepts a single hash of parameters
- Use `ActiveModel::Model` validation methods (`validates`, etc.) to add errors
- Success is based on `ActiveModel::Model#valid?` alone
This originally started with a desire to replace the ad hoc [`webauthn_setup_submitted`](https://github.com/18F/identity-idp/blob/99bad4f9a546ab1728a74a715304d5a2ff40424e/app/services/analytics_events.rb#L5694-L5706) with `multi_factor_auth_setup`, which then led to the realization that setups can happen through multiple pathways and forms ([`WebauthnSetupForm`](https://github.com/18F/identity-idp/blob/main/app/forms/webauthn_setup_form.rb) and [`WebauthnVisitForm`](https://github.com/18F/identity-idp/blob/main/app/forms/webauthn_vi …
=> Standardize form validation for WebauthnSetupForm

app/jobs/reports/drop_off_report.rb, lib/identity_config.rb, spec/jobs/reports/drop_off_report_spec.rb
[LG-13570](https://cm-jira.usa.gov/browse/LG-13570)
We were seeing the error: `no implicit conversion of Array into String` on the dropoff report.
This was because we're implicitly converting our configs to their described `type` in `identity_config.rb`, and then trying to parse that JSON with `JSON.parse` in `drop_off_report.rb`. 
This PR comments our code and removes the offending `parse`.
Thanks to @h-m-m and @nprimak for working on this bug.
=> LG-13570 we were parsing JSON as JSON and that was bad

.gitattributes
In #10518 we added `.gitattributes`
However, treating `yarn.lock` as a binary file has challenged my local workflow, so I can't add files incrementally with `git add --patch` (`git add -p`), they get skipped
This came up when I was working on https://github.com/18F/identity-idp/pull/10854
```bash
> git status
...
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   yarn.lock
> git add -p
Only binary files changed.
```
(I can update `yarn.lock` via `git add -p`)
=> Update list of diffable files

app/javascript/packages/build-sass/CHANGELOG.md, app/javascript/packages/build-sass/cli.js, yarn.lock
- yarn upgrade jsdom
- yarn upgrade webpack-dev-server
See: https://github.com/18F/identity-idp/security/dependabot/77
=> Update JS dependencies to fix vulnerable "ws" dependency

app/jobs/reports/drop_off_report.rb, lib/identity_config.rb, spec/jobs/reports/drop_off_report_spec.rb
- Reports: Resolve double-parsing JSON in Dropoff report (LG-13570) ([#10846](https://github.com/18F/identity-idp/pull/10846))
=> Deploy RC 391.1 to Production

app/controllers/idv/by_mail/request_letter_controller.rb, app/controllers/idv/enter_password_controller.rb, app/services/idv/gpo_mail.rb
Indirectly related to 13421
In my main story I'm adding a GpoVerifyByMailPolicy class. We want to eventually fold the GpoMail class into it.
As part of that, we noticed that `phone_step_attempts` in particular was sort of out of place in a class called GpoMail.
Because these are both small and simple, I just moved `hours_since_first_letter` into the two classes using it, and inlined what was formerly `phone_step_attempts`. It's ultimately a little less code.
=> Un-DRY GpoMail class a tad bit

app/models/user.rb, app/services/idv/gpo_mail.rb
Adjacent to 13421
Trying to shrink GpoMail, I wondered if `number_of_letter_requests_within` maybe better belonged on the GpoConfirmationCode model. @jmhooper and I got to looking at it and realized that adding a relation on User through Profile would let us simplify this a bit.
Also moved the `attr_reader` line up top due to deeply-held religious beliefs.
=> Simplify queries with a GpoConfirmationCode relationship

app/services/idv/agent.rb
We deprecated this argument in #10796. This commit stops invoking the job with the argument. A future commit should remove the argument from the job.
=> Remove the `should_proof_state_id` argument from the `Idv::Agent` call to the `ResolutionProofingJob`

app/controllers/idv/by_mail/resend_letter_controller.rb, app/services/analytics_events.rb, app/views/idv/by_mail/resend_letter/new.html.erb, config/routes.rb, spec/controllers/idv/by_mail/resend_letter_controller_spec.rb
This commit begins the process of splitting the `Idv::ByMail::RequestLetter` controller into 2 separate controllers:
1. A controller for requesting a letter in the IdV workflow
2. A controller for requesting a new letter after the IdV workflow from the enter-code step
This change is being made because the current `Idv::ByMail::RequestLetter` controller is built like an IdV-Step controller but has some hacks to enable it to be visited outside the IdV flow to support resends. These exceptions lead to a number of inconsistencies that risk becoming bugs as we make changes to the GPO flow.
This commit makes the first part of the change: Adding the new controller and setting up routes for it. A future change will start directing traffic to the new routes and a further change will remove the old …
=> Add a `Idv::ByMail::ResendLetterController` and associated routes

lib/reporting/fraud_metrics_lg99_report.rb, spec/lib/reporting/cloudwatch_client_spec.rb, spec/lib/reporting/fraud_metrics_lg99_report_spec.rb, spec/rails_helper.rb, spec/support/aws_cloudwatch_helper.rb
Background: https://github.com/18F/identity-idp/pull/10848 introduced a new runtime error when a query was misconfigured
This error triggered in int for the LG99 report: https://onenr.io/02R506rLmwb
This PR updates the stubbing to be more realistic so that the error shows up and can be handled, moves a helper to be shared more easily
=> Fix LG99 report Cloudwatch Error

app/jobs/reports/combined_invoice_supplement_report_v2.rb, app/services/db/monthly_sp_auth_count/total_monthly_auth_counts_within_iaa_window.rb, app/services/db/monthly_sp_auth_count/unique_monthly_auth_counts_by_iaa.rb, spec/jobs/reports/combined_invoice_supplement_report_v2_spec.rb, spec/services/db/monthly_sp_auth_count/total_monthly_auth_counts_within_iaa_window_spec.rb, spec/services/db/monthly_sp_auth_count/unique_monthly_auth_counts_by_iaa_spec.rb
[LG-13703](https://cm-jira.usa.gov/browse/LG-13703)
Updates calculations of unique users in CombinedInvoiceSupplementReportV2 to match finops team needs. Full description of logic changes is in the [FY24 Billing Report Explainer](https://docs.google.com/document/d/171lf1rSH1w1aSKVIejjb4z-ebtmdJxgyBVdpKp98GBM/edit) document
- remove iaa_ial1_plus_2_unique_users
- remove issuer_ial1_plus_2_unique_users
- add iaa_unique_users
- add issuer_unique_users
=> Billing Report Updates for Unique User Calculations (LG-13703)

lib/tasks/backfill_sponsor_id.rake, spec/factories/in_person_enrollments.rb, spec/lib/tasks/backfill_sponsor_id_rake_spec.rb
[LG-13578: Set Sponsor ID on existing enrollments in the database](https://cm-jira.usa.gov/browse/LG-13578)
- Write a rake task that will set the sponsor id on existing in_person_enrollments in the database that have a nil sponsor_id
- Use the sponsor id associated with IPP for all existing enrollments
=> LG-13578: Backfill sponsor id for in_person_enrollments

app/models/user.rb, spec/features/new_device_tracking_spec.rb, spec/models/user_spec.rb, spec/support/features/session_helper.rb
[LG-13739](https://cm-jira.usa.gov/browse/LG-13739)
Updates logic of `User#authenticated_device?` to consider the device authenticated if it was the one that had created the account. This fixes an issue where the new-device email would be unexpectedly sent the first time the user signs in after creating an account, even if that was the device they'd used to create the account.
The issue stems from the fact that we previously relied on `:sign_in_after_2fa` event existing for the device, but this event is only created if a user authenticates with 2FA, which doesn't happen during the account creation process.
1. In a private browsing window, go to http://localhost:3000
3. Once you reach the account dashboard, sign out
4. Sign in to that new account
Before: You'd receive …
=> LG-13739: Avoid sending new device email after account creation

app/services/vot/parser.rb, app/services/vot/supported_component_values.rb, spec/policies/service_provider_mfa_policy_spec.rb, spec/services/analytics_spec.rb, spec/services/vot/parser_spec.rb
When a service provider requests a biometric comparison we want to make this user proof through a process that requires 2 pieces of fair evidence. This commit starts the work for that by adding a requirement to the `Pb` component. Whenever the biometric request is made this requirement will be present on the `resolved_authn_context_result`. We can use this requirement to determine if the verify-by-mail flow is available to the user.
=> LG-13420 Add the `two_pieces_of_fair_evidence` requirement

app/views/idv/by_mail/enter_code/_did_not_receive_letter.html.erb, app/views/idv/by_mail/enter_code/_enter_code.html.erb, spec/features/idv/steps/request_letter_step_spec.rb, spec/features/saml/ial2_sso_spec.rb, spec/views/idv/by_mail/enter_code/index.html.erb_spec.rb
The `ResendLetterController` was introduced in #10864. It was not used to support the 50/50 state when old instances will not have the route and would 404 if users were linked there.
Once the changes in #10864 are fully merged this change can be merged to start linking users to the new `ResendLetterController`. From there the functionality to support resends can be removed from the `RequestLetterController`.
=> Begin using the new `ResendLetterController`

spec/views/accounts/show.html.erb_spec.rb
Fixes specs for the account page view to ensure that the view is consistently rendered when asserting expected behavior.
Because it's easy to assert that something doesn't render a particular template when you don't render anything at all, but it's not particularly useful 😉 Another case of `to_not` giving us a false sense of confidence.
Discovered via #10847
```
rspec spec/views/accounts/show.html.erb_spec.rb
```
=> Render negated test cases in account specs

app/controllers/idv/in_person/ready_to_verify_controller.rb, spec/controllers/idv/in_person/ready_to_verify_controller_spec.rb
Fixes a 500 from [New Relic](https://onenr.io/0ERzPNMgAQr) where `current_user` is nil in the `handle_fraud` methods further up the stack by moving the `confirm_two_factor_authenticated` check to be first.
=> Fix 500 in document capture when going to IPP

app/services/access_token_verifier.rb, spec/requests/openid_connect_userinfo_spec.rb
This PR fixes a 500 where we have a nil `identity` returned from the `AccessTokenVerifier`. There are two potential errors in validating the access token currently. The first is if the value doesn't start with `"Bearer"`, and the second is if we don't load an identity for the token. The value `"Bearer"` passes the first one, but we don't attempt to load the identity when `access_token` is nil, which means we also don't attempt to load the identity or add the error.
This PR adds an error if we get a blank `access_token`.
=> Fix 500 on blank Bearer Token in AccessTokenVerifier

app/forms/recaptcha_form.rb, spec/forms/recaptcha_enterprise_form_spec.rb
[LG-13336](https://cm-jira.usa.gov/browse/LG-13336)
This adds LOW_CONFIDENCE_SCORE as a type of reason we will currently ignore and allow users to continue. 
1.  Mimic recaptcha logging and return a LOW_CONFIDENCE_SCORE reason
2. Should not be blocked from continuing on.
=> LG-13336: Low confidence Score Exemption

app/controllers/openid_connect/logout_controller.rb, app/controllers/users/delete_controller.rb, spec/controllers/users/delete_controller_spec.rb, spec/controllers/users/piv_cac_login_controller_spec.rb, spec/support/analytics_helper.rb, spec/support/controller_helper.rb
[LG-13318](https://cm-jira.usa.gov/browse/LG-13318)
Fixes analytics logging for account deletion event to ensure that the user ID is logged correctly
Verify you see `user_id` in logged events after deleting an account:
1. Run `make watch_events` in a separate terminal process
3. Sign in to an account you don't mind deleting, or create a new account
4. Click "Delete account" in account dashboard sidebar
5. Confirm account deletion
6. In terminal process for `make watch_events`, observe `"Account Delete submitted"` event includes a non-`nil` `properties.user_id`
Spec updates should provide regression assurance:
```
rspec spec/controllers/users/delete_controller_spec.rb
```
=> LG-13318: Ensure user_id present in account deletion submitted event

app/services/gpo_confirmation_uploader.rb, spec/services/gpo_confirmation_uploader_spec.rb
We have observed a number of SSH errors when attempting to upload the GPO file. When those have occurred re-running the GPO job has resulted in a successful upload. This commit attempts to automate that by adding retry logic to confirmation uploader.
This change is limited to the SSH connection and upload. This is to tread carefully around the job's logic. It deletes the records it uploads so we need to tread lightly when performing retries.
=> LG-13775 Retry GPO confirmation upload when SSH errors occur

.gitlab-ci.yml
**Why**: These checks look for external changes (vulnerabilities reported, documentation out of date), so failing branch builds on them causes noisy issues for everybody.
They are now scheduled on main so they can be fixed for everybody
=> Remove scheduled CI checks from main

.eslintrc, app/javascript/packages/session/requests.spec.ts, app/javascript/packages/session/requests.ts, app/javascript/packs/document-capture.tsx, app/javascript/packs/session-timeout-ping.ts, app/views/idv/shared/_document_capture.html.erb, app/views/session_timeout/_ping.html.erb
Builds on work from @aduth and learnings from #10882 where hardcoded strings for URLs resulted in untranslated requests from JavaScript. This lint raises errors on `new URL(string)` to help mitigate against similar issues in the future.
`address_search_url` is not used currently due to current configurations, the functionality for `"/api/addresses"` was removed in https://github.com/18F/identity-idp/pull/9154. The replacement with an empty string is intended to serve as a placeholder while discussion on whether to remove the frontend components of the address search happens [here](https://gsa-tts.slack.com/archives/C04GA9WQ85B/p1719844684712719).
=> Add lint hardcoded URLs in JavaScript

app/controllers/concerns/idv/verify_by_mail_concern.rb, app/controllers/idv/by_mail/enter_code_controller.rb, app/forms/gpo_verify_form.rb, app/policies/idv/gpo_verify_by_mail_policy.rb, config/application.yml.default, lib/identity_config.rb, spec/controllers/idv/by_mail/enter_code_controller_spec.rb, spec/forms/gpo_verify_form_spec.rb, spec/policies/idv/gpo_verify_by_mail_policy_spec.rb, spec/services/gpo_reminder_sender_spec.rb, spec/views/idv/by_mail/enter_code/index.html.erb_spec.rb
In #10871 we added a requirement that 2 pieces of fair evidence are required during verification. This is active whenever a SP requests biometric comparison. This commit adds enforcement of that requirement. It uses the `GpoVerifyForm` added in #10844 to disallow sends when that requirement is in place.
=> Don't allow letter sends when 2 pieces of fair evidence are required

app/assets/stylesheets/email.css.scss, app/javascript/packages/stylelint-config/CHANGELOG.md, app/javascript/packages/stylelint-config/index.js
Updates `@18f/identity-stylelint-config` shared Stylelint configuration to enable the [`declaration-no-important`](https://stylelint.io/user-guide/rules/declaration-no-important/) rule.
Related changelog entry, from proposed code:
> ### Breaking Changes
>[...]
>- The [`declaration-no-important`](https://stylelint.io/user-guide/rules/declaration-no-important/) rule is now enabled, which disallows `!important` in stylesheets.
>   - `!important` is a sledgehammer solution which often causes more problems than it helps, and usually stems from misunderstandings of [CSS specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity). See related ["Best practices" MDN documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/important#best_practices).
As part of this, the …
=> Update Stylelint configuration to forbid CSS !important

app/controllers/concerns/idv_step_concern.rb, app/controllers/concerns/verify_profile_concern.rb, app/controllers/idv/personal_key_controller.rb, spec/controllers/concerns/idv_step_concern_spec.rb, spec/controllers/idv/personal_key_controller_spec.rb, spec/features/idv/verify_by_mail_pending_spec.rb
The `PendingProfileConcern` uses the `PendingProfilePolicy` to check if a user has a pending profile and needs to be redirected to finish proofing. We have code in the `IdvStepConcern` that does the same, but does not factor all of the things that go into that function, such as whether the SP requested a biometric comparison and the pending profile had a biometric comparison.
This commit uses the `PendingProfileConcern` in the `IdvStepConcern` to ensure the pending profile logic is consistent.
=> LG-13692 Use `PendingProfileConcern` to check for pending profiles during IdV

app/controllers/concerns/idv_session_concern.rb, spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb
[LG-13624](https://cm-jira.usa.gov/browse/LG-13624)
Fixed `IdvSessionConcern` to use `idv_session_user` rather than `current_usr` and added a test for this bug.
=> LG-13624 document capture with selfie crashes on cancel

app/policies/idv/gpo_verify_by_mail_policy.rb, spec/features/idv/end_to_end_idv_spec.rb, spec/features/idv/in_person_spec.rb, spec/policies/idv/gpo_verify_by_mail_policy_spec.rb
[LG-13423](https://cm-jira.usa.gov/browse/LG-13423)
Update `GpoVerifyByMailPolicy` to disallow requesting GPO letters if the user has opted for in-person proofing.
- Set `no_verify_by_mail_for_biometric_comparison_enabled` to true
- Go through Idv w/ IPP
- Ensure you're not offered the chance to verify your address by mail
- Set `no_verify_by_mail_for_biometric_comparison_enabled` to false
- Go through Idv w/ IPP
- Ensure you *are* offered the chance to verify your address by mail
=> LG-13423: Don't allow letter sends when an IPP enrollment is in progress

app/controllers/two_factor_authentication/piv_cac_verification_controller.rb, app/services/analytics_events.rb, spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb
[LG-13311](https://cm-jira.usa.gov/browse/LG-13311)
Updates PIV/CAC verification controller to avoid logging `multi_factor_auth_enter_piv_cac` when the user visits the screen before being redirected to the PIV/CAC service.
The intent of this change is to avoid double-logging `multi_factor_auth_enter_piv_cac` for each PIV/CAC verification, and instead logging it once when the user visits, and relying on the existing "Multi-Factor Authentication" event to be logged when the user returns from the PKI service.
The `#show` action is used for both the initial visit as well as the return target from the PKI service. The changes here conditionally log the event only when the user is not being returned from the PKI service (when the token parameter is absent).
Prerequisite: Have an account with …
=> LG-13311: Avoid logging multi_factor_auth_enter_piv_cac twice for PIV MFA

app/services/uri_service.rb, spec/services/uri_service_spec.rb
Little Friday cleanup
- Main change: Make `params_to_add` required instead of optional, it's always provided anyways
- Bonus: Add YARD documentation for method
=> Clean up UriService

app/views/users/service_provider_inactive/index.html.erb, spec/views/users/service_provider_inactive/index.html.erb_spec.rb
[LG-13585](https://cm-jira.usa.gov/browse/LG-13585)
Updates the inactive service provider error page to ensure that it renders with an H1.
- https://dequeuniversity.com/rules/axe/4.9/page-has-heading-one
- https://www.w3.org/WAI/tutorials/page-structure/headings/
- https://www.w3.org/WAI/WCAG21/Understanding/headings-and-labels.html
It may be simpler to review with whitespace changes hidden: https://github.com/18F/identity-idp/pull/10921/files?w=1
1. Go to http://localhost:3000/errors/service_provider_inactive
2. Inspect heading
3. Verify markup includes `<h1>` element
Alternatively, run an accessibility checker to verify no headings-related errors.
&nbsp;|Before|After
---|---|---
With SP|![image](https://github.com/18F/identity-idp/assets/1779930/b45ea1dc-9e68-4acc-925d …
=> LG-13585: Render H1 for inactive service provider error page

app/forms/idv/state_id_form.rb, spec/controllers/idv/in_person/state_id_controller_spec.rb, spec/features/idv/analytics_spec.rb, spec/forms/idv/state_id_form_spec.rb, spec/services/idv/steps/in_person/state_id_step_spec.rb
[LG-13487](https://cm-jira.usa.gov/browse/LG-13487)
- Add `birth_year` property to the event_properties for the `IdV: in person proofing state_id submitted` event log when submitting state id form data in the idv state id form step.
- Update both Flow State Machine `state_id_step` code and the `state_id_controller`.
Scenario: Verify birth_year is logged after state_id form submission. (Flow State Machine)
Scenario: Verify birth_year is logged after state_id form re-submission. (Flow State Machine)
---
Before Execution: 
Scenario: Verify birth_year is logged after state_id form submission. 
Scenario: Verify birth_year is logged after state_id form re-submission.
=> LG-13487: Add birth year to state id submitted event

app/jobs/reports/drop_off_report.rb, config/application.yml.default, lib/reporting/drop_off_report.rb, spec/jobs/reports/drop_off_report_spec.rb
[LG-13722](https://cm-jira.usa.gov/browse/LG-13722)
We didn't have test coverage that made sure to exercise the boundary between `Reporting::DropOffReport` and `Reports::DropOffReport`. There were some mismatches in expectations. Now we have tests that exercise and changes that make those tests pass by updating those two classes to be more lenient in the arguments they accept
=> Ensure the drop-off report and its tests are more robust

app/forms/idv/in_person/address_form.rb, app/forms/idv/state_id_form.rb, spec/controllers/idv/in_person/address_controller_spec.rb, spec/controllers/idv/in_person/state_id_controller_spec.rb, spec/features/idv/analytics_spec.rb, spec/forms/idv/state_id_form_spec.rb, spec/services/idv/steps/in_person/state_id_step_spec.rb
[LG-13512](https://cm-jira.usa.gov/browse/LG-13512)
Note: These changes are closely related to LG-13487 and are based on those initial changes. See https://github.com/18F/identity-idp/pull/10899
- Added `document_zip_code` property to the event_properties for the "IdV: in person proofing state_id submitted" event log when submitting state id form data in the idv state id form step.
- Updated both Flow State Machine state_id_step code and the state_id_controller.
- Added `current_address_zip_code` property to the event_properties for the "IdV: in person proofing residential address submitted" event log when submitting current address data in the idv "current address" form step.
- Only address_controller needed updating since this form does not use a Flow State …
=> LG-13512 Add zipcode to ipp analytics logging

lib/action_account.rb, spec/lib/action_account_spec.rb
[LG-13848](https://cm-jira.usa.gov/browse/LG-13848)
When a user is reinstated, for some reason the Cloudwatch log doesn't always show up. (This should be investigated separately!)
If the (employee) user tries to reinstate a user who has already been reinstated, let's give a clearer error message.
I have included a timestamp because that was helpful to Rebecca in digging into this yesterday, so let's just include that.
=> LG-13848 | ActionAccount reinstated message
